### ISSUE TITLE
Natural language queries (Q&A)

### ISSUE THREAD

**Issue by dlopez831** [MicrosoftDocs/powerbi-docs#1001]
According to this article Natural language queries (Q&A) capability is available both in dashborard and reports. If so, then it should not be in the table because it is not a difference. If not, then it should be fixed.
According to this earlier article https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reports it is not available in reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [Intro to dashboards for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboards#feedback)
* Content Source: [powerbi-docs/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiemsft
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @dlopez831 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @dlopez831 -- so true! Article is fixed.
