### ISSUE TITLE
PDF connector no longer preview-only

### ISSUE THREAD

**Issue by danpere** [MicrosoftDocs/powerbi-docs#1003]
As announced here ( https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-april-2019-feature-summary/#pdf ), as of the April 2019 release, the PDF connector is now a generally available feature, so enabling it is no longer necessary and the "(beta)" tag is no longer part of the connector name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ab70d2-6a8d-9457-9fe0-b7e5a11f7a23
* Version Independent ID: 8d847641-59f8-8914-799d-0c1c7ccad9a6
* Content: [Connect to a PDF file in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-pdf#feedback)
* Content Source: [powerbi-docs/desktop-connect-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for catching that issue, @danpere ! This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Fixed - thanks! Update will show online within 24 hours.

**Comment by debbiefox** [comment]
When will this be available for PowerQuery in Excel and not just Desktop?
