### ISSUE TITLE
PBI Embedded doesn't support Paginated Reports

### ISSUE THREAD

**Issue by stevejmorgan** [MicrosoftDocs/powerbi-docs#1004]
This page refers to the PBI Embedded "A" SKUs but paginated reports aren't supported in Embedded as per internal Teams discussion with PBICAT team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09cf6129-9d7f-0e47-75f3-89f5df01c5e9
* Version Independent ID: a1d90b2d-0e8b-da1f-fa30-a3294a98dc25
* Content: [Paginated reports in Power BI: FAQ (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-faq)
* Content Source: [powerbi-docs/paginated-reports-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-faq.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @stevejmorgan. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi @stevejmorgan -- thanks for your question! 
The article says you can use “paginated reports on P1 – P3 SKUs for public preview. You may also use it for test/dev scenarios with A4 – A6 SKUs,” and it says you can’t use PBI embedded at all. So I'm not sure what you're asking.
Thanks!

**Comment by stevejmorgan** [comment]
Hi Maggie 
My understanding that the A SKUs are PowerBI Embedded but I've been told by the PBICAT team that paginated reports can't be used with any flavour of Embedded.
Steve
