### ISSUE TITLE
Changing gateway parameter isanchorgateway through powershell module?

### ISSUE THREAD

**Issue by sgoley** [MicrosoftDocs/powerbi-docs#1005]
Is there any possibility of adding a parameter to the Set-OnPremisesDataGateway module that can change the "Anchor Gateway" for that cluster?

Example:

`Set-OnPremisesDataGateway -ClusterObjectId **example-clusterid**  -GatewayObjectId **example-gatewayid** -MemberStatus Enabled -isAnchorGateway True`

Granted, this might be an extremely rare use case but it would prevent me from having to go through the lengthy process of removing all gateways, remove cluster, and then reinstall all gateways following installation of new cluster on new anchor machine. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a971ee3-1d8f-50bf-0a23-20bf592779bd
* Version Independent ID: b69b3560-08fd-6c9e-4bb3-4dfa3838d223
* Content: [High availability clusters for On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-high-availability-clusters)
* Content Source: [powerbi-docs/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-high-availability-clusters.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @sgoley. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
