### ISSUE TITLE
Re-publish with a refresh schedule triggers an immediate cloud refresh

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1006]
From my observation (and confirmed by threads in the community forums), when you re-publish and you have a refresh schedule defined, the web service starts a cloud refresh immediately after you publish. This should probably be optional or explicit in the Publish UI, but can you start by documenting it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- thanks for your observation. I've assigned this to the author.

**Comment by davidiseminger** [comment]
Thanks for posting - I've added a note, which will update in the article within 24 hours.
