### ISSUE TITLE
github issue

### ISSUE THREAD

**Issue by LordUber** [MicrosoftDocs/powerbi-docs#1007]
I am using a fully updated Windows 7 installation. When I "get data" for github in Power BI , I am asked to sign in. I then get to the "authorise github for power bi" page but I can't click the authorise button. At the top of the pop-up box I have a message, "Github no longer supports Internet Explorer." Can I get this page to pop-up in Chrome rather than IE? My default browser is Chrome. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github#feedback)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @LordUber --sorry to hear you're having this issue. Can you explain your issue at the support site, https://powerbi.microsoft.com/en-us/support/? I hope that helps.
