### ISSUE TITLE
Incorrect Authorize Uri

### ISSUE THREAD

**Issue by johnnycardy** [MicrosoftDocs/powerbi-docs#1008]
`https://login.microsoftonline.net/common` should be `https://login.microsoftonline.com/common` I believe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#feedback)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @johnnycardy -- thanks for pointing that out. I've assigned this to the author.

**Comment by markingmyname** [comment]
@johnnycardy,

Thanks for the feedback, I updated the authority URI in the code block to show ".com" instead of ".net."

I also updated article - https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token- with this info as well.

Changes should show live by the end of the week.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
