### ISSUE TITLE
AuthorityUri is incorrect

### ISSUE THREAD

**Issue by bretf-ik** [MicrosoftDocs/powerbi-docs#1009]
The AuthorityUri shown in the various code snippets incorrectly points to login.microsoftonline.net when it should be .com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ccad8d-7403-3c43-4393-b4c5070bee56
* Version Independent ID: b12911fe-8b9b-8f77-491e-fc628b458ebe
* Content: [Create a dataset - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-create-dataset#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-create-dataset.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-create-dataset.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @bretf-ik -- thanks for pointing this out. I've assigned this to the author.

**Comment by markingmyname** [comment]
@bretf-ik,

Thanks for the feedback, I updated the authority URI in the code block to show ".com" instead of ".net."

I also updated all the automation walkthrough articles with the same block of code for the authorityuri.

Changes should show live by the end of the week.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
