### ISSUE TITLE
Outdated pictures

### ISSUE THREAD

**Issue by Oddjobe** [MicrosoftDocs/powerbi-docs#1011]
The pictures under "Finding Parameter Values" needs an update/new screenshot to reflect current look and feel!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a51592-74c3-54c1-1c57-fc102648cb2f
* Version Independent ID: efac35dc-4ea4-483c-7b63-412abeaf053c
* Content: [Azure SQL Database with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-sql-database-with-direct-connect#finding-parameter-values)
* Content Source: [powerbi-docs/service-azure-sql-database-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-sql-database-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @Oddjobe -- thanks for your observation! I've assigned this to the author.

**Comment by mgblythe** [comment]
Updated in June for freshness, thanks @Oddjobe.
