### ISSUE TITLE
Very useful page

### ISSUE THREAD

**Issue by duncanwil** [MicrosoftDocs/powerbi-docs#1013]
Sorting in Excel and PBI can be problematic and this page has given me the perfect solution for small data set I am analysing.

Thanks for creating this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7502a07a-7f30-882d-7542-2a194651c421
* Version Independent ID: e3c6e2fd-b672-6858-864c-69026d36c0ae
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-and-binning#feedback)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @duncanwil -- so glad to hear it! I've assigned this to the author, and I'm closing it. Thanks for letting us know!
