### ISSUE TITLE
How long is the cache persisted before invalidating/refreshing

### ISSUE THREAD

**Issue by atomek1000** [MicrosoftDocs/powerbi-docs#1014]
How long is the cache persisted before invalidating/refreshing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @atomek1000 -- got an answer for you: "it is just persisted until the next time the dataset is refreshed."

**Comment by atomek1000** [comment]
What about direct query?

**Comment by Bhavik-MSFT** [comment]
For DirectQuery its determined by your cache refresh frequency setting. Please have a look at the settings in this section of the refresh documentation: https://docs.microsoft.com/en-us/power-bi/refresh-data#databases-in-the-cloud. Bear in mind if the user hits the Refresh button in Power BI we will always fetch the latest data and repopulate the cache
