### ISSUE TITLE
Please clarify the scope of using Azure Consumption Insights connector and the Azure Cost Management connector

### ISSUE THREAD

**Issue by shalosi** [MicrosoftDocs/powerbi-docs#1015]
Hello team,

Please add the note that if the EA customer is trying to use the Azure Cost Management connector and they don't see the 'Billing Profile ID' in their Cost Management Blade, they are not in the Modern Commerce Platform, so they have to use the Azure Consumption Insights connector instead and it won't ask the 'Billing Profile ID' only the EA enrollment number. That is the issue that the customer has in the comment below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure cost and usage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#connect-with-azure-cost-management)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @shalosi -- thanks for your suggestion! I've assigned this to the author.

**Comment by davidiseminger** [comment]
Added a note to this effect. The article will update within 24 hours.
