### ISSUE TITLE
VirtualEnv / Dependencies 

### ISSUE THREAD

**Issue by jasonwbaxter1990** [MicrosoftDocs/powerbi-docs#1016]
Hi , So i'm looking at testing this out , and i have a few questions around how to manage python dependencies etc.

So currently i use VirtualEnv  to separate out dependencies between projects , I don't however see PowerBi options to connect or activate virtualenv , but i also may have multiple python projects with different versions etc .

Should i combine my projects and try resolve the dependencies if i wish to have multiple python scripts showing different visuals ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce2833fb-c5eb-3c0a-313d-3865ef9a1bfb
* Version Independent ID: cd8168fa-f253-be5e-4b8e-0d9ae185fa40
* Content: [Use an external Python IDE with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-ide#feedback)
* Content Source: [powerbi-docs/desktop-python-ide.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-ide.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jasonwbaxter1990 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
