### ISSUE TITLE
Multi-Geo

### ISSUE THREAD

**Issue by dethompson97** [MicrosoftDocs/powerbi-docs#1017]
For the views and rankings in a multi-geo setting, is this calculated for all tenants (ex. Europe, East US and Asia) or for each individual tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor usage metrics for dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/service-usage-metrics#feedback)
* Content Source: [powerbi-docs/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @dethompson97 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

You might also find your answer from the community (https://community.powerbi.com)

**Comment by maggiesMSFT** [comment]
Hi, @dethompson97 -- I got an answer for you: "I assume by tenants they mean capacities in this question.
If so then the answer is that usage is across the tenant, regardless where the capacities are."
