### ISSUE TITLE
Dynamic RLS when Power BI report is embedded 

### ISSUE THREAD

**Issue by ekozelek** [MicrosoftDocs/powerbi-docs#1018]
I'd like to know if I could setup RLS on the Analysis Services & then embed that report in our web application. The identifier would be passed from our app to the report. 

Currently, we use RLS on Power BI using an import connection. Our app passes the identifier to the report & users only see what they should. The issue is that import is a difficult model to maintain when you're working with a lot of data.

**Comment by maggiesMSFT** [comment]
Hi, @ekozelek -- thanks for your question! Are you referring to a particular article? 
I recommend asking the community, https://community.powerbi.com/. Hope that helps!
