### ISSUE TITLE
pbiviz --install-cert crashes powershell

### ISSUE THREAD

**Issue by williamdlupo** [MicrosoftDocs/powerbi-docs#1019]
pbiviz --install-cert outputs error:

This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ start C:\Users\...\AppData\Roaming\npm\node_modules\powerbi-vis ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI Custom Visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#prerequisites)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by maggiesMSFT** [comment]
Hi, @williamdlupo, I've assigned your question to the author. In the meantime I recommend asking the Power BI community, https://community.powerbi.com/.

**Comment by israelifalcon** [comment]
i had the same problem fix by typing .\pbiviz --install-cert

**Comment by israelifalcon** [comment]
or you can add C:\Users...\AppData\Roaming\npm\node_modules\powerbi-vis ... to your PATH

**Comment by zBritva** [comment]
@williamdlupo hello, could you tell the version of powershell on your system?

**Comment by KesemSharabi** [comment]
Hi @williamdlupo

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
