### ISSUE TITLE
Color Map Legend

### ISSUE THREAD

**Issue by goelkir** [MicrosoftDocs/powerbi-docs#1020]
How to show the colormap legend on the graph, so that user can get a visual clue regarding which color means what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting#feedback)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @goelkir . This issue has been assigned to the doc author for review. In the meantime, can you provide a little more detail on the issue you raised? Is there an example chart you can point us to?

**Comment by smferro54** [comment]
Hi! Any one of your charts, how else would the user know what the colors mean?

**Comment by glokan1** [comment]
Hi,

I don't see an option to do any of this in a bar chart in BI,I could do it for a table(Conditional formation) but it doesnt display for bar charts.
