### ISSUE TITLE
powerbi alerts

### ISSUE THREAD

**Issue by vrod9429** [MicrosoftDocs/powerbi-docs#1021]
The suggestion does not work to create powerbi alerts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-set-data-alerts#feedback)
* Content Source: [powerbi-docs/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @vrod9429 -- are data alerts working for you now? If not, I suggest reading through the article again and make sure the situation meets all the criteria. If that doesn't resolve it, check the Power BI Community, https://community.powerbi.com/, to see if anyone else has experienced anything similar. Barring that, try the Support site, https://powerbi.microsoft.com/en-us/support/. 
Good luck!
