### ISSUE TITLE
.Net Core Master User Example

### ISSUE THREAD

**Issue by finnbr** [MicrosoftDocs/powerbi-docs#1022]
Hello,

I am trying to create a .Net Core 2.2 app owns data/master user example.  The problem I am running into is with this line:
var credential = new UserPasswordCredential(Username, Password);
This is apparently not supported in .Net Core but is supported in .Net Framework.

Can you please explain how to get a token for using app owns data/master user (authentication with username and password) in .Net Core 2.2?

Thank you and keep up the good work! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @finnbr. This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Thanks for your comment, @finnbr.  This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
