### ISSUE TITLE
Server Core not supported

### ISSUE THREAD

**Issue by AMSoftwareNL** [MicrosoftDocs/powerbi-docs#1023]
Please add to the requirements Server Core installations are not supported. Installation succeeds, but sign in the Azure fails as no IEFRAME.DLL is available on Server Core. 
Support for Server Core would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#feedback)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @AMSoftwareNL. We're reworking the gateway docs, and I'll add this to the backlog.

@arthiriyer as FYI

**Comment by mgblythe** [comment]
We now doc this here: https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install
