### ISSUE TITLE
Grant type support issue

### ISSUE THREAD

**Issue by Athimoolaganesh** [MicrosoftDocs/powerbi-docs#1024]
.Net ADAL does not support UserPassword credential grant type, AcquireTokenAsync does not have constructor to accept userpassword credential parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#feedback)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @Athimoolaganesh. This issue has been assigned to the doc manager for review.

In the meantime, can you provide some additional info - is the issue an error in the docs or a limitation of the API?

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @Athimoolaganesh,

Thanks for the information. We will review this article and amend it if needed.

In the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by dlmotter** [comment]
This issue has been reported multiple times, but MS just diverts to the (totally useless) PBI Community page. If you are like me and having this issue, you may have luck with https://www.c-sharpcorner.com/article/how-to-get-access-token-for-powerbi-embedding-in-net-core/

I did not write and have no affiliation with that site - it's just the solution that worked for me.
