### ISSUE TITLE
Token acquisition code out of date

### ISSUE THREAD

**Issue by stimms** [MicrosoftDocs/powerbi-docs#1025]
There are multiple other issues(#521, #200, #953) on this which have been closed without being resolved. But in .NET Core there is no way to authenticate with a user name and password using ADAL 3.0. The sample should be updated to show authenticating and acquiring a token without user name and password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @stimms. This issue has been assigned to the doc manager for review.

**Comment by markingmyname** [comment]
@stimms Thank you for catching this in this article.  This information was updated in another article - https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#troubleshoot.

However, I also updated the NuGet download link to be more current.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
