### ISSUE TITLE
This is just a sample - the CircleCard visual circlecard.pbiviz could not be used for different data set after packaging the visual

### ISSUE THREAD

**Issue by SimonSD43** [MicrosoftDocs/powerbi-docs#1026]
Thanks for the tutorial on CircleCard visual. However, the data 256396 is hard-coded and it could not be changed with different data set that I put in. How can I change the data input on the CircleCard visual?

Please help...
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f573b62f-4028-ce65-b5ae-a4115ee1bcd1
* Version Independent ID: 1cedde6a-9245-42da-c25e-83706f551c79
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by mgblythe** [comment]
Thanks for your comment, @SimonSD43. This issue has been assigned to the doc author for review.

**Comment by zBritva** [comment]
@SimonSD34, please review the step two on preview article:
https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#configuring-data-binding-1

The visual gets value from Power BI.

**Comment by uve** [comment]
#please-close @kfollis
