### ISSUE TITLE
Limitations section - contradiction

### ISSUE THREAD

**Issue by mjc543** [MicrosoftDocs/powerbi-docs#1027]
In the Limitations section, Clustered Column chart is mentioned twice; once in "full use of..." list and again for "trend line ... only option" - which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Using the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-analytics-pane#feedback)
* Content Source: [powerbi-docs/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @mjc543. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Sorry for the confusion - I've updated with a correction. The correction will show up within 24 hours.
