### ISSUE TITLE
Content Add Request

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#1028]
Please add a page that describes:
- the types of data sources that can be used in embedded scenarios
- whether or not imported and directquery sources can be used
- whether or not gateways can be used with embedded

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a447889-379d-3ded-9ab9-313c4f55a667
* Version Independent ID: 4f8e3f79-5025-919a-7282-8a63dda6bc8d
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @danmyhre. This issue has been assigned to the doc manager for review.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Thanks @danmyhre, currently we are not going to add documented support for this. To answer your questions:

- the types of data sources that can be used in embedded scenarios
   All data types with the exception of paginated reports

- whether or not imported and directquery sources can be used
   Yes, directquery sources can be used

- whether or not gateways can be used with embedded
   Yes, gateways can be used with embedded
