### ISSUE TITLE
Missing info on assigning Power BI Pro licenses to Guest users

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1029]
The info above in the section "Assign licenses in Office 365" does not work for Guest users. The "Product Licenses" information is (stupidly) hidden.  The task can be achieved by checking the box for the Guest user, then hitting the More button and choosing Edit Product Licenses.  

It's described in some detail in this answer:
https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/assign-a-pro-license-to-a-guest-user-in-o365-admin/f70b2a84-269d-43f4-8890-1d0e65c307a2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d7c8609-4a9a-2a7b-5533-fd9684ae5fc6
* Version Independent ID: c8bb1362-f519-e0f7-a85d-d46dd06c1b15
* Content: [Purchase and assign Power BI Pro licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-purchasing-power-bi-pro#assign-licenses-in-office-365)
* Content Source: [powerbi-docs/service-admin-purchasing-power-bi-pro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-purchasing-power-bi-pro.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- thanks for your comment and link to the article. I've assign this to the author.

**Comment by mgblythe** [comment]
Sorry for the delay on this. I added similar info to the B2B and purchasing articles, with links out to the Office docs. The specific steps are different in the new admin UI.

Assigning a Power BI Pro license to a guest user within your tenant lets that guest user view content in the tenant. For more information about assigning licenses, see [Assign licenses to users on the Licenses page](https://docs.microsoft.com/office365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-users-on-the-licenses-page). Before assigning Pro licenses to guest users, contact your Microsoft account representative to ensure you're in compliance with the terms of your agreement with Microsoft.
