### ISSUE TITLE
AppWorks Space and Apps - Roapmap

### ISSUE THREAD

**Issue by shakanand** [MicrosoftDocs/powerbi-docs#103]
The below blog mentions that there are plans to improve the workspace and app experience.  Can you please share the link to roadmap blog that is referred below.  I would like to understand if we are going to have a Many to Many relationship between workspace and apps ?

You can create multiple content packs from any workspace, but an app has a 1:1 relationship with its workspace. We believe this makes apps easier to understand and maintain over the long run. **See the roadmap section of the Power BI blog** for more on how we plan to improve this area

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/19440916-create-multiple-apps-from-same-workspace

https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Create and publish apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @shakanand -- Thanks for your question! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @shakanand -- We've released a preview of the new workspaces. See if this article helps answer your question: https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces.
