### ISSUE TITLE
Does the connector for on-premise SAB-BW version 7.0 works with the PowerBI and On-premise data gateway?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1031]
Can anyone tell me if the connector for on-premise SAP-BW version 7.0 works with the PowerBI and On-Premise data gateway or do we need to upgrade the SAP-BW 7.0 to a higher version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP BW Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-bw-connector)
* Content Source: [powerbi-docs/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-bw-connector.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @anmolah . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by Anmolgan81** [comment]
I haven't got any response since I asked this question yesterday on powerbi community.

Regards
Anmol Ganju

________________________________

**Comment by davidiseminger** [comment]
Please feel free to post again to the community, or to the support page, if you haven't found your answer.
