### ISSUE TITLE
Missing steps under admin controls?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#1034]
Under "Admin controls for usage metrics - for Power BI administrators" this document shows "usage metrics for content creators".  But that is not there (or anywhere else I can find) in my admin controls.  Where else do I look for it?  Or, even better, how can I make these changes with powershell?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor usage metrics for dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/service-usage-metrics)
* Content Source: [powerbi-docs/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @jordanmills . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @jordanmills -- Thanks for your question! I've checked. You should see it where you see it in the screen shots in the article. If you're not seeing there, you may need to check with Power BI support, https://powerbi.microsoft.com/en-us/support/. 

Also, there are no public APIs or cmdlets to configure tenant settings yet. Check the Power BI ideas site, https://ideas.powerbi.com/forums/265200-power-bi to see if anyone else has asked for them. If yes, you can vote their idea up. If no, then you can enter your own idea. 

Hope that helps -- thanks!

**Comment by jordanmills** [comment]
Well thanks for checking.  There are lots of ideas covering most of what we need for powershell/programmatic administration, they're just not being acted on.  I can't even get signed in on that site because there's an error with the capcha system.
