### ISSUE TITLE
Left Navigation Pane Missing QBO Links

### ISSUE THREAD

**Issue by ybulman** [MicrosoftDocs/powerbi-docs#1035]
Hello, 

In this article it states;

After Power BI imports the data, you see a new dashboard, report, and dataset in the left navigation pane. New items are marked with a yellow asterisk *.

I have connected successfully but I still don't see these links in the navigation pane

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mihart** [comment]
Thanks for your comment, @ybulman . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @ybulman -- the app has been completely updated. Are you still seeing this issue? If not, we'll close this issue.
thanks!

**Comment by mgblythe** [comment]
Closing this one out based on the last update. @ybulman - feel free to reopen if you're still seeing issues.
