### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by ArvidBaa** [MicrosoftDocs/powerbi-docs#1036]
I miss an explanation on the output format for the script. Should the script simply end with a DataFrame in a variable with name df, or is it more generic than that? If I want to import and combine multiple DataFrames (as the introduction indicates is possible), then how should the DataFrames be saved? In an array with a specific name? Or, perhaps Power BI will import each individual DataFrame variable?

Please, could you add some explanation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Running Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment]
Thanks for your comment, @ArvidBaa . This issue has been assigned to the doc author for review.

**Comment by otarb** [comment]
Hello @ArvidBaa, to import data frame from python script into Power BI all you have to do is to a have variable of type DataFrame you want to import. All variables that are of pandas DataFrame type will be imported as entities using variable name as a name, rest are ignored.

![image](https://user-images.githubusercontent.com/17887981/60464681-20774380-9c04-11e9-9d72-52048cca34e3.png)

![image](https://user-images.githubusercontent.com/17887981/60464702-2e2cc900-9c04-11e9-884c-34c1b72f9f92.png)

**Comment by ArvidBaa** [comment]
Hi @otarb and thank you for the explanation!

**Comment by otarb** [comment]
#please-close @mgblythe
