### ISSUE TITLE
Billing Profile ID and Tenant ID 

### ISSUE THREAD

**Issue by BrianPie** [MicrosoftDocs/powerbi-docs#1037]
After entering Billing Profile ID , Power Query Editor returns the message "TenantId: Failed to discover tenantsBillingAccountId: Failed to discover tenants"   Would someone add in the permission requirements needed to access the data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure cost and usage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @BrianPie . This issue has been assigned to the doc author for review.

**Comment by awentzel** [comment]
This also happens to myself.  Additionally, My portal does not have a Billing Profile. Perhaps it's because i'm and internally billed subscription for Microsoft. However, the documentation should be updated to match the current user interface.  Really, it seems like it's asking not for Billing Profile ID, but, rather the Subscription ID.

**Comment by sbhuttan** [comment]
Is there an update on this issue? Is there a way to connect using Azure Cost Management or acknowledgement if this is a work in progress? 

There is no billing profile ID to be found on Azure. Using Subscription ID instead is giving error as above.

**Comment by vcandeau** [comment]
Still no update for this problem.

We open a support case but no answer from microsoft about the wrong documentation

**Comment by tnewton81** [comment]
> This also happens to myself. Additionally, My portal does not have a Billing Profile. Perhaps it's because i'm and internally billed subscription for Microsoft. However, the documentation should be updated to match the current user interface. Really, it seems like it's asking not for Billing Profile ID, but, rather the Subscription ID.

Neither subscription ID or Enrollment numbers will work.

**Comment by matt-egroup** [comment]
I'm in the same boat and see this same thread in other forums. I know it says this on the connector but I guess they REALLY mean it is in Beta.

**Comment by BrianPie** [comment]
I kinda of having it working using Power BI.   Correct me if I err on any statements: 

Get Data -> Azure -> Azure Cost Management (Beta) is for non Enterprise  Agreements. Error:  TenantId: Failed to discover tenantsBillingAccountId: Failed to discover tenants

For Enterprise Agreements 
Get Data -> Online Services -> Microsoft Azure Consumption Insights (Beta).

**Comment by joanabdo** [comment]
Any update for this issue?

**Comment by markmassad** [comment]
BrianPie, with that Beta connection, it asks for Account Key.  What did you use for that?

**Comment by BrianPie** [comment]
It has been a year since I closed that issue.  I don’t remember what I used to connect.

Brian Pierschbacher   |   Database Engineer
[cid:image005.png@01D6917D.180EA200]    601 6th Avenue                             [cid:image006.png@01D6917D.180EA200]        brian.pierschbacher@americanenterprise.com
        Des Moines, Iowa 50309            [cid:image007.png@01D6917D.180EA200]       office phone: 515.695.2457

[cid:image008.png@01D6917D.180EA200]<http://www.americanenterprise.com/>
