### ISSUE TITLE
Add Intellisense in Scripting Pane

### ISSUE THREAD

**Issue by databoxinsights** [MicrosoftDocs/powerbi-docs#1039]
Please add an intellisense option when scripting in Python within M queries :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Running Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment]
Thanks for your comment, @databoxinsights . This issue has been assigned to the doc author for review.

**Comment by otarb** [comment]
Intellisense is currently only supported in script editor when developing script based visuals

For adding intellisense support in PowerQuery script transforms and get data experience, please create idea on https://ideas.powerbi.com/

Thanks

**Comment by otarb** [comment]
#please-close @mgblythe
