### ISSUE TITLE
More Information on R Packages Supported by Power BI Service

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/powerbi-docs#104]
This issue was created by @enterprisecommunity-dsa from https://github.com/MicrosoftDocs/feedback/issues/545
In the article "R packages in the Power BI service", can the list of supported packages be improved to give more information? I am attempting to browse the list to find a package which has functionality similar to the package I have been using in development, but with no information other than a package name and version number, this is a tiresome exercise.
A list of package names with their subtitles as published to CRAN (see link) is much much easier to read to find an appropriate alternative package.
https://cran.r-project.org/web/packages/available_packages_by_name.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported for using and creating R scripts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@Powerhelmsman - thanks for your suggestion and request. I've recently updated the list of supported R packages, so hopefully that's useful. Adding more information can create an update issue (how to monitor when those change, and keep it fresh) but I'll discuss with the engineering team. Thanks for the feedback!
