### ISSUE TITLE
Can authentication be done through MSI?

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#1040]
Can authentication be done through MSI?
What would be the resource URL to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @djpirra -- thanks for your question! I've assigned it to the writer to investigate.

**Comment by mwc360** [comment]
IS there an update on this?

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @djpirra,

At present Power BI Embedded uses token authentication. MSI is not supported.

You might find more information relating to what you're trying to do, in the [Power BI Community]( https://community.powerbi.com).
