### ISSUE TITLE
Python data source cannot be used in Power BI Service through the gateway

### ISSUE THREAD

**Issue by ArvidBaa** [MicrosoftDocs/powerbi-docs#1041]
I just set up a data source using a python script, that collects a number of files, applies some filters and finally combines them into a single Pandas DataFrame. This works just fine in Power BI Desktop, but as soon as I try to publish the dataset to Power BI Service, the scheduled refresh stops working. After quite some time searching the web I finally found someone saying that Python scripts doesn't work as data source in Power BI Service, but no reference to any documentation. I think it would be wise to add that information here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Running Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by maggiesMSFT** [comment]
Hi, @ArvidBaa -- thanks for your question! I've assigned it to the author. In the meantime, I recommend checking the community site to see if anyone there has an answer.
https://community.powerbi.com/

**Comment by ArvidBaa** [comment]
Hi, @maggiesMSFT and thank you for the response. I am confident that the answer I had already found about Python script not working as data source in Power BI Service was correct. So this is not a question about a problem that I want an answer to, but a suggestion to add the information about the limitations of how and when Python scripts will and will not work to the documentation.

**Comment by maggiesMSFT** [comment]
Thanks for clarifying, @ArvidBaa! I'll pass this on to the author also.

**Comment by otarb** [comment]
@ArvidBaa to be able to use Python (or R) as data-source in the service, you need to set up a personal gateway

For more information check out this article [Use personal gateways in Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode)


Information about this is also mentioned at [Using Python in Query Editor](https://docs.microsoft.com/en-us/power-bi/desktop-python-in-query-editor), under the limitations section

**Comment by otarb** [comment]
#please-close @otarb
