### ISSUE TITLE
This sorting doesn't appear to work on the "matrix" visual

### ISSUE THREAD

**Issue by JuniorIce** [MicrosoftDocs/powerbi-docs#1042]
I have a matrix visual that has months in the header (January 2019, February 2019, etc.) and then the rows show the revenue by company (each month). There doesn't appear to be any way to sort the rows (largest to smallest) based on the value under a particular month column. I see that I can add a total column and sort on that, but I'm not able to sort based on the sales amount by customer for a particular month.  Is there a way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sort-by-column#feedback)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @JuniorIce -- thanks for your question! I've assigned it to the author. In the meantime, you may want to ask the Power BI community, https://community.powerbi.com/.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
