### ISSUE TITLE
Limitation - Power BI Premium

### ISSUE THREAD

**Issue by siva44** [MicrosoftDocs/powerbi-docs#1043]
Hello,
Are these limitations applicable to Premium as well?

Thanks,
Siva

**Comment by maggiesMSFT** [comment]
Hi, @siva44 -- it's unclear which limitations you're referring to. Can you include a link to an article?
thanks!

**Comment by siva44** [comment]
Here it is, https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#limitations-and-considerations

**Comment by maggiesMSFT** [comment]
Got it, thanks! I've assigned your question to the author.

**Comment by mgblythe** [comment]
Thanks for the question. The article now include the following sentence:

These limitations and considerations apply to Power BI Desktop and the Power BI service, including Power BI Pro and Premium
