### ISSUE TITLE
Remove video

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/powerbi-docs#1044]
That video at the top of this article is so old, almost all of the content in the video has been replaced by other stuff.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70948401-a30b-6499-82ce-cbc659b07d74
* Version Independent ID: 3b891116-3acd-dcd0-47e0-b99375696d56
* Content: [Find Power BI users that have signed in - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-access-usage)
* Content Source: [powerbi-docs/service-admin-access-usage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-access-usage.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for the feedback, @poortom1004 ! I've assigned it to the author.

**Comment by mgblythe** [comment]
Thanks @poortom1004 - removed the video, updated article should be live in a couple of hours.
