### ISSUE TITLE
[WTD] Write the Docs Inclusion Project

### ISSUE THREAD

**Issue by SyntaxC4** [MicrosoftDocs/powerbi-docs#1045]
Hello fellow documentarians! 

First off, I'd like to thank each of you for participating in the Write the Docs writing day. We appreciate you spending time with us while we work towards building more inclusive documentation. 

# The Goal 

At Microsoft, our mission is to empower every person and every organization on the planet to achieve more. To realize this mission, we need to ensure that our documentation speaks to a global audience and is inclusive of all. 

We are seeking your help to assist us in ensuring our documentation is more inclusive. Review the [resources](#resources) below, as they will help you on your way.  

We are asking for your help in the following ways: 

* [Provide an update from our curated list of suggestions](#suggestions)
* [Update a topic you are familiar with, which has an issue](#familiar-topic)
* [File an issue on content in which you’ve found an issue](#file-an-issue)

<a id="suggestions"></a>
### How to contribute from the curated list of suggestions 

1. Review the list of GitHub Issues to find suggested updates curated by our team 
1. Provide a comment on an issue that you are picking up, to avoid duplicate effort 
1. Fix the issue(s) outlined in the GitHub Issue 
1. Create a Pull Request to submit the fix 
    1. Start the PR title with **[WTD]**

<a id="familiar-topic"></a>
### How to contribute to a topic you are familiar with 

1. Browse to the article on [docs.microsoft.com](https://docs.microsoft.com)
1. Select the edit button in the header to be redirected to the article on GitHub 
1. Select the pencil icon, and edit the relevant lines of the article 
1. SelectPropose file change, in the GitHub UI to create a pull request 
    1. Start the PR title with **[WTD]**

<a id="file-an-issue"></a>
### File an issue on content in which you’ve found an issue 

1. Browse to an article on docs.microsoft.com 
1. Under the Feedback header at the bottom of the page, select the “This page” button under the Send feedback about text. 
    1. Start the Issue Title with **[WTD]**
1. Leave a descriptive comment to help us narrow down how to resolve the issue 
    1. Include a link to one of the Inclusive Language resources below (or others you know of) -- help us grow and learn, as well! 

<a id="resources"></a>
## Resources 

* [Microsoft Docs Contributors Guide](https://docs.microsoft.com/en-us/contribute/)
* [Gender Inclusive Language Guidelines](https://www.un.org/en/gender-inclusive-language/guidelines.shtml) – UN 
* [Inclusive Language in Four Easy Steps](https://www.extension.harvard.edu/professional-development/blog/inclusive-language-four-easy-steps) - Harvard 

## Repositories in Scope

* [Azure Docs](https://github.com/MicrosoftDocs/azure-docs/labels/%3Abook%3A%20Write%20the%20Docs)
* [PowerBI Docs](https://github.com/MicrosoftDocs/powerbi-docs/labels/%3Abook%3A%20Write%20the%20Docs)
* [System Center Configuration Manager (SCCM) Docs](https://github.com/MicrosoftDocs/SCCMdocs/labels/%3Abook%3A%20Write%20the%20Docs)

**Comment by mgblythe** [comment]
Fixed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/2311
