### ISSUE TITLE
RLS

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#1046]
RLS does work at least for report subscriptions.  The data is filtered accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe yourself and others to reports and dashboards in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-report-subscribe#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- me again! OK, I checked with the product team. Here's their response: 
IF the report subscription is only for yourself, it does work – you simply can’t subscribe others to a report with RLS in Power BI right now.  
Paginated Reports allows you to subscribe other users to reports with RLS turned on, however, the attachment data is based on the initial subscriber only.
Hope that clears things up. I'll look at the article and see if I need to clarify.
Thanks for asking!

**Comment by asocorro** [comment]
Hi!  Thanks for the quick response, as usual.

IF the report subscription is only for yourself, it does work – you simply can’t subscribe others to a report with RLS in Power BI right now.
Yes, my comment was that the article says it doesn’t.

By the way, it would be nice if subscriptions remembered the filter state of the report (if one so chooses).

Have a nice weekend,
Adolfo

**Comment by maggiesMSFT** [comment]
@asocorro -- got it, thanks. Yes, I'll update the article.

**Comment by maggiesMSFT** [comment]
OK, article updated. Thanks, @asocorro !
