### ISSUE TITLE
Bookmarks and date hierarchies

### ISSUE THREAD

**Issue by Derwilf** [MicrosoftDocs/powerbi-docs#105]
Hello, I am trying to create bookmarks in my report. The report contains a date hierarchy, and the goal is to use the bookmark feature to switch between a monthly report and a weekly report. I have two bookmarks, one with a drill down on month and the other with a drill down on week. Switching bookmarks changes filters, but only keeps the last drill down state. Are there any plans to fix that, I am using March 2018 version optimized for report servers. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @Derwilf -- this sounds like a product question rather than about the docs. I recommend asking in the Power BI Community, https://community.powerbi.com/. Thanks!
