### ISSUE TITLE
missing content

### ISSUE THREAD

**Issue by tomwill98103** [MicrosoftDocs/powerbi-docs#1055]
Last sentence in the 'Schema discovery' is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b2117-3a8d-1b35-109c-df315738beac
* Version Independent ID: d31fe48a-8b7d-149f-0db5-2818a4fa07cc
* Content: [Azure Machine Learning integration in Power BI (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-machine-learning-integration)
* Content Source: [powerbi-docs/service-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @tomwill98103 -- thanks for pointing that out! I've assigned it to the author to look at.

**Comment by davidiseminger** [comment]
Thanks for pointing that out, and sorry about that! Fixed.
