### ISSUE TITLE
Clarification on API restrictions

### ISSUE THREAD

**Issue by awbarbeau** [MicrosoftDocs/powerbi-docs#1056]
Can you please clarify if the limitation “Service principal does not support admin APIs” applies to just the *AsAdmin operations for the Power BI REST APIs, or if the API restriction is colloquial and any other API operations are not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi @awbarbeau -- thanks for your question! I've assigned it to the authors. In the meantime I recommend going to the Power BI community site and asking there, too. https://community.powerbi.com/

**Comment by markingmyname** [comment]
Hi @awbarbeau,

I changed the limitation in the article to state "any" admin APIs to be more clear.

This update will go live in a few days.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
