### ISSUE TITLE
Is there a self-service sign-up for Power BI Free license

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#1058]
This comment could have been dropped in the Self-service sign-up as well, but there it states clearly that its only for PRO-license.
My question is if you have missed to describe how to do self-service sign-up for just a Free license or if this is only possible to do as you describe in this article by either signing up for a PRO trial or by centrally managing users from the admin center (or scripting) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9cf4ce3-f6b1-2c73-d0f9-44573242fb85
* Version Independent ID: fc6a52fd-db96-6e9f-f89a-3dea59bff3b7
* Content: [Power BI licensing in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-licensing-organization)
* Content Source: [powerbi-docs/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @erapade -- thanks for your question! I've assigned it to the author. In the meantime I recommend going to the Power BI community site and asking there, too. https://community.powerbi.com/

**Comment by mgblythe** [comment]
Hi, @erapade - the self-service flow is for Pro trial. If you let the trial expire, you end up with a free license.

**Comment by erapade** [comment]
Hi @mgblythe
As we have some premium plans, we are not interested in having our report viewers also getting a PRO license. I can see that visiting http://app.powerbi.com, you get the possibility to sign up for just a free account, although by getting two pop up questions. But as I don’t see this described in your documentation’s I would like to point out that you also should add this information.
