### ISSUE TITLE
Java Script Error

### ISSUE THREAD

**Issue by bdevany** [MicrosoftDocs/powerbi-docs#1059]
When trying to connect to Quickbooks Online, a Java Script error message pops up each time the window opens to log into Quickbooks.  After selecting "yes" to continue running the script, the outside frame of the Quickbooks window appears, but the fields to enter credentials never appears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @bdevany -- this looks like a bug. Please go to the Power BI support site and ask there: https://powerbi.microsoft.com/en-us/support/
