### ISSUE TITLE
Sharing via API

### ISSUE THREAD

**Issue by alexb5dh** [MicrosoftDocs/powerbi-docs#1068]
Is it possible to share via Power BI REST APIs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-dashboards)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alexb5dh -- Thanks for your question! I don't know the answer. I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @alexb5dh -- here's your answer: Sharing, as in directly sharing a report with a user is not available, but sharing as in adding a user to a workspace is: https://docs.microsoft.com/en-us/rest/api/power-bi/groups/addgroupuser
That currently supports adding a user as an admin only.
Hope that helps!
