### ISSUE TITLE
SSMS Failing to connect to a premium capacity(with '&' character in name)

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#1069]
Hello,

SSMS is failing to connect to a powerbi premium capacity workspace with '&' in the character.. it throws an error with message box(which shows '&' removed).. which makes me believe SSMS is discarding '&' and trying

-Ganesh M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1b920c-639a-a627-58f2-e8fd69c9ef7d
* Version Independent ID: ab13e62f-0629-0aed-7e85-a902e150f9b1
* Content: [Connect to Power BI Premium datasets with client applications and tools (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-connect-tools#connecting-to-a-premium-workspace)
* Content Source: [powerbi-docs/service-premium-connect-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-connect-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @mganeshphani -- Thanks for your question! I've assigned it to the author. 
In the meantime I recommend asking the Power BI community https://community.powerbi.com/.

**Comment by Minewiskan** [comment]
#in-progress

**Comment by franklinherrera** [comment]
Hello,

 Thank you for sharing this awesome post. I'm trying to connect to a Premium workspace using SSMS but I get the next error:

TITLE: Connect to Server
------------------------------
Cannot connect to powerbi://api.powerbi.com/v1.0/[tenant name]/[workspace name]
------------------------------
ADDITIONAL INFORMATION:
The integrated security 'ClaimsToken' is not supported for native connections. (Microsoft.AnalysisServices.AppLocal.AdomdClient)
------------------------------
BUTTONS: OK
------------------------------

Should I have to do something in my tenant or workspace?

**Comment by Minewiskan** [comment]
@mganeshphani - Are you still seeing this issue? We tested and aren't able to repro.

**Comment by Minewiskan** [comment]
No response. #please-close

**Comment by jediwarpraptor** [comment]
Was this ever actually resolved?  I'm currently getting the same exact error trying to connect to PowerBI Premium capacity using SSMS.

**Comment by Minewiskan** [comment]
@jediwarpraptor - The outcome of this particular issue is unknown. Please open a support case for your issue. If you're able to determine a resolution, please post it in this Git Issue.

**Comment by anniexudan** [comment]
@franklinherrera @jediwarpraptor  upgrade your SSMS version to 18.1 and above should solve the problem.
