### ISSUE TITLE
Power BI Guided Learning - visualization

### ISSUE THREAD

**Issue by shitalneralkar** [MicrosoftDocs/powerbi-docs#107]
This training/learning video is awesome
All contents has very clear understanding and very good demo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08962cd6-cbb2-3342-09df-aa199623e9fb
* Version Independent ID: d4ebdf44-cde2-82b6-3f82-8524f370d980
* Content: [Visualizations - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/visualizations?tutorial-step=20)
* Content Source: [powerbi-docs/guided-learning/visualizations.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/visualizations.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @shitalneralkar -- Thanks for the feedback! I'll let the author, @davidiseminger, know. We're glad you appreciated it and hope it helps you learn how best to use Power BI!
