### ISSUE TITLE
Confusion around "Power BI Premium" ACLs for DataFlow & ADLSG2 Integration

### ISSUE THREAD

**Issue by kafong123** [MicrosoftDocs/powerbi-docs#1071]
In step 5 of https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#grant-power-bi-permissions-to-the-file-system, it is not clear that we have to add the object Id of "Power BI Premium" to ADLS Gen 2 ACLs for the integration to work. If we can clarify step 5 and 7 to include adding "Power BI Premium" to ADLS Gen 2 ACLs, that will be great!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#grant-power-bi-permissions-to-the-file-system)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @kafong123 -- thanks for the suggestion! I've assigned it to the author.

**Comment by davidiseminger** [comment]
Thanks for pointing this out - I've fixed those, they'll show up in the article within 24 hours.
