### ISSUE TITLE
Subscription are now supported for paginated reports

### ISSUE THREAD

**Issue by geneosu** [MicrosoftDocs/powerbi-docs#1072]
Here's the announcment: https://powerbi.microsoft.com/en-us/blog/e-mail-subscriptions-for-paginated-reports-is-now-available/
and the documentation page: https://docs.microsoft.com/en-us/power-bi/paginated-reports-subscriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce5d0507-1ff2-46ed-8563-e80b19644f26
* Version Independent ID: 415119ab-1731-b361-10ec-d9ace9802f7d
* Content: [What are paginated reports in Power BI Premium? (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-report-builder-power-bi#feedback)
* Content Source: [powerbi-docs/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @geneosu -- awesome, thanks for the reminder! I'm updating the article now.

**Comment by maggiesMSFT** [comment]
OK, article updated. Thanks, @geneosu !
