### ISSUE TITLE
Restart capacity API

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#1073]
Hello,

We have seen restarting premium capacity once in a week has helped with different type of refresh issues on our premium capacities. is there an API we can use to automate this process?

-Ganesh m.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ac065d-33c5-2f3b-6cee-36153c2a8afa
* Version Independent ID: 40b95c43-2aca-da1b-9325-709366056f28
* Content: [Restart a Power BI Premium capacity - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-restart#how-do-i-restart-a-capacity)
* Content Source: [powerbi-docs/service-admin-premium-restart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-restart.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @mganeshphani -- thanks for your question! I've assigned it to the author. In the meantime, you can ask the Power BI community, https://community.powerbi.com/

**Comment by mganeshphani** [comment]
Thanks @maggiesMSFT .. I asked help from our TAM to reach engg team to find answers.. but not gotten any traction yet.

**Comment by mgblythe** [comment]
Hi @mganeshphani - there is currently no API available for capacity restart. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by Bryand13** [comment]
Hello,

Sorry if this is not the right way.  But is there any API or documentation to restart the capacity premium?

Thanks in advance!
