### ISSUE TITLE
sample databases

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#1075]
Please link SQL sample databases like [Contoso](https://www.microsoft.com/en-us/download/details.aspx?id=46801)

**Comment by mihart** [comment]
Thanks for this idea @rootsmusic . Based on documentation priorities, we're not planning to address the issue at this time, but will consider it when we roll out the new samples.

**Comment by maggiesMSFT** [comment]
Hi, @rootsmusic -- I like the idea! I'll try to work it in. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @rootsmusic -- I'm closing this issue, as you have opened a new one on the same subject, https://github.com/MicrosoftDocs/powerbi-docs/issues/1399. 
I still think it's a good idea. I still can't promise a timeline.
