### ISSUE TITLE
duplicate phrase

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#1077]
On Step 6, under Counting values with DAX: "...but DAX approaches in a different way in a different way,...."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7#feedback)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Good catch, @nicheplayer ! I'll pass it along to the author.

**Comment by davidiseminger** [comment]
Good catch! Thanks, fixed. Will update online within 24 hours.
