### ISSUE TITLE
apply a filter while loading a table

### ISSUE THREAD

**Issue by damf74** [MicrosoftDocs/powerbi-docs#1078]
Hey,
Can I apply a filter to avoid loading a entire very heavy table ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29bfbd4c-5149-93be-3982-81af6852a5dd
* Version Independent ID: 75460ed0-c7d9-fe67-8010-b843661dc66e
* Content: [Connect to an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-odata#feedback)
* Content Source: [powerbi-docs/desktop-connect-odata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-odata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @damf74 -- thanks for your question! I'm assigning it to the author to follow up.
Just curious, during the Get Data process, in the Navigator dialog, did you try selecting Edit rather than Load? You should be able to filter the data in the Query Editor.

**Comment by Remeth** [comment]
Being able to use the SELECT and the FILTER parts of the ODATA source in Power BI seems very lacking.

Without using Json.Document(Web.Content("http://myodataapi/odata/selectAndFilter"))

Why doesn't the OData connector support the OData v4 standard way of doing selects and filters?

**Comment by davidiseminger** [comment]
Thanks for your comment, @damf74 . 

The quick answer is: yes, you can apply filters in Power Query Editor to pare down the data you load into a model, without having to load the entire source. Power BI lets you see a portion of the data so you can get a view into it, and from which you can apply all sorts of filters to minimize (or trim) the size of the data load.

For more in-depth questions, look at the Power BI Community, found at https://community.powerbi.com. And you can get support by going to https://support.powerbi.com.
