### ISSUE TITLE
Advanced analytics not appearing for Scatter plot

### ISSUE THREAD

**Issue by whiteleyrod** [MicrosoftDocs/powerbi-docs#1079]
Hey,
I have a bunch of scatters on a report that I'm trying to add some analytic lines to, but the only options appearing are: Trend Line, X- and Y-Axis Constant, and Symmetry Shading (4 options total).
I can't find, for example, a median line, or the others which I think should be here such as Min, Max, Forecasting, etc.
I'm using Version: 2.68.5432.841 64-bit (April 2019)
What am I missing here?
thanks in advance for any help,
Rod

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Using the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-analytics-pane#feedback)
* Content Source: [powerbi-docs/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @whiteleyrod -- thanks for your question! I've assigned it to the article author.

**Comment by davidiseminger** [comment]
Thanks for your comment, @whiteleyrod . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
