### ISSUE TITLE
SQL Server requirements

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#1081]
This document should specify that only Enterprise and BI editions of SQL Server 2012 and 2014 support live connection and that SQL Server 2016 or later is required when using Standard edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00aefcea-9c15-e4a5-b66b-59b6f446348e
* Version Independent ID: 098101d4-0cdb-913f-1d6d-f6b74cc25426
* Content: [Analysis Services Multidimensional data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-ssas-multidimensional#feedback)
* Content Source: [powerbi-docs/desktop-ssas-multidimensional.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-ssas-multidimensional.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @rcfoyn -- thanks for your comment! I've assigned it to the author.

**Comment by davidiseminger** [comment]
Thanks for your clarifications - I've added that to the Limitations section, which will show up within 24 hours.
