### ISSUE TITLE
Query caching not available on datasets created via the API

### ISSUE THREAD

**Issue by MPEV** [MicrosoftDocs/powerbi-docs#1082]
Based on my findings, it would appear that datasets created via the API don't have this option. Assuming this is correct, it might be worth clarifying this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching#feedback)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MPEV -- thanks for your comment! I've assigned it to an expert on the subject.

**Comment by Bhavik-MSFT** [comment]
Hi @MPEV is the dataset on a Premium workspace? Are there any other errors or warnings showing on the dataset settings page?

**Comment by MPEV** [comment]
I've subsequently found that when the dataset is created (via the API) the option is not there. But if I refresh a minute or two later it appears.
Can the value of this be set via the API? The wording also suggests it can be set via the Capacity, but I can't find this setting on the Capacity inthe Azure portal - is it possible?

**Comment by Bhavik-MSFT** [comment]
We are investigating this issue and will resolve. The caching setting cannot be set via the API at the moment.

**Comment by Bhavik-MSFT** [comment]
#please-close @maggiesMSFT
