### ISSUE TITLE
Embedding setup tool only creates traditional workspace and is not compatible with ServicePrincipal authentication

### ISSUE THREAD

**Issue by rohancragg** [MicrosoftDocs/powerbi-docs#1083]
This article states "if you use service principal to sign into your application, then you're required to you use the new workspaces"

Where this is the case, readers should be warned NOT to use the 'Embedding setup tool'.

I wasted a day doing this and was unable to get the resulting 'App Owns Data' sample app working because the automated tool creates the wrong sort of workspace (traditional), which is not compatible with ServicePrincipal authentication type (this is because you cannot make the ServicePrincipal an Admin of a traditional workspace).

I was able to work around this by manually creating a 'new' workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @rohancragg -- thanks for your comment! I've assigned it to a few people to look into.

**Comment by markingmyname** [comment]
Hi @rohancragg,

We are aware of this limitation.

The plan is to address this limit when Service Principal for Power BI Embedded goes GA and is no longer in "preview."

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
