### ISSUE TITLE
Some features missing in latest version + error

### ISSUE THREAD

**Issue by rvcedd** [MicrosoftDocs/powerbi-docs#1084]
Hello, just completed a full read of the article and wanted to give you some feedback.

Regarding: "You can also use the Include and Exclude menu items to keep (or remove, respectively) the right-clicked row (and any subcategories) from the matrix."
It appears that in the Apr 2019 version the "Include" and "Exclude" features are not available anymore

Regarding "In the Format section of the Visualizations pane, expand the Subtotals card, and turn the Row subtotals slider to Off. When you do so, the subtotals are not shown."

The image following this sentence still display row-level totals. The picture looks identical to the one above suggesting there has been a typo.

Thanks,

Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d5bd-51e3-468a-0f7d-a936083f0dc5
* Version Independent ID: 59eea08a-c392-951e-2ba6-860cfcc58281
* Content: [Use the matrix visual in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual#feedback)
* Content Source: [powerbi-docs/visuals/desktop-matrix-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-matrix-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @rvcedd -- thanks for your comment! I've assigned it to the author.

**Comment by mihart** [comment]
Hi @rvcedd, thank you for the suggestions.  I've rewritten the article to match the improved interface. It will go live tomorrow.
Take care. 
The DOCS team.
