### ISSUE TITLE
can  “max” (target)  be a lower value than “min” (baseline)?

### ISSUE THREAD

**Issue by wsitek** [MicrosoftDocs/powerbi-docs#1085]
Is it possible to set “max” to a lower value than “min” in a radial gauge  in cases where a lower value is the goal? Similarly to setting “green” as “good” in the KPi visual?

We are using the gauges in a dashboard where a few KPIs are about reducing numbers, not increasing them, and it would be great for this to be visually similar to the more “normal” assumption that higher is better. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20ec85-cf09-5d0e-317c-1897a6f63b0b
* Version Independent ID: 8979a4de-7c09-8c5d-0415-e82957d29ccb
* Content: [Radial gauge charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-radial-gauge-charts#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @wsitek -- interesting question! I've assigned it to the author. In the meantime, consider asking in the Power BI community, https://community.powerbi.com/

**Comment by mihart** [comment]
Thanks for your comment, @wsitek . I spent a few minutes trying this out and couldn't get it to work.  However, I suggest that you post this question in the Power BI Community, at https://community.powerbi.com, and see if someone there has a suggestion.
