### ISSUE TITLE
Cross-report filters not working on shared reports

### ISSUE THREAD

**Issue by eliaspm15** [MicrosoftDocs/powerbi-docs#1086]
We have been testing Cross-Report filtering on the Power BI Service Premium and shared reports are only working for the user that published the report. When shared, users are unable to use this feature. Can you please comment on this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70cc0df0-14a7-079d-c32c-78fff8aef03f
* Version Independent ID: ff23bd8e-3901-3010-af39-19fb69f2fa6c
* Content: [Use cross-report drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-cross-report-drill-through#feedback)
* Content Source: [powerbi-docs/desktop-cross-report-drill-through.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-cross-report-drill-through.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @eliaspm15 -- interesting question! I've assigned it to the author. 
In the meantime, consider asking in the Power BI Community, https://community.powerbi.com/

**Comment by davidiseminger** [comment]
Thanks for your comment, @eliaspm15 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by gebberry** [comment]
Other thing is it doesn't seem to work for embedded links?
