### ISSUE TITLE
Default experience?  Doesn't seem to be.

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#1087]
"The new workspace experience has reached general availability (GA), and is now the default workspace."

I don't think this is accurate.  Nothing has changed with the interface when I try to create a new workspace.  I'm still prompted for data for a unified group workspace, with the "try now" button for a new workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jordanmills -- hmmm, that's not right. Can you head to the support site, https://powerbi.microsoft.com/en-us/support/?
