### ISSUE TITLE
Size Limits

### ISSUE THREAD

**Issue by vishalaj1** [MicrosoftDocs/powerbi-docs#1088]
Hi,

Does the size limit still applies on Power BI Service or Power BI Desktop?

1GB per dataset?

Regards,
Vishal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @vishalaj1 -- thanks for your question! I've assigned it to the author.

**Comment by davidiseminger** [comment]
It applies to the Power BI service, as stated in the article.
