### ISSUE TITLE
Making RLS work in a workspace (settings)

### ISSUE THREAD

**Issue by vincent2369** [MicrosoftDocs/powerbi-docs#1089]
It would be useful to add to this article that the admin of the workspace where the file with RLS has been published has to set members at read only for the RLS to work in the workspace. Otherwise by default this option is at members can read and edit report and RLS doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @vincent2369 -- thanks so much for your comment! I've assigned it to the author.

**Comment by mgblythe** [comment]
Thanks @vincent2369 - if I understand you correctly, this is covered in the doc: https://docs.microsoft.com/en-us/power-bi/service-admin-rls#using-rls-with-app-workspaces-in-power-bi.

**Comment by mgblythe** [comment]
Closing, feel free to reopen if this doesn't address your issue.
