### ISSUE TITLE
Install Out Of Date

### ISSUE THREAD

**Issue by keithspitz** [MicrosoftDocs/powerbi-docs#109]
Running "npm" command yields MANY warnings about out of date or risky components being installed.  This should be maintained/updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Use developer tools to create custom visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/service-custom-visuals-getting-started-with-developer-tools)
* Content Source: [powerbi-docs/service-custom-visuals-getting-started-with-developer-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-custom-visuals-getting-started-with-developer-tools.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ignatvilesov Please review.

**Comment by ignatvilesov** [comment]
This is a known issue as PBIVIZ dependencies are out of date. We're implementing a new PBIVIZ with updated dependencies and better developer experience.
This version is supporting ES2015 modules and other modern features.
