### ISSUE TITLE
Cannot drop database "TestGatewayDocs" because it is currently in use.

### ISSUE THREAD

**Issue by jeffzdli** [MicrosoftDocs/powerbi-docs#1090]
I followed Tutorial: Connect to on-premises data in SQL Server. In the end I tried to clean resource but I encountered issue: Cannot drop database "TestGatewayDocs" because it is currently in use. I deleted geteway related objects from my Power Bi Service: geteway instance, dataset, and report. Also I uninstalled on-premise from my pc. However, it still shows the same error message.

**Comment by davidiseminger** [comment]
Thanks for your comment, @jeffzdli. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
