### ISSUE TITLE
Contradicting documentation for hyperlink support in Power BI Service

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/powerbi-docs#1091]
&gt; Then use either Desktop or Power BI service to add those hyperlinks to your report tables and matrixes.

This seems half correct, if I understand correctly Power BI service only supports hyperlinks for tables.

&gt; You can create hyperlinks in tables and matrixes in Power BI Desktop, but not in the Power BI Service.

This seems outdated since tables now support hyperlinks in the Power BI Service.

In short, the page should be reviewed so everything is up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks for pointing this out, @jawn -- I'll check into it and clean it up.

**Comment by kfollis** [comment]
@jawn - Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
