### ISSUE TITLE
Export PDF for Power BI Desktop not working 

### ISSUE THREAD

**Issue by rjptechsolutions** [MicrosoftDocs/powerbi-docs#1092]
I used Power BI for couple of days I am learning phase of it but I don't know why power BI Desktop want Administrator privileges to open it and Export PDF Dialog is not coming up and not showing any error

**Comment by mihart** [comment]
Thanks for your comment, @rjptechsolutions . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
