### ISSUE TITLE
Dataflows

### ISSUE THREAD

**Issue by amlucius** [MicrosoftDocs/powerbi-docs#1094]
Is there a timeline for Dataflows availability in US gov cloud? If so, could you post it here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for United States Government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/service-govus-overview#feedback)
* Content Source: [powerbi-docs/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @amlucius -- thanks for your question! We don't refer to future features or functionality in the docs. That information is in the Business Applications Release Notes, https://docs.microsoft.com/en-us/business-applications-release-notes/april19/business-intelligence/planned-features.
Hope that helps!
