### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#1095]
You shouldn't be referring to this as OneDrive.  The Office 365 group has a SharePoint site collection behind it.  OneDrive is a personal space for users (which runs on SharePoint).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#workspace-onedrive)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @danmyhre -- thanks for your feedback! I'll check to see what would be better wording.

**Comment by danmyhre** [comment]
Maybe add clarification then until they fix the product.
