### ISSUE TITLE
 Status: Unauthorized (401)?

### ISSUE THREAD

**Issue by arashaga** [MicrosoftDocs/powerbi-docs#1096]
When I click on Embed report i get this:

Error
            Status: Unauthorized (401)
Response: {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
RequestId: dea63ade-adc6-4e4b-9860-f63744d6c1d2

**Comment by mihart** [comment]
Thanks for your comment, @arashaga. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
