### ISSUE TITLE
Repeating sentence

### ISSUE THREAD

**Issue by Downez** [MicrosoftDocs/powerbi-docs#1097]
Under header "RangeStart and RangeEnd parameters", the final three sentences read:

"Once published, the parameter values are overridden automatically by the Power BI service. 
There's no need to set them in dataset settings in the service. 
Once published, the parameter values are overridden automatically by the Power BI service."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @christianwade
* Microsoft Alias: **chwade**

**Comment by mihart** [comment]
Thanks for catching that issue, @Downez ! This issue has been assigned to the doc author for review.

**Comment by christianwade** [comment]
@mgblythe can you please assign to the docs owner to get it corrected?

**Comment by mgblythe** [comment]
@christianwade - issue and article now assigned to me, thanks.

**Comment by mgblythe** [comment]
Fix is now live.
