### ISSUE TITLE
New Navigation experience on mobile app

### ISSUE THREAD

**Issue by devaccount89** [MicrosoftDocs/powerbi-docs#1099]
The new navigation structure is not reflected in the PowerBI iPhone app. Is this by design or an issue ? Thanks. Best, Moritz

**Comment by mgblythe** [comment]
Thanks for your comment, @devaccount89. This looks like a product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
