### ISSUE TITLE
Compatibility with a non default language PWA site

### ISSUE THREAD

**Issue by matthiasvanneste** [MicrosoftDocs/powerbi-docs#110]
Our PWA site has been setup using Dutch as our default language. I'm assuming this is why installing the PWA app fails in our Power BI instance. Is there currently a way to make this work on PWA sites that don't use any of the default languages? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8a7a22-e258-4da3-4c55-6ddb1085c521
* Version Independent ID: 0b3f2b88-9e73-f4dd-0f21-fe3c156a99b8
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-project-online)
* Content Source: [powerbi-docs/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-project-online.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @matthiasvanneste -- Thanks for your question. I've assigned it to the author, @SarinaJoan. I suggest also trying the community site, https://community.powerbi.com/. Good luck!
