### ISSUE TITLE
Required Permissions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#1100]
Please add the type of permissions that are required to install the gateway and managed it in the PowerBI Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91f53e6-e1f8-02c0-0421-94eac7fe05e3
* Version Independent ID: a4e20869-112a-a8e0-4fd4-9d75e12667d1
* Content: [Install a gateway for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-install)
* Content Source: [powerbi-docs/service-gateway-install.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-install.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @DeanGross, we're updating the gateway docs, and I'll include this request.

@arthiriyer as FYI

**Comment by mgblythe** [comment]
Added question and answer to the gateway FAQ (https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem-faq) indicating no special permissions are required to install the gateway:

Question: Are there any permissions prerequisites to install gateways?
Answer: There are no restrictions for installing and registering a gateway, but every cloud service could have restrictions on how gateways are used within their service based on licensing.

Thanks!
