### ISSUE TITLE
Incorrect Screenshot

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerbi-docs#1101]
Hello,

Under step 5 of "Get started with a service principal", the screenshot displayed shows adding the service principal account to the workspace's **contact list**. However, the instructions describe adding that account as an admin--which, when done through the UI, involves editing the **access list**, not the **contact list**. Should the current screenshot be swapped out for one of the access list?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @bgribaudo. This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Good eye, @bgribaudo!  

I have updated the image to show the access list instead of the contact list.

The update should be live by the end of the week.

Thanks again!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by bgribaudo** [comment]
Thank you, @markingmyname!
