### ISSUE TITLE
Getting a bounce back on the R package suggestions email

### ISSUE THREAD

**Issue by crabdata** [MicrosoftDocs/powerbi-docs#1102]
Hello,

I was hoping to get an email out with the suggestion of a package 'bizdays' in but I'm getting a bounce back. would love to get this supported in PowerBI

It is already part of the cran repository: 
https://cran.r-project.org/package=bizdays

Thanks,
Clayton

**Comment by mgblythe** [comment]
@crabdata - what email address are you trying to send to?

**Comment by mgblythe** [comment]
@davidiseminger - assigning to you in case you know of an email address we provide for package suggestions.

**Comment by davidiseminger** [comment]
Thanks for your suggestion / request, @crabdata. For product feedback and requests, you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
