### ISSUE TITLE
Add page navigation

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1103]
Add a section on page navigation within a report, including right-clicking the arrow buttons in the bottom-left corner to pull up a menu of pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3aacded-9b0b-b9f4-918a-787f1211bb37
* Version Independent ID: 0219e69f-78b4-e962-2b86-41cae51c479b
* Content: [Power BI consumer capabilities in Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reading-view)
* Content Source: [powerbi-docs/consumer/end-user-reading-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-reading-view.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @Mike-Honey . I’ve added this to my docs backlog.  This is a great addition to the doc.  Thanks!
