### ISSUE TITLE
I have no "add tile" button

### ISSUE THREAD

**Issue by dimaty26** [MicrosoftDocs/powerbi-docs#1104]
I don't know why but I don't have this button. Is it one of updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f30eb2-e55e-635d-e161-6c26f20fac2d
* Version Independent ID: 7d1fd996-9981-a844-0f2b-abb35cf21b7f
* Content: [Add image, text, video, streaming data to your dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-add-widget)
* Content Source: [powerbi-docs/service-dashboard-add-widget.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-add-widget.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
@dimaty26 - you should have this button if you're in a _dashboard_. Are you trying to do this from a _report_?

**Comment by dimaty26** [comment]
![No tile](https://user-images.githubusercontent.com/44339621/58642501-2b3d7080-8306-11e9-9af9-38532924ae5c.PNG)

**Comment by mgblythe** [comment]
@dimaty26 - assigning to the author, but you should see **Add Tile** if you click one of the dashboards in that list, e.g. Marketing.

**Comment by maggiesMSFT** [comment]
Hi, @dimaty26 -- You're right! **Add tile** has moved to the ellipsis (...). Thanks for pointing that out! I'll update the article.

**Comment by maggiesMSFT** [comment]
Oh, @dimaty26, wait, I spoke to soon. That change is coming, but not yet. No, if you're looking at a dashboard, for the time being you should still see the big + sign and **Add tile**.

**Comment by kfollis** [comment]
@dimaty26 - Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
