### ISSUE TITLE
Inconsistency (Carlos)

### ISSUE THREAD

**Issue by woshigabriel** [MicrosoftDocs/powerbi-docs#1106]
"3b. The first PivotTable tells us that Carlos' revenue for his top Product, Primus, is down 152% from last year."

His revenue grew by 152% from last year... Something is wrong with the data here, or was his target/KPI set too high?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c25ad9a8-50b9-7f83-4e10-ebbbff013d6b
* Version Independent ID: 0584427f-6438-277b-4a0c-5d51f4694f63
* Content: [Customer Profitability sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-customer-profitability#feedback)
* Content Source: [powerbi-docs/sample-customer-profitability.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-customer-profitability.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @woshigabriel -- thanks for your question! I'll check into it and get back to you.

**Comment by kfollis** [comment]
@maggiesMSFT - Please validate the explanation for the data point for Primus total revenue. Explanation says revenue is down, but numbers show revenue growth.
![image](https://user-images.githubusercontent.com/28766705/98606911-f2e0e680-229c-11eb-93b2-d6abb77ef627.png)

**Comment by mihart** [comment]
Hi @woshigabriel ,
The data is indeed strange.  I've asked the sample owner to look into the data.  In the meantime, I've replaced the example with different data -- still showing how you can interact with the Excel file from within Power BI. 
Thank you for pointing this out.
The DOCS team
