### ISSUE TITLE
Reactivating disabled Power BI publisher for Excel addon

### ISSUE THREAD

**Issue by vincent2369** [MicrosoftDocs/powerbi-docs#1107]
Hello, I was doing an excel report connected to a Power BI report and when I changed the order of some field in the pivot table menu excel froze, after a bit it said it had to deactivate the Power BI plugin. 

to reactivate it I had to do:
"File &gt; Options &gt; Add-ins &gt; Disabled Items" to enable it then go back in "File &gt; Options &gt; Add-ins &gt; COM Add-ins" to activate it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Using Power BI publisher for Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @vincent2369. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting!
