### ISSUE TITLE
Recently experiencing temporary 500 errors on calls to Power BI REST API

### ISSUE THREAD

**Issue by donquijotedelamancha** [MicrosoftDocs/powerbi-docs#1108]
We follow this exact workflow to embed Power BI on an Asp.Net MVC app using App Owns Data and Master user.
Everything has been working normally until in the last weeks we start receiving 500 errors on the calls to the Power BI REST API.
The erros are temporary with all calls failing during a period of time with the same calls working again after.
You can find a bit more info on a StackOverflow entry regarding this issue:
https://stackoverflow.com/questions/56397893/power-bi-rest-api-temporary-500-errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by donquijotedelamancha** [comment]
This is being now reflected on the support page:
[https://powerbi.microsoft.com/en-us/support/](url)
Some Premium capacity customers in the West Europe B region may have intermittent issues with refreshes. Engineers are investigating the issue and will provide an update soon.

**Comment by mgblythe** [comment]
Thanks @donquijotedelamancha! Closing this out here b/c it's being tracked on the support site.
