### ISSUE TITLE
service principle unauthorized

### ISSUE THREAD

**Issue by jianyeliu** [MicrosoftDocs/powerbi-docs#1109]
[Enter feedback here]
I followed the steps smoothly according to https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal, and then run the sample application according to https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers.

I encountered below error while no error if use master user.

Status: Unauthorized (401)
Response: {"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}
RequestId: 49c2e739-d400-429c-860b-856b92f52a4b

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @jianyeliu. This issue has been assigned to the doc author for review. In the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com).

**Comment by jianyeliu** [comment]
I solved, thanks

**Comment by alexeybogusevich** [comment]
@jianyeliu can you please tell what was the problem?
