### ISSUE TITLE
Sharing

### ISSUE THREAD

**Issue by alokgupta1986** [MicrosoftDocs/powerbi-docs#111]
Should have more options for collaboration!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-dashboards)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alokgupta1986 -- Thanks for your comment! It seems more like feedback about the product than about the documentation. Here's the Power BI product feedback site: https://ideas.powerbi.com/forums/265200-power-bi. Search to see if anyone else has raised a similar issue. If they have, you can vote for it. If not, create a new issue. Good luck!

**Comment by makima** [comment]
Hi,
Some users, with permissions keep on having pop up messages requesting access when they open reports whereas they already have access. "x Let's get you permission to view this report". 
The accesses have been removed and setted back nothing changed
Any advice?
