### ISSUE TITLE
Role-based security

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#1110]
I would very much appreciate exhaustive information regarding the capabilities and limitations of Power BI ability to relate to the permissions defined in SSAS roles.

I suppose the following pertains to members being restricted from using entire dimensions (which seems to be supported in Power BI):
"When a user has dimension security applied, the respective dimension members are not seen by the user in Power BI."

When using the term 'cell' in the following, does this mean, for example, a specific member of a dimension? And this is not supported (would cause the user to be unable to connect to the cube at all?!)? If so, Microsoft should definitely work hard to provide such support, as this is one of the most important and useful aspects of restricting data access!
"When a user has a cell security permission defined, where certain cells are restricted, then that user cannot connect to the cube using Power BI."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00aefcea-9c15-e4a5-b66b-59b6f446348e
* Version Independent ID: 098101d4-0cdb-913f-1d6d-f6b74cc25426
* Content: [Analysis Services Multidimensional data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-ssas-multidimensional)
* Content Source: [powerbi-docs/desktop-ssas-multidimensional.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-ssas-multidimensional.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @rcfoyn. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Adding members for review.

**Comment by christianwade** [comment]
Hi @rcfoyn

Cell level security is described here: https://docs.microsoft.com/en-us/analysis-services/multidimensional-models/grant-custom-access-to-cell-data-analysis-services

Dimension security doesn't necessarily mean the user doesn't have access to the whole dimension, it can be just the restricted members. Further info here: https://docs.microsoft.com/en-us/analysis-services/multidimensional-models/grant-custom-access-to-dimension-data-analysis-services

**Comment by christianwade** [comment]
#please-close @mgblythe
