### ISSUE TITLE
Dedicated or embedded capacity?

### ISSUE THREAD

**Issue by dirk-seifert-obungi** [MicrosoftDocs/powerbi-docs#1111]
Under "Considerations and limitations":
"Dedicated Premium capacity is required when moving to production."

Is this correct, or is "Embedded capacity" meant? 

Embedded capacity was the requirement under the old app-owns-data sing-in model with a master user. It would make sense here, too - or does using the new service-principal sign-in actually require the (much more expensive) "Dedicated Premium Capacity"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @dirk-seifert-obungi. This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Good eye, @dirk-seifert-obungi!  

I've addressed this by editing to now show as "Dedicated capacity" as it does in the Power BI service.

This change should go live by the end of the week.

Did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by dirk-seifert-obungi** [comment]
@markingmyname Hi Mark, 

Thanks fo so quickly taking care of this!!

Should it not actually be "**embedded** capacity"? - as described here: 

https://docs.microsoft.com/en-us/power-bi/developer/azure-pbie-create-capacity
