### ISSUE TITLE
no sizing information for the report server database itself

### ISSUE THREAD

**Issue by iturner1** [MicrosoftDocs/powerbi-docs#1112]
it mentions the version requirements but nothing about how important the database is, what it contains, how to size it, etc..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f20394b-f5b1-2924-3670-932dba073875
* Version Independent ID: 71ec4d31-53e6-16d4-c250-c38f1bba2ba6
* Content: [Hardware and software requirements for installing Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/system-requirements#feedback)
* Content Source: [powerbi-docs/report-server/system-requirements.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/system-requirements.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @iturner1. This issue has been assigned to the doc author for review.

**Comment by teoaraujo** [comment]
Any news?

**Comment by maggiesMSFT** [comment]
Hi, @iturner1 and @teoaraujo -- belatedly, here's a related Reporting Services article that may help. https://docs.microsoft.com/en-us/sql/reporting-services/report-server/report-server-database-ssrs-native-mode
