### ISSUE TITLE
Incremental Refresh Screen Shots

### ISSUE THREAD

**Issue by bjstigall** [MicrosoftDocs/powerbi-docs#1113]
Incremental Refresh Screen Shots do not have a unit of time selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60093b2-2bdf-92e9-ee7c-de316b601beb
* Version Independent ID: 25307bcb-648e-e620-3fe9-a1412e89c0b5
* Content: [Using incremental refresh with Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-dataflows-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @bjstigall . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Now fixed, thanks for the heads up @bjstigall!
