### ISSUE TITLE
visual not getting displayed

### ISSUE THREAD

**Issue by narmadakrishnasamy** [MicrosoftDocs/powerbi-docs#1114]
After my pbiviz start command, i get a compiled successfully message and visual rebuild completed message in my terminal. but when i open my developer visual in power bi online i get an empty visual. please help. Reloading and creating new developer visual did not help either.

**Comment by davidiseminger** [comment]
Thanks for your comment, @narmadakrishnasamy . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
