### ISSUE TITLE
visual.ts causes errors when executing "pbiviz start"

### ISSUE THREAD

**Issue by benmjarmany** [MicrosoftDocs/powerbi-docs#1115]
When executing "pbiviz start" after making the edits to the visual.ts file, I get a lot of errors, such as:
"ERROR in C:\Users\ben.mckenna\circleCard\src\visual.ts(3,36)
      TS2304: Cannot find name 'IVisual'."
and the compile process fails.

I've also noticed that the content of the file seems to be very different to what this tutorial says should be there. The code starts with "use strict" followed by 10 import lines. This tutorial also expects there to be a line declaring a module at the start, but there is none in the file.

Perhaps there has been an update that the tutorial needs to account for?
Please advise. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI Custom Visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by davidiseminger** [comment]
Thanks for your comment, @benmjarmany. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by jarnawer** [comment]
@benmjarmany, @davidiseminger  I hit the same issue...take a look at this:

https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/

Maybe  you are using pbiviz v3.x...
You need to get rid of module declarations on your source code, among others...

Hope it works!

**Comment by benmjarmany** [comment]
Hi @jarnawer, thanks for the tip, I'll give this a go. And yes, I'm using v3.1.1. I'll report back once I've worked through the guide.

**Comment by jarnawer** [comment]
Hi @benmjarmany did you manage to solve the issue? 

If you want to check out my repo, i have a working example of a simple chart line using a custom visual:
https://github.com/jarnawer/pbiviz-linechart

Regards!

**Comment by benmjarmany** [comment]
Hi @jarnawer, thanks. The first article certainly helped, and I was able to get the CircleCard visual to display as desired.

I've had to move on to a different project now, but I'll be sure to check out your visual if I need further help. Thanks again.

**Comment by jpcarnes** [comment]
Hi @benmjarmany I was wondering if you could share what you did to fix this problem. I had similar issues that you had when trying to start my example visual.

Thanks in advance for the help!

**Comment by benmjarmany** [comment]
Hi @jpcarnes, the solution for me was actually just following the steps shown in the article @jarnawer shared, [at this URL.](https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/)
I didn't get round to finishing it, but I did manage to get the circle showing with text in it, which shows I was on the right track!
