### ISSUE TITLE
"Assign a Power BI Pro license to guest user" - yeah ok, but how?

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1116]
For the scenario above, "Assign a Power BI Pro license to guest user", please add some info on how to actually do this. It turns out to be quite obscure and most people fail, ref: 

https://answers.microsoft.com/en-us/msoffice/forum/msoffice_o365admin-mso_dep365-mso_o365b/assign-a-pro-license-to-a-guest-user-in-o365-admin/f70b2a84-269d-43f4-8890-1d0e65c307a2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for the link @Mike-Honey, I'll make an update for this.

**Comment by mgblythe** [comment]
Sorry for the delay on this. I added similar info to the B2B and purchasing articles, with links out to the Office docs. The specific steps are different in the new admin UI.

Assigning a Power BI Pro license to a guest user within your tenant lets that guest user view content in the tenant. For more information about assigning licenses, see [Assign licenses to users on the Licenses page](https://docs.microsoft.com/office365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-users-on-the-licenses-page). Before assigning Pro licenses to guest users, contact your Microsoft account representative to ensure you're in compliance with the terms of your agreement with Microsoft.

**Comment by Mike-Honey** [comment]
This is such a mess. All I do every day is work on Power BI, yet I am hopelessly lost on this feature and can never get it to work. 

Whoever built it, tested it or signed off on it as a working feature should be deeply ashamed of their work.
