### ISSUE TITLE
clarification, by default all the data from dataflow is stored in Azure  Data Lake storage v2? 

### ISSUE THREAD

**Issue by JulsGranados** [MicrosoftDocs/powerbi-docs#1118]
Hello , in the parragraph
"Data is stored as entities in the Common Data Model in Azure Data Lake Storage Gen2" , i'm confuse because I understand that were two ways in order to use Dataflows , 

- Use dataflows with your own azure datalake storage v2 (integrating the service with azure datalake storage gen2  in the admin Power BI admin portal, with the storage account) 
- Use dataflows without an azure datalake storage v2.

By default Power BI service use an data lake storage V2 , in order to save the dataflows?
my doub comes because in the whitepapers from dataflows didnt say that.

Best regards !!

**Comment by mgblythe** [comment]
Thanks for your comment, @JulsGranados. This issue has been assigned to the doc author for review.

Article: https://docs.microsoft.com/en-us/power-bi/service-dataflows-overview

**Comment by davidiseminger** [comment]
Bringing in other folks who can answer.

**Comment by bensack** [comment]
Hi @JulsGranados, 

Power BI will store dataflows in storage it provides you within the Power BI service. You will be able to access the data stored in Power BI's service, via the Dataflows connector. You have an option to provide your own storage account, if you would like to access the "CDM Folder" created by the dataflow directly in the lake. And, you can still leverage the Dataflows connector to access that data.

The benefit of the latter, providing your own storage account to store Power BI dataflows in, is that you can access the data via Azure Data and AI services or Custom LOB applications/services you may build.

In both cases, dataflows leverage Azure Data Lake Storage accounts.

Thank you,
Ben

**Comment by mgblythe** [comment]
Thanks @bensack, assigning back to @davidiseminger in case we need a doc update.
