### ISSUE TITLE
Config Files

### ISSUE THREAD

**Issue by SheepRock** [MicrosoftDocs/powerbi-docs#1119]
I use the personal mode and I didn't find the files in the given location (C:\Program Files\On-premises data gateway) but I found in "%localappdata%\Microsoft\On-premises data gateway (personal mode)". Has it changed or is it different for personal mode? Also, the file I found was "PersonalGatewayConfigurator.exe.config" instead of "enterprisegatewayconfigurator.exe.config" and "Microsoft.PowerBI.DataMovement.PersonalGateway.exe.config" instead of "Microsoft.PowerBI.EnterpriseGateway.exe.config"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b8b6b4-6aec-cca6-c819-4ea1f40c513b
* Version Independent ID: c9196fdc-12cb-69f3-c6b6-ad6dd95d2abd
* Content: [Configuring proxy settings for the On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-proxy)
* Content Source: [powerbi-docs/service-gateway-proxy.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-proxy.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment @SheepRock. We're redoing the gateway docs, and I'll add this to the list.

**Comment by mgblythe** [comment]
We moved this doc to the generic doc set where we cover the enterprise gateway but not the personal gateway. The [personal gateway article](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode) shows the correct path.
