### ISSUE TITLE
Federated Azure AD workflow does not support OAuth2/Modern Auth

### ISSUE THREAD

**Issue by ryanbooz** [MicrosoftDocs/powerbi-docs#112]
When following the "App Owns Data" sample, we were getting an authorization error on the "AcquireAsyncToken" request because we use federated Azure AD with our internal ADFS SSO server. The request was correctly forwarded to our SSO server, but the request was denied access because we require Modern Authentication with mulit-factor auth.

I can only assume the reason that this workflow isn't supported is because each request to get a token and view the dashboard would/might require a MFA challenge. That said, there is nothing in the documentation or in the Azure AD registered app forms for creating a client application, that suggests federated login isn't possible.

As a workaround, we have created a user simply within our 'onmicrosoft' domain which does not require MFA. This might be a better solution anyway, but does add some further complications for licensing and permissions that we'll have to manage.

If this workflow isn't supported, it should either be made clear here in some way, or provide some documentation for a supported workaround.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#feedback)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ryanbooz  Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by ryanbooz** [comment]
Thanks @markingmyname . We were able to get it to work by calling the token endpoint directly (https://login.microsoftonline.com/common/oauth2/token) with the appropriate parameters as a few others have suggested, which gets the access token. So that might simply be all that needs to be added to the docs and/or example, but worth knowing for .NET Core 2+ apps.

Thanks!

**Comment by markingmyname** [comment]
Thank you again @ryanbooz for the helpful information.

Below is the outcome of the discussions around this topic.

Master users that are unable to pass through federation auth types is not a PBI issue, but more of an AAD restriction. 

1.    We are working on a real and right solution for this – app-only authentication.
2.    Meanwhile, creating a non-federated user (and adapting licenses and permissions) is a valid workaround.
3.    We heard from other customers that a per-app configuration along AAD guidelines could also help to overcome the challenge in some cases – as an alternative to #2. https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-authentication-for-federated-users-portal#enable-direct-authentication-for-legacy-applications

Perhaps the AAD CSS team may have further advice on how noninteractive sign-in can be enabled for ADFS federated tenants (solutions may depend on federation configurations).

As for your suggestion, we will consider adding it to the article.

Thank you again.

**Comment by ryanbooz** [comment]
@markingmyname  I do want to apologize for adding that second comment. I had gotten past the AAD issue with the non-SSO user and then got stuck with the .NET Core 2 authentication issue and got confused when responding.

What I meant to say was that after deciding to implement your option #2 (non-federated user), I ran into further authentication issues with the PowerBI Embedded SDK trying to authenticate because it currently only appears to support .Net 4.6.1.  The authentications section (actually the same method that fails with federated users) isn't supported under .Net Core/Standard 2.1.  Instead, you have to currently call the token endpoint directly.

So, sorry for kind of mixing two related issues.  I think they're both worth some consideration for documentation and appreciate your quick feedback and responses here. Great work!

**Comment by markingmyname** [comment]
@ryanbooz We are aware of the limitations surrounding .Net Core. We are planning to address this limitation with one of the suggested solutions offered earlier with app-only authentication.  

Thank you again for your feedback.
