### ISSUE TITLE
Troubleshooting remark on manually copying oraons.dll applies also to PowerBI Gateway

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/powerbi-docs#1120]
I had the error message returned "Object reference not set" in the PowerBI Gateway when connecting to Oracle and solved it also with the workaround mentioned here by copying the oraons.dll. Maybe you add this advice also here: https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-manage-oracle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @TrutzS ]. This issue has been assigned to the doc author for review..

**Comment by davidiseminger** [comment]
I added that to the article - thanks! Will show up within 24 hours.
