### ISSUE TITLE
share all workspace reports?

### ISSUE THREAD

**Issue by Ccccche** [MicrosoftDocs/powerbi-docs#1121]
Can I share all reports or all dashboards in my workspace with external users instead of sharing a single report or dashboard?  Or how can I share published APP to a user outside our origination?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-dashboards)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Ccccche -- Check out template apps. They may be just what you're looking for. https://docs.microsoft.com/en-us/power-bi/service-template-apps-overview
