### ISSUE TITLE
Report tooltips in custom visuals

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#1122]
The following page (see also the comments at the bottom) suggest that report tooltips can be added to custom visuals:
https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/adding-report-page-tooltips/#applying-report-page-tooltips

Can this be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips#limitations-and-considerations)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello @otravers - as stated in the [Limitations and Considerations](https://docs.microsoft.com/power-bi/desktop-tooltips#limitations-and-considerations) section of the article, custom visuals are not supported.

**Comment by otravers** [comment]
@davidiseminger can you explain what "not supported" means? Because the KPIColumn custom chart from MAQ does work with a report page tooltip (as discussed in the link I posted), I just tested it!

![image](https://user-images.githubusercontent.com/3731532/59222212-f7303e00-8b96-11e9-885a-5bcef8f34be3.png)

**Comment by otravers** [comment]
@davidiseminger there was also this [official release note](https://docs.microsoft.com/en-us/business-applications-release-notes/October18/intelligence-platform/power-bi-custom-visuals/custom-visual-support-report-tooltips) dated 07/21/2018:

> "Custom visuals will support report tooltips in the Power BI Desktop and service."
