### ISSUE TITLE
new feature not documented - 

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/powerbi-docs#1123]
There are two new tick boxes on the permissions tab of the publish APP button 
- Allow all users to connect to the app's underlying datasets using the Build permission
- Allow users to make a copy of the reports in this APP
Neither is documented on this page, even though the "Learn more" link brings you here.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-gb/power-bi/service-create-distribute-apps)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ChipDale66 -- you are so ahead of the curve! Yup, we're updating the docs this AM. Thanks for being alert, and using Power BI!

**Comment by maggiesMSFT** [comment]
OK, @ChipDale66 -- update is live. Thanks for asking!
