### ISSUE TITLE
Relative date filtering not available

### ISSUE THREAD

**Issue by dwightathompson** [MicrosoftDocs/powerbi-docs#1125]
In the new filtering experience, the "Relative date filtering" option is not available. For example, I can no longer filter using "is in the last" x weeks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by Sujata994** [comment]
Can you share a screenshot? In the newest build we see the relative date feature. Are you looking at the pane in edit or read mode?

**Comment by maggiesMSFT** [comment]
Hi, @dwightathompson -- thanks for the question! I've added someone who should be able to comment. I suggest also checking on https://community.powerbi.com/.

**Comment by dwightathompson** [comment]
![image](https://user-images.githubusercontent.com/26628120/59226165-a1a46300-8b8f-11e9-82dd-ca683cf1262a.png)

**Comment by dwightathompson** [comment]
![image](https://user-images.githubusercontent.com/26628120/59226228-c00a5e80-8b8f-11e9-8a1a-10ae3e99d462.png)

**Comment by dwightathompson** [comment]
I am in edit mode.

**Comment by Sujata994** [comment]
Is "Earliest closed_at" a measure?

**Comment by dwightathompson** [comment]
No, it's a Date field.

**Comment by dwightathompson** [comment]
I noticed that I have the relative date option if I use the field as a page filter, but the relative date option is not available when using the field as a visual filter. Again, this is when using the new filter experience that is still in preview.

**Comment by Sujata994** [comment]
Hi Dwight, this appears to be a bug then. Could you share us a link to download the report you are using with that field?

**Comment by dwightathompson** [comment]
https://imaginelearning1-my.sharepoint.com/:u:/g/personal/dwight_thompson_imaginelearning_com/Eevu92sxc7RBrFnSY5TQouwBqe9yn-hS5ox2Yhx7u492EA?e=8Bt88f

**Comment by Sujata994** [comment]
Hi Dwight, we are reviewing the report. What’s happening is when you add a Column in the "Values" drop zone, it becomes a measure. Measures can only be used as advanced filters and the type can’t be changed. If the column is added to the "Columns" drop zone, then you can change the filter types. Let me know if you have further questions. Thanks, Sujata

**Comment by dwightathompson** [comment]
I see. Thank you so much for your help!
