### ISSUE TITLE
How are the bins calculated for the linear regression (numeric values)

### ISSUE THREAD

**Issue by gerachanante** [MicrosoftDocs/powerbi-docs#1126]
I am not completely sure about how are the bins calculated by the ML when analysing numeric key influencers for numeric outputs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @gerachanante . I’ll review this request for inclusion in our docs backlog.

**Comment by juluczni** [comment]
Thanks @gerachanante. I'll update the documentation to explain how the binning works.

**Comment by juluczni** [comment]
#please-close @mgblythe
