### ISSUE TITLE
Data Export from Table Visual

### ISSUE THREAD

**Issue by sarava8304** [MicrosoftDocs/powerbi-docs#1127]
[I have an Model with RLS implemented, the Table visual contains the details of Fact Table to display.
The output in the table looks correct, but when i export this to excel (Summarized) the complete data is shown in the table.
Need immeditae support on this issue]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sarava8304. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
