### ISSUE TITLE
Error:400 (BadRequest)

### ISSUE THREAD

**Issue by Ccccche** [MicrosoftDocs/powerbi-docs#1128]
Follow this tutorial, use the demo APP you provided, set-up everything for the development environment. When I debug it, after I hit embed report on the home page, lead me to a error page saying Response status code does not indicate success: 400 (BadRequest). Use the troubleshooting document but unable to specific this error. Can someone find any reason why this happened?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#application-id)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @Ccccche . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by mgblythe** [comment]
@markingmyname - just checking whether there's info we should add for this or whether @Ccccche should contact support

**Comment by markingmyname** [comment]
@Ccccche/@mgblythe,

My recommendation is to collect a fiddler trace to see where the bad request is coming from first.  Once that is collected, then contact support to see if they can help.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
