### ISSUE TITLE
Descending icon is not shown

### ISSUE THREAD

**Issue by vsevolodts** [MicrosoftDocs/powerbi-docs#113]
When selecting axis values as a sorting option it is not possible to select Descending. The icon is greyed out and when selected the sorting is switching to sorting by values. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Change how a chart is sorted in a Power BI report - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-change-sort)
* Content Source: [powerbi-docs/power-bi-report-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-change-sort.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @vsevolodts ,
Can you send along an example?  I've tried to reproduce your issue and cannot. 
Thanks,
Michele
