### ISSUE TITLE
Vertica Support

### ISSUE THREAD

**Issue by neilgalloway** [MicrosoftDocs/powerbi-docs#1130]
In the table under "List of available data source types", it is missing an entry Vertica.  The Gateway does support it, but it doesn't state if LiveQuery is supported or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#feedback)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @neilgalloway - we'll add this info as part of a gateway docs update we're doing.

**Comment by mgblythe** [comment]
We clarified in the List of available data source types table in https://docs.microsoft.com/power-bi/service-gateway-data-sources. Thanks!
