### ISSUE TITLE
Machine learning explained

### ISSUE THREAD

**Issue by gerachanante** [MicrosoftDocs/powerbi-docs#1131]
Hi, I understand that logistic regression (categories), linear regression (continuous) and decision trees (segments & continuous) ML.NET models are used to calculate the key influencers and segments.

Could you provide an example of the ML part of this calculation. For example, how is the data split between training and test sets, what parameters are used in the models, etc.

I find this visual extremely helpful and it would be extremely powerful to be able to see these things somehow to:
1. Prove that there is a statistics baseline for the analysis
2. Perhaps help to modify the ML parameters
3. Compare more effectively with other ML models run on the same data

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @gerachanante. This issue has been assigned to the doc author for review.

**Comment by juluczni** [comment]
Hi @gerachanante - you can take a look at ML.NETs case study on which methods are used by the key influencers visual. Hope this helps: https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/customers/power-bi

**Comment by juluczni** [comment]
#please-close @mgblythe
