### ISSUE TITLE
AllowAdHocSubscriptions = $false and blocking of Pro Trial signup

### ISSUE THREAD

**Issue by DBojsen** [MicrosoftDocs/powerbi-docs#1134]
Hi 

When you set AllowAdHocSubscriptions = $false to make sure users cannot sign up themselves,
and manually (or dynamically) administer free and pro licenses, it seems to still allow for a free user to signup for a pro trial.
First - you should change that.  There's a reason that a customer choose to disable self service signup.
Second - could you please update the documentation to reflect this, as it is not clearly stated anywhere.

If I am not correct, please correct me ;-)

BR David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up for Power BI as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/service-self-service-signup-for-power-bi#individual-sign-up-has-been-turned-off)
* Content Source: [powerbi-docs/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comments, @DBojsen! I've assigned it to the author to investigate.

**Comment by mgblythe** [comment]
@DBojsen - I'll note this in the docs. If you want to hide the pro trial button, see this [blog post](https://powerbi.microsoft.com/en-us/blog/tailoring-help-and-support-for-power-bi-users/). 

You can also submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). .
