### ISSUE TITLE
PowerBI Instructions

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#1135]
Does PowerBI desktop need to be installed on the Gateway server? I hope not, Please clarify this in the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45b21ee8-e9f9-bf63-78b4-c464f080329d
* Version Independent ID: f3b7c030-9eb5-f5b2-878c-ec9456a1e662
* Content: [Gateway performance monitoring (public preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-performance-monitoring)
* Content Source: [powerbi-docs/service-gateway-performance-monitoring.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-performance-monitoring.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- thanks for your question! I've assigned it to the author to reply. In the meantime, consider checking with the Power BI community, https://community.powerbi.com/

**Comment by mgblythe** [comment]
Hi @DeanGross, there's no requirement to have Desktop installed on the Gateway server.
