### ISSUE TITLE
Site data is no longer up-to-date

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1136]
Hi team, 
I'm moving this from here since the user is requesting an update in the original documentation: https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/18

@thiagollrc commented 18 hours ago
Dear, I am studying PowerBI but the site table "http://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx" does not bring all the columns as this page indicates. I suggest an update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Getting started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc and @thiagollrc -- thanks for your comment! I've assigned it to the author to investigate.

**Comment by ahmad-beshr** [comment]
the data still not updated. is there any plan to either update this training or the data source ?

**Comment by davidiseminger** [comment]
I added a note clarifying that some of the steps might be different if the source data changes over time - we don't own the openly available target data, so it might indeed change, which is part of the adaptable nature of learning. I hope that helps.
