### ISSUE TITLE
Matrix Interaction Buttons

### ISSUE THREAD

**Issue by ferdsjoseph** [MicrosoftDocs/powerbi-docs#1137]
Although the date of this page is 5/28/2019, the buttons shown in screenshots are still from the older version of Power BI.  Please update with screenshots from the newer version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d5bd-51e3-468a-0f7d-a936083f0dc5
* Version Independent ID: 59eea08a-c392-951e-2ba6-860cfcc58281
* Content: [Use the matrix visual in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual#feedback)
* Content Source: [powerbi-docs/visuals/desktop-matrix-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-matrix-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @ferdsjoseph -- you are so right! When the product changes as much as it did this time, we have many, many screen shots to update. We try to get to them expeditiously. I'm assigning your comment to the author, who is I'm sure already aware of the update.
Thanks for your attentive reading, and for using Power BI!

**Comment by mihart** [comment]
Hi @ferdsjoseph ,
Thank you for your feedback.  The matrix article is being updated this week, so look for the fresh new screenshots no later than next week.

**Comment by ferdsjoseph** [comment]
Thank you!
