### ISSUE TITLE
Update Troubleshooting steps to include limitation

### ISSUE THREAD

**Issue by amanarneja** [MicrosoftDocs/powerbi-docs#1138]
There currently seems to be a limitation that you cannot use a URL that is not @.uservoice.com i.e. if my company has a URL feedback.abc.com which UserVoice allows, it cannot be connected using this content pack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9e7f81-23c2-cd15-a266-77871ba9d8a2
* Version Independent ID: 540ee6c3-31b4-5c35-b4fa-eee36e258c09
* Content: [Connect to UserVoice with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-uservoice)
* Content Source: [powerbi-docs/service-connect-to-uservoice.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-uservoice.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @amanarneja -- thanks for your question! I've assigned it to the author to investigate.

**Comment by robertburron** [comment]
Hi there, I am currently experiencing the same issue. Are there any updates that you are able to provide?

**Comment by mgblythe** [comment]
Closing b/c this content pack will be deprecated on Sept. 25.
