### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#1139]
It's unclear where to put the theming commands - do these go in the page section? is this a visual style? More clarity in this documentation would be very helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview#feedback)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @klinejordan -- thanks for the question! I'm including @Sujata994 for help with the answer.

**Comment by Sujata994** [comment]
Hi Kline, you are correct. It goes in the page section. Let me know if you have further questions.
