### ISSUE TITLE
Composite is spelled wrong

### ISSUE THREAD

**Issue by aldupler** [MicrosoftDocs/powerbi-docs#114]
Composite is spelled wrong in the first sentence of the section "Setting Storage Mode". :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use Composite Models in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models#setting-storage-mode)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Good catch, @aldupler! We add those mistakes on purpose just to see if anyone's paying attention... NOT! I'll let @davidiseminger know. Thanks!

**Comment by davidiseminger** [comment]
@aldupler - thanks for the close read! Had an extra n in there, it somehow snuck in. Fixed it, and it'll be updated within a day or so. Thanks!
