### ISSUE TITLE
Page refers to options that are not provided by the product

### ISSUE THREAD

**Issue by eldang** [MicrosoftDocs/powerbi-docs#1140]
There is no "Color saturation" well available, either in the Power BI web service or the current desktop client (Version: 2.69.5467.2151 64-bit (May, 2019))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47d7082-17fb-3b37-de23-020f49991e0c
* Version Independent ID: 4d904a62-6e2e-b05f-b222-2500df079b76
* Content: [Filled Maps (Choropleths) in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-filled-maps-choropleths#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @eldang -- thanks for your question! I've assigned it to the author to investigate.

**Comment by mihart** [comment]
Hi @eldang,
Thank you for your feedback.  Yes, the color saturation is now part of the Formatting pane.  I'm updating the article now so it should go live no later than next week.

**Comment by eldang** [comment]
@mihart but there's no color saturation option under formatting either!  As far as I can tell, there's currently no way to do a choropleth map with a continuous colour scale (as opposed to categories), which seems like kind of a basic need for an analytics package, and it's frustrating when the docs show examples.  Or have I missed something that is available somewhere?

**Comment by mihart** [comment]
Hi @eldang 
Under the Format tab, expand "Data colors".  Then select the 3 dots and choose "Conditional formatting".  In the pane that appears, add the field you'd like to use for saturation.  
I'm adding this to the doc today because it is rather hard to find.
