### ISSUE TITLE
If you have SQL Server Enterprise under MPSA how to find Power BI Report server key?

### ISSUE THREAD

**Issue by xantari** [MicrosoftDocs/powerbi-docs#1141]
This page assumes you use volume licensing service center. However MPSA is different portal located here: https://businessaccount.microsoft.com/Customer/Entitlements/

So when you have it under MPSA, how do you find it? It is not in Business Center.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4600c4b7-8444-f0d4-9e81-25882a951d22
* Version Independent ID: 68e1a06b-69f7-8fc9-cfb9-8e4956580fab
* Content: [How to find your report server product key - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/find-product-key#feedback)
* Content Source: [powerbi-docs/report-server/find-product-key.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/find-product-key.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @xantari -- Thanks for asking! I'm checking and will get back to you with the answer.

**Comment by cmfinlan** [comment]
You need to have SA to take advantage of this benefit - since MPSA allows you to not have SA, it isn't available through that portal.

**Comment by xantari** [comment]
@cmfinlan We still have SA under MPSA. The only difference is that when we pay yearly everything gets synced to the same renewal date so we aren't paying for our products under SA many times throughout the year. Makes budgeting and paying much easier. We had about a dozen volume licensing agreements under the open business plan and we were creating PO's for the renewals almost every month!

**Comment by xantari** [comment]
@cmfinlan FYI, you can confirm yourself, software assurance is available under MPSA as indicated in their FAQ of MPSA: https://www.microsoft.com/en-us/licensing/mpsa/default

**Comment by cmfinlan** [comment]
I understand it is still available, it's more around the frequency of renewals made some things a challenge at the time this was implemented IIRC.  I'll follow up with business planning to see if they can make a change there going forward to make it available - if you work with a Microsoft rep directly, they should be able to assist as well.

**Comment by xantari** [comment]
@cmfinlan We work with CDW, not sure if we have a MS Rep assigned to us? How would I know? Any idea how to get the license key from MPSA Business Center? Even though we spent 15k / year on SQL Server Enterprise licensing, and we can see it in MPSA Business Center, we are unable to get Power BI Report Server. Searching for "power" yields no results:

![image](https://user-images.githubusercontent.com/6610039/60202327-f55db000-980f-11e9-8feb-0d2c4085023e.png)

**Comment by maggiesMSFT** [comment]
Hi, @xantari -- hope you've figured this out by now. If not, please enter a support ticket at https://powerbi.microsoft.com/en-us/support/
They can help investigate.
Thanks!

**Comment by chris-schulz** [comment]
Im having the same issue. The page here: https://docs.microsoft.com/en-us/power-bi/report-server/find-product-key is wrong as the SQL EE SA product no longer lists the key. :-\ This is poorly managed for SA users.

**Comment by xantari** [comment]
Yeah I never got the key. It seems when you buy SQL Enterprise via MPSA you do not get it! We have SA on our license and everything. Once we transitioned from volume licensing (open business) to MPSA it no longer shows key for Power BI Report Server :(
