### ISSUE TITLE
mr.hkm

### ISSUE THREAD

**Issue by omarman2** [MicrosoftDocs/powerbi-docs#1142]
omarman_2006a@hotmail.com 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up for Power BI as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/service-self-service-signup-for-power-bi?lc=11265#feedback)
* Content Source: [powerbi-docs/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @omarman2 -- I'm closing this issue because it doesn't contain a comment or question. If you have a comment or question, please start a new issue. Thanks!
