### ISSUE TITLE
In requirements, add dependency on .Net 4.6 for Power BI Desktop

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1143]
This visual breaks down in Power BI Desktop if .Net 4.6 is not installed on the machine.  

The visual appears blank with a message: This visual is not enabled.  The File / Options ... Preview list does not show an option to check the Key influencers visual.

Ref:
https://community.powerbi.com/t5/Desktop/Key-Influencer-Visual-not-visible/m-p/694499#M335024

https://www.microsoft.com/en-us/download/details.aspx?id=53344

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- thanks for your feedback! I've assigned it to the author, who will review and get back to you.

**Comment by juluczni** [comment]
Hi Mike,

Thanks for the message. The visualization is dependent on ML.NET which requires .Net 4.6. I will add that to the documentation to make the requirement clear.

Thanks!

**Comment by Mike-Honey** [comment]
Hi Justyna,

A pop-up message from the Power BI Desktop app to explain this dependency would also be helpful.  Currently its very obscure - the visual just doesn't appear in the list.

Thanks

**Comment by juluczni** [comment]
#please-close @mgblythe
