### ISSUE TITLE
Relative Date Filtering for both future and past dates

### ISSUE THREAD

**Issue by DerekTrujillo** [MicrosoftDocs/powerbi-docs#1145]
I understand relative date filtering, but want to apply it as an 'or' with future dates to create a dynamic date range filter.  For example.  If there was a report that showed both forecast and actuals in the same report you might want to show the past 5 years and also show the next 5 years (Date is in the last 5 years including today or is in the next 5 years not including today) to have a rolling 10 year window for the report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range#feedback)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @DerekTrujillo . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
