### ISSUE TITLE
Using RLS with CustomData(), over Gateway, to on-prem SSAS is can work

### ISSUE THREAD

**Issue by mitchonfire** [MicrosoftDocs/powerbi-docs#1146]
Using RLS with CustomData(), over Gateway, to on-prem SSAS is can work by making the gateway do "AD Account switching".

See workaround here:

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/17768485-ssas-gateway-data-source-customdata-setting-is-bro 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @mitchonfire . This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
@mitchonfire,

Thank you for your feedback! We will investigate and get back to you with the relevant info.

@rkarlin for awareness.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @MicrosoftDocs, thanks for pointing this out! As this is not a documentation question I'm closing the case.
