### ISSUE TITLE
A way to use CustomData() for RLS over Gateway against on-prem SSAS Roles

### ISSUE THREAD

**Issue by mitchonfire** [MicrosoftDocs/powerbi-docs#1147]
I want raise awareness around this issue and to share my work around which uses the ADUserNameReplacementProperty gateway setting to switch from the admin AD account so that role filters will be applied, i.e.

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/17768485-ssas-gateway-data-source-customdata-setting-is-bro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshooting the On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot)
* Content Source: [powerbi-docs/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @mitchonfire . This issue has been assigned to the doc author for review.

**Comment by arthiriyer** [comment]
@mitchonfire - can you please provide more information on the work you are referring to? 
Unfortunately the idea seems to no longer exist so I am not able to view that.

**Comment by mitchonfire** [comment]
> @mitchonfire - can you please provide more information on the work you are referring to?
> Unfortunately the idea seems to no longer exist so I am not able to view that.

Hi @arthiriyer, the idea and my workaround seems to have vanished off ideas.powerbi.com, oh well.

Try follow this diagram for the workaround:
![RLS_OnPremSSASLive_CustomData_2ADAccounts]
(https://user-images.githubusercontent.com/17173734/65003196-bc2e6b00-d93a-11e9-9ead-b90a2d6ece1b.jpg)

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
