### ISSUE TITLE
Wrong direction of arrow in picture for customer embedding

### ISSUE THREAD

**Issue by laandermsft** [MicrosoftDocs/powerbi-docs#1148]
I read this documentation and I may be wrong, but the arrow next to "Acquire embed token" is pointing in the wrong direction. As far as I know the acquired embed tokens should be sent from Power BI to the ISV application. Correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7d9793-ede4-653a-bc25-cf91be807edb
* Version Independent ID: bb12e45c-9aaa-97b2-cfc7-31e1c511fd00
* Content: [Embedded analytics with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedding#feedback)
* Content Source: [powerbi-docs/developer/embedding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedding.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @laandermsft . This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Hi, laandermsft,

The image is correct.

The application needs to generate the token and send that request to PBI, so PBI can verify access to the data.

However, is the image seems confusing, we can take a look at that.

thank you.

@rkarlin for awareness.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
