### ISSUE TITLE
Issues since recent update appearing to be linked to COMPOSITE

### ISSUE THREAD

**Issue by cjmuldoon** [MicrosoftDocs/powerbi-docs#115]
Since this update I have had to re-publish all of my reports using DirectQuery otherwise no data is presented from the models. I'm also hitting an error with a couple reports that say I can't publish it because it's using COMPOSITE, when it says it's actually using DirectQuery and no changes were made since last publishing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use Composite Models in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-au/power-bi/desktop-composite-models)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @cjmuldoon -- Sorry to hear it. Sounds more like a product issue than a docs issue. I recommend checking on https://community.powerbi.com/ to see if others are reporting similar issues. Thanks!
