### ISSUE TITLE
Does Android app support it now?

### ISSUE THREAD

**Issue by angiwang** [MicrosoftDocs/powerbi-docs#1150]
The article write in 06/07/2018 and Note: Viewing Power BI Reports hosted in Power BI Report Server using WAP to authenticate is currently supported only in iOS app. Android app is not officially supported at this time.

Does Android app support it now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e74357ec-d4ac-973f-64ca-f8f4ca4e431a
* Version Independent ID: 0e59b701-0c57-6b4d-40bd-5f5f2734cf96
* Content: [Using OAuth to connect to Power BI Report Server and SSRS - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-oauth-ssrs#feedback)
* Content Source: [powerbi-docs/consumer/mobile/mobile-oauth-ssrs.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-oauth-ssrs.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @angiwang -- thanks for your question! Assigning this to someone who can answer. Thanks!

**Comment by mshenhav** [comment]
Hey @angiwang, 

Starting from 112683 app update, it is also supported in Android.

Maya

**Comment by angiwang** [comment]
Great! Thank you so much!
