### ISSUE TITLE
PowerBI Premium Dedicated Capacity vs PowerBI Embedded Dedicated Capacity

### ISSUE THREAD

**Issue by alpinedelight** [MicrosoftDocs/powerbi-docs#1151]
In the section "Moving to production" it states that dedicated capacity is required and can be purchased from Azure portal.
It would help to clarify the difference with PowerBI Premium which offers dedicated capacity, or are they in fact the same (https://powerbi.microsoft.com/en-us/pricing/)?
If my organisation is already paying for Premium, can they use that capacity to embed PowerBI content within their apps?  Unclear from reading this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#move-to-production)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @alpinedelight. This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Hi alpinedelight,

thank you for your comment.

A SKUs can only be purchased in Azure, therefore specifying Embedded vs. Premium is not truly needed here. 

However, I understand where you are coming from with this info.

Thank you.

@rkarlin for awareness.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
