### ISSUE TITLE
Article insinuates two App registrations - is this correct?

### ISSUE THREAD

**Issue by alpinedelight** [MicrosoftDocs/powerbi-docs#1152]
Entering the details in web.config when setting up the "App Owns" sample, the article states how to get the app id (https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#application-id) highlighting the "PBI Embed Test" app registration. Slightly further down it then talks about getting the application secret (https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#application-id), but now using "New_App_Reg_SP". Unclear from the article why you would use app id from one app-registration, and app-secret from another? Am I misunderstanding something, or is this a mistake?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#application-secret)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @alpinedelight. This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Hi alpinedelight,

If I understand correctly, you are referring to understanding why using app id and app secret?

I can say the article discusses using a UN/PW for auth vs using Service Principal for auth.

The article tries to give you different options of how to authenticate your application.

In both cases, an app id is required, but you only need to use the app secret when using Service Principal for authentication.

Hope that helps.

Thank you.

@rkarlin for awareness.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
