### ISSUE TITLE
Download PowerBI Excel Publisher

### ISSUE THREAD

**Issue by adojeda** [MicrosoftDocs/powerbi-docs#1153]
Link to download PowerBI Excel publisher takes you to documentation to PowerBI Analyze in Excel. Should the link to download the PowerBI Excel publisher take you to:
https://www.microsoft.com/en-us/download/details.aspx?id=50729 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Using Power BI publisher for Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel#feedback)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
You're right - that link needed updating! Thanks for pointing it out, fixed, will show up within 24 hours.
