### ISSUE TITLE
Stale links

### ISSUE THREAD

**Issue by miroslavplese** [MicrosoftDocs/powerbi-docs#1154]
Links in Next Steps section are stale or non-existent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8e549-7fba-9ece-3e32-73a0cc3c6046
* Version Independent ID: a9b39810-c302-c153-3123-ddb8f459e9f4
* Content: [Add a custom column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-add-custom-column#feedback)
* Content Source: [powerbi-docs/desktop-add-custom-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-add-custom-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @miroslavplese. This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
@miroslavplese - I removed one of the links and changed the other to the top level of the reference: https://docs.microsoft.com/powerquery-m/power-query-m-reference. This will be live later today.

**Comment by mgblythe** [comment]
Fix is now live.
