### ISSUE TITLE
Cross Report Filter not working as expected

### ISSUE THREAD

**Issue by Krishna-Paudel** [MicrosoftDocs/powerbi-docs#1155]
We want to implement Cross Report Drillthrough across few Power BI reports. However, we are unable to proceed with this due to a potential bug in the Power BI Service. 

**Details**: Scenario: Drillthrough the Account ABC from Source Page to Target Page 

**Expected Behavior**: Drillthrough filter is passed with the value ABC and the Target Page is filtered for this account. 

**Actual Behavior**: On drilling through, the filter is passed as expected, however, the Target Page does not get filtered unless User hits "Refresh" button. 

**Impact**: Unable to build reports with Cross Report Drillthrough functionality. 

Many other users are facing the exact same issue. I have logged an issue in Power BI forum as well. 
[https://community.powerbi.com/t5/Issues/Drill-through-to-another-Report-Cross-Report-Not-Working/idc-p/718201](url)

**Comment by mgblythe** [comment]
Thanks for your comment, @Krishna-Paudel. This looks like product feedback, rather than documentation feedback. It looks like you've logged the issue. You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
