### ISSUE TITLE
No mention of Imports via SSO through an Enterprise Data Gateway

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1156]
No mention of Imports via SSO through an Enterprise Data Gateway. Is that coming? Soon? Currently imports only work via Personal Data Gateways using windows credentials. Keep in mind we only allow SSO, so direct DB passwords won't work for us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7ca8d8-0f83-2cd6-57b1-04fc8e04981b
* Version Independent ID: 196ee3c3-aa88-f8ca-c725-33bf77be0db5
* Content: [Use SAML for single sign-on (SSO) to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-saml)
* Content Source: [powerbi-docs/service-gateway-sso-saml.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sso-saml.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your question @pcgeekus. Adding @arthiriyer to comment.

**Comment by arthiriyer** [comment]
@pcgeekus Currently SSO is available for DQ. We may consider it for the upcoming semester starting October- please upvote at ideas.PowerBI.com so ew can prioritize.

**Comment by mgblythe** [comment]
Thanks @arthiriyer, closing this out.

**Comment by pcgeekus** [comment]
I think product development is already working on it, please check and let
me know
