### ISSUE TITLE
No mention of Imports via SSO through an Enterprise Data Gateway

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1157]
No info on Imports via SSO through an Enterprise Data Gateway. Is that coming? Soon? Currently imports only work via Personal Data Gateways using windows credentials. Keep in mind we only allow SSO, so direct DB passwords won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60da74f1-d9a3-c9b2-da26-344333edeefe
* Version Independent ID: a65e9394-3d26-bbb7-e6bd-6a575c37cb07
* Content: [Manage your SAP HANA data source - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-sap)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-sap.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-enterprise-manage-sap.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for the comment @pcgeekus, closing as a dup of #1156.
