### ISSUE TITLE
Please add licensing requirements for the different mode

### ISSUE THREAD

**Issue by minyos** [MicrosoftDocs/powerbi-docs#1158]
hi, can you please include licensing information so we are aware which types of licensing requirements are required for the different methods of refreshing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data#feedback)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment @minyos, I'm checking if there are any licensing restrictions/implications I should add to the article.

**Comment by mgblythe** [comment]
@minyos - this is the only licensing-related difference, which is documented:

Power BI limits datasets on shared capacity to eight daily refreshes. If the dataset resides on a Premium capacity, you can perform up to 48 refreshes per day.
