### ISSUE TITLE
Article needs updating

### ISSUE THREAD

**Issue by sslezic** [MicrosoftDocs/powerbi-docs#1159]
Most of the information in this article is out of date. The tools and wizards used in this article have all been updated according to:
https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI Custom Visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by maggiesMSFT** [comment]
Thanks, @sslezic! Assigning to the author to address the issue.

**Comment by JamesHamilMSFT** [comment]
Can I bump this? I need this as well.

**Comment by djohansen01** [comment]
Thanks for posting the update!

**Comment by voidrealm** [comment]
Please update, this article is not useful with the latest version of your tools.

**Comment by anusiner92** [comment]
Please update this article. I need this information as well

**Comment by Sheriseology** [comment]
Yes, please update.

**Comment by Sheriseology** [comment]
Or at least leave a note and link at the top to let readers know that they need to see the update documentation (https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/) in order to get this to work with the latest version

**Comment by zBritva** [comment]
Article was updated

**Comment by KesemSharabi** [comment]
Thanks @sslezic, @JameshMSFT, @djohansen01, @voidrealm and @Sheriseology.

Now that the article was updated, I'm closing this case.
