### ISSUE TITLE
Instructions for updating are dangerously false

### ISSUE THREAD

**Issue by cpcodes** [MicrosoftDocs/powerbi-docs#116]
The instructions state: "Note that updating the On-premises data gateway is achieved by reinstalling the gateway, as described in this section. When updating the gateway (by reinstalling), your existing gateways settings are retained."

Attempting to install over an existing installation results in the installer failing with the instruction that "The on-premises data gateway installation has failed. It looks like you are trying to reinstall. Please uninstall the current version first." So far so good - reinstalling requires uninstalling. So I did this.

When I ran the installer again, it did a fresh install, and required me to enter all settings from scratch - it did not retain my existing gateway settings. I was given the option to "Migrate, restore, or takeover and existing gateway", but this requires a Recovery key that I have no means of obtaining.

In short, following these instructions effectively deleted my existing gateway and all settings with it. Previously, running the installer would detect the previous install of the gateway and instead of asking for it to be deleted, would proceed to update it instead. Can we revert to this functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @cpcodes -- Thanks for the feedback! The author for this article, @mgblythe, is currently away. He'll review your feedback when he returns. Thanks!

**Comment by mgblythe** [comment]
Thanks @cpcodes, checking with engineering on the behavior change as well as the steps update.

**Comment by arthiriyer** [comment]
Hi @cpcodes -This specific error occurs only when you try to reinstall the same version you have already. You will get a variation of this error when you try to install a lower version than the one you have currently. In these cases unfortunately you will have to reinstall and not be able to update - in which case you lose your existing settings.

FYI @mgblythe

**Comment by mgblythe** [comment]
@cpcodes -- updating the content with the following information:

Note that you update the On-premises data gateway by installing the gateway again, as described in this section. As long as you install a newer version of the gateway, your existing settings are retained. If you install the same version, it treats this as a complete reinstall, and your settings are not retained.

Feel free to reopen this issue if necessary.
