### ISSUE TITLE
Bad link or functionality removed

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1160]
@ldeoux commented on [Thu Jun 20 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/12)
Hello
The links to the Power BI Publisher for Excel module download refer to the Excel Analyzer page ...
Excel Analyzer makes it possible to analyze give PowerBI in Excel ... it's not what I want ... I want to display an Excel Dashboard in PowerBI ...
This function is no longer valid or is this the link that is simply invalid?
thank you for your comeback
cordially

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Utiliser Power BI Publisher pour Excel - Power BI](https://docs.microsoft.com/fr-fr/power-bi/publisher-for-excel#feedback)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user reports the current funcionality differs from what it says the article.

**Comment by maggiesMSFT** [comment]
Hi, @ldeoux Perhaps this is the functionality you're looking for? 
https://docs.microsoft.com/en-us/power-bi/publisher-for-excel
Or https://docs.microsoft.com/fr-fr/power-bi/publisher-for-excel in French

cc @CeciAc

**Comment by ldeoux** [comment]
Hello Maggie

Thank you to follow the case.
You're right sending me the link for Publisher-for-Excel in french… but when I follow this Link… and when I choose this other Link in the new opened page : Télécharger Power BI Publisher for Excel<http://go.microsoft.com/fwlink/?LinkId=715729>,  to download the component…
I'm redirected on the Excel Analyser service page… it's impossible to download the component right now

That is the Reason why I create the case with my comments on GitHub.
I wondered wether the component Publisher-for-Excel  is still available or if its just a link error.

Read you soon

Laurent
________________________________
De : Maggie Sparkman <notifications@github.com>
Envoyé : jeudi 20 juin 2019 22:46
À : MicrosoftDocs/powerbi-docs
Cc : ldeoux; Mention
Objet : Re: [MicrosoftDocs/powerbi-docs] Bad link or functionality removed (#1160)


Hi, @ldeoux<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fldeoux&data=02%7C01%7C%7Caace2b1fc4f94ef6917208d6f5c06178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636966603941648356&sdata=ZK5boLfAUYNxRXrYRagLWoDRlJ5mCyHgZvp7WBnhDhU%3D&reserved=0> Perhaps this is the functionality you're looking for?
https://docs.microsoft.com/en-us/power-bi/publisher-for-excel<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-bi%2Fpublisher-for-excel&data=02%7C01%7C%7Caace2b1fc4f94ef6917208d6f5c06178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636966603941658373&sdata=anXSYttuaQJGQuFqrerlNAQ2vhCcS7ZC3JwQzPJQ4TA%3D&reserved=0>
Or https://docs.microsoft.com/fr-fr/power-bi/publisher-for-excel<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Ffr-fr%2Fpower-bi%2Fpublisher-for-excel&data=02%7C01%7C%7Caace2b1fc4f94ef6917208d6f5c06178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636966603941668378&sdata=LCHTWsjEGKHSNNY1vayptJ2pVF0y9q4HydsY%2BOqbmpM%3D&reserved=0> in French

cc @CeciAc<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCeciAc&data=02%7C01%7C%7Caace2b1fc4f94ef6917208d6f5c06178%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636966603941678389&sdata=hX5xvlgGYkJy0FZkOOPvhLmr9kXtYqCyaUW52TzsscM%3D&reserved=0>

**Comment by cymbolz** [comment]
I posted to the PBI Community about this and the response was quite underwhelming. 

So I logged a support ticket.  After spending far too much time demonstrating the issue to them (which anyone with reasonable comprehension could see from the documentation and following the links) I was advised to try the now un-documented link to the separate Publisher for Excel installer.

The issue is still with the product team to figure out what they want from all of this.  It's difficult to understand who / how the documentation has been updated in this way, how the link was removed from the Power BI Service site, yet the installer is still stand-alone rather than, as the doco suggests, incorporated in the Analyze in Excel installer.

For all the good things MS are doing with Power BI, it would take a lot of effort to screw up something as simple as this.

**Comment by ldeoux** [comment]
Hello Matthew
Sorry you spent So much time...
Would  you please send me the non documented link you mentioned ?
Thand you in advance

________________________________

**Comment by cymbolz** [comment]
@ldeoux This is the page on Publisher for Excel: https://docs.microsoft.com/en-us/power-bi/publisher-for-excel

**Comment by ldeoux** [comment]
Hello Mathew…
I’m afraid but I have the sensation to go around in circles again !
I would like to download the “power bi publisher for excel” module… the link you sent to me still drive me to the “Excel analyser” module when I choose to download the link “power bi publisher for excel”…

I hope this module still exist

Thank you
Best regards
Laurent


De : Matthew Cymbalak <notifications@github.com>
Envoyé : vendredi 28 juin 2019 04:44
À : MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc : ldeoux <ldeoux@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/powerbi-docs] Bad link or functionality removed (#1160)


@ldeoux<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fldeoux&data=02%7C01%7C%7C80c10a10945349cedace08d6fb726cf7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636972866198969147&sdata=eqqZyhM%2BgEB4lsCrn3tFn8N1SSpGMDLDEGKO07xzb6U%3D&reserved=0> This is the page on Publisher for Excel: https://docs.microsoft.com/en-us/power-bi/publisher-for-excel<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpower-bi%2Fpublisher-for-excel&data=02%7C01%7C%7C80c10a10945349cedace08d6fb726cf7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636972866198979152&sdata=Oc7dyCSf6rutTSPbWrbpGMCebS62M%2FIQHIhqxuVJTn4%3D&reserved=0>

**Comment by adojeda** [comment]
This is the same issue I posted under Download PowerBI Excel Publisher. What’s the correct link to download?

**Comment by cymbolz** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=50729
@ldeoux @adojeda

**Comment by davidiseminger** [comment]
I've updated the link to Publisher for Excel, and made sure the link is pointing to a download page.

**Comment by ldeoux** [comment]
👍

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by cymbolz** [comment]
@davidiseminger The link still directs to the Analyze in Excel page
