### ISSUE TITLE
Firewall Settings

### ISSUE THREAD

**Issue by RealNoArms** [MicrosoftDocs/powerbi-docs#1162]
How do we set PowerBI as a trusted service, or which IP range should we permit through the firewall?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126A
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @RealNoArms -- thanks for your question! Assigning to the author to get back to you.

**Comment by davidiseminger** [comment]
Thanks for your comment, @RealNoArms . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by DaveRuijter** [comment]
I hope I can reopen this issue? This is actually a legit question that should be addressed on this documentation page.
"How do we set Power BI as a trusted service, or which IP range should we permit through the firewall?"
