### ISSUE TITLE
The method of describing how to connect to a HANA server (type in ServerXYZ:30015) is out of date

### ISSUE THREAD

**Issue by AdamBJ** [MicrosoftDocs/powerbi-docs#1163]
The connection UI has been updated to use a port dropdown

**Comment by maggiesMSFT** [comment]
Hi, @AdamBJ -- thanks for your observation. Is this the article you're referring to? 
https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana
Assigning to that author on that assumption.

**Comment by davidiseminger** [comment]
Thanks! I've removed the dated screen and updated instructions.
