### ISSUE TITLE
Specific Instructions on Creating Custom Visuals that Work on Report Server

### ISSUE THREAD

**Issue by sjlarkin** [MicrosoftDocs/powerbi-docs#1164]
There are no instructions on how custom visuals can be created so that they work on PBI Report Server. Really need to add this because not all the Marketplace custom visuals work on PBIRS, and we are having trouble creating one.

**Comment by maggiesMSFT** [comment]
Hi, @sjlarkin Thanks for your comment. Assigning to someone familiar with custom visuals, to help.

**Comment by uve** [comment]
Custom Visuals don't require any changes for PBI Report Server.
@sjlarkin, Could you please send a list of visuals which don't work in PBI RS?

**Comment by sjlarkin** [comment]
@uve, R visualizations do not work on PBIRS. Beyond that, I don't have a list, but asked Microsoft to mark the custom visualizations that either work or don't work on Report Server. Crickets. 

We have had to do it by trial and error. Use a visualization with a very simple dataset, upload to PBIRS, and see if it works. 

If you add the idea to the ideas page, and get some response, can you post it here on this thread?

**Comment by sjlarkin** [comment]
All, I've added a new idea to ideas.powerbi.com. Please vote it up:
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/39855259-mark-custom-visualizations-that-work-with-power-bi.

Sorry you have to copy and paste. I'm using IE11, and probably should be using Chrome.

**Comment by kfollis** [comment]
@sjlarkin - Thank you for submitting feedback on our documentation. Since this comment is not against a specific article and the you've posted to ideas, we'll now close this issue. If your feedback isn't addressed, please feel free to submit additional feedback for a particular page.
