### ISSUE TITLE
Field icon list incomplete.

### ISSUE THREAD

**Issue by carlhodder** [MicrosoftDocs/powerbi-docs#1168]
I've got icons appearing in the field list, on a field I'm having issues with power BI embedded. The icon isn't listed here, and I can't find an authoritative list on these anywhere else.

Isn't it about time to update this to include all icons used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd081c3-9f0f-07b5-b0dd-4270ddc2232f
* Version Independent ID: 8d92a854-ddff-3c3e-c044-a2d06e68f55c
* Content: [Tour the report editor - Power BI](https://docs.microsoft.com/en-us/power-bi/service-the-report-editor-take-a-tour#feedback)
* Content Source: [powerbi-docs/service-the-report-editor-take-a-tour.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-the-report-editor-take-a-tour.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @carlhodder -- Thanks for the feedback. Could you attach a screen shot of the icon? I can do some sleuthing.

**Comment by carlhodder** [comment]
Thank you very much!

I'm about 90% confident that this is due to the field being grouped:
![GroupNew](https://user-images.githubusercontent.com/39107659/59889261-b4d0f180-941f-11e9-9c36-d49e70fd43c4.PNG)

However from memory I thought the grouped icon was this:
![GroupOld](https://user-images.githubusercontent.com/39107659/59889274-c2867700-941f-11e9-8d9a-efe468e329b3.PNG)

Anyway, the first icon is the one I'm confused with.

Thanks!
-Carl

**Comment by maggiesMSFT** [comment]
Thanks, @carlhodder -- I'm checking.

**Comment by hugotoledo** [comment]
Seconding Carl's points. The June 2019 update's icons are not reflected here. The Hierarchy icon is certainly wrong.

**Comment by maggiesMSFT** [comment]
Yes, @carlhodder, you're right, that's the grouping icon. @hugotoledo, the hierarchy icon looks the same to    me, though the color scheme is reversed. 
At any rate, I need to update the article.
thanks!

**Comment by maggiesMSFT** [comment]
OK, @carlhodder and @hugotoledo, article is updated and live. Thanks for the questions!
