### ISSUE TITLE
List of shortcuts in Accessibility In PowerBi article is a screenshot

### ISSUE THREAD

**Issue by ferBonnin** [MicrosoftDocs/powerbi-docs#1169]
Instead of a screenshot of the list of shortcuts, would be nice to have an actual table with the list of shortcuts in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd07909e-f46b-a054-3e58-0a5e7db25d19
* Version Independent ID: 49e245ff-9702-969e-0086-76cf4f86af66
* Content: [Accessibility in Power BI Desktop reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-accessibility#consuming-a-power-bi-desktop-report-with-a-keyboard-or-screen-reader)
* Content Source: [powerbi-docs/desktop-accessibility.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-accessibility.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @ferBonnin. This issue has been assigned to the doc author for review.

**Comment by PHATLXIV** [comment]
@ferBonnin: If you are referring to the image in the "Consuming a Power BI Desktop report with a keyboard or screen reader" section of the article, this is not a bug or issue that needs to be fixed. The image is an example of what users would see when pressing the specified hotkey to open that window. Also, the image has proper alt text. This issue should be closed as 'Won't fix'.

**Comment by ferBonnin** [comment]
I somehow missed the list of the hotkeys in the article. Closing since that answers the ask of this issues.
