### ISSUE TITLE
Old link to SAP in 'Installation of Implementation 2.0 SAP Connector'

### ISSUE THREAD

**Issue by patrickgans** [MicrosoftDocs/powerbi-docs#117]
The new link should be:
https://support.sap.com/en/product/connectors/msnet.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP BW Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-bw-connector)
* Content Source: [powerbi-docs/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-bw-connector.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great! Thanks for the update @patrickgans - I've updated the link, the change should show up in a day or so.
