### ISSUE TITLE
Button properties when selected is removed?

### ISSUE THREAD

**Issue by AciongAksaya** [MicrosoftDocs/powerbi-docs#1170]
I am on June update and I only see default state, on hover, on press.
My goal is to highlight the bookmark when selected also not just on hover.
Thanks...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c379d7f1-f977-7906-c4ba-6f58ab47d785
* Version Independent ID: 088a4f2c-e571-1282-b265-9b90d4995505
* Content: [Using buttons in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-buttons#feedback)
* Content Source: [powerbi-docs/desktop-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-buttons.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @AciongAksaya. This issue has been assigned to the doc author for review. In the meantime, is the issue that the feature isn't acting as documented or that you're looking for additional functionality?

**Comment by davidiseminger** [comment]
Hello @AciongAksaya  - I believe what you're looking to do is available in the recent releases of Power BI Desktop.
