### ISSUE TITLE
Columns argument

### ISSUE THREAD

**Issue by RonaiBertalan** [MicrosoftDocs/powerbi-docs#1171]
This page should mention that importing a csv file generates a 'columns=10' (10 is just an example for a number here) argument in power query and if your csv file at the next time of refresh contains more columns, those won't be refreshed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc9321af-e669-2f8b-b362-e23ccaa45b35
* Version Independent ID: 6bd31c55-cfc7-0f22-139f-1b2c690a5784
* Content: [Connect to CSV files in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-csv#feedback)
* Content Source: [powerbi-docs/desktop-connect-csv.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-csv.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for the help! I've added a note to that in the article, will show up within 24 hours.
