### ISSUE TITLE
CustomData

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#1172]
In the window "Map user names" there is a choice between "Effective user names" and "CustomData". This choice is nowhere described and the latter is not even mentioned in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa43934-b1b5-2227-9f9e-cfce1801b659
* Version Independent ID: 0d169b19-7c1c-b37d-3915-b8c55da6f0ff
* Content: [Manage your data source - Analysis Services - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-ssas#feedback)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-ssas.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-enterprise-manage-ssas.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @rcfoyn, I'm adding this to the backlog of work for gateway docs, which we're currently updating.

**Comment by arthiriyer** [comment]
@rcfoyn. The information is available here https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-ssas#manual-user-name-remapping.
