### ISSUE TITLE
Markup missing?

### ISSUE THREAD

**Issue by steelanddata** [MicrosoftDocs/powerbi-docs#1173]
There's a raw file path (C:\...powerbi-content-pr\articles\media\powerbi-desktop-troubleshooting-analyze-in-excel) in the body of this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae990a42-30ce-e2cd-ef81-b2caba935050
* Version Independent ID: cd6b2f01-2ab8-bd8e-67a5-29a8f1ce3555
* Content: [Troubleshooting Analyze in Excel in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/desktop-troubleshooting-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks @steelanddata, I'm making this fix now, and it will be live later today.

**Comment by davidiseminger** [comment]
Thanks for pointing this out, looks like it's already been fixed.
