### ISSUE TITLE
PBIRS: Power BI Data Refresh - Minimum recommended interval

### ISSUE THREAD

**Issue by VinitashokPatil** [MicrosoftDocs/powerbi-docs#1174]
We have some users setting 1 minute interval for data refresh of Power BI report on PowerBI Report Server.  Is it ok to set such a short interval for data refresh ?
We are also seeing that there are a large number of entries (databases) in Analysis Service corresponding to this PowerBI report (when connecting via SSMS to analysis service), it could be a side effect of this short interval.
Requesting for guidance what would be a minimum interval that is recommended to be set for data refresh. Also if there are any considerations that may determine how small interval will be ok ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7b3eb03-b0dd-9c02-0c23-40a0a8476642
* Version Independent ID: 6f13876a-e24a-414d-154e-bdad5ee741f8
* Content: [Troubleshoot scheduled refresh in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/scheduled-refresh-troubleshoot)
* Content Source: [powerbi-docs/report-server/scheduled-refresh-troubleshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/scheduled-refresh-troubleshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment @VinitashokPatil. I'm checking with the product team on recommendations.

**Comment by mgblythe** [comment]
@VinitashokPatil - every 15-30 mins is typical. For future questions like this, I suggest posting in the [Power BI Community](https://community.powerbi.com).
