### ISSUE TITLE
Screen-shots are out-of-date

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1175]
Left nav now only has 3 icons and this one has a tool-tip of "Model".

Also UI color scheme has unfortunately been unilaterally changed, so all screenshots are out-of-date. Perhaps wait a month or two as it might be unilaterally changed again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cfe8c6-b047-1277-8726-0d45d3630b8d
* Version Independent ID: b2e24404-209e-f043-b749-2e2e865a9e79
* Content: [Use Modeling view in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-modeling-view#setting-common-properties)
* Content Source: [powerbi-docs/desktop-modeling-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-modeling-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
@Mike-Honey - thanks for your post! We're planning on going through and updating all these new screens once we get some time to do so, so it's on our radar. Thanks!

**Comment by alwweb** [comment]
The screen shots are still out of date and there are even more inconsistencies now.
