### ISSUE TITLE
Document the Properties

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1176]
Many properties are available, these seem undocumented?

E.g. what does the "Is nullable" property do?

If you are stuck on that one you can phone a friend:

https://blog.crossjoin.co.uk/2019/01/20/is-nullable-column-property-power-bi/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cfe8c6-b047-1277-8726-0d45d3630b8d
* Version Independent ID: b2e24404-209e-f043-b749-2e2e865a9e79
* Content: [Use Modeling view in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-modeling-view#setting-common-properties)
* Content Source: [powerbi-docs/desktop-modeling-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-modeling-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks @Mike-Honey for your comment. These (and other) properties are constantly being updated, so documenting them is literally a moving target. When we have a property that isn't terribly self-explanatory, we do document that (or aspire to) upon release. Thanks!
