### ISSUE TITLE
No Filters in Live Connection?

### ISSUE THREAD

**Issue by donalmc** [MicrosoftDocs/powerbi-docs#1178]
I've created and published a dataset to the PBI Service.
If I connect to the dataset live with PBI Desktop, it seems that I can't add a filter to any visuals or report pages - is this correct?
The image shown above has the Filters options.
I'm using the June 2019 release of PBI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets#feedback)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @donalmc. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment @donalmc - you can indeed apply filters for such datasets from the Desktop, I'm not sure why you're running into that issue. You may want to consider updating to the latest version of Power BI Desktop. If you run into the issue again, feel free to reach out to https://support.powerbi.com
