### ISSUE TITLE
What is the "Build" permission?

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#1179]
The "Build" permission is mentioned once in this page without explaining what it is or where it is set:

&gt;&gt; To allow users with Viewer role to export data, ensure 
&gt;&gt; they have Build permission on the datasets in the workspace.

i.e. what is this?  where/how is this set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @cbailiss. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Yes, thanks @cbailiss -- great point! I'll add a link. In the meantime, check out this article: https://docs.microsoft.com/en-us/power-bi/service-datasets-build-permissions#build-permissions-for-shared-datasets

**Comment by maggiesMSFT** [comment]
OK, @cbailiss -- article is updated with link. Thanks for asking!
