### ISSUE TITLE
Text is quite repetitive + overuse of "unique"

### ISSUE THREAD

**Issue by Hansonaplane** [MicrosoftDocs/powerbi-docs#1180]
When reading this text, I felt like getting the same information in different words several times, for example the parts about live connections or planned refreshs. Also, you claim four different tools to be unique - this somehow loses credibility after the second time. Why not just explain the differences between these tools? It's not important if they are unique or not. I think that this text could be way more concise and on point, you should think of re-working it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data#create-new-content)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Hansonaplane. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
You're right, I agree. As the current owner, I'm happy to remove all instances of "unique" and refresh. I'll also put reworking / paring down the content in the queue. Thanks!
