### ISSUE TITLE
conditions to see datasets in selection GUI

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#1181]
The datasets you see in this list meet at least one of the following conditions:
The articles says this: 

"The dataset is in one of the new workspace experience workspaces, and you're a member of that workspace. See Considerations and limitations.
You have Build permission for the dataset, which is in a new workspace experience workspace.
The dataset is in your My Workspace."

But in Power BI Desktop I see all datasets I have build permission on, regardless of if its a new or classic workspace. I think those conditions are true if you're using the service, but not Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0097b22-50b6-445a-10e9-a8e2a26dabbe
* Version Independent ID: daf670da-4171-29b2-7171-4e46637c099d
* Content: [Create reports based on datasets from different workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-discover-across-workspaces)
* Content Source: [powerbi-docs/service-datasets-discover-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-discover-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @klinejordan. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@klinejordan - Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page
