### ISSUE TITLE
Reports list view for Apps

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#1182]
The documentation mentions a "Reports list view" for apps but does not explain how to get there. What is the "reports list view" in the context of an app that is shared with me? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-copy-reports)
* Content Source: [powerbi-docs/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @klinejordan. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @klinejordan -- you probably figured this out long ago, but if not, this view is the Report list view:
![image](https://user-images.githubusercontent.com/12401230/72571403-5912fd80-3874-11ea-83ac-2d9065d35a58.png)
Hope that helps!

**Comment by klinejordan** [comment]
That view is only available to workspace users, not app users. Users of apps will never be able to see that view.

sent from mobile

________________________________

**Comment by maggiesMSFT** [comment]
@klinejordan -- you are right. The article is wrong. Testing it now, it appears I can only save a copy to My Workspace. I don't have the option to choose where the copy is saved. 
I need to rewrite the article to state that. I'll also confirm with the product team.
Thanks for your question and for insisting!

**Comment by maggiesMSFT** [comment]
@klinejordan --
Done. Should be live tomorrow.
Thanks again!
