### ISSUE TITLE
Edit interactions is not working

### ISSUE THREAD

**Issue by bartedgerton** [MicrosoftDocs/powerbi-docs#1184]
I have visual A doing cross-filtering on visuals B and C, which is desired; However, I want to disable cross-filtering when a value is selected in visual B, I don't want to filter visual A or C.  To that end, I have selected visual B, choose "Edit Interactions" from the Format menu, then select the "None" icon for visual A and visual C.  However, selecting a value in visual B still is causing some strange filtering behavior in visuals A and C both, (not to mention that visual B is also completely screwed up by selecting any value in the visual)

Also, it's worth mentioning that trying to actually hit the moving targets of the icons can be very difficult.  I had to rearrange my visuals just to be able to reach the controls, which move when you hover over them anyway, causing the user to inadvertently click the wrong icon, which exacerbates the problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-reports-visual-interactions)
* Content Source: [powerbi-docs/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @bartedgerton. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
