### ISSUE TITLE
Great tutorial !!!

### ISSUE THREAD

**Issue by mau-lopez** [MicrosoftDocs/powerbi-docs#1185]
These are among the best short tutorials I've watched. Very clear, at the right pace. Congrats on that! I want to suggest that you do the same for Power Query, it would be awesome to have this kind of clarity with that one too! Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7#feedback)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @mau-lopez. We really appreciate the positive feedback. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
@mau-lopez  - thank you! Happy to hear you liked these, and we'll see about doing the same for Power Query.
