### ISSUE TITLE
Confusion on what SKU this is capability available for.

### ISSUE THREAD

**Issue by Pokeystuff** [MicrosoftDocs/powerbi-docs#1186]
When looking at https://powerbi.microsoft.com/en-us/pricing/ it indicates this is only a Power BI Premium feature however this seems to indicate it is available to the service generically. please provide clarity on this as it is a very important distinction. Either this page or the pricing page will need to change unless there is some nuance that requires further information on what is and isn't included here. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Pokeystuff -- thanks for your question! Assigning to the writer to respond.

**Comment by davidiseminger** [comment]
Sorry for any confusion @Pokeystuff  - it is indeed a Premium feature.
