### ISSUE TITLE
Disable Promote

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#1187]
Is it possible to disable dataset promotion ?
We may only want certified dataset. Or maybe at limit the user able to endorse the dataset to a promoted status. Is it possible ?
Also is it possible in Power bi desktop to know for the selected dataset who endorsed it and see the description  ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc5682bb-d690-0e47-e23e-79377668fe47
* Version Independent ID: f2ef1103-5f2b-eec2-e1fc-f6ed31dc61c6
* Content: [Promote your dataset (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-promote#feedback)
* Content Source: [powerbi-docs/service-datasets-promote.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-promote.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Ilocans -- good question! Not that I know of, but I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @Ilocans -- got your answers! I'll update the articles.

**Is it possible to disable dataset promotion ? Or maybe at limit the user able to endorse the dataset to a promoted status.**
No, this is currently not possible. Every workspace member with Write permissions can promote a dataset. That said, these questions are good feedback – it would be interesting to understand the customer scenario a bit better, i.e. what’s the perceived drawback of not posing restrictions on the ability to promote datasets?

**Also is it possible in Power bi desktop to know for the selected dataset who endorsed it and see the description ?**
The information who certified a dataset when is showing up in a tool tip in the dataset discovery experience; hover over the “Certified” label and you will see it.
Unfortunately, the description is currently not visible anywhere – we realize that this is a painful gap in the user experience and we are working on fixing this issue.

**Comment by maggiesMSFT** [comment]
Hi, @Ilocans -- I added info to this article about not disabling dataset promotion. I recommend posting your other suggestions in the Power BI Ideas forum, https://ideas.powerbi.com/forums/265200-power-bi. 
Thanks again!
