### ISSUE TITLE
Deletion accross workspace

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#1188]
Hi,

If I publish in a workspace a report with a dataset coming from another workspace, it create 2 objects: the report and the dataset. If I delete the report, the dataset remain. There is no way to also delete it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f09aabd-9f0d-f94d-6e0a-7c9a9884dd71
* Version Independent ID: b4528bd4-f503-3cc2-52ec-9257e485555e
* Content: [Use datasets across workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-across-workspaces)
* Content Source: [powerbi-docs/service-datasets-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Good question, @Ilocans ! I don't see how either. I'll ask and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @Ilocans -- here's your other answer:

**If I publish in a workspace a report with a dataset coming from another workspace, it create 2 objects: the report and the dataset. If I delete the report, the dataset remain. There is no way to also delete it.**

First, let me clarify that in this scenario Power BI does not create another instance of the dataset. The shared dataset remains in its original location; in the report’s workspace we show a “reference item” for the dataset, i.e. basically a pointer to the dataset that provides basic information about the dataset (name, refresh data).
It is true that this reference item will not immediately vanish when you delete the associated report. This is a refresh issue – when you leave the workspace and come back to it the reference item will be gone.

**Comment by maggiesMSFT** [comment]
Hi, @Ilocans -- I added this info to the article https://docs.microsoft.com/en-us/power-bi/service-datasets-copy-reports#delete-a-report-and-its-shared-dataset. 
Thanks again!

**Comment by Ilocans** [comment]
Thank you
