### ISSUE TITLE
Power BI intro videos

### ISSUE THREAD

**Issue by wjdanalharthi** [MicrosoftDocs/powerbi-docs#1189]
Second and third URLs (the ones above the video previews) point to the same youtube video 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd66fe6d-5d79-32f8-d77d-621df2e04d97
* Version Independent ID: 5004c7d8-ea11-8cc2-0e25-69b9ab98f5e1
* Content: [Power BI Desktop videos - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-videos#feedback)
* Content Source: [powerbi-docs/desktop-videos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-videos.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @wjdanalharthi -- thanks for letting us know! Assigning to the author to take care of it.

**Comment by davidiseminger** [comment]
Thanks for that - sorry about that! We'll update those video links.
