### ISSUE TITLE
404 error on writing rows

### ISSUE THREAD

**Issue by kasajian** [MicrosoftDocs/powerbi-docs#119]
In order for this code to run, you cannot have any other datasets already on the site. 

The code:
`datasetId = results["value"][0]`

gets the dataset Id of the first dataset on the site, which is not necessarily the dataset the code just created.

In for the code to work as-is, the first dataset must be the dataset that just got created, and in order for that to be the case, no other datasets can exist prior to running this code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f8c50b5-a016-4fca-43fa-706dd8756148
* Version Independent ID: 3ab5d96f-d01d-ce04-9ae7-e366064bd9d1
* Content: [Add rows to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-add-rows)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-add-rows.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-add-rows.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
Although, we specify that we “//Get the first id,” the code is not accurate. The correct thing to do is search the dataset by name.  I will add some content to reference this.  Thank you again for your feedback.

**Comment by pspathakmsft** [comment]
## Quick workaround rename/force SalesMarketing dataset to be the first one in the list (I have appended 00 in the beginning )
//Create dataset JSON for POST request
            string datasetJson = "{\"name\": \"00SalesMarketing\", \"tables\": " + 

Hope this helps!
