### ISSUE TITLE
Please clarify what types of agreements are AllowAdHocSubscriptions = false by default

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1190]
@UKayo commented on [Wed Jun 26 2019](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/issues/10)

A tenant with EAS agreement was set to False, but a tenant with MPSA agreement was set to true. Please clarify.

 "If you acquired Power BI through a partner, this might be set to false, which means it is disabled." 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f9cf4ce3-f6b1-2c73-d0f9-44573242fb85
* Version Independent ID: fc6a52fd-db96-6e9f-f89a-3dea59bff3b7
* Content: [組織での Power BI のライセンス - Power BI](https://docs.microsoft.com/ja-jp/power-bi/service-admin-licensing-organization)
* Content Source: [powerbi-docs/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by CeciAc** [comment]
Hi team, I'm moving this here since the user is referring to the original documentation

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc -- thanks for posting the question here. I've assigned it to the author to reply.

**Comment by mgblythe** [comment]
The default is AllowAdHocSubscriptions = true, regardless of license type. Partners can decide to set as false as indicated in the article.
