### ISSUE TITLE
Broken links to DAX function documentation

### ISSUE THREAD

**Issue by CheapSquier** [MicrosoftDocs/powerbi-docs#1191]
The links in this sentence: "DAX includes the following categories of functions: Date and Time, Time Intelligence, Information, Logical, Mathematical, Statistical, Text, Parent/Child, and Other functions." result in a page not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [DAX basics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quickstart-learn-dax-basics#feedback)
* Content Source: [powerbi-docs/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @CheapSquier -- thanks for letting us know! Assigning to the writer to look into.

**Comment by davidiseminger** [comment]
Sorry for the inconvenience @CheapSquier - that must have been a temporary glitch, because they all work properly now. Thanks for posting!
