### ISSUE TITLE
Also the link to DAX Reference is broken

### ISSUE THREAD

**Issue by CheapSquier** [MicrosoftDocs/powerbi-docs#1192]
There are many DAX resources available to you; most important is the Data Analysis Expressions (DAX) Reference.
https://msdn.microsoft.com/query-bi/dax/data-analysis-expressions-dax-reference

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [DAX basics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quickstart-learn-dax-basics#feedback)
* Content Source: [powerbi-docs/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @CheapSquier -- thanks for this one, too! Assigning to the writer to look into.

**Comment by davidiseminger** [comment]
That one, too, has been fixed and works properly. Sorry for the inconvenience.
