### ISSUE TITLE
No Power BI Ribbon

### ISSUE THREAD

**Issue by AntiSquare** [MicrosoftDocs/powerbi-docs#1194]
In the section about "Users with multiple Power BI accounts" it states that "You can also select Profile from the Power BI ribbon tab in Excel".

However, when you open the .ODC file there is no Power BI ribbon.  You use to be able to get a similar looking Power BI ribbon by downloading the Power BI Publisher addon for Excel. The page about the Power BI Publisher takes you here to download it now (https://docs.microsoft.com/en-us/power-bi/publisher-for-excel).  So there does not seem to be any way to get that Power BI ribbon anymore.

Also, with the old Power BI Publisher addon I have the new v2 App workspaces do not show up in the workspaces lists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @AntiSquare -- good question. Assigning to the writer. In the meantime, you can check with the Power BI support site to see if they have more info. https://powerbi.microsoft.com/en-us/support/

**Comment by JossephAnthony** [comment]
Hello, I have the same problem... I'm trying to find the webpage where I can download the Power BI ribbon for Excel but I can't find it.

**Comment by JossephAnthony** [comment]
Finally, I find the correct link https://www.microsoft.com/en-US/download/details.aspx?id=50729

**Comment by maggiesMSFT** [comment]
Great sleuthing, @JossephAnthony -- we can update the link with your info!

**Comment by davidiseminger** [comment]
Thanks for the sleuthing! I've added that link to the article, and it'll refresh the article in the next 24 hours.
