### ISSUE TITLE
Better clarification on how to output the dataset after running an R Script

### ISSUE THREAD

**Issue by OdinTech3** [MicrosoftDocs/powerbi-docs#1195]
I had trouble figuring out how to return a filtered dataset using `dplyr`, I wrote out the bellow piece of code
```r
# 'dataset' holds the input data for this script
library(dplyr)

dataset<- dataset %>% filter(some_condition)
```
and I expected the result to be a new dataset with the filter applied to it, but it didn't happen like that. Then after looking through the docs more times than was necessary, I figured I had to overwrite a variable named `output`

 ```r
# 'dataset' holds the input data for this script
library(dplyr)

output <- dataset %>% filter(some_condition)
```

I think documenting this step one has to take would be beneficial, it would make things very clear right from the get go. Even adding it to the boilerplate comment would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Using R in Power Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-in-query-editor#feedback)
* Content Source: [powerbi-docs/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @OdinTech3 -- thanks for the suggestion! Assigning to the author for further consideration.

**Comment by davidiseminger** [comment]
Thanks for your comment @OdinTech3  - I've added a note to that effect, hopefully that'll let your experience help others. Thanks! Should show up live in ~24 hours.
