### ISSUE TITLE
Licensing for BYOL

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#1196]
How can the inviting organization determine if the B2B guest user has a PBI Pro license already?  Can you please expand on how we would ensure license compliance in that section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad42c3b-e011-733d-dbdf-53944a2724a6
* Version Independent ID: 05e0f67c-5852-5b10-ac94-694ec2d0d8f9
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-azure-b2b-power-bi#approach-3-guest-users-bring-their-own-power-bi-pro-license)
* Content Source: [powerbi-docs/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @danmyhre -- thanks for your question! Assigning to the author to respond.

**Comment by davidiseminger** [comment]
Hello @danmyhre and thanks for your question. This is more of a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by danmyhre** [comment]
I was looking for the official requirements from MSFT to be documented on this topic
