### ISSUE TITLE
Guest Account with PBI Pro License

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#1197]
It doesn't seem like this article is accurate on the licensing side.  I used a guest account (with B2B) to access a shared report.  When logging in, I was prompted with the Pro upgrade notice, so having a Pro license in the home tenant does NOT allow access to shared content in a guest tenant.

This is the message: 
This content is only available to users with a Power BI Pro license. When you upgrade, you get access to collaborate with others and distribute content. Upgrade today or try it free for 60 days.Learn more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad42c3b-e011-733d-dbdf-53944a2724a6
* Version Independent ID: 05e0f67c-5852-5b10-ac94-694ec2d0d8f9
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-azure-b2b-power-bi#feedback)
* Content Source: [powerbi-docs/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @danmyhre -- thanks for asking! Assigning to the author to look into it.

**Comment by davidiseminger** [comment]
Including the content owner of that whitepaper.

**Comment by davidiseminger** [comment]
Adding additional content folks to review and comment.

**Comment by mihart** [comment]
Hi @danmyhre ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
