### ISSUE TITLE
Cannot assign ReadOverrideEffectiveIdentity to Service Principle

### ISSUE THREAD

**Issue by gronnerup** [MicrosoftDocs/powerbi-docs#1198]
When assigning the Service Principle with the ReadOverrideEffectiveIdentity permission using the REST API the following response is recieved.
{
  "error": {
    "code": "DMTS_PrincipalsAreInvalidError",
    "pbi.error": {
      "code": "DMTS_PrincipalsAreInvalidError",
      "parameters": {},
      "details": [],
      "exceptionCulprit": 1
    }
  }
}

I have verified that the gateway and datasource is correct. Also it is possible to retrieve current users using the GET method. 

The identifier used is the App/Client ID also used when embedding which works fine with import mode. So the SP identier is valid.

The body posted is 
{"identifier": xxxxxxxx-xxxx-415a-a801-xxxxxxxxxxxxx", "datasourceAccessRight": "ReadOverrideEffectiveIdentity"}

**Comment by maggiesMSFT** [comment]
Hi, @gronnerup -- are you referring to this article, https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal? I'm assigning your comment to someone on the docs team to look at, but it sounds like a support question. Please see https://powerbi.microsoft.com/en-us/support/ for help.

**Comment by gronnerup** [comment]
Hi @maggiesMSFT , actually I had not taken this doc article into consideration but it actually solved it for me. It turned out that the Object ID which i was adding was not the correct one. I took the object ID from the App Registration pages and not from the Service Principle page. 

Thanks for leading me back on track. So no need to assign the comment to the docs team.

**Comment by maggiesMSFT** [comment]
@gronnerup -- that's great! Glad I could help. I'll close this issue now.

**Comment by Rakeshsinghr** [comment]
were you able to add Appid to Gateway datasource users using the API? I get 400 response code.

**Comment by gronnerup** [comment]
@Rakeshsinghr, please verify that you are applying the object ID fetched via the "Managed Application in local directory" property? 

So go the the Azure Portal, navigate to the app registration you are using and click on the hyperlink next to “Managed Application in local directory”. This has the same name as your app registration. Then copy the Object ID from this page.
