### ISSUE TITLE
Please document visualHeader enhancements from July 2018

### ISSUE THREAD

**Issue by fpk3** [MicrosoftDocs/powerbi-docs#120]
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @fpk3 -- thanks for the suggestion! I've passed it along to the author, @davidiseminger

**Comment by davidiseminger** [comment]
Hi @fpk3 - they're already documented. Check out https://docs.microsoft.com/power-bi/desktop-visual-elements-for-reports#using-improved-visual-headers-in-power-bi-reports. Thanks for posting.
