### ISSUE TITLE
Copied report not available to be published in app

### ISSUE THREAD

**Issue by MikeBrough** [MicrosoftDocs/powerbi-docs#1201]
Hi, I've copied a report to another app. This report has been built by connecting to a power bi dataset as a live connection. The report is not available to be published in an app in another workspace (the option 'Included in app' is greyed out). Is this correct? I would have thought all reports could be published in an app? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-copy-reports#feedback)
* Content Source: [powerbi-docs/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MikeBrough -- yes, that's currently true. See the Limitations and Considerations section of this article: https://docs.microsoft.com/en-us/power-bi/service-datasets-across-workspaces#considerations-and-limitations. 
I'll add a link from this article to it. Good point.
If you'd like to suggest a feature or a change, consider going to Power BI Ideas. You can search to see if anyone else has suggested it and vote for it, or add a new one.

**Comment by maggiesMSFT** [comment]
Hi, @MikeBrough -- link is added. Thanks again!
