### ISSUE TITLE
Links are broken

### ISSUE THREAD

**Issue by BozekD** [MicrosoftDocs/powerbi-docs#1202]
The following links in the first paragraph go to resource not found pages:

"M formulas" -&gt; https://msdn.microsoft.com/library/mt270235.aspx
"comprehensive function reference content set" -&gt; https://msdn.microsoft.com/library/mt779182.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8e549-7fba-9ece-3e32-73a0cc3c6046
* Version Independent ID: a9b39810-c302-c153-3123-ddb8f459e9f4
* Content: [Add a custom column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-add-custom-column#feedback)
* Content Source: [powerbi-docs/desktop-add-custom-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-add-custom-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @BozekD -- thanks for pointing that out! Assigning to the author to look into it. In the meantime, try this link: https://docs.microsoft.com/en-us/powerquery-m/power-query-m-reference

**Comment by davidiseminger** [comment]
Sorry for the inconvenience - those links now work properly.
