### ISSUE TITLE
Update link to Azure IP port information

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#1203]
Please update the link to the Azure Datacenter IPs, it is currently pointing to a resource that is going to be deprecated, the new link should be  https://www.microsoft.com/en-us/download/details.aspx?id=56519 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshooting the On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot)
* Content Source: [powerbi-docs/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- thanks for the heads-up. Assigning to the author.

**Comment by mgblythe** [comment]
Thanks @DeanGross, updating now. Note that this article has moved in our revised gateway docs: https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-tshoot.

**Comment by mgblythe** [comment]
Fix verified, closing
