### ISSUE TITLE
can you use a third party app registration to access api.powerbi.com on behalf of another tenant?

### ISSUE THREAD

**Issue by mlegris** [MicrosoftDocs/powerbi-docs#1205]
We have an app registration that can access management.azure.com APIs on behalf of our clients (other tenants). But it doesn't work with api.powerbi.com... I followed this tutorial, 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-api-authentication#check-if-user-can-assign-access-to-subscription

How can I reproduce the "getAppOnlyToken" that would allow me to access our client's api.powerbi.com  apis? Through azure management I can create, update, delete, list, suspend, resume Capacities. But I can't assign them to a workgroup. Why did you split those functionalities into two seperate apis?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @mlegris . This issue has been assigned to the doc author for review.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Thanks for your comment, @mlegris.

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
