### ISSUE TITLE
Token based Identity tutorial

### ISSUE THREAD

**Issue by LeoFurnari** [MicrosoftDocs/powerbi-docs#1206]
I would really like to use the Token Based Identity PBI Embedded concept with an App Service, however I don’t have the funds for a dedicated capacity. I would be much more motivated to use the feature if there was a clear tutorial on how to configure authentication with an App Service and Azure SQL DB in tandem with PBI Embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @LeoFurnari . This issue has been assigned to the doc author for review.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @LeoFurnari, currently there is no such solution. To use Power BI embedded you need to have a capacity. You can refer to the following article to decide what is the best solution for you - [Frequently asked questions about Power BI Embedded](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq).
