### ISSUE TITLE
How can I execute Bex queries in PowerBI? How can I pull them too?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1207]
How can I write or pull Bex queries in Powerbi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3310d6cb-93c6-823f-760e-ea08a4627017
* Version Independent ID: 3932a2fb-a84f-0df8-c977-1d17860c51bc
* Content: [DirectQuery and SAP Business Warehouse (BW) in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-sap-bw)
* Content Source: [powerbi-docs/desktop-directquery-sap-bw.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-sap-bw.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Anmolgan81. I've assigned this issue to the doc author for review. In the meantime, I recommend asking if this is possible in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment, @Anmolgan81 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
