### ISSUE TITLE
How cross report filters works in Power Bi Report Server

### ISSUE THREAD

**Issue by psrinivasamaniprabhakar** [MicrosoftDocs/powerbi-docs#1208]
I saw in recent release of POWER BI Report server May 2016 we have cross report filters enabled.  How it is going to work.  I am trying to work it out, but unable to there is no url or report name where i can mention and say this report is drill through report

**Comment by mgblythe** [comment]
Thanks for your comment, @[github person who posted]. I've assigned this issue to the report server writer for review. In the meantime, I would ask in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @psrinivasamaniprabhakar -- are you referring to Power BI reports or paginated (Report Builder) reports in Power BI Report Server?
thanks --

**Comment by maggiesMSFT** [comment]
Hi, @psrinivasamaniprabhakar -- Receiving no reply, I'm closing this issue. Please feel free to reopen at any point.
