### ISSUE TITLE
Power BI - Performance Analyzer - JSON export

### ISSUE THREAD

**Issue by LoisLoriot** [MicrosoftDocs/powerbi-docs#1210]
Hi,

Is it possible to have more information about the data exported in JSON (the meaning of the different hierarchies especially).

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/38054662-performance-analyzer-json-export

https://community.powerbi.com/t5/Desktop/Performance-Analyzer-GUI-vs-JSON/m-p/726764

Thanks!
Lois

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407af4e5-336a-af92-35ad-7a449cced735
* Version Independent ID: 53dc34f6-68b5-3e30-dcc2-1a8525c800bb
* Content: [Use Performance Analyzer to examine report element performance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-performance-analyzer#feedback)
* Content Source: [powerbi-docs/desktop-performance-analyzer.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-performance-analyzer.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @LoisLoriot. I've assigned this issue to the doc author for review.

**Comment by LoisLoriot** [comment]
Hi,

@mgblythe, @davidiseminger , any updates? :)

Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment and follow up, @LoisLoriot . The performance analyzer is undergoing frequent updates, so thanks for your interest. The best avenue to ask for more information about the feature (and its JSON data) is to submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by LoisLoriot** [comment]
Hi @davidiseminger,

Thanks for your answer. 
Please note that I already submitted product feedback and engaged with the Power BI community back in July. Until now: still no reply, which I can understand because the blocker is the lack of technical documentation about this JSON export feature.

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/38054662-performance-analyzer-json-export

https://community.powerbi.com/t5/Desktop/Performance-Analyzer-GUI-vs-JSON/m-p/726764

Thanks anyway,
Lois
