### ISSUE TITLE
Desktop -> Service -> DS -> Gateway -> Cube not working

### ISSUE THREAD

**Issue by raptor75** [MicrosoftDocs/powerbi-docs#1211]
We created a Data GAteway, then in Power Bi Service, we created a Datasource going through this Gateway to the required cube.

When connecting to the cube from Power BI Desktop through Power BI Service, after selecting the Data Source, Desktop still tries to connect directly to the Cube instead of going through the Gateway.

Is this how it should be working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by msfttimmac** [comment]
Where is the Cube?  If the cube is in the cloud, then yes, that is the way it should work.  Initially it will reach down to get the driver information and how to connect.  From that point forward, it should go directly to the cloud source in the Power BI Service.

**Comment by mgblythe** [comment]
Closing this one out.
