### ISSUE TITLE
What do you do when it assumes your Onpremise SP source is Cloud?

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1213]
What do you do when it assumes your On-premise SharePoint 2016 source is in the Cloud and does not offer you your Personal Data Gateway in gateway selections? Is there something we can do in Advanced Editor to convince it it is On Premise?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7028bd8d-f24b-526c-f504-1db3802be099
* Version Independent ID: ed198ac1-3dab-8515-1d2b-3987b1a03561
* Content: [Troubleshooting Power BI Gateway - Personal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-troubleshooting-power-bi-personal-gateway)
* Content Source: [powerbi-docs/service-admin-troubleshooting-power-bi-personal-gateway.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-troubleshooting-power-bi-personal-gateway.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Thanks for your comment, @pcgeekus . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
