### ISSUE TITLE
PowerBI authorization for service principals

### ISSUE THREAD

**Issue by sshresthareach** [MicrosoftDocs/powerbi-docs#1214]
I have a PowerBI application where users can authorize the application to read their PowerBI contents. I am using the OAuth2 code flow to get proper authorization and access tokens. Is it possible to get authorization using service principal rather than the users having to use their PowerBI account. Or is the Service Principal meant for something else entirely?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by adamvan101** [comment]
Yes, that is essentially the intent

**Comment by sshresthareach** [comment]
@adamvan101 Thank you for the response. The reason I thought it could be for something else is because I could not find any documentation on how I can use service principal to generate access token for PowerBI. The only example I found was a C# code snippet which is not very helpful if I'm not using C#.
Do you know if there's any documentation that I can follow on this topic?

**Comment by adamvan101** [comment]
@sshresthareach the docs here are fairly low-level and should, therefore, be easily translatable to any language: [https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)

**Comment by sshresthareach** [comment]
@adamvan101 This is the page that I was referring to earlier. It has a C# code snippet to authenticate as shown below. The code below seems to be the only relevant code to generate access token using service principals. But the code makes use of C# classes like ClientCrendential and AuthenticationContext which abstracts away a lot of things. As per this example, am I supposed to use OAuth2 Client Crendential flow? 
```
var authenticationContext = new AuthenticationContext(AuthorityUrl);
       AuthenticationResult authenticationResult = null;
       if (AuthenticationType.Equals("MasterUser"))
       {
              // Authentication using master user credentials
              var credential = new UserPasswordCredential(Username, Password);
              authenticationResult = authenticationContext.AcquireTokenAsync(ResourceUrl, ApplicationId, credential).Result;
       }
       else
       {
             // Authentication using app credentials
             var credential = new ClientCredential(ApplicationId, ApplicationSecret);
             authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, credential);
       }


m_tokenCredentials = new TokenCredentials(authenticationResult.AccessToken, "Bearer");
```

**Comment by adamvan101** [comment]
@sshresthareach yes, it uses the OAuth2 flow - unfortunately I don't have any good references for you that aren't C#

**Comment by sshresthareach** [comment]
@adamvan101 Thank you for confirming that. I will try the Client Credential flow for OAauth2

**Comment by kfile** [comment]
Thank you for your question and to @adamvan101  for the responses. It looks like we have a gap in documentation so I've assigned this to the writer. We have a lot of people on vacation through the summer so it might be a little while before it gets addressed. @markingmyname  - can you handle this one until your replacement is hired?

**Comment by markingmyname** [comment]
Thanks for your comment, @sshresthareach. This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.  

I would add your suggestion to the [ideas page](https://ideas.powerbi.com/forums/265200-power-bi-ideas).

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by sshresthareach** [comment]
@markingmyname I think this is a documentation issue because there really is no documentation on _how to generate access token using service principal_, other than a small C# snippet. If someone is new to Oauth2 and C# then there would really be no direction one could take. In contrast there is a tonne documentation to generate a token with a powerbi account.
I think it would be helpful if the documentation included something about OAuth2 and the correct flow to use. Also the documentation could include the endpoints to call for the OAuth2 flow rather than a C# snippet.

**Comment by Ichtil** [comment]
@markingmyname I agree with @sshresthareach, I am going through a similiar issue. Not everybody is using C# and having some REST calls shown would be helpful.

**Comment by markingmyname** [comment]
#reassign Keseem Sharabi

**Comment by PRMerger13** [comment]
Keseem is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by markingmyname** [comment]
@sshresthareach and @Ichtil    

We apologize that you feel there should be more information about how to generate an access token using OAuth2 and C#.

I have assigned to the current author to look into this further.

Thank you.

**Comment by Ichtil** [comment]
You misunderstood - we don't want c#, we want rest API endpoints and show how to call these (eg. with service principal). I found that it is covered by Login Microsoft endpoints, but it wasn't until I connected with the support that I found what resource/scope I need to use.
