### ISSUE TITLE
Documentation to get access token for Service principal missing

### ISSUE THREAD

**Issue by sshresthareach** [MicrosoftDocs/powerbi-docs#1215]
The above documentation says that you can generate access token for PowerBI using service principal and the example shows C# code to do it. But I could not find documentation on how to generate the token if I'm not using C# library. Could you please help me find it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by jesusvpct** [comment]
Hello, I had the same problem, but now I have an example using PHP (based on [this link](https://docs.microsoft.com/en-us/graph/auth-v2-service#4-get-an-access-token) and [this other link](https://github.com/thephpleague/oauth2-client)). This is the code:

```
$clientId = 'YOUR_APP_ID';
$clientSecret = 'YOUR_APP_SECRET';
$urlAuthorize = 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize';
$tenantId = 'YOUR_TENANT_ID';
$urlAccessToken = "https://login.windows.net/$tenantId/oauth2/token";
$scope = 'openid';
$resource = 'https://analysis.windows.net/powerbi/api';

$oauthClient = new GenericProvider([
    'clientId'                        => $clientId,
    'clientSecret'                    => $clientSecret,
    'urlAuthorize'                    => $urlAuthorize,
    'urlAccessToken'                  => $urlAccessToken,
    'urlResourceOwnerDetails'         => '',
    'scope'                           => 'openid'
]);

$accessToken= $oauthClient->getAccessToken('client_credentials', [
	'resource' => $resource
]);

$token = $accessToken->getToken();
```

I hope this helps.

**Comment by sshresthareach** [comment]
@jesusvpct Thanks a lot. This does help. It looks like I'm supposed to use OAuth2 Client Credential flow to generate the token.

**Comment by kfile** [comment]
Thank you for your question (and the helpful reply). I've assigned this to the writer to do a doc enhancement per your request. We are in between writers right now so the one who's covering might not get to it right away.

**Comment by sshresthareach** [comment]
@kfile Thanks Kelly. I guess if the documentation mentioned that you have to use OAuth2 Client Credential flow, it would have given me some direction on how to use the service principal.

**Comment by kfile** [comment]
Understood. I think that will be clear to the writer.

**Comment by ka2er** [comment]
same issue here. We are trying to implement in PHP and can't rely on REST sequence diagram or something like that to fetch our first data (client app auth - SP > fetch first report or data)

**Comment by kfile** [comment]
OK thanks @ka2er

**Comment by markingmyname** [comment]
Thanks for your comment, everyone This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.  

I would add your suggestion to the [ideas page](https://ideas.powerbi.com/forums/265200-power-bi-ideas).

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
