### ISSUE TITLE
Not pulling in all tickets?

### ISSUE THREAD

**Issue by cjs-github** [MicrosoftDocs/powerbi-docs#1216]
I've managed to plug this into Zendesk, but PowerBI only 'sees' ~25,000 tickets. There are more than 100,000 in Zendesk.

**Comment by kfile** [comment]
Thanks for your comment, @cjs-github . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
