### ISSUE TITLE
parameters

### ISSUE THREAD

**Issue by pomer97** [MicrosoftDocs/powerbi-docs#1218]
what i need to do to pass parameters with that link .
like id 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21813211-4c66-33dd-94bd-576addc9f910
* Version Independent ID: 618c0c7a-20cc-1450-cb42-ca73156a7598
* Content: [Add a hyperlink to a text box in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-add-hyperlink-to-text-box#feedback)
* Content Source: [powerbi-docs/service-add-hyperlink-to-text-box.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-add-hyperlink-to-text-box.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
HI @pomer97 and thanks for your question. It may need to go to the product team but first I thought I'd see if the writer can help you. I've assigned it to her for now.

**Comment by dodgy99** [comment]
I would also like to know how to pass a parameter to this link rather than hard coding it

**Comment by maggiesMSFT** [comment]
Hi, @pomer97 and @dodgy99 -- see if this article helps: https://docs.microsoft.com/en-us/power-bi/service-url-filters
Thanks!

**Comment by dodgy99** [comment]
Hi Maggie's,

I'm afraid that's not quite what I was after, I wanted to have the URL in a text box fed from a measure similar to chart titles. However instead of using text I imported an image of the text and assigned a bookmark URL to get the desired effect.

**Comment by maggiesMSFT** [comment]
Hi, @dodgy99 -- Good you found a workaround. 
@pomer97 --how about you?

**Comment by rburcham** [comment]
@dodgy99 can you explain what you did?  I also need to invoke an external URL passing parameters.  It would be great if I could do this with a POST, but will be happy to take what I can GET.

@maggiesMSFT do you know if this is possible?

**Comment by maggiesMSFT** [comment]
Hi, @pomer97 @dodgy99 & @rburcham --
Got an answer. Hope this helps:
It sounds like you want it to be a dynamic URL. It would pick up the selections made in the report and attach that to the URL. You can't do it for a URL in a textbox, but you can bind a Button to a dynamic URL. Like this:
https://docs.microsoft.com/en-us/power-bi/desktop-conditional-format-visual-titles which it sounds like you know about, but for the URL of a button.
Again, hope that helps!
