### ISSUE TITLE
BankRate Data Incorrect

### ISSUE THREAD

**Issue by RodrigoSeer** [MicrosoftDocs/powerbi-docs#122]
Some of the column titles where different between what the tutorial states and what is actually pulled from the link.

The Senior column does not come with the BankRate data

It seems that this tutorial may need to be revised with the current data that is being pulled. Nothing major the tutorial can still be accomplished once we realize what is missing or named differently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Shape and combine data from multiple sources - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @RodrigoSeer -- thanks for the feedback! I'm assigning to the author to look at it and get back to you.

**Comment by davidiseminger** [comment]
Thanks for your comment @RodrigoSeer - we'll put that in the list of updates we do. Note that there may be other pressing work before we get to this, but it's a reasonable request.

**Comment by rafaelhenck** [comment]
Not sure why is this a closed ticket because the problem remains today.
