### ISSUE TITLE
Out of Date Description - Connect, manage and view Excel in Power BI

### ISSUE THREAD

**Issue by v-kerwan** [MicrosoftDocs/powerbi-docs#1220]
When choosing this way, Power BI will create a corresponding dataset for the connected workbook. You can use this dataset to create a Power BI report if needed. Your workbook will also appear in your Power BI workspace navigation pane under Reports. Connected workbooks have a special Excel icon.

Above Description is incorrect, which is opposite from (Reference: https://docs.microsoft.com/en-us/power-bi/refresh-excel-file-onedrive)

Correct Description:
When you connect to an Excel workbook this way, a dataset is not created in Power BI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b088da-d833-fba7-a07d-3a1a07ff557d
* Version Independent ID: 8c423288-260e-386a-4c75-4e39f7be6ff1
* Content: [Get data from Excel workbook files - Power BI](https://docs.microsoft.com/en-us/power-bi/service-excel-workbook-files)
* Content Source: [powerbi-docs/service-excel-workbook-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-excel-workbook-files.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @v-kerwan . I've assigned this issue to the writer for consideration. Thank you for your question.

**Comment by davidiseminger** [comment]
Thanks for the post - I've updated that article, and will be reflected online in about 24 hours.
