### ISSUE TITLE
Live Connection to PowerBI Dataset ?

### ISSUE THREAD

**Issue by MichaelDotEarly** [MicrosoftDocs/powerbi-docs#1221]
Hi. I am getting the message saying that "this Visual is not supported on the following scenario....".

It was communicated Live Connection to PowerBI Dataset was now supported in the June 2019 update.

Full context:
Live Connection to PowerBI Dataset, itself connecting to Azure Analysis Tabular Model, including RLS.

**Comment by davidiseminger** [comment]
Thanks for your comment, @MichaelDotEarly. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
