### ISSUE TITLE
Documentation to setup ExpressRoute with Power BI - Private or Microsoft Peering?

### ISSUE THREAD

**Issue by SB-o-matic** [MicrosoftDocs/powerbi-docs#1223]
Hello,

Can some one please provide any documentation to set this up? With Private Peering I am thinking the gateway server in Azure, the SQL databases on-prem or both servers in Azure.

With Microsoft Peering, I do not see Power BI in the "Allowed services list" when managing the route filter rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54c2c06-9e5e-1ded-a3f8-396f7fdf7841
* Version Independent ID: 4cde51d1-ab58-8889-b187-ac0d3020bdee
* Content: [Power BI and ExpressRoute - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-expressroute#feedback)
* Content Source: [powerbi-docs/service-admin-power-bi-expressroute.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-expressroute.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @SB-o-matic. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @SB-o-matic - there is no plan to provide additional ExpressRoute documentation at this time. I'll reopen if we do.

**Comment by SB-o-matic** [comment]
I am not sure I understand.

It is possible to leverage Microsoft Peering for the Power suite (Power BI, PowerApps, Flow) or not?

I see "Other Office365 Services (12076:5100)" under allowed service communities when managing rules for a Route filters associated with an expressroute circuit. Will that apply?

Please answer my question as we already have prod implementations that need better throughput.

**Comment by SB-o-matic** [comment]
Dear Microsoft, 
Can someone please answer my question? Products are increasingly being made available without adequate supporting documentation. I don't understand why a question is closed without an answer or consent from the one who asked it.
