### ISSUE TITLE
Incorrect capacity type 

### ISSUE THREAD

**Issue by 12Iryna12** [MicrosoftDocs/powerbi-docs#1225]
https://docs.microsoft.com/en-us/power-bi/refresh-data

In Datasets in Import mode section, please change A4 and P2 to A5 and P2 ( Current Behaviour: A4 or P2 | 6 GB ). In the following link https://docs.microsoft.com/en-us/power-bi/service-premium-what-is, we have the indication that A5 capacity type corresponds to P2. 

Thank you in advance.

**Comment by davidiseminger** [comment]
Thanks for your comment, @12Iryna12 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @12Iryna12 - fix will be live tomorrow.

**Comment by mgblythe** [comment]
Fix verified, closing
