### ISSUE TITLE
The dataflows feature (in preview) is not supported on Multi-GEO at this time.

### ISSUE THREAD

**Issue by snotebaert** [MicrosoftDocs/powerbi-docs#1226]
Dataflows are GA since april 2nd, 2019.  What is the status with the multi-geo support of dataflows? 

https://powerbi.microsoft.com/en-us/blog/announcing-power-bi-dataflows-general-availability/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-multi-geo#feedback)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @snotebaert . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @snotebaert - I'll review the (preview). I don't see any reference to multi-geo support in the [release plan](https://docs.microsoft.com/power-platform-release-plan/2019wave2/business-intelligence/planned-features).

**Comment by mgblythe** [comment]
Fix verified, closing.
