### ISSUE TITLE
Version Numbering 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#123]
When I open the Power BI desktop app from the Windows Store, the About screen shows Version 3218.30725.1673 and the What's new screen discusses versions 1673, 1657, 1633 and 1609. None of those numbers correlate with any of the information on this page which is not consistent with the phrase "The monthly versions are the same, regardless of which way you install Power BI Desktop". Please revise the text to clarify how version numbers are displayed and used in each app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update-archive)
* Content Source: [powerbi-docs/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update-archive.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @DeanGross  Good question! I've assigned to the author to get back to you.

**Comment by davidiseminger** [comment]
Thanks @DeanGross - I'll bring this up with engineering and see how we can better clarify it.

**Comment by davidiseminger** [comment]
Sorry for the delay @DeanGross - and you're correct, the numbering is different in each version even though the functionality of each is the same. Sorry for any confusion. I've clarified that in the article. Thanks!
