### ISSUE TITLE
Overpowered permission required for day 1 functionality (export)

### ISSUE THREAD

**Issue by GeorgeCMElliott** [MicrosoftDocs/powerbi-docs#1231]
"To export the data from a visual, you need to have Build permission for the underlying dataset."

The only reason this hasn't turned into an issue with users yet is because the build permission rollout in June automatically added the "build" permission for any datasets attached to shared reports prior to the go-live of build permissions.

Once people realize that entire datasets are now exposed to users that once only had access to the report it will be raised as a security concern.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by GeorgeCMElliott** [comment]
By the way, the only reason this hasn't blown up in Microsoft's face yet is because the rollout automatically added the "build" permission for any datasets attached to shared reports prior to the go-live of build permissions. Of course if more people realized that (ie infosec teams) there would probably be a huge data sensitivity concerned being raised as well. I wonder how long that will take to happen?

**Comment by GeorgeCMElliott** [comment]
Imagine you create a report with filters so users can only see certain data (probably didn't use rls), but because the user can only view the report you shared with them they can't see any sensitive data. Not anymore, we just gave all of your users the ability to see the entire dataset.

**Comment by davidiseminger** [comment]
Thanks for your comment, @GeorgeCMElliott. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks for the comment @GeorgeCMElliott. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
