### ISSUE TITLE
Connect power BI datasource to dataflow

### ISSUE THREAD

**Issue by lypolyzo** [MicrosoftDocs/powerbi-docs#1232]
I was wondering if it's possible to connect a power BI datasource to a dataflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating and using dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-create-use)
* Content Source: [powerbi-docs/service-dataflows-create-use.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-create-use.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @lypolyzo . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
