### ISSUE TITLE
Not Able to See Field Properties Option in Menu or Properties option in Model

### ISSUE THREAD

**Issue by HarsimranjeetSingh** [MicrosoftDocs/powerbi-docs#1233]
Hi Team,

I'm not able to see the **Field Properties** mentioned in Top of [https://docs.microsoft.com/en-us/power-bi/desktop-storage-mode](url).

I've downloaded latest Power BI Desktop

**Comment by davidiseminger** [comment]
Thanks for your comment, @HarsimranjeetSingh . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by HarsimranjeetSingh** [comment]
Hi @davidiseminger ,

**Please update the Document**

Thanks to Power BI Forum [https://community.powerbi.com/t5/Desktop/View-Field-properties-June-2019-version/m-p/713156#M344213](url) , as it's available now  when we look to model and there after select required entity from model.

Thanks,
Harry

**Comment by davidiseminger** [comment]
Thanks for your comment. I've updated the article to reflect that. Thanks!
