### ISSUE TITLE
 An unexpected 'StartArray' node was found when reading from the JSON reader

### ISSUE THREAD

**Issue by max1weber** [MicrosoftDocs/powerbi-docs#1234]
Simple Web API 2.2. Odata v4: 

DataSource.Error: OData: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'StartObject' node was expected.
Details:
    DataSourceKind=OData

How can I fix it...  is the Micosoft.Restier nuget package the only direction to solve it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29bfbd4c-5149-93be-3982-81af6852a5dd
* Version Independent ID: 75460ed0-c7d9-fe67-8010-b843661dc66e
* Content: [Connect to an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-odata#feedback)
* Content Source: [powerbi-docs/desktop-connect-odata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-odata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @max1weber. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
