### ISSUE TITLE
Test to see if your firewall, or proxy, may be blocking connections always fails. When run the following powershell script "Test-NetConnection -ComputerName watchdog.servicebus.windows.net -Port 9350" it gives always the following warning (WARNING: Name resolution of watchdog.servicebus.windows.net failed). But the gateway works fine.

### ISSUE THREAD

**Issue by DatStone** [MicrosoftDocs/powerbi-docs#1236]

**Comment by davidiseminger** [comment]
Thanks for your comment, @DatStone . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
