### ISSUE TITLE
Remove 2017 update references, rewrite to clearly describe clean install

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1237]
This whole article reads like an update guide for a 2017 release.  That's now irrelevant. The article should be rewritten to focus on a clean install scenario (no previous gateway). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea871f0a-018e-0335-7261-f9d9d2232e36
* Version Independent ID: 345a024a-5964-0979-494f-6f7196a3c929
* Content: [On-premises data gateway (personal mode) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode)
* Content Source: [powerbi-docs/service-gateway-personal-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-personal-mode.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Mike-Honey. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @Mike-Honey, we just revised the gateway docs across the board. Let me know what you think of the current version of this article.

**Comment by Mike-Honey** [comment]
That's a lot cleaner - thanks. What I now see as missing is any info on how to actually use the personal gateway. OK I have it installed, it says it is connected and all the test work. What happens next? How do I use it?

**Comment by mgblythe** [comment]
#reassign @arthiriyer to see about adding info the article.

**Comment by kfollis** [comment]
@Mike-Honey - Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
