### ISSUE TITLE
Documentation for Power BI excludes GCC High specific details

### ISSUE THREAD

**Issue by patrickabel** [MicrosoftDocs/powerbi-docs#1239]
The above documentation for Power BI for US Government excludes details regarding the URL to access the service for GCC High customers. This URL is: https://app.high.powerbigov.us

Can we get this documentation updated to reflect both tenant types?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for United States Government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/service-govus-overview#feedback)
* Content Source: [powerbi-docs/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment @patrickabel. I've assigned this issue to the author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback @patrickabel  - I've added that URL to the FAQ section, it'll update in the next 24 hours. Thanks!
