### ISSUE TITLE
Page Length

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#124]
There are so many versions listed I have to use 2 different vertical scroll bars to navigate the page. It might be helpful if the older updates were moved onto separate pages, maybe one page per year or an archive page would make it easier to navigate. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update-archive)
* Content Source: [powerbi-docs/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update-archive.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- Thanks for your comment! I'm assigning it to the author to get back to you.

**Comment by davidiseminger** [comment]
Thanks for the suggestion @DeanGross - yes, there have been many updates, and the page does get long.
