### ISSUE TITLE
Is this feature cancelled 

### ISSUE THREAD

**Issue by bikubay** [MicrosoftDocs/powerbi-docs#1242]
is this feature cancelled ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9707e1ff-5927-e3e4-134d-8d2b04266f9c
* Version Independent ID: bec9f641-757c-b76f-4cee-c823c60222b4
* Content: [Create featured questions for Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/service-q-and-a-create-featured-questions#feedback)
* Content Source: [powerbi-docs/service-q-and-a-create-featured-questions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-q-and-a-create-featured-questions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @bikubay -- thanks for your question! Are you referring to the ability to add featured Q&A questions? If so, then no, it's not cancelled. 
For my own edification, could you say why you thought it was cancelled?

**Comment by maggiesMSFT** [comment]
Hi, @bikubay -- feel free to reopen if you have further questions.
