### ISSUE TITLE
SAP BW and support for sapcrypto

### ISSUE THREAD

**Issue by laandermsft** [MicrosoftDocs/powerbi-docs#1243]
Under https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos#configure-sap-bw-for-sso it says "The Common Crypto Library (sapcrypto) isn't currently supported.". However, in blog post from 7th June 2019 it is stated that "With the June gateway release, we are introducing support for the SAP common crypto library for Kerberos based SSO for SAP BW Application Server".
I believe this documentation should be updated :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Use Kerberos for single sign-on (SSO) to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos#configure-sap-bw-for-sso)
* Content Source: [powerbi-docs/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @laandermsft - I'll update the docs.

**Comment by mgblythe** [comment]
Fix verified, closing.
