### ISSUE TITLE
Is this supported in custom themes yet?

### ISSUE THREAD

**Issue by fpk3** [MicrosoftDocs/powerbi-docs#125]
"visualHeader": [{
                    "show": false
                }]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db547626-10e8-5ea4-e1c3-7da6c236ce9f
* Version Independent ID: 4529c3a6-1f8f-2e8c-4eaf-9bde90c4df54
* Content: [Use visual elements to enhance Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-visual-elements-for-reports#using-improved-visual-headers-in-power-bi-reports)
* Content Source: [powerbi-docs/desktop-visual-elements-for-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-visual-elements-for-reports.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @fpk3! I've alerted the author that you have a question.

**Comment by davidiseminger** [comment]
Hi @fpk3 - looks like you have product feedback or a support question, rather than a comment on docs. Please use the other link, or check out support.powerbi.com.
