### ISSUE TITLE
Licensing for R Visuals

### ISSUE THREAD

**Issue by rudzimj** [MicrosoftDocs/powerbi-docs#1251]
I can't find where this is documented, but we are receiving this error message: "R visuals are a Power BI pro feature.  Only users with a Power BI pro license can create, view or interact with R visuals." I thought any user could see R Visuals in a Premium workspace. Is this not the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9cf4ce3-f6b1-2c73-d0f9-44573242fb85
* Version Independent ID: fc6a52fd-db96-6e9f-f89a-3dea59bff3b7
* Content: [Power BI licensing in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-licensing-organization)
* Content Source: [powerbi-docs/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for the comment @rudzimj. I'll check and get back to you on the expected behavior.

**Comment by rudzimj** [comment]
This page says R visuals are visible in Premium workspace:
https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#licensing

I am trying to validate that the user who reported this is really using a Premium workspace. If so, we will raise a support ticket.

**Comment by mgblythe** [comment]
Thanks @rudzimj, closing this now, but feel free to reopen and let us know if what we have doc'd doesn't match your experience.
