### ISSUE TITLE
New reports created on powerbi.com have the new filter experience enabled. Existing reports don't

### ISSUE THREAD

**Issue by jackwoodward** [MicrosoftDocs/powerbi-docs#1252]
Per this documentation you need to enable this from desktop, that doesn't seem to be the case now? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jackwoodward -- thanks for your question! To be sure I'm answering the question you're asking: Are you asking if you no longer need to enable it in Power BI Desktop to see it in Desktop? Or are you asking if you no longer need to enable it in Power BI Desktop to see it in the Power BI service online? Thanks!

**Comment by jackwoodward** [comment]
2 questions, 1. Is the intent that new reports will have the new filter pane enabled with the Power BI service(because that is what I see)? Is there a way to enable existing reports to have the new filter pane using Power BI service?

**Comment by maggiesMSFT** [comment]
Hi, @jackwoodward -- thanks for clarifying!
1. Yes, new reports have the new filter pane enabled in the service. 
2. As of today, no. Coming very soon, yes. Stay tuned!
