### ISSUE TITLE
Column "Abreviatura" in Mexico: States map keys is wrong

### ISSUE THREAD

**Issue by GuitarLennon** [MicrosoftDocs/powerbi-docs#1253]
Hi,

The column "abreviatura" in the Mexico: states map keys table is wrong on Chiapas, Coahuila, Colima and México City.

See below.

INSERT INTO dbo.Entidades VALUES 
	('mx-zac', 'Zac.', 'MX-ZAC', 'Zacatecas', 'Zacatecas', 'ZA'),
	('mx-yuc', 'Yuc.', 'MX-YUC', 'Yucatán', 'Yucatan', 'YU'),
	('mx-ver', 'Ver.', 'MX-VER', 'Veracruz', 'Veracruz', 'VE'),
	('mx-tla', 'Tlax.', 'MX-TLA', 'Tlaxcala', 'Tlaxcala', 'TL'),
	('mx-tam', 'Tamps.', 'MX-TAM', 'Tamaulipas', 'Tamaulipas', 'TM'),
	('mx-tab', 'Tab.', 'MX-TAB', 'Tabasco', 'Tabasco', 'TB'),
	('mx-son', 'Son.', 'MX-SON', 'Sonora', 'Sonora', 'SO'),
	('mx-sin', 'Sin.', 'MX-SIN', 'Sinaloa', 'Sinaloa', 'SI'),
	('mx-slp', 'S.L.P.', 'MX-SLP', 'San Luis Potosí', 'San Luis Potosi', 'SL'),
	('mx-roo', 'Q.R.', 'MX-ROO', 'Quintana Roo', 'Quintana Roo', 'QR'),
	('mx-que', 'Qro.', 'MX-QUE', 'Querétaro', 'Queretaro', 'QE'),
	('mx-pue', 'Pue.', 'MX-PUE', 'Puebla', 'Puebla', 'PU'),
	('mx-oax', 'Oax.', 'MX-OAX', 'Oaxaca', 'Oaxaca', 'OA'),
	('mx-nle', 'N.L.', 'MX-NLE', 'Nuevo León', 'Nuevo Leon', 'NL'),
	('mx-nay', 'Nay.', 'MX-NAY', 'Nayarit', 'Nayarit', 'NA'),
	('mx-mor', 'Mor.', 'MX-MOR', 'Morelos', 'Morelos', 'MR'),
	('mx-mic', 'Mich.', 'MX-MIC', 'Michoacán', 'Michoacan', 'MC'),
	('mx-mex', 'Méx.', 'MX-MEX', 'Estado de México', 'Mexico State', 'MX'),
	('mx-jal', 'Jal.', 'MX-JAL', 'Jalisco', 'Jalisco', 'JA'),
	('mx-hid', 'Hgo.', 'MX-HID', 'Hidalgo', 'Hidalgo', 'HI'),
	('mx-gro', 'Gro.', 'MX-GRO', 'Guerrero', 'Guerrero', 'GR'),
	('mx-gua', 'Gto.', 'MX-GUA', 'Guanajuato', 'Guanajuato', 'GT'),
	('mx-dur', 'Dgo.', 'MX-DUR', 'Durango', 'Durango', 'DU'),
	('mx-dif', 'CDMX.', 'MX-DIF', 'Ciudad de México', 'Mexico City', 'DF'),
	('mx-col', 'Col.', 'MX-COL', 'Colima', 'Colima', 'CL'),
	('mx-coa', 'Coah.', 'MX-COA', 'Coahuila', 'Coahuila', 'CA'),
	('mx-chh', 'Chih.', 'MX-CHH', 'Chihuahua', 'Chihuahua', 'CH'),
	('mx-chp', 'Chis.', 'MX-CHP', 'Chiapas', 'Chiapas', 'CP'),
	('mx-cam', 'Camp.', 'MX-CAM', 'Campeche', 'Campeche', 'CM'),
	('mx-bcs', 'B.C.S.', 'MX-BCS', 'Baja California Sur', 'Baja California Sur', 'BS'),
	('mx-bcn', 'B.C.', 'MX-BCN', 'Baja California', 'Baja California', 'BN'),
	('mx-agu', 'Ags.', 'MX-AGU', 'Aguascalientes', 'Aguascalientes', 'AG')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map#feedback)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks @GuitarLennon , Great catch!  I've made the changes and set the article to republish.
Take care,
Michele
