### ISSUE TITLE
Change the screenshot of PBI Desktop download!

### ISSUE THREAD

**Issue by sjlarkin** [MicrosoftDocs/powerbi-docs#1254]
The screenshot showing which version of Desktop to select is very misleading because it has an arrow pointing to the 64-bit version when what you are recommending on this solution is the 32-bit version. People might not read all your instructions including the disclaimer that the screenshot shows the 64-bit version is selected, but that they should opt for the 32-bit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680485c7-5823-2c7f-df5d-b8c8a8205759
* Version Independent ID: 5a217642-7723-6980-28ae-e26559c24201
* Content: [Resolve Access and .XLS import issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-access-database-errors#feedback)
* Content Source: [powerbi-docs/desktop-access-database-errors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-access-database-errors.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello @sjlarkin and thanks for your post. Note that in the article, it directs you to use the version that matches your version of Desktop. Customers can experience this in either direction (32 vs 64, and 64 vs 32). The text above also clearly explains which is selected, and how to make the correct selection.
Sorry for any confusion.
