### ISSUE TITLE
Theme pattern for Filter Pane not present in Theme documentation 

### ISSUE THREAD

**Issue by awbarbeau** [MicrosoftDocs/powerbi-docs#1255]
It is not clear how to integrate the example for a theme JSON file to apply to the filter pane into the overall theme file. Can this example and the filter pane options be integrated into the Desktop Report Themes documentation with all properties defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter#feedback)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @awbarbeau -- good idea. Let's see what we can do. Thanks!
@Sujata994, here's the json part of the report themes article https://docs.microsoft.com/power-bi/desktop-report-themes#report-theme-json-file-format

**Comment by Sujata994** [comment]
@maggiesMSFT, can you assign this to @amandacofsky since she owns the theming part of the docs.

**Comment by maggiesMSFT** [comment]
Hi, @amandacofsky -- can you update the json part of the report themes article, https://docs.microsoft.com/power-bi/desktop-report-themes#report-theme-json-file-format, with the theme info for filters?
thanks!

**Comment by Sujata994** [comment]
Hi @Amanda<mailto:amac@microsoft.com>,

We got this feedback again from customers saying the themes doc is out of date and doesn’t include info about filter pane. Can you prioritize updating it?

the site linked from Power BI Desktop ( https://docs.microsoft.com/en-us/power-bi/desktop-report-themes ) is out of date and has no reference to Themes or the "outspacePane" seciton as described in the May blog post.



Thanks,
Sujata

**Comment by kfollis** [comment]
@sujata9994 and @maggiesMSFT - can you please verify that this change has been made and close if appropriate?

**Comment by maggiesMSFT** [comment]
Hi, @awbarbeau -- I see filterCard added to the JSON example in the Themes article, https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#report-theme-json-file-format, so I think your question is resolved. You can reopen this issue if not.
Thanks!
