### ISSUE TITLE
Cloud or gateway refresh not supported.

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1256]
To avoid wasting the time of Power BI users, this page should clarify in ALL CAPS in the first paragraph that PDF files are not supported as a data source in either cloud or gateway refresh scenarios. Anyone using this connector in Power BI Desktop should not be misled that it will work "just like any other data source", as most users would expect.

I certainly dont understand why that should be the case, and the error messages returned make it look like an obvious coding mistake, but it does appear to be the current reality, ref:

https://community.powerbi.com/t5/Issues/Support-for-Cloud-based-PDF-files-without-requiring-an-On/idi-p/740913

https://community.powerbi.com/t5/Service/Extract-error-from-PDF/m-p/743734#M72501

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ab70d2-6a8d-9457-9fe0-b7e5a11f7a23
* Version Independent ID: 8d847641-59f8-8914-799d-0c1c7ccad9a6
* Content: [Connect to a PDF file in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-pdf)
* Content Source: [powerbi-docs/desktop-connect-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Mike-Honey. I've assigned this issue to the doc author for review.

**Comment by danpere** [comment]
Reading the comments on https://community.powerbi.com/t5/Issues/Support-for-Cloud-based-PDF-files-without-requiring-an-On/idi-p/740913 it appears this issue has been fixed?

**Comment by Mike-Honey** [comment]
It does seem to be working now for the Cloud refresh scenario, for the one project I'm interested in.  There hasn't been any independent confirmation of that or any authoritative statement from anyone at Microsoft, so perhaps that's too early to call.

I haven't tested the Gateway refresh scenario, so I'm not sure if that is still broken.

Can't you clarify this definitively with any of your colleagues at Microsoft?

**Comment by davidiseminger** [comment]
Thanks for your comments. It appears this has been resolved, but you can always make product feature requests or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
