### ISSUE TITLE
Can I Buy PowerBI Premium Trial for 1 Hour?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1257]
Can I purchase a premium trial for 1 hour just to get a hold of what PowerBI Premium can do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-faq)
* Content Source: [powerbi-docs/service-premium-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@Anmolgan81 - you could use an A4 SKU through Power BI Embedded, which is billed by the minute.

**Comment by Anmolgan81** [comment]
But embedded is different then premium right? then how can I test this?

Regards
Anmol Ganju

________________________________

**Comment by mgblythe** [comment]
As long as you sign into Azure with an account that is also a Power BI admin, you will see the A SKU capacity under Settings->Admin portal->Capacity settings->Power BI Embedded. You can assign workspaces to this capacity as described in this doc: https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage. You will then be able to test the functionality that Power BI Premium offers with the exception of broad sharing/consumption for free users.
