### ISSUE TITLE
Code is out of date/not working.

### ISSUE THREAD

**Issue by Synikx** [MicrosoftDocs/powerbi-docs#1258]
The code in the article is not working. Specifically this line: 

`string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;`

I tried reading through all the comments and still have not been able to figure out what is wrong. It seems like this issue extends back 9 months ago, but the article has not changed. Not sure where to go from here.

**Comment by mgblythe** [comment]
Thanks @Synikx, which article is this? I see it in a few, and it might be an issue in all of them:

  \developer\walkthrough-push-data-add-rows.md (1 hit)
	Line 169:                 string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;
  \developer\walkthrough-push-data-complete-code.md (1 hit)
	Line 81:                   string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;
  \developer\walkthrough-push-data-create-dataset.md (1 hit)
	Line 164:             string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;
  \developer\walkthrough-push-data-get-datasets.md (1 hit)
	Line 165:             string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;
  \developer\walkthrough-push-data-get-token.md (2 hits)
	Line 98:            string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;
	Line 163:             string token = authContext.AcquireToken(resourceUri, clientID, new Uri(redirectUri)).AccessToken;

**Comment by Synikx** [comment]
Sorry, I clicked leave a comment on the doc page and thought this forum linked directly to it. This is the article: https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback

**Comment by mgblythe** [comment]
Thanks @Synikx, assigning the author to review.

**Comment by markingmyname** [comment]
@rkarlin @mgblythe,

This one requires engineering to evaluate.

Thank you.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @Synikx,

The article does need some updating, and I will be working with the team to update it.

In the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
