### ISSUE TITLE
Link Name for June 2019 Download needs changed

### ISSUE THREAD

**Issue by mrioux** [MicrosoftDocs/powerbi-docs#1259]
Currently the Archive download for June 2019 PowerBI says May 2019.

But downloads the correct June 2019 build. 

May 2019 version of Power BI Desktop - 32-bit
May 2019 version of Power BI Desktop - 64-bit

**Comment by mgblythe** [comment]
Thanks @mrioux. Is this a link from the docs or somewhere else?

**Comment by mgblythe** [comment]
Closing out. @mrioux - please reopen if you still see this issue.
