### ISSUE TITLE
Needs addition of using Power BI Desktop

### ISSUE THREAD

**Issue by AnthonyBe** [MicrosoftDocs/powerbi-docs#126]
This page doesn't include how to do this when using Power BI Desktop and it seems to be quite different. Please update the article to include how to use Excel workbook, stored in OneDrive for Business/SharePoint Online, as a datasource so that a scheduled refresh can be performed on the dataset once it is published.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b088da-d833-fba7-a07d-3a1a07ff557d
* Version Independent ID: 8c423288-260e-386a-4c75-4e39f7be6ff1
* Content: [Get data from Excel workbook files - Power BI](https://docs.microsoft.com/en-us/power-bi/service-excel-workbook-files)
* Content Source: [powerbi-docs/service-excel-workbook-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-excel-workbook-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for contacting us, @AnthonyBe! I've let the author know you have a comment.

**Comment by davidiseminger** [comment]
@AnthonyBe - thanks for the suggestion. Let me look into adding that.

**Comment by davidiseminger** [comment]
Thanks for your feedback @AnthonyBe - you can create a dataset in Power BI Desktop using Excel, publish it to the service, then set the refresh schedule as another way of achieving this. Let me look into whether including Desktop steps in this article would help though - thanks!

**Comment by AnthonyBe** [comment]
@davidiseminger I do think it would. My searches landed me on this page particular page, but it didn't have this particular scenario covered so I had to continue searching.

**Comment by johnz-bys** [comment]
@AnthonyBe , any luck in your searching? I ran into this page as well when I wanted to add onedrive excel file as one more source to an existing dataset, but cannot figure out how to do that in Power BI Desktop..

**Comment by AnthonyBe** [comment]
Is it possible, but unfortunately given it was 6 months ago I can't remember how I did it, and I no longer have access to the environment where I set this up to back and validate.
