### ISSUE TITLE
Importing data samples from this page to PBI

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/powerbi-docs#1260]
"... Copy the ProjectHours table below into an Excel worksheet ..."
a Web source would be a neater solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-create-and-manage-relationships#feedback)
* Content Source: [powerbi-docs/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @dudu-markovitz. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the feedback, we'll look at adding that option in the future.
