### ISSUE TITLE
Usage metrics report has stopped updating from 15 July 2019

### ISSUE THREAD

**Issue by lsabaite** [MicrosoftDocs/powerbi-docs#1261]
Created data report works good, but usage metrics report updating has stopped and right now (23 July) I have usage data only for last day 15 July.
The same situation is for different report with another sources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor usage metrics for dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/service-usage-metrics#feedback)
* Content Source: [powerbi-docs/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @lsabaite -- I'm sorry to hear that! Try the Community site https://community.powerbi.com/, and if that doesn't work, check the support site, https://powerbi.microsoft.com/en-us/support/. Good luck!
