### ISSUE TITLE
Errors when attempting to connect to app. 

### ISSUE THREAD

**Issue by Synikx** [MicrosoftDocs/powerbi-docs#1262]
In the Power BI web service I am attempting to connect to the UserVoice app and getting the error:

> Failed to update data source credentials: The credentials provided for the UserVoice source are invalid. 

I am testing this using a UserVoice account that has Full Access privileges.. I also tested it with my boss using his UserVoice account that he created the company-wide UserVoice service for and also got the same error, so I'm guessing its not an admin credential issue.

Has anyone else ran into this issue? Any ideas on how to get past this or things to try? Any help would be greatly appreciated!

EDIT: This problem is regarding the UserVoice Power BI app:  https://docs.microsoft.com/en-us/power-bi/service-connect-to-uservoice

**Comment by mgblythe** [comment]
Thanks for your comment, @Synikx. This looks like a product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
