### ISSUE TITLE
How to set the date range for the report

### ISSUE THREAD

**Issue by tkumark** [MicrosoftDocs/powerbi-docs#1264]
How to set the date range for the report? According to the screen shot How to connect step 4 where we enter the enrollment number I also see "Number Of Month". But when I try in I do not see the number of months option when entering the enrollment Number. I need to pull out the usage detail for the past 12 months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @tkumark. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by flanakin** [comment]
To change the number of months, go to Edit Queries > (select query) > Advanced Editor.

**Comment by mgblythe** [comment]
@maggieMSFT, can you update the doc or reassign as appropriate?

**Comment by maggiesMSFT** [comment]
Thanks for the suggestion, @flanakin !
Hi, @tkumark -- @flanakin has a good suggestion. It does require using Power BI Desktop instead of the Power BI service. See this article for details: 
https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights
I'll add a link to that article from this article. Thanks!
