### ISSUE TITLE
Read Only Dataset Access on Aggregate tables

### ISSUE THREAD

**Issue by GeorgeCMElliott** [MicrosoftDocs/powerbi-docs#1265]
"Users with read-only access to the dataset cannot query aggregation tables. This avoids security concerns when used with RLS. Consumers and queries refer to the detail table, not the aggregation table; they don't even need to know the aggregation table exists."

Since we now have RLS with General Availability can read-only users now utilize aggregated datasets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [Use Aggregations in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-aggregations)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @GeorgeCMElliott. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Adding an engineering contact to verify and provide clarifications.

**Comment by davidiseminger** [comment]
Adding engineering contact again.

**Comment by christianwade** [comment]
Hi @GeorgeCMElliott, yes read-only users can utilize aggregated datasets. They just can't query the agg table. Queries to the detail table are redirected to the agg table.

**Comment by christianwade** [comment]
#please-close @mgblythe
