### ISSUE TITLE
Problem Connecting to Project Online App

### ISSUE THREAD

**Issue by gohkohwee** [MicrosoftDocs/powerbi-docs#1266]
While connecting to the Project Online App, I got the following error:
Something went wrong
Failed to update model parameters. Please try again later.
Please try again later or contact support. If you contact support, please provide these details.
Activity ID: d7740ad3-dc50-44fe-8bff-5ea30228007d
Request ID: cdf76757-60b4-ff2f-b8f7-df558be1953b
Correlation ID: f7f338cd-e007-b756-56bc-ad94d9cfb127
Status code: 400
Time: Thu Jul 25 2019 11:05:30 GMT+0800 (Malay Peninsula Standard Time)
Version: 13.0.10175.153
Cluster URI: https://wabi-south-east-asia-b-primary-redirect.analysis.windows.net

Could anyone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8a7a22-e258-4da3-4c55-6ddb1085c521
* Version Independent ID: 0b3f2b88-9e73-f4dd-0f21-fe3c156a99b8
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-project-online)
* Content Source: [powerbi-docs/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-project-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @gohkohwee -- referring you to @jaduong, who may be able to help. If not, please do as the error message says and contact support with that information: https://powerbi.microsoft.com/en-us/support/
Good luck with your issue!

**Comment by jaduong** [comment]
Hi @gohkohwee, contacting support might be more helpful. My immediate thoughts are: did you type in your PWA site correctly, and select the correct language of your PWA site?

**Comment by mgblythe** [comment]
Thanks @maggieMSFT and @jadong. @gohkohwee - closing this one out with a recommendation to contact support. Thanks!
