### ISSUE TITLE
Do you need to create calculations?

### ISSUE THREAD

**Issue by tudor2it** [MicrosoftDocs/powerbi-docs#1267]
The text in the section ["Do you need to create calculations?"](https://docs.microsoft.com/en-us/power-bi/report-builder-planning-report#do-you-need-to-create-calculations) looks like a code section when it is only pure text. The same situation is with ["How are you going to deliver your report?"](https://docs.microsoft.com/en-us/power-bi/report-builder-planning-report#how-are-you-going-to-deliver-your-report) section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bc24ef0-6212-bf12-d30e-ff4e1c71da02
* Version Independent ID: c59cdb27-60fb-4ff1-937a-5a1ae4353b85
* Content: [Planning a report in Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-planning-report)
* Content Source: [powerbi-docs/report-builder-planning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-planning-report.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @tudor2it -- thanks, good catch! I'll fix those.

**Comment by maggiesMSFT** [comment]
Fixed. Thanks again @tudor2it !
