### ISSUE TITLE
publishing reports without overwriting dataset ?

### ISSUE THREAD

**Issue by Chateaux83** [MicrosoftDocs/powerbi-docs#1268]
Dear all,

is it possible to create a report (obviously from a dataset "A") and then upload w**ithout having this action creating a different dataset "B" ?** 

This is a problem, since the moment the new dataset "B" is generated, the report is not linked to "A" anymore - and "A" is the one which is regularly updated with new data. 

Is there a solution for this?
Thanks!
Luca

**Comment by maggiesMSFT** [comment]
Hi, @Chateaux83 -- Thanks for your question! Are you creating the report in Power BI Desktop? If so, see this article about the shared dataset feature, https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets.
Hope that helps!

**Comment by Chateaux83** [comment]
Hi Maggie,

thanks for the reply. I do, and I know that procedure - but that does not solve the issue. The problem is that when I edit the PBIX file (using PBI desktop and the 'main' dataset) and then publish it, it creates **another** dataset - which is not the 'main' one anymore, therefore does not get regularly updated by IT in my organization. And this 'duplication' happens every time I have to make a small edit on the PBIX clearly.

Hope I explained myself better :)

Luca

**Comment by MI77** [comment]
Luca, when you publish the second time, do you not see the message about replacing the dataset?
![image](https://user-images.githubusercontent.com/10352928/61980892-e142d500-afac-11e9-8d46-58d28f257914.png)

If the pbix name locally matches the dataset name in the service, you should be prompted if you want to overwrite like that.
