### ISSUE TITLE
DAX Basics

### ISSUE THREAD

**Issue by RavinderSunkara** [MicrosoftDocs/powerbi-docs#127]
Very useful videos and nicely blended to understand the topics

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Great, @RavinderSunkara -- glad to hear it! I'll let the writer know.

**Comment by davidiseminger** [comment]
@RavinderSunkara - glad you like it! Thanks for the nice comment.
