### ISSUE TITLE
Please add Dremio to the list.

### ISSUE THREAD

**Issue by VarunBhandary** [MicrosoftDocs/powerbi-docs#1271]
Dremio connector for Power BI is now generally available, certified and also supports 'Direct Query'.
reference: https://docs.dremio.com/client-applications/microsoft-power-bi.html

**Comment by mgblythe** [comment]
Thanks for your comment, @VarunBhandary . I've assigned this issue to the doc author for review.

@davidiseminger - can you make sure we cover Dremio in data source and DQ docs?

**Comment by davidiseminger** [comment]
Thanks @VarunBhandary - we've updated that Dremio is no longer beta, and are confirming its support for DirectQuery.

**Comment by davidiseminger** [comment]
Thanks for your inquiry. Dremio is a certified connector, which is great, but we only list built-in connectors in that list.
