### ISSUE TITLE
New single installer .exe switches

### ISSUE THREAD

**Issue by rhalabi** [MicrosoftDocs/powerbi-docs#1273]
What are the new single installer .exe switches so we can use in command line to perform silent installation or select the language to more automate the installation?

**Comment by mgblythe** [comment]
Thanks for your comment, @rhakabi. I've assigned this issue for review. Are you referring to this article: https://docs.microsoft.com/en-us/power-bi/desktop-get-the-desktop?

**Comment by rhalabi** [comment]
Yes, how to perform a silent install with the new installer?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
