### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by kanhuangats** [MicrosoftDocs/powerbi-docs#1274]
Did you guys actually test this before post it in your tutorial? 
It is not clear and this does NOT work....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a74ae11-d926-0ec2-3339-8b77c6a15965
* Version Independent ID: 48241c6e-453b-e477-46ea-99b1b5d99364
* Content: [Launch URL - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/launch-url#feedback)
* Content Source: [powerbi-docs/developer/visuals/launch-url.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/launch-url.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @Guy-Moses
* Microsoft Alias: **guymos**

**Comment by mgblythe** [comment]
Thanks for your comment, @kanhuangats. I've assigned this issue for review.

**Comment by uve** [comment]
@kanhuangats What API version do you use?
Do use see any errors when you call launchUrl method? 
Is it possible to share your source code to find an issue?

**Comment by devwheel** [comment]
what do I need to install to use this?  I'm using a new project with api version 2.6.1 and Ivisualhost is not found.  It would be nice if the NPM I command would be included in the documentation

**Comment by kfollis** [comment]
@kanhuangats and @devwheel - Thank you for submitting feedback on our documentation. We are closing this issue, but if your feedback isn’t addressed, please feel free to submit additional feedback for the page. We recently added an article, which you may find useful: https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup
