### ISSUE TITLE
"Do not enable Privacy Levels"?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#1275]
This article reads: "Do not enable Privacy Levels unless you are confident that the data source does not contain sensitive or confidential data."

Should it instead be "Do not IGNORE Privacy Levels unless you are confident that the data source does not contain sensitive or confidential data."?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-privacy-levels)
* Content Source: [powerbi-docs/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @chrisweis. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment - that passage was not clear. I've adjusted the wording to make it clear. Thanks for posting, the change will show up online within 24 hours.
