### ISSUE TITLE
Time intelligence functions in DirectQuery mode

### ISSUE THREAD

**Issue by anandavnz** [MicrosoftDocs/powerbi-docs#128]
Hi,
Is the limitations on Time Intelligence functions removed when composite mode is enabled?
The option "Allow unrestricted measures in DirectQuery mode" under DirectQuery disappears when Composite mode is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use Storage Mode in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-storage-mode)
* Content Source: [powerbi-docs/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-storage-mode.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @anandavnz -- thanks for contacting us! I've let the author know you have a question.

**Comment by davidiseminger** [comment]
@anandavnz - thanks for your question, that's a question you'll need to check with support on, at support.powerbi.com. Also please note that this is currently a Preview feature, so it may change in the future.
