### ISSUE TITLE
Python Script with Advantage database

### ISSUE THREAD

**Issue by carattikid** [MicrosoftDocs/powerbi-docs#1280]
pyodbc connection to Advantage Database does not work. The Power BI 'Python Script' data import (PythonScriptWrapper.PY) assumes that the default ODBC connection is Microsoft.

Would be great if Advantage databases are added to the supported architecture.

Details: "ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 13, in <module>
    conn = odbc.connect('DSN=ads;UID=username;PWD=passwordy')
pyodbc.Error: ('IM014', '[IM014] [Microsoft][ODBC Driver Manager] The specified DSN contains an architecture mismatch between the Driver and Application (0) (SQLDriverConnect)')
"

**Comment by mgblythe** [comment]
Thanks for your comment, @carattikid. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
