### ISSUE TITLE
Visual Element and Data Binding part unclear

### ISSUE THREAD

**Issue by suvratrai** [MicrosoftDocs/powerbi-docs#1281]
The section of document that describes visual element creation and data binding setup is not clear and the exact code to be used for setting up this custom visualization should be provided. Can you share the GitHub link of the code used for this visual for a better perspective on this topic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by mgblythe** [comment]
Thanks for your comment, @suvratrai. I've assigned this issue to the doc author for review.

**Comment by MarkMoretto** [comment]
Hi,

I had trouble, too, and looking at one of the demo repos helped to resolve some questions, but not all.  The repo is the following: https://github.com/microsoft/PowerBI-visuals-sampleBarChart

**Comment by KesemSharabi** [comment]
Hi @suvratrai

We are working to improve this document and are hoping to have a revised version by the end of the month.

**Comment by KesemSharabi** [comment]
Hi @suvratrai

Please review [Example 3](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings#example-3) from the [Understand data view mapping in Power BI visuals](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings) article.
