### ISSUE TITLE
Supported 'Column' fields

### ISSUE THREAD

**Issue by alexb5dh** [MicrosoftDocs/powerbi-docs#1282]
Are __Column__ fields like _formatString_ and _dataCategory_ supported in Push Dataset API? They are not listed in related reference: https://docs.microsoft.com/en-us/rest/api/power-bi/pushdatasets/datasets_postdatasetingroup#column

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0edb0181-a93b-1a46-0eb8-56d0262eb063
* Version Independent ID: c5833e6f-b0c1-4a92-0039-d4ef9b2b935a
* Content: [Power BI dataset properties - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/api-dataset-properties#column)
* Content Source: [powerbi-docs/developer/api-dataset-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/api-dataset-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @alexb5dh. I've assigned this issue to the doc author for review.

**Comment by markingmyname** [comment]
@alexb5dh,

No, sorry they are not yet.

There is no ETA to my knowledge.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
