### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by martynickel-at-gaffey** [MicrosoftDocs/powerbi-docs#1283]
The instructions make it easy to install the gateway app, and give no clue whatsoever how to use it in Power BI.  Somewhere between steps 3 and 4 about, you should say HOW to use the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @martynickel-at-gaffey . This issue has been assigned to the doc author for review.

**Comment by mkjohnson** [comment]
I have the same questions.

**Comment by mikemorrison111** [comment]
@mkjohnson see: https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-app

**Comment by mgblythe** [comment]
Thanks @martynickel-at-gaffey - I'll make some updates to the links. In the meantime, in addition to the gateway app article that @mikemorrison111 suggests, I recommend this article to see an end-to-end gateway scenari: https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial.

**Comment by mgblythe** [comment]
The second link to Configure goes to the article about the gateway app. I added the link to the end-to-end gateway scenario: https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial as step 4. This will go live shortly.
