### ISSUE TITLE
Sync Power BI Row level security list to MVC 

### ISSUE THREAD

**Issue by callranjithkani** [MicrosoftDocs/powerbi-docs#1284]
Hi,

My concern is I have MVC web application and PowerBI reports, I want to sync PowerBI Row level security list to my own database table. How it possible,, provide me an right solution.

**Comment by mgblythe** [comment]
Thanks for your comment, @callranjithkani. This looks like a product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com).

**Comment by mgblythe** [comment]
Docs for reference (from other open issues): https://docs.microsoft.com/en-us/power-bi/service-admin-rls and https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security
