### ISSUE TITLE
Want to get list of roles in power bi

### ISSUE THREAD

**Issue by callranjithkani** [MicrosoftDocs/powerbi-docs#1285]
Hi,

My concern is I have MVC web application and PowerBI reports, I want to sync PowerBI Row level security list to my own database table. How it possible,, provide me an right solution.

https://docs.microsoft.com/en-us/power-bi/service-admin-rls

**Comment by mgblythe** [comment]
Closing as dup of https://github.com/MicrosoftDocs/powerbi-docs/issues/1284
