### ISSUE TITLE
Sync Power BI roles to Data base

### ISSUE THREAD

**Issue by callranjithkani** [MicrosoftDocs/powerbi-docs#1286]
Hi,

My concern is I have MVC web application and PowerBI reports, I want to sync PowerBI Row level security list to my own database table. How it possible,, provide me an right solution.

https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security

**Comment by mgblythe** [comment]
Closing as dup of https://github.com/MicrosoftDocs/powerbi-docs/issues/1284
