### ISSUE TITLE
BLANK

### ISSUE THREAD

**Issue by amkumar5** [MicrosoftDocs/powerbi-docs#1288]
Why Power BI is adding BLANK to the Slicer when am selecting element/Name/Field/Column from Dimension table means it is NOT NULL, and NOT BLANK.
Default behavior should be strictly based on Dim table, it should not look at Fact table.
I cannot post this in Power bi website as I do not have Power BI account. My team is planning to migrate to Power BI so I started learning myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Tutorial - Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @v-thepet
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @amkumar5. I've assigned this issue to the doc author for review. In the meantime, are you saying you can't access the the [Power BI Community](https://community.powerbi.com) yet?

**Comment by amkumar5** [comment]
Thank you.

Yes, I cannot access Power BI community as I do not have Work Power BI account yet. My Org is planning to implement Power BI but not officially started.

Thanks,
Lakshman
________________________________

**Comment by MI77** [comment]
BLANK in a slicer usually means that you have fact table entries with no corresponding value in the dimension table. You can filter them out in the filter pane.

**Comment by mihart** [comment]
Hi @MI77 and @amkumar5 . 
I see that MI77 responded to your question. I am closing this Git Issue now.  If you have further questions, please visit community.powerbi.com.  Thank you.
