### ISSUE TITLE
Urgent answers needed on this.

### ISSUE THREAD

**Issue by Bally-Kahlon** [MicrosoftDocs/powerbi-docs#1289]
We need some urgent answers as to a. where are reports that guest users created hosted?  i.e. our premium capacity? b. why is this feature linked to export to excel from visuals.  In most cases, we need users to export to excel from visuals but not have build permissions.  c. why this was automatically enabled for all users who had read only access.  Please can someone urgently contact me about this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Create and share datasets (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-build-permissions#build-permissions-for-shared-datasets)
* Content Source: [powerbi-docs/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment @Bally-Kahlon. The author for this feature is currently out. I recommend posting your questions solution in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @Bally-Kahlon -- some answers for you, and a question.
a. where are reports that guest users created hosted? i.e. our premium capacity? 
Can you elaborate so we can provide a useful answer?
b. why is this feature linked to export to excel from visuals. In most cases, we need users to export to excel from visuals but not have build permissions. 
We clearly heard our customers’ feedback. We are actively working on a change to decouple exporting summarized data from the Build permission. In the near future it will be possible to export data from visuals without the Build permission.
c. why this was automatically enabled for all users who had read only access.
We split existing Read permissions into Read and Build for backward compatibility – we needed to ensure that users could continue using Analyze in Excel as they could before with the Read permission. This is also mentioned in the article in the section “More granular permissions”. Note that this didn’t change the security posture of a dataset – anyone who received the Build permission already had full access previously to the data model via Analyze in Excel.
Hope that helps!

**Comment by Bally-Kahlon** [comment]
Thanks @MaggiesMSFT. 
a. We provide external guests with access to reports and dashboards in our Premium capacity.  Now, these guest users can build their own reports based on the datasets.  Are these reports created by guest users added to our Premium capacity or are they added to general Power BI service under the guest users own allocation?  Bear in mind that many guest users we share with do not have any pro licensing...
b. Any timings on when this decouple will occur?
c. But they did not have the ability to build reports!!

**Comment by maggiesMSFT** [comment]
Hi, @Bally-Kahlon -- Here's the follow-up answer for a.
"External users should not be able to use shared datasets unless they are enabled via the Edit and Manage feature (see below). If it is not enabled, and the customer sees these experience enabled, ask them to call Support so we can investigate why.

This the the feature I'm referring to. 
https://powerbi.microsoft.com/en-us/blog/azure-ad-b2b-guest-users-can-now-edit-and-manage-content-in-power-bi-to-collaborate-better-across-organizations/"

Hope that helps!
