### ISSUE TITLE
Finding dataset for a given error

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#129]
It would be helpful if the documentation could answer this question:
Probably like most organisations using the Gateway, we have many users refreshing datasets via the Gateway.  I see some errors in the Gateway log files, but I don't know which datasets they relate to.  How can I find the dataset for a given error?  
The new Power BI PowerShell commandlets allow me to list all datasets in the tenant, so if I can get the dataset ID for a given error, I can contact the dataset owner, which is what I (in some cases) want to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshooting the On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot)
* Content Source: [powerbi-docs/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @cbailiss -- thanks for contacting us! The author of this article is out this week, but will be back next week. In the meantime, if you'd like you can try asking in https://community.powerbi.com/.

**Comment by mgblythe** [comment]
Thanks @cbailiss -- checking with engineering on functionality.

**Comment by arthiriyer** [comment]
@cbailiss - unfortunately this is not possible currently but do vote on ideas.powerbi.com so we can work on this feature soon.
