### ISSUE TITLE
Snapshots on this page are out of date

### ISSUE THREAD

**Issue by CheapSquier** [MicrosoftDocs/powerbi-docs#1290]
I'm using the July 2019 version and these snapshots don't match what I see. This is not how you go to Conditional Formatting.

Feedback Type:
Frown (Error)

Timestamp:
2019-08-02T02:53:11.0676127Z

Local Time:
2019-08-01T21:53:11.0676127-05:00

Session ID:
29af062e-aa0c-474c-8fbe-53b421bc02db

Release:
July 2019

Product Version:
2.71.5523.941 (19.07) (x64)

OS Version:
Microsoft Windows NT 10.0.17134.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 461808]

Peak Virtual Memory:
38.1 GB

Private Memory:
407 MB

Peak Working Set:
487 MB

IE Version:
11.885.17134.0

User ID:
3178cab2-09b7-4cc9-92ba-0eb67052367b

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
Import

Snapshot Trace Logs:
C:\Users\wadeb\Microsoft\Power BI Desktop Store App\FrownSnapShot2107016659.zip

Performance Trace Logs:
C:\Users\wadeb\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_NewWebTableInference
PBI_showIncrementalRefreshPolicy
PBI_qnaLiveConnect
PBI_keyDrivers
PBI_userFavoriteResourcePackagesEnabled

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared CmprsrInfoMTBF_file = let
    Source = Csv.Document(File.Contents("C:\Users\wadeb\OneDrive\Documents\CurrentGradClasses\7063-Practicum\CmprsrInfoMTBF_file.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StageNumber", Int64.Type}, {"Type", type text}, {"DischargePressure", Int64.Type}, {"LiquidPressure", Int64.Type}, {"SuctionPressure", Int64.Type}, {"SerialNumber", type text}, {"AmbTemp", Int64.Type}, {"Status", type text}, {"MTBF", type number}, {"MdlSubDesc", type text}})
in
    #"Changed Type";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @CheapSquier. I've assigned this issue to the doc author for review.

**Comment by dmukil** [comment]
Hi, 

Can you please provide the right screenshots. I am not able to find the conditional formatting for tables and bar charts. Please support.

**Comment by CheapSquier** [comment]
Ok, I think I found what I was referring to. Conditional formatting can ALSO be set from the "Format" tab. It's likely that I was in a hurry and only looked at the pictures. Since "Format" might be a more intuitive place to find "Conditional Formatting" I probably found it there and then complained (incorrectly) that your page was out of date. Here's a snapshot for getting to Conditional Formatting in the "Field" 
![image](https://user-images.githubusercontent.com/42678884/64069074-c3017200-cc07-11e9-99c9-2a850d106cbd.png)

I do think that it's easier to use conditional formatting from the Values well, so maybe you could tweak your snapshot to highlight that the pop-up menu shown is accessed from the Values well. Something like this: 
![image](https://user-images.githubusercontent.com/42678884/64069191-6489c300-cc0a-11e9-9559-b9c06503e60e.png)

Finally, @dmukil 's comment about '[conditional formatting for bar charts]'... is that possible? I'm not sure, conceptually, how that works.Can you set it so that bar colors change when above a certain value? Or for the top 3 values, for example? Something like that? If so, I don't see a page or a link to a page that covers that.

Thanks!

**Comment by dmukil** [comment]
@CheapSquier , I am looking for something similar to what you have mentioned above. I want to do a conditional formatting in tables( color of values get changes when it is above or below threshold) and Bar charts( Bar color get changes in a similiar way) when we do benchmark analysis. Can you share some screens on how to do this?

**Comment by davidiseminger** [comment]
Thanks for your comments. We're in the process of updating all our screenshots in documentation, as our resources allow.
