### ISSUE TITLE
Power BI integration with Oracle Transportation Management Cloud

### ISSUE THREAD

**Issue by rohankrr** [MicrosoftDocs/powerbi-docs#1291]
Hi, Just wondering since Oracle Transportation Management Cloud services do not allow access to it database through ServerName/SID/ServiceName which is prevalent on on-premise. How is this integration possible now? Thanks, Rohan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @rohankrr. This looks like a  product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com).
