### ISSUE TITLE
Make Power BI Consumer "Get Started" section even simpler!

### ISSUE THREAD

**Issue by ryanmajidi** [MicrosoftDocs/powerbi-docs#1294]
**Submitted to [site feedback](https://github.com/MicrosoftDocs/feedback/issues/1769) by @SMHolck **

Some of the content on the landing page for Consumers of Power BI feels like too deep of a dive. There is no "guided learning" yet for Consumers, which would also be great!

I was so excited today to see that there is now documentation for Consumers of Power BI. https://docs.microsoft.com/en-us/power-bi/consumer/power-bi-consumer-landing Love it! Not sure how long it has been hiding, but this is a piece I've been wanting for awhile. I clicked around on it a little, and I have concerns about the Getting Started section. It seems too deep a dive for a first look.

For example, https://docs.microsoft.com/en-us/power-bi/service-get-started is the first link. But it is targeted toward report designers and data modelers, not toward consumers. If I send my C level execs here, they won't stay long. Too much to read and they still can't schedule their own meetings - build a report, get data? I don't think so. They just want to understand how to get to dashboards and reports and then navigate between them. They want to know how to click on a dashboard to get to the report and then back out again to look at another item on the dashboard. They want to know how to filter, bookmark, drill in/out. They want to know who to call if the numbers excite them (good or bad).

Describe the solution you'd like
Approach the documentation from a consumer perspective. I'm new. I'm never planning to create reports and dashboards or get data. I just want to see what others have built for me.

I would:

Remove the link to "Take a Tour of Power BI Service"
Optionally replace it with an overview of the "Power BI Ecosystem" but put that link further down or in a section that says "What features do I get if I buy Power BI?"
Move the multi-link line that says "What's the difference: Reports, Dashboards, Apps" to the "View Content" section and have it go to a single page that actually explains the difference instead of making the user read 3 whole separate sections.
Add a link under "Get Started" to "What you can see as a Power BI Consumer" that shows a sample app, sample dashboard, sample report and explains difference between apps and work spaces (if there is one any more?)
The "Sign In / Sign Out" documentation would actually be confusing to my Office 365 users who had a license assigned to them and should just use their O365 username/password. I'm not really sure what to tell you there. Maybe add instructions for trying your O365 username/password first.
Describe alternatives you've considered
Not really sure what to put here. This was my first consideration. I'd appreciate other perspectives from other folks who are trying to get Power BI adopted in their company.

Writing my own documentation/training - but my company doesn't have a BI program so I have to wait and charge it to the first department that requests it in their project budget.
Send people to outside training - not sure there's much for consumers and again, C level execs wouldn't go for it
Become a content author for Linked In, Coursera, EdX, Pluralsight and make $$ so I can afford a training program at my office?
Additional context

image

**Comment by mgblythe** [comment]
Thanks for the detailed feedback @ryanmajidi, we really appreciate it! I'm assigning this item to the author for review, but in the meantime, please check out the new [consumer learning path](https://docs.microsoft.com/en-us/learn/paths/consume-data-with-power-bi/). Feel free to open another issue with feedback on that if you like. Thanks again.

**Comment by mihart** [comment]
Hi @SMHolck and @ryanmajidi 
Wow, this is awesome feedback.  We are about to do a rewrite on all the consumer content to match the new look.  I will definitely use your feedback.  If you send me your email address, I'll add you as a regular reviewer.  Thanks for taking so much time and thought, I appreciate it.
