### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Immortalsonly** [MicrosoftDocs/powerbi-docs#1296]
On page; https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization#create-and-publish-your-paginated-reports
Paragraph; Create and publish your paginated reports
Error; ...the report needs to _jave_ a Power BI Pro license to publish to ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505b774c-e4e2-78b0-dad9-ae19c9240004
* Version Independent ID: a5dac00f-35c2-a87d-3224-c96682d2ffb7
* Content: [Embedded analytics to embed Power BI content in your application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization#create-and-publish-your-paginated-reports)
* Content Source: [powerbi-docs/developer/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for catching that issue, @Immortalsonly! I'll fix this today.

For future reference - you can also edit articles directly. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer, who will sign off and get it published. Thanks again!

**Comment by mgblythe** [comment]
Verified fix

**Comment by Immortalsonly** [comment]
> Thanks for catching that issue, @Immortalsonly! I'll fix this today.
> 
> For future reference - you can also edit articles directly. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer, who will sign off and get it published. Thanks again!

Thanks for the Tip! i will do this in the future.
