### ISSUE TITLE
AI Insights not accessible via Azure A SKUs

### ISSUE THREAD

**Issue by sachatomey** [MicrosoftDocs/powerbi-docs#1297]
It would be good to update the Technical/Features section to indicate what technical features are and are not available across the SKUs.  For example, AI Insights + Auto ML are only available to Power BI Premium and not the Azure 'A' SKUS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a447889-379d-3ded-9ab9-313c4f55a667
* Version Independent ID: 4f8e3f79-5025-919a-7282-8a63dda6bc8d
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq#feedback)
* Content Source: [powerbi-docs/developer/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @sachatomey. I've assigned this issue to the doc author for review.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @sachatomey, 

Thanks you for your feedback, I have forwarded your request to the relevant project manager. We will look into adding technical information to the SKU list in this article.
