### ISSUE TITLE
Dataflow Environment Management

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#1298]
Hello,

I was looking in the documentation : what's about migrating dataflows between different environment ? (Dev to test to Prod....) Do I have to recreate it or is there any mechanism that could be documented here ? Maybe using export json or something else ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating and using dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-create-use)
* Content Source: [powerbi-docs/service-dataflows-create-use.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-create-use.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @llocans. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @Ilocans. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by Ilocans** [comment]
Hi,

You explain in your documentation how to connect, to use dataflows,... It seems logic you explains how to work with dataflow with different environment: Dev, Test, Prod,... What is the best practice you recommend to move between them ?
