### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by sprengmi** [MicrosoftDocs/powerbi-docs#1299]
Could you clarify "You can create reports in app workspaces that are based on datasets in a different workspace. However, you can't create an app for a workspace that contains those datasets."
The way this is phrased is not very clear to me.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f09aabd-9f0d-f94d-6e0a-7c9a9884dd71
* Version Independent ID: b4528bd4-f503-3cc2-52ec-9257e485555e
* Content: [Use datasets across workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-gb/power-bi/service-datasets-across-workspaces#feedback)
* Content Source: [powerbi-docs/service-datasets-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @sprengmi. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @sprengmi -- good question. It's not clear, and it's not true. It should read:
"You can create a report in an app workspace that is based on a dataset in a different workspace. However, when you create an app for that workspace, you can't include the report based on the shared dataset in the app."
Does that make sense?

**Comment by sprengmi** [comment]
I think so.
So basically the functionality allows us to create reports based on shared datasets across *workspaces*. But a shared dataset can NOT be used in reports across multiple apps?

**Comment by maggiesMSFT** [comment]
At this time, yes. I'll update the article. 
Always a good idea to let the product team know your thoughts on features! https://ideas.powerbi.com/forums/265200-power-bi

**Comment by sprengmi** [comment]
Thanks for the response!

**Comment by sprengmi** [comment]
Hi @maggiesMSFT. Just wanted to follow up. I tested this out and it seems it does actually work unless I'm missing something:
- Created two new workspaces
- Created a data source in Workspace A
- Published the Workspace A App
- Connected to the dataset from Workspace A in Workspace B and saved a new report in Workspace B
- Published the Workspace B App, ensured 'included in app' was checked for the report
- Both apps now have the Report based on the shared dataset available....

Thanks for your help, we just want to be sure we understand the limitation before moving forward.

**Comment by maggiesMSFT** [comment]
@sprengmi , you are right. I tried it yesterday and it didn't work, don't know why. But I just tried it again, and it worked. Thanks for checking!
I'll update the article to reflect that.

**Comment by maggiesMSFT** [comment]
@sprengmi -- Ah ha! I've discovered why I had 2 different experiences. Turns out if I’m a member of workspace B that contains a report, but not a member of workspace A that contains its dataset, I can publish an app from workspace B, but it can’t include that report.

**Comment by maggiesMSFT** [comment]
OK, @sprengmi -- published the update today. Thanks for asking the original question!
