### ISSUE TITLE
Useless!!!

### ISSUE THREAD

**Issue by JuanPerezHdz** [MicrosoftDocs/powerbi-docs#130]
Useless if you can't publish to power bi service!! I need to use many to many relationships and I can only use it on Power Bi Desktop. Please don't release something if it's not going to work properly!! I was so excited about this new feature and I'm already using M:M but now I have to change everything!! So disappointed!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use Composite Models in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Sorry to hear it, @JuanPerezHdz! I recommend clicking the Product Feedback link at the bottom of this page instead of the Content Feedback link. Thanks!
