### ISSUE TITLE
Error: "Only Pro users can... consume content from app workspaces"

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#1301]
The following snippet seems inaccurate in this page: "Only Pro users can publish to and consume content from app workspaces"

Reason: I understand that the new Viewer role in Power BI Workspaces v2 allows non-Pro users to view content in workspaces without a Pro license.  Please confirm and update.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9cf4ce3-f6b1-2c73-d0f9-44573242fb85
* Version Independent ID: fc6a52fd-db96-6e9f-f89a-3dea59bff3b7
* Content: [Power BI licensing in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-licensing-organization#manage-power-bi-free-licenses)
* Content Source: [powerbi-docs/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @chrisweis, I'll take a look at this one.

**Comment by mgblythe** [comment]
Thanks @chrisweis - updating this sentence to read "Only Pro users can publish content to app workspaces".
