### ISSUE TITLE
The SwaggerHub link provided by the documentation is not available, can I also get a list of the APIs available to the report server. Only individual examples are provided in GitHub.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1302]
Hi team, 
I'm moving this here because the user is reporting missing information in the documentation
Original post: https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/33

I'm pasting a rough translation since the user wrote in their native language. 

@r48 commented 4 days ago
The SwaggerHub link provided by the documentation is not available, can I also get a list of the APIs available to the report server. Only individual examples are provided in GitHub.

@r48 commented 19 hours ago
The main appeal is to understand which APIs are exposed by Powerbi's report server in order to manipulate the report server through external tools.

The problem encountered: In the online documentation of the powebi report server, only the description of the report server api list is found in the current article, and the current article only mentions that the api list can be obtained from SwaggerHub, but the SwaggerHub link provided by the article is not available. . Therefore, I still don't know which APIs are provided by the powebi report server. What parameters do these APIs have, and how to combine these parameters to call these APIs.
Thanks for the reply! If you need further explanation, please indicate the place to explain, so that I can refine the issue description in a targeted manner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6a98d6-e7d6-3d8b-5d15-b0dbf74fbd69
* Version Independent ID: 12688481-06ff-fb15-7eae-21e925492b40
* Content: [Develop with the REST APIs for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/rest-api)
* Content Source: [powerbi-docs/report-server/rest-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/rest-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @r48 and @CeciAc -- is this the link you're trying? https://app.swaggerhub.com/apis/microsoft-rs/PBIRS/2.0
It is working for me.

**Comment by r48** [comment]
Hi, the link is  https://app.swaggerhub.com/apis/microsoft-rs/PBIRS/2.0 and it is working for me now too . Thank you!

**Comment by maggiesMSFT** [comment]
Hi, @r48 -- glad to hear it's working for you! Closing this issue.
