### ISSUE TITLE
Sign up for a trial section not for Pro?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#1303]
It looks like the steps for signing up for a trial may no longer be valid?  If non-Pro users (who have never had a Pro trial) use that link, they get the error "No need to sign up. You already have a license for Microsoft Power BI." and they don't begin a Pro trial.  Please confirm, is this document accurate?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up for Power BI as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/service-self-service-signup-for-power-bi)
* Content Source: [powerbi-docs/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
The doc is incorrect - I'll be updating it shortly. If you already have a free license and you need a pro trial, go into **Settings** (gear icon on the top bar) > **Manage personal storage** and select the **Pro Trial** option.

**Comment by chrisweis** [comment]
Thanks @mgblythe !  Really appreciate you keeping these docs accurate!
