### ISSUE TITLE
Enhanced compute engine

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#1304]
Hi, are you planning to add documentation about recently released Enhanced compute engine?
https://powerbi.microsoft.com/en-us/blog/power-bi-dataflows-june-2019-feature-summary/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-workloads#feedback)
* Content Source: [powerbi-docs/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @MartinKDK, I'll take a look at this one to update in the topic referenced and/or the dataflows docs.

**Comment by mgblythe** [comment]
Thanks @MartinKDK, I added the enhanced engine info + updated for latest settings for all workloads.
