### ISSUE TITLE
Incorrect information on metadata 

### ISSUE THREAD

**Issue by niball** [MicrosoftDocs/powerbi-docs#1306]
Under Limitation 

Multi-Geo doesn't result in better performance in general. Loading reports and dashboards still involves requests to the home region for metadata.

It is incorrect that home region is used for metadata. Can you fix this and add the correct behavior

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-multi-geo#feedback)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @niball . This issue has been assigned to the doc author for review.

**Comment by niball** [comment]
Any update @mgblythe

**Comment by mgblythe** [comment]
#reassign @DavidMagarMS for confirmation on this issue.

**Comment by kfollis** [comment]
@niball - Thank you for submitting feedback on our documentation. This article has been recently updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page. You may also edit the page directly and your changes will be reviewed by a writer before publishing.
