### ISSUE TITLE
Personal Bookmarks feature needs it's own page

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1307]
It's now 8 months after the release of the Personal Bookmarks feature, which I expect is used more often than the Power BI Desktop bookmarks feature.  Yet it doesn't have it's own page in the documentation, just a link to a blog post?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Mike-Honey . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion. We'll look into adding a separate page for personal bookmarks to our queue.
