### ISSUE TITLE
asset allocation

### ISSUE THREAD

**Issue by BIAgents** [MicrosoftDocs/powerbi-docs#1308]
get data from data bases

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964f91f6-81f3-8d83-4c73-d5ad8a7e77c5
* Version Independent ID: 7027312f-a8e3-a8c6-cb38-1200790271dc
* Content: [Certify datasets (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-certify#feedback)
* Content Source: [powerbi-docs/service-datasets-certify.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-certify.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by BIAgents** [comment]
$ git push updates

**Comment by maggiesMSFT** [comment]
Hi, @BIAgents -- did you make a change to the article? I'm not seeing it. 
thx

**Comment by maggiesMSFT** [comment]
Closing this. Please reopen if you have a question or suggestion.
