### ISSUE TITLE
Confusion about Persistent Filters feature

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1309]
References to "In the Power BI service, reports keep any changes you make in the Filters pane. " and "Reset filter to default" should be clear that this is an option in the report design, which the report author can disable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1465b3a1-a6de-e2f3-154c-817ea13aa4f0
* Version Independent ID: 20ea6924-2307-d6ef-d601-7f949fe58944
* Content: [Tour the report Filters pane - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-filter)
* Content Source: [powerbi-docs/consumer/end-user-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @Mike-Honey . This issue has been assigned to the doc author (me) for review.
