### ISSUE TITLE
Useless!!

### ISSUE THREAD

**Issue by JuanPerezHdz** [MicrosoftDocs/powerbi-docs#131]
Useless if you can't publish to power bi service!! I need to use many to many relationships and I can only use it on Power Bi Desktop. Please don't release something if it's not going to work properly!! I was so excited about this new feature and I'm already using M:M but now I have to change everything!! So disappointed!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477d54a5-8a27-ae63-9887-9801639962e8
* Version Independent ID: 8a2c56c0-cf25-bd2d-8de9-207ccc1e83d1
* Content: [Many-to-many relationships in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-many-to-many-relationships)
* Content Source: [powerbi-docs/desktop-many-to-many-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-many-to-many-relationships.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @JuanPerezHdz - thanks for your comment. Did you see that this is a Preview feature? That means it's not a generally available (GA) feature (yet), and is out there for feedback and to test with users. Limitations such as being unable to publish to the Power BI service may be removed when it reaches GA.

**Comment by erapade** [comment]
As my data model is cluttered with M2M relationships, I can't wait for the GA to be able to publish in the Power BI Service. Any planned date for a GA?
