### ISSUE TITLE
Update for new Filter Pane

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1310]
The new Filter Pane became the default as of July 2019, so most of the screen-shots above are out-of-date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1465b3a1-a6de-e2f3-154c-817ea13aa4f0
* Version Independent ID: 20ea6924-2307-d6ef-d601-7f949fe58944
* Content: [Tour the report Filters pane - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-filter)
* Content Source: [powerbi-docs/consumer/end-user-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @Mike-Honey . This issue has been assigned to the doc author for review. We're working on updating screenshots asap.

**Comment by mihart** [comment]
Hi @Mike-Honey 
We're currently updating all visual articles to include the new look.  You should see the new screenshots appearing by end of the month. 
Thank you for your input, we do appreciate it.
