### ISSUE TITLE
Options and settings, especially Persistent Filters

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1311]
From the File menu, there are many important features controlled by the Options and settings / Options window. That needs it's own page (or several pages) somewhere in the Power BI Desktop section. Under Reference?

Most critical & urgent is to describe the Persistent Filters feature (in the Current File / Report Settings section) and note that it is turned on by default. This (very poor IMO) decision is causing so much confusion and angst between report authors and consumers - as it is  undocumented (besides a very old blog post), there is just a lot of finger pointing and confusion.  At least documenting the feature clearly would go some way towards reducing that unnecessary stress.

https://powerbi.microsoft.com/en-us/blog/announcing-persistent-filters-in-the-service/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-what-is-desktop)
* Content Source: [powerbi-docs/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-what-is-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Mike-Honey . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
