### ISSUE TITLE
tree mapping

### ISSUE THREAD

**Issue by saviourofdp** [MicrosoftDocs/powerbi-docs#1312]
There's no mention here of the `tree` mapping, which is evident in the image on [Exploring the dataview](https://docs.microsoft.com/en-gb/power-bi/developer/custom-visual-develop-tutorial#exploring-the-dataview)
![image](https://user-images.githubusercontent.com/9444683/62686630-00822f00-b9bd-11e9-8625-d3b8a71575cf.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595c371b-cced-07b1-2581-07a96b4c5af0
* Version Independent ID: bebdf7f8-3ea0-cea4-4c9f-9b029020ef9f
* Content: [Data view mappings - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/visuals/dataview-mappings#feedback)
* Content Source: [powerbi-docs/developer/visuals/dataview-mappings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/dataview-mappings.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @asander
* Microsoft Alias: **asander**

**Comment by mgblythe** [comment]
Thanks for your comment, @saviourofdp. I've assigned this issue to the doc author for review.

**Comment by uve** [comment]
@saviourofdp currently, **tree** option isn't supported by Custom Visuals.

**Comment by uve** [comment]
#please-close @kfollis
