### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by nallasamyponnusamy** [MicrosoftDocs/powerbi-docs#1315]
The link " Load Testing Power BI Applications with Visual Studio Load Test" is broken, can you fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38feecc0-9338-8359-5ce0-d2120c0b0004
* Version Independent ID: 96a236e6-2389-dc75-f5c5-4ead7dbd5c30
* Content: [Optimize Microsoft Power BI Premium capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-capacity-optimize#feedback)
* Content Source: [powerbi-docs/service-premium-capacity-optimize.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-capacity-optimize.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @nallasamyponnusamy . This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Thanks @nallasamyponnusamy - fixing now. The correct link is https://www.youtube.com/watch?v=UFbCh5TaR4w
