### ISSUE TITLE
Azure App registration setting unclear

### ISSUE THREAD

**Issue by rudzimj** [MicrosoftDocs/powerbi-docs#1316]
This sample requires a Redirect uri of http://localhost:13526/Redirect on the App registration. This isn't really mentioned as a step, and it is confusing because Cloud.config has the setting for RedirectUrl as "http://localhost:13526/" and then appends "Redirect" to the URL when used in the code. I would suggest calling out "Set the Redirect uri to http://localhost:13526/Redirect" in the "Register an application in Azure Active Directory" paragraph, and then show how to confirm the setting in step 3 of "Embed your content by using the sample application" section by adding RedirectUrl as another setting in the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505b774c-e4e2-78b0-dad9-ae19c9240004
* Version Independent ID: a5dac00f-35c2-a87d-3224-c96682d2ffb7
* Content: [Embedded analytics to embed Power BI content in your application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization#embed-your-content-by-using-the-sample-application)
* Content Source: [powerbi-docs/developer/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @rudzimj. I've assigned this issue to the doc author for review.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @rudzimj,

Thank you for the suggestion.

I'm reviewing the article and will update it shortly.

**Comment by KesemSharabi** [comment]
Hi @rudzimj,

Thank you for your comment.

I added a sentence about the redirect issue in the [Register an application in Azure Active Directory](https://docs.microsoft.com/power-bi/developer/embed-sample-for-your-organization#register-an-application-in-azure-active-directory) section of the [Embed Power BI content into an application for your organization](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization) tutorial.
