### ISSUE TITLE
Power BI API Users link gives 404

### ISSUE THREAD

**Issue by Dmitrij-J** [MicrosoftDocs/powerbi-docs#1318]
Link "https://docs.microsoft.com/en-us/rest/api/power-bi/users" gives 404.

Please correct it!

Thank you!

**Comment by mgblythe** [comment]
Thanks @Dmitrij-J - I'll look into this.

**Comment by mgblythe** [comment]
This is resolved now, closing out the issue. Thanks again @Dmitrij-J
