### ISSUE TITLE
M

### ISSUE THREAD

**Issue by Analytis** [MicrosoftDocs/powerbi-docs#132]
M

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff1b7488-9278-5b12-2025-9d602c113ecd
* Version Independent ID: dbe2cb00-7ab7-5c58-e902-234f0f3ae39c
* Content: [Connect to Google Analytics with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-google-analytics)
* Content Source: [powerbi-docs/service-connect-to-google-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-google-analytics.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi @Analytis -- I"m not sure what you're looking for. Can you elaborate? Thanks!
