### ISSUE TITLE
Typos, clarity issues

### ISSUE THREAD

**Issue by Industry** [MicrosoftDocs/powerbi-docs#1322]
Tons of mistakes in the text and not a very clear tutorial. Please remake

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7#feedback)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @Industry. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments - we've gone through the tutorial and fixed the typos, and will look at rewriting it when resources allow.
