### ISSUE TITLE
Need IP's associated with URL's

### ISSUE THREAD

**Issue by DonPetry-EY** [MicrosoftDocs/powerbi-docs#1323]
Please provide a link to the actual IP ranges associated with each of these services.  Similar to the Azure DataCenter Whitelists/Service Tags.  Without this, we cannot configure outbound NSG's.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297c1372-b1bb-57c4-9c31-840b4cad2c37
* Version Independent ID: 0bb282a3-4aa6-1094-d8a4-652ec726734f
* Content: [Power BI URLs for whitelisting - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-whitelist-urls#feedback)
* Content Source: [powerbi-docs/power-bi-whitelist-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-whitelist-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @DonPetry-EY. I’ll add this request to our docs backlog.

**Comment by mgblythe** [comment]
@DonPetry-EY - The only info I can provide at this point is that Power BI uses all the Azure IP address ranges.

**Comment by DonPetry-EY** [comment]
Hi there… I see you just closed this?

Can we take another look at this?  For our InfoSec Teams, indicating that Power BI is somewhere inside the Azure IP address range is a non-starter.  That same IP range also houses every other organization’s Azure hosted apps and data.

As with other Azure services, we would like:

  1.  A definition of the public IP’s required for the service.
  2.  An NSG service tag making it easy to restrict/allow access to the Power BI service.

Please re-open this request and provide the requested information.

**Comment by DonPetry-EY** [comment]
Hey Don,

I would imagine the Public IP’s aren’t listed because of the complexity of Power BI relying on multiple components that feed into it and potentially IP’s being added over time. I haven’t received a concrete answer on Power BI for this scenario, but I’ve had this question across other services such as Intune/Autopilot, Device Registration, etc. and that was usually the case. I’ll let Michael comment further in case he has any other information.

On your second item below, I already contacted the Product Group to check on a Power BI Service Tag and it seems this is on the roadmap already, but there’s not currently at ETA yet.

Thanks,

Sean Sewell
Technical Account manager | Microsoft Enterprise services
Work: (980) 776-2898 | Cell: (404) 702-4092 | Sean.Sewell@microsoft.com<mailto:Sean.Sewell@microsoft.com> | Skype IM: sesewell@microsoft.com<sip:sesewell@microsoft.com>
Premier Support: (800) 936-3100 | https://premier.microsoft.com/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpremier.microsoft.com%2F&data=02%7C01%7CSean.Sewell%40microsoft.com%7Cbca91199f7364797b8bf08d66c444e25%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636815437955592836&sdata=lwJkmvYDUD414ERYoHe2A66Vg5vGYW2jlDy1RExTUhg%3D&reserved=0>
How to open an Azure Support Case<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-supportability%2Fhow-to-create-azure-support-request&data=02%7C01%7CSean.Sewell%40microsoft.com%7Cbca91199f7364797b8bf08d66c444e25%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636815437955592836&sdata=SAt702Gb2AuQ%2F5ABabxcnf4kGO7KcFnfRsl4M9jrSw8%3D&reserved=0>

From: Don Petry <don.petry@ey.com>
Sent: Tuesday, September 10, 2019 5:55 PM
To: MicrosoftDocs/powerbi-docs <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Sean Sewell <Sean.Sewell@microsoft.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Need IP's associated with URL's (#1323)

Hi there… I see you just closed this?

Can we take another look at this?  For our InfoSec Teams, indicating that Power BI is somewhere inside the Azure IP address range is a non-starter.  That same IP range also houses every other organization’s Azure hosted apps and data.

As with other Azure services, we would like:

  1.  A definition of the public IP’s required for the service.
  2.  An NSG service tag making it easy to restrict/allow access to the Power BI service.

Please re-open this request and provide the requested information.

**Comment by Jayesh040** [comment]
Hi @DonPetry-EY, We are having same scenario.
Could you please help us if you got any IP range list to PowerBI Online service. That would be very helpful.
