### ISSUE TITLE
Does RLS Support Import connection methods for SAP-BW?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1324]
Does RLS support Import connection methods for SAP-BW server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @Anmolgan81. I’ll add this request to our docs backlog. In the meantime, you can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by mgblythe** [comment]
Adding @MI77 to see if he has an answer for this one.

**Comment by MI77** [comment]
Made PR https://github.com/MicrosoftDocs/powerbi-docs/pull/1451

#please-close @mgblythe - can you edit for clarity please? :)

**Comment by mgblythe** [comment]
Thanks @MI77. @Anmolgan81 - here's the new FAQ entry:

**Question:** My data source already has security roles defined (for example SQL Server roles or SAP BW roles). What is the relationship between these and RLS?  

**Answer:** The answer depends on whether you're importing data or using DirectQuery. If you're importing data into your Power BI dataset, the security roles in your data source aren't used. In this case, you should define RLS to enforce security rules for users who connect in Power BI. If you're using DirectQuery, the security roles in your data source are used. When a user opens a report Power BI sends a query to the underlying data source, which applies security rules to the data based on the user's credentials.

**Comment by Anmolgan81** [comment]
So RLS is supported in sap bw?

Regards
Anmol Ganju

________________________________
