### ISSUE TITLE
Need update on limitations? 

### ISSUE THREAD

**Issue by MichaelDotEarly** [MicrosoftDocs/powerbi-docs#1326]
I believe this one is not: Export using Underlying data won't work if The data source is an Analysis Services live connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc572957-04b2-9512-afb5-11bc0393cf66
* Version Independent ID: 70c74633-44df-466b-879c-4ae5c1524fc1
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @MichaelDotEarly . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @MichaelDotEarly ,
Wanted to let you know that the limitation has been removed from the documentation.  Thank you for letting us know.
