### ISSUE TITLE
Incorrect syntax for DATETIME

### ISSUE THREAD

**Issue by dsujs** [MicrosoftDocs/powerbi-docs#1327]
I get an incorrect syntax error for the DATETIME strings in the example below:

CustomFiscalPeriods =
DATATABLE (
"Fiscal YearNumber", INTEGER,
"FirstDayOfYear", DATETIME,
"LastDayOfYear", DATETIME,
{
{ 2016, "2015-06-28", "2016-07-02" },
{ 2017, "2016-07-03", "2017-07-01" },
{ 2018, "2017-07-02", "2018-06-30" },
{ 2019, "2018-07-01", "2019-06-29" }
}
)
 
The syntax for "2015-08-16" is invalid.

I tested with Power-BI versions of June and May as well what gives the same error message!
My Input method is:
English (United States) and Belgian (Period) keyboard.

![Annotation 2019-08-14 094916](https://user-images.githubusercontent.com/54027192/63013960-b651ef80-be8d-11e9-9f4a-a5a3a41ae955.png)

**Comment by mihart** [comment]
Thanks for your comment, @dsujs . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
