### ISSUE TITLE
Filter sidebar

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1328]
**Translated**
@NooWinFr commented on [Wed Aug 14 2019](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/35)

Hello, the article does not seem to indicate how to modify the theme of the filter sidebar.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [在 Power BI Desktop 中使用报表主题 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-report-themes#report-theme-json-file-format)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Wed Aug 14 2019](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/35#issuecomment-521123112)

Hello, @NooWinFr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
This issue was Machine translated

**Comment by ToddChitt** [comment]
Check the Power BI Blog post for the May update. There is info in there about applying a theme to the Filter Pane sidebar.

**Comment by davidiseminger** [comment]
The Themes document has been updated recently, reflecting many updates that include addressing this question.
