### ISSUE TITLE
Copy and paste between reports has the wrong image

### ISSUE THREAD

**Issue by evilches** [MicrosoftDocs/powerbi-docs#1329]
It is a duplicate of the hiding a report page image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f750471-143b-f0fe-3d92-0bdaaa06dcc1
* Version Independent ID: 66cc67fb-28ff-4a0c-34f0-f688369cc15c
* Content: [Report View in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-view#feedback)
* Content Source: [powerbi-docs/desktop-report-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @evilches -- thanks for the heads-up! I've assigned this to the author to update.

**Comment by davidiseminger** [comment]
You're right - sorry about that. The image was incorrect, and needed to be moved a few sentences down. I've fixed that now, will show up online in ~24 hours. Thanks!
