### ISSUE TITLE
Please add Azure Databricks to this list.

### ISSUE THREAD

**Issue by yoshihirok** [MicrosoftDocs/powerbi-docs#133]
Power BI Desktop can use Azure Databricks as the data source of DirectQuery.
and Azure Databricks based on Spark,
so Please add Azure Databricks to this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources#feedback)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @yoshihirok -- thanks for your feedback! I've let the writer know.

**Comment by davidiseminger** [comment]
Thanks for your comment and update, I've added Azure Data Bricks to the list. Should show up in the next couple of days. Thanks @yoshihirok

**Comment by yoshihirok** [comment]
Thanks @maggiesMSFT , @davidiseminger
