### ISSUE TITLE
Does not work on private repos

### ISSUE THREAD

**Issue by chris-schulz** [MicrosoftDocs/powerbi-docs#1330]
Hi, 

This only seems to work for public repos and therefore cant be used within our (or most) enterprise solutions. Can you advise on any roadmap to have this working with private repos?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 076ce105-645c-cf91-44b7-4e2192eed874
* Version Independent ID: fb6358ab-0940-7ced-1036-2ddc49b78ce5
* Content: [Tutorial: Connect to a GitHub repo with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-tutorial-connect-to-github#feedback)
* Content Source: [powerbi-docs/service-tutorial-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-tutorial-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- thanks for your question! Hmmm. I specifically chose a public repo for this article so folks could follow along, but I can create a report for our private content repo, too. In our case, I have to add "-pr" to the end of the repo name. Not sure if that's a GitHub convention, or just our internal convention. Can you try it with your private repo name?

**Comment by chris-schulz** [comment]
> Hi, @chris-schulz -- thanks for your question! Hmmm. I specifically chose a public repo for this article so folks could follow along, but I can create a report for our private content repo, too. In our case, I have to add "-pr" to the end of the repo name. Not sure if that's a GitHub convention, or just our internal convention. Can you try it with your private repo name?

No success I'm afraid...
```
MessageWeb.Contents failed to get contents from 'https://api.github.com/repos/<myreponame>/reporting-pr' (404): Not Found Table: RepoDetails.
Cluster URIWABI-AUSTRALIA-SOUTHEAST-redirect.analysis.windows.net
Activity IDa97b9064-d1be-4d29-8bd4-8c03cae3fbe6
Request ID460cd385-9c98-f4a8-b2a5-ad5bace2a79c
```

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- I'm checking with someone else. In the meantime you can try the Power BI community and support sites, 
https://community.powerbi.com/
https://powerbi.microsoft.com/en-us/support/

**Comment by chris-schulz** [comment]
Yep, that's where I started... crickets... :(

**Comment by maggiesMSFT** [comment]
OK. Well, I've sent your question to someone else. We'll see what I get back.

**Comment by ZynThaX** [comment]
Was there ever a fix for this?
I'm having problem connecting to a private repository that I'm admin for.

I'm getting the following error:


<span ng-transclude="" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, wf_segoe-ui_normal, helvetica, arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 249, 174); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span ng-bind="lastRefreshStatus">Last refresh failed: Mon May 17 2021 18:43:32 GMT+0200 (Central European Summer Time)</span><br><span ng-bind="lastRefreshFailureMessage">There was an error when processing the data in the dataset.</span></span><span ng-if="nameValuePairs!=null" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, wf_segoe-ui_normal, helvetica, arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 249, 174); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Processing error: | The column 'Column1' of the table wasn't found.
-- | --
Cluster URI: | WABI-NORTH-EUROPE-K-PRIMARY-redirect.analysis.windows.net
Activity ID: | 26135b3c-faf4-2cd6-ab23-5846b39ed6dd
Request ID: | e6470c97-7fea-8eba-94f0-12cc394b4351
Time: | 2021-05-17 16:43:32Z

</span>

Inside github the Power-BI is approved as it should be:
![bild](https://user-images.githubusercontent.com/1674831/118526768-dd171700-b740-11eb-8257-221d15badc1a.png)
