### ISSUE TITLE
Something more user friendly?

### ISSUE THREAD

**Issue by sandramcg** [MicrosoftDocs/powerbi-docs#1331]
Users don't want to click on text, only to have to then click on a long hyperlink from a popup window. Is there a more user friendly way of adding a link to a report page? I'm thinking a clickable shape rather than a text box.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21813211-4c66-33dd-94bd-576addc9f910
* Version Independent ID: 618c0c7a-20cc-1450-cb42-ca73156a7598
* Content: [Add a hyperlink to a text box in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-add-hyperlink-to-text-box)
* Content Source: [powerbi-docs/service-add-hyperlink-to-text-box.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-add-hyperlink-to-text-box.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @sandramcg. I've assigned this issue to the doc author for review. In the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @sandramcg -- question for you: Do you have a set of links in a column in a table, or a link or 2 in a text box?

**Comment by maggiesMSFT** [comment]
Hi, @sandramcg -- thanks for getting back to me. 
Here's a suggestion. Check out this section of this article, https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#create-a-table-or-matrix-hyperlink-in-power-bi-desktop -- specifically step 5. You can replace the URL with a little hyperlink icon. Ends up looking like this:
![image](https://user-images.githubusercontent.com/12401230/67800961-7c809600-fa45-11e9-924f-ad23d3099024.png)
Does that help?
thx!

**Comment by sandramcg** [comment]
Thank you so much maggiesMSFT, this has worked perfectly!

**Comment by maggiesMSFT** [comment]
@sandramcg -- Yay! That makes my morning.
