### ISSUE TITLE
This process is no longer working

### ISSUE THREAD

**Issue by K-MUS** [MicrosoftDocs/powerbi-docs#1332]
You copy the link, delete the ?web=1 parameter, but now Power BI desktop intead of "downloading" the file seems to be trying to connecto to a REST API because even do my url ended in .xlsx ... Power BI shows and error in wich the URL ends in 

/_api/contextinfo

Saying that cannot is unable to connect

EDIT: I'm using the latest release August 2019

**Comment by maggiesMSFT** [comment]
Hi, @K-MUS -- are you writing to ask about a specific article? If so, we can't tell which one.
thanks!

**Comment by K-MUS** [comment]
yeah, this article

https://docs.microsoft.com/en-us/power-bi/desktop-use-onedrive-business-links

**Comment by maggiesMSFT** [comment]
Ah, thanks, @K-MUS ! OK, assigning to the author of that article.
In the meantime, consider asking your question of the Power BI community, https://community.powerbi.com/.
Good luck!

**Comment by davidiseminger** [comment]
Thanks for your post. If you confirm the steps are an issue with the community, or with support, feel free to post back here and let us know - we haven't heard of other folks having trouble with this.
