### ISSUE TITLE
Re: "Only you can see the alerts you set, even if you share your dashboard."

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#1333]
To clarify: *Anyone* with access to a KPI on a dashboard can set a data alert, yes? So any given KPI on a dashboard could have multiple alerts set. As the "owner" of the dashboard, can I see all the notifications set on any KPIs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-set-data-alerts#managing-alerts)
* Content Source: [powerbi-docs/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- good clarifying question! I'll try it out and report back.

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- and the answer is No, as the owner you can't see alerts other people set.

Thanks for asking!
