### ISSUE TITLE
Sample Audit Log Data

### ISSUE THREAD

**Issue by WillieAhlers1** [MicrosoftDocs/powerbi-docs#1334]
Looking for sample audit log data, my organization does not allow Admin access to production environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Use auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#feedback)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @WillieAhlers1 -- thanks for your question. I'm assigning it to the author, to see if he can assist.

**Comment by mgblythe** [comment]
Hi @WillieAhlers1 - Here's an example row from the output:


Date | IP address | User | Activity | Item | Detail | More
-- | -- | -- | -- | -- | -- | --
8/18/2019 23:37 | nnn.nn.nnn.nn | adam@some-domain.com | Viewed Power BI dashboard | Human Resources Sample | Data classification undefined
| | | | | |

**Comment by mgblythe** [comment]
Closing this one out. @WillieAhlers1 - let me know if you need additional info.

**Comment by WillieAhlers1** [comment]
Hi Michael,

Thank you for the feedback on my question, I do appreciate it.

Regards,
Willie.

Sent from Mail for Windows 10
