### ISSUE TITLE
MicrosoftAzureConsumptionInsights.Table Parameters

### ISSUE THREAD

**Issue by jasonpnnl** [MicrosoftDocs/powerbi-docs#1335]
Could information be provided about the MicrosoftAzureConsumptionInsights.Table and parameters for it, specifically how to specify number of months? There are examples in the doc of how to do that with MicrosoftAzureConsumptionInsights.Contents but this is not the default way that the Consumption Insights connector works any longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure cost and usage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @jasonpnnl -- thanks for your question! I've assigned it to the author to help.

**Comment by davidiseminger** [comment]
We're working with engineering to address this, and will update the article soon. Thanks for reporting it.

**Comment by davidiseminger** [comment]
We're in the process of updating this article with changes to its functionality, and adding more information. Should be available in the next week or so, so hopefully the updates address your post. Thanks for your post, and your suggestions.
