### ISSUE TITLE
Superfluous text in para 2 of measures

### ISSUE THREAD

**Issue by nonodename** [MicrosoftDocs/powerbi-docs#1336]
2nd para of measures: https://docs.microsoft.com/en-us/power-bi/guidance/star-schema#measures has a final sentence "Learn more link?" Looks like a comment that became text?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [What is a star schema and why do I need one for Power BI? - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema#feedback)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @guyinacube
* Microsoft Alias: **v-pemyer**

**Comment by maggiesMSFT** [comment]
Hi, @nonodename -- thanks for pointing that out! Assigning to the owner for a fix.

**Comment by mgblythe** [comment]
Fixed and closing. Thanks again @nonodename.
