### ISSUE TITLE
Mistakes

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1337]
Hi team,
I'm moving this from here: https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/issues/4
The comment was machine translated

@MarchukNic commented 2 hours ago
1.     The code does not work according to this instruction, after the step of editing the source visual.ts file
     Launch failed.

2.    "In the browser area, expand the src folder and select the settings.ts file." - the wrong file is specified, it must be "visual.ts".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by a10k** [comment]
This documentation is old, the new dev tools use webpack etc., I recommend using pbiviz new [some-name] and checking out the actual files created to see how webpack is used.

**Comment by mgblythe** [comment]
Thanks for your comment, @a10k. I've assigned this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @MarchukNic and @CeciAc,

The document was fixed to include the 'visual.ts' file.
