### ISSUE TITLE
Supported variable types? 

### ISSUE THREAD

**Issue by ROBROICH** [MicrosoftDocs/powerbi-docs#1341]
Are there any restrictions in terms of supported variables types? 
https://wiki.scn.sap.com/wiki/display/BI/Variable+Types

Customer exit and text variables are mentioned here:
https://docs.microsoft.com/en-us/power-bi/desktop-directquery-sap-bw

All other variable types and variable entry(text Ranges, Exclude, &lt;, &gt;, &lt;=, ) options are supported? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9c21b0-3583-2744-5a5f-9401b791821c
* Version Independent ID: f8432546-d080-97aa-7b15-7c456f0e5a12
* Content: [Edit SAP variables in the Power BI service (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-edit-sap-variables)
* Content Source: [powerbi-docs/service-edit-sap-variables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-edit-sap-variables.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ROBROICH -- Thanks for asking! Assigning to someone who can answer your question.

**Comment by Sujata994** [comment]
For SAP BW we support all variable types within the limitations of the 3rd party interface provided by SAP. Customer exit variables for example are not supported in the 3rd party interface. We treat Text and Formula types as passthrough, so there’s no special handling, it’ll work if it’s supported by MDX. We don’t support Ranges, Exclude, <, >, <=,. 

For SAP HANA we support all variable types with some limitations. At this point we don't have a suitable way for customers to specify multiple values for range or interval parameters, and we don’t support default values for range or interval parameters.

**Comment by kfollis** [comment]
#please-close
