### ISSUE TITLE
Constructive feedback on sample reports.

### ISSUE THREAD

**Issue by kriscredon** [MicrosoftDocs/powerbi-docs#1342]
Hi,

As a fan and heavy user (consultant) of Power BI, I want to signal you that I think the demo apps are realy outdated. I think they will do more "damage" than good. I know you have to prioritise your efforts, and this is not a prio. That's OK. But I would already remove the link form within Power BI to these reports. They are not representative of Power BI any more in my opinion.

For the rest : realy good job overall in the development of Power BI ! The monthy updates are a great way to keep the community involved.

Best regards,
Kris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Take a tour of the samples available with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-datasets#feedback)
* Content Source: [powerbi-docs/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks @kriscredon, we appreciate the feedback. I'm going to close this here b/c we'll keep the article in the docs unless the product changes, but we'll pass along the feedback to the product team.

@maggiesMSFT

**Comment by maggiesMSFT** [comment]
Hi, @kriscredon -- yes, thanks for the blunt but honest critique!
In the meantime, we do have one updated sample template app available from the app store. This direct link should work: https://appsource.microsoft.com/product/power-bi/microsoft-retail-analysis-sample.salesandmarketingsample?tab=Overview
If not, go to **Apps** > **Get apps** > **Apps** tab, and search for "Microsoft Sample - Sales & Marketing"
Hope that helps!
