### ISSUE TITLE
Need better samples

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerbi-docs#1344]
Sorry, but this document does not really help the user write their own JSON theme file. 
All I want is a visualStyle section with a "card": {...} section and a "page": {...} section.

it should look like this: 

{
	"name": "CardTemplate",
	"visualStyles": 
	{

		"card": 
		{
			"*": 
			{
				"border": 
				[
					{
					"show": true,
					"color": { "solid": { "color": "#062b60"}}
					}
				]
			}
		}

		
	    "page": {
            "*": {
                "background": [{
                    "color": { "solid": { "color": "#062b60" } },
                    "transparency": 50
                }],
                "outspace": [{
                    "color": { "solid": { "color": "#062b60" } },
                    "transparency": 50
                }]
            }
        }

		
		
	}
}

But it bombs out. Why? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#json-file-element-definitions)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @ToddChitt. I've assigned this issue to the doc author for review.

**Comment by RobLW** [comment]
I just find that unless the text is all on a single line, it bombs out. I have to remove all carrage returns. In the end it's just easier to use this site https://powerbi.tips/tools/report-theme-generator-v3/

**Comment by ToddChitt** [comment]
I found my mistake. There should be a comma after the last closing curly brace BEFORE "page" section starts. But lacking any samples that showed two sections in the same file together, it was hard to diagnose. 
In the end, I have TWO json files. One is 'production' and is good and right. The other is a copy of that, plus ONE change at a time. If that change does what I expect it to do, then THAT file becomes PROD, another copy is made, and the process repeats. (It's brute force source control, *heavy sigh*).

**Comment by davidiseminger** [comment]
Thanks for your comments. We're actively working on improving the documentation for themes (and themes themselves), and will update the article shortly.
