### ISSUE TITLE
Please update FAQ: PBIRS is available through Power BI Premium along with SQL Standard for hosting report server databases

### ISSUE THREAD

**Issue by mpsingh24** [MicrosoftDocs/powerbi-docs#1345]
Please update FAQ to reflect that PBIRS is available through Power BI Premium along with SQL Standard for hosting report server databases. 

PBIRS requires SQL Server Instance for hosting report server databases. Customers are confused on licensing aspects for the SQL instance when they avail Power BI Report Server through Power BI Premium.

The Premium licensing provides use rights to SQL Server Standard to be used in conjunction with Power BI Report Server, which you’d use for hosting the report server database. Also, PBIRS can be hosted on Azure VMs as well and not limited just to on-prem. 

It will be great to have this clarified within the documentation. Few more open items for FAQ:
- Can the SQL Standard Instance be hosted on separate VM from PBIRS? Is there a licensing restriction preventing this?
- In case the customer wants to set up HA configuration for PBIRS, is that covered as a part of the license?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-faq)
* Content Source: [powerbi-docs/service-premium-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @mpsingh24. I’ll add this request to our docs backlog.

**Comment by mgblythe** [comment]
@maggiesMSFT - can you add info to the FAQ or get back to me with the right wording and I'l add it, thanks!

**Comment by maggiesMSFT** [comment]
Hi, @mpsingh24 -- thanks for your question! See https://docs.microsoft.com/power-bi/report-server/get-started#licensing-power-bi-report-server for licensing details. I'm adding a link from this article that that section.
