### ISSUE TITLE
This app isn't available

### ISSUE THREAD

**Issue by brooksw78** [MicrosoftDocs/powerbi-docs#1348]
The MailChimp template app for Power BI does not exist. It may have existed before, but there's nothing there now. The link to the MailChimp template app at the top of the page redirects to https://app.powerbi.com/home

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1a58f41-ee6e-cbc1-2fa0-e39157588dfd
* Version Independent ID: 01ee6d74-1cb0-7bd2-709d-1d437ce9e456
* Content: [Connect to MailChimp with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-mailchimp#feedback)
* Content Source: [powerbi-docs/service-connect-to-mailchimp.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-mailchimp.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @brooksw78 -- Thanks, I'll check it out and get back to you.

**Comment by maggiesMSFT** [comment]
Well, @brooksw78 -- I have news, though not necessarily good news. The MailChimp template app is temporarily out of commission, so I'm going to remove this article for now. Thanks for pointing this out! And sorry it's not a happier outcome. We'll reinstate the article when the app is back.
