### ISSUE TITLE
limitation 

### ISSUE THREAD

**Issue by phobag** [MicrosoftDocs/powerbi-docs#1349]
Need to let users know this limitation 

the code is using datavolume 4 which is 5,000 data points. However, due to the shape of the data, and whether there are blank intersections, the data limit can be lower. Also, the datasource may not have statistics or dynamic limits may not be enabled, which does lead to lower actual counts in some cases.

**Comment by mgblythe** [comment]
Hi @phobag - is there a particular article you had in mind when making this suggestion? Thanks!

**Comment by phobag** [comment]
Hi @mgblythe these docs below. This limitation is for shape maps

https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-data-points


just need to let user know that the Point is 5,000 and that depending on the datasoure and shape this can lower the limitation for the points

**Comment by mgblythe** [comment]
Thanks @phobag, I assigned to the author for review.

**Comment by mihart** [comment]
Hi @phobag ,
I've checked with the shape map PM. The maximum, for now, is 1,500 data points.  The visual is still in Preview and this limitation may increase when the visual comes out of Preview. 
Thank you for your question.
