### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerbi-docs#135]
@DaveRuijter commented on [Sat Jul 14 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/4)

I expect the licensing requirements for SharePoint embedding to be mentioned here.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Insluiten met webonderdeel Rapport in SharePoint Online - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-embed-report-spo#next-steps)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by DavidPrio** [comment]
Hi @markingmyname I am not author for this. Please reassign accordingly. Thanks!
@Sara-Nicolini FYI

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@DaveRuijter Changes have been made to the requirements section.  The changes should be present in a few days.

**Comment by DaveRuijter** [comment]
Thanks for the changes.
