### ISSUE TITLE
Enter data directly only allows you to create a new table, not add data to an existing table.

### ISSUE THREAD

**Issue by djurecic** [MicrosoftDocs/powerbi-docs#1350]
I think the sentence below is a little confusing or incomplete- this direction only allows you to create a new table and enter data directly, not enter data directly to an existing table.

"To enter data directly, select Enter Data from the Home ribbon."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38a6766-9c9e-bb63-02db-893ed942db94
* Version Independent ID: ef2b000c-0ed9-fdb3-f4fe-165262b695f9
* Content: [Enter data directly into Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-enter-data-directly-into-desktop#feedback)
* Content Source: [powerbi-docs/desktop-enter-data-directly-into-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-enter-data-directly-into-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @djurecic. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post. I've clarified that sentence to state it's entered in the form of a new table, which will show up online in ~24 hours.
