### ISSUE TITLE
Broken demo data

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#1353]
pbix file and excel file are broke

"To follow along, open the Customer Feedback PBIX file in Power BI Desktop. You also can download the Customer Feedback Excel file for Power BI service or Power BI Desktop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @[github person who posted]. I've assigned this issue to the doc author for review.

**Comment by mgblythe** [comment]
@chizhova - the files are there, click **Download** on the GitHub page. @mihart - can you add a quick explanation to the doc?
