### ISSUE TITLE
Not seeing the group option

### ISSUE THREAD

**Issue by st3vemartin** [MicrosoftDocs/powerbi-docs#1355]
Hello - I have the August 19 Version, but ctrl-select multiple items and right click doesn't show the Group Option.  

I don't see this new feature  under preview features.  Is there another prerequisite, such as having certain Visual Options turned on in Report Settings.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6669843-8752-7777-31e8-1d1e4ec96648
* Version Independent ID: b7be0303-1882-621e-a630-32895aafa84d
* Content: [Use grouping in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-visuals#feedback)
* Content Source: [powerbi-docs/desktop-grouping-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @st3vemartin. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Hello @st3vemartin  - you need to have the most recent version of Power BI Desktop for this feature to work.

**Comment by wanajo38** [comment]
Hello, I have the last version and I don't see this option too...
