### ISSUE TITLE
Conversion?

### ISSUE THREAD

**Issue by apfenech** [MicrosoftDocs/powerbi-docs#1356]
There used to be a lot of notes that after GA we would be able to convert existing workspaces to the new workspace experience.  The only place I can see this note now is here (https://docs.microsoft.com/en-us/business-applications-release-notes/April19/business-intelligence/power-bi-service/new-workspaces#tell-us-what-you-think).

Is this feature still planned?  If so, is there any idea on a possible release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @apfenech. I've assigned this issue to the doc author for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by sjs210** [comment]
Is there any status update on a conversion tool to upgrade classic to the new workspace?  I do not want to invest a lot of time manually converting workspaces (and the upheaval of having all of the connected Excel report data connections change) if there is an automated conversion tool that will be available in the near future.  

The road map seemed to indicate this tool would be available in Sept 2019 or when the new work spaces were generally available.   If this is not the case, a status update would be very helpful as it is something we need to make plans for either way!  

Thanks,
Sally

**Comment by maggiesMSFT** [comment]
Hi, @apfenech and @sjs210 -- reasonable questions! The Release Notes remain the best bet for discussions of upcoming features. The docs stick to what's already released. So your link, https://docs.microsoft.com/en-us/business-applications-release-notes/April19/business-intelligence/power-bi-service/new-workspaces, is still the best source of info.
Thanks!

**Comment by sjs210** [comment]
@maggieMSFT Is there any update on the ability to convert classic to new app workspace? Is it due to rollout this month (NOV 2019?) per https://docs.microsoft.com/en-us/business-applications-release-notes/April19/business-intelligence/planned-features?
