### ISSUE TITLE
pbiviz --install-cert 3.1.5 is throwing error  UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined with Node 10.16.3 and npm 6.11.1

### ISSUE THREAD

**Issue by ajbrepository** [MicrosoftDocs/powerbi-docs#1357]

**Comment by ajbrepository** [comment]
error  Certificate not found. The new certificate will be generated
(node:2180) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'indexOf' of undefined
    at Object.createCertFile (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\CertificateTools.js:193:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by mgblythe** [comment]
Thanks for your comment, @ajbrepository. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
