### ISSUE TITLE
KCD for multi-domain scenarios

### ISSUE THREAD

**Issue by amasse3** [MicrosoftDocs/powerbi-docs#1358]
> Question: What if I install the gateway on a computer in a different domain from my on-premises server that uses Windows authentication?
> 
> Answer: No guarantees here. It all depends on the trust relationship between the two domains. If the two different domains are in a trusted domain model, the gateway might be able to connect to the Analysis Services server and the effective username can be resolved. If not, you might encounter a login failure.

I believe we can be more specific here.  If the two AD domains are in the same forest and A) the On-Premises Data Gateway is in the same domain as the authenticating user, or B) is in the same domain as the connected data service, kerberos authentication should work.  This should hold true unless there is something non-traditional about the trust configuration of the child domains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdf9bdea-bf34-70bb-01f6-98d4d1206be9
* Version Independent ID: 99ec91fe-a671-1f00-cb71-3f9fa2b98fdf
* Content: [On-premises data gateway FAQ - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-power-bi-faq#feedback)
* Content Source: [powerbi-docs/service-gateway-power-bi-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-power-bi-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @amasse3. I’ll add this request to our docs backlog.

**Comment by kfollis** [comment]
@amasse3 - Thank you for submitting feedback on our documentation. We are closing this issue since there has been no action. If your feedback isn't addressed, please feel free to submit additional feedback for the page. You may also edit the page directly and your submission will be reviewed by a writer before publishing.
