### ISSUE TITLE
Is this the procedure also meant for Power BI New feature on July 2019 updates

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/powerbi-docs#1359]
Hi, just need some confirmation. Does this procedure still in-line with Power BI July updates ?
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2019-feature-summary/#azureDataLake

And according to the ideas, it is direct connection, so my confusion is, does it still need procedures describe on this page ?
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/37015567-power-bi-direct-connector-to-adls2-azure-data-lak%C2%A0

Thanks,

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-gb/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @axaeffect. I've assigned this issue to the doc author for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Hi @axaeffect - please use the most recent version of Power BI Desktop and try again. If you still have trouble, please check the community at https://community.powerbi.com or support by going to https://support.powerbi.com.
