### ISSUE TITLE
non-profit pricing plan is not available

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerbi-docs#136]
@chrsh18 commented on [Sat Jul 14 2018](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/2)

The non-profit pricing plan is not available, link is broken. Please fix this. TIA

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d877b0ce-2e0b-dca4-709d-24b4e5a374b4
* Version Independent ID: 8d727d5a-7e46-62a7-8530-882ee9653640
* Content: [Häufig gestellte Fragen zu Power BI - Power BI](https://docs.microsoft.com/de-de/power-bi/service-frequently-asked-questions)
* Content Source: [powerbi-docs/service-frequently-asked-questions.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/service-frequently-asked-questions.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by LisandroSu** [comment]
Hi team,

The link reported by the user is not working.

Thanks.

**Comment by maggiesMSFT** [comment]
Thanks, @chrsh18 and @LisandroSu -- I found this link, https://www.microsoft.com/en-us/nonprofits/power-bi, and will update the article.

**Comment by maggiesMSFT** [comment]
Hi @chrsh18  and @LisandroSu, I've updated the link. It'll be live later this afternoon. Thanks!

**Comment by Baranee28** [comment]
I would like to access the Audit Log details related to Power BI services such as dataset details, count of datasets, number of users, active user details etc, using Power Shell scripts. While i explored i found the possible way to achieve this functionality is through Exchange Online. But i dont have privileges to execute Exchange Online cmdlets. Can you please help me, is there any alternate way to achieve this one.
