### ISSUE TITLE
ACCEPT_EULA command line option

### ISSUE THREAD

**Issue by dave-stagg** [MicrosoftDocs/powerbi-docs#1360]
Section "Using command-line options during installation" should mention that a silent installation also requires the command line option ACCEPT_EULA=1 . Installation fails without this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322970ff-d62a-adeb-c8b3-d1141d3a272f
* Version Independent ID: 94d82157-a824-73c8-2add-462ee6b033b1
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-get-the-desktop#feedback)
* Content Source: [powerbi-docs/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @dave-stagg. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion @dave-stagg - we've added that information to the article.
