### ISSUE TITLE
Incremental Refreshes: Refresh Now vs Scheduled Refresh

### ISSUE THREAD

**Issue by nicki-t** [MicrosoftDocs/powerbi-docs#1361]
Does using Refresh Now mean the whole dataset is refreshed (ie not just the Incremental loading?)

**Comment by mgblythe** [comment]
Hi @nicki-t. The whole dataset is refreshed unless you're using [incremental refresh in Power BI Premium](https://docs.microsoft.com/power-bi/service-premium-incremental-refresh).

**Comment by nicki-t** [comment]
We use Power BI embedded and have a premium capacity meaning we have access to this. However it's not clear when the refresh is incrementally loading or doing an incremental refresh. Doing some testing, it would appear that using refresh now always performs a full refresh. Is that your understanding?
