### ISSUE TITLE
Doesn't work for me, or I don't unerstand what visual elements should be included in the "theme"

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerbi-docs#1362]
I have tried just about everything to customize my dashboard. 
My report has a custom JSON theme that I authored. Card visual take on the properties specified in the theme, namely, that the font (foreground0 color is blue, not black. They show up properly in the published report. But if I pin a card tile to a dashboard and select "Keep current theme", the pinned card has BLACK foreground, not blue. Why?
So I pin a second card tile and select "Use destination theme", then go to the dashboard and upload the SAME JSON file as the report uses, and STILL, the card visuals show BLACK foreground. 

Please be specific about what visual elements I can customize on a Dashboard theme? Card tile Title foreground and background? Nope. Data foreground and background? Nope.

Seems the only thing I can do is pick one of the canned themes in the Dashboard.
Only be reverse-engineering the downloaded theme do I discover that there is a separate section for "tiles":{...}
What other things might I be missing? 
I already have a specified color in my theme for background and I don't want to change that. What I want is for the DASHBAORD to have a DIFFERENT background color. Is that possible to do in the JSON Theme file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b534707-1253-6a56-5b6e-d69edf32e1ab
* Version Independent ID: 34be0bef-858c-658f-4bbd-dc4da405759c
* Content: [Use dashboard themes in Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-themes)
* Content Source: [powerbi-docs/service-dashboard-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @ToddChitt. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @ToddChitt -- I'm working on getting an answer for you. Sorry for the delay.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. We are closing this issue, but have created a work item in the writer’s backlog to consider your feedback in the next update.

**Comment by ToddChitt** [comment]
Really? That's it? After a year this is getting closed? Will I get notified when they fix the issue?

**Comment by kfollis** [comment]
I've reviewed the article and have created a work item for the writer to make extensive updates as the UI has changed. Your feedback has been carried into the work item. I'm happy to reopen the issue if you'd like to track article updates, we are simply clearing issues that have had no action. If you are still having problems with your theme, you may want to review the themes gallery here: https://community.powerbi.com/t5/Themes-Gallery/bd-p/ThemesGallery or submit a question to community.

**Comment by maggiesMSFT** [comment]
Hi, @ToddChitt and @kfollis  -- for real, I'm tracking down the person on the team who can get me the details on the JSON for dashboard themes. In the meantime I've updated the screenshots and steps.

**Comment by ToddChitt** [comment]
To be honest I’m a more than a little disillusioned with Microsoft regarding a lot of Power BI backlog stuff, this being one of several. They have moved on to the ‘cool and sexy’ stuff like AI integration, etc. but are leaving basic issues in the dust. User navigation regarding losing of the focus is horrible. Font sizes across visuals are inconsistent, more so with custom visuals, even ones that are “certified by Microsoft”. SSAS Tabular database projects in Visual Studio has been abandoned, no new fixes to that mess, even though you need it to take advantage of Azure Analysis Services. UserVoice site is a joke; it never should have been converted to Org Authentication without working out all the issues that brought. Stuff moves so fast that documentation pages like this are outdated within six months.

Power BI is a great tool on the face, but dive deep into the guts and it’s getting too big for its britches.

If I was in charge, I would stop all new development and have all hands on deck cleaning up the myriad of loose ends before moving forward again.

Sorry for rant. I have been watching Power BI since  six months BEFORE GA and can only throw up my hands and say, “oh well.”

**Comment by maggiesMSFT** [comment]
Hi, @ToddChitt -- I'm sorry for your disillusionment!
I was able to find a blog post about the dashboard theme JSON file, https://powerbi.microsoft.com/en-us/blog/announcing-dashboard-theming-in-the-power-bi-service/, which does contain some details about the JSON file. I'll add it to the article.

**Comment by maggiesMSFT** [comment]
Hi, @ToddChitt -- BTW, turns out the black text limitation is spelled out in this article, https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-pin-tile-from-report#limitations.
