### ISSUE TITLE
Security Groups?

### ISSUE THREAD

**Issue by phantem** [MicrosoftDocs/powerbi-docs#1364]
Can you provide an example of how to add access for security group? All attempts for our OU-based security group indicate that the entity is invalid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
#reassign @maggiesMSFT

**Comment by mgblythe** [comment]
Thanks for your comment, @phantem. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @phantem -- I've checked. Security groups are definitely supported. If you're still having an issue, you'll need to open a support ticket: https://powerbi.microsoft.com/en-us/support/
Good luck!
