### ISSUE TITLE
Slicer values are not responsive of selections made by other filters.

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#1365]
For the sake of understanding the problems let's say you have a Slicer with a Slider with numeric inputs for 4 ID numbers. (1001 - 9999). Okay. Now lets say each 1000 numbers belong to a particular department. (IT -&gt; 2001 -2999 ; HR -&gt; 1001 - 1999; and so on) .
If we have a 'Group' description slicer in the form of list values, along with the Slider slicer, the values in the slider slicer don't seem to change upon selection of that particular group.
For example if User select HR, then the slicer slider should automatically convert from full range to the Group's range (i.e from 1001 - 9999 --&gt; to 1001 - 1999) . For some reason this simple thing does not work in the August 2019 update at least. 
So i guess the end goal of this bug/issue or the fix to it would be to make the values in the Slicer Slider responsive as well. 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc558f3-8a74-7154-c048-2dd74ad4eb8a
* Version Independent ID: f84aa1a5-4bab-6f6d-a0ba-5040c0f5defb
* Content: [Use the numeric range slicer in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-slicer-numeric-range#display-formatting-with-the-date-range-slicer)
* Content Source: [powerbi-docs/desktop-slicer-numeric-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-slicer-numeric-range.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @dhruvinushah. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
