### ISSUE TITLE
How can I purchase PowerBI Premium with trial?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1366]
Is it possible to purchase powerbi premium with trial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase#feedback)
* Content Source: [powerbi-docs/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-purchase.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @Anmolgan81. I’ll add this request to our docs backlog. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mgblythe** [comment]
There is not trial per se, but you can use an A4 SKU, which is billed hourly, to test functionality. As long as you sign into Azure with an account that is also a Power BI admin (when you create the SKU), you will see the A SKU capacity under Settings->Admin portal->Capacity settings->Power BI Embedded. You can assign workspaces to this capacity as described in this doc: https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage. You will then be able to test the functionality that Power BI Premium offers with the exception of broad sharing/consumption for free users.

**Comment by Anmolgan81** [comment]
But the Premium and Embedded capacities are different right?

**Comment by mgblythe** [comment]
You don't get the ability for free users to share but the A4 SKU should allow you to test out all the other Premium functionality.
