### ISSUE TITLE
Example used.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [MicrosoftDocs/powerbi-docs#1367]
The '=' operator treats '0' zero and BLANK  as being equal. 

A small example shows this:
EVALUATE
FILTER (
    {
        ( "01", 0 ),
        ( "02", BLANK () ),
        ( "03", 200 )
    },
    [Value2] = 0
)

Wouldn't it be better to change the example:
=IF(ISBLANK([Sales]) || [Sales] = 0, BLANK(), [Profit] / [Sales])
to
=IF( [Sales] = 0, BLANK(), [Profit] / [Sales])

The original example leaves the readers with the impression that '=' treats '0' zero and BLANK  as not being equal. I may be a stickler for accuracy but since this is an official guidance I think it would be better not to introduce confusion or let the reader be left with the wrong impression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b331cbb-81c4-add1-da29-3783ed6ad9a6
* Version Independent ID: 9f4ca24a-ad9b-2601-7a40-5ffd5eef8254
* Content: [DAX: DIVIDE function vs divide operator (/) - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/dax-divide-function-operator#feedback)
* Content Source: [powerbi-docs/guidance/dax-divide-function-operator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/dax-divide-function-operator.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @guyinacube
* Microsoft Alias: **v-pemyer**

**Comment by Oxenskiold-DAX** [comment]
Alternatively you could change the example into:

`=IF(ISBLANK([Sales]) || [Sales] == 0, BLANK(), [Profit] / [Sales])`

I.e using the '==' operator instead of the '=' operator. This actually may have been the intention of the guidance author all along; to emphasise the two scenarios that can occur regarding the denominator.

**Comment by mgblythe** [comment]
The example is now updated to `=IF(OR(ISBLANK([Sales]), [Sales] == 0), BLANK(), [Profit] / [Sales])`. Thanks @Oxenskiold-DAX, closing this one out.
