### ISSUE TITLE
horrible documentation

### ISSUE THREAD

**Issue by ranaalisaeed** [MicrosoftDocs/powerbi-docs#1369]
can you make this document more longer by whinging and whining a bit more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179482da-6009-3602-8e51-c20a42c83b5b
* Version Independent ID: b023c9e5-94e0-4d0c-67ce-465916170c43
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-troubleshooting-refresh-scenarios#feedback)
* Content Source: [powerbi-docs/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Closing out. @ranaalisaeed - feel free to reopen if you have any details you'd like to provide.
