### ISSUE TITLE
App Registration permissions need broader documentation

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#137]
Hello,

This table lists some Power BI scope values and descriptions, but it doesn't include all the values listed in Azure Active Directory's App Registration permissions.  For example, Tenant.Read.All (we can't tell if that allows only access to Power BI or the entire O365 tenant).  Please create more clear documentation about ALL of the Power BI security permissions, in a single place, rather than only a subset of them in this page.

Thanks!
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b836b669-bee0-737a-8de1-b3fd0cda0218
* Version Independent ID: f6ae700d-4db0-fd20-fab5-6020ecde08c4
* Content: [Power BI permissions - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/power-bi-permissions)
* Content Source: [powerbi-docs/developer/power-bi-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/power-bi-permissions.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks for the feedback, @chrisweis! I'll pass it along to the author.

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@chrisweis We understand it can be a bit frustrating to have related pieces of information in different places.  We are working on getting the information more straightforward. To answer your question, Tenant.Read.All is just for Power BI.  Thank you again for your feedback.
