### ISSUE TITLE
Add PostgreSQL to list of supported DirectQuery sources

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerbi-docs#1370]
Hi,
in the august 2019 feature summary, Postgresql was added as a (preview) data source.
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2019-feature-summary/

Can we add this source in the list? 
Is there a specific driver version necessary? Once I add a 'count' measure to a visual, I get the error "we couldn't fold the expression to the data source. please try a simpler expression".

thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources#feedback)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by miragliag** [comment]
I have this problem too. publishing the direct query report results in an error on the Web. Thanks for an update. Is there a Postgres minmal Version? Is 9.6 supported in direct Query mode?

**Comment by davidiseminger** [comment]
We've added PostgreSQL to the list, thanks for pointing this out.
