### ISSUE TITLE
New filter experience

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#1371]
This page should be updated to reflect the new filter panel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b3989d-4ab1-51f2-6823-970c04f6fba9
* Version Independent ID: 673ccbe9-ef77-5c5b-9936-37eaeb4d3762
* Content: [Filter a report and share it with coworkers - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-reports#feedback)
* Content Source: [powerbi-docs/service-share-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @otravers -- yes, you're right. I've made the changes but they may not be live until Monday. 
Thanks for your careful observation!
