### ISSUE TITLE
USERCULTURE() is not working

### ISSUE THREAD

**Issue by ankitgthub** [MicrosoftDocs/powerbi-docs#1372]
USERCULTURE() function is not getting detected in power bi. Error message"'USERCULTURE' is not a function". Also I am not able to find any reference of USERCULTURE() in MSDN dax documents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a270e6-b0c1-bb57-831c-ce75a4d42085
* Version Independent ID: f831c935-823e-be44-02b8-c4145fe89d28
* Content: [Expression-based titles in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-format-visual-titles#feedback)
* Content Source: [powerbi-docs/desktop-conditional-format-visual-titles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-format-visual-titles.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.

**Comment by Didierma92** [comment]
Any News for that important matter ? Thsi function is enlisted in the DAX documentation and does not work.
