### ISSUE TITLE
List of "Other" needs updating

### ISSUE THREAD

**Issue by JoshKF** [MicrosoftDocs/powerbi-docs#1373]
I think "Denodo" is misspelled as "Denado" and the Paxata listing is down with the Beta Connectors even though it's GA. I think the placement and otherwise ordering of the list is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources#feedback)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your post, and it was indeed misspelled - thanks for clarifying. I'll also pass along your comments about the ordering of the list.
