### ISSUE TITLE
What is PowerBI

### ISSUE THREAD

**Issue by gustavothomas17** [MicrosoftDocs/powerbi-docs#1374]
I would suggest just to mention the three view options (Model, Data and Report) matching each with a step in the analysis, for example:
Model is the View Option where the user manages the relationships among datasets
Data is the View Option where the user transforms the sets of data so that they become ready for analysis and
Report is where the visualizations are built.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-what-is-desktop)
* Content Source: [powerbi-docs/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-what-is-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great idea @gustavothomas17  - I've added those descriptions to the top of the article. Thanks!
