### ISSUE TITLE
PBIRS-May-2019 download page doesn't list that it is supported on Windows server 2019 though it is actually supported. 

### ISSUE THREAD

**Issue by MikeSunGithub** [MicrosoftDocs/powerbi-docs#1376]
PBIRS-May-2019 download page(https://www.microsoft.com/en-us/download/details.aspx?id=56722) doesn't list that it is supported on Windows server 2019 though it is actually supported per this document. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f20394b-f5b1-2924-3670-932dba073875
* Version Independent ID: 71ec4d31-53e6-16d4-c250-c38f1bba2ba6
* Content: [Hardware and software requirements for installing Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/system-requirements#feedback)
* Content Source: [powerbi-docs/report-server/system-requirements.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/system-requirements.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
OK, @MikeSunGithub -- I've verified. The article is correct, it is supported on Windows server 2019. I've sent along the request to update the download page. Thanks for catching that!
