### ISSUE TITLE
Reserved Instance valid EA Key

### ISSUE THREAD

**Issue by KLCKLCKLC** [MicrosoftDocs/powerbi-docs#1377]
Could you let me know if it's normal that the tables for RICharges / RIRecommendations_Single / RIRecommendations_Shared / RIUsage / Budget are in error if the EA API Key is not at the enrollment-level?

If yes, could you add this information in the documentation ?

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
