### ISSUE TITLE
Share report by email feature shown as unavailable at PowerBI Support page

### ISSUE THREAD

**Issue by c13GitHub** [MicrosoftDocs/powerbi-docs#1378]
I had previously been aware of the subscription and share report by email capabilities as launched in PowerBI in 2017. I revisited the service offering support page (https://powerbi.microsoft.com/en-us/support/) after reading this documentation, and I believe there is an information that Share may be experiencing an issue to be fixed on 09/06/2019.

If the Share issue being fixed is related to the feature described in this doc, will the doc be updated as to what sharing functionality would be impacted (or even augmented) in PowerBI Pro service offering? 

If I want to stay informed about the future of Share by email, since it is a key feature required for my use case, what are good resources to observe that roadmap for the PowerBI service offering?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe yourself and others to reports and dashboards - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-report-subscribe)
* Content Source: [powerbi-docs/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @[github person who posted]. I've assigned this issue to the doc author for review.

For upcoming features, I recommend checking the [What's new and planned doc](https://docs.microsoft.com/business-applications-release-notes/april19/business-intelligence/planned-feature).

**Comment by maggiesMSFT** [comment]
Hi, @c13GitHub -- good questions! 
When the share issue is fixed, the feature will be back to its previous state.
How to find out about the future of Power BI features: Are you familiar with the Release Notes? That's where the product team lays out updates coming in the future. https://docs.microsoft.com/en-us/business-applications-release-notes/april19/business-intelligence/planned-features. 
Hope that helps!
