### ISSUE TITLE
Developpment Approach

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#1379]
This article is interesting but what about developppment approach in a premium environment ? 
Should we developp in premium capacity or shared ? If we need to use premium specific feature such as incremental refresh or dataflow premium feature ? Should we also use A SKUs  like testing approach ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c913b90d-071a-7be0-6652-4b1b024e7f45
* Version Independent ID: bc99d496-cf13-552b-b6df-55229ad9ff1d
* Content: [Deploying and Managing Power BI Premium Capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-premium-deployment#feedback)
* Content Source: [powerbi-docs/whitepaper-powerbi-premium-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-powerbi-premium-deployment.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Yes A SKUs are the right approach for testing. If you use A4, you will then be able to test the functionality that Power BI Premium offers with the exception of broad sharing/consumption for free users.
