### ISSUE TITLE
Provide Test file

### ISSUE THREAD

**Issue by vikasbansalcse** [MicrosoftDocs/powerbi-docs#138]
In each documentation, whatever file you use for explaining concept (such as in this doc you used, KPIs workbook), Do provide that file link somewhere so that we can have hands on practice to feel confidant.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa598a25-4c63-01da-accd-1b4782ad0991
* Version Independent ID: d84fce3e-37c7-0def-3220-1643afb0e4e9
* Content: [Import and display KPIs in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-import-and-display-kpis)
* Content Source: [powerbi-docs/desktop-import-and-display-kpis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-import-and-display-kpis.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for the suggestion, @vikasbansalcse! I'm passing it on to the author.

**Comment by davidiseminger** [comment]
Thanks for the suggestion, @vikasbansalcse - we do have many samples available, and will consider adding these as well.
