### ISSUE TITLE
Email subscriptions needs updating

### ISSUE THREAD

**Issue by mgcharumilind** [MicrosoftDocs/powerbi-docs#1380]
According to Christopher Finlan on Twitter :)
I think Power BI service supports subscriptions to paginated reports now or something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service#feedback)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by aaronjschmidt** [comment]
Agreed.  It's even less clear why I might want a Report Server now:
https://docs.microsoft.com/en-us/power-bi/paginated-reports-subscriptions
https://powerbi.microsoft.com/en-us/blog/e-mail-subscriptions-for-paginated-reports-is-now-available/

**Comment by mihart** [comment]
Thanks for your comment, @mgcharumilind. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @mgcharumilind -- Yup, good job! I've updated the article already, thanks to you.
Hi, @aaronjschmidt -- good point. Go with the Power BI service!
