### ISSUE TITLE
It probably needs more information about capabilities

### ISSUE THREAD

**Issue by Calvini03** [MicrosoftDocs/powerbi-docs#1383]
It is clear what capabilities regarding data accessibility the personal gateway provides. A question:

Is app & workspaces and sharing the same as in the "On premise Data Gateway (no personal mode)?

Also, PowerBI shows if there is an on-premise data gateway (DG)but it looks like that it does not show when there is a personal DG? Is that the case?

- Logs. Is it possible to have a track of personal data gateway (and on-premise data gateways in general)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea871f0a-018e-0335-7261-f9d9d2232e36
* Version Independent ID: 345a024a-5964-0979-494f-6f7196a3c929
* Content: [Use personal gateways in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode#feedback)
* Content Source: [powerbi-docs/service-gateway-personal-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-personal-mode.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @calvini03. This issue has been assigned to the doc author for review.

**Comment by arthiriyer** [comment]
@Calvini03 - you cannot share personal gateways. It runs under a user's context. 
You cannot see it in Power BI "Manage gateways" page but should be able to see it in [Power platform admin center](https://admin.powerplatform.microsoft.com/ext/DataGateways)

**Comment by arthiriyer** [comment]
#please-close @mgblythe
