### ISSUE TITLE
I know its a third party tool but.....

### ISSUE THREAD

**Issue by dbszepesi** [MicrosoftDocs/powerbi-docs#1385]
It seems ridiculous to not even mention DaxStudio in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc3724b-5c69-73df-1ff2-8fa0a28c9c79
* Version Independent ID: 86932e18-54c4-dc9e-67f9-fe95f1e20f08
* Content: [Power BI performance best practices - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-reports-performance#feedback)
* Content Source: [powerbi-docs/power-bi-reports-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-reports-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @MarkMcGeeAtAquent
* Microsoft Alias: **kfile**

**Comment by mihart** [comment]
Thanks for your comment, @dbszepesi. This issue has been assigned to the doc manager for review.

**Comment by Bhavik-MSFT** [comment]
Hi @dbszepesi, we do agree that DAX Studio is a useful tool for performance tuning. There also other utilities from the community that are helpful in this space. However, since these are not produced by Microsoft we do not support them and cannot officially recommend them in documentation.

**Comment by Bhavik-MSFT** [comment]
#please-close @mgblythe
