### ISSUE TITLE
Power BI visuals GitHub link

### ISSUE THREAD

**Issue by alexb5dh** [MicrosoftDocs/powerbi-docs#1386]
> We’re enabling developers to easily add custom visuals into Power BI for use in dashboard and reports. To help you get started, we’ve published the code for all of our visualizations to GitHub.

Can you please provide a link? I'm trying to extend built-in Clustered Column Chart. The closest thing I found on GitHub is [this](https://github.com/microsoft/PowerBI-visuals-sampleBarChart) which seems to be just a sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by mihart** [comment]
Thanks for your comment, @alexb5dh. This issue has been assigned to the doc author for review.

**Comment by brianhyn** [comment]
Same issue. Any updates?

**Comment by sixlead** [comment]
Try this - https://github.com/microsoft?utf8=%E2%9C%93&q=power+bi&type=&language=

**Comment by zBritva** [comment]
@brianhyn @alexb5dh 
The sources of the visuals are listed in GitHub Pages:
https://microsoft.github.io/PowerBI-visuals/samples/

**Comment by brianhyn** [comment]
I appreciate the feedback on this thread. What I would like to get is the code for the visuals that MS provides with PBI out of the box, without any modification. From my research, it seems this was once publicly available and perhaps isn't now? Thanks.

**Comment by zBritva** [comment]
@brianhyn The sources of core visuals in Power BI Desktop/Service aren't available anymore.

**Comment by KesemSharabi** [comment]
Thanks for your comments, @alexb5dh and @brianhyn. 

If you require further support besides what was listed above, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
