### ISSUE TITLE
Storage Mode is no longer on the report fields pane, it's been moved to the model page

### ISSUE THREAD

**Issue by vksf01** [MicrosoftDocs/powerbi-docs#1387]
I'm using the latest version of Power BI Desktop (August 2019) and the storage mode described on this page does not exist anymore and appears have been moved to the Model page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-storage-mode#feedback)
* Content Source: [powerbi-docs/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-storage-mode.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @vksf01. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for pointing this out @vksf01 - you are indeed correct. I've updated the document, which will be live in the next ~24 hours. Thanks for posting!
