### ISSUE TITLE
old azure portal image

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1388]
@hongju commented on [Sun Sep 01 2019](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/issues/414)

This article has very old feature image and description, so need update.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 8b88d198-6022-4b58-7dca-abd17fbd8b5a
* Version Independent ID: da72fb29-713d-e133-0f45-2ecab458ead0
* Content: [Azure SQL Database에 대해 예약된 새로 고침의 문제 해결 - Power BI](https://docs.microsoft.com/ko-kr/power-bi/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases)
* Content Source: [powerbi-docs/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases.md](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/blob/live/powerbi-docs/service-admin-troubleshooting-scheduled-refresh-azure-sql-databases.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

---

@srvbpigh commented on [Sun Sep 01 2019](https://github.com/MicrosoftDocs/powerbi-docs.ko-kr/issues/414#issuecomment-526915714)

Hello, @hongju
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the reported images are the same as in en-US
best regards

**Comment by mihart** [comment]
Thanks for your comment, @ceciAc. This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Thanks @CeciAc, now fixed.
