### ISSUE TITLE
Please add "No need Java code" description to Spark, Azure Databricks, Apache Spark for Azure HDInsight 

### ISSUE THREAD

**Issue by yoshihirok** [MicrosoftDocs/powerbi-docs#139]
"No need Java code" mean that Citizen analysts can use the data on Spark/Azure Databricks by Power BI,
many person, many workers can analyze.

and Spark documents usually use Java code to use it, and dose NOT write that Power BI can use the data without Java code.
So, I hope to add "No need Java code" description. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @yoshihirok! I'll pass your feedback along to the author.

**Comment by davidiseminger** [comment]
Thanks for your comments @yoshihirok, I'll pass this to the engineering team for confirmation.

**Comment by yoshihirok** [comment]
Thanks @maggiesMSFT , @davidiseminger
