### ISSUE TITLE
Incorrect link to Monthly gateway updates

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#1391]
The link to the Monthly gateway updates is incorrect, it points to:
https://review.docs.microsoft.com/data-integration/gateway/service-gateway-monthly-updates?branch=master.
This has to be: https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-monthly-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#feedback)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @NickyvVr. This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Thanks @NickyvVr, fixing this today.

**Comment by mgblythe** [comment]
Now fixed and live
