### ISSUE TITLE
New look : title from different app

### ISSUE THREAD

**Issue by rmhess** [MicrosoftDocs/powerbi-docs#1392]
With the apps 'new look', there's a title/dropdown in the middle of the bar on top that shows the apps title and owner when clicked. But recently, what's shown is information from a different app!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps#feedback)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @rmhess. This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Thanks @rmhess, this sounds more like a product issue than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
