### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by tconrady** [MicrosoftDocs/powerbi-docs#1393]
At the top of the documentation it shows four actions, but the parameter reference explains only one of them. Specifically the first chapter says 

"Here are actions you can perform through URL access parameters:
   ...[list of four actions]
For the complete list of commands and settings available through URL access, see [URL access parameter reference] later in this article." 

This complete list of commands is missing three of the four commands though. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ad3c142-3ac7-abf8-d41f-64ca977e2847
* Version Independent ID: 8fbf0c86-d87a-fb30-f4e1-c80f5fe32dd3
* Content: [URL parameters in paginated reports - Power BI Report Builder - Power BI](https://docs.microsoft.com/en-gb/power-bi/report-builder-url-parameters#feedback)
* Content Source: [powerbi-docs/report-builder-url-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-url-parameters.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @tconrady -- belatedly, thanks for your feedback! You're right, the article was incomplete. I've added the Parameter panel state section. Check it out: 
https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-url-parameters#url-access-parameter-reference
Thanks!
