### ISSUE TITLE
Page doesn't work with Dark Theme

### ISSUE THREAD

**Issue by LouOtway** [MicrosoftDocs/powerbi-docs#1394]
Consider using graphics that work with dark theme in future!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security)
* Content Source: [powerbi-docs/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by LouOtway** [comment]
Ahh, sorry, seems I'm not the first to make this comment!

**Comment by mgblythe** [comment]
@LouOtway - I'll take a look and fix these

**Comment by mgblythe** [comment]
Fixed, thanks for pointing this out.
