### ISSUE TITLE
Contributor 

### ISSUE THREAD

**Issue by ak-sbd** [MicrosoftDocs/powerbi-docs#1395]
in the table, it seems as if contributor can "Create, edit, and delete content in the workspace." however it seems to me as if that person still needs a pro license to create content. Which means there should be a asterisks 1 up there in the table next to "Create, edit, and delete content in the workspace." for Contributor.

This goes to the extent that if I add a new user as a contributer but that person does not have a pro license, he can not actually join to even view this workspace since there is a misalignment of role vs permission.

@maggiesMSFT please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @ak-sbd. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @ak-sbd -- I see your point. What isn't stated in the article, and should be, is that admins, members, and contributors have to have Pro licenses to do any of the things assigned to them in the table. The superscript 1 is just to indicate that for those 2 actions, even a viewer role also needs a Pro license. Really the only action a person can do in a workspace without a Pro license is view an item.
Thanks for pointing that out. I'll make it clearer.

**Comment by maggiesMSFT** [comment]
Hi, @ak-sbd -- I've updated the article to make it clearer. Hope that helps. Thanks!
