### ISSUE TITLE
SQL server running on a VM in Azure

### ISSUE THREAD

**Issue by SuperSing** [MicrosoftDocs/powerbi-docs#1396]
Hi, Is Power BI gateway needed for connecting to a SQL server running on a VM in Azure.

**Comment by maggiesMSFT** [comment]
Hi, @SuperSing -- not sure which article you're referring to. Assigning to the author for gateways in the hope that he can help.
Thanks!

**Comment by SuperSing** [comment]
Thanks! It is related to on-premise gateway.


On torsdag, september 5, 2019, 11:24 pm, Maggie Sparkman <notifications@github.com> wrote:


Hi, @SuperSing -- not sure which article you're referring to. Assigning to the author for gateways in the hope that he can help.
Thanks!

**Comment by mgblythe** [comment]
Hi @SuperSing, a gateway is required for SQL Server on a VM. You could also use SQL Azure database, which might or might not require a gateway depending on how you configure connectivity.
