### ISSUE TITLE
How to identify CapacityID

### ISSUE THREAD

**Issue by Matusa69** [MicrosoftDocs/powerbi-docs#1397]
Improve the documentation about how to use the Set-PowerBICapacityEncryptionKey becuase it is not explained how to identify the CapacityID. 

Add the information to use the Get-PowerBICapacity cmdlet. 
Also not sure if CapacityID is visible on the Power BI Capacity Admin page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9a86dc-4be4-d0a2-644d-cb20e3af74fb
* Version Independent ID: d08af8bc-fb3e-e443-7152-abaa0f2df6cc
* Content: [Bring your own encryption keys for Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-encryption-byok#feedback)
* Content Source: [powerbi-docs/service-encryption-byok.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-encryption-byok.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @Matusa69 -- thanks for your comment. I've assigned it to the author to investigate.

**Comment by mgblythe** [comment]
Thanks @Matusa69, I added a step that shows Get-PowerBICapacity
