### ISSUE TITLE
Can we have a section on how to customize the relative date range slicer to show Data ranges according to the Fiscal year and not the auto calendar year?

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#1398]
It by defaults uses jan 1st and dec 31st as start and end of year. Would be good to have a document that shows how to use Fiscal year to be displayed. 
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab98c7ec-c151-af65-c116-d03d6b2506a2
* Version Independent ID: 8767e90e-0f08-0dc6-a52f-10298a6128b7
* Content: [Overview of report visualizations in Power BI service and Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-report-visualizations)
* Content Source: [powerbi-docs/visuals/power-bi-report-visualizations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-report-visualizations.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @dhruvinushah -- a useful idea. I'm assigning it to the author for consideration.
Thanks!

**Comment by mihart** [comment]
Hi @dhruvinushah ,
This has been added to our backlog. We will try to add this scenario to the slicer documentation the next time it is updated.
