### ISSUE TITLE
sample databases

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#1399]
Merge [issue #1075](https://github.com/MicrosoftDocs/powerbi-docs/issues/1075)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Take a tour of the samples available with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-datasets)
* Content Source: [powerbi-docs/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @rootsmusic -- I closed the old issue https://github.com/MicrosoftDocs/powerbi-docs/issues/1075 as you have opened this new one on the same subject, and we don't need 2 issues.
I still think it's a good idea. I still can't promise a timeline.
Thanks!
