### ISSUE TITLE
REST API V2

### ISSUE THREAD

**Issue by AlanPBourke** [MicrosoftDocs/powerbi-docs#140]
Badly need examples based on REST API V2 and async operations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6192675-1fad-3f96-36c7-16a54075a060
* Version Independent ID: 8aa38db1-1768-3588-1517-d0ddd2b10a7d
* Content: [Push data into a dataset - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data)
* Content Source: [powerbi-docs/developer/walkthrough-push-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks @AlanPBourke! I'm passing your feedback on to the author.

**Comment by markingmyname** [comment]
@AlanPBourke Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@AlanPBourke There is currently no REST API V2.

**Comment by SaranrajK** [comment]
Is it possible to push data to existing data set that's not created using rest API.

**Comment by ranmax123** [comment]
@SaranrajK: Not possible.
