### ISSUE TITLE
Paginated Reports

### ISSUE THREAD

**Issue by mattschoen** [MicrosoftDocs/powerbi-docs#1401]
When will PowerBI Embedded support paginated reports for the "App Owns Data" scenarios?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @mattschoen -- for news on upcoming features, the place to look is the New & planned features page in the Business Applications Release Notes:
https://docs.microsoft.com/en-us/business-applications-release-notes/april19/business-intelligence/planned-features
Hope that helps!

**Comment by khregs** [comment]
The link posted by maggieMSFT above is outdated. Current link:
[https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/business-intelligence/planned-features](https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/business-intelligence/planned-features)

It would also be helpful if this information was added to the [Paginated Reports in Power BI FAQ](https://docs.microsoft.com/en-us/power-bi/paginated-reports-faq). My team spent a not-insignificant amount of effort trying to deploy a new paginated report into an existing embedded application before stumbling across this thread.

Thanks!
