### ISSUE TITLE
When will PowerBI Embedded support paginated reports for the "App Owns Data" scenarios?

### ISSUE THREAD

**Issue by mattschoen** [MicrosoftDocs/powerbi-docs#1402]
ETA?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09cf6129-9d7f-0e47-75f3-89f5df01c5e9
* Version Independent ID: a1d90b2d-0e8b-da1f-fa30-a3294a98dc25
* Content: [Paginated reports in Power BI: FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-faq)
* Content Source: [powerbi-docs/paginated-reports-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-faq.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mattschoen -- for news on upcoming features, the place to look is the New & planned features page in the Business Applications Release Notes:
https://docs.microsoft.com/en-us/business-applications-release-notes/april19/business-intelligence/planned-features
Hope that helps!
BTW, I'm going to add the same note to your other Git Issue, https://github.com/MicrosoftDocs/powerbi-docs/issues/1401.
Thanks!
