### ISSUE TITLE
Is this for S/4 HANA on-premise or cloud or both?

### ISSUE THREAD

**Issue by kfeit** [MicrosoftDocs/powerbi-docs#1403]
Please clarify if this page applies to S/4 HANA on-premise or S/4 HANA Cloud, or to both options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea414a5c-c3ca-281e-46ca-3e677d27924b
* Version Independent ID: 363a9c9c-13e2-58ce-cb79-9f897d83c307
* Content: [Use SAP HANA in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana)
* Content Source: [powerbi-docs/desktop-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-hana.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @kfeit  - thanks for your question! Assigning to the author to investigate and reply.

**Comment by davidiseminger** [comment]
Thanks for your post - it applies to both.
