### ISSUE TITLE
version number not correct

### ISSUE THREAD

**Issue by lcallewi** [MicrosoftDocs/powerbi-docs#1405]
Hello,
it seems the version number for the August 2019 Update (2.71.5523.641) release as stated on this page is the same as the version number for the July 2019 Update (2.71.5523.641) on page https://docs.microsoft.com/en-us/power-bi/desktop-latest-update-archive. We are taking these version numbers to report on in our Power BI  reporting. The duplicates are causing us a problem in the reporting. Thanks for rectifying. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#feedback)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks @lcallewi. I'm assigning to the author to fix. My current install is at 2.73.5586.421, but it's possible that's ahead of the August release.

**Comment by davidiseminger** [comment]
Sorry about that, @lcallewi ! I've updated the article, which will be live in the next ~24 hours.

Meanwhile, the correct number for August is: 2.72.5556.801
