### ISSUE TITLE
The report render function in Embed doesn't work with mobile layaout

### ISSUE THREAD

**Issue by Hormash** [MicrosoftDocs/powerbi-docs#1406]
I have a report in Power BI with a mobile layout (and also desktop).
I load my report with `report.load(embedContainer, conf);` to set up my report in Power BI Embedded with JavaScript, after this I use `report.render(conf);` or `report.render();` to show it, but my report with a Mobile Layout, will load a desktop view. It is like has lost the `layoutType` variable. Is there some kind of solution to this?

`var conf:{
...
    settings: {                
        layoutType: models.LayoutType.MobilePortrait
    }
}`
If I user `powerbi.embed(embedContainer, config);` there is no problem, but is not ideal to me.

**Comment by maggiesMSFT** [comment]
Hi, @Hormash -- are you asking about a specific article? That will help in assigning your question.
Thanks!

**Comment by Hormash** [comment]
Hi, my problem is with **PowerBI-JavaScript**, the render function lost the layoutType variable, so will load a desktop view.

**Comment by rkarlin** [comment]
@paulinbar

**Comment by paulinbar** [comment]
Hi @Hormash. Thank for pointing this out. I am forwarding your comment on to the team that is checking that out. So for now I'll close the issue here. 
Thanks for reaching out!
