### ISSUE TITLE
using the same account for Power BI and Azure

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#1407]
I'm signed into the Azure portal, and my role is account admin.  I'm trying to follow step #2, but I don't see "Administrators" listed under Settings.
![image](https://user-images.githubusercontent.com/22034168/64456688-aea8f380-d0a5-11e9-9076-92fb808ae947.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1c4bd6b-562e-8df4-975c-ca75cfab47b6
* Version Independent ID: 7fe0beaa-870d-f157-0e25-12a0709a4b77
* Content: [Using the same account for Power BI and Azure - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-how-to-use-the-same-account-as-azure)
* Content Source: [powerbi-docs/service-admin-how-to-use-the-same-account-as-azure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-how-to-use-the-same-account-as-azure.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @rootsmusic -- I'm assigning your question to the author to advise. Thanks!

**Comment by mgblythe** [comment]
Hi @rootsmusic -this will be fixed tomorrow. In the meantime, here's the correct steps:

In the navigation pane, select **Access control (IAM)**, then select **Add** and **Add co-administrator**.

**Comment by mgblythe** [comment]
Updated the article, so closing this one out. Thanks @rootsmusic!
