### ISSUE TITLE
Multiple Enrollments?

### ISSUE THREAD

**Issue by mattlinak** [MicrosoftDocs/powerbi-docs#1408]
How do you handle multiple enrollments, each has its own API access key. What if I want to combine them all into one view instead of separate PowerBI workspaces?

**Comment by davidiseminger** [comment]
Thanks for your comment, @mattlinak. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
