### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by nphadro** [MicrosoftDocs/powerbi-docs#1409]
Please help me understand if RLS passes through when Analyzing in excel?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @nphadro . Let me look into that and respond to this thread (and update the doc) accordingly. Thanks!

**Comment by joebrown42** [comment]
Hi. this is crucial for me in a project I am working on. Does RLS pass through the Analyze in Excel option?

**Comment by nphadro** [comment]
@davidiseminger any updates? Thanks

**Comment by davidiseminger** [comment]
@nphadro  -  yes, RLS passes through when using Analyze in Excel.
