### ISSUE TITLE
Dashboard Theme Images

### ISSUE THREAD

**Issue by kfollmer24** [MicrosoftDocs/powerbi-docs#141]
I'm excited about using a custom image as a background to my dashboard, but does it have to be a publicly available image? Will this change?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b534707-1253-6a56-5b6e-d69edf32e1ab
* Version Independent ID: 34be0bef-858c-658f-4bbd-dc4da405759c
* Content: [Use dashboard themes in Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-themes)
* Content Source: [powerbi-docs/service-dashboard-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-themes.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Good question, @kfollmer24! I've pinged the author.

**Comment by mihart** [comment]
Hi @kfollmer24 ,
Thank you for writing.  I've updated the article to include this limitation.  In the meantime, I'm checking with the feature owner to find out all the URL limitations so I can add these to the document as well. 
Take care,
Michele
