### ISSUE TITLE
Example shown only works for Summaries

### ISSUE THREAD

**Issue by TheSaltyKorean** [MicrosoftDocs/powerbi-docs#1410]
The example shown for the custom report months, only works for the Summaries table.  In most cases we need UsageDetails.  We also need resource name in Usage Details as well.

https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#using-azure-consumption-insights

**Comment by mihart** [comment]
Thanks for your comment, @TheSaltyKorean. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @TheSaltyKorean - we're in the process of updating that article, and will address that and other questions in the next update. Thanks.
