### ISSUE TITLE
Security rules are defined in the underlying source

### ISSUE THREAD

**Issue by mpsingh24** [MicrosoftDocs/powerbi-docs#1411]
Can you please update the article and publish a list of data sources where Power BI can leverage "Security rules defined in the underlying source"? E.g. SSAS, SQL Server, Teradata?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mpsingh24. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @mpsingh24. There are many, many data sources out there and coverage of all of them as you described would be challenging, and run the risk of leaving some out unintentionally. 

That said, you can submit product feedback or feature ideas by going to https://ideas.powerbi.com, including asking for creating a list like you describe. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
