### ISSUE TITLE
In power BI Service New Look we are not able to Navigate from Hidden page to some other pages

### ISSUE THREAD

**Issue by kanthu85** [MicrosoftDocs/powerbi-docs#1412]
I have 4 Pages A,B,C,D in Power BI Desktop. B page is hidden and using bookmark I am accessing B From A.
After Publishing the report(New Look) From A I am going to B by using button(Which is hidden).From there I am not navigating to C,D.
In power bI Service  New Look.

**Comment by mgblythe** [comment]
Thanks for your comment, @kanthu85. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
