### ISSUE TITLE
Updates are a pain

### ISSUE THREAD

**Issue by tyddaj** [MicrosoftDocs/powerbi-docs#1413]
Why can't Power BI Desktop be updated through Windows Update? Or when you update Office 365?
Or even offered as a product category in SCCM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#previous-months-updates)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @tyddaj -- Thanks for the feedback! 
This is a good place to make documentation feedback. 
https://ideas.powerbi.com/forums/265200-power-bi is the place to submit product feedback. Plus you can look through it and see if anyone else has suggested the same thing already.
Thanks!
