### ISSUE TITLE
Special datetime format required?

### ISSUE THREAD

**Issue by Mholsen** [MicrosoftDocs/powerbi-docs#1414]
I have a table in a Azure SQL database with a datetime column which I want to enable incremental refresh on. The problem is that I keep getting the "query folding" warning, and if I run the incremental refresh anyway it is painfully slow.
The only thing I can think of being the cause of the query being non-foldable is the fact that the DateTime column also contains milliseconds.
Does the DateTime format strictly has to be 'YYYY-MM-DD-HH-MM-SS' for query folding and therefore incremental refresh to work in Power BI? Maybe there is even a preferred T-SQL DateTime format like 120 etc?
If so you should add it to the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @Mholsen -- thanks for the question and suggestion! I've assigned to the author to look into it.

**Comment by mgblythe** [comment]
Assigning to @christianwade to see if he can clarify what's expected here, and we can update the docs.

**Comment by christianwade** [comment]
It sounds more likely that there was a different cause for not folding, like data type conversion, or other logic in the query.
#please-close
