### ISSUE TITLE
Filter Pane, visual header features are hidden

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1415]
The Limitations section should note that the Filter pane and most visual header features are hidden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web#limitations)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- thanks for the suggestion! I've assigned it to the author for their consideration.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @Mike-Honey,

Thanks for bringing this to our attention.

I'm looking into the issue and will ask the article owner to update it shortly.

**Comment by KesemSharabi** [comment]
Hi @Mike-Honey, 

Thanks for your comment and apologies for the late response.

When you use the **Publish to web** feature, the embedded content only includes the report you publish. As a result, you cannot access additional Power BI features such as the filter pane, from the embedded report. This is not a limitation, it's simply the way this feature is designed.

If you want to have greater control over the embedded content, I suggest that you try **Embedded analytics**. This is allows greater control over the way your content is embedded, and is also a much more secure way of embedding your Power BI content. You can try one of the following solutions:
* [Embedded analytics with Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedding)
* [Power BI Embedded in Azure](https://docs.microsoft.com/en-us/power-bi/developer/azure-pbie-what-is-power-bi-embedded)

Thanks,

Kesem

**Comment by Mike-Honey** [comment]
Hi @KesemSharabi 
Understood. I was hoping for the documentation page (linked to this issue) could be updated to covey that information to a broader audience?
Regards, Mike
