### ISSUE TITLE
2GB Limit with On-Premise PBI Report Server?

### ISSUE THREAD

**Issue by ScottAdams1** [MicrosoftDocs/powerbi-docs#1416]
It seems like there should not be a limit for the PBI Report Server since the memory resources are all coming from my server (not a PBI hosted server).  Is this documentation accurate when it says "You can upload files up to 2 GB in size"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff7e1942-9181-3451-5d1e-08bfa2ca9454
* Version Independent ID: 5547fc15-7d0e-225f-e0f1-890470f6cd5e
* Content: [What's new in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/whats-new#feedback)
* Content Source: [powerbi-docs/report-server/whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/whats-new.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ScottAdams1 -- good question. I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @ScottAdams1 -- wow, got you a quick answer! 
The way the models are stored in the SQL database hosting the catalog means we are limited to 2 GB per model.
