### ISSUE TITLE
New Look and New Filters

### ISSUE THREAD

**Issue by mikecjohn** [MicrosoftDocs/powerbi-docs#1417]
If and when the New Look is turned on by default, how will report designers know?  We are so impressed with the constant evolution of new features in Power BI, but I have trouble knowing which features are in preview for me, and which ones my colleagues are seeing by default. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter#feedback)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mikecjohn -- good question! Typically new features are turned on when they become generally available (GA). If you follow the monthly Power BI blog (https://powerbi.microsoft.com/en-us/blog/), you'll see an announcement when the new look reaches GA. 
Hope that helps!
