### ISSUE TITLE
Restrict changes to filter type

### ISSUE THREAD

**Issue by mikecjohn** [MicrosoftDocs/powerbi-docs#1418]
This section needs more description. Does this mean that users (report consumers) can change a filter from "less than" to "more than" unless we take this ability away by unchecking this box?  Or does it mean much more than that? What are the other filter types, and what exactly is enabled if this box is checked? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mikecjohn -- thanks for asking. I'll get back to you and update the article.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
