### ISSUE TITLE
Unhelpful reference

### ISSUE THREAD

**Issue by DG-LPS** [MicrosoftDocs/powerbi-docs#1419]
Item 5 states: "Compare the provider with the list of supported data sources found within Refresh data in Power BI".
I can't find any such list in the referenced page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a46dbd1-2511-bc77-e09a-00b01540afa5
* Version Independent ID: 58ec402c-8a94-0752-c823-2ddd917b18df
* Content: [Troubleshooting unsupported data source for refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-troubleshoot-unsupported-data-source-for-refresh#feedback)
* Content Source: [powerbi-docs/service-admin-troubleshoot-unsupported-data-source-for-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-troubleshoot-unsupported-data-source-for-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @DG-LPS, we have some work underway to improve refresh troubleshooting in general as well as better data source info. I'll leave this open until we publish those updates.

**Comment by BSLATTER** [comment]
Hi @mgblythe - is there an update for this?

**Comment by mgblythe** [comment]
Updating the link today, the article it now points to is https://docs.microsoft.com/power-bi/power-bi-data-sources
