### ISSUE TITLE
Practice material used by the trainer

### ISSUE THREAD

**Issue by Emuntean** [MicrosoftDocs/powerbi-docs#142]
I would be great to have access to the sample data files used in the examples provided.
Good to review the practices.
Attachments to be provided to each example should be useful.
rgs,
Eugen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Getting data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @Emuntean -- interesting idea! I've let the author know.

**Comment by davidiseminger** [comment]
Thanks for your comment @Emuntean - some of our docs do include the data used in the demo, but not all. In the future, we'll try to add a link to those so you can use them yourself. Thanks!
