### ISSUE TITLE
Incorrect Sequence Numbers for August 2019

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#1422]
The August and July sequence numbers are identical:
August 2019 Update (2.71.5523.641)
July 2019 Update (2.71.5523.641)

August should be listed as (2.72.5556.801)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update-archive#feedback)
* Content Source: [powerbi-docs/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @itsnotaboutthecell. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Sorry about that, and thanks! I've updated that number, should be live in ~24 hours.
