### ISSUE TITLE
Two typos

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#1424]
"and enhanced engine has been release" should be "an enhanced engine has been released" (and -&gt; an, release -&gt; released)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd16a9c-3620-e1c6-518a-d6a5f9174089
* Version Independent ID: c55ccf5a-5563-1a05-7cec-46666a9e8f08
* Content: [Best practices for Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-best-practices)
* Content Source: [powerbi-docs/service-dataflows-best-practices.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-best-practices.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mohaali
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for catching that issue, @otravers! I've assigned this issue to the doc author for review.

For future reference - you can also edit articles directly. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. The change is then sent directly to the writer, who will sign off and get it published. Thanks again!

**Comment by davidiseminger** [comment]
You're right, @otravers - I've made that correction, should update in ~24 hours. Thanks for the close read, and for pointing it out!
