### ISSUE TITLE
Change language of x-axis

### ISSUE THREAD

**Issue by damf74** [MicrosoftDocs/powerbi-docs#1425]
Hi, is it possible to rename or change the language of x-axis, like changing "Qtr" (english) to "Trim" (french) for example ? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad604499-b845-44de-acc9-1bd9a7a97488
* Version Independent ID: f16079ec-98ee-e35d-f928-c5d493365051
* Content: [Customize X-Axis and Y-Axis properties - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-customize-x-axis-and-y-axis#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @damf74. I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Thanks for your comment, @damf74. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
