### ISSUE TITLE
Trend Line and Forecast Options Missing

### ISSUE THREAD

**Issue by Shart243** [MicrosoftDocs/powerbi-docs#1426]
Hi - The Trend Line and Forecast Options are missing in the first 7 screenshots.  How do you get them to appear in the last screenshot? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Using the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-analytics-pane#feedback)
* Content Source: [powerbi-docs/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. I believe if you just experiment with your report and model, you'll learn how forecasting (what I believe you mean by a trend line) works in reports.

Another avenue for input on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com.
