### ISSUE TITLE
Lack of detail in documentation re: optional paths in this screen; pitfall ridden code (assumes all worksheet names are consistent, instead of allowing an option to choose by ordinal position

### ISSUE THREAD

**Issue by torevor** [MicrosoftDocs/powerbi-docs#1427]
Lack of detail in documentation re: optional paths in this screen - with an Excel workbook, it appears you must choose a specific worksheet, but you can also select the root, so the function is passed the entire workbook.  Literally one sentence pointing this out on this screen written by one developer would likely save thousands of end user hours.

Pitfall ridden code - assumes all worksheet names are consistent, instead of allowing an option to choose by ordinal position

If importing from a folder, assumes all files/worksheets have the same number of columns as the sample file, instead os using something more robust like:
    #"Expanded Data" = Table.ExpandTableColumn(theTable, "Data", List.Union(List.Transform(theTable[Data], each Table.ColumnNames(_))))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f77182-6acb-3273-cb81-2ccf5aacf4dd
* Version Independent ID: 092dfc43-f05f-61f2-ebc4-67ae4f41266b
* Content: [Combine files (binaries) in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-combine-binaries#feedback)
* Content Source: [powerbi-docs/desktop-combine-binaries.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-combine-binaries.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @torevor . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thank you for your comments. I've updated that article, and added a note that lets readers know the implications of where they select the file, folder, worksheet and so on. Directly below that note, it (already) specifies that you can combine files as long as they have the same file structure. These updates will be live in the next ~24 hours.
