### ISSUE TITLE
Paginated reports for Power BI Govt Cloud

### ISSUE THREAD

**Issue by saket90** [MicrosoftDocs/powerbi-docs#1428]
I am unable to upload the .rdl files to app.powerbigov.us. There is not even an option to enable this feature in the admin portal. Could you confirm if this feature has been rolled out for the government cloud?

**Comment by davidiseminger** [comment]
Thanks for your comment, @saket90 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
