### ISSUE TITLE
Link to resources / api

### ISSUE THREAD

**Issue by jbreadner** [MicrosoftDocs/powerbi-docs#1429]
This page works well as a resource to guide someone through the process of creating a visualization.  However, these pages could really benefit from linking to the full scope of what features are available.  For instance, what are valid values for capabilities.json's objects.*.properties.*.type ?  Other sections of the tutorial could also benefit, like what are all of the different capabilities.js  dataViewMappings.table.rows.select options?  Links to API documentation for each of the major PowerBI components would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f573b62f-4028-ce65-b5ae-a4115ee1bcd1
* Version Independent ID: 1cedde6a-9245-42da-c25e-83706f551c79
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jbreadner. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @jbreadner,

Thank you for your comment. We will take it into consideration when updating the article.

For now, please review the [Power BI visual concept](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept) article for additional information.
