### ISSUE TITLE
Access to data used

### ISSUE THREAD

**Issue by scramiro** [MicrosoftDocs/powerbi-docs#1431]
The word doc is great to understand it. However, I can't completely understand it. it would help to have the data to see how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7bffc1-7691-53e6-c582-c17b3f4c03da
* Version Independent ID: 6d3ce776-d39a-b834-e05b-73bc5452fd63
* Content: [Bidirectional cross-filtering in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bidirectional-filtering#feedback)
* Content Source: [powerbi-docs/desktop-bidirectional-filtering.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bidirectional-filtering.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @scramiro. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments. We'll look into posting the data in a future update.
