### ISSUE TITLE
Incremental Refresh Supported For SAP BW?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1432]
It seems that Microsoft has not made clear if all the data sources are enabled with Incremental Refresh, for now I can see that composite model have limitations, but if I have an SAP BW model and only 1 method of connectivity is used lets say import, then will it support for Incremental Refresh?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @Anmolgan81 . This issue has been assigned to the doc author for review.

**Comment by christianwade** [comment]
Given that there are many different causes for not folding queries including source system capabilities, which change, we were unable to provide a definitive list of data sources that "do" or "don't" support query folding required for incremental refresh. All the information we were able to provide is here: https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#query-folding
#please-close
