### ISSUE TITLE
Published Apps on android issue

### ISSUE THREAD

**Issue by sedaelmas** [MicrosoftDocs/powerbi-docs#1433]
When i want to access to a published power BI app on power BI mobile aplication on android device, it opens the first dashboard as default. I have to 2-3 clicks to reach the navigation view of the published app.
Are there any way to make it behave like IOS in Android too? (In IOS when i click to puplished app, it opens navigation list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f16a650-3781-bafb-88da-25ee12d688a1
* Version Independent ID: 4fc5c657-cbae-d49c-ce67-e8ae8b503164
* Content: [Get started with the Power BI mobile app on Android devices - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-android-app-get-started#feedback)
* Content Source: [powerbi-docs/consumer/mobile/mobile-android-app-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-android-app-get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @mshenhav
* Microsoft Alias: **mshenhav**

**Comment by mihart** [comment]
Thanks for your comment, @sedaelmas . This issue has been assigned to the doc author for review.

**Comment by mshenhav** [comment]
Hey @sedaelmas , 

Both apps should behave the same. Make sure you have the recent store app on each platform.
In addition, make sure you test the same published app. There are differences between apps published before the service released custom navigation and new app with custom navigation.

Regardless, the in the next Power BI apps release (expected in the coming weeks) we will be adding an action that will allow you to navigate the app list directly from the apps menu.

Regards, 
Maya

**Comment by mgblythe** [comment]
Thanks @mshenhav!
