### ISSUE TITLE
Can you increase the size of the field icon pictures?

### ISSUE THREAD

**Issue by sandramcg** [MicrosoftDocs/powerbi-docs#1434]
It's quite hard to see the differences between the different icons in the section "The field icons", it would be really helpful if these were doubled in size.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd081c3-9f0f-07b5-b0dd-4270ddc2232f
* Version Independent ID: 8d92a854-ddff-3c3e-c044-a2d06e68f55c
* Content: [Tour the report editor - Power BI](https://docs.microsoft.com/en-us/power-bi/service-the-report-editor-take-a-tour#what-do-the-field-icons-mean)
* Content Source: [powerbi-docs/service-the-report-editor-take-a-tour.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-the-report-editor-take-a-tour.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @sandramcg. I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @sandramcg -- good idea! I don't know if I can get larger versions. I can't just make these images larger. They will look funky. I'll check and let you know.
Thanks!

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. We are closing this issue, but have created a work item in the writer’s backlog to consider your feedback in the next update.
