### ISSUE TITLE
Zendesk :: Time Slicer not working

### ISSUE THREAD

**Issue by francesco1119** [MicrosoftDocs/powerbi-docs#1435]
I tried a few time slicers: 

![Zendesk - Power BI 2019-09-18 11-05-11](https://user-images.githubusercontent.com/3397477/65134265-48589500-da04-11e9-9093-6e1202a0cb35.png)

Non e is working.

Is it possible to add a time slicer to such metrics? 

Thank you

**Comment by mgblythe** [comment]
Thanks for your comment, @francesco1119. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by francesco1119** [comment]
I found a solution BTW, I had to use a specific metric from Zendesk about the ticket updates.

SOLVED
