### ISSUE TITLE
SAP BW/4HANA is not supported in dataflows 

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#1436]
Hello, PowerBI PG has stated that SAP BW/4HANA is not officially supported in dataflows. Can we include this in the document? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1458e2bc-7637-e305-55f3-596c64972ff3
* Version Independent ID: b5437e14-6d46-e2f6-0369-e61f72988ff3
* Content: [Learn how to connect to dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-data-sources#feedback)
* Content Source: [powerbi-docs/service-dataflows-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @adamwp1993. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment @adamwp1993. We don't generally list data sources that are _not_ supported for a given feature, since that could be a vast and open-ended list. Rather, we clarify which sources are supported.

**Comment by adamwp1993** [comment]
SAP/BW is under the list of things that you can connect with but our product group has stated that it is not supported :

The following list shows which connectors you can currently use by copying and pasting the M query into a blank query:
	
SAP Business Warehouse
	Azure analysis Services
	Adobe Analytics
	ODBC
	OLE DB
	Folder
	SharePoint Online folder
	SharePoint folder
	Hadoop HDFS
	Azure HDInsight (HDFS)
	Hadoop file HDFS
	Informix (beta)

We should remove SAP BW from the doc then since it is confirmed as not supported.

**Comment by davidiseminger** [comment]
Hi @adamwp1993 , sorry for my misunderstanding. I've removed SAP from the list of supported connectors. The article will update and be live within ~24 hours.
