### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#1437]
this sentence:

"Power BI limits datasets on shared capacity to eight daily refreshes. If the dataset resides on a Premium capacity, you can perform up to 48 refreshes per day. For more information, see Configuring scheduled refresh later in this article." 

is no longer the case. It is just a limit of the UI, while that limit does not apply to APIs 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data#feedback)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @frvigano. I’ll add this request to our docs backlog.

**Comment by mgblythe** [comment]
Assigning to @KayUnkroth to confirm the rewrite:

Power BI limits datasets on shared capacity to eight daily refreshes. If the dataset resides on a Premium capacity, you can perform up to 48 refreshes per day through the UI. There is no limit if you use the API. For more information, see Configuring scheduled refresh later in this article

**Comment by mgblythe** [comment]
Thanks @frvigano, confirmed that there are no limits for Premium with the API. Docs will be updated later today or early next week.
