### ISSUE TITLE
Embed in SharePoint Online => Require License for viewer

### ISSUE THREAD

**Issue by yhlow72** [MicrosoftDocs/powerbi-docs#1439]
Embed in SharePoint Online =&gt; Require License for viewer
Embed in SharePoint Online works with the Power BI web part for SharePoint Online. It provides a single sign-on experience with control over how the report is embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df058604-4117-88d8-0cb0-935d08e5b22a
* Version Independent ID: dc8d3604-1fea-0109-2a94-13bd70a10522
* Content: [Ways to share your work in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-how-to-collaborate-distribute-dashboards-reports#feedback)
* Content Source: [powerbi-docs/service-how-to-collaborate-distribute-dashboards-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-how-to-collaborate-distribute-dashboards-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @yhlow72. I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
