### ISSUE TITLE
Multiple themes within one report

### ISSUE THREAD

**Issue by cy2k** [MicrosoftDocs/powerbi-docs#144]
The custom report themes are great, but what we really need is the ability to have multiple color themes within one report, within one page.  I need to be able to have a particular color scheme for a bar chart, and then have a donut chart with different colors.  Because it can be confusing for people when they see charts with different data but have similar colors; it makes it seem like the data is about the same thing when it's not.  Is this being worked?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by ChipDale66** [comment]
this allows you to do just that i.e. have a particular color scheme for a bar chart, and then have a donut chart with different colors. Just define different colours for each type of chart.

**Comment by davidiseminger** [comment]
Thanks for your comment @cy2k - sounds like this is a feature request rather than doc feedback, so please use the ideas.powerbi.com venue for that. Also, the Power BI blog (https://powerbi.microsoft.com/blog/) has links to providing feedback on recent feature releases, so check that out as well to provide feedback or requests.
