### ISSUE TITLE
Add user to group docs wrong

### ISSUE THREAD

**Issue by scottmelhop** [MicrosoftDocs/powerbi-docs#1441]
On https://docs.microsoft.com/en-us/rest/api/power-bi/groups/addgroupuser the Group User parameter for email address is: emailAddress. However this returns:

`{"error":{"code":"InvalidRequest","message":"Parameter userDetails.UserEmailAddress is missing or invalid"}}`

Changing the parameter to UserEmailAddress works. Update docs please.

**Comment by mgblythe** [comment]
Thanks for your comment, @scottmelhop. I've assigned this issue to the doc author for review.

**Comment by laurent-mic** [comment]
Hi,
I am unable to reproduce this case. The only parameter accepted is **emailAddress**.
Sending this pots request with parameters like userEmailAddress, UserEmailAddress, EmailAddress, will return a Bad Request message is received (400).

Please check again and if you still see this strange behavior, please send more details: which version of the API you are using + details network traces of the API call including URL body and response .

**Comment by maggiesMSFT** [comment]
Hi, @scottmelhop -- closing the issue. If you still see the strange behavior, you can submit more details.
