### ISSUE TITLE
JSON in the Properties within each card - errors

### ISSUE THREAD

**Issue by poujor** [MicrosoftDocs/powerbi-docs#1442]
The huge JSON after the Heading :  Properties within each card
has a few syntactial errors:
{	is missing in first line - before	"general":  (Line 1)
{	is missing at the end of 		"general":  (Line 1) 
,	is missing at the end of 		}	    (Line 12)	just before the line with:	"legend": [
finally 2 closing
}	are missing at the end of the JSON

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @poujor. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you @poujor  - and apologies for those missing syntax elements. I've updated that sample, and it'll be reflected in the live article in ~24 hours. THANK YOU for taking the time to post those corrections!
