### ISSUE TITLE
Should mention this is Windows only

### ISSUE THREAD

**Issue by gflores1023** [MicrosoftDocs/powerbi-docs#1443]
I believe this is Windows only? It should mention that in the requirements since this doesn't work on Mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @gflores1023. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Good point @gflores1023  - I've added that to the requirements.
