### ISSUE TITLE
How can you tell if Query Caching is working?

### ISSUE THREAD

**Issue by rogersmj** [MicrosoftDocs/powerbi-docs#1444]
This sounds like the answer to our prayers (we have lots of QPU-intensive calculations but loads of memory headroom), but it doesn't seem to work. I enabled it on one of our heavy datasets, which has a calculation that typically takes around 80 seconds to complete. After enabling, that calculation still takes 80 seconds to complete every time I load the report.

**Comment by mgblythe** [comment]
Hi @rogersmj - thanks for the question. Was this related to a specific doc you were reading? We might be able to add something to the docs, but in the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by mgblythe** [comment]
Assigning to @Bhavik-MSFT to see if he has any insight into this.

**Comment by Bhavik-MSFT** [comment]
Hi @rogersmj , i assume you are talking about [Query Caching in Premium/Embedded](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching). We mention in the documentation that we only cache the first page of a report for a security context (including bookmarked state). We also don't cache queries generated by in-report interactions like slicer selections. In your case it seems the slow query is not actually cached - it should not even hit the engine if we have a cached result. Please try disabling caching for the dataset, then make sure the first page you view thereafter is the one with the slow query. We have work in progress right now to extend this caching to additional scenarios.
