### ISSUE TITLE
Does the availability include Southeast Asia?

### ISSUE THREAD

**Issue by timp3261** [MicrosoftDocs/powerbi-docs#1446]
Hi,
I saw Asia Pacific in the list but am not sure about Southeast Asia.
Please clarify.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-multi-geo#feedback)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @timp3261 . This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
@timp3261 -- I believe it does include SE Asia, but including @DavidMagarMS to confirm.

**Comment by DavidMagarMS** [comment]
yes it includes Southeast Asia.
an up to date view is always available in the trust center:
https://www.microsoft.com/en-us/TrustCenter/CloudServices/business-application-platform/data-location

**Comment by mgblythe** [comment]
Thanks @DavidMagarMS, closing this one out.
