### ISSUE TITLE
pbiviz start > Error in visual.ts 'TS2741: Property 'foreach' is missing in type 'HTMLCollectionOf<HTMLHeadElement>' but required in type 'NodeListOf<HTMLHeadElement>'.'

### ISSUE THREAD

**Issue by Shaney-ops** [MicrosoftDocs/powerbi-docs#1449]
Hi all,

I am having difficulties loading this visual.ts when executing "pbiviz start".
Something is off in this file and I can't seem to find the issue.

Can somebody help me?

I'm getting the following messages:

> ERROR in C:\sampleR\src\visual.ts
> ./src/visual.ts
> [tsl] ERROR in C:\sampleR\src\visual.ts(148,17)
>       TS2741: Property 'forEach' is missing in type 'HTMLCollectionOf<HTMLHeadElement>' but required in type 'NodeListOf<HTMLHeadElement>'.
> 
> ERROR in C:\sampleR\src\visual.ts
> ./src/visual.ts
> [tsl] ERROR in C:\sampleR\src\visual.ts(160,13)
>       TS2741: Property 'forEach' is missing in type 'HTMLCollectionOf<HTMLBodyElement>' but required in type 'NodeListOf<HTMLBodyElement>'.
> i ｢wdm｣: Failed to compile.

The code in visual.ts is:
```
141 // if 'updateHTMLHead == false', then the code updates the header data only on the 1st 
rendering
142        // this option allows loading and parsing of large and recurring scripts only once.
143        if (updateHTMLHead || this.headNodes.length === 0) {
144            while (this.headNodes.length > 0) {
145               let tempNode: Node = this.headNodes.pop();
146                document.head.removeChild(tempNode);
147            }
148            let headList: NodeListOf<HTMLHeadElement> = el.getElementsByTagName("head");
149            if (headList && headList.length > 0) {
150                let head: HTMLHeadElement = headList[0];
151                this.headNodes = ParseElement(head, document.head);
152            }
153        }
154
155        // update 'body' nodes, under the rootElement
156        while (this.bodyNodes.length > 0) {
157            let tempNode: Node = this.bodyNodes.pop();
158            this.rootElement.removeChild(tempNode);
159        }
160        let bodyList: NodeListOf<HTMLBodyElement> = el.getElementsByTagName("body");
161        if (bodyList && bodyList.length > 0) {
162            let body: HTMLBodyElement = bodyList[0];
163            this.bodyNodes = ParseElement(body, this.rootElement);
164        }
```

**Comment by mihart** [comment]
Thanks for your comment, @Shaney-ops . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
