### ISSUE TITLE
I want Data Sources supported by "Live Connection", too

### ISSUE THREAD

**Issue by yoshihirok** [MicrosoftDocs/powerbi-docs#145]
This content is nice, "Data sources supported by DirectQuery".
Next, I want new content "Data sources by Live Connection", too.

for create a Data Model by know which Data sources connected Import or DirectQuery or Live Connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by yoshihirok** [comment]
and Now, Power BI can connect multiple Data Sources supported by both Import and DirectQuery.
therefore, I want The List of Data Source supported by Live Connection.

**Comment by davidiseminger** [comment]
Thanks for your comment @yoshihirok - please see the Data Sources article for information about supported data sources. https://docs.microsoft.com/power-bi/desktop-data-sources

**Comment by yoshihirok** [comment]
Thanks
