### ISSUE TITLE
All data not showing in metrics tool sections.

### ISSUE THREAD

**Issue by rhalabi** [MicrosoftDocs/powerbi-docs#1450]
I am not seeing all data in the metrics tools for my premium workspaces. I have valid workspaces with datasets, but these workspaces/datasets do not show up in the corresponding dataset size and  dataset query durations sections in the metrics tool.  Many are missing, not just a couple.

**Comment by mihart** [comment]
Thanks for your comment, @rhalabi . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
