### ISSUE TITLE
Row Level Security vs Role Level Security

### ISSUE THREAD

**Issue by bfrancom** [MicrosoftDocs/powerbi-docs#1452]
Both this page and the Power BI security whitepaper¹ reference "RLS". In the whitepaper, it denotes Role level security, while this page denotes Row level security (Row vs Role, but use the same acronym). 
Are these the same things?
1. https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-security#user-authentication-to-data-sources

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @bfrancom -- thanks for your question(s)! I've assigned both to the authors.

**Comment by stoicmz** [comment]
Is Row level security and Role level security the same?

**Comment by mgblythe** [comment]
@bfrancom, @stoicmz  - yes these are the same thing in Power BI. It's _role_ based but has the effect of controlling access to specific _rows_.
