### ISSUE TITLE
Slicers do support visual level filters now.

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/powerbi-docs#1454]
See title.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Tutorial - Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @v-thepet
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @kthejoker -- thanks for pointing that out! Assigned to the author.

**Comment by mihart** [comment]
Hi @kthejoker ,
I've updated the document to remove this limitation.  Thanks for letting me know.
Michele
