### ISSUE TITLE
Download gateway link doesn't work

### ISSUE THREAD

**Issue by ManonHotte** [MicrosoftDocs/powerbi-docs#1455]
The link doesn't work : 
HTTP Error 500
http://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/PowerBIGatewayInstaller.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#feedback)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @ManonHotte -- Thanks for your question! 
I don't find this link, http://download.microsoft.com/download/D/A/1/DA1FDDB8-6DA8-4F50-B4D0-18019591E182/PowerBIGatewayInstaller.exe, on this page. Could you check again? 
Thanks!

**Comment by ManonHotte** [comment]
Hi @maggiesMSFT 
Sorry I couldn't answer sooner. Apparently the link now works, so no more problem !
Thank's a lot for your help !

**Comment by maggiesMSFT** [comment]
Hi @ManonHotte -- glad to hear it! I'll close this issue now. Thanks for letting us know!
