### ISSUE TITLE
Does Quickbooks Online still exist?

### ISSUE THREAD

**Issue by abshakibaBT** [MicrosoftDocs/powerbi-docs#1456]
In section 2, when I search for QuickBooks Online app, only the PREVIEW version of it shows up which is not free and works with Power BI Pro. 
Am I missing something here, that the free version of QuickBooks Online doesn't show up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by teddybercovitz** [comment]
Hi @abshakibaBT, The app itself is free - we will remove the (preview) in next weeks. 
Regarding pro - Installing a template app requires PowerBI pro while service content packs could be installed by a free user.
Service content packs were deprecated - if you have already installed a content pack it will continue to work.

**Comment by maggiesMSFT** [comment]
Thanks, @teddybercovitz ! Closing the issue
