### ISSUE TITLE
command-line options

### ISSUE THREAD

**Issue by DomHel** [MicrosoftDocs/powerbi-docs#1458]
1) please add a "-nocancelbutton" option when using "-passive" command-line switch (like qb-! MSI switch)
2) you forget to mention that the property DISABLE_UPDATE_NOTIFICATION=1 can also be used as a syntax parameter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 322970ff-d62a-adeb-c8b3-d1141d3a272f
* Version Independent ID: 94d82157-a824-73c8-2add-462ee6b033b1
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-get-the-desktop#feedback)
* Content Source: [powerbi-docs/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @DomHel -- thanks for the suggestions! Assigning to the author for visibility.

**Comment by davidiseminger** [comment]
Added the disable update notification information; the other parameter can be sent as a suggestion to the engineering team, using https://ideas.powerbi.com.
