### ISSUE TITLE
How To setup alerts after each successful refresh?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1459]
How can I send the alerts after each successful alerts? the alert should send a report overview screenshot and the link to the report after each refresh has successfuly configured.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe yourself and others to reports and dashboards - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-report-subscribe#feedback)
* Content Source: [powerbi-docs/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Anmolgan81 -- thanks for your question. I'm checking with my sources and will let you know.

**Comment by afreenhossain** [comment]
Hello, is there any update on this? The hourly option can be too spammy, so we would rather like to have it after every refresh.

**Comment by Anmolgan81** [comment]
They will not respond, since its not in development, if this is in development they should have responded long time ago.

**Comment by maggiesMSFT** [comment]
Thanks for asking @Anmolgan81. You're right -- this functionality doesn't exist yet. Please go to https://ideas.powerbi.com/forums/265200-power-bi-ideas and request it!
