### ISSUE TITLE
Calculated measure limitations

### ISSUE THREAD

**Issue by roofiq** [MicrosoftDocs/powerbi-docs#1460]
Hello,

I am highly disappointed with, as I have discovered, limitations in using calculated measures on live dataset.
It is not even possible to show aggregated value for latest date. Those are like basics to work with when it comes to these kind of solutions.

Hope it will be extended in the future.

Cheers

**Comment by maggiesMSFT** [comment]
Hi, @roofiq -- Thanks for reaching out! This sounds like a product issue, not a docs issue. I suggest entering your feedback in the Power BI Ideas site, https://ideas.powerbi.com/forums/265200-power-bi.
