### ISSUE TITLE
HELP ME POWER BI - USER TOKEN is Invalid

### ISSUE THREAD

**Issue by daisysim** [MicrosoftDocs/powerbi-docs#1461]
It's **IMPOSSIBLE** to get help from Power BI. The Support Ticket REFUSES to sign me in, despite changing my password 3 times, creating and logging into two different accounts. All because I want to edit my User Token information. Whenever I got on Power BI Desktop and I try to get data from my Quick Base website, they ask for an application URL and then state that I got the wrong User Token. Whenever I try to click on "edit" to change my User Token information, it goes back to the URL page but never shows an option to edit my User Token. I've tried LITERALLY EVERYTHING I can to get some help (Including creating this GitHub account) just to post on this on this Microsoft Help Page. _**SOMEONE WHO WORKS FOR POWER BI HELP ME WITH MY PROBLEM!!!**_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by ezaviv** [comment]
Hi daisysim, first Im sorry to hear you could not get any help from any of our customer facing channels, please make sure you are using our community pages to get all the info you need https://community.powerbi.com/
WRT the issue you raised, is this user token you are trying to use for Power BI embedded? if so please follow these docs, (I followed the links you have provided and found reference to old materials). 
https://docs.microsoft.com/en-us/rest/api/power-bi/embedtoken 
https://www.youtube.com/watch?v=4KuyPNtVijo - Power BI Embed Token Using Powershell
if this doesnt help, please let me know and i will ask a developer to further assist
Aviv

**Comment by daisysim** [comment]
Hello,

Thank you for your response. I really do appreciate any help you can
provide. A couple of notes to add context to this problem.

1. I'm using Power BI Desktop (not the Power BI, I don't know if that's
making a difference).
2. I'm just trying to log into my Quick Base account, so that I can get my
data there. (Since you offer Quick Base as an Online Service I can 'get
data' from I'm going to assume that yes this is an embedded user token)
3. I watched your Youtube video but found myself to be more confused. I
don't believe this is the error I'm encountering
4. I already have the user token (b4mscz_m4ny_bdrxtdtzw8j8fdym8y4abxsa67c) but
Power BI Desktop just won't let me edit my previous entry.
5. Whenever I try to get my Quick Base data, it asks for the application
URL and a user token but whenever I enter the URL, it states that I made an
error with the user token without ever giving me the option to edit the
user token.

I just want to edit our my previous entry for the user token and try this
one. By any chance can we schedule a time for us to either Zoom or Skype so
I can show you what I mean.

Thank you,
Daisy H. Sim

**Comment by rkarlin** [comment]
@ezaviv @maggiesMSFT

**Comment by KesemSharabi** [comment]
Thanks for your comment, @daisysim. 

This looks like a support request or product question rather than documentation feedback.

Please try to look for a solution in our [support page](https://support.powerbi.com) and the [Power BI documentation](https://docs.microsoft.com/power-bi/).
