### ISSUE TITLE
Support for MySQL?

### ISSUE THREAD

**Issue by RickyMcMaster** [MicrosoftDocs/powerbi-docs#1462]
Hi, is MySQL completely supported for incremental refresh?  It's working fine for me so far but it isn't listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#limitations)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe

**Comment by mgblythe** [comment]
Hi @RickyMcMaster, thanks for your question. I'm assigning @christianwade to confirm, then I can update docs if necessary.

**Comment by christianwade** [comment]
It depends on whether the logic can be folded or not. It's not as simple as listing the supported data sources. See [here ](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#query-folding)for more info. If you have traced the queries on the source and the date filter logic is being folded (included in the source queries), then you should be good.

**Comment by christianwade** [comment]
#please-close @mgblythe
