### ISSUE TITLE
Broken/inconsistent command line install options

### ISSUE THREAD

**Issue by MDawg957** [MicrosoftDocs/powerbi-docs#1463]
I'm trying to set up an install based off the instructions from https://docs.microsoft.com/en-us/power-bi/desktop-get-the-desktop#using-command-line-options-during-installation but I'm noticing multiple issues.

ENABLECXP - only works for the account the software is installed from.  Additional accounts do not reflect this setting. Value of `"EnableCustomerExperienceProgram"=dword:00000000` is placed in the key `HKEY_CURRENT_USER\Software\Microsoft\Microsoft Power BI Desktop` .

REG_SHOWLEADGENDIALOG - Does not work at all.  There is a value of `"ShowLeadGenDialog"=dword:00000001` set in the  `HKEY_CURRENT_USER\Software\Microsoft\Microsoft Power BI Desktop` key even though I set it to `0` in my command line. This should be set to something that applies to all users. I am able to resolve this by adding the value `"ShowLeadGenDialog"=dword:00000000` in the key `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Power BI Desktop` but this should work with the documented command.

For reference I'm using the command `PBIDesktopSetup_x64.exe -passive -norestart ACCEPT_EULA=1 DISABLE_UPDATE_NOTIFICATION=1 ENABLECXP=0 INSTALLDESKTOPSHORTCUT=0 REG_SHOWLEADGENDIALOG=0` for my installation.

**Comment by mgblythe** [comment]
Thanks for your comment, @MDawg957. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, adding another contact to help sort through your comments.

**Comment by MI77** [comment]
We fixed a couple of bugs in this area with the November release. This scenario should work now.

**Comment by MI77** [comment]
#please-close
