### ISSUE TITLE
Linking to specific pages or bookmarks

### ISSUE THREAD

**Issue by mlongoria** [MicrosoftDocs/powerbi-docs#1465]
It appears we cannot link to a specific report page or bookmark when using Publish To Web. I thought we could at one point, but adding the "/ReportSection{GUID}" at the end of a Publish to Web url doesn't work. Could you verify one way or the other and add to the limitations if we can't in fact link to a page or bookmark?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web#limitations)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for your comment, @mlongoria. I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by rkarlin** [comment]
@KesemSharabi can you please look into this?

**Comment by Smul1975** [comment]
Still waiting for an answer. In the past I could link to a specific report page when using Publish To Web. Now I can't succeed anymore. Is it disabled?
Would be a shame.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by AmanDaga** [comment]
Any updates on how could we do this? 
Not able to link a specific report page using Embed, only can change the landing page.

**Comment by KesemSharabi** [comment]
Hi @mlongoria,

Thanks for bringing this issue to our attention. I'm checking with the relevant team and will get back to you as soon as I get an answer.

**Comment by LukaszPawlowski-MS** [comment]
Sorry for the super late response. The publish to web URL supports a query string parameter 

&pageName=<pageIdentifer>

You can find the page identifier as the 'report section' at the end of the URL in the address bar when you view a report in the Power BI service. 

For example, if the report URL is:
https://app.powerbi.com/.../reports/abc123-72a8-421e-b503-xyz567/ReportSection2

Then "ReportSection2" is the page identifier. 

You would append the following to the Publish to web URL to open that page by default:
&pageName=ReportSection2

**Comment by dedijunadi** [comment]
Hi @LukaszPawlowski-MS I have a similar issue on publishing a spesific pages for PBIX report. I have 1 PBIX report that consist of 5 pages which I want to publish into 2 different website/portal.
- web1: publish all pages
- web2: publishe first page only
please kindly advise on the iframe URL for the 'web2'? thank you
