### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/powerbi-docs#1466]
Hi team, the comment below was machine translated.

@LucasCartisano commented on [Fri Sep 27 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/25)

I edited the permissions following the instructions on the page, both at the report level and at the data level it appears that user X has read permission, however when entering with this user the report, each visual object says that it contains restricted data

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Uso compartido de informes y paneles de Power BI con compañeros y otros usuarios - Power BI](https://docs.microsoft.com/es-es/power-bi/service-share-dashboards#feedback)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@srvbpigh commented on [Fri Sep 27 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/25#issuecomment-536098074)

Hello, @LucasCartisano
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
I moved this here because the user says that the instructions did not work for them.

Thanks!

**Comment by mihart** [comment]
Thanks for your comment, @lichasu. This issue has been assigned to the doc author for review.

**Comment by LucasCartisano** [comment]
Is not a doc issue, is a software error, the program say user has permissions but the user can not wee the reports

**Comment by maggiesMSFT** [comment]
Hi, @LucasCartisano and @ghost -- if it's a software issue, then the user needs to consult support, https://powerbi.microsoft.com/en-us/support/
