### ISSUE TITLE
RLS - Does Not Work on Dataset

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1467]
@lfalexandre commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/27)

I did the procedure described for RLS security, which works perfectly at the reporting level, however if the user connects via Dataset through Power BI Desktop, the RLS filter does not work and the user has full access to the Set even if he is classified as a Viewer.

Thanks

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [RLS (segurança em nível de linha) com o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

---

@srvbpigh commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/27#issuecomment-536736930)

Hello, @lfalexandre
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because it may be an issue related with the original documentation
best

**Comment by mihart** [comment]
Thanks for your comment, @CeciAc . This issue has been assigned to the doc author for review.

**Comment by MI77** [comment]
A user with edit permissions in a workspace will always be able to see the whole dataset (they could download the pbix and see all the data as well). If workspace members just have view permissions the RLS rules should be applied. Is it possible that test user is in a group that gives them edit permissions? If you're confident that they don't have edit permissions, please file a support ticket for us to investigate your scenario as this may be a bug.

**Comment by MI77** [comment]
#please-close
