### ISSUE TITLE
Feature not available anymore!

### ISSUE THREAD

**Issue by mail2vjj** [MicrosoftDocs/powerbi-docs#1468]
This feature is not available in the recent updates of Power BI, hence this page is useless now.
Please let me know if tooltips can still be edited as stated on this page, without having to use Report Page tooltips.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfbc531-11a6-2543-6c99-d38128af21e4
* Version Independent ID: d7dd98cd-d0f9-5738-677d-41fd64804f16
* Content: [Customizing tooltips in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-custom-tooltips#feedback)
* Content Source: [powerbi-docs/desktop-custom-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-custom-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mail2vjj . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello @mail2vjj and thanks for your post. This functionality is indeed still available in Power BI Desktop, and there are other ways to create custom, specialized tooltips that you can create for specific visuals. Both approaches do indeed work. For more information, please see:

https://docs.microsoft.com/power-bi/desktop-tooltips
