### ISSUE TITLE
Link for App Registration points to "classic" view and should point to the new method

### ISSUE THREAD

**Issue by awentzel** [MicrosoftDocs/powerbi-docs#1469]
Existing Link is https://docs.microsoft.com/en-us/power-bi/developer/register-app#using-the-azure-ad-portal although per the Azure Portal should be using the new link for App Registrations in October 19'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edce6995-b777-06fc-49ee-b23eabf6a862
* Version Independent ID: ffd0c74b-4a05-1019-6897-804d60c13765
* Content: [Register an app to embed Power BI content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/register-app)
* Content Source: [powerbi-docs/developer/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/register-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @awentzel,

Thank you for pointing this out.

I fixed the link in the [Using the Azure AD portal](https://docs.microsoft.com/en-us/power-bi/developer/register-app#using-the-azure-ad-portal) section of the [Register an Azure AD application to use with Power BI](https://docs.microsoft.com/en-us/power-bi/developer/register-app#using-the-azure-ad-portal) article.

Now it is pointing to the new Azure app registration method.
