### ISSUE TITLE
Whitepapers

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs#147]
You should add a link to the Power BI whitepapers overview as a 'resource' in the menu on the left:
https://docs.microsoft.com/nl-nl/power-bi/whitepapers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba176b5-d050-3be8-cc69-d8534b7e1982
* Version Independent ID: 8284cd12-eae5-29ea-7c19-3b6ef883355e
* Content: [Governance and deployment approaches - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-governance)
* Content Source: [powerbi-docs/service-admin-governance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-governance.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @DaveRuijter - I like the idea, but that topic is already in the TOC under the main Resources node (same level as Admin). We don't add more than once b/c the behavior is a little weird.
