### ISSUE TITLE
Sharing Reports with pro

### ISSUE THREAD

**Issue by GitHubRojosoft** [MicrosoftDocs/powerbi-docs#1470]
When i tried to share reports to another person who isnt in my domain organization the report doesnt reach the destiny.

**Comment by GitHubRojosoft** [comment]
Im pro user

**Comment by davidiseminger** [comment]
Thanks for your comment, @GitHubRojosoft. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
