### ISSUE TITLE
Doesn't work with PowerBi embedded

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/powerbi-docs#1472]
@Digit-89 commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/14)

This page is referred by [this one](https://docs.microsoft.com/en-us/dynamics365/portals/set-up-power-bi-integration), but URL parameter filters don't work with PowerBi embedded in a Microsoft Dynamics portal (neither PowerPortal).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filtrer un rapport à l’aide de paramètres de chaîne de requête dans l’URL - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@srvbpigh commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/14#issuecomment-537460494)

Hello, @Digit-89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.
Thanks!

**Comment by davidiseminger** [comment]
Assigning to the author, who will take a look and comment on the post.

**Comment by maggiesMSFT** [comment]
Hi, @Digit-89, I'm checking on your question and will get back to you.
Thanks!

**Comment by vincentys99** [comment]
Hi all,
I was trying to figure out how this can be achieved and I found out that if you apply &?filter=........... to the end of the url, it should be working fine. 

So it should looks something like this:
<iframe width="800" height="600" src="https://app.powerbi.com/view?r=[abunchofcharacters]&?filter=[TableName/ColName eq 'Value']" frameborder="0" allowFullScreen="true"></iframe>

**Comment by Digit-89** [comment]
It has been silently fixed. It works without modifying anything.

**Comment by maggiesMSFT** [comment]
OK, thanks for letting me know. I'm glad it working now!
