### ISSUE TITLE
Host and Connect to Power Platform Data Sources

### ISSUE THREAD

**Issue by rywilli** [MicrosoftDocs/powerbi-docs#1474]
I think a major difference between Report Server and the cloud service is the ability to host and connect to Power BI Datasets. Many organizations are looking to use this feature to establish a clean semantic layer and enable self-service reporting. I think it would be useful to call out this limitation of PBI RS on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service#feedback)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your post @rywilli - I've assigned the issue to the author, who will take a look and respond to the post.

**Comment by rywilli** [comment]
Any update on this?

**Comment by maggiesMSFT** [comment]
Great idea! Sorry it took me a while. Adding it today, will be live this afternoon or tomorrow.

**Comment by rywilli** [comment]
Can I suggest that the documentation referenced is this page, which is specific to the current build: https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets

The documentation you referenced is connecting to shared datasets across workspaces , which is a nice feature but is still in preview and build upon the core functionality mentioned in the above mentioned documentation.

Thanks,
Ryan

Ryan Williams
Power Platform Technical Specialist
Power BI | PowerApps | Power Automate
Cell: 443.852.2818
