### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by DaniilMaslyuk** [MicrosoftDocs/powerbi-docs#1476]
The screenshot is incorrect. There are actually three options:
1. Capacity default
2. Off
3. On

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @DaniilMaslyuk -- thanks for pointing that out! I'll get it updated.

**Comment by maggiesMSFT** [comment]
Hi, @DaniilMaslyuk -- it's fixed. Change will be live this afternoon. Thanks again!
@KesemSharabi
