### ISSUE TITLE
workspace list view

### ISSUE THREAD

**Issue by gavinsinclair** [MicrosoftDocs/powerbi-docs#1477]
"To access lineage view, go to the workspace list view."

Where is the workspace list view?  Despite having Admin role on a workspace, and a Pro licence, I cannot find it.  How do I reach it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43c8665-8c3a-3ece-c2cc-593ade6ce37f
* Version Independent ID: 8cffbebb-8e7c-5eae-d9e4-d1789abac390
* Content: [Data lineage (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-data-lineage#feedback)
* Content Source: [powerbi-docs/service-data-lineage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-data-lineage.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @gavinsinclair -- it's the view of a workspace that lists the dashboards, reports, etc. Can you see this image? I can't tell if it's going to show:
![image](https://user-images.githubusercontent.com/12401230/66172701-9b843780-e601-11e9-945d-3ccaa3e48a17.png)
A minute ago, I couldn't see the List view icon either. Try opening Power BI in a new browser. That worked for me.
