### ISSUE TITLE
The code sample refers to an old version of ADAL

### ISSUE THREAD

**Issue by RayGHeld** [MicrosoftDocs/powerbi-docs#1479]
You need to update this document.  It needs to reference the nuget package for ADAL 5.2.2 and then the code needs changed like so:

    class Program
    {
        private static string token = string.Empty;
        static void Main ( string [ ] args )
        {
            token = GetToken ();

            Console.WriteLine ( token );
            Console.ReadKey ();
        }

        private static string GetToken ()
        {
            string clientID = "{client_id}";
            string redirectUir = "https://login.live.com/oauth20_desktop.srf";
            string resourceUri = "https://analysis.windows.net/powerbi/api";
            string authorityUri = "https://login.microsoftonline.com/common/";

            AuthenticationContext authContext = new AuthenticationContext(authorityUri);
            string token = authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUir), new PlatformParameters(PromptBehavior.Always)).Result.AccessToken;
            return token;

        }
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Thanks, @RayGHeld ! Assigning to author to take care of this.

**Comment by rkarlin** [comment]
@KesemSharabi

**Comment by KesemSharabi** [comment]
Hi @RayGHeld,

Thanks for pointing this out.

I'm checking the code with the developers and will update you shortly.

If the code is incorrect, we will update the document accordingly.

**Comment by KesemSharabi** [comment]
Hi @RayGHeld,

I can confirm that this article needs updating. This may take some time but once it's done, I'll update you.

**Comment by KesemSharabi** [comment]
Hi @RayGHeld,

Thank you for suggesting a fix for this article. I added this article to our backlog and we will fix it in the future.
