### ISSUE TITLE
Refine recommendation for DIVIDE use

### ISSUE THREAD

**Issue by OmriAvissar** [MicrosoftDocs/powerbi-docs#1480]
The current recommendation is to use the DIVIDE function whenever the denominator is an expression that could return zero or BLANK.

I suggest to add an exception for a BLANK numerator.
i.e: (BLANK() / 0) == (BLANK() / BLANK()) == BLANK()

A common use case is:
COUNTROWS(Table1) / CALCULATE(COUNTROWS(Table1), ALL(Table1[Column1]))
If the denominator is BLANK, the numerator must be also BLANK- So this is a safe use of "/".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b331cbb-81c4-add1-da29-3783ed6ad9a6
* Version Independent ID: 9f4ca24a-ad9b-2601-7a40-5ffd5eef8254
* Content: [DAX: DIVIDE function vs divide operator (/) - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/dax-divide-function-operator#feedback)
* Content Source: [powerbi-docs/guidance/dax-divide-function-operator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/dax-divide-function-operator.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by mgblythe** [comment]
Thanks for your comment, @OmriAvissar. I've assigned this issue to the doc author for review.

**Comment by peter-myers** [comment]
Thanks for the suggestion, we will consider it for a future revision.

**Comment by peter-myers** [comment]
#please-close
