### ISSUE TITLE
Please add how to pass parameters t Paginated Reports

### ISSUE THREAD

**Issue by amkumar5** [MicrosoftDocs/powerbi-docs#1482]
Power BI Report is primary and i want to navigate to Paginated Reports with parameters based on selection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bbba956-a7bf-d125-6db5-07ce9c445a0a
* Version Independent ID: 5703d3a1-cf11-45c3-056c-09774ebbf3b9
* Content: [Create a paginated report for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-create-paginated-report)
* Content Source: [powerbi-docs/report-server/quickstart-create-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/quickstart-create-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @amkumar5. I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by amkumar5** [comment]
Thanks, Mike

But 80% of the questions in those forums are unanswered. Answers are not marked.
Not much response.
________________________________

**Comment by maggiesMSFT** [comment]
Hi, @amkumar5 -- here's a video that demonstrates how to do what you're asking for. Hope that helps!
https://www.youtube.com/watch?v=KYfhclGrI48&t=1s
