### ISSUE TITLE
. Python script error in Power Query Editor

### ISSUE THREAD

**Issue by linxurong** [MicrosoftDocs/powerbi-docs#1483]
When I use python script for power query editor, most of time I faced error as below. 
How can I solve this issue. 

DataSource.Error: ADO.NET: A problem occurred while processing your Python script.
Here are the technical details: Process must exit before requested information can be determined.
Details:
DataSourceKind=Python
DataSourcePath=Python
Message=A problem occurred while processing your Python script.
Here are the technical details: Process must exit before requested information can be determined.
ErrorCode=-2147467259
ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonUnexpectedException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd46971-2ea5-9271-3b2a-824efc1821e1
* Version Independent ID: 68669cdb-5e4d-bb96-d2d5-bdad4088fb03
* Content: [Using Python in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-in-query-editor)
* Content Source: [powerbi-docs/desktop-python-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by davidiseminger** [comment]
Thanks for your comment, @linxurong . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by tarunbadial** [comment]
When I use python script for power query editor, most of time I faced error as below.
How can I solve this issue.
![image](https://user-images.githubusercontent.com/43639402/73068342-fd2e2180-3ed0-11ea-8133-cea813b49adf.png)
 **Run code:**
![image](https://user-images.githubusercontent.com/43639402/73068262-d7088180-3ed0-11ea-875c-08a71172a9e6.png)
