### ISSUE TITLE
Power BI Desktop of microsoft store mandatory

### ISSUE THREAD

**Issue by PoussinBleu** [MicrosoftDocs/powerbi-docs#1484]
Hello,
I have the problem to connect to my oracle database. Unfortunately, all the links to Power BI Desktop redirect to the microsoft store version (even this one :  https://powerbi.microsoft.com/desktop). I do the installation of the oracle client you put at the beginning of the page but nothing changes. Is there another way to have the "non microsoft store" version ?
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry for the confusion, @PoussinBleu. You can get the .exe version (the non-Microsoft Store version) at the following link:

https://www.microsoft.com/download/details.aspx?id=58494 

You can use the "See download or language options" on the Download page to get to those options.

**Comment by PoussinBleu** [comment]
Thank you !
