### ISSUE TITLE
MarkLogic is missing from the supported ODBC drivers above.

### ISSUE THREAD

**Issue by aroach337** [MicrosoftDocs/powerbi-docs#1485]
MarkLogic DirectQuery is available through ODBC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df452d2e-9a96-a9cb-40a7-830d6282c68b
* Version Independent ID: 1f84e9ab-409e-59fc-d35a-dc66f3d6bcb3
* Content: [Connect to data using generic interfaces in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-using-generic-interfaces)
* Content Source: [powerbi-docs/desktop-connect-using-generic-interfaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-using-generic-interfaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for letting everyone know, @aroach337 !
