### ISSUE TITLE
Unable to roll up a partition

### ISSUE THREAD

**Issue by ndesousa** [MicrosoftDocs/powerbi-docs#1486]
I have a quarter partition that is unable to be "closed off" as I keep getting an error message: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647. The partition size is 2.2GB

As a result, I get several snapshots of data of the same size at each refresh, which results in a failure, even though a snapshot is being written to my Azure Data Lake Gen 2 account. Is there a way to overcome this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60093b2-2bdf-92e9-ee7c-de316b601beb
* Version Independent ID: 25307bcb-648e-e620-3fe9-a1412e89c0b5
* Content: [Using incremental refresh with Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-dataflows-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @ndesousa . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
