### ISSUE TITLE
Unsubscribing from notifications

### ISSUE THREAD

**Issue by TravisSpomer** [MicrosoftDocs/powerbi-docs#1488]
I get a LOT of emails directing me to this page for Power BI documents I've never seen before (I've never used Power BI).  It'd certainly be nice if this page explained how to stop getting notifications.  (Obviously it'd be nicer if I could "unsubscribe" myself from a direct link in the email, but...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179482da-6009-3602-8e51-c20a42c83b5b
* Version Independent ID: b023c9e5-94e0-4d0c-67ce-465916170c43
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-troubleshooting-refresh-scenarios#feedback)
* Content Source: [powerbi-docs/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @mgblythe . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @TravisSpomer . This issue has been assigned to the doc author for review.

**Comment by chrisant996** [comment]
I get notifications for things I've never heard of, and they send me here.  But it seems that a deeper problem is msit.powerbi.com/sharedwithme says 2,235 items have been shared with me -- there are tons of things I've never heard of, don't care about, and have nothing to do with my job.    Clearly things are organized poorly.

**Comment by TravisSpomer** [comment]
![image](https://user-images.githubusercontent.com/16262858/67881115-1fe0b200-fafd-11e9-9a1e-f9ce41985be1.png)

Here's one of six I got all at the same time, all relating to things I don't know anything about.

**Comment by mgblythe** [comment]
Does your organization use Power BI? My guess is you're on an email list that is specified in Power BI to receive these types of notifications.

**Comment by TravisSpomer** [comment]
Sure.  But I have no way of finding out why I'm getting the emails, or how to make them stop, and the large "Learn more" link points to a page that doesn't include the most important bit of information: how to unsubscribe from the emails.

**Comment by mgblythe** [comment]
Your admin would need to remove your email or list you're subscrbied to from the following dialog ![refresh-email](https://user-images.githubusercontent.com/12448473/67891011-00eb1b80-fb0f-11e9-9e3d-cd6f3a0d3ac6.png)

**Comment by mgblythe** [comment]
Thanks @TravisSpomer, I'm adding a section to the doc today to address this issue.
