### ISSUE TITLE
Support for Custom Connectors?

### ISSUE THREAD

**Issue by ramenjosh** [MicrosoftDocs/powerbi-docs#1489]
Is it possible to use a custom Data Connector (https://github.com/microsoft/DataConnectors) with Power BI Report Server? There is support in the Power BI service via an on-premises data gateway but I can't see anything for the report server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37efb1d4-b4bb-f035-c63b-1f8b17d4f448
* Version Independent ID: fe9f8822-a20a-e17c-195c-1dc261ab480f
* Content: [Power BI report data sources in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/data-sources)
* Content Source: [powerbi-docs/report-server/data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
@ramenjosh Thank you for the comment. This issue has been passed on to the original author.

**Comment by maggiesMSFT** [comment]
Hi, @ramenjosh -- Thanks for asking. No, it's not possible to use a customer data connector with Power BI Report Server, and it's not planned.
