### ISSUE TITLE
Composite Model Implementation?

### ISSUE THREAD

**Issue by karissashapard** [MicrosoftDocs/powerbi-docs#149]
When will the feature be able to be pushed up to the Power BI Service? I created a whole report based on this feature (its a good improvement) and want to know if that is something that will become usable in the near future

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use Composite Models in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @karissashapard - this feature is currently in preview, and there isn't a defined time when (or whether) it will be made generally available, or when updates will occur.
