### ISSUE TITLE
Allow color formatting for SSAS Tabular Live Connections as well

### ISSUE THREAD

**Issue by cts14** [MicrosoftDocs/powerbi-docs#1490]
e.g.  General;[Red]-General as custom number format doesn't bring the same result as in excel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#feedback)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
@cts14 Thank you for your comment. Is your feedback concerning the difference in behavior from Power BI to Excel?

**Comment by cts14** [comment]
Hi Robert, 

My desired result is to have profit numbers in PowerBI Tabular SSAS LIVE connection to be in red colour when negative. I do know that this is achievable with conditional formatting but I would like it to be across the model not just within a pbix/pbit. 

In regards to https://docs.microsoft.com/en-us/power-bi/desktop-custom-format-strings it could be the solution to my problem but it doesn't seem to work with colors.

In excel you have both options, custom format strings and conditional formatting.

**Comment by srigney2142** [comment]
Thanks for your comment, @cts14  This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
