### ISSUE TITLE
DirectQuery in PBI Service

### ISSUE THREAD

**Issue by AnaSeremet** [MicrosoftDocs/powerbi-docs#1491]
It says that 2 sources are available directly in the service: Spark and Azure SQL DWH. Is this information really accurate?  Isn't that possibility deprecated? Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#feedback)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
@AnaSeremet Thank you for the comment. This issue has been passed on to the original author.

**Comment by davidiseminger** [comment]
That is currently correct.
