### ISSUE TITLE
Dataflows permissions not explained.

### ISSUE THREAD

**Issue by savoy9** [MicrosoftDocs/powerbi-docs#1493]
The document, and especially this table (https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#roles-in-the-new-workspaces) doesn't detail which roles can read data stored in workspace dataflows into power bi desktop. This also doesn't seem to be detailed in the Dataflows documentation either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#roles-in-the-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @savoy9  I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Great question, @savoy9 ! I'll go find out. Adding @LukaszPawlowski-MS

**Comment by savoy9** [comment]
@maggiesMSFT, did this ever get resolved? I'd love to know if I can use a viewer or contributor role for my dataflows consumers.

**Comment by maggiesMSFT** [comment]
Hi, @savoy9 -- yes, I've gotten confirmation for users in any role can read data stored in workspace dataflows. I'll add that to the table in the article. Thanks for asking and thanks for your patience!

**Comment by savoy9** [comment]
Thanks @maggiesMSFT

**Comment by maggiesMSFT** [comment]
The change will be live later this afternoon (Pacific time)
