### ISSUE TITLE
Is highlight supported in Table data mapping?

### ISSUE THREAD

**Issue by kuehcj** [MicrosoftDocs/powerbi-docs#1496]
The example above used categorical data mapping, but can we use this highlight feature in table data mapping? There is no highlights array when table mapping is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80303b53-8f3f-e9d3-f00c-1316b44432ee
* Version Independent ID: 774a462b-8188-ebaf-ee87-863c4c0947c4
* Content: [Highlighting - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/highlight#feedback)
* Content Source: [powerbi-docs/developer/visuals/highlight.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/highlight.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by srigney2142** [comment]
Thanks for your comment, @kuehcj  I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by KesemSharabi** [comment]
Hi @kuehcj,

Thanks for your question. As far as I understand, table data mapping doesn't support highlights.

I am double checking and will add a note in the article after I get confirmation.

**Comment by KesemSharabi** [comment]
Hi @kuehcj,

Thanks for your question. Unfortunately, data view mapping doesn't support the highlights feature. 

We've added a note to address this in the [Highlight data points in Power BI Visuals](https://docs.microsoft.com/en-us/power-bi/developer/visuals/highlight) article.
