### ISSUE TITLE
url parameter for switching report pages

### ISSUE THREAD

**Issue by bjhulst** [MicrosoftDocs/powerbi-docs#1498]
Hi,

It is not clear to me how to switch to the other page in the report using a parameter in the report url?
Is it possible and documented somewhere?

**Comment by srigney2142** [comment]
Thank you for your question @bjhulst I took a look at the document you were referring to and I believe I found your answer: 

Note in this example URL the bolded section is where the report page value is located:

app.powerbi.com/groups/me/apps/app-id/reports/report-id/**ReportSection**?filter=Table/Field eq 'value&'ctid=ctid

And in the Retail Analysis sample of this document, the overview page would be:

https://app.powerbi.com/groups/me/reports/8d6e300b-696f-498e-b611-41ae03366851/**ReportSection3**?filter=Store/TerritoryChain eq 'NC – Lindseys'

By changing this value you change which page you are viewing, so Report, Report1, Report2, Report3, Report4, etc. 

I hope this answered your question.

**Comment by bjhulst** [comment]
That parameter does not seem to have any effect.

**Comment by srigney2142** [comment]
@bjhulst I'm sorry my information did not answer your question. Can you provide more information? It's my understanding that you wanted to know what controlled switching between report pages, such as **Overview** to **New Stores** was this incorrect?

**Comment by bjhulst** [comment]
I have a powerbi report with 4 pages using the same dataset. (navigation tabs).
called: tab1     tab2   tab3    tab3.

how to write the url so the webpage of the powerbi report opens on tab2?  or tab3?

And with the query filter parameter?

(message sent via mobile)

**Comment by bjhulst** [comment]
and on purpose I put single word names for the tabs to avoid url misinterpretation of spaces and other special characters....

**Comment by srigney2142** [comment]
@bjhulst The value in the url will not necissarily reflect the name you gave to the pages. Might I suggest manually changing between pages and finding the value that changes, that will be the value that determines the visible page.

**Comment by bjhulst** [comment]
Manually changing the tabs does not change the url. The javascript code is doing XHR queries to the backend from inside the current page assigned by the navigation carousel widget. I checked that already... 😎

**Comment by srigney2142** [comment]
@bjhulst You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). 
I will also assign the doc author to review the documentation.

**Comment by bjhulst** [comment]
The community pages do not have info on this topic in detail. Most refer to this document in github... Looks like product support it is.
Thank you for checking this request.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
