### ISSUE TITLE
Nice feature, needs to be more open

### ISSUE THREAD

**Issue by tdexterus** [MicrosoftDocs/powerbi-docs#150]
We are looking for a way for our users to have a one stop shop for things like time, geog, sales, hr and product hierarchies. It would be great to set these up on a central data model and allow folks to hit it and join their own data to the standard data sets. This doesnt quite fit the bill :(
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thank you for your feedback @tdexterus.
