### ISSUE TITLE
TimeZone display on the Subscription Email

### ISSUE THREAD

**Issue by vanessayuyo** [MicrosoftDocs/powerbi-docs#1500]
The Subscription Email content shows "You’re receiving this email because you subscribed to the '[Page Name]' page of the '[Report Name]' report. The image above was generated at MONTH DAY, YYYY dd:mm UTC."

Is it possible to configure / change the time zone displayed from UTC to other time zone?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe yourself and others to reports and dashboards - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-report-subscribe#feedback)
* Content Source: [powerbi-docs/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @vanessayuyo I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Good question, @vanessayuyo ! Adding @cmfinlan for his sage reply.

**Comment by cmfinlan** [comment]
It isn't currently, no

**Comment by maggiesMSFT** [comment]
Thanks, @cmfinlan .
@vanessayuyo , if you'd like to see this functionality added to the product, go to https://ideas.powerbi.com/forums/265200-power-bi and add it.
