### ISSUE TITLE
Custom sortin

### ISSUE THREAD

**Issue by saifulhq** [MicrosoftDocs/powerbi-docs#1501]
how developer to managed the sorting? i need to sorting data by code, please give me some article or sample git please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67359639-c02c-0575-28a5-81d63d3aef02
* Version Independent ID: 9994b227-4db7-7f36-6f6f-8160e454d34b
* Content: [Sorting options for Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/sort-options#feedback)
* Content Source: [powerbi-docs/developer/visuals/sort-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/sort-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by srigney2142** [comment]
Thanks for your comment, @saifulhq  This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
