### ISSUE TITLE
Use geo-hierarchies so you can drill down to different "levels" of location Not correct?

### ISSUE THREAD

**Issue by bgnichwitz** [MicrosoftDocs/powerbi-docs#1502]
It does not work for me to just put multiple columns in location on filled map and it does creat a hierachie. I need to create a hierachie and drag this to location. This seems to be more inutite anyways but this page is not up to date i guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by srigney2142** [comment]
@bgnichwitz Thank you for the comment. This issue has been passed on to the original author.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
