### ISSUE TITLE
does "1G for a dataset" apply to a report or a visual on a report?

### ISSUE THREAD

**Issue by selina00** [MicrosoftDocs/powerbi-docs#1503]
Hello, 
Could you specify if "1G for a dataset" applies to a report or a visual on a report?
Because I encountered a scenario that a visual(table) can't display due to "visual has exceeded the available resource" however the other visuals can display. 
Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data#considerations-and-limitations)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
Thanks for your comment, @selina00 I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
It applies to the dataset, not each visual. You might find a solution to the visual issue in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
