### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by branchfork** [MicrosoftDocs/powerbi-docs#1504]
The article says "When you build reports in Power BI Desktop that use custom data connectors, you can use the on-premises data gateway to refresh those reports from the Power BI service.". Can you please confirm whether it's possible to refresh a report that uses a custom data connector without using the data gateway where the custom data source is cloud-based?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137ea074-f635-5cd9-6e94-f6bc12ac2452
* Version Independent ID: 4ce609b2-adfa-8575-4e4a-9cc285028043
* Content: [Use custom data connectors with the on-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-custom-connectors)
* Content Source: [powerbi-docs/service-gateway-custom-connectors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-custom-connectors.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srigney2142** [comment]
Thanks for your comment, @mattonmicrosoft  I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by kfollis** [comment]
@branchfork - Thank you for submitting feedback on our documentation. Please see https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data#data-refresh for more information about refresh in Power BI. I believe this answers your question. The gateway is used to bridge cloud and on-premises, so if your data source is cloud-based, no gateway should be required. We are closing this issue, but if your question isn't addressed in this link, please feel free to submit feedback for that page.
