### ISSUE TITLE
Power BI service displays fewer datasets than Power BI Desktop

### ISSUE THREAD

**Issue by rudy365** [MicrosoftDocs/powerbi-docs#1505]
I followed the steps in this article and everything works for me, except that when I click Get data &gt; Published datasets in Power BI service, I am seeing fewer datasets than through Power BI Desktop. I validated this in two tenants with two different accounts and with a coworker. Could this be a small defect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0097b22-50b6-445a-10e9-a8e2a26dabbe
* Version Independent ID: daf670da-4171-29b2-7171-4e46637c099d
* Content: [Create reports based on datasets from different workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-discover-across-workspaces#feedback)
* Content Source: [powerbi-docs/service-datasets-discover-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-discover-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @rudy365 This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
