### ISSUE TITLE
Division: Integer / Currency --> Currency

### ISSUE THREAD

**Issue by cervanta** [MicrosoftDocs/powerbi-docs#1506]
Is this correct?:
For example, if an integer is combined with a currency value in a division operation, both values are converted to _**real numbers**_, and the result is also a **_real number_**.
The chart suggests a Currency

**Comment by srigney2142** [comment]
Thanks for your comment, @cervanta This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
