### ISSUE TITLE
Minor typo that could change some logic of the explanation

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerbi-docs#1507]
Hello,

Regarding the 5th scenario: "Nate makes updates to the dashboard and when it's ready, will publish a new version of the content pack." - I think there is a typo in "Julio's" options:

> Julio, another distribution group member, didn't customize the original content pack. The new changes are automatically applied to **Jane's** version of the content pack.

I think it should be:

> Julio, another distribution group member, didn't customize the original content pack. The new changes are automatically applied to **Julio's** version of the content pack.

Kind Regards,
Lucian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d547a10-cdbd-0df0-5173-14531ff0e0a4
* Version Independent ID: 54a111fa-c230-6964-f975-fe8a9b9d7566
* Content: [Intro to organizational content packs in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-organizational-content-pack-introduction#feedback)
* Content Source: [powerbi-docs/service-organizational-content-pack-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-organizational-content-pack-introduction.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @luconsta I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Good point, @luconsta ! Will fix shortly.
