### ISSUE TITLE
Update docs: Synonyms moved to Properties pane

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerbi-docs#1512]
Hello,

The docs refering to synonyms should be updated: https://docs.microsoft.com/en-us/power-bi/desktop-qna-in-reports#add-synonyms-to-tables-and-columns: they are no longer available through Relations view\Modeling tab\Language\Synonyms - they are in Modeling view\Properties pane.

I had to google a lot until I found it. :)

Kind regards,
Lucian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d342e58-4617-9c79-706f-dcff2f6320d5
* Version Independent ID: 07d1834d-4eca-712c-570b-0ed4586fa95e
* Content: [Using Q&A in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-qna-in-reports)
* Content Source: [powerbi-docs/desktop-qna-in-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-qna-in-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @luconsta, and sorry for the time you had to spend searching. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @luconsta -- 
Oh, so true. Q&A recently underwent a major upgrade, with new docs to go with it, starting with this one: https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-intro
I'll be removing or updating the previous docs soon. Thanks!
