### ISSUE TITLE
RE: Confirming Workspace features that work differently

### ISSUE THREAD

**Issue by adamsorensen93** [MicrosoftDocs/powerbi-docs#1517]
Hi there,

I was reading through this document, and I noticed the following dot-point regarding workspace access:

"Users without a Pro license can access the workspace if the workspace is in a Power BI Premium capacity, even if users have only the Viewer role."

However, I've also found that the documentation for Premium capacity seems to indicate that non-Pro users can only access content if it is published in an App. I could see this information at the following location: https://docs.microsoft.com/en-us/power-bi/service-premium-what-is
Located in the image under "Unlimited content sharing". 

Are you able to clarify if non-licensed users can access Workspace reports and Apps if they are not in Premium capacity?

Many thanks,
Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @adamsorensen93 I've assigned this issue to the doc author for review.

**Comment by adamsorensen93** [comment]
Thank you for responding. To correct my last statement, I am wondering if non-licensed users can access content in a Premium Workspace, or can they only access the App that the workspace is tied to? Many thanks

**Comment by maggiesMSFT** [comment]
Hi, @adamsorensen93 -- I see what you mean about https://docs.microsoft.com/en-us/power-bi/service-premium-what-is. It doesn't say they can, but it doesn't say they can't. It's just silent. 
The answer to your question: Yes, non-licensed (with a free license, not a Pro license) users can access content in a Premium-capacity workspace, if they have a Viewer role. They can view and interact with the content in the workspace, but not make changes. 
I'll ping the author of the https://docs.microsoft.com/en-us/power-bi/service-premium-what-is article, see if we should update it.

**Comment by maggiesMSFT** [comment]
Hi, @davidiseminger -- In https://docs.microsoft.com/en-us/power-bi/service-premium-what-is, consider clarifying that "Users without a Pro license can access the workspace if the workspace is in a Power BI Premium capacity, even if users have only the Viewer role"? 
thx!

**Comment by davidiseminger** [comment]
Added that to the article - thanks!
