### ISSUE TITLE
Is it possible to point to a Dataflow using the new PBIDS file type?

### ISSUE THREAD

**Issue by edfreeman** [MicrosoftDocs/powerbi-docs#1518]
It's unclear from this page whether Dataflows are supported as a connection for a PBIDS file. I've tried numerous things to try to get it to work, to no avail. There's no mention of connecting to a dataflow in the "Data Source Reference (DSR) format for protocol and address information" link provided, either.

I'm wondering whether Dataflows are classed as a "Blank query" and therefore they aren't supported in PBIDS yet. Could anyone confirm this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
Thanks for your comment, @edfreeman I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by edfreeman** [comment]
Thanks @srigney2142. Couldn't find anything preexisting on the Power BI Community, so I've Just posted the question there as well (https://community.powerbi.com/t5/Desktop/Does-the-PBIDS-file-type-support-a-Dataflow-connection/m-p/820905#M394432).

**Comment by pawhe** [comment]
Yes it is possible. The protocol is "powerbi-dataflows".
Below is a sample.
Workspace id and dataflow id can be found by clicking on the dataflow in the Power BI web app and looking at the url.
https://app.powerbi.com/groups/<workspace id>/dataflows/<dataflow id>
{
  "version": "0.1",
  "connections": [
    {
      "details": {
        "protocol":"powerbi-dataflows",
        "address":{
          "workspace":"<workspace id>",
          "dataflow":"<optional dataflow id>"
        }
      }
    }
  ]
}
