### ISSUE TITLE
Link broken for download of Sept-2019 PBID files

### ISSUE THREAD

**Issue by zenzeinet** [MicrosoftDocs/powerbi-docs#1519]
Hi, the links for the downloads of Sept-2019 PowerBI Destkop installation files are broken (404). August are there.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update-archive#feedback)
* Content Source: [powerbi-docs/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
Thanks for your comment, @zenzeinet I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Fixed - and note that downloads for previous versions of Power BI Desktop are only available for the previous six months from the most recent release.
