### ISSUE TITLE
Wrong Account

### ISSUE THREAD

**Issue by designertechno** [MicrosoftDocs/powerbi-docs#152]
The guide says: "Step 6 Sign up for Power BI with your user account that you created in step 5." However the user created in Step 5 was only a "User" not a Global Admin. So when you log into Azure in the next module for Embed Power Bi you will have the wrong user type. It should be made clear that Power BI Pro account need to be created with  Global Admin Account, and it is with this account that you should register your app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c718914f-db23-aff5-186c-0f2cd192ebbe
* Version Independent ID: 76fc3bb6-d6b9-70e1-e1bc-c8ace0f79fac
* Content: [Create an Azure Active Directory tenant to use with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/create-an-azure-active-directory-tenant)
* Content Source: [powerbi-docs/developer/create-an-azure-active-directory-tenant.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/create-an-azure-active-directory-tenant.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@designertechno Thank you for your feedback.  Can I ask for some clarification?

It states in Step 4 that the user needs to be a Global Admin.

+++
Provide a name and username for this user. This will be your Global Admin for the tenant. You will also want to change the Directory role to Global administrator. You can also show the temporary password. When you are done, select Create. 
+++

Are you requesting that the user step 6 is referring to is from step 4 and not from step 5?
