### ISSUE TITLE
Paginated Reports

### ISSUE THREAD

**Issue by stephenjenks** [MicrosoftDocs/powerbi-docs#1521]
Hi, I am interested in knowing if Paginated Reports are supported or not in PBI Gov Cloud.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for United States Government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/service-govus-overview#feedback)
* Content Source: [powerbi-docs/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by stephenjenks** [comment]
Thank you. If I could go one step further, it would be incredibly helpful to have a functionality comparison matrix (or similar) between commercial premium service and the government premium service. Currently, it is very hard to tell when commercial features have been added to the government service. Please let me know if this is already available!

**Comment by maggiesMSFT** [comment]
Thanks, @stephenjenks! Adding @cmfinlan to comment on paginated reports in the government cloud.

**Comment by cmfinlan** [comment]
It is now available in USGOV Virginia - we are hoping to have it soon in Texas as well.

**Comment by maggiesMSFT** [comment]
Updating the article to reflect this info.
