### ISSUE TITLE
How does one upload a custom assembly?

### ISSUE THREAD

**Issue by samsonfr** [MicrosoftDocs/powerbi-docs#1524]
With good old Reporting Services, we simply deployed our custom assemblies to ReportServer bin directory. This page mention the possibility of adding a reference to a custom assembly. If I do and save the report to workspace with a Power BI premium dedicated capacity, I get the error "Error while loading code module". How are we supposed to upload our custom assembly? Otherwise, please remove any reference to that possibility from documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c360a7-58cd-a6a0-4bb8-38825ca73e68
* Version Independent ID: 0a648a26-0120-7dbb-0093-d2051d5732da
* Content: [Expression examples in Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-expression-examples#feedback)
* Content Source: [powerbi-docs/report-builder-expression-examples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-expression-examples.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @samsonfr I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Ah, @samsonfr -- good catch! You can’t have a reference to a custom assembly, but you should be able to take the code and embed it into the report. 
I'll update the article. Thanks for pointing that out!
