### ISSUE TITLE
User!Language is always en-US

### ISSUE THREAD

**Issue by samsonfr** [MicrosoftDocs/powerbi-docs#1525]
Even if I change my browser preferred language or Power BI service UI interface. Is it a bug or it's just not implemented yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c360a7-58cd-a6a0-4bb8-38825ca73e68
* Version Independent ID: 0a648a26-0120-7dbb-0093-d2051d5732da
* Content: [Expression examples in Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-expression-examples#Properties)
* Content Source: [powerbi-docs/report-builder-expression-examples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-expression-examples.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srigney2142** [comment]
Thanks for your comment, @samsonfr I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @samsonfr -- adding @cmfinlan for comment.
thanks!

**Comment by cmfinlan** [comment]
It's not yet implemented.

**Comment by maggiesMSFT** [comment]
Thanks for the info, @cmfinlan . Closing this issue.
