### ISSUE TITLE
"Color formatting by field value" doesn't work unless Measure type is converted to Text from Modeling menu

### ISSUE THREAD

**Issue by erichste** [MicrosoftDocs/powerbi-docs#1526]
Measures that aren't **Text** type are grayed out when trying to select as a color source.

The documentation misses the step where you need to go to the Modeling menu and select the measure's type as Text so, that this can work.

So,
**Step 1:** You create the measure that returns a color or color code.
**Step 2:** You select the measure from fields list and go to Modelling ribbon and select the measure type to be "Text"
**Step 3:** You add the measure to your table
**Step 4:** You select the measure in "Color formatting by field value" for another filed.
**Step 5:** You remove the measure from your table because you don't want to see those color codes in your table unless that is the column you need.

**Comment by srigney2142** [comment]
Thanks for your comment, @erichste I've assigned this issue to the doc author for review. In the meantime, can you provide a little more detail on the issue you raised?

**Comment by mgblythe** [comment]
Closing this one out. @erichste - feel free to reopen if you can provide info on what doc you think needs updating for this issue. Thanks!
