### ISSUE TITLE
Project online odata, how to get Task custom fields

### ISSUE THREAD

**Issue by kmanmeet** [MicrosoftDocs/powerbi-docs#1527]
We are trying to connect to Project Online for PowerBI reports. I am able to connect to the following URL to get Tasks, but doesn't show custom fields such as Flag1, Flag2...Flag3
https://<tenantname>.sharepoint.com/sites/pwa/_api/Projectdata//Projects(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/Tasks

How can we get the custom fields we use in the project

**Comment by srigney2142** [comment]
Thanks for your comment, @kmanmeet This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @kmanmeet -- adding @teddybercovitz to see if he can advise. If not, then yes, you might find a solution in the Power BI Community. If not, try our support page.

**Comment by teddybercovitz** [comment]
+ @Jackie Duong<mailto:jaduong@microsoft.com> - Can you help?

the question is: "

We are trying to connect to Project Online for PowerBI reports. I am able to connect to the following URL to get Tasks, but doesn't show custom fields such as Flag1, Flag2...Flag3
https://.sharepoint.com/sites/pwa/_api/Projectdata//Projects(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/Tasks

How can we get the custom fields we use in the project"



________________________________

**Comment by teddybercovitz** [comment]
The user would need to modify the PBI data tables to import that as well, to extend the dataset to get those custom fields.

________________________________

**Comment by maggiesMSFT** [comment]
Also from @teddybercovitz: "User will need the pbit file for this which he can get from: https://github.com/OfficeDev/Project-Power-BI-Templates"
Hi, @kmanmeet -- hope that helps!
