### ISSUE TITLE
What is required if I wanted to connect different MSSQL onpremise servers and build a powerbi report

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#153]
Can I use the data gateway for MSSQL Servers that are located in different regions and build a powerbi report by using all the data sources all together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks Anmo;gan81 -- will reply back on this the week of 8/20.

**Comment by Anmolgan81** [comment]
Hi,

Any updates???

**Comment by arthiriyer** [comment]
@Anmolgan81  - This should be possible but you will need to use a single gateway since the same Power BI report uses all these data sources
FYI @mgblythe

**Comment by mgblythe** [comment]
@Anmolgan81 - closing this out, but please reopen if necessary. Thanks!
