### ISSUE TITLE
Conditional formatting in PowerBI Service is responding slow

### ISSUE THREAD

**Issue by jboots2** [MicrosoftDocs/powerbi-docs#1534]
We are experience a new issue in Power BI as a Service where our conditionally formatted title for a text box is responding one slicer click late. For example, we have a report where a user selects a new school name from a slicer and the text box title is supposed to respond by showing that school name. When user logs into service and selects "School A" from the slicer, all of the visualizations change but the dynamic title for the text box does not change at all. All of the other chart dynamic titles do change to show School A. When user selects "School B" from the slicer, all of the chart dynamic titles now show School B, except the text box dynamic slicer shows School A.

**Comment by srigney2142** [comment]
Thanks for your comment, @jboots2 This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
