### ISSUE TITLE
SPN is supported with the PowerShell DataGateway Module

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#1538]
please refrence this doc: 
https://docs.microsoft.com/en-us/powershell/module/datagateway.profile/Connect-DataGatewayServiceAccount?view=datagateway-ps

It appears SPN is supported with the DataGateway Module 
Can install and manage an On-premises data gateway	Yes	No

Can we update the chart to reflect? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by srigney2142** [comment]
Thanks for your comment, @adamwp1993 I've assigned this issue to the doc author for review.

**Comment by jayendranarumugam** [comment]
Hi @adamwp1993 

I tried like below but getting the error. Could you please explain how you get connected using the SPN ?

```
$applicationId = "xxx-xxxx" 
$clientsec = "xxxxxxxs" | ConvertTo-SecureString -AsPlainText -Force 

$credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $applicationId, $clientsec 
Connect-DataGatewayServiceAccount -ServicePrincipal -Credential $credential -TenantId "xxx-xxx" 
```

Error is

> Message        : The method or operation is not implemented.
> StackTrace     :    at Microsoft.DataMovement.Powershell.Commands.Common.AuthenticationFactorySelector.Microsoft.DataMo
>                  vement.Powershell.Abstractions.Interfaces.IAuthenticationServicePrincipalFactory.Authenticate(String
>                  userName, SecureString password, IPowerBISettings settings)
>                     at Microsoft.DataMovement.Powershell.Commands.DataGateway.Profile.ConnectDataGatewayServiceAccount.
>                  ExecuteCmdlet()
>                     at Microsoft.DataMovement.Powershell.Commands.Common.PowerBICmdlet.ProcessRecord()
>                     at System.Management.Automation.CommandProcessor.ProcessRecord()
> Exception      : System.NotImplementedException
> InvocationInfo : {Connect-DataGatewayServiceAccount}
> Line           : Connect-DataGatewayServiceAccount -ServicePrincipal -Credential $credential -TenantId
>                  "5b973f99-77df-4beb-b27d-aa0c70b8482c"
> Position       : At line:1 char:1
>                  + Connect-DataGatewayServiceAccount -ServicePrincipal -Credential $cred ...

**Comment by KesemSharabi** [comment]
Hi @adamwp1993,

From a Power BI prespective, you cannot use Power BI APIs to manage DataGateway with Service Principal. 

You may be able to find an answer in the [DataGateway ](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem) documentation, or with the DataGateway team.

**Comment by jayendranarumugam** [comment]
@KesemSharabi 
can you please check the latest announcement about automation of data gateway ?https://powerbi.microsoft.com/en-us/blog/announcing-automation-of-data-gateway-installationpublic-preview/

![image](https://user-images.githubusercontent.com/25414541/81938730-f3146800-9612-11ea-90d0-0acce287a1dc.png)


So SPN Authentication is possible for Gateway ?

**Comment by jayendranarumugam** [comment]
For others, Please see my [blog here](https://community.powerbi.com/t5/Community-Blog/Data-Gateway-Automation-using-PowerShell-Part-1/ba-p/1117330) on how to implement that
