### ISSUE TITLE
Personal pro license

### ISSUE THREAD

**Issue by jenseggerath** [MicrosoftDocs/powerbi-docs#154]
If I already have a personal Power BI Pro license with another account - like a private one - , will I be able to use/import that license in an existing Office 365 environment?

Regards, 
  Jens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5f9906-58f7-9b21-85ee-8d33ffcbdce0
* Version Independent ID: 712e418a-5290-fe94-e9b0-6fa84ec1c7cb
* Content: [Quickstart: Purchase Power BI Pro licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-purchasing-power-bi-pro#purchase-subscription-in-office-365)
* Content Source: [powerbi-docs/service-admin-purchasing-power-bi-pro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-purchasing-power-bi-pro.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Hi @jenseggerath -- have you tried asking this question in the forums: https://community.powerbi.com/t5/Service/bd-p/power-bi-web-app?

**Comment by KayUnkroth** [comment]
No, unfortunately not. Licenses, i.e. subscriptions, are provisioned on a tenant by tenant basis. If you have a separate tenant, you are effectively working with another account, which would necessitate the purchase of a separate license. You can't share a license or subscription between tenants.

**Comment by jenseggerath** [comment]
@KayUnkroth Thank you! I had meanwhile forgotten about this thread, but the problem has been solved as well. 
Thanks - closing this.
