### ISSUE TITLE
There is any support about this

### ISSUE THREAD

**Issue by ediazrod** [MicrosoftDocs/powerbi-docs#1540]
Some times don't work some times yes, there any way to get support or this is a best effort service?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by srigney2142** [comment]
Thanks for your comment, @ediazrod This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @ediazrod -- I suggest starting a support ticket at https://powerbi.microsoft.com/en-us/support/. 
Hope that helps!
