### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by bdmccarty22** [MicrosoftDocs/powerbi-docs#1542]
Is this product still available? I am no longer able to access it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2ce012-0b66-7a2d-2ce0-630f35abdf88
* Version Independent ID: 7d647855-d659-d495-e876-9189a5ba5125
* Content: [Connect to ServiceNow with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-servicenow)
* Content Source: [powerbi-docs/service-connect-to-servicenow.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-servicenow.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **sarinas**

**Comment by srigney2142** [comment]
Thanks for your comment, @bdmccarty22 I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @bdmccarty22 -- you're right. The ServiceNow app is no longer available. I recommend going to https://ideas.powerbi.com/forums/265200-power-bi to express your interest in it. 
thanks!
