### ISSUE TITLE
Deprecation of Azure Consumption Insights connector

### ISSUE THREAD

**Issue by sahan91** [MicrosoftDocs/powerbi-docs#1544]
Hi Team,

We have a client whose Enrollment No and Key will be used to import consumption data into Power BI. At the moment we are using the Azure Consumption Insights connector without any issue. But the new Azure Cost Management connector doesn't work as it requires OAuth 2.0 login to verify the credentials. We, unfortunately, do not have access to an Enterprise Admin account of our client.

My question is, whether the Azure Consumption Insights connector going to be deprecated any time soon? So that it would be fine to use that connector instead of the new one?

Thank you

**Comment by maggiesMSFT** [comment]
Hi, @sahan91 -- Assigning to the author of the Azure Consumption Insights connector article, https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights, but it's really more of a product question. Those are best asked in the feedback forum, https://ideas.powerbi.com/forums/265200-power-bi. 
Hope that helps!

**Comment by sahan91** [comment]
Thanks for your prompt reply @maggiesMSFT Yes, it makes sense to move this question to Power BI feedback community. It would also be beneficial to perhaps add a small excerpt on the Azure Consumption Insights connector's article to in regard to the future deprecation/upgrade plan for existing users. I will wait for @davidiseminger's comments as well. Cheers!

**Comment by davidiseminger** [comment]
Hello - we can speculate about future releases (or support cycles) until they are officially announced, sorry about that.
