### ISSUE TITLE
[Missing] API

### ISSUE THREAD

**Issue by g-berthiaume** [MicrosoftDocs/powerbi-docs#1547]
It is now possible to export reports as pdf using the GUI.
I think it would be useful for developers to have a section mentioning how to do it using the PowerBI REST API.
Thanks.

**Comment by srigney2142** [comment]
Thanks for your comment, @g-berthiaume In the meantime, can you provide a little more detail on the issue you raised? Which document needs this new information and who is the author?

**Comment by mgblythe** [comment]
Assigning to @KesemSharabi to potentially get the API docs updated.

**Comment by KesemSharabi** [comment]
Hi @g-berthiaume, thanks for your comments. The 'export report to PDF etc.' API will be in public preview in the end of February 2020. The documentation for this feature will also be available around that time.

**Comment by g-berthiaume** [comment]
>The 'export report to PDF etc.' API will be in public preview in the end of February 2020. The documentation for this feature will also be available around that time.


Excellent news. Thanks for your reply @KesemSharabi .
I'm looking forward to it.
