### ISSUE TITLE
Please update the list of certifed Visuals

### ISSUE THREAD

**Issue by klabir** [MicrosoftDocs/powerbi-docs#1549]
for example, Ultimate KPI Card is missing.
thx
Klaus

**Comment by srigney2142** [comment]
Thanks for your comment, @klabir Can you provide a little more detail on the issue you raised?

**Comment by klabir** [comment]
https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified
on the end of the site, a list of certified visuals is displayed, it miss Ultimate KPI Card  which was recently certified. thx klaus

**Comment by maggiesMSFT** [comment]
Hi, @klabir -- thanks for providing more info! Assigning to the author to assess.

**Comment by KesemSharabi** [comment]
Hi @klabir,

I'm looking into this and will update you shortly.

**Comment by KesemSharabi** [comment]
Hi @klabir,

I updated the list of certified Power BI visuals in [Get a Power BI visual certified](https://docs.microsoft.com/en-us/power-bi/developer/power-bi-custom-visuals-certified). It now includes  Ultimate KPI Card.

To view the list directly, see [Certified Power BI visuals](https://docs.microsoft.com/en-us/power-bi/developer/power-bi-custom-visuals-certified#certified-power-bi-visuals).

Thanks,

Kesem
