### ISSUE TITLE
KPI VISUALS - POWER BI MICROSOFT DOCS

### ISSUE THREAD

**Issue by Yettybrown** [MicrosoftDocs/powerbi-docs#155]
Very well explained thank you very much !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [KPI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-visualization-kpi)
* Content Source: [powerbi-docs/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-visualization-kpi.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
@Yettybrown ,
Thank you :-)  Always nice to open feedback and find positive comments. 
Take care,
Michele
