### ISSUE TITLE
Free Account

### ISSUE THREAD

**Issue by mike-the-walsh** [MicrosoftDocs/powerbi-docs#1550]
Please document to process to try this for free...creating a VM is not at all like this. I have tried with a couple of email addresses to get to the Power BI Report Server on the VM step (https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal#power-bi-report-server-on-the-vm) and the desktop is a barebones 2012 server. I also was advised that I was not eligible for a free preview account to try it out, that I had te register for a pay as you go account...not cool. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c7b5d6-c9a4-3445-81c1-41dc41ae0929
* Version Independent ID: a45e9b8a-185b-ff29-dc4a-b8912c13ed1b
* Content: [Tutorial: Explore Power BI Report Server in a VM - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal#feedback)
* Content Source: [powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mike-the-walsh** [comment]
took a while...restarted from VM Panel in Azure...

**Comment by maggiesMSFT** [comment]
Hi, @mike-the-walsh -- glad to hear it worked out!
