### ISSUE TITLE
Admin Settings?

### ISSUE THREAD

**Issue by apfenech** [MicrosoftDocs/powerbi-docs#1556]
Hello - it's mentioned that the Premium capacity admin can turn this on/off and set the minimum refresh interval but I cannot find this in the admin portal; where are these settings located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedb7099-554f-0eed-eaa6-fc13851eb3b1
* Version Independent ID: 8beddbbe-5ebc-60e4-ab28-fd130283a8c1
* Content: [Automatic page refresh in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-automatic-page-refresh)
* Content Source: [powerbi-docs/desktop-automatic-page-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-automatic-page-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srigney2142** [comment]
Thanks for your comment, @apfenech  I've assigned this issue to the doc author for review.

 In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by spatney** [comment]
@apfenech, they are located under "Workloads" within settings for your capacity.
