### ISSUE TITLE
Disabled the conditional formatting option for graphics.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1559]
The comment below was machine translated

@andersonbernard0 commented on [Mon Oct 28 2019](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/28)

Have there been any changes to the version of Power BI? Conditional formatting options for graphics are no longer enabled.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Dicas e truques para formatação com cores no Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/visuals/service-tips-and-tricks-for-color-formatting#feedback)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

---

@srvbpigh commented on [Mon Oct 28 2019](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/28#issuecomment-546966774)

Hello, @andersonbernard0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mgblythe** [comment]
Thanks @CeciAc. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Assigning to content owner.

**Comment by mihart** [comment]
Hi @CeciAc ,
Thank you for your question.  Conditional formatting is still supported and still in the product. It has moved and you now need to select the three vertical dots next to "Default color".  You can see how to do this by reading powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md and scrolling down to the section titled "Base the color of data points on a value". 
Hope this helps!

**Comment by santiagobs** [comment]
Hi, on the current PowerBI Version (2.79.5768.1082 march 2020) I can't seem to find this conditional formatting for maps and other visuals, it seems now it's only supported by matrix and table visualizations.

**Comment by suresh-myneni** [comment]
Conditional formatting is not showing up for visuals (line, bar charts... ??) Did anyone figure out how to get them enabled in the latest version?
