### ISSUE TITLE
All permissions no access

### ISSUE THREAD

**Issue by cschmid16** [MicrosoftDocs/powerbi-docs#1560]
I am the project site administrator.  I am a portfolio manager. I have all access permissions.  Why do I continue to get the error "Access to the resource is forbidden?
![Unable to Connect](https://user-images.githubusercontent.com/45680577/67734700-b911aa80-f9cf-11e9-804a-6d44373e9385.png)
Reference: https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data

**Comment by srigney2142** [comment]
Thanks for your comment, @cschmid16  This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
