### ISSUE TITLE
Unable to create paginated report from power bi dataset.

### ISSUE THREAD

**Issue by MungBurger** [MicrosoftDocs/powerbi-docs#1561]
I've followed instructions above but when I get to posting the DAX query - the designer is not available. If I refresh field i am prompted for credentials. This fails, then the error returned is "Value cannot be null. Parameter name: uriString"
The data source for the Power BI dataset is a direct query to a SQL Database. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf55ca48-9d24-4a87-0f90-b660d3d0ca50
* Version Independent ID: 09e9b1e9-82b6-3efd-7b77-040c284b917b
* Content: [Use shared datasets in Power BI Paginated Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-shared-datasets#feedback)
* Content Source: [powerbi-docs/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MungBurger -- I'll look into this and see what's up. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @MungBurger -- just checked. Something's not working, so you need to enter a support case at https://powerbi.microsoft.com/en-us/support/
Hope that helps!
