### ISSUE TITLE
Analyzed By External Application

### ISSUE THREAD

**Issue by chayakiran** [MicrosoftDocs/powerbi-docs#1564]
In the Audit Logs, for the Operation of "Analyzed By External Applications", the Dataset ID is missing. Displaying just the Dataset Name that is being analyzed is not sufficient in our org, as we have same dataset name across the Dev, QA and Prod workspaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Use auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#feedback)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srigney2142** [comment]
Thanks for your comment, @chayakiran This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by mgblythe** [comment]
Hi @chayakiran - if this is a suggestion on how to improve the product, you can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
