### ISSUE TITLE
A Bug Still Exists

### ISSUE THREAD

**Issue by DucatiV4S** [MicrosoftDocs/powerbi-docs#1565]
There is still a bug which needs to be resolved. You can also reference this post https://community.powerbi.com/t5/Issues/Gateway-data-refresh-fails-when-data-is-merged-from-web-and-on/idi-p/594579

I have my enterprise on-prem gateway data sources all set to "Organizational" I have a SharePoint 365 connection to an Excel file which is also set to "Organizational". I merge (left join) my gateway SQL query with an Excel file source from SharePoint. Again, both are set to "Organizational". I receive the error message that my credentials are invalid, even though that is not true. If I remove the merge from my query the dashboard scheduled refresh executes without any issue. I have tried using From SharePoint Folder to grab the Excel file and From Web Excel.Workbook etc. Both sources set to "Organizational" and I still receive the same error. It's a known bug and everyone is having the same problem. PLEASE can you solve this bug? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud#feedback)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by srigney2142** [comment]
Thanks for your comment, @DucatiV4S  This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
