### ISSUE TITLE
Does the push dataset support the association of different variable dimensions in the data?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1568]
The comment below was machine translated

@miya898 commented on [Tue Oct 29 2019](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/48)

As the title, suppose you want to upload multiple variables, but also want to have an association between these variables, like in the database, can you?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Power BI 中的实时流式处理 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/service-real-time-streaming#feedback)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Tue Oct 29 2019](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/48#issuecomment-547423062)

Hello, @miya898
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mgblythe** [comment]
Thanks @CeciAc. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @CeciAc . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
