### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#157]
@DaveRuijter commented on [Mon Aug 06 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/6)

Please keep the list of audited actions up-to-date.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Auditing gebruiken binnen uw organisatie - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

---

@LisandroSu commented on [Mon Aug 06 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/6#issuecomment-410834746)

Hello, @DaveRuijter , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user reports out of date data.

Kind regards,
Microsoft DOCS International Team

**Comment by mgblythe** [comment]
Thanks @DaveRuijter -- I'm putting an item in my backlog for next month to address issues with the audit info. I will keep this issue open until I address it.

**Comment by mgblythe** [comment]
The table at the end of this article is now complete: https://docs.microsoft.com/en-us/power-bi/service-admin-auditing. Closing this issue out. Thanks!
