### ISSUE TITLE
Add Custom Visual API Version supported by Report Server

### ISSUE THREAD

**Issue by klabir** [MicrosoftDocs/powerbi-docs#1570]
we need to know which Custom Visual API shipped with the release

**Comment by mgblythe** [comment]
Thanks for your comment, @klabir. I'm assigning to one of our authors for review, but can you provide more info on which release you're referring to? Desktop? 

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by klabir** [comment]
hello, yes,which API for Power bi custom visuals is supported in the current release. for example i assume currently it is API 2.6.. but not sure

**Comment by KesemSharabi** [comment]
Hi @klabir,

Power BI RS September 2019 supports API 2.6.0.

To the best of my knowledge, Power BI RS May 2019 also supports API 2.6.0.
