### ISSUE TITLE
Planning a Power BI Enterprise Deployment - needs a refresh

### ISSUE THREAD

**Issue by KKrachmer** [MicrosoftDocs/powerbi-docs#1571]
There is a lot of great information in these whitepapers.  We have heavily referenced the "Planning a Power BI Enterprise Deployment" document.  It is now well over a year old. In Power BI world, that is a long time.  When will it be refreshed? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e576bbf-5964-ce92-cb3a-3bbc57c6bd61
* Version Independent ID: 9e87a5bd-07d8-20f6-2f50-fa5e4cbb2eb7
* Content: [Whitepapers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepapers#feedback)
* Content Source: [powerbi-docs/whitepapers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepapers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @KKrachmer. I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article was updated in May (https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment). If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
