### ISSUE TITLE
Provide your Access key to connect page is always blank

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/powerbi-docs#1572]
Hi,
Is this page outdated? Is the Connector outdated ?
Everyone is reporting that the Provide your "Access key to connect" Step always shows a blank page. 
![image](https://user-images.githubusercontent.com/14938496/67941466-f182d580-fbd5-11e9-9bac-45c0bea7276d.png)

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights#FindingParams)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by jtallman** [comment]
I am experiencing the same from the Power BI service and have a spinning connect button on the Account Key Screen when attempting to connect through Power BI desktop.
![AzureConsumptionInsites Account Key screen](https://user-images.githubusercontent.com/2665982/67975572-9a7b0180-fbd1-11e9-8614-493ad7d618fc.png)

**Comment by mgblythe** [comment]
Thanks for your comments, @SamirFarhat and @jtallman. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
