### ISSUE TITLE
Preferred communication method: TCP or HTTPS

### ISSUE THREAD

**Issue by ancibira** [MicrosoftDocs/powerbi-docs#1573]
The Power BI enterprise deployment white paper states that TCP is faster than HTTPS, but as of July 2019 the default gateway communication is HTTPS. Can you confirm that TCP is still faster for Power BI?
https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#force-https-communication-with-azure-service-bus

**Comment by mgblythe** [comment]
Thanks for your comment, @ancibira. I've assigned this @arthiriyer to address.

**Comment by kfollis** [comment]
@ancibira - Thank you for the feedback on our documentation. The enterprise deployment whitepaper has been updated (https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment). The whitepaper notes that the change to HTTPS as default should have only a nominal performance impact. We are closing this issue, but if you feel your feedback isn't addressed, please feel free to submit additional feedback for the page.
