### ISSUE TITLE
ServiceNow App is not showing up?

### ISSUE THREAD

**Issue by alparslankaya** [MicrosoftDocs/powerbi-docs#1575]
When I search for "Service" or "ServiceNow", the app does not appear on the list.  Although when I searched for it the other day, the ServiceNow app was showing up in my search.  Is this app still available or is there another issue? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2ce012-0b66-7a2d-2ce0-630f35abdf88
* Version Independent ID: 7d647855-d659-d495-e876-9189a5ba5125
* Content: [Connect to ServiceNow with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-servicenow#feedback)
* Content Source: [powerbi-docs/service-connect-to-servicenow.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-servicenow.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @alparslankaya. I've assigned this issue to the doc author for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by alparslankaya** [comment]
Thanks Michael

I took a look at the PBI community but this SNOW /pbi app and if it exists or has been pulled is very unclear.  I was hoping we could get a final concise answer. Our online docs says the SNOW app should exist.

Looking forward to hearing from you guys
Thanks!
Alp

**Comment by maggiesMSFT** [comment]
Hi, @alparslankaya -- you're right. The ServiceNow app is no longer available. I recommend going to https://ideas.powerbi.com/forums/265200-power-bi to express your interest in it. 
thanks!
