### ISSUE TITLE
What's the next step?

### ISSUE THREAD

**Issue by mssososophie** [MicrosoftDocs/powerbi-docs#1576]
I'd have expected to see a link to docs on how I upload/intergrate this sample template to my own data sets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b777f61-d4cf-bc8e-64b5-43c2e695051b
* Version Independent ID: 20c2b71c-b805-b5e1-4de3-f5bc51de91e5
* Content: [Template apps samples - Power BI](https://docs.microsoft.com/en-us/power-bi/service-template-apps-samples#feedback)
* Content Source: [powerbi-docs/service-template-apps-samples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-template-apps-samples.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @teddybercovitz
* Microsoft Alias: **tebercov**

**Comment by mgblythe** [comment]
Thanks for your comment, @mssososophie. I've assigned this issue to the doc author for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by teddybercovitz** [comment]
Thanks for the question @mssososophie, could you clarify what did you mean by merging with your own dataset. Is the goal to create your own template app and share in AppSource or refresh it with your own data? 
@paulinbar

**Comment by mssososophie** [comment]
Under the list titled 'Downloadable Template apps samples' I was expecting to see a link to a page that would help me author those app samples. 

I'm a new user of PBI so knowing the next step after downloading those samples would be valuable to me.

you mention in the paragraph at the top 'The Samples are in pbix file format and can be _authored_ with Power BI desktop.' I don't know what specifically 'authoring' means nor how to do it.

**Comment by paulinbar** [comment]
Hi @mssososophie, you said that you are a new user of PBI. Was your expectation of the sample that it would help you learn how to use PBI Desktop, or were you intending to create a template app, which is a specific kind of thing? I am a documentation person and I'm very interested in your experience and in determining where things went wrong for you and how to address that so that someone like yourself gets to the information that that they need. Thanks.

**Comment by paulinbar** [comment]
Hi @mssososophie , getting back to your statement that you are a new PBI user, I suggest that the place to start is with the Desktop. There you create the reports that eventually you publish online to the PBI service. So perhaps please take look at this link https://docs.microsoft.com/en-us/power-bi/desktop-getting-started and also, when you start Power BI Desktop, on the splash screen that you see at first, there are links both to documentation, tutorials, and samples that you can download and start playing around with. Hopefully the documentation link I sent will get you started learning about how to "author" reports in Power BI Desktop. I find that there is also a lot of good information to be found just by googling on whatever question you have, and then again there is a pretty good [Power BI Community]( https://community.powerbi.com) that sometimes can be of help.
In any event,, good luck! I'm closing this issue for now, but feel free to get back to me if you have further questions about how to get started.
