### ISSUE TITLE
On Prem requirements conflicts with Direct Query list

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerbi-docs#1577]
It seems the On Prem Gateway requirements are for databases in general, but this page is supposed to be about support for Direct Query. MySQL is not supported by Direct Query, but it is listed in the On Prem Gateway requirements, so it is a bit misleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @edhans. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
I'm sorry you found that a bit misleading, we're trying to provide as much information in that table as possible. We'll look at how we can restructure that table to avoid creating confusion. Thanks for your feedback.

**Comment by mgblythe** [comment]
@davidiseminger - I removed the article that this comment originally referred to and redirected to the new article that covers DQ and gateways. We should be all good on conflicting info b/c there's now only one source.

**Comment by edhans** [comment]
Thanks! Much cleaner. Appreciate it team.
