### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by cstork** [MicrosoftDocs/powerbi-docs#1579]
This seems out of date: nested hierarchies are an old feature by now. This makes me wonder if the troubleshooting section is also out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a19e5f1-0d56-2e8b-b7eb-2fa9753738d4
* Version Independent ID: db10dca9-4082-e863-a971-adc1bd37e7fe
* Content: [Use inline hierarchy labels in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-inline-hierarchy-labels)
* Content Source: [powerbi-docs/desktop-inline-hierarchy-labels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-inline-hierarchy-labels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
