### ISSUE TITLE
Downloading the PBIX

### ISSUE THREAD

**Issue by mcsmith3** [MicrosoftDocs/powerbi-docs#1581]
Is it possible to make it so the user can download the PBIX files that are created by these?  We have some custom fields and would like to utilize this structure along with them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8a7a22-e258-4da3-4c55-6ddb1085c521
* Version Independent ID: 0b3f2b88-9e73-f4dd-0f21-fe3c156a99b8
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-project-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-project-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @mcsmith3.

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
