### ISSUE TITLE
View sharing permissions 

### ISSUE THREAD

**Issue by Bryand13** [MicrosoftDocs/powerbi-docs#1582]
Hi all,

Is there any way to see sharing permissions on, reports, dashboards and apps?

Thanks in advance!

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Bryand13 .

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by Bryand13** [comment]
> Thanks for your comment, @Bryand13 .
> 
> This looks like a support request or product question rather than documentation feedback.
> 
> You might find a solution in the [Power BI Community](https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by Bryand13** [comment]
Thank you @KesemSharabi for your response.

I was meant via API REST or directly with powershell. But i'll try to find the answer in the pages that you mentioned also.

Thank you!
