### ISSUE TITLE
Parameters not accepted in Custom Filter

### ISSUE THREAD

**Issue by kamikazenaz** [MicrosoftDocs/powerbi-docs#1583]
Needs updating: In the 'Filter Rows' illustration it shows the parameters being selected in the basic setting but I had to go to Advanced to be able to select the set parameters as otherwise it would not accept anything that was not a date.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-gb/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by paulinbar** [comment]
Thanks for reaching out to us with your comment, @kamikazenaz! I've assigned this issue to the doc author for review.

**Comment by mgblythe** [comment]
#reassign @kfollis

**Comment by mgblythe** [comment]
#reassign @mgblythe

**Comment by mgblythe** [comment]
#reassign @christianwade for a new screenshot.

**Comment by christianwade** [comment]
Unable to repro. Successfully walked through the steps without needing to go to Advanced.
#please-close
