### ISSUE TITLE
Can this connector be used to pull the data given by ACM Exports directly in to PowerBI 

### ISSUE THREAD

**Issue by hisathya** [MicrosoftDocs/powerbi-docs#1584]
Can this connector be used to pull the data given by ACM Exports directly in to PowerBI  ? In detail, I do not intend to use Exports or APIs and storage account.  I want to pull that Exports data directly into PowerBI may be at subscription level or management group level. 

Is that something supported with this connector ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @hisathya.  

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
