### ISSUE TITLE
R Visuals are not working in Power BI Service

### ISSUE THREAD

**Issue by isa1821** [MicrosoftDocs/powerbi-docs#1585]
I created some visuals in Power BI Desktop using R scripts. However, when I published my report, I got the following error in my R visuals: "Script Runtime Error An error occurred while running the script Please try again later or contact support. If you contact support, please provide these details.". Can anyone help me?

**Comment by paulinbar** [comment]
Hi @isa1821, thanks for reaching out to us with your question. It looks to me like R Visuals don't display when publishing to the web. See the limitation in this [support article](https://docs.microsoft.com/power-bi/visuals/service-r-visuals#known-limitations). You might also see the comment on the [Power BI Community](https://community.powerbi.com/t5/Service/Publishing-R-visual-into-Power-BI-Service-Run-time-error-RODBC/td-p/475079). Feel free to get back to us if this does not answer your question.
