### ISSUE TITLE
Service Principal

### ISSUE THREAD

**Issue by jgoleson** [MicrosoftDocs/powerbi-docs#1586]
In our situation, when testing this out, we are using an "App Owns Data" web application for our embedded reports. This is accessed through the service principal, so that's the value that shows up when using UserID (Just shows the spn Object ID). How do we get the logged in user and not spn. In the past we used the "CustomData" property to do something similar to pass the user id to an AAS cube. Is there something similar here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3e7facd-9b41-c417-3309-ee80c2d10d66
* Version Independent ID: 111c21d8-602f-7df3-4e41-bcfb3cb82c31
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/paginated-reports-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/paginated-reports-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/paginated-reports-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @jgoleson,  I've assigned your question to the author responsible for the doc you referred to. Thanks for reaching out to us!

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jgoleson. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
