### ISSUE TITLE
Avoiding IMPORT data while setting up incremental refresh in context menu

### ISSUE THREAD

**Issue by Mech-Mind** [MicrosoftDocs/powerbi-docs#1587]
I understand that IMPORT is required in order to use Incremental Refresh but I do not want to download billions of records via IMPORT to my PBI Desktop just to finish setting it up. When I go to the Incremental Refresh context menu of the table it has everything disabled because it is not set to IMPORT. I'm kind of in a catch-22... How do you get around this setup issue when dealing with a ginormous table that you do not want to download locally?

**Comment by paulinbar** [comment]
Hi @Mech-Mind, thanks for reaching out to us with your question. Have you looked at either of the following pages? [Using DirectQuery in Power BI](https://docs.microsoft.com/power-bi/desktop-directquery-about) or [Incremental refresh in Power BI Premium](https://docs.microsoft.com/power-bi/service-premium-incremental-refresh
). If you don't find an answer to you question in the documentation, I suggest you try either the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com).
