### ISSUE TITLE
Minimum data source version for PostgreSQL

### ISSUE THREAD

**Issue by AldrinL** [MicrosoftDocs/powerbi-docs#1588]
On this doc, it says PostgreSQL aim to be compatible with all currently supported PostgreSQL versions, which means 5 years back. Earlier versions may still work but we don't perform continuous testing on them or commit to resolving issues on them.
https://www.npgsql.org/doc/compatibility.html
7.4 is not supported since 2010.10.1. I think you should change the version to 9.4 which is the oldest support version.
Version 	Current minor 	Supported 	First Release     	Final Release
9.4 	               9.4.24   	             Yes 	December 18, 2014 	February 13, 2020

We need to change this because it is bringing unnecessary troubleshooting work for CSS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d081a0-4c4b-f756-eaf7-1e98d583ecf8
* Version Independent ID: 0b694de6-df10-daca-888c-1062dd3299db
* Content: [Power BI data source prerequisites - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-source-prerequisites#feedback)
* Content Source: [powerbi-docs/desktop-data-source-prerequisites.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-source-prerequisites.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @AldrinL . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Great point - I've changed that. Thanks for bringing that to our attention!
