### ISSUE TITLE
No mention of schedule refresh limitations

### ISSUE THREAD

**Issue by mdjaniga** [MicrosoftDocs/powerbi-docs#1589]
For instance limitation such as refreshes per day by license type should be explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-scheduled-refresh#feedback)
* Content Source: [powerbi-docs/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @mdjaniga . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @mdjaniga - we cover this here: https://docs.microsoft.com/power-bi/refresh-data#data-refresh. I'll add a link from the scheduled refresh doc to this one.

**Comment by mgblythe** [comment]
I added the following sentence:

For more information about data refresh, including limitations on refresh schedules, see Data refresh.

**Comment by mdjaniga** [comment]
Thanks Y'all, looks good.

M
