### ISSUE TITLE
How to assign "My Workspace" to Premium capacity?

### ISSUE THREAD

**Issue by hrjoshi** [MicrosoftDocs/powerbi-docs#159]
In Known issues section, it is mentioned that "If the My Workspace is in a Premium capacity, then free users and user groups will receive the emails.".
How do we assign "My Workspace" to premium?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks @hrjoshi, assigning to @maggiesMSFT to fix. She is on vacation but will address when she returns.

**Comment by maggiesMSFT** [comment]
Hi, @hrjoshi -- select **Workspaces** in the left nav > select the ellipsis (...) next to **My Workspace** > select **Edit workspace**. You'll see an option to turn on **Dedicated capacity**. 
You may not have permissions to turn it on. In that case, contact your Power BI admin.
Hope that helps!
