### ISSUE TITLE
Exporting answers from Power BI QnA visual/Customizing answers 

### ISSUE THREAD

**Issue by kishan19** [MicrosoftDocs/powerbi-docs#1590]
Hi, is there any way I can customize the way answers are displayed  from the Power BI QnA visual or access the answer data and send it to an external system in real time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cce1494-8caa-53a4-497b-fbdcd6595a5c
* Version Independent ID: c4f3b927-5eb0-6bd9-3cb2-b366e90da3b3
* Content: [Create a visual with Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-visualization-introduction-to-q-and-a#feedback)
* Content Source: [powerbi-docs/power-bi-visualization-introduction-to-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-visualization-introduction-to-q-and-a.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for posting @kishan19  – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
