### ISSUE TITLE
DQ row number limit

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#1591]
Hi team. 
We have the following statement in this page: "There is a one-million-row limit for returning data when using DirectQuery. (..) If more than 1 million rows would be returned from DirectQuery, Power BI returns an error."
But it is true for Pro. 
For premium we can increase this number (proof) https://powerbi.microsoft.com/es-es/blog/five-new-power-bi-premium-capacity-settings-is-available-on-the-portal-preloaded-with-default-values-admin-can-review-and-override-the-defaults-with-their-preference-to-better-fence-their-capacity/
How this behavior work in desktop? 1 million is for everyone but later it can be increased on the service (if in premium)?
Shouldn't we point this out clearly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery#limitations-of-directquery)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @chizhova . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Great point - I've added that note, and linked to that blog post. Thanks!
