### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Betenoir7** [MicrosoftDocs/powerbi-docs#1595]
In the 1st line of para 5 in the Strong relationships section following the Note, it says, " For Many-to-many relationships, table expansion takes place from the "many" to the "one" sides by using LEFT OUTER JOIN semantics."

Shouldn't this read "For One-to-many relationships, table expansion takes place from the "many" to the "one" sides by using LEFT OUTER JOIN semantics." ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-relationships-understand#feedback)
* Content Source: [powerbi-docs/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Betenoir7 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by peter-myers** [comment]
Thanks for picking up the typo! The fix will appear shortly.

**Comment by peter-myers** [comment]
#please-close
