### ISSUE TITLE
OAuth - supported or not?

### ISSUE THREAD

**Issue by Matthew-Lewis** [MicrosoftDocs/powerbi-docs#1596]
The limitations section of this documentation says that "OAuth isn't a supported authentication scheme with the on-premises data gateway."

However, this blog post:

https://powerbi.microsoft.com/en-us/blog/on-premises-data-gateway-october-update-is-now-available-2/

says that OAuth support was added in October 2018.

Does anyone know which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce758c1b-c94e-3fbb-2310-fa888c6640d8
* Version Independent ID: 0c647a13-fd95-ae03-1a15-5f5da162091d
* Content: [Manage your data source - Import/scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-scheduled-refresh#feedback)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-enterprise-manage-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Matthew-Lewis . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by omnoms** [comment]
The term "shortly" is relative here :D

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been recently updated and the referenced section no longer exists. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
