### ISSUE TITLE
This page mis-represents abilities & layouts of visual headers

### ISSUE THREAD

**Issue by hsims19** [MicrosoftDocs/powerbi-docs#1597]
This page states that visual headers by default are stationed in line with the title (if the visual has one). This is not accurate. No matter the alignment, size, or presence of a title, the visual header is always positioned above the visual (as is shown above when the visual does *not* have a title. This is incredibly frustrating because I need this capability but the product does not do what you say it does. Instead, I have to create a separate text ow as the title and try ot line it up with the visual header from the visual below. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db547626-10e8-5ea4-e1c3-7da6c236ce9f
* Version Independent ID: 4529c3a6-1f8f-2e8c-4eaf-9bde90c4df54
* Content: [Use visual elements to enhance Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-visual-elements-for-reports#feedback)
* Content Source: [powerbi-docs/desktop-visual-elements-for-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-visual-elements-for-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @hsims19 . We’ll take a look at that and get back to you soon. Thanks!

**Comment by hsims19** [comment]
Hi David,

I found the issue is my screen resolution. If I fit to page and have the left hand toolbar open, it squeezes the visual header to the top. If I put the report on my external monitor, it behaves as expected. However, given that I cannot anticipate how my users will be viewing this report, their screen size, etc, this still means I still consider this a bug that I have to design around with the text box title solution unless I can be guaranteed that on any desktop/laptop machine the visual header will *always* work as expected.

**Comment by davidiseminger** [comment]
Thanks for the clarification - your information will hopefully help others who see this. I'll close this, but it'll stay for others to learn from how you fixed your issue.
