### ISSUE TITLE
[OOS]Excel workbook failed to open on powerbi report server WEB portal

### ISSUE THREAD

**Issue by KEID07** [MicrosoftDocs/powerbi-docs#1598]
**Problem:**
After my excel workbook is opened, the powerbi report server displays a blank page, and the page prompts: "< my internalurl > take too long to respond."

**Background information:**
I have two servers, both of which use Windows Server 2012 R2 system.   
They are all in the same domain.   
One (A) is domain controller, and the other (B) has office online server and powerbi report server installed.  
 I configured according to the [document ](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oo) and returned the correct XML data in "< internalurl > / hosting / discovery".

**Possible relevant information returned from Google Chorme:**
"http://<my internalurl>/x/_layouts/xlviewerinternal.aspx?WOPISrc=http%3A%2F%2Flocalhost%3A8080%2Fwopi%2Ffiles%2F52291a55-9092-4bda-8bba-758d0585c336&amp;ui=en-US"
header:Request URL: http://<my internalurl>/x/_layouts/xlviewerinternal.aspx?WOPISrc=http%3A%2F%2Flocalhost%3A8080%2Fwopi%2Ffiles%2F52291a55-9092-4bda-8bba-758d0585c336&amp;ui=en-US
Preview: Fail to load response data
"
**About version:**
office online server 2016 may (run on machine B, Port:80,443,809,810)
powerbi report server september (run on machine B,
Port:8080)
IIS Express: 8.0 (run on machine B)
SQL Server 2017 (run on machine A for hosting report server database)

**Comment by mihart** [comment]
Thanks for your comment, @KEID07 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
