### ISSUE TITLE
How can we get weekly data?

### ISSUE THREAD

**Issue by geeliano** [MicrosoftDocs/powerbi-docs#1599]
We need to have a powerbi dashboard either with daily or weekly cost but all this connector seems to show is months total. Is information missing and there is some way to get weekly data or is the feature not available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data in Power BI desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @geeliano . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @geeliano . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
