### ISSUE TITLE
What about Power BI Report Server?

### ISSUE THREAD

**Issue by gunarvingren** [MicrosoftDocs/powerbi-docs#160]
I am currently not able to perform this action on the Power BI Report Server with in my company intranet. Could you tell me how I can achieve this? Within My Workspace I can not find the Analyze in Excel option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-hz2_OuXfksn9FamjfmAgOw&epi=je6NUbpObpQ-hz2_OuXfksn9FamjfmAgOw&irgwc=1&OCID=AID681541_aff_7593_1243925&tduid=(ir_TIs0n20TmTWf0yr1Jq2xP3EgUkjSSET27201UU0)(7593)(1243925)(je6NUbpObpQ-hz2_OuXfksn9FamjfmAgOw)()&irclickid=TIs0n20TmTWf0yr1Jq2xP3EgUkjSSET27201UU0)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry to hear about your trouble. This is a support request, rather than documentation feedback. Please use https://support.powerbi.com to submit support tickets.
