### ISSUE TITLE
The second part of this article maybe is outdated

### ISSUE THREAD

**Issue by NorbertoAlves** [MicrosoftDocs/powerbi-docs#1600]
When I had attempted to Validate the role within the Power BI service, I couldn't relate people to the security roles created because there is a message that this feature has been moved to Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @NorbertoAlves . This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Hi @NorbertoAlves, which part of the article is the issue? You need to define roles in Desktop, and you can test them there also. You then add users to those roles in the service, and you can test them again from <Dataset> -> Security in the left nav. Let me know if there's anything we can clarify.

**Comment by NorbertoAlves** [comment]
@mgblythe 
When I had created this issue, I have seen a message at Power BI Service that the functionality of assigning people to each role had been moved to Power BI Desktop, but today, when I tested again to take a screenshot to clarify, this has changed to the same screens that we can see in the article. Sorry for the inconvenience, and thank you for your response.
