### ISSUE TITLE
PowerBI RS Download link: please update to the latest Download link

### ISSUE THREAD

**Issue by v-maudel** [MicrosoftDocs/powerbi-docs#1602]
@arcus4 commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/10)

https://www.microsoft.com/download/details.aspx?id=56722 is an older version of PowerBI RS.
Pls update to the latest Download link https://www.microsoft.com/en-us/download/details.aspx?id=57270

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 69db1b96-91ed-2440-5a1c-873a19d7ee47
* Version Independent ID: db0e2007-963b-44a5-9b6e-5be35481473e
* Content: [Installieren von Power BI-Berichtsserver - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/install-report-server#feedback)
* Content Source: [powerbi-docs/report-server/install-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/install-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@srvbpigh commented on [Tue Nov 12 2019](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/10#issuecomment-552922500)

Hello, @arcus4
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @v-maudel . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
@arcus4 - you're right! Thanks for the reminder. I'll fix it.

**Comment by maggiesMSFT** [comment]
Thanks again, @arcus4. Update will be live this afternoon.
