### ISSUE TITLE
Are we supposed to create an "Application Security Group" or a plain old group?

### ISSUE THREAD

**Issue by DanielJBrown** [MicrosoftDocs/powerbi-docs#1603]
This link for "security group in Azure Active Directory (AAD)" in the following section above...
2. Recommended - Create a security group in Azure Active Directory (AAD), and add the application you created to that security group. You can create an AAD security group with PowerShell.
Takes me to 
https://docs.microsoft.com/en-gb/azure/active-directory/fundamentals/active-directory-groups-create-azure-portal

I believe this is the incorrect location.
It should be point to instructions to create an APPLICATION security group not just a plain old Azure directory group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @DanielJBrown. I've assigned this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @DanielJBrown,

Thanks for pointing out the error in the document.

I've fixed the [Service principal with Power BI](https://docs.microsoft.com/power-bi/developer/embed-service-principal) article, and it is now pointing to [Application and service principal objects in Azure Active Directory](https://docs.microsoft.com/en-gb/azure/active-directory/develop/app-objects-and-service-principals).

See [Get started with a service principal](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal) step 2.
