### ISSUE TITLE
On-demand refresh incorrectly mentioned

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#1604]
At paragraph https://docs.microsoft.com/en-us/power-bi/refresh-data#data-refresh it says (which is correct in my opinion):
On-demand refreshes are not included in the refresh limitation.
But in paragraph https://docs.microsoft.com/en-us/power-bi/refresh-data#configure-scheduled-refresh it says:
On-demand refreshes don't affect the next scheduled refresh time, but they count against the daily refresh limit, as explained earlier in this article.
This last statement is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data#configure-scheduled-refresh)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by KesemSharabi** [comment]
Thanks for catching that issue, @NickyvVr! I've assigned this issue to the doc author for review.

For future reference - you can also edit articles directly: 

1. Select the Edit pencil icon at the top of the article, then select the little Edit pencil in GitHub. 
2. Make your change, scroll to the bottom, and select Propose file change.

The change is then sent directly to the writer, who will sign off and get it published. Thanks again!

**Comment by KesemSharabi** [comment]
Closed by mistake. Now reopened.

**Comment by mgblythe** [comment]
Thanks @NickyvVr, fixing this today.

**Comment by mgblythe** [comment]
Fixed and published.
