### ISSUE TITLE
Power BI Licensing

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1608]
Hi team,
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/issues/8

The comment below was machine translated

@TimTacko commented 1 hour ago — with docs.microsoft.com
On the page, in the line "License" it is indicated that the product "Power BI Report Server" requires SQL Server EE with the rights of a system administrator. I believe that there is a translation error, instead of the system administrator, you must specify Software Assurance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service#feedback)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
assigned to myself to write out 'Software Assurance.'

**Comment by maggiesMSFT** [comment]
@CeciAc -- Done. Thanks!
