### ISSUE TITLE
Cortana answer card stuck on "Loading"

### ISSUE THREAD

**Issue by vassallosm** [MicrosoftDocs/powerbi-docs#161]
I have created a Power Bi answer card, did all the other permissions setup and configurations. I go to Cortana, search for the need card, find it, click it and is stuck on the Loading screen. 

Any thoughts?

**Comment by mgblythe** [comment]
@mihart -- any ideas what the issue might be here?

**Comment by maggiesMSFT** [comment]
Hi @vassallosm -- I suggest checking the Power BI Community https://community.powerbi.com/ for an answer.

**Comment by vassallosm** [comment]
@maggiesMSFT @mgblythe  
The issue has been resolved, it was a bug in the PowerBI code that the product group had to patch and update.

**Comment by maggiesMSFT** [comment]
Hi @vassallosm -- thanks for the update!
