### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by davesides** [MicrosoftDocs/powerbi-docs#1610]
Clicking on "Differences between OLAP and non-OLAP PivotTables in Excel" leads to page not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae990a42-30ce-e2cd-ef81-b2caba935050
* Version Independent ID: cd6b2f01-2ab8-bd8e-67a5-29a8f1ce3555
* Content: [Troubleshooting Analyze in Excel in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/desktop-troubleshooting-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for pointing this out to us @davesides . I've assigned this issue to the doc owner to be looked into.

**Comment by davidiseminger** [comment]
Sorry about that - looks like that resource is no longer available. I've removed that link.
