### ISSUE TITLE
Can you please keep updating the available regions updates here too.

### ISSUE THREAD

**Issue by dhawal16** [MicrosoftDocs/powerbi-docs#1611]
Team,

We are seeing https://powerbi.microsoft.com/fr-fr/blog/new-power-bi-regions-in-france-and-in-korea/ 
which is not updated here, can you please do the needful.

Thanks,
Dhawal Mehta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @dhawal16 -- thanks for your comment! Assigning to the author to take care of it.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
