### ISSUE TITLE
Typo contained in white paper

### ISSUE THREAD

**Issue by Betenoir7** [MicrosoftDocs/powerbi-docs#1612]
In para 1 on page 5 it says: "If John and Jane each contribute $100 to their account..."

For the example being used to make sense, the word "each" shouldn't be there.

It should read, "If John and Jane contribute $100 to their account..." 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7bffc1-7691-53e6-c582-c17b3f4c03da
* Version Independent ID: 6d3ce776-d39a-b834-e05b-73bc5452fd63
* Content: [Bidirectional cross-filtering in Power BI Desktop - Power BI](https://docs.microsoft.com/en-gb/power-bi/desktop-bidirectional-filtering#feedback)
* Content Source: [powerbi-docs/desktop-bidirectional-filtering.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bidirectional-filtering.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback - that page has been updated, and that passage removed. Thanks for the close read!
