### ISSUE TITLE
What does the * mean next to some theme classes?

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#1613]
The doc shows * next to multi row card title and reference line labels but doesn't explain what that is (unless I'm missing an explanation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @klinejordan -- I see what you mean. Assigning to the author to clarify. Thanks!

**Comment by davidiseminger** [comment]
We've updated the article to make themes much clearer. I hope that helps, thanks for your feedback.
