### ISSUE TITLE
Access without Enrollment or Billing ID

### ISSUE THREAD

**Issue by chrisjstanley** [MicrosoftDocs/powerbi-docs#1614]
As a subscription owner and cost contributor without Enrollment or Billing ID there is no way to connect to the data available in the Azure Cost Management. Would like to see Subscription ID be used in addition to Enrollment or Billing ID.

**Comment by maggiesMSFT** [comment]
Hi, @chrisjstanley -- this sounds like product feedback, not content feedback. Could you enter it at https://ideas.powerbi.com/forums/265200-power-bi?
Thanks!
