### ISSUE TITLE
Problema No se ha configurado la referencia del objeto

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1615]
@akelazr commented on [Fri Nov 15 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/26)

In this page is indicate as solution to the problem "Object reference not set" when connect to an Oracle DB . Copy oraons.dll but don´t specify the destination. Where should i copy this file?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Conectarse a una base de datos de Oracle - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Fri Nov 15 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/26#issuecomment-554368447)

Hello, @akelazr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc and @akelazr  -- Thanks for asking! Passing your question to the author of the article.

**Comment by davidiseminger** [comment]
Thanks for your comment. This is a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
