### ISSUE TITLE
Can you provide the sample dataset to reproduce this tut?

### ISSUE THREAD

**Issue by chris-han** [MicrosoftDocs/powerbi-docs#1617]
It's much easier for users to learn from hands-on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree?source=docs#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by M4RKLY** [comment]
As above please - the tutorial describes two datasets but doesn't provide them or the instructions for that part...

**Comment by mihart** [comment]
Thanks for your comment, @chris-han and @M4RKLY . This issue has been assigned to the doc author for review.

**Comment by emegallardog88** [comment]
Hi, I would love to have the sample dataset used in this example. As it was mentioned, it help to understand better how to create future visualization

**Comment by shethsameer** [comment]
Hi, wondering since Nov,2019 when @M4RKLY brought to notice about sample dataset do we have an update?

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated and a link to the sample data used in the supply chain scenario is included in the introductory section. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
