### ISSUE TITLE
Unable to see Edit Variables

### ISSUE THREAD

**Issue by yihjyh** [MicrosoftDocs/powerbi-docs#1618]
[Enter feedback here]
It is exciting to know now users can edit the SAP variables in Power BI Service, however, when I tested with one sample dashboard which connect to a SAP Hana view with variables, the option of "Edit Variables" is not showing up.
I have done both: wait for more than 5 minutes, and manually refresh the report but to no avail.
The settings for DirectQuery > Allow end users to change SAP variables has also been switched on. What could be missing? Any help?
Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9c21b0-3583-2744-5a5f-9401b791821c
* Version Independent ID: f8432546-d080-97aa-7b15-7c456f0e5a12
* Content: [Edit SAP variables in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-edit-sap-variables)
* Content Source: [powerbi-docs/service-edit-sap-variables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-edit-sap-variables.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by mihart** [comment]
Thanks for your comment, @yihjyh . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
