### ISSUE TITLE
This Contnet is not availble error

### ISSUE THREAD

**Issue by iLikeAzureSQL** [MicrosoftDocs/powerbi-docs#1619]
After publishing to public and using the URL I'm getting this error

This content is not available
Learn more about PowerBI

How can I debug ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mihart** [comment]
Thanks for your comment, @iLikeAzureSQL . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @iLikeAzureSQL -- if you're still having trouble with this issue, it sounds like you need to contact support, https://powerbi.microsoft.com/en-us/support/
Hope that helps!
