### ISSUE TITLE
Model language selection is missing

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#162]
Hi! In both Power BI Desktop for cloud and for Report Server the option for model language selection is missing in current versions
(Cloud version: 2.61.5192.601 64-bit; RS version 2.56.5023.1043 64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01f4ea6-33ff-97ca-4a4e-8a1beb88f12f
* Version Independent ID: e5224487-369d-23be-98cb-ebab58c75ac4
* Content: [Supported languages and countries/regions for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/supported-languages-countries-regions)
* Content Source: [powerbi-docs/supported-languages-countries-regions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/supported-languages-countries-regions.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks @chizhova, assigning to @maggiesMSFT to fix. She is on vacation but will address when she returns.

**Comment by maggiesMSFT** [comment]
Hi, @chizhova -- hearing no reply, I'm going to close your comment. Feel free to reopen it later. Thanks!

**Comment by pmi777** [comment]
Hi @maggiesMSFT, Options->Global->Regional Settings  this is missing in Microsoft Power BI Desktop (Optimized for Power BI Report Server), at least tested in last 2 releases, which means May 2019 as well as September 2019

**Comment by maggiesMSFT** [comment]
Hi, @pmi777 -- interesting question! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @pmi777 -- got an answer for you!

**Comment by pmi777** [comment]
Hi, @maggiesMSFT, first of all thanks for your attention. I think unified way of working in both versions would be more easy and beneficial, at least with common features that regional setting definitely is. Try to work with PBI desktop optimized which is installed in other language (e.g. Finnish) than you can understand where the only reason for that other language is the correct sorting requirement. Having there also Options->Global->Regional Settings we could set different language for the model and that way could avoid installation of localized PBI desktop optimized. Also for MSFT it would make life easier as it would not be needed to build and deploy language specific installers, but only one would be enough.

**Comment by maggiesMSFT** [comment]
Hi, @pmi777 -- thanks for elaborating! This is more feedback for the product than for the docs, right? Can you enter this feedback on the Power BI Ideas site, https://ideas.powerbi.com/forums/265200-power-bi? 
Thanks and good luck!

**Comment by pmi777** [comment]
Hi, @maggiesMSFT, i consider this as a bug rather than something worth to propose as a brand new idea to have. Anyhow thanks for you attention, however seems a waste of or time.
