### ISSUE TITLE
Row limit for direct query

### ISSUE THREAD

**Issue by stunugun** [MicrosoftDocs/powerbi-docs#1620]
To test the row limit, i created pbix file with direct query to a table which has 2 million rows which has an ID column.. I was able to browse the data in Power BI Services... Table Visualization all the 2 million records, so I am confused as what is meant by Direct query Row limit of 1 million.

**Comment by mihart** [comment]
Hi @stunugun, please let us know which article you are referencing.

**Comment by stunugun** [comment]
it is in multiple location below is one reference
"Model queries that require retrieval of more than one million rows will fail"

https://docs.microsoft.com/en-us/power-bi/service-dataset-modes-understand

**Comment by mihart** [comment]
Hi @stunugun , thank you for clarifying.  I've assigned this issue to the author of that article.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the referenced article or related articles.
