### ISSUE TITLE
Budgets table error

### ISSUE THREAD

**Issue by mcollis2** [MicrosoftDocs/powerbi-docs#1621]
When using this cost management data source, there is an error on the Budgets Table:
Expression.Error: The column 'budgetAmount' of the table wasn't found.
Details:
    budgetAmount
This prevents automatic refresh of data even if not using budgets when publishing to power bi workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mcollis2 . This issue has been assigned to the doc author for review.

**Comment by mcollis2** [comment]
This is being tracked here too:
https://community.powerbi.com/t5/Service/Failed-to-update-data-source-credentials-The-column-budgetAmount/td-p/833839
I can't post because of organizational policies.  Its a problem with the loading of the budgets table on the cost management source.

**Comment by tom-ditlev** [comment]
Having the exact same issue, preventing me in using the new "Modern" Connector. Reverting to using the "Legacy" MicrosoftAzureConsumptionInsights.Contents :-(

**Comment by mcollis2** [comment]
I'll have to find the Legacy connector - now the entire connector is broken - none of the tables load at all.

**Comment by wi5nia** [comment]
Still the same issue

**Comment by davidiseminger** [comment]
Thanks for your comment, and sorry you're having trouble. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
