### ISSUE TITLE
Stripe (Beta)

### ISSUE THREAD

**Issue by HashamNiaz** [MicrosoftDocs/powerbi-docs#1623]
Stripe (Beta) is no longer available after Nov 2019 updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources#feedback)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @HashamNiaz . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks - we've removed that.
