### ISSUE TITLE
The database does not correspond to the explanations

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1624]
The comment below was machine-translated

@ChristopheRpp commented on [Fri Nov 15 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/15)

Hello,
The database found on:
https://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx
is no longer the one used in the tutorial.
Same for the database merge.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Prise en main de Power BI Desktop - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Tue Nov 19 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/15#issuecomment-555490782)

Hello, @ChristopheRpp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @CeciAc . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @ChristopheRpp. This issue has been assigned to the doc author for review.

**Comment by ChristopheRpp** [comment]
Any feedback from the author?

**Comment by rritec** [comment]
I Think this issue is resloved, iam seeing right data.

**Comment by davidiseminger** [comment]
Thanks for your comment, we've updated the tutorial to reflect that.
