### ISSUE TITLE
requests have pending changes

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1625]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/issues/7
The comments below were machine-translated

@kum12neon commented 6 days ago
"there are pending changes in requests, ..."
where is the "CANCEL" button ???

----

Later, user added a second comment to clarify:
@kum12neon commented 6 days ago
Hello CeciAc!
I will clarify the situation. The program itself is still quite "raw" and is most confused in the names of the "fields". If you compare, for example, the mechanics of comparing Google Analytics and BI, then here you can spend a lot of time finding the suitable (necessary) fields for my report from Analytics in BI itself. Those. - they vary greatly both in the name itself and in the category (according to the structure of the category tree).

Therefore, when BI asked to “Accept” the changes without the ability to “Undo” them, I had this question - why is there no “rollback” button to the previous state of the set of commands for generating a request to Google Analytics (and to other databases as well)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data#feedback)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @kum12neon and @CeciAc . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @CeciAc . Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
