### ISSUE TITLE
Data lineage view showing old connections not used by the Power Query

### ISSUE THREAD

**Issue by busht** [MicrosoftDocs/powerbi-docs#1626]
Hi,

Do you have any plans to allow the removal of unused data sources from the dataflow that are not referenced in the power query?

During the life cycle of a dataflow it is common for it to be pointed to different sources, ETL logic changed etc. This causes a lot of redundant sources to show up in the data lineage view, making the data lineage look more complex than it actually is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e43c8665-8c3a-3ece-c2cc-593ade6ce37f
* Version Independent ID: 8cffbebb-8e7c-5eae-d9e4-d1789abac390
* Content: [Data lineage (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-data-lineage#feedback)
* Content Source: [powerbi-docs/service-data-lineage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-data-lineage.md)
* Service: **powerbi**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @busht . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @busht , Thanks for your question. I have forwarded it along to the product manager who I hope will be able to provide an answer to your question. He is out for a few days but I'll get back to you as soon as I hear from him.
@yaroncan

**Comment by paulinbar** [comment]
Hi @busht, I checked with the development team and they said that your issue is indeed a problem and that they are aware of it. It is in their plans to address, but due to the complex nature of the problem they can't say exactly when it will be resolved. Probably not the answer you wanted to hear but that's the story at present. In any event thanks for taking the trouble to report your experience with the issue.

**Comment by gavira** [comment]
Hi, this is still an issue as of September 2022. Is there anything new on this matter?

**Comment by JamesDBartlett3** [comment]
This is still an issue as of January 2024. Any updates on when this will be addressed?

**Comment by paulinbar** [comment]
Hi @JamesDBartlett3, I am checking. I'll let you know soon when I hear back.

**Comment by JamesDBartlett3** [comment]
There is [a workaround](https://community.fabric.microsoft.com/t5/Service/Obsolete-data-sources-in-dataflow-lineage/m-p/3002006/highlight/true#M184506), but it requires manually editing every affected dataflow.

**Comment by paulinbar** [comment]
Hi @JamesDBartlett3, thanks for the info. I talked to the lineage people and they indeed said that there is a dependency on datamarts, and as far as they know that team is not planning to fix the issue. I will try to contact the datamart people directly to check whether this is still true. Probably not the answer you wanted to hear... anyway, I get back to you.

**Comment by JamesDBartlett3** [comment]
> I talked to the lineage people and they indeed said that **_there is a dependency on datamarts_**, and as far as they know that team is not planning to fix the issue.

@paulinbar, does this mean that Dataflows have a dependency on code that is part of Datamarts, or the other way around?
