### ISSUE TITLE
The data isn't all there

### ISSUE THREAD

**Issue by rebecca-aaas** [MicrosoftDocs/powerbi-docs#1627]
On the website link provided, most of the information is not there to load.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Getting started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @rebecca-aaas . I've assigned your issue to the doc author for review. In the meantime, can you tell us specifically which website link you are referring to that page? Thanks.

**Comment by rebecca-aaas** [comment]
https://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx

**Comment by davidiseminger** [comment]
We've updated the doc to reflect changes in that table. Sorry for the inconvenience.
