### ISSUE TITLE
Template App - Parameter as list

### ISSUE THREAD

**Issue by dfehrer** [MicrosoftDocs/powerbi-docs#1629]
We are developing a template app and would like users to enter a parameter by choosing from a dropdown list. This works in the Destkop version but not once we publish the template app. Is this feature supported in the in the template apps?

**Comment by paulinbar** [comment]
Thanks for reaching out to us with your question @dfehrer . Let me start checking this out and I'll get back to you.

**Comment by paulinbar** [comment]
Hi @dfehrer .  I checked with the template app people, and they said that the drop down like you mentioned is not currently supported in template apps, but that it is on their backlog of things to do. They are just not certain when they will be able to do it. Probably not what you wanted to hear but that's the story at this point. Thanks for asking though!
