### ISSUE TITLE
On Premise Data Gateway will not connect to DB with a period in the name

### ISSUE THREAD

**Issue by markrullo** [MicrosoftDocs/powerbi-docs#163]
I'm trying to connect to a DB, let's call it [foo.fighters] with the On Premise Data Gateway. Unfortunately I get this error:

Activity ID: | a01883d5-e2b7-e90b-3594-b4d55e528e64
-- | --
Request ID: | a9265323-0aa1-8cc7-852d-53a0ff21eb1c
Cluster URI: | https://wabi-canada-central-redirect.analysis.windows.net
Status code: | 400
Error Code: | DMTS_PublishDatasourceToClusterErrorCode
Time: | Tue Aug 14 2018 09:34:13 GMT-0400 (Eastern Daylight Time)
Version: | 13.0.6289.161

I'm certain it's not permissions related because when I change the Database name to another on that same server with the same level of permissions, it works.

Thoughts?

**Comment by mgblythe** [comment]
@markrullo -- did you get any more error info than what's listed above? Have you looked at the gateway troubleshooting topic: https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot?

**Comment by arthiriyer** [comment]
@markrullo -  I can connect with the gateway(September 2018 release) to a database having a period. It could have been a bug in previous versions(the version you have in the snip seems very old) but when you update to the latest one, you don't see this happening.
@mgblythe - FYI

**Comment by mgblythe** [comment]
@markrullo - closing this one out, please reopen if necessary.
