### ISSUE TITLE
How do I link from a different column?

### ISSUE THREAD

**Issue by kjetilhamre** [MicrosoftDocs/powerbi-docs#1630]
In the previous example step 6, I would like to link from the City column directly instead of having a special column with only a link icon. Click paris and open info on paris. Click edition and open info on edition. Surely, this must be possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#feedback)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Thanks for your comment, @kjetilhamre . I've assigned your question to the doc author for review.
@maggiesMSFT

**Comment by raghav1107** [comment]
I am also looking on how to link the url from the other column. Can you please let me know on this ?

**Comment by maggiesMSFT** [comment]
Hi, @kjetilhamre and @raghav1107 -- currently no, that's not possible. Please go to Power BI Ideas, https://ideas.powerbi.com/forums/265200-power-bi. If someone else has suggested it, you can vote it up. If not, be the first!
