### ISSUE TITLE
How incremental refresh is affected when re-publishing the dataset?

### ISSUE THREAD

**Issue by ruanonline** [MicrosoftDocs/powerbi-docs#1631]
I would like to see some explicit information about the impact (or non impact) of re-publishing of dataset that has incremental refresh active. Are there any limitations? How are the changes in the dataset managed? Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @ruanonline -- thanks for your question! Assigning to the author to follow up.

**Comment by antmon99** [comment]
I would like to see some clarification around re-publishing a dataset that has incremental refresh set.  It seems that if you make a change and re-publish then it will need another full refresh on the server which is not ideal
Would be good to have options similar to SSAS to Publish FULL or just PROCESS

**Comment by hnjames9** [comment]
This is incredibly annoying and our biggest pain point - we cannot use incremental and iteratively deliver new functionality within that data model to our business without publishing over the dataset with the subset of data and then manually kicking off full refresh again.  The functionality is ONLY usable and scalable for a static dataset now - which is not acceptable for an enterprise adoption.

**Comment by joonassoukki** [comment]
Any plans/workarounds for this problem?

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests. 

Meanwhile, there are many community and support options for you to find answers to your questions. Getting an answer or feedback on your question from the community (https://community.powerbi.com) or from support at https://support.powerbi.com are options. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
