### ISSUE TITLE
Language errors

### ISSUE THREAD

**Issue by Hansonaplane** [MicrosoftDocs/powerbi-docs#1632]
You might want to think about proofreading this article again as there are many errors in the text (like "witch represents" and "DOm elemtns").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d211e63f-7300-55bc-3e19-2e48b11afd7d
* Version Independent ID: fc3890a9-de8b-cda4-8f8c-823663b37a42
* Content: [Power BI visuals interactivity utils - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-interactivity-selections)
* Content Source: [powerbi-docs/developer/visuals/utils-interactivity-selections.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/utils-interactivity-selections.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @zBritva
* Microsoft Alias: **v-ilgali**

**Comment by paulinbar** [comment]
Hi @Hansonaplane , thanks for your comment. I've assigned the article to the author for review.

**Comment by KesemSharabi** [comment]
Hi @Hansonaplane,

Thanks for pointing out that this article needs proofreading.

I'm looking into updating the entire Power BI visuals doc set, and will update and refresh this article as part of this effort.

Please revisit this article in a few months time. Hopefully by then it will have been updated.
