### ISSUE TITLE
Missing import statement in the Custom Power BI Visual tutorial

### ISSUE THREAD

**Issue by peterbud** [MicrosoftDocs/powerbi-docs#1633]
At Step 9 there is a new method added to populate formatting options:
```
public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstanceEnumeration {
    const settings: VisualSettings = this.visualSettings || <VisualSettings>VisualSettings.getDefault();
    return VisualSettings.enumerateObjectInstances(settings, options);
}
```
In order to make this step work, you need to add previously this import:
`import VisualObjectInstanceEnumeration = powerbi.VisualObjectInstanceEnumeration;`

And in fact I believe the below import needs to be added: this is added by default by `pbviz`, but at the previous tutorial page some people can have the impression that it is not needed and can remove (as I did for the first time) - so to be on the safe side I'd add here a comment to make sure this import is also there:
`import EnumerateVisualObjectInstancesOptions = powerbi.EnumerateVisualObjectInstancesOptions;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks @peterbud for your comment on the tutorial. I have passed your observation on to the author for review.
@KesemSharabi

**Comment by KesemSharabi** [comment]
Thanks for your observation @peterbud. I added the two imports to **step 8** in the [Adding custom formatting options](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#adding-custom-formatting-options) section, in the [Tutorial: Adding formatting options to a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options).
