### ISSUE TITLE
Packaging visual requires additional data

### ISSUE THREAD

**Issue by peterbud** [MicrosoftDocs/powerbi-docs#1634]
` pbiviz package`  now requires author name, author email and supportURL as a bare minimum, otherwise throws an error. Would be nice to add these to the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi again, @peterbud. Have also passed this comment on to the author for consideration. Thanks for bringing these issues to our attention!

@KesemSharabi

**Comment by KesemSharabi** [comment]
Thanks for your observation @peterbud. I added the following to the [Packaging the custom visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#packaging-the-custom-visual) section in the [Tutorial: Adding formatting options to a Power BI visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options):
* Author object (name and email) - step 6
* SupportURL - step 5
