### ISSUE TITLE
Viewer role

### ISSUE THREAD

**Issue by saiprasadb365** [MicrosoftDocs/powerbi-docs#1635]
"All of these capabilities except the last require a Power BI Pro license." is misleading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @saiprasadb365 -- thanks for pointing that out! I see what you mean. I'll work on rephrasing it.

**Comment by maggiesMSFT** [comment]
OK, I reworded it. Should be live later today. Let me know what you think!

**Comment by saiprasadb365** [comment]
Thanks, yet Can you remove the statement "All of these capabilities, except viewing and interacting, require a Power BI Pro license." as this statement still doesn't convey the Power BI Premium capacity and the text following the table gives enough details Power BI Premium capacity and Pro license access
