### ISSUE TITLE
Unable to get data for tutoriel "Introduction to modeling your data"

### ISSUE THREAD

**Issue by Jaggana** [MicrosoftDocs/powerbi-docs#1636]
Hello,

In this tutoriel https://docs.microsoft.com/en-us/learn/modules/model-data-power-bi/1-overview-power-bi the first video says "I'm using the datas I've used before", and there's really no clue about where to find those datas.
Could you help me ?

**Comment by Jaggana** [comment]
It looks like the source is coming from an Access Database than can be found here : https://github.com/MicrosoftLearning/Analyzing-Visualizing-Data-PowerBI/tree/master/Lab1

**Comment by maggiesMSFT** [comment]
Hi, @Jaggana -- thanks for asking! I've assigned your question to the author to follow up.

**Comment by heyrob** [comment]
@Jaggana, I added correct link to sample Access db for this module. Thank you.

**Comment by heyrob** [comment]
Just merged to Master.
#please-close @kfollis

**Comment by maggiesMSFT** [comment]
Thanks, @heyrob !
