### ISSUE TITLE
This guide is brilliant!

### ISSUE THREAD

**Issue by Mholsen** [MicrosoftDocs/powerbi-docs#1637]
Clear and concise - I hope this guide can serve as best practice for other Power BI related guides!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf55ca48-9d24-4a87-0f90-b660d3d0ca50
* Version Independent ID: 09e9b1e9-82b6-3efd-7b77-040c284b917b
* Content: [Use shared datasets in Power BI Paginated Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-shared-datasets)
* Content Source: [powerbi-docs/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @Mholsen . Your feedback has been passed along to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks so much, @Mholsen! Glad it helped. I have to say it's one of my favorites, too.
