### ISSUE TITLE
Dashboard subscription sending to only some of the individuals listed

### ISSUE THREAD

**Issue by mtiano802** [MicrosoftDocs/powerbi-docs#1638]
I have a dashboard programmed to send a daily refresh at 9:30am. Everything computes correctly in the data, but only me and one other person subscribed actually receive the email. If I click "Run Now", all people receive it correctly. 
Not sure why everyone isn't receiving the email daily?

**Comment by mihart** [comment]
Thanks for your comment, @mtiano802 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
