### ISSUE TITLE
Shouldn't be dataflow a category as well?

### ISSUE THREAD

**Issue by klabir** [MicrosoftDocs/powerbi-docs#1639]
We miss Power BI Dataflows as an additional category, its different from Desktop and Service as far as I know

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @klabir . This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
Thanks @klabir, dataflows info is on this page right now: https://docs.microsoft.com/power-bi/service-dataflows-data-sources, but assigning to @mohaali to see about adding a column to the table.

@kfollis, @cpopell as FYI

**Comment by kfollis** [comment]
@klabir - Thank you for submitting feedback on our documentation. This article has been updated and now includes a dataflow column.
