### ISSUE TITLE
Compartilhar um relatório para pessoas fora da organização

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerbi-docs#164]
@marcelosalata commented on [Mon Jul 23 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/2)

A documentação não informou o que e como parametrizar o PowerBi para permitir o compartilhamento com pessoas fora da organização. Somente informa o que estas pessoas podem ou não podem ver.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Compartilhe os painéis e os relatórios do Power BI com colegas e outras pessoas - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-share-dashboards#share-a-dashboard-or-report-with-people-outside-your-organization)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@LisandroSu commented on [Wed Aug 01 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/2#issuecomment-409731529)

Olá, @marcelosalata , 

Agradecemos seus comentários. 

Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by LisandroSu** [comment]
Hi team,

Can you help the user with their issue?

Rough translation: _The documentation did not tell you what and how to parameterize PowerBi to allow sharing with people outside the organization. It only tells what these people can or can not see._

Thanks!

**Comment by maggiesMSFT** [comment]
Hi @LisandroSu -- could you collect more information? I'm unclear what the customer is trying to do. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @LisandroSu -- not hearing a reply, I'm going to close this issue. Please feel free to open later when you have more info. Thanks!
