### ISSUE TITLE
"Python Scripting" is not available on the Options page

### ISSUE THREAD

**Issue by tomanizer** [MicrosoftDocs/powerbi-docs#1643]
The Options page only shows "R scripting", no "Python scripting".
Is there a certain version required for Python integration. If yes, the article should mention the Power BI Desktop versions which support Python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by maggiesMSFT** [comment]
Hi, @tomanizer -- Thanks for your comment! Assigning to the author to assess.

**Comment by otarb** [comment]
Feature is available since August 2018

Blog regarding the release and all feature included
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2018-feature-summary/

**Comment by otarb** [comment]
Feature is available since August 2018

Blog regarding the release and feature summary
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2018-feature-summary/

**Comment by maggiesMSFT** [comment]
Thanks, @otarb . 
@tomanizer can you try installing a newer version of Power BI Desktop? 
https://docs.microsoft.com/power-bi/desktop-get-the-desktop
