### ISSUE TITLE
Google Analytics Connector Please update for New API Release

### ISSUE THREAD

**Issue by jenyart** [MicrosoftDocs/powerbi-docs#1645]
Looks like there has been an update to the Google Analytics API to now include Lifetime Value and Cohort Analysis metrics in late November 2019. Could you check into updating the power bi connector to reflect this.

**Comment by maggiesMSFT** [comment]
Hi, @jenyart -- this looks like a question best addressed by the product team, not the docs team. Can you submit your idea/request at the Power BI Ideas site, https://ideas.powerbi.com/forums/265200-power-bi? 
Thanks and here's hoping!
