### ISSUE TITLE
Dataflow owner

### ISSUE THREAD

**Issue by saiprasadb365** [MicrosoftDocs/powerbi-docs#1647]
This statement is wrong "Each dataflow created in Power BI is stored in its own CDM folder, and the owner of the dataflow is granted read-only access to the CDM folder and its contents" ... instead it should be "Each dataflow created in Power BI is stored in its own CDM folder, and only the owner of the dataflow is granted write access to the CDM folder and its contents"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Dataflows and Azure Data Lake integration - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-azure-data-lake-integration#feedback)
* Content Source: [powerbi-docs/service-dataflows-azure-data-lake-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-azure-data-lake-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for this observation, @saiprasadb365. I have assigned this issue to the author of the article for review.

**Comment by davidiseminger** [comment]
We've updated that article, thanks for posting.
