### ISSUE TITLE
Power BI Optimized for Report Server version 2.51.4885.3981 (October 2017)

### ISSUE THREAD

**Issue by liudaburtseva** [MicrosoftDocs/powerbi-docs#1649]
Hello everyone!

My organization works with Power BI Report Server, version from October 2017.

And to have access to my corporate server I need Power BI Desktop Optimized for Report Server, version 2.51.4885.3981 (October 2017). I know that this version is out of support, however I still need it. 

Maybe someone still has this installation and can share with me. I will be very grateful for Your help! 

Many thanks in advance!

**Comment by paulinbar** [comment]
Hi @liudaburtseva ! Have you tried the [Power BI Community]( https://community.powerbi.com)? I see that there is some correspondence about previous versions there, although I don't have direct experience with that. In the meantime I am forwarding your question on to someone who may have some knowledge about the availability of previous Power BI versions.

**Comment by liudaburtseva** [comment]
Hi @paulinbar ! Yes, I have tried not only Power BI Community. All my searching ended up with Power BI for RS version from August 2018. And now I'm trying to find any possible information on different forums.

**Comment by davidiseminger** [comment]
Thanks for your comment, and sorry about the trouble you're having. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
