### ISSUE TITLE
RSS feed for the change log page ?

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/powerbi-docs#165]
It would be a charm to have an RSS feed for all the change log pages, so one gets automatically notified if new changes appear ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Changelog for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog#feedback)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* GitHub Login: @jtarquino
* Microsoft Alias: **jtarquino**

**Comment by jtarquino** [comment]
Thanks for the feedback I would like to invite you to post it in ideas.powerbi.com
