### ISSUE TITLE
WCAG Principles are POUR. Why leave off robust?

### ISSUE THREAD

**Issue by mlongoria** [MicrosoftDocs/powerbi-docs#1651]
https://www.w3.org/WAI/WCAG21/Understanding/intro#understanding-the-four-principles-of-accessibility

There are 4 accessibility principles. We commonly pronounce the acronym as the word it spells (pour). Although users can't affect the conformance of the robustness as it mostly pertains to tags and assistive technologies, it would be good to list it and maybe explain how Power BI is designed to meet it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a040fd91-bc39-f1f7-b5bf-1a2964e7067e
* Version Independent ID: 1dd198ca-08a2-022b-a186-70f355882821
* Content: [Overview of accessibility in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-accessibility-overview)
* Content Source: [powerbi-docs/desktop-accessibility-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-accessibility-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who will consult with the engineering team and will respond shortly. Thanks!

**Comment by davidiseminger** [comment]
Thank you for your feedback, and your clarification about accessibility and those accessibility principles. We've put this doc request into our queue, and will review it with other documentation requests.
