### ISSUE TITLE
Decomposition tree visual

### ISSUE THREAD

**Issue by ndcorchuelo** [MicrosoftDocs/powerbi-docs#1652]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by lubma** [comment]
The visual does not include a scrollbar an the left had side if Explain By: 'some category' has too many values to fit on page.

**Comment by davidiseminger** [comment]
Thanks for your comment, @lubma. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by juluczni** [comment]
Hi lubma, you can pan and zoom the visual to move it around (just like a map visual). So click into the visual and drag it around to move it.

**Comment by lubma** [comment]
Hi juluczni, thank you for pointing that out. It is really useful when adjusting the visual but I found that when you zoom out to fit all the values in the column it becomes hard to see what value you want to drill down into or see the relationship of the lower values in regards to the higher ones.  It becomes an issue when you are making a report for a customer who isn't familiar with pbi capabilities and simply wants to see all the represented data on a report. My tree is already taking up the standard page size and zoomed to a reasonable reading text size but a lot of that data is still trailing off.

**Comment by ftorresv** [comment]
Hi lubma, I can't find the viz at the marketplace...

**Comment by lubma** [comment]
@ftorresv open pbi go to file -> options and settings -> options -> preview visual -> select decomposition tree(preview) and restart pbi, it should now be in the visual pane. if it is still not there try updating pbi and following the same steps or searching the marketplace.

**Comment by lubma** [comment]
correction, preview features not preview visual

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
