### ISSUE TITLE
Unable to Locate Stripe

### ISSUE THREAD

**Issue by kylebamfordpc** [MicrosoftDocs/powerbi-docs#1653]
Stripe is listed as a data source on this page, but in both Power BI Desktop and Power BI web, I'm unable to locate Stripe as a "Get Data" option. Is there any way to confirm Stripe is actually still a supported data source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @kylebamfordpc . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mattmasson** [comment]
The Stripe connector was deprecated in the November release of Power BI Desktop. It no longer appears in the Get Data dialog. The underlying functions are still available (as of 12/4/2019), so existing reports will continue to work, but these may be removed in the future. We've invited the Stripe team to submit a new connector through the Certified Connector program, but have not received a response at this time.

**Comment by kylebamfordpc** [comment]
Thanks for following up!
