### ISSUE TITLE
Quickbooks template Issue

### ISSUE THREAD

**Issue by conorodocr** [MicrosoftDocs/powerbi-docs#1655]
Hi,

For some reason the accounts in the Quickbooks template is missing the subtype "Other Business Expenses".

Any idea why and how to fix?

Thanks,

**Comment by conorodocr** [comment]
Also - am I able to show Profit & Loss by Class?

**Comment by davidiseminger** [comment]
Thanks for your comment, @conorodocr . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
