### ISSUE TITLE
OData Feed link isn't working as used in the page

### ISSUE THREAD

**Issue by sarat-nakkina** [MicrosoftDocs/powerbi-docs#1656]
Provided web feed - https://services.odata.org/V3/Northwind/Northwind.svc/ only displays collection irrespective of the orders table as mentioned in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0f7e4-74cd-dadb-c2ce-4b6c0c511e20
* Version Independent ID: 0d14b983-c47a-1fa7-7103-15182735f26b
* Content: [Tutorial: Combine data from Excel and an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @sarat-nakkina . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by sarat-nakkina** [comment]
Thanks @davidiseminger, I'm wrong as I was using web feed instead of OData feed. URL mentioned is OData feed and using OData feed in Get Data works perfectly.
