### ISSUE TITLE
Whitepaper link does not work

### ISSUE THREAD

**Issue by JBVerveer** [MicrosoftDocs/powerbi-docs#1657]
The link for  the 'Planning a Power BI Enterprise Deployment' does not work. Is there a way to get this document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e576bbf-5964-ce92-cb3a-3bbc57c6bd61
* Version Independent ID: 9e87a5bd-07d8-20f6-2f50-fa5e4cbb2eb7
* Content: [Whitepapers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepapers#feedback)
* Content Source: [powerbi-docs/whitepapers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepapers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @JBVerveer -- hmmm. I can download and open that whitepaper. Can you try again?
thanks!

**Comment by JBVerveer** [comment]
I am still getting an error. Please check the attachment for the specifics. All the other links work though...
![Capture](https://user-images.githubusercontent.com/58489453/70127297-0e01aa00-167b-11ea-8a87-e6b5af2ed707.PNG)
