### ISSUE TITLE
unable to  "find your fully qualified server name and database name in the Azure portal"

### ISSUE THREAD

**Issue by RonMeyn** [MicrosoftDocs/powerbi-docs#1658]
unfortunately, the Portal admin changes so often; my equivalent of the screenshot does not offer a "server name":..

Instead, I am getting the following list on the RHS...

Version: SQL Server 2017
Edition: Standard
Virtual machine: pharlap-01
Virtual machine OS: Windows (Windows Server 2016 Datacenter)
Virtual machine size: Standard DS3 v2
License type:   Pay As You Go

I've been able to access the data via the machines' IP address (in PowerBI Desktop), but when I publish the dataset says there needs to be a gateway. 

DO I need to install a gateway somewhere in my Azure cloud? it's confusing to me as my servers are not "on Premise" and I would have thought that there was some kind of direct way to establish a connection between my Azure SQL servers and the online PowerBI space? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a51592-74c3-54c1-1c57-fc102648cb2f
* Version Independent ID: efac35dc-4ea4-483c-7b63-412abeaf053c
* Content: [Azure SQL Database with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-sql-database-with-direct-connect#feedback)
* Content Source: [powerbi-docs/service-azure-sql-database-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-sql-database-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by ElectricLlama** [comment]
That isn't Azure SQL Database, it's SQL Server installed in a VM (This is called IaaS). Yes you need to install a gateway on your VM. Yes, your VM is in the cloud, but it isn't the "PaaS" version of SQL Server, it's in the IaaS version. I hope this helps.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
