### ISSUE TITLE
Is this connector open-sourced?

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/powerbi-docs#1659]
There was a previous sample data connector for GitHub [here](https://github.com/microsoft/DataConnectors/tree/master/samples/Github) that looks similar.  

*Is this the successor, and if so is it also open-sourced on GitHub, but somewhere else?*

There's also another [doc](https://docs.microsoft.com/en-us/power-query/samples/github/readme) that went along with that.

Just want to know, as we have this [issue](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/19327633-github-label-and-project-info) which blocks us from using this connector to get the data we need, and it'd be great if we could just look at fixing this existing connector than having to build our own custom one.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @michael-hawker -- adding @teddybercovitz , who should be able to answer your question.
thanks!

**Comment by teddybercovitz** [comment]
Hi, It's the same connector. You could ask for connector changes on the connector github page.

Thanks!

**Comment by michael-hawker** [comment]
@maggiesMSFT & @teddybercovitz should the doc be updated to point to the repo if that's supposed to be the source though?
