### ISSUE TITLE
Is Renaming A Power BI Report Server Supported?

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#166]
It is possible to rename the computer/server hosting SSRS as described here:
https://docs.microsoft.com/en-us/sql/reporting-services/report-server/rename-a-report-server-computer?view=sql-server-2017
Is this supported for the Power BI Report Server as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13389638-3e8a-5a77-d078-54b60abd54f8
* Version Independent ID: 0def82a7-b474-4eac-2196-a992b480730b
* Content: [Admin overview, Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/admin-handbook-overview)
* Content Source: [powerbi-docs/report-server/admin-handbook-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/admin-handbook-overview.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks @cbailiss, assigning to @markingmyname to fix. He is on vacation but will address when he returns.

**Comment by markingmyname** [comment]
Thanks for your comment, @cbailiss. Sounds like this is a product question, so please use the Product Feedback button in this article, or try the community, https://community.powerbi.com/.

Thank you.

**Comment by cbailiss** [comment]
Thanks for the reply, however, I disagree.  
Product feedback relates to requests for changes/enhancements.  
I am asking about whether a specific type of configuration change is supported - i.e. is renaming the computer running Power BI Report Server supported?
If the answer is no, then I will be happy to add a request to the Product Feedback area.  
I chose to raise the question against this page, since this page in the documentation (Admin/Configuration) would presumably be where this information would/should be documented.
Installation, Migration, etc is documented on this page (with links to the relevant section in the SSRS docs).
If would be great if this page could be expanded to either state that renaming is not supported currently, or to state that renaming is supported - and then link to the SSRS page from my original question, if this is correct still for the Power BI Report Server.
Thanks.
