### ISSUE TITLE
The funnel does not make any sense!

### ISSUE THREAD

**Issue by JohnJiang-Australia** [MicrosoftDocs/powerbi-docs#1660]
The status would change every month. let's take Feb for example. 

All new leads came in Feb may turn into proposal in Feb, Mar, Apr and so on so forth. When you look at funnel, you would want to know all leads came in Feb and what's the status now to understand the conversion rate. 

The status in this chart would represent current status of the item. Just because it says it is in proposal status does not mean it came in as a proposal , it comes in as a lead as always! 
![image](https://user-images.githubusercontent.com/39290373/70118869-2d212b80-16bd-11ea-82e6-71c29fca7217.png)

This item has only one status in the dataset so it is definitely missing from lead calculation in the funnel! It does not work that way in a real world example. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14fa9def-43a2-7673-c891-3cd9df9e3d18
* Version Independent ID: f54b6ef4-eebd-3b31-2261-881166045dc2
* Content: [Funnel charts - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-funnel-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-funnel-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-funnel-charts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JohnJiang-Australia.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @JohnJiang-Australia JohnJiang,
I've added this task to my backlog.  I'll update this Git Issue after I've published the updated funnel article.  Thank you for your feedback.
@mihart

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
