### ISSUE TITLE
Workspace Access

### ISSUE THREAD

**Issue by schwinnen** [MicrosoftDocs/powerbi-docs#1662]
I assigned a Viewer role to a Microsoft 365 user group in a premium workspace.  I tested this out a couple of weeks ago and it worked fine.  Now users are getting prompted to sign up for Power BI Pro.  Has something changed in the past couple of weeks?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @schwinnen , thanks for reaching out to us with your question. On the face of it it looks like the case you describe should be ok according to the table on that page. I'm forwarding your question to the page author - she may be able to shed some light or point you in the right direction.

**Comment by maggiesMSFT** [comment]
Hi, @schwinnen -- thanks for asking! Question: when you say it "worked fine" -- with a Viewer role, they should be able to view and interact with reports in the Premium workspace. You're saying they can't do that? If so, that sounds like you might need to contact support, https://powerbi.microsoft.com/en-us/support/.
Hope that helps!

**Comment by schwinnen** [comment]
@maggiesMSFT - I am in contact with support, but nothing has been resolved yet.  To answer your question - I have assigned Viewer access to a distribution group within my premium workspaces.  Users within this distribution group cannot access the reports in these premium workspaces.  They are being prompted to sign up for Power BI Pro or to start a Power BI Pro trial.  Based on your documentation, this is not the behavior I should be getting.  Can you confirm this?  Or, is there something else I need to do to make sure the users have access?
