### ISSUE TITLE
Visuals Gridlines Formatting

### ISSUE THREAD

**Issue by lhanna-wmp** [MicrosoftDocs/powerbi-docs#1663]
It seems that formatting for the gridelines is not working. I have the below code within my otherwise working JSON file, but no formatting is applied upon import.

{
  "name": "Custom",
  "dataColors": [ "#2372B9", "#81CFE7", "#F15323", "#F99B2F", "#008D48", "#B9C53A", "#595959", "#A1ABBB" ],
  "background": "#595959",
  "foreground": "#FFFFFF",
  "textClasses": {
    "callout": {
      "fontFace": "Segoe UI"
    },
    "title": {
      "fontFace": "Segoe UI"
    },
    "header": {
      "fontFace": "Segoe UI"
    },
    "label": {
      "fontFace": "Segoe UI"
    }
  },
  "visualStyles": {
    "*": {
      "*": {
        "title": [
          {
            "show": true,
            "fontColor": { "solid": { "color": "#666666" } },
            "background": { "solid": { "color": "#FFFFFF" } },
            "fontSize": 11,
            "alignment": "center"
          }
        ],
        "legend": [
          {
            "show": true,
            "fontColor": { "solid": { "color": "#666666" } },
            "fontSize": 8,
            "position": "Top"
          }
        ],
        "columnHeaders": [
          {
            "fontColor": { "solid": { "color": "#FFFFFF" } },
            "backColor": { "solid": { "color": "#2372B9" } },
            "fontSize": "10"
          }
        ],
        "values": [
          {
            "backColorPrimary": { "solid": { "color": "#FFFFFF" } },
            "backColorSecondary": { "solid": { "color": "#FFFFFF" } },
            "fontColorPrimary": { "solid": { "color": "#666666" } },
            "fontColorSecondary": { "solid": { "color": "#666666" } },
            "fontSize": 8,
            "fontFamily": "Segoe UI Light"
          }
        ],
        "valueAxis": [
          {
            "gridlinesShow": true,
            "gridlinesStyle": "dotted",
            "labelColor": { "solid": { "color": "#666666" } }
          }
        ]
      }
    },
    "slicer": {
      "*": {
        "background": [
          {
            "show": false
          }
        ],
        "selection": [
          {
            "selectAllCheckboxEnabled": true
          }
        ],
        "items": [
          {
            "fontColor": { "solid": { "color": "#666666" } },
            "background": { "solid": { "color": "#FFFFFF" } },
            "textSize": 9,
            "fontFamily": "Segoe UI Light"
          }
        ],
        "header": [
          {
            "show": true,
            "fontColor": { "solid": { "color": "#FFFFFF" } },
            "background": { "solid": { "color": "#2372B9" } },
            "textSize": 10,
            "fontFamily": "Segoe UI"
          }
        ],
        "border": [
          {
            "show": false
          }
        ]
      }
    }
  }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @lhanna-wmp , thanks for reaching out to us. This sounds like it is probably a product rather than a documentation issue, but I am assigning your comment to the author of the article you mentioned. He may be able to point you in the right direction.

**Comment by davidiseminger** [comment]
Thanks for your comment - this does look like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
