### ISSUE TITLE
Changing Live connected data set in Onedrive refresh scenario is not supported

### ISSUE THREAD

**Issue by saigrsundaram** [MicrosoftDocs/powerbi-docs#1664]
Currently, Changing Live connected data sets in Onedrive refresh scenario is not supported as per Power BI engineering team. I request you to include this information in the "What's supported" section in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset from OneDrive or SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-desktop-file-onedrive#feedback)
* Content Source: [powerbi-docs/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @saigrsundaram . Thanks for your comment. I am forwarding it along to the author of the page you mentioned.

**Comment by davidiseminger** [comment]
Added a note under "What's Supported" to clarify live connections are not supported for refrehsh.

**Comment by saigrsundaram** [comment]
Hello David,
The information added to the article is not correct. We do support refreshing information from a PBIX published to the service using OneDrive. What we don’t support is changing the dataset in a live connected dataset scenario is not supported.
The following is what it should read:
“Changing Live connected data set in Onedrive refresh scenario is not supported”

R.B.Ganesh
Sr. Support Escalation Engineer | Support Engineering - Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
•(980) 776-7308; • ganeshbg@microsoft.com<mailto:ganeshbg@microsoft.com>; Working hours:  Mon - Fri 8 am EST to 4 pm EST

If you have any feedback about my work, please contact either me or my manager Sean Marvin at •(980) 776-7574 |  jsmarvin@microsoft.com<mailto:jsmarvin@microsoft.com>

**Comment by saigrsundaram** [comment]
Hello David,
I have been trying to get your attention on this documentation update since Friday last week. As stated in my email below, The information added to the article is not correct. We do support refreshing information from a PBIX published to the service using OneDrive. What we don’t support is changing the dataset in a live connected dataset scenario is not supported.
The following is what it should read:
“Changing Live connected data set in Onedrive refresh scenario is not supported”

How can we get this corrected?

R.B.Ganesh
Sr. Support Escalation Engineer | Support Engineering - Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
•(980) 776-7308; • ganeshbg@microsoft.com<mailto:ganeshbg@microsoft.com>; Working hours:  Mon - Fri 8 am EST to 4 pm EST

If you have any feedback about my work, please contact either me or my manager Sean Marvin at •(980) 776-7574 |  jsmarvin@microsoft.com<mailto:jsmarvin@microsoft.com>


From: Ganesh R Babugnanasundaram
Sent: Friday, January 10, 2020 8:12 AM
To: MicrosoftDocs/powerbi-docs <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>; David Iseminger <davidi@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Changing Live connected data set in Onedrive refresh scenario is not supported (#1664)
Importance: High

Hello David,
The information added to the article is not correct. We do support refreshing information from a PBIX published to the service using OneDrive. What we don’t support is changing the dataset in a live connected dataset scenario is not supported.
The following is what it should read:
“Changing Live connected data set in Onedrive refresh scenario is not supported”

R.B.Ganesh
Sr. Support Escalation Engineer | Support Engineering - Cloud & Infrastructure Solutions
Customer Services & Support | Microsoft Corporation
•(980) 776-7308; • ganeshbg@microsoft.com<mailto:ganeshbg@microsoft.com>; Working hours:  Mon - Fri 8 am EST to 4 pm EST

If you have any feedback about my work, please contact either me or my manager Sean Marvin at •(980) 776-7574 |  jsmarvin@microsoft.com<mailto:jsmarvin@microsoft.com>
