### ISSUE TITLE
Why isnt' this topic available in the table of contents?

### ISSUE THREAD

**Issue by JimDaly** [MicrosoftDocs/powerbi-docs#1665]
seems like an  orphan page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Troubleshooting Sign-in issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-sign-in#how-to-collect-a-trace-in-power-bi-desktop)
* Content Source: [powerbi-docs/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @JimDaly , 
Thanks for your observation. I am forwarding it along the author of article you mentioned for review.

**Comment by davidiseminger** [comment]
It certainly should be! Fixed that, it'll show up in the Resources section. Thanks for pointing that out.
