### ISSUE TITLE
Main page isn't getting updated when child page is updated

### ISSUE THREAD

**Issue by matt40k** [MicrosoftDocs/powerbi-docs#1667]
Looking at https://docs.microsoft.com/en-us/power-bi/service-admin-rls

It hasn't been updated with https://github.com/MicrosoftDocs/powerbi-docs/pull/1650

Looking at the page: https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md

it uses:

[!INCLUDE include-short-name]

The fact the child page has been updated doesn't appear to force the parent to be regenerated.

**Comment by maggiesMSFT** [comment]
Hi, @matt40k -- I checked the INCLUDE file; I don't know why, but it didn't show your update. So I updated the INCLUDE file again and just for good measure I forced a rebuild of the 2 files that show the INCLUDE. You should see your update later today.
Thanks!
