### ISSUE TITLE
Needs updated to Reflect new User Experience

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#1668]
Needs updated to Reflect new User Experience. For example, where you get the Embed URL has moved under the ... in the top bar and is no long Black

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by maggiesMSFT** [comment]
Hi, @pcgeekus -- So true! Good catch. I'll add it to my work items and get to it soon. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @pcgeekus -- updated it now. Change will go live this afternoon. Thanks!

**Comment by pcgeekus** [comment]
Thanks,
Jon
