### ISSUE TITLE
Error when using Enterprise ID: The field 'org_companies' of the record wasn't found.

### ISSUE THREAD

**Issue by Tiberriver256** [MicrosoftDocs/powerbi-docs#1669]
I get the following error when I log in with an Enterprise ID and click on the Connect button:

We encountered an error while trying to connect:
Details: "The field 'org_companies' of the record wasn't found."

Is there some pre-requisite task I need to complete for the connector to work properly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b88aa9e-5500-8904-286c-4a6d22be2e9f
* Version Independent ID: b0faa18f-b2ca-4c95-3486-7227cfb31277
* Content: [Connect to Adobe Analytics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-adobe-analytics)
* Content Source: [powerbi-docs/desktop-connect-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-adobe-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Tiberriver256. Let us look into this issue, and we'll respond to this thread shortly. Thanks!

**Comment by Tiberriver256** [comment]
Thank you!

**Comment by Tiberriver256** [comment]
Any update @davidiseminger?

**Comment by Tiberriver256** [comment]
Found a bit more detailed error by using the advanced editor that might provide a clue.

![image](https://user-images.githubusercontent.com/6989492/71186754-c0c13300-224b-11ea-8943-7a2d8d151cb7.png)

Looks like Adobe may have renamed a field in their authorization token from **org_companies** to **login_companies**?

**Comment by fpro123** [comment]
We are facing the same issue. However, we sign in with Adobe ID. Any news @davidiseminger ?

**Comment by RealEggboy** [comment]
@davidiseminger is the issue that this article states you need to connect via an Adobe ID and not an Enterprise ID? Which is an issue as the general practice and the recommended user type is Enterprise ID. Thanks!

**Comment by Tiberriver256** [comment]
@RealEggboy - The problem isn't the documentation. It is a bug within PowerBI, as described above you get an error when attempting to log in. I have the error when using an Enterprise ID fpro123 has the error with an Adobe ID. So it appears the connector may need some update before it works with Adobe.

**Comment by RealEggboy** [comment]
@Tiberriver256 Thanks...I was about to do the connection, and saw the documentation requires and Adobe ID instead of an Enterprise ID. From my end, I will take this up with our Adobe and Microsoft success managers...if I have an update I will post here too. Thanks so much!

**Comment by Tiberriver256** [comment]
Just wanted to post an update it looks like there may have been an update pushed to the Windows Store version of PowerBI that resolves the above issue. At least it is working for me now.

**Comment by fpro123** [comment]
@Tiberriver256 I could not find the update on Windows Store. My current version is Version: 2.76.5678.782 64-bit (december 2019). 
Did you log on with Enterprise ID or Adobe ID.

**Comment by Tiberriver256** [comment]
I've got the same version 2.76.5678.782 64-bit (december 2019). I did have to clear my connection settings on my second pc to get it to work. I am using an Enterprise ID.

### Clearing connection settings

File -> Options and Settings -> Data Source Settings -> Clear any permissions related to Adobe Analytics

It should prompt you to log in again next time you try to get data

**Comment by davidiseminger** [comment]
Great discussion all, and thanks for sharing the issue, the root problem, and the solution. Much appreciated!

**Comment by fpro123** [comment]
It still doesn’t work for us. We use Adobe ID, as described in the documentation. Only Entreprise ID seems to work according to the discussion, opposite of documentation. We did multiple times clear the connection permission.

**Comment by photolipps** [comment]
Did anyone make any progress on this issue?  I'm having the exact same problems on Version: 2.84.802.0 64-bit (August 2020).  Thanks!
