### ISSUE TITLE
Error while trying to connect ClickDimensions in Power BI

### ISSUE THREAD

**Issue by kvijay7** [MicrosoftDocs/powerbi-docs#167]
We couldn't install ClickDimensions
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
MessageOData: Request failed: The remote server returned an error: (500) Internal Server Error. (An error has occurred.) Table: Visit.
Activity ID6c5bd6e9-2a7a-4763-a2f9-ec279abfcf8d
Correlation IDb5f166fe-fa6c-2100-9302-edb267d34fab
Request IDf6af59e6-eb78-4c87-b64e-0d4889a79332
Status code400
TimeWed Aug 15 2018 11:42:23 GMT-0400 (Eastern Daylight Time)
Version13.0.6289.161
Cluster URIhttps://wabi-canada-central-redirect.analysis.windows.net

Learn more about solving this issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ee575f7-0994-0a28-e9d7-b4691733e51f
* Version Independent ID: e6ca9f1a-ef79-1e5b-fa3b-8b42a54a0291
* Content: [Connect to ClickDimensions with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-clickdimensions)
* Content Source: [powerbi-docs/service-connect-to-clickdimensions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-clickdimensions.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @kvijay7 -- is this still an issue for you? If so, I recommend contacting support, https://powerbi.microsoft.com/en-us/support/. 
Good luck!
