### ISSUE TITLE
Tooltip Formatting

### ISSUE THREAD

**Issue by RoseyAlexa** [MicrosoftDocs/powerbi-docs#1670]
It would be handy to include details for how to make a tooltip resemble the default tooltips.
Especially as you can seem to Left Justify a card, so the values are always centred.
Is there anyway to access/unzip a standard tooltip, and then edit it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips#feedback)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @RoseyAlexa. There is no way to edit a tooltip, but let us look into your other request and respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Assigning.
