### ISSUE TITLE
Full screen button for Dashboard with New Look On

### ISSUE THREAD

**Issue by alwweb** [MicrosoftDocs/powerbi-docs#1671]
The menus and icons I am seeing do not match the documentation. Also, there does not seem to be a Full Screen Mode icon when viewing a dashboard.  With a report, it is under the View menu, but neither looks like what is in the documentation. 

![image](https://user-images.githubusercontent.com/17628056/70391388-99907900-19a2-11ea-92ac-3c2e1fef35b1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052edfa5-0db0-da15-88c0-7841f4149347
* Version Independent ID: fa7d4f3d-6480-700b-bd67-3edcc464859b
* Content: [Focus mode and full screen mode - how to zoom in to see more detail - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-focus#feedback)
* Content Source: [powerbi-docs/consumer/end-user-focus.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-focus.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @alwweb. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @alwweb ,
I've updated the article to reflect the new screens.  And yes, you are correct re: dashboards.  
Thanks :-)
