### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by abasiko777** [MicrosoftDocs/powerbi-docs#1672]
all works finely

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16b31202-eae5-59aa-3de4-7e1fb897ed4f
* Version Independent ID: 9f595797-0c89-63d1-e8d8-9a67e2cc7e19
* Content: [Tutorial: Create calculated columns in Power BI Desktop - Power BI](https://docs.microsoft.com/en-gb/power-bi/desktop-tutorial-create-calculated-columns#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-create-calculated-columns.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-create-calculated-columns.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great! Glad to hear it, thanks for posting.
