### ISSUE TITLE
RefreshDataset

### ISSUE THREAD

**Issue by Mholsen** [MicrosoftDocs/powerbi-docs#1673]
Does the RefreshDataset activity include both manual and scheduled refreshes of a dataset? 
If so, is there any way to separate the two?
I'm guessing that you might be able to separate the two by looking if the UserAgent column being blank or not (blank would be a scheduled refresh), but it's hard to see based on the sparse information provided on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Use auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Mholsen. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
@Mholsen - thanks for being patient while I checked into this. RefreshDataset doesn't distinguish between manual and scheduled refresh. We recognize that this is something needs to be improved, but don't yet have a timeline for the work.
