### ISSUE TITLE
Some oversights

### ISSUE THREAD

**Issue by wbovela** [MicrosoftDocs/powerbi-docs#1678]
1. IVisualHost import missing
Following the tutorial the "import IVisualHost = powerbi.extensibility.visual.IVisualHost" instruction is missing which leads to breaking errors. The private host member isn't used though.

2. EnumerateVisualObjectInstancesOptions  and VisualObjectInstanceEnumeration imports missing
The following imports are missing in the tutorial, leading to breaking errors.
import EnumerateVisualObjectInstancesOptions = powerbi.EnumerateVisualObjectInstancesOptions;
import VisualObjectInstanceEnumeration = powerbi.VisualObjectInstanceEnumeration;

3. SupportURL missing
When packaging the visual, a support URL must be given.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @wbovela. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Thank you for your comments @wbovela.
*  **IVisualHost** is mentioned in the verification process in **Step 2**, in the [Developing the visual elements](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial#developing-the-visual-elements) section, in the [Tutorial: Developing a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial).
*  I added the **EnumerateVisualObjectInstancesOptions** and **VisualObjectInstanceEnumeration** imports to **step 8** in the section [Adding custom formatting options](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#adding-custom-formatting-options), in the [Tutorial: Adding formatting options to a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options).
* We also added **SupportURL** to **step 5** in the [Packaging the custom visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options#packaging-the-custom-visual) section in the [Tutorial: Adding formatting options to a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options).
