### ISSUE TITLE
Adding tooltips documentation

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#168]
I think it would be useful if we add info that tooltip in the mobile app can be seen with a long-tap on a specific bar\point on the chart

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf174abf-6474-14ae-3183-31e40fa9b1b6
* Version Independent ID: ca82ad59-c057-fccd-b6e0-627df4326c62
* Content: [Explore reports in the Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/mobile-reports-in-the-mobile-apps#drill-through-from-one-page-to-another)
* Content Source: [powerbi-docs/mobile-reports-in-the-mobile-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/mobile-reports-in-the-mobile-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks @chizhova, assigning to @maggiesMSFT to fix. She is on vacation but will address when she returns.

**Comment by maggiesMSFT** [comment]
Hi @chizhova -- yes, good idea! I'll add that to "Explore reports in the Power BI mobile apps - Power BI"
