### ISSUE TITLE
Configuring alerts with more conditions on Threshold - shown in the video 

### ISSUE THREAD

**Issue by ashumedi** [MicrosoftDocs/powerbi-docs#1681]
In the example shown I see sales target and regions, now can I create a alert on target for North America region? Is that functionality supported or any other way that it can be accomplished?

[Data alerts in the Power BI service](https://docs.microsoft.com/en-us/power-bi/service-set-data-alerts)

[Reference Youtube](https://www.youtube.com/watch?v=JbL2-HJ8clE#action=share)

**Comment by paulinbar** [comment]
Hi @ashumedi . Thanks for reaching out to us with your question. You've reached the documentation team, I am not %100 sure of the answer but I think you can only put set alerts on three types of tiles, gauges, KPIs, and cards, as mentioned in the documentation page and the video. I would imagine that you'd have to make a special report and then put in a tile on that that you'd set the alert on. Still, I suggest that you try further on the [Power BI Community]( https://community.powerbi.com) or [support page](https://support.powerbi.com) - there may be someone with specific experience with your case. Thanks and good luck! 
@maggiesMSFT
