### ISSUE TITLE
Azure Mac users.

### ISSUE THREAD

**Issue by tsaru72** [MicrosoftDocs/powerbi-docs#1682]
I recognize that PowerBI desktop doesn't work on Mac. Does the Azure PowerBI give us the same capabilities as the PowerBI Desktop or can I presume that PowerBI is not for Mac users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @tsaru72,

I'm not sure what you mean by 'Azure Power BI'.

[Power BI service ](https://docs.microsoft.com/power-bi/power-bi-service-overview) has many of the Power BI Desktop capabilities such as [creating a report](https://docs.microsoft.com/power-bi/power-bi-service-overview#creating-reports-in-the-service).

I suggest that you [sign up for a free Power BI account](https://docs.microsoft.com/power-bi/service-self-service-signup-for-power-bi) and try it out.

Thanks,

Kesem
