### ISSUE TITLE
Row Level Security Limitation

### ISSUE THREAD

**Issue by MACEL94** [MicrosoftDocs/powerbi-docs#1683]
Hi, 

in section "Working with members" it's not clear if there is a way to bulk add members.
It's tedious to do if they are a lot, especially if you can't(or don't want to) do it by group.

Is there a way to script/bulk add members by username/groups once you have activated RLS?

Thank you for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by MACEL94** [comment]
Hi

is there a chance i will get any answer on this matter?
Or should i close this issue?

Thank you anyway

**Comment by paulinbar** [comment]
Hi @MACEL94 , sorry for not responding earlier. Have you tried creating a comma separated list of email addresses and pasting that into the text field where you are asked to supply names? I tried that and it seemed to work. It also worked if the separator was a semi-colon. Emails for people outside the organization were rejected. It is possible to add them, but they have to be B2B guests. Let me know if you need a reference for that. 
I am going to close this issue now, but please open it again if this isn't what you had in mind.
We are in the process of updating the row level security articles, and I have made a note of your issue, and will put a note in the documentation about being able to enter multiple email addresses. Thanks!
Paul

**Comment by MACEL94** [comment]
Hi, my issue was that it's not clear, if you have an on-premise instance of PBI, how can you bulk add by API/script a lot of emails, I don't want to do it manually from the UI.

Can you please re-open the issue?

Thank you!

**Comment by kfollis** [comment]
Hi @MACEL94 - I have opened a work item for us to research this scenario and identify the best way for you to accomplish the goal so that we can enhance the article. You might try checking out this community thread for some ideas: https://community.powerbi.com/t5/Service/Assigning-RLS-roles-in-bulk/m-p/812623#M77938 or posting a new question to the community. The best way to accomplish bulk permissions seems to be by adding users to AD security groups.
