### ISSUE TITLE
Add help section

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/powerbi-docs#1684]
It isn't clear to me how you have done the example shown in the Add Help section. How did you put a ? on a visual. Is it just a separate button, or is there a way to add this directly on a visual somehow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db84fc62-b85a-1bef-987c-36345b762928
* Version Independent ID: a8c23738-1f6f-f99a-0cff-9553dca83d96
* Content: [Extending visuals with report page tooltips - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/report-page-tooltips)
* Content Source: [powerbi-docs/guidance/report-page-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/report-page-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by peter-myers** [comment]
The question mark (?) is the "Visual header tooltip icon" that can be turned on for any visual (see the Visual Header section in the Format pane). When it's turned on you can configure a visual header tooltip. The tooltip can display formatted text, or a report page tooltip. In this image, you can see a report page tooltip. The design of the page includes four text boxes and a shape (line). I hope this helps! #please-close
