### ISSUE TITLE
Needs to be a workspace admin if used with Power BI Embedded

### ISSUE THREAD

**Issue by viragg** [MicrosoftDocs/powerbi-docs#1685]
Is this correct? Row level security only work if the user account is read only. Does this mean for Power BI Embedded RLS does not work and you need Power BI Premium if you need RLS? 
Is admin only needed if you are using to do more than just embedding reports like creating workspaces etc. The documentation does not state either way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @viragg . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @viragg,

There is a gap in our documentation which I will shortly close. In any case, an admin or a member cannot implement RLS in the way you are trying to.

For RLS with Service Principal, please refer to the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
