### ISSUE TITLE
Error in tutorial

### ISSUE THREAD

**Issue by rudzimj** [MicrosoftDocs/powerbi-docs#1686]
In section "Developing the visual elements",  had to add the following 3 lines to visual.ts before the export statement. The bottom 2 lines are shown in the sample as already being there, but need to be added manually.

import IVisualHost = powerbi.extensibility.IVisualHost;
import * as d3 from "d3";
type Selection&lt;T extends d3.BaseType&gt; = d3.Selection&lt;T, any,any, any&gt;;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @rudzimj , thanks for your comment. I have assigned this issue to the content developer responsible for this article.

**Comment by KesemSharabi** [comment]
Thank you for your comment, @rudzimj.

I added the missing lines to the code caption in the verification process - **step 2** in the [Developing the visual elements](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial#developing-the-visual-elements) section, in the [Tutorial: Developing a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/custom-visual-develop-tutorial).
