### ISSUE TITLE
Data Sources not updated since 05/17/2018

### ISSUE THREAD

**Issue by thierryhouy** [MicrosoftDocs/powerbi-docs#1687]
We can find in the latest version of PBIRS (september 2019) new sources that are not on this list. Eg:
* HDInsight Interactive Query (Import & DirectQuery)
* PostgreSQL Database (DirectQuery also supported)
Is it possible to update this list?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37efb1d4-b4bb-f035-c63b-1f8b17d4f448
* Version Independent ID: fe9f8822-a20a-e17c-195c-1dc261ab480f
* Content: [Power BI report data sources in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/data-sources#feedback)
* Content Source: [powerbi-docs/report-server/data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @thierryhouy -- thanks for asking! These data sources are supported in Power BI Desktop, but not on Power BI Report Server. So no, they can’t be added.  
Thanks
