### ISSUE TITLE
When is it applicable?

### ISSUE THREAD

**Issue by eshkin-Kot** [MicrosoftDocs/powerbi-docs#1688]
Doesn't work for my import connection. I have read that it only works with the Direct Query.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99521173-b241-25e5-ea78-de782dc25edc
* Version Independent ID: 98a21d67-6880-73cd-571b-cfcf4aeac4f2
* Content: [Change data source connection strings with PowerShell - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis#feedback)
* Content Source: [powerbi-docs/report-server/connect-data-source-apis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/connect-data-source-apis.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by eshkin-Kot** [comment]
UPD: doesn't work with the Direct Query as well.

**Comment by maggiesMSFT** [comment]
Hi, @eshkin-Kot -- You're right that it's currently DirectQuery only. So if you're having issues with DirectQuery, you may need to enter a support request, https://powerbi.microsoft.com/en-us/support/
