### ISSUE TITLE
Calculate turnover rate sliced by period

### ISSUE THREAD

**Issue by Eutardigrade** [MicrosoftDocs/powerbi-docs#1689]
Hi there, thank you for this tutorial and for providing the environment and data for me to play with. I created a new measure "Turnover = DIVIDE([Seps],Employee[EmpCount])".  I then plot this measure into a waterfall chart with Turnover in Y Axis and Period as Category. The chart is then sliced with a slicer 'Date'[Year] and year 2014 is chosen. The waterfall chart returns the total as 49.36%. When this Turnover measure is plotted into a Card chart,  it returns 48.74%. Why the total shows in the Waterfall chart does not equal to the figure shown in the Card chart? Thank you for your help..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26de6125-fac6-cf9b-3677-861d0dd69d13
* Version Independent ID: 7ab8f758-bc5a-12b6-96ba-1b14c091811a
* Content: [Human Resources sample: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-human-resources#feedback)
* Content Source: [powerbi-docs/sample-human-resources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-human-resources.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Eutardigrade -- well, that's a puzzler! Thanks for asking. I'm checking and will get back to you.

**Comment by mihart** [comment]
Thanks for your question, @Eutardigrade. I noticed that it's been a while since you submitted this Git Issue -- were you able to get an answer? If not, I suggest that you ask the Power BI Community, at https://community.powerbi.com.  
All the best,
The DOCS team
