### ISSUE TITLE
Can Add Service Principle to Workspace, but not Group

### ISSUE THREAD

**Issue by lphomiej** [MicrosoftDocs/powerbi-docs#1690]
We have a mix of Workspaces and Office 365 Groups in our "Workspaces" in PowerBI web app. I can add a service principle to a workspace (using the instructions above), but I can't figure out how to provide permissions for a service principle to be an admin for a "Group" Workspace. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @lphomiej, 

It isn't possible to provide permissions for a service principle to be an admin for a "Group" Workspace (the old workspace). 

This only works with  the new workspace as mentioned in the first bullet in [Service principal with Power BI](https://docs.microsoft.com/power-bi/developer/embed-service-principal) > [Considerations and limitations](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#considerations-and-limitations).
