### ISSUE TITLE
Conflicting Statements about Calculated Tables

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#1691]
Under the "Calculated Tables" heading, these two statements appear to disagree with each other:

&gt;&gt; Calculated tables are always imported, and their data is refreshed when you refresh the tables. 
&gt;&gt; If a calculated table refers to a DirectQuery table, visuals that refer to the DirectQuery table always show the latest values in the underlying source.

The first sentence appears to state that direct query doesn't fully work with calculated tables, e.g. if I schedule my model to do a data refresh four times per day, the calculated table is only updated at these four times during the day, even if the table that the calculated table is based on is a direct query table.

The second sentence appears to state that calculated tables are not imported, and that calculated tables are updated as needed when the table is accessed via visuals (i.e. more than four times per day in my example above).

Which is true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models#feedback)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by cbailiss** [comment]
Or, in the second sentence.... "...visuals that refer to the DirectQuery table..." is that referring to the base table that the calculated table is based on?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @cbailiss.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
I don't believe those sentences are in conflict - the table gets imported into the report regardless of import or DirecQuery (either works, the updated data stays in the report), and furthermore, if it's a DirecQuery connect, that calculated table will always show the latest values (rather than be delayed by awaiting a refresh, for example, where other visuals in the report that do not use DirecQuery may not).
