### ISSUE TITLE
Can't reinstall the PBI Premium capacity metrics app. Stuck at 'Please hold on while we load a few things...'

### ISSUE THREAD

**Issue by thomas-lala** [MicrosoftDocs/powerbi-docs#1692]
I wanted to re-install the app, as it suddenly stopped showing memory usage. A few other metrics was  showing, such as refresh of datasets, though.

I tried yesterday, and suspected, that perhaps some temporary outage prevented me from doing it, as the message when it's about to install the app "Please hold on while we load a few things..." never disappeared, and the app never got installed. Had it stuck like that, for about an hour+. 

Now having waited a day for any temporary hick ups, and checked that there's no interruptions in the PBI service, I am not sure what else to do. Any help is much appreciated.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @PRMerger19. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
