### ISSUE TITLE
RLS behavior in case of users not belonging to a role

### ISSUE THREAD

**Issue by ChristianBraun190** [MicrosoftDocs/powerbi-docs#1693]
The article doesn't seem to describe what happens if a user doesn't belong to a role. Let's say I have sensitive data in a single table. I set up a role for people who are allowed to see that data, using a trivial filter expression like 1=1. Everyone else should not see it; also, I don't want to enumerate who "everyone else" is. How does this work? Can I assume that by default a table is not visible if it has security defined? Also, how would I test the behavior in the service - "Test as role" is only available for a given role, not for uses without a role. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by jiteshparwal93** [comment]
@ChristianBraun190 : You are correct, if user is not added in RLS group, he will not be able to see data until unless he is admin or a member with edit permission.

**Comment by paulinbar** [comment]
Hi @ChristianBraun190. I've noted your comments and will address them in the rewrite of the RLS articles that is now underway. In the meantime I am closing this issue now. Thanks for your input!
