### ISSUE TITLE
Instructions for VLSC no longer work

### ISSUE THREAD

**Issue by chris-schulz** [MicrosoftDocs/powerbi-docs#1694]
When using VLSC the SQL server 2016 (per core) item now states "licence key no longer required" however it is needed for Power BI Report server installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69db1b96-91ed-2440-5a1c-873a19d7ee47
* Version Independent ID: db0e2007-963b-44a5-9b6e-5be35481473e
* Content: [Install Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/install-report-server#feedback)
* Content Source: [powerbi-docs/report-server/install-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/install-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chris-schulz.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- as noted in your other issue, https://github.com/MicrosoftDocs/powerbi-docs/issues/1695, "There was a change in the SQL Server install media made available from the Microsoft Download center; the SQL Server key is no longer required to be entered when installing that media; however, the key is still required for Power BI Report Server."
Hope that helps! I'm adding a note to the article.

**Comment by chris-schulz** [comment]
Hi, this is a bug and is preventing SQL EE users from retrieving the key to install Power BI. Its not resolved!

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- further investigation. It appears the key is only showing in the section for SQL Server 2017, not 2016. But it's a static key, so you can get it from 2017 and use it in 2016. They're working on rectifying it, but in the meantime you can use it. Hope that helps.
