### ISSUE TITLE
This no longer works

### ISSUE THREAD

**Issue by chris-schulz** [MicrosoftDocs/powerbi-docs#1695]
SQL Server 2016 Enterprise Edition - Per core is no longer available in the list only SP1 and SP2. They both say "licence key no longer needed"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4600c4b7-8444-f0d4-9e81-25882a951d22
* Version Independent ID: 68e1a06b-69f7-8fc9-cfb9-8e4956580fab
* Content: [How to find your report server product key - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/find-product-key)
* Content Source: [powerbi-docs/report-server/find-product-key.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/find-product-key.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chris-schulz.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- There was a change in the SQL Server install media made available from the Microsoft Download center; the SQL Server key is no longer required to be entered when installing that media; however, the key is still required for Power BI Report Server.

**Comment by chris-schulz** [comment]
Hi, this is a bug. It is not resolved. There is no way to install Power BI since this change prevents us from retrieving the key.

**Comment by maggiesMSFT** [comment]
Just so this issue has the same note:
Hi, @chris-schulz -- further investigation. It appears the key is only showing in the section for SQL Server 2017, not 2016. But it's a static key, so you can get it from 2017 and use it in 2016. They're working on rectifying it, but in the meantime you can use it. Hope that helps.

**Comment by maggiesMSFT** [comment]
Hi, @chris-schulz -- BTW the key should be showing for SQL 2016, 2017, and 2019 now. 
thanks!
