### ISSUE TITLE
How do I connect to Azure Cost Management?

### ISSUE THREAD

**Issue by andrejohansson** [MicrosoftDocs/powerbi-docs#1696]
We have a normal Azure account, signed up for online. According to this article:
https://docs.microsoft.com/en-us/azure/billing/billing-view-all-accounts

We seem to have a **Microsoft Online Services Program** account.

How can I use the connector **Azure Cost Management** to get our cost data into Power BI?

A comment in #995 indicates that this account type is not supported, only EA and MCA accounts are supported?

Is this true? Is there some other way I can get the cost data into power bi?

Entering our billing account id (which I had to lookup by looking at api calls) just gives me the error:

``Billing AccountId Discover : Failed to discover Billing account for Billing Profile : xxxx`

**Comment by KesemSharabi** [comment]
Thanks for your comment, @andrejohansson. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
