### ISSUE TITLE
Installing via Developer edition will not provide PWBIRS

### ISSUE THREAD

**Issue by HarsimranjeetSingh** [MicrosoftDocs/powerbi-docs#1697]
Hi Team,

Installing POWER BI REPORT SERVER via Developer edition will not provide PWBIRS

**Comment by KesemSharabi** [comment]
Thanks for your comment, @HarsimranjeetSingh. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
