### ISSUE TITLE
External sharing contradicting information? 

### ISSUE THREAD

**Issue by AlexJPawlak** [MicrosoftDocs/powerbi-docs#1698]
Hello!
I noticed contradictory statement between this page and https://docs.microsoft.com/en-us/power-bi/service-admin-azure-ad-b2b

Here it says clearly: 

"Doesn't support external guest users with Azure business to business (B2B)." 

Although on the mentioned page, it says something entirely different: 

"When using the Allow external guest users to edit and manage content in the organization feature, the specified guest users get access to your organization's Power BI. They can see any content to which they have permission. They can access Home, browse workspaces, install apps, see where they are on the access list, and contribute content to workspaces. "
"The guest user must have the proper licensing in place to view the content that you shared. There are three ways to make sure the user has a proper license: use Power BI Premium, assign a Power BI Pro license, or use the guest's Power BI Pro license."

Could you help clarify which piece of information is current? Based on #615 I'd be inclined this page needs updating, but it's just a guess. 

Best regards,
AlexP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-secure#feedback)
* Content Source: [powerbi-docs/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by KesemSharabi** [comment]
Hi @AlexJPawlak,

I'm looking into this issue and will get back to you shortly.

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated and no longer mentions Azure B2B. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
