### ISSUE TITLE
Getting "Mice" errors when running script in 

### ISSUE THREAD

**Issue by ONLC-Classes** [MicrosoftDocs/powerbi-docs#170]

**Comment by ONLC-Classes** [comment]
A script is provided for this class.  We are giving complete credit to this repository for lab instructions, but in the first day,we are running power bi script you provided (see below):
===
SCRIPT Module 1

library(mice)
tempData <- mice(dataset,m=1,maxit=50,meth='pmm',seed=100)
completedData <- complete(tempData,1)
output <- dataset
output$completedValues <- completedData$"SMI missing values"
=====
IT's coming back with a MICE error - any ideas?

**Comment by mgblythe** [comment]
@davidi this is for desktop-r-in-query-editor file.

**Comment by davidiseminger** [comment]
Sorry about the trouble you're having. Sounds like you have a support request, rather than documentation feedback. Please use https://support.powerbi.com to submit support tickets.
