### ISSUE TITLE
Type?

### ISSUE THREAD

**Issue by stannov** [MicrosoftDocs/powerbi-docs#1703]
Count (Not Blanks): 6 .. should it be 7?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0509d4c-73e0-1ffe-6e71-965f76ec4e12
* Version Independent ID: d6ea7fca-f40e-5ac3-0d6a-11d072f64fe4
* Content: [Work with aggregates (sum, average, and so on) in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-aggregates#feedback)
* Content Source: [powerbi-docs/service-aggregates.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-aggregates.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @stannov.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @stannov, 
Good question -- thanks for asking! 6 is correct, because it's counting values in the Amount column, not the Country column. Make sense?
