### ISSUE TITLE
This document is partial and not self explanatory

### ISSUE THREAD

**Issue by tomer-agam** [MicrosoftDocs/powerbi-docs#1704]
Questions:
1. Why would I want to use advanced edit mode in the first place? (what can I achieve in doing so? or what can't I achieve without it?)
2. Where in the "capabilities.json" does "advancedEditModeSupport" reside?
3. After setting this mode - How do I use it in the custom visual? (an example would be very useful)
3.1. Next steps? Where is the next document that comes after this one, that explains actually how to use this feature?
4. What does "in focus mode" mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518254a4-e001-3e16-1220-9bc0358475bb
* Version Independent ID: a445a855-c10e-8b16-9808-26b9e9db5ca1
* Content: [Advanced edit mode in Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/advanced-edit-mode#feedback)
* Content Source: [powerbi-docs/developer/visuals/advanced-edit-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/advanced-edit-mode.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @tomer-agam.

I've assigned this issue to the Power BI visual support team for review.

**Comment by uve** [comment]
1. advanced edit mode allows to disable focus mode functionality.
2. you need to define advancedEditModeSupport in the root of capabilities.json.
3. no further steps are needed. PowerBI will handle this flag.
4. you can read about focus mode [here](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-focus#what-is-focus-mode).

**Comment by uve** [comment]
#please-close @kfollis
