### ISSUE TITLE
Document too complex to read and hard to understand

### ISSUE THREAD

**Issue by tomer-agam** [MicrosoftDocs/powerbi-docs#1705]
Missing:
1. Overview of the whole selection mechanism and how does it work
2. What are the different features and when are they used? example:
    withCapabilities, withSeries, withMeasures (etc.)
    In what cases should one use them? Does it make sense to use them together? Or does each one of them work for a 
    different usecase?
3. Is it required to execute "createSelectionIdBuilder()" for each new selectionId? or can this object be reused? (and why)

Maybe if there was somewhere to read about general structure (series, category, measure) and their relationship, things would be clearer here, but I cannot find any such document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75effaec-3c6e-83c9-c26e-8e58046cb347
* Version Independent ID: 971d9758-f10b-cddb-f6fa-c007e193e457
* Content: [Power BI visual data point selections - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/selection-api)
* Content Source: [powerbi-docs/developer/visuals/selection-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/selection-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @zBritva
* Microsoft Alias: **v-ilgali**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @tomer-agam.

I've assigned this issue to the Power BI visual support team for review.

**Comment by uve** [comment]
Both of withSeries and withMeasures are used, it will create appropriate selectionId based on data a user passed into the visual.
createSelectionIdBuilder() is used for every datapoint, you can't reuse it.

**Comment by uve** [comment]
#please-close @kfollis
