### ISSUE TITLE
CS1061: "AuthenticationContext" does not contain a definition of "AcquireToken"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1706]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/53

The comments below were machine-translated

@isKevinTrue commented yesterday — with docs.microsoft.com
Incorrect sample code
Error CS1061: "AuthenticationContext" does not contain a definition for "AcquireToken" and no accessible extension method "AcquireToken" was found that would accept the first parameter of type "AuthenticationContext" (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @CeciAc. I’ll add this request to our docs backlog.

**Comment by KesemSharabi** [comment]
Hi @CeciAc, 

This issue was fixed by updating the code snippets in [Get an authentication access token](https://docs.microsoft.com/power-bi/developer/automation/walkthrough-push-data-get-token#get-an-authentication-access-token).

Thanks,

Kesem
