### ISSUE TITLE
September 2019 Support Dates Unclear

### ISSUE THREAD

**Issue by maddhatter** [MicrosoftDocs/powerbi-docs#1709]
The last row of the Version History Table is unclear:

| **Version** | **Availability date** | **Support end date** |
| --- | --- | --- |
| September 2019 | September 2020 | September 2021 

I would expect an actual availability date (not a month) in 2019, and a support end date in 2020.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b388ff1b-9b08-2ac3-bb06-125115c96758
* Version Independent ID: f7b5f58c-9219-e9f8-2b3f-ae39b0c278f3
* Content: [Support timeline for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/support-timeline)
* Content Source: [powerbi-docs/report-server/support-timeline.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/support-timeline.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @maddhatter -- you are so right about the years! I'll update the article. Thanks for pointing that out! 
Re the date: Hmmm, I don't have that. I'll ask around. 
Thanks again!
