### ISSUE TITLE
Sharing Individual tabs of a Report

### ISSUE THREAD

**Issue by agwagner30** [MicrosoftDocs/powerbi-docs#1710]
Is it possible along with sharing filtered reports to also only share one tab of a report rather than the entire thing? I am trying to share certain tabs with some people and other tabs with others within the same report without making dashboards.

**Comment by maggiesMSFT** [comment]
Hi, @agwagner30 -- Thanks for asking! 
You can't share certain tabs with some people and other tabs with others within the same report. 
Suggestion: You can create reports based on other reports, then delete the pages you don't want in each version of the report. That way, the data stays up to date. See https://docs.microsoft.com/en-us/power-bi/service-datasets-discover-across-workspaces for more info. 
Hope that helps!

**Comment by agwagner30** [comment]
This was helpful, thank you Maggie!
