### ISSUE TITLE
User Owns Embedded tutorial is not accurate 

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#1711]
Followed the tutorial here (https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization) step by step but the embedding didn't work. Also the exact steps are not documented clearly. Had to make some changes as follows.

The AADAuthorityUrl given in the document is not correct. I had to use the AADAuhtorityUrl in the following format - https://login.windows.net/"tenant Id" to make it to work.

**Comment by mihart** [comment]
Thanks for your comment, @haider392 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @haider392,

Thank you for your feedback.

I am aware that the [Embed Power BI content into an application for your organization](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization) tutorial is not up-to-date, and will revise it (along with the other tutorials for Power BI embedded analytics) shortly.
