### ISSUE TITLE
Multiple Queries Per Visual

### ISSUE THREAD

**Issue by thehappycheese** [MicrosoftDocs/powerbi-docs#1712]
Hello, may I please know if it will ever be possible to have multiple queries per visual? It is causing me no end of bother to have this restriction. I have thoughally investigated slicers filters etc to try spread my plots over multiple visuals, but it boils down to needing multiple unrelated datasets to show up on one visual in a way that I can control the relationship between the various plots.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595c371b-cced-07b1-2581-07a96b4c5af0
* Version Independent ID: bebdf7f8-3ea0-cea4-4c9f-9b029020ef9f
* Content: [Understand data view mapping in Power BI visuals - Power BI](https://docs.microsoft.com/en-au/power-bi/developer/visuals/dataview-mappings#feedback)
* Content Source: [powerbi-docs/developer/visuals/dataview-mappings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/dataview-mappings.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @thehappycheese . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
