### ISSUE TITLE
Inaccurate mention of Excel worksheet

### ISSUE THREAD

**Issue by mlongoria** [MicrosoftDocs/powerbi-docs#1714]
In the Reference queries in the Query Editor section, a sentence starts "By default all queries load to either an Excel worksheet or the data model (or both)..." This looks like it was copied from docs on Excel. This should just say that queries load to the data model since we are only discussing Power BI Desktop here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70782244-c01c-bc5b-d266-d9404e02678e
* Version Independent ID: 1fda6a5f-784f-cfee-1352-81619f490814
* Content: [Tips and tricks for creating reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tips-and-tricks-for-creating-reports#reference-queries-in-the-query-editor)
* Content Source: [powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mlongoria . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for bringing that up, I've updated the article.
