### ISSUE TITLE
Configure Oracle Client. Provide More Details

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#1715]
It would be helpful to provide more details on the configuration of Oracle client. Many customers are experiencing issues at the time of configuring the client, especially to enable all drivers required to have the direct query working properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @frvigano . This issue has been assigned to the doc author for review.

**Comment by kritchens** [comment]
There needs to be more specific information on what exact version of ODAC works with Powerbi Currently the version that is linked to you get an error that its not the correct version. It seems like a the ODAC version of ODAC121024_x64 works correctly and it runs queries faster than the version this page links to.

**Comment by wgeerts69** [comment]
Getting an errror as well with the ODAC version mentioned in the document indicating it is an old version.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
