### ISSUE TITLE
Manager-specific dashboard tiles

### ISSUE THREAD

**Issue by lorenamschafer** [MicrosoftDocs/powerbi-docs#1717]
Is there a way to add all of these without needing to filter on the report individually and adding? If not, I tried this filter then pin method and I can't tell which filter is being applied, so is there a way to include that in the title?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c25ad9a8-50b9-7f83-4e10-ebbbff013d6b
* Version Independent ID: 0584427f-6438-277b-4a0c-5d51f4694f63
* Content: [Customer Profitability sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-customer-profitability#manager-specific-dashboard-tiles)
* Content Source: [powerbi-docs/sample-customer-profitability.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-customer-profitability.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @lorenamschafer . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @lorenamschafer - the bad news is that you do have to make them each individually. The good news is that you can retitle them. Select **More options** (the 3 dots ... in the upper right corner) of the tile and select Edit details. There you can give it any title you want.
Hope that helps!

**Comment by lorenamschafer** [comment]
When I create the tile it doesn't give me the name and I had two results
that had very close results so I wasn't sure which it was.

**Comment by maggiesMSFT** [comment]
Hi, @lorenamschafer -- Understood. Suggestion: Create and rename them one at a time, so you're sure which one gets which name. Make sense?

**Comment by lorenamschafer** [comment]
Sure, thank you.
