### ISSUE TITLE
The Last Navigator Screenshot is not aligned 

### ISSUE THREAD

**Issue by kamaljeetsingh-ism** [MicrosoftDocs/powerbi-docs#1719]
When i installed the power BI desktop from https://www.microsoft.com/en-us/download/details.aspx?id=58494 and tried using snowflake provider to connect snowflake. Inside Navigator pane, i see "Transform data" instead of "Edit" what it has been showcased in the screenshot in Microsoft document page

**Comment by mihart** [comment]
Hi @kamaljeetsingh-ism, 
Can you write back and let us know  to which document/article you are referring?  Thanks.

**Comment by kamaljeetsingh-ism** [comment]
https://docs.microsoft.com/en-us/power-bi/desktop-connect-snowflake
