### ISSUE TITLE
is there not a possibility to miss some events at the end of the day?

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/powerbi-docs#1720]
in the examples you give

```
$activities = Get-PowerBIActivityEvent -StartDateTime '2019-08-31T00:00:00' -EndDateTime '2019-08-31T23:59:59' ...
```

but wouldn't this miss any event that happened between 2019-08-31T23:59:59.0000001 and 2019-08-31T23:59:59.9999999?

If so please provide an example that avoids this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @o-o00o-o . This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@o-o00o-o - thanks for the patience while I researched your question! No, you won't miss data by using the timestamp values as shown in the examples. There is no timestamp larger than '2019-08-31T23:59:59' or smaller than '2019-09-31T00:00:00. The events fall on either boundary and will be included accordingly. I've added a note to the article to make that clear.
