### ISSUE TITLE
Page is missing some information regarding current privacy level options.

### ISSUE THREAD

**Issue by cajslc** [MicrosoftDocs/powerbi-docs#1722]
This page doesn't mention anything about the third privacy level: "Combine data according to each files privacy level settings".  It'd be great to know how this option works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-privacy-levels#feedback)
* Content Source: [powerbi-docs/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @cajslc . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests. 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
