### ISSUE TITLE
No data when using Enterprise Administrator (read only)

### ISSUE THREAD

**Issue by ironicLemon** [MicrosoftDocs/powerbi-docs#1723]
Accessing an EA agreement using an account with the role Enterprise Administrator (read only)

Gives errors getting the data:
401: The user does not have any claims associated
Details:
    error=
        code=401
        message=The user does not have any claims associated

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ironicLemon. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
