### ISSUE TITLE
Why Multiple Reg Forms

### ISSUE THREAD

**Issue by RichPDev** [MicrosoftDocs/powerbi-docs#1725]
I'm a registered user who wants to review the webinars. What's the point of having a profile if I have to fill out the registration form for EACH webinar? What a waste of time. Certainly this should be changed to recognize the profile asking to access the video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a082e6-1c36-af62-95b7-69405696764e
* Version Independent ID: 0425ef3a-54b6-3527-6a02-a60642c9d61c
* Content: [Power BI webinars - Power BI](https://docs.microsoft.com/en-us/power-bi/webinars#feedback)
* Content Source: [powerbi-docs/webinars.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/webinars.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @v-tatero
* Microsoft Alias: **v-tatero**

**Comment by davidiseminger** [comment]
Thanks for your comment, @RichPDev . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by v-tatero** [comment]
Adding the GEP lead, who will have a better answer for you.

Thanks,
Tatevik
________________________________

**Comment by kfollis** [comment]
Thank you for your feedback. We apologize for the inconvenience of having to register for each webinar. Your profile is saved for contact purposes, but isn’t used for authentication or authorization to the site so we have to collect that information each time. We’ll certainly consider your experience in future site improvements.

**Comment by kfollis** [comment]
#please-close
