### ISSUE TITLE
Would be good to have a Walkthrough and example on "Summarized Numeric Column"

### ISSUE THREAD

**Issue by AnandaSim** [MicrosoftDocs/powerbi-docs#1729]
I'm new to Power BI, the explanation of how "Summarized Numeric Column" works is trse. Could we have an example please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Use drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @AnandaSim . We’ll take a look at whether we have the resources to create that example, and get back here. Thanks!

**Comment by davidiseminger** [comment]
Added author.

**Comment by cool-Blue** [comment]
You give a rough description of how t create the page you drill through to page, but it's not clear to the busy consumer, what to do on the drill through from page.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
