### ISSUE TITLE
Can't find package corrplot

### ISSUE THREAD

**Issue by maxdomico** [MicrosoftDocs/powerbi-docs#173]
Feedback Type:
Frown (Error)

Timestamp:
2018-08-17T08:36:12.0684178Z

Local Time:
2018-08-17T16:36:12.0684178+08:00

Session ID:
1ac88a1e-d801-4b59-9239-8ea775fdff4c

Release:
August 2018

Product Version:
2.61.5192.601 (18.08) (x64)

Error Message:
R script error.
Loading required package: corrplot
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'corrplot'
Error in library(corrplot) : there is no package called 'corrplot'
Execution halted

OS Version:
Microsoft Windows NT 10.0.17134.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 461808]

Peak Virtual Memory:
38.3 GB

Private Memory:
340 MB

Peak Working Set:
487 MB

IE Version:
11.228.17134.0

User ID:
5166e17d-ad7b-45a2-8375-f3c3c767b3ff

Workbook Package Info:
1* - en-US, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
Import

Snapshot Trace Logs:
C:\Users\Aaron\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot111451933.zip

Performance Trace Logs:
C:\Users\Aaron\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_newFromWeb
PBI_SpanishLinguisticsEnabled
CustomConnectors
PBI_variationUIChange
PBI_canvasTooltips
PBI_PythonSupportEnabled
PBI_showIncrementalRefreshPolicy
PBI_compositeModels
PBI_DB2DQ

Disabled DirectQuery Options:
PBI_DirectQuery_Unrestricted
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
100%

Supported Services:
Power BI

Formulas:

section Section1;

shared mtcars = let
    Source = Csv.Document(File.Contents("C:\Users\shalaiva\Documents\Mdocs\PBI\samples\R\forecast_corr_demo\mtcars.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"model", type text}, {"mpg", type number}, {"cyl", Int64.Type}, {"disp", type number}, {"hp", Int64.Type}, {"drat", type number}, {"wt", type number}, {"qsec", type number}, {"vs", Int64.Type}, {"am", Int64.Type}, {"gear", Int64.Type}, {"carb", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"am", "Auto/Manual"}, {"wt", "Weight"}, {"hp", "Horse Power"}, {"cyl", "Num of Cyl"}, {"disp", "displacement"}, {"mpg", "mile/gallon"}, {"qsec", "sec for qMile"}})
in
    #"Renamed Columns";

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-visuals)
* Content Source: [powerbi-docs/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-visuals.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry to hear about your trouble. This is a support request, rather than documentation feedback. Please use https://support.powerbi.com to submit support tickets.
