### ISSUE TITLE
How to generate embed token from Azure AD token

### ISSUE THREAD

**Issue by er-mohd-ali** [MicrosoftDocs/powerbi-docs#1730]
I have already generated AD token and tried Implementing Row Level Security but it didn't work. I actually wanted to implement RLS is it necessary to use embed token to implement RLS? How to generate embed token from AD access token?

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
