### ISSUE TITLE
Query on power bi gateway and its secure credential management

### ISSUE THREAD

**Issue by Jawahar-Kaliraj** [MicrosoftDocs/powerbi-docs#1732]
In a query "When working with the on-premises data gateway, how are recovery keys used and where are they stored? What about secure credential management?", we have the following quote.

"When a user enters data source credentials in the Power BI service UI, the credentials are encrypted with the public key in the browser. The gateway decrypts the credentials using the RSA private key and re-encrypts them with an AES symmetric key before the data is stored in the Power BI service. With this process, the Power BI service never has access to the unencrypted data."

Here, what "data" is re-encrypted by AES symmetric key before it is stored in the Power BI service? Is it "data read from underlying data source"? If so, "Power BI" service can decrypt the data and show the reports with latest data please?

Thanks
Jawahar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b73941-7a77-b7e6-01a5-6d088f7c50ec
* Version Independent ID: ca5a44b2-88c7-e03d-4e94-a0a727160fff
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-security#feedback)
* Content Source: [powerbi-docs/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
