### ISSUE TITLE
Remove the word be in the note

### ISSUE THREAD

**Issue by noahamolot** [MicrosoftDocs/powerbi-docs#1733]
IN the Note at the top of the page, the word "be" is misplaced.  It currently reads "You aren't automatically be creating an Office......". It should just read "You aren't automatically creating an Office...."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19005ba4-1b45-4a5e-2335-3408eaaffbf5
* Version Independent ID: 3587ce6f-8a2f-34c4-e00b-c28985833249
* Content: [Manage your workspace in Power BI and Office 365 - Power BI](https://docs.microsoft.com/en-us/power-bi/service-manage-app-workspace-in-power-bi-and-office-365#feedback)
* Content Source: [powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @noahamolot and for the close read! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @noahamolot ! Fixed it. Update will be live later today.
