### ISSUE TITLE
Is Power BI report inside Dynamics 365 F &  SCM consider Embedded and needs Token

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/powerbi-docs#1735]
As subject, do we need token to view our custom Power BI report inside Dynamics 365 F&SCM ?
Is there any step by step guide how to embed specific for Dynamics 365 F&SCM ?
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @axaeffect . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Thanks for your comment, @axaeffect.

At the moment there isn't a plan to create a 'how to' guide for embedding in Dynamics.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
