### ISSUE TITLE
Inaccurate instructions in cross-report drillthrough doc

### ISSUE THREAD

**Issue by smith-erik** [MicrosoftDocs/powerbi-docs#1737]
Text probably wrong in section [Enable cross-report drillthrough](https://docs.microsoft.com/en-us/power-bi/desktop-cross-report-drill-through#enable-cross-report-drillthrough).

> To enable a report to be the **target** of a cross-report drillthrough, you must enable the feature for that report in the Options window.

Shouldn't the highlighted option be _enabled in the source report_, not in the target report? Option text "Allow visuals in this report to use drillthrough targets from other reports" implies this. (Also did some local tests, which confirmed my suspicions.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70cc0df0-14a7-079d-c32c-78fff8aef03f
* Version Independent ID: ff23bd8e-3901-3010-af39-19fb69f2fa6c
* Content: [Use cross-report drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-cross-report-drill-through#feedback)
* Content Source: [powerbi-docs/desktop-cross-report-drill-through.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-cross-report-drill-through.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @smith-erik . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by v-thepet** [comment]
@smith-erik @davidiseminger - This is corrected in PR https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3133 - to be submitted for author review today 1/17. Thanks for pointing this out.

**Comment by michael-hawker** [comment]
I don't even see the option in my Options dialog.  I have `Persistent filters`, `Visual options` and `Export Data` sections only...

**Comment by davidiseminger** [comment]
Thanks for the feedback, this has been corrected in an article update.
