### ISSUE TITLE
PowerBI Premium Failover

### ISSUE THREAD

**Issue by jonnyleigh** [MicrosoftDocs/powerbi-docs#1738]
Is this guidance about failover relevant for PowerBI Premium as well as PowerBI Service?
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ce540da-a491-f6c2-d33a-5293f09d2182
* Version Independent ID: dbdbaf6a-5c69-f33c-dc57-3a7b707ba5eb
* Content: [Power BI high availability, failover, and disaster recovery FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-failover#feedback)
* Content Source: [powerbi-docs/service-admin-failover.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-failover.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @jonnyleigh . This issue has been assigned to the doc author for review.

**Comment by BSLATTER** [comment]
mihart - Any update on this? I'd like to also confirm the Premium question

**Comment by kfollis** [comment]
@blsatter - thanks for the ping! Taking a look into this issue now.

**Comment by davidiseminger** [comment]
In the section, "Am I responsible for the availability of my Power BI solution?" it describes the differences in responsibility for the service, versus Premium. I believe that answers your question. 

If it does not, you can also find help in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by jonnyleigh** [comment]
Hi, the document isn't 100% clear on this point, the page is talking about PowerBI Service.  There's one bullet point mentioning PowerBI Premium which is saying that one must ensure that the node is not overloaded.  Could you please clarify that PowerBI Premium has the same failover capabilities as Service (e.g. read-only failover), as long as the user ensures the capcity is well managed as mentioned in the section "Am I responsible for the availablilty of my PowerBI solution".
Thanks,
