### ISSUE TITLE
The first Example used

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [MicrosoftDocs/powerbi-docs#1739]
"Here's an improved measure definition, which uses a Boolean expression instead of the table expression"

Red Sales =
CALCULATE(
    [Sales],
    'Product'[Color] = "Red"
)

The expression you show is not semantically similar to the expression it is supposed to replace. The correct/closest expression would be:

Red Sales =
CALCULATE (
    [Sales],
    KEEPFILTERS ( 'Product'[Color] = "Red" )
)

I.e adding KEEPFILTERS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7165e16-2eee-d5ba-e704-775d505b6646
* Version Independent ID: 25f1fbef-4a77-c0df-86aa-8c7ce4d91369
* Content: [DAX: Avoid using FILTER as a filter argument - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/dax-avoid-avoid-filter-as-filter-argument)
* Content Source: [powerbi-docs/guidance/dax-avoid-avoid-filter-as-filter-argument.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/dax-avoid-avoid-filter-as-filter-argument.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by mihart** [comment]
Thanks for your comment, @Oxenskiold-DAX . This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Thanks for pointing this issue out, @Oxenskiold-DAX. I've updated the formula, and surrounding text. #please-close
