### ISSUE TITLE
Capacity paused or deleted in Power BI Embedded

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/powerbi-docs#1740]
In section Power BI Embedded https://docs.microsoft.com/en-us/power-bi/developer/embedded-troubleshoot#typical-errors-when-embedding-for-power-bi-users
There are some reasons explain about Capacity paused or deleted.
Please help to elaborate what Capacity is this ? and where we should set or check this.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23f97f59-f933-6bcc-24e5-dfcaefbc2d28
* Version Independent ID: 4c97d24e-32ea-f021-257b-7d9bacbdd4f3
* Content: [Troubleshooting your embedded application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-troubleshoot#typical-errors-when-embedding-for-power-bi-users)
* Content Source: [powerbi-docs/developer/embedded-troubleshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-troubleshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @axaeffect . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @axaeffect,

I'm not exactly sure what you're looking for... 

You can stop/start and scale up/down [Power BI Embedded](https://docs.microsoft.com/power-bi/developer/azure-pbie-what-is-power-bi-embedded) which is shipped with *A* SKUs on an *Azure* capacity.

Please review the following:
 * [Power BI Embedded pricing](https://azure.microsoft.com/pricing/details/power-bi-embedded/)
* [Pause and start your Power BI Embedded capacity in the Azure portal](https://docs.microsoft.com/power-bi/developer/azure-pbie-pause-start)
* [Scale your Power BI Embedded capacity in the Azure portal](https://docs.microsoft.com/power-bi/developer/azure-pbie-scale-capacity)

Hope this helps,

Kesem

**Comment by axaeffect** [comment]
Sorry, I'm looking from the other Microsoft product which Dynamics 365 F&O. This "embed to your application" stuff apparently is not meant for D365 F&O.
