### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#1742]
This document is outdated and describes an user experience that it is no longer possibile as it is described. Update the document please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5c2cbb-f3de-c63e-fc74-a5157d5f5c9c
* Version Independent ID: dd280f16-bad8-5f60-f960-208047f6f9b2
* Content: [Azure SQL Data Warehouse with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-sql-data-warehouse-with-direct-connect#connecting-through-power-bi)
* Content Source: [powerbi-docs/service-azure-sql-data-warehouse-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-sql-data-warehouse-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @frvigano . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
