### ISSUE TITLE
Page is not updated with current PowerBI version available

### ISSUE THREAD

**Issue by adrianjumangit** [MicrosoftDocs/powerbi-docs#1743]
Page is not updated with current PowerBI version available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2a19e-3613-9ec0-8818-8f76d3c7eef9
* Version Independent ID: 0b8ebf11-af44-2556-db7c-766d5f844c98
* Content: [How to configure Power BI report scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/configure-scheduled-refresh#feedback)
* Content Source: [powerbi-docs/report-server/configure-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/configure-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by AriehEdelson** [comment]
https://docs.microsoft.com/en-us/power-bi/refresh-scheduled-refresh

**Comment by maggiesMSFT** [comment]
Hi, @adrianjumangit -- thanks for your comment. Could you elaborate? I just walked through the steps as spelled out and they seem correct.
And @AriehEdelson -- do you have a question about that page?
thanks

**Comment by AriehEdelson** [comment]
I had been having the same issue as Adrian. The link I provided helped me get to where I need to be and so I hoped to help Adrian. Thanks!
It's more that the images didn't match what I had on my screen.

**Comment by maggiesMSFT** [comment]
OK, thanks to you both, @adrianjumangit and @AriehEdelson ! Closing this issue. Feel free to reopen if necessary.
