### ISSUE TITLE
No source for usage of "Total Storage" for Dataflows (Power BI Pro)

### ISSUE THREAD

**Issue by mtthsbrr** [MicrosoftDocs/powerbi-docs#1744]
As a Power BI Pro user, I would like to check about the 10 GB/user total storage limit for dataflows, but I could not find the usage number anywhere yet.

Please advice. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4e74b8-9f4a-a195-7347-cf6732ffeab5
* Version Independent ID: a1513d50-f098-9b75-2b48-94e08ee34751
* Content: [Learn about dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-overview#feedback)
* Content Source: [powerbi-docs/service-dataflows-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mtthsbrr . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello there - the 10 GB/user for Pro includes the size of any dataflows. This should be reflected in your Power BI storage / usage information. For more information, take a look at the following Power BI community post: https://community.powerbi.com/t5/Service/Size-limit-for-data-flow-for-pro-user/td-p/880278
