### ISSUE TITLE
Correct JSON of "Properties within each card"

### ISSUE THREAD

**Issue by Heitor4u** [MicrosoftDocs/powerbi-docs#1745]
Changed the JSON to be valid for parsing. 
Could you take a look and change it at this page? Link below.
https://github.com/Heitor4u/Temp/blob/master/ThemeProperties.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Heitor4u . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment - the JSON and other content on that page has been significantly updated for better clarity.
