### ISSUE TITLE
Error signing in to register gateway

### ISSUE THREAD

**Issue by kanene** [MicrosoftDocs/powerbi-docs#1746]
Our company works with a third party MFA, when we try to register the gateway the application crash authenticating the user:

Faulting application name: EnterpriseGatewayConfigurator.exe, version: 3000.21.18.0, time stamp: 0xf5f94667
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3085, time stamp: 0x5d1d7c66
Exception code: 0x80004005
Fault offset: 0x0000000000034c48
Faulting process id: 0x878
Faulting application start time: 0x01d5cb264ed1cf71
Faulting application path: C:\Program Files\On-premises data gateway\EnterpriseGatewayConfigurator.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 049162f6-51c5-484d-a5c9-0e79025d2e8f
Faulting package full name: 
Faulting package-relative application ID: 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#next-steps)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by mihart** [comment]
Thanks for your comment, @kanene . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by kanene** [comment]
Thank you for your feedback!
