### ISSUE TITLE
What is "Source Spacing" under the font setting

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerbi-docs#1747]
I have the December 2019 Power BI Desktop and there is a "Source Spacing" in the Data Label section under the font family that is not shown or discussed on this page. It defaults to on, but I cannot tell the difference in the card with it on or off. Would like some documentation on this. See https://twitter.com/ehansalytics/status/1217224352866820096 for a screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b39f54-b688-a2e0-2097-76abe2086b7c
* Version Independent ID: 6376d063-b0b2-21f2-4fb8-506a016caf7d
* Content: [Card visualizations (big number tiles) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-card)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-card.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-card.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @edhans . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @edhans ,
It lets you display any extra spaces in the data label.  In Desktop, hover over the "Source spacing" and a tooltip pops up to explain what it is.  
HTH,
The DOCS team
