### ISSUE TITLE
Incorrect hyperlink for dynamic binding in 1st paragraph

### ISSUE THREAD

**Issue by upzone** [MicrosoftDocs/powerbi-docs#1748]
Wrong url for dynamic binding: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FLate_binding&data=02%7C01%7CKesem.Sharabi%40microsoft.com%7C5d5b0d2d62cf4818f0c108d7635b151e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637087115150775585&sdata=AbEtdJvgy4ivi4v4ziuui%2Bw2ibTQQXBQNYRKbXn5scA%3D&reserved=0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 693cc71b-6ad7-2fb7-8d01-c18fc3d8d7e7
* Version Independent ID: 5d564080-5a8d-f544-6a16-349a89465496
* Content: [Connect a report to a dataset using dynamic binding - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-dynamic-binding#feedback)
* Content Source: [powerbi-docs/developer/embed-dynamic-binding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-dynamic-binding.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @upzone. This is the correct link to the conceptual article on Wikipedia. Dynamic binding is also called late binding, as mentioned in the first line of the Wikipedia article.
