### ISSUE TITLE
Scheduled Refresh Dataset Table Timings

### ISSUE THREAD

**Issue by Saltzmea** [MicrosoftDocs/powerbi-docs#1749]
The articles don't discuss how a scheduled refresh for an import on SQL Server is executed. I noticed that some of my dataset tables with a handful of records return newly processed information before the processing is complete for large fact tables. Analysis Services preforms a swap of the data models after processing is complete. Is the scheduled refresh in Power BI refreshing each table independently and not inline with the way Analysis Services swaps the complete data model? My users are confused as to why the refresh timestamp defined by the (DateTime.LocalNow()) function is showing a new date if the records for their sales transactions are not yet available.  Can you confirm in documentation or report a bug to the product team?

**Comment by paulinbar** [comment]
Hi @Saltzmea , thanks for reaching out to us. Can you provide me the names or urls of some of the articles you consulted? This will help me identify the relevant author. Thanks!

**Comment by paulinbar** [comment]
Hi @Saltzmea , You've reached the documentation team. I am not sure what documents you are referring to, but in any event this sounds more like a support request or product question than documentation feedback. I suggest you try asking your question in the [Power BI Community]( https://community.powerbi.com), or, if you think this is erroneous behavior, file a bug on the Power BI [support page](https://support.powerbi.com).
