### ISSUE TITLE
EffectiveUserName on local machine

### ISSUE THREAD

**Issue by KoenVerbeeck** [MicrosoftDocs/powerbi-docs#175]
When OOS is installed on the same machine as SSAS (and in my case as SSRS as well), you don't need to add the machine name as admin to SSAS, but rather NT AUTHORITY\NETWORK SERVICE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90025eee-cd72-9503-6c1d-c14bb617b5b4
* Version Independent ID: 58e25db4-5d25-ac1d-b763-72d27e943373
* Content: [Host Excel workbooks using Office Online Server (OOS) - Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oos)
* Content Source: [powerbi-docs/report-server/excel-oos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/excel-oos.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@KoenVerbeeck Thank you for your suggestion. That is correct. It can work with the "NT AUTHORITY\NETWORK" service when all the requirements are installed on the same local machine.  However, it is good practice to add the "EffectiveUserName" when dealing with Analysis Services.

**Comment by KoenVerbeeck** [comment]
Hi @markingmyname, what do you mean with "adding the "EffectiveUserName""? The machine name of the OOS server?

**Comment by markingmyname** [comment]
@KoenVerbeeck I meant using the "EffectiveUserName" to add to the machine account of the OOS server for the Analysis Services instance.  Hope that helps.

**Comment by KoenVerbeeck** [comment]
Hi @markingmyname, yes that helps. But as I stated earlier, when everything is on the same machine, adding the machine account doesn't help. You still get errors until you add the network service. I'd like to see this reflected in the documentation as well.

**Comment by markingmyname** [comment]
@KoenVerbeeck I understand now.  I will do what I can to reflect this information. 

THank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we can always reopen the issue.

**Comment by KoenVerbeeck** [comment]
OK thanks!

Sent on my mobile device
________________________________
