### ISSUE TITLE
Access required to delete a dataset

### ISSUE THREAD

**Issue by salimassaf** [MicrosoftDocs/powerbi-docs#1750]
What access is required to delete a dataset?  You would expect it to be "Contributor" as that user should be able to "Create, edit, and delete content in the workspace" but that does not seem to be the case.  Can the chart be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @salimassaf . Thanks for your question. I am forwarding it on to the article author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @salimassaf -- good question! I'll check and get back to you, and update the article if necessary.

**Comment by maggiesMSFT** [comment]
Hi, @salimassaf -- turns out you've discovered an issue that Contributors don't see all the menu options they should see. A fix is in the works, but I don't have a date for it.
Hope that helps!
