### ISSUE TITLE
Quickbooks Online App does not show up

### ISSUE THREAD

**Issue by larrycsonka** [MicrosoftDocs/powerbi-docs#1751]
On this page it mentions installing the Quickbooks app to create reporting - but I don't see anything like that come up when I search.
Does this still exist?

https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online

**Comment by paulinbar** [comment]
Hi @larrycsonka . Thanks for your question. It looks to me like the documentation indeed is outdated. I am assigning that to an author. In terms of the app you mentioned, let me ask @teddybercovitz . Teddy, has Quickbooks Online become something else?

**Comment by paulinbar** [comment]
Hi @larrycsonka , I don't know whether this is still relevant, but I see that Quickbooks Online is now available again : https://app.powerbi.com/groups/me/getapps/services/pbi-contentpacks.pbiapps-quickbooksonline
Template apps have undergone a lot of  changes recently. The documentation is not entirely up to date, but I will be working on this soon.
Sorry for such a late reply.
