### ISSUE TITLE
How to apply in F&O work space ?

### ISSUE THREAD

**Issue by axaeffect** [MicrosoftDocs/powerbi-docs#1754]
My company has A SKU which is Power BI Embedded not a premium. How is this applied to our ERP which is Dynamics 365 F&O, especially if we create custom entity and create our own PBIX.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @axaeffect -- I'm assigning this to the author to see if they have a suggestion, or want to update the article. You may want to try the Community, https://community.powerbi.com/, or you may need to contact Support https://powerbi.microsoft.com/en-us/support/. Good luck!

**Comment by KesemSharabi** [comment]
Hi @axaeffect,

A SKUs are not supported for embedding in Dynamics - see the [Power BI now offers three SKUs for embedding: A SKUs, EM SKUs, and P SKUs. Which one should I purchase for my scenario?](https://docs.microsoft.com/power-bi/developer/embedded-faq#power-bi-now-offers-three-skus-for-embedding-a-skus-em-skus-and-p-skus-which-one-should-i-purchase-for-my-scenario) table in the [Frequently asked questions about Power BI Embedded](https://docs.microsoft.com/power-bi/developer/embedded-faq) article.
