### ISSUE TITLE
Performance and Impact on datset size

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#1755]
Can we get more details about how the group and bins work? Can we consider them to be created in the same way as a Calculated Column? if yes what is the advantage? If not how is it different?
Thanks in advance!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7502a07a-7f30-882d-7542-2a194651c421
* Version Independent ID: e3c6e2fd-b672-6858-864c-69026d36c0ae
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.

**Comment by dhruvinushah** [comment]
@davidiseminger Thanks David for reviewing my request. It would be helpful to know how the grouping works in order to create reports which are faster and would take less time to refresh! Hoping to see this soon in the documentation!
