### ISSUE TITLE
Complete list of JSON objects & properties

### ISSUE THREAD

**Issue by gah112** [MicrosoftDocs/powerbi-docs#1757]
Hi MS Team - this article is fantastic. Having a complete list of the available theme properties and objects would be an excellent addition. In trying to set a few properties (e.g. for the "visualHeaderTooltip" object) I have had some issues determining the correct property names. Thanks for your support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi, @gah112 . Thanks for your comment! I am assigning it to the author of the article for consideration. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your input @gah112 , we're in the process of updating the document and that JSON, and will include more complete information.
