### ISSUE TITLE
PBIVIZ install and certificate

### ISSUE THREAD

**Issue by Withnail99** [MicrosoftDocs/powerbi-docs#1758]
When installing PBIVIZ per above I get the warning message core-js@2.3.0 is no longer maintained and not recommended.... etct
When trying to create and install a certificate, I get the error message below. I am now stuck - can you help resolve? Thanks.

pbiviz : File C:\Users\customer\AppData\Roaming\npm\pbiviz.ps1 cannot be loaded. The file C:\Users\customer\AppData\Roaming\npm\pbiviz.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting
execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ pbiviz --install-cert
+ ~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by CyrusGrimes** [comment]
I also had the same experience with the installation of PBIVIZ, and had the same message generated. I was able to register my certificate, but I had to manually open the certificate importer. The process fully broke at step 3. To create a custom visual project, enter the following command. CircleCard is the name of the project.
I got 
PS C:\Windows\system32> pbiviz new CircleCard
 info   Creating new visual
node.exe :  error  Unable to create visual. Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\circleCard'
At C:\Users\cgrimes\AppData\Roaming\npm\pbiviz.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/powerbi-visuals-tools/bin/pbiv ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ( error  Unable ...m32\circleCard':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at Object.mkdirSync (fs.js:856:3)
    at mkDirAndCopy (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:107:6)
    at onDir (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:99:25)
    at getStats (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:45:37)
    at startCopy (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:38:10)
    at handleFilterAndCopy (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:33:10)
    at Object.copySync (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\fs-extra\lib\copy-sync\copy-sync.js:26:10)
    at copyVisualTemplate (C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\VisualGenerator.js:124:8)
    at C:\Users\cgrimes\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\lib\VisualGenerator.js:275:21
    at FSReqCallback.oncomplete (fs.js:154:23) {
  errno: -4048,
  syscall: 'mkdir',
  code: 'EPERM',
  path: 'C:\\Windows\\system32\\circleCard'
}

**Comment by CyrusGrimes** [comment]
nevermind I was using the powershell ISE, not just the regular powershell.

**Comment by maggiesMSFT** [comment]
Hi, @Withnail99 and @CyrusGrimes -- I'm assigning this to the author to see if they have a suggestion, or want to update the article. You may want to try the Community, https://community.powerbi.com/, or you may need to contact Support https://powerbi.microsoft.com/en-us/support/. Good luck!

**Comment by KesemSharabi** [comment]
Hi @Withnail99,

I'm assigning this issue to  one of our support managers for further investigation.

**Comment by uve** [comment]
@CyrusGrimes **C:\Windows\system32\** is not the best folder to create a new visual.
Users don't have an access to that folder.

**Comment by uve** [comment]
#please-close @kfollis

**Comment by douglasg14b** [comment]
Was there a resolution to this? I'm on a fresh system (literally, today). Installed NPM, installed the power bi tools via `npm i -g powerbi-visuals-tools`, and cannot run any `pbiviz` commands to the the same error OP saw:

> pbiviz : File C:\Users\Douglas\AppData\Roaming\npm\pbiviz.ps1 cannot be loaded. The file C:\Users\Douglas\AppData\Roaming\npm\pbiviz.ps1 is not digitally signed. You cannot run this script on the 
current system.

**Comment by Seebaer1986** [comment]
Same problem here. Fresh install of windows, NPM and pbiviz. When trying to install the certificate i get the same error as OP.

**Comment by kfollis** [comment]
It appears that this issue is resolved in comments. To allow the script to run, you can modify the local execution policy as shown in @Seebaer1986's comment (these PS cmds first allow the script to run then reset the policy to default): 
Get-ExecutionPolicy
Set-ExecutionPolicy -Scope CurrentUser Bypass
y
pbiviz --install-cert
Set-ExecutionPolicy -Scope CurrentUser Allsigned (or whatever your policy was originally set to - see step 1)
y
And, as @uve notes, be sure to save the visual in a location that users can access. This issue is closed. If you have new feedback, please submit a new comment. Thanks!
