### ISSUE TITLE
Good article, but a bit vauge concerning users, members, and owners

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#176]
For Owners, please be more precise. Do you mean owner of workspace or owner of .pbix file
"Members of a workspace cannot replace the originally shared report". I guess you mean .pbix file or report/dataset. 
If I understand this correctly: As a member of a workspace, you can upload new reports/datasets, but can't modify others. Is this correct

Also, this article doesn't say anything about shared datasets that are published as an Power BI app. Does that change the behavior of sharing?
And at last a product feedback. Using the Power BI Service and managing the data sets permissions, It looks like the dataset is shared, even with users not a member of the workspace. I don't think is shall be possible to share a dataset with users not belonging to the workspace if that doesn't work in reality

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by erapade** [comment]
I also realized that the owner listed of my dataset is the O365 group only. , since my workspace is created as a Team site. Although, looking in the Team-site, I'm listed as the Owner. A lot of confusions as I see this

**Comment by davidiseminger** [comment]
Thanks for your feedback! We will look at this article, @erapade, and see about providing more clarity in the areas  you point out.
