### ISSUE TITLE
Matplotlib

### ISSUE THREAD

**Issue by agustingc** [MicrosoftDocs/powerbi-docs#1761]
There are several references to a "Matprolib library" in this article where I believe the correct name is Matplotlib.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6b7b4f-9f34-cec1-687c-2f5c708fe99f
* Version Independent ID: e66e6e43-157d-8331-20e2-89d1379c5251
* Content: [Create Power BI visuals using Python in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-visuals#feedback)
* Content Source: [powerbi-docs/desktop-python-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @agustingc.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for your patience and your good eye, @agustingc ! These are fixed, will be published at the latest Mon Apr 6.

**Comment by agustingc** [comment]
> Thanks for your patience and your good eye, @agustingc ! These are fixed, will be published at the latest Mon Apr 6.

Welcome!
