### ISSUE TITLE
Is there a chance of 'late arrivals' when obtaining data using ActivityEvents REST API? 

### ISSUE THREAD

**Issue by olyamusok** [MicrosoftDocs/powerbi-docs#1762]
aka when is the safest I can call the cmdlet/script to export full data for the previous completed UTC day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @olyamusok.

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
@olyamusok - Thanks for being patient while I investigated. Yes, it can take up to 24 hours for an event show up. It typically happens much sooner than that. I've added a note to the article to make that clarification.
