### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by timp3261** [MicrosoftDocs/powerbi-docs#1763]
Hi, 
The steps provided in the page is not working.
I received the following error after entering the page id and the connection.
"Facebook: (#10) This endpoint requires the 'manage_pages' permission or the 'Page Public Content Access' feature. Refer to https://developers.facebook.com/docs/apps/review/login-permissions#manage-pages and https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS for details."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Facebook analytics using Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-facebook-analytics#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @timp3261. This issue has been assigned to the doc author for review.

**Comment by DataAdminEviso** [comment]
Hello,
I got the same error.
Please inform when the API has again Manage_page permission from Facebook.
Thanks

**Comment by vanessa89-aus** [comment]
Hi there, 

I ran into the same error message. 

Can you advise next steps to resolve as I've contacted both Facebook and trolled forums but no fix or suggestions on how to overcome the error and connect Facebook to PowerBI.

**Comment by davidiseminger** [comment]
Hi all,
Sorry for the inconvenience - you may not have seen the warning at the top of the article, where it states that the Facebook APIs are currently not working. We're working with Facebook on the issue, and once it's resolved, will update this article.
