### ISSUE TITLE
Transparent images with black text unreadable using dark theme

### ISSUE THREAD

**Issue by evandromr** [MicrosoftDocs/powerbi-docs#1764]
For example https://docs.microsoft.com/en-us/power-bi/guidance/media/star-schema/field-list-example.png

Images on this page have a dark text with a transparent background. When viewing the page using a dark theme the text is unreadable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema#feedback)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by paulinbar** [comment]
Thanks for letting us know Evandro. I've fixed the image transparency. The fix should be out live by around midnight. Thanks!
@evandromr
