### ISSUE TITLE
Upgrade Web Report with Sharepoint PBIX

### ISSUE THREAD

**Issue by Diego-MX** [MicrosoftDocs/powerbi-docs#1765]
I just found out how to create a web report / dataset in Power BI web, based off on a desktop PBIX that has been stored in OneDrive or Sharepoint site.  

Link to the documentation, [here](https://docs.microsoft.com/en-us/power-bi/service-desktop-files)

This is a great feature that allows one to sync the web report with the corresponding PBIX.  And thus avoid downloading the PBIX when transfering changes from app.powerbi to desktop, or publishing the pbix when making changes the other way around. 

This is great for new reports that I'd like to provide my workmates, as I'll just create them there. 

Still, there are a few reports that I have uploaded already from a pbix in the old fashion.  And that I keep publishing whenever I need to save changes from the desktop, or downloading again when someone else makes changes directly on the app. 

Since I have already sent the corresponding linkes, and embedded them in other websites, I wouldn't have to recreate them.  It would be great if I could just modify something on the web report, in order to point to the Sharepoint site.  And move it to this new way of syncing the two versions of the file.  

Is this possible at the moment?  
If not, could I make this a feature request? 
Thanks .

**Comment by mihart** [comment]
Thanks for your comment, @Diego-MX . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. To submit this as a new idea, visit ideas.powerbi.com.

**Comment by Diego-MX** [comment]
Oh.  It was a feature request.   Got me the wrong channel.   
Thanks. 
Cheers from Mexico.
