### ISSUE TITLE
PBIDS - specify Implementation 2.0 SAP BW Connector 

### ISSUE THREAD

**Issue by LuminousIncal** [MicrosoftDocs/powerbi-docs#1767]
Hi,

Is it possible to specify the implementation 2.0 SAP Connector in a PBIDS file? At the moment this defaults to the implementation 1.0, which doesn't work for us.

Also, can other options such as LanguageCode be specified in the connector?

I've tried adding an options field but without success:
		"options": {
			"LanguageCode": "EN",
			"Implementation": "2.0"
		}

Many thanks,

Andy Thomas

**Comment by KesemSharabi** [comment]
Thanks for your comment, @LuminousIncal. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
