### ISSUE TITLE
Missing icon for data groups?

### ISSUE THREAD

**Issue by edfreeman** [MicrosoftDocs/powerbi-docs#1768]
It seems the icon for "data groups" isn't listed above. Took me a while to figure out what the icon signified, so it might be helpful to add it to the list above?

![image](https://user-images.githubusercontent.com/30260217/72912146-1ac58480-3d33-11ea-9d4a-a137df1ea5f5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dd081c3-9f0f-07b5-b0dd-4270ddc2232f
* Version Independent ID: 8d92a854-ddff-3c3e-c044-a2d06e68f55c
* Content: [Tour the report editor - Power BI](https://docs.microsoft.com/en-us/power-bi/service-the-report-editor-take-a-tour)
* Content Source: [powerbi-docs/service-the-report-editor-take-a-tour.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-the-report-editor-take-a-tour.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi Ed, thanks for your comment. I've assigned your issue to the doc author for consideration. Thanks!
@edfreeman

**Comment by DougSte** [comment]
It would be great if this icon list could be 100% complete. Currently it says "Here are some of the more common ones." which is a little ambiguous. It would be great if this were a complete reference or had a link to the complete reference.  Also it would be helpful to have an explanation for what it means when a field has no icon.

**Comment by maggiesMSFT** [comment]
Hi, @DougSte and @edfreeman -- belated thanks! I've updated the article with a link to a complete list of the field icons.
