### ISSUE TITLE
User can't access dataset if it has RLS

### ISSUE THREAD

**Issue by enjoy-qa** [MicrosoftDocs/powerbi-docs#1769]
Even if that user has access to a portion of the data, if he wants to create a dashboard in his own workspace with that dataset (the one with rls), he can't see nor access to de dataset.
its that ok? A dataset with rls can't be access by any member with a role in its own workspace?
that dataset use to be accesible to that user before rls.
thanks

**Comment by paulinbar** [comment]
Hi @enjoy-qa. You have reached the documentation team, and I don't see a reference to any specific documentation item. I think your question is perhaps more of a product question. I suggest you put your question to the [Power BI Community]( https://community.powerbi.com). There are a great many experienced people there and someone may be able to answer your question. 
Thanks for reaching out to us!
