### ISSUE TITLE
Limitations and considerations

### ISSUE THREAD

**Issue by TaicoRoswall** [MicrosoftDocs/powerbi-docs#177]
The ability to view Excel workbooks within Power BI Report Server is currently in preview.?
Is this still in preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90025eee-cd72-9503-6c1d-c14bb617b5b4
* Version Independent ID: 58e25db4-5d25-ac1d-b763-72d27e943373
* Content: [Host Excel workbooks using Office Online Server (OOS) - Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oos)
* Content Source: [powerbi-docs/report-server/excel-oos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/excel-oos.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@TaicoRoswall Thanks for the comment!  It is no longer in preview.  The article will be updated accordingly in a few days.

**Comment by eased** [comment]
Can you drill through to details with OOS?
