### ISSUE TITLE
NPGSQL for Postgresql

### ISSUE THREAD

**Issue by cpyne** [MicrosoftDocs/powerbi-docs#1770]
Version number 2.0.12 appears to be wrong for PostgreSQL.  This article says 4.0.10   https://docs.microsoft.com/en-us/power-query/connectors/postgresql

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d081a0-4c4b-f756-eaf7-1e98d583ecf8
* Version Independent ID: 0b694de6-df10-daca-888c-1062dd3299db
* Content: [Power BI data source prerequisites - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-source-prerequisites)
* Content Source: [powerbi-docs/desktop-data-source-prerequisites.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-source-prerequisites.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi Charlie, thanks for your comment. I've assigned this issue to the doc author for consideration. Thanks!
@cpyne

**Comment by davidiseminger** [comment]
Assigning to author.

**Comment by cpopell** [comment]
Can we close this issue?

**Comment by kfollis** [comment]
Thank you for submitting feedback on our documentation. This article has been updated. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
