### ISSUE TITLE
Supported Data Sources

### ISSUE THREAD

**Issue by ancibira** [MicrosoftDocs/powerbi-docs#1771]
Hi there, in this page it states that OData typically does not support query folding. In the following doc it says that OData does support query folding: https://docs.microsoft.com/en-us/power-query/power-query-folding 
Could you please make it more clear regarding what aspects of OData supports query folding? Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @ancibira, thanks for your observation. I've assigned your issue to the doc author for consideration. Thanks!

**Comment by davidiseminger** [comment]
Apologies for the confusion - I've updated the initial article to reflect that OData does support folding.
