### ISSUE TITLE
Plan for limitations

### ISSUE THREAD

**Issue by fanzhangrsllifecareorgau** [MicrosoftDocs/powerbi-docs#1772]
Is it possible to provide a date or plan against each item in the "Known limitations" section, so we know if we should wait for the limitation removed in the future or find other solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @fanzhangrsllifecareorgau -- we on the docs team won't have that information. The best way to find out what's coming and approximately when is to check the Power BI release notes, https://docs.microsoft.com/en-us/power-platform-release-plan/2019wave2/business-intelligence/planned-features. 
Hope that helps!
