### ISSUE TITLE
Description associated with importing a local file seems to be incorrect

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#1773]
The description says the import is getting the data, where in fact it seems to be getting data + PowerPivot + Power View + Power Query. 

The tooltip in Power BI Desktop is correct in that it mentions the 3 Excel Power Tools next to the Import option.

This could technically be a product bug rather than one in documentation, because the description is in Power BI portal itself.

**Service**

![image](https://user-images.githubusercontent.com/1765732/73042004-96a3f780-3e2d-11ea-8ce5-acb3a303ee98.png)

**Desktop**

![image](https://user-images.githubusercontent.com/1765732/73042100-e8e51880-3e2d-11ea-9396-b99c0b6ee333.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2b088da-d833-fba7-a07d-3a1a07ff557d
* Version Independent ID: 8c423288-260e-386a-4c75-4e39f7be6ff1
* Content: [Get data from Excel workbook files - Power BI](https://docs.microsoft.com/en-us/power-bi/service-excel-workbook-files)
* Content Source: [powerbi-docs/service-excel-workbook-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-excel-workbook-files.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- good catch! That is indeed a product bug, so you need to provide that feedback in the Power BI product forum, https://ideas.powerbi.com/forums/265200-power-bi. 
Thanks!
