### ISSUE TITLE
foloder

### ISSUE THREAD

**Issue by pb1051** [MicrosoftDocs/powerbi-docs#1775]
"In the information that's displayed, the dataflow's CDM foloder location appears under Dataflow Storage location, as shown in the following image."

Should be: 
"In the information that's displayed, the dataflow's CDM folder location appears under Dataflow Storage location, as shown in the following image."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure workspace dataflow settings - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-configure-workspace-storage-settings#feedback)
* Content Source: [powerbi-docs/service-dataflows-configure-workspace-storage-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-configure-workspace-storage-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @pb1051 -- good eye! I've assigned to the author to take care of it.
Thanks!

**Comment by pb1051** [comment]
;-) Thanks!

**Comment by davidiseminger** [comment]
Thanks for the close read! Fixed!
