### ISSUE TITLE
#Enable to Run Python Script in PowerBI

### ISSUE THREAD

**Issue by tarunbadial** [MicrosoftDocs/powerbi-docs#1776]
I am tired to run the script on get data from python script but it seems some below error:
**Issue Screenshot:**
![image](https://user-images.githubusercontent.com/43639402/73153943-a7898d00-40fb-11ea-93b4-58391d88b3c1.png)

**Python Script**
![image](https://user-images.githubusercontent.com/43639402/73154104-41513a00-40fc-11ea-85ff-be002f55d89f.png)

**PowerBI Version:**
![image](https://user-images.githubusercontent.com/43639402/73153972-bbcd8a00-40fb-11ea-90d2-62032628495d.png)

**Python Version:** I am also try in below version
Python 3.8.1
Python 3.7.0
Python 3.6.8

please help regarding to resolve this issue. what i do wrong in step i am also add the path of python in options in under file>Option And Settings>Option

**Comment by KesemSharabi** [comment]
Thanks for your comment, @PRMerger14. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
