### ISSUE TITLE
Incorrect link for finding parameters

### ISSUE THREAD

**Issue by davidmytton** [MicrosoftDocs/powerbi-docs#1778]
The link "finding these parameters" in step 7 links to the anchor on the wrong page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3f49d98-4002-a7d8-d41b-74f4079cb905
* Version Independent ID: 08f3c0e6-9a0f-a200-52a6-8cdc447dae46
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-microsoft-sustainability-calculator#feedback)
* Content Source: [powerbi-docs/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @joshthor3222
* Microsoft Alias: **v-tikid**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @davidmytton.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @KesemSharabi @joshthor3222 ,
I made the corrections and added it to my PR.
