### ISSUE TITLE
Dataset - modifying the Gateway Connection.

### ISSUE THREAD

**Issue by salimassaf** [MicrosoftDocs/powerbi-docs#1779]
It seems like a user requires two types of access to be able to publish a report using a particular data source.
1. User access to the gateway connection itself.
2. Member access to the workspace.

In particular reason why someone needs member access instead of contributor access to maintain a gateway connection within the dataset? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @salimassaf.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @salimassaf -- I'm investigating. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @salimassaf -- you're right, you need permissions on the gateway. In the workspace, you need either an Admin, Member, and Contributor role. I'm adding it to the table in the article. Thanks for asking!
