### ISSUE TITLE
Whats read-only access to content?

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#178]
"Read-only workspaces: replaced by a forthcoming Viewer role, which allows read-only access to content in a workspace"
Does this mean that the viewer role can connect to a live power bi data set from Power BI Desktop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#how-are-the-new-app-workspaces-different-from-current-app-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @erapade -- ah, another good question. In this case, no, the Viewer role will be similar to granting users read-only access to a workspace. Those with the Viewer role will be able to see the content in a workspace, but won't be able to modify or share it. I'm updating the article to make that clearer. Thanks!

**Comment by clokeshreddy1** [comment]
Hi,
Also how to provide read only access to the users on a workspace,so that the users connect to the dataset via power bi live service connection and build there own reports and deploy to the workspaces of there choice?

**Comment by Vinhaman** [comment]
Hi, @maggiesMSFT
I'm making new apps available to users that should only have the Read Only permission. Is there a ETA for this role to come out? 
I didn't want to create old workspaces just for this read only feature and have to migrate them latter.

**Comment by MMurray2018** [comment]
When will the viewer roll be available? This is causing a delay in our rolling out to users. Since this is a new installation we chose to use the new improved workspaces.

**Comment by maggiesMSFT** [comment]
Hi, @Vinhaman and @MMurray2018 -- great questions! Beyond the purview of the docs, however. Our team can only answer feedback related to the documentation. Please enter product questions and feedback by selecting the "Product Feedback" button at the bottom of the article. You can also submit product feedback or feature ideas at https://ideas.powerbi.com, and engage with the Power BI Community at https://community.powerbi.com.
If you do have any feedback about the documentation, feel free to enter it here. Thanks!

**Comment by lorelai-rm** [comment]
Hi, @maggiesMSFT. 

Does this mean that RLS in the new workspaces will only work until the Viewer role is released? 

Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @lorelai-rm -- no, RLS controls access to data. The Viewer role controls access to an app workspace. Does that answer your question? Thanks!

**Comment by lorelai-rm** [comment]
@maggiesMSFT, Thanks for the quick reply. It does not answer my question. Basically, I want to know which role is equivalent to the "Member can only view Power BI content" since this is the one I use to enforce RLS.
