### ISSUE TITLE
Power BI Mobile + OAuth + WAP: Can successfully auth, but 404 on all reports

### ISSUE THREAD

**Issue by sjnovick** [MicrosoftDocs/powerbi-docs#1780]
Greetings,

I have configured Power BI Server + OAuth + ADFS + WAP per https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-oauth-ssrs.md and https://www.youtube.com/embed/okzPAI2uUek.

Using Power BI mobile app on Android and iOS, I can successfully authenticate. However, attempting to render any report just "spins" and if clicking refresh, returns 404.

I have seen this error reported in a few other places, including:
https://community.powerbi.com/t5/Report-Server/PBI-with-ADFS-and-WAP-i-can-authenticate-to-Server-but-all/m-p/367034#M4177

I have tried various combinations of changes to the WAP Application, the ADFS Application Group, and SPNs. 

When attempting to observe via Fiddler, I see the 404 returned on "GET https://FQDN/powerbi/mobile?manifest=OfflineSupport..." Not sure if that's helpful, or a red herring.

I also noticed that there are some differences between the github docs and guyinacube's youtube video re ExternalURL and BackEndServerURL. Some examples include "/reports/" and some do not. I'm wondering if that could be related?

Any help greatly appreciated.

Thanks,
JN

**Comment by maggiesMSFT** [comment]
Hi, @sjnovick -- Sorry to hear this isn't working for you! For the most part, it sounds like a product issue, not a docs issue. You may need to contact https://powerbi.microsoft.com/en-us/support/. 
I'm assigning this to one of the authors to see if they can answer the question about the differences between the docs and the guyinacube video: "I also noticed that there are some differences between the github docs and guyinacube's youtube video re ExternalURL and BackEndServerURL. Some examples include "/reports/" and some do not. I'm wondering if that could be related?"
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @sjnovick -- thanks for your patience! You need to create a support case to handle this. https://powerbi.microsoft.com/en-us/support/
