### ISSUE TITLE
ODBC Connector Documentation

### ISSUE THREAD

**Issue by carriety** [MicrosoftDocs/powerbi-docs#1784]
In the Dataflow Get Data menu, ODBC connector is now an option. Better documentation is needed on expected field values for that connector. Page still states that M query copy is required for connecting to ODBC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1458e2bc-7637-e305-55f3-596c64972ff3
* Version Independent ID: b5437e14-6d46-e2f6-0369-e61f72988ff3
* Content: [Learn how to connect to dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-data-sources#feedback)
* Content Source: [powerbi-docs/service-dataflows-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @carriety ! Assigned to author to investigate.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
