### ISSUE TITLE
Advanced queries to access securityActions, ThreatIntelligence, etc...

### ISSUE THREAD

**Issue by dhoegl** [MicrosoftDocs/powerbi-docs#1785]
I was hoping this documentation would explain how to run queries that only work with 'Application-Level' permissions in an Azure tenant (as opposed to Delegated). Graph Security Connector registers as an 'Enterprise Application' when consented by an Admin. However, advanced queries such as "https://graph.microsoft.com/beta/security/securityActions" and "https://graph.microsoft.com/beta/security/TiIndicators/..." require elevated permissions that are only possible via 'App Registration' (e.g. SecurityActions.Read.All and ThreatIndicators.Read.All).

Is using this advanced feature missing in this documentation, or is there somewhere else that explains in detail?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-graph-security?source=docs#feedback)
* Content Source: [powerbi-docs/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @preetikr
* Microsoft Alias: **preetikr**

**Comment by maggiesMSFT** [comment]
Hi, @dhoegl -- good question! Asking the author to investigate.

**Comment by davidiseminger** [comment]
Thanks for your question, assigning so we can take a look.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer to your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
