### ISSUE TITLE
Use of spaces in capacity name

### ISSUE THREAD

**Issue by Mholsen** [MicrosoftDocs/powerbi-docs#1786]
Are you sure that spaces in the capacity name are allowed like shown in your picture?
Twice I have tried to create a capacity with spaces in the name and both failed.
Creating the capacity without spaces succeeded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Configure and manage capacities in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage)
* Content Source: [powerbi-docs/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-manage.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Mholsen -- good question! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
Sorry about that - I haven't heard of others having this problem, and many capacities do have spaces in their names. You can ask if others have had trouble with this at https://community.powerbi.com - and if so, we can dive deeper into what that difference (some having troubles, others not) might be.
