### ISSUE TITLE
RLS with nested distribution groups

### ISSUE THREAD

**Issue by mperkins312** [MicrosoftDocs/powerbi-docs#1787]
I'm assigning distribution groups to the security groups in Power BI and we realized that the security doesn't pass to the nested distribution groups. I looked online and this seems to be expected behavior, but I'm having a hard time finding any MSFT documentation on the subject. Could you please confirm this limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
You are right, nesting distribution groups into security groups isn't a supported scenario. It's flagged in this article as a limitation: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-groups-membership-azure-portal. I did note that the RLS article mentions that you can add distribution lists to a role - I'll make an update to clarify. Thank you for your input!

**Comment by kfollis** [comment]
Closing this issue. The mention of distribution groups has been removed. Only security principals can be used to apply permissions.
