### ISSUE TITLE
What about managed identity?

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/powerbi-docs#1789]
I'm trying to use the managed identity of a logicapp/azurefunction/data factory but it is not working. Managed identity is also using service principal in the background right? Why is it not working?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @baatch -- sorry to hear it! This sounds like a support request. Please see https://powerbi.microsoft.com/en-us/support/ for support.
Thanks!
