### ISSUE TITLE
more than one app in one workspace?

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#179]
Where you say:
* Publish and update apps.
* Share items and share apps.
Does this mean that the new workspaces can have more than one App for each workspace (Question due to that you say apps and not app) I'm not native English so this could also be an misunderstanding from my side

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#other-planned-new-app-workspace-preview-features)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @erapade -- great question! The article was not clear. Only one app per workspace. I've clarified it in the article and it will be republished on Monday.
