### ISSUE TITLE
Can't connect to a gateway in PowerBI online

### ISSUE THREAD

**Issue by Kazanskyi** [MicrosoftDocs/powerbi-docs#1790]
I connected successfully MS Project to PowerBI desktop and uploaded report to a cloud.
Now I am trying to set up automatic updates but I can't as I get "Invalid connection credentials".
I use the same credentials that were used for a desktop version.
Please help to solve this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data#feedback)
* Content Source: [powerbi-docs/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Kazanskyi -- sorry to hear it! This sounds like a support request. Please visit https://powerbi.microsoft.com/en-us/support/ for help resolving the issue.
