### ISSUE TITLE
Wrong precedence rules

### ISSUE THREAD

**Issue by marcosqlbi** [MicrosoftDocs/powerbi-docs#1791]
The list for performance preference is not correct.
The proper order is:
1) One-to-many intra-island relationships
2) Many-to-many model relationships achieved with an intermediary table that involves at least one bi-directional relationship
3) Many-to-many cardinality relationships
4) Cross-island relationships
Moreover, there are many different types of many-to-many relationships, so the list should be longer. More details here: https://www.sqlbi.com/tv/different-types-of-many-to-many-relationships-in-power-bi/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-relationships-understand#feedback)
* Content Source: [powerbi-docs/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by peter-myers** [comment]
Thanks for the feedback @marcosqlbi - we're taking a look at this, and will revert soon.

**Comment by marcosqlbi** [comment]
Thanks @peter-myers - please note that the list is just for performance. For small cardinality relationships I suggest 3) over 2) because it is simpler to implement.
The many-to-many cardinality relationship only replaces the many-one-many chain of relationships (intermediate table can be inferred from the content of the other tables). Usually it connects a fact table to a dimension table to an attribute that is not a primary key of the dimension.
The many-to-many cardinality relationship cannot replace a one-many-one chain of relationships (intermediate table is a bridge table coming from the data source - think about Customers/Accounts). Usually it connects two dimensions.

**Comment by davidiseminger** [comment]
Assigning so we can review - thanks for posting.

**Comment by janizz** [comment]
Being an Marco's avid learner, I was also baffled by the ordering :) did you really optimize the many-to-many to be so fast?

**Comment by kfollis** [comment]
@peter-myers - please review and make an update if needed so that we can close this old issue. Thanks!

**Comment by peter-myers** [comment]
Hi @marcosqlbi - thanks for your feedback. We're actively working with engineering to gain a deeper understanding. Stay tuned for an update to this article when we learn more. #please-close

**Comment by marcosqlbi** [comment]
There are no reasons to close this issue.
After 11 months, nothing changed: the current version of Power BI (and the version we had in February) still have the same behavior: all the performance benchmark we ran demonstrates that the right performance preference **is not** what the documentation suggests.
We continue to provide a different suggestion in terms of performance, we can also demonstrate this with measures. I understand that this _could_ change in the future, but the documentation should state what the situation is today and possibly what a direction for future changes could be.
The current documentation is providing wrong suggestions that might create performance issues to people choosing (2) instead of (3).

**Comment by kfollis** [comment]
Reopening and reassigning.

**Comment by jeroenterheerdt** [comment]
@marcosqlbi glad to report we have updated the documentation https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand#performance-preference. Thanks for reporting and your work and patience is appreciated, as always. We will keep a closer eye on this for any future changes.

**Comment by jeroenterheerdt** [comment]
#please-close

**Comment by marcosqlbi** [comment]
Thanks!
