### ISSUE TITLE
Auto datetime availability in all clients

### ISSUE THREAD

**Issue by kazyakj** [MicrosoftDocs/powerbi-docs#1792]
It might be helpful to add a note that the auto date/time hierarchy aren't available in all client tools (I didn't see them when connecting live via Excel or Tableau.) Maybe it's common knowledge but I don't think I've seen it explicitly stated in any existing documentation. Knowing up front that users clicking 'Analyze in Excel' won't be able to see or leverage those fields might help dataset developers determine a custom datedim is necessary vs having to change their model later if users complain. 

I was able to create MDX measures in excel referencing the hidden date table so I'd imagine that means that it's just up to the client tool to expose them, or is there a something that would prevent MDX clients from doing this? Just wanted to check if it was possible before going over to the ideas board. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c46ebd6-98bf-698e-ee1d-dc2691586c98
* Version Independent ID: 02aba4ee-a52c-41da-e5e2-9caa44048b4c
* Content: [Auto date/time in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-auto-date-time#feedback)
* Content Source: [powerbi-docs/desktop-auto-date-time.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-auto-date-time.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @kazyakj.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by peter-myers** [comment]
Hi @kazyakj - the article targets modelers in Power BI Desktop. However, I have added an additional sentence to the article making your point clear. Thanks for the suggestion. #please-close
