### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by nicolgit** [MicrosoftDocs/powerbi-docs#1794]
https://blogs.office.com/2014/03/24/creating-burndown-charts-for-project-using-power-pivot-and-power-query/ does not exist anymore, please check

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data)
* Content Source: [powerbi-docs/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @nicolgit. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. That link is now working, thanks for bringing it to our attention.
