### ISSUE TITLE
Percentage Indicator and Target goals

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#1795]
What if my Indicator and Target goals measures should be shown as percentages? There seem to be no support for this, i.e. the KPI visual does not support the format defined on the chosen measure. It always uses a standard format, does it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [Key Performance Indicator (KPI) visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-kpi#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-kpi.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @rcfoyn . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
