### ISSUE TITLE
Percentage values

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#1796]
What if my values are actually percentage values, i.e. with Percentage set as the format of the measures? This visual does not seem to recognize the set format of the measure, but instead always uses a standard format. Please verify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20ec85-cf09-5d0e-317c-1897a6f63b0b
* Version Independent ID: 8979a4de-7c09-8c5d-0415-e82957d29ccb
* Content: [Radial gauge charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-radial-gauge-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @rcfoyn . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @rcfoyn . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
