### ISSUE TITLE
Formatting options need documentation

### ISSUE THREAD

**Issue by rudzimj** [MicrosoftDocs/powerbi-docs#1799]
&gt; "Each visual also has a card in the Formatting section of the Visualizations pane called Visual header. In that card you can adjust all sorts of characteristics of the visual header."

I can't find anywhere where the Visual Header formatting options are explained. If you hover over each option, there is help text, but most do not explain what the option controls. For example, I am trying to find out what the "Drill on dropdown" setting does. The help text says it turns on the drill on dropdown feature, but doesn't say what "drill on dropdown" does! When I web search "drill on dropdown" I am not finding anything that explains this. The "Filter icon" help text is well written by comparison and explains what it does (shows users filters applied to a visual). 

On this page or elsewhere, it would be good to show examples of each formatting option, especially icons that might only appear on a data refresh such as the Visual information/warning/error icons. What are the situations that would cause these to show up? This is also needed because most of these settings are not visible in Desktop, but only after they are published and viewed in the reader.

So long term, better documentation would help here. Short term, can you help me understand "Drill on dropdown"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db547626-10e8-5ea4-e1c3-7da6c236ce9f
* Version Independent ID: 4529c3a6-1f8f-2e8c-4eaf-9bde90c4df54
* Content: [Use visual elements to enhance Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-visual-elements-for-reports#using-improved-visual-headers-in-power-bi-reports)
* Content Source: [powerbi-docs/desktop-visual-elements-for-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-visual-elements-for-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @rudzimj,
Thank you for your comment. There are just so many formatting options that we cannot document them all.  We are, however, trying to do a better job with hover tooltips!  So for a drillable visual, you can decide what to show in the dropdown and/or header for that visual.  One of the options is  to turn On and Off "Drill on dropdown".  You can also turn On and Off the header icons -- drill down icon, drill up icon, Show next level, etc...   After you make the changes, you need to go to Reading view in the Power BI service, to see the changes. 

I hope this answers you question,
@mihart
