### ISSUE TITLE
Differences between dataset in workspace and published in App?

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#180]
Might not fit here, but have never seen a definition about towards what dataset a report is connecting to using live connection. Will a report using a live connection connect to different datasets depending on if I'm using the report in the workspace (or the Power BI Desktop) or the report published as an App
If not fitted here, please point me to where I can find this definition

Sorry for this many feedbacks :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#other-planned-new-app-workspace-preview-features)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @erapade -- no worries! I'll answer what I think is your question: the report in the workspace and the report published in an app will both link to the same dataset. Does that answer your question? Thanks for asking!

**Comment by erapade** [comment]
Hi Maggie, Yes maybe it did answer my question, but let's double-check :-) And sorry for extending the question by this.
For reports, the workspace works like a staging are, once a report has been published (or updated as an App), any additional changes to the report stays in the workspace area until the App is updated the next time. This way the workspace works like a staging area so that you have Report(Workspace) and Report(App)

My question was if this is also true for Datasets so you have Dataset(Workspace) and Dataset(App). If so this also leads to other questions like: 
1) Refreshing the dataset. Does this happen twice (one time for the Workspace and one time for the App), and in this case at the same schedule
2) What reports are connecting to the workspace dataset and what reports are connecting to the App dataset? A guess is that reports not yet included in a App update will connect to the workspace dataset and the reports previously included in a App update will connect to the App dataset. Then the question goes to Live connections from a power BI Desktop, will those connect to the workspace dataset or to the App dataset

Please not that if the dataset is always the same in both the workspace and the App (meaning no staging capability for a dataset), all the question above is not valid

**Comment by maggiesMSFT** [comment]
Hi, @erapade -- good clarifying question. Both the published report in the app and the report in the workspace are accessing a single dataset. So when the dataset refreshes, it's refreshing the data in both reports. Thanks!
