### ISSUE TITLE
Data view icon missing - how do I access data view?

### ISSUE THREAD

**Issue by itthing** [MicrosoftDocs/powerbi-docs#1800]
I have a pbix file I've created recently with some connections to a couple of SQL instances, but the Data View icon is not present.  I can use the same install of desktop to open a different pbix file and the Data View icon is present.

What should a user do in such a case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32b2d1e0-b435-be54-bcf5-bdd0dfe1e813
* Version Independent ID: 18009f37-9663-0513-b62d-8fc3cf5da5b3
* Content: [Data view in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-view#feedback)
* Content Source: [powerbi-docs/desktop-data-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @itthing . This issue has been assigned to the doc author for review.

**Comment by itthing** [comment]
I determined the issue was that my data sources were all SQL with directaccess.  I changed them to import, refreshed my data and the Data View icon appeared.  It might be helpful to include something in the documentation about such situations.

**Comment by GitHubSig** [comment]
I encountered the same confusion.  Now I reckon that it's my use of PBI's StorageMode = DirectQuery (rather than Import) that is the reason that PBI (PBI Desktop September 2019) is not showing the Data View icon.
The documentation should be enhanced to clarify that.

**Comment by davidiseminger** [comment]
Great point - sorry about the confusion. I've added a note early in that document to that effect, which will be updated soon. Thanks!
