### ISSUE TITLE
Possible mistake?

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#1803]
section
Guest users using Personal accounts will experience more limitations due to sign-in restrictions.
"They can use consumption experiences in the Power BI service through a web browser"

Can they? Can you please check this statement. Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-azure-ad-b2b#considerations-and-limitations)
* Content Source: [powerbi-docs/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chizhova.

I've assigned this issue to the doc author for review.

**Comment by RileyCarney-DirectTechnology** [comment]
Need update please.
Under **Assign a Power BI Pro license to guest user**
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/assign-licenses-to-users?view=o365-worldwide#assign-licenses-to-users-on-the-licenses-page 
Nothing about assigning a license to a guest user.

**Comment by mihart** [comment]
Hi @chizhova,
We've update this article since you submitted this Issue. I'm going to close this because the article has been updated and also because it is true that guest users can consume content using Power BI service.  If you feel that this Issue is not resolved, please let us know.  
Thank you for your feedback,
The DOCS team
