### ISSUE TITLE
outof date ref effective identity 

### ISSUE THREAD

**Issue by rinso11** [MicrosoftDocs/powerbi-docs#1804]
"For example, you could change the PowerBIEmbedded_AppOwnsData sample. Services\EmbedService.cs line 76 and 77 could be updated from"

These lines do not represent the code you are referring to anymore

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @rinso11,

Thank you for your feedback - I have noted it and will refresh this article shortly.
