### ISSUE TITLE
HANA LDAP Authentication Not Working

### ISSUE THREAD

**Issue by bgbearcatfan** [MicrosoftDocs/powerbi-docs#1805]
We have successfully configured PowerBI to connect to HANA using encryption with local user accounts.  However, when we try to login with an LDAP user, we given the message "The credentials provided are invalid.".  LDAP authentication is working, as ODBC connections using Windows ODBC Data Source Administrator with an LDAP user is successful.  Any ideas to get this working with Power BI?

Edit:
To be more specific, error details are:
[SAP AG][LIBODBCHDB DLL][HDBODBC] General error;10 authentication failed

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bgbearcatfan. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
