### ISSUE TITLE
"Page can still be accessed by users using other methods"

### ISSUE THREAD

**Issue by soldstatic** [MicrosoftDocs/powerbi-docs#1806]
What are those other methods? I have several tabs hidden and so far the only method I know to get to them is with drill through and bookmarks, and I don't want either of those as they are visible to end users. But I want to be able to go grab those tabs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f750471-143b-f0fe-3d92-0bdaaa06dcc1
* Version Independent ID: 66cc67fb-28ff-4a0c-34f0-f688369cc15c
* Content: [Report View in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-view)
* Content Source: [powerbi-docs/desktop-report-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @soldstatic -- thanks for your question! Assigning to the author for consideration.

**Comment by davidiseminger** [comment]
You can use drill-through, bookmarks, or buttons to get to hidden tabs in a report. The buttons may be visible to end-users as well, but you may be able to get creative about where you place them (or perhaps permissions) to make them less visible. 

Hope that helps. Also, you might want to check with the community at https://community.powerbi.com for more ideas.

**Comment by soldstatic** [comment]
That doesn't really help. We should be able to impose the end user experience without having to have white text on a white background and cross our fingers an end user doesn't accidentally click the pink pixel on the image of the girl from the chat room while facing north (any Margret Atwood fans here? lol)

Anyway - point is there are also issues with being unable to embed report tabs unless they are visible. I suspect this behavior is related. As the report owners we should be able to specify these things.

**Comment by maggiesMSFT** [comment]
Hi, @soldstatic -- good to hear from you! Your point sounds like a feature request, which of course you can make at https://ideas.powerbi.com/forums/265200-power-bi. I suggest searching the Ideas site first to see if someone else has already made that suggestion. Then you can vote it up.
