### ISSUE TITLE
Issue 809 is still present

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#1809]
The single-database limitation for DirectQuery has been eliminated several months ago. So the following note on this page is incorrect and should be removed:

"All tables must come from a single database, unless you use composite models."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- thanks! Assigning to the author for review.

**Comment by davidiseminger** [comment]
Thanks for that - I'll update the article and get it published, should show up in ~24 hours. Thanks!
