### ISSUE TITLE
Power BI Pro or Premium?

### ISSUE THREAD

**Issue by djheston** [MicrosoftDocs/powerbi-docs#181]
Are bookmarks only available in the premium version of Power BI?
In Pro, going to File &gt; Options and Settings &gt; Options &gt; Preview Features, there is no bookmarks option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks#bookmarks-in-the-power-bi-service)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
It's available in Pro or Premium.

**Comment by adarshmadrecha** [comment]
Bookmarks are also available in free version of Power BI Desktop.
