### ISSUE TITLE
Not available for embedded

### ISSUE THREAD

**Issue by jlhjr** [MicrosoftDocs/powerbi-docs#1810]
It should be clarified somewhere that paginated reports based on Power BI shared data sets cannot be embedded (yet?) in the "App Owns Data" scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf55ca48-9d24-4a87-0f90-b660d3d0ca50
* Version Independent ID: 09e9b1e9-82b6-3efd-7b77-040c284b917b
* Content: [Create a paginated report with a Power BI shared dataset - Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/report-builder-shared-datasets#feedback)
* Content Source: [powerbi-docs/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @jlhjr ! Confirming with the product team and will update.

**Comment by maggiesMSFT** [comment]
Thanks, @jlhjr ! Updating the article today.
