### ISSUE TITLE
Microsoft Admin 365 Link

### ISSUE THREAD

**Issue by Withnail99** [MicrosoftDocs/powerbi-docs#1811]
The first link in the page - Microsoft 365 admin center - is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase)
* Content Source: [powerbi-docs/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-purchase.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Withnail99 -- thanks for the heads-up! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
Sorry about that! I've removed that link, since pricing information is found later in that article. The updated article should show up live in ~24 hours.
