### ISSUE TITLE
Provider Oracle.DataAccess.Client not found

### ISSUE THREAD

**Issue by filippobottega** [MicrosoftDocs/powerbi-docs#1812]
Hello,
  I get this error:

![image](https://user-images.githubusercontent.com/2587684/74047610-f0312800-49d0-11ea-8baa-e3812f3136c8.png)

   As suggested by Josh Galus here [Struggling with Oracle DB Connection](https://www.pbiusergroup.com/communities/community-home/digestviewer/viewthread?MessageKey=0ac479ec-35bc-4d73-9c92-48a52f9f43e7&CommunityKey=b35c8468-2fd8-4e1a-8429-322c39fe7110&tab=digestviewer) I have done these steps:

![image](https://user-images.githubusercontent.com/2587684/74047975-91b87980-49d1-11ea-90b8-1f93da8c17bd.png)

  If I continue ignoring the error I get another error:

![image](https://user-images.githubusercontent.com/2587684/74048025-af85de80-49d1-11ea-9e63-9463e9c7f1ef.png)

  and I'm not able to connect to Oracle.

  What is missing? Can I check something else to solve the issue?

  Thank you!

**Comment by filippobottega** [comment]
Solved! As explained at issue #784, it's MANDATORY to use the file ODAC121024_x64.zip

> You can try to use the following link, it worked for me where I was facing the same issue:
> http://download.oracle.com/otn/other/ole-oo4o/ODAC121024_x64.zip
> 
> I can Confirm this worked. It seems there has to be a specific version of Oracle Client installed to run correctly.

Please update the documentation and explain to the users that the only correct setup is ODAC121024_x64.zip.

**Comment by maggiesMSFT** [comment]
Hi, @filippobottega -- thanks for providing the info and the link to the previous issue, https://github.com/MicrosoftDocs/powerbi-docs/issues/784. 
Assigning to the author of https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#troubleshooting to update the article with more info.

**Comment by filippobottega** [comment]
Hi @maggiesMSFT , I have an update.
The problem is not the version of Oracle ODAC but a little and subtle difference between the Oracle ODAC Setup wizards.
If you compare ODAC121024_x64.zip with ODAC122011_x64.zip you'll find that the first one registers the ODAC .NET components on the GAC by default:

![image](https://user-images.githubusercontent.com/2587684/74135151-12eb5880-4bec-11ea-9863-779e4227bd6b.png)

The second one not:

![image](https://user-images.githubusercontent.com/2587684/74135178-21397480-4bec-11ea-8c30-21554d6598a1.png)

To let PowerBI to use Oracle ODAC is mandatory to register the ODAC components in the GAC:

![image](https://user-images.githubusercontent.com/2587684/74135249-4332f700-4bec-11ea-96ff-5610ce094df1.png)

Please tell to the author of the documentation to explain how to install Oracle ODAC to avoid this subtle and annoying issue.

Thank you!

**Comment by davidiseminger** [comment]
Thanks for the thorough information! I've added that to the article, in a note, to help others. Thanks for posting and sharing your findings!
