### ISSUE TITLE
 Problem with publishing on the Internet # 10

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/powerbi-docs#1813]
@DotBlackDot commented 2 days ago — with docs.microsoft.com

Earlier (until 01/01/2020) on the free version, reports were quietly published on the Internet, now it does not. Implementation - Publish on the Internet, a window pops up - "Ask the administrator to enable the creation of implementation codes." Previously created reports work. The account is free, I am the administrator. When you select the tab "management of implementation codes" - there are no available options for new reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web#feedback)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by ticianaciminari** [comment]
Hi Team, could you please check this issue from user?

Kind regards, 

Microsoft DOCS International Team

**Comment by ygyousif** [comment]
experiencing the same issue

**Comment by ygyousif** [comment]
never mind... went into Admin, turned the feature on then back on and now I can create the embed code.

**Comment by maggiesMSFT** [comment]
Thanks @ygyousif ! Hope that helps, @ticianaciminari !

**Comment by ticianaciminari** [comment]
@DotBlackDot FYI

**Comment by Yury133** [comment]
Hi Team,
I have same problem: "Ask the administrator to enable the creation of implementation codes."
What can be done?

> never mind... went into Admin, turned the feature on then back on and now I can create the embed code.
How can I go into Admin?

**Comment by poulinechen** [comment]
Hi ALL
  I have the same problem and I am the admin... What can I do? Thanks.

**Comment by DotBlackDot** [comment]
> Hi ALL
> I have the same problem and I am the admin... What can I do? Thanks.


I solved the problem this way.
In managing the domain’s mail account, I entered the data necessary to qualify for administrator status from here https://admin.microsoft.com/Adminportal/Home#/homepage

**Comment by Yury133** [comment]
> I solved the problem this way.
> In managing the domain’s mail account, I entered the data necessary to qualify for administrator status from here https://admin.microsoft.com/Adminportal/Home#/homepage

unfortunately I don't have access to this page...

**Comment by poulinechen** [comment]
> > Hi ALL
> > I have the same problem and I am the admin... What can I do? Thanks.
> 
> I solved the problem this way.
> In managing the domain’s mail account, I entered the data necessary to qualify for administrator status from here https://admin.microsoft.com/Adminportal/Home#/homepage

I already set my Power BI account as BI Admin..It didn't work .. What else I need to setup.. Thanks a lot.
