### ISSUE TITLE
Image Mismatch or Change

### ISSUE THREAD

**Issue by v-merpet** [MicrosoftDocs/powerbi-docs#1814]
The image you have provided for power-bi-format-conditional-web-url does not match the desktop URL image. There is no Web URL selection available under Conditional Formatting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#feedback)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @v-merpet . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @v-merpet -- can you check to see if you formatted the column with the hyperlinks as Web URL in the Data Category dropdown list? It's counter-intuitive, but for the https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#format-link-text-as-a-hyperlink option, you DON'T format the hyperlink column as Web URL. 
I state that in the first sentence, but I think I'll add it to the steps.

**Comment by matt-davis27** [comment]
@maggiesMSFT I too cannot see the Web URL selection under Conditional Formatting. I am currently using September 2019 version of Power BI as my employer's PBIRS uses that version. I asked a co-worker who is using the latest version of Power BI (February 2020) and he can see that selector. Can you add a disclaimer in the considerations that outlines the required version of Power BI to use this new feature?

**Comment by maggiesMSFT** [comment]
Great point, @matt-davis27 ! The Power BI Report Server version of Power BI Desktop rolls up features from the last several months and releases a few times a year. So you will be able to see it soon, assuming you can install a newer version of Power BI Report Server plus Power BI Desktop.

**Comment by mihart** [comment]
Hi @v-merpet ,
Thank you for pointing this out.  It's been a while since you originally submitted this Git Issue and we've added a disclaimer.  Please let us know if you are still having problems with Web URLs. 
All the best,
The DOCS team
