### ISSUE TITLE
this is a totally unnecessary change

### ISSUE THREAD

**Issue by jaschro** [MicrosoftDocs/powerbi-docs#1816]
It's been well documented for years that "Publish to Web" makes the content visible on the web.  This new roadblock is unhelpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web#feedback)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jaschro . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @jaschro -- sounds like your comment is about the product and not the documentation. I recommend going to https://ideas.powerbi.com/forums/265200-power-bi and stating your opinion.
Thanks!

**Comment by jaschro** [comment]
The article I read pointed to this page, which is why I posted where in
did.   And yes, my opinion is that making it incredibly difficult to use
Publish to Web made me waste a lot of time and energy trying to figure out
how to jump thru  the onerous hoop of proving I own the domain.  It was a
very technical process and one for which the documentation was bad.  Lots
of trial and error involved.
