### ISSUE TITLE
Only supports USA!

### ISSUE THREAD

**Issue by alexwhittles** [MicrosoftDocs/powerbi-docs#1821]
Please enhance this to support non-USA based QB - would be very useful to have a version that works with UK Quickbooks.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alexwhittles -- This doesn't appear to be a documentation issue. Can you make a suggestion in the Power BI Ideas forum, https://ideas.powerbi.com/forums/265200-power-bi? 
Hope that helps!
