### ISSUE TITLE
BigQuery Doesn't work with VPC Service Controls 

### ISSUE THREAD

**Issue by wortel3** [MicrosoftDocs/powerbi-docs#1822]
When a BigQuery project is inside a [VPC Service Perimeter](https://cloud.google.com/vpc-service-controls/) the Data Source will throw the following error when you drill down to the table level: 

DataSource.Error: ODBC: ERROR [HY000] [Microsoft][BigQuery] (100) Error interacting with REST API: VPC Service Controls: Request is prohibited by organization's policy. vpcServiceControlsUniqueIdentifier:

**Comment by davidiseminger** [comment]
Hi @wortel3 - could you please reference the article you're asking about, so we can investigate? Thanks.

**Comment by wortel3** [comment]
Hi David ,
 
Thank you for responding. 

The issue is with trying to access a table data inside a project in a [VPC Service Parameter](https://cloud.google.com/vpc-service-controls/docs/), using the BigQuery connector for PowerBI. You can drill down, using the Navigation Dialog , to the BigQuery dataset, but you can access the table itself. 

I understand that the VPC Service Parameter in GCP is meant to work in this way, i.e. to prevent data exfiltration, but  [the Simba ODBC connector](https://cloud.google.com/bigquery/providers/simba-drivers/) works in this way. The reason we can't just use that as a connector for BigQuery is because we need to be able to issue Direct Queries. 

Please let me know if you need more info. 

Thanks, 
Gerhard 
![image](https://user-images.githubusercontent.com/22468044/74315047-51fde300-4d7f-11ea-85a4-89c06ffd86bc.png)

**Comment by wortel3** [comment]
Apologies, I  see this repo is only for documentation. I was referring to the actual product itself. 

Thanks, 
Gerhard

**Comment by KesemSharabi** [comment]
Thanks @wortel3,

As this is product question not related to documentation, I'm closing the GitHub issue.
