### ISSUE TITLE
Connecting Power BI to Excel files on One Drive (Business)

### ISSUE THREAD

**Issue by kroman503** [MicrosoftDocs/powerbi-docs#1823]
I am not sure I understand the product design logic here. 
All of the products in this solution/article are created by Microsoft, so why can't there be a very simple option in Power BI titled "Connect to One Drive" or Connect to Excel file on OneDrive" with a straightforward logic?! Why do we have to research online how to connect products within the same family of products together?! And when finally Microsoft publishes a solution, why does it have to be such a complicated procedure?! Seriously, Microsoft, you want me to download online file, just so I could obtain a file location web path, and as if this was not enough, I have to modify that path to use it with power BI??!  Am I asking for too much in 2020?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-onedrive-business-links#feedback)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kroman503** [comment]
I am thankful to whoever released this solution. After spending a few hours and trying out many other solutions, this one actually worked.

**Comment by davidiseminger** [comment]
Glad to hear it worked out, @kroman503, and thanks for your feedback!
