### ISSUE TITLE
 Causal Impact R package missing

### ISSUE THREAD

**Issue by valc1** [MicrosoftDocs/powerbi-docs#1824]
I came across a situation where I wasn’t able to use an R visual in a Power BI service. It works perfectly fine in the desktop version.
Can you please add the Causal Impact R package? https://cran.r-project.org/web/packages/CausalImpact/CausalImpact.pdf
Thank you very much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#feedback)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @valc1 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your post - the best place for you to submit product feedback or feature ideas like this (and perhaps get others to request it, as well) is by going to https://ideas.powerbi.com.
