### ISSUE TITLE
Two Axes with Lines

### ISSUE THREAD

**Issue by lcortivo** [MicrosoftDocs/powerbi-docs#1825]
It would be nice if we could transpose the collumns into lines also, keeping the two axes but instead of show the numbers with columns keep showing with lines. Example:
The user has on te X axe Month-Year.
One line would be Sales
Another line would be Margin
Right now we're only able to see this kind of information with colum and line. I didn't find a way to just demonstrate by lines. In some cases the column is irrelevant to the analysis and we want to see the correlation between the lines.

Hope you've understood what I mean.
thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e368c2-36c2-a5c0-f2af-993f6ee73665
* Version Independent ID: 452524d5-e375-9750-19ac-eb76903b36b3
* Content: [Combo chart in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-combo-chart#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-combo-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-combo-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @lcortivo. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @lcortivo,
Unfortunately, we don't have a native visual for dual axes line charts.  However, I attended a talk last week and the speaker demonstrated a custom visual that does this exact thing. https://powerbi.tips/2019/09/dual-y-axis-line-chart/

Hope this helps,
@mihart
