### ISSUE TITLE
Cannot copy report to my personal workspace.

### ISSUE THREAD

**Issue by Agroskater** [MicrosoftDocs/powerbi-docs#1826]
I made a bunch of Teams, and those teams automatically had a workspace made from them when we got Power BI. 

When I try to copy a report to my personal workspace, My Workspace isn't an option. The only option is the one Workspace I made in PowerBI.com

When I try to pin the report to my own workspace's dashboard none appear.

This is frustrating because I made all of the teams, all of the reports and cannot share the reports to my own dashboard where I would like to keep track of everything. The workspace calls the Team itself as the owner and I'm only an admin. What can I do to fix this?

**Comment by mihart** [comment]
Thanks for your comment, @Agroskater . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
