### ISSUE TITLE
Power Bi no longer supports iOS10 for Mobile browser

### ISSUE THREAD

**Issue by Dadams0201** [MicrosoftDocs/powerbi-docs#1827]
This document does not include what version of iOS is supported for the mobile browser. 

Power Bi no longer supports iOS10 Mobile browsers. Only goes over Safari Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-browsers#feedback)
* Content Source: [powerbi-docs/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @Dadams0201 . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @Dadams0201 -- you're right! I'll update this article.

**Comment by maggiesMSFT** [comment]
Thanks, @Dadams0201 -- updated, will be live tomorrow.
