### ISSUE TITLE
Notice on the use of distribution groups with external mail contacts

### ISSUE THREAD

**Issue by jadesolis** [MicrosoftDocs/powerbi-docs#1829]
It should be disclosed that using emails of External mail contacts in Distribution Groups, when using distribution groups to manage permissions, will NOT work since these artifacts are only available to Exchange Online, and cannot be resolved by Azure AD. Adding these external email addresses directly in the permissions setting may work (citation needed), as it would initiate a B2B guest account relationship in the host's AAD.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-dashboards)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jadesolis -- thanks for asking! Confirming, then I'll update the article.

**Comment by maggiesMSFT** [comment]
Hi, @jadesolis -- adding the note today. Thanks again!
