### ISSUE TITLE
in Operator

### ISSUE THREAD

**Issue by aruparel** [MicrosoftDocs/powerbi-docs#183]
I tried "in" operator and it supports all the three data types, string, number and date. But as per the information in the table above, it indicates that it works only for date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @aruparel,
We're rolling out "in" and "or" over the next few weeks.  Look for the article to be updated as those features become officially GA. 
Take care,
Michele

**Comment by maggiesMSFT** [comment]
Good catch, @aruparel! Updating the table now.
