### ISSUE TITLE
Role required for Scheduling Refreshes

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#1831]
Hi, in the table under the heading "Roles in the new workspaces", it does not mention which role(s) are able to schedule data refreshes via the on-premise gateway.  Which roles can do this?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @cbailiss -- good question! I'll check and add it to the article.

**Comment by maggiesMSFT** [comment]
Hi, @cbailiss -- belatedly I have the answer. Admins, Members, and Contributors can schedule data refreshes via the on-premise gateway. I'm adding it to the table in the article. Thanks for asking!
