### ISSUE TITLE
Analyze in excel

### ISSUE THREAD

**Issue by savoy9** [MicrosoftDocs/powerbi-docs#1832]
I'm 99% sure that the build permission now gates people from using analyze in excel. However, neither this page or the analyze in excel page call that out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-build-permissions#feedback)
* Content Source: [powerbi-docs/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @savoy9 -- Thanks for asking! Confirming this, then I'll update the doc.

**Comment by maggiesMSFT** [comment]
Updating the doc now.
