### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by rasavio** [MicrosoftDocs/powerbi-docs#1833]
Hi,

The linked email address within this article for the 'R in Power BI Feedback Team' (rinpbifb@microsoft.com) is invalid.

I wish to request that the packages `ggfittext` (https://cran.r-project.org/web/packages/ggfittext/index.html) and `tidyquant` (https://cran.r-project.org/web/packages/tidyquant/index.html) please be added as Supported R Packages for Power BI.

Regards
Ryan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#feedback)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @rasavio, thanks for your comment. I am forwarding it on to the author of the article you mentioned for consideration.

**Comment by davidiseminger** [comment]
Hi @rasavio - thanks for your feedback, and your interest. 

You can make that product request by using the product feedback or feature ideas request at https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
