### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by harriyott** [MicrosoftDocs/powerbi-docs#1834]
"Embedding Power BI content from a Government Community Cloud (GCC), can only be done with an Office 356 SKU. Other national cloud customers can use Office 356 or Azure SKUs."

Office 356 =&gt; Office 365

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 286e7693-df7f-d311-952b-9d5d846f57d3
* Version Independent ID: a9728923-20a2-cafc-72a8-a26b4e1a5d72
* Content: [Embed content in your application for government and national cloud - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers-national-clouds#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers-national-clouds.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers-national-clouds.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
@harriyott fixed in master. Will go live in next publishing cycle later today.
