### ISSUE TITLE
Steady share and Low variance

### ISSUE THREAD

**Issue by rohit-mapakshi97** [MicrosoftDocs/powerbi-docs#1836]
What is the difference between Steady share insight and low variance here? As far as I can understand, you calculate the coefficient of variation for steady share insight to determine which region has steady values. If that is isn't the case, what am I missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2368b421-38bc-b939-af6e-2cd36e3e752d
* Version Independent ID: 4c44f153-86e5-1f2b-5d04-705676475f96
* Content: [Types of Insights supported by Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insight-types#feedback)
* Content Source: [powerbi-docs/consumer/end-user-insight-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-insight-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @rohit-mapakshi97 , thanks for your question. I am forwarding it along to the author of the article you mentioned. Hopefully they'll be able to point you in the right direction. In the meantime, you might check the [Power BI Community]( https://community.powerbi.com) to see if you can find an answer to your question.

**Comment by mihart** [comment]
Hi @rohit-mapakshi97 ,
I've updated the document with this info from the Insights developer: 

The low variance insights relates to the variance of a measure (say “sum of sales”) across a dimension (say “region”). The insight triggers when the variance of sales across all regions is below a threshold. In other words, when sales are pretty even across all regions (“about the same”).

The steady share insight applies to the context of a measure, a dimension, and another date/time dimension. This insight triggers when a particular dimension value, e.g. “the northeast region”, has a steady percentage of overall sales across that date/time dimension.

The steady share insight is indeed similar to the first one, but it relates to the evenness of the percentage of overall across time (for a specific filter value), vs. evenness of the absolute measure values across a dimension.

Thanks for your question and contribution to the docs.
The DOCS team.
