### ISSUE TITLE
Incorrect information about what is being sent to Bing Maps

### ISSUE THREAD

**Issue by benfaria** [MicrosoftDocs/powerbi-docs#1837]
Hello, I have had it verified by Microsoft engineers that under 'What is sent to Bing Maps', statements pertaining to sending filter bucket information to Bing Maps is incorrect (first para and first bullet point). Only the Location, Latitude and Longitude are being sent to Bing Maps. The filter data stays within the PBI data service. Please correct this as this has led to a lot of confusion and indicates a breach of privacy. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @benfaria, thanks for your comment. I am forwarding it on to the author of the article you mentioned for consideration.

**Comment by mihart** [comment]
Hi @benfaria ,
We've updated the article.  Thank you for pointing out the issue!
The DOCS team
