### ISSUE TITLE
Incomplete list of limitations

### ISSUE THREAD

**Issue by joaoverissimo** [MicrosoftDocs/powerbi-docs#1840]
Today we reach the limits for the API https://api.powerbi.com/v1.0/myorg/datasets/{datasetId}/Default.UpdateParameters. On the log, we can see Error Status 429.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f23877ad-9fe2-9c48-0b61-5b04f02d4b71
* Version Independent ID: 77df250f-0fa8-0080-67f6-131fff3b0a42
* Content: [Power BI REST API limitations - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/api-rest-api-limitations?redirectedfrom=MSDN)
* Content Source: [powerbi-docs/developer/api-rest-api-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/api-rest-api-limitations.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @joaoverissimo , thanks for reaching out to us. I am not sure whether this is documentation issue or just a product question about what to do when you reach a limit. I am forwarding your question along to the author of the article you mentioned and perhaps he will be able to point you in the right direction.

**Comment by paulinbar** [comment]
Hi again, @joaoverissimo. In the meantime, you might look for an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by joaoverissimo** [comment]
Actually this is an important detail.  Without knowing how is our limit we cannot create a pipeline of deployment. Today it happens again =/

**Comment by KesemSharabi** [comment]
Hi @joaoverissimo,

The limitations are described in [Power BI REST API limitations](https://docs.microsoft.com/power-bi/developer/automation/api-rest-api-limitations?redirectedfrom=MSDN).

Please check your call to find out which limitation you're exceeding.

For further assistance, open a [support ticket](https://support.powerbi.com).
