### ISSUE TITLE
Power BI Desktop UI has changed with latest version - Please change documentation to reflect the same

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#1841]
The UI of Power BI Desktop has changed completely with the latest version and documentation no longer guides us through proper steps. Please change all Power BI Desktop related documentation to reflect the new UI.

**Comment by paulinbar** [comment]
Hi @haider392 , thanks for your comment. I am forwarding it on to the author who may be able to give you some more information regarding this issue. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment and feedback @haider392 - there are many UI changes for Power BI Desktop, including the new ribbon that's currently in preview. We're planning on major updates to the documentation once the ribbon is Generally Available. Thanks!
