### ISSUE TITLE
Need to add examples for section: "Add a measure to drillthrough"

### ISSUE THREAD

**Issue by ZacharyGoldman** [MicrosoftDocs/powerbi-docs#1844]
The section called "Add a measure to drillthrough" could greatly benefit from at least one clear example of what this looks like in practice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Use drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough#feedback)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @ZacharyGoldman . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the suggestion - there's a great video that describes this, at https://www.youtube.com/watch?v=-_GMCE1TLvQ&feature=youtu.be&t=2m9s 

I hope that helps - and I've reassigned this to the correct article owner. Hope that helps!

**Comment by mihart** [comment]
Hi @ZacharyGoldman ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
