### ISSUE TITLE
Clarify which page (drillthrough or drilled-from) to take action on 

### ISSUE THREAD

**Issue by ZacharyGoldman** [MicrosoftDocs/powerbi-docs#1845]
In each section, it would be helpful to be explicit about which page's drillthrough pane is being modified, the drillthrough page, or the page that was drilled from. I think it is (almost?) always the drillthrough page you are referring to, but it would be better if this was made explicit, at least once per section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Use drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough#feedback)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @ZacharyGoldman . This issue has been assigned to the doc author for review.

**Comment by ElectricLlama** [comment]
I agree, perhaps you could use the terminology "Source" and "Target" and include a diagram.

**Comment by davidiseminger** [comment]
Good input - forwarding to the current author.

**Comment by maggiesMSFT** [comment]
Good idea, @ZacharyGoldman and @ElectricLlama ! I've added "target page" and "source page" liberally throughout the article. Hope that helps! Changes should be live tomorrow afternoon Jan 7 Pacific time
