### ISSUE TITLE
Azure databricks table supported as source?

### ISSUE THREAD

**Issue by baatch** [MicrosoftDocs/powerbi-docs#1846]
Hi is Azure Databricks supported as a source for incremental refresh? I’m designing a new solution for a customer and need to validate this from official sources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @baatch . This issue has been assigned to the doc author for review.

**Comment by baatch** [comment]
Hello?

**Comment by davidiseminger** [comment]
Hi @baatch - there's no exclusion for Azure databricks and incremental refresh, so as long as you follow the requirements outlined in our refresh and incremental refresh content, it should work properly.
