### ISSUE TITLE
Purchase a Premium Licence from a distributor

### ISSUE THREAD

**Issue by HappymediaDz** [MicrosoftDocs/powerbi-docs#1848]
Hi,
We are an MS Partner located in Algeria and we wanted to purchase a Power BI Premium Licence from our local Microsoft Distributor however the Distributor indicates that the SKU is not on his price list; What is the solution ?
Regards
Mehdi HAMMADI

**Comment by KesemSharabi** [comment]
Hi @HappymediaDz,

Please ask your local Microsoft Distributor to get in touch with our marketing Power BI product marketing manager Megan Tomlin.

As this is a documentation channel and your question isn't related to documentation, I'm closing the GitHub issue.

Thanks,

Kesem
