### ISSUE TITLE
Working with time related parameters query (Cube.ApplyParameter)

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#1849]
As of the december build of Power BI desktop (and service) previously created queries doesn't work any longer. This is due to the Time parameter applied in the query. 

Previously (September build and before) the Cube.ApplyParameter accepted parameters applied in text format like: 
{Cube.ApplyParameter, "[E0PRDATE]", {"[0CALDAY].[20190101]", "[0CALDAY].[20190110]"}},

The above doesn't work in december build and later. While running the query, it returns an error stating: 
"InternalError","subCode":0,"message":"We cannot convert the value \"[0CALDAY].[20190101]\" to type Date."

The solution we found to get this working again, is changing the Cube.ApplyParameter to change the query to a date format like below: 
{Cube.ApplyParameter, "[E0PRDATE]", {#date(2020,2,01),#date(2020, 2, 12)}},

However, this does not work in september build. By changing this to date format again, it works in september version as well. Example below. 
{Cube.ApplyParameter, "[E0PRDATE]", {Date.ToText(#date(2020,2,01)),Date.ToText(#date(2020, 2, 12))}},

The way how time related parameters are handled is changed in the connector for both dataflows and datasets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP Business Warehouse (BW) Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-bw-connector#feedback)
* Content Source: [powerbi-docs/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-bw-connector.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @marclelijveld.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment, @marclelijveld and sorry about the trouble you're having. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by marclelijveld** [comment]
@davidiseminger, Thanks for your comment. We had a support ticket running on this issue. Ticket is already closed and above is the outcome / solution I'm sharing here. During the support tickets the PG was involved as well and agreed that the docs were not in line with the current way of working. Please reconsider.
