### ISSUE TITLE
Connecting to an EA account does not work

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/powerbi-docs#1850]
Hi,

We have followed the instructions here to connect the connector to Azure, but we have always permissions issue:
- My Account is an Enterprise Administrator
- We are under EA (not MCA)

When connecting and clicking to preview the tables, i receive the following error: 401: Access denied at Enrollment level with ENrollmentNumber 12345678. User does not have above subscriptions access. details: error= code= 401 Access denied at Enrollment level with ENrollmentNumber 12345678. User does not have above 

So the question is:
1- What are the required permissions: Is EA Administrator enough ? Do we need additional permissions over the subscriptions like Billing Account Owner or something like that
2- Are the EA Biling APIs still supported ? Does this work? Is there any new version of the connector ?

It has been one week with this issue, please tell us if the documented permissions and steps are enough to make the connector work. 

Thanks for your help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by BenShy** [comment]
Do you only get this error on attempting to load RI charges table? EA admin (even read-only EA admin) should be enough.

**Comment by SamirFarhat** [comment]
Hi,
No i have the error for every table. We have used different account but the same problem happens.
Thanks

**Comment by mihart** [comment]
Thanks for your comment, @SamirFarhat . This issue has been assigned to the doc author for review.
You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by SamirFarhat** [comment]
Hi,
Just to clarify. We were able to fix the issue, but please mention that a Read-Only Enterprise Admin is sufficient for the connector to work
Thanks

**Comment by brgsstm** [comment]
@SamirFarhat - how was this issue fixed please?  Are you saying that RO admin is NOT enough?

**Comment by brgsstm** [comment]
> Hi,
> Just to clarify. We were able to fix the issue, but please mention that a Read-Only Enterprise Admin is sufficient for the connector to work
> Thanks

@SamirFarhat - how was this issue fixed please? Are you saying that RO admin is NOT enough?

**Comment by SamirFarhat** [comment]
Hi,
The admins 'were' providing the permissions over a different EA. I know, but i can't do anything :(
