### ISSUE TITLE
DeleteDatasetRows not Listed as Operation

### ISSUE THREAD

**Issue by TravisKale** [MicrosoftDocs/powerbi-docs#1852]
DeleteDatasetRows not Listed as Operation.  What else is missing?   

Doc URL: https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#operations-available-in-the-audit-and-activity-logs
I'm trying to use PowerShell to pull in audit logs, I want all operations for the most part but the DeleteDatasetRows, which is not Listed as Operation, is generating 5K rows per hour in our log and is too noisy for analysis.  

It doesn't seem as though there is a way to exclude an operation, only include [x,y,z] operations.  So I need a full list of operations to be able to include them all except this one operation.   

The fact that this documentation is missing an operation ,for a feature/operation that is very mature, leaves me suspect of other missing operations.

**Comment by mihart** [comment]
Hi @TravisKale, 
Please let us know which document you are using. That way I can assign this Issue to the document author,  
Thanks
The DOCS team

**Comment by TravisKale** [comment]
Updated original issue with doc URL.   https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#operations-available-in-the-audit-and-activity-logs

**Comment by mihart** [comment]
Thanks @TravisKale.  This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @TravisKale - Thanks for your patience while I researched. We acknowledge that DeleteDatasetRows  can be a nuisance. And, unfortunately, the filter action only supports "equal" & "and", making it impractical to exclude events. Today, the better approach is to download all events and then exclude or delete in the local archive. I've shared your feedback with the product group.

**Comment by TravisKale** [comment]
@kfollis This issue is not about the filtering capability, its that the documentation I point to does not have the DeleteDatasetRows operation defined.  The only reason I mention the filtering is because of the lack of sophistication in the tooling, I need to know all the possible operations to filter out what I don't want, i.e. I have to call out every operation I do want.

**Comment by kfollis** [comment]
Thanks for clarifying @TravisKale. I've reopened your issue and am looking into the enhancement you've requested. For the task you're describing, the better approach is to download all events and then exclude or delete in the local archive. But if I understand what you're asking for correctly, you can't tell what you do want because you're not sure that the operations list includes all the operations you might want.

**Comment by TravisKale** [comment]
@kfollis Yes, that is my main concern, not all operations are listed in the documentation, well at least one for sure, and I need a comprehensive list to make sure I'm not excluding anything by not including it in my include list.

**Comment by mihart** [comment]
Hi @TravisKale,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by TravisKale** [comment]
@mihart No, the documentation is still incomplete.  Very frustrating to see this issue linger for over a year only to be swept under the rug.

**Comment by georgedarakji** [comment]
@mihart the issue @TravisKale pointed is still not resolved. I was also trying to understand what the "DeleteDatasetRows" event means but couldn't find it in the documentation

**Comment by kfollis** [comment]
@georgedarakji and @TravisKale - I am reopening this issue due to the gaps that you're still seeing. The article was recently updated and numerous events were added, but I do note that the documentation is incomplete - I will refer the issue to the product team owner for further discovery.

**Comment by KesemSharabi** [comment]
Hi @TravisKale,

Can you please post a snippet of the log containing this event (DeleteDatasetRows)?

Thanks,

Kesem

**Comment by georgedarakji** [comment]
@KesemSharabi below is a screenshot. I am pulling the audit log using the API and this is what I am getting in the screenshot. 
![image](https://user-images.githubusercontent.com/57322126/145628362-9d637409-040a-458a-a517-493a7325066e.png)
@TravisKale please jump in if you can and provide a snippet too

**Comment by KesemSharabi** [comment]
Thanks @TravisKale, I'm pulling the engineering team to look into this and will update you shortly.

**Comment by georgedarakji** [comment]
Hi @KesemSharabi. I can see that the DeleteDatasetRows activity was added to the documentation but it is still not clear what this activity represents. It will be great if you can explain it in the Notes field. Does it represent rows getting deleted as a result of a dataset refresh or what exactly is it? Thank you

**Comment by georgedarakji** [comment]
@KesemSharabi @kfollis any update regarding my last post please?

**Comment by KesemSharabi** [comment]
Hi @TravisKale,

`DeleteDatasetRows` Indicates that the [Push Datasets - Datasets DeleteRows](https://docs.microsoft.com/rest/api/power-bi/push-datasets/datasets-delete-rows) API was called.

I added this information to [Operations available in the audit and activity logs](https://docs.microsoft.com/power-bi/admin/service-admin-auditing#operations-available-in-the-audit-and-activity-logs).

Thank you for your patience and for getting involved.

Kesem
