### ISSUE TITLE
there is no thousand separator in Card Visual if you want to have big number as result of SUM

### ISSUE THREAD

**Issue by kgliang** [MicrosoftDocs/powerbi-docs#1853]
" For example, 125.8K instead of 125,832.00." this is a false statement since there is NO thousand separator (,) in the Card Visual. please correct me if I was wrong here. thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b39f54-b688-a2e0-2097-76abe2086b7c
* Version Independent ID: 6376d063-b0b2-21f2-4fb8-506a016caf7d
* Content: [Card visualizations (big number tiles) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-card)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-card.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-card.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @kgliang ,
Yes, it is doable.  If I select "thousands" for **Display units**, and set the decimal places to 2.  For example, I have a card that is displaying 18K.  **Display units** is "Auto" and **Value decimal places** is "0".  If I select "Thousands" and "2" my card will display $17,674.05K.  I hope this answers your question.
@mihart
