### ISSUE TITLE
Please add Pro License Incremental License Functionality

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#1854]
Incremental Refresh functionality needs to be enabled for pro license also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by gerardv** [comment]
It is, actually, as per this month's update: https://powerbi.microsoft.com/nl-nl/blog/power-bi-desktop-february-2020-feature-summary/#_Incremental_refresh

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Anmolgan81.

I've assigned this issue to the doc author for review.

**Comment by Huwei612** [comment]
Hi. Thanks for this great update. I am on Power BI Pro account and it gives me error when publish the datasets with incremental refresh to myworkspace. It says it need a premium workspace. please help

**Comment by cmajka** [comment]
I am also receiving the same error as Huwei612. I go through the steps to configure the IR and when i'm ready to publish to the service, It throws an error stating "You can only publish datasets with incremental refresh to premium workspace."

**Comment by GTModeler** [comment]
seeing the same notification: This dataflow contains entities with active incremental refresh policies, which require Premium to refresh

**Comment by KonradLeffler** [comment]
I get the same error. "You can only publish datasets with incremental refresh to premium workspace."

**Comment by cmajka** [comment]
I believe this issue was related to not having downloaded and installed the latest version of PBI Desktop. I thought i had it but apparently i did not. Once i installed the latest version, the error went away - now i have a new issue! lol

**Comment by shishirmax** [comment]
My Incremental refresh is not working when I published the PBI to PBI Services.
Even in the PBI Desktop it does not seems to be working as the complete data refresh is taking more than 2hrs.
Over PBI Services it shows Time out as an error.

**Comment by davidiseminger** [comment]
Sorry to hear about this (and happy that an update to the latest Desktop release helped!). For the last issue, your best avenue for support / information is going to be from the Power BI Community, found at https://community.powerbi.com. If that doesn't help, you can get support by going to https://support.powerbi.com. 

Thanks for the conversation, and your persistence in getting the refresh working for Pro.
