### ISSUE TITLE
Incremental Refresh not a Preview Features option

### ISSUE THREAD

**Issue by sheepworrier** [MicrosoftDocs/powerbi-docs#1855]
Is there another step needed to enable this?  I have the 64-bit February 2020 version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sheepworrier.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

Also, can you please provide some more details such as what you're trying to do, and what have you done so far?

**Comment by sheepworrier** [comment]
I've downloaded the latest 64-bit version of the desktop software:

![image](https://user-images.githubusercontent.com/9438974/74844446-5b5df100-5325-11ea-82eb-a5580fe697da.png)

However, there is no checkbox to enable Incremental Refresh like there is in the equivalent documentation screenshot:

![image](https://user-images.githubusercontent.com/9438974/74844662-b263c600-5325-11ea-92a4-110d9b2771d4.png)

**Comment by PunchcardCoder** [comment]
Incremental refresh is now generally available, hence it's not showing as a preview option anymore. I just tried it on a pro account and it is working as expected. Thumbs up to the powerbi team!

**Comment by sheepworrier** [comment]
Thanks - documentation updated to remove misleading screenshot about Preview Features
