### ISSUE TITLE
Authorize Uri 404

### ISSUE THREAD

**Issue by code-po8** [MicrosoftDocs/powerbi-docs#1856]
I'm now receiving a 404 when trying to hit https://login.microsoftonline.com/common/ with or without a query string as shown in the example.  I assume the link has changed again.

--edit--
For background, I'm trying to translate the C# code into PHP, so I don't have access to Properties.Settings.Default.AADAuthorityUri to know what URI is returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users & get Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#feedback)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @code-po8 , thanks for reaching out to us. I am forwarding your comment on to the doc author to see about that URL that is mentioned in the article. In the meantime, you might also check with the [Power BI Community]( https://community.powerbi.com); perhaps someone there has experience with what you're talking about.

**Comment by KesemSharabi** [comment]
Hi @code-po8,

To the best of my knowledge the link hasn't changed.

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
