### ISSUE TITLE
Expression Connection String

### ISSUE THREAD

**Issue by EricMaibach** [MicrosoftDocs/powerbi-docs#1859]
This document states that it applies to Azure SQL databases, and it also states that in Report Builder, in the 'Data Source Properties' dialog there should be an 'expression (fx)' button for entering an expression for the connection string.

I have the latest version of Report Builder installed, and when I look at the Data Source Properties dialog for a Azure SQL Database there is no 'expression (fx)' button.  

Furthermore, if I do enter an expression for the connection string then Power BI will not longer allow me to upload the .RDL file, stating that 'the definition of the report is not valid or supported by this version of Reporting Services.'.  I did verify that the connection string expression was correct by running it locally in the Visual Studio report editor.

So are connection string expressions supported in Power BI Paginated reports? 

Thank You

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce53723-1aab-8da6-9d14-de6414115204
* Version Independent ID: 84b52d10-86d7-51af-0fb6-dd497bf68beb
* Content: [Embedded data sources for paginated reports in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-embedded-data-source#feedback)
* Content Source: [powerbi-docs/paginated-reports-embedded-data-source.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-embedded-data-source.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @EricMaibach , thanks for your question. I am forwarding your comment along to the doc author for consideration. In the meantime, you might also try looking in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @EricMaibach -- you're right, connection string expressions aren't supported in Power BI Paginated reports. We've removed that from the article to avoid future confusion. Thanks for bringing it to my attention!
