### ISSUE TITLE
Publish and export dataset to Power Bi

### ISSUE THREAD

**Issue by ChristopherSt-Pierre** [MicrosoftDocs/powerbi-docs#1860]
After a discussion with Microsoft support, it seems that the function of publishing to workspaces has been deprecated...

EDIT:

The only capability available is the publish to "My Workspace". No more Shared Workspaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d15b3b2-c33a-9293-a6f2-749d164d1f1c
* Version Independent ID: 5bafb24c-0e82-7b95-1bc5-468debe8111a
* Content: [Publish to Power BI from Excel 2016 - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-from-excel#feedback)
* Content Source: [powerbi-docs/service-publish-from-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-from-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @ChristopherSt-Pierre , thanks for your observation. I am passing it along to the doc author to check out the situation. Thanks!

**Comment by rudzimj** [comment]
You can still publish to workspaces from a local file. You can only publish to "My Workspace" from a file on OneDrive.

**Comment by davidiseminger** [comment]
Thanks for the clarification. I've added clarification to the article - much appreciated!
