### ISSUE TITLE
Incorrect text for Filter specification?

### ISSUE THREAD

**Issue by CarrieAnne** [MicrosoftDocs/powerbi-docs#1861]
Should:
Filter specification will flow from CompanyProject to CompanyEmployee (as shown in the following image), but it won’t flow up to CompanyEmployee.
Say:
Filter specification will flow from CompanyProject to ProjectHours (as shown in the following image), but it won’t flow up to CompanyEmployee.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-create-and-manage-relationships#understanding-additional-options)
* Content Source: [powerbi-docs/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @CarrieAnne , thanks for your observation. It certainly looks like you are correct, but I am forwarding it on to the doc author for confirmation in any case. Thanks for reaching out to us!

**Comment by davidiseminger** [comment]
Hi @CarrieAnne  - yes, it should! Sheesh - thanks for pointing that out. I've fixed that in the article, which will be updated soon. Thanks for the close read, keen eye, and for sending this correction our way!
