### ISSUE TITLE
I cannot see Data Category in Modeling tab

### ISSUE THREAD

**Issue by nehuenlihue** [MicrosoftDocs/powerbi-docs#1862]
I downloaded the last version 2.78.5740.721 February 2020 (spanish version) but I cannot see Data Category in Modeling tab. What could be the problem here?

![Capture](https://user-images.githubusercontent.com/16430901/74940603-733e7f00-53d0-11ea-95c6-ab3c2695d884.JPG)

Thanks in advance.

**Comment by paulinbar** [comment]
Thanks for your comment, @nehuenlihue . This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try the Power BI [support page](https://support.powerbi.com).  Thanks!
