### ISSUE TITLE
data updated

### ISSUE THREAD

**Issue by jontybuk** [MicrosoftDocs/powerbi-docs#1863]
if I'm using a field which is date stamped when a user updates any item in the table, how does incremental refresh handle this? will it overwrite the row or add a new row? e.g. i'm storing 5 years worth of data, a user updates a record thus adding a new timestamp, will the information in the stored data be replaced. or a new row be added in the refresh?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @jontybuk, thanks for reaching out to us. I am not sure this is a documenation question, but I'm forwarding it on to the doc author for consideration in any case as a possible doc enhancement. In the meantime. You might find an answer to your question in the [Power BI Community]( https://community.powerbi.com) or with Power BI [support](https://support.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment, @jontybuk. As Paul mentioned, this does indeed look like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
