### ISSUE TITLE
Very important page

### ISSUE THREAD

**Issue by Joe8908** [MicrosoftDocs/powerbi-docs#1864]
Hi this page explains very well how to configure a Registered Application to access Power BI.
It took me 1/2 a day to find it as all other Power BI Embedded docs referred to setting up with ordinary accounts. They referred to the fact that you could also use ApplicationID and Secret, but did not Link to this page to show how.
Please get those pages linked to this page.
Well done on this page BTW.
JK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @Joe8908 , thanks for the kind words and also the helpful, specific suggestion. It's really great to get feedback like this that helps us improve the docs. The doc author will be pleased to know you found the article useful, and I'm sure he'll be glad to act on your suggestion in order to make the article easier to find. Thanks again!

**Comment by KesemSharabi** [comment]
Thank you for your comment, @Joe8908.

We're in the process of updating and refreshing the embedded analytics content. As part of this process we'll update the [Service principal with Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal) article, and make sure it is linked to from other relevant documents.

Please note that this may take some time.

Kesem
