### ISSUE TITLE
Close...but

### ISSUE THREAD

**Issue by DaveStabilify** [MicrosoftDocs/powerbi-docs#1865]
Issue #1: Why can the parameters only be applied to date/time data types??? Best practice says to split date/time fields into separate date and separate time fields.  So I have NO fields where this can be used.
Issue #2: What is the purpose of filtering the data in Power Query? What are the parameters supposed to represent? This is very poorly illustrated.
Issue #3: Why can't the RangeEnd value be dynamic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @DaveStabilify , thanks for reaching out to us. We are the doc team - I think your comments are mix of product questions and doc questions. For your questions 1 and 3, I suggest you submit them to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi) or engage with the Power BI engineering team in the [Power BI Community](https://community.powerbi.com). Regarding question 2, I am forwarding it along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Hi @DaveStabilify - thanks for your questions, and Paul is correct that 1 and 3 are product feedback items best put tot he Power BI Ideas or community pages. On 2, filtering the data in Power Query enables you to optimize the data being incrementally refreshed - targeting only the data that would benefit from being refreshed - and thereby increasing performance. I hope that helps.
