### ISSUE TITLE
Incremental Refresh for Pro not recognized when published

### ISSUE THREAD

**Issue by cmajka** [MicrosoftDocs/powerbi-docs#1868]
After going through the steps to configure IR with my Pro license, i click Publish and immediately receive a window that states: "You can only publish datasets with incremental refresh to premium workspace."

![image](https://user-images.githubusercontent.com/52413144/74975800-a3e4df80-53f5-11ea-922d-d8ea4294d66f.png)

**Comment by paulinbar** [comment]
Hi @cmajka , thanks for reaching out to us. Can you send a reference to the article you are referring to? Also, it sounds like you were annoyed by having gone through the whole procedure only to get that notification. Would you have been spared the effort if there had been a note at the beginning of the article stating licensing requirements? Thanks.

**Comment by cmajka** [comment]
Hi @paulinbar - the incremental refresh should now be generally available for all Pro license users with the February 2020 Power BI Desktop update - article here: https://docs.microsoft.com/en-us/power-bi/desktop-latest-update

I don't see any issues with the article and license requirements - they are plainly spelled out. I believe i am receiving an error incorrectly - unless it hasn't fully been rolled out to everyone yet.

Thanks

**Comment by paulinbar** [comment]
Hi @cmajka . Adding @davidiseminger

**Comment by KonradLeffler** [comment]
I get the same error. Any news on the issue?

**Comment by cmajka** [comment]
I have not received any news on this issue and haven't been able to find much info online either - at this point it's pretty much a black hole.

**Comment by paulinbar** [comment]
Hi @christianwade , can you shed any light on the issue that @cmajka and @KonradLeffler are experiencing?

**Comment by christianwade** [comment]
Can you please try the latest version of Power BI Desktop? The Feb release should have removed that limitation in the publish dialog

**Comment by paulinbar** [comment]
Hi @KonradLeffler and @cmajka , can you try what @christianwade suggests? And if that still doesn't work, I suggest filing a bug at the [Power BI support site](https://powerbi.microsoft.com/en-us/support/) (looks towards the bottom of the page). Issues opened there are tracked.

**Comment by cmajka** [comment]
I thought that i had installed the latest version of PBI desktop, however i was wrong - my apologies. I went and installed the February version and it allowed me to publish the data set with no issues.  However, now i receive an error that 'Parameters haven't been defined for this data set. If you want to set parameters, use the Query Editor." I've followed the instructions for setting up the parameters, so i'll go ahead and file a bug at the support site. Thanks for your help!

**Comment by KonradLeffler** [comment]
Thank you @paulinbar and @christianwade  for your help! After making sure that I had the latest version of Power  BI Desktop installed, it works fine to publish a report with Incremental Refresh to a Pro workspace. Thank you!

**Comment by paulinbar** [comment]
Hi @KonradLeffler and @cmajka , Great! Thanks for letting us know. I am glad things seem to be working out. Christopher, I hope you manage to get the problem with the parameters solved. In the meantime I'll close this particular issue. Good luck with everything!
