### ISSUE TITLE
Differences with the Data Management Gateway

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#187]
It'd be useful to add a link to this page pointing to a new page explaining the differences between the Power BI Gateway and the Data Management Gateway (used by Azure Machine Learning Studio and Azure Data Factory).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb1195df-a72b-61c1-3490-64ca851e81b1
* Version Independent ID: 8e9e2f51-78eb-7dfc-8195-cf99bd55d61c
* Content: [What are Power BI gateways? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started)
* Content Source: [powerbi-docs/service-gateway-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-getting-started.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@arthiriyer - I'll add this as part of the gateways doc update.

**Comment by mgblythe** [comment]
We added a question to the [gateway FAQ](https://docs.microsoft.com/data-integration/gateway/service-gateway-onprem-faq):

Question: Are the on-premises data gateway and the Data Management Gateway (used by Azure Machine Learning Studio and Azure Data Factory) the same thing?
Answer: No, they are two different products. To get more information about the Data Management Gateway (now called Self-hosted Integration Runtime), see Create and configure a self-hosted integration runtime.
