### ISSUE TITLE
Package Request

### ISSUE THREAD

**Issue by daniellemmas** [MicrosoftDocs/powerbi-docs#1870]
Hi there, 

I'm just wondering if it is at all possible for the following packaged to be added as a Support Package for R in Power BI? 
processanimateR v1.0.0 https://cran.r-project.org/web/packages/processanimateR/processanimateR.pdf 

The email address to request through is invalid. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#feedback)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by sheepworrier** [comment]
Funnily enough, I just requested the same package and discovered that the email address isn't working :-)

**Comment by davidiseminger** [comment]
Sorry for the inconvenience - not sure why that alias no longer works. I've updated the article so others don't have to send emails into the abyss, and updated it with guidance about how to submit ideas for R packages. Please submit those ideas to feature ideas - https://ideas.powerbi.com.

**Comment by koureasstavros** [comment]
https://ideas.powerbi.com/ideas/search-ideas/?q=PROCESSANIMATER&forum=+%22Power%20BI%20Ideas%22
