### ISSUE TITLE
RLS and Workspace access associated with this feature.

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#1871]
Please include a section of in depth detail regarding the security features or the access requirement associated with sharing the report via QR code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b935cd03-7dc8-c8cc-2e9c-8d7956270d8d
* Version Independent ID: f9b14089-3720-2ea0-416c-7c798fb62ce3
* Content: [Create a QR code for a report to use in Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-qr-code-for-report#feedback)
* Content Source: [powerbi-docs/service-create-qr-code-for-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-qr-code-for-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @dhruvinushah , thanks for your comment. I am forwarding it along to the doc author for consideration. In the meantime, you might find useful information in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @dhruvinushah -- still a valid question. Reassigning it to new article owner.

**Comment by paulinbar** [comment]
Hi @dhruvinushah, sorry for the VERY delayed response. In any event, a QR code is just a representation of a link to a report. Once scanned, the code is decoded as report link and then the app opens the report as any other report, and will be able to see whatever their Power BI permissions and RLS allow them to see.  If the user does not have access, the report won’t open and a "request access" flow start. I hope this answers your question.
I will take your suggestion and add a note to the article that explains what I just mentioned above.
Thanks for the question!
