### ISSUE TITLE
Does still exist the app?

### ISSUE THREAD

**Issue by AlejandroDominguez89** [MicrosoftDocs/powerbi-docs#1872]
I was wondering if the app still exist. I go trought step 2 on the "Connect to QuickBooks Online with Power BI" documentation. 
It seems that the app doesn't exist, I just type "quick" on Apps/GetApps/Appsource/Apps and nothing appears. 

Could you help me? Do I need special rights? I'm a power bi pro user. 

![image](https://user-images.githubusercontent.com/57954807/75060195-fbda1f80-54a3-11ea-86ea-952c7af1c86a.png)

**Comment by maggiesMSFT** [comment]
Hi, @AlejandroDominguez89 -- you're referring to this article, right?
https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online
Hmmm, I'm not seeing the QuickBooks app in AppSource either. @teddybercovitz , does it still exist?
cc @paulinbar

**Comment by AlejandroDominguez89** [comment]
@maggiesMSFT Yes! I was reading a lot of documentation about this app or service that you can relate to your workspace just typing "quickbook" on the apps (or services) but I couldn't find it.

**Comment by teddybercovitz** [comment]
Hi, we fixed the QuickBooks connector problems this past month and now made it go live again. 
https://appsource.microsoft.com/product/power-bi/pbi-contentpacks.pbiapps-quickbooksonline?tab=Overview

**Comment by maggiesMSFT** [comment]
Thanks, @teddybercovitz ! Closing this issue.

**Comment by AlejandroDominguez89** [comment]
Thank you All guys, I appreciate it!
