### ISSUE TITLE
Guest users not allowed

### ISSUE THREAD

**Issue by Data-touille** [MicrosoftDocs/powerbi-docs#1873]
Guest users aren't allowed to 'analyse in Excel' a dataset sent from another tenant.
I am pretty sure they were able to do this in the past (assuming they had a Power BI Pro license). Am I wrong? Are you working on it ? Otherwise, you should mention this limitation on the documentation !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Data-touille. We’ve assigned your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Sorry for the inconvenience - I've added that to the requirements section. Thanks for posting!
