### ISSUE TITLE
Sample file doesn't match the videos

### ISSUE THREAD

**Issue by Krays23** [MicrosoftDocs/powerbi-docs#1876]
Video: Modeling and transforming data shows a different file being worked on its not the financial sample in video. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423bed63-655a-3079-815e-0d9a8c7de44d
* Version Independent ID: ed119c4a-d4f0-7458-fd57-d7247edbd70e
* Content: [Download the Financial Sample workbook for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-financial-download#feedback)
* Content Source: [powerbi-docs/sample-financial-download.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-financial-download.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @Krays23. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Krays23 -- thanks for your comment! Could you include a link to the article containing the video? I'll need that to address the issue.
thanks again --

**Comment by R-Rustamli** [comment]
https://docs.microsoft.com/en-us/learn/modules/get-data-power-bi/4-clean-data-query-editor

in the video there is a access file

**Comment by maggiesMSFT** [comment]
Thanks, @R-Rustamli and @Krays23 ! I've contacted the author of the Learn content, who is going to fix the links in those articles to go to other data sources. I'm closing this issue.
Thanks again!

**Comment by heyrob** [comment]
Thank you for catching this. The module switches between a sample Excel sheet and an Access database. The link to the Access db in the video has been added to the unit content.

**Comment by maggiesMSFT** [comment]
Thanks, @heyrob !

**Comment by R-Rustamli** [comment]
@maggiesMSFT @heyrob  thank you
