### ISSUE TITLE
Detect Data Changes failing in Pro incremental refresh on Service

### ISSUE THREAD

**Issue by datahai** [MicrosoftDocs/powerbi-docs#1877]
I'm getting an error when I enabled the Detect Data Changes option in the new Pro Incremental refresh feature.  My data source is an Azure SQL Database in North Europe.  Without enabling this feature, incremental refresh works fine in the service when refreshing.  The error I get in the service when refreshing if the Detect Data Changes is enabled (the column I'm using in a different datetime column) is:

Message: Resource name and Location need to match. Resource name: DWIncremental FactPurchase. Location: Polling_36686F87_B3FA_4760_A613_9C6D47A37170.
Cluster URI: WABI-UK-SOUTH-B-PRIMARY-redirect.analysis.windows.net
Activity ID: 86c1f61d-9449-460b-b1c3-af4c2b989a25
Request ID: 0952351a-5ce0-d781-a883-4da446ec2abc
Time: 2020-02-23 21:50:45Z

 
My Power BI service region is UK South so I'm wondering if the data source needed to be in the same region so I created a SQL Database in UK South but I'm getting the same issue.

**Comment by mihart** [comment]
Thanks for your comment, @datahai . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
