### ISSUE TITLE
unable to delete existing Power BI Metrics App

### ISSUE THREAD

**Issue by deepu299** [MicrosoftDocs/powerbi-docs#1878]
I am unable to delete the app installed in March 2019, I have tried at least 40 times, whenever I refresh the browser it keeps coming. Is there any way to delete the app completely. Without deleting it if I install new app, it is showing data from April 2019

**Comment by mihart** [comment]
Thanks for your comment, @deepu299 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
