### ISSUE TITLE
This is all just not accurate anymore

### ISSUE THREAD

**Issue by Panzerbjrn** [MicrosoftDocs/powerbi-docs#1879]
This page may have been accurate at some point, but now it is full of errors.
Someone should really take the time to go through this and update it. 
Blob Container? What is that? Do you mean Storage Container?

In the step where you write: "In the search bar, type Power and a collection of Object IDs for Power BI and Power Query applications appear." I get 30-40 results. Maybe you could be a bit clearer about what you are after?

And it doesn't get any better from there. These instructions are really bad, even by tech industry standards. They are so bad, they could almost be VMware documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by 274188A** [comment]
"they could almost be VMware documentation." LOL

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Panzerbjrn.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, and hope that the content is now clearer. Thanks for your feedback.
