### ISSUE TITLE
Limitation: Row-level-security does not apply to viewer role with dataset build permission in Analyze in Excel

### ISSUE THREAD

**Issue by TrutzS** [MicrosoftDocs/powerbi-docs#1880]
We've build a data model with dynamic row-level security using the UserPrincipalName() function. All works fine in the service when we add users with viewer permission to the app workspace.
In a second step we add the "Build" permission on the underlying dataset for some users with "Viewer" role.
Now the users can create new reports, connecting to the dataset in Power BI Desktop and the RLS permissions still apply.
But when the users use "Analyze in Excel" on the dataset, the RLS no longer works.
If we publish the app workspace as app and hand users a build permission via the published app, the RLS works fine with Analyze in Excel. But, of course, getting this to work in the app workspace would be better, because I can set a more granular level, who gets a build permission instead of all published app members.
It is either a bug of the product or a limitation that should be stated explicitly here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @TrutzS , thanks for reaching out to us with your comment. I am forwarding it along to the doc author for further consideration. In the meantime, you might try asking in the [Power BI Community]( https://community.powerbi.com) or on our [support page](https://support.powerbi.com). Thanks!

**Comment by Bmatix** [comment]
@TrutzS I have a question for you, did you shared the app outside your domain, like to external users?

**Comment by addaaddaadda** [comment]
Hi, is there any update about this issue ?
Thanks.

**Comment by Oddjobe** [comment]
I have a customer with the same ask. Any updates on this ?
Thanks

**Comment by LukaszPawlowski-MS** [comment]
RLS doesn't apply to a user if they have edit permission on the dataset. If a user is an Admin, Member, or Contributor to a workspace a dataset is in, they have edit permission on the dataset.

If the user who ONLY has Viewer role with Build permission added uses Analyze in Excel, RLS should be fully in effect like it is for Power BI desktop.

Can you share the exactly permissions on the dataset a user you're referring to has? You'll find it in the Manage Permission pane for the dataset. Remember that a user may get permissions to the dataset through groups they are in. The user will get the sum of all the permissions they've been assigned individually or through groups.

**Comment by addaaddaadda** [comment]
Tkx Lukasz for your comment.

The access is provided to the application for the users :
![image](https://user-images.githubusercontent.com/70952785/93255109-b8296900-f799-11ea-9f14-c623658724ae.png)

And they are assigned to a specific role with filter on attribute :
![image](https://user-images.githubusercontent.com/70952785/93255278-fd4d9b00-f799-11ea-90c0-8f681cf53656.png)

In the manage permission of the dataser the user has these permissions :
![image](https://user-images.githubusercontent.com/70952785/93255344-15251f00-f79a-11ea-9a09-b87fc8fb0b8d.png)
 
FYI the users can access to the app and report is filtred as per there role, but when they try to do an analysis in Excel they get a message error "XML parser". But they can analyze in Excel another report on which there is no RLS security defined.

Hope I was clear and thanks in advance.

**Comment by LukaszPawlowski-MS** [comment]
Look like they're configured correctly for RLS. The issue is this XML parser issue. Please open a support ticket so someone can investigate the root cause of the issue. It's not something we can diagnose in comments on the documentation.

**Comment by paulinbar** [comment]
Hi @TrutzS. I am in the process of rewriting the RLS docs now and will see whether there is something from your issue that needs to be addressed in the documentation as opposed to the product. In the meantime I'm closing this issue. Thanks for your comments!
