### ISSUE TITLE
The information is quite old so I recommend to update the page

### ISSUE THREAD

**Issue by kenakamu** [MicrosoftDocs/powerbi-docs#1881]
Great article, but a bit confusing as the information is old and incomplete.
Only way to figure this out is actually look into existing sample repository which is not ideal for the people new to our doc.

Could you please consider updating it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e31ebbc-e248-fc7f-24cf-6e5e9ae04eef
* Version Independent ID: 85ba273c-34bf-bb77-ff62-a9bfc454c63f
* Content: [Introduction to unit tests for Power BI visual projects - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/unit-tests-introduction#feedback)
* Content Source: [powerbi-docs/developer/visuals/unit-tests-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/unit-tests-introduction.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thank you for your comment @kenakamu.

We're in the process of updating the Power BI visuals docset. As part of this process, we'll also update the tutorials.

Please take into account that this may take some time.

Kesem

**Comment by zafaralam** [comment]
Is there an update on when this content on unit testing power bi custom visuals will be updated?

**Comment by lund76** [comment]
I'm trying to piece together a working test for a Custom Visual project I have taken - and this guide is very confusing, because it's so incomplete

**Comment by ashfaqdawood** [comment]
I agree to the other comments here, the reference code in the doc is old, the referenced bar-chart git library itself does not have the tests incorporated and is a bit confusing with half baked information about imports and such.
