### ISSUE TITLE
Copy report and edit in PowerBi Desktop?

### ISSUE THREAD

**Issue by CristianAven** [MicrosoftDocs/powerbi-docs#1882]
Hi. Is there any way to copy the report and edit it in the PowerBi Desktop?
That's something we need, as it will allow multi-developer (or users) to work on the same data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces (Preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-datasets-copy-reports)
* Content Source: [powerbi-docs/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @CristianAven -- currently you can't do that, no, although with the right permissions you can copy a report to another workspace and modify it there. I suggest providing that feedback request at the Ideas site, https://ideas.powerbi.com/forums/265200-power-bi.
