### ISSUE TITLE
Updating Plotly Package on Service

### ISSUE THREAD

**Issue by johnneil17** [MicrosoftDocs/powerbi-docs#1884]
Plotly package is failing. Was wondering if this could be updated?

**Comment by maggiesMSFT** [comment]
Hi, @johnneil17 -- this doesn't appear to be a question about an article in the documentation. I suggest you go to https://community.powerbi.com/ for suggestions, or to support https://powerbi.microsoft.com/en-us/support/. 
If it is a question about an article, please reopen and indicate the article.
thanks!
