### ISSUE TITLE
Filter a report using query string parameters in the URL: Unstable

### ISSUE THREAD

**Issue by Vicchi21** [MicrosoftDocs/powerbi-docs#1886]
This feature/option does work sometimes, but not always. It never filters sometimes. Also, please let know if this option also works on the embedded URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Vicchi21. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. 

Also, looks like this also is product feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by maggiesMSFT** [comment]
Hi, @Vicchi21 -- thanks for your comment and question! 
I'll check on your embedded URL question. 
For your other comment, "This feature/option does work sometimes, but not always. It never filters sometimes." can you elaborate? I'm not following.

**Comment by joelvega** [comment]
I can also confirm that this feature will stop working sometimes. When it does not work it sends the user to the Power BI log-in screen. After entering credentials, it will throw an error page saying that the page cannot be found.

**Comment by maggiesMSFT** [comment]
Hi, @Vicchi21 -- 2nd comment first:
Also, please let know if this option also works on the embedded URL.
Good news! URL filters are supported in Power BI Embedded. See here: https://azure.microsoft.com/en-us/updates/power-bi-embedded-advanced-url-filtering-capabilities/
I'll update this article with that info and link. Thanks for asking!
for @Vicchi21 and @joelvega, your 1st comment: This feature/option does work sometimes, but not always. It never filters sometimes. These sound like bugs. I recommend contacting support: https://powerbi.microsoft.com/en-us/support/
