### ISSUE TITLE
Out of Date Screenshots

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerbi-docs#1887]
Hello,

Just wanted to let you know that the data type screenshots on this page are out of date. For example, the query editor data type menu image does not show an option for "Percentage"--which is a choice that is now in that menu.

Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-types)
* Content Source: [powerbi-docs/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @bgribaudo. We know we have screen updates for that article, since Power BI Desktop is always marching ahead with new UI elements and features, especially lately. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks again for your comment - I've updated those screens to reflect the current UI.
