### ISSUE TITLE
Maximum Length vs. Maximum Precision

### ISSUE THREAD

**Issue by bgribaudo** [MicrosoftDocs/powerbi-docs#1888]
Hello,

In the description of data types, “decimal number” is noted as supporting values up to 15 digits long. However, I believe 15 digits here is referring to the data type’s maximum *precision*, not maximum *length*. A 64-bit floating point value, when written out, can be many more digits in length than 15 (e.g. have lots and lots of zeros) but only has 15 or so digits of precision. 

Could this be clarified so that readers aren’t left thinking that type decimal number is unable to handle values longer than 15 total digits?

Along the same lines, under “whole number”, it seems like statement “it can represent the largest possible number of the various numeric data types” is actually referring to the largest possible precision of the various numeric data types. Decimal number can hold numbers that are larger than whole number but does not have more digits of precision than whole number.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-types)
* Content Source: [powerbi-docs/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @bgribaudo. I appreciate the close read, and the feedback. I've forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
This is great input @bgribaudo - thank you! I've updated the article to reflect your more *precise* expression of those data types. Truly appreciated, from us and others who read this.

**Comment by bgribaudo** [comment]
Thank you, @davidiseminger!
