### ISSUE TITLE
URLs

### ISSUE THREAD

**Issue by diab-mossa** [MicrosoftDocs/powerbi-docs#1889]
Hi, I can see that only certain Urls/protocols are supported, I just wonder how to add a skype call to the table/matrix. (e.g.: skype:echo123?call) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#feedback)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @diab-mossa -- good question! I'll ask around and let you know what I find out.

**Comment by maggiesMSFT** [comment]
Hi, @diab-mossa -- got an answer already. It's a feature request. Head to https://ideas.powerbi.com/forums/265200-power-bi-ideas to suggest it!
