### ISSUE TITLE
Topojson is not an ESRI data type

### ISSUE THREAD

**Issue by rbrundritt** [MicrosoftDocs/powerbi-docs#1891]
Near the top of the document there is "ESRI/TopoJSON", this should just be "TopoJSON", ESRI is not relevant here. TopoJSON is an open standard created by people who don't work at ESRI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rbrundritt . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @rbrundritt ,
I've updated the shape map visual and it should go live by tomorrow.  Thank you for your help with the docs.
