### ISSUE TITLE
o365 Group linkage incorrect

### ISSUE THREAD

**Issue by v-taitani** [MicrosoftDocs/powerbi-docs#1892]
Deleting workspace V1 also deletes Office 365 groups.
It wasn't a major incident because we were able to restore from the deleted one, but please correct it because the material is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19005ba4-1b45-4a5e-2335-3408eaaffbf5
* Version Independent ID: 3587ce6f-8a2f-34c4-e00b-c28985833249
* Content: [Manage your workspace in Power BI and Office 365 - Power BI](https://docs.microsoft.com/en-us/power-bi/service-manage-app-workspace-in-power-bi-and-office-365#feedback)
* Content Source: [powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-manage-app-workspace-in-power-bi-and-office-365.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @v-taitani -- sorry to hear it, glad it worked out. I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Good point! I've updated the article. The change will go live tomorrow.

**Comment by v-taitani** [comment]
I confirmed that the [en-us] page has been corrected.
Unfortunately, the Japanese page [ja-jp] was left untouched.
Thank you for your continued support.

**Comment by maggiesMSFT** [comment]
Hi, @v-taitani -- you're right, localization of content changes is not instant. The Japanese page will be updated soon. Thanks!

**Comment by v-taitani** [comment]
Hi @maggiesMSFT
Thank you for your response.
I look forward to that time.

**Comment by walkingstar1** [comment]
Clicking on Members in Step 2, redirects to outlook office 365 site (which isn't configured). So the link is actually broken. What causes this configuration ? or how to manage members?
