### ISSUE TITLE
Obsolete statement about members edit permissions

### ISSUE THREAD

**Issue by DavidPROVOST** [MicrosoftDocs/powerbi-docs#1893]
This article says "If you have configured the workspace so that members have edit permissions, the RLS roles will not be applied to them. Users will be able to see all of the data."
There are now 4 roles in New App workspaces, and except the Viewer role, others DO have edit permissions.
By the way, it would be interesting to say here, if "members" and "contributors" bypass the roles the same way admins do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @DavidPROVOST . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @DavidPROVOST. I've noted your comments and will address them in the rewrite of the RLS articles that is now underway. In the meantime I am closing this issue now. Thanks for your input!
