### ISSUE TITLE
Some visual content could improve greatly this page

### ISSUE THREAD

**Issue by simonmijares** [MicrosoftDocs/powerbi-docs#1894]
Histogram are quite useful and in my case was easier to solve it with R, just scarifying some interactivity. With some specifics examples and visual support this page could have been a great place to start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70782244-c01c-bc5b-d266-d9404e02678e
* Version Independent ID: 1fda6a5f-784f-cfee-1352-81619f490814
* Content: [Tips and tricks for creating reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tips-and-tricks-for-creating-reports#feedback)
* Content Source: [powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @simonmijares . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this request into our queue, and will review it with other documentation requests.
