### ISSUE TITLE
Workspace contact list

### ISSUE THREAD

**Issue by YvonneArnoldus** [MicrosoftDocs/powerbi-docs#1896]
It seems you need to configure something to get the AD groups in your contact list because I do not see them or can use them. 

I found that I needed to set "Guest users permissions are limited" in Azure AD to NO (would als be nice to link this here) but that still does not give met the groups. So I would be nice to add content here to articles to make user you can select users and groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @YvonneArnoldus.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @YvonneArnoldus -- thanks for your question. Have you looked at the Azure Active Directory docs? Specifically this article:
https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/users-default-permissions
Let me know if you have further questions.
Thanks!

**Comment by YvonneArnoldus** [comment]
Hi @maggiesMSFT,

I read those but nothing about Power BI. But i think I found the solution it seems only office groups can be used in Power BI and not normal Azure groups. But that was not clear to me.

**Comment by mihart** [comment]
Hi @YvonneArnoldus ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
