### ISSUE TITLE
Remove data source from dataflow in Power BI Service

### ISSUE THREAD

**Issue by makri36** [MicrosoftDocs/powerbi-docs#1897]
Hi,

I, by mistake, added a test-environment data source to one of my dataflows and now I cannot remove it. The fact that the test-environment datasource is still in the dataflows stops me from scheduling updates since for my dataset I no longer accept updated credentials. 

Please support on this.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @makri36. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
