### ISSUE TITLE
Filters from previous selection

### ISSUE THREAD

**Issue by ArpithaGMGowda** [MicrosoftDocs/powerbi-docs#1898]
I have 5 charts in a dashboard, one is **Ring Chart by MAQ Software**  another 4 is **Line and Clustered Column chart**  when I select any value in first chart (Ring Chart) chart, rest all 4 charts got filtered which is fine, but when I selected another data from 2nd chart (Line and Clustered), the 2nd chart got back to the original stage which I didn't expected.

Thank you in advance :)

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ArpithaGMGowda. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
