### ISSUE TITLE
Almost there. When will section\page activity be exposed in the activity.

### ISSUE THREAD

**Issue by PAPutzback** [MicrosoftDocs/powerbi-docs#1900]
I have seen hundreds of posts from users wanting cross work space usage reporting. While this helps it doesn't give enough detail. Plus it requires a Power BI admin to export it. Understandably since this comes from the admin service. It would be nice if the model for the Usage Report could be exposed and use row level security to expose the data that the end-user running the report has access to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#feedback)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @PAPutzback. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
@PAPutzback - thanks for your patience while I investigated. We're working on the requested feature enhancement. Unfortunately I can't give a specific timeline, but we do expect this to be available in the near term.
