### ISSUE TITLE
Rehsare Permissions

### ISSUE THREAD

**Issue by tyvich** [MicrosoftDocs/powerbi-docs#1902]
Could you please update the documentation to describe how reshare permissions are granted on all datasets when publishing an app?  This seems to be built-in functionality.

https://community.powerbi.com/t5/Service/quot-App-Reshare-quot-permissions-keep-coming-back/m-p/958148#M89212

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps#feedback)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @tyvich , thanks for your comment. I am forwarding it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @tyvich -- sorry for the delayed response! Reading through https://community.powerbi.com/t5/Service/quot-App-Reshare-quot-permissions-keep-coming-back/m-p/958148#M89212 and trying it myself, I'm not seeing this behavior. 
If it's still an issue, I suggest creating a support ticket at https://powerbi.microsoft.com/en-us/support/
