### ISSUE TITLE
Wrong title

### ISSUE THREAD

**Issue by Susanthab** [MicrosoftDocs/powerbi-docs#1904]
How does Microsoft decide to failover

**Comment by paulinbar** [comment]
Hi @Susanthab , You have reached the documentation team. Do you have a question about a specific article? Can you provide a bit more information? If you have a general question that isn't related to a specific doc, I suggest you try the [Power BI Community]( https://community.powerbi.com.

**Comment by Susanthab** [comment]
In this doc, https://docs.microsoft.com/en-us/power-bi/service-admin-failover, there is a sub-topic named "How does Microsoft decide to failover". Would that be a correct topic name?

**Comment by paulinbar** [comment]
Hi @Susanthab. Yes, you are right. Good call. Sorry for the delay. Making the change.
