### ISSUE TITLE
None of the source data of the pbix samples is working

### ISSUE THREAD

**Issue by chanmmn** [MicrosoftDocs/powerbi-docs#1905]
https://docs.microsoft.com/en-us/power-bi/sample-datasets#the-power-bi-samples-as-pbix-files 
Have anyone get the pbix and its sources like Excel running. I could not get any one of this running. All broken. 
Screenshot 
https://1drv.ms/u/s!AuZYHSwsevw1j0id8zB35_k03Tze?e=MVHt3j 
https://1drv.ms/u/s!AuZYHSwsevw1j0kv0cR6FAS_m6os?e=ZOhEai 
Can someone check and fix it?

**Comment by paulinbar** [comment]
Hi @chanmmn, thanks for reaching out to us. I have forwarded your comment on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @chanmmn -- thanks for reporting this issue! I can verify that the report in one of your screen shots, IT Spend Analysis.pbix, is not working. However, Sales & Marketing.pbix opens for me. Of the rest of the 8 .pbix files, all the others are working except Opportunity Analysis.pbix. 
For the Excel files, open Excel first, then open the file from within Excel. You need to Enable Editing, then Enable Content, and then you can open the Power Pivot window. I was able to open all the Excel files except IT Spend Analysis. 
Unfortunately we can't fix the files at this point, so I'll remove the links to the files that aren't working. 
Thanks!
