### ISSUE TITLE
How to delete a workspace

### ISSUE THREAD

**Issue by YvonneArnoldus** [MicrosoftDocs/powerbi-docs#1906]
Hi,

I've be click all menu's and options to see if there is a delete there is not. I would be nice to have a section on how to delete a workspace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @YvonneArnoldus , thanks for reaching out to us. You have to be a workspace admin to delete a workspace. But try looking here: https://docs.microsoft.com/en-us/power-bi/service-delete#delete-a-workspace. Basically, in the left hand pane you hover over the name of the workspace, select the three dots you see, and then choose Workspace settings. At the bottom of the Workspace settings window that appears on the right, you will see a delete button, if you have the admin permissions. Let me know if this helped.

**Comment by YvonneArnoldus** [comment]
Thank you it is hidden well but I found it.
