### ISSUE TITLE
Document the maximum length of the "username" parameter when requesting an embed token.

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerbi-docs#1908]
When trying to request an embed token, we discovered the limitation that an identities' username property, can only be 256 characters long.
Is this correct (expected behaviour)? Can this be added in the documentation?

thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#applying-user-and-role-to-an-embed-token)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @w0ut0 , thanks for your comment. I have forwarded it on to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @w0ut0,

I added a note to [Using the CustomData feature](https://docs.microsoft.com/power-bi/developer/embedded/embedded-row-level-security#using-the-customdata-feature) stating that the CustomData username can only be 256 characters long.

Once again, thanks for your feedback.

Kesem

**Comment by shriramcs-ikea** [comment]
Hi @KesemSharabi  thanks for the documentation. However, we have met with a scenario where i need to pass more data using username CustomData. is there a way to pass more data to api ?
