### ISSUE TITLE
Missing Image in step 7a

### ISSUE THREAD

**Issue by UhmBrock** [MicrosoftDocs/powerbi-docs#1909]
Instead of showing the image, the page shows a snippet box with the following inside:
```
![Screenshot of the Font color and Background color options.](media/power-bi-visualization-customize-title-background-and-legend/power-bi-color.png)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355cc0f7-069a-e7af-9ceb-18c9bab1fb46
* Version Independent ID: 853cf3e3-b702-1dc6-e368-56fc1103c6b3
* Content: [Get started formatting Power BI visualizations - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-customize-title-background-and-legend)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-customize-title-background-and-legend.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-customize-title-background-and-legend.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @UhmBrock , thanks for the observation. I have corrected the markdown file so the image should now display correctly when the docs are next built later today. Thanks again!
