### ISSUE TITLE
PostgreSQL requires gateway

### ISSUE THREAD

**Issue by hablaras** [MicrosoftDocs/powerbi-docs#1910]
The table is incorrect; PostgreSQL requires the data gateway to connect and refresh from the Power BI Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @hablaras , thanks for your comment. I am forwarding the article on to the author for consideration.

**Comment by sinisakomlen** [comment]
Is it still not possible to access Postgres without the gateway? Do not get it why the gateway is needed if it is Cloud (AWS)-To-Cloud (Azure) connection.

**Comment by kfollis** [comment]
Hello @hablaras and @sinisakomlen - apologies for the delay. I checked with our engineering team, and the gateway for PostgreSQL is shown as supported, but not required. PostgreSQL has a separate cloud offering and your configuration determines the need for the gateway.

**Comment by sinisakomlen** [comment]
Hi @kfollis 
What does this answer mean in practice? Which configuration is needed for PostgreSQL on AWS so Data Gateway is not required for PowerBI Service refresh? Can you point us to some documentation how to achieve this?

**Comment by kfollis** [comment]
There are some related discussions in community, like this one: https://community.powerbi.com/t5/Power-Query/Connecting-to-PostgresSQL-hosted-on-AWS-RDS/td-p/135666 that may help and you can always post a new question.

**Comment by sinisakomlen** [comment]
The link you provided is for PowerBI Desktop. The question here is if PowerBI Service can refresh from PostgreSQL hosted on AWS, without the Data Gateway. I know it is possible for AWS Redshift.
If this is not possible for PostgreSQL then documentation should be corrected.

**Comment by sinisakomlen** [comment]
@hablaras Would you like to open a new ticket for this? Or you have the option to make it Open again. I do not understand why this ticket is closed as the answer is not given.

**Comment by kfollis** [comment]
Hello @sinisakomlen and @hablaras - I have spoken with our engineering team to get clarification on whether this article needs to be updated based on your feedback. They have not recommended changes and say that there's nothing stopping cloud to cloud refresh of Postgres in AWS, but there also aren't any particular AWS specific capabilities. You may want to post a new question in https://community.powerbi.com or request support through https://support.powerbi.com.

**Comment by sinisakomlen** [comment]
Hi @kfollis. 
I understand it is convenient to keep it as it is but I am as well challenging if Microsoft's statement is correct.
To make it short, you are correct that nothing is stopping cloud-to-cloud refresh, but in case of PostgreSQL data gateway seems mandatory and this is not in line with Microsoft documentation.

As @hablaras named this ticket: PostgreSQL requires Gateway, the documentation says it is not required. There can be only two solutions on this ticket prior to closing it:

- Microsoft explains in which circumstances Data Gateway is not required for PostgreSQL connection in Microsoft Service. Then we admit that documentation is correct.

- Microsoft adjusts the documentation as it is not possible to connect to PostgreSQL in the PowerBI service without the Data Gateway.
