### ISSUE TITLE
Expose TopN Selection and Customize How TopN Aggregates

### ISSUE THREAD

**Issue by indiana-nikel** [MicrosoftDocs/powerbi-docs#1911]
In the "Known Limitations" section, it is mentioned that: "We truncate levels to show top n. Currently the top n per level is set to 10." 

Would there be plans to expose this "top n" variable for customization (say to show only the top &lt;x&gt; instead of 10)? Along the same train of thought, would there also be plans to customize how the rest of the "top n" selection is aggregated (here we are only truncating, but another option could be to sum into an "All Others" category)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @indiana-nikel , thanks for your question. You've reached the doc authors, and I think yours sounds like a product question. I am forwarding your question on to the doc author and perhaps she'll be better able to direct your question.

**Comment by mihart** [comment]
Thanks for your comment, @indiana-nikel . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
