### ISSUE TITLE
Bigquery Required Permissions

### ISSUE THREAD

**Issue by burnzy** [MicrosoftDocs/powerbi-docs#1912]
What are the required GCP BigQuery IAM permissions that are required to access a dataset from powerbi?
(I can't find documentation on permissions anywhere -- if this is mentioned elsewhere, please let me know)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-bigquery#feedback)
* Content Source: [powerbi-docs/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-bigquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @burnzy -- thanks for asking! Referring to the author to investigate.

**Comment by burnzy** [comment]
Hi @maggiesMSFT / @davidiseminger -- wondering if in the meantime, could you please let me know what the required permissions are? We are still struggling to find the minimum required GCP IAM permissions required for powerbi to be able to read from a bigquery dataset. We'd rather not be over-permissive in this case if possible. Do you happen to know?

**Comment by burnzy** [comment]
For any others with the same problem, after some testing it appears that the minimum required GCP roles are `roles/bigquery.jobUser` at the project level, and `READER` special role or just `roles/bigquery.dataViewer` at the dataset level. This allows a user to read data from PowerBI.

**Comment by davidiseminger** [comment]
Thanks for posting this! I'm sure other readers will appreciate seeing this. In terms of doing a full assessment of the credentials required, and documenting them here, we've put this request into our queue, and will review it with other documentation requests.
