### ISSUE TITLE
Facebook option no longer available

### ISSUE THREAD

**Issue by lauratsui** [MicrosoftDocs/powerbi-docs#1913]
Hi, the option to get data from Facebook as an Online Service is no longer available on the latest version of power bi desktop (as of march 2020). Is there a reason? I read somewhere else that it's because facebook retired one of its graph APIs, which power bi was linked to? any way we can still access facebook data from power bi? Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Analyze Facebook data by using Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-facebook-analytics#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @lauratsui -- good question! Referring to the author to investigate.

**Comment by pullmyleg** [comment]
Hi, any update on when this will be back online? Even an indication of timeframe e.g. 1 week, month, a year or never would be great... Thanks!

**Comment by helloworld2019-joy** [comment]
Hi, please advise the way to access facebook data from bi ! thanks a lot!

**Comment by Truc-NguyenThanh** [comment]
I have the same problem, I can't search get data -> more -> online services -> Facebook. Seemingly Facebook data is no longer supported.

**Comment by charlesanands** [comment]
Its not right to keep the Power BI website flashing with Facebook integration, but the connector is missing! When do we expect it to be resolved?

**Comment by davidiseminger** [comment]
Sorry for the inconvenience - I've added a note to the top of this tutorial that warns users that, due to Facebook App permission restrictions, the connector isn't currently working properly. 

From a feature request perspective, you can vote on this feature (to get it working again) at https://ideas.powerbi.com.
