### ISSUE TITLE
Access to Azure Cost details like Management Groups, Azure Cost Management Budgets...

### ISSUE THREAD

**Issue by SamirFarhat** [MicrosoftDocs/powerbi-docs#1914]
Hi,
There is a lot of confusion when a connector uses the EA APIs to get usage data, and we don't know if it will collect data related to Management Groups, Azure Budgets...
Can you please note if the connector will collect data from the Azure Cost Management API in case of EA ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @SamirFarhat -- good question! Referring to the author for more information.

**Comment by davidiseminger** [comment]
Thanks for your input and question. This is more of a product question, especially based on the specific licensing aspect, which would be better answered in a community or support venue.

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
