### ISSUE TITLE
Billing ID and permissions

### ISSUE THREAD

**Issue by ourcloudnetworkcom** [MicrosoftDocs/powerbi-docs#1915]
I have an issue that when referring to 'Billing ID', is it actually referring to the Subscription ID within our Microsoft Partner Network subscription? Also it does not advise of the role assignment requirements? for example, wanting read-only access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Daniel-AFK12 -- good question! Referring to the author to investigate.

**Comment by gregdegruy** [comment]
@maggiesMSFT  did we get an answer on if  Billing ID, is it actually referring to the Subscription ID ? I do not see a billing id in the overview page?
![Annotation 2020-05-05 110623](https://user-images.githubusercontent.com/8151045/81099921-808fe380-8ec0-11ea-9961-e486ea1fcfe2.png)

**Comment by davidiseminger** [comment]
Including the writer responsible for the technical implementation of this connector, too.

**Comment by davidiseminger** [comment]
Hello @ourcloudnetworkcom and @gregdegruy  - here's some clarification. 

As described in the last sentence of the second paragraph, there are specific permissions required.

The Azure Cost Management connector supports two account types: Microsoft Customer Agreement and Enterprise Agreement (EA). Billing profile ID is required for Microsoft Customer Agreement and you can find that at https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#connect-to-a-microsoft-customer-agreement-account. The enrollment number is needed for EA and you can find that at https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#connect-to-an-enterprise-agreement-account

The connector doesn’t support other account types, including CSP (which you might have based on your question). 

Also, the subscription level scope isn’t supported by the connector. For both Microsoft Customer Agreement and EA, the connector gets data at a higher level (Billing profile and EA Enrollment). Both might contain many different subscriptions.

In the screenshot added by @gregdegruy, it shows an internal subscription that isn’t supported.

Hope that helps clarify.
