### ISSUE TITLE
info in this page is bit outdated.

### ISSUE THREAD

**Issue by YassinePBI** [MicrosoftDocs/powerbi-docs#1917]
Dataset size for shared capacity is limited to 1 GB but for premium it can go over 10 GB.
Free users personal storage shows now as 10 GB not 1GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-manage-your-data-storage-in-power-bi#feedback)
* Content Source: [powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @YassinePBI . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @YassinePBI ,
Thank you for your comment.  I noticed that this Git Issue was never closed.  The article has been updated, so I am going to close this Issue.  If you still have documentation suggestions, please let us know. 
All the best,
the DOCS team
