### ISSUE TITLE
Drill through will not traverse a relationship

### ISSUE THREAD

**Issue by ElectricLlama** [MicrosoftDocs/powerbi-docs#1918]
Please add a section on 'what doesn't work'. I've found that if you have a header import table with OrderId and a detail direct query table, also with OrderId, with a relationship defined, drill through doesn't recognise the relationship. i.e. both the source and taget pages need OrderId from one table only. So either the source header page needs the detal OrderId, OR the target detail page needs the parent OrderId. Hopefully you can make sense of this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Use drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ElectricLlama . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thank you for your feedback. After review, we've put this doc request into our queue and will review it with other documentation requests.
