### ISSUE TITLE
Almost - please allow me to set a sync slicer as well.

### ISSUE THREAD

**Issue by dgwilson** [MicrosoftDocs/powerbi-docs#192]
This is a great development in the product and I've managed to figure out my url for filtering.
https://app.powerbi.com/groups/me/apps/....&lt;content redacted&gt;?filter=Date_x0020_Week_x0020_Ending~2FWeek_x0020_Ending_x0020_Date%20ge%202018-08-01%20and%20Date_x0020_Week_x0020_Ending~2FWeek_x0020_Ending_x0020_Date%20le%202018-08-04

It however doesn't quite work for me. I have a Synced filter/slicer on the landing page. What I really need to be able to do is set the value in that slicer as directed by the filter in the url. Then all would be well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @dgwilson 
I'm sorry, but there is no plan to allow you to set the filter state in URL parameters.  You could add it to ideas.powerbi.com and if it gets enough votes the Product team might implement it...

HTH,
Michele
