### ISSUE TITLE
EM-SKU

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/powerbi-docs#1920]
The link to the calculator ONLY gives prices for P-SKU I am still struggling to find the pricing for the EM-SKU.  Why is it so difficult to find?  Even the Microsoft employees only link the calculator which ONLY gives prices for the P-SKU.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-faq#feedback)
* Content Source: [powerbi-docs/service-premium-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rwlpf . This looks like a support / sales request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
