### ISSUE TITLE
Reference to Kimball 2nd Edition -> 3rd Edition

### ISSUE THREAD

**Issue by kaysauter** [MicrosoftDocs/powerbi-docs#1921]
I think the reference to Kimballs book should note that there is a 3rd edition (2013) unless there is a good reason to refer to the older one. 
Suggestion: The Data Warehouse Toolkit: The Definitive Guide to Dimensional Modeling (3rd Edition 2013) by Ralph Kimball and Margy Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema#feedback)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by davidiseminger** [comment]
Thanks for your comment, @kaysauter . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by peter-myers** [comment]
Hi @kaysauter - thanks for pointing out the older book reference. I've updated the article today. #please-close
