### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by pfprado** [MicrosoftDocs/powerbi-docs#1923]
I try to refresh my data from Project Web App to Power BI but I get an error for timeout, how I can to reduce to the PWA data volume, for example the last year? Thanks

**Comment by davidiseminger** [comment]
Hi @pfprado  - could you include the page you're asking about, so we can investigate? Thanks.

**Comment by pfprado** [comment]
Hi @davidiseminger , the page is this:
https://docs.microsoft.com/en-us/power-bi/service-connect-to-project-online
Thanks

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @pfprado ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, your Issue does sound more like a product question than a documentation suggestion.  For product questions, I recommend submitting your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
