### ISSUE TITLE
Typo can can't

### ISSUE THREAD

**Issue by ThomasKwakman** [MicrosoftDocs/powerbi-docs#1926]
**Typo can can't**
When you connect to those multi-dimensional sources by using DirectQuery, you **can can't** connect to another DirectQuery source or combine it with imported data.

**Comment by mihart** [comment]
desktop-storage-mode

**Comment by mihart** [comment]
Thanks for your comment, @ThomasKwakman . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing this out - it's fixed in the currently published article. Thanks!
