### ISSUE TITLE
ExpressRoute document should be restored

### ISSUE THREAD

**Issue by chrolivier** [MicrosoftDocs/powerbi-docs#1927]
The file \articles\powerbi-admin-power-bi-expressroute.md was removed as part of the following commit: 11fe374752b613721e83b9ba39e6e2e2e16baca5

I believe this was a mistake because the information is still relevant and I have not been able to find a replacement for this page on the documentation site as it stands today.

**Comment by mihart** [comment]
Thanks for your comment, @chrolivier . This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @chrolivier - In my review I discovered that the Power BI ExpressRoute article was retired more than 2 years ago. You can find documentation for the ExpressRoute service here: https://docs.microsoft.com/en-us/azure/expressroute/ and a list of Power BI URLs here: https://docs.microsoft.com/en-us/power-bi/power-bi-whitelist-urls. I believe this satisfies the requirements to deploy.

**Comment by otravers** [comment]
For the benefit of people googling their way to this page and left scratching their head as to why integration documentation randomly disappears, here's the aforementioned documentation:
https://github.com/MicrosoftDocs/powerbi-docs/blob/fcebab0706773c2cd57ba45f49c0dfdbbdb6ed3b/articles/powerbi-admin-power-bi-expressroute.md
