### ISSUE TITLE
Migrate to Service Principal Inaccuracy

### ISSUE THREAD

**Issue by boylec** [MicrosoftDocs/powerbi-docs#1928]
Under "Migrate to Service Principal" this page says "However, if you're using the traditional workspaces, copy or move your Power BI artifacts and resources into the new workspaces, and then add the service principal as an admin to those workspaces."

However, can't a user simply go to app.powerbi.com -&gt; Edit workspace -&gt; Advanced -&gt; Upgrade Now without having to copy things over manually to a new workspace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @boylec . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @boylec,

Yes, you should be able to migrate to a new workspace without making any changes.

Also, please note that we upgraded the [service principal](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal) article, and that it now longer includes this advise. In addition, for improved security, you can now use [service principal with a certificate](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal-certificate).

Hope this helps,

Kesem
