### ISSUE TITLE
"Get started with a service principal" section confusion

### ISSUE THREAD

**Issue by boylec** [MicrosoftDocs/powerbi-docs#1929]
Step 1. provides a link to "Register a service-side web application", but when one follows the guide found in "Register a service-side web application" and uses the PowerBI Onboarding Tool to register a new application, it says directly in that tool on the bottom "Note: An application registered here can’t be used as a service principal."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @boylec . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @boylec,

Thank you for your comment.

We've revised the [service principal](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal) article and removed some errors and confusing parts.

Please follow the new instructions - hopefully they'll make more sense now.

Thanks,

Kesem
