### ISSUE TITLE
Unable to connect to VM

### ISSUE THREAD

**Issue by monteleon** [MicrosoftDocs/powerbi-docs#193]
Hi, followed all the steps for setup but receive an error message when trying to connect to the VM. Indicated it might be something to do with Oracle CredSSP. 

Do you have any further information about this?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c7b5d6-c9a4-3445-81c1-41dc41ae0929
* Version Independent ID: a45e9b8a-185b-ff29-dc4a-b8912c13ed1b
* Content: [Tutorial: Explore Power BI Report Server in a VM - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal)
* Content Source: [powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @monteleon -- yes, some folks have seen this problem. Turns out the issue is on your machine, and there's a Microsoft Support article that shows how to fix it: https://support.microsoft.com/en-us/help/4295591/credssp-encryption-oracle-remediation-error-when-to-rdp-to-azure-vm.
Hope that helps!

**Comment by monteleon** [comment]
Hi @maggiesMSFT, finally managed to get in, thank you! Now I'm in, I can't see any of the applications that are supposed to be installed and the report server doesn't seem to be configured either!

**Comment by maggiesMSFT** [comment]
Hi @monteleon -- hmmm, OK, I'll check. I haven't looked at it in a few days.
