### ISSUE TITLE
The Onboarding Embed Tool page

### ISSUE THREAD

**Issue by boylec** [MicrosoftDocs/powerbi-docs#1930]
The embed tool page links to this doc on the bottom where it says "Note: An application registered here can’t be used as a service principal."

But the "Register with the Power BI Application Registration Tool" section on this page seems to imply that using the tool for service principals is completely fine because it mentions selecting certain options if you are expecting to use the app registration as a service principal.

What gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edce6995-b777-06fc-49ee-b23eabf6a862
* Version Independent ID: ffd0c74b-4a05-1019-6897-804d60c13765
* Content: [Register an app to embed Power BI content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/register-app)
* Content Source: [powerbi-docs/developer/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/register-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @boylec . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @boylec,

You're right, you can use service principal in this scenario. We will update the embedding setup tool statement accordingly. The documentation for [service principal](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal) has already changed.

Thanks for pointing this out.

Kesem
