### ISSUE TITLE
Update bookmark after changing visibility of selection

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1931]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/issues/6

@BeFresh78 commented 21 hours ago — with docs.microsoft.com
Please note: When using the selection pane in combination with bookmarks, make sure you right-click on the corresponding bookmark an click "update" after changing the visibility of a selection. Otherwise visibility will revert to default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Use bookmarks in Power BI Desktop to share insights and build stories - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks#feedback)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @CeciAc . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Updating the correct author assignment.

**Comment by davidiseminger** [comment]
I've added a note to that article, to clarify what you pointed out. Thanks for helping out with that, I'm sure other customers will benefit!
