### ISSUE TITLE
The R script that works on my side

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1933]
@Photogratte commented on [Tue Mar 10 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/21)

dataset <- read.csv(file="C:/Users/gmalherbe/OneDrive - Groupe Pichet/Projets/Formation Power BI/Microsoft Power BI R/EuStockMarkets_NA.csv"
                    , header=TRUE, sep=",", dec=".", na.strings="NA")
#summary(dataset)
library(mice)
library(dplyr)
md.pattern(dataset)
tempData <- mice(select(dataset, Day, SMI.missing.values), m=5, maxit=50, meth="pmm", seed=500)
#summary(tempData)
#xyplot(tempData, Day ~ SMI.missing.values, pch = 18, cex = 1)
#densityplot(tempData)
tempData$imp$SMI.missing.values
completedData <- complete(data=tempData, action=1)
output <- dataset
output$completedValues <- completedData$SMI.missing.values
#summary(output)
#plot(select(filter(output,is.na(SMI.missing.values)), SMI, completedValues), col = "RED")
#cor(select(filter(output,is.na(SMI.missing.values)), SMI, completedValues))

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Utiliser le langage R dans l’Éditeur Power Query - Power BI](https://docs.microsoft.com/fr-fr/power-bi/desktop-r-in-query-editor#feedback)
* Content Source: [powerbi-docs/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Tue Mar 10 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/21#issuecomment-597227447)

Hello, @Photogratte
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @Photogratte. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hi @CeciAc  - thanks for posting. I'm sure others will appreciate seeing how the script worked for you, in case they run into trouble with the script provided in the article. Thanks!
