### ISSUE TITLE
Incremental refresh and a model update

### ISSUE THREAD

**Issue by joonassoukki** [MicrosoftDocs/powerbi-docs#1935]
Hi, I could not find from the docs how a model update should be handled? Now it seems that when the incremental refresh is applied, a new version of an existing data model replaces the old one and always starts updating from the scratch. This will cause unwanted wait time when it comes to production usage?

**Comment by mihart** [comment]
Thanks for your comment, @joonassoukki . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
