### ISSUE TITLE
Encounter without SameSite error when visit the embed report 

### ISSUE THREAD

**Issue by f14eagle** [MicrosoftDocs/powerbi-docs#1936]
Hi,

I followed the article and added the report to a HTML page, everything works fine, except some users report that they encountered below issue:

`A cookie associated with a cross-site resource at https://app.powerbi.com/ was set without the SameSite attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with SameSite=None and Secure.`

I have checked with user, the chrome version is 80.0.3987.132. And the 'SameSite by default cookies' is set to Default.

Any suggestions regarding the issue?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-secure#feedback)
* Content Source: [powerbi-docs/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @f14eagle . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @f14eagle -- thanks for sending your issue! Currently investigating. Question I've gotten: "Is this error actually blocking the customer?" 
Is the error keeping users from viewing your report in the HTML page?
Thanks!

**Comment by f14eagle** [comment]
> Hi, @f14eagle -- thanks for sending your issue! Currently investigating. Question I've gotten: "Is this error actually blocking the customer?"
> Is the error keeping users from viewing your report in the HTML page?
> Thanks!

Hi @maggiesMSFT , apologies for the delay. You are correct, user cannot see my reports which is embedded in the HTML page. But there are only few users encounter this issue, I'm not sure if there are some settings in the browser block them.

Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @f14eagle -- here's the answer: please file a support ticket to diagnose what the problem is.
https://powerbi.microsoft.com/en-us/support/
That Chrome warning shouldn’t be blocking a report from loading and there’s probably something else going on.
Hope that helps!

**Comment by f14eagle** [comment]
> Hi, @f14eagle -- here's the answer: please file a support ticket to diagnose what the problem is.
> https://powerbi.microsoft.com/en-us/support/
> That Chrome warning shouldn’t be blocking a report from loading and there’s probably something else going on.
> Hope that helps!

Got it. Thank you.

**Comment by aastroza** [comment]
The warning will be critical in the future, Chrome 80 will reject that kind of cookies: https://www.chromestatus.com/feature/5633521622188032 

Is there any fix getting ready?

**Comment by Hormash** [comment]
I'm working with powerbi-client v2.11.0 in js and getting this warning.

Soon enough, Chrome will block all iframe with this security problem

**Comment by vish02chouhan** [comment]
Hi - It has started blocking to me. Whats the work around?

**Comment by zachpainter77** [comment]
Yes my embedded report is blocked what can I do?

**Comment by maggiesMSFT** [comment]
Hi, @zachpainter77 -- sorry to hear it! I checked with the engineer, who says:
Please file a support ticket to diagnose what the problem is.
https://powerbi.microsoft.com/en-us/support/ 
I don’t understand how the report is blocked because of some app insights cookies.
Hope that helps!
