### ISSUE TITLE
Permission on Shared Datasets

### ISSUE THREAD

**Issue by Estiane** [MicrosoftDocs/powerbi-docs#1938]
Need some explanation regarding the issue we are facing around the shared datasets and the permissions on the model side. I have a premium capacity and we are letting users use this to build reports in their own workspaces. They are admins in their own workspaces and only have read and build permissions on the shared datasets. They do not reside in the workspace itself where the model is (premium capacity). 

We have RLS applied to our model and AD groups to manage all these users. 

When the users create their reports and share them with other business users, the users are added to the permissions. Users that are in an AD group (that have build and read permissions) are added individually again. 

This does not seem correct in the way of working, can someone please help with this?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Estiane. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
