### ISSUE TITLE
Power BI Direct Query Error 

### ISSUE THREAD

**Issue by ebram-sifain** [MicrosoftDocs/powerbi-docs#1939]
Hello everyone, I need help due Direct Query Error  .
I’m trying to contact with Oracle Schema using an Direct Query option but unfortunately it gives me this Error Message:
“Cannot load model 
We couldn't connect to your DirectQuery data source or internal model. Double-check that your server and database names are correct, and that you have permission to access them.

The managed provider 'Oracle.DataAccess.Client' could not be instantiated. Unable to find the requested .Net Framework Data Provider. It may not be installed. “

Noted that  Oracle ODP.net driver
 already installed and also .Net framework
And I can access data sources using loads  option

Please advise , if I need to reinstall anything   Appreciate send Link to download

**Comment by paulinbar** [comment]
Hi @ebram-sifain , thanks for reaching out to us. You used a channel that gets to the documentation team, and I think you have more of a support question that we can't really help you with. I suggest you try either the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com). Hope you find the help you need!
