### ISSUE TITLE
Permission to create app workspace

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/powerbi-docs#194]
Now that creation of app workspace do not create an Office365 Group. What permission do an user need to create an app workspace? can you please add this in the docs? I tried creating an app workspace(preview version) and received following error.
"App workspace creation is disabled
Creation of app workspaces is disabled by your tenant admin, or you need permissions to create them. Please contact your tenant admin." 
What permission do Tenant admin need to give to the user - please make the permission criteria's explicit in all docs - this is always the blocker in getting started with any feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @subashsivaji -- great question. I've updated the article with a link to the Admin Portal doc, https://docs.microsoft.com/en-us/power-bi/service-admin-portal. That's where we have info about admins and permissions.
