### ISSUE TITLE
account

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1940]
The comments below were machine-translated

@lucas378 commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/34)

How do I reopen an account. because he is no longer of this type with this icon for "reopen your account"

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c12dd3d7-8816-3a42-a21d-2c0600a83b44
* Version Independent ID: 2f443100-7d3c-0766-c0fd-2979cdc41fe4
* Content: [Fechar sua conta do Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/service-admin-closing-your-account#feedback)
* Content Source: [powerbi-docs/service-admin-closing-your-account.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/service-admin-closing-your-account.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

---

@srvbpigh commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/34#issuecomment-597809319)

Hello, @lucas378
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lucas378** [comment]
a conta que estou tentando usar é rafael.porto@grupofortaleza.co
preciso reabrir ela

**Comment by lucas378** [comment]
Algum retorno ?

**Comment by lucas378** [comment]
????????????????

**Comment by lucas378** [comment]
algum retorno ?

**Comment by kfollis** [comment]
Please see this related community thread: https://community.powerbi.com/t5/Service/Unable-to-reopen-a-closed-account/td-p/371394. If you are unable to use these steps and your admin is unable to reassign a license, please visit http://support.powerbi.com for further assistance.
