### ISSUE TITLE
Documentation is unclear in regards to conditional coloring using DAX

### ISSUE THREAD

**Issue by realdanielbyrne** [MicrosoftDocs/powerbi-docs#1941]
The brief section "Color based on a calculation" is unclear and misleading.  
- The section references using a DAX formula but an M formula is shown instead. 
- The formula show is referencing a table, "Expanded State Codes 1" , but that table is not part of the sample referenced on this page.  The screen shot at the top of the page shows only 2 tables, "State codes" and "Best states for sun...".
- Interpolating I added a column to the table Im am trying to color, but it produces an error on every column.

In short the section is not helpful and should be rewritten.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-table-formatting#feedback)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @realdanielbyrne , thanks for your comment. I am forwarding it along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thanks for your feedback, and sorry for the confusion. I've updated that section to remove references to DAX, and we'll come back to the entire section to review rewriting it as time allows.
