### ISSUE TITLE
Full screen mode for tablets

### ISSUE THREAD

**Issue by davecope1982** [MicrosoftDocs/powerbi-docs#1942]
Is it possible to go into full screen mode when viewing reports on a tablet? 

And if so - how? I cannot remove the grey banner, filter pane or report page list from view at all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 052edfa5-0db0-da15-88c0-7841f4149347
* Version Independent ID: fa7d4f3d-6480-700b-bd67-3edcc464859b
* Content: [Focus mode and full screen mode - how to zoom in to see more detail - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-focus)
* Content Source: [powerbi-docs/consumer/end-user-focus.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-focus.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @davecope1982 , what tablet are you using? Are you viewing the report on the Power BI service or are you using the Power BI mobile app?

**Comment by davecope1982** [comment]
On an iPad using the mobile app

**Comment by paulinbar** [comment]
Hi again @davecope1982 . Judging from this https://docs.microsoft.com/en-us/power-bi/consumer/end-user-focus#what-is-full-screen-mode, and also my own experience, I believe that full screen mode with reports is only possible for Windows 10 mobile apps, not on iOS and Android. However, I can ask some people and get a definitive answer for you, but I might not be able to get that until Sunday. I can get back to you by then, if not before.

**Comment by paulinbar** [comment]
Hi yet again, @davecope1982 ... now I am not sure.. do you have towards the upper right of your screen a diagonal two-headed arrow? That is supposed make the report go to full screen.

**Comment by paulinbar** [comment]
@davecope1982 
![image](https://user-images.githubusercontent.com/54644589/76575626-6e00bb80-64c8-11ea-8d34-dafa7596b0a4.png)

**Comment by davecope1982** [comment]
![Open PowerPlatformDemoADCMotors007 in Power BI](https://user-images.githubusercontent.com/49394333/76608702-ffdee780-650d-11ea-86fb-a99a51b384ed.png)

**Comment by paulinbar** [comment]
Hi @davecope1982 , ok, I have a feeling that full screen for reports must not supported for the iPad, since I am pretty sure that if it was there, you would have found it. It may be available for tiles.. i.e. if you open up one of the tiles on the report you might see those arrows. But let me check with the app developers, and I'll get  back to you. As I said, that might not be until Sunday, since it is the weekend here already. Sorry for the delay.

**Comment by paulinbar** [comment]
Hi @davecope1982 ,
I asked the Mobile app people, and indeed, the full screen for reports is currently only supported for phones, not tablets. They were interested in your feedback however and encourage you to suggest what you want as a new idea in the [user voice forum](https://ideas.powerbi.com/forums/265200-power-bi-ideas/filters/new?category_id=105939). Anyway, thanks for your comment. I am going to work on making the documentation more clear as to what the situation currently is.
I'll close this issue now, but let me know if you have any more questions or comments.
