### ISSUE TITLE
Migrate to service principal detail

### ISSUE THREAD

**Issue by boylec** [MicrosoftDocs/powerbi-docs#1944]
It took quite awhile to figure out that I had to change my authority url to https://login.microsoftonline.com/{my AAD tenant id} from https://login.microsoftonline.com/common.

May want to mention this here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @boylec , thanks for your suggestion. I am forwarding on to the doc author for consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @boylec,

We're currently updating the service principal article. Please check this article again in a couple of weeks, once the article is revised.

Thanks,

Kesem
