### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/powerbi-docs#1945]
how to  add images or screenshots in docs.microsoft.com articles , i am a contributor on docs.microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 917c3c6b-e10e-2623-e7ba-e7b804a23a3b
* Version Independent ID: bdf7ffe2-3795-abd6-fe64-2b263386a42e
* Content: [Add images, videos, and more to your dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-add-widget)
* Content Source: [powerbi-docs/service-dashboard-add-widget.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-add-widget.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @RAJU2529 -- which article are you trying to contribute to? This article that you commented on is not about adding images to docs articles. It's about adding images to Power BI reports. If you can tell me the article you're interested in, I can see who you need to get in touch with.

**Comment by RAJU2529** [comment]
@maggiesMSFT . Thanks for your reply , here is the article  address , i want to replace existing screenshot to new one 

**https://docs.microsoft.com/en-us/windows/security/identity-protection/credential-guard/credential-guard-manage#feedback**

**Comment by maggiesMSFT** [comment]
Hi, @RAJU2529 -- I've contacted the owner of that article and asked them to get in touch with you. Good luck!
