### ISSUE TITLE
Operation Name for publication of a report

### ISSUE THREAD

**Issue by PowerBiGuy** [MicrosoftDocs/powerbi-docs#1946]
There does not seem to be an obvious Operation Name for the event of publication of a report from Desktop to the Power BI service. If this exists, what is it called? If it does not exist then how can this event be determined from logs?

**Comment by maggiesMSFT** [comment]
Hi, @PowerBiGuy -- are you referring to a specific article? If not, you might try posting your questions in the Community forum, https://community.powerbi.com/. 
Thanks!

**Comment by PowerBiGuy** [comment]
Sorry, I was linked here from this article: https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#use-the-activity-log

**Comment by maggiesMSFT** [comment]
Thanks, @PowerBiGuy ! Assigning to the author for further investigation.

**Comment by kfollis** [comment]
Hi @PowerBiGuy - I got some clarification around your question and made a couple of updates to the article to make sure the answer is documented. Publishing from desktop to the service is a CreateReport event in the service.
