### ISSUE TITLE
Cannot find "Sort by Column" button for March 2020 version of PowerBI Desktop

### ISSUE THREAD

**Issue by LydiaLim93** [MicrosoftDocs/powerbi-docs#1947]
Can someone please update this documentation, as the "Sort by Column" button doesn't seem to be located under the "Modelling" tab anymore. I have looked high and low but to no avail!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sort-by-column#feedback)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @LydiaLim93, and sorry for the inconvenience. Let us take a look at what happened there, and get back to you shortly. Thanks!

**Comment by davidiseminger** [comment]
Adding tags

**Comment by Gangula2** [comment]
Previously the "Sort By Column" used to be in the Modeling tab. But, it has been moved to Contextual Tab - "Column Tools". 

But the button is **not working properly** as described in the documentation.
![image](https://user-images.githubusercontent.com/22996896/77258450-ac546280-6ca0-11ea-8d9a-137bbed92f12.png)

**Comment by jspotanski** [comment]
@Gangula2, I only have contextual tabs for Format and Data/Drill even when I select a table.  I can't find Sort by column anywhere in the product :(

**Comment by apffer** [comment]
The correct procedure is: Go to the "Data" view, select the table and the field you are using on your report visualization. Go to the "Column tools" tab. Use the "Sort by column" to select any field in the table that should be used to sort the selected field wherever it is used. For instance, you would select a "Month Name" field, and then "Sort By Column->Month Number".

**Comment by Gangula2** [comment]
@jspotanski, you need to select a field/column to see the contextual tab for Column Tools.
When you select a table the "Table Tools" tab shows up, when you select a field/column the "Column Tools" tab show up and when you select a measure, the "Measure Tools" show up. You can refer to the screenshot in my comment above.

**Comment by jujiro** [comment]
Is there a way to determine what the current Sort By column is set to?

**Comment by mihart** [comment]
Hi @LydiaLim93 ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, let us know and/or submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
