### ISSUE TITLE
Publish to web

### ISSUE THREAD

**Issue by AeliusRuivus** [MicrosoftDocs/powerbi-docs#1949]
Upgrading (or creating a new workspace) renders the "Publish to Web" option unusable. It generates the link, but it returns the message "This content isn't available...".

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3645c7a6-ea10-3dc5-2120-aa17355278ec
* Version Independent ID: 2d13d46d-1eaf-b767-cc88-5663c9191ee1
* Content: [Upgrade classic workspaces to the new workspaces - Power BI](https://docs.microsoft.com/en-gb/power-bi/designer/service-upgrade-workspaces#feedback)
* Content Source: [powerbi-docs/designer/service-upgrade-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/designer/service-upgrade-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @AeliusRuivus . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @AeliusRuivus -- are you still having this issue? I just tried it and the link worked fine. If it's still not working, I suggest opening a support ticket. https://powerbi.microsoft.com/en-us/support/
Hope that helps!
