### ISSUE TITLE
App Owns Data sample does not work with ADAL3 and .NET Core

### ISSUE THREAD

**Issue by AkosLukacs** [MicrosoftDocs/powerbi-docs#195]
Since by design the latest .NET Core version of ADAL does not have `UserPasswordCredential`, the App Owns Data sample does not work.
Please provide a sample that works with ADAL3 and .NET Core (api secret key, or client cert authentications).

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thanks for your comment, @AkosLukacs. Sounds like this is a product question, so please use the Product Feedback button in this article, or try the community, https://community.powerbi.com/.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we can always reopen the issue.

**Comment by markingmyname** [comment]
@AkosLukacs 

.Net Core doesn’t support UserPasswordCredential in ADAL nuget.

We don't recommend using username/password in .Net Core with using ADAL.

You can use one of the following solutions:
•    Use ADAL REST APIs instead.
•    Have mini .NET Standard service which generates Embed Tokens. Use Service-to-service authentication between .Net Core and .Net standard.
•    Wait for an App-Only token.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we can always reopen the issue.

**Comment by dlmotter** [comment]
This issue has been reported multiple times, but MS just diverts to the (totally useless) PBI Community page. If you are like me and having this issue, you may have luck with https://www.c-sharpcorner.com/article/how-to-get-access-token-for-powerbi-embedding-in-net-core/

I did not write and have no affiliation with that site - it's just the solution that worked for me.
