### ISSUE TITLE
Missing SKUs

### ISSUE THREAD

**Issue by RichG36** [MicrosoftDocs/powerbi-docs#1951]
You list P SKUs P1 - P3 but there's no mention of P4 and P5 which were added in 2018? https://powerbi.microsoft.com/en-us/blog/power-bi-service-and-mobile-february-2018-feature-summary/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-what-is#feedback)
* Content Source: [powerbi-docs/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @RichG36. Let us take a look at that, and respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback - I've added P4 and P5, thanks for bringing that up!
