### ISSUE TITLE
About Private IP environment

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#1952]
@YoshitakaTakada commented on [Mon Mar 16 2020](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/issues/25)

Add the following as a cautionary note.
"When using Azure SQL Database with Private IP," On-premises data gateway is required. "

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Power BI Desktop の DirectQuery - Power BI](https://docs.microsoft.com/ja-jp/power-bi/desktop-use-directquery)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Mon Mar 16 2020](https://github.com/MicrosoftDocs/powerbi-docs.ja-jp/issues/25#issuecomment-599333179)

Hello, @YoshitakaTakada
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidiseminger** [comment]
Thanks for your comment, @CeciAc. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for the input @CeciAc  - I've added a note to that effect, so others can benefit. Much appreciated!
