### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jboriott** [MicrosoftDocs/powerbi-docs#1953]
At the end of the third large paragraph is a link for "Office 365 Compliance Framework."  That doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b73941-7a77-b7e6-01a5-6d088f7c50ec
* Version Independent ID: ca5a44b2-88c7-e03d-4e94-a0a727160fff
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-security#feedback)
* Content Source: [powerbi-docs/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jboriott. Let us look into that link, and respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Sorry for the inconvenience. We've updated that link to bring customers to the overall Trust Center, where they can find overall information (and deep dives, if needed) about compliance.
