### ISSUE TITLE
Scheduled Refresh Timeout

### ISSUE THREAD

**Issue by boylec** [MicrosoftDocs/powerbi-docs#1954]
This section claims that if a dataset is in a premium capacity workspace then the timeout will be increased to 5 hours.

I have a dataset in a premium capacity workspace wherein the refresh is timing out after 2 hours.

Is there some discrepancy/inaccuracy in this documentation or some way to enable this increased timeout for a premium capacity workspace/dataset that isn't documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179482da-6009-3602-8e51-c20a42c83b5b
* Version Independent ID: b023c9e5-94e0-4d0c-67ce-465916170c43
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-troubleshooting-refresh-scenarios#feedback)
* Content Source: [powerbi-docs/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @boylec. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @boylec , 
Thank you for your suggestion.  Here is the response I received from the Engineer:

The shorter time probably comes from data source. In PBI, minimum timeout for refresh a Premium dataset is 5 hours.

If you still have questions, please let us know. 
All the best,
The DOCS team
