### ISSUE TITLE
D365 RDL support

### ISSUE THREAD

**Issue by baibhav-82** [MicrosoftDocs/powerbi-docs#1957]
Hi,

Does it support D365 SSRS reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-in/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service#feedback)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @baibhav-82. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @baibhav-82 -- thanks for asking! No, it doesn't support D365 SSRS reports.

**Comment by baibhav-82** [comment]
Thanks for the info
