### ISSUE TITLE
need clarity 

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#1958]
"Once a report is published, the maximum number of concurrent queries sent to the underlying data source also depend upon fixed limits. The limits depend on the target environment to which the report is published. Different environments, such as Power BI, Power BI Premium, or Power BI Report Server, can impose different limits."
This is extremely vague, what are these limitations? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#maximum-number-of-connections-option-for-directquery)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @adamwp1993 . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
There are various constraints that can be put on how many queries are allowed in each of those environments, such as administrative constraints, the type of Premium subscription, and so on, which introduces too many variables to enumerate all of the combinations. 

If you have a specific question about your environment, you can post a question / look for an answer in the Power BI Community, found at https://community.powerbi.com. If that doesn't solve the question, you can get support by going to https://support.powerbi.com.
