### ISSUE TITLE
Limitations - which are likely to be resolved for GA?

### ISSUE THREAD

**Issue by mikegoatly** [MicrosoftDocs/powerbi-docs#1959]
This blog post (https://powerbi.microsoft.com/en-us/blog/export-report-to-pdf-pptx-and-png-files-using-power-bi-rest-api/) suggests that some of the limitations are only there for public preview ("Other public preview limitations..."). Only one listed here mentions that it's for public preview only - should the take-away be that the others will still be there for GA?

I'm specifically interested in the Service principal limitation as we have recently migrated from a master account to exclusively using service principals so we can enable 2FA across the board in our AAD. (We didn't have much luck with app passwords and the Power BI APIs)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24f5f312-1684-c361-7a81-c505dca55658
* Version Independent ID: fac40af8-6fe2-f6a7-9dff-051b31a5e52a
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/export-to#limitations)
* Content Source: [powerbi-docs/developer/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @mikegoatly . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
