### ISSUE TITLE
Working Files?

### ISSUE THREAD

**Issue by phamhoangtien** [MicrosoftDocs/powerbi-docs#196]
Can I have the working files of this tut? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0614115b-602d-cab2-307e-618f6a3dbd2f
* Version Independent ID: 09e23d6d-c1f8-ca45-3ad0-47a6ff5ec213
* Content: [Use Quick measures to easily perform common and powerful calculations in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quick-measures)
* Content Source: [powerbi-docs/desktop-quick-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quick-measures.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. Some of our tutorials include links to the sample data, others do not. I'll look into this article and see if the data is available, and if it is I'll update the article with a link.
