### ISSUE TITLE
Why are there guidelines about 'embedding for your customers' on this page?

### ISSUE THREAD

**Issue by Koning53** [MicrosoftDocs/powerbi-docs#1960]
The sentence "If you're embedding reports, dashboards, or tiles for your customers, then you have to place your content within a workspace." is a bit confusing as this page describes embedding for your organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90078026-b608-ccf2-f3ef-58021b484f75
* Version Independent ID: e51ab568-5610-ff18-c5c0-4d2f27935dfa
* Content: [Embed content in your application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-your-organization#feedback)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @Koning53 , thanks for your observation. I am passing it on to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @Koning53,

Thank you for your comment. You're right, this sentence is confusing.

We're in the process of updating all the embedded analytics tutorial, and will shortly update this one too.

Please check these tutorials in a couple of months, once they're updated.

Thansk,

Kesem
