### ISSUE TITLE
Is Row Level Security (RLS) available when doing this type of embedding?

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/powerbi-docs#1964]
Be nice if the article could describe the RLS support such as the Embed report in secure portal or website does here: https://docs.microsoft.com/en-us/power-bi/service-embed-secure. Second to last sentence in the first paragraph at this time. Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo#feedback)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for reaching out to us, @ShawnPOWER . I am looking into your comment, and will get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Issue resolved by @paulinbar
