### ISSUE TITLE
Validate the roles within Power BI Desktop with UPN

### ISSUE THREAD

**Issue by ColeenB** [MicrosoftDocs/powerbi-docs#1965]
The screenshot of the View as roles popup (item #3) shows only the "Other" box checked. I tried this and the visualizations were not filtered for the user whose UPM I entered. I had to check the "Other" box AND the box with the Role Name in order for it to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for your input, @ColeenB. We're working on this article now and will validate and update the procedure. I've assigned the author for review and follow-up.

**Comment by paulinbar** [comment]
Hi @ColeenB. I've noted your comments and will address them in the rewrite of the RLS articles that is now underway. In the meantime I am closing this issue now. Thanks for your input!
