### ISSUE TITLE
Get assigned user information? 

### ISSUE THREAD

**Issue by mimckitt** [MicrosoftDocs/powerbi-docs#1966]
I am wondering if it is possible to pull in information about issues and who they are assigned to. Currently I find that the only assignee information available using the default settings is in regards to pull requests. I am interested in looking at total number of open issues (Which I can do) as well as who those issues are assigned to in GitHub.

 And if this is not included in this app, is there a way to modify the dataset to grab this information or request it be added to the app? 

I also don't find any LiveURL information. This would be great so a person could actually click the link to the issue and take action. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github#feedback)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mimckitt** [comment]
I also found out some additional information while playing around with this. 

If you use PowerBI desktop, you are able to pull the dataset from GitHub and get the assignee information which is great! However, when pulling from the GitHub data set in PowerBI desktop, you no longer pull the information about the labels on each issue. 

Hence, I am stuck in the middle with The GitHub app having everything I need except the person the issue is assigned to, and the PowerBI Desktop version having everything I need except labels.... :)

**Comment by paulinbar** [comment]
Hi @mimckitt , well, it sounds like you are farther along in all this than I am.. my only advantage is that one of my PMs is the template apps person and he knows that app pretty well. I'll ask him after the weekend hopefully we'll managed to sew together your two solutions lol... in any event, I'll move our communication over to teams or email. Thanks for the further comments!

**Comment by mimckitt** [comment]
Sounds great. Thanks for taking the time :)
