### ISSUE TITLE
Azure Data Lake Storage Gen2 connector

### ISSUE THREAD

**Issue by amlucius** [MicrosoftDocs/powerbi-docs#1967]
The connector works in GCC. Not sure about GCC High or DoD. Can someone please update the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US Government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/service-govus-overview)
* Content Source: [powerbi-docs/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@amlucius - thanks for helping us keep things current! This change has been made and you should see the update shortly.
