### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by amkumar5** [MicrosoftDocs/powerbi-docs#1968]
Embed documentation is in 5 lines but it it's not working at all.
and as a PBIRS product user am having tough time to get support as Name is similar. even though searching PBIRS, getting all results for PBI. 
am looking for embed in Regular Sharepoint and am always getting search results for 'SharePoint Online'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3889030d-38f1-8788-119d-3615f7487f73
* Version Independent ID: f6b4aecd-1fc0-2b39-d1ac-27735f36329e
* Content: [Developer handbook overview, Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/developer-handbook-overview#feedback)
* Content Source: [powerbi-docs/report-server/developer-handbook-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/developer-handbook-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @amkumar5 -- thanks for the feedback! I'll look into it. In the meantime I recommend checking the SQL Server Reporting Services documentation, https://docs.microsoft.com/en-us/sql/reporting-services/create-deploy-and-manage-mobile-and-paginated-reports.. Hope that helps.

**Comment by maggiesMSFT** [comment]
Hi, @amkumar5 -- yes, that's the best resource to answer your question. Hope that helps!
