### ISSUE TITLE
Image is transparent, and doesn't show up in dark mode

### ISSUE THREAD

**Issue by chrisbues** [MicrosoftDocs/powerbi-docs#1969]
This image: https://docs.microsoft.com/en-us/power-bi/media/desktop-default-member-multidimensional-models/default-members_01.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970bf2d5-28fc-cc40-0f5c-7bac93c47bd9
* Version Independent ID: 79d25279-d612-23e0-5689-9fddc8ad15b4
* Content: [Default member in multidimensional models in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-default-member-multidimensional-models)
* Content Source: [powerbi-docs/desktop-default-member-multidimensional-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-default-member-multidimensional-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @chrisbues -- thanks for catching that. I'll pass your feedback to the author.

**Comment by davidiseminger** [comment]
You're absolutely right - sorry about that. I've recreated that image with a very bright, white background. Thanks for pointing this out!
