### ISSUE TITLE
disconnect?

### ISSUE THREAD

**Issue by brown1mr** [MicrosoftDocs/powerbi-docs#197]
In the May Power BI feature summary (snippet below)  it mentions an improvement so that content can be shared to invited users and they’ll get just the one link that lets them accept the invite and access the content.  I can’t get the Power BI dev to share to an invited recipient unless they have the “export/share to external” switch enabled and have been granted this privilege, which if they have this, the external recipient doesn’t even have to be in an invited status in order to be able to share to them.  We need to be able to do ‘planned’ bulk invite (with no email), then let the Power BI dev share content to them (and we don’t want the dev to have the export/share with external privilege) and the recipient would get the one email when the content is shared to them.

Azure B2B invite workflow improvements for reports
We have seen increasing usage of our Azure B2B external user sharing features that help you collaborate securely across organizations. However, the invite acceptance workflow has been complicated because the user needs first to accept the Azure B2B invite, and then click the link to the Power BI content in a separate email.
Moving forward, we have simplified the workflow for reports so that invited external users get a single email to the report in Power BI. When they click the link, they accept the invite and can immediately access the content. It’s a simple way we’re trying to smooth out the wrinkles to make it easier to collaborate across organizations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute Power BI content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by KayUnkroth** [comment]
Thanks for the feedback, brown1mr. I shared your comments with the PM owner for Power BI sharing and collaboration. Hopefully, a future release will make it even easier to collaborate with external (guest) users.

**Comment by mgblythe** [comment]
@brown1mr - closing this based on Kay's response.
