### ISSUE TITLE
Microsoft Project Web App supports only En-us Language(1)

### ISSUE THREAD

**Issue by Petryxasport** [MicrosoftDocs/powerbi-docs#1970]
After typing different language we always see the English.
![issue](https://user-images.githubusercontent.com/17165899/77177984-7adc6b00-6ad7-11ea-9290-1a50be051f6e.png)
We would like to see not only default languages.
Can we change the url parameters to support language like this: http://.../_api/ProjectData/[ru-ru]
Because Rest API supports ru-ru and other :)

**Comment by maggiesMSFT** [comment]
Hi, @Petryxasport -- I'm sorry to hear this! It appears to be a product issue, not a documentation issue. I recommend trying the support site, https://powerbi.microsoft.com/en-us/support/. Good luck!
