### ISSUE TITLE
Looks like this is a duplicate page

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#1971]
Hi there. Just a heads up that it looks like this page is a duplicate of another page with the same name. The other one has been updated more recently. See 8 items higher on the left nav that has the same name, or here: https://docs.microsoft.com/en-us/power-bi/desktop-tips-and-tricks-for-creating-reports 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a08ab5c-b7f6-2789-3a20-716ac0110089
* Version Independent ID: a68bdc48-295a-41d6-b713-1c26498beb5c
* Content: [Tips for creating stunning reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-reports-tips-and-tricks-for-creating#feedback)
* Content Source: [powerbi-docs/power-bi-reports-tips-and-tricks-for-creating.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-reports-tips-and-tricks-for-creating.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @sqlchick -- thanks, you're right! They're not exactly the same, either. Assigned to the author to investigate.

**Comment by davidiseminger** [comment]
Thanks for pointing this out @sqlchick - much appreciated! You're right, and I've consolidated those articles into one, and removed the duplicate (this page). Thanks!
