### ISSUE TITLE
Exchange Online doesn't support shared inboxes in the service

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#1972]
It should be called out that Power BI Service only supports Exchange Online if the connection is to a user's individual account, not shared inboxes. We've had multiple teams in our company run into this limitation and be frustrated as it is not documented anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @klinejordan - we’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @klinejordan , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
