### ISSUE TITLE
Additional Troubleshooting Scenarios

### ISSUE THREAD

**Issue by DonPetry-EY** [MicrosoftDocs/powerbi-docs#1973]
Hello... I wanted to share that we're facing PBI Desktop sign-in issues on a secured DSVM.  It appears that there additional sign-in requirements such as Javascript being enabled in IE.  See https://community.powerbi.com/t5/Desktop/Problem-signing-in-to-Power-BI-script-error/td-p/586231

Also, there doesn't seem to be an option to use an alternative browser or use a device code.

Can we enhance this to cover these scenarios explicitly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Troubleshooting Sign-in issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-sign-in#how-to-collect-a-trace-in-power-bi-desktop)
* Content Source: [powerbi-docs/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @DonPetry-EY. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
