### ISSUE TITLE
Missing old ribbon

### ISSUE THREAD

**Issue by manu3lco** [MicrosoftDocs/powerbi-docs#1975]
I cannot find how to go to the query editor and the article doesn't explain what it has been removed in detail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93a9e0e5-9166-bbd6-5ab2-7dc552d2d5d7
* Version Independent ID: 5478be1c-64f8-2b5e-f51f-06d3311f89b9
* Content: [Use the updated ribbon in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-ribbon#feedback)
* Content Source: [powerbi-docs/desktop-ribbon.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-ribbon.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
You can open Power Query Editor on the main (new) ribbon, in the Home ribbon, by selecting the **Transform data** button.
