### ISSUE TITLE
Sorting is not working for performance_bucket export from Azure

### ISSUE THREAD

**Issue by wcom939** [MicrosoftDocs/powerbi-docs#1976]
Please see the attached files, when exporting a sort by "performance_bucket" the ordering is wrong on the X axis.

Azure:
![image](https://user-images.githubusercontent.com/16446451/77253876-db80ba80-6c33-11ea-839d-3d23f1148f63.png)

Power Bi Desktop:
![image](https://user-images.githubusercontent.com/16446451/77253868-c73cbd80-6c33-11ea-8bfb-92099ef08797.png)

**Comment by davidiseminger** [comment]
Thanks for your comment, @wcom939 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
