### ISSUE TITLE
Add description of the Selection pane

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1977]
The Selection pane should be referenced in the section on z-order. It probably needs it's own page in docs, which seems to be missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e311f65-8df9-951f-6398-bab28566c8d5
* Version Independent ID: c227717d-d15e-9e34-2874-47c8dfb2e23a
* Content: [Use gridlines and snap-to-grid in Power BI Desktop reports - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-gridlines-snap-to-grid#using-z-order-align-and-distribute)
* Content Source: [powerbi-docs/desktop-gridlines-snap-to-grid.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-gridlines-snap-to-grid.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Mike-Honey. We’ve assigned your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback. We've added this request to our queue of work items, and will work through it as time and resources allow. Much appreciated.
