### ISSUE TITLE
The Selection pane section incomplete.

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#1978]
The Selection pane section does not describe the z-order change features. The Selection pane actually has several features which don't appear to be documented anywhere in docs? I recommend it get's it's own page, then this page could just link to that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Use bookmarks in Power BI Desktop to share insights and build stories - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks#visibility-using-the-selection-pane)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your suggestion (and the other feedback about the Selection pane). As mentioned, we've added this to our queue of requested content, and will add it as time and resources allow.
