### ISSUE TITLE
If Azure consumption feture support China EA?

### ISSUE THREAD

**Issue by juchen0411** [MicrosoftDocs/powerbi-docs#1979]
Hi team,
We have partner in China using China Azure (hosted by 21VNet), and they would like to know if China EA enrollment and key are able to fetch the data? We assume this function is limited to global Azure EA only, is it correct? Thank you.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @juchen0411. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
