### ISSUE TITLE
Power BI

### ISSUE THREAD

**Issue by Prashantkumartyagi** [MicrosoftDocs/powerbi-docs#198]
Easy to understand and easy to use .
It documentation is very halpfull.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08962cd6-cbb2-3342-09df-aa199623e9fb
* Version Independent ID: d4ebdf44-cde2-82b6-3f82-8524f370d980
* Content: [Visualizations - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/visualizations?tutorial-step=20)
* Content Source: [powerbi-docs/guided-learning/visualizations.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/visualizations.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks!! Glad you found it useful, @Prashantkumartyagi!
