### ISSUE TITLE
incorrect url for "authorityUrl" for GCC

### ISSUE THREAD

**Issue by sajas-s** [MicrosoftDocs/powerbi-docs#1981]
"authorityUrl" key for GCC should be &lt;add key="authorityUrl" value="https://login.microsoftonline.com/common/" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0658cf44-97c9-cb23-68bd-146f29eb644c
* Version Independent ID: e05ed89e-2dfa-0d31-4198-9170a33ef120
* Content: [Embed content in your application for government and national cloud - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers-national-clouds#feedback)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ssalahud1 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @sajas-s,

You're correct. I fixed `authorityUrl` in Government Community Cloud (GCC) - see [Download the sample](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers-national-clouds#download-the-sample).

Thanks for catching this,

Kesem
