### ISSUE TITLE
Download Feature does not support Shared Capacity.

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#1982]
Please contact Siqwang if you need any further information, if report is build on Shared Dataset, it won't be able to download. 
Action Need : Updated Document that this is currently not supported

Workspace 1 : User 1: Create dataset and give permission to User 2 (only build permission)

User 2 Logs in Desktop

Connect to the above dataset

Publish the report to workspace 2

User 2 logs into service

Navigate to Workspace 2

Open the published report

Download the report as pbix

error :

Can't export to Power BI Desktop format
We couldn't export to .pbix format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-export-to-pbix#feedback)
* Content Source: [powerbi-docs/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KerryWang94** [comment]
Sorry, shared datasets, wrong titile

**Comment by mihart** [comment]
Thanks for your comment, @KerryWang94 . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @KerryWang94 -- taking this offline with you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @KerryWang94 -- fixed it, added the note. It'll be live later today. Thanks!
