### ISSUE TITLE
Issue collecting data 

### ISSUE THREAD

**Issue by abnadi** [MicrosoftDocs/powerbi-docs#1984]
We make us of the Microsoft Azure Consumption Insight plugins in PowerBI (online version)
to collect consumption data. SInce 2 weeks we cannot collect any more data.

message we receive:
Data source error The 'Consumed Quantity' column does not exist in the rowset. Table: Usage Details

**Comment by mihart** [comment]
Thanks for your comment, @abnadi. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
