### ISSUE TITLE
Incremental Refresh through custom connector

### ISSUE THREAD

**Issue by alex-v-ivanov** [MicrosoftDocs/powerbi-docs#1985]
Is it possible to implement incremental refresh for my own data source using On-premises gateway and a custom connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @alex-v-ivanov . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, @alex-v-ivanov. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
