### ISSUE TITLE
Need Update Document

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#1988]
Could you please add this part as consideration and limitiation of this document ?

Please contact siqwang for reference and ICM 142191141

“Power BI is designed to work with any of our supported browsers, but performance does differ depending on a user’s choice of browser.  Internet Explorer users in particular may encounter worse performance, and we strongly recommend users of Internet Explorer switch to a modern browser for better performance, including Microsoft Edge.  We expect Microsoft Edge performance to continue to improve with Edge Chromium, which is still available only in Preview.  For users still encountering unacceptable performance, you should test other supported modern browsers to see if they provide better results for your Power BI solution.”

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-au/power-bi/power-bi-browsers)
* Content Source: [powerbi-docs/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KerryWang94** [comment]
Note Edge Chromium is no longer in Preview, please check with document author seeing what would be best words on this doc.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @KerryWang94.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @KerryWang94 ! I've made the update. The change will go live this afternoon.
