### ISSUE TITLE
Power BI Python

### ISSUE THREAD

**Issue by twoyoungtwosimple** [MicrosoftDocs/powerbi-docs#1989]
If I create a visual object in Python, after the release, if someone else's computer does not have Python or the Python package, can others interact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd46971-2ea5-9271-3b2a-824efc1821e1
* Version Independent ID: 68669cdb-5e4d-bb96-d2d5-bdad4088fb03
* Content: [Using Python in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-in-query-editor#feedback)
* Content Source: [powerbi-docs/desktop-python-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @twoyoungtwosimple.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by otarb** [comment]
No, they won't be able to use python visual, it won't render. 

Python (and R) visuals are not cached and will render when report is opened, using user's environment. 

Which Python (or R) environment to use is configurable from settings pane. 

#please-close @otarb
