### ISSUE TITLE
What will be involved in converting old workspaces to new ones

### ISSUE THREAD

**Issue by olopuc** [MicrosoftDocs/powerbi-docs#199]
In the doc it says you'll need to prepare to migrate your workspaces to the new workspaces infrastructure.  Later it says, When the new workspaces are generally available (GA), you can opt in to migrate the old ones automatically. At some point after GA, you'll have to migrate them.

How will the migration work, can this be done  at an Admin level in an organization or only by a workspace's Admin. Will it be push button, and what changes may occur as a result (for example will a new link to the workspace / app be created, will it need to be unpublished / republished?

We have several workspaces that are linked via dashboard tiles that could break if the link changes. I'm trying to figure our what the impact will be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by chrisweis** [comment]
Great question @olopuc, +1

**Comment by maggiesMSFT** [comment]
Hi, @olopuc and @chrisweis -- I don't have the when or the how details yet. This Summary of Planned Features article is a good place to check for upcoming features. https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features. 
Thanks -- hope that helps!
