### ISSUE TITLE
Gateway support on Cloud Resource

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#1990]
As mentioned in this document "This article applies only to datasets that have cloud and on-premises data sources merged or appended in a single query. For datasets that include separate queries--one that connects to an on-premises data source and the other to a cloud data source--the gateway doesn't execute the query for the cloud data source."

It's very easliy to mislead people to believe that Gateway doesn't execute the query for the any cloud data source, actually On-Prem data Gateway does support a list of cloud resoruce such as Azure SQL DB, and this list is mentioned in https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources"

Could you please try to improve the expression a bit ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @KerryWang94.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @KerryWang94 ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
