### ISSUE TITLE
Schema mismatch and fixing it with JSON file from Machine Learning Designer

### ISSUE THREAD

**Issue by afelthe** [MicrosoftDocs/powerbi-docs#1991]
There are a couple critical steps missing for folks using CSV files as the schema will not transfer in often.  I am happy to share these steps and screen shots.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8e2403-884c-ccf3-ac6a-82d53c4ee018
* Version Independent ID: cb5eefd9-3a07-7440-ae26-69b2a0b8fe78
* Content: [Tutorial: Invoke a Machine Learning Studio (classic) model in Power BI (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-tutorial-invoke-machine-learning-model)
* Content Source: [powerbi-docs/service-tutorial-invoke-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-tutorial-invoke-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @afelthe.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment! Yes @afelthe, please add those steps by submitting a PR to the documentation, and I'll look over them for approval. It's a great way to contribute. Thank you!
