### ISSUE TITLE
Import custom theme not available

### ISSUE THREAD

**Issue by FThun89** [MicrosoftDocs/powerbi-docs#1992]
I've version: 2.79.5768.721 of PowerBI Desktop App in older versions it was possible to import a custom theme like described here but in this version there is no "switch theme" in the Home Ribbon and in the Visualization Ribbon the theme can be switched but not customized

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#feedback)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @FThun89.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by Sil-L** [comment]
Hi FThun, 

see my comment above for a step by step of how to do it - the feature is still there, it has just changed to be in the 'View' Ribbon. Hope this helps.

**Comment by davidiseminger** [comment]
Thanks for clarifying @Sil-L !
