### ISSUE TITLE
More functions

### ISSUE THREAD

**Issue by shalinderverma** [MicrosoftDocs/powerbi-docs#1993]
There are more functions for DAX tables like GROUPBY, SUMMARIZE, CALCULATETABLE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23f1335-bb33-544a-67da-006015cfc92f
* Version Independent ID: 3e1dc63e-f0ac-5201-c0a5-bc7e4ee30944
* Content: [Using calculated tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-calculated-tables#feedback)
* Content Source: [powerbi-docs/desktop-calculated-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-calculated-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @shalinderverma. I've assigned this issue to the author to consider adding those additional functions.

**Comment by davidiseminger** [comment]
Thanks for your comment - and indeed you're correct there are more functions for DAX tables. The functions listed were just the more common functions used.
