### ISSUE TITLE
Ability to change Group Name

### ISSUE THREAD

**Issue by aguinaldo92** [MicrosoftDocs/powerbi-docs#1994]
Hi,
cannot see any explanation about how to change the group name. I've lot of Group 1,2,3, etc. that i'd like to rename but couldn't find a way so far

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6669843-8752-7777-31e8-1d1e4ec96648
* Version Independent ID: b7be0303-1882-621e-a630-32895aafa84d
* Content: [Use grouping in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-visuals#feedback)
* Content Source: [powerbi-docs/desktop-grouping-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Great question, @aguinaldo92! If you double-click the group name in the selection pane, it becomes editable and you can change the name. I'm adding to the author for review to consider adding that detail.

**Comment by davidiseminger** [comment]
Hi @aguinaldo92 - I've added how to rename a group to that article. Good suggestion!
