### ISSUE TITLE
Additional Auth Requirements & Troubleshooting Steps

### ISSUE THREAD

**Issue by don-petry** [MicrosoftDocs/powerbi-docs#1995]
Let me try this again.

There are additional troubleshooting scenarios and Power BI Desktop authentication requirements not covered by this document.  Please add details about the following PBI Desktop Auth requirements:

1) Dependent on Internet Explorer/Edge.  Changing default browser in OS doesn't affect this.  

2) Javascript must enabled in IE  (See https://community.powerbi.com/t5/Desktop/Problem-signing-in-to-Power-BI-script-error/td-p/586231)  Incompatible with IE enhanced security config

3) No option to use an alternative browser or use a device code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Troubleshooting Sign-in issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-sign-in#how-to-collect-a-trace-in-power-bi-desktop)
* Content Source: [powerbi-docs/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the input, @don-petry. Assigning this issue to the author for review and to consider adding this troubleshooting scenario. It may not be a common use case or could resolved in the latest builds, but we'll take a look.

**Comment by sandegan1** [comment]
Hi Kate 
If Java script is disabled on internet explerer and same is enabled on other browsers (Edge and Chrome) even after making those browser as default browsers , PBI Desktop is throwing script while entering loging credentials. PBI desktop is not looking on the default browser , it using internet explorer always.Because of this , unable to login from PowerBI desktop. 
Please let me know if you need any addional information.

**Comment by mihart** [comment]
Hi @don-petry ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
