### ISSUE TITLE
Great video series! 9/10 stars

### ISSUE THREAD

**Issue by JamesDBartlett** [MicrosoftDocs/powerbi-docs#1996]
You guys did a great job with this video series. The content is 100% on-point, and the balance between big-picture and nitty-gritty is superb. I only have one suggestion (which may still be possible, if you still have the source video files): 
I'd suggest uploading the videos in a higher resolution than 720p. Everything looks kinda grainy, and many of the small details are so blurry or pixelated that they're unreadable. Other than that, everything was excellent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0439d49-76b1-380b-f226-317e96ca0397
* Version Independent ID: 2dd9f620-5244-936f-76f9-1f32f5ac5a23
* Content: [Online course: Power BI Paginated Reports in a Day - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-online-course#feedback)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-online-course.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports/paginated-reports-online-course.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by kfollis** [comment]
Thank you for the nice feedback, @JamesDBartlett! I'm assigning this issue to the author so that they can consider your suggestion for higher resolution.

**Comment by peter-myers** [comment]
Hi @JamesDBartlett - thanks your positive feedback! The videos were produced in HD. I've just taken a look at some of them, especially those with demonstrations, and I can read the fine details. I wonder if your problem is related to the speed of your internet connection or your YouTube quality settings?

Please refer to this YouTube Help article for more information: https://support.google.com/youtube/answer/91449?hl=en

#please-close

**Comment by JamesDBartlett** [comment]
@peter-myers As I mentioned in my original comment, the videos in your playlist on YouTube max out at 720p, so though your source video files may be full HD, the videos on YouTube are not. 

Here's a screenshot, showing YouTube's resolution selection menu on the first video in your series, with 720p selected, and no higher resolution options available:
![image](https://user-images.githubusercontent.com/37491308/79524038-20c2bd00-8025-11ea-9664-450f405ac32c.png)

In answer to your suggestion that my internet connection may be at fault, here is a screenshot of a 4K resolution video on YouTube, which I loaded up right after taking the previous screenshot. 
![image](https://user-images.githubusercontent.com/37491308/79524286-bbbb9700-8025-11ea-8e56-6cf2e0a5b870.png)
The player's buffer has ample lead time on the play head, so we can eliminate my internet connection as the source of the problem. 

Here's an example of the pixelation that I was referring to. It's still mostly readable, but some of the characters, particularly the punctuation symbols, are all but obliterated, and we all know how important it is to get those punctuation symbols exactly right in our connection strings, agreed? ;-)
![image](https://user-images.githubusercontent.com/37491308/79524646-b1e66380-8026-11ea-986c-829347db11de.png)

I really don't mean to nitpick. I've been recommending this video series to my colleagues left-and-right ever since I first watched it, so trust me, I'm not complaining. I'm just hoping you can get a higher resolution version uploaded, so people can see the pixel-perfect detail that Power BI Paginated Reports are so famous for. :-D

Cheers!
