### ISSUE TITLE
Power BI report content is missing.

### ISSUE THREAD

**Issue by RyusukeGondo** [MicrosoftDocs/powerbi-docs#1997]
The Power BI report content for viewing test results is no longer visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b28829-a0e6-9377-35af-bd5661012ace
* Version Independent ID: 607b2bdf-58aa-c392-fe98-3a8264c9edca
* Content: [Capacity planning guidance for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/capacity-planning#feedback)
* Content Source: [powerbi-docs/report-server/capacity-planning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/capacity-planning.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @parthsha
* Microsoft Alias: **parshah**

**Comment by maggiesMSFT** [comment]
Hi, @RyusukeGondo -- Thanks for your observation! I'll investigate and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @RyusukeGondo -- Turns out the report no longer exists. I've removed it from the article. Thanks for reporting it!
