### ISSUE TITLE
Export restrictions when measures exist in Analysis Service

### ISSUE THREAD

**Issue by neko-daisuki** [MicrosoftDocs/powerbi-docs#1998]
[Underlying dataset] cannot be exported from data that has a DirectQuery connection when measures exist in the Analysis Service.
The following is possible with Pattern.
-When a measure is deleted from the Analysis Service and a DirectQuery connection is made
-The measure was left in Analysis Service and imported.

Please describe in "Restrictions".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#limitations-and-considerations)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Thanks for your question, @neko-daisuki ! Assigning to the author to investigate and answer.

**Comment by neko-daisuki** [comment]
@maggiesMSFT
Reports that have both measures in the Analysis Service as well as in Power BI Desktop and have made a DirectQuery connection to the Analysis Service fail to export the underlying data.
It is not clear from the comment on the error what the cause is, so it is not clear how to resolve it.
Take countermeasures.

The relevant materials are described below.

Title: Export the data that was used to create a visualization
URL: https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data

**Comment by msftrien** [comment]
@mihart , I don't think I'm the right assignee here -- export underlying data is a Service-only feature, and I'm not aware of what error is being shown. So I can add a line indicating the above into the doc, but don't know how to verify and don't see any other mention of AS besides version.

**Comment by mihart** [comment]
Hi @neko-daisuki ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  
All the best,
the DOCS team
