### ISSUE TITLE
CustomData Max length 256

### ISSUE THREAD

**Issue by luuksommers** [MicrosoftDocs/powerbi-docs#1999]
When using custom data with Power BI Embedded we get the error: `Provided CustomData value exceeds the maximum supported length of 256`, although this is not documented. Can we bypass this limitation? 
We want to send a list of values in custom data to do row level filtering (currently around 800 characters).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Thanks for your question, @luuksommers ! Assigning to the author to answer.

**Comment by iburki** [comment]
@KesemSharabi Any update on this issue?  We also need to send a list of values to do row level security.

**Comment by KesemSharabi** [comment]
Hi @luuksommers,

You have indeed reached the limit (256). I'll update the documentation shortly.

Thanks,

Kesem

**Comment by B14m3m3** [comment]
@KesemSharabi Is there any way to bypass the limitation or can this limit can be increased? 256 characters seems like a very low limit if you want to use multiple filters.

**Comment by KesemSharabi** [comment]
Hi @luuksommers,

I added a note to [Using the CustomData feature](https://docs.microsoft.com/power-bi/developer/embedded/embedded-row-level-security#using-the-customdata-feature) stating that the CustomData username can only be 256 characters long.

Once again, thanks for your feedback.

@B14m3m3 - I'm not aware of a way to bypass this limitation. You're welcome to try the the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com), or submit product feedback and feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

Kesem

**Comment by lukasz786** [comment]
Hi all,

Do you have any update for above? I'm facing the same issue..

**Comment by daniel-seitz** [comment]
@KesemSharabi two points:
1. The link you provided above doesn't show anything about 256 character limits
2. You mentioned "username" (where in my opinion it makes sense to have that limit) but with RLS we can also provide "customData" additionally. There it makes sense to allow a much bigger payload.

Could you update the link and provide insights into whether changes to this are on the horizon?

Thank you.
