### ISSUE TITLE
Validation Policies link broken/outdated

### ISSUE THREAD

**Issue by Matusa69** [MicrosoftDocs/powerbi-docs#2000]
Looks like Validation Policies link is broken/outdated:
https://dev.office.com/officestore/docs/validation-policies#13-power-bi-custom-visuals 
Hmmm… can't reach this page
dev.office.com’s server IP address could not be found.

Is this link the new policies? 
https://docs.microsoft.com/en-us/legal/marketplace/certification-policies#1180-power-bi-visuals

Thx
A.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0667ec6-a57d-c9c4-3ced-d33e418ace20
* Version Independent ID: d76851d1-c104-b809-225c-f349e11809a5
* Content: [Publish Power BI visuals to Partner Center - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store#submitting-to-appsource)
* Content Source: [powerbi-docs/developer/visuals/office-store.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/office-store.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
HI, @Matusa69 -- thanks for the heads-up! Assigning to the author to investigate.

**Comment by KesemSharabi** [comment]
Hi @Matusa69,

Thank you for your observation, you're absolutely right and I corrected the article accordingly.

The **validation policies** in the [Tracking submission status and usage](https://docs.microsoft.com/power-bi/developer/visuals/office-store#submitting-to-appsource) section now points to the right place.

Thanks,

Kesem
