### ISSUE TITLE
Power BI Premium Requirements

### ISSUE THREAD

**Issue by DieselAnalytics** [MicrosoftDocs/powerbi-docs#2003]
To whom it may concern,

I think you all should make it clear that Power BI Premium is needed to use custom models in Azure Machine Learning Services. Some of your literature and conference videos on YouTube suggest that you can use custom azure machine learning models in Power BI without the need of premium compacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b2117-3a8d-1b35-109c-df315738beac
* Version Independent ID: d31fe48a-8b7d-149f-0db5-2818a4fa07cc
* Content: [Azure Machine Learning integration in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-machine-learning-integration#feedback)
* Content Source: [powerbi-docs/service-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by DieselAnalytics** [comment]
And this article does not make it clear you need Power BI premium.

**Comment by paulinbar** [comment]
Hi @DieselAnalytics , thanks for your comment. I am forwarding it on to the doc author for consideration. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your suggested improvement. I've added that requirement to the article.
