### ISSUE TITLE
OData does not support authentication

### ISSUE THREAD

**Issue by mmschouten** [MicrosoftDocs/powerbi-docs#2004]
Please document the limited support for OData feeds that require authentication. As per support request 120031725002435, only Power BI Desktop supports authentication, Power BI Service does not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @mmschouten , thank you for the comment. Do you by chance have a link support request 120031725002435? In any event I am forwarding your comment on to the doc owner for consideration. Thanks!

**Comment by mmschouten** [comment]
Hi @paulinbar , I'm not sure how to retrieve the link for the support request. It was created through the Power BI site, not through the Microsoft 365 Admin Center.

**Comment by kfollis** [comment]
Hi @mmschouten - I've added a footnote to the OData entry to note that Power BI service doesn't support feeds that require authentication. The changes will publish live this week.
