### ISSUE TITLE
Feature not longer available

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2005]
Feature documented in this link is no longer available - Please confirm with Power BI PG and  update or remove documentation

Link - https://docs.microsoft.com/en-us/power-bi/service-connect-to-salesforce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b5bc04-3e2a-820f-6069-7392a2317108
* Version Independent ID: 43adcf87-006a-a74b-29c8-a7ff1701f13d
* Content: [Connect to Salesforce with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-salesforce)
* Content Source: [powerbi-docs/service-connect-to-salesforce.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-salesforce.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mihart** [comment]
Thanks for your comment, @haider392. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @haider392 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
