### ISSUE TITLE
Indication of successful restart

### ISSUE THREAD

**Issue by nielsgarde** [MicrosoftDocs/powerbi-docs#2006]
Hi,
how can I tell if a capacity was actually restarted or is in the process of getting restarted. There is a small wheel turning around a second, but non of my refreshes are broken (which is a good thing I suppose) so I have no real proof that anything happened. Maybe some history/status page of last restarts could help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ac065d-33c5-2f3b-6cee-36153c2a8afa
* Version Independent ID: 40b95c43-2aca-da1b-9325-709366056f28
* Content: [Restart a Power BI Premium capacity - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-restart#feedback)
* Content Source: [powerbi-docs/service-admin-premium-restart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-restart.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @nielsgarde ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please submit your question to the Power BI community (community.powerbi.com) or add it as a suggestion on the Ideas site (ideas.powerbi.com).  
All the best,
the DOCS team
