### ISSUE TITLE
Feature no longer available in Power BI

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2007]
The feature documented in this article is no longer available in Power BI - https://docs.microsoft.com/en-us/power-bi/service-connect-to-project-online

Please confirm from Power BI PG and remove or update documentation.

**Comment by mihart** [comment]
Thanks for your comment, @haider392 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @haider392 ,
I noticed that this issue is old, so I'm going to close this.  The article you reference is no longer live. 
All the best,
The DOCS team
