### ISSUE TITLE
No show tool decomposition tree visuals 

### ISSUE THREAD

**Issue by borisgr04** [MicrosoftDocs/powerbi-docs#2008]
In my Pc No Can Create and view decomposition tree visuals in Power BI (preview).

**Comment by KesemSharabi** [comment]
Thanks for your comment, @borisgr04. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
