### ISSUE TITLE
normalizeSelector

### ISSUE THREAD

**Issue by twastvedt** [MicrosoftDocs/powerbi-docs#2009]
"static normalizeSelector: This method returns the normalized selector"
Could you add documentation for this method? What does it mean for a selector to be normalized? What does the second argument do? When is the method used and why? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cb8fba-241c-285a-3483-a6f9e8043a30
* Version Independent ID: 642518f9-28fe-e83f-ae4b-7c6b618294ba
* Content: [Introduction to use color utils in Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-color#feedback)
* Content Source: [powerbi-docs/developer/visuals/utils-color.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/utils-color.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @twastvedt! I'm assigning this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @uve,

Can you please assist with @twastvedt questions?

Thanks,

Kesem

**Comment by uve** [comment]
Hi @twastvedt,
 Thanks for your feedback, we're going to extend our docs soon. It's an internal method, you shouldn't use it for now.
You can find the source code of this method [here](https://github.com/microsoft/powerbi-visuals-utils-colorutils/blob/master/src/colorHelper.ts#L85)
