### ISSUE TITLE
PowerBius.gov

### ISSUE THREAD

**Issue by nrreyes** [MicrosoftDocs/powerbi-docs#201]
How does this article apply if you are working on the Power BI US GOV Service? I still cannot figure out how to 'sign in' from BI Desktop so I can publish. Trying this guide causes the same dilemma. All I can do is upload the .pbix directly to the service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your question, @nrreyes - let me look in this and see if I can find a solution, and I'll get back to you on this thread.

**Comment by davidiseminger** [comment]
@nrreyes - the sign in procedure for gov and public clouds operate the same way, confirmed with the engineering team. If you continue to have trouble, please visit the community at https://community.powerbi.com. If you can't find help there, perhaps try https://support.powerbi.com.
