### ISSUE TITLE
Filters "on visual" are trumping "report" and "page filters"

### ISSUE THREAD

**Issue by fordmaxson** [MicrosoftDocs/powerbi-docs#2011]
Would like to know if there is a way to keep report and page filters at the top so we don't lose them every time someone clicks something on a visual.  Wrote recommendation at https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/40073473-change-default-order-of-report-page-visual-fil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks for the feedback, @fordmaxson! I'm assigning the doc author for their review and comment.

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- thanks for the question! I'll check, but I'm pretty sure the answer is no, you can't control that at this point. You did the right thing by creating the suggestion at https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/40073473-change-default-order-of-report-page-visual-fil

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- I confirmed, the answer is no, they don't stay at the top.
