### ISSUE TITLE
error when connect to sharepoint list

### ISSUE THREAD

**Issue by Jessicaoo** [MicrosoftDocs/powerbi-docs#2012]
Hi team, could you help to solve the error when I tried to connect to sharepoint list by following the guidance? The error popped up after step 6 on part1, and it said that "Access to the resources is forbidden." Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57e8911-0181-d93e-4bd6-ebb6b86324c9
* Version Independent ID: 2cce7962-5ee9-5f67-af93-2c67bb10911f
* Content: [Create a report on a SharePoint List - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sharepoint-online-list#feedback)
* Content Source: [powerbi-docs/desktop-sharepoint-online-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sharepoint-online-list.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @Jessicaoo - I couldn't reproduce your experience and believe it's a permissions issue to the resource. I'm adding the author to take a look and verify. You may want to try asking the community here: https://community.powerbi.com/

**Comment by Jessicaoo** [comment]
Hi,Kate,
Thanks for replying. The list is based on a folder I created under Teams. It’s a private one. Is it the matter that making connection failed? How can I solve this? Thanks for help.

Regards
Jessica

发自我的iPhone

在 2020年4月3日，07:04，Kate Follis <notifications@github.com> 写道：

﻿

Hi @Jessicaoo<https://github.com/Jessicaoo> - I couldn't reproduce your experience and believe it's a permissions issue to the resource. I'm adding the author to take a look and verify. You may want to try asking the community here: https://community.powerbi.com/

**Comment by Amdisilword** [comment]
Hi
I have the same issue. "Details: "Access to the resource is forbidden.". 
The first time I tried to Connect to Sharepoint folder. I entered the URL code for specific the sharepoint site. 
The next window was Share point access screen. Here I chose Windows. And then it denied after click on Connect.
Now I will tried again and use Microsoft Account. After enter URL code again. It just write "Access to the resource is forbidden.".
The Share Point Access screen doesn't appear so I can change my choice.

Some who can help ?

**Comment by Amdisilword** [comment]
@jessicaoo

**Comment by Amdisilword** [comment]
Hi @kfollis. 
Out from my describtion. Do you have any idea how to get the Share Point Access screen visible again.

**Comment by kfollis** [comment]
I found a similar question in the Power BI Community - it's a great resource! Does this https://community.powerbi.com/t5/Desktop/Access-Forbidden-connecting-to-SharePoint-Online-List/m-p/604255#M287613 thread help to resolve the problem?

**Comment by Amdisilword** [comment]
Hi  @kfollis 
Many thank you for your guide. 
It was just the issue.

I have been sought  and sought and did never come to this post in the community.
I'am curious which search text you wrote.

Can you remember that ?

**Comment by kfollis** [comment]
I'm pretty sure my search criteria was "SharePoint access forbidden" - I'm very happy that the post helped with your issue!
