### ISSUE TITLE
Useful Intro

### ISSUE THREAD

**Issue by Joe8908** [MicrosoftDocs/powerbi-docs#2013]
I have been doing this a while but I still found the explanations here really clear and useful, especially the Junk Dim, which I had heard about but did not understand. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by kfollis** [comment]
@Joe8908 - I'm glad that you found the explanations useful! Thanks so much for sharing your feedback with us, and I'll be sure to extend your thanks to the author, @peter-myers.

**Comment by Joe8908** [comment]
That explains it. @peter-myers is awesome :-)
