### ISSUE TITLE
Access without work or school account

### ISSUE THREAD

**Issue by alathrop** [MicrosoftDocs/powerbi-docs#2014]
The documentation on this page says you must have a work or school account to sign up for Power BI. With potentially thousands or millions of people losing their jobs due to COVID, they are losing their work email accounts, and also looking for training on products like Power BI. Are there any options in the current economic environment to sign up for Power BI without a work or school address, or using a personal MS account associated with a consumer email?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up for Power BI as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/service-self-service-signup-for-power-bi#feedback)
* Content Source: [powerbi-docs/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @alathrop - thanks for the feedback! The Power BI services relies on Azure AD for authentication, so does require a work or school account. However, you can download and use Power BI desktop with a consumer email account and our Learn resources are also available here: https://docs.microsoft.com/en-us/learn/browse/?products=power-bi

#please-close

**Comment by alathrop** [comment]
Thanks!
