### ISSUE TITLE
Don't think publishing a report is equivalent as using Get Data. 

### ISSUE THREAD

**Issue by Diego-MX** [MicrosoftDocs/powerbi-docs#2015]
From my experience, using Get Data button is better for having access to the P-BI report in the web app for one reason:  editing the report in the web platform saves the changes in the desktop file.  
Before I knew about this functionality, I would often encounter situations where the desktop version and the web version where outdated between each other.  
That is, failing to publish the report from the desktop version, or needing to download a pbix copy from the web platform, after making changes would result in those being outdated. 

Having them being synced via OneDrive is a great feature, and I was surprised to read them being equivalent. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b53a16-6109-2b1b-d9da-37ac34b1cb63
* Version Independent ID: 8f0d70eb-5fbf-5ece-8918-0609b10b69a3
* Content: [Get data from Power BI Desktop files - Power BI](https://docs.microsoft.com/en-us/power-bi/service-desktop-files#feedback)
* Content Source: [powerbi-docs/service-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-desktop-files.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @Diego-MX! Thanks for the feedback. I'm adding the author to review and comment.

**Comment by davidiseminger** [comment]
That's a great point. It's good to refresh the data to ensure they stay in sync. I've added a comment to that effect in the article. Thanks!
