### ISSUE TITLE
Leaflet Maps in PowerBI

### ISSUE THREAD

**Issue by mike-osberg** [MicrosoftDocs/powerbi-docs#2017]
I'm trying to include some Leaflet maps using the R visual - is this a possibility/are there examples of other people trying to do this? Also - if I build these maps, will they still be controllable via slicers and filters from other measures in PowerBI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-visuals#feedback)
* Content Source: [powerbi-docs/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
