### ISSUE TITLE
Will be good the to document Power BI works correctly when the storage's firewall is off.

### ISSUE THREAD

**Issue by rrockbrand** [MicrosoftDocs/powerbi-docs#2021]
Will be good the to document Power BI works correctly when the storage's firewall is off.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#feedback)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @rrockbrand , thanks for your comment. I have forwarded it along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thank you for your feedback. We've put this doc request into our queue, and will review it with other documentation requests.
