### ISSUE TITLE
Can we have a sample when we use several fields for the category?

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2022]
I have scenarios where I have several fields for the category and I want to have a selection based on the combination of those field values/categories.
How can this be achieved?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75effaec-3c6e-83c9-c26e-8e58046cb347
* Version Independent ID: 971d9758-f10b-cddb-f6fa-c007e193e457
* Content: [Power BI visual data point selections - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/selection-api#feedback)
* Content Source: [powerbi-docs/developer/visuals/selection-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/selection-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @djpirra , thanks for you comment. I have forwarded it along to the doc author for consideration.

**Comment by KesemSharabi** [comment]
@uve - is it possible to do what @djpirra describes?

**Comment by uve** [comment]
Hi @djpirra, you can create a new SelectionID for each of your columns:
```
const categorySelectionId0 = this.host.createSelectionIdBuilder()
        .withCategory(categories[0], categoryIndex) 
        .createSelectionId();

const categorySelectionId1 = this.host.createSelectionIdBuilder()
        .withCategory(categories[1], categoryIndex) 
        .createSelectionId();
```
