### ISSUE TITLE
Where to get more information on the types of properties?

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2023]
Like for fonts, font sizes, toggles etc...
Example:
"type": {
     "formatting": {
            "fontSize": true
     }
}

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18bae87-ca93-25e9-26a6-5daf585b4798
* Version Independent ID: 2c2793d0-50a6-c401-3ecf-ccba9f155397
* Content: [Objects and properties of Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/objects-properties)
* Content Source: [powerbi-docs/developer/visuals/objects-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/objects-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @djpirra. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by intellectyxArria** [comment]
Any updates Teams.

**Comment by NaveenIntellectyx** [comment]
Hello Team, any updates on this.

**Comment by KesemSharabi** [comment]
@uve - do we have more information describing the Power BI property types?

**Comment by uve** [comment]
Hello @djpirra,
We're going to extend our docs soon. Currently, you can find more info in [definition file](https://github.com/microsoft/powerbi-visuals-api/blob/master/schema.capabilities.json#L1015).
