### ISSUE TITLE
Problems when using fontSize

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2024]
Hi,
I currently have several objects that I want to set a specific font size on...
I am using something like:
"labelFontSize": {
                    "displayName": "Label Size",
                    "type": {
                        "formatting": {
                            "fontSize": true
                        }
                    }
                }

But I am getting a percentage slider instead of a numeric slider.
What is the issue?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18bae87-ca93-25e9-26a6-5daf585b4798
* Version Independent ID: 2c2793d0-50a6-c401-3ecf-ccba9f155397
* Content: [Objects and properties of Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/objects-properties)
* Content Source: [powerbi-docs/developer/visuals/objects-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/objects-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @djpirra. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @uve,

Can you please assist @djpirra?

Thanks,

Kesem

**Comment by uve** [comment]
Hello @djpirra,
 The numeric slide is not supported currently. Please use the numeric input field instead.
