### ISSUE TITLE
we can't figure out how to schedule the Power Pivot refresh like you can with SharePoint

### ISSUE THREAD

**Issue by MikeSunGithub** [MicrosoftDocs/powerbi-docs#2025]
I have same question asked 1-2 years ago.  " how to schedule the Power Pivot refresh like you can with SharePoint". Kindly update. Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90025eee-cd72-9503-6c1d-c14bb617b5b4
* Version Independent ID: 58e25db4-5d25-ac1d-b763-72d27e943373
* Content: [Host Excel workbooks using Office Online Server (OOS) - Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oos)
* Content Source: [powerbi-docs/report-server/excel-oos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/excel-oos.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @MikeSunGithub. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by MikeSunGithub** [comment]
Confirmed internally , scheduled refresh feature for PBIRS Excel Workbooks is not supported.

**Comment by maggiesMSFT** [comment]
Hi, @MikeSunGithub -- yes, as you confirmed, scheduled refresh isn't supported for Excel workbooks in Power BI Report Server. I've added that to the article. Thanks!
