### ISSUE TITLE
Access Audit Data non-interactively

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#2026]
The page does not talk about accessing audit data in an automated non-interactive way.
Is is possible to access the audit log data (i.e. execute Get-PowerBIActivityEvent) using an Azure Service Principal?
If so, is it possible to grant granular permissions to the service principal - or can/must the Service Principal be set up as a Power BI Service Admin (which isn't very desirable)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @cbailiss. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
Thanks for the patience, @cbailiss. You could automate access to audit data by using the REST API or PowerShell. I've added a link to more detail on the Power BI REST API to the article. PowerShell is another option. Also see this article https://docs.microsoft.com/en-us/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#requirements-to-search-the-audit-log about the required permissions.  This article also describes how to programmatically download data from the audit log. I will add more details in the next article update, and have added this doc enhancement to an internal backlog.

**Comment by cbailiss** [comment]
Hi @kfollis 

For reference (and for anyone else seeing this in the future) the approaches recommended here often **won't** work in practice.  In my organisation and others, Power BI Service Administrators do not have permissions to call the Office 365 APIs/PowerShell CmdLets.

What is needed is a way, as a Power BI Service Administrator, to **non-interactively** (i.e. as a Service Principal) call the Power BI API or Power BI Audit Log CmdLet (i.e. Get-PowerBIActivityEvent).  I have recently worked through a support call on this and it turns out sadly that currently the Get-PowerBIActivityEvent CmdLet and underlying Rest API method doesn't work with Service Principals.  This seems a strange oversight to me, given a lot of audit log data is captured by automated processes.

This limitation should be made clearer in the documentation - it would have saved me and MS support a lot of time if it was documented.
