### ISSUE TITLE
User resizing the visual causes unnecessary rendering overload

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2027]
Hi,

Is there any option to only load the custom visual once the user finishes dragging/resizing the visual?
I am having lag on the custom visual when a user is resizing and the visual keeps redrawing.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4c3363-db7e-fa34-3ade-dc56ab85fbdd
* Version Independent ID: 71959fd9-4aff-cec0-9f14-93ae3923d8be
* Content: [Power BI visuals concepts - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept)
* Content Source: [powerbi-docs/developer/visuals/power-bi-visuals-concept.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/power-bi-visuals-concept.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @djpirra . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @uve,

Can you please assist @djpirra?

Thanks,

Kesem

**Comment by uve** [comment]
Hi @djpirra.
Yes, **"update"** method receives [VisualUpdateType](https://github.com/microsoft/powerbi-visuals-api/blob/master/index.d.ts#L14) as an argument.
Your visual can skip any updates with **"Resize"** type.
