### ISSUE TITLE
"supportsHighlight": true not working

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2028]
I am using the property "supportsHighlight": true in the capabilities.json and using categorical.
In the values I do not see the highlight array. What am I missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80303b53-8f3f-e9d3-f00c-1316b44432ee
* Version Independent ID: 774a462b-8188-ebaf-ee87-863c4c0947c4
* Content: [Highlighting - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/highlight)
* Content Source: [powerbi-docs/developer/visuals/highlight.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/highlight.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @djpirra . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @uve,

Can you please assist @djpirra?

Thanks,

Kesem

**Comment by uve** [comment]
Hi @djpirra,
 Please find the sample of usage "highlight" [here](https://github.com/microsoft/powerbi-visuals-linedotchart/blob/master/src/visual.ts#L384)
