### ISSUE TITLE
Publish to Web does not support he Filter Pane

### ISSUE THREAD

**Issue by fordmaxson** [MicrosoftDocs/powerbi-docs#2029]
Spent time modifying report to use the new filter pane and took out a number of slicers.  Then went to use "Publish to Web" feature to make report available.  Unfortunately, publish to web option does not display the filter pane and there is no option to do so.  Report is useless without the filter, so back to square one.  Found this request ticket that aligns... https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/11725446-add-filter-feature-in-publish-to-web

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter#feedback)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- I can update the docs with that caveat. In the meantime, I hope you up-voted that ticket, https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/11725446-add-filter-feature-in-publish-to-web!

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- updating the article with this consideration. Thanks!
