### ISSUE TITLE
Per Workspace Limit

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2033]
Not sure if there’s a type but the storage limit is 10GB in a shared workspace not 100gb.

There is a per-workspace storage limit of 100 GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-manage-your-data-storage-in-power-bi#feedback)
* Content Source: [powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @itsnotaboutthecell -- Thanks for asking! Good question. I'm checking and will get back to you, and update the article if necessary.

**Comment by maggiesMSFT** [comment]
Hi, @itsnotaboutthecell -- whew, fixing this now. Thanks!
