### ISSUE TITLE
Using Billing API Key

### ISSUE THREAD

**Issue by jjindrich** [MicrosoftDocs/powerbi-docs#2034]
Hi, is it possible to use Billing API key from EA portal ? I cannot find this option in authentication dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by jjindrich** [comment]
I'm refering this API key https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/enterprise-api#enabling-data-access-to-the-api
It was possible to use it for previous version of PowerBI Consumption Insights report

**Comment by mblanco77** [comment]
I think this is critical to enable the billing key api , with this new connector , many roles in an EA use this to control costs

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by alexdrenea** [comment]
Can we get an update on this? It's blocking us from creating a dashboard since not all users have credentials to authenticate to Azure EA portal.

**Comment by davidiseminger** [comment]
@alexdrenea , @mblanco77 , @jjindrich 

The EA API  key isn’t supported by the connector. Azure service principal support is being investigated for possible future support, but currently is not supported.

**Comment by bjornsivertsen** [comment]
Has there been any development since May on this?
