### ISSUE TITLE
no network connectivity information

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/powerbi-docs#2035]
no network connectivity information
port / egress and ingress

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by maggiesMSFT** [comment]
Hi, @bakerm00 -- thanks for asking! Assigning to the author to investigate.

**Comment by arthiriyer** [comment]
Requested information is documented here https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication

**Comment by mihart** [comment]
Hi @bakerm00 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
