### ISSUE TITLE
"You should instead upload and replace file B, which keeps the same item ID."

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/powerbi-docs#2037]
So the implication of this paragraph is that the only way to keep a OneDrive csv file in sync is to use the file explorer to drag the new file into onedrive.  If you _copy_ the file from powershell or simple run a script to recreate   the file you lose sync.  This seems like a thoroughly poor design decision but if it really is the way things work, then the documentation would be a lot more helpful if it gave some tips as to how a *script* can refresh a CSV in a safe manner.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @NeilMacMullen -- thanks for your comment. Assigning to the author to investigate.

**Comment by NeilMacMullen** [comment]
Thanks @maggiesMSFT  After further investigation it seems that the paragraph is unnecessarily alarmist.  Copying over, or recreating the file in your locally synced OneDrive folder appears not to cause PowerBi to lose track of it.  (Perhaps there is some other action that can lead to this problem but I haven't found it.)  However one thing that is not clear from the documentation is that it can take PowerBI some time (5-10 minutes) to refresh a dataset _even after sync has completed on your local machine and after you're used "Refresh Now" in the web UI_.  This can certainly make it appear that sync has been broken so it would be good to add this information.

**Comment by davidiseminger** [comment]
These are great points @NeilMacMullen - I've reworded that note (and put it into a normal paragraph, to avoid it being so alarmist) and added a note about the potential delay. Thanks!
