### ISSUE TITLE
Azure Cost management connecting to Azure Gov.

### ISSUE THREAD

**Issue by KevinDMack** [MicrosoftDocs/powerbi-docs#2038]
Is there any guidiance around connecting the cost management power bi reports to Azure Government.  I work with a lot of customers that want to use this, but are receiving errors when they try to get it connected to their Azure Gov tenant.  Any guidiance?

**Comment by maggiesMSFT** [comment]
Hi, @KevinDMack -- are you referring to a specific article in the Power BI docs? I'd like to direct your question to someone who can answer it. Thanks!

**Comment by KevinDMack** [comment]
Specifically when you select "Get Data" one of the options is "Azure Cost Management", and when you select that and try to connect to an Azure Government Enrollment.  It errors out.  I have more details but it has some customer specific details.  So happy to email MSFT internal.

**Comment by maggiesMSFT** [comment]
Hi, @KevinDMack -- thanks for asking! This sounds like a product question. Please submit your question through the channel we discussed. Good luck!
