### ISSUE TITLE
Unable to generate Token in C# - with username and reportId

### ISSUE THREAD

**Issue by Assad-Baig** [MicrosoftDocs/powerbi-docs#2039]
Can we have C# example for embedding a paginated report for your customers, for method Reports.GenerateTokenForCreateInGroup() ?

where you specify username (mapped to UserId)?

Equivalent to following JSON:
{
    "accessLevel": "View",
    "reportId": "cfafbeb1-8037-4d0c-896e-a46fb27ff229",
    "identities": [
            {
                    // Replace the 'username' with a paginated report parameter
                    "username":     "...",
                    "reports: [
                        "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
                    ]
            }
    ]
}

and why you need "Create" (GenerateTokenForCreateInGroup) when you are "Veiw" (GenerateTokenInGroup)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561fba06-3092-f009-343e-b37f133bee44
* Version Independent ID: e0d74c12-1a25-18ba-e511-49466055cb98
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/paginated-reports-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded/paginated-reports-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/paginated-reports-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by Assad-Baig** [comment]
I found it and might be helpful to others: (you do not need GenerateTokenFor*Create*InGroup or any datasetid)

generateTokenRequestParameters = new GenerateTokenRequest(accessLevel: "view", identities: new List<EffectiveIdentity> { new EffectiveIdentity(username: "myCustomUserName001", reports: new List<string> { report.Id.ToString() }) });

var tokenResponse = await client.Reports.GenerateTokenInGroupAsync(WorkspaceId, report.Id, generateTokenRequestParameters);

**Comment by maggiesMSFT** [comment]
Hi, @Assad-Baig -- thanks for your question and your answer! Referring to the author for further action.

**Comment by KesemSharabi** [comment]
Hi @Assad-Baig,

The scenario you're describing, embedding paginated reports, requires service principal (see [prerequisites](https://docs.microsoft.com/power-bi/developer/embedded/embed-paginated-reports-customers#prerequisites)).

You can find a code example in [create the embed token](https://docs.microsoft.com/power-bi/developer/embedded/embed-paginated-reports-customers#create-the-embed-token) (not an end-to-end example).

Hope this helps,

Kesem

**Comment by Assad-Baig** [comment]
Thank you Kesem for the reply.
I do understand that you do need Service Principle for the paginated report, but my question was about something else.
In the article, it emphasis to use "GenerateTokenForCreateInGroup" API to create a token, which is incorrect.
You do not need "GenerateTokenForCreateInGroup" which requires DatasetId for report creation (Note: datasetId is not present in your JSON)  --- so for basic RLS context, you only need "GenerateTokenInGroup" to create a token---- for which you do not need to specify datasetId. --- Make sense?
Regards,Assad Baig 

    On Monday, May 25, 2020, 08:22:33 a.m. EDT, Kesem Sharabi <notifications@github.com> wrote:  
 
 


Hi @Assad-Baig,

The scenario you're describing, embedding paginated reports, requires service principal (see prerequisites).

You can find a code example in create the embed token (not an end-to-end example).

Hope this helps,

Kesem

**Comment by KesemSharabi** [comment]
Hi @Assad-Baig,

You're correct and thanks for pointing this out.

I'll replace GenerateTokenForCreateInGroup with GenerateTokenForCreateInGroup in the [paginated reports article](https://docs.microsoft.com/power-bi/developer/embedded/paginated-reports-row-level-security).

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @Assad-Baig,

I replaced GenerateTokenForCreateInGroup with [GenerateTokenInGroup](https://docs.microsoft.com/rest/api/power-bi/embedtoken/reports_generatetokeningroup) in [Implementing row-level security in embedded paginated reports](https://docs.microsoft.com/power-bi/developer/embedded/paginated-reports-row-level-security).

Once again, thanks for your feedback,

Kesem

**Comment by Assad-Baig** [comment]
Hi Kesem,
Thank you, Much appreciated!
Regards,Assad Baig 

    On Sunday, June 7, 2020, 03:53:55 a.m. EDT, Kesem Sharabi <notifications@github.com> wrote:  
 
 


Hi @Assad-Baig,

I replaced GenerateTokenForCreateInGroup with GenerateTokenInGroup in Implementing row-level security in embedded paginated reports.

Once again, thanks for your feedback,

Kesem
