### ISSUE TITLE
A few grammatical errors and typos

### ISSUE THREAD

**Issue by skepticatgit** [MicrosoftDocs/powerbi-docs#204]
Please see these sections
1. Section "Pushing data to datasets": Power BI REST APIs can be used to create and send data to push datasets and to and streaming datasets.
2. Section "Pushing data to datasets": Take now, however, that the Azure AD (AAD) approach still works to push data into the dataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Fixed typos - thanks!
