### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by thegreatfatzby** [MicrosoftDocs/powerbi-docs#2040]
Should "If row-level security ISN'T defined, such caches aren't shared across users." be "If row-level security IS defined, such caches aren't shared across users"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#feedback)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @thegreatfatzby -- thanks for asking! Referring to the author to investigate.

**Comment by davidiseminger** [comment]
You're right - thanks for the close read! I've fixed that in the doc.
