### ISSUE TITLE
See Records and Show Data - rename, and some content

### ISSUE THREAD

**Issue by MatthLee** [MicrosoftDocs/powerbi-docs#2041]
https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-see-data-see-records.md

These options are now "Show as table" and "Show data point as a table" in the context menu, and "Visual table" and "Data point table" in the new ribbon. Please update strings, and screenshots.

Also, for the second one - data point table - we need to add or update the text to state that it will show all the dimension fields related to the data point, not ALL fields. We have customer confusion around this - we don't show all the other values and measures in the table, only the dimensions (non value/measure).

![image](https://user-images.githubusercontent.com/13227614/79012231-aec91000-7b1a-11ea-8146-deb0eb45eb3f.png)

**Comment by maggiesMSFT** [comment]
Hi, @MatthLee -- thanks for pointing that out. Referring to the author of https://docs.microsoft.com/en-us/power-bi/desktop-see-data-see-records to take care of it.

**Comment by davidiseminger** [comment]
Updated - will go out with today's publishing run.
