### ISSUE TITLE
Need "powerbi" filesystem for this to work

### ISSUE THREAD

**Issue by tekmerion** [MicrosoftDocs/powerbi-docs#2043]
None of the steps that require the creation of the "powerbi" filesystem in the Storage Account Blob Containers are included in this document any more.  I had to delete and recreate my Storage Account that is permanently linked to my PowerBI tenant, and I tried to follow these steps to recreate it - but it wouldn't work.  I remembered that there used to be steps requiring the existing of a "powerbi" filesystem - with permissions assigned to the Power BI Service, Power BI Premium, and Power Online Query service accounts in order for this to work.  Once I did those steps (from memory) - it worked again.  Would recommend that you work those back into this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#feedback)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @tekmerion . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by MikeLarah** [comment]
I'm not sure if something has changed since this comment, but I found that connecting the Data Lake to Power BI worked fine without having to create the 'powerbi' filesystem myself. In fact, it explicitly errored when I tried to connect a Data Lake with a pre-existing 'powerbi' filesystem.

**Comment by davidiseminger** [comment]
Sounds like the guidance now works as described. If not, feel free to reopen this. You might also find more specific guidance and feedback in the Power BI community, found at https://community.powerbi.com.
