### ISSUE TITLE
"Sorty by" not available on Modeling tab

### ISSUE THREAD

**Issue by montybax** [MicrosoftDocs/powerbi-docs#2044]
To sort on a different field, need to: (1) sort the visual by a field via the ... menu of the visual. (2) Select that field in the Fields pane (right-hand side). The "Column tools" tab should become active in the ribbon. (3) Drop down the "Sort by column" list. (4) Select the field you want to sort on. (5) The visual should sort on the desired field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sort-by-column#feedback)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @montybax . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by bigarabuza** [comment]
Thanks for this comment! Took me way too long to figure how to do this!

**Comment by mihart** [comment]
Hi @montybax , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
