### ISSUE TITLE
how to "order by column" if the data source is SSAS tabular?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2046]
@aisbergde commented on [Sun Apr 12 2020](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/13)

"Sort by Column" is not available if the database is SSAS tabular.
How to sort by column in this case?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sortieren nach Spalten in Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-sort-by-column)
* Content Source: [powerbi-docs/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Sun Apr 12 2020](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/13#issuecomment-612686753)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidiseminger** [comment]
Thanks for your comment, @CeciAc . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
