### ISSUE TITLE
Email subscription - Free users

### ISSUE THREAD

**Issue by shakanand** [MicrosoftDocs/powerbi-docs#2047]
In a non-premium setup, free users cannot be the recipient of email subscriptions.   This case is not documented in our docs. Please update the docs to reflect this case.

https://docs.microsoft.com/en-us/power-bi/service-report-subscribe

**Comment by mihart** [comment]
Thanks for your comment, @shakanand . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @shakanand -- thanks for your comment. I've added the info in a bullet point in https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-report-subscribe#considerations-and-troubleshooting. Change should be live this afternoon.
