### ISSUE TITLE
What happens to the alert once it crosses the threshold limit? 

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#2049]
Some cards / KPIs numbers involves sums that increase and decrease. for example Sales and refunds total. The net income is calculated after summing up the total sales and total refunds. If i have a card representing the same and the number crosses my threshold of $450k but after some time decreases back to $400k due to refunds in place;  does the alert come back online? 

Does the alert remain active in future until disabled or deleted, assuming that the threshold for the alert was crossed early on..?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-set-data-alerts#feedback)
* Content Source: [powerbi-docs/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @dhruvinushah . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @dhruvinushah . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
