### ISSUE TITLE
Change conection string

### ISSUE THREAD

**Issue by ginanjarnugroho** [MicrosoftDocs/powerbi-docs#205]
Error when change conection string in powerbi import (nondirect query). Please give solution please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c227d05-ba6d-2a1a-860d-55b59517273e
* Version Independent ID: 731538dd-109b-842c-6086-f412c0ffe0a8
* Content: [Code snippets for migrating content from Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/migrate-code-snippets)
* Content Source: [powerbi-docs/developer/migrate-code-snippets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/migrate-code-snippets.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ginanjarnugroho Thanks for your comment. Sounds like this is a product question, so please use the product feedback button or contact support at support.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we can always reopen the issue.
