### ISSUE TITLE
Connector stop working with new-generated API keys 

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#2051]
Hi team. Starting from 10.04 connector stop working with keys which were generated on 10.04 and later.
I've tested it both with Demo EA enrollment 8608480 (which was re-generated (not by me) on the EA portal on 10.04) and with several production EA enrollments, which were generated from 10.04 till 14.04.
If you try to go through interface https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#connect-with-azure-consumption-insights, on the step where you choose tables, system (again) asks for API KEY and here always thinks that it is incorrect.
If you go with code https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#migrate-from-the-azure-enterprise-connector it just thinks that the API Key is incorrect.
Tried to re-enter keys, to delete them from data sources, nothing helped.
Accounts, whose API Keys were generated before (have 5 to test) are fine, with both regular update and if you try to re-build connection from scratch. 
Reported it also to Issue forum and microsoft service-now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#migrate-from-the-azure-enterprise-connector)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by ryanferguson** [comment]
Did you ever get this solved?  Seeing the same issue.

**Comment by mihart** [comment]
Thanks for your comment, @chizhova . Did you find your answer on the Issues site? If not, this looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
