### ISSUE TITLE
Power BI update credentials issue

### ISSUE THREAD

**Issue by ajEnthusiastic** [MicrosoftDocs/powerbi-docs#2054]
I tried all steps above for DirectQuery Power BI sample. After updating credentials when I tried to view, it shows error as 'Couldn't load the model schema associated with this report. Make sure you have a connection to the server, and try again'. When I downloaded same file, opened locally and checked connections, everything is updated as expected & report is also loading correct data. On server it takes more than 24 hours to update report properly.
All above scenario is for Premium workspaces. It is working fine with other workspaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49734fef-2078-76da-a1a1-6a0f1beb49d3
* Version Independent ID: 85700b22-60a2-388d-6230-9b27e8a80d04
* Content: [Configure credentials programmatically for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/configure-credentials?tabs=sdk3#feedback)
* Content Source: [powerbi-docs/developer/automation/configure-credentials.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/configure-credentials.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @ajEnthusiastic . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
@amit-shuster - can you please assist with this?

**Comment by amit-shuster** [comment]
This is not documentation issue. Please contact support: https://powerbi.microsoft.com/en-us/support/
