### ISSUE TITLE
Outdated workspace content

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#2055]
The information listed above is outdated in multiple ways. The screenshots are based on the old Power BI inteface, as well as the old workspace experience. In the section listed after this sentence, the information refers to Admin/Member workspace permissions which are only applicable to v1 / old workspaces.  https://docs.microsoft.com/en-us/power-bi/service-delete#to-remove-a-workspace-from-your-list 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, dataset, or workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/service-delete#feedback)
* Content Source: [powerbi-docs/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-delete.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @marclelijveld ! You're right, the article needs to be updated. Adding it to the backlog.

**Comment by maggiesMSFT** [comment]
Hi, @marclelijveld  -- good catch! Fixing it now; update will be live tomorrow.
