### ISSUE TITLE
Cancel a subscription

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs#2056]
There is an inconsistency in the explanation for expired or canceled subscriptions:
- The first note on the site states that "After a (premium) subscription expires, your content reverts to a shared capacity. Models that are greater than 1 GB are not supported in shared capacity.". First question would be: what happens to models greater than 1 GB?
- The section "Cancel your subscription" states: "After 30 days, you will no longer be able to access your Premium capacities or workspaces in them." - refer to https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase#when-canceling-or-your-license-expires. Even worse, point 5 in the "Cancel you subscription" section states that "This page will also let you know when the data will be deleted for the subscription.". 
These are 3 different statements from "revert to a shared capacity" to "not accessible" to "data will be deleted". Would be great if that could be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase#feedback)
* Content Source: [powerbi-docs/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-purchase.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mpoeckl . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @mpoeckl , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
