### ISSUE TITLE
Cancelling subscriptions - additional scenarios/questions

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs#2057]
Additional questions with regards to cancelling of subscriptions would be:
1 What if a cancelled subscription affects only a part of the resources of one capacity? Assume that there are 1x P1 and 1xP2 subscriptions (24 v-cores in total) and one premium capacity assigned with 16 V-cores (P2), additional 8 v-cores are free. What happens if the P2 subscription gets cancelled?
2. Is it possible to purchase a new premium subscription within 30 days to "re-activate" the expired capacity (any manual re-assignment of cores of the expired capacity needed?)
3. Is it possible to downsize other existing premium capacities (reduce the v-core/capacity SKUs) to free up v-cores? 
4. If you have multiple premium licenses/subscriptions and multiple premium capacities set-up and only a part of the premium subscriptions are cancelled that only a part of the existing capacities would be covered by the remaining number of v-cores, how does Power BI decide which of the capacities to "deactivate"? Are premium capacities that are "out of licenses/v-cores" somehow marked/shown in the Admin portal/capacity settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase#feedback)
* Content Source: [powerbi-docs/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-purchase.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mpoeckl . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Old issue and article has been heavily updated. Closing.
