### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by mjc543** [MicrosoftDocs/powerbi-docs#2058]
Clicking on "requires measures to be defined in the external model" hyperlink in the 'Can't drag anything to the PivotTable Values area' section of this article doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae990a42-30ce-e2cd-ef81-b2caba935050
* Version Independent ID: cd6b2f01-2ab8-bd8e-67a5-29a8f1ce3555
* Content: [Troubleshooting Analyze in Excel in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-troubleshooting-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/desktop-troubleshooting-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-troubleshooting-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mjc543 . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Sorry about that - that article is no longer available. I've removed the link.
