### ISSUE TITLE
unable to publish

### ISSUE THREAD

**Issue by Wlibin-92** [MicrosoftDocs/powerbi-docs#2059]
When I try to publish the report, it shows:
Sorry , no workspaces were found in Power BI Service, please try again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets#feedback)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
I'm sorry you're having problems, @Wlibin-92. There are some limitations listed in the article, you might check into those and if you still encounter issues, reach out to https://powerbi.microsoft.com/en-us/support/
