### ISSUE TITLE
Old connector deprecation date 

### ISSUE THREAD

**Issue by dannradkov** [MicrosoftDocs/powerbi-docs#2060]
Can you define when the old connector is going to be deprecated ? 
Also what are the differences between Cost management connector and  Azure Consumption Insights and Azure Cost Management (Beta) in practice ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-cost-management#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@dannradkov - here's the answer for you, thanks for your patience.

There is no ongoing development for the Azure Consumption Insights connector. However, Microsoft hasn’t announced an official deprecation schedule for it. All new features will be included in the Azure Cost Management connector. The significant difference between the two connectors is that the Azure Cost Management connector supports Reservations. The older Azure Consumption Insights connector doesn’t.
