### ISSUE TITLE
Other Workspaces

### ISSUE THREAD

**Issue by cajslc** [MicrosoftDocs/powerbi-docs#2062]
It would be fantastic if there was information included to determine where a report or dashboard is located that is referenced in the Other Workspaces section of Related Content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f150614-d6da-f190-519b-b6fca174771c
* Version Independent ID: 6ae71716-e278-d75f-f024-23785b65427e
* Content: [View related content from dashboards, reports, and datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-related#feedback)
* Content Source: [powerbi-docs/consumer/end-user-related.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-related.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Thanks @cajslc! I'm assigning your issue to the doc owner for review. They'll follow up soon.

**Comment by mihart** [comment]
Hi @2cajslc, 
Thanks for your question. Can you provide additional details?  Are you looking at related content for a dashboard or report?  Where are you seeing "Other Workspaces"? And, by location, do you want to know the name of the workspace, or whether it is in capacity, etc?  Thanks.
