### ISSUE TITLE
Using Service Principal w/ On premise Data Gateway 

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#2063]
In order to use the Service Principal with the on-prem data gateway, you have to make an API call to Add Datasource User REST API. What is not documented anywhere though, is that the "Identifier" for this call is NOT the AAD application ID or the service principal Object ID. In order to run that successfully, you have to Call "Get Group Users" API endpoint, which will return a third (Correct) ID value so you can successfully make that call. Otherwise you will just be greeted with a DMTS_InvalidPrinicpals error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks @adamwp1993! I'm assigning to the docs owner for review and they'll follow up soon.

**Comment by adamwp1993** [comment]
@kfollis any update on this? Thanks

**Comment by KesemSharabi** [comment]
Hi @adamwp1993,

Thanks for your comment. We are currently making changes to the way service principal uses on premise data gateway. Once this change takes place (in a few weeks time), we'll update all relevant articles accordingly.
