### ISSUE TITLE
Outdated interface

### ISSUE THREAD

**Issue by alwweb** [MicrosoftDocs/powerbi-docs#2064]
This page still shows the old Power BI Interface (New look off). When I turn the new look on for the full interface, I see sample questions created I assume by some sort of AI, but I do not see my questions.  This page should be updated for the current operations, since I believe the new look is now supposed to be the "official" look.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9707e1ff-5927-e3e4-134d-8d2b04266f9c
* Version Independent ID: bec9f641-757c-b76f-4cee-c823c60222b4
* Content: [Create featured questions for Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/service-q-and-a-create-featured-questions)
* Content Source: [powerbi-docs/service-q-and-a-create-featured-questions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-q-and-a-create-featured-questions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thank you for the feedback, @alwweb. I'm assigning this issue to the docs author for review. They'll follow up soon.

**Comment by maggiesMSFT** [comment]
Hi, @alwweb -- belatedly, thanks for your comment. This article has been updated since your comment and looks up to date now.
Thanks!
