### ISSUE TITLE
Afficher graphique issu table sur point carte géo localisé précisément (long-lat 191015FG.pbix) ?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2065]
@MANTE49 commented on [Wed Apr 15 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/23)

Bonjour, POWER BI DESKSTOP je ne réussis pas à mettre un ou plusieurs graphiques simples issus de ma table sur chaque chef-lieu de région d'un pays, pourtant localisés sans problème (longitude/latitude). Pourtant dans un tuto même de PBI (visuel/Disposition et mise en forme), une visualisation illustre que c'est possible (carte USA) mais ne dit pas comment faire. 
Quelqu'un peut-il me dire comment afficher un ou plusieurs graphiques issus de ma table sur un point géolocalisé précisément (long/lat) ? (voir 191015FG.pbix page 1 publié si besoin°

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Conseils et astuces pour les cartes (y compris l’intégration Bing Maps) - Power BI](https://docs.microsoft.com/fr-fr/power-bi/visuals/power-bi-map-tips-and-tricks#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

---

@srvbpigh commented on [Wed Apr 15 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/23#issuecomment-613884944)

Hello, @MANTE49
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Bonjour, @CeciAc -- Je chercherai quelqu'un qui peut repondre a votre question!

**Comment by maggiesMSFT** [comment]
@CeciAc -- SVP, quelle est l'adresse de ce tuto de PBI (visuel/Disposition et mise en forme) qui a une visualisation illustre que c'est possible (carte USA)? Merci

**Comment by MANTE49** [comment]
Merci Madame, il s'agit du tuto simple de POWER BI

https://docs.microsoft.com/fr-fr/learn/modules/visuals-in-power-bi/12-formatting

Voicice que je voudrais pouvoir faire (capture sur ce tuto), cad afficher en pointsgéolocalisés des graphiques issus de ma table.




J'aifais des essais sans succès sur un rapport pbix (page 1, 191015FG.pbix que jepense avoir publié, si vous pouvez le retrouver, il s'agit de chefs lieux derégions de Côte d'Ivoire, où j'essaie d'afficher desgraphiques camemberts (ouhistogrammes) de proportion filles garçosn du ctcle secondaire). Je peux vousle joindre également.

Avecme remerciements


    Le vendredi 17 avril 2020 à 19:42:04 UTC+2, Maggie Sparkman <notifications@github.com> a écrit :  
 
 


@CeciAc -- SVP, quelle est l'adresse de ce tuto de PBI (visuel/Disposition et mise en forme) qui a une visualisation illustre que c'est possible (carte USA)? Merci

**Comment by maggiesMSFT** [comment]
Bonjour, @CeciAc -- vous dites que vous utilisez les coordines latitude et longitude? Si oui, donc, il n'y a auncune raison que ca ne marche pas. Peutetre que vous serriez obliger d'ouvrir un cas sur le site https://powerbi.microsoft.com/en-us/support/.

**Comment by MANTE49** [comment]
Merci mais je ne trouve aucun résultat à ma question
Hello, how todisplay a graph from my table on a point on a geolocalized map (longitude /latitude) ?

Bonjour, comment afficher un graphique issu de ma table surun point d'une carte géolocalisé (longitude/latitude) ?
J'ai bien dasn ma table une colonne latitude, une colonne longitude, des colonnes contenant les données du graphique, mais je ne peux créer un graphique que sur une ligne. Je ne saus pas comment créeer un graphique par ligne et les afficher sur les points correspondants de la carte. En PJ l'exemple de ce que je veux (Disposition et mise en forme - Learn

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Disposition et mise en forme - Learn

Découvrez la disposition et la mise en forme dans Power BI.
 |

 |

 |


+ mon pbix (voir rapport page 1)Il doit bien exister un moyen d'afficher un graphique simple sur point géolocalisé d'une carte.Merci de me trouver une solution.
    Le samedi 18 avril 2020 à 02:17:59 UTC+2, Maggie Sparkman <notifications@github.com> a écrit :  
 
 


Bonjour, @CeciAc -- vous dites que vous utilisez les coordines latitude et longitude? Si oui, donc, il n'y a auncune raison que ca ne marche pas. Peutetre que vous serriez obliger d'ouvrir un cas sur le site https://powerbi.microsoft.com/en-us/support/.
