### ISSUE TITLE
Pause capacity renders embedded reports?

### ISSUE THREAD

**Issue by joanteixi** [MicrosoftDocs/powerbi-docs#2066]
Hi, 

when we pause a capacity can we render the reports? I'm trying and it seems that an embedded report is rendered when capacity is in pause. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37c7960-448a-0f10-c84a-f9c531452320
* Version Independent ID: 4867daee-c097-cde7-81c9-4f2a44a4f5b3
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Hi @joanteixi - Thanks for the question! I'm assigning your question to the docs author for review. They'll follow up soon.

**Comment by KesemSharabi** [comment]
@amit-shuster - can you please assist with this question?

**Comment by amit-shuster** [comment]
Hi,

You might be using your free trail of embed token, that is why the report is rendered.
When the capacity is paused it is not used.
Please not that the free trail of embed tokens can't be used for production.
