### ISSUE TITLE
The script configureRSServer for the creation the Power BI Report Server web portal in a VM

### ISSUE THREAD

**Issue by RaoulHolzer** [MicrosoftDocs/powerbi-docs#2067]
Marketplace offering has been trying to deploy for almost 2 hours without success.
Looks to be hung up on the REPORTVM/configureRSServer extension.

It fail to install the nuget packageprovider install-PackageProvider -Name "Nuget"

A fast fix is to connect to the vm and set the tls version [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by kfollis** [comment]
Hi @RaoulHolzer. I'm sorry that you're having problems. Is there a particular document you were referencing that needs to be updated? If not, your best bet is to connect with https://powerbi.microsoft.com/en-us/support/.

**Comment by RaoulHolzer** [comment]
Hi, it the https://docs.microsoft.com/en-us/ower-bi/report-server/tutorial-explore-report-server-web-portal page. The creation of the VM doens't work

**Comment by kfollis** [comment]
Thanks for clarifying! I've assigned this to the documentation owner to investigate.

**Comment by maggiesMSFT** [comment]
Hi, @RaoulHolzer -- thanks for asking. I'll check and see if the VM should still work.
Here's a working link to the article: https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal

**Comment by maggiesMSFT** [comment]
Hi, @RaoulHolzer -- This should be fixed now. If not, let us know. Thanks!
