### ISSUE TITLE
Microsoft Power BI Information Service

### ISSUE THREAD

**Issue by HarrisburgUSysAdmin** [MicrosoftDocs/powerbi-docs#2068]
Does Microsoft Power BI Information Service need to be in global admins? I have been auditing our Azure AD roles and found Microsoft Power BI Information Service listed as a global admin.  Does seem correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f546db7-20fa-c87d-f7a4-a0a931f47e05
* Version Independent ID: 0180dfc6-d05d-8517-ec8c-94723f0f832e
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-portal)
* Content Source: [powerbi-docs/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @HarrisburgUSysAdmin - thanks for the question. I'm verifying with our engineering team, but this appears to be related to an older product version. I located this related community thread: https://community.powerbi.com/t5/Power-Query/What-is-the-quot-Microsoft-Power-BI-Information-Service-quot/td-p/568946 which may help to resolve this for you. I'll follow up with any additional info I can get.

**Comment by kfollis** [comment]
Hi @HarrisburgUSysAdmin - I confirmed that the account you see in global admins is a legacy artifact of a previous version of Power BI (original implementation). It's not used today and should be safe to remove. 

Closing the issue.
