### ISSUE TITLE
Filter search option

### ISSUE THREAD

**Issue by markshull-TR** [MicrosoftDocs/powerbi-docs#2069]
When selecting Filter Type - Basic Filtering - what triggers the Search option availability? is there a limit to the number of terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter#feedback)
* Content Source: [powerbi-docs/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @markshull-TR -- thanks for your question! Just so I'm clear on what you're asking: Does a field have to have a minimum number of values in a field before you'd see a Search option? Does that paraphrase your question?

**Comment by markshull-TR** [comment]
I have a field that does not toggle on the search option when setting the Basic Filter. All values in the field have only 1 occurrence each.  probably over couple hundred values (don't have the exact count)

**Comment by maggiesMSFT** [comment]
Hi, @markshull-TR -- That's plenty of values, definitely. What kind of values are they -- e.g., numbers, calculated column, measure, text...?

**Comment by markshull-TR** [comment]
Hi maggieMSFT,
The values are numeric,  6 and 7 digits in length

**Comment by maggiesMSFT** [comment]
Thanks, @markshull-TR. I have a hunch, but I'll confirm first and get back to you.

**Comment by paulinbar** [comment]
Hi @markshull-TR, adding this issue to our work item backlog. Closing this issue here now. Thanks for providing your feedback!
