### ISSUE TITLE
Unclear on special characters

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/powerbi-docs#207]
"prefix those special characters with an escape code (_x) and the 4-digit Unicode" but the examples show "Table Name" as Table_x0020_Name which has a prefix and a suffix of _. Which is it? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Great catch, @o-o00o-o! The article is unclear. Turns out you also need the underscore after the 4-digit Unicode value. I'll update the article to state that.

**Comment by maggiesMSFT** [comment]
Done
