### ISSUE TITLE
Update this and related doc for MG for perf improvement phase 1

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/powerbi-docs#2070]
Please add a sentence or two to reflect the fact that query text and query result traffic for imported data models is no longer transiting through the home region. MG for perf improvement phase 1 is in production: https://powerbi.microsoft.com/en-us/blog/announcing-performance-improvements-for-multi-geo-premium-capacities/. Need to clarify that the report metadata still comes from the remote region and weird DNS routing can still take traffic out of the region. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-multi-geo#feedback)
* Content Source: [powerbi-docs/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks @sergeigms. Assigning to the docs author for review.

**Comment by davidiseminger** [comment]
Added a bullet list item to Limitations and considerations. Thanks for the update!
