### ISSUE TITLE
formatting - datetime and number format for Desktop

### ISSUE THREAD

**Issue by MatthLee** [MicrosoftDocs/powerbi-docs#2071]
https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/supported-languages-countries-regions.md

Can we add a note about how Desktop gets default number and date format options? We have had a few customer complaints about this.

Windows Settings -> Region -> "Additional date, time, and regional settings" link
![image](https://user-images.githubusercontent.com/13227614/79490206-5b026f00-7fd1-11ea-920a-3df431ac12bd.png)

This launches the old Control Panel to Clock and Region. Click the "Change date, time, or number formats" option here.
![image](https://user-images.githubusercontent.com/13227614/79490280-78373d80-7fd1-11ea-9f0e-8677d80cb756.png)

Ensure it says "Match Windows display language"
![image](https://user-images.githubusercontent.com/13227614/79490314-85ecc300-7fd1-11ea-9e20-ee1a1f40cb36.png)
Or change it if necessary.

This setting controls default date format (separator, month before day or opposite, etc) and number thousands/decimal separator.

**Comment by kfollis** [comment]
Thanks for the feedback, @MatthLee. I'm assigning to the author to consider your update request.

**Comment by maggiesMSFT** [comment]
resolving in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/3726
