### ISSUE TITLE
SHOW GRAPHIC ON POINT GeOLOCALISE of a map?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2072]
The comments below were machine-translated
@MANTE49 commented on [Thu Apr 16 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/25)

How do you display a graph on a geolocated point (longitude / latitude) precisely on a map? The graph data is in the table. Should we create a graphic field? If yes, how ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Changer le mode tri d’un graphique dans un rapport - Power BI](https://docs.microsoft.com/fr-fr/power-bi/consumer/end-user-change-sort)
* Content Source: [powerbi-docs/consumer/end-user-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/consumer/end-user-change-sort.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

---

@srvbpigh commented on [Thu Apr 16 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/25#issuecomment-614558447)

Hello, @MANTE49
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @CeciAc and @mante49 . This looks like a support request or product question rather than documentation feedback. Your question is about maps but the article is about sorting. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
