### ISSUE TITLE
Direct Query working with MFA

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#2073]
It seems that at least with MSFT users (@microsoft.com) MFA works also with direct query and SQL DW, which seems against what we report in our documentation.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5c2cbb-f3de-c63e-fc74-a5157d5f5c9c
* Version Independent ID: dd280f16-bad8-5f60-f960-208047f6f9b2
* Content: [Azure SQL Data Warehouse with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-sql-data-warehouse-with-direct-connect)
* Content Source: [powerbi-docs/service-azure-sql-data-warehouse-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-sql-data-warehouse-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @frvigano -- given you're a MSFT user, I'm going to reach out to you offline with a suggestion. Thx!
