### ISSUE TITLE
Rest API for the lineage would be awesome.

### ISSUE THREAD

**Issue by mohammad-amiri** [MicrosoftDocs/powerbi-docs#2075]
If we can have the lineage report API it would be great.
I would like it at the organization level.
  
This level of detail tells me everything I want to know about a report/dataset/.....

Another thought would be a set of Power BI admin reports (organization level reports)  that would provide 
what would be great.
1. Start from the gateway and give details at every level [datasource/dataset...]all the down to the report/dashboard [include all the entities used in the model] -scope organization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b34cb8-3435-8176-a8b9-2a99b2d5ce2d
* Version Independent ID: 3d7b6b44-02c2-1a66-0672-794dd1c3975b
* Content: [Data lineage - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-data-lineage#feedback)
* Content Source: [powerbi-docs/collaborate-share/service-data-lineage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-data-lineage.md)
* Service: **powerbi**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @mohammad-amiri -- good ideas! Try searching for them on the Power BI ideas site, https://ideas.powerbi.com/forums/265200-power-bi, to see if anyone else has suggested them. If not, please enter them there. Good luck!
