### ISSUE TITLE
What are the selected fields to study?

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2076]
Hi, when following the example I get this message in the step where the fields are chosen:

We could not complete the analysis to recommend fields at this time. We've selected all the fields as default. You may change the selections to include only the fields you want the model to study.

This does not match with the screenshot provided and it is not clear which fields to choose.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a Machine Learning model in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-tutorial-build-machine-learning-model)
* Content Source: [powerbi-docs/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- how are you? Assigning to the author to check into your issue. cheers!

**Comment by davidiseminger** [comment]
Hi there - there may be variations in how the sample tutorial operates, so you can choose which fields you would like. If you'd like more in-depth guidance about how the feature works, you can check in the Power BI Community, found at https://community.powerbi.com.
