### ISSUE TITLE
Working Code Sample

### ISSUE THREAD

**Issue by Perams** [MicrosoftDocs/powerbi-docs#2077]
First things first, Thanks a ton for getting this much needed feature out. 

However, can we get a full working sample rather than bits and pieces of code here. For example in the code above "PostExportRequest" you are using Name and Client variables that are defined in the function, I am sure you would have declared them in your code. if you can post the entire code or redirect us to a github link for the entire code. It will be much helpful.

Thanks in advance 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#feedback)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @Perams -- thanks for your feedback! Assigning to the author to assess.

**Comment by YMainich** [comment]
Yes, I agree with Peter.  If you can provide a github link for the entire code, it will be great.

**Comment by Sil3ntGam3r** [comment]
I also want to see the entire code

**Comment by Sil3ntGam3r** [comment]
> First things first, Thanks a ton for getting this much needed feature out.
> 
> However, can we get a full working sample rather than bits and pieces of code here. For example in the code above "PostExportRequest" you are using Name and Client variables that are defined in the function, I am sure you would have declared them in your code. if you can post the entire code or redirect us to a github link for the entire code. It will be much helpful.
> 
> Thanks in advance
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
> * Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
> * Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#feedback)
> * Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
> * Service: **powerbi**
> * Sub-service: **powerbi-developer**
> * GitHub Login: @KesemSharabi
> * Microsoft Alias: **kesharab**

Any progress on this request?
This will help everyone

**Comment by YMainich** [comment]
Yes, Could you please provide any update on this request?

**Comment by Sil3ntGam3r** [comment]
@maggiesMSFT  and @KesemSharabi Its been almost a month since this request has been put in. Can we please get an update on this?

**Comment by KesemSharabi** [comment]
Hi @Perams,

Apologies for the length of time this is taking. Currently we don't have an end-to-end example, however, I'm meeting with the development team to improve the current code sample. Hopefully, I'll be able to update the article shortly.

Thanks,

Kesem

**Comment by Sil3ntGam3r** [comment]
Thank You. Looking forward to hearing from you

**Comment by KesemSharabi** [comment]
Hi @Perams,

We improved the code samples in [Export Power BI report to file](https://docs.microsoft.com/power-bi/developer/embedded/export-to).

This included changing `Name` to `pageName` and adding this comment: The 'Client' object is an instance of the Power BI .NET SDK.

I hope this adds clarity to the article.

Thanks,

Kesem

**Comment by MarcoAntonioLenguaHinojosa** [comment]
Hi folks,
exactly that comment  // The 'Client' object is an instance of the Power BI .NET SDK
is confusing me. i am using the app owns data with some frontend configurations to invoke a downlaod link on my page, but i dont undestand what this client object is or where to get it from. i tried creating one through the embed service. but it stucks somehow in the aadservice.cs. do i even have to create a new client object or can i use an existing one. the following code is in my new service where i used the code snippets from the link above but it does end with an thread existing code that i dont understand and no file is downloaded. 
    var pbiClient = await EmbedService.GetPowerBiClient();
    var export = await Client.Reports.ExportToFileInGroupAsync(groupId, reportId, exportRequest);
please help me out!
