### ISSUE TITLE
R Package Request for Power BI

### ISSUE THREAD

**Issue by robbiersm** [MicrosoftDocs/powerbi-docs#2078]
Hello - could you please add the radiant package to Power BI? 

https://CRAN.R-project.org/package=radiant

https://github.com/radiant-rstats/radiant

Thanks in advance.

**Comment by maggiesMSFT** [comment]
Hi @robbiersm -- yours looks like a product request, not a documentation issue. Please submit it at Power BI Ideas site, https://ideas.powerbi.com/forums/265200-power-bi. Or check to see if someone has already suggested it, and vote it up!
