### ISSUE TITLE
How to use a personal email address to use Power BI

### ISSUE THREAD

**Issue by 1Steve0** [MicrosoftDocs/powerbi-docs#2079]
[
I was unable to use a work email address to setup Power BI so I needed to use a personal email address @gmail.com.  I found many posts online with frustrated users trying to use personal email addresses to register and it just kept going around in circles and not working. I went to the trouble of contacting Microsoft Support who directed me to JusAnswer.com. I paid $5 but this also was not helpful. Finally I made it through the maze of disjointed and un-linked pages and steps. Personally I feel this warrants its only separate instruction page. Here's how I successfully made it through using a person email address to setup Power Bi free trial without a business email.

1) Register for a Office 365 free trial with my personal email address
2) Visit Microsoft page to transform your personalemail@gmail.com email address into a microsoft business email address. I Created MyName.on.microsoft.com as my Web address and info@MyName.on.microsoft.com as my new business email address.
3) Next visit the start free trial https://signup.microsoft.com/create-account/signup and use the work email or microsoft work email address to complete the sign in process.

Hopefully this will save another user hours and allow you to start learning sooner!
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ce18a4-d4d9-c16f-0ffd-c0711564ca7a
* Version Independent ID: c6c897ce-2f0f-9a13-a321-89b5a8c85152
* Content: [Sign in and sign out - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-sign-in)
* Content Source: [powerbi-docs/consumer/end-user-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @1Steve0 -- thanks for your detailed comment! Assigning to the author to assess.

**Comment by mihart** [comment]
Hi @1Steve0 ,
I too just went through this process.  I've updated the docs and hope the process is now less disjointed.  Take a look at: https://docs.microsoft.com/en-us/power-bi/service-self-service-signup-for-power-bi.  There is a section about email addresses and a link to an article that steps you through what you did above.
