### ISSUE TITLE
Does this work for tabular live connected reports?

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/powerbi-docs#208]
I can't get this to work with a tabular live connected cobe. It just sits there with the pulsing powerbi logo in the middle of the screen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
@KayUnkroth , @mgblythe 
This is a product question, not a doc issue. Reassigning to the URL filters expert, Kay.

**Comment by mgblythe** [comment]
Hi @o-o00o-o - have you tried sharing your filtered URL in the forums (https://community.powerbi.com/) or contacting support?

**Comment by o-o00o-o** [comment]
Hi no I haven’t, I just wanted to check if this is officially supported as many things in power bi don’t work with live-connected reports and I spent 30 minutes trying different things and the only thing that seemed to take just give me a progress bar style pulsing icon in the middle of the screen and never returned. So are you saying that it *is* supported or are you saying that you don't know if it is supported?

**Comment by mgblythe** [comment]
@o-o00o-o - this is supported and should work.

**Comment by jtjones0304** [comment]
We are using URL parameters with a Power BI report sourced from tabular live and it works fine.

**Comment by o-o00o-o** [comment]
Thanks guys, I can confirm that this is now working
