### ISSUE TITLE
Where is the example for Custom valueFormatter?

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2080]
How do you format your data based on specific configurations?
Previously there was powerbi.extensibility.utils.formatting.valueFormatter.
Is it still the case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @djpirra. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
@uve - can you please assist with this question?

**Comment by uve** [comment]
ValueFormatter function is a part of [powerbi-visuals-utils-formattingutils](https://www.npmjs.com/package/powerbi-visuals-utils-formattingutils)
https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-formatting#value-formatter
