### ISSUE TITLE
The link to the download page does not work

### ISSUE THREAD

**Issue by Ghuiles** [MicrosoftDocs/powerbi-docs#2081]
Hi!
The link from "download Power BI publisher for Excel " does not work (download not available anymore). Can you please have a look at it?
BR

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel#feedback)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Ghuiles -- thanks for catching that! You're right, the link is broken because Publisher for Excel has been deprecated. Please use Analyze in Excel. 
I've removed the link from the article.
