### ISSUE TITLE
Missing "reader" role

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2082]
@ThomasKwakman commented on [Sat Apr 18 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/26)

Hi,

For the following sentence, the reader role is missing, isn't it?

"Add security groups, distribution lists, Office 365 groups, or individuals to these workspaces as members, contributors, or admins. See Roles in the new workspaces for an explanation of the different roles."

Have a nice day
Best regards
Thomas Kwakman

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Créer les nouveaux espaces de travail - Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@srvbpigh commented on [Sat Apr 18 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/26#issuecomment-615907194)

Hello, @ThomasKwakman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @ThomasKwakman -- oui, vous avez raison! Je vais ajouter "Viewer role." Merci!

**Comment by maggiesMSFT** [comment]
Hi, @ThomasKwakman -- ok, c'est fait. Merci!
