### ISSUE TITLE
about what is cached

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2083]
Hi, the text says "At present the service only does query caching for the initial page that you land on."   What if the last page I visited was Page 2?  Would Page 2 be the new cached page, because it will be the page I will first see when I reopen the report?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @asocorro . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @asocorro, 

Here's the response I got from one of our experts:  

After caching is turned on, we don’t change which page is cached, regardless of which one was the last you visited. If you need to change which one is cached, simply disable the caching feature to drop the cache information.

Hope this helps,

Kesem
