### ISSUE TITLE
Which Map do you use in Covid-19 dashboard?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2084]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/issues/3

@ofyayla commented 2 days ago — with docs.microsoft.com
I am trying to make the same dashboard, but I didn't find which the map you use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c22af6d-1ae9-9288-51b6-8d05c51d1b56
* Version Independent ID: bd77226f-99c4-9f7f-c353-7fa0891a891c
* Content: [COVID-19 tracking sample for US state and local governments - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-covid-19-us)
* Content Source: [powerbi-docs/create-reports/sample-covid-19-us.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/sample-covid-19-us.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @LukaszPawlowski-MS
* Microsoft Alias: **lukaszp**

**Comment by maggiesMSFT** [comment]
Hi, @ofyayla -- thanks for asking! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @ofyayla -- the US map is a standard shape map in Power BI. The drill-down county maps are Bing maps. Hope that helps!
