### ISSUE TITLE
Broken Webinar Links

### ISSUE THREAD

**Issue by masaki1234** [MicrosoftDocs/powerbi-docs#2086]
Hello,

The following links at https://docs.microsoft.com/en-us/power-bi/webinars are broken and redirect me to https://www.microsoft.com/en-ca/industry/?rtc=1 .

Boost Your BI with Location Intelligence
Register and watch now (https://info.microsoft.com/ww-ondeamnd-boost-powerbi-with-arcgis.html?Is=Website)

Applied Intelligence for Sales & Services
Register and watch now (https://info.microsoft.com/applied-intelligence-for-sales-service.html?Is=Website)

Power BI adoption framework webinar series
https://info.microsoft.com/ww-landing-powerbi-adoption-framework-series.html?Is=Website

Office 365 Finance Pros Webinar Series
Register and watch now (https://aka.ms/Office365FinanceProsPBI)

How to Implement a Successful Data Governance Strategy That Makes Your Organization More Secure
Register and watch now (https://info.microsoft.com/powerbi-data-governance-strategy-ondemand.html?Is=Website)

Accelerating modern BI adoption with Power BI Premium
Register and watch now (https://info.microsoft.com/powerbi-premium-webinar-ondemand.html?Is=Website)

What's new and exciting in Power BI Report Server
Register and watch now (https://info.microsoft.com/whats-new-powerbi-report-server.html?Is=Website)

How Microsoft does Power BI
Register and watch now (https://info.microsoft.com/US-PowerBI-WBNR-FY17-11Nov-29-BIATMIcrosoft274828_01Registration-ForminBody.html?Is=Website)

Regards,
Masaki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a082e6-1c36-af62-95b7-69405696764e
* Version Independent ID: 0425ef3a-54b6-3527-6a02-a60642c9d61c
* Content: [Power BI webinars - Power BI](https://docs.microsoft.com/en-us/power-bi/webinars#feedback)
* Content Source: [powerbi-docs/webinars.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/webinars.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @v-tatero
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @masaki1234.

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
Hi @masaki1234 - Thank you so much for the heads up on the broken links. We are investigating and expect to have those links fixed up soon. I'll keep this issue open for now will respond again when I have confirmed that the webinar links are working again.

**Comment by kfollis** [comment]
Hello again @masaki1234 - Our investigation discovered that some of the webinars weren't current and so were removed. This article with the links simply missed the update. I've removed links to webinars that are no longer valid. Sorry about that! If there's a particular webinar you're looking for, you can submit an idea to https://ideas.powerbi.com/. You might also take a look at the resources in our learning catalog https://docs.microsoft.com/en-us/power-bi/learning-catalog/. Thanks again for flagging the broken links! I'll close this issue now.

**Comment by masaki1234** [comment]
Hi @kfollis, 

I just visited https://docs.microsoft.com/en-us/power-bi/webinars . I still see the same broken links. 

Did you commit your changes?

Masaki

**Comment by kfollis** [comment]
Yes - I should have clarified - the changes are staged and awaiting publishing. Changes will be live later this afternoon. Just getting a little ahead of myself.
