### ISSUE TITLE
Synchronize the cross-analysis filter to other pages

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2088]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.zh-tw/issues/15

the comments below were machine-translated
@myyt0523 commented 19 hours ago — with docs.microsoft.com
Is this synchronization function of cross analysis filter available on the dashboard?
I use this function in power bi desktop to synchronize, but after the power BI service is pinned to the dashboard, this synchronization function is invalid

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks @myyt0523 for the question. I'm assigning this issue to the author to take a look. They'll follow up soon.

**Comment by maggiesMSFT** [comment]
Hi, @myyt0523 -- thanks for asking! If I understand your question correctly, no filters don't apply to dashboards. Please clarify, if that was not your question.

**Comment by myyt0523** [comment]
Hi , @maggiesMSFT , 
Is this synchronization function of cross analysis filter available on different dashboards?
Or it only works on report?
Thanks for your reply~

**Comment by mihart** [comment]
Hi @CeciAc , @myyt0523 ,
I see that this Git issue is a bit old, so I'm going to close it. From what I can tell, maggieMSFT answered your question about filters -- that they cannot be used on dashboards, only on reports.  If you still have questions, please let us know.   
All the best,
the DOCS team
