### ISSUE TITLE
Export row limitations

### ISSUE THREAD

**Issue by laandermsft** [MicrosoftDocs/powerbi-docs#2089]
In the "Limitations and considerations" section it says that "The maximum number of rows that the applications can export from an import mode report to an .xlsx file is 150,000." and it also says that "When using DirectQuery, the maximum amount of data that Power BI can export is 16-MB uncompressed data.". 
I know that there is also a limitation of 150,000 rows usind DirectQuery, but it is not 100% in the documentation. Please make it more clear to avoid misunderstandings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Thanks for the feedback, @laandermsft. I'm assigning this issue to the author for review. They'll follow up soon!

**Comment by mihart** [comment]
Thanks @laandermsft .  Update should go live tomorrow.
