### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by hfulks** [MicrosoftDocs/powerbi-docs#2091]
I saw the preview and pressed "Load", this is the result:  
Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references unknown variable or function 'Python.Execute'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by otarb** [comment]
Please share more details. How are you getting data? pandas.read_csv ?

If you can share your python script and the dataset, that would help to reproduce issue on our

**Comment by lgpreston75** [comment]
I am getting the same error.  I have loaded the data from a SQL Server (unfortunately not able to share it). The pandas script 
``
# for pbi
current_fiscal_week =dataset.loc[dataset['CurFiscalWeek']==1]['FiscalWeekNo'].unique().item()

def get_weeks_cover(subset_df):
    test = subset_df.copy()
    test = test.sort_values(['FiscalWeekNo'])
    stock = test.loc[test['FiscalWeekNo'] <= current_fiscal_week].set_index(['FiscalWeekNo'])['AvailableQuantity']

    commitment = test.set_index('FiscalWeekNo')['Commitment'].reindex(range(1,53)).fillna(0)


    # weekly sales units for weeks after the current fiscal week - for the current SKU - future data!
    ly_sku_sales = test.loc[test['FiscalWeekNo'] > current_fiscal_week].set_index(['FiscalWeekNo'])['WeeklySaleLY']
    cur_seas_avg = round(test['WeeklySales'].mean(),0)

    if ly_sku_sales.index.tolist() != list(range(current_fiscal_week, 52)):
        ly_sku_sales = ly_sku_sales.reindex(list(range(current_fiscal_week, 52))).fillna(cur_seas_avg)

    fcast_sales = ly_sku_sales.copy()
    rest_of_season = fcast_sales
    try:
        rest_of_season.iloc[0] = stock.loc[current_fiscal_week] - rest_of_season.loc[current_fiscal_week] 

        rest_of_season.iloc[1:] = rest_of_season.iloc[1:]*-1
        rest_of_season = (rest_of_season + commitment).dropna()
        rest_of_season = rest_of_season.cumsum()


        week_stockout = rest_of_season.loc[rest_of_season <= 0].index[0]

        if week_stockout is not None:
            if week_stockout == current_fiscal_week:
                weeks_cover = -9999 # out of stock
            else:
                weeks_cover = week_stockout - current_fiscal_week
        else:
            weeks_cover = -9998 #fiscal year covered
    except:
        weeks_cover = -9999 # out of stock

    return weeks_cover

wks_cover = dataset.groupby(['BI_ItemVariantID','Code']).apply(get_weeks_cover).reset_index().rename(columns={0:'Weeks Cover'})``

Someone who worked on the file previously had "store data with enhanced metadata" enable, has this now rendered python scripts unusable in the file?

**Comment by otarb** [comment]
@lgpreston75 please share more details. where are you running this script? As a PowerQuery transformation? 

This article is about using Python as data source but you said you are using SQL to get the data.

**Comment by lgpreston75** [comment]
Apologies, the script is being run as a Python Script in the Power Query Editor on a table which is from a SQL database

**Comment by otarb** [comment]
hello @lgpreston75, can you confirm that you have [Enhanced Metadata (Preview) feature](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata) enabled? 

Currently there is a limitation that reports updated to use new format, do not support Python scripts.

This will be resolved for June release.

**Comment by otarb** [comment]
updated documentation to include in known limitations

**Comment by otarb** [comment]
#please-close @otarb
