### ISSUE TITLE
More transform steps might be needed to get this working

### ISSUE THREAD

**Issue by hfulks** [MicrosoftDocs/powerbi-docs#2092]
When I went through this process, I needed to update all of the CSV column types from text to numeric and decimal. Then after running the Python script, I was left with two datasets and I needed to select the final one prior to closing and applying my changes. Maybe add a note about filtering the Day range too, so that the visuals match... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd46971-2ea5-9271-3b2a-824efc1821e1
* Version Independent ID: 68669cdb-5e4d-bb96-d2d5-bdad4088fb03
* Content: [Using Python in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-in-query-editor)
* Content Source: [powerbi-docs/desktop-python-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by otarb** [comment]
How are you reading csv? PowerQuery should auto-detect types based on top 200 rows by default. There is an option to change it to use complete dataset, or disable type detection altogether.

There are two datasets because there are two variables defined in Python, that is expected.

**Comment by otarb** [comment]
#please-close @otarb
