### ISSUE TITLE
Service content pack for power BI

### ISSUE THREAD

**Issue by sandeeplodhirajput** [MicrosoftDocs/powerbi-docs#2094]
HI i am not able to find servicenow content pack from app.powerbi.com.

can someone please share the link.

DO NOT SHARE BELOW LINKS ITS JUST useless....

https://powerbi.microsoft.com/fr-fr/blog/explore-your-servicenow-data-with-power-bi/

https://docs.microsoft.com/en-us/power-bi/service-connect-to-services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 537ddf19-2c92-8e39-e0f0-b505acf23b0d
* Version Independent ID: 8ed0072d-1e27-19c4-9284-789de828230e
* Content: [Connect to the services you use with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-services)
* Content Source: [powerbi-docs/service-connect-to-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-services.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by samhodgkinson** [comment]
Does this content pack still exist? Can we get an update

**Comment by oloboy** [comment]
I have the same problem question where is the service now connector?

**Comment by maggiesMSFT** [comment]
Hi, @oloboy , @samhodgkinson , and @sandeeplodhirajput -- If you don't see it in AppSource, then I'm afraid it  isn't available anymore. I'm checking.

**Comment by pranaysharmamanulife** [comment]
@maggiesMSFT : Any update?

**Comment by maggiesMSFT** [comment]
Hi, @samhodgkinson , @pranaysharmamanulife , @oloboy -- I'm sorry, the Service Now content pack no longer exists. I recommend requesting or suggesting it at https://ideas.powerbi.com/ideas/. 
cc @paulinbar
