### ISSUE TITLE
There is no Power BI Premium Whitepaper (2019) here

### ISSUE THREAD

**Issue by narismadz** [MicrosoftDocs/powerbi-docs#2095]
Based on this link https://powerbi.microsoft.com/en-us/blog/power-bi-premium-deployment-and-management-whitepaper-added/ there's some mentioned that Peter Myer's whitepaper (2019) is available for download but there's no downloadble content here and also in Whitepaper page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c913b90d-071a-7be0-6652-4b1b024e7f45
* Version Independent ID: bc99d496-cf13-552b-b6df-55229ad9ff1d
* Content: [Deploying and Managing Power BI Premium Capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-powerbi-premium-deployment?branch=pr-en-us-1636)
* Content Source: [powerbi-docs/whitepaper-powerbi-premium-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-powerbi-premium-deployment.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @narismadz -- thanks for your question. Referring to the author to check into it.

**Comment by davidiseminger** [comment]
I've updated the reference to clarify (as it states on the top of this page, but is easy to miss) that this content has been incorporated into our general guidance. Sorry for the confusion.
