### ISSUE TITLE
Doubt with discretization of dates.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2096]
The comments below were machine-translated

@Shibz17 commented on [Thu Apr 23 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/28)

I have a calendar table that starts on January 02, 2017 and ends on January 03, 2021. When I group by 7 days, to achieve grouping by weeks (from Monday to Sunday), it mistakenly returns the beginning of the week.

For example:
Discretization type: "Discretization size" = 7 days.
Discretion for 7 days, should be from January 02, 2017 to January 08, 2017
but it returns: January 01, 2017 to January 07, 2017.

Another example:
Discretization type: "Number of discretizations" = 209. (the number of weeks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 7502a07a-7f30-882d-7542-2a194651c421
* Version Independent ID: e3c6e2fd-b672-6858-864c-69026d36c0ae
* Content: [Usar la agrupación y la discretización en Power BI Desktop - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-grouping-and-binning#feedback)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@Shibz17 commented on [Thu Apr 23 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/28#issuecomment-618631183)

Another example:
Discretization type: "Number of discretizations" = 209. (the number of weeks the table has)

Week 1: January 02, 2017 to January 08, 2017. Correct for the moment, because the day gradually begins to run, and I changed the date format to include the hours and I realized that it does the following.
Week 1: January 02, 2017 0:00:00 to January 08, 2017 23:53:06.
Therefore, in 2020 the weeks are run.

Another example:
Discretization type: "Discretization size" = 604800 seconds.
Week 1: December 31, 2016 to January 6, 2017.

So how can I get it to group correctly for 7 days?

---

@Shibz17 commented on [Thu Apr 23 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/28#issuecomment-618631551)

* Not manual, since they will understand that due to the size of the file it would be extremely tedious.

---

@srvbpigh commented on [Thu Apr 23 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/28#issuecomment-618643116)

Hello, @Shibz17
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc and @shibz17 -- thanks for your question! Referring to the author to investigate.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
