### ISSUE TITLE
How to create an aggregate table

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2098]
Hi team, I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/59

The comments below were machine-translated
@hlhxwithmj commented on [Fri Apr 24 2020](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/59)

Ask how to create an aggregate table? Through "New Table" in the "Modeling" module?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [在 Power BI Desktop 中使用和管理聚合 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/desktop-aggregations#feedback)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Fri Apr 24 2020](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/59#issuecomment-618905699)

Hello, @hlhxwithmj
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by paulinbar** [comment]
Hi, @hlhxwithmj, thanks for reaching out to us. I have forwarded your question on to the doc author for consideration. I believe your question related to this page: 
https://docs.microsoft.com/en-us/power-bi/desktop-aggregations

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
