### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerbi-docs#2099]
Could you please describe how this works, or maybe publish a video how to set this up? Even the screenshots on this manual page show that it does not work. they show black tiles instead of the visual, and that's what I experience as well. And please mention all relevant preconditions and limitations, like I need a specific license, I need a specific .net version installed etc. etc. since this obviously does not work straight forward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e0dcdb-8538-0912-4198-9262ce1b3e62
* Version Independent ID: 8ca5416b-0427-f632-4c7c-a948a793a556
* Content: [Pin dashboard to Windows 10 Start screen - Power BI mobile app - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-pin-dashboard-start-screen-windows-10-phone-app)
* Content Source: [powerbi-docs/consumer/mobile/mobile-pin-dashboard-start-screen-windows-10-phone-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-pin-dashboard-start-screen-windows-10-phone-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @MartinBubenheimer , just read your comment. Let me look into this. May not manage to get back to you today, but will try by tomorrow. And I'll update the doc according to what I find out. Thanks for calling this out!

**Comment by paulinbar** [comment]
Hi @MartinBubenheimer . Ok, I heard back. Apparently the "live" feature was deprecated by Windows, and the doc was updated with a non-live picture (hence the non-live image that you saw in the doc), but for some reason it was still called live. I will update the doc so as to remove that confusion. Thanks for contacting us about this, and sorry for the inconvenience...
