### ISSUE TITLE
Page/Report filters

### ISSUE THREAD

**Issue by o-o00o-o** [MicrosoftDocs/powerbi-docs#210]
how do we control which filter is set? Is it always a report filter applied or page filter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
@o-o00o-o ,
The filters you apply in a URL are considered report filters.  That's how they are saved in the report.  You can try it out with a report.  Create the URL parameter in the URL and hit ENTER.  When the report reloads, the URL parameter show up in the Report filters field.  I'll update the article to say this.  
Thanks!
Michele
