### ISSUE TITLE
Cannot generate embed token for paginated report

### ISSUE THREAD

**Issue by iranimohamad** [MicrosoftDocs/powerbi-docs#2100]
I getting a bad request error when trying to embed the paginated reports.

InvalidRequest-Creating embed token for paginated report is only supported with workspaces v2

can someone help with this error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5c029a-8d59-20e1-ca77-ffdf36dab6b9
* Version Independent ID: ced00854-5af3-53f6-700e-236f22061b85
* Content: [Embed paginated reports in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports-customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-paginated-reports-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @iranimohamad . Thanks for reaching out to us. You have reached the documentation team. Before I forward your question on, do you know whether you are working with workspaces v2? Check out this blog post that briefly describes the new workspaces (i.e. v2). It also has links to some docs that have more detail about workspaces. The pre-v2 workspaces are now called "classic" workspaces. Anyway, here's the link to the blog: https://powerbi.microsoft.com/en-us/blog/announcing-upgrade-your-classic-workspaces-to-the-new-workspace-experience-public-preview-is-rolling-out/ . If this is not the issue, then I suggest trying either the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com).

**Comment by paulinbar** [comment]
Hi @iranimohamad. I haven't heard back from you regarding whether the new workspaces V2 was the problem. I am closing this issue now, but please reach out again if you are still having problems. Thanks.
