### ISSUE TITLE
Feature has been renamed to "Show as a table" - content is out-of-date.

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2101]
The page title, url and content are all out-of-date. I dont know when this feature was renamed, maybe 3-4 months ago? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b060f1a-22fd-1b17-6c0a-bc363a2510cd
* Version Independent ID: e4310a93-83c5-1df3-c82a-fe5589fb8b04
* Content: [Show the data that was used to create the visual - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-show-data)
* Content Source: [powerbi-docs/consumer/end-user-show-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-show-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @Mike-Honey , thanks for your comment. I have forwarded it along to the doc author for consideration.

**Comment by mihart** [comment]
Hi @Mike-Honey ,
I've made the updates and they should go live tomorrow.  Thanks for the reminder!
Michele
