### ISSUE TITLE
Is the export-to API relevant for embedded report?

### ISSUE THREAD

**Issue by yaelkfir** [MicrosoftDocs/powerbi-docs#2103]
embeddedReport: Embed; 
is embeddedReport.exportToFile({ format:'PDF '}) a thing?

I in the d.ts file of powerbi-client(latest) it doesn't exists  but the documentation is a bit confusing... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#feedback)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @yaelkfir . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by liavZayde** [comment]
Hi @yaelkfir, the exportTo API is a Rest API and is available through the .NET SDK and not the JS SDK (aka powerbi-client).
For more info about the .NET SDK please check out [this link](https://github.com/microsoft/PowerBI-CSharp).
