### ISSUE TITLE
Easy to follow article.

### ISSUE THREAD

**Issue by cal172** [MicrosoftDocs/powerbi-docs#2104]
Exactly what I was looking for.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips#feedback)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@cal172  - thank you! It's great to hear it's what you were looking for, and thanks for taking the time to share that you liked it. Much appreciated!
