### ISSUE TITLE
Available clouds

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#2105]
Please identify which clouds in which this is available. I just told a client that they could use this only to find out that it is not yet in the Gov clouds. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 085fcf12-3551-ccc4-d2ac-9b660c0dab54
* Version Independent ID: eee33150-c98d-029c-8c35-39cb702cc577
* Content: [Apply sensitivity labels in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/designer/service-security-apply-data-sensitivity-labels)
* Content Source: [powerbi-docs/designer/service-security-apply-data-sensitivity-labels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/designer/service-security-apply-data-sensitivity-labels.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by davidiseminger** [comment]
Thanks for your comment, @DeanGross. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by paulinbar** [comment]
Hi @DeanGross . Thanks for your feedback. There is a mention in the [Considerations and Limitations -10th bullet...](https://docs.microsoft.com/power-bi/designer/service-security-apply-data-sensitivity-labels#considerations-and-limitations) that sensitivity labels are only supported in the global (public) clouds, but government clouds are not specifically mentioned - they just fall under the "other" clouds, which are not supported. Your experience clearly demonstrates that this is not at all a suitable mention - it's so buried and obliquely mentioned that it's invisible for all intents and purposes. I am currently rewriting the docs, and part of the effort is lifting some very important issues out of the considerations and limitations and trying to give them the visibility their importance deserves. Your feedback is very helpful and timely.

**Comment by DeanGross** [comment]
@paulinbar thanks for the quick response, some of the docs pages have an "applicable version" at the top to show what it applies to, i.e.,  SharePoint 2010, 2013, 2016, and/or 2019. Doing something similar for the various clouds and possibly licensing packages would be super helpful.

**Comment by mrpullen** [comment]
Is there any change of having the connector that enables this to be made open source - it seems like a very quick fix to make this available on a government cloud if I can modify the endpoints..
