### ISSUE TITLE
Unable to update storage location of a workspace created before BYO Data Lake capability configured on the tenant

### ISSUE THREAD

**Issue by edfreeman** [MicrosoftDocs/powerbi-docs#2107]
I've tested this in a number of tenants, now. You can't update the Dataflow storage location on workspaces that were created before the bring-your-own Data Lake integration was configured on the tenant, even after you've deleted all the Dataflows from that workspace. 

Not sure whether this is a bug or by design - either way, I think it's worth mentioning in these docs.

Ed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure workspace dataflow settings - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-configure-workspace-storage-settings)
* Content Source: [powerbi-docs/service-dataflows-configure-workspace-storage-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-configure-workspace-storage-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @edfreeman . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @edfreeman ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
