### ISSUE TITLE
Snowflake connection string doesn't have option to specify additional parameters.

### ISSUE THREAD

**Issue by jjjain** [MicrosoftDocs/powerbi-docs#2109]
Snowflake connection string doesn't have option to specify additional parameters. Since all our traffic outside is encrypted, we need to specify a CABundleFile in connection string. There is no way to specify this in Snowflake connector in Power BI.

Also, need a way to specify an authenticator to use (e.g. okta site)

This is similar to a need to specify a role (like how you allow a warehouse to be selected)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-snowflake#feedback)
* Content Source: [powerbi-docs/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jjjain . This issue has been assigned to the doc author for review.

**Comment by jjjain** [comment]
thanks, I have opened a ticket with Snowflake as well. But this needs to be
looked at by Microsoft as well as Snowflake

**Comment by davidiseminger** [comment]
Thanks for your comment, @jjjain . Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
