### ISSUE TITLE
How do you connect this app if you use federated single sign on?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#211]
The instructions only list connecting with basic authentication.  How do you connect if your org uses ADFS to connect to planview?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 150dab75-72d8-5401-d7cb-7d689ed8f418
* Version Independent ID: daa4df06-ea9b-fdd0-6d93-ff9fef21731c
* Content: [Connect to Planview Enterprise with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-planview)
* Content Source: [powerbi-docs/service-connect-to-planview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-planview.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mschmidt0208** [comment]
Hello,
Here's what the connection instructions Planview sent us says:

To use your Planview Enterprise data with Microsoft Power BI, you need to authenticate your access when signing in. However, if your environment uses Single Sign-On (SSO), you may not know your Planview Enterprise user name and password. To use SSO with Power BI, you must create and use an authentication token, which acts as your user name and password and authenticates your access. 
https://success.planview.com/Planview_Enterprise/Analytics_and_Reporting/Power_BI/Using_Power_BI/Using_Power_BI_and_Single_Sign-On_(SSO)  

Hope it helps!

**Comment by jordanmills** [comment]
Chicken and egg.  That page reads "Sign in to access this product help article."  And you can't sign in to there with SSO.

I did find some options in planview for authentication tokens and was able to create one. But the powerBI app for planview only allows basic sign in, not an authentication token.

After more digging around, I was able to uncover an interface in planview to reset a user's password.  It's fairly well hidden, and I don't remember how I got to it.  But it's at https://[orgname].pvcloud.com/planview/login/ResetPasswordRequest.aspx (replace [orgname] with your orgname, and you'll need to know your database, listed under "about" when you're logged in to planview).  That seems to be the only way to activate/link the powerbi app for planview.

**Comment by jrsilva24** [comment]
In order to use the generated token, you must pass in the token in basic auth in the username field and leave the password blank.

**Comment by maggiesMSFT** [comment]
Thanks for replying, @jrsilva24! 
Hi @jordanmills -- @jrsilva24 is from Planview, so what @jrsilva24 says, goes. Thanks for asking!

**Comment by jordanmills** [comment]
I will do that.  Thanks!
