### ISSUE TITLE
Schedule a Data Set refresh using On-Prem Gateway -- mixed Sharepoint Online and on-premise Excel and SQL Server

### ISSUE THREAD

**Issue by mgaynor** [MicrosoftDocs/powerbi-docs#2110]
Is there a way to schedule a Data Set refresh using On-Prem Gateway when the sources are Sharepoint Lists and on-premise SQL Server?

**Comment by mihart** [comment]
Thanks for your comment, @mgaynor . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
