### ISSUE TITLE
Copy Path location image doesn't match current Excel

### ISSUE THREAD

**Issue by hrr** [MicrosoftDocs/powerbi-docs#2112]
Location on documentation:
![image](https://user-images.githubusercontent.com/2828703/80585847-93309580-8a46-11ea-87a9-4176193e7da1.png)

Location now:
![image](https://user-images.githubusercontent.com/2828703/80586039-ea366a80-8a46-11ea-9872-dd159860a9a1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @hrr.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out! I've updated the image.

**Comment by kieranhogg** [comment]
This hasn't made it to the live page yet?
