### ISSUE TITLE
Not able to connect to my dataflow from pbi desktop

### ISSUE THREAD

**Issue by sandeeplodhirajput** [MicrosoftDocs/powerbi-docs#2113]
HI,
I created a dataflow in service and when i try to connect it through desktop i am getting below error.
I am using the same credential which i have used in log into pbi service. please suggest help here. 

This page can’t be displayed

•Make sure the web address https://login.microsoftonline.com is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating and using dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-create-use#feedback)
* Content Source: [powerbi-docs/service-dataflows-create-use.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-create-use.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sandeeplodhirajput.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment, @sandeeplodhirajput. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
