### ISSUE TITLE
Make sure you authorize at the Organizational level

### ISSUE THREAD

**Issue by psiservices-rfeiock** [MicrosoftDocs/powerbi-docs#2116]
When setting up the GitHub authentication for the first time, you are presented with 2 options for authorization, at the user level or the organization level.  I originally authorized at the user level, and then encountered 404 errors when trying to pull from my GitHub repository.  After a bit of troubleshooting, I assumed the issues was with the authorization, but there is no way to go back and change it.  I eventually figured out a workaround where I could completely remove the GitHub app/workspace, and have a coworker add it fresh, and then that coworker authorized at the Org level, which we then accepted on the GitHub side.  Once that was complete, then I was able to connect to the repositories with no problem.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github#feedback)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @psiservices-rfeiock.

I've assigned this issue to the doc author for review.

**Comment by paulinbar** [comment]
Hi @psiservices-rfeiock - when you say Github authentication - do you refer to the dialogs of the template app, or does it take you to github to sign in? If you are already logged into github in your browser, I don't think you'll get the Github sign in screens - you'll just have the two from the template app - the first, where you specify the repo owner and the repo, and the next, the authentication dialog - there you make sure that oAuth2 is selected. You should leave the privacy level at None. Just sign in.
I am a bit curious about the going back part. If you delete the app, and the app workspace, you should be able to just reinstall the template app, going through the whole setup again. This didn't work for you?

**Comment by psiservices-rfeiock** [comment]
It is a GitHub screen, and below is an example.  It is not the GitHub login screen, rather it is the authorization screen that allows Power BI access to the user's GitHub data.  The two dialogs you mentioned above are not a problem because as you said, if a user deletes the workspace and re-adds, then the user is prompted for them again.  This GitHub authorization screen however, there is no simple way to get prompted for it again after making an initial selection.  

![github_authorize](https://user-images.githubusercontent.com/43249710/81184524-7c2a0000-8f7e-11ea-9b16-e288a0ecc51d.png)

**Comment by paulinbar** [comment]
Hi @psiservices-rfeiock , ok.. thanks for clarifying. I will look into this further in order to understand how best to fix the doc so that people don't run into the same problem you did. Will keep you posted.

**Comment by paulinbar** [comment]
Hi @psiservices-rfeiock. I realize it's been a LONG time..  but the template apps have undergone lots of changes, and it is now much easier to remove the whole template app, workspace and all, once it's been installed. I suggest trying the whole thing again and see if you run into the same issues. If you have an opportunity to do this, but still run into problems. please reopen this issue. Thanks!
