### ISSUE TITLE
Missing Release Notes for latest version? 

### ISSUE THREAD

**Issue by CitDev82** [MicrosoftDocs/powerbi-docs#2117]
According to this website the latest version of Power BI Desktop is 2.79.5768.1082, published on 04/01/2020:
https://www.microsoft.com/en-us/download/details.aspx?id=58494
But I can't find the release notes anywhere. This article covers only version 2.79.5768.562...

Many thanks in advance!
Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#feedback)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @CitDev82 -- coming soon!
