### ISSUE TITLE
I get nothing but a blank page

### ISSUE THREAD

**Issue by russellclaude** [MicrosoftDocs/powerbi-docs#2118]
I have tried on IE/Edge/Firefox, and I have tried with simple table/field names, and I get nothing but a redirected URL and a blank page:

view-source:https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-982a-7cb446e25bc6?filter=ReportingCalendar/period%20eq%20%27Latest%2052%27/oauth2/authorize&client_id=871c010f-5e61-4fb1-83ac-98610a7e9110&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DGtGOEE4kEL5mx8tHwKGJQT8BGrFOGdYLtcAIe-iNA5D98uGQO5bM2CtTA0eves86_juEHH4RSrWI8eRYbiZVO-xMJgfSQPy1swZbF4qu99Q683yFcrx7c-8mvNVUCMpCNSJ9rNU3JQxJDwlOPYQgPJfoP9LDaMSopsGzXm6C8xK1l2ImYktRk0Dymkenty1B4hPpiibWUaWmRBu02FptSPBEdbQ3_yn3KZJR7UtUSreDfBKCFvmNlJJRANlrDj5n-hhKYYHnc5MKgb9ecYOvuHCcKLtKn9xEn3G-nCz7p4XfeDnJm0uI48gRzd01fORsV_vOPFsovkcLnwf26FYw8Js501Mu2YVM3KSDt6l47KGjG42cyorTk6iM3uvqelYdRhpcdO8qCp7zJonHnroqV6hBnQcTl6balFTPk_nRdHZ-AvKELkWZZpmv3-JMzt7fwpNzKA-iHFvNb4TtnJBM8VA4k7LS7SwjxFPLY8L-8orxa_W1VZnSjF8qsBw08k26qwJMqpUpfoOeg9hJxxJ3t_a4YISXHhga0z8QDuNY-UPPsFA9c67A75Ec6K0YImxu&response_mode=form_post&nonce=637237895676791988.YTlkNDQ3MTUtYzQzMC00OWYyLWJlNjctY2VhNTRmZjk0OWNkYzc5YmFlMjUtODJhMC00ODM0LTljMmMtNDQ1ZjBmNDAzMGVm&site_id=500453&redirect_uri=https%3A%2F%2Fapp.powerbi.com%2Fgroups%2Fe65cdc98-1166-402c-a9d8-2b0489fb5d91%2Freports%2F0eb2b36a-2803-4fa8-8b47-a8f1c9e7d819%2FReportSection%3Fctid%3D2fc13e34-f03f-498b-982a-7cb446e25bc6%3Ffilter%3DReportingCalendar%2Fperiod%2520eq%2520%2527Latest%252052%2527&post_logout_redirect_uri=https%3A%2F%2Fapp.powerbi.com%2Fgroups%2Fe65cdc98-1166-402c-a9d8-2b0489fb5d91%2Freports%2F0eb2b36a-2803-4fa8-8b47-a8f1c9e7d819%2FReportSection%3Fctid%3D2fc13e34-f03f-498b-982a-7cb446e25bc6%3Ffilter%3DReportingCalendar%2Fperiod%2520eq%2520%2527Latest%252052%2527&resource=https%3A%2F%2Fanalysis.windows.net%2Fpowerbi%2Fapi&nux=1&x-client-SKU=ID_NET45&x-client-ver=5.3.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @russellclaude -- it's not possible to view your report. This doesn't sound like a documentation issue. You need to contact the support folks, https://powerbi.microsoft.com/en-us/support/.
