### ISSUE TITLE
Great information

### ISSUE THREAD

**Issue by tireraid** [MicrosoftDocs/powerbi-docs#2120]
This page cleared up a lot of confusion for me, thank you. I was linked here from the following page, which has also been very helpful: https://docs.microsoft.com/en-us/learn/modules/model-data-power-bi/2-how-to-manage-data-relationships

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-create-and-manage-relationships#feedback)
* Content Source: [powerbi-docs/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @tireraid ! The author will be happy to hear it.

**Comment by davidiseminger** [comment]
Thank you!
