### ISSUE TITLE
Test Subscription (ID=100) Access

### ISSUE THREAD

**Issue by ryanferguson** [MicrosoftDocs/powerbi-docs#2121]
Is there any data that Microsoft allows access to for the generation of templated reporting?  In the beta connector before, you could get the API key for Enrollemtn 100 and pull data that way.  Is there any similar option with this method?

**Comment by maggiesMSFT** [comment]
Hi, @ryanferguson -- are you referring to a specific article? I'm unsure to whom to direct your question. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ryanferguson -- hearing no reply, I'm closing this issue. Thanks.
