### ISSUE TITLE
Decomposition Tree bar scaling

### ISSUE THREAD

**Issue by CeesvEgmond** [MicrosoftDocs/powerbi-docs#2122]
Currently, I'm trying to use Decomposition Trees to preform progress root-cause analysis.
The progress is measured on a scale of 0-100% for each object.
Values are correctly shown in the visual, I'm only not able to get the Data Bar scaled correctly.
Current options are: scaled to -
- Top node
- Paren node
- Level Maximum

I would like to use 0-100% as scale for my bar.

refer to below:
![2020-05-01 12_17_40-temp - Power BI Desktop](https://user-images.githubusercontent.com/58607351/80799026-0b619d00-8ba6-11ea-8f7d-da3a760f43d7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree#known-limitations)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @CeesvEgmond -- thanks for your question! Checking to find the best person to assign it to.

**Comment by juluczni** [comment]
Thanks for the feedback! This isn't currently supported but we have added it to our backlog of potential things to add.
