### ISSUE TITLE
Add mention of dynamic binding

### ISSUE THREAD

**Issue by iMicknl** [MicrosoftDocs/powerbi-docs#2123]
Would it be an idea to add a mention of [dynamic binding](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-dynamic-binding) to this page? This could be really useful for multi-tenancy solutions where different datasets are used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 671c4fcd-ba24-fec3-fccc-d06004b46eb0
* Version Independent ID: 507e43c5-d2e2-7f3a-5441-a8641e1a25df
* Content: [Manage multi-tenancy with Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-multi-tenancy)
* Content Source: [powerbi-docs/developer/embedded/embed-multi-tenancy.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-multi-tenancy.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @iMicknl -- thanks for your suggestion! Passing it on to the author.

**Comment by KesemSharabi** [comment]
Hi @iMicknl,

Thank you for your suggestion, I'll look into it when I next refresh the [multi-tenancy article](https://docs.microsoft.com/power-bi/developer/embedded/embed-multi-tenancy).

Kesem
