### ISSUE TITLE
Power BI Premium Capacity App role requirements

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2124]
This is regarding https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity

Not all users can install or access the app. Please mention the role requirement in the documentation for this after confirming from the Product Group. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @haider392 -- thanks for your question! Referring to the author to investigate.

**Comment by mihart** [comment]
More than 1 year old git issue from internal. Closing.
