### ISSUE TITLE
Referenced page does not show DAX table functions

### ISSUE THREAD

**Issue by sartoris** [MicrosoftDocs/powerbi-docs#2125]
Clicking the 'DAX Function Reference' link send you to the DAX functin reference page, but I don't see any mention of the ...JOIN functions or UNION or INTERSECT functions there

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23f1335-bb33-544a-67da-006015cfc92f
* Version Independent ID: 3e1dc63e-f0ac-5201-c0a5-bc7e4ee30944
* Content: [Using calculated tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-calculated-tables#feedback)
* Content Source: [powerbi-docs/desktop-calculated-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-calculated-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @sartoris -- thanks for your question! Referring it to the author for further investigation.

**Comment by davidiseminger** [comment]
Hi @sartoris  - take a look in the "Other functions" section as well. You'll see UNION, INTERSECT, and other there. You can always search that page, in the top-left box, for others.
