### ISSUE TITLE
References for statsitical algorithms?

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2127]
the document says - "Power BI uses statistical algorithms to uncover Insights." can you please provide some references to what algorithms, methods are being used? Knowing this will help us understand the strengths and limitations of these method and optimize/shape the data to make the most of it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2368b421-38bc-b939-af6e-2cd36e3e752d
* Version Independent ID: 4c44f153-86e5-1f2b-5d04-705676475f96
* Content: [Types of Insights supported by Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insight-types)
* Content Source: [powerbi-docs/consumer/end-user-insight-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-insight-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @pawarbi -- thanks for your question! Later in the article, it spells out the different algorithms: https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insight-types#what-types-of-insights-can-you-find. 
Referring to the author in case they can provide more, but the article itself is quite specific.

**Comment by pawarbi** [comment]
Thanks @maggiesMSFT for your reply.. documentation mentions what the algorithm does in general terms but does not spell out how it's done. for example. 

Category outliers (top/bottom) :Highlights cases where one or two categories have much larger values than other categories.

But does not specify the statistical test performed, or how its done. is it by count, mean, standard deviation, any other statistical parameter etc. Users don't need to know the exact details but some technical details would help us understand what exactly being done so analysts can prep the data accordingly. If MS has any published documentation/research paper on this, it would be good to have reference/citation here. Thanks.

**Comment by juluczni** [comment]
Hi Pawar- you can take a look at which specific algorithms are used here: https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/customers/power-bi
