### ISSUE TITLE
Still not able to install Access database redistributable

### ISSUE THREAD

**Issue by ajityadav83** [MicrosoftDocs/powerbi-docs#2128]
I have 32 bit office on my machine, I have installed x86 POwer BI. I am tring to install 32 bit Access exe but getting an error " you have 64 bit office products on your machine".

Tried with 64bit Access bit exe , gave me an error " you have 32 bit office products on your machine".

tried passive way as well, even that didn't work out.

Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680485c7-5823-2c7f-df5d-b8c8a8205759
* Version Independent ID: 5a217642-7723-6980-28ae-e26559c24201
* Content: [Resolve Access and .XLS import issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-access-database-errors#feedback)
* Content Source: [powerbi-docs/desktop-access-database-errors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-access-database-errors.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ajityadav83 -- this sounds like a support issue. You can try the community to see if they have any suggestions: https://community.powerbi.com/.
If not, please contact https://powerbi.microsoft.com/en-us/support/
Hope that helps!
