### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/powerbi-docs#2129]
I found this beginners course very helpful. What would be even better would be being able to download the PIBX so we can play along.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7#feedback)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @makdaddy8888 , thanks for your feedback - a great suggestion! I am forwarding it along to the doc author - he'll know better than I whether that's a possibility. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment. We will look into posting that file for download, so users can experiment on their own.
