### ISSUE TITLE
Permissions required to change workspace photo

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#213]
Please provide detailed information about the set of permissions on O365 side to be able to change the picture on the workspace group.
There are a lot of users complaining about not seeing the option or even having errors for not having a exchange online license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54452a1b-613f-5718-a6bd-16429fdfc678
* Version Independent ID: 3352343d-b326-4f63-5c37-51403d8f6358
* Content: [Create workspaces with your colleagues in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-workspaces#add-an-image-to-your-office-365-app-workspace-optional)
* Content Source: [powerbi-docs/service-create-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by GKNetaphor** [comment]
same problem - I only see Edit Workspace and Leave Workspace options.  I do not see members, etc.

**Comment by maggiesMSFT** [comment]
Hi @djpirra and @GKNetaphor -- Thanks for asking! Yes, you need to be an owner of an app workspace in Power BI to edit the picture of the workspace group in Office 365. Likewise, you only see Edit Workspace and Leave Workspace if you're not an owner. 
Hope that helps!
