### ISSUE TITLE
The module of power BI was great , the explanation for every module was explained in well manner 

### ISSUE THREAD

**Issue by Ganesh0799** [MicrosoftDocs/powerbi-docs#2130]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7#feedback)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @Ganesh0799 , I'm glad you found the module useful, and appreciate your taking the time to give your feedback. I am passing your comment on to the doc author, who I am sure will be pleased to hear that his work was of benefit to you. Thanks! 
@davidiseminger
