### ISSUE TITLE
invoke custom function

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#2131]
In the Add Column tab, I want to learn about the button to "invoke custom function".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8e549-7fba-9ece-3e32-73a0cc3c6046
* Version Independent ID: a9b39810-c302-c153-3123-ddb8f459e9f4
* Content: [Add a custom column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-add-custom-column#feedback)
* Content Source: [powerbi-docs/desktop-add-custom-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-add-custom-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @rootsmusic , thanks for reaching out to us with your comment. I am forwarding it along to the doc author for consideration. In the meantime, I suggest you also check out the the [Power BI Community]( https://community.powerbi.com) - sometimes you can find answers there, or if you write a question, often people respond who are able to provide useful information.

**Comment by davidiseminger** [comment]
Thanks for your interest. Here's a good link from a well-known Power BI expert:
https://blog.crossjoin.co.uk/2016/10/01/using-the-invoke-custom-function-button-in-power-bi/
