### ISSUE TITLE
Full support of Firefox for macOS

### ISSUE THREAD

**Issue by glasody** [MicrosoftDocs/powerbi-docs#2132]
Hi,
it still seems to not support proper scrolling actions in the latest firefox on macOS for dropdown slicers.
Could you please update the docs to make sure that this is clear?
It says that firefox on desktop is supported when that is not the case on what we have tested.

macOS 10.14.6
Firefox for Mac 75.0

Just a reference from a representative ages ago referencing this page.
https://community.powerbi.com/t5/Issues/PBI-Slicer-Functionality-Firefox-54-0-Mac/idc-p/200166/highlight/true#M9644

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-browsers#feedback)
* Content Source: [powerbi-docs/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @glasody , thanks for your comment. I am forwarding it on to the doc author for consideration. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @glasody -- I'm checking and I'll get back to you. Thanks!

**Comment by mihart** [comment]
Hi @glasody ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
