### ISSUE TITLE
Bug with mulitple gateways

### ISSUE THREAD

**Issue by jeppesal** [MicrosoftDocs/powerbi-docs#2133]
It is not possible to select a gateway with only the on-prem connection mapped (Invalid configured gateway) if you have multiple gatewayes. The UI will select a working gateway.
I had to remove the other gatewayes to make this guide work and to be allowed to select a partially configured gateway for only on-prem sources.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jeppesal. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Older than 1 year. Article updated. PM never responded. Closing.
