### ISSUE TITLE
Pause and start Power BI Embedded programmatically

### ISSUE THREAD

**Issue by itm-platform** [MicrosoftDocs/powerbi-docs#2135]
This page explains how to pause and start the service manually. Can this be done programmatically?
Use case: Power BI is embedded in a page of an application that has a rather low usage. 
Objective: pay per use of Power BI Embedded, not just its availability
Question: Can the PBI Embedded service be activated when that page is accessed and paused when left?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842bcbb2-ce2c-3729-f876-5d306595b33c
* Version Independent ID: 1a915436-b70f-a6e9-a3c1-f7fc8db4cdb2
* Content: [Pause and start your Power BI Embedded capacity in the Azure portal - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-pause-start)
* Content Source: [powerbi-docs/developer/embedded/azure-pbie-pause-start.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/azure-pbie-pause-start.md)
* Service: **power-bi-embedded**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.

I've also forwarded your feedback to the writer, who may have insight on your question as well.

**Comment by KesemSharabi** [comment]
Hi @itm-platform,

Yes, you can use the Azure ARM APIs [suspend](https://docs.microsoft.com/rest/api/power-bi-embedded/capacities/suspend) and [resume](https://docs.microsoft.com/rest/api/power-bi-embedded/capacities/resume).

Or, you can use a Power BI Embedded PowerShell script; [Suspend-AzPowerBIEmbeddedCapacity](https://docs.microsoft.com/powershell/module/az.powerbiembedded/Suspend-AzPowerBIEmbeddedCapacity?view=azps-4.1.0) and [Resume-AzPowerBIEmbeddedCapacity](https://docs.microsoft.com/powershell/module/az.powerbiembedded/Resume-AzPowerBIEmbeddedCapacity?view=azps-4.1.0).

Hope this helps,

Kesem
