### ISSUE TITLE
Power BI Dataset option does not appear

### ISSUE THREAD

**Issue by romerohe** [MicrosoftDocs/powerbi-docs#2136]
Hi, I'm trying to follow the document steps to connect from Power BI desktop to an Power BI dataset which is on my Working Area in the Power BI service, but the "Power BI Dataset" option is not available under the "Power Platform" tab.

I just have the other 3 options (Power BI dataflow, Common data service, Power platform dataflow).

Do you know what is going wrong?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets#feedback)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi there @romahamu - do you have the latest version of Power BI Desktop? In Power BI Desktop, go to File > About and see which version (and in parenthesis, the month) of the release you're using. If it's not up to date, that may - and likely is - the reason.

**Comment by davidiseminger** [comment]
Assigning author.

**Comment by romerohe** [comment]
Hi David, thank you for your reply.

I think my Power BI desktop is updated. This is my version information:
"Versión: 2.79.5768.1082 64-bit (marzo de 2020)"

**Comment by romerohe** [comment]
Hi David, do you have any news about this issue? I attach an image of my screen (it's in Spanish)

![image](https://user-images.githubusercontent.com/49759275/81703239-aed26d80-9442-11ea-961f-36315191d741.png)

**Comment by davidiseminger** [comment]
Hi @romerohe - I'm sorry, but I can't reproduce your issue on my side; I see the "Power BI datasets" in the Power Platform section of Get Data. As such, I think your best bet is to ask the community, or contact support. If you find that it's an issue we can address in the docs, please let me know. 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
