### ISSUE TITLE
Sample PBIX files don't have transformable data

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/powerbi-docs#2137]
If you try and go to the transform data view and edit any of the backing data for the local PBIX file downloads, you get an error about not having permissions for a native query. It'd be great if these local reports just had raw data tables or connected to a sample backend somewhere. Then you could explore modifying these report samples across all aspects of what Power BI does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-datasets#install-built-in-content-packs)
* Content Source: [powerbi-docs/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @michael-hawker . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @michael-hawker -- you're right. Here are a couple of other articles that link to flat Excel files.
https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report
Hope that helps!
