### ISSUE TITLE
Contact in apps are not show, but shows Data set Owners.

### ISSUE THREAD

**Issue by luaguila** [MicrosoftDocs/powerbi-docs#2138]
Right now we are also put the Data set Owner this is causing, that some users get confused, It will be good to put a note about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f59ea7e-d3e7-3986-34f8-b1211bb3fc66
* Version Independent ID: 44c49bf9-9898-eeed-01c0-18cb267f5ea8
* Content: [Set contact information for reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/service-item-contact#feedback)
* Content Source: [powerbi-docs/service-item-contact.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-item-contact.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @LukaszPawlowski-MS
* Microsoft Alias: **lukaszp**

**Comment by mihart** [comment]
Thanks for your comment, @luaguila . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @luaguila -- could you elaborate? I'm not sure what you're seeing. Or is it resolved now? Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @luaguila -- not hearing back from you, I'm closing this issue.
