### ISSUE TITLE
Map chart in Greek

### ISSUE THREAD

**Issue by ath-violettak** [MicrosoftDocs/powerbi-docs#2141]
I would like to know how I can have my map in English as although I have tried changing all relative setting to English, I still get my map showing the locations in Greek.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ath-violettak.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Thanks for your comment, @ath-violettak. This appears to be an old Git Issue and I hope that you were able to solve your problem.  If not, please post your question in the community forum, at https://community.powerbi.com.
