### ISSUE TITLE
Is it working for on-premise (Report Server) PowerBI desktop or not?

### ISSUE THREAD

**Issue by sloggiz** [MicrosoftDocs/powerbi-docs#2142]
I can't find any information about supported versions of PowerBI Desktop application. I'm currently running PowerBI Desktop RS Jan 2020 and I can't find composite mode anywhere. 
If it's not supported, please explicitly write this in the article. And in general I noticed that this kind of information is never present in official PowerBI documentaion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sloggiz.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @sloggiz ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
