### ISSUE TITLE
Persistent local cache in Power Query and Power BI Desktop

### ISSUE THREAD

**Issue by GeneCCC947** [MicrosoftDocs/powerbi-docs#2145]
Very informative post and answers many questions regarding buffering and referencing.  For those of us who don't have Power BI access, It would be very helpful to be able to designate a local cache to a workbook or Power BI Desktop instantiation for given connections to servers. During development, many accesses to a sources can be painful.  Similarly, being able to create a Dataflow design that would allow "buffering" between queries would improve performance.  This suggestion is with respect to "Small" Data.  My application data is updated on an intermittent schedule over a period of 5-6 months, with the frequency increasing toward the end of the period.  Data file size begins with a few KB and increases to more than 5 MB toward the end of the period.  New files are created on an annual, basis.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb0fcf5f-584d-9825-7f9e-20b4cf290f73
* Version Independent ID: f010d1f9-3f7d-c7ef-68ba-4cd133e4c7fb
* Content: [Referencing Power Query queries - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/power-query-referenced-queries)
* Content Source: [powerbi-docs/guidance/power-query-referenced-queries.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/power-query-referenced-queries.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by maggiesMSFT** [comment]
Hi, @GeneCCC947 -- is this a documentation question, or a product suggestion? If the latter, you can provide it at https://ideas.powerbi.com/forums/265200-power-bi.
Thanks!
