### ISSUE TITLE
Oracle ODAC 18 is supported with additional steps 

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#2147]
Unlike ODAC 12.2 installer, ODAC 18.x/19.x does not have an option to install the ODAC components to GAC and register them in machine config. These steps have to be run manually for ODAC 18.x and above for them to be usable in Power BI desktop or power bi service through gateway.

Once Oracle 18.x/19.x is installed go to the install directory and navigate to 
1.	odp.net\bin\2.x for .net 2.0
2.	odp.net\bin\4 for .net 4
From this folder using administrator command window they need to run 
1.	OraProvCfg.exe /action:gac /providerpath:"Oracle.DataAccess.dll"
2.	OraProvCfg /action:config /force /product:odp /component:dbproviderfactory /frameworkversion: v4.0.30319 /providerpath: Oracle.DataAccess.dll
a.	Look in c:\windows\microsoft.net\framework64 to see the correct versions for .net there should be a v2.0.xxxx folder and v4.0.xxxx folder use these strings as frameworkversion in above

This will register the oracle ado.net provider in machine configuration and allows power bi to use it. To see if the registration and configuration is done correctly the customer can open a powershell window and run this command
•	[System.Data.Common.DbProviderFactories]::GetFactoryClasses(),  they should see a few entries and entry like this below:
ODP.NET, Unmanaged Driver                      Oracle Data Provider for .NET, Unmanaged Driver               Oracle.DataAccess.Client

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by adamwp1993** [comment]
note: once these steps are performed you have to restart Gateway service

**Comment by vumsum** [comment]
Please note this is for ODAC 18.x as well as 19.x ….basically any version after 12.2 needs to have these extra steps done.

**Comment by adamwp1993** [comment]
@davidiseminger  any update on this?

**Comment by OraDotNetDev** [comment]
I don't think Step 4 is required.

The DbProviderFactories entry is added to the Machine Config by the first call to OraProvCfg.exe [step 3.] Tested against ODAC 19.3 xcopy install.

> Unlike ODAC 12.2 installer, ODAC 18.x/19.x does not have an option to install the ODAC components to GAC and register them in machine config. These steps have to be run manually for ODAC 18.x and above for them to be usable in Power BI desktop or power bi service through gateway.
> 
> Once Oracle 18.x/19.x is installed go to the install directory and navigate to
> 
> 1. odp.net\bin\2.x for .net 2.0
> 2. odp.net\bin\4 for .net 4
>    From this folder using administrator command window they need to run
> 3. OraProvCfg.exe /action:gac /providerpath:"Oracle.DataAccess.dll"
> 4. OraProvCfg /action:config /force /product:odp /component:dbproviderfactory /frameworkversion: v4.0.30319 /providerpath: Oracle.DataAccess.dll
>    a.	Look in c:\windows\microsoft.net\framework64 to see the correct versions for .net there should be a v2.0.xxxx folder and v4.0.xxxx folder use these strings as frameworkversion in above
> 
> This will register the oracle ado.net provider in machine configuration and allows power bi to use it. To see if the registration and configuration is done correctly the customer can open a powershell window and run this command
> • [System.Data.Common.DbProviderFactories]::GetFactoryClasses(), they should see a few entries and entry like this below:
> ODP.NET, Unmanaged Driver Oracle Data Provider for .NET, Unmanaged Driver Oracle.DataAccess.Client
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 382f269e-2072-ec03-7c88-335cbd5df919
> * Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
> * Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database)
> * Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
> * Service: **powerbi**
> * Sub-service: **powerbi-desktop**
> * GitHub Login: @davidiseminger
> * Microsoft Alias: **davidi**

**Comment by kumarvinit67** [comment]
Hi Team,
we are facing issue in step 4 and getting below error:
ERROR: Invalid <action> parameter value:

**Comment by kumarvinit67** [comment]
Hi Team,
Request your help on step no 4.

Regards,
vinit

**Comment by rduke-cfpwood** [comment]
> Hi Team,
> Request your help on step no 4.
> 
> Regards,
> vinit

There are a couple of extra spaces in step 4. Below is corrected.

OraProvCfg /action:config /force /product:odp /component:dbproviderfactory /frameworkversion:v4.0.30319 /providerpath:Oracle.DataAccess.dll

**Comment by davidiseminger** [comment]
These updates have been made to the article, and in addition, review of connector documentation is underway to ensure consistency and freshness. Thanks for posting.

**Comment by nitelor** [comment]
Does anyone know where I can find the odac for 18c 64 bit, and also follow these steps?
