### ISSUE TITLE
Connector Limitation - Please contact siqwang for more detail - internal request

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#2149]
Description: Zendesk made an Update on their public API, Before Oct 15, 2019, The Zendesk Support Search API allows for a total of 200,000 results to be received through pagination of large queries. In order to align search usage with its intended scope, Zendesk will be changing the maximum number of results returned. Instead of up to 200,000 results, the Search API will return a maximum of 1,000 total results with a maximum of 100 results per page.  

Referencing: https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits

Impact: This change behavior would cause Power BI Zendesk goes wrong when user tried to request large amount of data because current Power BI Zendesk Connector still creating API call which exceed new limits.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2231f5c7-c73c-0b80-d6b9-5adf207a6b62
* Version Independent ID: 91e7c633-83d4-0714-e92f-e3f169549bd5
* Content: [Connect to Zendesk with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-zendesk#feedback)
* Content Source: [powerbi-docs/service-connect-to-zendesk.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-zendesk.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @KerryWang94 -- Thanks for the information! Assigning to the author to investigate.

**Comment by paulinbar** [comment]
Hi @KerryWang94, thanks for the info. I am checking out the details about where and how to document this limitation. I'll keep you posted.

**Comment by KerryWang94** [comment]
Hi Paul,

Sure thanks, also here is a attachment for the conversation I did with Product Group.

Best Regards,
Kerry

**Comment by paulinbar** [comment]
Hi @KerryWang94 . I added the following warning: Before Oct 15, 2019, the Zendesk Support Search API allowed for a total of 200,000 results to be received through pagination of large queries. To align search usage with its intended scope, Zendesk now limits the maximum number of results returned to 1,000 total results, with a maximum of 100 results per page. However, the current Power BI Zendesk connector can still create API calls that exceed these new limits, resulting in possibly misleading results. Contact me if there's a problem.

**Comment by brettoll** [comment]
Hi - @paulinbar. Would that mean that the connection should be removed as advertised? There isn't really a user case for 1000 total results. A notification repeating back to the users what we raised as an issue doesn't resolve the issue.

Is there any suggested fixes?

**Comment by brettoll** [comment]
https://develop.zendesk.com/hc/en-us/articles/360022563994--BREAKING-New-Search-API-Result-Limits?page=2#comment_360003446454

Zendesk were saying they were reaching out to MS for changing to incremental refresh

**Comment by paulinbar** [comment]
Hi @brettoll, let me make sure I understand you correctly, so I can pass on your message. You're saying basically that a 1000 total limit on results is essentially useless, as is just informing you of the limitation in the documentation, rather than suggesting some way of fixing or overcoming the limitation? In any event, let me check with template app people and hear what they have to say, and I'll get back to you.
Thanks

**Comment by brettoll** [comment]
Hi Paul - that is correct. The users that have had this problem are aware of the 200k to 1000 change.

There is a suggested fix by Julio Garcés Teuber in below thread that people are using which may be useful for the template app.
https://develop.zendesk.com/hc/en-us/articles/360022563994?page=2#comment_360003420813
