### ISSUE TITLE
Where is this 'handy tool'?

### ISSUE THREAD

**Issue by karmamule** [MicrosoftDocs/powerbi-docs#215]
In the section "How can I clear all the values on a push dataset?" a 'handy tool' is mentioned, but there is no link or reference available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @karmamule, and sorry for the delay and confusion. That handy tool is not available, and I've removed reference to it. Sorry for the inconvenience.
