### ISSUE TITLE
Q&A in Streaming Datasets

### ISSUE THREAD

**Issue by tomasbaima** [MicrosoftDocs/powerbi-docs#2151]
Hello, this update does not work on the streaming data set. I don't have the settings icon in the upper right corner. I can create suggestive questions in the power bi service but I cannot teach Q&A.

**Comment by maggiesMSFT** [comment]
Hi, @tomasbaima -- are you referring to a specific article? If so, can you please provide a link? Otherwise, this sounds like it may be a support issue. If so, please submit it at https://powerbi.microsoft.com/en-us/support/
thanks!

**Comment by maggiesMSFT** [comment]
Hi, @tomasbaima -- Having not heard back from you, I'm closing this issue. I hope you were able to resolve the issue!
