### ISSUE TITLE
Problem viewing published report

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/powerbi-docs#2152]
@ProstoJohn commented 5 hours ago — with docs.microsoft.com

After successfully publishing a report and trying to view it using the link that Power BI issued, the following error occurs: "This content is not available. More information about Power BI" (https://snipboard.io/fjmUAI.jpg), click on the link "More information about Power BI "(https://go.microsoft.com/fwlink/?LinkID=722383&clcid=0x409) did not find any useful information.

How can I get out of this situation? Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web#feedback)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @v-radelg -- this sounds like a product support issue. Can you please submit it at https://powerbi.microsoft.com/en-us/support/?
thanks!
