### ISSUE TITLE
rolesIndex missing from the API

### ISSUE THREAD

**Issue by danieleperilli** [MicrosoftDocs/powerbi-docs#2153]
When there are multiple columns/measures mapped to different roles in the Fields panel, we need to understand the position of each one. I just discovered that there is a specific property named **rolesIndex** to do that, which is not exposed in the API. It's safe to use it? Is it going to be included in the API? Thanks.

![image](https://user-images.githubusercontent.com/9072177/81470526-78e77c00-91eb-11ea-9a10-4b265b2d1e70.png)

![image](https://user-images.githubusercontent.com/9072177/81470608-dd0a4000-91eb-11ea-83dc-cfff16916814.png)

**Comment by davidiseminger** [comment]
Thanks for your comment, @danieleperilli. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @danieleperilli,

Can you please let me know which article you're referring to?

Thanks,

Kesem

**Comment by danieleperilli** [comment]
I've just posted this from the official documentation page for the dataview mapping: https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings

**Comment by KesemSharabi** [comment]
Hi @uve,

Can you please assist with @danieleperilli questions?

Thanks,

Kesem

**Comment by uve** [comment]
Please use [powerbi-visuals-utils-dateviewutils](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-dataview) to find the specific Role.

**Comment by danieleperilli** [comment]
Sorry, but without exposing the roleIndex, a custom visual can't know the order of the fields in the Fields panel. And this could be a problem when there are fields with multiple roles.

**Comment by sriharshAmur** [comment]
This property is not yet part of the API. Is there a plan to include it in the near future @uve? I currently have to set the type to 'any'. The reason I am using the RolesIndex property is that I need to know the position of the column in that particular role.

I made the same issue in the community forum: https://community.powerbi.com/t5/Developer/Property-rolesIndex-does-not-exist-on-type/m-p/2486804
