### ISSUE TITLE
Unable to teach Q&A in Streaming datasets

### ISSUE THREAD

**Issue by tomasbaima** [MicrosoftDocs/powerbi-docs#2155]
Unable to teach about questions and answers in Streaming datasets, the setting icon does not appear in the upper right corner. I can highlight questions but not teach them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3be58e8-522b-1bc1-5c20-94349d5ed617
* Version Independent ID: ecbf2a74-8efd-aecd-3d15-b24bc0a1ca46
* Content: [Teach Q&A to understand questions and terms in Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-teach-q-and-a)
* Content Source: [powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/natural-language/q-and-a-tooling-teach-q-and-a.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @tomasbaima. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @tomasbaima ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
