### ISSUE TITLE
Subreports are now available

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2157]
Limitations: "Subreports and drillthrough reports. You may consider using URL parameters with paginated reports to achieve drillthrough scenarios, however."

Drillthrough are still not available.

https://powerbi.microsoft.com/en-us/blog/subreports-now-available-for-paginated-reports-in-power-bi/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720989e-e6c4-2377-e0c0-8c80d5691f46
* Version Independent ID: 3c6392e8-0f91-1c9c-2c21-15291d46bfd0
* Content: [What are paginated reports in Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi#limitations-and-considerations)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @itsnotaboutthecell. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Good catch, thanks! Updating the article now.
