### ISSUE TITLE
Dataflow Partitioning & XMLA-endpoint

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#2159]
"Dataflows use partitioning for incremental refresh. Once XMLA-endpoints for Power BI Premium are available, the partitions become visible."

Could you clarify what this means ?
It doesn't look like possible to access to dataflow's partition using the XMAL-endpoint, only dataset's partition. Or could you explain how ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60093b2-2bdf-92e9-ee7c-de316b601beb
* Version Independent ID: 25307bcb-648e-e620-3fe9-a1412e89c0b5
* Content: [Using incremental refresh with Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-dataflows-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Ilocans. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
