### ISSUE TITLE
Missing powerbi title bar (updated ribbon)

### ISSUE THREAD

**Issue by Gurucog11** [MicrosoftDocs/powerbi-docs#2162]
When I used updated Powerbi Ribbo for the first time I saw dark grey title bar(Highlighted in the attachment). But it does not appears now. 
Have reinstalled complete powerbi still doesn't help.

![I only see this](https://user-images.githubusercontent.com/28487453/81649850-95cfb980-944e-11ea-819a-2764c2b12b5c.jpg)
![Missing title bar](https://user-images.githubusercontent.com/28487453/81649854-9700e680-944e-11ea-824a-ae0192962c8c.jpg)

**Comment by mihart** [comment]
Thanks for your comment, @Gurucog11 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
