### ISSUE TITLE
Add "Enhanaced Meta-data" limitation

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2163]
You cannot use Python Script if [Enhanced Metadata (Preview) feature](https://docs.microsoft.com/en-us/power-bi/desktop-enhanced-dataset-metadata) is turned-on. Please add it to the limitation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment]
Thanks for your comment, @pawarbi . This issue has been assigned to the doc author for review.

**Comment by otarb** [comment]
hello @pawarbi, you won't be able to use Python script based transformation (get data or in PQ) if you have feature enabled and updated your report to use new format. 

If you enabled feature and open report which already had Python scripts, those will continue to work. 

This will be resolved in June release.

**Comment by pawarbi** [comment]
Thanks @otarb for the update, but please add it to the Limitations of using Python script in Power BI page for now. I unfortunately lost a report because the changes are irrevocable. BI Developers should be aware of this limitation, until it is fixed, on the Python Script page. Hope that makes sense.

**Comment by otarb** [comment]
update doc.

#close

**Comment by otarb** [comment]
#please-close @otarb
