### ISSUE TITLE
Review Power BI Dataflow Best Practices

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerbi-docs#2164]
Been reviewing this recently and noticing that some of the data might be out of date. 

https://docs.microsoft.com/en-us/power-bi/service-dataflows-best-practices

- We're not experiencing similar behavior from the process of having Ingestion and Computed dataflows in the same workspace and actually find it better to have them contained within the same workspace. The reason for this is when the Linked Source is refreshed it automatically refreshes the Computed dataflow which would save time. The only reason I could truly see of scheduling Linked Dataflows is to make your schedules more granular if you refresh your Ingestion dataflows frequently.

- Another item is we encounter quite a bit of problems with the Enhanced Compute engine since it's still in preview.

Trying to figure out if anyone else has other items because i'm trying to stick with this documentation.

**Comment by mihart** [comment]
Thanks for your comment, @cvillegashak. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
