### ISSUE TITLE
Cannot Connect ADLS2 Account to PowerBI

### ISSUE THREAD

**Issue by JamesJHart** [MicrosoftDocs/powerbi-docs#2166]
We have added the permissions listed in the error that PowerBI is giving when we try to connect to the storage account, but we are still not able to connect.

![image](https://user-images.githubusercontent.com/65257817/81749438-7e99c780-9460-11ea-894b-b7ea9a208113.png)

![image](https://user-images.githubusercontent.com/65257817/81749936-6eceb300-9461-11ea-9206-1bc25b6d3e97.png)

I have removed user names from the accounts listed for privacy purposes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#grant-power-bi-permissions-to-the-file-system)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @JamesJHart . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
