### ISSUE TITLE
How to apply Trend line on visual using power bi embed client api?

### ISSUE THREAD

**Issue by jnavaskhan** [MicrosoftDocs/powerbi-docs#2167]
In powerbi embed, currently I see authoring library help to do some action on report.
Example using changeType(visualType: string): Promise&lt;void&gt;;
node_modules\powerbi-report-authoring\dist\powerbi-report-authoring.d.ts

Can we do similar action for analytics functionalities on report through power bi embed using client library? is there any js client api available to do that?
Example i want to apply `Trend Line` on my line chart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95f8c96-ab3e-b94c-2de5-abcf98e71169
* Version Independent ID: 709cb0ed-717a-10bc-62d6-2e4075806ce0
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-analytics-pane#apply-forecasting)
* Content Source: [powerbi-docs/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jnavaskhan . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
