### ISSUE TITLE
Only publish to a different workspace

### ISSUE THREAD

**Issue by JackHorlock** [MicrosoftDocs/powerbi-docs#2169]
Hi,
Can you please confirm that a user with 'build' permission to a dataset but that does not have 'contributor' permission to the workspace where the dataset resides can only produce reports from the dataset (using the service and desktop app) and publish them to a different workspace? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JackHorlock. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
