### ISSUE TITLE
That is very welcomed

### ISSUE THREAD

**Issue by MichaelPointeauItron** [MicrosoftDocs/powerbi-docs#217]
I was waiting for some of this since we decided to subscribe to Premium.
Currently discovery the App.  
I have already a question: how far would we be able to look at the past registered data?
Also we have not waited for this App to get Statistics and Understanding on PowerBI Usage, leveraging the AuditLog option, and we produced  neat Reports and App (using PowerBI off course), so is it possible already or planned to let us reach the underlying data that is sourcing your App? That will be handsome for us to merge everything in one place and provide a unique, always available PowerBI Overall Status / Usage understanding to our company employees.
Thank you.
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity?view=powerbi-ps#next-steps)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by swgupt** [comment]
@MichaelPointeauItron , Thanks for your feedback. You should be able to look at the past 7 days of data. We are  working to make improvements in this area. Be sure to submit your ideas or vote on existing suggestions here : https://ideas.powerbi.com/forums/265200-power-bi-ideas
