### ISSUE TITLE
Gateway

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#2170]
This document suggests that to use live query the gateway is required. Actually, Live Query supports Azure Analysis Services without the data gateway 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fe9672-0cf8-7566-6f4b-49991f9aba3f
* Version Independent ID: fd7ecaee-3d87-272c-713b-03b446008cfc
* Content: [Use Q&A with live connections in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-q-and-a-direct-query#enable-qa)
* Content Source: [powerbi-docs/create-reports/service-q-and-a-direct-query.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-q-and-a-direct-query.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @frvigano.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @frvigano -- Gateways are specifically for on-premises data. Azure Analysis Services data is in the cloud, not on premises, so no, no gateway is needed. Do you think we need to state that in the article? If so, where would you mention it?
Thanks!

**Comment by frvigano** [comment]
The title of the document is “Enable Q&A for live connections in Power BI” : also a report based on Azure Analysis Services is based on a live connection

My point is that we should provide information about both scenarios.

I wrote: “This document suggests that to use live query the gateway is required. Actually, Live Query supports Azure Analysis Services without the data gateway"

Best regards
Francesco

**Comment by maggiesMSFT** [comment]
Ah, got it. OK, thanks! I've changed the article. Update will be live later this afternoon.
