### ISSUE TITLE
Subscriptions with bookmarks

### ISSUE THREAD

**Issue by smithjackson35** [MicrosoftDocs/powerbi-docs#2173]
Are you able to apply a bookmark to a subscription? I have tried adding a subscription with the book mark selected but have been unsuccessful in  making the report deliver with the book mark selected on the data.

**Comment by maggiesMSFT** [comment]
Hi, @smithjackson35 -- interesting question! I'll investigate and let you know.

**Comment by smithjackson35** [comment]
Thank you!

**Comment by maggiesMSFT** [comment]
And thanks to a very responsive program manager, I have an answer already!
"It’s not supported yet."
I'll add this to the subscriptions article, https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-report-subscribe#considerations-and-troubleshooting.
