### ISSUE TITLE
Slicer Feature 

### ISSUE THREAD

**Issue by jtorres1127** [MicrosoftDocs/powerbi-docs#2174]
This Visualizer does not work as explained in the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc558f3-8a74-7154-c048-2dd74ad4eb8a
* Version Independent ID: f84aa1a5-4bab-6f6d-a0ba-5040c0f5defb
* Content: [Use the numeric range slicer in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-slicer-numeric-range#feedback)
* Content Source: [powerbi-docs/create-reports/desktop-slicer-numeric-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-slicer-numeric-range.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jtorres1127 -- Can you elaborate? How is it not working as explained?

**Comment by maggiesMSFT** [comment]
Hi, @jtorres1127 -- receiving no answer, I'm closing this issue. Feel free to reopen or create another issue, if you wish.
thanks!
