### ISSUE TITLE
Matrix visual - conditional formatting on sub-totals does not work for data bars

### ISSUE THREAD

**Issue by smurfer** [MicrosoftDocs/powerbi-docs#2175]
Since the April 2020 release, conditional formatting is supposed to be configurable also for subtotals. This works for conditional background colors, but not for data bars (Power.BI Desktop May 2020).

**Comment by maggiesMSFT** [comment]
Hi, @smurfer -- you're referring to this: https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-april-2020-feature-summary/#_Conditional_formatting, which is also in this article, https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting#totals-and-subtotals. 
Are you asking a question? 
Thanks!

**Comment by smurfer** [comment]
I was trying to raise the point that the statement "Beginning with the April 2020 release, you can apply conditional formatting rules to totals and subtotals, for both table and matrix visuals." is misleading... And actually I was hoping that comments would also make it to the development team.
I find the current behaviour confusing. In a Matrix , conditional formatting with data bars is shown on the top level, but in the levels below except for the lowest level not....

**Comment by maggiesMSFT** [comment]
Hi, @smurfer -- thanks for clarifying! Assigning to the author address it.

**Comment by davidiseminger** [comment]
Thanks for your comment, @smurfer. Since this is product feedback (rather than documentation feedback), your best bet is to submit product feedback or feature ideas by going to https://ideas.powerbi.com. 

You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
