### ISSUE TITLE
Text not consistent with diagram

### ISSUE THREAD

**Issue by pfischer54** [MicrosoftDocs/powerbi-docs#218]
Under "Shaped Data" section:
"You can also change, or transform, those columns from text to header by using the Transform ribbon. Here’s the Transform ribbon, with an arrow pointing toward the Data Type button, which lets you transform the current data type to another"
 Diagram does not show the Transform ribbon.  Also the text should presumably read "...from text to whole number..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Getting started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. I don't see or find the test you refer to in this article, perhaps you meant another article?
