### ISSUE TITLE
Stale instructions.

### ISSUE THREAD

**Issue by lkc22** [MicrosoftDocs/powerbi-docs#2180]
There is no "Don't have a work email?" hyperlink (option) on the new Web page
https://signup.microsoft.com/create-account/signup?offerid=B07A1127-DE83-4a6d-9F85-2C104BDAE8B4&dl=ENTERPRISEPACK&ispolaris=1&culture=en-US&country=US&ali=1&products=cfq7ttc0k59j:0009

What is the point of demanding a work email address for a 2 month trial license besides wasting 2 hours of my life trying to get this to work with my "PAID" Microsoft 365 license. Given the COVID 19 pandemic, which I'm sure you've read about, people are loosing their jobs and won't have access to their workplace email accounts. Some people are doing autonomous at home CBT training (www.lynda.com) to prepare for re-entry into the workforce.

Obviously Agile development paradigm precludes updating user documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f747f-9b4f-2bfc-831e-ed8232177d38
* Version Independent ID: b2da371d-aea3-010b-5e57-a6c8d5a9646d
* Content: [Signing up for Power BI with a new Microsoft 365 Trial - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial#feedback)
* Content Source: [powerbi-docs/admin/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by lkc22** [comment]
Here is screen clip of the new Office 365 E3 registration:

![image](https://user-images.githubusercontent.com/64289521/81957918-3c48c580-95db-11ea-9e83-423872ae4de5.png)

The appearance does NOT match the April 2020 released instructions. Note the absence "Don't have a work email?" hyperlink (option) . Obviously SCRUM master is not managing the downstream dependencies on evolving the Power BI registration s/w.

Also, the Product Owner and the BA need to understand environmental conditions that have come into play in then last 4 months such as people loosing their jobs to COVID 19. i.e. no accessible workplace email address. It's a two month trial license - make it easy for people to play with the software.

**Comment by kfollis** [comment]
Hi @lkc22 - Thanks for pointing out the mismatch between our documentation and the updated UI. The article is being updated this week to match the new sign-up steps. In the new flow, after you enter your email address, the system will check to see if that account can be used with Microsoft 365 business subscriptions. If not, in Step 3 (of the screenshot you attached), you create a new account to use with your trial. You can also download Power BI desktop for free from the Windows store. Our learning paths located here: https://docs.microsoft.com/en-us/learn/browse/?term=power%20bi include sandbox environments to use while learning the software.

**Comment by lkc22** [comment]
You still don’t get it.

The CBT course require Power BI, not Power BI Desktop. POWER BI trial license demands a workplace or student email account.

What is the harm in making the 60 day free trial license open ended i.e. independent of  a workplace or student email account? What is the importance of having business and student addresses only?  If it’s blotting the marketing databse, then make the product open ended.

Please read my edition to the complaint about people loosing their jobs. Please have your Power BI product owner or marketing call me at 613 293-5240 (M).

Practice KISS. Your customers will love you for it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lkc22** [comment]
You still don’t get it.

The CBT course require Power BI, not Power BI Desktop. POWER BI trial license demands a workplace or student email account.

What is the harm in making the 60 day free trial license open ended i.e. independent of  a workplace or student email account? What is the importance of having business and student addresses only?  If it’s blotting the marketing databse, then make the product open ended.

Please read my edition to the complaint about people loosing their jobs. Please have your Power BI product owner or marketing call me at 613 293-5240 (M).

Practice KISS. Your customers will love you for it.

Sent from Mail for Windows 10

**Comment by kfollis** [comment]
Removing personal information. This feedback channel is specifically for noting improvements to documentation. To discuss product marketing, try posting to https://ideas.powerbi.com/forums/265200-power-bi-ideas or the Power BI community: https://community.powerbi.com/.  A work or school account is required by the identity management system, which is Azure Active Directory. Consumer email identities are managed by their providers and can't be used with AAD.

**Comment by mihart** [comment]
Hi @kfollis , @lkc22 ,
I've updated the doc for signing up for a trial.  It should go live this afternoon.
Thanks for letting us know about the change to the process.
