### ISSUE TITLE
Adding role member in Power BI desktop.

### ISSUE THREAD

**Issue by johnyuan10** [MicrosoftDocs/powerbi-docs#2181]
It used to be able to add role members in Power BI desktop. Why that function is gone and is there a plan to bring it back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls#feedback)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by maggiesMSFT** [comment]
Hi, @johnyuan10 -- thanks for asking! Referring to the author to investigate.

**Comment by kfollis** [comment]
Role members are now added in the Power BI service by configuring security for the dataset. This is shown in the article.
