### ISSUE TITLE
Is This Correct?

### ISSUE THREAD

**Issue by PimKamp** [MicrosoftDocs/powerbi-docs#2185]
Users without a Pro license can access the workspace if the workspace is in a Power BI Premium capacity, even if users have only the Viewer role.
This seem more logical
Users without a Pro license can access the workspace if the workspace is in a Power BI Premium capacity, only if users have the Viewer role.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces#feedback)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @PimKamp -- I love it! Thanks for the careful read. I've tweaked it a little and made the change. It'll be live later today.
