### ISSUE TITLE
Business Analyst

### ISSUE THREAD

**Issue by ColeenB** [MicrosoftDocs/powerbi-docs#2186]
We're adding groups to the Permissions tab when publishing an app. These same groups are added to a RLS role in the Security setting for the database. This is working for one group, but the members of another group can't see the app at all. Both are distribution lists. Can you clarify the requirements for groups to be used to provide access to apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ColeenB -- a couple of questions:
- Is the app from a workspace in a Premium capacity?
- If not, do members of both groups have Power BI Pro licenses?
Thanks!

**Comment by ColeenB** [comment]
The workspace is in a Premium capacity.

Coleen

**Comment by maggiesMSFT** [comment]
Hi, @ColeenB -- thanks. It sounds like a bug, I'm afraid. You can try the Power BI community, https://community.powerbi.com/, to see if they have suggestions. If not, contact Power BI support, https://powerbi.microsoft.com/en-us/support/.
