### ISSUE TITLE
Table not correctly showing up in navigator while importing from web - wikipedia

### ISSUE THREAD

**Issue by kapilnigam** [MicrosoftDocs/powerbi-docs#2187]
I am trying to import data from following wikipedia page.
https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations

It seems PowerBI is picking up only first header and not able to navigate downward on Codes and abbreviations data.
![Wikipedia_List_of_U S _state_abbreviations_error](https://user-images.githubusercontent.com/46722456/82087585-035d3d80-970e-11ea-90f0-aa6ee30486e1.PNG)
![List_of_U S _state_abbreviations_error](https://user-images.githubusercontent.com/46722456/82087589-05270100-970e-11ea-9511-da07eee682e5.PNG)

**Comment by maggiesMSFT** [comment]
Hi, @kapilnigam -- I see the issue, the multi-level headings. Referring this question to the author of https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-to-web for a possible solution. In the meantime, I would ask the Power BI Community, https://community.powerbi.com/, or search in the Power BI Ideas Forum, https://ideas.powerbi.com/forums/265200-power-bi

**Comment by davidiseminger** [comment]
Sorry you're having trouble with that - and indeed, your best bet for a solution is to visit the community (as described in the previous comment) or suggest improvements in the Power BI Ideas Forum (also in the previous comment).
