### ISSUE TITLE
Why does this page show connecting to Exchange Online via PowerShell with basic auth?

### ISSUE THREAD

**Issue by ryanspletzer** [MicrosoftDocs/powerbi-docs#2189]
Microsoft has deprecated this insecure login method and is removing it mid-2021. (Originally October 2020 but that got pushed out.)

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-april-2020-update/ba-p/1275508

People should use the ClickOnce Exchange PowerShell that they can install from Exchange Admin Center, or more ideally the new Exchange V2 PowerShell module.

https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing#use-the-audit-log)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @ryanspletzer . Thanks for the comment. I'll look into this.

**Comment by kfollis** [comment]
HI @ryanspletzer - this article was recently updated and the PowerShell instructions were updated to reference the Exchange V2 PowerShell module. Thanks for flagging that, I appreciate the feedback. Closing this issue now.
