### ISSUE TITLE
Getting Error when installing the application

### ISSUE THREAD

**Issue by gregoryleandro** [MicrosoftDocs/powerbi-docs#219]
We couldn't install Power BI Premium Capacity Metrics
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Message: The column 'Column1' of the table wasn't found. Table: EvictionMetrics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@gregoryleandro - can you try an uninstall/reinstall to see if that addresses it?

**Comment by mgblythe** [comment]
@gregoryleandro - are you a capacity admin or a Power BI admin? You need admin rights to at least one capacity to use the app.

**Comment by gregoryleandro** [comment]
I'm am Power BI admin only. It would be nice for a Power BI  admin to have an overview of the metrics from all capacities on the tenant.
