### ISSUE TITLE
Shouldn't this be called "Role-level security"?

### ISSUE THREAD

**Issue by AsafMozes** [MicrosoftDocs/powerbi-docs#2191]
The feature allows different access per role. I don't see how rows are relevant here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls#feedback)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your question. There is a difference, and here's a discussion in the community:

https://community.powerbi.com/t5/Desktop/role-level-security-and-row-level-security-usage/td-p/366084
