### ISSUE TITLE
Use your imagination for Forecasting?

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2192]
Hi, the documentation says Use your imagination to see how it may apply to your model. Isn't that vague and ambiguous? We are working with concrete data and need to deploy the forecasting for the business leaders to use it, we can't use imagination to create a forecasting model. Please provide us specific guidelines when using the forecasting feature, what algorithms are used, when should we use it and what are the best practices.

**Comment by davidiseminger** [comment]
Thanks for your comments - could you tell us which article you're referring to? Then we can determine the best way to route your question.

**Comment by pawarbi** [comment]
>
> 
> Thanks for your comments - could you tell us which article you're referring to? Then we can determine the best way to route your question.

Yes, sorry I forgot to refer to the article. Here is the page I am referring to : https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane#apply-forecasting

**Comment by mihart** [comment]
Thanks for your comment, @pawarbi . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks. In terms of using your imagination, the intent is to suggest you use variations on the forecast length, confidence interval, and other forecasting parameters to see what the results might forecast.
