### ISSUE TITLE
Is there any detail documents about how to use enumerateObjectInstances?

### ISSUE THREAD

**Issue by f14eagle** [MicrosoftDocs/powerbi-docs#2193]
We are developing a custom powerbi visual, and we want to use the enumerate for one of the properties. The usage of enumerateObjectInstances in this article is not very clear so we are not able to implement a very basic enumerate feature in our component...

Is there any detail document, or existing sample about how to use 
enumerateObjectInstances?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18bae87-ca93-25e9-26a6-5daf585b4798
* Version Independent ID: 2c2793d0-50a6-c401-3ecf-ccba9f155397
* Content: [Objects and properties of Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/objects-properties)
* Content Source: [powerbi-docs/developer/visuals/objects-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/objects-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @f14eagle . This issue has been assigned to the doc author for review.

**Comment by uve** [comment]
Hello,
You can find working samples here:
1) [SampleBarChart](https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/471f103fcef9af93cff76cbac9c7fc67564acd4b/src/barChart.ts)
2) [DataBoundObjects.md](https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/61011c82b66ca0d3321868f1d089c65101ca42e6/Tutorial/DataBoundObjects.md)
3) [StaticObjects.md](https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/61011c82b66ca0d3321868f1d089c65101ca42e6/Tutorial/StaticObjects.md)
