### ISSUE TITLE
Possibility to drill through without any selection

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#2194]
This might seam like an odd request, but please read Justification section. 

My request is to add the possibility to enable drill-through without selecting any items. 

The button will then work like a page navigation button with the exception that it will also reset any existing drill-through filters on the destination page. A bookmark navigation can not be used as an alternative, since the bookmark data configuration will then also reset all page level filters on the destination page (and that is not always wanted)

Justification:
There's currently no way you can navigate to a drill through page without pre-selecting any filters. E.g. You have a main page where you can select part of you organization with e.g. your new hierarchy filter. This page contains visualizations that are using the sub-units of your organization on axis or legends. The drill through page enable drilling on sub-units. So this way you can drill through to the drill through page on sub-units. But what if you would like to navigate to the drill-through page using the whole of your organization. 
This can't be done using page navigation since this will not reset the filters on the drill-through columns/measures. And this can not be done using the bookmark navigation since the bookmark can not be configured to reset the drill-through filters (without resetting all the page filters)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15666d4-ae4f-6d89-ef11-e197238485eb
* Version Independent ID: 1cfb2398-7a74-9e37-3135-f0688fd39cf2
* Content: [Create a drill-through button in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-drill-through-buttons)
* Content Source: [powerbi-docs/create-reports/desktop-drill-through-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-drill-through-buttons.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by erapade** [comment]
Maybe this comment is only related to documentation. I added an idea on the same subject so you can close this if this is just for documentation

**Comment by mihart** [comment]
Hi @erapade 
I'm going to close this doc issue.  This isn't really an issue with the documentation but rather a product idea/suggestion.  You wrote that you've already posted it on ideas.community.com, which is the best approach.  Thanks.
