### ISSUE TITLE
installing pbiviz

### ISSUE THREAD

**Issue by powerbijools** [MicrosoftDocs/powerbi-docs#2195]
the code to enter into powershell to install pbiviz using npm i -g ~    does not work and i get the error below .  can you update this page or advise wha the error is thanks

PS C:\WINDOWS\system32&gt; npm i -g powerbi-visuals-tools
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC
npm ERR! errno ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC
npm ERR! request to https://registry.npmjs.org/@babel%2fplugin-transform-for-of failed, reason: 16536:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jools\AppData\Roaming\npm-cache\_logs\2020-05-19T14_04_13_580Z-debug.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @powerbijools . This issue has been assigned to the doc author for review.

**Comment by andreagutierrezampuero** [comment]
Try using this: npm config set strict-ssl false

**Comment by KesemSharabi** [comment]
Hi @uve, 

Can you please point @powerbijools in the right direction?

Thanks,

Kesem

**Comment by HarryLeboeuf** [comment]
Having the same problem, following the issue.

**Comment by andreagutierrezampuero** [comment]
This is the command I executed: npm config set strict-ssl false ... then I returned to true

**Comment by uve** [comment]
Try to upgrade your NodeJS to v12.x and install the package again.
