### ISSUE TITLE
Featured question

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/powerbi-docs#2199]
@sosotheso commented on [Tue May 19 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/27)

I want to know if powerbi generate itself the answer for our featured question, or we need to define the answer somewhere. thanks 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9707e1ff-5927-e3e4-134d-8d2b04266f9c
* Version Independent ID: bec9f641-757c-b76f-4cee-c823c60222b4
* Content: [Création de questions exemplaires pour les Q&R de Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/create-reports/service-q-and-a-create-featured-questions#feedback)
* Content Source: [powerbi-docs/create-reports/service-q-and-a-create-featured-questions.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/create-reports/service-q-and-a-create-featured-questions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

---

@srvbpigh commented on [Tue May 19 2020](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/27#issuecomment-631127188)

Hello, @sosotheso
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @v-radelg . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Bonjour, @v-radelg -- Oui, c'est Power BI qui cree la reponse. Merci d'avoir demander! J'ai ajoute ca a l'article.
