### ISSUE TITLE
Error in DAX function SELECTEDVALUE

### ISSUE THREAD

**Issue by Baksteen-BJD** [MicrosoftDocs/powerbi-docs#2200]
Hi, the example "See details" DAX function has a syntax error, if I am correct. It should read:
String_for_button = If(SELECTEDVALUE('Product'[Product], 0) == 0, "See product details", "See details for " & SELECTEDVALUE('Product'[Product]))
after the "==0" there should not be a close bracket ")".
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a15666d4-ae4f-6d89-ef11-e197238485eb
* Version Independent ID: 1cfb2398-7a74-9e37-3135-f0688fd39cf2
* Content: [Create a drill-through button in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-drill-through-buttons#feedback)
* Content Source: [powerbi-docs/create-reports/desktop-drill-through-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-drill-through-buttons.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @Baksteen-BJD . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
@Baksteen-BJD -- you're absolutely right! Thanks for catching that. Fixing it now. Fix will be live tomorrow afternoon.
