### ISSUE TITLE
regional settings on PowerBI service

### ISSUE THREAD

**Issue by hokeson** [MicrosoftDocs/powerbi-docs#2201]
Hello, how to change the regional settings in PBI service?
I would like to use English but with date format dd.MM.yyyy 
is there any way how to do that?
thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01f4ea6-33ff-97ca-4a4e-8a1beb88f12f
* Version Independent ID: e5224487-369d-23be-98cb-ebab58c75ac4
* Content: [Supported languages and countries/regions for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/supported-languages-countries-regions#feedback)
* Content Source: [powerbi-docs/fundamentals/supported-languages-countries-regions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/supported-languages-countries-regions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @hokeson . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
