### ISSUE TITLE
Additional operations

### ISSUE THREAD

**Issue by AleksaT** [MicrosoftDocs/powerbi-docs#2202]
Hey, I noticed that some of main PowerBI operations are missing like Shared Power BI dataset. Is this list of available operations will change over time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @AleksaT - thanks for your comment. Yes, the list of operations will change over time. I'll check into the operation you mention as part of the next update.

**Comment by mihart** [comment]
Hi @AleksaT ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
