### ISSUE TITLE
Include details on Forecasting 

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2203]
Power BI team shared the details on the Forecasting, algorithms used, and general guidelines here: https://powerbi.microsoft.com/en-us/blog/introducing-new-forecasting-capabilities-in-power-view-for-office-365/

Can you please include these details on the Forecasting page https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane#apply-forecasting for clarity. It will be very helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane#apply-forecasting)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @pawarbi.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
I've added a reference to that blog article, so users can find that information and use it, if useful.
