### ISSUE TITLE
Row Level Security (using dynamically generated datakey)

### ISSUE THREAD

**Issue by bradj813** [MicrosoftDocs/powerbi-docs#2204]
Hello. Can Power BI Paginated reports within the Power BI Service support dynamically generated datakeys for RLS? 
For instance, I currently have multiple Power BI reports, in the Service, that are filtered using RLS by a dynamically generated datakey the app passes to the report. This datakey is based on UserId_CompanyId, therefore, depending on the user who's logged into the app and that user's specific company access, a specific datakey will be generated then passed to the report to filter via RLS. (I've seen examples where UserId can be possible passed for RLS, but I need dynamic datakey support). Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561fba06-3092-f009-343e-b37f133bee44
* Version Independent ID: e0d74c12-1a25-18ba-e511-49466055cb98
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/paginated-reports-row-level-security#feedback)
* Content Source: [powerbi-docs/developer/embedded/paginated-reports-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/paginated-reports-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @	bradj813. I’ll look into your question.

**Comment by bradj813** [comment]
Thanks KesemSharabi. Any update on this?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bradj813. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
