### ISSUE TITLE
Updated URL's

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#2205]
The PowerBI Web Front ends have new URLS in the format of:
ssl.pbi-wfe-us-east2.azurewebsites.net
Can we update the doc to reflect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297c1372-b1bb-57c4-9c31-840b4cad2c37
* Version Independent ID: 0bb282a3-4aa6-1094-d8a4-652ec726734f
* Content: [Power BI URLs for whitelisting - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/power-bi-whitelist-urls)
* Content Source: [powerbi-docs/admin/power-bi-whitelist-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/power-bi-whitelist-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Added wildcard entry as determined through email conversation
