### ISSUE TITLE
Power BI custom visual simplest project

### ISSUE THREAD

**Issue by radiotalks** [MicrosoftDocs/powerbi-docs#2206]
I've created startup project using pbiviz new proj. Then after the visual has been imported in PB Desktop I see red frame around Font Size input field with a tooltip 'Value must be a number'. What's wrong with it ?
Thank You.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 049f618d-c8bf-2ff1-9cba-ce293816621e
* Version Independent ID: 905eaa9c-3d41-5ce2-6fd5-1015e27c042c
* Content: [Frequently asked questions about Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-faq)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/power-bi-custom-visuals-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @uve, can you please help with this?

**Comment by uve** [comment]
Font size input supports numbers only. And this input can't be empty.

**Comment by radiotalks** [comment]
Size of font is not zero and is of integer type. But red frame is shown
even for a valid input. I can send you screenshot for more detailed
description of a problem.

ср, 20 мая 2020 г. в 20:46, Nikita Grachev <notifications@github.com>:
