### ISSUE TITLE
Test key for Enrollment 100 no longer working...

### ISSUE THREAD

**Issue by ryanferguson** [MicrosoftDocs/powerbi-docs#2207]
The test key that is published for the 100 enrollment which is for testing purposes no longer seems to function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ryanferguson -- thanks for asking! Looking at the article, it appears the "100" is an example, not a number for testing purposes. The text after the screen shot is:
"You'll need to replace the enrollmentNumber value with _your enrollment number_. You can get your number from the Azure Enterprise Portal. The numberOfMonth parameter is how many months of data you want going back, from the current dat. Use zero (0) for the current month."
Adding the author in case he has other comments, and perhaps to clarify in the article.
Thanks!
