### ISSUE TITLE
Is there a test enrollment in which one can develop reporting against?

### ISSUE THREAD

**Issue by ryanferguson** [MicrosoftDocs/powerbi-docs#2208]
WIth the old connector, this was Enrollment 100 and the API key was published so we could generate repors on real data.  Is there any test data source that we can connect to for this connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ryanferguson - Ah, I see what you were asking in the other question, https://github.com/MicrosoftDocs/powerbi-docs/issues/2207
Adding @davidiseminger to see if he has further info. 
Probably can close the other one, yes?

**Comment by davidiseminger** [comment]
There is not a test data source available at this time. You might find more luck with that question (or see what others have done) in the Power BI Community, found at https://community.powerbi.com.
