### ISSUE TITLE
Workbooks "with ranges or tables of data" vs "with data models"

### ISSUE THREAD

**Issue by colmardev** [MicrosoftDocs/powerbi-docs#2209]
I think it's not clear enough how the presence of data model can influence the resulting Dataset.

All details [here](https://community.powerbi.com/t5/Service/Get-data-from-Excel-workbook-files/td-p/1093004)

Am I missing any other doc?

**Comment by maggiesMSFT** [comment]
Hi, @colmardev -- I see your question refers to this article, https://docs.microsoft.com/en-us/power-bi/connect-data/service-excel-workbook-files, right? Assigning to the author for consideration. Thanks!

**Comment by colmardev** [comment]
Yes, thanks, please take a look at my linked Power BI forum post

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. I see that you've already posted there and have received feedback and guidance, I hope that helped. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
