### ISSUE TITLE
PowerShell and the Power BI API

### ISSUE THREAD

**Issue by Paul-Gannaway** [MicrosoftDocs/powerbi-docs#2210]
We are trying to use PowerShell and the Power BI API to import RDL files from SSRS into Power BI but we have an on-premises version of the server.

It is basic authentication that I cannot do! The basic call Connect-PowerBIServiceAccount seems to only want to talk to a Cloud instance.

Was wondering if the API is supported on the o-p version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Paul-Gannaway -- thanks for asking! I'll investigate and get back to you. In the meantime, you might want to ask the Power BI community, https://community.powerbi.com/.

**Comment by maggiesMSFT** [comment]
Hi, @Paul-Gannaway -- could you use the SQL Server Reporting Services/Power BI Report Server migration tool plus scripts? See this article for guidance: https://docs.microsoft.com/power-bi/guidance/migrate-ssrs-reports-to-power-bi

**Comment by maggiesMSFT** [comment]
Hi, @Paul-Gannaway -- not hearing back from you, I'm closing this issue. Let me know if you have further question!
