### ISSUE TITLE
.json customize series(indexing multiple choices)

### ISSUE THREAD

**Issue by elcu** [MicrosoftDocs/powerbi-docs#2211]
Hello,

is there any way how to index, i.e. write multiple choice entries in visuals that have the option to "customize series"? For example in the area chart -> data labels -> customize series - you can manage the settings for each of the series. How to write this in .json please? It's missing in the documentation.

```
"labels": [{
		"showAll": true, --- this enables the option to customize each of the series
                 1. customize first serie - set: ("backgroundTransparency": 70)
                 2. customize second serie - set: ("backgroundTransparency": 60)
                 etc.
              }]
```
Thank you!

**Comment by maggiesMSFT** [comment]
Hi, @elcu -- could you tell me which article you were looking at? That will help assign it to the right author. Thanks!

**Comment by elcu** [comment]
Hello @maggiesMSFT ,

it should be part of this article:

https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#report-theme-json-file-format

It's about importing .json file with your own theme into power BI, and there is no mention how to set up/index the settings for "customized series" in some charts.

Thank you!

**Comment by maggiesMSFT** [comment]
Thanks, @elcu -- I've assigned it to the author for consideration. Thanks!

**Comment by mihart** [comment]
Hi @elcu,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
