### ISSUE TITLE
How to troubleshoot the error "There is no available gateway"

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#2212]
I noticed that section doesn't cover some more basic troubleshooting steps, and maybe they are obvious enough to not need mentioning. 

* Verify the gateway version is up to date
* Verify the report has a gateway selected. If no gateway is available, the datasource may have changed or is missing?

https://community.powerbi.com/t5/Service/January-2020-There-is-no-available-gateway/td-p/912677

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jonwbstr -- thanks for the suggestion! Assigning to the author for consideration.

**Comment by davidiseminger** [comment]
@jonwbstr - those are great basic steps. Thank you! I've added them to the top of that article, just to make sure people check those first. Great contribution, thanks!
