### ISSUE TITLE
Power BI Report Server unclear

### ISSUE THREAD

**Issue by markdburton** [MicrosoftDocs/powerbi-docs#2214]
Hi, my understanding was that SQL Server Enterprise Edition with SA grants PBI Premium use rights, but the wording above refers to the "service" and "capacity", which makes it unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec63d236-fde3-47d8-96a5-5d205dd96b59
* Version Independent ID: 0f9cc0dc-e417-ed61-ff2a-7155cdadf8c5
* Content: [Power BI licensing in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-licensing-organization)
* Content Source: [powerbi-docs/admin/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @markdburton -  I found some resources that should help to clarify the SQL Server SA benefit. This community thread provides an answer: https://community.powerbi.com/t5/Report-Server/SQL-Server-Enterprise-Edition-with-Software-Assurance/m-p/955582#M13282 and this article https://docs.microsoft.com/en-us/power-bi/admin/service-premium-faq addresses the question near the bottom of the page. Hope that helps!

**Comment by markdburton** [comment]
Yes, I understand the benefits, etc., but the article muddies the water by referring to 'capacity' and the 'service' which is not the only way to license my organisation (via SQL use rights). The article could be written in a way that covers the on premise PBI capability as well by fixing a few words - or the article should be labelled as applying to the service only and should have a link to the PBI RS licensing info.
