### ISSUE TITLE
Update to clarify purchase method for Volume Licensing customers

### ISSUE THREAD

**Issue by fmesposito** [MicrosoftDocs/powerbi-docs#2215]
Similar to the how to purchase documentation for other Microsoft Online Services, such as https://docs.microsoft.com/en-us/microsoft-365/commerce/licenses/buy-licenses?view=o365-worldwide#what-if-i-dont-see-the-addremove-licenses-link 

This page should be update to clarify that customers who typically purchase via Volume Licensing agreements, such as an Enterprise Agreement, that wish to be invoiced for Power BI instead of purchasing with a credit card, should submit orders through their Microsoft Reseller or via licensing reservations through the Volume Licensing Services Center.

**Comment by maggiesMSFT** [comment]
Hi, @fmesposito -- Thanks for your comment! Could you indicate which Power BI article you're referring to so I can assign you comment correctly? Thanks!

**Comment by fmesposito** [comment]
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-purchasing-power-bi-pro

Francesco Esposito
Sr Modern Workplace Specialist
Strategic Accounts
Great Lakes Enterprise Commercial
FrancEs@microsoft.com<mailto:frances@microsoft.com> | Teams: 248.200.5141

**Comment by maggiesMSFT** [comment]
Thanks, @fmesposito ! I've assigned it to the author for review.

**Comment by kfollis** [comment]
@fmesposito - thank you for your input! I have added a note to the article and a link to the Microsoft 365 related documentation. The updates will publish later today.

**Comment by fmesposito** [comment]
Great, thank you!

Francesco Esposito
Sr Modern Workplace Specialist
Strategic Accounts
Great Lakes Enterprise Commercial
FrancEs@microsoft.com<mailto:frances@microsoft.com> | Teams: 248.200.5141
