### ISSUE TITLE
Embed in SharePoint Online using the Power BI web part

### ISSUE THREAD

**Issue by sajas-s** [MicrosoftDocs/powerbi-docs#2218]
Embed in SharePoint Online using the Power BI web part is now available in GCC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview#feedback)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by maggiesMSFT** [comment]
Hi, @ssalahud1 -- thanks for the information! Assigning to the author.

**Comment by kfollis** [comment]
@sajas-s - thank you for helping keep this article up to date! I have made this change and it will be live this afternoon. Look for additional changes to this article in the next few days!
