### ISSUE TITLE
Guidance on using in Azure Government

### ISSUE THREAD

**Issue by mrpullen** [MicrosoftDocs/powerbi-docs#2219]
This doesn't seem to work in an Azure Government Tenant - any assistance / guidance that is available would be great on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management?source=docs)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mrpullen -- thanks for your question! Assigning to the author to investigate. In the meantime, you may want to check the Power BI community page, https://community.powerbi.com, to see if anyone has discussed this.

**Comment by davidiseminger** [comment]
Thanks for your comment @mrpullen. The Azure Government Tenant does sometimes diverge (in terms of available features) from public versions. 

Your best bet for getting this working in the GOV tenants is to contact your Microsoft representative, and to submit product feedback or feature ideas by going to https://ideas.powerbi.com.
