### ISSUE TITLE
Typo in the "Pull Request" table description? 

### ISSUE THREAD

**Issue by DaveBurnisonMS** [MicrosoftDocs/powerbi-docs#2220]
The last sentence of the "Pull Request" table description is: 
This table will be empty when there are no issues in the repo.

Should that be?:
This table will be empty when there are no pull requests in the repo. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github)
* Content Source: [powerbi-docs/connect-data/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @DaveBurnisonMS -- good question! Assigning to the author to check.

**Comment by paulinbar** [comment]
Hi @DaveBurnisonMS - Sharp eyes! Correction going live in a few hours. Thanks!
