### ISSUE TITLE
Additional Limitation on Refresh

### ISSUE THREAD

**Issue by gbrunnerbi** [MicrosoftDocs/powerbi-docs#2221]
**Web.BrowserContents appears to have the same effect as Web.Page - it requires a gateway to refresh otherwise you cannot refresh this data in the Power BI Service**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @gbrunnerbi.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @gbrunnerbi ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
