### ISSUE TITLE
Hyperlink Outdated

### ISSUE THREAD

**Issue by jeremyblackhub** [MicrosoftDocs/powerbi-docs#2222]
The Planning a Power BI Enterprise Deployment whitepaper is now on V3.0 as of April 2020. Please update link to https://aka.ms/PBIEnterpriseDeploymentWP as found on https://docs.microsoft.com/en-us/power-bi/guidance/whitepapers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd0baa2-2e0a-9bbe-115f-f545f7c1ec84
* Version Independent ID: 6148e740-b101-cf26-f445-0b6dc190b39e
* Content: [Power BI enterprise deployment whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jeremyblackhub. I'll look into this issue shortly.

**Comment by KesemSharabi** [comment]
Hi @jeremyblackhub,

As far as I can see after downloading the [Planning a Power BI Enterprise Deployment](https://aka.ms/PBIEnterpriseDeploymentWP) article, its version is 3.0.

Just to make sure we're on the same page, you're talking about the first article mentioned in the [Whitepapers for Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepapers) table - correct?

Is there something I'm missing?

Thanks,

Kesem

**Comment by jeremyblackhub** [comment]
Hello @KesemSharabi,

The first article mentioned in the [Whitepapers for Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepapers) table does link to the correct 3.0 version of the [Planning a Power BI Enterprise Deployment](https://aka.ms/PBIEnterpriseDeploymentWP) whitepaper, but the link on the [Governance and deployment approaches article](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-governance) points to an older, 2.0 version.

Thanks,
Jeremy

**Comment by KesemSharabi** [comment]
Hi @jeremyblackhub,

You're correct, the link from the [Governance and deployment approaches](https://docs.microsoft.com/power-bi/admin/service-admin-governance) article downloads the 2.0 version.

I'll look into it and update you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @jeremyblackhub,

I fixed the link in [Governance and deployment approaches](https://docs.microsoft.com/power-bi/admin/service-admin-governance) - it's now pointing to the correct **Planning a Power BI Enterprise Deployment** whitepaper.

Thanks,

Kesem
