### ISSUE TITLE
Are the development pipelines in PBI integrated in Azure DevOps?

### ISSUE THREAD

**Issue by Ghuiles** [MicrosoftDocs/powerbi-docs#2223]
Hi!

We are already using Azure Devops. What is the integration of the PBI pipeline, or what will it be?

Best regards
G.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c40e327-d8c8-3011-e68b-7694d0ed2b04
* Version Independent ID: 3947ee9f-58b0-763c-8b56-b21cfdcbaac1
* Content: [Deployment pipelines troubleshooting - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-troubleshooting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/deployment-pipelines-troubleshooting.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your question, @Ghuiles.

@NimrodShalit, can you please comment on future plans for integration between DevOps and Deployment pipelines?

Thanks,

Kesem

**Comment by NimrodShalit** [comment]
We are planning to build integration with DevOps in the future, don't have a specific timeline yet.

**Comment by Ghuiles** [comment]
Hi Nimrod!

Thanks for your reply.

Best regards
G.
