### ISSUE TITLE
Change in service principle display name

### ISSUE THREAD

**Issue by thereverand** [MicrosoftDocs/powerbi-docs#2224]
The display name of principle with id 00000009-0000-0000-c000-000000000000 is no longer 'Microsoft.Azure.AnalysisServices', it's Power BI Service

**Comment by KesemSharabi** [comment]
Thanks for your comment, @thereverand. I’ll add this request to our docs backlog.

**Comment by KesemSharabi** [comment]
Hi @thereverand,

Can you please let me know where in the documentation this string appears?

Thanks,

Kesem

**Comment by thereverand** [comment]
powerbi-docs/powerbi-docs/admin/service-encryption-byok.md

Under Configure Azure Key Vault > Add Service Principal

**Comment by KesemSharabi** [comment]
Hi @thereverand,

When I search **Key Vaults > Create key vault** for the string **00000009-0000-0000-c000-000000000000** (as per the instructions in [Add the service principal](https://docs.microsoft.com/power-bi/admin/service-encryption-byok#add-the-service-principal)), I get **Microsoft.Azure.AnalysisServices** which is the expected result according to the article.

![image](https://user-images.githubusercontent.com/54834915/87029804-507afe80-c1e9-11ea-842d-7fb7f9b9a08d.png)

Can you please post a screenshot with the information you're getting?

Thanks,

Kesem
