### ISSUE TITLE
Multiple Data Sets

### ISSUE THREAD

**Issue by soldstatic** [MicrosoftDocs/powerbi-docs#2225]
At the MS Biz Application summit ~ May 2, 2020 a presenter demo'd that left side modelling could be enabled and that multiple data models could be connected to as well. How do we enable those features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @soldstatic.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
@soldstatic - I believe you're talking about composite models. Here's a link to the document:

https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models

**Comment by soldstatic** [comment]
No, I'm not talking about composite models. I'm talking about being able to
inherit data sets from multiple workspaces and link them together.
