### ISSUE TITLE
Where do you set the enhanced compute engine at dataflow level?

### ISSUE THREAD

**Issue by PaulKna** [MicrosoftDocs/powerbi-docs#2226]
How do you access the screen shown by the screenshot under "Enable DirectQuery for dataflows"? I have the enhanced compute engine turned on at capacity level but cannot find this option to set the enhanced compute engine at dataflow level - it needs to be explained where this is accessed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369c84b0-97ef-a750-86cd-5330626c75ac
* Version Independent ID: 3af79c25-1e82-ab08-7604-bfaa9ace6128
* Content: [Use the enhanced compute engine with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-enhanced-compute-engine)
* Content Source: [powerbi-docs/transform-model/service-dataflows-enhanced-compute-engine.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-enhanced-compute-engine.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @PaulKna.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
