### ISSUE TITLE
Incorrect text for Many to one  Cardinality- doc bug

### ISSUE THREAD

**Issue by rukiacee** [MicrosoftDocs/powerbi-docs#2228]
Many to one (*:1): A many-to-one relationship is the most common, default type of realtionship. It means the **column in one** table can have more than one instance of a value, and the other related table, often know as the lookup table, has only one instance of a value.

This should be **column in many** 
https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-create-and-manage-relationships.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rukiacee.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. I've updated that article to make that passage clearer.
