### ISSUE TITLE
Power BI Publisher for excel is no longer available

### ISSUE THREAD

**Issue by GMAU01** [MicrosoftDocs/powerbi-docs#2229]
Why and when was Power BI Publisher for Excel removed?

So, now we have to go to Power BI, pick our report or dataset and then click menu item to Analyse in excel before we can connect excel to a  Power BI Dataset.  Not Great!!!  
We are currently using Excel 2016 and this change has a negative impact to our business.

This was much better when we were able to install Power BI Publisher for Excel and then in Excel we had the Power BI Ribbon and were able to easily connect to Power BI Datasets.

Will this feature come back??????

**Comment by KesemSharabi** [comment]
Thanks for your comment @GMAU01,

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).
