### ISSUE TITLE
'Power BI Premium Capacity Metrics' fails to install: 'There weren't enough elements in the enumeration...'

### ISSUE THREAD

**Issue by fishnexj** [MicrosoftDocs/powerbi-docs#223]
I am a Premium Capacity admin and a Power BI Service Admin. When I try to install the App, I get the following error.

`
We couldn't install Power BI Premium Capacity Metrics
There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Message: There weren't enough elements in the enumeration to complete the operation. Table: DQLCMetrics.
Activity ID: 477ca2a0-baae-4ed9-86a3-925a6d33c6ed
Correlation ID: b02fa112-b599-bcd0-1286-41ddaa6b844f
Request ID: 9cd51261-7ba6-81af-452c-9e6f9b70db97
Status code: 400
Time: Sat Sep 01 2018 02:55:21 GMT+0800 (Singapore Standard Time)
Version: 13.0.6517.123
Cluster URI: https://wabi-us-north-central-redirect.analysis.windows.net
`

Is there additional access I am missing? Or is this a data model bug? Something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by fishnexj** [comment]
It appears to be a more general error with the HTTPS calls, because now Table: MemoryMetrics is causing the same error when I attempt to install.

**Comment by fishnexj** [comment]
The issue turned out to be a Embedded node I had spun up in our Azure environment. It did not have the Power BI Service or Power BI Premium or Power BI as Readers in its IAM settings. Once we added those, the App worked fine!

**Comment by nusairi** [comment]
Thanks removing of embedded node done the job
