### ISSUE TITLE
Power bi .json Custom Theme - Revert visuals to default

### ISSUE THREAD

**Issue by elcu** [MicrosoftDocs/powerbi-docs#2230]
Hello, 

when you create your own theme in .json and they apply it to an already existing visuals, they do not get changed to the new style. You need to go to each of the visual's format tab, and manually click on the "revert to defaults" button. Then, the new theme and settings gets applied to the category. You need to do this for every category (10 to 20 of categories for each visual)

<img width="131" alt="revert" src="https://user-images.githubusercontent.com/65713198/83027157-13d7b700-a030-11ea-84c6-de28e2b7345a.png">

Is there a possibility to add some line of code into the .json which resets all of the visuals into this default mode? Smthg like this (or smthg applicable on the global level):

```
"categoryAxis": [
          {
            "show": true,
            "position": "Left",
            "revert to defaults": true
          }
                        ]
```

Thank you :)

**Comment by KesemSharabi** [comment]
Thanks for your comment, @elcu.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by elcu** [comment]
Hello @uve,

just to specify what I am looking for: 
[https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#situations-when-report-theme-colors-wont-stick-to-your-reports](url)

Situations when report theme colors won't stick to your reports

When you change something in the visual then your imported theme doesn't override this changed setting in the visual. It overwrites only clean/non-changed visuals.

I would like to insert a code into the json which resets the visual to its defaults.

**Comment by maggiesMSFT** [comment]
Hi, @elcu -- not sure why your link isn't working. You're referring to this article, right? https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#report-theme-json-file-format
Assigning to the author for consideration.

**Comment by elcu** [comment]
Yes @maggiesMSFT , I am referring to that article. There is a special section in it "Situations when report theme colors won't stick to your reports". You need to manually click on that "revert to default" button now, but I would like to implement it into the .json file.

**Comment by woodyj13** [comment]
@elcu Did you ever find a solution for this? I'm having the same problem.

**Comment by elcu** [comment]
Hi @woodyj13, nope no solution so far :/

pi 11. 9. 2020 o 5:57 woodyj13 <notifications@github.com> napísal(a):

**Comment by elcu** [comment]
@maggiesMSFT Hello Maggie, any update on this please? Thank you

**Comment by rikesh-neelakantan-jdas** [comment]
Hi, is there a solution to revert all visuals to default?

**Comment by woodyj13** [comment]
@rikesh-neelakantan-jdas not that I know of. Would really be helpful though.

**Comment by rafaelsmoreno** [comment]
Any update on that one? This feature would really make a difference. 

It should, however, be a button in PBI GUI (revert all visuals to default), or an option when changing the theme (e.g.: override manual configurations on all visuals).

**Comment by woodyj13** [comment]
I never solved this either. My project for a company default .json theme is "on hold" until I find a way to revert everything to default in the code.

> Any update on that one? This feature would really make a difference.
> 
> It should, however, be a button in PBI GUI (revert all visuals to default), or an option when changing the theme (e.g.: override manual configurations on all visuals).

**Comment by mihart** [comment]
Hi @elcu @woodyj13, @rafaelsmoreno ,
I've searched the Community forum and the ideas.powerbi.com website, and see that this question/idea has been posted by several users. I am unaware of a solution.  However, the more votes an Idea gets, the more likely it will catch the product team's attention.  Here's a link to the Idea that seems to best match: https://ideas.powerbi.com/ideas/idea/?ideaid=83137c9d-277f-4249-97f7-431cd98409dc.
All the best,
the DOCS team
