### ISSUE TITLE
COVID-19 Dashboard Add Moving Average Trendline to Bar Charts

### ISSUE THREAD

**Issue by harrisgr18** [MicrosoftDocs/powerbi-docs#2231]
We love this dashboard but we would like to add a 3 or 4 day moving average line to the two bar charts to even out the spikes in the data.  What would the formula need to be in order to accomplish this?

**Comment by maggiesMSFT** [comment]
Hi, @harrisgr18 -- I'm glad to hear you like it! I'm not sure which one you're referring to.  There are two. This one is the report itself: https://docs.microsoft.com/en-us/power-bi/create-reports/sample-covid-19-us
This one is the template app:
https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-covid-19-tracking
If you install the template app, you can modify the report yourself, and then distribute it. Does that help?
If not, you'll need to submit an idea on the Power BI Ideas page, https://ideas.powerbi.com/forums/265200-power-bi.
