### ISSUE TITLE
Direct Query is now supported

### ISSUE THREAD

**Issue by olthomps** [MicrosoftDocs/powerbi-docs#2232]
Direct Query is now supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by maggiesMSFT** [comment]
Hi, @olthomps -- thanks for your comment! Assigning to the author to make the update.

**Comment by mihart** [comment]
Hi @olthomps ,
Thank you for your suggestion.  We did update the article to remove the DirectQuery limitation.  And I realize that we never updated your Git Issue to let you know. We really appreciate your input!
All the best,
the DOCS team
