### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RoseAmS** [MicrosoftDocs/powerbi-docs#2233]
Hi!

"Plan capacity for embedded analytics with Power BI Premium" link is not working.
Could you fix it?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b427b153-9627-17f6-5a01-0b7009394944
* Version Independent ID: b5434461-32a3-8c8d-6faa-fe3144718784
* Content: [Whitepapers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepapers#feedback)
* Content Source: [powerbi-docs/guidance/whitepapers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/whitepapers.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @RoseAmS -- I don't see the link you're referring to on this page, https://docs.microsoft.com/en-us/power-bi/guidance/whitepapers#feedback. 
Can you point me to it? Thanks!

**Comment by RoseAmS** [comment]
Hi @maggiesMSFT !

Seems like that whitepaper was deprecated (I'm seeing page's last edit was yesterday), couldn't find it either.
Thanks anyway!

**Comment by maggiesMSFT** [comment]
Thanks, @RoseAmS. What timing! Closing this issue.
