### ISSUE TITLE
Power BI Embedded support (A SKUs)

### ISSUE THREAD

**Issue by atlaspolicy** [MicrosoftDocs/powerbi-docs#2234]
I'm trying to understand the extent to which the enhanced compute engine and direct queries are supported in the Power BI Embedded (A SKUs). It's not documented here and it's not available on the back end. The Enhanced Compute Engine is not available on an A2 capacity I'm using but the icons for the relevant queries implies it is being used. Please help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4696f74d-bce4-3808-008a-4375afdb71c5
* Version Independent ID: 339f52a6-9d08-4634-76f4-5195c3b475ec
* Content: [Use DirectQuery with dataflows in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-directquery)
* Content Source: [powerbi-docs/transform-model/service-dataflows-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @atlaspolicy -- thanks for asking! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @atlaspolicy ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by atlaspolicy** [comment]
No one replied to this message, unfortunately, so the question is still open.
