### ISSUE TITLE
PBI doesn't look like what you put here

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2235]
@RowlinAPsychologist commented on [Tue May 26 2020](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/70)

I tried to find the copy button (and the all the following functions) in the latest Desktop version and Web version. But I couldn't! Which version was this instruction referring to? How can I copy a chart in the lastest PBI?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [在 Power BI 中复制并粘贴可视化效果 - Power BI](https://docs.microsoft.com/zh-cn/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/blob/live/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

---

@srvbpigh commented on [Tue May 26 2020](https://github.com/MicrosoftDocs/powerbi-docs.zh-cn/issues/70#issuecomment-633977333)

Hello, @RowlinAPsychologist
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @RowlinAPsychologist and @CeciAc -- Yes, items on the ribbon have moves, with the newest version of Power BI Desktop. Assigning to the author to update the article. 
In the meantime: The ribbon does collapse. Maybe that's why you're not seeing all the options? Select the arrow at the far right to expand it. Hope that helps!

**Comment by RowlinAPsychologist** [comment]
> Hi, @RowlinAPsychologist and @CeciAc -- Yes, items on the ribbon have moves, with the newest version of Power BI Desktop. Assigning to the author to update the article.
> In the meantime: The ribbon does collapse. Maybe that's why you're not seeing all the options? Select the arrow at the far right to expand it. Hope that helps!

Thanks for the reply. But sorry, the guess is not valid.
I saw many users wish to copy the visual elements to Microsoft Office, like what we do to Excel charts. In many cases, we just want to embed charts in a document in case its receivers don't have access to internet or PBI desktop. Now the sharing problem is greatly undermining PBI's application.

**Comment by mihart** [comment]
Hi @RowlinAPsychologist and @CeciAc 
I've passed along your comment to the author.  But let me try to help too.  
1. Are you attempting to copy a visual from Power BI Desktop or from the Power BI service?
2. Are you attempting to copy a visual from a dashboard or from a report?
3. Are you using keyboard shortcuts or the icon (the one that looks like 2 pieces of paper)?
Thanks,
Michele

**Comment by msftrien** [comment]
Hi, I could be missing some of the context, but there are several different ways to copy things in Power BI, so I’d like to know the answers to those questions too. In the Service, for example, there is a button: [cid:image001.png@01D66C1B.706BD440]
that allows you to copy visual as image (which I believe Michele is alluding to with her third question). Is that what you’re looking for?

Rien

**Comment by mihart** [comment]
Hi @CeciAc ,
I've updated the article and it should go live today or tomorrow.  Thank you for your help with the documentation.
