### ISSUE TITLE
Publish overwrites data acquired via Incremental Refresh

### ISSUE THREAD

**Issue by fordmaxson** [MicrosoftDocs/powerbi-docs#2236]
The last part of this document explains that publishing a modified report from desktop can overwrite all the accumulated data acquire via incremental refresh.  I am trying to make use of the mentioned ALM toolkit and am corresponding with the team writing it, but currently it is clunky and does not appear to identify model vs data changes.

I believe it is critical that Microsoft make the Publish function smarter and give the user an option to publish the report changes minus the data overwrite.  I am stuck delivering what my customers need until such time.

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/admin/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- Thanks for your comment! It sounds like a product issue rather than a documentation issue. Please visit the Power BI Ideas page, https://ideas.powerbi.com/forums/265200-power-bi, to provide feedback

**Comment by fordmaxson** [comment]
Maggie,
Your document states...
"In some cases you may not want to replace the dataset, especially with incremental refresh. The dataset in Power BI Desktop could be much smaller than the one in the service. If the dataset in the service has an incremental refresh policy applied, it may have several years of historical data that will be lost if the dataset is replaced. Refreshing all the historical data could take hours and result in system downtime for users.

Instead, it's better to perform a metadata-only deployment. This allows deployment of new objects without losing the historical data. For example, if you have added a few measures, you can deploy only the new measures without needing to refresh the data, saving a lot of time.

When configured for read-write, the XMLA endpoint provides compatibility with tools that make this happen. For example, the ALM Toolkit is a schema diff tool for Power BI datasets and can be used to perform deployment of metadata only."

I have been in communication with Christian Wade from ALM Toolkit (https://github.com/microsoft/Analysis-Services/issues/58)
and he has confirmed that teh ALM Toolkit can only adjust what data is sent up, it has no ability to send report info (Charts/Measures) instead of datasets.

That makes your documentation look wrong and leaves me unsure how to use Incremental Refresh without overwriting years of data on the service.

Let me know if you have and option for my issue. Thanks

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- thanks for clarifying! I've reopened the issue and assigned it to the author for consideration.

**Comment by davidiseminger** [comment]
Looks like these changes have already been made to the documentation. Closing, as a result.
