### ISSUE TITLE
This new feature has created a bug

### ISSUE THREAD

**Issue by skiwii** [MicrosoftDocs/powerbi-docs#2237]
See the following page for the issue
https://community.powerbi.com/t5/Desktop/Failed-to-save-modifications-to-the-server-when-calling-API/td-p/990136/

I have the issue when I apply a custom function to a table that returns data (more rows). It works fine in PowerQuery but when you Apply this you get the error:
"Failed to save modifications to the server. Error returned: 'Expression in partition 'n/a' in table 'n/a' references an unknown entity."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-gb/power-bi/connect-data/desktop-enhanced-dataset-metadata)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @skiwii -- Thanks for asking! This sounds like a product issue rather than a documentation issue. You've done the right thing by posting in the Community site. The next step is probably a support request. https://powerbi.microsoft.com/en-us/support/
Hope that helps!
