### ISSUE TITLE
Heading "Unlimited content sharing" has incorrect information. 

### ISSUE THREAD

**Issue by emilylait** [MicrosoftDocs/powerbi-docs#2238]
The heading Unlimited content sharing has incorrect information. It implies that ALL premium SKUs allow unlimited content sharing with user free licenses.  It says (With Premium, anyone, whether they're inside or outside your organization can view your Power BI content including paginated and interactive reports without purchasing individual licenses.)
This is now incorrect with the newer EM premium SKUs! In this other Power BI Docs (https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#capacity-and-skus) it clearly states 'Only the P SKU allows free Power BI users to consume Power BI apps and shared content, in Power BI service.'.
Can this information be updated please? It implies that any Premium SKU has this capability but that is incorrect. Only the P premium SKUs allow this, and EM premium SKUs do not.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#unlimited-content-sharing)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your question, @emilylait ! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @emilylait , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
