### ISSUE TITLE
User license required for report publishers

### ISSUE THREAD

**Issue by MichaelAdrianJohnson** [MicrosoftDocs/powerbi-docs#2239]
There is no mention of the licensing requirement for report publishers on this page (and I could not find it anywhere else.)

The only guidance I could find was at the bottom of the pricing page in a footnote.
https://powerbi.microsoft.com/en-us/pricing/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc8bae8-be5d-ce63-6196-4c2e2f2d6779
* Version Independent ID: 2e836aec-a8a7-41fe-f562-c6c435e441ee
* Content: [What is Power BI Report Server? - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/get-started)
* Content Source: [powerbi-docs/report-server/get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MichaelAdrianJohnson -- thanks, great point! I've added it in the Licensing section. The change will be live tomorrow.
