### ISSUE TITLE
PowerBI Desktop ignored 

### ISSUE THREAD

**Issue by tomlaciano** [MicrosoftDocs/powerbi-docs#224]
This topic is an introduction to PowerBI but the bulk of the examples are about the PowerBI service but the explanation of PowerBI desktop is being a common starting point that creates reports that are then published to PowerBI Service. This module should have covered PowerBI Desktop getting source data, creating a report and publishing to PowerBI Service and then it should cover PowerBI Service using a connector. It should have finished by showing the PowerBI Mobile solution pulling the data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Getting started - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, @tomlaciano. You may be interested in the recently release Learn portal, which includes a tutorial on Power BI Desktop. See it here: https://docs.microsoft.com/learn/modules/get-started-with-power-bi/
