### ISSUE TITLE
AAS not supported with PowerBI Gateway 

### ISSUE THREAD

**Issue by adamwp1993** [MicrosoftDocs/powerbi-docs#2240]
There is no overlap in authentication mechanisms with AAS and the PowerBI gateway

Please reach out and i can direct to an incident number with the statements from engineering group. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@adamwp1993 - thanks for helping to keep the content up to date. Please provide the suggested update, as I'm unsure of what change needs to be made based on your feedback.

**Comment by kfollis** [comment]
change made and published to live
