### ISSUE TITLE
How to filter when import fails

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/powerbi-docs#2241]
[Enter feedback here]
Please add instructions for what to do if the pwa import fails because it is too big

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc8a7a22-e258-4da3-4c55-6ddb1085c521
* Version Independent ID: 0b3f2b88-9e73-f4dd-0f21-fe3c156a99b8
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-project-online)
* Content Source: [powerbi-docs/connect-data/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-connect-to-project-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by kfollis** [comment]
Hi @gkens - I'm adding the author to review and possibly add troubleshooting steps. If you need immediate help, please try the Power BI Community (https://community.powerbi.com) or support (https://support.powerbi.com).

**Comment by mihart** [comment]
Hi @gkens ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by gkens** [comment]
No I never received an answer


Glenn Kime
Principal
Enspired IT of Ann Arbor
Voice: 734-228-7077<tel:734-228-7070>

Fax:  734 219-5469<tel:734%20219-5469>

***@***.******@***.***>

www.enspireditaa.com<http://www.enspireditaa.com/>

[A close up of a logo  Description automatically generated]

________________________________
