### ISSUE TITLE
Standalone Text Tile can't be edited once added

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerbi-docs#2244]
The documentation should note that Standalone Text Tiles created directly by using the Add Tile control can't be edited.
Even better would be to fix the bug that prevents editing previously added Text Tiles.
Issue recorded in [Issues Log](https://community.powerbi.com/t5/Issues/Bug-Dashboard-Text-Box-Drops-Text-on-Edit/idi-p/1117945).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88b71635-b53c-d810-b40a-8c67ae1edba0
* Version Independent ID: 8de35da5-401a-7834-11de-7f4e8af35ca9
* Content: [Intro to dashboard tiles for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-tiles)
* Content Source: [powerbi-docs/create-reports/service-dashboard-tiles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-dashboard-tiles.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
@HairyDrumroll - got this twice, so closing the duplicate issue.
