### ISSUE TITLE
Standalone Text Tile can't be edited once added

### ISSUE THREAD

**Issue by HairyDrumroll** [MicrosoftDocs/powerbi-docs#2245]
The documentation should note that Standalone Text Tiles created directly by using the Add Tile control can't be edited.
Even better would be to fix the bug that prevents editing previously added Text Tiles.
Issue recorded in [Issues Log](https://community.powerbi.com/t5/Issues/Bug-Dashboard-Text-Box-Drops-Text-on-Edit/idi-p/1117945).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f30eb2-e55e-635d-e161-6c26f20fac2d
* Version Independent ID: 7d1fd996-9981-a844-0f2b-abb35cf21b7f
* Content: [Add images, videos, and more to your dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-add-widget)
* Content Source: [powerbi-docs/create-reports/service-dashboard-add-widget.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-dashboard-add-widget.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Hi @HairyDrumroll - thanks for the feedback. I'm assigning this issue to the author to review.

**Comment by HairyDrumroll** [comment]
The page [Intro to dashboard tiles for Power BI designers](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-tiles) should also have documentation updated - or the bug should be fixed which would be even better!

**Comment by maggiesMSFT** [comment]
Hi, @HairyDrumroll -- I'm not sure what you're seeing. You can indeed edit a standalone text tile after you add it. Here's how, later in that same article: https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-add-widget#edit-a-tile.
Thanks!

**Comment by HairyDrumroll** [comment]
Hi @maggiesMSFT, did you try it? Didn't work for me and someone has logged a [bug in the issues list](https://community.powerbi.com/t5/Issues/Bug-Dashboard-Text-Box-Drops-Text-on-Edit/idi-p/1117945) as well.

**Comment by HairyDrumroll** [comment]
Seems to be fixed now!
I swear it wasn't working on Friday!!

**Comment by maggiesMSFT** [comment]
Well, I'm glad it's working now anyway! Thanks for letting me know.
