### ISSUE TITLE
"Power BI Datasets" is missing from the Get Data -> Power Platform options

### ISSUE THREAD

**Issue by fordmaxson** [MicrosoftDocs/powerbi-docs#2246]
Can the article tell me what to do if "Power BI Datasets" is missing from the Get Data -> Power Platform options?

Does "Admin portal -> Tenant Settings -> Certification" have to be turned on before it shows?
Anything else?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets#limitations-and-considerations)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @fordmaxson -- yes, "Admin portal -> Tenant Settings -> Certification" does have to be turned on. See https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-admin-across-workspaces for more info.
Thanks!
