### ISSUE TITLE
Azure Consumption Insights RIUsage issue

### ISSUE THREAD

**Issue by lakeyeric22** [MicrosoftDocs/powerbi-docs#2247]
I am using Azure Consumptions Insights API to get RIUsage data.  This has been working great for a few months, but starting on 5/27 the TotalReservedQuantity field is always zero for all records.  I've attempted refreshing the data multiple times on multiple days.  I opened a ticket with Microsoft support on Wednesday and they have been no help at all.  Even stood me up on a meeting they scheduled with me yesterday.  Is anyone else experiencing this issue?

**Comment by maggiesMSFT** [comment]
Hi, @lakeyeric22 -- assigning to someone who may be able to answer your question.

**Comment by maggiesMSFT** [comment]
Referring to this article, right?
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-consumption-insights

**Comment by lakeyeric22** [comment]
@maggiesMSFT - yes that is the document.  Thanks!

**Comment by mihart** [comment]
Hi @lakeyeric22 ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
