### ISSUE TITLE
Clarify which capacities for which enhanced compute engine can be enabled.

### ISSUE THREAD

**Issue by unt1tled** [MicrosoftDocs/powerbi-docs#2248]
I discovered after much research that enhanced compute engine can not be enabled on A1-A2 Power BI capacities. It does work on A3 and above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 369c84b0-97ef-a750-86cd-5330626c75ac
* Version Independent ID: 3af79c25-1e82-ab08-7604-bfaa9ace6128
* Content: [Use the enhanced compute engine with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-enhanced-compute-engine)
* Content Source: [powerbi-docs/transform-model/service-dataflows-enhanced-compute-engine.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-enhanced-compute-engine.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your investigation @unt1tled and for sharing here. I've added a note so others can benefit, too. Thanks!
