### ISSUE TITLE
Ambiguous recommendation

### ISSUE THREAD

**Issue by bilukjak** [MicrosoftDocs/powerbi-docs#2250]
This [Section](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-best-practices#create-a-separate-workspace-for-ingestion-transformation) recommendation is ambiguous. What does "that has all the data you need" mean in that context? Linked entities are not allowed in that scenario? It seems that if I create a workspace for ingestion and second for transformation (with linked dataflow) I need to assign permissions for both workspaces. Otherwise users will not see the data from the first one (ingestion). So if I need to assign appropriate permissions for both workspaces what is the meaning of that recommendation? I understand that it make sense to split because of enhanced compute engine, but what is the sense of splitting for access layer if users have to possess rights to both workspaces?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd16a9c-3620-e1c6-518a-d6a5f9174089
* Version Independent ID: c55ccf5a-5563-1a05-7cec-46666a9e8f08
* Content: [Best practices for Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-best-practices)
* Content Source: [powerbi-docs/transform-model/service-dataflows-best-practices.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-best-practices.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @mohaali
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @bilukjak , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team

**Comment by mihart** [comment]
Hi @bilukjak 
The PM wanted to pass along this info: 
We provide some flexibility to segregate data to enable use cases where raw data can be prepped, transformed, and shared across workspaces either including access to to that raw data or just to the prepped /transformed layers. In this scenario folks who have the right access to earlier stages of data can preserve control and add data they have access to .
Thanks again for your input,
the DOCS team
