### ISSUE TITLE
Admin can Update and delete the workspace.

### ISSUE THREAD

**Issue by artsheiko** [MicrosoftDocs/powerbi-docs#2251]
Admin can Update and delete the workspace. This is not marked in a en-us page version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @artsheiko -- thanks for asking! I'm checking on this. I see that admins can edit details, but not that they can delete.

**Comment by maggiesMSFT** [comment]
Ha! I figured it out. I'll add it to the article. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @artsheiko -- 
I mentioned it in this article, then explained it in the Admin Portal article, https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#workspaces
Changes will be live next Mon Aug 10.
Thanks!
