### ISSUE TITLE
Connect to the facebook

### ISSUE THREAD

**Issue by BlendMW** [MicrosoftDocs/powerbi-docs#2253]
[The Facebook select doesn't exist in the Get Data dialog box]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Analyze Facebook data by using Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-facebook-analytics)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by BlendMW** [comment]
![image](https://user-images.githubusercontent.com/64715707/83488463-8e338b80-a4b5-11ea-813f-c5d19aef0af0.png)

**Comment by mihart** [comment]
Thanks for your comment, @BlendMW . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @BlendMW ,
This article has been updated to explain the connection issue with Facebook. 
_Due to Facebook App permission restrictions, the connector capabilities described in this article are not currently working properly. We’re working with Facebook to return this functionality as soon as possible_.
All the best,
the DOCS team
