### ISSUE TITLE
Real-time refresh- not working / more clarity needed on troubleshooting

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/powerbi-docs#2254]
From the doc:

> Once a report is created using the push dataset, any of its visuals can be pinned to a dashboard. **On that dashboard, visuals update in real-time whenever the data is updated. Within the service, the dashboard is triggering a tile refresh every time new data is received.**

and later ...

> Once a visual is pinned to a dashboard, you can use Q&A to ask questions of the push dataset in natural language. **Once you make a Q&A query, you can pin the resulting visual back to the dashboard, and that dashboard will also update in real-time.**

Can someone verify if this scenario is true for PowerBI Pro users?

I've created a push dataset using the API, created and pinned simple report visuals, created and pinned Q&A visuals - when I manually refresh I can see the new data I'm pushing in, but the dashboard never automatically refreshes - you can see there's no underlying activity at all from the browser.

It looks like it makes a call to powerbi/metadata/refresh/subscribe, which fails most of the time after a 60 second timeout (status "cancelled") ..

![image](https://user-images.githubusercontent.com/625949/83481348-218fa100-a463-11ea-8eef-096c0db09105.png)

But even on the rare instances where this successfully returns something (some JSON about a transactionID, a changeSourceID, a changeType - so looks like this is the change watcher for a push dataset ..?),  nothing ever actually refreshes.

Really hard to debug since absolutely no front end guidance is given around which tiles will refresh automatically, etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming)
* Content Source: [powerbi-docs/connect-data/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @kthejoker . This issue has been assigned to the doc author for review.

**Comment by kthejoker** [comment]
This was confirmed to  be a bug in the Power BI service and has since been resolved, thank you, no further action needed
