### ISSUE TITLE
Does this work with SSAS live connections?

### ISSUE THREAD

**Issue by bradj813** [MicrosoftDocs/powerbi-docs#2256]
I've read it does NOT work with SSAS live connections yet:
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/38683240-implement-rls-on-paginated-reports-using-ssas-tabu

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 561fba06-3092-f009-343e-b37f133bee44
* Version Independent ID: e0d74c12-1a25-18ba-e511-49466055cb98
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/paginated-reports-row-level-security)
* Content Source: [powerbi-docs/developer/embedded/paginated-reports-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/paginated-reports-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @bradj813 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @bradj813,

The information in the [Implementing row-level security in embedded paginated reports](https://docs.microsoft.com/power-bi/developer/embedded/paginated-reports-row-level-security) article should be up-to-date. Did you see SASS mentioned in this article?

Thanks,

Kesem

**Comment by bradj813** [comment]
No SASS mentioned, I’m sure you saw the same? If not mentioned, how do I know if it would work with SASS? 

Thanks

**Comment by KesemSharabi** [comment]
Hi @bradj813,

As SASS isn't mentioned in the limitations, it should work. If you need help with the configuration, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
