### ISSUE TITLE
Changing the SSAS live connection server

### ISSUE THREAD

**Issue by jdbuchanan** [MicrosoftDocs/powerbi-docs#2257]
The way you change the connection properties is different in newer versions of PowerBI desktop.
File > Options and settings > Date source settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4defd9-aeac-2135-1310-332bfe227342
* Version Independent ID: c68cb581-46fc-5b74-aff1-8a69dbf433dc
* Content: [Connect to Analysis Services tabular data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-analysis-services-tabular-data#feedback)
* Content Source: [powerbi-docs/connect-data/desktop-analysis-services-tabular-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-analysis-services-tabular-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jdbuchanan . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @jdbuchanan , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
