### ISSUE TITLE
Sharing externally is indeed possible from GCC to commercial tenants

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2258]
In considerations and limitations section, it is mentioned that, "Sharing outside your organization isn't supported national clouds. Instead, create user accounts in your organization that external users can use to access the content."

However, we tested and it is indeed supported. Please confirm from PG and update the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b#guest-users-who-can-edit-and-manage-content)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks, @haider392! I'll verify with the PG and get an update in soon.

**Comment by kfollis** [comment]
Hi @haider392 - I'm making the update now and you'll see the change live soon. To clarify, yes, external sharing is now available from government to commercial clouds. However, the functionality is not available in regional clouds, such as Germany and China. Thanks!
