### ISSUE TITLE
Connect a ADLS Gen2 with Firewall enabled to PowerBI

### ISSUE THREAD

**Issue by pnarsi** [MicrosoftDocs/powerbi-docs#2260]
For this ADLS Gen2 to Power BI integration for dataflow storage, can we use a Storage account with a firewall enabled?

Power BI is not listed as a supported Trusted Microsoft Service for Azure Storage https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security so I assume we need to either turn the firewall for the Storage Account off or whitelist a range of IP addresses used by Power BI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @pnarsi.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by DaveRuijter** [comment]
Any news on this issue: "can we use a Storage account with a firewall enabled?"
Answer is "no" for my current understanding.
Would be great if the product team knows about this and hopefully they can unlock this impediment!

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.

**Comment by DaveRuijter** [comment]
Hi @davidiseminger, this issue is not solved in the updated documentation.
