### ISSUE TITLE
Broken hyperlinking after  "Manage items you own"

### ISSUE THREAD

**Issue by milesgratz** [MicrosoftDocs/powerbi-docs#2262]
Content after "Manage items you own" header is showing up as a single hyperlink.

![image](https://user-images.githubusercontent.com/17114534/83661440-c3121200-a58b-11ea-9745-ccbe91069ca9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi#dataset-limits)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks, @milesgratz! This is assigned to the author and we'll get this updated quickly.

**Comment by maggiesMSFT** [comment]
Thanks so much, @milesgratz ! The article is fixed now.
