### ISSUE TITLE
Messed up formatting

### ISSUE THREAD

**Issue by nadjaklein** [MicrosoftDocs/powerbi-docs#2264]
Hi there,
the formatting on the lower part of the documentation is a bit messed up. Everything appears to be a hyperlink. Just wanted to highlight this in case you haven't realized that yet.
Cheers,
Nadja

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks, @nadjaklein! I'm assigning to the writer to make the correction.

**Comment by maggiesMSFT** [comment]
Thanks so much, @nadjaklein ! It's fixed now.
