### ISSUE TITLE
Where are the data sets for the tutorials in this page?

### ISSUE THREAD

**Issue by pdileepan** [MicrosoftDocs/powerbi-docs#2265]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the comment, @pdileepan. I'm assigning the issue to author to provide clarification.

**Comment by mihart** [comment]
Hi @pdileepan ,
Thank you for your question. 
Most of the sample data came from https://www.data.gov/.
All the best,
the DOCS team
