### ISSUE TITLE
Limitations link is broken

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/powerbi-docs#2266]
Link under Limitations is broken. Page was probably moved:

Limitations and considerations
For troubleshooting information, see Power Apps visual for Power BI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95396f22-677a-eb3c-bd1c-10344fe0ae70
* Version Independent ID: 1d471f6e-b3d8-e04e-d4c1-5353982e5c75
* Content: [Embed a new Power App in a Power BI Report - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-powerapp)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-powerapp.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-powerapp.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by kfollis** [comment]
Thanks, @martaequintao! I have made the correction and the change will be live later today.
