### ISSUE TITLE
Funny Dates

### ISSUE THREAD

**Issue by atalaycelebi** [MicrosoftDocs/powerbi-docs#2268]
Am I wrong or you guys are creating the RangeStart and RangeEnd as constant values. Arent they supposed to be dynamic values?
The post shows up as from 10 days ago but all the data are from 2012 and the data as R;ange start is also 2012.
If it is constant what is the significance of the date that we are creating this whole thing. 
Btw I forgot to say, I did and it didnt work.

Hoenstly, It seemed to me that you guys just skip the ciritical parts:(((

**Comment by kfollis** [comment]
Hi @atalaycelebi - I'm not sure what you're referring to. Is your comment for a specific article? Can you provide the link if so?

**Comment by kfollis** [comment]
Not enough info to address. Please submit new feedback and be sure to include the URL for the article you're referencing if this is still a problem. Thanks for taking the time to submit feedback.
