### ISSUE TITLE
This is typo issue in the documentation

### ISSUE THREAD

**Issue by AkhilMadivada** [MicrosoftDocs/powerbi-docs#2269]
As per the documentation explanation, the "AccountID **3** is associated with CustomerID 92" has to be changed to 
"AccountID **2** is associated with CustomerID 92"
![image](https://user-images.githubusercontent.com/32743267/83955542-c36b1100-a808-11ea-9bb1-4787f822012f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 864a3cfe-f1fb-342a-cf76-9603a81e64f9
* Version Independent ID: 59891c79-e71c-96e4-79ad-58853c6b9f0d
* Content: [Many-to-many relationship guidance - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/relationships-many-to-many)
* Content Source: [powerbi-docs/guidance/relationships-many-to-many.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/relationships-many-to-many.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by peter-myers** [comment]
Hi @AkhilMadivada - thanks for reporting this bug. The article has been fixed and an updated article - with correct values - will be available soon.
#please-close
