### ISSUE TITLE
Capacity Tiers Chart Wrong?

### ISSUE THREAD

**Issue by chadgr** [MicrosoftDocs/powerbi-docs#227]
Why does the capacity tiers chart show that shared does not support apps / sharing, it does for Pro users.  Also you can use the same rest API's for shared as Premium, why is there an X for Embedded API and controls.  They both seem wrong to me.  Please clarify exactly what those rows mean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [Power BI Premium - what is it? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
We removed the table during the rewrite for this article.
