### ISSUE TITLE
The required permission to manage scheduled refresh. 

### ISSUE THREAD

**Issue by Maggie18z** [MicrosoftDocs/powerbi-docs#2272]
Need some clarification on the required permission / role to manage schedule refresh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2a19e-3613-9ec0-8818-8f76d3c7eef9
* Version Independent ID: 0b8ebf11-af44-2556-db7c-766d5f844c98
* Content: [How to configure Power BI report scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/configure-scheduled-refresh)
* Content Source: [powerbi-docs/report-server/configure-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/configure-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by Maggie18z** [comment]
Thanks for your email.
Yes we need clarification on the required permission/role to create/edit/execute scheduled refresh.

Best Regards,
Maggie Zhang

**Comment by mihart** [comment]
Hi @Maggie18z , 
Thank you for your suggestion.  I notice that this is an older Git Issue and the article you reference has been updated.  A link has been added to an article that has role definitions, which is where the perms are defined for refresh.  Please take a look, and let me know if you still have questions. 
All the best,
The DOCS team
