### ISSUE TITLE
Power BI Premium capacity there is no Montly Commitment

### ISSUE THREAD

**Issue by mchoure** [MicrosoftDocs/powerbi-docs#2273]
[For Capacity Consideration table: https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity?source=docs#capacity-considerations
Power BI Premium capacity there is no Monthly Commitment as per our following comments from O365 Admin 
"This is not just for power bi premium capacities. Microsoft list prices for all Office 365 products on per month cost but you can’t purchase any licensing per month. Power BI costs $xx per user per month but you can’t buy it like that. It is the same method as described below and same for any other O365 product…."]
Request: Remove Monthly from Power BI Premium>P/SKU>Commitment
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @mchoure,

I'm looking into this issue and will update you as soon as I have an answer.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @mchoure, 

Thank you for your suggestion. I checked with our marketing team and the information in the [Capacity considerations](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity#capacity-considerations) table is correct.

I also double checked this in the portal.

![How Premium Power BI SKUs are billed](https://user-images.githubusercontent.com/54834915/87039908-896e9f80-c1f8-11ea-876c-d52387ca867a.png)

For more information, see [Purchase a Power BI Premium capacity for an existing organization](https://docs.microsoft.com/power-bi/admin/service-admin-premium-purchase#purchase-a-power-bi-premium-capacity-for-an-existing-organization).

Thanks,

Kesem
