### ISSUE TITLE
PBIRS May 2020

### ISSUE THREAD

**Issue by josef78** [MicrosoftDocs/powerbi-docs#2274]
PBI Report Server May 2020 update have critical issue related to refresh data (not working in all cases, e.g. https://community.powerbi.com/t5/Report-Server/PBI-Server-May-2020-not-refreshing-saved-reports/m-p/1135485 ), please remove download links to this version until new version will be published. Thx

**Comment by maggiesMSFT** [comment]
Hi, @josef78 -- Thanks for your comment! This is a known issue. A fix is in the works and should be out soon.
