### ISSUE TITLE
Page outdated - needs to be updated with new instructions and screenshots

### ISSUE THREAD

**Issue by Ascyron** [MicrosoftDocs/powerbi-docs#2276]
The section "Sort using the Sort by Column button" on this page is outdated and confusing - the options described aren't found in those menus any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @Ascyron , 
Thank you for your feedback.  We've made the update and set the article to republish. 
All the best,
The DOCS team
