### ISSUE TITLE
Steps to create phone (vertical layout) in PBI Service needed

### ISSUE THREAD

**Issue by alwweb** [MicrosoftDocs/powerbi-docs#2279]
The title leads us to believe that for reports, we can adjust and optimize for phone (vertical) layout in the service, but the directions only specify how to do this in the desktop app.  Can reports be optimized post deployment to the service, or is it only dashboard that can be optimized post deployment.

If phone view can only be defined for Reports in Desktop, the intro paragraph should be more clear.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f3739d4-b66c-1e13-4c4a-35990764216c
* Version Independent ID: 7c8e7cf4-4778-8871-bad0-452bb2edb36c
* Content: [Optimize reports for the Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-create-phone-report)
* Content Source: [powerbi-docs/create-reports/desktop-create-phone-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-create-phone-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Great feedback, @alwweb ! Yes, you can create a mobile layout for reports and dashboards in the Power BI service. I'll make that clearer in the article. Thanks!

**Comment by paulinbar** [comment]
Hi @alwweb , I've taken your suggestion and made a few changes to the article that I hope make it more clear that the mobile layout view is available in both Power BI Desktop and the Power BI service. The changes will go online soon.
Thanks for your input!
