### ISSUE TITLE
50 page per hour limitation

### ISSUE THREAD

**Issue by andrewpmk** [MicrosoftDocs/powerbi-docs#2280]
When is the 50 page per hour limitation going to be removed?

Our company is currently developing a web portal which uses the Power BI API to export Power BI reports to PDF/PowerPoint. We currently have 14 reports and we want to export each report daily (in both formats, so 28 files) so that it can be sent out by email, as well as cached so that when a user clicks the export button on the web portal it is exported immediately from the cache (instead of taking several minutes to load from the Power BI API). We cannot currently do this because of the 50 page per hour limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by Alonbaram** [comment]
We are still working on it
No ETA yet
