### ISSUE TITLE
Course recommended is no longer available.

### ISSUE THREAD

**Issue by mm8974** [MicrosoftDocs/powerbi-docs#2281]
The recommended course "Analyzing and Visualizing Data with Power BI" at the URL below is no longer available.  
https://prod-edx-mktg-edit.edx.org/course/analyzing-visualizing-data-power-bi-4

Is there a replacement?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6e66c7-0640-3bbe-b2e7-c9db15ab6dfb
* Version Independent ID: 9fe447f9-d6a0-c7d4-cfe0-e6f18191ee8e
* Content: [Get started with the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-get-started)
* Content Source: [powerbi-docs/fundamentals/service-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/service-get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mm8974 -- great question! I've deleted the broken link and added links to 2 new collections of Microsoft Learn content about Power BI:
Learn Power BI, https://docs.microsoft.com/users/microsoftpowerplatform-5978/collections/r52to235xrjxk
Become a Power BI data analyst, https://docs.microsoft.com/users/microsoftpowerplatform-5978/collections/djwu3eywpk4nm
