### ISSUE TITLE
Lack of consideration for the customer, claim to support above Office 2010 SP1 but do not support Office 2013

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2282]
I moved this from here: https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/37
The comments below were machine-translated

@henriquesantosneto commented on [Tue Jun 09 2020](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/37)

They say that the minimum requirement is Office 2010 SP1, which is a lie, because in office 2013 it doesn't work and Microsoft support isn't even calling the customer, they can't even solve a ridiculous Office problem. So that they put the editions really compatible.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analisar no Excel para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

---

@srvbpigh commented on [Tue Jun 09 2020](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/37#issuecomment-641278239)

Hello, @henriquesantosneto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by mihart** [comment]
Thanks for your comment, @CeciAc . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
