### ISSUE TITLE
Potentially conflicting information

### ISSUE THREAD

**Issue by mossywell** [MicrosoftDocs/powerbi-docs#2283]
Some potential conflicting information here:
"The data region is based on the country you select when you create the tenant." implies that the PowerBI location is based on the tenancy location. But you then have a screenshot of a _user_ setting and a sentence "Power BI picks a data region closest to your selection" (indicating the screenshot above referring to the user, not the tenancy). Of course, the tenant location doesn't need to match the user location (as indeed it doesn't in my case). When I tried it, I found that the PowerBI follows my user location, not the tenancy. It might be worth making it clearer that this happens?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe99dcd3-62d6-0f11-3b13-031eb65c426c
* Version Independent ID: c0dc599b-c84c-ae09-42a0-5c28bb635810
* Content: [Where is my Power BI tenant located? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located)
* Content Source: [powerbi-docs/admin/service-admin-where-is-my-tenant-located.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-where-is-my-tenant-located.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Hi @mossywell , 
Thank you for your suggestion.  We've made the update and set the article to republish tomorrow,  If you still have questions, please let us know.. 
All the best,
The DOCS team
