### ISSUE TITLE
There is an error in the filter expression

### ISSUE THREAD

**Issue by atinkerersnotebook** [MicrosoftDocs/powerbi-docs#2285]
The documentation says that the syntax for the filter is:

**?filter**=Table/Field eq 'Value'

It should be:
**&$filter**=Table/Field eq 'Value'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @atinkerersnotebook -- just circling back on your comment. I just tried both 
&$filter=Store/Territory eq 'NC'
and
?filter=Store/Territory eq 'NC'
Only the 2nd one filters the report. So I'm not sure what you're seeing.
Thanks!
