### ISSUE TITLE
Data shared with ESRI - is only location data shared? or all data in the visual?

### ISSUE THREAD

**Issue by mariewo** [MicrosoftDocs/powerbi-docs#2286]
Hello the section 'How do ArcGIS Maps for Power BI work together' says "You should assume any data bound to the data visualization can be sent to Esri’s services" which suggests to me anything in the visual including tooltip data and legend data etc, however the ESRI guidance on this (link below) suggests only location data is shared - can someone confirm which it is, as it's not clear to me?! Thanks

The page section:
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis#how-do-arcgis-maps-for-power-bi-work-together

ESRI statement on this:
https://doc.arcgis.com/en/maps-for-powerbi/get-started/data-transfer.htm

**Comment by mihart** [comment]
Hi @mariewo ,
I've contacted the developers and will reply when I get their response.  Thanks for the question.
Michele

**Comment by mihart** [comment]
Hi @mariewo ,
I see that this Git issue is a bit old, and I'm going to close it.  We've removed the article that you reference, and instead added a ink to ESRI's own documentation.   Thank you for the suggestion.
All the best,
the DOCS team
