### ISSUE TITLE
This example is deprecated with newer versions of AcquireToken function

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#2287]
@carfermar commented on [Wed Jun 10 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/30)

[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Obtener un token de acceso de autenticación - Power BI](https://docs.microsoft.com/es-es/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

---

@srvbpigh commented on [Wed Jun 10 2020](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/30#issuecomment-641902447)

Hello, @carfermar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc & @carfermar, thanks for your feedback! Assigning to the author to investigate.

**Comment by raymond-dillon** [comment]
The depreciated example is an issue for me as well - just adding my +1

**Comment by KesemSharabi** [comment]
Hi @CeciAc and @raymond-dillon,

I'm looking into refreshing the code snippets with our development team. This may take some time.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @CeciAc and @raymond-dillon,

This issue is in my backlog and I'll refresh the article as soon as I can.

Thanks,

Kesem

**Comment by rdc-Green** [comment]
I am having the same issue still:

CS1503	Argument 2: cannot convert from 'string' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential'	
CS1503	Argument 3: cannot convert from 'System.Uri' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.UserAssertion'

**Comment by jawwolfe** [comment]
I also ran this tutorial today using VS 2017 with the error below.  Can you please push this issue higher into your backlog?  This is now over one year old.   

 Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'System.Uri' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential'	walkthrough_push_data	C:\Users\awwolfe\source\repos\walkthrough_push_data\walkthrough_push_data\Program.cs	47	Active
