### ISSUE TITLE
Incorrect Formula

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2288]
Hi, (cc: @maggiesMSFT ) The formula at the bottom of[ this page](https://docs.microsoft.com/en-us/dax/rand-function-dax) for generating random numbers between two numbers (int1 & int2) is incorrect. Since int1 < int2, it will always generate numbers that are less than int1 and not between int1 & int2. It should be `RAND()*(int2-int1)+int1` and not `RAND()*(int1-int2)+int1`

**Comment by maggiesMSFT** [comment]
Hi, @pawarbi -- thanks for your comment! Assigning to the author to investigate.

**Comment by Minewiskan** [comment]
@pawarbi - You are correct. Thanks for bringing this to our attention. The article has been updated.
