### ISSUE TITLE
Power BI Data Gateway - Custom Connectors - Fully Qualified URLs

### ISSUE THREAD

**Issue by DMiradakis** [MicrosoftDocs/powerbi-docs#2289]
Microsoft Docs Team,

I wanted to open up a ticket and request that you consider adding an additional bullet point to your [Considerations and Limitations section of the document](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors#considerations-and-limitations):

After some troubleshooting I've done for the past few days, I realized that the reason my Standard Mode Power BI Data Gateway was not picking up the folder where my custom connector was installed was because my custom connector folder resided on a network folder/file server, and the URL that was being generated in the URL bar when I would point the Data Gateway to my custom connector folder was not fully-qualified. Once I manually typed in the fully qualified address into the URL bar, the Data Gateway detected my custom connector immediately.

Just a heads up for others if they have a Standard Mode Data Gateway installed on a server like my company does!

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137ea074-f635-5cd9-6e94-f6bc12ac2452
* Version Independent ID: 4ce609b2-adfa-8575-4e4a-9cc285028043
* Content: [Use custom data connectors with the on-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors)
* Content Source: [powerbi-docs/connect-data/service-gateway-custom-connectors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-gateway-custom-connectors.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by maggiesMSFT** [comment]
Hi, @DMiradakis -- thanks for your comment! Assigning to the author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @DMiradakis -- Thanks again! Adding this sentence to the article: 
"If your custom connector is on a network drive please include the fully qualified path on the On-premises data gateway app."
