### ISSUE TITLE
Email Notifications when a NEW Power BI workspace is created?

### ISSUE THREAD

**Issue by russty72** [MicrosoftDocs/powerbi-docs#229]
I'm trying to figure out whether email notifications are sent when a NEW Power BI Workspace is created. If I'm adding an "all company" security group or distribution list to a new Workspace I do not want an email notification going out to the whole company. 

Can someone help me understand two things:

1. Is an email notification sent to everyone in a Security Group or Distribution List when adding it to a new Power BI Workspace.

2. Is an email notification sent to everyone in a Security Group or Distribution List when a new Power BI Report or Dashboard is added to that Workspace.

Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @russty72 -- If I understand your questions correctly, here are the answers:
1. No, for the new workspaces, email notifications are not sent to a security group or distribution list.
2. No, when you add a new report or dashboard to the people in the security group or DL, they don't get an email notification.

**Comment by maggiesMSFT** [comment]
Please feel free to ask again, if I haven't answered your questions!

**Comment by russty72** [comment]
Thanks so much @maggiesMSFT !!
