### ISSUE TITLE
Old name used

### ISSUE THREAD

**Issue by kr10n1** [MicrosoftDocs/powerbi-docs#2291]
Seems like DataWarehouse is deprecated name and Synapse should be used. Currently it only causes confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5c2cbb-f3de-c63e-fc74-a5157d5f5c9c
* Version Independent ID: dd280f16-bad8-5f60-f960-208047f6f9b2
* Content: [Azure SQL Data Warehouse with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-azure-sql-data-warehouse-with-direct-connect)
* Content Source: [powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @kr10n1. We’ve assigned your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @kr10n1 , 
Thank you for your suggestion.  We are currently working on replacing all such mentions with Azure Synapse.  All Power BI documents will reflect this name change in the next month.  
All the best,
The DOCS team
