### ISSUE TITLE
RLS on app not working

### ISSUE THREAD

**Issue by Bmatix** [MicrosoftDocs/powerbi-docs#2292]
I tried a lot of times but the part where you do RLS and you say that by updating/sharing the app the external user can only see his data (accordingly to the RLS) is just not working with me. First I had with some dax code extracting the last part of our company emailadress which was then used to filter the data on company. But after trying so much went for the straight email link to company like in the example (user table) and still it didn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi#case-study-building-a-bi-portal-using-power-bi--azure-ad-b2b--step-by-step-instructions)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Bmatix - and sorry for the trouble you're encountering. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
