### ISSUE TITLE
Slicer Date Format Broken

### ISSUE THREAD

**Issue by DeleteThree** [MicrosoftDocs/powerbi-docs#2293]
Slicer Date format broken with latest version:
**https://photos.app.goo.gl/TUahjQMbqYKsnVxb9**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @DeleteThree. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @DeleteThree -- I'm sorry to hear it! This is product feedback. Please enter it at https://ideas.powerbi.com/ideas/
