### ISSUE TITLE
Many-to-many relationships feature (still) not available in Report Server

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2294]
The features listed omit "Many-to-many relationships". Despite being released for the Power BI service in 2018, it seems that feature is still not supported in Report Server as of May 2020.  

The workarounds entail hours of work and testing per model, so this should be clear before a product selection decision is made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
You're right, @Mike-Honey . I'm adding it to the table now. Thanks for asking!

**Comment by jrussi1301** [comment]
Does it means that now Power BI Desktop RS will finally open .PBIX files with many-to-many relationships models?

**Comment by maggiesMSFT** [comment]
Hi, @jrussi1301 -- no, many-to-many relationships aren't supported in either Power BI Desktop optimized for Power BI Report Server, or on Power BI Report Server itself. Thanks!

**Comment by jrussi1301** [comment]
Well, it's working here (in a bunch of reports), Power BI Server january/2020. In fact, even before january/2020 it was working. I've created the .PBIX on a normal PB Desktop and  have it uploaded on the server, directly on the web portal. It's running. Probably it's just a preview feature, but it is doing flawless. Power BI Desktop RS should allow it too, even with a preview alert.

**Comment by hifihedgehog** [comment]
Microsoft parlance translation: "Supported" means here "it is working but we don't want you to use it yet."

**Comment by maggiesMSFT** [comment]
Hi, @hifihedgehog and @jrussi1301 -- I'd say "supported" translates as: "We haven't tested it, so we can't guarantee it. Use at your own risk." Hope that helps!
