### ISSUE TITLE
Critical bug PBIRS 15.0.1103.232

### ISSUE THREAD

**Issue by josef78** [MicrosoftDocs/powerbi-docs#2295]
Hi,
new version of May2020 PowerBI Report Server 15.0.1103.232 still contain critical bug. In this version is completely not working scheduled data refresh in scale-out deployment, see https://community.powerbi.com/t5/Report-Server/PBI-Server-May-2020-not-refreshing-saved-reports/m-p/1135485

Please remove PBIRS May 2020 form downloads and go back to January 2020

**Comment by mihart** [comment]
Thanks for your comment, @josef78 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by josef78** [comment]
@mihart Thanks, but, community cannot solve bug in Microsoft product, and support.powerbi.com is only for cloud Power BI service, not for Power BI Report Server, it is different product.
