### ISSUE TITLE
Admin Privileges Requirement Could Be More Visible

### ISSUE THREAD

**Issue by BreakingBI** [MicrosoftDocs/powerbi-docs#2296]
Good morning,

Thanks so much for all the work you put into the great Power BI Emedded Documentation.  I've had a couple of customers missed one of the steps, which could likely be resolved by making it more visible and adding a hyperlink to the relevant section.

https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#create-a-workspace

This section mentions,

"In either scenario, both the master account or service principal must be an admin of the workspaces involved with your application."

This is critical to the process and is not entirely obvious if it is missed.  So, adding one of the purple "Important" boxes and possibly including this hyperlink could improve visibility of this critical step.

https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-the-new-workspaces#give-access-to-your-workspace

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#set-up-your-power-bi-environment)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @BreakingBI . This issue has been assigned to the doc author for review.
Hi Brad :-)

**Comment by KesemSharabi** [comment]
Hi @BreakingBI,

Thank you for your comment. I'm going to update all the embedded analytics tutorials shortly, and add a few new ones too. When I do this, I'll take your suggestion into account.

Please note that it will take a while for me to make these changes.

Once again, thanks for your suggestion.

Kesem
