### ISSUE TITLE
Aduit log Unified

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/powerbi-docs#2297]
I am looking to see if this activity *copy a visual* is audited, especially when the report has a sensitivity label applied. https://powerbi.microsoft.com/en-us/blog/announcing-copy-a-visual-as-an-image/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the question, @javirivas80. I'll look into this and provide an update within the next few days.

**Comment by kfollis** [comment]
Thanks for the patience, @javirivas80. I sent this question to our engineering team to get a definitive answer. The "copy visual image" event is NOT captured in the audit log. Although this feature is convenient, users can use snipping or screen capture tools to take snapshots of visuals too, so tracking would be incomplete. If a report has the sensitivity label applied, the user is prompted with a dialog advising that they're copying sensitive data. There are operations available for tracking when sensitivity labels are applied, changed, or removed.
