### ISSUE TITLE
Existing data

### ISSUE THREAD

**Issue by anurag-doshi** [MicrosoftDocs/powerbi-docs#230]
For incremental refresh, can you please state what would happen if an already imported row was updated?  Would it create duplicate rows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-incremental-refresh)
* Content Source: [powerbi-docs/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @christianwade
* Microsoft Alias: **chwade**

**Comment by christianwade** [comment]
This is already covered by the documentation. Copy paste paragraph below

The filter will be used to partition the data into ranges in the Power BI service. It is not designed to support updating this the filtered date column. An update will be interpreted as an insertion and a deletion (not an update). If the deletion occurs in the historical range and not the incremental range, it won’t get picked up.

**Comment by anurag-doshi** [comment]
Thank you Wade.

I did read the line but was struggling with the interpretation of it.

If the row is updated, it will be deleted from the existing data in power
bi and a new row added?

Thank you.

**Comment by christianwade** [comment]
No problem. Yes, that is correct. But if the deletion is not in the incremental range, the deletion won't happen

**Comment by maggiesMSFT** [comment]
Thanks, @anurag-doshi and @christianwade !
