### ISSUE TITLE
In Selection section 'Create selections for categorical data view mapping' in the Note part

### ISSUE THREAD

**Issue by BREN1234** [MicrosoftDocs/powerbi-docs#2300]
i think spelling for grouped is misspelled 'groped'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75effaec-3c6e-83c9-c26e-8e58046cb347
* Version Independent ID: 971d9758-f10b-cddb-f6fa-c007e193e457
* Content: [Power BI visual data point selections - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/selection-api)
* Content Source: [powerbi-docs/developer/visuals/selection-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/selection-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Oh my. Thank you, @BREN1234! I've made the fix and the change will be live soon.
