### ISSUE TITLE
What does this specifically mean?

### ISSUE THREAD

**Issue by bradj813** [MicrosoftDocs/powerbi-docs#2301]
"You can review and edit some parameter settings in the Power BI service -- not parameters that restrict the available data, but parameters that define and describe acceptable values."

What exactly can and can't we use parameters with? Can you give an example?

**Comment by kfollis** [comment]
Hi @bradj813, is this the article you're referencing: https://docs.microsoft.com/en-us/power-bi/connect-data/service-parameters? I'm assigning this issue to the author to consider updating to provide clarification. Thanks for the feedback!

**Comment by bradj813** [comment]
Hi Kate,

Yes. I wasn’t sure how to do that.

Thanks,
Brad

**Comment by maggiesMSFT** [comment]
Hi, @bradj813 -- just so you know, I'm working on finding an answer. I own the article but didn't write it originally.
thanks --

**Comment by maggiesMSFT** [comment]
Hi, @bradj813 -- whew, that took a while. The answer is: The sentence is misleading, and I'm rewriting it. It should say something simple like "You create parameters in Power BI Desktop. You can review and edit parameter settings in the Power BI service, but not create them."

**Comment by maggiesMSFT** [comment]
Thanks for asking, @bradj813 ! That sentence was uninformative.
