### ISSUE TITLE
Additional keyboard shortcuts

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2302]
Hi, 

I just [wrote a blog](https://pawarbi.github.io/blog/powerbi/2020/06/17/powerbi-keyboard-shortcuts.html) post on some of the keyboard shortcuts in powerbi that I use frequently and discovered that there is already a documentation page and it doesn't include these shortcuts. Not sure of the page has been updated in a while or not but you may want to update it or incorporate some of my shortcuts so all users can benefit from it , just a suggestion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks, @pawarbi! I'm assigning this to the author to review and compare and made updates for any default shortcuts that may be missing.

**Comment by mihart** [comment]
Hi @pawarbi ,
I see that this Git issue is a bit old, so I'm going to close it.  We took your suggestion and did a freshness pass on the article so it should be completely up-to-date now.  I've also added some of your shortcuts -- thank you so much for sending those along. 
All the best,
the DOCS team
