### ISSUE TITLE
Workspace limit error

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#2304]
Hi, this article indicates a 100 GB limit per Workspace for Pro licence, isn't it 10 GB ? Also what about the space used by dataflows, does it count for the 10 GB limit ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks for the question, @nstraw. I'm assigning to the author to follow-up and clarify the information as needed.

**Comment by maggiesMSFT** [comment]
Yes, thanks, @nstraw ! Fixing this now.
