### ISSUE TITLE
Client.Reports from where we are getting. No information on that line. 

### ISSUE THREAD

**Issue by sasidhar8785** [MicrosoftDocs/powerbi-docs#2306]
Client.Reports.Methods are no where in the current nuget packages. Please update your code accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @sasidhar8785. I'm assigning to the writer to investigate and make any needed updates.

**Comment by KesemSharabi** [comment]
Hi @sasidhar8785,

Can you please let me know where in the [Export paginated report to file](https://docs.microsoft.com/power-bi/developer/embedded/export-paginated-report) article you see **Client.Reports.Methods**?

Or, are you referring to these:
* Client.Reports.ExportToFileInGroupAsync
* Client.Reports.GetExportToFileStatusInGroupWithHttpMessagesAsync
* Client.Reports.GetFileOfExportToFileInGroupWithHttpMessagesAsync

If so, these methods are available in the [Microsoft.PowerBI.Api](https://www.nuget.org/packages/Microsoft.PowerBI.Api/) nuget. We don't document all the methods; try typing **Client.Reports.** for a complete list of methods.

Also, don't forget that in this example, the **Client** object is an instance of the Power BI .NET SDK (see comment in code in [Step 1 - sending an export request](https://docs.microsoft.com/power-bi/developer/embedded/export-to#step-1---sending-an-export-request)).

Hope this helps,

Kesem
