### ISSUE TITLE
You are recommending people install 3.5.3, yet this is NOT supported in the service. It should be mentioned that 3.4.4 is the highest supported version in the PBI Service

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/powerbi-docs#2307]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals)
* Content Source: [powerbi-docs/create-reports/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-r-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @ScottStauffer. I'm assigning this issue to the author to verify and make an update.

**Comment by ScottStauffer** [comment]
As shown below in red…
This is kinda critical that you either convince the team to move to a version that is not over 2 years old, or make the locations that reference the correct version consistent.
There are seems to be many issues when you put a higher version in initially…


[cid:image001.png@01D64645.B55877D0]

**Comment by VitalyMCT** [comment]
Can we please get some feedback on this one? It's indeed something that's rather important to many Power BI customers. The supported version is now over 3 years old.

**Comment by davidiseminger** [comment]
I updated the visual and the information on the page to reflect 3.4.4 is the most current version supported on both Desktop and the service. 

In terms of updating the version of R supported on the platform, your best avenue is to submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
