### ISSUE TITLE
Update the doc

### ISSUE THREAD

**Issue by BrainYinM** [MicrosoftDocs/powerbi-docs#2308]
Hi Team,

I am the internal guy from support team. Could contact me by leyin@microsoft.com
Current lots of user think power BI premium could improve the performance when refreshing or report loading. Actually, Power BI Premium could not even some time could cause bad performance.

Now even sales may tell customer premium could improve the performance.
So could we modify the doc, and share more proper information of about performance?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks, @BrainYinM! I'm assigning to the author to review your feedback and provide clarification in the docs.

**Comment by davidiseminger** [comment]
With the release of Premium Gen2, this is no longer an issue.
