### ISSUE TITLE
Unsupported Items need clarification: Enhanced Dataset Metadata

### ISSUE THREAD

**Issue by unt1tled** [MicrosoftDocs/powerbi-docs#2309]
There's a [bullet point](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#unsupported-items) which mentions "**Datasets that do not originate from a .pbix**". However, users that enable the Enhanced Dataset Metadata preview feature on their dataset will discover that the new format is among the list of **UnsupportedDatasetTypes**. There are no specific mentions of the new format not being supported in the pipeline documentation. There is no mention for when the new format will presumably be supported.

When attempting to publish a pipeline with a dataset that uses enhanced dataset metadata, the following response is returned by the service:

`{"error":{"code":"Alm_InvalidRequest_UnsupportedDatasetType","pbi.error":{"code":"Alm_InvalidRequest_UnsupportedDatasetType","details":[{"code":"UnsupportedDatasetType","detail":{"type":1,"value":"{\"artifactTypeName\":\"Datasets\",\"artifactId\":\"_dataset-guid_\"}"}}],"exceptionCulprit":1}}}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines process - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @unt1tled, thanks for your observation. I am forwarding it along to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @NimrodShalit - do you know anything about the new Enhanced Dataset Metadata preview feature, and its new format?

**Comment by NimrodShalit** [comment]
Yes, it’s the new XMLA end point support.
What’s the question?

**Comment by KesemSharabi** [comment]
Hi @NimrodShalit, @unt1tled is asking if deployment pipelines will support this format?

**Comment by NimrodShalit** [comment]
Yes, we will.

**Comment by KesemSharabi** [comment]
@NimrodShalit, do we have a rough estimation when?

**Comment by NimrodShalit** [comment]
Few weeks.

**Comment by KesemSharabi** [comment]
Hi @unt1tled,

I trust you got an answer to your question. In a few weeks time, once the new format is supported, I'll add it to the documentation.

Thanks,

Kesem
