### ISSUE TITLE
APi Links and Method names are out of date or wrong

### ISSUE THREAD

**Issue by metamoof** [MicrosoftDocs/powerbi-docs#231]
All the links to the power BI REST documentation leave you at the head of the REST documentation page, rather than to a particular method.

This documentation talks about AddRows and CreateDataset, but it appears you mean PostRows and PostDataset

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming)
* Content Source: [powerbi-docs/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-real-time-streaming.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comments @metamoof. I've fixed those links, thanks for pointing those out!
