### ISSUE TITLE
The option to copy a visual into an image does not exist in PowerBI Desktop

### ISSUE THREAD

**Issue by Itamar-** [MicrosoftDocs/powerbi-docs#2310]
In contrast to what one might understand from the header, the option to copy a visual into an image does not exist in PowerBI Desktop. 
Please add this essential (and quite trivial) option!!!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [Copy and paste a visualization in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your feedback. We need to add a note to that page that states "In Power BI Desktop, you can only copy and paste and entire interactive visual, not an image of the current state of a visual."

We need to add that early in the section titled "Copy a visual as an image to your clipboard"

Sorry for the oversight in that doc. We've assigned this issue to the owner of that article, who should respond shortly.

**Comment by Itamar-** [comment]
It is a real pity that the option does not exist. I added a request for this important option.
What does "copy and paste and entire interactive visual" mean exactly, Can you copy and paste into Powerpoint or just within Power BI?
Thanks

**Comment by mihart** [comment]
Hi @Itamar- 
"Copy and past an entire interactive visual" refers to Copy and paste described in the first half of the article.  Select a report visual, CTRL-c, go to another page in the report, CTRL-v.  When you paste the visual, it retains it's interactivity -- you can filter, personalize, drill, etc...  

For the copy and paste as an image, yes, you can paste it into PowerPoint and any other application that supports pasting. It works in Word, Outlook, Paint, etc...

The article is updated and will go live later this week.  Thank you for your help!
Michele
