### ISSUE TITLE
SharePoint Version

### ISSUE THREAD

**Issue by slopezv2** [MicrosoftDocs/powerbi-docs#2311]
[Enter feedback here]
Hi, Which SharePoint On-Premises versions work with this? Can I try this with SharePoint 2010?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [Embed a Power BI Report Server report using an iFrame in SharePoint Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-embed)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @slopezv2 -- thanks for asking! I'm checking and will get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @slopezv2 -- sadly, the answer is no, it won't work with SharePoint 2010. It requires versions 2013, 2016, and 2019. I'm adding that info to the article. Thanks for asking!
