### ISSUE TITLE
Issue with RI Usage Details - TotalReservedQuantity is always zero

### ISSUE THREAD

**Issue by lakeyeric22** [MicrosoftDocs/powerbi-docs#2312]
Starting about a month ago, the TotalReservedQuantity field in my RI Usage Details table from "Azure Cost Management" connector in Power BI, started returning all zeros instead of values like 1, 2, 3, 4, etc.  I've submitted a trouble ticket but it's been a month and I'm still not to the right team yet.  Has this field been deprecated?  Is anyone else experiencing this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry to hear about the trouble you're having - this feedback is only for the documentation, rather than for support issues, and if the behavior has changed overall and this document isn't current, we certainly will be happy to update the documentation. Meanwhile, while waiting for your support ticket to be resolved (sorry that's taking so long), you might find a solution in the Power BI Community, found at https://community.powerbi.com.

**Comment by davidiseminger** [comment]
Adding tags to follow up.

**Comment by mihart** [comment]
Hi @TravisKale,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by mihart** [comment]
Hi @lakeyeric22 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option for this type of question is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
