### ISSUE TITLE
Premium equals embedded?

### ISSUE THREAD

**Issue by miragliag** [MicrosoftDocs/powerbi-docs#2313]
I have embedded A2 Capacity. Does Directquery should work for Dataflow? Or is this feature only for P1, P2 etc.?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4696f74d-bce4-3808-008a-4375afdb71c5
* Version Independent ID: 339f52a6-9d08-4634-76f4-5195c3b475ec
* Content: [Use DirectQuery with dataflows in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-directquery)
* Content Source: [powerbi-docs/transform-model/service-dataflows-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @miragliag . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @miragliag . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
