### ISSUE TITLE
Prerequisite about IBM DB2 is not correct

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2315]
As advised by Power BI Product Group, the pre requisite as per this doc for IBM DB2 data source is not correct and up to date. Please consult with Product Group and change the doc. We had an IcM for this and you can see the comment from an engineer in PG in the attached screenshot.

![image](https://user-images.githubusercontent.com/30608419/85507104-623c8f00-b5b7-11ea-92b4-f5c1406e9de8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d081a0-4c4b-f756-eaf7-1e98d583ecf8
* Version Independent ID: 0b694de6-df10-daca-888c-1062dd3299db
* Content: [Power BI data source prerequisites - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-source-prerequisites)
* Content Source: [powerbi-docs/connect-data/desktop-data-source-prerequisites.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-data-source-prerequisites.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @haider392.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the information - fixed.
