### ISSUE TITLE
Change Log without timeline ? 

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/powerbi-docs#2316]
Hi it would be great to have the time lime for the API changes as well, currently I have no idea when which version of the API became productive. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91bb7ef2-b412-1d90-f0c5-b6231b3467e4
* Version Independent ID: d7ee6797-0554-ef39-64af-a9201333a95e
* Content: [Power BI visuals API changelog - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/changelog)
* Content Source: [powerbi-docs/developer/visuals/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @uve, 

Can we add this to the article?

Thanks,

Kesem

**Comment by uve** [comment]
thanks, @nojetlag for your suggestion. We'll add it to changelog soon. Please use the latest available API version for your visual.
