### ISSUE TITLE
Custom Visual API Version supported ?

### ISSUE THREAD

**Issue by nojetlag** [MicrosoftDocs/powerbi-docs#2317]
I remember there was a discussion to add the information what version of the custom visual api is supported in a PBIRS release, would it be possible to add this information in the changelog as well ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @nojetlag.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @nojetlag -- the Custom Visual API version number is in the Power BI Report Server What's new article, https://docs.microsoft.com/power-bi/report-server/whats-new#power-bi-visuals-api
Hope that helps!
