### ISSUE TITLE
How about two or more tables to hold the data?

### ISSUE THREAD

**Issue by peymanrah** [MicrosoftDocs/powerbi-docs#232]
Hi, 
I need to input two or more tables into my R script from PBI. dataset only hold the information of one table, correct? How do I import more than one table into my R script within PBI?

also, can you explain how do I connect a slicer value to the R script? I want an end user to slice over date and my R script reads the numbers from slicer in the R script and run analytics over the new values in slicer. How do I do this in PBI using R scripting?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Using R in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-in-query-editor.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @peymanrah. We’ve forwarded your question to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment, @peymanrah. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
