### ISSUE TITLE
Exporting Power BI Report with Custom Filters

### ISSUE THREAD

**Issue by kylemcguinn** [MicrosoftDocs/powerbi-docs#2322]
We are currently using Power BI Embedded to host a report with custom filters that are set from outside the report and passed in programmatically via the javascript API. I have been able to successfully call the Export API for this report and generate a PDF; however, I have not been able to have the report maintain its filter state and it always seems to run as if no filters were selected. I have tried using the javascript bookmark API to capture state and pass in via the DefaultBookmark property as referenced in the documentation to no avail. I was wondering if maintaining filter state is currently supported or if it's a planned future feature? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi Kyle, thanks for reaching out to us with your question. I have forwarded it on to the doc author for consideration. 
@kylemcguinn

**Comment by KesemSharabi** [comment]
Thanks for your comment, @kylemcguinn.

I confirmed with the development team that setting bookmark by state is tested and supported. 

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
