### ISSUE TITLE
Licensing requirement for GCC environment

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2323]
Since GCC environment doesn't have free licenses, please update licensing requirement for premium workspace access in GCC.

How do users who don't have a Power BI Pro license in GCC access a premium workspace?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @haider392 -- I added a link to the article "Power BI for US government customers"
https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview
The change will be live Mon Aug 10 afternoon. 
Hope that helps!
