### ISSUE TITLE
Need to capture case for DQ

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/powerbi-docs#2325]
Query text and query result Direct Query traffic per input from Orion Lee also remains in the remote region.  Only LiveConnect traffic will continue to transit through the home region.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/admin/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks, @sergeigms. Assigning to the author to make the clarification.

**Comment by davidiseminger** [comment]
This was updated a while back, closing now.
