### ISSUE TITLE
Our IP being blocked by api.powerbi.com??

### ISSUE THREAD

**Issue by zungam** [MicrosoftDocs/powerbi-docs#2326]
Hi,

trying to connect to 
`
new Microsoft.PowerBI.Api.V2.PowerBIClient("https://api.powerbi.com/", tokenCredentials)
`
but gets immediately blocked out by
`
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
`
All credentials should check out fine. The app works when running on my work-computer, but when pushing our ASP.net app to the Azure server it always gets blocked when trying to access your API. I suspect our company server IP is being blocked externally by your API. 

Why?

It run smooth in the cloud for years, then suddenly was blocked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297c1372-b1bb-57c4-9c31-840b4cad2c37
* Version Independent ID: 0bb282a3-4aa6-1094-d8a4-652ec726734f
* Content: [Power BI URLs for whitelisting - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/power-bi-whitelist-urls)
* Content Source: [powerbi-docs/admin/power-bi-whitelist-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/power-bi-whitelist-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @zungam - I'm sorry you're having issues. This looks like something you should connect with support on. You can start a ticket at https://support.powerbi.com. If they discover that changes to the article are needed, they'll let me know.
