### ISSUE TITLE
Grant the permissions

### ISSUE THREAD

**Issue by javirivas80** [MicrosoftDocs/powerbi-docs#2328]
Can you review this step ?,https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app#apply-permissions-to-your-application-within-azure-ad  the procedure is outdated with the new app registration experience. It is not possible to add permissions to the Master Account. Without the account having at least the Application Administator role

![image](https://user-images.githubusercontent.com/44674421/85739655-5cd66600-b6d7-11ea-9f5f-fe6754c613c6.png)

In tenant it is enabled, that the user can give consent.
![image](https://user-images.githubusercontent.com/44674421/85740052-afb01d80-b6d7-11ea-9662-eb865dddcb01.png)

https://stackoverflow.com/questions/59950232/how-is-the-grant-permissions-button-in-legacy-azure-ad-app-registration-differ
This is de missing:
**If you're not allowed to do tenant-wide admin consent, the button attempts to grant the permissions for your account only:**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dd93dd-c3a9-fccc-3a74-cebd6bf09067
* Version Independent ID: 0f61cf44-982a-1fcd-1396-4f3da8a40af2
* Content: [Register an app to embed Power BI content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app)
* Content Source: [powerbi-docs/developer/embedded/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/register-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the input, @javirivas80. I'm assigning this issue to the author so that they can review the step you've flagged.

**Comment by KesemSharabi** [comment]
Hi @javirivas80,

Thanks for pointing out that the information in the [Register an Azure AD application to use with Power BI](https://docs.microsoft.com/power-bi/developer/embedded/register-app) article is outdated.

I will add this article to my queue of articles to update, and will do it as soon as possible.

Thanks again for your comment,

Kesem
