### ISSUE TITLE
Power BI URLs for Government

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2329]
We receive many questions from our government customers about whitelisting URLs for GCC tenants. Can you provide info for government tenants in the doc.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 297c1372-b1bb-57c4-9c31-840b4cad2c37
* Version Independent ID: 0bb282a3-4aa6-1094-d8a4-652ec726734f
* Content: [Power BI URLs for whitelisting - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/power-bi-whitelist-urls)
* Content Source: [powerbi-docs/admin/power-bi-whitelist-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/power-bi-whitelist-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the comment, @haider392. There is a separate article for US Gov here: https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview#connect-government-and-global-azure-cloud-services that refers users to a downloadable file with IP ranges and service tags. Does that provide the information that you need?

**Comment by haider392** [comment]
Thanks @kfollis - I am aware of the Azure IP ranges. But since the IP list is dynamic (changes on a weekly basis), customers would need to update those frequently in their firewalls. Whitelisting URLs on the other hand is more permanent solution.

**Comment by kfollis** [comment]
Closing this issue. The URL list to add to allow lists is in tech review and will publish as a part of the US Gov document.
