### ISSUE TITLE
Azure Analysis Services as a Limitation/Consideration?

### ISSUE THREAD

**Issue by audreyhammonds** [MicrosoftDocs/powerbi-docs#233]
Should Azure Analysis Services be added as a multidimensional source that cannot be included in a composite model?  I've tested this, and once I add an Azure Analysis Services model, I am not able to add an additional source.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use Composite Models in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models#limitations-and-considerations)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @audreyhammonds. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
