### ISSUE TITLE
Dataflow Workload - "Compute engine memory (%) (Preview)" setting

### ISSUE THREAD

**Issue by PaulKna** [MicrosoftDocs/powerbi-docs#2330]
Can we have some explanation of what the "Compute engine memory (%) (Preview)" memory setting under the dataflows workload does (it was recently added to the Dataflow Workload options but is not covered on this page) e.g. what are the pros and cons of increasing it from the default 30%? 

This would be useful to me because I am intermittently getting an error "Error: Data Source Error : Microsoft SQL: There is insufficient system memory in resource pool 'default' to run this query" on a dataflow. This dataflow is performing grouping using the enhanced compute engine and don't know for sure if that means this setting is too low and what problems could arise if I increase it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-workloads)
* Content Source: [powerbi-docs/admin/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @PaulKna. I'm assigning this issue to the writer to look into providing the additional detail requested.

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
