### ISSUE TITLE
Snowflake Power BI Link Changed

### ISSUE THREAD

**Issue by nzregs** [MicrosoftDocs/powerbi-docs#2332]
The link to the Snowflake Power BI SSO docs has changed.  Can you please update this page with the new link?  

`"If you are the Snowflake admin, please read the **Power BI SSO to Snowflake - Getting Started** article in the Snowflake documentation" `
link should be: https://docs.snowflake.com/en/user-guide/oauth-powerbi.html

`"If you run into any issues with the integration, please refer to the Snowflake **troubleshooting guide**."`
link should be: https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake#troubleshooting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328a161c-b51e-05d1-c185-cb244547c3f3
* Version Independent ID: 0bef7bb0-541e-a74b-0f68-359690ae8b8e
* Content: [Connect to Snowflake with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/service-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by kfollis** [comment]
Thanks, @nzregs! I can make these changes, but have a question. Is there a localized version of the snowflake URL or is it English only? In the second link update, the URL you provide just loops back to itself. Is this the correct link instead? https://docs.snowflake.com/en/user-guide/tasks-ts.html

**Comment by kfollis** [comment]
I made the URL correction, and targeted the troubleshooting link here: https://docs.snowflake.com/en/user-guide/oauth-powerbi.html#troubleshooting. The updates will be live this afternoon.
I'll close the issue now. Thanks!
