### ISSUE TITLE
Token is never assigned in this example

### ISSUE THREAD

**Issue by ssisjoost** [MicrosoftDocs/powerbi-docs#2333]
The Token is never assigned within the method in this example...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @ssisjoost. I'm assigning this to the author to take a look at the method.

**Comment by KesemSharabi** [comment]
Hi @ssisjoost,

Following your comment I added a token declaration (`var token`) to the code in [Get an authentication access token](https://docs.microsoft.com/power-bi/developer/automation/walkthrough-push-data-get-token).

Thank you for highlighting this issue,

Kesem
