### ISSUE TITLE
Data Source Remove Button doesn't exist

### ISSUE THREAD

**Issue by kcnighsurf** [MicrosoftDocs/powerbi-docs#2334]
[Following instructions to 'Remove' data source but no Remove or delete button exists
Please update instructions.
![image](https://user-images.githubusercontent.com/53189318/85876239-a89a1580-b792-11ea-9a21-747d43a7cbe7.png)

]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Manage data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by javirivas80** [comment]
Hello, try to move the mouse to the end until you see the three points ...

![image](https://user-images.githubusercontent.com/44674421/85890419-aef4b580-b7c3-11ea-964e-575937f1aae9.png)




![image](https://user-images.githubusercontent.com/44674421/85890174-3d1c6c00-b7c3-11ea-9813-8b1cf6546e12.png)

**Comment by kcnighsurf** [comment]
Oh wow - someone should fix that GUI bug. 
Highlighting the menu option doesn't reveal that ... menu
![image](https://user-images.githubusercontent.com/53189318/85892098-8c57a200-b7ad-11ea-952c-328f9edffb7a.png)
It should also be an option in the edit screen.
You literally have to move your mouse to that end blank area in the menu item for that ... menu option to appear.
![image](https://user-images.githubusercontent.com/53189318/85892228-c6c13f00-b7ad-11ea-86a8-43e2427be1de.png)

Not sure how that passed microsoft QA.

**Comment by kfollis** [comment]
Thanks for the feedback, @kcnighsurf and the help in answering, @javirivas80. I'm glad you found the option. I will close this documentation issue, but will share the feedback with the design and engineering teams.
