### ISSUE TITLE
Microsoft Graph Attaching Power BI Tab is now disabled

### ISSUE THREAD

**Issue by ashoksubedi1** [MicrosoftDocs/powerbi-docs#2335]
[My code used to hang a  Power BI tab in every Team but now after this update now I can not do that. I am have to manually go and set up power tab on each and every teams]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd9c7dbe-8b03-52a9-b299-936856c89ba8
* Version Independent ID: f4496816-b872-4541-4ad9-f3b323b8917f
* Content: [Collaborate in Microsoft Teams with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-microsoft-teams)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @LukaszPawlowski-MS
* Microsoft Alias: **lukaszp**

**Comment by kfollis** [comment]
Thanks for the feedback, @ashoksubedi1. I'm assigning the issue to the author.

**Comment by maggiesMSFT** [comment]
Hi, @ashoksubedi1 -- I've checked with folks. They say: "I looked at the update and the change shouldn't break creating PowerBI Tab with Graph." They ask that you open a support ticket so we can investigate why it's not working. 
https://powerbi.microsoft.com/en-us/support/
Thanks!
