### ISSUE TITLE
Additional screenshot would be helpful to flag how to search non-promoted / certified tables

### ISSUE THREAD

**Issue by wynhopkins** [MicrosoftDocs/powerbi-docs#2336]
Hi  

Re:
"The Data Types experience in Excel is similar to a lookup function. It takes a cell value provided by the Excel sheet, and searches for matching rows in Power BI featured tables. The search experience has the following behaviors:

When using the **Organizational Data** button to search, Excel only searches featured tables in Certified datasets. "

It took me a few attempts and some trial and error for me to work out what this was saying.

Would be good to show the Organizational Data button AND a couple of examples of the Featured Table buttons to emphasize that you need to click on the specific Featured Table buttons if they aren't certified in order for the function to work

Also, a linked to how to certify a data set would be helpful here

Thanks

Wyn

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c639d8d-4ec5-6d21-b2f6-8d47de957b04
* Version Independent ID: 027ca3b7-27e1-a621-585b-665077746e5d
* Content: [Access Power BI featured tables in Excel (preview) - Power BI](https://docs.microsoft.com/en-gb/power-bi/collaborate-share/service-excel-featured-tables)
* Content Source: [powerbi-docs/collaborate-share/service-excel-featured-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-excel-featured-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @wynhopkins! Thanks for your feedback and suggestions. I am forwarding them on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @wynhopkins -- I too decided the article was confusing, so I kind of rewrote it. Got some good details from both product teams, too. Thanks for the nudge! 
Changes will be live next Monday 7/27 afternoon.
