### ISSUE TITLE
"Export report to image is disabled on tenant level" with PNG format

### ISSUE THREAD

**Issue by DanielSKim** [MicrosoftDocs/powerbi-docs#2337]
When call the ExportTo end point, I'm getting the following response message with `PNG` as the `format`:

`Export report to image is disabled on tenant level`

The requests are successful when specifying `PDF` or `PPTX`. This is for a report in a workspace using Azure Power BI Embedded SKU A1 capacity.

I don't see a setting for this when looking at the Tenant or Capacity settings in the Admin portal. Is there a setting that needs to be configured or is there a limitation in exporting to a PNG in some situations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @DanielSKim , thanks for reaching out to us with your question. I am forwarding it along to the doc author for consideration.
@KesemSharabi , do you know specifically which tenant setting controls export to PNG, which seems to be disabled by default? Is it the Export data setting?

**Comment by KesemSharabi** [comment]
Hi @DanielSKim,

The admin portal tenant setting isn't visible due to bug. The ETA for fixing the bug is by the end of the week. Please look for this setting early next week. Once enabled, your call should work.

Thanks,

Kesem

**Comment by DanielSKim** [comment]
@KesemSharabi Appreciate the follow up and great to hear! I'll keep an eye out over the next week.

**Comment by KesemSharabi** [comment]
Hi @DanielSKim,

Looks like the *export reports as images* option is now available.

![Export report as an image file.](https://user-images.githubusercontent.com/54834915/87542635-f4621f80-c6ab-11ea-950f-edc99478ad85.png)

Hope this helps,

Kesem
