### ISSUE TITLE
Sort By Column not present in current power bi desktop app

### ISSUE THREAD

**Issue by jnesfield** [MicrosoftDocs/powerbi-docs#2338]
[Enter feedback here]
Your documentation in several places references the option in the ribbon under the modeling tab to a sort by column button that is not present in the current power bi application. 
![image](https://user-images.githubusercontent.com/23704688/86032441-37ee3580-b9ec-11ea-942c-110b81fad915.png)

from: https://docs.microsoft.com/en-us/learn/modules/model-data-power-bi/4-optimize-data-models

![image](https://user-images.githubusercontent.com/23704688/86032481-49cfd880-b9ec-11ea-8909-ee8ef319adb9.png)

from: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column

![image](https://user-images.githubusercontent.com/23704688/86032532-5a804e80-b9ec-11ea-9032-1f2ce5841610.png)
 from actual application.

In addition all the power bi documentation present reflects an older user interface which does not match the current version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column#feedback)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @jnesfield , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
