### ISSUE TITLE
what is the source/owner of  this product?  microsoft?  

### ISSUE THREAD

**Issue by bob-pctest** [MicrosoftDocs/powerbi-docs#2339]
[Enter feedback here]
For those of us working for companies with a Cloud Access Security Broker (CASB), it is very important to understand the owner (source) of software.  Who wrote it?  What URLs does it access?

Our CASB does not block the download, but blocks the USE of this product.  We need a lot more information about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa9e720-7c65-9e70-acba-7cb58fd5b4b3
* Version Independent ID: 0bcb5169-a217-e90d-52b3-4fdff2b8cf4c
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bob-pctest.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by kfollis** [comment]
Hi @bob-pctest - thanks for the question. Microsoft is the source of the on-premises gateway. During installation, you can access the terms of use to view more details about the software. The endpoints accessed by Power BI are listed here: https://docs.microsoft.com/en-us/power-bi/admin/power-bi-whitelist-urls. The URLs accessed by the gateway will depend on how you configure it. There's a lot more info here: https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install. Is that what you need?

**Comment by bob-pctest** [comment]
Hi Kate:

I wanted to know the source of the add-on software app.  I know that Microsoft provides the gateway.

We are very concerned about the source of these apps, and we specifically disallow anything that is not written/provided by Microsoft itself.

Regards,

Bob Sauers
Principal Systems and Network Architect
IT Department
PCTEST Engineering Laboratory, Inc.
9017 Mendenhall CT, Suite G
Columbia, MD 21045

+1 (410) 290-6652 x550 Mobile +1 (443) 838-0477

**Comment by kfollis** [comment]
@bob-pctest - Microsoft Corporation is the verified publisher of the software. Certificate details are available when the software is launched.  I'll close this issue now. Thanks!
