### ISSUE TITLE
Strange filtering of data

### ISSUE THREAD

**Issue by CraigHumphrey** [MicrosoftDocs/powerbi-docs#234]
Hey Guys,

not sure if this should go in the PowerBI support, or here, as it's specific to the Microsoft Azure Consumption Insights reports.  Let me know if there's a better place to feedback on this specific content pack.

In the Lifetime based graphs, I'm seeing data from 2015-07 to 2018-04.
In the selected months based graphs, I'm seeing data from 2017-09 to 2018-06.

Why is the end date different?
How do I change the filter on "selected months", as when I go to the sub-report and try to filter it, the only months available are 2017-09 to 2018-06.
Why does lifetime not have 2018-05 and 2018-06?
I suspect the odd end dates are due to our Enterprise Agreement renewing (for another three years) at the beginning of July this year, but does that mean if I go an create a new instance of this content pack, with the new account code, it wont have all the data in the existing content pack?  Is this going to happen every three years?
Our EA has three departments assigned - three Azure tenants - it'd be handy to have a summary that gives me the annual spend (based on our financial year) for each department, so that we can do internal charging...

Thanks
Craig

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @CraigHumphrey. I think you're right -- this looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
