### ISSUE TITLE
Disconnect unused account

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2340]
[Enter feedback here]

The Power BI service now supports the functionality to "Disconnect unused account" for Azure Data Lake Storage accounts 
within the Dataflow settings in the Admin portal.

Currently within the Considerations and limitations - it states "it cannot be changed."

Considerations and limitations
Once a dataflow storage location is configured, it cannot be changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi Alex, thanks for your comment. I am forwarding it along to the doc author for further consideration.
@itsnotaboutthecell

**Comment by mihart** [comment]
Hi @itsnotaboutthecell ,
I see that this Git issue is a bit old, so I'm going to close it.  I checked the referenced article and no longer see the limitation included. Thank you for your suggestion!  
All the best,
the DOCS team
