### ISSUE TITLE
Not able to refresh Power BI report when having stored procedures with dynamic parameters

### ISSUE THREAD

**Issue by aivyle** [MicrosoftDocs/powerbi-docs#2341]
Hello,  

I have a report using dynamic parameters and it has been working fine.  Last week, on Thursday, the dataset failed to refresh and I saw the message gateway connection 'not configured correctly'.  After looking into this, it seems to me that the gateway is configured correctly and able to map to the data source if the parameter for the stored procedure is hard-coded but not working when the parameter is passing in dynamically.  I'm not sure if something changed recently since it was working fine before.  Please let me know.

Thanks
Vy

**Hard-coded parameter SiteNo and it's working fine.**

let
    Source = Sql.Database("server", "database", [Query="exec [test].[spTest] @SiteNo = 3"])
in
    Source

**Passing in dynamic parameter SiteNo and not able to refresh dataset.  Getting message gateway connection not configured correctly.**

let
    Source = Sql.Database("server", "database", [Query="exec [test].[spTest] @SiteNo = " & Number.ToText(SiteNo)])
in
    Source

**Comment by mihart** [comment]
Thanks for your comment, @aivyle . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
