### ISSUE TITLE
Dataflow incremental refresh and datasets

### ISSUE THREAD

**Issue by PowerBI-User999** [MicrosoftDocs/powerbi-docs#2342]
[Enter feedback here]
Hello,

Could you please clarify and confirm that the following scenario is working in Power BI Service:

1.	Incremental Refresh of a **specific Dataflow**
2.	Incremental Refresh of Datasets depending on **this specific Dataflow**
 
is technically possible and supported by Microsoft Power BI (Service) .

Reason for question: If you have to ingest large amounts of data from a Data-Source (i.e. DWH) via Dataflows (incrementally refreshed), then the depending Datasets have to be refreshed incrementally as well to take full advantage of the incremental refresh, else a full refresh of the Datasets will be too slow (e.g. for an nightly end-to-end Data Refresh Data-Source => Dataflow => Dataset).

Thanks for your support !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60093b2-2bdf-92e9-ee7c-de316b601beb
* Version Independent ID: 25307bcb-648e-e620-3fe9-a1412e89c0b5
* Content: [Using incremental refresh with Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-incremental-refresh)
* Content Source: [powerbi-docs/transform-model/service-dataflows-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @PowerBI-User999 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @PowerBI-User999 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
