### ISSUE TITLE
Python / R scripting for Server? 

### ISSUE THREAD

**Issue by donodata** [MicrosoftDocs/powerbi-docs#2344]
[There is not information about the Python Visuals or R/Python use for data manipulation on the query use on Server Vs. Cloud. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @donodata . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for asking @donodata ! I've added Python and R scripting to the table. The update will be live tomorrow afternoon, July 9.
