### ISSUE TITLE
1 P2 (16 Cores) is the same as 2 P1 (16 Cores)

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#2346]
The purple disclaimer included in the document is misleading.  Premium can be purchased in 8 Core increments and cores can be added to existing capacities as needed.  1 P2 (16 Cores) is the same as 2 P1 (16 Cores).

Often organizations start with an initial 1 P1 (8 core) capacity and over time may require additional capacity.  They can purchase an additional 1 P1 (8 Core) and combine it with an existing capacity, essentially scaling it up to 16 cores (1 P2).  This is a common behavior.

The way that the purple disclaimer is written, could be misinterpreted that organizations should be removing the 1 P1 from their agreement and adding 1 P2.  This behavior would be disruptive to end users.  Can we get the purple disclaimer updated to be more clear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @elfohl . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @elfohl ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
