### ISSUE TITLE
Minimum TLS Version

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2348]
Hi, I recently ran into issues with connecting dataflow with ADLSg2 storage account. Note that Power BI support engineer resolved the issue by selecting Minimum TLS Version = 1.2 in Azure storage configuration. She mentioned that this is a requirement and support for version <1.2 has been deprecated. Please update the requirements and the steps with the correct information. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @pawarbi . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @pawarbi ,
Thank you for your feedback.  I've updated the article to include this prerequisite.
