### ISSUE TITLE
Remove TOPN Function

### ISSUE THREAD

**Issue by stokeamb** [MicrosoftDocs/powerbi-docs#2349]
In the "Create the dataset with the query" section, please add instructions to remove the TOPN function from the copied DAX query before using it in the query designer. It seems this is essential to avoid limiting the data returned, but it isn't mentioned in the guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0cd82d-e7c4-4b5b-700f-1152a2a6bf38
* Version Independent ID: b2d4aeb5-1a98-ad43-4cf6-9539d9073600
* Content: [Create a paginated report with a Power BI shared dataset - Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets)
* Content Source: [powerbi-docs/paginated-reports/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @stokeamb . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @stokeamb -- Thanks! You're right, you do need to remove the TOPN. I've redone the screen shots and added a note. Changes will be live tomorrow afternoon, July 9.
