### ISSUE TITLE
premium capacity nodes compared to share capacity

### ISSUE THREAD

**Issue by thierryturpin** [MicrosoftDocs/powerbi-docs#235]
Good documentation, nevertheless it would be interesting to have the comparison to the shared capacity also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [Power BI Premium - what is it? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium#premium-capacity-nodes)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @thierryturpin - I'm planning updates to a related article, which should address this. I'll keep this issue open until I publish that update.

**Comment by mgblythe** [comment]
We rewrote this doc a while back. It focuses on what premium is but it has the following info, which really is the main point of comparison: _With Power BI Premium, you get dedicated capacities. In contrast to a shared capacity where workloads run on computational resources shared with other customers, a dedicated capacity is for exclusive use by an organization. It's isolated with dedicated computational resources, which provide dependable and consistent performance for hosted content._
