### ISSUE TITLE
More Clarification on the Dataflows Limitations

### ISSUE THREAD

**Issue by olyamusok** [MicrosoftDocs/powerbi-docs#2350]
Could you provide clarification on the statement that Dataflows feature is not supported for Multi-Geo:

1. Is it that dataflows are disabled?
2. Is it that dataflows are supported, but data storage and metadata all reside in the Home Tenant location? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/admin/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the question, @olyamusok. I'm assigning this issue to the author to look into providing that clarification.

**Comment by olyamusok** [comment]
@davidiseminger @kfollis 
Adding to the above question. After testing with capacity in remote region I am able to 

- create dataflows
- create and publish reports based on dataflows stored in a different capacity located in home region
This by itself brings a whole list of questions on where the data is actually stored in these cases? 

On another note on something else I do not see mentioned anywhere in documentation:
For **new capacities in remote regions dataflows** workload can not be disabled at all, see on the screenshot the toggle is greyed out to on by default, which calls for explanation:
![image](https://user-images.githubusercontent.com/40611069/87079300-d439e880-c1f3-11ea-9ad8-71d5e57cddee.png)

TIA

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.

**Comment by olyamusok** [comment]
@Davidseminger Could you please point me to the articles that have the updates related to dataflow storage and in particular its relation to Mult-Geo. I do not see any changes or clarifications in the article text: Multi-Geo support for Power BI Premium - Power BI
Do I need to look at a different doc? Thank you

**Comment by kfollis** [comment]
@olyamusok  - I don't think this article has the info you need, but the updated dataflow documentation is located in this section: https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-introduction-self-service
