### ISSUE TITLE
Downloading pbix file for desktop

### ISSUE THREAD

**Issue by SMay2020** [MicrosoftDocs/powerbi-docs#2351]
When I click on the link to download the HR sample pbix, I get a WinZip.  The WinZip doesn't appear to contain a pbix file - so there is nothing to open from Power BI desktop.  Selecting "open" rather than save the WinZip doesn't open it in Power BI either. What am I doing wrong here?

**Comment by kfollis** [comment]
Hi @SMay2020 - Is this the article that has the link: https://docs.microsoft.com/en-us/power-bi/create-reports/sample-human-resources#get-the-sample? I didn't repro your experience with the link in this article - the .pbix wasn't zipped for me. If the link you were using is in a different article, can you send the URL so I can check it out? Thanks!

**Comment by SMay2020** [comment]
Yes.  It is that link. I'm using desktop not service so need to download the file.
I've just tried to attach a screen shot.  It said uploaded but I can't see that its attached.

This is the link I'm using.
https://download.microsoft.com/download/6/9/5/69503155-05A5-483E-829A-F7B5F3DD5D27/Human%20Resources%20Sample%20PBIX.pbix

**Comment by SMay2020** [comment]
Yes.  It is that link. I'm using desktop not service so need to download the file.
I've just tried to attach a screen shot.  It said uploaded but I can't see that its attached.

This is the link I'm using.
https://download.microsoft.com/download/6/9/5/69503155-05A5-483E-829A-F7B5F3DD5D27/Human%20Resources%20Sample%20PBIX.pbix

**Comment by SMay2020** [comment]
There is no pbix file in the link for me.  Just a ZIP file called PBIX.zip.  When I click on the link it says "What do you want to do with the Human Resources Sample PBIX.zip (10.8MB)?  From: download.microsoft.com"  
When it downloads its contains multiple folders and files but none of these are pbix files.

**Comment by SMay2020** [comment]
Can you email me the .pbix file?

**Comment by kfollis** [comment]
Sorry you're still having problems, @Smay2020. I'm assigning this to the author of the article that I linked above to investigate the link that's giving you trouble. They'll follow up soon.

**Comment by maggiesMSFT** [comment]
Hi, @SMay2020 -- not sure what to tell you. I just tried the link for the PBIX file. It downloaded, and I was able to open it in Power BI Desktop. Not a ZIP file, just a single PBIX file. 
To be sure we're doing the same thing: In this section: https://docs.microsoft.com/en-us/power-bi/create-reports/sample-human-resources#get-the-pbix-file-for-this-sample
Select the blue text, ".pbix file", which I have outlined in red in the following screen shot:
![image](https://user-images.githubusercontent.com/12401230/87103425-d3ac4c80-c209-11ea-89a4-dc881b76dbf1.png)
Beyond that, what browser are you using? Not that it should matter. I have downloaded the file in Chrome and in Edge without problems.

**Comment by SMay2020** [comment]
Yes.  That’s the link I’ve been using.  I use the Edge browser (the same thing happens with Internet Explorer).

**Comment by SMay2020** [comment]
How do I attach a screen shot?!!!  Pasting doesn't work.  Saving into a Word doc and dragging doesn't work!!!

**Comment by maggiesMSFT** [comment]
Hi, @SMay2020 -- I don't know why you're having this issue. I can download it from the link you shared. Working on another option.

**Comment by maggiesMSFT** [comment]
Hi, @SMay2020 -- good news. I got the HR sample PBIX file saved to the Power BI Desktop Samples GitHub repo, https://github.com/microsoft/powerbi-desktop-samples/tree/master/Sample%20Reports
So you can go download it from there.
Cheers!
