### ISSUE TITLE
Complex dataTypes

### ISSUE THREAD

**Issue by emielvangoor** [MicrosoftDocs/powerbi-docs#2352]
Hello..

Is it also possible to push an complex datatype? (e.g. array of strings or objects)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edecc138-c6b3-86d8-9688-344772f94284
* Version Independent ID: 97e3d536-c49a-1b4d-e008-899e347f94a5
* Content: [Power BI dataset properties - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/api-dataset-properties)
* Content Source: [powerbi-docs/developer/automation/api-dataset-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/api-dataset-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the question, @emielvangoor! I'm assigning this issue to the author to check into it.

**Comment by KesemSharabi** [comment]
Hi @emielvangoor,

I double checked with our development team, and we don't support complex datatypes. For more information see the [New features for the Power BI Dataset API](https://powerbi.microsoft.com/sv-se/blog/newdatasets/) blog post.

Here are some restrictions per datatype (taken from the blog):
|Datatype         |Restrictions         |
|---------|---------|
|Int64         |*Int64.MaxValue* and *Int64.MinValue* are not allowed.         |
|Double         |*Double.MaxValue* and *Double.MinValue* values are not allowed. *NaN* isn't supported. *+Infinity* and *-Infinity* are not supported in some functions (such as Min and Max).         |
|Datetime         |During data loading we quantize values with day fractions to whole multiples of 1/300 seconds (3.33ms).         |
|String         |Up to 128K characters.         |

Hope this helps,

Kesem
