### ISSUE TITLE
PowerBI Datagateway silent installation fails on windows datacenter docker image

### ISSUE THREAD

**Issue by EruantalonJS** [MicrosoftDocs/powerbi-docs#2353]
Hi,

I'm trying to install the PowerBI datagateway in a docker image of windows datacenter (not core). I have found that, in a regular windows datacenter VM this works correctly, needing no user input, but on a docker image it stays stalled in the "Install-Datagateway" step, with the following messages:

> PS C:\gateway> Install-DataGateway -AcceptConditions
> Downloading installer.
> Completed installer download.
> Starting to install data gateway on server.

I've tried multiple options but there seems to be no verbose option that works for this commnand. In the documentation I've not found any reference to the silent installation not being available in a docker image, only that it would not work in windows datacenter core versions.

I'm not sure if this is a bug in the command, or if there is a gap in the documentation

---------------------------------------------

For reference, I'm following the documentation in this article: https://docs.microsoft.com/en-us/powershell/module/datagateway/install-datagateway?view=datagateway-ps

This is the base image I'm using ( I'm installing Powershell 7 on it on the docker build): mcr.microsoft.com/windows:1903

And this is the code I'm running:

```
New-ItemProperty -Path HKLM:Software\Microsoft\Windows\CurrentVersion\policies\system -Name EnableLUA -PropertyType DWord -Value 0 -Force

$tenantId = "****"
$applicationId = "****"
$secretKey = ConvertTo-SecureString -String "****" -AsPlainText -Force

Install-Module -Name DataGateway -Force

Connect-DataGatewayServiceAccount -ApplicationId $applicationId -ClientSecret $secretKey -Tenant $tenantId
Install-DataGateway -AcceptConditions

```

**Comment by paulinbar** [comment]
Thanks for your comment, @EruantalonJS. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
