### ISSUE TITLE
Help video is out of date (4 years old)

### ISSUE THREAD

**Issue by davidlamb** [MicrosoftDocs/powerbi-docs#2354]
[Enter feedback here]
The video in this help document is 4 years old. The workflow that shows is not the same anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Thanks for your comment, @davidlamb. I am forwarding it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Good point, @davidlamb ! Deleting it now. Update will be live tomorrow afternoon, July 9. Thanks!
