### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by jatorres1190** [MicrosoftDocs/powerbi-docs#2355]
Hi, 

Here is states that we can enable this option in the admin portal to export to PNG or image.
![image](https://user-images.githubusercontent.com/67752141/86498277-664c7780-bd42-11ea-9fb6-0c47a9fef0d5.png)

I have been checking the admin portal, tenant settings and there is no option to export report as image file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#code-examples)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for your comment @jatorre. Indeed there doesn't seem to be such an option in the tenant settings. I am forwarding your comment on to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @jatorres1190,

I understand from the development team that this is a GUI bug. The ETA for resolving the bug is the end of the week. Please try looking for the tenant image settings in the admin portal early next week.

Thanks,

Kesem

**Comment by jatorres1190** [comment]
Hi,

So will you provide a solution as well?
We can't seem to find how to enable the export to PNG.

Thanks

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by KesemSharabi** [comment]
Hi @jatorres1190,

Once the bug is fixed you'll be able to enable this setting in the admin tenant settings. Once enabled you'll be able to export to PNG. Please give it a try early next week.

Thanks,

Kesem

**Comment by jatorres1190** [comment]
Hi!

Great, hopefully this option will now be visible in the tenant settings.
Will you contact me to let me know or should I be testing every once in a while?

Thanks
Jose


________________________________

**Comment by KesemSharabi** [comment]
Hi @jatorres1190,

Looks like the *export reports as images* option is now available.

![Export report as an image file.](https://user-images.githubusercontent.com/54834915/87542635-f4621f80-c6ab-11ea-950f-edc99478ad85.png)

Hope this helps,

Kesem

**Comment by jatorres1190** [comment]
Hi

This is working now!
Thanks a lot! 🙂



________________________________

**Comment by KesemSharabi** [comment]
HI @jatorres1190,

Glad to hear it's working and thanks for getting in touch.

Kesem
