### ISSUE TITLE
Need startBillingDataWindow and endBillingDataWindow options for Azure Cost Management

### ISSUE THREAD

**Issue by lundejd** [MicrosoftDocs/powerbi-docs#2356]
Our EA has passed and I can no longer use the 36 month option, as it now assumes the current month + 35 back, which errors out since the EA expired last month.  With the previous connectors I could tell it to go a specific 36 month window but I don't see the option here.  

We need to pull our past 36 months then append the current in order to keep our reports valid. Right now it errors out and won't even load:

DataSource.Error: Web.Contents failed to get contents from 'https://management.azure.com/providers/Microsoft.Billing/billingAccounts/XXXXXXX/providers/Microsoft.Consumption/usageDetails/download?api-version=2019-05-01-preview&$filter=properties/usageStart+ge+'2017-07-01'+and+properties/usageStart+le+'2020-07-04'' (400): Bad Request
Details:
    DataSourceKind=AzureCostManagement
    DataSourcePath=Enrollment Number;XXXXXXX
    Url=https://management.azure.com/providers/Microsoft.Billing/billingAccounts/XXXXXX/providers/Microsoft.Consumption/usageDetails/download?api-version=2019-05-01-preview&$filter=properties/usageStart+ge+'2017-07-01'+and+properties/usageStart+le+'2020-07-04'

**Comment by paulinbar** [comment]
Hi @lundejd, you've reached the Power BI documentation team. I think your question would be better addressed to [Azure support](https://portal.azure.com/?feature.customportal=false#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview). Closing this issue for us now, but if you think I'm mistaken please feel free to reopen. Thanks!
