### ISSUE TITLE
How to connect Facebook to Power BI Desktop?

### ISSUE THREAD

**Issue by User31222** [MicrosoftDocs/powerbi-docs#2357]
I have trouble connecting Facebook to Power BI Desktop. The Facebook app is not shown under "Online Services". Any workaround for this? Thanks!

<img width="592" alt="Screenshot 2020-07-06 at 11 28 46 AM" src="https://user-images.githubusercontent.com/67886814/86553004-21138a00-bf7c-11ea-97e0-1bee4c3295c2.png">

**Comment by maggiesMSFT** [comment]
Hi, @User31222 -- bad news. According to this article, https://docs.microsoft.com/en-us/power-bi/connect-data/service-facebook-connector, the Facebook connector has been discontinued as of April 2020. I suggest going to https://ideas.powerbi.com/forums/265200-power-bi to ask about adding it, or searching to see if someone has already suggested it.
