### ISSUE TITLE
Filtering a report using query string parameters in the URL works only the first time

### ISSUE THREAD

**Issue by s3r3n3** [MicrosoftDocs/powerbi-docs#2358]
Hi,

Filtering a report using URL seems to work only the first time the url is used. After the first time, the very same url no longer works as the PowerBI shows all data without filter.

Could you please check?

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @s3r3n3 -- Hmmm, I'll check. That shouldn't be the case. I'll test it.

**Comment by maggiesMSFT** [comment]
Hi again, @s3r3n3 -- how are you getting to the report the 2nd and subsequent times? If I copy the link, every time I select it I get the same filtered view.

**Comment by s3r3n3** [comment]
Hi @maggiesMSFT ,

Thanks a lot for checking the issue. 

My PowerBI has a source table whose name contains only digits, eg _0050_. Using url to filter data, the filter function worked the first time. After that, the same url didn't work anymore.

I've just tested the same data but in a different table whose name doesn't start with a digit, eg _TestAbc_ or _Test123_. Then using url to filter data from this report works perfectly all the time.

**Comment by maggiesMSFT** [comment]
Hi, @s3r3n3 -- I've checked. I'm told you should enter a support ticket, as you have clear repro steps. 
Hope that helps!
