### ISSUE TITLE
Topology restrictions

### ISSUE THREAD

**Issue by DaniilMaslyuk** [MicrosoftDocs/powerbi-docs#2359]
The phrase "topology restrictions" is very unclear and should be reworded to make it easier to understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand)
* Content Source: [powerbi-docs/transform-model/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by maggiesMSFT** [comment]
Hi, @DaniilMaslyuk -- thanks for the suggestion! Assigned to the author to address.

**Comment by peter-myers** [comment]
Hi @DaniilMaslyuk - thanks for your feedback. We agree with your comments, and we're actively working with engineering to gain a deeper understanding. Stay tuned for an update to this article when we learn more. #please-close
