### ISSUE TITLE
Usage Metrics under New App Workspace?

### ISSUE THREAD

**Issue by darthbone** [MicrosoftDocs/powerbi-docs#236]
I don't see the button for Usage Metrics Report under the Dashboards page anymore. My manager likes to view these reports regularly, and I have no idea how to generate them anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @darthbone -- thanks for your comment! Yes, usage metrics aren't enabled yet for the preview. This article mentions that:
•	Usage metrics aren't supported yet.
Hope that helps!

**Comment by MartinaPD** [comment]
Hello, 
If the Usage Metric is not enabled yet, Can you advice how to set the Workspace back to standard? eg... not using the New workspace (preview).  Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @MartinaPD -- thanks for your question! There's no way to do that, no. There's no migration path. You can just create another workspace using the Create Workspace button.

**Comment by MartinaPD** [comment]
Hello Maggie,
thank you. 
I think I could not find the button :).
I can now.... shame I have to redo my work :(.
