### ISSUE TITLE
SelectionManager

### ISSUE THREAD

**Issue by Hamzamusameh** [MicrosoftDocs/powerbi-docs#2360]
Hi,

From where I will found (to import) selectionManager, please ?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4937ba26-0e7a-54aa-b7e0-918db3fb6bdf
* Version Independent ID: d948fd0c-8b97-7184-374b-56f04b46dd70
* Content: [Add Drill-Down support - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/drill-down-support)
* Content Source: [powerbi-docs/developer/visuals/drill-down-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/drill-down-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @Hamzamusameh . This issue has been assigned to the doc author for review. The author may need to reach out for additional information.  Thank you.

**Comment by KesemSharabi** [comment]
Hi @uve, 

Can you please assist with this?

Thanks,

Kesem

**Comment by uve** [comment]
@Hamzamusameh, you this construction to create a new instance of Selection Manager: 
`this.selectionManager = this.host.createSelectionManager();`
