### ISSUE TITLE
Missing closing /a element

### ISSUE THREAD

**Issue by smearp** [MicrosoftDocs/powerbi-docs#2361]
On https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi, everything from the "Manage items you own" header on down appears as if it is a giant link.  It appears to be missing a closing </a> element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @smearp . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Wow, good catch, @smearp -- thanks for pointing that out! Fixing it now. Update will be live tomorrow afternoon, July 9.
