### ISSUE TITLE
Installer files for older versions

### ISSUE THREAD

**Issue by ReBae** [MicrosoftDocs/powerbi-docs#2362]
Where can we find the actual installer files for older Power BI Report Server versions? 

The page only lists details of the older releases, doesn't contain the installer files themselves.

Could you also please consider allowing access to at least a year's back of releases? 6 months is too short. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ReBae.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by ReBae** [comment]
Thank you, @KesemSharabi, I should have added: the post was made after spending the better part of the day hunting through not only Power BI Community but also the world wide web.

**Comment by mihart** [comment]
Thanks for your comment, @ReBae . This looks like a support request or product question rather than documentation feedback. I hope that you were able to find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 
All the best,
the DOCS team
