### ISSUE TITLE
Please specify that O365 Groups are not supported for RLS

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#2363]
It would be nice to know that O365 Groups are not supported for RLS as they are supported in Workspace access and App permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls#add-members)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @Hikmer. I've noted your comments and will address them in the rewrite of the RLS articles that is now underway. In the meantime I am closing this issue now. Thanks for your input!
