### ISSUE TITLE
I can´t export Totals from a table

### ISSUE THREAD

**Issue by gabolivaf18** [MicrosoftDocs/powerbi-docs#2364]
I need export a table with its totals but when I export it doesn´t bring me the totals. Who can I export this data?

**Comment by maggiesMSFT** [comment]
Hi, @gabolivaf18 -- a question just to clarify the issue. Are you in the Power BI service, and you selected More options (...) then Export Data? 
![image](https://user-images.githubusercontent.com/12401230/87714460-a65b2380-c760-11ea-9576-dcc83c375f2b.png)
As spelled out in this article: https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#export-data-from-a-report
If so, then you're right, it doesn't export a total. You can add a total in Excel. 
Hope that helps.

**Comment by maggiesMSFT** [comment]
Hi, @gabolivaf18 -- receiving no reply, I'll assume that resolved your problem. If not, feel free to reopen. Thanks!
