### ISSUE TITLE
The code in the Doc is not working or well explained.

### ISSUE THREAD

**Issue by laancaro** [MicrosoftDocs/powerbi-docs#2365]
[Enter feedback here]
The example code is not working anymore. It's probably deprecated. 

I got too many errors. 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)	walkthrough_push_data	C:\Users\lacamach\source\repos\walkthrough_push_data\walkthrough_push_data\Program.cs	19	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientCredential'	walkthrough_push_data	C:\Users\lacamach\source\repos\walkthrough_push_data\walkthrough_push_data\Program.cs	47	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 3: cannot convert from 'System.Uri' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.UserAssertion'	walkthrough_push_data	C:\Users\lacamach\source\repos\walkthrough_push_data\walkthrough_push_data\Program.cs	47	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 856c2459-1221-d37d-a977-7baf42bedc80
* Version Independent ID: d99e1b35-749d-a75b-3f1a-f6502eb022ee
* Content: [Authenticate users & get Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/embedded/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @laancaro -- Assigning your issue to the author of the article. 
Can you provide more info about what you're doing when you see these errors?

**Comment by KesemSharabi** [comment]
Hi @laancaro, 

I'm working on updating the code snippets in the [Get an Azure AD access token for your Power BI application](https://docs.microsoft.com/power-bi/developer/embedded/get-azuread-access-token) article, with the help of our development team.

Please note that this may take some time.

Thanks,

Kesem

**Comment by laancaro** [comment]
Thanks!! I just copy-paste the code. 
Even I noted that the GetToken method is diferent in step 1 and 2 of documentation.

**Comment by KesemSharabi** [comment]
Hi @laancaro,

This issue is in my backlog and I'll refresh the article as soon as I can.

Thanks,

Kesem
