### ISSUE TITLE
Add explanation of 'lock filter' and hide filter button

### ISSUE THREAD

**Issue by adrianjellis** [MicrosoftDocs/powerbi-docs#2366]
I'm using PBI Desktop June 2020. There is a 'lock filter' and what looks like a show/hide filter toggle, however these are not explained on the help page. I was hoping the show/hide toggle would allow me to quickly enable/disable a filter without having to clear it, but it doesn't appear to do that. Could you include an explanation of the functionality for these two features? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1465b3a1-a6de-e2f3-154c-817ea13aa4f0
* Version Independent ID: 20ea6924-2307-d6ef-d601-7f949fe58944
* Content: [Tour the report Filters pane - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-filter)
* Content Source: [powerbi-docs/consumer/end-user-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-report-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @adrianjellis -- you landed on the article for using filters rather than creating them. Sorry about that! This article should help:
https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-report-filter#lock-or-hide-filters
