### ISSUE TITLE
Publishing report to existing Power BI app workspace

### ISSUE THREAD

**Issue by jacintmr** [MicrosoftDocs/powerbi-docs#237]
I made some changes on my Power BI Desktop report (.pbix) and I wanted to reflect them on my published app workspace. But whenever i click Publish, it always says Internal Server Error. Can somebody help me with my concern? Appreciate your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Thanks for your comment, @jacintmr . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
