### ISSUE TITLE
Embed token best practices with respect to expiration and reuse

### ISSUE THREAD

**Issue by jdanyow** [MicrosoftDocs/powerbi-docs#2370]
> #### Create the embed token
> Generate an embed token, which can be used from the JavaScript API. There are two types of APIs, the first group contains five APIs, each generates an embed token for a specific item. The second group, which contains only one API, generates a token that can be used to embed multiple items.
> https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#create-the-embed-token

Looking for some more details about the embed token. If I have a page that is embedding a power bi report, should the embed token be reused or should I be regenerating the embed token for each page view?

The API Docs indicates there's an expiration time for the token:
https://docs.microsoft.com/en-us/rest/api/power-bi/embedtoken/generatetoken#embedtoken

What is the expiration period? Minutes? Hours? Can it be controlled?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @jdanyow, thanks for reaching out to us with your question. I am forwarding it on to the doc author for consideration. Thanks!

**Comment by kthejoker** [comment]
@jdanyow The default time for token expiration is 1 hour

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#:~:text=The%20default%20lifetime%20of%20the,element%20in%20the%20token.

You can set the token lifetime during your request; The minimum refresh token time is 10 minutes and the maximum is 90 days.

**Comment by KesemSharabi** [comment]
Hi @jdanyow,

I just confirmed with one of our developers, the embed token is valid as long as the AAD token is valid. In other word, the expiry time of the embed token is inherited from the AAD token.

I hope this helps,

Kesem

**Comment by KesemSharabi** [comment]
Hi @jdanyow,

For more information, please see [Configurable token lifetimes in Microsoft identity platform (Preview)](https://docs.microsoft.com/azure/active-directory/develop/active-directory-configurable-token-lifetimes) and contact the Azure AD support team.

Thanks,

Kesem
