### ISSUE TITLE
Not very helpful

### ISSUE THREAD

**Issue by how-to-data** [MicrosoftDocs/powerbi-docs#2371]
Did not find the guidance helpful as it does not tally with what is now required, in addition it appears that either someone has changed the location for publishing the App Owns Data project, or Microsoft expects that businesses will have the clients on site viewing the project, as the destination in the project is localhost. I would not recommend following these instructions if you do not have fairly advanced web app building skills, PowerBI services skills and Azure AD skills. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#move-to-production)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @how-to-data. Thanks for your comments. I am forwarding it along to the doc author for further consideration.

**Comment by KesemSharabi** [comment]
Hi @how-to-data,

Thanks for your feedback.

I'm in the process of updating all the embedded analytics tutorials, as some of the information there is outdated.

Please note that this may take some time.

Kesem
