### ISSUE TITLE
Print limitation:  Data only in current view

### ISSUE THREAD

**Issue by elleneg** [MicrosoftDocs/powerbi-docs#2374]
This article is omitting the very significant and well-communicated point of user frustration that you can only print information in the current view.  Any data that you have to scroll to see is not printable.  I don't know why - in Tableau, Domo, Excel this is a built-in feature I never thought twice about scoping out in requirements when switching to BI. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bdf6ff3-a8d1-9d1d-e700-b2d3526c3ab3
* Version Independent ID: 48937cff-0cde-3e81-6a03-7288562af6de
* Content: [Export reports to PDF - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-pdf)
* Content Source: [powerbi-docs/consumer/end-user-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @elleneg . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @elleneg, 
Thank you for contributing to the docs.  I've updated the article to include this limitation.  To see the PDF feature improved, add your vote to this idea on ideas.powerbi.com -- it's a really good idea.
Take care,
Michele
