### ISSUE TITLE
Please clarify "This template app does not support GitHub Enterprise" - disambiguate between Enterprise Cloud or Enterprise Server

### ISSUE THREAD

**Issue by scarbone-msft** [MicrosoftDocs/powerbi-docs#2375]
👋 team - the verbiage "This template app does not support GitHub Enterprise" should be changed to reflect the correct GitHub product (i.e. GitHub Enterprise Cloud or GitHub Enterprise Server) to disambiguate as it is currently somewhat confusing - 🙇‍♂️ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github#system-requirements)
* Content Source: [powerbi-docs/connect-data/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @scarbone-msft , thanks for your comment. Let me check into this and I'll update the documentation accordingly.

**Comment by scarbone-msft** [comment]
Thank you 🙇‍♂️   Would you be able to point me to the team who is working on the PBI Template App for GitHub?  One of my large Microsoft/GitHub customers (with a number of Microsoft MVPs on-staff would like to connect with the team...

**Comment by paulinbar** [comment]
Hi Steve, I responded by email. I'm working on this so I'll close this Github issue for now. Please don't hesitate to reach out to me again though should the need arise. Thanks!
@scarbone-msft
