### ISSUE TITLE
Guide needed if customers are using SAP Cryptographic Library

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2376]
In the doc, it is mentioned, "While this guide uses OpenSSL as the HANA server's cryptographic provider, **SAP recommends you use the SAP Cryptographic Library (also known as CommonCryptoLib or sapcrypto)** instead of OpenSSL to complete the setup steps in which we establish the trust relationship."

We have a customer who is using SAP Cryptographic Library as recommended. So need guide accordingly to setup gateway for SAML SSO, The current instructions are for OpenSSL so not applicable for customers who use SAP recommendations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa7ca8d8-0f83-2cd6-57b1-04fc8e04981b
* Version Independent ID: 196ee3c3-aa88-f8ca-c725-33bf77be0db5
* Content: [Use Security Assertion Markup Language (SAML) for SSO from Power BI to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-saml)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-saml.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-gateway-sso-saml.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by mihart** [comment]
Hi @haider392 ,
I see that this Git issue is a bit old, so I'm going to close it.  I checked the article, and SAP Cryptographic Library instructions were added :-) 
All the best,
the DOCS team
