### ISSUE TITLE
Missing version on changelog

### ISSUE THREAD

**Issue by nava17490** [MicrosoftDocs/powerbi-docs#2378]
Hi,

There is a missing versión in the PowerBI Report Server change log. Version 2.81.5831.1181 is not appearing in the PowerBI Desktop optimized for Report Server but is available for downloading on the following link https://www.microsoft.com/en-us/download/details.aspx?id=56722 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by maggiesMSFT** [comment]
Hi, @nava17490 -- thanks for asking! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Thanks, @nava17490 ! Got the missing version added. Change will be live tomorrow afternoon.
