### ISSUE TITLE
Publishing to XMLA Enpoint Via Visual Studio Does Not Work for MFA Enabled Accounts

### ISSUE THREAD

**Issue by TravisKale** [MicrosoftDocs/powerbi-docs#2379]
The documentation lacks pointing out  that if your Azure Active Directory account is MFA enabled, publishing to the XMLA endpoint via Visual Studio will fail.   Error encountered when trying to do this is:

"Cannot deploy metadata. Reason: An error occurred while connecting to the server"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1b920c-639a-a627-58f2-e8fd69c9ef7d
* Version Independent ID: ab13e62f-0629-0aed-7e85-a902e150f9b1
* Content: [Dataset connectivity and management with the XMLA endpoint in Power BI Premium (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools#deploy-model-projects-from-visual-studio-ssdt)
* Content Source: [powerbi-docs/admin/service-premium-connect-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-connect-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by kfollis** [comment]
Thanks for the comment, @TravisKale ! I've assigned this issue to the writer for followup.

**Comment by Minewiskan** [comment]
@TravisKale - MFA is fully supported when deploying from VS to Power BI Premium. Make sure [Read\Write is enabled for the capacity](https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions#how-to-determine-client-library-version),  verify you're using the latest [Analysis Services projects extension](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftAnalysisServicesModelingProjectsl) in VS, and the latest [client libraries](https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions#how-to-determine-client-library-version) are installed. If after updating those, and you still cannot connect, it's best to contact support.
