### ISSUE TITLE
"How to update a visual" - Multi-version deployment not supported

### ISSUE THREAD

**Issue by mthierba** [MicrosoftDocs/powerbi-docs#238]
The "How to update a visual" suggests that multiple versions of the same visual can be uploaded as long as they get a different title (but maintain the same Visual ID):

&gt; However, if the new version of the visual might break any usage or data structure of the previous version of the visual, then do not replace the previous version. Instead, you should create a new listing for the new version of the visual. For example, add a new version number (version X.X) to the title of the new listed visual. This way it is clear that it is the same visual just with an updated version number, so existing reports do not break their functionality. Again, make sure the Visual ID remains unchanged.

That does not seem to be working as described. I have just tried exactly that, and an error message "There was a problem adding this custom visual. It already exists" is displayed. It appears that this would only be supported if a new Visual ID were assigned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-portal#organization-visuals)
* Content Source: [powerbi-docs/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-portal.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Thank you for your comment. This has been assigned to the document author.

**Comment by mgblythe** [comment]
Assigning to @markingmyname to address

**Comment by markingmyname** [comment]
@mthierba Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@uve, can you assist, please?

**Comment by uve** [comment]
This is a question  about importing Custom Visuals into Organizational Store. Assigning task to @sranins  to provide an answer.

**Comment by markingmyname** [comment]
@sranins

**Comment by uve** [comment]
Each Custom Visual should have only one unique GUID.
PowerBI always loads the latest version of the visuals from CDN based on this GUID number, even if you imported your own version of the visual with the same GUID to the report.
So administrators aren't able to import multiple versions of the visual with one GUID.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag the assignee in your reply. We will gladly continue the discussion, and we will reopen the issue.
