### ISSUE TITLE
how to read table of PDF file with arabic language

### ISSUE THREAD

**Issue by sallllam** [MicrosoftDocs/powerbi-docs#2382]
I tried to read a table in PDF file whit Arabic Letters but when it uploaded to the power bi its characters is unreadable
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ab70d2-6a8d-9457-9fe0-b7e5a11f7a23
* Version Independent ID: 8d847641-59f8-8914-799d-0c1c7ccad9a6
* Content: [Connect to a PDF file in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-pdf)
* Content Source: [powerbi-docs/connect-data/desktop-connect-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @sallllam, thanks for reaching out to us with your comment. I have forwarded it on to the doc author for further consideration. Have you considered the information here: https://docs.microsoft.com/en-us/power-bi/fundamentals/supported-languages-countries-regions#choose-the-locale-for-importing-data-into-power-bi-desktop? I am not sure it will solve your problem but it might be worth a try. I also encourage you to post your issue in the [Power BI Community]( https://community.powerbi.com) - there is a lot of experience out there. Or you can check our [support page](https://support.powerbi.com). Thanks!

**Comment by mihart** [comment]
Hi @sallllam ,
I see that this Git issue is a bit old, and we haven't heard back from you. I hope that you were able to get your questions answered. If not, please submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
