### ISSUE TITLE
Table showing features / limits / comparison for Power BI Embedded vs Power BI Pro

### ISSUE THREAD

**Issue by sethsanu** [MicrosoftDocs/powerbi-docs#2383]
Would love to see a basic table that shows the differences in features and limitations between PBI Embedded and PBI Pro. For example: Paginated Reports cannot use Power BI Datasets as a data source in PBI Embedded (works with PBI Pro). A lot of the good information in this FAQ could also be summarized in tabular form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37c7960-448a-0f10-c84a-f9c531452320
* Version Independent ID: 4867daee-c097-cde7-81c9-4f2a44a4f5b3
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @sethsanu. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @sethsanu, 

Power BI Pro is a user license and Power BI Embedded is a Premium offer solution. Pro doesn't require a capacity, while Embedded [requires a capacity](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity). Therefore comparing them doesn't make sense.

You can see a comparison between Power BI Pro and Power BI Premium if you scroll down our [pricing](https://powerbi.microsoft.com/pricing/) page.

Hope this helps,

Kesem
