### ISSUE TITLE
Documentation Issue: Power BI Datasets as a data source for paginated reports are not supported in PBI Embedded

### ISSUE THREAD

**Issue by sethsanu** [MicrosoftDocs/powerbi-docs#2384]
Please create a note, and cross reference https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports-customers, “Power BI Datasets are not supported as a data source.”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a5444a-ce6c-9a0c-3e84-832e67b75d47
* Version Independent ID: df2623ba-2917-faf6-0077-e9d182a9e96c
* Content: [Supported data sources for Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-data-sources)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports/paginated-reports-data-sources.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @onegoodsausage
* Microsoft Alias: **andremi**

**Comment by paulinbar** [comment]
Hi @sethsanu, thanks for reaching out to us with your comment! I have forwarded it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Thanks, @sethsanu ! I added that to the article, https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-data-sources
