### ISSUE TITLE
Enhanced metadata preview for DQ dataflows

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2386]
Hi, has this restriction been lifted?

_DirectQuery for dataflows does not work with the enhanced metadata preview feature enabled. This exclusion is expected to be removed in an upcoming monthly release of Power BI Desktop._

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4696f74d-bce4-3808-008a-4375afdb71c5
* Version Independent ID: 339f52a6-9d08-4634-76f4-5195c3b475ec
* Content: [Use DirectQuery with dataflows in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-directquery)
* Content Source: [powerbi-docs/transform-model/service-dataflows-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-directquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @asocorro.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
