### ISSUE TITLE
Steps for "Task: Create a measure formula" are not in the right order

### ISSUE THREAD

**Issue by erikmartell** [MicrosoftDocs/powerbi-docs#239]
Proposed correct order might be:

3. type CALCULATE  and opening parenthesis.
4. type SUM and opening parenthesis.
5. type Sales[SalesAmount] and close the SUM parenthesis
....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [DAX basics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quickstart-learn-dax-basics)
* Content Source: [powerbi-docs/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by erikmartell** [comment]
I just noticed it was mentioned by JohnYounie, but issue is Closed and still not corrected

**Comment by davidiseminger** [comment]
Thanks for your comment, @erikmartell. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
added tag

**Comment by davidiseminger** [comment]
Thanks for your comment, reassigning to get more input from author.

**Comment by Minewiskan** [comment]
@erikmartell  You are correct. I haven't seen this article in years. Not sure how it got twisted up. Open source, I guess. It's been corrected. Thanks for letting us know.
#please-close

**Comment by erikmartell** [comment]
Thank you very much for the correction and feedback
