### ISSUE TITLE
AndrewMa not AndrewMa 

### ISSUE THREAD

**Issue by ADefWebserver** [MicrosoftDocs/powerbi-docs#2390]
It should say Andrew Ma (with a space) not AndrewMa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @ADefWebserver, thanks for pointing that out! Forwarding your observation over to the doc author.

**Comment by KesemSharabi** [comment]
@ADefWebserver,

Thank you for spotting this!

I added a gap between 'Andrew' and 'Ma' - see [Adding roles with Power BI Desktop](https://docs.microsoft.com/power-bi/developer/embedded/embedded-row-level-security#adding-roles-with-power-bi-desktop).

Thanks again for your contribution,

Kesem
