### ISSUE TITLE
Cross report drill through function is not working in Power BI Report server

### ISSUE THREAD

**Issue by ey1020park** [MicrosoftDocs/powerbi-docs#2391]
Hi.
I am using Power BI Report server(May 2020 installed)
I want to use cross report drill through function in power bi report server. 
Even though cross report setting is shown on power bi desktop but it's not working when i published to PBIRS.

(I used the demo files from guy in a cube site
https://github.com/guyinacube/demo-files/blob/master/video%20demos/PBIX/2019/20190501%20-%20Cross%20Report.zip )

I wonder the functionality is available or not in PBIRS.

**Comment by maggiesMSFT** [comment]
Hi, @ey1020park -- good question! I'm checking and will get back to you. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ey1020park -- OK, checked. No, it's not supported. I need to add that statement to the docs. Were you looking at a specific article for this info?

**Comment by ey1020park** [comment]
Hi, @maggiesMSFT 
-- thank you for the clear comment.
I was looking at below article.
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-cross-report-drill-through#:~:text=To%20use%20cross%2Dreport%20drillthrough%2C%20select%20the%20source%20report%20in,then%20select%20the%20drillthrough%20target.

BTW, is there any possibility to be able to use the function in PBIRS? 
Many useful functions are only available in power bi server. :(

**Comment by maggiesMSFT** [comment]
Hi, @ey1020park -- thanks for the link. I'm adding a Considerations section to the article and adding it there. 
What's possible/not possible Power BI Report Server vs. the Power BI service: If you think of report functionality as 'inter-report' or maybe 'extra-report', those sorts of features don't necessarily work in the report server. If you think of 'intra-report' features, those do work. Make sense?

**Comment by maggiesMSFT** [comment]
Oh, I realized I can add it to this doc, too
https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service
