### ISSUE TITLE
Incremental Refresh not working with Template Apps

### ISSUE THREAD

**Issue by Data-touille** [MicrosoftDocs/powerbi-docs#2392]
Incremental refresh on a Power BI dataset deployed through a Template App in Power BI Service doesn't seem to work.
The dataset refresh in the destination (client) tenant always performs a FULL refresh even though we setup an incremental refresh in the initial Power BI Desktop file (.pbix).
In addition, the Power Query parameters RangeStart & RangeEnd (required for incremental refresh but usually hidden) clearly appear in the dataset settings of the destination tenant.
I can't find this info on the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0d7108-2bf9-1b09-a391-440a0c0e8dfb
* Version Independent ID: 0c67568f-5885-41d8-9b19-89b2a9fd4b3c
* Content: [What are Power BI template apps? - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-overview)
* Content Source: [powerbi-docs/connect-data/service-template-apps-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-template-apps-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi, @Data-touille, thanks for contacting us about this issue. Let me check into this and I'll get back to you. 
@teddybercovitz

**Comment by LeroyMeares** [comment]
Hi @teddybercovitz @paulinbar 

Has there been any further investigation into this?

Regards
Leroy

**Comment by paulinbar** [comment]
Hi @LeroyMeares and @Data-touille, indeed, template apps don't currently support incremental refresh. This situation may change in the coming year. In the meantime, I have added a limitation concerning incremental refresh to the template app documentation . Thanks for calling that out!
