### ISSUE TITLE
Section unclear if its computer or user account delegation being changed

### ISSUE THREAD

**Issue by prlipscombe** [MicrosoftDocs/powerbi-docs#2393]
This related to the 3rd section
https://docs.microsoft.com/en-us/power-bi/report-server/azure-application-proxy#3-configure-delegation-settings

Points 2 and 4 reference finding/changing the service account settings in AD (basically a user account)
However point 6 says trust this computer for delegation - which is not what a user object will show in AD but is what a computer object will show.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d3834a-e56a-f014-7a0c-ff3da615c8f2
* Version Independent ID: c78ecd60-559f-902f-6023-3448199bd67c
* Content: [Configure Power BI Report Server with Azure Application Proxy - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/azure-application-proxy#3-configure-delegation-settings)
* Content Source: [powerbi-docs/report-server/azure-application-proxy.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/azure-application-proxy.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @prlipscombe -- thanks for asking! I'll check and get back to you and see if we need to update the docs.

**Comment by maggiesMSFT** [comment]
Thanks, so much, @prlipscombe -- updating the doc to say "Trust this user" instead.
