### ISSUE TITLE
Missing Premium SKUs in comparison table

### ISSUE THREAD

**Issue by cricex** [MicrosoftDocs/powerbi-docs#2394]
Comparison table under 'Capacity nodes' stops at the P3 SKU while P4 and P5 exist.

Additionally, P5 is mentioned on the same page here: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#subscriptions-and-licensing
And here: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#size-considerations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#subscriptions-and-licensing)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @cricex, thanks for your observations.  I am forwarding them on to the doc author for further consideration.

**Comment by mihart** [comment]
Hi @cricex , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
