### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2396]
Push datasets are not supported with Publish To Web.

While there are no limitation section on the official Push/Streaming/PubNub datasets documentation it may be worth additionally calling it out.
URL: https://docs.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web#limitations)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @itsnotaboutthecell, thanks for your observations. I am forwarding them along to the doc author for further consideration.

**Comment by maggiesMSFT** [comment]
Thanks, @itsnotaboutthecell ! Taking the conversation offline.
