### ISSUE TITLE
Desktop Report Examples Missing

### ISSUE THREAD

**Issue by msftbrian** [MicrosoftDocs/powerbi-docs#2397]
Is there somewhere else where the prediction scoring is dropped into a power bi desktop report?  There's only a quick reference to using the enhanced model for reporting

**Comment by paulinbar** [comment]
Hi @msftbrian, thanks for reaching out to us with your question. Can you send us a reference to the page you are referring to in the documentation? Thanks!

**Comment by mihart** [comment]
Hi @msftbrian ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
