### ISSUE TITLE
Connecting PowerBI to access Azure Postgres Single Server

### ISSUE THREAD

**Issue by sunilagarwal** [MicrosoftDocs/powerbi-docs#2398]
I was looking at the source databases mentioned in the documentation. I think the list of source databases need to be updated. For example, PowerBI can integrate with Azure Postgres [https://docs.microsoft.com/en-us/archive/blogs/chmitch/complete-guide-to-setting-up-power-bi-connecting-to-postgres-w-refresh-enabled]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed468ec7-192b-8ad4-da13-fc3bca5c47b8
* Version Independent ID: a93614a9-2bda-3bb5-782b-ec75cd434105
* Content: [Azure and Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-azure-and-power-bi)
* Content Source: [powerbi-docs/connect-data/service-azure-and-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-azure-and-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great - thanks for your comment! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Good point, added a link to all Azure data sources. Thanks!
