### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by trevorragle** [MicrosoftDocs/powerbi-docs#2399]
Under "Limitations and Considerations", the word "access" is repeated. This is in the 2nd row and I think it is a grammatical error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee973158-6e02-2af5-17a6-05797c9630c5
* Version Independent ID: 45a55720-c645-b221-cdaf-5da204cff706
* Content: [Share a dataset - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-share)
* Content Source: [powerbi-docs/connect-data/service-datasets-share.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-share.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @trevorragle -- thanks! Fixed it. Update will be live later this afternoon, Mon July 27.
