### ISSUE TITLE
A Known issue should be written here

### ISSUE THREAD

**Issue by CSSBAPMICHAELMA** [MicrosoftDocs/powerbi-docs#240]
Power BI Desktop Microsoft Store version don't support connect to Oracle due to a oracle driver issue. Please use the msi version downloaded from app.powerbi.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks, @CSSBAPMICHAELMA! I hope to see you submit your suggested change through other channels.

**Comment by fabianomachadors** [comment]
It worked! The solution was to download Power BI Desktop through app.powerbi.com, not from the Microsoft Store.

**Comment by RobsonRogerio** [comment]
I would like to use the MS Store version, but I get the message below. Here I have the oracle client 12.2.0 and oraons.dll is already in the folder Oracle12c \ product \ 12.2.0 \ client_x64 \ bin

Details: "The provider in use is deprecated: 'System.Data.OracleClient requires client software Oracle version 8.1.7 or later.'. Visit https://go.microsoft.com/fwlink/p/?LinkID=272376 to install the official provider. "
