### ISSUE TITLE
Broken link to "Tabular Object Model" page

### ISSUE THREAD

**Issue by chrolivier** [MicrosoftDocs/powerbi-docs#2403]
The second paragraph contains the following link to a page that doesn't exist: 
https://docs.microsoft.com/en-us/bi-reference/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo

I suspect the correct link should be the following:
https://docs.microsoft.com/en-us/analysis-services/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-gb/power-bi/connect-data/desktop-enhanced-dataset-metadata)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @chrolivier, thank you for calling our attention to this. Yes, looks like a link didn't get changed with things moved around. I'm forwarding your comment on to the doc author for review. Thanks!

**Comment by kfollis** [comment]
Link is fixed.
