### ISSUE TITLE
Power BI Embedded API to export to PDF

### ISSUE THREAD

**Issue by dcp-unifin** [MicrosoftDocs/powerbi-docs#2404]
I'm having problems getting a button to print on my .net project. I've created the methods as released in C# but stuck in how to configure the button. Can you post something to give an example on how?

 private async Task<ExportedFile> ExportPowerBIReport(
    Guid reportId,
    Guid groupId,
    FileFormat format,
    int pollingtimeOutInMinutes,
    CancellationToken token,
    IList<string> pageNames = null /* Get the page names from the GetPages API */)
        {
            try
            {
                var exportId = await PostExportRequest(Configurations.reportId, Configurations.WorkspaceId, format, pageNames);
                var export = await PollExportRequest(Configurations.reportId, Configurations.WorkspaceId, exportId, pollingtimeOutInMinutes, token);
                if (export == null || export.Status != ExportState.Succeeded)
                {
                    // Error, failure in exporting the report

                    return null;
                }
                return await GetExportedFile(Configurations.reportId, Configurations.WorkspaceId, export);
            }
            catch
            {
                // Error handling
                throw;
            }
        }

**Comment by maggiesMSFT** [comment]
Hi, @dcp-unifin -- thanks for your question. I've assigned it to the author. Could you say which article you're looking at? That will help the author troubleshoot. Thanks!

**Comment by dcp-unifin** [comment]
Yes the article is https://powerbi.microsoft.com/en-us/blog/export-report-to-pdf-pptx-and-png-files-using-power-bi-rest-api/

**Comment by dcp-unifin** [comment]
I'm sorry but we can't implement the API...we need more documentation or the full end to end solution from button creation to saving the PDF. We've been trying to use this for over one month now..developing in C#, powershell...just not working. Pity

**Comment by KesemSharabi** [comment]
Hi @dcp-unifin, 

I'm sorry to hear that you're running into problems when you're trying to implement your solution. At this stage, we're not going to expand our documentation, as we feel that it covers the basic development needs. As I'm sure you'll understand, we can't cover every scenario and therefore the [examples](https://docs.microsoft.com/power-bi/developer/embedded/export-to#code-examples) are designed to be general, and just point you in the right direction.

You might find a solution for your specific problem in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). 

Thanks,

Kesem
