### ISSUE TITLE
If you want to use all features of Power BI Premium (except unlimited sharing), you need at at least an A4 SKU. 

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/powerbi-docs#2407]
Is this statement correct?  If so then if have an A4 sku then have access to Power BI Report Server, same number of refreshes, same max size of datasets etc.

Or specifically related to the compute power eg the number of refreshes front and back end CPU cores etc.  Therefore is not the same features.  Only the same subset of features?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-gb/power-bi/admin/service-admin-premium-purchase#purchase-a-power-bi-premium-capacity-for-an-existing-organization)
* Content Source: [powerbi-docs/admin/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-premium-purchase.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rwlpf. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Assigning...

**Comment by KesemSharabi** [comment]
The statement was removed from the doc.

Thanks,

Kesem
