### ISSUE TITLE
Snowflake doesn't have a Query Editor in Power BI

### ISSUE THREAD

**Issue by lakeyeric22** [MicrosoftDocs/powerbi-docs#2409]
This document says: "You can Load the selected table, which brings the entire table into Power BI Desktop, or you can Edit the query, which opens Query Editor so you can filter and refine the set of data you want to use, and then load that refined set of data into Power BI Desktop."

However, this is not the case.  The current functionality only allows entire tables or views to be loaded into Power BI Desktop.  There is no Edit button to edit the query.  There is an Idea for it, but it doesn't exist today.
https://ideas.powerbi.com/ideas/idea/?ideaid=25342316-0a28-401e-a6ad-9d7740a5dce8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve assigned your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
@cpopell - can you please review and validate this feedback?

**Comment by cpopell** [comment]
![image](https://user-images.githubusercontent.com/6355439/91436706-80c04000-e81d-11ea-8cda-ac4aceae4e1a.png)

Hi @lakeyeric22 -- is the Transform Data button not showing up for you?

**Comment by lakeyeric22** [comment]
Yes, I can see the Transform button.  After rereading the document I think
I misunderstood what it was saying.  It does give me the option to choose
columns and such.  I thought it was implying that i could edit the actual
query that connects to Snowflake, as opposed to editing the Power BI query
script.  I was hoping for the Custom SQL option like we have on the SQL
server connection.  Thanks for responding.

[image: image.png]
