### ISSUE TITLE
Need details around tenant level permissions

### ISSUE THREAD

**Issue by rhlgupta1383** [MicrosoftDocs/powerbi-docs#241]
Kindly provide more details around the following delegated permissions, available on Azure portal Power BI API:

1. Read and write all content in tenant
2. View all content in tenant

**Comment by mihart** [comment]
Dear @rhlgupta1383 ,
Can you provide a little more detail so that we can help you.  Is there one or more URLs or a specific topic?  Thank you.

**Comment by rhlgupta1383** [comment]
I was referring the link below:
https://docs.microsoft.com/en-us/power-bi/developer/power-bi-permissions

In Azure portal, use the below navigation steps:

App Registrations->(Your app)->Settings->Required Permissions->Power BI Service (Add if not already added)

There are two permissions which requires admin consent and does not have documentation around it. The permissions are as follows:

1. Read and write all content in tenant
2. View all content in tenant

Attaching screenshot for reference.

![capture](https://user-images.githubusercontent.com/4348908/45606924-ba4f7480-ba66-11e8-8c9a-1d9a95d60fd0.JPG)
![capture](https://user-images.githubusercontent.com/4348908/45606927-c0455580-ba66-11e8-9bb4-2e18084654fa.JPG)

**Comment by rhlgupta1383** [comment]
@mihart - Kindly let me know in case any additional information is required from my end to help provide further assistance on the issue

**Comment by maggiesMSFT** [comment]
Thanks for your explanation, @rhlgupta1383. Now we’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@rhlgupta1383 We are working on updating this page.

**Comment by markingmyname** [comment]
@rhlgupta1383 This page will be updated by the end of the week.  Thank you for your feedback!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by rhlgupta1383** [comment]
@markingmyname - Thanks for the update. Wanted to report a small miss in the spelling though

![image](https://user-images.githubusercontent.com/4348908/46594818-f66c7700-caf2-11e8-9a51-4031683b7473.png)
