### ISSUE TITLE
Reading from PDF

### ISSUE THREAD

**Issue by fauzisd** [MicrosoftDocs/powerbi-docs#2411]
This page does not tell me why Load button is greyed.  Only Cancel is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ab70d2-6a8d-9457-9fe0-b7e5a11f7a23
* Version Independent ID: 8d847641-59f8-8914-799d-0c1c7ccad9a6
* Content: [Connect to a PDF file in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-pdf)
* Content Source: [powerbi-docs/connect-data/desktop-connect-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @fauzisd.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @fauzisd , 
Thank you for your question.  Until you've made a selection from the left side of the screen (selected one or more tables), the Load button will remain grey.  If that doesn't answer your question, please let us know.  
All the best,
The DOCS team
