### ISSUE TITLE
Request for addition to the page: Comparing Power BI Desktop and the Power BI service

### ISSUE THREAD

**Issue by Mrtnkbg** [MicrosoftDocs/powerbi-docs#2412]
Hi,

I am currently moving into the Power BI area from e.g. SQL Server/SSRS and Power Pivot, and I am looking for a complete picture of the Power BI "toolbox" in order to decide the road ahead. When searching for information I ran into the page https://docs.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop.

The page is a good overview, but I miss information regarding how the Power BI Report Builder fits into the Power BI mix, and therefore I suggest that this information is added to this page in order to complete the picture.

Since I am new in this area I am aware that I may have missed a point in leaving out the Power BI Report Builder out of tis particular overview, so please bear with me.

Best regards,
Mrtnkbg
(P.S. New on GitHub and I hope it is not rude using the alias?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ba6184-412b-7e75-ef74-46ae14d62dd6
* Version Independent ID: bf97c0bc-6511-e0f0-8df3-9e4f83492fe9
* Content: [Comparing Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop)
* Content Source: [powerbi-docs/fundamentals/service-service-vs-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/service-service-vs-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Mrtnkbg.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @Mrtnkbg -- That's a great question! And a good use of the alias. I'll have to think about how to work it into this article.  Quick answer: Power BI Report Builder creates paginated reports with the RDL file format. Power BI Desktop creates Power BI reports with the PBIX file format. Here's an article all about paginated reports, which includes a section comparing the 2 file formats. 
https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi
Hope that helps!
