### ISSUE TITLE
Not enough detail for large data model feature

### ISSUE THREAD

**Issue by sqltj** [MicrosoftDocs/powerbi-docs#2413]
We need more detail here.

1. Model sizes can go larger than 10GB -> How much higher? Limitless?
2. A comparison with AAS model sizing would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large models in Power BI Premium (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models)
* Content Source: [powerbi-docs/admin/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @sqltj, thanks for your comments. I am forwarding them on the doc author for consideration.

**Comment by davidiseminger** [comment]
With the release of Gen2, this is no longer relevant.
