### ISSUE TITLE
Export Power BI report to file Rest API and its limitations

### ISSUE THREAD

**Issue by madhu5117** [MicrosoftDocs/powerbi-docs#2416]
Hi,

we have a requirement of snapshotting SSRS reports published in Power BI service and make them available for users. We are trying to explore the option of Export Power BI report to file Rest API ( https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to ) but see that it has limitations on size and no. pages it can export. we can live with size limitation but no. pages limitation seems to be stopping us. Is there any alternative solution for this limitation.

**Comment by maggiesMSFT** [comment]
Hi, @madhu5117 -- thanks for your question. Assigning this to the author of the article you mention, but I'm wondering if that's the right article. You're talking about SSRS reports -- in other words, RDL files, right? This article appears to be about Power BI reports, PBIX files. So I'm not convinced that it will help. Perhaps @KesemSharabi can advise. Thanks!

**Comment by dcp-unifin** [comment]
I'm sorry but we can't implement the API...we need more documentation or the full end to end solution from button creation to saving the PDF. We've been trying to use this for  over one month now..developing in C#, powershell...just not working. Pity

**Comment by madhu5117** [comment]
Hi Maggie, Yes, I am talking about SSRS reports. We have published SSRS reports in Power BI service and exploring the option of using this API.
