### ISSUE TITLE
The location for PowerBI to pick up the connector may vary

### ISSUE THREAD

**Issue by MikeAinOz** [MicrosoftDocs/powerbi-docs#2417]
There may be an issue with the PowerBI seeing the location of the connector if the [Document] library list contains OneDrive as mine does

I had to create this directory:
mkdir "$([Environment]::GetFolderPath("MyDocuments"))\Power BI Desktop\Custom Connectors"
which mapped to:
C:\Users\mike\OneDrive\Documents\Power BI Desktop\Custom Connectors
I put the signed connector in there and it all worked
See [https://github.com/microsoft/DataConnectors/issues/320](https://github.com/microsoft/DataConnectors/issues/320)
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db81b-e91f-c1c8-7062-eb8bd5920eb9
* Version Independent ID: 63ba058e-817c-3b82-767b-5f94d8204e5b
* Content: [Connector Extensibility in Power BI - Power BI](https://docs.microsoft.com/en-au/power-bi/connect-data/desktop-connector-extensibility#data-extension-security)
* Content Source: [powerbi-docs/connect-data/desktop-connector-extensibility.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connector-extensibility.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @cpopell
* Microsoft Alias: **gepopell**

**Comment by paulinbar** [comment]
Hi @MIkeAinOz. Thanks for reaching out to us with your comment. As this doesn't seem to be primarily a documentation issue at this point, I am forwarding your comment on to the connector specialists. If you don't hear anything please feel free to get back to me.

**Comment by mihart** [comment]
Closed because very old.
