### ISSUE TITLE
Connect to Oracle database with Power BI Desktop version 2.83.5894.961 64-bit (2020.July)

### ISSUE THREAD

**Issue by fmosolyg** [MicrosoftDocs/powerbi-docs#2418]
Hi,

I installed the version above and I could only connect to Oracle database if I wrote the net_service_name in the Server field with quotation marks. Without them I got Microsoft.Mashup.Evaluator.Interface.ErrorException message. The quotation marks are necessary for local database and autonomous database connections as well.

Please check it and add to the documentation.
If you need additional information, please let me know it.

Thanks in advance,
 Ferenc Mosolygo
fmosolyg@msn.com
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/connect-data/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your contribution, @fmosolyg - sorry you ran into that problem. I've added a note at that step, to the effect you described here. The new note will show up with the next build.

Thanks!

**Comment by davidiseminger** [comment]
Update complete.
