### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gvashishtha** [MicrosoftDocs/powerbi-docs#2419]
I recently refactored the Azure ML documentation, so that a link on this page no longer points to a useful location. Specifically the link whose text is " (Optional) Automatic Swagger schema generation in the Deploy models with the Azure Machine Learning " should point to https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-advanced-entry-script#power-bi-compatible-endpoint

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7b2117-3a8d-1b35-109c-df315738beac
* Version Independent ID: d31fe48a-8b7d-149f-0db5-2818a4fa07cc
* Content: [Azure Machine Learning integration in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-machine-learning-integration)
* Content Source: [powerbi-docs/transform-model/service-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @gvashishtha . This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Thanks for the letting us know, @gvashishtha . I've retargeted the link and am closing this issue.
