### ISSUE TITLE
Relative date slicer in chrome

### ISSUE THREAD

**Issue by RonaldMussche** [MicrosoftDocs/powerbi-docs#242]
In chrome the relative date filter is not working correctly anymore.  A cannot switch between Years days or weeks or change the time period (this,last or next) In edge it is working.

Regards,
Ronald Mussche

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753770c6-5424-85a6-1bd7-963e2c1c7e64
* Version Independent ID: 09a4403f-9fbd-535a-4b45-83e89f380ba0
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-browser-support)
* Content Source: [powerbi-docs/service-browser-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-browser-support.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @RonaldMussche 
This is more of a product question than a doc question.  The fastest way to get an answer is to post this on community.powerbi.com.  The product team monitor the community forum very closely. If you this is a bug, then submit it on support.powerbi.com instead. 
Take care,
Michele
