### ISSUE TITLE
AMO and ADOMD connection string does not work

### ISSUE THREAD

**Issue by ozhug** [MicrosoftDocs/powerbi-docs#2421]
AMO and ADOMD connection string does not work (or error message returned lacks detail)
connection string shown when replaced with details for my application
string connString = $"Provider=MSOLAP;Data source=powerbi://api.powerbi.com/v1.0/<tenant>/<workspacename>;Initial catalog=<datasetname>;User ID=app:{appId};Password={authKey};";
message returns
Exception thrown: 'Microsoft.AnalysisServices.ConnectionException' in Microsoft.AnalysisServices.Core.dll
An unhandled exception of type 'Microsoft.AnalysisServices.ConnectionException' occurred in Microsoft.AnalysisServices.Core.dll
The specified Power BI workspace is not found.

if i use a similar string 
string connString = $"Provider=MSOLAP;Data source=powerbi://api.powerbi.com/v1.0/<tenant>/<workspacename>;Initial catalog=<datasetname>;"
I am promoted for username and password as expected but the workspace is found.
additionally earlier in article connection string is shown as
Data Source=powerbi://api.powerbi.com/v1.0/myorg/<workspace name>; Initial Catalog=<dataset name>;User ID=app:<appId>@<tenantId>;Password=<app_secret>;
which did not work either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5b741e-07dc-f2e3-9dc5-68a09cf34d7e
* Version Independent ID: a1a6fa3b-c2f4-e754-7aaa-4be9b9322303
* Content: [Automate Power BI Premium workspace and dataset tasks with service principals - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-service-principal)
* Content Source: [powerbi-docs/admin/service-premium-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ozhug.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by Minewiskan** [comment]
@ozhug - We had three engineers look at this section in the article. It is technically correct, so there does not appear to be a documentation issue here. Make sure you're using the latest client libraries, and you can exclude Initial Catalog in the string. If those don't help, you can try [Power BI Community](https://community.powerbi.com/t5/Get-Help-with-Power-BI/ct-p/PBI_GetHelp) or create a Support incident.
