### ISSUE TITLE
What are the paginated reports REST API limitation ?

### ISSUE THREAD

**Issue by kirank5** [MicrosoftDocs/powerbi-docs#2422]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI paginated reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @kirank5. I’ll investigate and get back to you.

**Comment by KesemSharabi** [comment]
Hi @kirank5,

As far as I'm aware there are no limitations.

Thanks,

Kesem
