### ISSUE TITLE
Incorrect "authorityUrl" for Military Contractors (DoDCON):

### ISSUE THREAD

**Issue by preston-mathis** [MicrosoftDocs/powerbi-docs#2424]
Currently listed as:
`<add key="authorityUrl" value="https://login.microsoftonlineS.net/common/" />`

Should be ?,maybe:
`<add key="authorityUrl" value="https://login.microsoftonline.us/common/" />`

**Comment by paulinbar** [comment]
Hi @preston-mathis. Thanks for your comment. I assume you are referring to this article? Please correct me if I'm wrong.
https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers-national-clouds
 Please correct me if I'm wrong.
In any event, I am forwarding your comment along to the doc author for consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @preston-mathis,

Thanks for spotting this - you're right, `authorityUrl` for Military Contractors should end with `.us`.

Following your suggestion, I fixed this in the article - see the section [Download the sample](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers-national-clouds#download-the-sample).

Thanks again for your contribution,

Kesem
