### ISSUE TITLE
minor typo worth fixing

### ISSUE THREAD

**Issue by JD-BOS** [MicrosoftDocs/powerbi-docs#2425]
In the "Important" box shaded blue - small typo worth fixing: "metadat" should be "metadata" 
Enabling the enhanced dataset metadata feature results in an irreversible upgrade to reports. Any Power BI reports loaded or created with Power BI Desktop, once the enhanced dataset metadata enabled, are irreversibly converted to the enhanced dataset metadat **[METADATA]** format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks, @JD-BOS! Nice catch! I've corrected the typo.

**Comment by JD-BOS** [comment]
Thanks so much for the impressive PBI documentation – very helpful!! ~ Jay
