### ISSUE TITLE
How Does the Tenant Admin Grant Access For Certifying Datasets

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerbi-docs#2427]
This article, and the related articles, don't explain how the Tenant Admin grants access to Certifying datasets. This is a critical step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964f91f6-81f3-8d83-4c73-d5ad8a7e77c5
* Version Independent ID: 7027312f-a8e3-a8c6-cb38-1200790271dc
* Content: [Certify datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-certify)
* Content Source: [powerbi-docs/connect-data/service-datasets-certify.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-certify.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Great question, @JoelLeichty ! I'm assigning this to the author to add that detail to the article. Here's what I found: In the admin portal, under Tenant settings, there is a section "Export and sharing settings". "Certification" is an option in that area. You can enable for the entire org, or just for specific security groups. After that's enabled, you can go to Settings for the dataset and you'll find the certification option under "endorsement". Hope that helps!

**Comment by JoelLeichty** [comment]
Thanks.

I did find it by guessing and reading some other blog.

The docs article could explicitly say 1) the field that is populated to
provide Certification access and 2) you must use an AD group (named users
won’t work).

The field is in the screenshot, but it goes unmentioned. Also the field
label and ordering isn’t great - “Apply to...” - not intuitive what’s being
applied to what. In this case, the Power BI expert is trying to communicate
a task to the O365 Admin who needs the documentation and knowledge they are
not blowing anything up or adding risk.

Joel

**Comment by paulinbar** [comment]
Hi @JoelLeichty. Thanks for your comments - particularly for the perspective of the O365 Admin. I am in the process of rewriting the endorsement (promotion and certification) articles now and I will take all you said into account. Promotion and certification started out with datasets, then came to be supported for data flows as well, and now is soon to be supported also for reports and apps. 
Are you sure that named users won't work as values for the field where the admin specifies who can certify items? I will check this out. 
So as I said, thanks for your comments!

**Comment by paulinbar** [comment]
Hi again @JoelLeichty. Right you are about the AD group. Moreover, it must be a security group. Thanks for bringing this up. Will correct and be specific in the documentation.

**Comment by JoelLeichty** [comment]
@paulinbar Thanks! 

I wrote a long blog on this and some related topics, trying to get certification to fit into a larger deployment picture: https://www.dynamicconsulting.com/deployment-strategy-for-power-bi-app-workspaces/

**Comment by paulinbar** [comment]
Hi @JoelLeichty. The endorsement docs have been rewritten, taking your comments into consideration. The main conceptual doc is here: https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-endorsement-overview
Thanks for your comments. In the meantime I am closing this issue now, but feel free to reopen or file an new issue if you have other feedback. Thanks!
