### ISSUE TITLE
Small edit worth fixing - verb tense

### ISSUE THREAD

**Issue by JD-BOS** [MicrosoftDocs/powerbi-docs#2428]
very small word change (verb tense) and sorry for catching these "one at a time..."

Updating a report to use the enhanced dataset metadata feature is irreversible. During the update, however, a report backup file is create [should be CREATED] to save a version of the report in its original (pre-update) format. The backup file is removed after 30 days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata?source=docs)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @JD-BOS, thanks for calling this to our attention. The correction has been made and will go live at the next publishing cycle early this week. Thanks again!
