### ISSUE TITLE
Typo; sentence is missing the article "a"

### ISSUE THREAD

**Issue by hugotoledo** [MicrosoftDocs/powerbi-docs#2429]
The sentence:
**_Power BI Desktop what-if parameter is feature that..."_** is missing be article "a". 

It should be written as:
**_Power BI Desktop what-if parameter is a feature that..."_** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand)
* Content Source: [powerbi-docs/transform-model/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by paulinbar** [comment]
Hi @hugotoledo, thanks for pointing that out. The change has been made to the doc and will go live at the next publishing cycle. Thanks again for the sharp eyes!
