### ISSUE TITLE
Tips for making this easier to learn/understand

### ISSUE THREAD

**Issue by feemurk** [MicrosoftDocs/powerbi-docs#243]
Hi Guys,

Would you be able to attach the sample PBIX that you've used for your screenshots to demonstrate the functionality and configuration.?  I think it would help me metabolize the method more effectively.

Thanks,

Fahim.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips#feedback)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @feemurk - we'll look into attaching the PBIX files in future articles. You can also get the PBIX files used for monthly updates from the following location, which I believe includes the file you're looking for: https://github.com/Microsoft/powerbi-desktop-samples/tree/master/2018
