### ISSUE TITLE
ADLS Gen2 must be added to document under azure

### ISSUE THREAD

**Issue by rajrao** [MicrosoftDocs/powerbi-docs#2431]
Under Azure sources, "Azure Data Lake Storage Gen2" must be added. Additional information on what is supported, (eg: path to container level, path to folder in container, full file path to file) would be helpful. Finally, information on permissions and the setup in ADLGen2 would also be very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1458e2bc-7637-e305-55f3-596c64972ff3
* Version Independent ID: b5437e14-6d46-e2f6-0369-e61f72988ff3
* Content: [Learn how to connect to dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-data-sources)
* Content Source: [powerbi-docs/transform-model/service-dataflows-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. The Dataflows documentation is undergoing an update soon, and we'll make sure we include those items.
