### ISSUE TITLE
Consider indicating that custom connectors are not compatible with dataflows

### ISSUE THREAD

**Issue by slavatrofimov** [MicrosoftDocs/powerbi-docs#2432]
The documentation currently does not address the limitation that dataflows do not support Custom Connectors. Please consider adding this known limitation to the official documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305e8837-917d-43d4-4d09-a180082f3ab8
* Version Independent ID: b43bfaf7-d7e1-a715-1ffa-e1f9e78371e8
* Content: [Using dataflows with on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-on-premises-gateways)
* Content Source: [powerbi-docs/transform-model/service-dataflows-on-premises-gateways.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-on-premises-gateways.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. The dataflows documentation is going through an update soon, and we'll be sure to include this information. Thanks!
