### ISSUE TITLE
Consider indicating that custom connectors are not compatible with dataflows

### ISSUE THREAD

**Issue by slavatrofimov** [MicrosoftDocs/powerbi-docs#2433]
The documentation currently does not address the limitation that dataflows do not support Custom Connectors. Please consider adding this known limitation to the official documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137ea074-f635-5cd9-6e94-f6bc12ac2452
* Version Independent ID: 4ce609b2-adfa-8575-4e4a-9cc285028043
* Content: [Use custom data connectors with the on-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors)
* Content Source: [powerbi-docs/connect-data/service-gateway-custom-connectors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-gateway-custom-connectors.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by davidiseminger** [comment]
Thanks again for your comment, we're updating the dataflows documentation, and will include this information.
