### ISSUE TITLE
MicrosoftAzureConsumptionInsights - Databricks Missing

### ISSUE THREAD

**Issue by ryancthomas** [MicrosoftDocs/powerbi-docs#2435]
Regarding the recent communication where the meter names of Azure Databricks will change, Databricks meterid is not available using the MicrosoftAzureConsumptionInsights connection in PBI as of August.  
How do I capture the billing to pull into PowerBI?

Communication:
Azure Databricks     Effective     September 1, 2020, the meter names of Azure Databricks will change. Read complete details about these changes. | Azure Databricks     Effective     September 1, 2020, the meter names of Azure Databricks will change. Read complete details about these changes. |  
-- | -- | --
Azure Databricks     Effective     September 1, 2020, the meter names of Azure Databricks will change. Read complete details about these changes.

**Comment by kfollis** [comment]
Hi @ryancthomas - Thanks for the question. Is this the article where you'd expect to see an update: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-consumption-insights? And this is the announcement: https://azure.microsoft.com/en-us/updates/azure-analytics-data-bricks-meters/? Have you tried the steps in this article: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management? 
Sorry for all the questions! This feedback channel is for specific articles, so I just need a little help identifying which article should be updated.

**Comment by mihart** [comment]
Hi @ryancthomas ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
