### ISSUE TITLE
Unsupported features and connectors vague

### ISSUE THREAD

**Issue by MCarlisle3** [MicrosoftDocs/powerbi-docs#2436]
M expressions containing certain character combinations such as “\n” in column names

This is vague is there any other documentation listing the character combinations that are unsupported? Alternatively guidance on how we'd be able to spot this as being an issue, e.g. column names containing backslashes are unsupported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata#report-backup-files)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @MCarlisle3  - I did a quick search and didn't find a definitive answer for you. I'm going to assign this issue to the writer for follow-up to see if we can be more explicit when describing the supported/non-supported character combinations in M expressions.

**Comment by kfollis** [comment]
Fantastic detective work, @MCarlisle3! But not exactly a straightforward path. I'll let the writer confirm your assumption and add the clarification to the article.

**Comment by davidiseminger** [comment]
Added a limitation to that effect, though rather than calling them out I provided a reference to avoid duplication or update issues.
