### ISSUE TITLE
Spellings mistake

### ISSUE THREAD

**Issue by Abi0411** [MicrosoftDocs/powerbi-docs#2437]
The line should read, "select an existing measure" instead of select and existing measure. The mistake is after "Change Detection" section
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedb7099-554f-0eed-eaa6-fc13851eb3b1
* Version Independent ID: 8beddbbe-5ebc-60e4-ab28-fd130283a8c1
* Content: [Automatic page refresh in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh)
* Content Source: [powerbi-docs/create-reports/desktop-automatic-page-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-automatic-page-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by Abi0411** [comment]
"Once the window is open, you are presented with the Measure type option where you can _**select and existing**_ measure or create a new one from scratch."

**Comment by kfollis** [comment]
Thanks, @Abi0411! Good catch. I have made the correction and it'll go live tomorrow with our next publishing update.
