### ISSUE TITLE
Using data from data sources to build matrix

### ISSUE THREAD

**Issue by mhatreraja** [MicrosoftDocs/powerbi-docs#2438]
Hi,
I'm new to power bi (currently using Version: 2.83.5894.961 64-bit (July, 2020)) version.
My issue is two data sources have few of the identical columns  table 1 and table 2. However rows differ to column headers. Data will be appended on day by day, for below scenario data produced for one day. I will like to use the data from these table to build matrix, when they are used results are not as expected. Relationship between these two tables are cardinality many to many. 
If use dax for calculated column, latest date to be added to matrix visual to get the correct values however other dates are reflect to latest date numbers. Also tried adding date to matrix but no luck.
end goal: calculate table 2 #cores and memory with table 1 cpu and memory assigned to each vm in cluster.

refer attached
[Table1.xlsx](https://github.com/MicrosoftDocs/powerbi-docs/files/5097258/Table1.xlsx)
[Table2.xlsx](https://github.com/MicrosoftDocs/powerbi-docs/files/5097259/Table2.xlsx)
[Result.xlsx](https://github.com/MicrosoftDocs/powerbi-docs/files/5097310/Result.xlsx)

Thanks,
RM

**Comment by kfollis** [comment]
Hi @mhatreraja - this feedback channel is to address updates needed for specific articles. I think you should ask your question in https://community.powerbi.com. It's a really helpful community. And, if you haven't already looked, there is some training available at https://docs.microsoft.com/learn/powerplatform/power-bi.
