### ISSUE TITLE
Azure AD B2B with commercial in GCC High is not supported

### ISSUE THREAD

**Issue by raghu4sangeeth** [MicrosoftDocs/powerbi-docs#2440]
Azure AD B2B in Azure Gov only works with other Gov tenant users based on the following link - https://docs.microsoft.com/en-us/azure/azure-government/compare-azure-government-global-azure#azure-active-directory-premium-p1-and-p2

Please update the table to indicate that B2B is not supported for GCC High and DOD.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @raghu4sangeeth - the update is now live, so closing this issue.
