### ISSUE TITLE
Example doesn't load preview

### ISSUE THREAD

**Issue by bbpaulvanharen** [MicrosoftDocs/powerbi-docs#2441]
The very first example on this page, i.e. Get Data > Web from https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/ doesn't load the Table View Preview. Instead, a "Something went wrong" message appears, stating "The string did not match the expected pattern".

FYI: the Web View of the page loads as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for flagging that, @bbpaulvanharen. I was able to repro your experience. I'm going to assign this article to the writer to make an update. If you want to try the step with an alternative URL, you can find similar data on this site: https://www.retirementliving.com/best-and-worst-states-for-retirement-2020 and I was able to load the data without error.
