### ISSUE TITLE
Embedding Dashboard Instructions are way harder than Embedding Report instructions

### ISSUE THREAD

**Issue by peterdixon** [MicrosoftDocs/powerbi-docs#2444]
[Enter feedback here]
This section makes it too hard to figure out how to embed a dashboard, especially when comparing it to the ease of embedding a report.

Some lightweight code can be used to embed a report into another application. All you have to do is create an IFrame and copy and paste the embed link. This allows you to easily embed a power bi report into an ERP by changing one line of code.

Why can't the same be done for Dashboards?

Why can't the dashboard embed link be plainly visible from the Power BI page? I want to be able to just copy a link and paste it into my code. I'm not developing an application - I'm building a hack to put Power BI inside a custom portlet in NetSuite. All I need is the link. I'm not interested in developing an entire application to embed one dashboard into NetSuite.

This page should be intended for the users who are not hardcore devs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd1628b-cd62-92f8-8cdb-6411c74118da
* Version Independent ID: 8746a38d-bbd1-4a7d-726f-60247fc5c823
* Content: [Embed reports or dashboards from apps - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-from-apps)
* Content Source: [powerbi-docs/developer/embedded/embed-from-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-from-apps.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @peterdixon. I'm assigning this issue to the author to see what we can address with a content update. If the functionality is missing, you could submit your suggestion for an improvement here: https://ideas.powerbi.com/ideas/

**Comment by KesemSharabi** [comment]
Hi @peterdixon,

I'm sorry to hear that you're experiencing problems with embedding a Power BI Dashboard.

However, this looks like a support request or product request rather than documentation feedback.

You can try submitting this idea to [Power BI Ideas](https://ideas.powerbi.com/), or contact our [support page](https://support.powerbi.com) if you need further help.

Thanks,

Kesem
