### ISSUE TITLE
Facebook Connector on August 2020 Power BI Desktop Version not available

### ISSUE THREAD

**Issue by miragliag** [MicrosoftDocs/powerbi-docs#2445]
[Enter feedback here]
The Facebook Connector is not visibile in the Power BI Desktop August 2020 update. Any timeline by when it will be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Analyze Facebook data by using Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-facebook-analytics)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @miragliag - I see a note in the article that the connector isn't working properly, but you're right - I don't see it all in the August 2020 release. I'm adding the article author to see if there's an updated timeline to bring that back.

**Comment by mihart** [comment]
Thanks for your comment, @miragliag . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
All the best,
the DOCS team
