### ISSUE TITLE
Missing functionality in change log 

### ISSUE THREAD

**Issue by wilsoja1** [MicrosoftDocs/powerbi-docs#2446]
Greetings, I see the following in the change log but no mention of the same exact funtionality, just using SAML instead of Kerberos. 

"
Version 1.3.6801.38816 (Build 15.0.2.540), Released: August 15, 2018

    Features
        SAP HANA SSO Direct Query support with Kerberos now available for Power BI Reports  "

**Comment by kfollis** [comment]
Hi @wilsoja1 - is there a particular article that contains the issue? Typically this feedback includes an article link, but it's missing today, so I'm hoping you can help me find where you'd expect to find this information. We have content published here: https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-overview related to SSO if that helps!

**Comment by wilsoja1** [comment]
Thanks for the quick reply.  I'm guessing the functionality mentioned in my original post doesn't even exist for PBIRS, no articles, and nothing in the change log.

Could you forward to the internal PBIRS team to confirm?

*I would post in the PowerBI Server forum but Microsoft is only allowing organizational IDs / PowerBI Service cloud accounts to post - and we are 100% on premises only.

Thank you in advance for anything you can do to help.

Jimmy Wilson   |  Sr Principal S/W Dev Analyst, Information Delivery & Analytics

Northrop Grumman Corporation  |  Enterprise Services

O: 310-297-5884  |  C: 334-707-1676  |  James.Wilson3@ngc.com

On Aug 24, 2020 5:50 PM, Kate Follis <notifications@github.com> wrote:

Hi @wilsoja1<https://github.com/wilsoja1> - is there a particular article that contains the issue? Typically this feedback includes an article link, but it's missing today, so I'm hoping you can help me find where you'd expect to find this information. We have content published here: https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-overview related to SSO if that helps!

-

**Comment by kfollis** [comment]
Thanks for the additional info! There is an article here: https://docs.microsoft.com/en-us/power-bi/report-server/data-sources that lists the data sources and support authentication methods for Power BI Report Server - that may contain a reference. I will certainly forward this on to our engineering team to get confirmation.

**Comment by wilsoja1** [comment]
Thank you for forwarding on to engineering for confirmation.  It’ll be nice to know for sure that PBIRS does/does not support SAML against a HANA DB.

Below, the link you provided clearly shows that Windows AD SSO will work like a champ with PBIRS, just nothing about SAML.   And the kicker here, is that SAML auth against a HANA DB is supported if using the PBI Gateway, but as mentioned before we are 100% on-premises only.

[cid:image001.png@01D67AE6.F244F300]

Thanks,

Jimmy Wilson   |  Sr Principal S/W Dev Analyst, Information Delivery & Analytics
Northrop Grumman Corporation  |  Enterprise Services
O: 310-297-5884  |  C: 334-707-1676  |  James.Wilson3@ngc.com<mailto:James.Wilson3@ngc.com>

**Comment by kfollis** [comment]
HI @wilsoja1 - the engineering team has confirmed that SAML is not supported against a HANA DB. I'll go ahead and close this issue now.

**Comment by wilsoja1** [comment]
Kate, thanks again for confirming with the MS engineering team that the scenario of  PBI Server -> SAML SSO -> HANA DB is not possible at this point in time.   Is there any way you could ask if “SAML SSO against HANA” functionality is on the development horizon for PBI server ?  This will help us immensely with what direction we need to take internally as stewards of our enterprise.

PowerBI is quickly becoming the analytic tool of choice at my organization (60k+ on-premises potential user base) and there’s a strong need to make our PBI Server infrastructure fully interoperate with SAP HANA, using SAML SSO.

Regards,

Jimmy Wilson   |  Sr Principal S/W Dev Analyst, Information Delivery & Analytics
Northrop Grumman Corporation  |  Enterprise Services
O: 310-297-5884  |  C: 334-707-1676  |  James.Wilson3@ngc.com<mailto:James.Wilson3@ngc.com>

From: Wilson, Jimmy [US] (ES)
Sent: Tuesday, August 25, 2020 2:32 PM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: EXT :Re: [MicrosoftDocs/powerbi-docs] Missing functionality in change log (#2446)

Thank you for forwarding on to engineering for confirmation.  It’ll be nice to know for sure that PBIRS does/does not support SAML against a HANA DB.

Below, the link you provided clearly shows that Windows AD SSO will work like a champ with PBIRS, just nothing about SAML.   And the kicker here, is that SAML auth against a HANA DB is supported if using the PBI Gateway, but as mentioned before we are 100% on-premises only.

[cid:image001.png@01D68836.07153450]

Thanks,

Jimmy Wilson   |  Sr Principal S/W Dev Analyst, Information Delivery & Analytics
Northrop Grumman Corporation  |  Enterprise Services
O: 310-297-5884  |  C: 334-707-1676  |  James.Wilson3@ngc.com<mailto:James.Wilson3@ngc.com>

**Comment by kfollis** [comment]
Hi @wilsoja1 - you can reference this blog https://powerbi.microsoft.com/en-us/blog/licensing-and-roadmap-update-for-power-bi-report-server/ for more info about the on-premises roadmap. You can also go to http://ideas.powerbi.com to submit a suggestion to be voted on by other users.
