### ISSUE TITLE
Conditional formatting is applicable to total rows

### ISSUE THREAD

**Issue by Rickmaurinus** [MicrosoftDocs/powerbi-docs#2449]
[Enter feedback here]

The bottom of the page has the comment: 
Conditional formatting applies only to the values of Table or Matrix visuals, and doesn't apply to any subtotals, grand totals, or the Total row.

However, nowadays conditional formatting is also applicable to Subtotal, grand totals or total rows. This should be changed in this article. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks, @Rickmaurinus! I'm assigning this to the author to get those changes made.

**Comment by mihart** [comment]
Hi @Rickmaurinus, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
