### ISSUE TITLE
Add Undocumented Options

### ISSUE THREAD

**Issue by kelaude** [MicrosoftDocs/powerbi-docs#245]
There are a few options that are not documented here - it would be nice to have all these options in one place. Could those be added? I'm not sure which options are missing, but here are a few examples of some valid cardName and corrseponding propertyName values that are not in this documentation.

"visualHeader": [{
	"show": true
}]

"visualTooltip": [{
	"type": "Default"
}]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @kelaude! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback. We're working with the engineering team to add more information about report themes, and will update the article when that work is complete. Thanks for posting!
