### ISSUE TITLE
This page needs to state what permissions Role (Viewer, Contributor, Member, Admin) is REQUIRED to copy a report.  I spent many hours trying to get a user who had Build permissions + Viewer role the ability to copy a report to a different workspace, and it doesn't work.  Would have been nice to have known that from the documentation!!!

### ISSUE THREAD

**Issue by sjs210** [MicrosoftDocs/powerbi-docs#2450]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thank you for the feedback, @sjs210 and for taking the time to make us aware of this. What a frustrating experience! I'm assigning this to the author of the article to consider adding those prerequisites to help future readers.

**Comment by maggiesMSFT** [comment]
Hi, @sjs210 -- good point! I'm adding the info and a link to the article about roles in workspaces.
