### ISSUE TITLE
dataflow ownership

### ISSUE THREAD

**Issue by azadehgnia** [MicrosoftDocs/powerbi-docs#2451]
[Enter feedback here]
Hi,

I believe below statement is a bit misleading:

"It's important to know that there is only one owner of any dataflow, which is the person who creates it. "
 as another user is able to take over the ownership (since last year).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating and using dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/service-dataflows-create-use)
* Content Source: [powerbi-docs/transform-model/service-dataflows-create-use.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/service-dataflows-create-use.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @azadehgnia - Thanks for the feedback! I'm assigning to the author to make a clarifying update.

**Comment by davidiseminger** [comment]
We've updated all the dataflows documentation to address issues.
