### ISSUE TITLE
Get-PowerBIActivityEvent does not work non-interactively

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#2452]
It turns out from a recent support call that Get-PowerBIActivityEvent does not work when the caller is an Azure Service Principal - even if that service principal has been made the Power BI Service Administrator role, etc.

This should be documented on this page.  It would have saved me and MS support hours.

(It is also a rather silly limitation as a lot of audit data is captured and processed by automated processed, but that is irrelevant here I suppose...)

See #2026 for related discussion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks, @cbailiss - that's very helpful background. I'll make sure that gets flagged in the next update.
