### ISSUE TITLE
Incorrect link to Organizational visuals

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#2454]
The link with text "Learn more about deployment and management of organization Power BI visuals" has a linkid that is incorrectly configured (https://go.microsoft.com/fwlink/?linkid=866790).
It links to:
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#organization-visuals
While it should be:
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#organizational-visuals

I tried editing the page, but I'm not sure if I'm allowed to edit the linkid to the above URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746e3f8f-68fd-b7d2-f61e-6bb8daa63ea4
* Version Independent ID: 50a481ef-6d50-cec0-e21b-2deab73e73b3
* Content: [Organization visuals in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @NickyvVr, thanks for this observation. Indeed the docs have been reorganized and the value of this fw link apparently was overlooked. Forwarding to the to doc author for further action. Thanks!

**Comment by KesemSharabi** [comment]
Hi @NickyvVr 

Thanks for spotting this!

Actually, the link should be taking you to [Manage Power BI visuals admin settings](https://docs.microsoft.com/power-bi/admin/organizational-visuals) - a new article for managing the Power BI visuals admin settings.

As you suggested, I fixed this link in the [Administer organizational Power BI visuals](https://docs.microsoft.com/power-bi/developer/visuals/power-bi-custom-visuals-organization#administer-organizational-power-bi-visuals) section.

Thanks again for your contribution,

Kesem
