### ISSUE TITLE
OAuth support via Gateway for Azure SQL DB / DW

### ISSUE THREAD

**Issue by mariuspc** [MicrosoftDocs/powerbi-docs#2455]
The documentation says that connecting to Azure SQL DB and Azure SQL Data Warehouse (this should be renamed to Synapse) via a gateway does not support OAuth "Supported with the same M function as the on-premises version, causing restricted Auth options (gateway doesn't support OAuth)." The July release of the Power BI Gateway (https://powerbi.microsoft.com/en-us/blog/on-premises-data-gateway-july-2020-update-is-now-available/) has enabled OAuth for SQL Server: "We have enabled OAuth via the On-premises data gateway for SQL Server and Kusto connectors. This will enable use of AAD credentials  for connecting to data sources like SQL Azure."

Can you please fix or clarify?

**Comment by paulinbar** [comment]
Hi @mariuspc. Are you referring to note #2 on this page? https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources ? Assuming that's true, I'm forwarding your observation on to the author of that document. Thanks for the comment!

**Comment by mariuspc** [comment]
Hi @paulinbar  - yes, I am referring to note 2 on the page you referenced, stating that OAuth is not supported via the Gateway, when connecting to Azure SQL DB and Azure SQL DW. Best regards!

**Comment by paulinbar** [comment]
@davidiseminger

**Comment by mihart** [comment]
Hi @mariuspc ,
I see that this Git issue is a bit old, and the issue has been resolved. I'm closing this Git Issue, but please contact us if you have additional questions or suggestions. 
All the best,
the DOCS team
