### ISSUE TITLE
iframe example not working?

### ISSUE THREAD

**Issue by tfairfoul** [MicrosoftDocs/powerbi-docs#246]
Hi,  the below example no longer seems to work: 
&lt;iframe src="https://xyz.com"&gt;

 It just shows a blank window.

Thanks

Todd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f30eb2-e55e-635d-e161-6c26f20fac2d
* Version Independent ID: 7d1fd996-9981-a844-0f2b-abb35cf21b7f
* Content: [Add image, text, video, streaming data to your dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-add-widget)
* Content Source: [powerbi-docs/service-dashboard-add-widget.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-add-widget.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @tfairfoul! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @tfairfoul 
This part of the doc is not intended to be a link but to be an example.  Sorry for the confusion.
Thanks,
Michele

**Comment by tfairfoul** [comment]
Hi,
    The issue is that no matter what site I put in the iframe it does not work. www.microsoft.com<http://www.microsoft.com> for example.

<iframe src="https://www.microsoft.com"></iframe>

[cid:image001.png@01D45AF8.1CC1F710]

Thanks

Todd
