### ISSUE TITLE
Hover Function

### ISSUE THREAD

**Issue by egrusecki** [MicrosoftDocs/powerbi-docs#2461]
Do only certain devices allow the hover feature? every device i use it on only open the link right away be that a report or a tile.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd9453b-228c-1e2a-617b-bff8c512004d
* Version Independent ID: a9f27879-0427-c52d-b11d-8c80b94dfc78
* Content: [Get real-world data with the Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-data-in-real-world-context)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-data-in-real-world-context.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-apps-data-in-real-world-context.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @egrusecki . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @egrusecki, sorry for the long delay in responding. Can you please explain a bit more fully what you mean? That will help me get an answer to your question. What do you mean by "hover"?
Thanks.

**Comment by paulinbar** [comment]
Hi @egrusecki, I haven't heard from you regarding the details of the problem you were experiencing, so I am going to close this issue now. If you still want to pursue it, please give me a little more context and detail about what you observed, and I will check it out. Thanks!
