### ISSUE TITLE
Update to include MSAL either in addition to or instead of ADAL

### ISSUE THREAD

**Issue by skeeler** [MicrosoftDocs/powerbi-docs#2462]
Per this documentation: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-net-migration

"MSAL.NET is now the recommended auth library to use with the Microsoft identity platform. No new features will be implemented on ADAL.NET. The efforts are focused on improving MSAL."

Therefore, the Power BI documentation on acquiring a token should be updated to include information on using MSAL library, either instead of or in addition to, the existing ADAL library implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @skeeler - I'm assigning this to the author of the Power BI article to take a look at making that update.

**Comment by KesemSharabi** [comment]
Hi @skeeler,

This issue is in my backlog and I'll refresh the article as soon as I can.

Thanks,

Kesem
