### ISSUE TITLE
Why are Power BI Visuals not on this page?

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#2463]
I'm wondering why the Power BI Visuals part is no longer part of this page?
It's a little bit confusing when coming here, because that's the only part from the Admin Portal not on this page. I would expect at least a paragraph that names this feature and then links to the newly created page in the navigation pane (https://docs.microsoft.com/en-us/power-bi/admin/organizational-visuals).

I was updating a blog post and noticed the old link (https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#power-bi-visuals-settings) was now broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#power-bi-visuals-settings)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @NickyvVr - The (now broken) bookmark URL has been updated to this link: https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#organizational-visuals, which does then link to the new article. We will soon update the admin article to break out additional settings to their own article, and the visuals settings were first to move when the last update was made. I apologize for the confusion.
