### ISSUE TITLE
Data Type Consideration

### ISSUE THREAD

**Issue by millh0use** [MicrosoftDocs/powerbi-docs#2465]
[Enter feedback here]
Under "Considerations" it should be clarified that in order for the relative options to show up in the slicer, the data type must be configured as a date and not the default of text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range?source=docs)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @millh0use . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @millh0use ! Adding this now. Will be live tomorrow afternoon, Sept 10.
