### ISSUE TITLE
Query editor button is no longer up to date

### ISSUE THREAD

**Issue by Cizzzzz** [MicrosoftDocs/powerbi-docs#2466]
Query Editor has been changed to 'Transform Data'.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6ac628-d5b4-e722-0532-d467c8347a5a
* Version Independent ID: 20ec07f6-627d-3765-ddcb-4aa738b6952a
* Content: [Query overview in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-query-overview)
* Content Source: [powerbi-docs/transform-model/desktop-query-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-query-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @Cizzzzz , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
