### ISSUE TITLE
What Fields are Displayed?

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2467]
[Enter feedback here]
Hi, when "Show data point as a table" is selected, how are the displayed fields chosen?  I get a subset of the fields but can't figure out why.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2726d555-7957-af87-d477-c385602cb47e
* Version Independent ID: 88f11624-0c37-a767-026d-3eb34633bcef
* Content: [Visual table and records in Power BI Desktop visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-see-data-see-records)
* Content Source: [powerbi-docs/create-reports/desktop-see-data-see-records.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-see-data-see-records.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- how are you?! I'm assigning your question to the author to answer. In the meantime, I suggest asking on the Community site, https://community.powerbi.com/. Hope that helps!

**Comment by mihart** [comment]
Hi @TravisKale,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit these type of questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by asocorro** [comment]
Hi Michele, the issue might be old but I never got an answer.  I would like to know about this feature.

Cheers,
Adolfo
