### ISSUE TITLE
Personalize Visuals in Embed Scenarios

### ISSUE THREAD

**Issue by Abhik93-hub** [MicrosoftDocs/powerbi-docs#2469]
[Personalize Visuals feature is available in a report embedded in an html page. However, under limitations, it is mentioned that this feature isn't available in embed scenarios. Kindly clarify which embed scenario doesn't support this feature]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615021e0-5504-046d-d6ab-c2d8dee0656f
* Version Independent ID: d9c6ad5a-139f-716e-eb59-473a1f8d73de
* Content: [Let users personalize visuals in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-personalize-visuals)
* Content Source: [powerbi-docs/create-reports/power-bi-personalize-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/power-bi-personalize-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Abhik93-hub -- I'll see what I can find out, and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @Abhik93-hub -- here's the answer: we're exploring adding support for more embed scenarios, but for now, they're considered unsupported. Hope that helps!
