### ISSUE TITLE
Need to indicate that FB disabled access to PowerBI/Query app

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/powerbi-docs#2471]
Facebook disabled the app, apparently, so any attempt to connect to data from Excel or PowerBI fails with the following error:

Log in to use your Facebook account with Microsoft Power BI.

Error Accessing App

We're sorry, but the application you're trying to use doesn't exist or has been disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Analyze Facebook data by using Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-facebook-analytics)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ilyalehrman -- good question! Assigning to the author to resolve. In the meantime, consider asking the Community, https://community.powerbi.com/

**Comment by mihart** [comment]
Hi @ilyalehrman ,
I see that this Git issue is a bit old, so I'm going to close it.  We've added a note to the article explaining the situation with Facebook Analytics. Please let us know if you have any other questions.   
All the best,
the DOCS team
