### ISSUE TITLE
Update Doc 

### ISSUE THREAD

**Issue by farhansoomro** [MicrosoftDocs/powerbi-docs#2472]
[Enter feedback here]
Update the doc since we are supporting Q & A for DQ

Direct Query support for Q&A (preview)
We are excited to announce that Q&A now supports SQL Direct Query sources including SQL Server 2019, Azure SQL database and Azure Synapse Analytics. You can now go ahead and use Q&A to ask natural language questions against these data sources. Prior to this update, Q&A was not available for datasets with any Direct Query sources. You will also notice one minor change to the behavior of Q&A when it is operating in Direct Query mode. There is now a submit button which is now available when typing in your question. This is to prevent overloading the Direct Query source with unnecessary queries as the user types.

Note: Other Direct Query sources are not supported for Q&A. We don’t block Q&A altogether if you have other Direct Query sources in your dataset, but some questions may not be answered correctly or return errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c83048-7e4e-0df6-bd4c-16097df348cd
* Version Independent ID: c275fe95-edd1-a8c6-4b00-4857e1e65aab
* Content: [Limitations of Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-limitations)
* Content Source: [powerbi-docs/natural-language/q-and-a-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/natural-language/q-and-a-limitations.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @farhansoomro -- thanks for pointing that out! Will get it updated.

**Comment by maggiesMSFT** [comment]
@farhansoomro -- updated the article. Change will be live this afternoon. Thanks!
