### ISSUE TITLE
Adobe Analytics Error within the Power BI Service

### ISSUE THREAD

**Issue by danigle** [MicrosoftDocs/powerbi-docs#2473]
I'm having issues connecting to Adobe Analytics within the Power BI Service: 

I can get a connection working in the PBI Desktop, but not the PBI Service. 

This dataflow has existed for several months, is scheduled to refresh daily, and continues to refresh with no errors. The report that relies on this dataflow is still working properly and pulling in current data (minus the metric I'm trying to fix).

When I go into the dataflow in Power Query Editor I continue getting the following message: "Expression.Error: The key didn't match any rows in the table."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b88aa9e-5500-8904-286c-4a6d22be2e9f
* Version Independent ID: b0faa18f-b2ca-4c95-3486-7227cfb31277
* Content: [Connect to Adobe Analytics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-adobe-analytics)
* Content Source: [powerbi-docs/connect-data/desktop-connect-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-adobe-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @danigle -- I'm sorry to hear it! This sounds like an issue with the product, not the docs. You can try asking the Community for help, https://community.powerbi.com/. 
If that doesn't do the trick, you'll need to contact support, https://powerbi.microsoft.com/en-us/support/
I hope that helps!
