### ISSUE TITLE
Clarifying question - Does the doc describe a user flow or unattended operation?

### ISSUE THREAD

**Issue by CalumJEadie** [MicrosoftDocs/powerbi-docs#2474]
Does the doc describe a user flow or unattended operation?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @CalumJEadie . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @CalumJEadie,

This article describes getting the access token, and is valid for both cases.

Thanks,

Kesem
