### ISSUE TITLE
Self-reference link in the Next Steps section

### ISSUE THREAD

**Issue by yetanothermark** [MicrosoftDocs/powerbi-docs#2477]
The first bullet within the Next Steps section points to the same page that it belongs to (i.e. self-reference)

- Use a relative date slicer and filter in Power BI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
@yetanothermark -- fixed, will be live this afternoon. Thanks!
