### ISSUE TITLE
Broken link in "Educate users" section.

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/powerbi-docs#2478]
There is a broken link to a prior section in the Educate users section:

"It is important to educate your users on how to efficiently work with reports based on DirectQuery datasets. Your report authors should be educated on the content described in the [Optimize report designs](#optimize-report-designs section)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 694e3f20-79d0-debf-1449-38a62492424c
* Version Independent ID: 75c298be-5754-c342-cb4d-228b38f8cec7
* Content: [DirectQuery model guidance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance)
* Content Source: [powerbi-docs/guidance/directquery-model-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/directquery-model-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @kasavin.

I've assigned this issue to the doc author for review.

**Comment by peter-myers** [comment]
Thanks for your feedback, @kasavin. I've made a correction, which should go live shortly.
#please-close
