### ISSUE TITLE
Test Tool Deprecated

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2479]
Can the test tool be updated to leverage VS2019 and the new frameworks? 
Some of the dependency libraries have been deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b28829-a0e6-9377-35af-bd5661012ace
* Version Independent ID: 607b2bdf-58aa-c392-fe98-3a8264c9edca
* Content: [Capacity planning guidance for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/capacity-planning)
* Content Source: [powerbi-docs/report-server/capacity-planning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/capacity-planning.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @djpirra.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @djpirra -- I conferred with the team. They replied:
"Reporting Service LoadTest tool is compatible with Visual Studio 2015 enterprise versions onwards which include VS2019..

Also, this tool execute synthetic load for SQL Server Reporting Services 2016, SQL Server Reporting Services 2017 and Power BI Report Server. As far as I know none of these are deprecated. Any idea what the customer might be referring to in his second comment?

If we haven’t heard back from the customer on the dependencies being deprecated, we could request him to put his feedback directly in Github tool to engage with engineers directly."

Hope that helps!

**Comment by djpirra** [comment]
Hi @maggiesMSFT what information is required from me?
I used VS2019 and was unable to compile the code since the libraries were deprecated.

**Comment by maggiesMSFT** [comment]
Hi, @djpirra -- the recommendation is for you to put your feedback directly in the GitHub page for the tool, to engage with the engineers directly. Here's the GitHub page: 
https://github.com/Microsoft/Reporting-Services-LoadTest
Hope that helps!
