### ISSUE TITLE
Report shared with User and Embed in SharePoint Online shows "This content isn't available."

### ISSUE THREAD

**Issue by bybytaren** [MicrosoftDocs/powerbi-docs#248]
Report Workspace runs on Premium capacity and User is given Read access to Report which is added to Power BI web part on a modern page in a separate site. Report web part loads without issue for Workspace members. I also tested Pin to Dashboard and shared that with User. User can access Report in Power BI but not on SharePoint page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@bybytaren bybytaren Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
