### ISSUE TITLE
Update Text & Screenshots to Match New Desktop Menu Bar

### ISSUE THREAD

**Issue by DaxelCA** [MicrosoftDocs/powerbi-docs#2480]
Power BI Desktop was revamp.
Please update text and screenshots on page
https://docs.microsoft.com/en-ca/power-bi/create-reports/desktop-sort-by-column#sort-using-the-sort-by-column-button

**Sort By Column** is now located under **Column Tools** ribbon.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-ca/power-bi/create-reports/desktop-sort-by-column#sort-using-the-sort-by-column-button)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @DaxelCA -- thanks for pointing that out! Assigning to the author.

**Comment by mihart** [comment]
Hi @DaxelCA , 
Thank you for your suggestion.  We've made the updates and set the article to republish. 
All the best,
The DOCS team
