### ISSUE TITLE
Missing information regarding Paginated Reports

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#2483]
Regarding paginated reports, it would be great to understand where do Premium capacity stores the reports cache.

Additionally wanted to inform the page also refers an email address that does not seem to accepting emails.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @djpirra -- thanks for asking! Assigning to the author for consideration.

**Comment by mihart** [comment]
Hi @djpirra ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by djpirra** [comment]
How was I able to get my answer if none was given here? Please do not close this thread since I still do not have it clarified by the team.
