### ISSUE TITLE
How to create 'Client' object to instance of the Power BI .NET SDK ?

### ISSUE THREAD

**Issue by phaniraj-t** [MicrosoftDocs/powerbi-docs#2484]
How to create 'Client' object to instance of the Power BI .NET SDK IN PostExportRequest() method.
Description:
I have generated the toke using the ClientID and ClientSecret, Then need to call PostExportrequest() method,Here I need to create an object to PowerBI .NET SDK.

Please advice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI paginated reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @phaniraj-t -- assigning to the author to respond.
In the meantime, I recommend asking the Power BI community, https://community.powerbi.com/.
Hope that helps!

**Comment by KesemSharabi** [comment]
Thanks for your comment, @phaniraj-t. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
