### ISSUE TITLE
Tutorial no longer works

### ISSUE THREAD

**Issue by chrisdolby-HE** [MicrosoftDocs/powerbi-docs#2485]
This "Get started using Power BI Desktop" tutorial no longer works. I did report it in the community but no-one's done anything on that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @chrisdolby-HE -- thanks for your comment! Assigned to the author. It might help if you could be more specific: which part doesn't work? If you spelled that out in the community, you could just add a link to it. Thanks!

**Comment by chrisdolby-HE** [comment]
Hi @maggiesMSFT - I mentioned it on the community at the following link: https://community.powerbi.com/t5/Issues/Problem-loading-data-in-Get-Started-with-Power-BI-Tutorial/idc-p/1251857#M59369

**Comment by davidiseminger** [comment]
We're updated that tutorial, thanks!
