### ISSUE TITLE
Update Text and Screenshots

### ISSUE THREAD

**Issue by DaxelCA** [MicrosoftDocs/powerbi-docs#2486]
https://docs.microsoft.com/en-ca/power-bi/create-reports/power-bi-report-add-filter#add-a-filter-to-an-entire-page
https://docs.microsoft.com/en-ca/power-bi/create-reports/power-bi-report-add-filter#add-a-filter-to-a-visual

Both sections should be updated as **Filters** are now managed in Filters pane.

Regards,
Julie

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9848d00-1a27-8d72-88cb-d74cc50c496e
* Version Independent ID: 456b6ffd-5af0-a2d7-aa16-b0335ced93d0
* Content: [Add a filter to a report in Power BI - Power BI](https://docs.microsoft.com/en-ca/power-bi/create-reports/power-bi-report-add-filter#add-a-filter-to-an-entire-page)
* Content Source: [powerbi-docs/create-reports/power-bi-report-add-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/power-bi-report-add-filter.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @DaxelCA -- good points, thanks! I'll add it to my list.

**Comment by mihart** [comment]
Hi @DaxelCA , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
