### ISSUE TITLE
Quickbooks does not exist on Power BI online

### ISSUE THREAD

**Issue by adamson-andy** [MicrosoftDocs/powerbi-docs#2487]
According to this document, I should be able to add the Quickbooks app to Power BI online. When I follow these steps, Quickbooks is not included as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-quickbooks-online)
* Content Source: [powerbi-docs/connect-data/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @adamson-andy -- thanks for your comment! Assigning to the author to investigate.

**Comment by paulinbar** [comment]
Hi @adamson-andy. Indeed the Quickbooks Online template app is no longer available. I have removed the related documentation that you mentioned. Thanks for bringing this to my attention!
