### ISSUE TITLE
"To specify a data category" is wrong

### ISSUE THREAD

**Issue by Sdean1234** [MicrosoftDocs/powerbi-docs#2488]
The documentation says to look for Data Category on the Modeling tab. It is no longer there. It is now listed under Column Tools. 

![image](https://user-images.githubusercontent.com/49075704/92923821-a9d7f780-f3fd-11ea-888d-c3f4133e9cc3.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5bf15cc-1311-278f-5488-0d3c74f01e71
* Version Independent ID: 575f6f93-3945-2278-9027-b1881295078e
* Content: [Data categorization in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-data-categorization)
* Content Source: [powerbi-docs/transform-model/desktop-data-categorization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-data-categorization.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Sdean1234 -- thanks for pointing that out! Assigning to the author.

**Comment by maggiesMSFT** [comment]
@Sdean1234 -- thanks! I fixed the tab name.
