### ISSUE TITLE
Reference to colorutils instead of tooltiputils

### ISSUE THREAD

**Issue by heyconor** [MicrosoftDocs/powerbi-docs#2489]
Under the installation instructions, you accidentally reference **powerbi-visuals-utils-colorutils** instead of **powerbi-visuals-utils-tooltiputils**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0071ce04-4edd-4bc7-eed0-628e81d018b7
* Version Independent ID: dff92842-406b-e368-b37f-e9ca2ce50ca1
* Content: [Introduction to use tooltip utils in Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-tooltip)
* Content Source: [powerbi-docs/developer/visuals/utils-tooltip.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/utils-tooltip.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @heyconor. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
@uve - can you please confirm that what @heyconor is saying is true?

**Comment by uve** [comment]
Hi @heyconor,
 Are you referring to this line?:  

![image](https://user-images.githubusercontent.com/534586/96607316-70f74080-1322-11eb-971a-cbb505d91ef9.png)

**Comment by heyconor** [comment]
Yes, I was. I see it now refers to the correct tootltiputils. Problem solved!
