### ISSUE TITLE
How to escape a single quote in the filter value

### ISSUE THREAD

**Issue by jtjones0304** [MicrosoftDocs/powerbi-docs#249]
We have some filter values which contain single quotes but I don't see how to escape those characters so the single quote isn't interpreted as the end of the parameter value.  For example we have Facility/Hospital eq 'St. Joseph's'.  I've tried using the escape %27 or _x0027_ but non of them work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @jtjones0304 -- Turns out this is product feedback, because escaping single quotes isn't currently supported. I've passed your remark on to the product team. You can also go to  https://ideas.powerbi.com/forums/265200-power-bi and enter it there. Thanks!

**Comment by gopalnunna** [comment]
I am having the same issue , any update on this ?

**Comment by maggiesMSFT** [comment]
Hi, @gopalnunna -- This is product feedback, because escaping single quotes isn't currently supported. Please go to https://ideas.powerbi.com/forums/265200-power-bi to see if @jtjones0304 entered this feedback there. If so, you can vote for it. If not, you can enter it there. Thanks!
