### ISSUE TITLE
"String does not match"

### ISSUE THREAD

**Issue by terrysoltz** [MicrosoftDocs/powerbi-docs#2490]
There is a problem connecting to the data source at Bankrate. Apparently, the web table inference process does not work with this source and must be disabled. It is enabled by default with my new installation. Once it is disabled, it seems to load correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @terrysoltz. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by rjc825** [comment]
How can I disable to proceed with the material? Please advise.

**Comment by mihart** [comment]
Hi @terrysoltz  @rjc825 , 
Thank you for your feedback.  I believe that this problem has been fixed as I am unable to duplicate your issue.  If you are still having trouble, please let us know. 
All the best,
The DOCS team
