### ISSUE TITLE
How to add members

### ISSUE THREAD

**Issue by BobRed0965** [MicrosoftDocs/powerbi-docs#2491]
You show how to add members to a role "select ellipsis" but you don't show how to get to that screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for your comment, @BobRed0965. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by kfollis** [comment]
Thanks for pointing that out @BobRed0965! I'm working on fixing that now and you should see an update in the next day or so.

**Comment by kfollis** [comment]
The update is now pending and will be live on 9/18.
