### ISSUE TITLE
Row Level Security rather than Role Level

### ISSUE THREAD

**Issue by rcoder81** [MicrosoftDocs/powerbi-docs#2493]
Hi!

The PowerBI whitepaper on Security (https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security) refers to "**Role** Level Security", rather than **Row** Level Security.

While this is not on its own incorrect, it is inconsistent with the rest of the PowerBI literature and may cause confusion amongst readers.  Please consider updating the term RLS in the whitepaper to Row Level Security to ensure consistency with the rest of the documentation on the product.

For reference - here is the Docs pages on RLS (Row Level Security) for PowerBI
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-rls
https://docs.microsoft.com/en-us/power-bi/guidance/rls-guidance
https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security

Thank you!

Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment - we will look at making those updates during our next review.
