### ISSUE TITLE
Power BI Desktop Auto Refresh

### ISSUE THREAD

**Issue by md-rahim** [MicrosoftDocs/powerbi-docs#2494]
Hello,

I am using Power BI desktop license version. I am looking for auto refresh option in File menu, settings and option, settings , preview features..... but the option is not there. Also tried at page , format menu from visualization but there also only Filter cards is last option. So, where is my refresh option. my version is latest August 2020. please help me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedb7099-554f-0eed-eaa6-fc13851eb3b1
* Version Independent ID: 8beddbbe-5ebc-60e4-ab28-fd130283a8c1
* Content: [Automatic page refresh in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh)
* Content Source: [powerbi-docs/create-reports/desktop-automatic-page-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-automatic-page-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. Are you using a DirectQuery data source? As the article says, auto refresh is only available for DirectQuery sources.

**Comment by mihart** [comment]
Thanks for your comment, @md-rahim . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
