### ISSUE TITLE
Power BI Desktop Auto refresh option

### ISSUE THREAD

**Issue by md-rahim** [MicrosoftDocs/powerbi-docs#2495]
Hello, 
I didn't find my Power BI desktop auto refresh option. How to get it

![image](https://user-images.githubusercontent.com/33857297/93195174-bdbb8a80-f76a-11ea-855b-60c88c43ec4b.png)

**Comment by md-rahim** [comment]
![image](https://user-images.githubusercontent.com/33857297/93195334-f3607380-f76a-11ea-9667-8d51fd1d1bae.png)

there also not

**Comment by mihart** [comment]
Thanks for your comment, @md-rahim . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @md-rahim , 
Thank you for your question. Automatic page refresh is available for DirectQuery sources and some LiveConnect scenarios, so it will only be available when you are connected to a supported data source. This restriction applies to both automatic page refresh types.   If this doesn't answer your question, please let us know.
All the best,
The DOCS team
