### ISSUE TITLE
Using Analyze in Excel exposes all detail-level data to any users with permission to the dataset.

### ISSUE THREAD

**Issue by Oddjobe** [MicrosoftDocs/powerbi-docs#2496]
1. Can we cleary clarify that RLS isn't supported for the "analyze in Excel" feature
2. If RLS is supported for "analyze in Excel" feature, then specify in what scenarios for example, when published trough an app and the end-user has build permission.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Oddj0b . This issue has been assigned to the doc author for review.

**Comment by Oddj0b** [comment]
You got a job where you wanted a Jobe. It happens @Oddjobe

**Comment by maggiesMSFT** [comment]
Hi, @Oddjobe -- thanks for your question! Yes, Analyze in Excel does support RLS. I'm told if you can't get RLS to work, you need to file a support ticket, https://powerbi.microsoft.com/en-us/support/
Thanks!
