### ISSUE TITLE
Incorrect shortcuts

### ISSUE THREAD

**Issue by mikem-MS** [MicrosoftDocs/powerbi-docs#2497]
The keyboard shortcut for a new line in the DAX formula bar is Shift+Enter not Ctrl+Enter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mikem-MS . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @mikem-MS ,
Looks like this has been fixed in the documentation.  I'm going to close this Issue.  Thank you for your feedback.
