### ISSUE TITLE
References to "on-premises"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2498]
I think the language currently used seems to imply SQL Server Analysis Services is used to host the models. However, my understanding is that the behaviour would be identical for Azure Analysis Services. If so, the "on-premises" references should be removed.

**Comment by mihart** [comment]
Hi @kfollis - assigned to you since this is a very broad suggestion.  Can you triage?  Thanks.

**Comment by mihart** [comment]
Hi @VitalyMCT, 
Thank you for your feedback.  Does your comment refer to a specific document?  If so, please provide the URL.
Take care,
The DOCS team

**Comment by VitalyMCT** [comment]
Sorry, I've mistakenly removed the source URL from the issue template. 

It's https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls

**Comment by kfollis** [comment]
Thanks, @VitalyMCT! We are working on an update to the RLS docs and will certainly evaluate that language. I get what you're saying about the host, so definitely will review for accuracy. I appreciate the input!
