### ISSUE TITLE
Reports using a dataset from another workspace

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2499]
The following info appears to be out of date with the current behaviour of the new workspace experience:

>Power BI automatically creates an entry in the list of datasets if the report is based on a dataset outside of the workspace. The icon for this dataset is different from the icon for datasets in the workspace: 

Likewise for the corresponding screenshot.

**Comment by VitalyMCT** [comment]
@mihart , this is for https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-discover-across-workspaces

Sorry, I must've mistakenly removed the source URL from the issue template.

**Comment by mihart** [comment]
Thanks for your comment, @VitalyMCT . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @VitalyMCT, indeed, the UI may have undergone even more changes since you opened this issue. I'm moving this issue to our work item backlog, and will close it here for now. Thanks for taking the trouble to provide your feedback!
