### ISSUE TITLE
Last refresh not explained/available

### ISSUE THREAD

**Issue by kaylangan** [MicrosoftDocs/powerbi-docs#25]
I used to add "Last refresh" time to the tiles in my dashboard, however, I don't see it available anymore. Some pics in the docs suggest it existed; but there is no information on it. Was it removed and only available in certain versions?

Here's a section that shows a link to specifying "last refresh time", but the page it directs to doesn't have a section for it: https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-tiles.md#interacting-with-tiles-on-a-dashboard

**Comment by mgblythe** [comment]
@mihart -- can you take a look at this and update docs as appropriate.

**Comment by mihart** [comment]
@kaylangan 
Thanks for pointing this out.  Last refresh is no longer available on tiles.  
- Michele
