### ISSUE TITLE
Text boxes and buttons

### ISSUE THREAD

**Issue by ttplaya** [MicrosoftDocs/powerbi-docs#250]
This page makes no mention of text boxes and buttons. Is it possible to customize text boxes and buttons using the template json file? What would the visualName be for those? I tried "text", "textBox", "button", "buttonBox" and none of those worked. Please add documentation for those if the functionality exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @ttplaya! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback @ttplaya - you may find additional information about using themes in the community portal found at https://community.powerbi.com. We'll continue to add more content to the article you mention as our engineering team makes the information available.
