### ISSUE TITLE
Confusion / Missing the explanation on the data type used for the measures

### ISSUE THREAD

**Issue by Ghuiles** [MicrosoftDocs/powerbi-docs#2500]
Hi guys

This page explains well the data type used in for the fields in PBI, but not clearly the data types used for the measures.
A measure generates calculations and results. So, what we see in the tab "Measure Tool" > Format, like "General" (what is this?)  etc, is it pure cosmetic, or does it affect the calculations done by the measure?

BR, G.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-types)
* Content Source: [powerbi-docs/connect-data/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Ghuiles . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
