### ISSUE TITLE
Significant Confusion Caused by Limited Documentation, Error Messages and Multiple APIs for a single task

### ISSUE THREAD

**Issue by BreakingBI** [MicrosoftDocs/powerbi-docs#2501]
I'm working with a Data Collector in the process of building more comprehensive analytics capabilities into their application.  A key part of this is the embedding and automation of Power BI reports through use of the .NET SDK.  They were recently blocked for a few weeks by a scenario where they could not leverage an Azure App Registration Identity to add existing workspaces to capacities.  Our REST API Documentation is very good at calling out the privilege requirements for each API request.  However, there are a number of requests that can be handled by both the Admin and Non-Admin APIs.  Adding a workspace to a capacity is a great example of this.

https://docs.microsoft.com/en-us/rest/api/power-bi/admin/capacities_assignworkspacestocapacity
https://docs.microsoft.com/en-us/rest/api/power-bi/capacities/groups_assigntocapacity

The customer started by using the capacities API, but could not authenticate because they did not follow all of the steps outlined in the following articles

https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-the-new-workspaces#give-access-to-your-workspace
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#create-the-new-workspaces

At some point in this trial-and-error process, they swapped from the capacities API to admin API.  So, even though they did eventually all of the steps outlined above, they were still receiving the same error, shown below.

![image](https://user-images.githubusercontent.com/32003550/93339305-69abb700-f7f9-11ea-97a6-c00bf61a192e.png)

As we said, this was incredibly frustrating for them, as they found it far too difficult to navigate the multiple layers of documentation required and decipher very non-descript error messages.  So, here are a few pieces of feedback they wanted to provide.

1) Create more comprehensive .NET SDK documentation or, if it exists already, make it easier to find.  The documentation available at Link (a) is bare-bones and they found themselves resorting to the REST API documentation at Link (b), which requires abstraction to the .NET Layer.
    (a) https://github.com/Microsoft/PowerBI-CSharp
    (b) https://docs.microsoft.com/en-us/rest/api/power-bi/

2) In the API and SDK documentation, provide links to a fully-worked example or single article that shows all of the requirements in one place.  The requirements below are pulled straight from the REST API documentation and require finding the separate articles above, only 1 of which is actually linked to from the documentation.

Note: To perform this operation, the user must be admin on the specified workspace and have admin or assign permissions on the capacity. To unassign the specified workspace from a capacity, Empty Guid (00000000-0000-0000-0000-000000000000) should be provided as capacityId.

Required scope: Capacity.ReadWrite.All and Workspace.ReadWrite.All
To set the permissions scope, see Register an app.

3) When a developer calls one of the APIs that exists in both the Admin and Non-Admin sections, the error messages should include some small text like "Did you intend to use the Non-Admin version of this request instead?" with some type of hyperlink.  This error message alone would have saved this customer a week or digging.

4) Azure AD App Registrations created in Azure can be individually granted the Power BI permissions in Azure AD and the Workspace Admin permissions in Power BI.  However, only AAD security groups can be granted Capacity Admin permissions in Power BI.  This created an additional layer of complexity, as they needed to continually double-check to make sure that the app registration was in the right security group, which required constant navigation between three portals, the Azure portal, the Power BI user portal and the Power admin portal.

We hope this feedback helps.  Please let us know if you need anything else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92fe917a-772f-783b-927b-a629e83b9915
* Version Independent ID: 58d1916f-3371-0d26-1e11-e81f6a1d2e25
* Content: [What can I do with the Power BI API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/overview-of-power-bi-rest-api)
* Content Source: [powerbi-docs/developer/automation/overview-of-power-bi-rest-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/overview-of-power-bi-rest-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @BreakingBI . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @BreakingBI,

Thank you very much for your detailed feedback, and apologies for the late response. I've forwarded this feedback to the embedded analytics PMs, and we're discussing ways in which we can bridge some of the gaps you're describing (such as a dedicated article for admin and user APIs), and make our documents clearer.

We've already revised the [Register an Azure AD application to use with Power BI](https://docs.microsoft.com/power-bi/developer/embedded/register-app) article, and currently I'm working on updating the tutorials, which will include code samples for .NET, JAVA, C# and more (you can see some of the new samples here: [https://github.com/microsoft/PowerBI-Developer-Samples](https://github.com/microsoft/PowerBI-Developer-Samples)).

Please look out for these future documentation updates, and once again, thank you for contacting us.

Kesem
