### ISSUE TITLE
Outdated documentation on scope identity property selectors

### ISSUE THREAD

**Issue by niklaskarl** [MicrosoftDocs/powerbi-docs#2502]
The documentation at https://docs.microsoft.com/en-us/power-bi/developer/visuals/objects-properties#scope-identity seems to be outdated. The section about **Scope identity** refers to _DataViewScopeIdentity_ which is obsolete as of Version 2.1.0 (see: [Changelog](https://docs.microsoft.com/en-us/power-bi/developer/visuals/changelog#api-v210)). It says there that the interface was replaced with _data.DataRepetitionSelector_. In Version 2.5.0 (see: [Changelog](https://docs.microsoft.com/en-us/power-bi/developer/visuals/changelog#api-v250)) it says that _data.DataRepetitionSelector_ once again is replaced with _data.CustomVisualOpaqueIdentity_. Could you please update the documentation to reflect the most recent changes or give me an example on how to use scope identity property selectors in the latest version? Unfortunately there seems to be no example of this functionality on the web and neither _DataRepetitionSelector_ nor _CustomVisualOpaqueIdentity_ have a definition in the typescript typings of the power-bi apis.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b18bae87-ca93-25e9-26a6-5daf585b4798
* Version Independent ID: 2c2793d0-50a6-c401-3ecf-ccba9f155397
* Content: [Objects and properties of Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/objects-properties)
* Content Source: [powerbi-docs/developer/visuals/objects-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/objects-properties.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @niklaskarl. I'm assigning this to the author to review and comment and make updates as appropriate.

**Comment by KesemSharabi** [comment]
@uve - can you please respond to @niklaskarl's comments?

**Comment by uve** [comment]
thanks @niklaskarl for the feedback. We'll update the documentation soon.
