### ISSUE TITLE
Question about PBI B2B Tenant settings vs Documentation

### ISSUE THREAD

**Issue by mathiasekz** [MicrosoftDocs/powerbi-docs#2503]
The PBI tenant setting  Allow Azure Active Directory guest users to access Power BI which is described in the following article is not longer available in the tenant settings UI.

https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#export-and-sharing-settings

 Same comment for the setting Invite external users to your organization (documented but not visible in the tenant).

 Now we have these 2 settings:

- Share content with external users

- Allow external guest users to edit and manage content in the organization

These 2 settings are explained here:

https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi

One on my customer told me that this gap between articles is a bit confusing and would like to understand why we have this gap. I think this is just a question of document update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#export-and-sharing-settings)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for your comment, @mathiasekz. I agree that there is a need for a documentation update here. I'll assign a writer to take a look and make sure we're consistent across articles.

**Comment by kfollis** [comment]
I am closing this issue now. The referenced tenant settings article is accurate and the settings documented match what is shown in UI. The referenced whitepaper is intended to present a single scenario and is not inclusive of all related settings. It's possible that at the time the issue was created that settings were in the process of being updated, creating the confusion and inconsistency.
