### ISSUE TITLE
Some limitations of public preview of Featured Tables can be removed

### ISSUE THREAD

**Issue by markvsql** [MicrosoftDocs/powerbi-docs#2504]
The updated limitations should be as follows:

Here are limitations for the initial preview.
•	Featured tables in Power BI datasets that use the following capabilities aren't shown in Excel:
o	DirectQuery datasets. 
o	Datasets with a live connection. 
•	Excel shows only data in columns and calculated columns in the featured table. The following aren't provided in the initial preview:
o	Measures defined on related tables, and implicit measures calculated from relationships. 
•	Excel only displays featured tables that are stored in the new Power BI workspaces. Featured tables stored in the classic workspaces aren't shown as data types in Excel. You can upgrade classic workspaces to the new workspaces in Power BI.
•	See Considerations and limitations in the article "Access Power BI featured tables in Excel" for other Excel considerations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f8fd61-1d7c-6da2-7279-d88d72668a8a
* Version Independent ID: ce00fe65-ac80-be40-1bbd-ac799e6a2c53
* Content: [Set featured tables in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-excel-featured-tables)
* Content Source: [powerbi-docs/collaborate-share/service-create-excel-featured-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-create-excel-featured-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @markvsql -- Thanks for the update! I'll ping you offline about how you can make updates yourself!

**Comment by maggiesMSFT** [comment]
@markvsql -- updating now.

**Comment by markvsql** [comment]
Awesome. Thanks so much!

Mark Vaillancourt
(he/him)
Senior Program Manager
Power BI Customer Advisory Team

[cid:image001.jpg@01D68D2C.303E6040]
