### ISSUE TITLE
help? colors

### ISSUE THREAD

**Issue by chloestrasser** [MicrosoftDocs/powerbi-docs#2506]
I am using the electronic version of power bi. I don't see diverging colors in the data color option or able to click the three circles in the conditional formatting section mentioned on the page: https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting

I would appreciate any help. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in reports - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @chloestrasser. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @chloestrasser, 
The Power BI team has recently updated the conditional formatting experience.  You no longer need to select "the three circles"  :-) Please see the new documentation: https://docs.microsoft.com/power-bi/visuals/service-tips-and-tricks-for-color-formatting.  Thank you for your feedback.
