### ISSUE TITLE
How to export the data from the tab

### ISSUE THREAD

**Issue by Karthik301** [MicrosoftDocs/powerbi-docs#2507]
[Enter feedback here]

In MS Teams tab, when i export the data from POWER BI dashboard, i get the export completed message and nothing else. 
Not sure where the data got downloaded and saved. please help me explain. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0631fa24-d631-c11b-4984-7b518523cc6a
* Version Independent ID: ff9d382b-6c53-3662-0229-fb1e72f62c14
* Content: [Embed Power BI reports in Microsoft Teams - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-microsoft-teams)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-embed-report-microsoft-teams.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Karthik301. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @Karthik301 -- great question! I just tried it. You're right, you don't see where it went. It was saved, though -- check your Downloads folder. It's an Excel file called "data (n).xlsx" where *n* is the number of times you've exported data to the same folder. I'm up to data (19).xlsx myself. 
I'll add this to the article.

**Comment by Karthik301** [comment]
Thanks @maggiesMSFT for your explanation, I am able to find the files in the download folder. May be I missed to check these files because of the modification date for these downloaded files shows in the past. 
![WrongTime Stamp](https://user-images.githubusercontent.com/71615435/93837138-69635e00-fcc8-11ea-9a15-3dcaeb240edd.JPG)
