### ISSUE TITLE
Power BI Report Builder - extra blank rows in csv export

### ISSUE THREAD

**Issue by sukajalan2** [MicrosoftDocs/powerbi-docs#2508]
When exporting to csv file, two blank rows are included at the end of the csv file. Opening the csv file in excel does not show these 2 blank rows. Using power shell to count the rows also does not reveal these 2 extra rows. It shows only when the csv file is opened using notepad. 

It looks like the same issue with this bug?
https://feedback.azure.com/forums/908035-sql-server/suggestions/32910175-bug-557655-ssrs2008-extra-blank-line-in-csv-file

**Comment by davidiseminger** [comment]
Thanks for your comment @sukajalan2 - could you let us know which Power BI article you're referencing, so we can find the appropriate writer to help with your question? Thanks.

**Comment by sukajalan2** [comment]
@davidiseminger I found this link. It looks like it

https://feedback.azure.com/forums/908035-sql-server/suggestions/32910175-bug-557655-ssrs2008-extra-blank-line-in-csv-file

![image](https://user-images.githubusercontent.com/30907390/93831443-6a4caf00-fc38-11ea-9b96-51dd0f648b30.png)

**Comment by mihart** [comment]
Thanks for your comment, @sukajalan2 . Since this is a support request or product question rather than documentation feedback, I'm going to close this git issue. I see that this is a known issue -- if you add your votes to the Idea, it increases the chances that the Product team will work on it.
All the best,
the DOCS team

**Comment by sukajalan2** [comment]
Apparently this issue has been resolved. There are no more extra blank lines for csv export. However, there are still extra blank lines in excel export. Thanks.
