### ISSUE TITLE
BigQuery Service Refresh Permissions Issue

### ISSUE THREAD

**Issue by sarasanalytics** [MicrosoftDocs/powerbi-docs#2509]
Starting from Saturday, we started to get this error when we refresh the dataset using Power BI REST API. We did not change the permissions or anything in last 3 months. Is there a release that happened? We have bigquery.dataOwner and bigquery.jobuser permissions for the project. I don't know why this is giving a Google BigQuery Storage API error?

Data source errorERROR [HY000] [Microsoft][BigQuery] (131) Unable to authenticate with Google BigQuery Storage API. Check your account permissions.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action. Table: fOrders.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-bigquery)
* Content Source: [powerbi-docs/connect-data/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-bigquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by gfelot** [comment]
No more news about it ? I have the exact same issue for one of my user, the other are fine.

**Comment by mihart** [comment]
Thanks for your comment, @gfelot  @sarasanalytics . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
