### ISSUE TITLE
'Create a real-time Power BI dashboard' is no longer available

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/powerbi-docs#251]
'[Create a real-time Power BI dashboard](https://msdn.microsoft.com/library/mt267603.aspx)' has no content in the '[Real-time dashboard](https://docs.microsoft.com/en-us/power-bi/refresh-data#real-time-dashboards)' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data#real-time-dashboards)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @kazshi and you're right - that article has been removed. I've removed the reference to it as well.
