### ISSUE TITLE
Obsolte or missing screenshot

### ISSUE THREAD

**Issue by thierryhouy** [MicrosoftDocs/powerbi-docs#2510]
[Enter feedback here]
Hello, 

The screenshot on Using RLS with workspaces in Power BI only takes into account classic deprecated Workspaces (v1) and not the new experience (v2) the default today which confuses the users.

Thank you,
Thierry Houy-Boucheny

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls#using-rls-with-workspaces-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @thierryhouy.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @thierryhouy -- great point! Just fixed that section, clarifying exactly what you bring up. Change will be live this afternoon 9 April 2021. Thanks@
