### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by shakanand** [MicrosoftDocs/powerbi-docs#2512]
The current documentation does not clearly call out that export to PDF only export only the visible elements from the page. For example, if table has 500 rows, the exported PDF will only have what's was visible on the screen.   Please make this part clear in our documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export your reports to PDF format from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-export-to-pdf)
* Content Source: [powerbi-docs/create-reports/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-export-to-pdf.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @shakanand. Thanks for your feedback! I am forwarding it along to the doc author for consideration.

**Comment by mihart** [comment]
Hi @shakanand , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
