### ISSUE TITLE
Web Service

### ISSUE THREAD

**Issue by dotnick365** [MicrosoftDocs/powerbi-docs#2513]
Can we please ensure that the FQDN and IP information is published and maintained through the Microsoft 365 Web Service? This is the best approach as it allows a automated, programmatic, and centralized way to obtain all necessary FQDN and IP information. Great to maintain it here as well.

https://docs.microsoft.com/en-us/microsoft-365/enterprise/microsoft-365-ip-web-service?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview#power-bi-urls-for-general-site-usage)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the feedback, @dotnick365! Yes, our goal is to make the FQDN and IP info available through the web service - and we agree that's the best approach. I'll share your feedback with the engineering team.
