### ISSUE TITLE
Update required for the authentication example. ADAL authentication to MSAL

### ISSUE THREAD

**Issue by aditya-s-prabhu** [MicrosoftDocs/powerbi-docs#2515]
Update required for the authentication example. ADAL authentication to MSAL
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @aditya-s-prabhu -- thanks for your comment! Assigning to the author to take care of.

**Comment by KesemSharabi** [comment]
Hi @aditya-s-prabhu,

This issue is in my backlog and I'll refresh the article as soon as I can.

Thanks,

Kesem
