### ISSUE TITLE
pbiviz commands & certificate instructions do not work as expected

### ISSUE THREAD

**Issue by douglasg14b** [MicrosoftDocs/powerbi-docs#2516]
Three issues:

1. `pbiviz` cannot be ran from powershell due to `pbiviz.ps1` not being digitally signed.
    * `File C:\Users\Douglas\AppData\Roaming\npm\pbiviz.ps1 cannot be loaded. The file C:\Users\Douglas\AppData\Roaming\npm\pbiviz.ps1 is not digitally signed. You cannot run this script on the 
current system.`
2. When `pbiviz --install-cert` is ran from CMD it does not open the `Certificate Import Wizard`.
3. The certificate that is generated by  `pbiviz --install-cert` is literally a 0-byte file named `blank` despite the command showing that a certificate was generated
    * Output: `Certificate not found. The new certificate will be generated
 info   Certificate generated. Location is C:\Users\Douglas\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\certs\PowerBICustomVisualTest_public.pfx. Passphrase is '[snip]'`

There needs to be alternative instructions as it seems the current ones are pretty fragile, that or the tooling is broke?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d42a638-f0b9-abd1-43da-0c1618394948
* Version Independent ID: 1350b334-88ef-1aaf-61b6-6b78ab1baf82
* Content: [Developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @douglasg14b -- thanks for your comment! Assigning to the author to investigate.

**Comment by KesemSharabi** [comment]
@douglasg14b,

I revamped this tutorial - please try to follow the instructions in [Tutorial: Develop a Power BI circle card visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/develop-circle-card).

Hopefully this should work for you.

Thanks,

Kesem
