### ISSUE TITLE
Review EmbededService.cs AuthorityUrl value.

### ISSUE THREAD

**Issue by uron83** [MicrosoftDocs/powerbi-docs#2517]
When authenticating with ServicePrincipal [EmbededService.cs](https://docs.microsoft.com/en-us/power-bi/developer/embedded/get-azuread-access-token#embedservicecs)
The AuthorityUrl must be https://login.microsoftonline.com/*TenantId* where TenantId id is the AppId tenant.
Otherwise, PowerBI will return Unauthorized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 856c2459-1221-d37d-a977-7baf42bedc80
* Version Independent ID: d99e1b35-749d-a75b-3f1a-f6502eb022ee
* Content: [Authenticate users & get Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/embedded/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @uron83 -- thanks for your comment! Assigning to the author to investigate.

**Comment by KesemSharabi** [comment]
@uron83,

Thank you for spotting this and letting us know. You're correct, `AuthorityUrl` should end with `TenantId` - this is now fixed in the article.

Thanks,

Kesem
