### ISSUE TITLE
Not closed link after 'Complete code listing'

### ISSUE THREAD

**Issue by FoxyChmoxy** [MicrosoftDocs/powerbi-docs#2518]
Maybe you forgot to close the link, because all the text, including the code, turned into a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33bbd1b-d18e-600f-5ab1-36b8d9ed335f
* Version Independent ID: 11afb4f2-cd83-4a6e-ce66-3ceaa82407cd
* Content: [Add rows to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-add-rows)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-add-rows.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-add-rows.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Thanks for pointing that out! Fixed it.
