### ISSUE TITLE
Sharing Report Grants Analyze in Excel Permissions

### ISSUE THREAD

**Issue by dpcollins-bi** [MicrosoftDocs/powerbi-docs#2519]
This page states: "Users can connect to datasets through Analyze in Excel if they have permission for the underlying dataset. A user could have this permission in several ways, such as having the Member role in the workspace containing the dataset, **having a report or dashboard shared to them that uses the dataset**, or having Build permission for the dataset"

I do not believe merely sharing a report bypasses the need for BUILD permissions on the dataset, based on community posts and testing. This should be clarified. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel#requirements)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @dpcollins-bi. We’ve assigned your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @dpcollins-bi , good point! I'm updating the article to state that you need Build permission, not just sharing. Thanks!
