### ISSUE TITLE
It's not possible to connect to Azure Data Lake Storage diagnostic logs.

### ISSUE THREAD

**Issue by GaryStrange** [MicrosoftDocs/powerbi-docs#2521]
Azure Data Lake Storage Gen2 can be configured to capture diagnostic logs. The logs are written to the system controlled $logs container.

The PBI - Azure Data Lake Storage Gen2 connector (in preview) uses a URL end-point to connect to ADLS Gen2. To read the $logs container the URL would need to be:  https://myresourcename.blob.core.windows.net/$logs

However, the connector considers the URL to be invalid.

Details: "The Container name must be 3 to 63 lower case letters and numbers. It must start with a letter or number and can contain only letters, numbers, and the dash (-) character. No consecutive dashes are allowed. Every dash (-) character must be immediately preceded and followed by a letter or number."

Thanks,

Gary

**Comment by mihart** [comment]
Thanks for your comment, @GaryStrange . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
