### ISSUE TITLE
to export the data from a visual, Build permission is no more needed

### ISSUE THREAD

**Issue by JasaBB** [MicrosoftDocs/powerbi-docs#2522]
Hi all,
Please review this statement in Limitations and considerations section:
"To export the data from a visual, you need to have Build permission for the underlying dataset."

It is enough to have App permissions (without Build) to be able to export data from a visual.
br, Jasa 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @JasaBB. This issue has been assigned to the doc author for review.

**Comment by msftrien** [comment]
I don't know what the "App permission" is. I imagine it might mean "access" permission? But build permission is a requirement to export underlying data (to be clear, there are other forms of exporting data that don't require build permission). @mihart I don't think this warrants any changes to docs
