### ISSUE TITLE
Q&A Tooling note

### ISSUE THREAD

**Issue by markvsql** [MicrosoftDocs/powerbi-docs#2523]
Since the Note regarding Q&A Tooling only currently support Import connections applies to all Tooling, not just the Teach Q&A feature, should the note move from the Teach Q&A Limitations section to the Tooling Limitations section? I chose to leave this feedback rather than change it myself in case there was something I was missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c83048-7e4e-0df6-bd4c-16097df348cd
* Version Independent ID: c275fe95-edd1-a8c6-4b00-4857e1e65aab
* Content: [Limitations of Power BI Q&A - Power BI](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-limitations#teach-qa-limitations)
* Content Source: [powerbi-docs/natural-language/q-and-a-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/natural-language/q-and-a-limitations.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @markvsql -- thanks for asking. Checking with the PMs.

**Comment by paulinbar** [comment]
Hi @markvsql, moving this issue to our work item backlog. Closing it here in the meantime.
