### ISSUE TITLE
Error when setting up - Use Web Application Proxy and Active Directory Federated Services - Power BI Report Server

### ISSUE THREAD

**Issue by mimanu** [MicrosoftDocs/powerbi-docs#2525]
I'm trying to setup a adfs login later with MFA on my Powerbi report server which will be access internally

I've seen this article and follow the steps: https://docs.microsoft.com/en-us/power-bi/report-server/connect-adfs-wap-report-server

I've finished the guide and tried to access the site. but got an error. tried the some online resolutions based from error code but it didnt solve the issue
 
Report Server Configuration
![image](https://user-images.githubusercontent.com/41720328/94792134-1d709180-040b-11eb-9f8b-f60a20f744db.png)

when tried to access the URL configure on the external. I encounter an error 
![image](https://user-images.githubusercontent.com/41720328/94792182-2d887100-040b-11eb-8353-5f64d413d1eb.png)
![image](https://user-images.githubusercontent.com/41720328/94792436-8e17ae00-040b-11eb-900e-e7bea4f2a259.png)
![image](https://user-images.githubusercontent.com/41720328/94792241-44c75e80-040b-11eb-9b09-7775550126f4.png)
![image](https://user-images.githubusercontent.com/41720328/94792277-501a8a00-040b-11eb-84c6-b3357395fa51.png)

**Comment by kfollis** [comment]
Hi @mimanu - I'm sorry you're having trouble with the configuration. This channel is for documentation feedback, however, you can contact Support to start a ticket here: https://powerbi.microsoft.com/en-us/support/. Or, you might try posting your question to the community to get help from your peers here: //community.powerbi.com/
