### ISSUE TITLE
Please add that 1-to-1 relations cannot be imported for Direct Query

### ISSUE THREAD

**Issue by KevinDEX** [MicrosoftDocs/powerbi-docs#2526]
While setting up some reports for my companies data management team, we attempted to import several tables that used a Primary Key on one table, with a foreign key in another table pointing to that PK as well as a unique constraint on the column.  These relationships should be sufficient for Power BI to recognize the relationship between the tables as 1-to-1.  And in fact it will if you set the option to NOT detect relationships, then set it manually.  If you set it to detect relationships, it maps it to 1..* and it will say 1-1 is an invalid mapping if you attempt to change it.

I brought this up in a support ticket with power bi support team, and confirmed that this is not possible.

This seems like a bug or at least a limitation that should be specified in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about#modeling-limitations)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @KevinDEX. I'm assigning this to the writer to review and make any updates needed to the article. Thanks for raising the issue!

**Comment by davidiseminger** [comment]
Thanks for your feedback, we've forwarded this to the feature team for consideration.
