### ISSUE TITLE
Seeking clarification on certification requirements "Code Quality"

### ISSUE THREAD

**Issue by douglasg14b** [MicrosoftDocs/powerbi-docs#2527]
`Code Quality` is a broad term embroiled in a significant amount of subjectivity and ambiguity. There are numerous principles, smells, and patterns that may be recognized & employed to ensure a code base is `clean`. In many cases it can even boil down to personal preferences. Knowing what Microsoft considers unambiguously `clean` will help optimize the direction of such a drive. Most of these items optimize for readability & maintainability, which are both mentioned in the description of this policy.

I am seeking clarification for concrete policies/requirements that highlight the minimum acceptable level of quality for such a repository.

Thanks!

Ref: https://docs.microsoft.com/en-us/legal/marketplace/certification-policies#120012-code-quality
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f4f9f01-c83a-e696-5347-ff7f714ad78d
* Version Independent ID: 88855898-104f-7ad4-49ca-dc566edfd0f7
* Content: [Certified Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified#source-code-requirements)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-certified.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/power-bi-custom-visuals-certified.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @douglasg14b -- thanks for the question! Passing along to the author for consideration.

**Comment by douglasg14b** [comment]
Thanks!

**Comment by KesemSharabi** [comment]
@douglasg14b,

You're right, [Code Quality](https://docs.microsoft.com/legal/marketplace/certification-policies#120012-code-quality) is somewhat ambiguous. However if your code is readable, maintainable and exposes no functionality errors, it should be ok.

@uve - is there anything to add here re the code for creating a Power BI visual?

Thanks,

Kesem

**Comment by douglasg14b** [comment]
Hi @KesemSharabi What you mentioned is *literally* what I am seeking clarification on. I, personally, understand maintainable & readable code, however, this must be quantified in a way that is actionable.

For context, I'm looking at a couple PBI visuals that are definitely not clean, readable, or maintainable by *my* standards. The key here is `by my standards`, I have pretty high standards for code quality, you may not. This is where the subjectivity becomes problematic, do we submit visuals assuming the quality is "good enough", or put further work into cleaning it up? The ambiguity makes it difficult for organizational decisions to be made there, as each person has different opinions on what quality code is.

**Comment by KesemSharabi** [comment]
Hi @douglasg14b

What your suggesting seems like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

Hope this helps,

Kesem
