### ISSUE TITLE
Delete workspace information incomplete

### ISSUE THREAD

**Issue by roberdaniel** [MicrosoftDocs/powerbi-docs#2528]
This clarification is needed:
If you create a O365group a workspace with the same name is created.
If this workspace is in "classic mode" and you delete it the associated AD group is also deleted.
but if the workspace has been migrated to "New experience mode" and you delete it the AD group is not deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, dataset, or workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-delete)
* Content Source: [powerbi-docs/create-reports/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-delete.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment and input, @roberdaniel ! We've assigned this to the writer of the article, who will take a look at it shortly.

**Comment by maggiesMSFT** [comment]
Hi, @roberdaniel -- good catch! Fixing it now; update will be live tomorrow.
