### ISSUE TITLE
The link for Matt Masson script seems broken

### ISSUE THREAD

**Issue by dudu-markovitz** [MicrosoftDocs/powerbi-docs#2529]
It seems to lead to the right page ("Creating a Date Dimension with a Power Query Script") but the script is not shown and there is also a message "There has been a critical error on your website."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e837063b-c36b-6bac-5c6b-10534146325c
* Version Independent ID: 7dcf1114-8d0e-39e7-e58f-894904f5a252
* Content: [Create date tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/model-date-tables)
* Content Source: [powerbi-docs/guidance/model-date-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/model-date-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by davidiseminger** [comment]
Thanks for your comment @dudu-markovitz - sorry about the inconvenience. We've assigned this issue to the article's author, who will review and take a look at the issue soon. Thanks!

**Comment by peter-myers** [comment]
Thanks @dudu-markovitz for pointing this issue out. I'd hoped that Matt's blog would come back online, but alas no. I've removed the reference. #please-close
