### ISSUE TITLE
No indication of minimum version for features

### ISSUE THREAD

**Issue by tamasys** [MicrosoftDocs/powerbi-docs#253]
The documentation doesn't list a version that features were introduced in, so I'm not sure if I'm doing something wrong when using this, or if it just isn't supported on the old version of Power BI available at my workplace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @tamasys ,
Thank you for your question.  I've forwarded this info to the document author and we'll get this addressed asap.  Thanks, Michele

**Comment by davidiseminger** [comment]
Thanks for your comment @tamasys. You're right, we do not track minimum versions of Power BI Desktop on a feature level. We always suggest you download and use the most current version of Power BI Desktop to ensure the functionality is as up to date as possible.

**Comment by tamasys** [comment]
@davidiseminger Unfortunately a) Power BI for Report Server is always a few versions behind, and b) most corporations control which version of a product is available. So using the latest version isn't actually an option for a lot of users.
