### ISSUE TITLE
Clarify which data sources are affected by "maximum number of connections per data source" setting

### ISSUE THREAD

**Issue by mattmasson** [MicrosoftDocs/powerbi-docs#2530]
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about#maximum-number-of-connections-option-for-directquery

We should clarify which data sources are impacted by the "maximum number of connections per data source" setting. I believe it only impacts legacy/cartridge based connectors, and not DQ connectors that go through Power Query. If it does impact Power Query sources, there might be a different number of default/max value than cartridge based connectors. The Power BI Desktop team should be able to clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about#maximum-number-of-connections-option-for-directquery)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, I'll follow up with the Power BI Desktop team.

**Comment by davidiseminger** [comment]
The setting applies equally to all DirectQuery data sources, when enhanced metadata is enabled (this is now the default setting). Legacy data sources - for datasets created prior to October 2020, or not updated to use enhanced metadata - are impacted differently. I've included a note to clarify.
