### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by kevman123** [MicrosoftDocs/powerbi-docs#2531]
In the Military Contractors (DoDCON) section there is a typo. There should be no S on microsoftonline.us

<add key="authorityUrl" value="https://login.microsoftonlineS.us/common/" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0658cf44-97c9-cb23-68bd-146f29eb644c
* Version Independent ID: e05ed89e-2dfa-0d31-4198-9170a33ef120
* Content: [Embed content in your application for government and national cloud - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers-national-clouds)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @kevman123. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @kevman123,

Thanks for spotting this typo and notifying us - it is now fixed.
