### ISSUE TITLE
50 Page Limit per hour

### ISSUE THREAD

**Issue by talderman** [MicrosoftDocs/powerbi-docs#2532]
My apologies if this not the correct places for this ask.

I think it would be helpful if there is any information added about how or if page count can be tracked through the API

My reason for this ask is for automation:
I want to a feature to my application that will allow reports to be exported to PDF.  If I have multiple users active creating these exported PDF documents.  I want to be able to get the available pages in that current hour.   This maybe something I need to track at the application level, but I wanted to know if this information was available through the API.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#limitations)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @talderman. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @talderman, 

I double checked with the development team and unfortunately there isn't a way to monitor the number of Power BI report pages exported per hour.

The good news is that when this feature becomes a General Availability (GA) feature (sometime during 2021), the 50 page per hour restriction will be removed.

Thanks,

Kesem

**Comment by BlazinSun0** [comment]
> Hi @talderman,
> 
> I double checked with the development team and unfortunately there isn't a way to monitor the number of Power BI report pages exported per hour.
> 
> The good news is that when this feature becomes a General Availability (GA) feature (sometime during 2021), the 50 page per hour restriction will be removed.
> 
> Thanks,
> 
> Kesem

Hi @KesemSharabi , just wondering if the 50 page per hour restriction is still on schedule to be lifted in 2021?  

Thanks.

**Comment by DevRahul05** [comment]
@KesemSharabi , 

Hi,

What would be the new limit once this feature becomes General Availability (GA) feature?
