### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by kevman123** [MicrosoftDocs/powerbi-docs#2533]
The link provided for the Embedded Setup tool is wrong. It is pointing to the commercial version and should point to:

https://app.high.powerbigov.us/embedsetup/appownsdata

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @kevman123 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @kevman123,

You're right about the link being wrong. However, we have a new version of this tool which differs from the link you suggest - [https://app.powerbi.com/embedsetup](https://app.powerbi.com/embedsetup).

I'll update the documents shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @kevman123,

I fixed the incorrect link in the [Set up your embedded analytics development environment](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#set-up-your-embedded-analytics-development-environment) section.

Once again, thanks for pointing this out,

Kesem
