### ISSUE TITLE
Feedback 

### ISSUE THREAD

**Issue by mercytum** [MicrosoftDocs/powerbi-docs#2534]
[Enter feedback here]
Under Prerequisite:
1. Adding the file wasn't on the upper left but the bottom left (called get data)
2. I was confused by the report view and went to the reports section under my workspace. However, I later realized that steps 3 and 4 should have been done under Datasets in my workspace. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38dbc6a2-d5f6-dd85-76ce-20755a81c148
* Version Independent ID: 35ecb094-52f5-0294-74dd-5975e359ad6d
* Content: [Treemaps in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-treemaps)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-treemaps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-treemaps.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by mihart** [comment]
Thanks for your comment, @mercytum . This issue has been assigned to the doc author for review.

**Comment by msftrien** [comment]
mercytum found a different way to do the tutorial prerequisite, but the instructions in the doc aren't wrong or unclear. It sounds to me like the major disconnect here is that mercytum was on Service, not Desktop? And so was looking at the wrong screens while trying to follow the instructions. Recommend closing the issue (but not sure how to do this)

**Comment by mihart** [comment]
Hi @mercytum , 
Thank you for your suggestion.  I spoke with the product PM. You've discovered a different way to complete the tutorial, but the instructions in the doc are also valid.  There are some differences in the UI when you use Power BI service versus Power BI Desktop.  This article used Desktop and we believe that you were using the service and that was one of the reasons that you had a different experience. 
All the best,
The DOCS team
