### ISSUE TITLE
which enduser/consumer permissions needed when publishing paginated report as App? 

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/powerbi-docs#2536]
Szenario:
- I created with Report Builder a paginated Report, it has two datasources: AzureAS + PBI Dataset published in Workspace1
- I created a App1 in Workspace1 which includes the paginated Reports
Questions:
Which permissions needs to be set for endusers to be able to use the paginated report via app publishing and without the need to give the user workspace permissions?

Full community entry:
https://community.powerbi.com/t5/Desktop/Paginated-Reports-with-PBI-Dataset-which-permissions-needed-when/m-p/1418155#M599095 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @JJDE -- I'll check and get back to you. Thanks for asking!

**Comment by maggiesMSFT** [comment]
Hi, @JJDE -- OK, thanks to a quick response, I'm able to get back to you. It's a support issue, so you need to open a support case at https://powerbi.microsoft.com/en-us/support/. 
Thanks!
