### ISSUE TITLE
Change Query Editor button to Transfor Data

### ISSUE THREAD

**Issue by dayawn** [MicrosoftDocs/powerbi-docs#2537]
The documentation says to click on the Powery Query editor button in the Home tab but the button has been renamed in the current version of PowerBI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6ac628-d5b4-e722-0532-d467c8347a5a
* Version Independent ID: 20ec07f6-627d-3765-ddcb-4aa738b6952a
* Content: [Query overview in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-query-overview)
* Content Source: [powerbi-docs/transform-model/desktop-query-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/transform-model/desktop-query-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @dayawn -- thanks for pointing that out! Assigning to the author.

**Comment by mihart** [comment]
Hi @, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
