### ISSUE TITLE
Its not clear where the code should be copied

### ISSUE THREAD

**Issue by MehdiRMS** [MicrosoftDocs/powerbi-docs#2538]
Its not clear where the code should be copied
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-bar-chart)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @MehdiRMS -- thanks for asking! Assigning to the author.

**Comment by KesemSharabi** [comment]
Hi @uve, can you please help @MehdiRMS understand where the code needs to be copied to?

**Comment by uve** [comment]
@MehdiRMS, please get the full source code of the visual here: 
https://github.com/Microsoft/PowerBI-visuals-sampleBarChart
