### ISSUE TITLE
On-Premises Gateway can also be used to allow access to services using virtual networks

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#254]
On-Premises Gateway can also be used to allow access to services using virtual networks, as for example Azure Analysis Services requiring access to SQL DW on a VNet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @djpirra ,
Thank you for your Power BI doc feedback.  I've assigned this to the author who will work on it asap. 
Take care,
Michele

**Comment by mgblythe** [comment]
@arthiriyer - will clarify this when we do gateway docs update.

**Comment by mgblythe** [comment]
Fixed - we added a note after the list of available data source types at https://docs.microsoft.com/power-bi/service-gateway-data-sources#list-of-available-data-source-types. I'll probably pull the info up to the top of the table. Thanks!
