### ISSUE TITLE
Is it applicable for Power BI Desktop for Report Server?

### ISSUE THREAD

**Issue by eperfilyev** [MicrosoftDocs/powerbi-docs#2540]
Hi Team,

Is it applicable for Power BI Desktop for Report Server?

Also which registry parent folder it is?

In the text it refers to HKEY_LOCAL_MACHINE and on the picture it's HKEY_CURRENT_USER

Thank you

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Troubleshooting Sign-in issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-gb/power-bi/connect-data/desktop-troubleshooting-sign-in)
* Content Source: [powerbi-docs/connect-data/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @eperfilyev -- thanks for asking! I'll check and get back to you.

**Comment by mihart** [comment]
Hi @eperfilyev , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
