### ISSUE TITLE
are these content the latest?

### ISSUE THREAD

**Issue by delphinechenhong** [MicrosoftDocs/powerbi-docs#2541]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a5b29e-747f-20fe-2184-e1b68bc5558b
* Version Independent ID: 1175916c-1360-7786-c007-0ddf044d5315
* Content: [Drill down and drill up in a visual - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-drill)
* Content Source: [powerbi-docs/consumer/end-user-drill.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-drill.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @delphinechenhong -- thanks for asking! Assigning to the author.

**Comment by mihart** [comment]
Hi @delphinechenhong, 
Thank you for your suggestion.  We aim to have all documentation up-to-date at all times. Unfortunately, we sometimes fall behind.  I've moved this article up on the list for a freshness pass.  In the meantime, if you have specific questions, please let us know. 
All the best,
The DOCS team
