### ISSUE TITLE
Content Update - Synapse Link

### ISSUE THREAD

**Issue by Rodrigossz** [MicrosoftDocs/powerbi-docs#2545]
[Enter feedback here]

Hello @davidiseminger and @maggiesMSFT 

Can you please update this content and replace SQL DW with Azure Synapse Analytics and also Azure Synapse Link?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @Rodrigossz , thanks for your comment. I have forwarded it along to David. He'll take a look at this soon.

**Comment by Rodrigossz** [comment]
Hello @davidiseminger and @paulinbar 

It would be great if you could drill down to Synapse runtime level: Instead of Azure Synapse Analytics, be specific to SQL Pool, SQL serverless Pool, Spark Pool, etc.

Tks

**Comment by davidiseminger** [comment]
Completed - thanks!
