### ISSUE TITLE
Sales table - display issue

### ISSUE THREAD

**Issue by AkhilMadivada** [MicrosoftDocs/powerbi-docs#2546]
In the article, you mentioned **order line number** columns haven't been loaded to the Sales table. But, if you see the diagram it shows the **order line number** in the Sales table. 

![image](https://user-images.githubusercontent.com/32743267/95687098-58668800-0bb6-11eb-981a-c9b31eb35b10.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b48a70da-5b66-7cff-ccaa-d792822855b1
* Version Independent ID: 83df0b29-0204-e119-e0f1-6adf17d190e3
* Content: [One-to-one relationship guidance - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/relationships-one-to-one)
* Content Source: [powerbi-docs/guidance/relationships-one-to-one.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/guidance/relationships-one-to-one.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by paulinbar** [comment]
Hi @AkhilMadivada , thanks for your comment. I am forwarding it along to the doc author for consideration.

**Comment by peter-myers** [comment]
Hi @AkhilMadivada - good pick up! Thanks for pointing out the error. A corrected image will be published soon. #please-close

**Comment by AkhilMadivada** [comment]
Great! Thank you.
