### ISSUE TITLE
Query contains unknown function name: Python.Execute.

### ISSUE THREAD

**Issue by FoxyChmoxy** [MicrosoftDocs/powerbi-docs#2547]
I was trying to do this example https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-in-query-editor

But I faced this error after publishing:
![image](https://user-images.githubusercontent.com/38606307/95719893-4eb25280-0c92-11eb-808a-118f1929b721.png)

Now I'm unable to automatically refresh my dataset. I don't use Python Visuals or Python Scripts to extract dataset from data source. This is my python code bellow:
```py
# Python:

import pandas as pd

def get_value(id):
    try:
        value = df2[df2['attributevalue'] == int(id)]['value'].values[0]        
        return value
    except:
        return 'Empty'

def transfer_column(column):
    return ', '.join([get_value(id) for id in column.split(',')])

final = pd.DataFrame(df1)
final['column'] = final['column'].apply(transfer_column)
```
I don't know why Power BI Service reports I have `Query1` if I don't have such a table...

**Comment by KesemSharabi** [comment]
Hi @kfollis, do you know who owns the [Use Python in Query Editor](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-in-query-editor) article?

**Comment by kfollis** [comment]
Hi @FoxyChmoxy - I'm assigning this issue to the writer to review and determine whether an article update is required. You may also want to reach out to https://support.powerbi.com or https://community.powerbi.com to get some help with the error you're seeing.

**Comment by otarb** [comment]
hi @FoxyChmoxy , when using Python (or R) as data source (Get data -> Python script) or PowerQuery transformation (Transform -> Run Python script) you will need to setup personal gateway to be able to refresh dataset in the service.  This is mentioned in the limitations section of the article you used as well (dataset that uses Python as source or transformation, is usually referred as 'python dataset'). Please be aware that this will only work with personal gateway, not with enterprise one. 

Let me know if you are still having trouble with refresh after configuring gateway.

**Comment by FoxyChmoxy** [comment]
Hi @otarb 

Thank you for your replying. The question is still open, I cannot use a personal gateway, since the data source is a corporate Common Data Service. In the settings of the **Gateway Clusters** there is no option to select the **Type of Data Source** as **CDS** and I'm unable to use OAuth2 as Authentication Method (idk why).

Also I can't get why I should use Personal Gateway if I'm using data that stored in the cloud, not on-premises data.

![image](https://user-images.githubusercontent.com/38606307/96349669-cf2de480-10d2-11eb-9b06-f3ae71e7deae.png)

_The on-premises data gateway (personal mode) is a version of the on-premises data gateway that works only with Power BI. You can use a personal gateway to install a gateway on your own computer and gain access to on-premises data._

Also, the gateway is unacceptable for the reason that if it is installed on my personal computer, then the service will not be able to update the dataset, at least due to the fact that my PC is turned off.

**Comment by otarb** [comment]
By configuring personal gateway, PowerBI service will be able to run Python transformation on your machine (even in cases where actual data doesn't live on same machine). This is done in order to give customers more flexibility and control over environment in which script is executed, this way transformations will be run in same Python environment (runtime version, available packages and versions) as it was during authoring. If transformations where run in service, customers would be limited by what packages they can use and what version of Python environment.

**Comment by otarb** [comment]
#please-close @otarb
