### ISSUE TITLE
How to purchase EM1 skus?

### ISSUE THREAD

**Issue by docgregt** [MicrosoftDocs/powerbi-docs#255]
The documentation has no links, phone #s or contact method on how to purchase EM1 skus. Please provide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c351d62-f45d-908e-bbc5-bc9bdcbe8372
* Version Independent ID: e6f1968c-a72b-7f79-9105-6d685e099af5
* Content: [How to purchase Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-purchase)
* Content Source: [powerbi-docs/service-admin-premium-purchase.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-purchase.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @docgregt 
Thank you for your Power BI doc feedback.  I've assigned this to the author who will work on it asap. 
Take care,
Michele

**Comment by mgblythe** [comment]
@docgregt - I'm looking into this for a related issue, I'll reply back here.

**Comment by patrickbutler** [comment]
Hello, can we get an update on the EM1skus? How can we purchase these?

**Comment by mgblythe** [comment]
EM1 and EM2 SKUs are available only through volume licensing plans. They can't be purchased directly.

**Comment by rwlpf** [comment]
Nice to know somethings are kept secret :-(

**Comment by hacenedjelid** [comment]
Hello Team, we are looking into a way to purchase the PowerBI EM1 sku for our customer through Volume Licensing but couldn't. There is no way to reach anyone in the VLSC department. Any help will be greatly appreciated! Thanks!
