### ISSUE TITLE
Sort By Column is permanently greyed out

### ISSUE THREAD

**Issue by The-Real-David-Williams** [MicrosoftDocs/powerbi-docs#2550]
Previously, I was using "Sort by Column" on this data. Recently (perhaps after an update?), no matter which fields I select, the button is always greyed out.

In the following example, the _Group_ column has six distinct values, in a table with an _Order_ column that has the numbers 1-6 corresponding to them. When I select the _Group_ column, "Sort by Column" remains greyed out.

![image](https://user-images.githubusercontent.com/26913623/95912514-c0080900-0d57-11eb-94a0-364e6277b524.png)

**Comment by KesemSharabi** [comment]
Thanks for your comment, @The-Real-David-Williams. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
