### ISSUE TITLE
1M Limit clarification for direct query

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#2552]
Following document says the 1M limit is configurable for direct query,
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-workloads#max-intermediate-row-set-count

while this document says it's not possible, what's the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @mganeshphani.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Good point - the difference is that it can exceed 1m only in Premium capacities. I've added a clarification and a link - thanks!
