### ISSUE TITLE
BigQuery - partitioned datasets

### ISSUE THREAD

**Issue by VenkatGowrishankar** [MicrosoftDocs/powerbi-docs#2555]
[Enter feedback here]
Hi, 

One of the customers is  a large big query  user - with data in PB scale. There are questions around the following - 
1. Sharded/Partitioned data sets, how to specify partitions in a direct query connectivity mode? 
2. Best practices - is it better to directly connect to big query? / cache the data in PBI using large models. 

Thanks, 
Venkat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-bigquery)
* Content Source: [powerbi-docs/connect-data/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-bigquery.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @VenkatGowrishankar - I'm assigning this issue to the author to consider your feedback in a future update. You may want to post your question to https://community.powerbi.com to get feedback from peers and other BigQuery users. The article you reference describes how to connect. You may find helpful best practices in our guidance documentation located here: https://docs.microsoft.com/en-us/power-bi/guidance/.

**Comment by mihart** [comment]
Thanks for your comment, @VenkatGowrishankar . I noticed that this is an older Git Issue and I hope that you were able to get your answer from the Power BI Community.  If you still have documentation questions, please let us know.  
All the best,
the DOCS team
