### ISSUE TITLE
Extra Dash in the Formatting

### ISSUE THREAD

**Issue by DigitalCog** [MicrosoftDocs/powerbi-docs#2556]
In the "Considerations and troubleshooting" section of the page, the url prefix for mailto has a dash(-), showing as "-mailto:", which the Power BI Desktop does not take as the prefix. Instead, PBI Desktop takes "mailto:" as a prefix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-hyperlinks-in-tables)
* Content Source: [powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @DigitalCog -- thanks for your sharp eye! Fixing it now.
