### ISSUE TITLE
Live Connection Missing

### ISSUE THREAD

**Issue by jlmcdermott** [MicrosoftDocs/powerbi-docs#2557]
[Enter feedback here]

This page doesn't mention live connections as a type of mode which is relevant for when connecting to Analysis Services models.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4113f426-5c74-c68d-781b-be0bb9358db1
* Version Independent ID: 4ef47ef7-0502-4161-a43e-4eabc3545931
* Content: [Dataset modes in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand)
* Content Source: [powerbi-docs/connect-data/service-dataset-modes-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-dataset-modes-understand.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by kfollis** [comment]
Hi @jlmcdermott - thanks for your feedback. I noted that in the article introduction it states that "It applies to datasets that represent a live connection to an external-hosted Analysis Services model," but that may not address your feedback. I'm assigning this issue to the writer to consider your input in a future update.

**Comment by peter-myers** [comment]
Hi @jlmcdermott - thanks for your feedback. We're currently reviewing dataset/data model documentation in light of the new composite modeling capabilities made available as a preview feature in the Power BI Desktop December 2020 release. We'll be sure to clarify that a dataset can be a live connection to an external-hosted model in Azure or SQL Server. #please-close
