### ISSUE TITLE
Full review / update required for Data Classification page

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2559]
This article is 3 years old and naturally drifted away from service behaviour. 

Some items that require an update:

1. Screenshots to match new workspace experience and other changes to Power BI service UI
2. Elements documented that do not work the same way in service. Example: https://github.com/MicrosoftDocs/powerbi-docs/issues/2443

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 460b9768-213a-bd8b-5ad8-ed5071848a98
* Version Independent ID: 24bdc0f5-a172-0d0b-02b2-ff798ccd96cf
* Content: [Dashboard data classification - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-data-classification)
* Content Source: [powerbi-docs/create-reports/service-data-classification.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/service-data-classification.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thanks, @VitalyMCT - I've assigned this issue to the author to review for accuracy and make an update. I appreciate you flagging this for us.

**Comment by paulinbar** [comment]
Hi @VitalyMCT, this type of data classification was discontinued some time ago and this article was removed, redirecting users to the sensitivity label documentation. Closing this issue now. Sorry for the long overdue notice...
