### ISSUE TITLE
Typo in the Text

### ISSUE THREAD

**Issue by brdudley** [MicrosoftDocs/powerbi-docs#256]
In the paragraph, "User Authentication" -- "whenever a user attempt to resources" :  should it be "whenever a user attempts to access resources..."

Same paragraph -- "Power BI uses the that login email..." : should be "Power BI uses that login email..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security)
* Content Source: [powerbi-docs/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-security.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @brdudley ,
Thank you for finding that typo.  I've assigned this to the author who will fix it asap. 
Take care,
Michele

**Comment by davidiseminger** [comment]
Thanks for your close read, @brdudley - I've fixed those typos. Much appreciated!
