### ISSUE TITLE
What has changed in the latest build 2.85.985.0?

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2560]
What has changed in the latest build 2.85.985.0 published 10/15/2020?
Why does it have the same build number as the version published 10/3/2020?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI Desktop update - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- Docs will be updated next week, so check back then. Closing this in the meantime. 
Thanks!
