### ISSUE TITLE
Modification needed for text about multiple-column joins

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#2563]
You say:
Avoid relationships on calculated columns. This guidance is relevant to databases where you need to do multi-column joins. Power BI today doesn't allow a relationship to be based on multiple columns as the FK/PK. The common workaround is to concatenate the columns together using a calculated column, and base the join on that column. While this workaround is reasonable for imported data, for DirectQuery, it results in a join on an expression. That result commonly prevents use of any indexes, and leads to poor performance. The only workaround is to actually materialize the multiple columns into a single column in the underlying database.

As I understand, Multi-column joins are still possible if they are done using none loading queries. So we can setup a query doing multi-column joins at the schematic Power Query level. Please let me know if you don't agree, as I find the wording "The only workaround is to actually materialize the multiple columns into a single column in the underlying database" not suggesting this would be possible

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @erapade.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the doc idea, and for the comment. We'll consider adding this to the documentation.
