### ISSUE TITLE
Typo: var exportRequest = new ExportReportRequest     {         Format = FileFormat.PDF,         PaginatedReportExportConfiguration = paginatedReportExportConfiguration,     }; -> the last comma should be removed!?

### ISSUE THREAD

**Issue by ErlandDEV** [MicrosoftDocs/powerbi-docs#2564]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI paginated reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @ErlandDEV, thanks for your comment. I have forwarded it on to the doc author for further consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @ErlandDEV,

Thanks for your comment, however, this is not a mistake.

 C# supports trailing commas for reasons outlined in [Code Syntax Style: Trailing Commas](https://www.jetbrains.com/help/resharper/Trailing_Commas_Style.html).

Once again, thanks for getting in touch,

Kesem
