### ISSUE TITLE
What time does the refresh limit gets reset ( in GMT time please)

### ISSUE THREAD

**Issue by vandesandtmarc** [MicrosoftDocs/powerbi-docs#2565]
Hi I would just like to know at what time does the refresh limit get reset? So that we can plan on when we will be refreshing. And know in advance when we have the next 8 refreshes avail with the pro license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @vandesandtmarc . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @vandesandtmarc , 
Thank you for your suggestion.  We've made the update and set the article to republish.  The refresh limit gets reset at 12:01 am local time. "Local time" is based on the time zone you selected on the Dataset Settings screen. 
All the best,
The DOCS team
