### ISSUE TITLE
Format by field value not applicable 

### ISSUE THREAD

**Issue by jw3315** [MicrosoftDocs/powerbi-docs#2566]
![9EA72054-2565-437C-A06B-DF97DC94D94F](https://user-images.githubusercontent.com/23145149/96543733-a17ba380-126a-11eb-867e-9bf8d871b189.jpeg)

[Enter feedback here]
Power bi report server May 2020, to format color by field value, I can’t select a column to perform this function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jw3315 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @jw3315 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option for this type of issue is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
