### ISSUE TITLE
Confusion on Custom Maps

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2568]
The below statement leaves a lot of grey area.
"Shape Map visuals --- have the compelling ability to use custom maps that you can create."
"Examples of custom maps are: geographical --- and others."
"The ability to use custom maps is not available in Preview"

I would like to know - if the Shape Map creates / has the ability to use custom maps is it available during Preview?

---

Description:

Shape Map visuals are based on TopoJSON maps, which have the compelling ability to use custom maps that you can create. Examples of custom maps are: geographical, seating arrangements, floor plans, and others. The ability to use custom maps is not available in this Preview release of Shape Map.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map#use-custom-maps)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by mihart** [comment]
Thanks for your comment, @itsnotaboutthecell . This issue has been assigned to the doc author for review.

**Comment by msftrien** [comment]
Yeah, I've no idea why that line is there. I'm deleting the "not available" sentence.

**Comment by mihart** [comment]
@msftrien thank you for the update!
@itsnotaboutthecell , thank you for your suggestion.
