### ISSUE TITLE
What is the list of available parameters?

### ISSUE THREAD

**Issue by RudyCo** [MicrosoftDocs/powerbi-docs#2571]
This page does not explain what are the available parameters in brackets below:
Source = AzureCostManagement.Tables("Enrollment Number", "1111111111", 1, []),

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management#next-steps)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @RudyCo.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community](https://community.powerbi.com).

**Comment by RudyCo** [comment]
Any update @KesemSharabi? There is no answer on https://community.powerbi.com/.
Thanks in advance!

**Comment by davidiseminger** [comment]
There have been many updates to this article in recent months. Your best venue for getting an answer on your question is from the community (https://community.powerbi.com) which may now have more information, or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
