### ISSUE TITLE
Build permissions documentation

### ISSUE THREAD

**Issue by yahsee** [MicrosoftDocs/powerbi-docs#2572]
The instructions don't appear to apply to the current version of Power BI. I don't see manage permissions as an option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @yahsee -- Thanks for asking! Manage permissions is still there. You need to have at least a Contributor role in the workspace, so Admin, Member, or Contributor, but not Viewer. Also, Manage permissions is for the datasets, right? 
You point out a flaw -- I'll add a link to the table about roles in workspaces, https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces#roles-in-the-new-workspaces -- and I'll add a line to the Roles table specifically for managing permissions on a dataset. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @yahsee -- thanks again! Fixes made, will be in the articles tomorrow.
