### ISSUE TITLE
Is also a Power BI report template available?

### ISSUE THREAD

**Issue by michalmar** [MicrosoftDocs/powerbi-docs#2575]
[Enter feedback here]
There used to be a Power BI template report available for Billing API Key in form of PBIX - is there anything similar for this Consumption API? thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @michalmar.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by michalmar** [comment]
@KesemSharabi any update on this please?

**Comment by michalmar** [comment]
@KesemSharabi any update on this please?

**Comment by mihart** [comment]
Hi @michalmar ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit these types of questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by michalmar** [comment]
Unfortunately not solved.
