### ISSUE TITLE
Reports containing report-level DAX measures?

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2577]
Hi, what does the limitation "Reports containing report-level DAX measures" mean exactly?  What is a report-level measure and how is it different from a regular measure?  Aren't all measures defined using expressions?  Thanks in advance for clarifying this.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- how are you? That's a good question. I'm going to check and get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- here's the answer:
GuyInACube had an episode on it: https://guyinacube.com/2017/07/19/report-level-measures-power-bi-live-connections/
 Basically, a report level measure is a measure that you create against a Live connection to either SSAS Tabular, a Power BI dataset or AAS.
Hope that helps!
