### ISSUE TITLE
GITHUB Repository usages in not connecting to the our Organisation wide repo

### ISSUE THREAD

**Issue by arunbala9** [MicrosoftDocs/powerbi-docs#2579]
Hi, 

We have all our GitHub under the organization folder.  The Github is setup with Two-way authentication. I was able to curl the Github in command prompt by creating personal access tokens. When I try to access the same, Power bi is throwing an error message.

There was an error when processing the data in the dataset.
Please try again later or contact support. If you contact support, please provide these details.
Processing errorWeb.Contents failed to get contents from 'https://api.github.com/repos/turnercode/cnn-content-hub' (404): Not Found
Cluster URIWABI-US-NORTH-CENTRAL-redirect.analysis.windows.net
Activity ID87825a00-6d04-41bd-a878-bcc08da7a797
Request IDbe40f7c4-78a8-bfcb-f1f3-83ac956bb142
Time2020-10-22 20:28:13Z****

any help would be appreciated

**Comment by maggiesMSFT** [comment]
Hi, @arunbala9 -- this sounds like a product issue, not a docs issue. 
Can you try the Power BI community, https://community.powerbi.com/? 
If they're no help, you may need to contact support, https://powerbi.microsoft.com/en-us/support/
Hope that helps!
