### ISSUE TITLE
The "How can I monitor capacity consumption?" section needs an update...

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#258]
...to reflect the new "Power BI Premium Capacity Metrics" App that Microsoft published. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a447889-379d-3ded-9ab9-313c4f55a667
* Version Independent ID: 4f8e3f79-5025-919a-7282-8a63dda6bc8d
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-faq.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@chrisweis Thank you for your feedback! We are already in the process of updating that information.  We are planning for it to be updated by next week.  Thank you.

**Comment by markingmyname** [comment]
@chrisweis We added that information to the FAQ article.  It should go live in a day or two.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
