### ISSUE TITLE
Is the XMLA readonly endpoint in GA?

### ISSUE THREAD

**Issue by joymon** [MicrosoftDocs/powerbi-docs#2580]
I understand that the writeback endpoint (feature) using XMLA is in preview. But what about the XMLA read-only endpoint? Did it reach GA? 
I could see the documentation still says Preview for XMLA endpoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1b920c-639a-a627-58f2-e8fd69c9ef7d
* Version Independent ID: ab13e62f-0629-0aed-7e85-a902e150f9b1
* Content: [Dataset connectivity and management with the XMLA endpoint in Power BI Premium (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-connect-tools)
* Content Source: [powerbi-docs/admin/service-premium-connect-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-premium-connect-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by davidiseminger** [comment]
Thanks for your comment, @joymon. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by Minewiskan** [comment]
@joymon - XMLA endpoint, which supports read only and read-write operations is still in preview. That said, keep a close eye on the Power BI blog in the coming weeks.
#please-close
