### ISSUE TITLE
Which statement is correct ?

### ISSUE THREAD

**Issue by ryoma-nagata** [MicrosoftDocs/powerbi-docs#2581]
[Enter feedback here]
Hi,

There are two contradictory statements Which is correct?

1.
>You may use an Enterprise Gateway with Azure SQL DB. However, you may not use SSO or oAuth2 to authenticate in those scenarios.
2.
>For paginated reports, Azure SQL Database and Azure Analysis Services currently can't be accessed via a Power BI data gateway.

If both are correct, the difference between the assumptions cannot be read from the description, so the difference needs to be clarified.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a5444a-ce6c-9a0c-3e84-832e67b75d47
* Version Independent ID: df2623ba-2917-faf6-0077-e9d182a9e96c
* Content: [Supported data sources for Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-data-sources)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-data-sources.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @onegoodsausage
* Microsoft Alias: **andremi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ryoma-nagata - sorry for the confusion. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ryoma-nagata -- thanks for asking! We've updated the article. The change should be published this afternoon.

**Comment by ryoma-nagata** [comment]
Thank you for your help.
