### ISSUE TITLE
Hive LLAP Connector

### ISSUE THREAD

**Issue by FranGenoa** [MicrosoftDocs/powerbi-docs#2583]
Hi All, 
in march it was released the Hive LLAP connector (beta) but there is no mention at this page of the documentation. 
https://powerbi.microsoft.com/en-us/blog/tag/hive-llap/
Is it possible to add it as well?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @FranGenoa ,
I see that this Git issue is a bit old, so I'm going to close it.  I checked, and the article has already been updated with your suggestion.  Thank you for your contribution!   
All the best,
the DOCS team
