### ISSUE TITLE
Inconsistency in the steps?

### ISSUE THREAD

**Issue by rubencanlas** [MicrosoftDocs/powerbi-docs#2584]
This pertains to [Visual 5](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#visual-5-year-slicer). It calls for removing the Quarter and Day from the hierarchy. However, these have previously been removed in the instructions for [Visual 2](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#visual-2-profit-by-date) where the user was asked to change Date Hierarchy to Date. So by the time I reached Visual 5, there are no Quarter and Day items to remove and the slicer is limited to the full date. Am I missing something?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Sorry about that, and thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!
