### ISSUE TITLE
Personalize Visuals - Table or Matrix change column order not working

### ISSUE THREAD

**Issue by zenton2000** [MicrosoftDocs/powerbi-docs#2585]
Hi 
I have enabled Personalize visuals in Report settings and publish my report
I can change the visual type and add and remove fields but I can not change the order by drag and drop.
Nothing moves.

Thanks Rodney

**Comment by davidiseminger** [comment]
Thanks for your comment, @zenton2000. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
