### ISSUE TITLE
Power BI not opening

### ISSUE THREAD

**Issue by goghit** [MicrosoftDocs/powerbi-docs#2586]
Hi Everyone,

We are experiencing a issue at our company in one of our domains we have users that installed Power BI and it is not opening instead it displays the below error: 

![image](https://user-images.githubusercontent.com/66320481/97291918-370ec880-1853-11eb-8071-76b5d6834dcc.png)

In the same affected domain if we open Power BI as Administrator it opens successfully. We use the same version **(2.81.5831.1181)** of Power BI on all other domains and all other domains the users are able to use Power BI without executing as administrator.

I found the following [article ](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-error-launching-desktop) from Microsoft  but although it describes the issue the suggestions is they make to fix this does not make sense "Run as Admin" / "Install latest Power BI"

Please if someone has some insight on what could be the cause / fix I will appreciate your feedback.

**Comment by davidiseminger** [comment]
Thanks for your comment, @goghit. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by goghit** [comment]
Thank you @davidiseminger 👍
