### ISSUE TITLE
Update from Preview to GA

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2587]
The sidebar navigation lists this feature as (preview) but it is currently generally available.

As displayed on the left-hand navigation menu:
Using enhanced dataset metadata in Power BI Desktop (preview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e42fcb7-fa8f-638c-bdfd-8d5110baa3ed
* Version Independent ID: c5e57e1b-b10a-7070-d26e-829feda2f2ed
* Content: [Using enhanced dataset metadata in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata)
* Content Source: [powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-enhanced-dataset-metadata.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment - good catch! I've updated that TOC listing to remove the (preview) tag, will be reflected later today. Much appreciated!
