### ISSUE TITLE
Binding parameter

### ISSUE THREAD

**Issue by Zechman** [MicrosoftDocs/powerbi-docs#2588]
[Enter feedback here]
Step 10 Property **Binding parameter** in advanced, is not available in last version, tested on 32 and 6
 versions . 2.86.902.0 October 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Zechman . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll determine the best way to adjust the article, if needed.
