### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by RobvanB** [MicrosoftDocs/powerbi-docs#259]
Is there any info on a release date for the composite models?
We want to use this, but cannot, as you cannot publish a report that uses preview features.....

**Comment by mihart** [comment]
Hi @RobvanB ,
That's a great question, but it's more of a product question than a doc question.  For product-related questions, please use the Power BI Community site:  community.powerbi.com.  That site is closely monitored by the product team and you'll get answers from them and/or community members.  If for some reason you don't get a quick answer, please write back.

Take care,
Michele
