### ISSUE TITLE
the alternative "Combine data to each file's Privacy Level settings" are missing in the description

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#2590]
Depending on if you configure the Global settings or the Current file settings, there are different options for configuring data privacy settings. There are 3 in the global settings and 2 in the local file settings. Please describe each of these since they are slightly different and this is a complex subject with sometimes vague definitions 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/desktop-privacy-levels)
* Content Source: [powerbi-docs/admin/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @erapade.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll consult with the product team to determine the appropriate level of further information.
