### ISSUE TITLE
Correct some of the wording on the Power BI Premium dataflow workloads page

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerbi-docs#2591]
Check on these statements as it appears that words are missing:

Compute engine is on but performance is slow
Take the following steps when investigating scenarios where the Compute engine is on, but you're seeing slower performance:

Limit computed and linked entities that exist cross workspace.  **<- should this be across workspaces?**

**missing "is" between refresh the the compute engine turned on ->** If your initial refresh with the compute engine turned on, then data gets written in the lake and in the cache. This double write means these refreshes will be slower.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6054103-4999-9ce2-ba30-095a6d469465
* Version Independent ID: 2ce5b049-276a-a159-4f28-fd1dca17442f
* Content: [Configure Power BI Premium dataflow workloads - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-workload-configuration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @cvillegashak.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @cvillegashak , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
