### ISSUE TITLE
help

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/powerbi-docs#2592]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8e2480-703a-1417-c5d9-8d019669f45a
* Version Independent ID: 17a9f60e-b9b6-8426-2176-86b5ec3cb68f
* Content: [Q&A for Power BI business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-q-and-a.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @matuhinal -- it appears you didn't enter any feedback for the article. Closing this issue; feel free to open another one with a comment!

**Comment by matuhinal** [comment]
Здравствуйте! Срочно нужна помощь.Кто у меня саонсор?
________________________________
От: Maggie Sparkman <notifications@github.com>
Отправлено: 31 октября 2020 г. 0:07
Кому: MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Копия: matuhinal <ayuditgarantdigital@outlook.com>; Mention <mention@noreply.github.com>
Тема: Re: [MicrosoftDocs/powerbi-docs] help (#2592)


Hi, @matuhinal<https://github.com/matuhinal> -- it appears you didn't enter any feedback for the article. Closing this issue; feel free to open another one with a comment!
