### ISSUE TITLE
Add SharePoint/OneDrive source limitation to another section

### ISSUE THREAD

**Issue by deliafernandez** [MicrosoftDocs/powerbi-docs#2593]
Hi,

We had a case were the customer had added images from SharePoint and it was not clear for him that this is not going to work. We looked for documentation and this information was hard to find.

Our recommendation is to add this consideration/limitation to the considerations and limitations part of this document, so its clear and easy to find for users.

"Make sure security credentials aren't required to access the image file. 
OneDrive and SharePoint require authentication, images stored there can't be added to a dashboard this way."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53f30eb2-e55e-635d-e161-6c26f20fac2d
* Version Independent ID: 7d1fd996-9981-a844-0f2b-abb35cf21b7f
* Content: [Add images, videos, and more to your dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-add-widget)
* Content Source: [powerbi-docs/create-reports/service-dashboard-add-widget.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-dashboard-add-widget.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @deliafernandez -- OK adding it to the "Considerations" section, though it's already in the "Add an image" section. Thanks!
