### ISSUE TITLE
Power BI Report Server October 2020

### ISSUE THREAD

**Issue by pjpike** [MicrosoftDocs/powerbi-docs#2594]
Change log needs to be updated for October 2020 release of Power BI Report Server, 
- download is now available here https://www.microsoft.com/en-us/download/details.aspx?id=57270
- blog update is here https://powerbi.microsoft.com/en-us/blog/power-bi-report-server-october-2020-feature-summary/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by maggiesMSFT** [comment]
Hi, @pjpike -- ah, you're too quick for us! We just published the updated What's New and Change Log for Power BI Report Server yesterday. But I hadn't included the link to the blog post from the What's New, so thanks to you, I've added it. Change will be live later today. Thanks!
