### ISSUE TITLE
Support for import and data refresh is coming. 

### ISSUE THREAD

**Issue by Maenglar** [MicrosoftDocs/powerbi-docs#2595]
This Feature is now available in October 2020 upgrade ?

**Comment by maggiesMSFT** [comment]
Hi, @Maenglar -- are you referring to a specific article? Not sure to whom to assign your question. Thanks!

**Comment by Maenglar** [comment]
Yes, sorry this is the artcile (https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis).
But i see that thi article have update in 26/10/2020.
So perfect!!!

**Comment by maggiesMSFT** [comment]
@Maenglar - great !I'll close this then.
