### ISSUE TITLE
Sort by column option doesn't appear in modeling tab

### ISSUE THREAD

**Issue by stevenfayers** [MicrosoftDocs/powerbi-docs#2596]
The Sort by column icon that is shown in the examples doesn't appear in the modeling tab when the chart is selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @stevenfayers -- right you are! You have to select a field in the Fields pane, and then you see Sort by column, which is now on the Column tools tab. Assigning to the author to update. Thanks!

**Comment by mihart** [comment]
Hi @stevenfayers , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
