### ISSUE TITLE
Setting up Drill through reports

### ISSUE THREAD

**Issue by MCcoder52** [MicrosoftDocs/powerbi-docs#2597]
Documentation does not fully define how two different pages are connected. 
Changing the image for the back button only changes the image but the sequence of the document implies that step is key in establishing the drill-through relationship. The document offers no explanation of how two pages end up automatically connected. 
It appears as though an assumption is made in the narrative that the datasets for both pages are the same but no where is that made clear. 
We are told to enable the drill-through field in the drill-through well on the drill-through (Drill-through = destination?) page but no guidance given on defining the field passed from the 'Drill-from' page. Also no comment on how the correct Drill-from page knows it is to be drilled through(Mine picked a page that I did not touch and does not use the same data set.) 
Terms do not seem to be fully defined and are awkward.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drill through in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MCcoder52 -- thanks for your comment! I'll see what I can do to make it clearer. 
One question: When you say that your drill-through "picked a page that I did not touch and does not use the same data set," could you elaborate? Your report has more than one dataset?

**Comment by MCcoder52** [comment]
Yes, the report has more than one dataset. One is a direct Import of a SQL Server table the other 4 are query Import extracts of  a table (3) or a view(1). I worked out the issue. Thank you for reaching out.  Sent from Mail for Windows 10 From: Maggie SparkmanSent: Friday, October 30, 2020 3:28 PMTo: MicrosoftDocs/powerbi-docsCc: MCcoder52; MentionSubject: Re: [MicrosoftDocs/powerbi-docs] Setting up Drill through reports (#2597) Hi, @MCcoder52 -- thanks for your comment! I'll see what I can do to make it clearer.One question: When you say that your drill-through "picked a page that I did not touch and does not use the same data set," could you elaborate? Your report has more than one dataset?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maggiesMSFT** [comment]
OK, thanks for letting me know, @MCcoder52 ! Closing this issue.
