### ISSUE TITLE
Performance improvements to IF and SWITCH functions

### ISSUE THREAD

**Issue by HansSprangers** [MicrosoftDocs/powerbi-docs#2598]
I can't find any articles explaining what improvements were done. In other words. Supplied link does not mention anything about this topic.

**Comment by maggiesMSFT** [comment]
Hello, @HansSprangers -- could you provide a link to the article you're referring to? It isn't included in this Git Issue. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @HansSprangers -- closing this issue for now. If you can provide the link to the article, please reopen it!
