### ISSUE TITLE
Doesn't connect to the Private repos

### ISSUE THREAD

**Issue by arunbala9** [MicrosoftDocs/powerbi-docs#2599]
Hi The article doesn't talk anything about connecting to the private repos and the APP doesn't connect to the private repos.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 076ce105-645c-cf91-44b7-4e2192eed874
* Version Independent ID: fb6358ab-0940-7ced-1036-2ddc49b78ce5
* Content: [Tutorial: Connect to a GitHub repo with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-tutorial-connect-to-github)
* Content Source: [powerbi-docs/connect-data/service-tutorial-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-tutorial-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @arunbala9 -- hmmm, I just tried and was able to connect to our private repo. Not sure what issue you're experiencing. Try using this Power BI template app for GitHub instead: https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github. I'm adding a link to that article from the GitHub tutorial. Thanks!
