### ISSUE TITLE
COUNTA vs. DISTINCTCOUNT

### ISSUE THREAD

**Issue by rslayunc** [MicrosoftDocs/powerbi-docs#260]
Hi!
I am learning Power BI and am studying the Opportunity Analysis dataset. I am had a question about the "Opportunity Count" measure in the "Fact" table. The measure uses the formula "Opportunity Count = COUNTA([Opportunity ID])" and returns a value of 487 in the Report View.
However, when I look at the "Opportunity ID" column in the data table there are only 486 rows. I initially used the formula "Opportunity Count = DISTINCTCOUNT([Opportunity ID])" when I created a copy version for practice and received a total of 486 when I included the measure in the Report View.
Is the use of COUNTA correct and if so, why does is there one additional value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3041354-2ebf-99f3-e0c5-ac57227904c8
* Version Independent ID: 3a410693-c86e-70c3-4b44-1fad4719ffb3
* Content: [Opportunity Analysis sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-opportunity-analysis)
* Content Source: [powerbi-docs/sample-opportunity-analysis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-opportunity-analysis.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @rslayunc ,
That's a really good question.  I'll look into this and get back to you asap.
Thanks
Michele

**Comment by mihart** [comment]
Hi @rslayunc 
This took a lot of investigation, thanks to WillT and JeffreyW.  
You have Opportunity ID 302 twice in the Fact table, therefore distinct count is 486 but countis 487. To easily visualize the data issue, simply create a table visual and add [Opportunity ID] to the visual twice, once using Do Not Summarize, the second time using Count. Sort the rows by Count in descending order and you’ll see the duplicate value.
Take care,
Michele
