### ISSUE TITLE
glossary feedback - dashboard

### ISSUE THREAD

**Issue by TwiddlyTiger** [MicrosoftDocs/powerbi-docs#2600]
Dashboard definition isn't great, particularly as it means something very specific in a Power BI concept (although the one-page thing is already widely misunderstood, this adds a further level of potential confusion). In my internal work terminology guide I suggest the following, although the glossary would need to cut down on this detail...
but at the very least shouldn't it cross-reference https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts#dashboards or the following MS definition?
**“A Power BI dashboard is a single page, often called a canvas, that uses visualizations to tell a story. Because it is limited to one page, a well-designed dashboard contains only the most important elements of that story.”**

Me: 

> "It’s a common misconception that anything that draws together visuals and text in one place is a dashboard. This is incorrect, and most of what are commonly called ‘dashboards’ are actually reports (in some cases these could be faceted analytical displays).
> In Power BI a dashboard has a specific technical meaning, and can only be created or viewed in the Power BI Service. Dashboards can’t be created in Power BI Desktop, although content originating in Power BI Desktop can end up in a dashboard. Dashboards usually can’t be embedded to SharePoint pages or external web pages. 
> https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts#dashboards
> 
> “A Power BI dashboard is a single page, often called a canvas, that uses visualizations to tell a story. Because it is limited to one page, a well-designed dashboard contains only the most important elements of that story.”"

[further MS articles then linked, including Dashboards versus reports for Power BI business users]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52715480-01e0-b777-74ae-1aadb5fd3f2d
* Version Independent ID: f8ec264c-2df4-5adf-fdba-aa46d30bb07b
* Content: [Glossary for Power BI business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-glossary)
* Content Source: [powerbi-docs/consumer/end-user-glossary.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-glossary.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @TwiddlyTiger -- you're right, so often people call a report a "dashboard," which then muddies the water about what a dashboard really is. Passing your feedback along to the author for consideration.

**Comment by mihart** [comment]
Hi @TwiddlyTiger . Thank you for your suggestions.  I've updated the definition for dashboards..not exactly what you wrote, but very close :-)
