### ISSUE TITLE
API Limitations for GET Requests

### ISSUE THREAD

**Issue by dannyp** [MicrosoftDocs/powerbi-docs#2601]
The Power BI REST API limitations only contains information for POST requests, however I've run into a "TooManyRequests" error doing just Get-PowerBIReport commands. 

Should this page also include request limits per minute / hour for this type of API request, and the other "Get-*" operations in the Powershell Mgmt add in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e0de30-226e-6586-e735-2a57c7d29d1f
* Version Independent ID: 865d55d9-0267-eb3f-83e2-89fcf244b10a
* Content: [Power BI REST API limitations - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/api-rest-api-limitations?redirectedfrom=MSDN)
* Content Source: [powerbi-docs/developer/automation/api-rest-api-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/api-rest-api-limitations.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @dannyp -- thanks for your suggestion! Passing it along to the author for consideration.

**Comment by KesemSharabi** [comment]
Hi @dannyp

After consulting with the development team we've decided not to update the [Power BI REST API limitations](https://docs.microsoft.com/power-bi/developer/automation/api-rest-api-limitations) page. We feel that the 'TooManyRequests' error is informative enough. If you send too many requests you'll get this error.

Thanks again for your comment and for getting involved.

Kesem

**Comment by RonaiBertalan** [comment]
Hi! 
I am currently trying solve this by putting Start-Sleep commands between API calls in the powershell script. Where can I read the exact limitation limits? It's a bit slow to develop this way because when I hit the limit, 
I can't continue testing for an unknown amount of time. Thanks in advance!

**Comment by reubster** [comment]
> Hi @dannyp
> 
> After consulting with the development team we've decided not to update the [Power BI REST API limitations](https://docs.microsoft.com/power-bi/developer/automation/api-rest-api-limitations) page. We feel that the 'TooManyRequests' error is informative enough. If you send too many requests you'll get this error.
> 
> Thanks again for your comment and for getting involved.
> 
> Kesem

Ok, that's fair enough... but do I wait 15minutes? 2 hours? 24 hours?
