### ISSUE TITLE
EM Skus do not support FREE Users.  This should be called out in this on-line document.

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#2602]
The EM Skus do not support FREE Users.  This document is misleading in the capacity nodes section of making it sound as if EM is a smaller Premium Capacity option.  It is for some scenarios but not in the free user scenario.  This should be called out explicitly.  P Skus are the only skus that support free users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @elfohl, thanks for your comment. I am forwarding it on to the doc author for further action.

**Comment by mihart** [comment]
Hi @elfohl , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
