### ISSUE TITLE
Excel sample file not found

### ISSUE THREAD

**Issue by ank-rapmap** [MicrosoftDocs/powerbi-docs#2605]
[Enter feedback here]
Prerequisites
This tutorial uses the [Financial sample Excel file](https://download.microsoft.com/download/9/6/D/96DDC2FF-2568-491D-AAFA-AFDD6F763AE3/Retail%20Analysis%20Sample%20PBIX.pbix): 
This link is directing to PBIX file not the excel file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20ec85-cf09-5d0e-317c-1897a6f63b0b
* Version Independent ID: 8979a4de-7c09-8c5d-0415-e82957d29ccb
* Content: [Radial gauge charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-radial-gauge-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ank-rapmap. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @ank-rapmap .  You are right!  I've fixed the link and set the article to republish.  Thank you so much.

**Comment by ank-rapmap** [comment]
Thanks for @davidiseminger , it is working now. 👍
