### ISSUE TITLE
selectionId 

### ISSUE THREAD

**Issue by HMLaozitech** [MicrosoftDocs/powerbi-docs#2606]
Can anyone tell me what is selectionId parameter (Sending to selectionManager to appear drill through option in the context menu)?

**Comment by davidiseminger** [comment]
Thanks for your comment, @HMLaozitech. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
