### ISSUE TITLE
Expanded Hardware information and guidance for Power BI Desktop

### ISSUE THREAD

**Issue by Spiller70** [MicrosoftDocs/powerbi-docs#2607]
I am seeing poor performance in the PowerBI Desktop (PBD) application that appears to be hardware related as once the PBD has launched all other applications are impacted.
Ram8GB, i5-8400, 1TB hdd @7200. At a glance the hardware should be decent, though at starting PBD unallocated RAM is less than 1GB. 1440 display on Integrated GPU.
It would be nice to see which hardware items yield most effective/detriment when not ideal and if there are issues with particular configurations.
Also might there be some issues from network connections, firewalls or security software. Probably information on such possibilities would be inappropriate in the main article but links to reference for IT would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Spiller70.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Thanks for your comment, @Spiller70 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
