### ISSUE TITLE
UI Does Not Match Documentation

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerbi-docs#2608]
This is probably more about fixing the UI than the documentation. Feedback is from Chrome/Edge browsers.

1. The "Add Data Source" button has a + sign in the documentation. No plus sign in the UI. Button looks like a header.
2. The ellipsis are only visible when OnSelected AND MouseOverEllipsis. How is one supposed to know the ellipsis exist if they are invisible? They should show up for OnSelected.

Thanks,

Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Manage data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by kfollis** [comment]
Thanks for the feedback, @JoelLeichty. I'll share your suggestions for UI improvements with the engineering team and will review the article to ensure that the documentation is up to date with the current UI.

**Comment by kfollis** [comment]
@arthiriyer - I can make sure that the article matches UI, but wanted to make sure you saw the feedback on how the "more options" (ellipsis) is exposed.

**Comment by kfollis** [comment]
This article has been updated to reflect the current UI and will publish later today. Closing this issue and I hope the changes made help to clarify the UI interaction! The feedback on how the more options menu appears (or doesn't) has been shared with the product team.
