### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2609]
[Enter feedback here]
 
In the "Create and install a certificate" section, the Important block in blue says "PowerSell".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thank you for your comment, I'll fix this typo shortly.

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thank you for spotting this typo and letting us know. This typo is now fixed - see [Set up your environment for developing a Power BI visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup).
