### ISSUE TITLE
No detail on active directory data sources?

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#261]
It looks like there's no documentation on using active directory as a data source, and not much to configure.  How can I get information on objects in other partitions?  In this case, I need to build an analysis of sites and subnets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @jordanmills .
Thank you for your Power BI doc feedback.  I've assigned this to the author who will work on it asap. 
Take care,
Michele

**Comment by mihart** [comment]
added tag

**Comment by davidiseminger** [comment]
Thanks for your comment, @jordanmills. This looks like a community or support request. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
