### ISSUE TITLE
Please describe which Permissions and Role - both Azure and EA portal needs to be configured.

### ISSUE THREAD

**Issue by michalmar** [MicrosoftDocs/powerbi-docs#2614]
Please describe which Permissions and Role - both Azure and EA portal needs to be configured for Consumption API to be accessible by PowerBI.

It is not clear - especially if we are deprecating old Billing Key access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @michalmar. I'm assigning this is to the writer to review the doc and make sure that the prerequisite steps of configuring Azure and the EA portal - and understanding of the required permissions and roles to make the connection - are covered.

**Comment by michalmar** [comment]
Any update on this, please?

**Comment by kfollis** [comment]
Hi @michalmar - thanks for the patience. We are verifying the correct minimum access level, but I believe that this article: https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/assign-access-acm-data contains the permissions and roles info that you need.

**Comment by davidiseminger** [comment]
I updated to clarify which accounts must be needed, but indeed, the stated accounts are correc.t
