### ISSUE TITLE
Track users in power bi embedded

### ISSUE THREAD

**Issue by dasunik7-max** [MicrosoftDocs/powerbi-docs#2615]
Does this method work when a power bi report is embedded on our own web site and when the customers log in to the system using accounts in the web site and view power bi content. Are those users tracked using this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @dasunik7-max. Thanks for the question! I believe that because the users are authenticated that their activity can be tracked. However, I'm adding the writer for Power BI embedded to confirm.

**Comment by KesemSharabi** [comment]
Hi @dasunik7-max,

It sounds like you're implementing the *embed for your organization* solution. If so, you'll be able to track the users activities.

In a *embed for your customers* scenario however, you'll only get results for one user - the user you're using for embedding your app.

Hope this helps,

Kesem
