### ISSUE TITLE
sort button does not show up 

### ISSUE THREAD

**Issue by mikelauxihs** [MicrosoftDocs/powerbi-docs#2616]
The Sort by Column button is not appearing in the Modeling tab when I select a field in the Fields section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @mikelauxihs! I'm adding the writer to review and make an update. I did a quick test, and when I select a field, I now see a "column tools" menu tab and the ribbon there includes a "sort by column" button.

**Comment by mihart** [comment]
Hi @mikelauxihs , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
