### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by patrickjlee** [MicrosoftDocs/powerbi-docs#2619]
I'm trying to follow the instructions for Scheduling refresh in Power BI (Desktop) and this page seems to be completely out of date! Please provide updated instructions that work with Power BI Desktop version 2.86.902 (October 2020).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-scheduled-refresh)
* Content Source: [powerbi-docs/connect-data/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @patrickjlee -- thanks for your comment! Referring to the author for consideration.

**Comment by davidiseminger** [comment]
This article (and the product) has been updated since this post. Thanks.
