### ISSUE TITLE
Are other SQL Server services (Analysis, Reports) implied?

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/powerbi-docs#262]
The documentation says that only SQL Server is supported, but is unclear if that support extends to Analysis Services, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b25ab3-f22b-e70b-e262-6266dd132692
* Version Independent ID: e5cbbdd4-0c02-6c05-91f4-016b767eb233
* Content: [Use Kerberos on the on-premises gateway for SSO (single sign-on) from Power BI to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-kerberos-for-sso-pbi-to-on-premises-data)
* Content Source: [powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by arthiriyer** [comment]
@cmeyertons The direct query equivalent for analysis services is Live connection. This help run the report under the user context.
 @mgblythe FYI
