### ISSUE TITLE
Sharing Report

### ISSUE THREAD

**Issue by rwatty** [MicrosoftDocs/powerbi-docs#2620]
I have a customer who has their own PowerBI Premium license.  I am sharing a report with one person at that organization who then wants to share report with others at that organization.  They share the link which was given to them so anyone in there organization with link can click and request access to report.  However, the user gets message, report is not available.  They never get the option to request access to report.  How do I get around this issue without having to know all 10 thousand employees who need to see this report created by my company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee97d20-cca2-c705-0429-6debab9f9a32
* Version Independent ID: 40334cca-f3c1-e8a8-7df2-e53e78ecfb40
* Content: [Request or grant access to dashboards or reports - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-request-access)
* Content Source: [powerbi-docs/collaborate-share/service-request-access.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-request-access.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @rwatty -- I can check and get back to you. In the meantime, I recommend asking in the Community, https://community.powerbi.com/.

**Comment by mihart** [comment]
Thanks for your comment, @rwatty . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
