### ISSUE TITLE
Grammatically Incorrect phrase

### ISSUE THREAD

**Issue by Alisha-Acharya** [MicrosoftDocs/powerbi-docs#2621]
The first bullet under prerequisites is not phrased correctly.
It reads " To copy or a report" , I believe it should say "To copy a report".
This is leading to translation issues.
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @Alisha-Acharya -- fixed!
