### ISSUE TITLE
Needs clarification on whether Power BI Embedded supports it or not

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2622]
This page is unclear on whether the personalize visuals feature works or not in Power BI Embedded, within an ISV application.  Would be great if that could be clarified!  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615021e0-5504-046d-d6ab-c2d8dee0656f
* Version Independent ID: d9c6ad5a-139f-716e-eb59-473a1f8d73de
* Content: [Let users personalize visuals in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-personalize-visuals)
* Content Source: [powerbi-docs/create-reports/power-bi-personalize-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-personalize-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @chrisweis. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- thanks for asking! Yes, the personalize visuals feature does work in Power BI Embedded, within an ISV application. I've added a simple sentence and will add more after conferring with the Power BI Embedded writer. 
Thanks!
