### ISSUE TITLE
Minor typo - Extra closing bracket in code block

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2623]
Hi Kesem,

In the section "Receive properties from Power BI" | Point no 3 | Code block - The if condition has an extra closing bracket.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfc5549-16a6-5afd-dac4-64021c25dfa9
* Version Independent ID: b8bf0ca1-1f11-bac0-76fa-cfd6a0d1231b
* Content: [Tutorial: Create a React-based visual for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual)
* Content Source: [powerbi-docs/developer/visuals/create-react-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/create-react-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @premradhakrishnan . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thanks for spotting this typo and letting us know. It's now fixed - see [Receive properties from Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual#receive-properties-from-power-bi).
