### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2624]
Hi,

In the section "User interacts with the visual directly" |  the current text has "A visual can save properties values **thought** the Power BI API" which I think should be "A visual can save properties values **through** the Power BI API" or something similar?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4c3363-db7e-fa34-3ade-dc56ab85fbdd
* Version Independent ID: 71959fd9-4aff-cec0-9f14-93ae3923d8be
* Content: [Power BI visuals concepts - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept)
* Content Source: [powerbi-docs/developer/visuals/power-bi-visuals-concept.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/power-bi-visuals-concept.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @premradhakrishnan . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thanks for spotting this typo - it's fixed now - see [User interacts with the visual directly](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept#user-interacts-with-the-visual-directly).

Thanks,

Kesem
