### ISSUE TITLE
Missing import declaration

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2625]
[Enter feedback here]
Hi

The code uses ISelectionManager and ISelectionID but the import declarations are missing for these. Would be great if the below is mentioned somewhere.

`import ISelectionManager = powerbi.extensibility.ISelectionManager;`
`import ISelectionID = powerbi.visuals.ISelectionId;`

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4937ba26-0e7a-54aa-b7e0-918db3fb6bdf
* Version Independent ID: d948fd0c-8b97-7184-374b-56f04b46dd70
* Content: [Add Drill-Down support - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/drill-down-support)
* Content Source: [powerbi-docs/developer/visuals/drill-down-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/drill-down-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment.

@uve - can you please assist with @premradhakrishnan's request?

**Comment by uve** [comment]
Thanks @premradhakrishnan for your feedback. We'll update the code snippet soon,

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

The missing declarations were added to [Add Drill-Down support](https://docs.microsoft.com/power-bi/developer/visuals/drill-down-support) - see [Add context menu to visual elements](https://docs.microsoft.com/power-bi/developer/visuals/drill-down-support#add-context-menu-to-visual-elements).

Thanks for pointing this out!

Kesem
