### ISSUE TITLE
Security Whitepaper is missing details on Private Link details

### ISSUE THREAD

**Issue by Johannes-Vink** [MicrosoftDocs/powerbi-docs#2626]
The Power BI Security Whitepaper does not refer to the new feature of Private Link and blocking public internet access.

As these are also security features, I guess the whitepaper should be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @Johannes-Vink! Good call - I'll assign this to a writer so that they can add the private links reference.

**Comment by paulinbar** [comment]
Hi @Johannes-Vink, an updated version of the security white paper was published this morning. It includes some mention of Private Link.
https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security
