### ISSUE TITLE
Hitting edit on this page yields a 404

### ISSUE THREAD

**Issue by jabbera** [MicrosoftDocs/powerbi-docs#2627]
The edit link on this page should go to the github document for it, instead I get a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd16a9c-3620-e1c6-518a-d6a5f9174089
* Version Independent ID: c55ccf5a-5563-1a05-7cec-46666a9e8f08
* Content: [Introduction to dataflows and self-service data prep - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-introduction-self-service#feedback)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-introduction-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-introduction-self-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@jabbera - thank you for bringing this to our attention! It looks like an underlying folder change may have broken the edit access. I'm assigning this issue to the writer to get this fixed up ASAP.

**Comment by maggiesMSFT** [comment]
Hi, @jabbera -- can you try again? I'd like to see if it's fixed.
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @jabbera -- this is fixed, so go ahead and edit. Thanks!
