### ISSUE TITLE
How to disable the pop-up when printing?

### ISSUE THREAD

**Issue by sankarapadmanathan** [MicrosoftDocs/powerbi-docs#2628]
Is there any option to disable the pop-up window when printing? Please include that information in this page.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c738da8-eb0a-7e87-0cbc-f424d4d2f381
* Version Independent ID: 1584c6a8-2152-8657-6a0b-6538f94fd1e3
* Content: [Print from the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-print)
* Content Source: [powerbi-docs/consumer/end-user-print.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-print.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Thanks for the question, @sankarapadmanathan. I'm not sure if that's possible or not, so adding the writer to comment.

**Comment by mihart** [comment]
Hi @sankarapadmanathan .  Thank you for your question.  Kate is correct, there is no way for me to write about this. When you print from Power BI, your browser opens a Print window. Each browser's Print window is different from the others.  Once you select Print, your print program takes over.  The pop-up is your print program asking for input.
