### ISSUE TITLE
How do i confirm if my dataset is using enhanced metadata model?

### ISSUE THREAD

**Issue by FFCMSouza** [MicrosoftDocs/powerbi-docs#2629]
Sometimes when i update connections parameters the connection doesn't change and i can't bind the gateway datasource.
I want to confirm if my dataset is using enhanced metadata model to guarantee that's not the problem.
How do i know it?

**Comment by kfollis** [comment]
Hi @FFCMSouza - We use this feedback channel to address issues in our documentation. Is there a particular article where you need clarification? If so, please be sure to submit feedback for that page. You can also contact https://support.powerbi.com or https://community.powerbi.com for assistance with your question. Here is an article on enhanced metadata that may help: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-enhanced-dataset-metadata. I'll close this issue now, but please feel free to submit additional feedback against a specific page. Thanks!
