### ISSUE TITLE
Any guidance on environment separation?

### ISSUE THREAD

**Issue by cmeyertons** [MicrosoftDocs/powerbi-docs#263]
In a typical enterprise scenario, do you have separate gateway(s) for each environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c772b2-ccb1-a6dc-5bf6-a94e5cadc4d8
* Version Independent ID: 8dd056db-f148-b0db-0ee9-044ab5c0dbbd
* Content: [Guidance for deploying a data gateway for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-deployment-guidance)
* Content Source: [powerbi-docs/service-gateway-deployment-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-deployment-guidance.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@cmeyertons - closing this out with answer from @arthiriyer. Feel free to reopen if necessary.
