### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by jmsmtn** [MicrosoftDocs/powerbi-docs#2635]
"Take now, however, that the" probably should be "Take note, however, that the"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming)
* Content Source: [powerbi-docs/connect-data/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jmsmtn . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for your sharp eye, @jmsmtn ! Fixed it. Fix will be live this afternoon Pacific time Fri 20 Nov 2020
