### ISSUE TITLE
In slice listview, can we sort one column based on count() from another int column DESC?

### ISSUE THREAD

**Issue by simonxiaoss** [MicrosoftDocs/powerbi-docs#2636]
For example, I have a table with two columns: 
-----------------------------------------
vendor name  |     SKU     |  Number
-----------------------------------------
Mike               |    TypeA   | 5
-----------------------------------------
Mike               |    TypeB   | 4
-----------------------------------------
Mike               |    TypeC   | 3
-----------------------------------------
Zeter               |    TypeA   | 15
-----------------------------------------
Zeter               |    TypeB   | 25
-----------------------------------------

How can I sort "vendor name" in a slice list based on the value of count(Number) desc?
This is the list I want (Zter is at the 1st place as the count is 40; Mike is the 2nd place as the count is 12):
-------------------
vendor name 
-------------------
Zeter               
-------------------
Mike               
-------------------

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @simonxiaoss . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
