### ISSUE TITLE
A full working example would be very helpful

### ISSUE THREAD

**Issue by premradhakrishnan** [MicrosoftDocs/powerbi-docs#2637]
Hi,

I have been trying to work through the tutorials under Custom Visuals in Power BI. There are some pages (this one for example) where the code feels really incomplete. A lot of declarations and imports are missing and it makes it very difficult to work through the example. Just one example is the line `this.host = options.host`; This requires a declaration `private host: IVisualHost;` and an import `import IVisualHost = powerbi.extensibility.visual.IVisualHost;` which are both missing in the tutorial.

I only knew to add these based on another example I had worked on. There are several others that are missing I have to google each one to find out how to get those libraries. 

Having so many missing elements in the code doesn't give you much confidence in the documentation and makes you feel doubtful that at the end of all the effort the example will not work.

It would be very helpful if there was a link to a complete working example in github for these pages and also save anyone trying to learn a lot of time.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75effaec-3c6e-83c9-c26e-8e58046cb347
* Version Independent ID: 971d9758-f10b-cddb-f6fa-c007e193e457
* Content: [Power BI visual data point selections - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/selection-api)
* Content Source: [powerbi-docs/developer/visuals/selection-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/selection-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @premradhakrishnan,

Thank you very much for your feedback, and for getting involved.

I'm slowly working through the tutorials and how-tos in the [Power BI visuals docset](https://docs.microsoft.com/en-us/power-bi/developer/visuals/), revising them and bringing them up-to-date.

As I'm sure you've seen, there's a difference between the [Develop a Power BI circle card visual](https://docs.microsoft.com/power-bi/developer/visuals/develop-circle-card) tutorial, and the other tutorials. The [Develop a Power BI circle card visual](https://docs.microsoft.com/power-bi/developer/visuals/develop-circle-card)  tutorial was recently updated, and the other tutorials have not yet been updated. My goal is to bring all the tutorials to the level of the [Develop a Power BI circle card visual](https://docs.microsoft.com/power-bi/developer/visuals/develop-circle-card)  tutorial. However, please note that this may take some time. In the meantime continue looking for answers the [Power BI Community]( https://community.powerbi.com) and elsewhere online.

Thanks again,

Kesem

**Comment by premradhakrishnan** [comment]
Hi Kesem,

I can definitely tell the difference between the circle card visual and others. The React one is also quite good - may be you have re-worked that too.

Thank you for letting me know. I can imagine it will take a while but at least we know the docs will improve in future. Good luck with all the changes.

Cheers
Prem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
