### ISSUE TITLE
Please elaborate CPU consumption

### ISSUE THREAD

**Issue by Landers3n** [MicrosoftDocs/powerbi-docs#2638]
[Even with the explenation on how to enterpret the CPU consumption graph in the Power BI Premium Capacity Metrics App I'm unable to understand how to enterpret it since the numbers shown in the graph in my app is more than 100 accumulated. 
"
CPU consumption | Maximum CPU consumption during the hour, by workload as a percentage of total CPU capacity. Shown hourly, for the previous seven days.
-- | --"

Is it possible to elaborate a bit on the discription?

Regards
Lasse 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/admin/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @Landers3n. I'll assign to this to the writer to review and see what additional details we can add to help with interpretation of CPU consumption.
