### ISSUE TITLE
keep the header of the table

### ISSUE THREAD

**Issue by SPIMS** [MicrosoftDocs/powerbi-docs#2639]
[Enter feedback here]
Is it possible to keep the header of the tab when we scroll down ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Good question, @SPIMS - I agree this would be handy with the long table in this article. This may be a limitation of our authoring tools, but let me check into that verify. If we can't do it now, I can submit it as a future enhancement to our tools. Thanks!

**Comment by mihart** [comment]
Hi @SPIMS 
Thank you for your suggestion.  I could not find a way to freeze the header row.  Instead, I broke up the loooonnnnggg table into  alphabetical chunks :-)
All the best,
the DOCS team
