### ISSUE TITLE
Other things to try

### ISSUE THREAD

**Issue by skiwii** [MicrosoftDocs/powerbi-docs#264]
We used the SQL Server Kerberos diagnostics tool https://www.microsoft.com/en-ca/download/details.aspx?id=39046 which showed 2 issues.  We ran the SPN commands and rebooted the box but still had the problem.
The issue was with people using Internet Explorer.  The resolution is to delete all of the history in IE (go to Settings -&gt; Safety -&gt; Delete browsing history… And delete everything except "Preserve Favorites website data”. )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a56b58c-95a4-9216-61cf-3758c5debb3d
* Version Independent ID: cd953c75-d91f-91c6-f94a-cb75eff28f6e
* Content: [Configure Kerberos to use Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/configure-kerberos-powerbi-reports)
* Content Source: [powerbi-docs/report-server/configure-kerberos-powerbi-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/configure-kerberos-powerbi-reports.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@skiwii We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
