### ISSUE TITLE
This is missing PowerShell for adding the Security group to the workspace. The other steps show powershell code. This is probably the most important because we have 300+ workspaces to add the security group to. 

### ISSUE THREAD

**Issue by brianrreed** [MicrosoftDocs/powerbi-docs#2641]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 794566fc-c06c-1d9c-b656-2e7b59bc2874
* Version Independent ID: 4c57568f-c4f2-0bd6-b724-9868b2455d50
* Content: [Embed Power BI content with service principal and an application secret - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal)
* Content Source: [powerbi-docs/developer/embedded/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for your feedback, @brianrreed. I'm assigning this to the author to see if they're able to add the requested PS sample code.

**Comment by brianrreed** [comment]
Here is the code I used to do this: 
`Login-PowerBI

# Object ID for 'Power BI Administrator Security Group'
$SecurityGroup = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
$pbiWorkspace = Get-PowerBIWorkspace -All -Scope Organization 
$i = 1
foreach($ws in $pbiWorkspace){
        Add-PowerBIWorkspaceUser -Scope Organization -Id $ws.ID -Identifier $SecurityGroup -AccessRight admin
}`

**Comment by KesemSharabi** [comment]
@brianrreed,

Thanks for your comments and suggestion. I'm checking with our development team and if applicable, I'll add a PowerShell code to the [Add the service principal to your workspace](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal#step-4---add-the-service-principal-to-your-workspace) section.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @brianrreed,

Thank you for your great suggestion. We added PowerShell scripts for adding [service principal as a workspace member](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal#add-a-service-principal-as-a-workspace-member-using-powershell) and [a security group as a workspace member](https://docs.microsoft.com/power-bi/developer/embedded/embed-service-principal#add-a-security-group-as-a-workspace-member-using-powershell).

Thanks again for getting involved,

Kesem
