### ISSUE TITLE
Having a download available for the OpportunityData.xlsx Excel file would have been preferred.

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerbi-docs#2642]
The title stands on its own. Why give me a Power BI PBIX file connected to Excel data but NOT also give me the Excel data as well? Instead you give me "Opportunity Tracking Samples.xlsx" which does not contain the source data. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3041354-2ebf-99f3-e0c5-ac57227904c8
* Version Independent ID: 3a410693-c86e-70c3-4b44-1fad4719ffb3
* Content: [Opportunity Analysis sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-opportunity-analysis#get-the-content-pack-for-this-sample)
* Content Source: [powerbi-docs/create-reports/sample-opportunity-analysis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/sample-opportunity-analysis.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Hi @ToddChitt - I'm assigning your feedback to the writer to ensure that the steps to view the Excel data are clear. You are right, that the xlsx doesn't show the data by default, it shows Power View sheets. I tried the steps, and was able to access the Excel data, but not until after enabling an Excel add-in as described here: https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets#explore-excel-samples-inside-excel. I hope that helps!

**Comment by ToddChitt** [comment]
Why does getting the sample data have to be so difficult? The author lets us download the Power BI file without issue. Why not give us the Excel file upon which all the Power Queries are based? Why do I have to download something else, then do a REGISTRY HACK?!? For something that is BLOCKED BY DEFAULT FOR SECURITY REASONS?!?

Sorry, but I totally lost interest in what this author has to say and without the back end data, the whole article is useless. 

I'm a data person. I START with data. If I don't have Data as a cornerstone, I'm not interested. I was trying to figure out the whole integration with Power Apps and have a write-back scenario. But since I can't get the back end data, no thank you. I'll move on to some other article.

Frustrated.

**Comment by paulinbar** [comment]
Hi @ToddChitt, it looks like this is still an issue. Moving it to our work item backlog and closing it here for the time being.
