### ISSUE TITLE
Licensing requirement is not clear

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#2646]
Under licensing requirements, it is mentioned that free users can access premium workspace if they are added as viewer role. However, this is not fully true. Free users can only access premium workspace that are added to 'P' SKU. If workspace is assigned to an A or EM premium capacity, then users need pro license. This requirement should be clearly mentioned. Right now, the licensing requirement is misleading and creates confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @haider392. Thanks for your comment. I am forwarding it along to the doc author for further consideration.

**Comment by mihart** [comment]
Hi @haider392 , 
Thank you for your suggestion.  A and EM SKUs are not Premium capacity.  Only the P SKU = Premium.  We've made your other suggested update and set the article to republish. 
All the best,
The DOCS team
