### ISSUE TITLE
Does this work also with Power BI Premium per User Licence?

### ISSUE THREAD

**Issue by miragliag** [MicrosoftDocs/powerbi-docs#2649]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @miragliag, thanks for your question. I am forwarding it along to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @miragliag,

Thanks for your comment.

The [Embed Power BI content using a sample embed for your customers application](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers) tutorial, was updated to reflect the fact that the sample application works with Premium Per User (PPU).

However, you can only run the sample application with a PPU license. If you want to [move to production](https://docs.microsoft.com/power-bi/developer/embedded/move-to-production) you'll require a [capacity](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity).

Hope this helps,

Kesem

**Comment by miragliag** [comment]
Thanks! Thats perfect!

Giovanni Miraglia
Betriebsökonom FH & Data-Scientist
Tel. +41 76 674 33 21
mail: giovanni@miraglia-bi.com<mailto:giovanni@miraglia-bi.com>
web: miraglia-bi.com<http://www.miraglia-bi.com>
vCard: Kontaktdaten herunterladen<https://www.miraglia-bi.com/app/download/12312501857/Giovanni+Miraglia.vcf?t=1590121962>


Von: Kesem Sharabi <notifications@github.com>
Antworten an: MicrosoftDocs/powerbi-docs <reply@reply.github.com>
Datum: Mittwoch, 16. Dezember 2020 um 14:42
An: MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc: Giovanni Miraglia <giovanni@miraglia-bi.com>, Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/powerbi-docs] Does this work also with Power BI Premium per User Licence? (#2649)


Hi @miragliag<https://github.com/miragliag>,

Thanks for your comment.

The Embed Power BI content using a sample embed for your customers application<https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers> tutorial, was updated to reflect the fact that the sample application works with Premium Per User (PPU).

However, you can only run the sample application with a PPU license. If you want to move to production<https://docs.microsoft.com/power-bi/developer/embedded/move-to-production> you'll require a capacity<https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity>.

Hope this helps,

Kesem
