### ISSUE TITLE
Correct Limitations

### ISSUE THREAD

**Issue by smjanalytics** [MicrosoftDocs/powerbi-docs#265]
"Report tooltips are not supported when viewing reports in mobile apps or in embedded environments, including Publish to web."

Custom tool-tips are working in the Embedded platform, can we please update this documentation accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Certainly, @smjanalytics - thanks for posting! I've updated the doc.
