### ISSUE TITLE
Signature Lean 101

### ISSUE THREAD

**Issue by MichaelFoundation** [MicrosoftDocs/powerbi-docs#2651]
![Uploading 100584400...]

**Comment by MichaelFoundation** [comment]
[47100](Jan Michael Omondang)
[1500](Passport Influencer)
- #[EB6296000](Most Safest Web https://@optimisitcjan@gmail.com_****_)

**Comment by MichaelFoundation** [comment]
[ROMANA LING BAYOTAS](MD CHIEF101)

**Comment by maggiesMSFT** [comment]
Hi, @MichaelFoundation -- if you have a question about Power BI documentation, please ask! In the meantime, I'm closing this issue.
