### ISSUE TITLE
Dual mode with SAP Hana

### ISSUE THREAD

**Issue by cozmicon** [MicrosoftDocs/powerbi-docs#2652]
Hello, this page does not mention the use of dual mode and the known issues and limitations when using dual mode with SAP Hana, however including this could be useful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3124203c-c90c-4b87-f657-e3373af0d480
* Version Independent ID: c2f065a5-d48a-c921-92d8-8f99874fef3b
* Content: [DirectQuery for SAP HANA in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-sap-hana)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-directquery-sap-hana.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by cozmicon** [comment]
Also, duel mode have not been mentioned on this page either. https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-sap-hana  
Does the SAP Hana connector support dual mode?

**Comment by maggiesMSFT** [comment]
Hi, @cozmicon -- thanks for your comment! Referring to the author for consideration.

**Comment by davidiseminger** [comment]
Thanks for your comment, we've updated this article, and are currently reviewing all connector articles for improvement.
