### ISSUE TITLE
This is old. There is no sharing of reports. 

### ISSUE THREAD

**Issue by kristyler** [MicrosoftDocs/powerbi-docs#2655]
Need to edit this:
There's no share in CHROME. When I open the exact same report in Firefox or Edge, share is available. 
My company uses Chrome by default. 

Chrome Version: Version 87.0.4280.66 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/57181629/100644935-956f1100-3301-11eb-8422-83a6e507408a.png)
Firefox Version: 83.0 (64-bit)
![image](https://user-images.githubusercontent.com/57181629/100645150-e2eb7e00-3301-11eb-9785-5040913b9097.png)
Edge Version: 44.17763.831.0
![Edge PBI bar](https://user-images.githubusercontent.com/57181629/100644783-5fca2800-3301-11eb-9db5-300b8dae6e94.jpg)

In Chrome only, the share item is gone.
This is either a Chrome issue or a MS issue. Sending bugs to both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b3989d-4ab1-51f2-6823-970c04f6fba9
* Version Independent ID: 673ccbe9-ef77-5c5b-9936-37eaeb4d3762
* Content: [Filter and share a Power BI report - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-reports)
* Content Source: [powerbi-docs/collaborate-share/service-share-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @kristyler -- hmmm, I just checked Power BI in Chrome and I see Share.

![image](https://user-images.githubusercontent.com/12401230/100658509-07485a00-3304-11eb-81a4-ff5087d12dbc.png)

Not sure what's causing your issue. You can contact Power BI support: https://powerbi.microsoft.com/en-us/support/
Hope that helps!

**Comment by kristyler** [comment]
Maggie,

What version of Chrome are you using?


Kris Tyler
Data Analyst
2321 N Loop Dr, Ste 220, Ames, IA, 50010
O: (515) 817-2143
LandusCooperative.com  |  Kris.Tyler@landuscooperative.com
This email is intended for the use of the person to whom it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. Dissemination, distribution or copying of this information in an unauthorized manner is strictly prohibited. Sender accepts no liability for any damage caused by any virus transmitted by this email. If you receive this email in error, please notify the sender.

**Comment by maggiesMSFT** [comment]
Hi, @kristyler -- well, this AM when I first checked, I was running:

![image](https://user-images.githubusercontent.com/12401230/100666054-3f07cf80-330d-11eb-80af-fada6e685ed6.png)

but just now it updated to

![image](https://user-images.githubusercontent.com/12401230/100666081-48913780-330d-11eb-852e-5b502e1646ea.png)

and I see the Share button in both versions.

Could it possibly be a permissions issue? Are you looking at the same report in Chrome and in Edge? You probably are; just asking.

**Comment by kristyler** [comment]
I am. I’m the BI lead. I am admin everywhere, and we have a Premium license. If it were permissions, I would never see it.


Kris Tyler
Data Analyst
2321 N Loop Dr, Ste 220, Ames, IA, 50010
O: (515) 817-2143
LandusCooperative.com  |  Kris.Tyler@landuscooperative.com
This email is intended for the use of the person to whom it is addressed and may contain information that is privileged and confidential, the disclosure of which is governed by applicable law. Dissemination, distribution or copying of this information in an unauthorized manner is strictly prohibited. Sender accepts no liability for any damage caused by any virus transmitted by this email. If you receive this email in error, please notify the sender.
