### ISSUE TITLE
Sharing reports outside the tenant?

### ISSUE THREAD

**Issue by nimai123** [MicrosoftDocs/powerbi-docs#2656]
Hello,

Can I integrate my power Bi report in teams and share it with external users.

If yes, then what are the pre-requisites for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd9c7dbe-8b03-52a9-b299-936856c89ba8
* Version Independent ID: f4496816-b872-4541-4ad9-f3b323b8917f
* Content: [Collaborate in Microsoft Teams with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-collaborate-microsoft-teams)
* Content Source: [powerbi-docs/collaborate-share/service-collaborate-microsoft-teams.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-collaborate-microsoft-teams.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @nimai123 -- good question! I'll check and let you know.

**Comment by nimai123** [comment]
Yes @maggiesMSFT ,  hope we find something on it.

**Comment by nimai123** [comment]
Hello @maggiesMSFT 
Hope you are doing good.

Did we find a way to implement the above scenario?

Regards,

**Comment by maggiesMSFT** [comment]
Hi, @nimai123 -- Still checking!

**Comment by maggiesMSFT** [comment]
Hi, @nimai123 -- here's a quick answer:

To make it work end to end, the user will need:
1.	Ensure the external user is invited to the organization and accepts that invitation
2.	Ensure the external user is added to have permission on the report, using individual permissions assignment works best right now
3.	Ensure the external user has a Power BI license assigned to them. Recommend Free license and for content to be in Premium

Hope that helps! I'll file a work item to update the article.

**Comment by nimai123** [comment]
Thanks for the update @maggiesMSFT 

That really helps!
