### ISSUE TITLE
Private links for accessing Power BI: Can't create Microsoft.PowerBI/privateLinkServicesForPowerBI resource with the ARM template

### ISSUE THREAD

**Issue by flecoqui** [MicrosoftDocs/powerbi-docs#2658]
[Enter feedback here]
I wanted to test the Private links for accessing Power BI and I faced the following issue:

I can't create Microsoft.PowerBI/privateLinkServicesForPowerBI resource with the ARM template
When deploying the template it returns first an InternalServerError and after more than an hour a timeout error.

Questions:
I used a trial version of Power BI Service, are Private Links supported with trial version?
The Azure AD Tenant associated with Power BI Service is not directly linked with an Azure Subscription.
The users of the Azure AD Tenant associated with Power BI Services have access (Owner) to a resource group in another Azure Subscription, is this scenario supported?

Do you confirm the <tenant-object-id> in the ARM Template is the Tenant Object ID of the Azure AD Tenant associated with Power BI Service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private links for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @flecoqui . This issue has been assigned to the doc author for review.

**Comment by petetakacs** [comment]
I have the same issue.

**Comment by flecoqui** [comment]
Any news about this issue?
Are the private links for accessing Power BI only available with Power BI Premium service?
Can we use the private links with Trial version of Power BI?
Can we use the private links with an Azure AD Tenant not associated with an Azure Subscription?
In the documentation, do you confirm the value 52d40f65-ad6d-48c3-906f-1ccf598612d4 and 52d40f65ad6d48c3906f1ccf598612d4-api.privatelink.analysis.windows.net should be replaced with the customer Tenant ID?
--



52d40f65-ad6d-48c3-906f-1ccf598612d4
--




52d40f65-ad6d-48c3-906f-1ccf598612d4
--




52d40f65-ad6d-48c3-906f-1ccf598612d4
--

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
