### ISSUE TITLE
Missing files in sample application linked from article

### ISSUE THREAD

**Issue by JPassenger** [MicrosoftDocs/powerbi-docs#2659]
I've just downloaded the master branch of the Power BI Developer Samples linked from this article and attempted to use the AppOwnsData sample for .NET Framework. When then running the application, it fails due to missing files (initially powerbi.js, then others). If this sample is intended to be used for a tutorial, it would be good if it actually worked!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @JPassenger . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @JPassenger,

I'm sorry to hear that you had a bas experience when using the sample application.  The [Embed Power BI content using a sample embed for your customers application](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers) tutorial, and the sample applications have recently been updated.

We've run several checks to verify that the samples work. I assume you followed the tutorial, is that correct? If so, can you please list the files you think are missing from the sample application and explain were you got stuck?

Thanks,

Kesem

**Comment by JPassenger** [comment]
Hi @KesemSharabi,
	
I was indeed following that tutorial which took me to the sample application.
	
I have been able to run the .NET Core App Owns Data version of the sample application without a problem, but I initially attempted to use the .NET Framework App Owns Data version and ran into numerous issues.
	
My initial problems I believe were local to me (missing references, etc.), but then I ran into several missing files. Unfortunately I did not keep a log of them all.
	
The first one I ran into was the powerbi.js file, which was referenced in one of the files (in /AppOwnsData/Scripts), but was not present in the solution. I checked this against the repository in case it was a download failure, or some other user error(!), but the file (and the folder in which it resided) was not present in the online repo either. I have a screenshot of the repository folder with no /scripts folder present:
![image](https://user-images.githubusercontent.com/75342113/102366358-7b475b00-3fb0-11eb-8fb8-c809dd3c9a6b.png)
	
I attempted to use an earlier commit, which does have the referenced file:
![image](https://user-images.githubusercontent.com/75342113/102365201-30791380-3faf-11eb-8237-d2a21099e5b6.png)
However, this had other issues and flagged different missing files.

Initially this meant that the sample application would load a local web page but then be unable to load the Power BI embedded report, then when I switched to the earlier commit it regressed to the point it would not build successfully.

I had not attempted to make any changes, except for the IDs as directed by the tutorial, so I'm confident it was not on my side.

**Comment by KesemSharabi** [comment]
Hi @JPassenger,

Thanks for the detailed info. I've asked our dev team to look into this and will get back to you shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @JPassenger,

This seems to be a known issue. You need to reinstall the NuGet packages as suggested in the note at the bottom of the [Step 8 - Embed your content](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-framework#step-8---embed-your-content) (after step 9):
![article note](https://user-images.githubusercontent.com/54834915/102902574-ddec9b00-4477-11eb-9a02-ce15cb605001.png)


There's also a reference to this in the .NET Framework README file:

![image](https://user-images.githubusercontent.com/54834915/102902737-07a5c200-4478-11eb-989e-cd33b646160a.png)

Hope this helps,

Kesem
