### ISSUE TITLE
Paginated report subscriptions for external / guest users

### ISSUE THREAD

**Issue by christianb7** [MicrosoftDocs/powerbi-docs#2660]
Hi,  This page seems to suggest that paginated report subscriptions are available, but doesn't restrict the scope to just internal users. My understanding is that you can not subscribe or an external user cannot subscribe to a paginated report (given they have premium per user activated).  Are you able to clarify/confirm this in the documentation.

Thanks,
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Subscribe to paginated reports in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/paginated-reports-subscriptions)
* Content Source: [powerbi-docs/consumer/paginated-reports-subscriptions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/paginated-reports-subscriptions.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Thank you for your feedback, @christianb7. I'm assigning this to the author of the article so that they can make that detail clear.

**Comment by mihart** [comment]
Hi @christianb7 , 
Thank you for your suggestion.  We've made the update and set the article to republish later today or tomorrow. 
All the best,
The DOCS team
