### ISSUE TITLE
Report subscriptions for external users

### ISSUE THREAD

**Issue by christianb7** [MicrosoftDocs/powerbi-docs#2661]
Under the heading "Considerations and Limitations" it states that report subscriptions can be created for external users, but right underneath in the bullet list it also says that they can't be created. Are you able to update the document to make this accurate to what is currently available please? Specifically regarding paginated reports vs power bi reports.

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@christianb7 - thanks for pointing that out. I'll work with the feature owner to verify the guest user capabilities and update the documentation to clarify the capabilities. If you need a quick answer, you may want to ask a question in the https://community.powerbi.com.

**Comment by mihart** [comment]
Hi @christianb7 , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
