### ISSUE TITLE
It is Unclear what kind of table the data is required to be in

### ISSUE THREAD

**Issue by Spiller70** [MicrosoftDocs/powerbi-docs#2662]
The article has a note about the data being required to be in a Table in Excel. That is unclear as there is a table object available in Excel as well as the common interpretation of data organized in a table with headers and fields. Of course in the later type, headers may be in the rows and records in the columns non-standard to Excel power users, but again that is unclear as PowerBI is reaching business users that are likely technically deficient in Excel and other DB concepts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394d90a7-d6ad-c666-9099-a85e7ab4d817
* Version Independent ID: 5077293e-a2c0-16b6-08bb-b65b11b1e9e5
* Content: [Get data from files for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data-from-files)
* Content Source: [powerbi-docs/connect-data/service-get-data-from-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-get-data-from-files.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thank you for the feedback, @Spiller70! I'm assigning this to the author for the article to consider making an update to clarify that detail.

**Comment by mihart** [comment]
Hi @Spiller70 , 
Thank you for your suggestion.  We've made the update and set the article to republish tomorrow. 
All the best,
The DOCS team
