### ISSUE TITLE
Automate : Export from Dashboard

### ISSUE THREAD

**Issue by OneConsutlantsDemo** [MicrosoftDocs/powerbi-docs#2665]
Can we use R Script to automate the Export from Dashboard every time we refresh?

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Thanks for the question, @OneConsutlantsDemo. I don't know the answer to that, so assigning this to the author for investigation. You may want to ask the question in https://community.powerbi.com to see if your peers can help with an answer.

**Comment by mihart** [comment]
Thanks for your comment, @. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
