### ISSUE TITLE
(Obviously) Missing screencaps and misleading terminology

### ISSUE THREAD

**Issue by bajumar** [MicrosoftDocs/powerbi-docs#2667]
Instructions for Finding Parameters (https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator#finding-parameters) section says "as shown below" in the steps, but there is nothing shown below.

I believe the intention was to include screencaps like the documentation for Consumption Insights here - "https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-consumption-insights"

Please add the screenshots as customers are confused about where to look.

Also, the terminology in the configuration wizard uses "Account Key", which further confuses customers because Azure Storage Accounts have Account Keys, but what they need from the EA Portal is the API Key.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc4bd0c-b3d7-3ace-ca76-696e9c278d4b
* Version Independent ID: 3c0f58ee-b290-559a-cb6d-b7afe1996760
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator)
* Content Source: [powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @bajumar -- thanks for your feedback! Assigning to the author to investigate.

**Comment by paulinbar** [comment]
@bajumar , I see what you mean and I am looking for the info I need to update the article. I'll keep you informed. Thanks for your input!

**Comment by paulinbar** [comment]
Hi @bajumar, as you might recall, I forwarded your comments along to the Sustainability Calculator team, and apparently they were working on a new version of the calculator, which has just now become available in preview on AppSource (https://appsource.microsoft.com/en-us/product/power-bi/coi-sustainability.sustainability_calculator_public_preview?tab=Overview). In the document you originally commented about they have also added documentation for that preview version. If you get a chance, please check it out and see whether it addresses the issues you mentioned. I don't think the documentation for the older version has been changed at all. In the meantime I am closing this issue. Please reopen or file another issue if necessary. Thanks!
