### ISSUE TITLE
"Script before and after" image in "Add user parameters" section is broken

### ISSUE THREAD

**Issue by Alisha-Acharya** [MicrosoftDocs/powerbi-docs#2668]
"Script before and after" image in "Add user parameters" section is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 862ef376-e3d8-fbb7-9bf6-b1323968ba4b
* Version Independent ID: 28234d27-622f-1015-c83b-ca4419ec80a8
* Content: [Build a funnel plot from R script to R visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/funnel-plot-from-r)
* Content Source: [powerbi-docs/developer/visuals/funnel-plot-from-r.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/funnel-plot-from-r.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @Alisha-Acharya . This issue has been assigned to the doc author for review.

**Comment by uve** [comment]
thanks @Alisha-Acharya for the report. We'll update image URL shortly

**Comment by KesemSharabi** [comment]
Hi @Alisha-Acharya,

Thanks for pointing this out. I've fixed this issue and you can now see the missing image in [Add user parameters](https://docs.microsoft.com/power-bi/developer/visuals/funnel-plot-from-r#add-user-parameters).

Thanks again for getting involved!

Kesem
