### ISSUE TITLE
Report export using node.js

### ISSUE THREAD

**Issue by Jhomalex** [MicrosoftDocs/powerbi-docs#2669]
Hello, I have a question about exporting PBI reports. I would like to know if a report could be exported using node.js as a backend since in the documentation I only find information for .Net.

Where could I get examples or material of the above?

**Comment by mihart** [comment]
Thanks for your comment, @Jhomalex . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
