### ISSUE TITLE
Tips and Tricks for View modes could use more detail

### ISSUE THREAD

**Issue by jrichview** [MicrosoftDocs/powerbi-docs#267]
This section needs a more step-by-step explanation.  I tried doing what it said and did not get the resulting page to format as described. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-publish-to-web)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@jrichview Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by jrichview** [comment]
It's difficult to answer now because we've been trying every possible idea we can find to get the iframe to render attractively and sensibly. It's our last technical hurdle, but we're not finding anything that seems ideal for our client.

**Comment by jrichview** [comment]
Here's a related question that this section doesn't clear up. We're editing locally in the Desktop app, then publishing to the PBI service so it can be hosted in an iframe.  Does it make any difference whether the view mode is set in Desktop before publishing or can it just be set in the PBI service web page?  Do both impact the rendering identically?

**Comment by jrichview** [comment]
What we really want is to set an iframe with a fixed width and then set each report page to render aligned top/left in that frame and to fit the width.  That doesn't sound difficult but if we set a width we find there is centering happening rather than top/left alignment and it does not present well.

**Comment by markingmyname** [comment]
@jrichview THanks for your comments. We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@jrichview Please try this - https://lukaszpawlowski-ms.github.io/Optimize-Publish-To-Web/.

Let me know your feedback.

Thank you.

**Comment by markingmyname** [comment]
@jrichview We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by jrichview** [comment]
I'm reviewing the html and script code this generates, @markingmyname, but the optimizer assumes I will only be embedding one report. I have three.
