### ISSUE TITLE
dsa

### ISSUE THREAD

**Issue by Ravi-Kumar-P** [MicrosoftDocs/powerbi-docs#2670]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e311f65-8df9-951f-6398-bab28566c8d5
* Version Independent ID: c227717d-d15e-9e34-2874-47c8dfb2e23a
* Content: [Use gridlines and snap-to-grid in Power BI Desktop reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-gridlines-snap-to-grid)
* Content Source: [powerbi-docs/create-reports/desktop-gridlines-snap-to-grid.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-gridlines-snap-to-grid.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Ravi-Kumar-P . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @Ravi-Kumar-P ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
