### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2671]
The link for [ Data warehousing using dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/best-practices-for-data-warehouse-using-dataflows) in the table is not working. Please fix it
-- | --

---
#### Detail Dokumen

⚠ *Jangan edit bagian ini. Diperlukan untuk masalah penautan docs.microsoft.com ➟ GitHub.*

* ID: 1b1b9aba-16ea-95b8-350f-a28ff62abe2e
* Version Independent ID: 121a4eff-746c-0015-c765-e2e7fa24ab4f
* Content: [Dataflows best practices - Power BI](https://docs.microsoft.com/id-id/power-bi/transform-model/dataflows/dataflows-best-practices)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-best-practices.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-best-practices.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @pawarbi  This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @pawarbi ,
I wasn't able to reproduce this.  Please try the link again and let me know if it is still broken for you.
Thanks.
