### ISSUE TITLE
Is a trend line for Scatter map supported?

### ISSUE THREAD

**Issue by TestKTMS** [MicrosoftDocs/powerbi-docs#2672]
[Enter feedback here]
We can create a trend line for Scatter map, but it is not mentioned below:

The following visuals can use a trend line if there's time data:
•	Area chart
•	Clustered column chart
•	Line chart
•	Line and clustered column chart

Is a trend line for Scatter map supported?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane#limitations)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @TestKTMS . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @TestKTMS ,
Thank you for this feedback.  I've added Scatter chart to the list and am checking with the PM to see if the list is now complete.
