### ISSUE TITLE
Power BI Report Server Subscriptions

### ISSUE THREAD

**Issue by wtg-bko** [MicrosoftDocs/powerbi-docs#2673]
[Enter feedback here]

Under this section https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports#considerations-and-limitations it says that "You can't share reports from **Power BI Report Server**. Instead, you can create subscriptions for yourself or others." and it has a hyperlink to this https://docs.microsoft.com/en-us/sql/reporting-services/working-with-subscriptions-web-portal?view=sql-server-ver15. I checked my report hosted on PBI Report Server and I didn't see any option to setup "Subscriptions". Is this section correct? I wonder if this is something that is available just for SSRS but not for PBI RS and should not have been mentioned here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df058604-4117-88d8-0cb0-935d08e5b22a
* Version Independent ID: dc8d3604-1fea-0109-2a94-13bd70a10522
* Content: [Ways to collaborate and share in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports)
* Content Source: [powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @wtg-bko.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @wtg-bko -- a reasonable question! To clarify, Power BI Report Server is a superset of current versions of SQL Server Reporting Services, so anything you can do in Reporting Services, you can do in Report Server. (Current version, because SharePoint integrated mode is deprecated in the current versions of Reporting Services.)
Anyway: Could it be a permissions issue? Here's the article about permissions: https://docs.microsoft.com/en-us/sql/reporting-services/security/tasks-and-permissions-item-level-tasks. Several of them have to do with subscriptions.
Hope that helps!

**Comment by wtg-bko** [comment]
Hi Maggie,

I am on PBI RS Oct 2020. I have System Administrator role under Site Settings and Content Manager permission on the report folder and file which are the highest level roles available to assign in Power BI RS and I am not sure how to assign these permissions for Item-Level Tasks you are referring to.

When I look at a report’ “Manage” menu in Power BI RS, what I see on the left hand side are Properties, Data Source, Scheduled refresh, Row-level security, and Security.
When I check the available roles on the PBI RS folder/file, it only has the following roles and none of them mentions about ability to manage subscriptions:
Role
Description
Browser
May view folders, reports and subscribe to reports.
Content Manager
May manage content in the Report Server. This includes folders, reports and resources.
My Reports
May publish reports and linked reports; manage folders, reports and resources in a users My Reports folder.
Publisher
May publish reports and linked reports to the Report Server.
Report Builder
May view report definitions.

**Comment by maggiesMSFT** [comment]
Hi, @wtg-bko -- Ah, you're not asking for paginated reports but Power BI reports , which currently does not have a subscription option. You can upvote this in user voice 😊:
Subscription to PBI Report in PBI Report Server - Microsoft Power BI Community, 
https://community.powerbi.com/t5/Report-Server/Subscription-to-PBI-Report-in-PBI-Report-Server/td-p/612844
