### ISSUE TITLE
pbiviz Installation Error

### ISSUE THREAD

**Issue by annettetc** [MicrosoftDocs/powerbi-docs#2674]
Hi,

I'm tryin to install pbiviz using the command : npm i -g powerbi-visuals-tools. However, I'm facing the below error every time and have been unable to find any solution online. Can you please provide help on how to proceed? Thanks

request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN rollback Rolling back powerbi-visuals-tools@3.1.15 failed (this is probably harmless): EBUSY: resource busy or locked, rmdir 'C:\Users\abc\AppData\Roaming\npm\node_modules\powerbi-visuals-tools'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\powerbi-visuals-tools\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\powerbi-visuals-tools\node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\powerbi-visuals-tools\node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\abc\AppData\Roaming\npm\node_modules\powerbi-visuals-tools
npm ERR! dest C:\Users\abc\AppData\Roaming\npm\node_modules\.powerbi-visuals-tools.DELETE
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\abc\AppData\Roaming\npm\node_modules\powerbi-visuals-tools' -> 'C:\Users\abc\AppData\Roaming\npm\node_modules\.powerbi-visuals-tools.DELETE'

**Comment by KesemSharabi** [comment]
Hi @annettetc, 

Sorry to hear you're running into errors with this command.

Just to confirm, you're following the instructions in [Set up your environment for developing a Power BI visual](https://docs.microsoft.com/power-bi/developer/visuals/environment-setup?tabs=windows) including installing *nodes.js* - correct?

@uve can you help with this error?

Thanks,

Kesem

**Comment by annettetc** [comment]
Hi @KesemSharabi ,

Yes, I am following the steps as mentioned in [ Set up your environment for developing a Power BI visual](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows) and have installed the version 14.5.1 of node.js.

**Comment by uve** [comment]
@annettetc  what is your OS and NodeJS version?
