### ISSUE TITLE
Azure Databricks is not listed as a Power BI data source

### ISSUE THREAD

**Issue by msdotnetclr** [MicrosoftDocs/powerbi-docs#2675]
Recently "native" support to Azure Databricks was added, but it is not listed as a Power BI data source on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thank you for letting us know, @msdotnetclr! We'll verify the details with the engineering team to make sure we get the right yes/no in all the columns and will get that added to the list.

**Comment by kfollis** [comment]
Thanks again, @msdotnetclr. We have added Azure Databricks to the list along with the supported connections info.
