### ISSUE TITLE
page update (date)

### ISSUE THREAD

**Issue by feemurk** [MicrosoftDocs/powerbi-docs#2677]
This page has definitely been updated since 05/08/2019 (the current reported update date).

"Beginning in the September 2020 release, we enabled support for the Google BigQuery Storage API." appears to be after the date stated.

Please update the the update date

Cheers,

Fahim.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-bigquery)
* Content Source: [powerbi-docs/connect-data/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-bigquery.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Great point, @feemurk! Sometimes people help us out to keep the content accurate, and assume the date will update automatically. But for good reasons, it doesn't! So we humans have to do it. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @feemurk ! Fixed the date. Update will be live with the next build on Monday Dec 14, 2020.
