### ISSUE TITLE
Why no Edge Chromium listed?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2678]
Based upon this list, it's unclear whether Edge Chromium is supported in Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-browsers)
* Content Source: [powerbi-docs/fundamentals/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- thanks for asking! Assigning to the writer to check.

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- turns out Edge is the official name, so that's what we call it 😁. Thanks for asking!
