### ISSUE TITLE
Contains

### ISSUE THREAD

**Issue by cjmain** [MicrosoftDocs/powerbi-docs#268]
Would love to see the 'contains' filter supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @cjmain --  thanks for your contribution! 
Our team can only answer feedback related to the documentation. Please enter your product feedback by selecting the "Product Feedback" button at the bottom of the article. You can also submit product feedback or feature ideas at https://ideas.powerbi.com, and engage with the Power BI Community at https://community.powerbi.com.
If you do have any feedback about the documentation, feel free to enter it here.
We appreciate your contribution to our articles!
