### ISSUE TITLE
Get Key in the scenario of acquiring SQL server Enterprise Edition as a Subscription License (through CSP for example)

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/powerbi-docs#2681]
When acquiring SQL server Enterprise Edition as a Subscription License (through CSP for example) it also provides the right to run Power Bi Report Server even if it does not have Software Assurance. This is not mentioned in almost all the documentation however it's possible as you can see in the [Licensing Terms](https://www.microsoft.com/pt-pt/Licensing/product-licensing/products) Page 63:

![image](https://user-images.githubusercontent.com/26462830/102108474-e49d6180-3e2a-11eb-850c-3462146699f7.png)

Besides the update that should be done in all the documentation.  in this specific page should be added the process to get the KEY in this scenario. It requires to open a CSP ticket in the Partner Center Portal:
https://partner.microsoft.com/en-US/dashboard/support/csp/servicerequests/create
Step1 : Select the options CSP > Transact and Manage > Help with downloading or activating customer software 
Step2 : Select Review solutions
Step 3: Select Provide issue details
Step 4 : Fill the form and submit a ticket request 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4600c4b7-8444-f0d4-9e81-25882a951d22
* Version Independent ID: 68e1a06b-69f7-8fc9-cfb9-8e4956580fab
* Content: [How to find your report server product key - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/find-product-key)
* Content Source: [powerbi-docs/report-server/find-product-key.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/find-product-key.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @miguelvidex.

I've assigned this issue to the doc author for review.
