### ISSUE TITLE
 SQL server Enterprise Edition as a Subscription License as a licensing option to PBI-RS

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/powerbi-docs#2682]
When acquiring SQL server Enterprise Edition as a Subscription License (through CSP for example) it also provides the right to run Power Bi Report Server even if it does not have Software Assurance. This is not mentioned in almost all the documentation however it's possible as you can see in the [Licensing Terms](https://www.microsoft.com/pt-pt/Licensing/product-licensing/products) Page 63:

![image](https://user-images.githubusercontent.com/26462830/102108474-e49d6180-3e2a-11eb-850c-3462146699f7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4600c4b7-8444-f0d4-9e81-25882a951d22
* Version Independent ID: 68e1a06b-69f7-8fc9-cfb9-8e4956580fab
* Content: [How to find your report server product key - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/find-product-key)
* Content Source: [powerbi-docs/report-server/find-product-key.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/find-product-key.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @miguelvidex.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @miguelvidex -- belatedly, the article is updated. The change will be live today. Thanks!
