### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/powerbi-docs#2683]
For more information about available data sources, see **Data Sources**. For information about connecting to data, including examples and steps, see **Connect to Data**.

The bolded sections above, Data Sources and Connect to Data should be links.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd6ac628-d5b4-e722-0532-d467c8347a5a
* Version Independent ID: 20ec07f6-627d-3765-ddcb-4aa738b6952a
* Content: [Query overview in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-query-overview)
* Content Source: [powerbi-docs/transform-model/desktop-query-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-query-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @j2associates . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @j2associates ,
Thank you for your suggestions.  I've added links to the article.
