### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/powerbi-docs#2684]
this line

background, firstLevelElements, and tableAccent (etc.):

should be

background, **foreground**, and tableAccent (etc.):

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#import-custom-report-theme-files)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @j2associates. This issue has been assigned to the doc author for review.

**Comment by j2associates** [comment]
Based on additional reading after I posted the above, it may be that the Json code should be changed instead as I think I recall seeing that foreground, background, etc have been deprecated. I'm not exactly sure.

**Comment by maggiesMSFT** [comment]
Thanks, @j2associates ! Fixed. Update will be live tomorrow afternoon, Feb 17, 2021
