### ISSUE TITLE
Description of applied filters missing/misleading

### ISSUE THREAD

**Issue by JosefPrakljacic** [MicrosoftDocs/powerbi-docs#2685]
[Enter feedback here]
For me as a reader of this documentation it is not clear if the copy of the visual only means that the set filters are described textually or if the filters set in the report are also found in the generated link.

That means when I click on the link I see exactly what the copier saw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [Copy and paste a visualization in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-copy-paste#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @JosefPrakljacic . This issue has been assigned to the doc author for review.

**Comment by msftrien** [comment]
Edited to make it more clear. Now it reads: "When you copy a static image of a visual, you get a copy of the visual, including filters applied to it, along with its metadata."

**Comment by mihart** [comment]
@msftrien @JosefPrakljacic 
Thank you both :-)  Closing this git issue now.
