### ISSUE TITLE
Symbol list

### ISSUE THREAD

**Issue by microscone** [MicrosoftDocs/powerbi-docs#2686]
This symbol list is not complete!
Please complete your documentation.

There is a symbol for an added column (calculated column), and that is not included on this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781ebece-b103-78ae-2c8a-8db99390f23d
* Version Independent ID: ca9c1aec-14fd-867a-1660-79fd33cb8158
* Content: [Using the Field list in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-field-list#field-list-changes)
* Content Source: [powerbi-docs/transform-model/desktop-field-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-field-list.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @microscone - thanks for the feedback on our documentation. I see 2 entries for calculated columns in this section of the article: https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-field-list#field-list-icons. Are we still missing an entry here or is it missing in a different section? Appreciate any additional clarification you may have!

**Comment by microscone** [comment]
Thanks for the response! Must be my mistake.
The sigma symbol isn't apparent in the desktop view, as it is not actually highlighted/accented in the way the website shows it, so it looked like a different symbol all together! 
Thanks again for the follow-up.
