### ISSUE TITLE
limitation: conditional formatting can only use measures defined in underlying model not ones created in report

### ISSUE THREAD

**Issue by fpk3** [MicrosoftDocs/powerbi-docs#2688]
limitation: conditional formatting can only use measures defined in underlying model not ones locally created in report (dataset connection).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a270e6-b0c1-bb57-831c-ce75a4d42085
* Version Independent ID: f831c935-823e-be44-02b8-c4145fe89d28
* Content: [Expression-based titles in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-format-visual-titles)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-format-visual-titles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-conditional-format-visual-titles.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thanks for the feedback, @fpk3! I'm assigning this to the writer to verify and make an update to the article.

**Comment by davidiseminger** [comment]
Thanks for your information @fpk3. I've updated the article to reflect this.
