### ISSUE TITLE
"Report settings" should be "Preview features"

### ISSUE THREAD

**Issue by NickyvVr** [MicrosoftDocs/powerbi-docs#2689]
The link described to enable this preview feature is not correct.
It says in Report settings enable the preview, but those are enabled in the tab "Preview features".

Btw, I wasn't able to edit the document itself straight away because I ended up at a 404-Page not found in Github.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b13312-84ac-72b4-483f-5d8169ecf1e0
* Version Independent ID: f648e18b-55f9-9167-a6f1-98be8180bac1
* Content: [Using DirectQuery for datasets and Azure Analysis Services (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services?source=docs)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @NickyvVr -- thanks for the feedback, and for trying to edit the doc yourself! I'm surprised you got the 404. Can you try again? Meanwhile, assigning to the author to update.

**Comment by NickyvVr** [comment]
I still get the 404. I do have to say there was also an issue displaying this article the first time (from Power BI Desktop). The URL was pointing to ...services.md instead of ...services in the end. Not sure if that is related

**Comment by maggiesMSFT** [comment]
Hi, @NickyvVr -- Hmmm, maybe because the article is new...? IDK! But thanks. I'm updating it now. Fix will be live this afternoon.
