### ISSUE TITLE
Screenshot does not match content of link

### ISSUE THREAD

**Issue by paulghodgson** [MicrosoftDocs/powerbi-docs#2690]
The Power BI Desktop samples link navigates to https://github.com/microsoft/PowerBI-Developer-Samples which does not match the screenshot.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application for your customers - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-framework)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
Thanks for the feedback, @paulghodgson! I'm assigning this to the writer to make that update.

**Comment by KesemSharabi** [comment]
@paulghodgson,

Thank you for pointing this out. I fixed the link and now it's pointing to the right GitHub folder (see [Step 4 - Create and publish a Power BI report](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-framework#step-4---create-and-publish-a-power-bi-report)).

Thanks again for getting involved!

Kesem
