### ISSUE TITLE
Add the architecture reference to documentation

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2691]
Hello, 

Can you please add [this](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/customers/power-bi) as a reference in the documentation for people who are interested in learning more about the architecture and other important details on implementation. It's already published on MS's website, but the users will find it very helpful if this is added as a reference. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Thanks for the feedback, @pawarbi! I'm assigning this to the writer to evaluate your suggestion and follow up.

**Comment by mihart** [comment]
Hi @pawarbi, 
Thank you for your suggestion.  I've added a link to the ML.NET article  :-)

**Comment by pawarbi** [comment]
Thank you
