### ISSUE TITLE
Needs to be updated for PowerBI App in Teams

### ISSUE THREAD

**Issue by tolga-balci** [MicrosoftDocs/powerbi-docs#2692]
The page needs to be updated for the PowerBI App in Teams. 
When you export the data in Excel/CSV format in Teams, PowerBI reports that the export is complete, but it does not prompt to save the file or open it automatically in Excel.

Steps to reproduce the issue:
1. Install the PowerBI App on Teams
2. Go to a tabular report in PowerBI
3. Click the three dots, select Export Data, use default values (Summarized Data) and click Export
4. PowerBU displays the dialog box "Export successful." 
5. At this stage PowerBI should prompt to save the exported file like in PowerBI online. But this does not happen in Teams app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Hi @tolga-balci - thank you for flagging that issue for us. I did reproduce your experience in Teams and also saw that no indication of where the file was saved is given. However, I did find the exported data file in the local Downloads folder. I'm assigning this to the writer and the feature owner to follow up. Thanks again!

**Comment by tolga-balci** [comment]
Thanks a lot @kfollis . After I postedto GitHub, I realized that the exported data was under the Downloads folder with the name data.xlsx.

**Comment by mihart** [comment]
Hi @tolga-balci, 
Thank you for your suggestion.  I've updated two documents to address where files are saved when using the Teams app.
