### ISSUE TITLE
does not give uptodate information!!!!!!!!!

### ISSUE THREAD

**Issue by haliluysal** [MicrosoftDocs/powerbi-docs#2694]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-hyperlinks-in-tables)
* Content Source: [powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @haliluysal . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Not enough info. Closed.
