### ISSUE TITLE
PPU License Question 

### ISSUE THREAD

**Issue by mhammons** [MicrosoftDocs/powerbi-docs#2695]
Question 14
"Can I have a dataflow run in a Premium per user workspace, be imported into a Power BI dataset in another workspace, and users who consume that content not need a Premium per user license?

As long as the Power BI report author has a Premium Per User license, this is possible during the preview period for PPU."

What does this answer actually mean? Will it NOT be possible after PPU is GA? Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User FAQ (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @mhammons. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @mhammons , 
Thank you for your question.  I checked with the Engineer responsible for this feature and he responded that #14 is not supported.  If you have additional questions, try asking the Power BI community (community.powerbi.com).
All the best,
The DOCS team
