### ISSUE TITLE
Wrong information in ko-kr doc

### ISSUE THREAD

**Issue by sehee4017** [MicrosoftDocs/powerbi-docs#2697]
Korean document of this page contains wrong information. 

English: 
![image](https://user-images.githubusercontent.com/74294219/102879453-1ba7ee80-448d-11eb-8514-4f895d728f4b.png)
https://docs.microsoft.com/en-us/power-bi/report-server/data-sources#list-of-supported-authentication-methods-for-model-refresh
Korean:
![image](https://user-images.githubusercontent.com/74294219/102879392-03d06a80-448d-11eb-9018-d87753c12d96.png)
https://docs.microsoft.com/ko-kr/power-bi/report-server/data-sources#list-of-supported-authentication-methods-for-model-refresh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37efb1d4-b4bb-f035-c63b-1f8b17d4f448
* Version Independent ID: fe9f8822-a20a-e17c-195c-1dc261ab480f
* Content: [Power BI report data sources in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/data-sources#list-of-supported-authentication-methods-for-model-refresh)
* Content Source: [powerbi-docs/report-server/data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @sehee4017 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Older than 1 year. Closing.
