### ISSUE TITLE
Sync Slicers Advanced Options info missing

### ISSUE THREAD

**Issue by excelwithallison** [MicrosoftDocs/powerbi-docs#2700]
Main edit: This page has no information on the 'Advanced options' for Sync Slicers. What does Group sync do? This blog is a bit confusing but does provide some examples: https://prathy.com/2019/02/sync-slicers-sync-slicers-advanced-options/ 

Minor: This page is outdated with its screenshots for how to turn on Sync Slicers pane 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @excelwithallison, thanks for your comment about the Sync slicers. I am forwarding it on to the doc owner for further consideration.

**Comment by mihart** [comment]
Page has been updated often since this issue was created. Closing.
