### ISSUE TITLE
Unable to connect to using Azure Cost Management with MCA

### ISSUE THREAD

**Issue by jf781** [MicrosoftDocs/powerbi-docs#2701]
I am unable to connect to Azure Cost Management using MCA.   I have entered the billing profile ID correctly as it resolves to the Billing Account.   However, no matter what I try I am given the error:

"User does not have required permissions to view events for Billing Account: "

I am a billing account owner (verified multiple times).   I am using version 2.88.802.0 of the PowerBI desktop. 

Any help would be greatly appreciated.

**Comment by paulinbar** [comment]
Thanks for your comment, @jf781. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
