### ISSUE TITLE
Add reference to the algorith used for detecting anomalies

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2705]
Hi, can you please add a reference to the algorithm used to detect anomalies using this visual. Justyna Lucznik, who is the PM for this group at Microsoft, shared the algorithm details [here](https://twitter.com/JustynaLucznik/status/1328334141893459968?s=20). Users will find it extremely helpful if [this](https://techcommunity.microsoft.com/t5/ai-customer-engineering-team/overview-of-sr-cnn-algorithm-in-azure-anomaly-detector/ba-p/982798) is added to the documentation page as a reference.

Thanks !  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946c17db-7cc8-70d7-45d5-5502fe115f67
* Version Independent ID: 62a891ef-32c6-9913-699c-dfed292839d7
* Content: [Anomaly detection tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-anomaly-detection)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by paulinbar** [comment]
Hi @pawarbi, thanks for your suggestion. I am forwarding it on to the doc authors for consideration.

**Comment by pawarbi** [comment]
@paulinbar You can close this issue. I see that they updated the documentation with the [reference](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-anomaly-detection#get-started) in this section. Thanks !

**Comment by mihart** [comment]
Hi @pawarbi ,
Thank you for your suggestion and the great links.  I've added a link to Tony Xing's post, as you suggested. The article will republish early next week.
All the best,
the DOCS team
