### ISSUE TITLE
What "AI" algorithm(s) is (are) used? Please provide reference

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#2706]
Hi, for other "AI Visuals" such as Key Influencer, Anomaly Deetection etc, the algorithm(s) used to create the visuals are cited in the documentation or are mentioned in Power BI blogs. This helps the users understand these visuals more and use them correctly. Can you please provide reference for what AI algorithm or architecture is used to create the AI splits? 

The Power BI team provided [this reference for the Key Influencer visual ](https://dotnet.microsoft.com/apps/machinelearning-ai/ml-dotnet/customers/power-bi)  and was added to the documentation page for Key Influencer as a reference. If you could add a similar reference/documentation for  the Decomposition tree visual, it will help greatly. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @pawarbi, thanks for your comment. I am forwarding it on to the doc owner for consideration.

**Comment by mihart** [comment]
Hi @pawarbi ,
We tried to explain how the decomp tree works through the following in the documentation:
The analysis can work in two ways depending on your preferences. The default behavior is as follows:
•	High Value: Considers all available fields and determines which one to drill into to get the highest value of the measure being analyzed.
•	Low Value: Considers all available fields and determines which one to drill into to get the lowest value of the measure being analyzed.

And:
You can configure the visual to find Relative AI splits as opposed to Absolute ones.
Relative mode looks for high values that stand out (compared to the rest of the data in the column).

Other than this, there are no specific other algorithms that run in the background.  

Thanks for your question. 
The DOCS team.

**Comment by pawarbi** [comment]
Thank you @mihart. Happy new year.  I wish the term 'AI' wasn't use in that case, it's misleading. Thank you for the response and the clarification.
