### ISSUE TITLE
The URL example is missing some underscores

### ISSUE THREAD

**Issue by Piquet65** [MicrosoftDocs/powerbi-docs#2707]
[Enter feedback here]
The example syntax for query-string URL immediately preceding the "Special characters in values" section is incorrect - some of the escaped characters are missing a leading underscore (specifically the square brackets).
PK
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @Piquet65, thanks for your comments. I am forwarding it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @Piquet65 -- I believe the brackets and underscores are correct now. Please do let me know if not.
Thanks!
