### ISSUE TITLE
Is incremental refresh compatible with queries that aggregate source data by month?

### ISSUE THREAD

**Issue by MRBreen** [MicrosoftDocs/powerbi-docs#2708]
Is incremental refresh compatible with queries that aggregate source data by month?
Scenario:
The source data consists of ~100k rows per day (3 ~million per month).  Fields include TimeStamps (also a Date field) and the data we’re aggregating (for example, distinct counts of TenantIDs).
The pbix file has a query that aggregates (in Kusto, summarize) by month.
I would like to incrementally refresh monthly data once a full month is available.   

Notes:
The incremental refresh examples append row for row from the source data to the pbix file, and are not an aggregated query.  
The source data lags by about 5-6 days.
Feel free to reach out for clarification on teams or email:  v-mibre

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-incremental-refresh?source=docs)
* Content Source: [powerbi-docs/admin/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @MRBreen, thanks for reaching out to us with your question. I'm forwarding in on to the doc author for consideration. Thanks!

**Comment by mihart** [comment]
Thanks for your comment, @MRBreen . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
