### ISSUE TITLE
Why Chrome not edge and bing

### ISSUE THREAD

**Issue by aguptadel** [MicrosoftDocs/powerbi-docs#271]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c35dd8c-d5d5-50d3-2f4c-26993f7966aa
* Version Independent ID: 56842b5d-abd0-a5e8-a8b5-1f6a274940f7
* Content: [Exploring data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/exploringdata)
* Content Source: [powerbi-docs/guided-learning/exploringdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/exploringdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @aguptadel, thank you for your comment. I assume you are asking why our examples show Chrome vs. Edge and Bing. We do this for a couple of reasons. 1) we want to show readers that we are not Microsoft-centric and 2) we want to acknowledge that the majority of users are running Chrome and reflect that in our docs.
