### ISSUE TITLE
TRUE/FALSE settings on Visual Header

### ISSUE THREAD

**Issue by MisterOttermayer** [MicrosoftDocs/powerbi-docs#2711]
Can these be set to default values via a template? There is no mention of this in the documentation, but I bet it's possible

**Comment by paulinbar** [comment]
Hi @MisterOttermayer, you've opened your comment as a docs issue. Can you provide a URL for the doc you are referring to? Thanks.

**Comment by MisterOttermayer** [comment]
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes

**Comment by paulinbar** [comment]
Thanks for the quick response @MisterOttermayer! I am now forwarding this along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
