### ISSUE TITLE
does this functionality depend on having premium workspace?

### ISSUE THREAD

**Issue by JainVikas** [MicrosoftDocs/powerbi-docs#2714]
I tried following the document, it worked fine till publishing. However, I tried manually adding more data to my db and refresh to see if new records will also be score and it doesn't work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdd02ee-f034-f9c3-7d52-199944ac23bb
* Version Independent ID: 4336a0d9-94d1-a5f7-f0d1-e5d260018b68
* Content: [Tutorial: Consume an Azure Machine Learning model in Power BI - Azure Machine Learning](https://docs.microsoft.com/en-us/power-bi/connect-data/service-aml-integrate?context=azure/machine-learning/context/ml-context)
* Content Source: [powerbi-docs/connect-data/service-aml-integrate.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-aml-integrate.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @samuel100
* Microsoft Alias: **samkemp**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JainVikas.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @JainVikas -- good question! I'm checking and will let you know. Thanks for asking!

**Comment by maggiesMSFT** [comment]
Hi, @JainVikas -- I was able to save this sample to a non-Premium workspace. I have a Pro license. 
Does that answer your question? 
Thanks!
cc @sdgilley

**Comment by JainVikas** [comment]
unfortunately it doesn't. Let me give you an example of what happens.

say I am using a SQL db to store new data on which I need to do prediction. 
When I am on desktop, the azure insight works well, everytime i refresh my data, the new data get feeded and the prediction results are available. Now if I publish my desktop to PowerBI service, note the credentials are verified and they are correct. Then if we get new data in db, and I have a scheduled refresh on my PowerBI service, the new data get fetched and display in the table but the prediction doesn't happen, the column is just blank. 
That is why I was wondering if having a premium workspace is a way to go. Sorry I can see that it was not clear from my first question,

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation has changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
