### ISSUE TITLE
Multiple broken links

### ISSUE THREAD

**Issue by jrp13149** [MicrosoftDocs/powerbi-docs#2715]
[Enter feedback here]

I was interested in this but the links to the sample scripts and PBIX file all appear to be broken.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 862ef376-e3d8-fbb7-9bf6-b1323968ba4b
* Version Independent ID: 28234d27-622f-1015-c83b-ca4419ec80a8
* Content: [Build a funnel plot from R script to R visual in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/funnel-plot-from-r)
* Content Source: [powerbi-docs/developer/visuals/funnel-plot-from-r.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/funnel-plot-from-r.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
@jrp13149 - thank you for bringing this to our attention. I'll assign this issue to the author to verify and update the broken links. I was able to repro your experience with the links to the spline visual and the PBIX for the HTML widgets gallery, and we'll be sure to check them all. Thanks again for the feedback!

**Comment by KesemSharabi** [comment]
Hi @@jrp13149,

Thanks for letting us know about these broken links. I'll fix them shortly.

Kesem

**Comment by helen508light** [comment]
@jrp13149 
Is this repo and its files not available to you? https://github.com/PowerBi-Projects/PowerBI-visuals/tree/master/RVisualTutorial/TutorialFunnelPlot/chapter4_RHTMLCustomVisual/multipleRHTML ?
