### ISSUE TITLE
Trust Center link

### ISSUE THREAD

**Issue by CC-Fleming** [MicrosoftDocs/powerbi-docs#2716]
I believe the link to Trust Center is inaccurate, the link currently brings us to "International availability of Dynamics 365".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6bd837-63e3-8bcd-9743-425e6da4a9b8
* Version Independent ID: 944bd5e0-a52f-0a4c-362b-68701f03c8d8
* Content: [Administering Power BI - frequently asked questions (FAQ) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-faq)
* Content Source: [powerbi-docs/admin/service-admin-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @CC-Fleming - thank you for flagging that. I'll look up the correct URL and make a swap.

**Comment by kfollis** [comment]
Thanks again, @CC-Fleming! I found several instances of the same URL and have updated the URL to go here instead: https://www.microsoft.com/trust-center/product-overview. The change will be live later this afternoon.
