### ISSUE TITLE
Clarity needed in a specific line

### ISSUE THREAD

**Issue by vtitte2020** [MicrosoftDocs/powerbi-docs#2717]
This statement in the Power BI security white paper doesn’t make sense. Unless I am missing something. From a DAX query stand point, queries against import dataset, the gateway is really not an issue. Gateway is only needed to refresh the dataset. Seems like this statement needs to broken up or clarified. Can you take a look?

>> **Import queries do not include credentials for the underlying data, and the underlying data is loaded into the Power BI service unless it is on-premises data accessed through a Power BI Gateway, in which case the query only stores references to on-premises data.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security#data-storage-and-movement)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@vtitte2020 - thank you for the feedback on the documentation. I am assigning this issue to the writer to review this section of the article for clarity.

**Comment by davidiseminger** [comment]
Larger changes being incorporated to that article, underway.
