### ISSUE TITLE
Are you sure that dashboard does not allow for filtering?

### ISSUE THREAD

**Issue by LydiaLim93** [MicrosoftDocs/powerbi-docs#2718]
It is INCORRECT to say that dashboard does not allow for filtering. All you need to do is open a tile in dashboard in Focus mode, and filters are there for your perusal. You are contradicting the Learning Path quiz answers.

Location of error in documentation:
![image](https://user-images.githubusercontent.com/45248088/103976428-b0129080-51b1-11eb-8806-eff362d2f46a.png)

Answer as per Learning Path:
![image](https://user-images.githubusercontent.com/45248088/103976589-18fa0880-51b2-11eb-9ce7-c78e98c8d0e4.png)

Proof that filtering IS possible for dashboard:
![image](https://user-images.githubusercontent.com/45248088/103976641-434bc600-51b2-11eb-9744-b336268b4b03.png)

Maybe the sentence should be changed to say that dashboard tiles do not cross-filter ? Be more specific about what you mean by "filter is not allowed in dashboards"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [Intro to dashboards for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboards)
* Content Source: [powerbi-docs/create-reports/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @LydiaLim93 -- you're right that you can filter an individual tile on a dashboard! You can't save the filters; when you exit focus mode, it goes back to its original state. I added a note to the table in this article, with a link to the article about focus mode, https://docs.microsoft.com/en-us/power-bi/consumer/end-user-focus#working-in-focus-mode.
I'll mention it to the folks who work on the Learning Path content, too.
Thanks!

**Comment by LydiaLim93** [comment]
Hey Maggie, Thank you very much for the prompt response!
