### ISSUE TITLE
How does the engine construct table schemas based on the data?

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/powerbi-docs#2719]
When you write data from your dataflow to the Azure SQL enhanced compute engine, presumably it's creating the schema based on data samples?

Can you write a little more about how the system creates the schema? What if a text column in your first 1,000 rows only has 5 character strings, but later columns have 7 character strings? Can we explicitly set the schema of the tables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @kthejoker  -- thanks for your question! Assigning to the author for consideration.

**Comment by mihart** [comment]
Hi @kthejoker, 
Thank you for your suggestion.  I contacted the Product team and received the following answer to your question.

The validation and refresh processes inform dataflows of the model schema. To set schema, you use the PowerQuery Online Editor and set data types. 

If this didn't answer your question, I suggest posting to the community forum: community.powerbi.com.
All the best,
The DOCS team
