### ISSUE TITLE
Moving pages bar to top of the report.

### ISSUE THREAD

**Issue by ranjit321** [MicrosoftDocs/powerbi-docs#272]
Is there any way I can move bar containing page names to top of the report instead of bottom? I mean page1 , page 2 .... should be on top of the report from where I can navigate to different pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tooltips)
* Content Source: [powerbi-docs/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tooltips.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ranjit321. The functionality you're asking about isn't currently possible in Power BI Desktop.

You can submit product feedback or feature ideas by using the button labeled Give Product Feedback, or by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
