### ISSUE TITLE
Tutorial does not use same data as Quickstart: Connect to data in Power BI Desktop

### ISSUE THREAD

**Issue by advbsmith** [MicrosoftDocs/powerbi-docs#2720]
The Quickstart: Connect to data in Power BI Desktop links to this page, and it would be logical to use the same data. There should be a logical progression in the Tutorials from an earlier tutorial to the next tutorial in the sequence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @advbsmith -- thanks for your feedback! Assigning to the author. I see what you mean about having the tutorials follow one after the other and build on each other. On the other hand, this one is illustrating a different scenario, getting data from a web page. 
Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look into consolidating the samples we use in our articles.
