### ISSUE TITLE
Personalization is not saved

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2721]
Hi, one thing to note is that any personalization of visuals does not seem to be saved as part of the comment's bookmark.  Is this intentional?  Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe39329-a8c9-8a14-ab97-ca853b432bf3
* Version Independent ID: 7dbe16ce-5a10-1162-a1f1-92d5280ed534
* Content: [Add comments to dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-comment)
* Content Source: [powerbi-docs/consumer/end-user-comment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-comment.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro -- happy new year! I hope you are well. 
You mean personalizing visuals, as in https://docs.microsoft.com/en-us/power-bi/consumer/end-user-personalize-visuals? Good question! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @asocorro ,
I see that this Git issue is a bit old and there hasn't been activity for a while, so I'm going to close it.  I hope that you were able to get your questions answered. If not, another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by asocorro** [comment]
Hi Michele, I don’t understand why issues are closed without a reply.  This is about the third email I get about issues being closed because they are “old.”

Thanks,
Adolfo
