### ISSUE TITLE
Page not up to date

### ISSUE THREAD

**Issue by guissebr** [MicrosoftDocs/powerbi-docs#2723]
This page hasn't been updated since April 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66293710-49bc-2b37-8899-bd917e70d626
* Version Independent ID: 913116b4-7117-ee02-8aff-5be681896a71
* Content: [What's new in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-whats-new)
* Content Source: [powerbi-docs/fundamentals/service-whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-whats-new.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @NikhilGaekwad-MSFT
* Microsoft Alias: **nikhilga**

**Comment by maggiesMSFT** [comment]
Hi, @guissebr -- you're right, it is not up to date. Assigning to the author to see what we need to do to get it back up to date.

Thanks!

**Comment by mihart** [comment]
Hi @guissebr , 
Thank you for your suggestion.  We've updated the page.  I believe there is a plan in the works to combine the Power BI service and Power BI Desktop "What's new" articles in the near future.  
All the best,
The DOCS team
