### ISSUE TITLE
Changing role name in documentation to be more consistent. 

### ISSUE THREAD

**Issue by sneakernuts** [MicrosoftDocs/powerbi-docs#2725]
In the documentation it shows the old role "Power BI Service Administrator", in the admin portal it's referred to as "Power BI administrator"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20e00bb3-017a-1954-148c-d5cfa665a2de
* Version Independent ID: a5a1ccf2-e84a-9041-c157-fa6d80ef769b
* Content: [Understanding Power BI service administrator roles - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-role)
* Content Source: [powerbi-docs/admin/service-admin-role.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-role.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks @sneakernuts! I'll get that cleaned up right away - appreciate you flagging that for us.

**Comment by kfollis** [comment]
Thanks again, @sneakernuts! This change has been made and the update will publish later this afternoon. I do want to note that PowerShell still returns the full "Power BI service administrator" role name so that example hasn't been changed, but all other mentions should now be consistent.
