### ISSUE TITLE
Page inappropriate to source 

### ISSUE THREAD

**Issue by andymayPlunket** [MicrosoftDocs/powerbi-docs#2729]
[Enter feedback here]
I got to this page from a "lean more" link in the colour function for a Card visualisation, the way the function works is similar, but not the same as conditional formatting of a column in a table, therefore is quite missleading

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-nz/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, @andymayPlunket - could you post where that link was from (the article / location), so we can get that fixed? Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @andymayPlunket -- great feedback! Though not really about the article itself. I've passed it on to the product team. You can also provide feedback to the product team at https://ideas.powerbi.com/ideas/.
Thanks!
