### ISSUE TITLE
More Visual Examples?

### ISSUE THREAD

**Issue by dduksoup** [MicrosoftDocs/powerbi-docs#273]
I thought that was a very basic introduction to getting started with what Power BI has to offer. I'm coming from a Tableau background, and I would appreciate it more if the guided learning provided more visual examples to illustrate the concepts introduced in the lessons. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Getting started - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@dduksoup - thanks for your feedback! We're working on improving our Learning experience, and will certainly take your feedback into consideration. We're happy you're here, and hope you find our future content improvements compelling.
