### ISSUE TITLE
User cannot see the data gateway except if he is added as a gateway administrator

### ISSUE THREAD

**Issue by arseyam** [MicrosoftDocs/powerbi-docs#2730]
[Enter feedback here]
I created a data gateway then added a data source and assigned a user access to it however he was not able to select the data source from the dataset settings except when I added him as a data gateway administrator!

This is not the right approach since we are sharing this data gateway between multiple users and we don't want anyone to miss with the permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sql-tutorial#connect-a-dataset-to-a-sql-server-database)
* Content Source: [powerbi-docs/connect-data/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by mihart** [comment]
Author never responded and issue is more than 1 year old. Closing.
