### ISSUE TITLE
Multiple customer issues with missed instructions

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2732]
"Make sure there are no Power BI admin-consent-required permissions set on this application."

Several customers are having issues with these instructions and missed the important section called out earlier; is there anyway we can add this as an important call out within the docs, either thru commonly used iconography and color-differentiation or any other creative methods. I've had this come up now with multiple customers and this would be helpful to avoid potential future customer issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd7616-4a1c-fe01-1b6b-6190bd2fdb63
* Version Independent ID: 93839448-4a4b-5489-14d4-6eebe4b3d34a
* Content: [Enable service principal authentication for read-only admin APIs (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/admin/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @itsnotaboutthecell . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @itsnotaboutthecell, thanks for your comment. I just want to clarify your request. Are you suggesting that we take the current statement and make it more visible somehow, or is the statement itself not clear, in addition to not being prominent enough? 
Thanks!

**Comment by itsnotaboutthecell** [comment]
@paulinbar more prominent, it's clear in its instruction but I've had multiple interactions now where the reader simply missed this particularly crucial step.

**Comment by mihart** [comment]
Hi @itsnotaboutthecell , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
