### ISSUE TITLE
Word duplication

### ISSUE THREAD

**Issue by Jaqiehaas** [MicrosoftDocs/powerbi-docs#2733]
This allows the model to be queried even when **being it's being** processed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-ca/power-bi/admin/service-premium-what-is#how-capacities-function)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @Jaqiehaas 

Well done for catching this typo, and thanks for letting us know. I'll fix it shortly and let you know when it's done.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @Jaqiehaas,

Once again, thanks for spotting this. The document is now fixed - see [How capacities function](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#how-capacities-function).

Thanks,

Kesem
