### ISSUE TITLE
Analysis Services Vertical engine?!

### ISSUE THREAD

**Issue by Jaqiehaas** [MicrosoftDocs/powerbi-docs#2734]
Should it not be Analysis Services **Vertipaq** engine?
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-ca/power-bi/admin/service-premium-what-is#how-capacities-function)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Jaqiehaas -- Ha! Good catch. Fixed. Change will be live this afternoon, Fri Jan 15, 2021
