### ISSUE TITLE
First sentence uses incorrect phrasing

### ISSUE THREAD

**Issue by alan-at-microsoft** [MicrosoftDocs/powerbi-docs#2736]
The first sentence of this document, "Monitor report performance in Power BI Desktop by using the Power BI Premium Metrics app", incorrectly relates Power BI desktop with a monitoring capability uniquely available within the Power BI service (i.e. the Premium Capacity monitoring app). Performance Analyzer is a tool used to monitor performance of content within Power BI desktop.

Based on the nature of this document and the specific topics that are addressed, this opening statement could say a flavor of the following:

"Monitor report performance in Power BI Desktop using the Performance Analyzer, and monitor performance of content deployed into your organization's Power BI Premium capacity with the help of the Power BI Premium Metrics app" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683b70c5-16bc-6d10-0433-a39a6be16995
* Version Independent ID: 9d664ac7-b484-3b5f-f215-613f95fe60ec
* Content: [Monitor report performance in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/monitor-report-performance)
* Content Source: [powerbi-docs/guidance/monitor-report-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/monitor-report-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-pemyer**

**Comment by maggiesMSFT** [comment]
Thanks, @alan-at-microsoft ! Agreed. I made the change; update will be live this afternoon.

**Comment by alan-at-microsoft** [comment]
Great, thank you!

Alan Lantz
Power BI Technical Specialist
Enterprise commercial - Manufacturing
mobile: 412-395-5156 | alan.lantz@microsoft.com<mailto:ben.tirado@microsoft.com> |LinkedIn<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Falanlantz%2F&data=02%7C01%7CAlan.Lantz%40microsoft.com%7Cad218619e0844a59409908d751a63e5c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637067646766966535&sdata=TtqzUdmc4%2FQqrgD8e6rLXxKDWWXAJOmhqTcbbMT64hw%3D&reserved=0>
Free Online Power BI training<https://aka.ms/PBItraining>
[cid:image001.gif@01D6EB2F.BF7674D0]
