### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by Krzysztof-Hyla** [MicrosoftDocs/powerbi-docs#2737]
Hi, the link to the pbix file returns an 404 error - could you please fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c22af6d-1ae9-9288-51b6-8d05c51d1b56
* Version Independent ID: bd77226f-99c4-9f7f-c353-7fa0891a891c
* Content: [COVID-19 tracking sample for US state and local governments - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-covid-19-us#feedback)
* Content Source: [powerbi-docs/create-reports/sample-covid-19-us.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/sample-covid-19-us.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Krzysztof-Hyla -- hmmm, not good. I'll investigate soon. Thanks for letting me know!

**Comment by mihart** [comment]
Hi @Krzysztof-Hyla ,
Thank you for your question.  However, I am unable to replicate it, so I am going to close this Git Issue.  Perhaps the broken link has already been updated?  If you still have problems, just let us know.
Take care,
the DOCS team
