### ISSUE TITLE
Outdated ggplot2 package version.

### ISSUE THREAD

**Issue by NairaMSFT** [MicrosoftDocs/powerbi-docs#2738]
Hi team, 

The ggplot2 version was recently updated on Power BI Service to support version 3.3.2. Please kindly update this version on the supported versions in R script.

Regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-r-packages-support#r-packages-that-are-supported-in-power-bi)
* Content Source: [powerbi-docs/connect-data/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @NairaMSFT -- thanks for your comment! 
Question: I selected the link in the ggplot2 row of the table, https://cran.r-project.org/web/packages/ggplot2/index.html. It lists the version as 3.3.3.
Should we put 3.3.2 or 3.3.3 in the table? 
Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @NairaMSFT ! Change is made, will be live later today.

**Comment by NairaMSFT** [comment]
Thanks a lot for the help!
