### ISSUE TITLE
Cannout publish report to new workspace with Power BI dataset as source

### ISSUE THREAD

**Issue by rebeckanylin** [MicrosoftDocs/powerbi-docs#274]
Hi,
When I use a Power BI dataset as data source from a new workspace I cannot publish that report to the new workspace. The same thing for old workspaces works fine.

**Comment by davidiseminger** [comment]
Thanks for your comment, @rebeckanylin. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
