### ISSUE TITLE
Where do I sign for Power BI Pro?

### ISSUE THREAD

**Issue by AeliusRuivus** [MicrosoftDocs/powerbi-docs#2741]
I just want to know where do I click to sign for Power BI Pro. It is the second time I go through this maze, this information should not be buried behind 70 pages!

![image](https://user-images.githubusercontent.com/46090686/104902289-3cc60700-5987-11eb-95a3-20e9ea2eb574.png)

Power BI service redirects to this page, and this page is useless regarding how to sign up for the service!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @AeliusRuivus . This issue has been assigned to the doc author for review. I've also assigned to the product team to take a look at the Learn more link.

**Comment by maggiesMSFT** [comment]
Hi, @AeliusRuivus -- sorry to hear the link wasn't useful. Would either of these links have been more helpful? 

- https://docs.microsoft.com/en-us/power-bi/admin/service-admin-disable-self-service
- https://docs.microsoft.com/en-us/power-bi/admin/service-admin-purchasing-power-bi-pro 

It sounds like you did eventually end up at an article with useful info. If so, could you share that? Thanks!

**Comment by AeliusRuivus** [comment]
Hi Maggie, the second link describes how I did it, but I did not use that page to get there - I found out on my own.
Maybe you could add the specific, direct url to start the purchasing process. Navigating the admin center is counter intuitive enough, but if the document could be more direct (like a tl, dr version), that would be helpful.

Moreover, why doesn't power bi have a direct link for purchase? I am the only admin (and the only person, period) in the "orgnization", so there is no need to isolate me from the purchase link.

Digging even deeper, and outside of documentation scope, why is so difficult to get power bi as an individual? Doesn't Microsoft want more people using the tool? If I, a data scientist, could purchase my own license, I would take power bi with me to every company. Right now, I tell companies to avoid it because of those annoyances...


Ruivo
________________________________

**Comment by haydnr** [comment]
Hi Rafael,

I want to start by thanking you for taking the time to provide us feedback. It's very helpful and we truly appreciate it!

We very much want to make it as easy as possible to get Power BI as an individual. We do have a direct link for purchase which is available for many users but there are some circumstances we're not currently able to support. If you are willing to share the domain of your tenant with us it will be easier to debug your situation and determine why you did not see a direct link to the purchase process.

Haydn

**Comment by AeliusRuivus** [comment]
Hi Haydn, I’m more than willing to share the tenant, but (and this is one of the things that frustrates me the most), I don’t even know how to do that. Tell me where I can find this and I’ll share, no problem.

I have a pretty good idea on why I can’t see the direct link you mention – this is the one that appears after you try to do something supported only in PRO, right? The pop up where you can try out for 60 days? Thing is, I did the trial a few months ago, and now the same action just refers me to the documentation page (hence me bothering you guys).

I apologise for my frustration, I understand a lot of it is transpiring in my emails. It is just that trying to manage Power BI as a stand alone product is very, very frustrating. The settings are so fragmented, and the entire thing is so unwieldly awkward that feels like an IBM solution of the 90’s (no offence intended).

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by haydnr** [comment]
Thanks for being willing to continue the conversation Rafael!
Your prior trial status should have no bearing on your eligibility to purchase Power BI in product. Trial and in-product purchase eligibility are independent.
You statement below pains us. We aspire to so much better than this.
It is just that trying to manage Power BI as a stand alone product is very, very frustrating. The settings are so fragmented, and the entire thing is so unwieldly awkward that feels like an IBM solution of the 90's (no offence intended).

I'd love to understand what you would envision as your ideal solution for managing Power BI as a standalone product.

Two simple starting points for investigating your specific situation might be

  1.  Share with us the email address you use to sign-in to Power BI
  2.  If you click on the "Me Control" in the top right of Power BI (see below) and select View Account and then select Subscriptions, it will show you a User Unique Identifier which if you share it with us we can use to look you up
[cid:image001.png@01D6EF01.8069A020]
[cid:image002.png@01D6EF01.8069A020]

[cid:image004.png@01D6EF02.5281A710]

**Comment by AeliusRuivus** [comment]
Hi Haydn, let me start by saying that even though Power BI frustrates me, your attention to my rabid ramblings is both inspiring and refreshing. Thank you, and if this is the attitude of the rest of the team, my faith is, restored, for what it is worth.

As for the subject at hand, my email is ruivo@busson.com.br<mailto:ruivo@busson.com.br>. Here is my account contact:
[cid:image001.png@01D6EF5E.35F87D10]

As you can see, I managed to get the subscription going, so don’t worry about that particular account.

Regarding what I think could improve, I would love to provide feedback if you guys want, but a good starting point is the ability to actually control my subscription on the very page I took the above screenshot from. As it stands, I have to Google how to log into Admin center.

Wouldn’t be better if I could click to upgrade or cancel? Let the system figure out if I’m the sysadmin or not, the tenant admin or not (I’m both because I’m the one that set up the entire thing in the first place – and yet the system still refers me to “your administrator” (that is one of the 90’s IBM vibes I mentioned earlier 😊)

Once again, I apologise for venting my frustration earlier. But like you, I believe Power BI has all the elements to be a excellent platform, if only certain annoyances are squashed. If you knew the truckload of suggestions waiting for a willing ear in the product and dashboard visuals department!

Best regards, and let me know if further feedback is indeed useful.

Regards,

Ruivo

**Comment by haydnr** [comment]
Thank you Ruivo.
That’s enough for us to investigate.
Unfortunately your screenshot is not coming through mail. You might try sending to me directly @ haydnr@microsoft.com<mailto:haydnr@microsoft.com> and if that doesn’t work I’d be open to a call where you can show me directly. I agree that it would be a better experience for the system to determine that you are the Global Admin and then route you directly to the appropriate admin experience. I’m investigating now what it would take for us to make that change.

If you have other suggestions in the product and visuals department that you would be willing to write up I can ensure they get to the right folks. Timing is good right now as we’re planning our next set of work.

Thank you for your continued engagement!
It’s feedback like yours from the Power BI community that enables us to continuously improve the product.
I’d also recommend that you participate in Ideas (powerbi.com)<https://ideas.powerbi.com/ideas/>. The team takes the feedback and suggestions in the Ideas forum very seriously and we make a point of delivering against many of the top items in every release.

**Comment by maggiesMSFT** [comment]
Hi, @AeliusRuivus and @haydnr -- sounds like you were able to connect via email, so I'm closing this issue. Thanks so much for the in-depth and cordial conversation!
