### ISSUE TITLE
I have the latest Power BI Desktop Version but I cannot see the Azure Cost Management Connector

### ISSUE THREAD

**Issue by HaoZhang615** [MicrosoftDocs/powerbi-docs#2743]
![image](https://user-images.githubusercontent.com/30301459/105066617-45016d80-5a7f-11eb-94c3-998dfaefbf00.png)

**Comment by mihart** [comment]
Thanks for your comment, @HaoZhang615 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
