### ISSUE TITLE
Which version of PowerBI.Net SDK Supports Large Models?

### ISSUE THREAD

**Issue by vtjc2002** [MicrosoftDocs/powerbi-docs#2744]
Which version of PowerBI.Net SDK Supports Large Dataset?
And please share the doc location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large datasets in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models)
* Content Source: [powerbi-docs/admin/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @vtjc2002 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @vtjc2002,

Large models are supported on any recent version of the V2 SDK, for example version 4.3.0 [https://www.nuget.org/packages/Microsoft.PowerBI.Api/4.3.0](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FMicrosoft.PowerBI.Api%2F4.3.0&data=04%7C01%7CKesem.Sharabi%40microsoft.com%7C064aca965daf44af273308d9f0a76098%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637805424008330061%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0di3eabBKIYPRaVVs%2BWHxLURsz%2FDUE0rYK%2Bw7ajgJMk%3D&reserved=0)

Here are some documents that might help you:
* [Datasets - Update Dataset](https://docs.microsoft.com/rest/api/power-bi/datasets/update-dataset)
* [Datasets - Update Dataset In Group](https://docs.microsoft.com/rest/api/power-bi/datasets/update-dataset-in-group)

Thanks and sorry for the very long wait,

Kesem

**Comment by vtjc2002** [comment]
Thank you
