### ISSUE TITLE
Some example code would be wonderful

### ISSUE THREAD

**Issue by wbovela** [MicrosoftDocs/powerbi-docs#2745]
[Enter feedback here]
How to add analytics to the correct pane is valuable. But adding some example code, or even a link to a github repository of a visual including analytics would complete this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21268b6d-592b-8a5e-e332-2ce014c2d36a
* Version Independent ID: eb9c880d-35fe-f931-2485-1aa3d1958845
* Content: [The Analytics pane in Power BI visuals in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/analytics-pane?WT.mc_id=DP-MVP-5003712)
* Content Source: [powerbi-docs/developer/visuals/analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @wbovela

Thank you for your suggestion.

@uve - who can help with adding examples to [The Analytics pane in Power BI visuals](https://docs.microsoft.com/power-bi/developer/visuals/analytics-pane).

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @wbovela,

Unfortunately we don't have any samples at present. Perhaps in the future we'll be able to add samples to this article.

Thanks,

Kesem
