### ISSUE TITLE
Microsoft 365 group is not supported for sharing

### ISSUE THREAD

**Issue by VsabGit** [MicrosoftDocs/powerbi-docs#2746]
Hi,
in the limitations and consideration section, you don't mention that the users can't share with a Microsoft 365 group.
Even though when now the user tries to share with an M365 group they get an a very clear error message
![image](https://user-images.githubusercontent.com/25950746/105149720-8724c080-5b0c-11eb-9cbb-37d5e5450c05.png)

We encountered an issue where about 6 months ago users somehow managed to shared a report with an M365 group, and they embedded that report in SPO. now the users they shared the report with access SPO and try to consume the report and get an error that they have no access - since sharing to an M365 is not supported. The whole situation was very confusing, and it took us a while to figure out what happened.

So can you please address that as well, that if somehow an M365 group is show under Access as being shared with, it's not actually supported and the users of that group won't have access to the report.

Thanks,
Sabre

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @VsabGit.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, so much, @VsabGit -- you're right, and the Limitations and considerations section has been updated accordingly. Thanks!
