### ISSUE TITLE
Needs to be updated to show the new look in Power BI Desktop and the Power BI service

### ISSUE THREAD

**Issue by SQLGuyJPS** [MicrosoftDocs/powerbi-docs#2747]
This page needs to be updated to reflect the new appearance of the Power BI Desktop application and the Power BI service. The screenshots and instructions are out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Use bookmarks in Power BI Desktop to share insights and build stories - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-bookmarks#feedback)
* Content Source: [powerbi-docs/create-reports/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @SQLGuyJPS .

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @SQLGuyJPS -- of course you're so right! Article has been updated in the meantime. Thanks!
