### ISSUE TITLE
Should this page mention necessary user security level for subscribing others?

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#2748]
The users in my premium capacity are trying to create subscriptions and add others but are being told they can't because they aren't owners. Seems like that would be useful information to include here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Subscribe to paginated reports in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/paginated-reports-subscriptions)
* Content Source: [powerbi-docs/consumer/paginated-reports-subscriptions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/paginated-reports-subscriptions.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- Good idea! Added it. Thanks!
