### ISSUE TITLE
What are the advanges for datasets of size less than 10GB?

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#2749]
I ask because I see this message in the service for an existing dataset:

The size of your dataset is 205 MB. For most Premium capacities, using large dataset storage format can improve performance. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large datasets in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models#enable-large-models)
* Content Source: [powerbi-docs/admin/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro ! How are you? Assigning to the author to investigate and answer. Thanks!

**Comment by asocorro** [comment]
Thank you, Maggie!
