### ISSUE TITLE
Additional DAX editor shortcut keys

### ISSUE THREAD

**Issue by xo9agq46a8k** [MicrosoftDocs/powerbi-docs#2752]
These shortcut keys are missing from 'DAX editor' section of this page as of 20 Jan 2021:

* Deleting a full line of code – (Ctrl + Shift + K)
* Go to the Start and End line of code – (Ctrl + Home ) and (Ctrl + End)
* Select line above or below – (Shift + Up arrow key) / (Shift + Down arrow key)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @xo9agq46a8k -- thanks! Assigning to the author.

**Comment by mihart** [comment]
Hi @xo9agq46a8k , 
Thank you for your suggestion.  We've made the update and set the article to republish in the next few days. 
All the best,
The DOCS team
