### ISSUE TITLE
Clarify the usage rights for Power BI Desktop

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/powerbi-docs#2753]
Can you please add some clarification within the docs that will cover sharing PBIX files. It doesn't appear to be explicitly mentioned and I have heard many different opinions about which usage requires paid licensing.

As I understand it, I can use Power BI Desktop to create PBIX/PBIT files. I can share those PBIX/PBIT files with anyone else with Power BI Desktop for FREE. If I want to publish and share the reports with others through the Power BI Service, that's where the paid licensing comes into play. Is this correct or am I missing something obvious? I get that the wording may be intentionally vague to nudge people toward paid licensing for the service, but I think it should be spelled out for better clarity. Maybe even have some sample scenarios that show acceptable usage.

SCENARIO 1
You create a PBIX report in Power BI Desktop. You publish it to your Workspace on the Power BI Service. - No licensing required

SCENARIO 2
You create a PBIX report in Power BI Desktop and share the PBIX file to other people who open the file in Power BI Desktop - No licensing required.

SCENARIO 3
You create a PBIX report in Power BI Desktop and publish to a shared workspace. - License Required

SCENARIO 4
You are sent a link to a report hosted on the Power BI Service and want to view it. - License Required

Etc....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up for the Power BI service as an individual - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi)
* Content Source: [powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by Garthmj** [comment]
Just to expand on Scenario 2.
You create a PBIX/PBIT report in Power BI Desktop and share the PBIX/PBIT file to other people from your company who open the file in Power BI Desktop - No licensing required.

You create a PBIX/PBIT report in Power BI Desktop and share (give/sell) the PBIX/PBIT file to other people outside of your company who open the file in Power BI Desktop - No licensing required.

You create a PBIX/PBIT report in Power BI Desktop for Power BI Report Server and Publish it to your Power BI Report Server (PBRS) - No licensing required for Power BI Desktop for the designer but PBRS will require license. 

You create a PBIX/PBIT report in Power BI Desktop for Power BI Report Server and give/sell it to other outside of you company. -  No licensing required for Power BI Desktop for the designer but PBRS will require license.

**Comment by maggiesMSFT** [comment]
Hi, @Garthmj -- interesting idea and questions! Passing along to the author for consideration.

**Comment by mihart** [comment]
Hi @AdamGrossTX , 
Thank you for your suggestion.  You sparked an in-depth conversation in our team  :-)  We've made the update you suggested, and set the article to republish next week. 
All the best,
The DOCS team
