### ISSUE TITLE
Missing Details: Cloud-to-Cloud connection from Power BI to Google BigQuery

### ISSUE THREAD

**Issue by venki7744** [MicrosoftDocs/powerbi-docs#2754]
Hi,

The document does mention using cloud-to-cloud connection for connecting from Power BI service to Google BigQuery. However there is no documentation (similar to Power BI Desktop) with detail steps on how this is done. I also could not find any documentation about cloud-to-cloud connection in general (nor do I see this option in Power BI Service).

**Comment by maggiesMSFT** [comment]
Hi, @venki7744 -- are you referring to a specific article? If so, could you include a link so I can direct your comment to an author?

If it's more of a product question, consider asking it in the Power BI ideas page, https://ideas.powerbi.com/ideas/, or the Community page, https://community.powerbi.com/

**Comment by venki7744** [comment]
> Hi, @venki7744 -- are you referring to a specific article? If so, could you include a link so I can direct your comment to an author?
> 
> If it's more of a product question, consider asking it in the Power BI ideas page, https://ideas.powerbi.com/ideas/, or the Community page, https://community.powerbi.com/

Hi @maggieMSFT,

Thanks for the quick reply. I am referring to the specific article; https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-bigquery , section "Considerations and Limitations" there is a mention of cloud-to-cloud connection but no details on how it can be configured.

**Comment by paulinbar** [comment]
Hi @venki7744, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for your question!
