### ISSUE TITLE
There are two types of licenses

### ISSUE THREAD

**Issue by IT-8943765** [MicrosoftDocs/powerbi-docs#2755]
"There are two kinds of Power BI per-user licenses: free Pro and Premium."
No, there are 2 per user and 1 per instance , right?!? PowerBI Free is user based
PowerBI Pro is user based
Power BI Premium is $4995 per instance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec63d236-fde3-47d8-96a5-5d205dd96b59
* Version Independent ID: 0f9cc0dc-e417-ed61-ff2a-7155cdadf8c5
* Content: [Power BI licensing for users in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-licensing-organization)
* Content Source: [powerbi-docs/admin/service-admin-licensing-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-licensing-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @IT-8943765 -- Thanks for asking! There's a new Premium Per User license, too. Here's a link to the FAQ:
https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq
I've added the link to the article, too.
Thanks!
