### ISSUE TITLE
Lack of specificity with regard to the level at which the per-user export API is enforced

### ISSUE THREAD

**Issue by PATRICKwithMSFT** [MicrosoftDocs/powerbi-docs#2756]
With regards to below. This leaves it unclear as to whether or not the single call per 5 minutes limitation is enforced at the tenant level, per-user level, or workspace level. I have since confirmed with the product group that this constraint is placed at the per-user capacity level. Please consider revising to reflect that specificity. 

"7. Will the export API be available for Premium Per User?

This is currently available for paginated reports, and is restricted to a single call once every 5 minutes. Power BI reports are not supported at this time."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User FAQ (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @PATRICKwithMSFT -- thanks for asking! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @PATRICKwithMSFT , 
Thank you for your suggestion.  I checked with the Engineer and this is their response: This is currently available for paginated reports, and is restricted to a single call once every 5 minutes on a per user basis.  Power BI reports are not supported at this time.  The updated article will go live later this week.
All the best,
The DOCS team
