### ISSUE TITLE
GCC High cannot use Purchase Services

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/powerbi-docs#2758]
FYI, this section will not work in GCC High/DoD. 
https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup#add-power-bi-to-a-microsoft-365-government-plan

The Purchase Services option is present, but displays an error because all licenses have to be purchased via a re-seller and placed on their enrollment.

Can a note be added to clarify that 'Government' here may only apply to GCC?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5ba960-512e-7a76-10c9-ac6a33bd6022
* Version Independent ID: 44d12651-bb26-9d9d-42c4-66b3c42e8465
* Content: [Sign Up for Power BI for United States government customers - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup)
* Content Source: [powerbi-docs/admin/service-govus-signup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-govus-signup.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@kerbos - thank you for letting me know about this! Yes, I'm happy to add a clarifying note to the article and will address this very soon.

**Comment by kfollis** [comment]
Thanks for your persistence in getting this fixed! I've updated the article, so will now close this issue.
