### ISSUE TITLE
ArcGIS Workspace Setting

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#2759]
Please also include the workspace setting for ArcGIS visual.  It is rather hidden.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Interacting with an ArcGIS map that has been shared with you - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @Hikmer, thanks for your comment! I am forwarding it on to the doc owner for further consideration.

**Comment by mihart** [comment]
Hi @Hikmer ,
Thank you for your suggestion. I'm not sure I understand the question.  What do you mean by "workspace settings"? If I add an ArcGIS visual to a page in a report, and that report is in a workspace, then the workspace settings are set at the workspace level.  Those  same settings would apply to all report pages in that workspace.  

If I'm not understanding your question, please let me know. 
Take care,
the DOCS team

**Comment by Hikmer** [comment]
There is no mention of the workspace level checkbox that enables/disables
ArcGIS.  Many miss this step and open support tickets.

**Comment by msftrien** [comment]
It's mentioned under the "Manage the use of ArcGIS for Power BI within your organization" section in the doc.

**Comment by Hikmer** [comment]
The workspace setting is not mentioned in this article

[image: image.png]

**Comment by msftrien** [comment]
I'm getting [image: image.png] from your message -- can't actually see the attachment, for some reason? Do you mind trying again?

**Comment by Hikmer** [comment]
Sure, here it is as an attachment

**Comment by msftrien** [comment]
Can you just email me directly rien@microsoft.com 

still can't see it :(
