### ISSUE TITLE
A couple of missing links?

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/powerbi-docs#2765]
Hi - I think the following sentences are meant to include links?

- "Read more about Report Parameters"
- "For more information, see Grouping Pane and Understanding Groups."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba7c7d3-1d26-5f99-53e3-0b85379e4f74
* Version Independent ID: 3fa5bbb4-0e89-0203-a3d4-0df72d6462f8
* Content: [Getting around in Report Design View for paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-design-view)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-report-design-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-report-design-view.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @kasavin, thanks for your observations! I am sending them on to the doc owner for consideration.

**Comment by mihart** [comment]
Hi @kasavin, 
Thank you for your suggestion.  We've made the update and set the article to republish in the next few days. 
All the best,
The DOCS team
