### ISSUE TITLE
Incomplete REST API documentation

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#2767]
The documentation for [Gateway Datasources](https://docs.microsoft.com/en-us/rest/api/power-bi/gateways/getdatasources?WT.mc_id=DP-MVP-5003435&) is incomplete. The required permission to run this API is Gateway Admin, which is not listed in the description of this API. 

The doc states: "Returns a list of datasources from the specified gateway." 
I suggest the following: "Returns a list of datasources from the specified gateway where the user has admin privileges" or something in that order.

This issue applies to nearly all [REST API calls for gateways](https://docs.microsoft.com/en-us/rest/api/power-bi/gateways?WT.mc_id=DP-MVP-5003435&).

**Comment by KesemSharabi** [comment]
Hi @marclelijveld,

Thank you for your comment. I'll look into your suggestion shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @marclelijveld,

Thank you for your feedback. I added a note to the [gateway APIs](https://docs.microsoft.com/rest/api/power-bi/gateways), stating that they require gateway admin permissions.

Thanks again for getting involved and pointing this out,

Kesem
