### ISSUE TITLE
"Power BI Apps Marketplace" link failing

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2769]
The link "Power BI Apps Marketplace" in the first section is failing with the error "Something's wrong with the URL you tried to open, and we can't get to that page. We'll take you to Power BI Home" when clicked.

Its URL: https://app.powerbi.com/getdata/services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d0d7108-2bf9-1b09-a391-440a0c0e8dfb
* Version Independent ID: 0c67568f-5885-41d8-9b19-89b2a9fd4b3c
* Content: [What are Power BI template apps? - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-overview#feedback)
* Content Source: [powerbi-docs/connect-data/service-template-apps-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-template-apps-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @chrisweis . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @chrisweis, Thanks for calling this to my attention. I have fixed the links and they will be live online in about 5 hours. Thanks again!
