### ISSUE TITLE
Attempting to Pass a parameter through a URL in Power BI Report Server (on-site)

### ISSUE THREAD

**Issue by dbvinson4** [MicrosoftDocs/powerbi-docs#277]
DoePerusing this docum and p

Prepared my URL as I thought I should
http://&lt;REDACTED PBIRS SERVER&gt;/Report Folder/Report Name?filter=Spreadsheet Query/Status eq 'Open'

Spreadsheet Query is the name of the table (data source folder)
Status is the name of the field
Status shows up in the Filters window
Status is also a slicer that is visible

Report Executes in PBIRS but returns all values. 
Tried with and without the name of the data source folder, same results.
Data Source Storage Mode is Imp

Is this not possible in PowerBi Report Server?ort

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @dbvinson4 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
