### ISSUE TITLE
Yes, but WHICH permissions allow you to leave comments?

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#2770]
It would be great to know *which* permission levels enable users to leave comments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcadad2e-3b44-6a5e-96d5-ddbd89bdc550
* Version Independent ID: c27e9b88-6286-c601-ea8d-27df7ff93078
* Content: [Add comments to a report in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/add-comments)
* Content Source: [powerbi-docs/report-server/add-comments.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/add-comments.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @nicheplayer. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for the question, @nicheplayer -- updating the article with the info today.
