### ISSUE TITLE
Typo in code sample for categorical data mapping

### ISSUE THREAD

**Issue by heyconor** [MicrosoftDocs/powerbi-docs#2771]
You have a typo in the code sample for the "Categorical Data Mapping" section.

The code sample has text that reads: 

`import DataViewDataViewCategoricalSingle = powerbi.DataViewCategorical;`

I'm pretty sure this should be:

`import DataViewCategorical = powerbi.DataViewCategorical;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 595c371b-cced-07b1-2581-07a96b4c5af0
* Version Independent ID: bebdf7f8-3ea0-cea4-4c9f-9b029020ef9f
* Content: [Understand data view mapping in Power BI visuals in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings)
* Content Source: [powerbi-docs/developer/visuals/dataview-mappings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/dataview-mappings.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @heyconor. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @heyconor, 

Thank you for pointing this out.

@uve - can you confirm that this is correct?

Thanks,

Kesem

**Comment by uve** [comment]
@KesemSharabi, yes, this is a typo, let's fix it

**Comment by KesemSharabi** [comment]
@heyconor,

Thanks for spotting this typo and notifying us. Now it's fixed, see code sample in [Example 6](https://docs.microsoft.com/power-bi/developer/visuals/dataview-mappings#example-6).

Kesem
