### ISSUE TITLE
There should be a document listing "SSAS live connection doesn't support translation in Power BI Report Server" or it should be included in this document as it is listed for Power BI Desktop and Power BI Service 

### ISSUE THREAD

**Issue by BuntyMS** [MicrosoftDocs/powerbi-docs#2773]
Its not listed in Microsoft Documents that SSAS live connection doesn't support translation in Power Bi Report Server, although it is listed for Power BI Desktop/Service but not for Power BI Report Server. Please include this information in official Microsoft Documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa43934-b1b5-2227-9f9e-cfce1801b659
* Version Independent ID: 0d169b19-7c1c-b37d-3915-b8c55da6f0ff
* Content: [Manage your data source - Analysis Services - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-enterprise-manage-ssas#limitations-of-analysis-services-live-connections)
* Content Source: [powerbi-docs/connect-data/service-gateway-enterprise-manage-ssas.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-enterprise-manage-ssas.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @BuntyMS.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @BuntyMS -- In investigating your question, I was overlooking one crucial element: Power BI Report Server is on-premises, so it doesn't use gateways at all. I hope that clears up your question. Thanks!
cc:
@davidiseminger 
@kfollis 
@arthiriyer 
@mibruhje
