### ISSUE TITLE
Azure Cost Management that you have IT Admin privileges - Roles

### ISSUE THREAD

**Issue by Dastreum** [MicrosoftDocs/powerbi-docs#2774]
Hi Team,

After checking it looks like the roles  "IT Admin privileges " does not exists.

Here are the role to access ACM data (with an EA agreement)

https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/understand-ea-roles#usage-and-costs-access-by-role

Regards,

Anthony Joret
ASMS - SE
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc4bd0c-b3d7-3ace-ca76-696e9c278d4b
* Version Independent ID: 3c0f58ee-b290-559a-cb6d-b7afe1996760
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator#sustainability-calculator-release-preview-december-2020)
* Content Source: [powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @andreabichsel
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Dastreum.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
This article has been retired.
