### ISSUE TITLE
Code Broken in Multiple place

### ISSUE THREAD

**Issue by blabz2007** [MicrosoftDocs/powerbi-docs#2775]
[Enter feedback here]
Arguments passed into AcquireTokenAsync don't work in any version of Microsoft.IndentityModel.Clients.ActiveDirectory.

The call to GetToken() would require a ".Result" because the method returns a Task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token  in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @blabz2007 -- thanks for your feedback! Assigning to the author for further investigation.

**Comment by KesemSharabi** [comment]
Hi @blabz2007,

We're aware of the fact that the code in the automation tutorials needs to be replaced. Unfortunately, it'll take us a while to get to this task.

Apologies in advance for the inconvenience,

Kesem
