### ISSUE TITLE
Project type

### ISSUE THREAD

**Issue by Mcclellange** [MicrosoftDocs/powerbi-docs#2777]
I see on the dashboard there is an "enterprise project", we have some people that use enterprise projects, we also have some that use project online projects. Additionally, we are looking at business case to decommission Jira for Azure boards as well as Daptiv. Is there a way to pull in to the PBIX the data from all 3 type of projects, I'm hoping there is due to the ability to get them all on a roadmap in project. Those instructions would be amazing to have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecdd014-b4d0-e97b-78a6-ef22e71d05f8
* Version Independent ID: 0bea8666-c1e3-74ec-d805-c9925baa9999
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-project-online)
* Content Source: [powerbi-docs/connect-data/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-project-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @Mcclellange -- interesting question! Assigning to the author for further investigation.

**Comment by Mcclellange** [comment]
I found the github repo that I would recommend linking to this article.
[https://github.com/OfficeDev/Project-Power-BI-Templates](https://github.com/OfficeDev/Project-Power-BI-Templates)
This covers the 2 type of project types (online and for the web), the outstanding issue at least for us would be the Azure boards.

**Comment by paulinbar** [comment]
Hi @Mcclellange, did you ever figure out the issue with the Azure boards?

**Comment by paulinbar** [comment]
Hi @Mcclellange, I am VERY sorry for the long delay. I suggest if you still have your question, you the Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com). In the meantime I am closing this issue for now. Thanks!
