### ISSUE TITLE
Is Dataverse connection type officially supported now? 

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerbi-docs#2778]
With the CDS(Preview) connection type having been renamed to "Dataverse" in the report builder, is this a fully supported data source now? Wondering if you are planning on adding it to the list of supported datasources on this page.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a5444a-ce6c-9a0c-3e84-832e67b75d47
* Version Independent ID: df2623ba-2917-faf6-0077-e9d182a9e96c
* Content: [Supported data sources for Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-data-sources)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-data-sources.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ashlega -- great timing! We just added Dataverse to this article. The change will be live later today! Here's what it says:


Data Source | Authentication | Notes
-- | -- | --
Dataverse | SSO, OAuth2 | Can't use a gateway as multi-factor authentication (MFA) isn't supported.
