### ISSUE TITLE
Needs to be updated for new workspace experience

### ISSUE THREAD

**Issue by zmottie** [MicrosoftDocs/powerbi-docs#2780]
This document is no longer valid since the new Workspaces experiences changes how Microsoft 365 Groups work with Workspaces. Could use an update for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08345191-caf2-6c56-cf95-ecd009dae438
* Version Independent ID: 447ea5e5-d102-1cac-8cbf-1b1136dfb24c
* Content: [Connect to files in OneDrive for a Power BI workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business)
* Content Source: [powerbi-docs/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Good point, @zmottie ! I'm updating the title and first paragraph to make clear this only applies to the classic, not the new workspaces. Thanks!
