### ISSUE TITLE
really "by design" permanent Limitation or work in progress?

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/powerbi-docs#2781]
regarding "However, once the authentication type for a given data source is changed to OAuth2, it can't revert back to use SSO. In addition, this change applies to all the reports that use that data source across all workspaces for a given tenant. Row-level security in paginated reports won't work unless users choose SSO for authentication type."

..>Is this a temporary limitation? Or is there really no work in progress to allow in future switching back from OUTH2 to SSO? In our environment we "breaked" a paginated report by switching accidentally to OUTH2 and i CAN'T BELIEVE that there is no way back to get the report running a again with SSO?? FYI: Lot of users have the same issue: https://community.powerbi.com/t5/Issues/Revert-back-to-SSO-from-oAuth2-on-Paginated-Report-Data-Source/idi-p/1557546

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a5444a-ce6c-9a0c-3e84-832e67b75d47
* Version Independent ID: df2623ba-2917-faf6-0077-e9d182a9e96c
* Content: [Supported data sources for Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-data-sources)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-data-sources.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @JJDE -- thanks for your question! I'll investigate and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @JJDE -- sorry for the delay! At this time this is the limitation, though a fix is planned. You can file a support ticket at https://powerbi.microsoft.com/en-us/support/ and get help there.
