### ISSUE TITLE
How to setup SSO of Power BI Report Service for SQL Server Database Default Instance?

### ISSUE THREAD

**Issue by PancoCheong** [MicrosoftDocs/powerbi-docs#2782]
How to setup SSO of Power BI Report Service for SQL Server Database Default Instance?

**Comment by maggiesMSFT** [comment]
Hi, @PancoCheong -- does this article help? 
https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos
If not, can you be more specific? I'm not sure if you're referring to "Power BI Report Server" the on-premises report server, or "the Power BI service" app.powerbi.com.
Thanks!

**Comment by mihart** [comment]
Hi @PancoCheong ,
I see that there has been no response on this GitIssue for a couple of months, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
