### ISSUE TITLE
Q&A Visualization

### ISSUE THREAD

**Issue by spontello** [MicrosoftDocs/powerbi-docs#2783]
I would like to be able to visualize the result set using a custom shape map.  Example use case is presenting demographic data to a local population using Q&A and a custom shape map to plot the results.

**Comment by maggiesMSFT** [comment]
Hi, @spontello -- have you checked out the articles about Q&A? Here are a couple to get started:
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-q-and-a
and
https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-tutorial-q-and-a

**Comment by mihart** [comment]
Hi @spontello ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
