### ISSUE TITLE
Cross-highlighting needs additional explanation

### ISSUE THREAD

**Issue by Scott123456** [MicrosoftDocs/powerbi-docs#2784]
I do not see the "cross-highlighting" interaction option on any my visuals. Add description of how/when this option is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions)
* Content Source: [powerbi-docs/create-reports/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Scott123456 -- thanks for asking! First, can you tell me, are you creating a report, or interacting with a report someone else created?

**Comment by Scott123456** [comment]
Both. It seems it is just not available on some chart types. For example, I can make a scatter chart cross-highlight interactively with a bar chart; but I cannot make a bar chart cross-highlight interactively with a scatter chart. It is not clear in the documentation that this cross-highlighting feature is unavailable in many standard visuals.

**Comment by maggiesMSFT** [comment]
@Scott123456 -- got it. Agreed! I'm adding more explanation to this article:
https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-reports-filters-and-highlighting#ad-hoc-highlighting
Update should be live this afternoon.
