### ISSUE TITLE
these instructions seem to be incomplete

### ISSUE THREAD

**Issue by degrover-cn** [MicrosoftDocs/powerbi-docs#2785]
pbiviz version 3.1.15 - latest
API version 2.6 

followed instructions in the document but get

Property 'applyJsonFilter' does not exist on type 'IVisualHost'.

Property 'FilterAction' does not exist on type 'typeof import("c:/Users/russell/source/Workspaces/FloridaHealthFinder/PBI/fhfFilterNew/node_modules/powerbi-models/dist/models")'.

Please advise how to properly import needed resources in this scenario

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c2058e5-5d38-f0ce-1065-594ccf9a089f
* Version Independent ID: 78516875-71b8-de4e-7052-607880efb1ff
* Content: [The Visual Filters API in Power BI visuals in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/filter-api#the-basic-filter-api)
* Content Source: [powerbi-docs/developer/visuals/filter-api.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/filter-api.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @degrover-cn -- thanks for asking! Assigning to the author for further investigation.

**Comment by KesemSharabi** [comment]
Hi @degrover-cn,

Thank you for your comment.

@uve - can you please advise what imports are missing?

Thanks,

Kesem

**Comment by uve** [comment]
Hello @degrover-cn,
 You can use the sample from this code:
https://github.com/microsoft/powerbi-visuals-timeline/blob/master/src/timeLine.ts#L935
