### ISSUE TITLE
Transform Data

### ISSUE THREAD

**Issue by RyanCalovich** [MicrosoftDocs/powerbi-docs#2786]
[Enter feedback here]
Under the "Transform and clean data, create a model" header, is the following:
"To start Power Query Editor:

Select Edit Queries > Edit Queries from the Home ribbon."

However, this doesn't work for me. To get to the Power Query Editor I actually just click on "Queries > Transform Data" from the Home ribbon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-what-is-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @RyanCalovich -- you are so right! I've updated it. Change will be live this afternoon.
