### ISSUE TITLE
Example for moving Workspaces via API or link

### ISSUE THREAD

**Issue by sethsanuMSFT** [MicrosoftDocs/powerbi-docs#2787]
Need to have an example of how to programmatically move workspaces from Gen 1 to Gen 2. as indicated in the last paragraph

**Comment by maggiesMSFT** [comment]
Hi, @sethsanuMSFT -- Could you specify which article you're referring to? For some reason that info didn't come through. Thanks!

**Comment by mihart** [comment]
No reply. Closing.
