### ISSUE TITLE
Report builder report using dataset from another workspace doesn't seem to work

### ISSUE THREAD

**Issue by ShawnPOWER** [MicrosoftDocs/powerbi-docs#2788]
Could this document be updated to describe if a dataset in another workspace works properly with a Power BI report builder report or not? Through my testing today, here is an example. I assigned read permission to a user on a dataset inside of a modern workspace which is different than the modern workspace the report builder report (RDL) is located (the user was granted app permissions, no permissions directly on the report itself) does not seem to function. However, a Power BI Desktop report (PBIX) will function properly it seems with this same approach described above. It is also worth mentioning that both workspaces I described here are premium capacity and the user had no Power BI Pro license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ShawnPOWER -- could you check out this article and see if it helps? 
"Create a paginated report based on a Power BI shared dataset"
https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets
Thanks!

**Comment by ShawnPOWER** [comment]
Hi @maggiesMSFT, I appreciate the response and information. Absolutely, I gave it a go and unfortunately, I ended up at the same result as I described previously. Thank you!

**Comment by maggiesMSFT** [comment]
Hi, @ShawnPOWER -- just so you know I haven't forgotten you. I'm still checking. You may need to enter a support request, https://powerbi.microsoft.com/en-us/support/
Thanks!

**Comment by ShawnPOWER** [comment]
Hi @maggiesMSFT, I appreciate the update and you looking into it for me. I will get a support request in also, thank you!

**Comment by maggiesMSFT** [comment]
Hi, @ShawnPOWER -- 

Rereading your original comment – if you only assigned Read permission to a user, they shouldn’t be able to build a paginated report OR a PBIX report. However, you say they can do the one, build a PBIX report --- but not the other, build the paginated report. 

“Through my testing today, here is an example. I assigned read permission to a user on a dataset inside of a modern workspace which is different than the modern workspace the report builder report (RDL) is located (the user was granted app permissions, no permissions directly on the report itself) does not seem to function. However, a Power BI Desktop report (PBIX) will function properly it seems with this same approach described above.”

Could  you check and see what permission you assigned them? If they have Build permission, they should indeed be able to create a paginated report based on that dataset.

**Comment by maggiesMSFT** [comment]
Hi, @ShawnPOWER -- I've confirmed that if the user has Build permissions on a dataset, they should be able to create either a PBIX report or a paginated report.

**Comment by ShawnPOWER** [comment]
Hi @maggiesMSFT, apologies for the confusion with my original comment. My original comment is actually around a user viewing a published Power BI Report Builder (RDL) report which contains a dataset which is in another workspace. Where the user has read access on the dataset and app permissions on the report itself (no direct read permissions). This is what I found to not function through my testing. However, a Power BI Desktop (PBIX) report which contains a dataset which is in another workspace will function properly. That has the same permission configuration for the user will function. I am not interested currently in the user performing a build on any reports at this time.

The scenario I am investigating which lead me to this document is to store many datasets in a single workspace (I would remove the reports, so it would just be the datasets). Then store several paginated reports in many different workspaces which do not contain any of the datasets. The workspaces with the paginated reports will also have an app the users will use, this will provide users read access to the reports in the workspace (no build permissions or anything else needed). Then I will provide read access to the datasets which are stored in a workspace which is not any of the paginated workspaces. Side note, I wish I could assign at the app level read permissions in the dataset only workspace but it doesn't look like that is possible when the reports are removed from it.

**Comment by maggiesMSFT** [comment]
Hi, @ShawnPOWER -- sorry for the delay. I'm told that yes, that should work, and if it's not, it's a bug. Can you file a support ticket at https://powerbi.microsoft.com/en-us/support/ so they can help?

**Comment by ShawnPOWER** [comment]
Hi @maggiesMSFT, no problem and will do. I appreciate it!
