### ISSUE TITLE
Doesn't explain non-gateway scenario, doesn't explain how to add schedule times

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#279]
The **Gateway connection** and **Data source credentials** sections should explain the scenario where the dataset does not require a gateway e.g. reading from SharePoint Online or OneDrive. Currently it's implied that some kind of gateway is mandatory.

Also the **Schedule refresh** section does not describe the steps need to add refresh times and the limitation of 8 times per day for Free & Pro workspaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-scheduled-refresh)
* Content Source: [powerbi-docs/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-scheduled-refresh.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Mike-Honey . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by arthiriyer** [comment]
@Mike-Honey - Thanks MIke for the feedback. I think for the first one, We already mention that we require gateway only to connect to On-premises sources.
Agree about the second feedback.
@mblythe

**Comment by AzoricoTC** [comment]
I second this issue. Still unclear whether a source such as Azure PostgresDB requires a gateway or not and, if it does not, how to configure it.

**Comment by mgblythe** [comment]
@arthiriyer - will address this as part of gateway docs update

**Comment by mgblythe** [comment]
We now have a centralized data source article - https://docs.microsoft.com/en-us/power-bi/power-bi-data-sources. Let us know of any additional feedback there. Thanks!
