### ISSUE TITLE
Typo in "Licenses and subscriptions for business users"

### ISSUE THREAD

**Issue by SteveHills** [MicrosoftDocs/powerbi-docs#2790]
It looks like you have a typo in the Licenses section
"Each user of the Power BI service has either a free license, a Pro license, of a Premium per-user* license." I presume this is meant to say **or a Premium per-user\* license** rather then **of...** - but if not, then further clarification of the sentence's meaning would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696d95c8-9c63-06ad-3f7a-7d7e83519ffd
* Version Independent ID: e92490bd-7b7f-2fdc-823a-46d81d39dc55
* Content: [Types of licenses for Power BI business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-license?WT.mc_id=email)
* Content Source: [powerbi-docs/consumer/end-user-license.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-license.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
You're right! Thanks for pointing that out, and it's a quick fix. I'll get that fixed and updated - should be in the live doc set in a day or so. Thanks again @SteveHills.
