### ISSUE TITLE
Explore and monitor key repository in Power BI by connecting to your GitHub data. Get a Power BI dashboard and reports with insights.

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/powerbi-docs#2792]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by matuhinal** [comment]
https://github.com/MicrosoftDocs/powerbi-docs/issues/2792#issue-798192306

**Comment by davidiseminger** [comment]
Thanks for your submission, @matuhinal - could you provide a bit more context about what issue you've found, here in the Comment area?

**Comment by maggiesMSFT** [comment]
Hi, @matuhinal -- closing this issue. Please reopen or create another issue, to provide more context, so we can understand the issue.
Thanks!

**Comment by matuhinal** [comment]
Good day!
Please no closing.
Lyudmila
________________________________
От: Maggie Sparkman <notifications@github.com>
Отправлено: 12 февраля 2021 г. 8:35
Кому: MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Копия: Matuhinal <ayuditgarantdigital@outlook.com>; Mention <mention@noreply.github.com>
Тема: Re: [MicrosoftDocs/powerbi-docs] Explore and monitor key repository in Power BI by connecting to your GitHub data. Get a Power BI dashboard and reports with insights. (#2792)


Hi, @matuhinal<https://github.com/matuhinal> -- closing this issue. Please reopen or create another issue, to provide more context, so we can understand the issue.
Thanks!
