### ISSUE TITLE
Misleading/inaccurate terminology

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#2797]
The use of OneDrive to describe workspace locations is totally misleading. These locations are not created in individual users onedrive for business sites, they are created in SharePoint Online sites. Please correct this terminology so that people are not confused. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-the-new-workspaces#feedback)
* Content Source: [powerbi-docs/collaborate-share/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @DeanGross . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @DeanGross -- thanks for your feedback. The docs do reflect the product... I'm checking with the product group to see how we can make it clearer. 
Thanks!
