### ISSUE TITLE
Typo on the package seaborn

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#2798]
There is a typo (maybe a couple of spaces) into the name of the package seaborn. I see "s  eaborn".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db4f2779-18a0-100c-dc5f-ac0f77f05d19
* Version Independent ID: e6654e84-bba6-8280-645a-5e56e999276e
* Content: [Learn which Python packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-python-packages-support)
* Content Source: [powerbi-docs/connect-data/service-python-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-python-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment]
Thanks for your comment, @lucazav . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @lucazav ! Fixed it. Update will be live tomorrow afternoon.
