### ISSUE TITLE
TOPN Function in DAX Query

### ISSUE THREAD

**Issue by AjKolla** [MicrosoftDocs/powerbi-docs#2801]
[Enter feedback here]
[https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets#feedback](url)
Step 5 Note: If your query includes the TOPN function, delete it from your query.
Right now I am not able to get al the data from the dataset it is limiting to 501 records due to the TOPN function. When I delete the TOPN function my query is not being executed, I get an error like this 
TITLE: Power BI Report Builder
------------------------------

Query preparation failed.

------------------------------
ADDITIONAL INFORMATION:

Query (117, 16) The syntax for '<pii>,</pii>' is incorrect. (<pii>// DAX Query
DEFINE
  VAR __DS0Core = 
    SELECTCOLUMNS(
      KEEPFILTERS(
        FILTER(
          KEEPFILTERS(
            SUMMARIZECOLUMNS(
              'Query1'[Invoice_Complete],
              'Query1'[Invoiced_Quantity],
              'Query1'[Staples_order_no],
              'Query1'[Staples_return_order_no],
              'Query1'[return_status_description],
              'Query1'[customer_name],
              'Query1'[External_Document_No],
              'Query1'[Our_Item_No],
              'Query1'[EXTERNAL_ITEM_NO],
              'Query1'[Return_Node],
              'Query1'[Create_date],
              'Query1'[return_create_date],
              'Query1'[return_date_plus18days],
              'Query1'[Open_days],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo],
              'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day],
              "CountRowsQuery1", CALCULATE(COUNTROWS('Query1'))
            )
          ),
          OR(
            OR(
              OR(
                OR(
                  OR(
                    OR(
                      OR(
                        OR(
                          OR(
                            OR(
                              OR(
                                OR(
                                  OR(
                                    OR(
                                      OR(
                                        OR(
                                          OR(
                                            OR(
                                              OR(
                                                NOT(ISBLANK('Query1'[Invoice_Complete])),
                                                NOT(ISBLANK('Query1'[Invoiced_Quantity]))
                                              ),
                                              NOT(ISBLANK('Query1'[Staples_order_no]))
                                            ),
                                            NOT(ISBLANK('Query1'[Staples_return_order_no]))
                                          ),
                                          NOT(ISBLANK('Query1'[return_status_description]))
                                        ),
                                        NOT(ISBLANK('Query1'[customer_name]))
                                      ),
                                      NOT(ISBLANK('Query1'[External_Document_No]))
                                    ),
                                    NOT(ISBLANK('Query1'[Our_Item_No]))
                                  ),
                                  NOT(ISBLANK('Query1'[EXTERNAL_ITEM_NO]))
                                ),
                                NOT(ISBLANK('Query1'[Return_Node]))
                              ),
                              NOT(ISBLANK('Query1'[Create_date]))
                            ),
                            NOT(ISBLANK('Query1'[return_create_date]))
                          ),
                          NOT(ISBLANK('Query1'[return_date_plus18days]))
                        ),
                        NOT(ISBLANK('Query1'[Open_days]))
                      ),
                      NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year]))
                    ),
                    NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter]))
                  ),
                  NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo]))
                ),
                NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month]))
              ),
              NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo]))
            ),
            NOT(ISBLANK('LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day]))
          )
        )
      ),
      "'Query1'[Invoice_Complete]", 'Query1'[Invoice_Complete],
      "'Query1'[Invoiced_Quantity]", 'Query1'[Invoiced_Quantity],
      "'Query1'[Staples_order_no]", 'Query1'[Staples_order_no],
      "'Query1'[Staples_return_order_no]", 'Query1'[Staples_return_order_no],
      "'Query1'[return_status_description]", 'Query1'[return_status_description],
      "'Query1'[customer_name]", 'Query1'[customer_name],
      "'Query1'[External_Document_No]", 'Query1'[External_Document_No],
      "'Query1'[Our_Item_No]", 'Query1'[Our_Item_No],
      "'Query1'[EXTERNAL_ITEM_NO]", 'Query1'[EXTERNAL_ITEM_NO],
      "'Query1'[Return_Node]", 'Query1'[Return_Node],
      "'Query1'[Create_date]", 'Query1'[Create_date],
      "'Query1'[return_create_date]", 'Query1'[return_create_date],
      "'Query1'[return_date_plus18days]", 'Query1'[return_date_plus18days],
      "'Query1'[Open_days]", 'Query1'[Open_days],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo],
      "'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day]", 'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day]
    )

  VAR __DS0PrimaryWindowed = 
   // TOPN(
    //  501,
      __DS0Core,
      'Query1'[customer_name],
      1,
      'Query1'[Invoice_Complete],
      1,
      'Query1'[Invoiced_Quantity],
      1,
      'Query1'[Staples_order_no],
      1,
      'Query1'[Staples_return_order_no],
      1,
      'Query1'[return_status_description],
      1,
      'Query1'[External_Document_No],
      1,
      'Query1'[Our_Item_No],
      1,
      'Query1'[EXTERNAL_ITEM_NO],
      1,
      'Query1'[Return_Node],
      1,
      'Query1'[Create_date],
      1,
      'Query1'[return_create_date],
      1,
      'Query1'[return_date_plus18days],
      1,
      'Query1'[Open_days],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month],
      1,
      'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day],
      1
    )

EVALUATE
  __DS0PrimaryWindowed

ORDER BY
  'Query1'[customer_name],
  'Query1'[Invoice_Complete],
  'Query1'[Invoiced_Quantity],
  'Query1'[Staples_order_no],
  'Query1'[Staples_return_order_no],
  'Query1'[return_status_description],
  'Query1'[External_Document_No],
  'Query1'[Our_Item_No],
  'Query1'[EXTERNAL_ITEM_NO],
  'Query1'[Return_Node],
  'Query1'[Create_date],
  'Query1'[return_create_date],
  'Query1'[return_date_plus18days],
  'Query1'[Open_days],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Year],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[QuarterNo],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Quarter],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[MonthNo],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Month],
  'LocalDateTable_fd4ab7aa-4e0a-4c2f-baeb-1a0197162a03'[Day]
</pii>). (Microsoft Analysis Services)

------------------------------
BUTTONS:

OK
------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0cd82d-e7c4-4b5b-700f-1152a2a6bf38
* Version Independent ID: b2d4aeb5-1a98-ad43-4cf6-9539d9073600
* Content: [Create a paginated report with a Power BI shared dataset - Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets#feedback)
* Content Source: [powerbi-docs/paginated-reports/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @AjKolla . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.  In case it is not a support or product question, I've assigned this to the author of the referenced document.

**Comment by AjKolla** [comment]
@mihart Yes it is a community or support request question. For better documentation. it may be a good idea to mention how the specific TOPN function can be deleted without resulting in an error with a sample video or a snapshot. It will be really helpful for people new to DAX.

**Comment by maggiesMSFT** [comment]
Hi, @AjKolla -- thanks for asking. I'll check and get back to you. Ironically, I added that note at the request of another customer. So let me check and see what the best advice is. Thanks!

**Comment by paulinbar** [comment]
Hi @AjKolla, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for your suggestion!
