### ISSUE TITLE
Datasets Hub in Navigation Pane - Refresh Functionality

### ISSUE THREAD

**Issue by Ian-Mac-Aus** [MicrosoftDocs/powerbi-docs#2802]
It would be very useful to be able to manage dataset refreshes directly from this page rather than having to click through.

**Comment by mihart** [comment]
Thanks for your comment, @Ian-Mac-Aus . I'm not sure if this is documentation feedback or a product question. Please reply with more detail, such as the URL of the page you were reading.

**Comment by Ian-Mac-Aus** [comment]
Hi Michele,

It's a product suggestion rather than doc feedback so does that belong in the Ideas area rather than Github?

This is the page URL: https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-hub



Ian Macmillan|Business Intelligence Lead
Quality
T: (03) 9611 9200|F: (03) 9611 9222|E: Ian.Macmillan@vincentcare.org.au
Gerald Ward House |43 Prospect Street Box Hill 3128
Mon - Thu
I respectfully acknowledge the Traditional Owners of the land on which we meet and work, and pay respect to 
​Elders, past, present and future.
VincentCare values diversity and is committed to providing housing and support services that are fully inclusive.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Ian-Mac-Aus.

You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
