### ISSUE TITLE
Hyperlink is missing 

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#2803]
In the line " For more information on using date columns versus date hierarchies, visit this article" when you click on this it does not takes you anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b13312-84ac-72b4-483f-5d8169ecf1e0
* Version Independent ID: f648e18b-55f9-9167-a6f1-98be8180bac1
* Content: [Using DirectQuery for datasets and Azure Analysis Services (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services?source=docs#considerations-and-limitations)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @prvillal . This issue has been assigned to the doc author for review.

**Comment by prvillal** [comment]
Thank you

Priscila Villalobos B

Power BI | Support Escalation Engineer
CSSBI
Customer Service & Support
Office:   506-4116-0767
prvillal@microsoft.com<mailto:prvillal@microsoft.com>

[cid:image001.png@01D6FB16.B019EE30]
[MSFT_logo_Gray DE sized SIG1.png]

**Comment by mihart** [comment]
Hi @prvillal,
Thank you for your suggestion.  The link has been added.
