### ISSUE TITLE
Missing: Need documentation on how to move Gen 1 to Gen 2.

### ISSUE THREAD

**Issue by sethsanuMSFT** [MicrosoftDocs/powerbi-docs#2804]
Critical: Need example code or further documentation on how to move Gen 1 to Gen 2. The document tells you what to do, that it is important, but not HOW to do it. Perhaps the code exists on Github or available from the product group?

"Once you create a capacity resource, you cannot switch generations. If you want to change your Power BI Embedded generation, you can create another resource using a different generation, and reassign your workspaces to it. You can also automate this process using Azure Resource Manager APIs."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02968b97-6e0b-06d0-001e-d22ace5ce8a9
* Version Independent ID: b3fc0d8e-79fd-41ae-8d93-0acffc820970
* Content: [Create Power BI Embedded capacity in the Azure portal for your Power BI embedded analytics embedded BI solution - Power BI](https://review.docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-create-capacity?branch=pr-en-us-5057&tabs=portal)
* Content Source: [powerbi-docs/developer/embedded/azure-pbie-create-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/azure-pbie-create-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @sethsanuMSFT . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @sethsanuMSFT,

I'm not sure what you're after. We don't have code examples documenting how to move from Gen1 to Gen2. You'll have to look into the [Azure Resource Manager](https://docs.microsoft.com/rest/api/resources/) REST APIs to do this.

Perhaps the [Embedded Gen2](https://docs.microsoft.com/power-bi/developer/embedded/azure-pbie-create-capacity?tabs=ARM-template#embedded-gen2-preview) ARM template will also help.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @sethsanuMSFT,

You can also try using these APIs:
* [Capacities - Get Capacities](https://docs.microsoft.com/rest/api/power-bi/capacities/getcapacities) - to obtain the capacity ID, which is the input of the `AssignToCapacity` API.
* [Capacities - Groups AssignToCapacity](https://docs.microsoft.com/rest/api/power-bi/capacities/groups_assigntocapacity)

Hope this helps,

Kesem
