### ISSUE TITLE
güncel bilgilere ulaşmak gibi

### ISSUE THREAD

**Issue by mekmin100** [MicrosoftDocs/powerbi-docs#2808]
evet program ilişkilendirmeleri yaparken veri tabanında bazı programlar yeni çalışmalar yapıyo ve bu çalışmalar bazen sorun bazende dez avantaş saglıyo  ve ben bunun github tabanında olmasını istemiyom yada bu konu hakkındada tartışma çekme çatalama code ayırma olabilir diyom #

**Comment by kfollis** [comment]
@mekmin100 - Ben geribildirim hakkında ne olduğunu anlamak için bir makale bağlantısı gerekir. Konuyu tartışmak için https://community.powerbi.com deneyebilirsiniz. Ayrıca en güncel bilgiler için ürün blogunu takip edebilirsiniz. https://powerbi.microsoft.com/blog/
