### ISSUE TITLE
Add a limitation 

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#2811]
Under section Known limitations in Premium Gen2 https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#known-limitations-in-premium-gen2 Please add that if customer is using Import Mode with BYOK in a dataset this will fail as its not yet supported

Thanks 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @prvillal - thank you for the feedback! I am assigning this issue to the article author to verify the limitation and make an update to the article.

**Comment by prvillal** [comment]
Thank you

Priscila Villalobos B

Power BI | Support Escalation Engineer
CSSBI
Customer Service & Support
Office:   506-4116-0767
prvillal@microsoft.com<mailto:prvillal@microsoft.com>

[cid:image001.png@01D6FB16.B3F77680]
[MSFT_logo_Gray DE sized SIG1.png]

**Comment by mihart** [comment]
Hi @prvillal ,
Thank you for this information.  I've added it to the documentation.
