### ISSUE TITLE
Group Types supported for RLS

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#2812]
This page should describe the different types of groups that are or are not supported for RLS.  (There are four different types of groups).
This is surely a common question and yet inexplicably not answered in this documentation.
In the end I found an old answer in the following video (which explains the four different types):
https://www.youtube.com/watch?v=oxYQ2GGefrs
I am not sure if that answer is correct today.
Seems unbelieve that O365 groups are not supported for RLS!
Irrespective of that, this page should make it clear which of the four types of groups are supported and which types aren't supported for RLS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @cbailiss -- thanks for your suggestion! Passing it along to the author for consideration.

**Comment by mihart** [comment]
Hi @cbailiss , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
