### ISSUE TITLE
Is there an Upgrade Path to Gen2

### ISSUE THREAD

**Issue by brianrreed** [MicrosoftDocs/powerbi-docs#2814]
Is there an upgrade path for Gen2? If not should that be listed under limitations on this page? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 441d62b8-a64d-7259-0b53-1754e0281a0b
* Version Independent ID: 00dbd257-d104-953c-a9eb-d929b3dc37ff
* Content: [Power BI Embedded Generation 2 explained as part of Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2)
* Content Source: [powerbi-docs/developer/embedded/power-bi-embedded-generation-2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/power-bi-embedded-generation-2.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @brianrreed -- thanks for your suggestion! Passing it along to the author for consideration.

**Comment by KesemSharabi** [comment]
Hi @brianrreed,

I'm not sure what you mean by 'upgrade path' - can you please explain?

If you want to move from Gen1 to Gen2, perhaps the information in [Create Power BI Embedded capacity in the Azure portal](https://docs.microsoft.com/power-bi/developer/embedded/azure-pbie-create-capacity?tabs=portal) will assist you.

Thanks,

Kesem
