### ISSUE TITLE
Embedding for Power BI Report Server

### ISSUE THREAD

**Issue by jtjones0304** [MicrosoftDocs/powerbi-docs#2816]
Does this approach also work in Power BI Report Server?

**Comment by KesemSharabi** [comment]
Hi @jtjones0304,

Can you please let us know which document you're referring to?

Thanks,

Kesem

**Comment by mihart** [comment]
Hi @jtjones0304 ,
I see that this Git issue is a bit old, and we haven't heard back from you -- so I'm going to close it.  I hope that you were able to get your questions answered. If not, please contact us again or submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
