### ISSUE TITLE
Reducing repetition, making the sentenses more consistent and more oriented to the users

### ISSUE THREAD

**Issue by Yuliadocs** [MicrosoftDocs/powerbi-docs#2817]
Would suggest to simply these two (2) sentences by reducing repetition, making them more consistent and more oriented to the users:

With Power BI Desktop, you can build advanced queries, models, and reports that visualize data. You can also build data models, create reports, and share your work by publishing to the Power BI service. Power BI Desktop is free to download.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Yuliadocs.

I've assigned this issue to the doc author for review.
