### ISSUE TITLE
To make more concise and consistent

### ISSUE THREAD

**Issue by Yuliadocs** [MicrosoftDocs/powerbi-docs#2818]
To make more concise and consistent:

To get Power BI Desktop, you can use one of the two approaches (instead of "ways" in order to be consistent with the paragraph below) (no need for "which are described in the following sections" as it will be mentioned in the next paragraph:

    Install as an app from the Microsoft Store.
    Download directly, as an executable you download and install on your computer.

Either of the two approaches gets the latest version of Power BI Desktop onto your computer; however, it is worth to note the differences which are described in the following sections below.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Yuliadocs.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Thank you @Yuliadocs.  The article has been updated.
