### ISSUE TITLE
Editing suggestion for Important

### ISSUE THREAD

**Issue by Yuliadocs** [MicrosoftDocs/powerbi-docs#2819]
Power BI Desktop is updated incorporating new features, based on the customer feedback ("the' is missing) and released on a monthly basis. Only the latest (instead of "most recent") version of Power BI Desktop is supported (put a dot instead of the semi-colon). You (instead of "customers who" because "you" is used the next sentences) will be asked to upgrade the application (need to specify what to upgrade) to the latest version when contacting the Support (to add "the" and Support with capital S) for Power BI Desktop. You can get the latest version of Power BI Desktop from the Windows Store (the comma is not necessary here) or as a single executable containing all supported languages that you download and install on your computer.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Thank you @Yuliadocs. The article has been updated.
