### ISSUE TITLE
Typo in the Special characters in URL filters section

### ISSUE THREAD

**Issue by jhauff77060** [MicrosoftDocs/powerbi-docs#282]
I believe that there is a typo in the Special characters in URL filters section. The Unicode for left bracket "[" shows ..005B while the Coding for Power BI shows ..0058. Could you please double-check this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#special-characters-in-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Thanks so much for catching that, @jhauff77060! You're right. It's wrong. I'll fix it.

**Comment by maggiesMSFT** [comment]
Fixed -- fix will be live tomorrow afternoon. Thanks again, @jhauff77060
