### ISSUE TITLE
Instructions for Install as an app from the Microsoft Store

### ISSUE THREAD

**Issue by Yuliadocs** [MicrosoftDocs/powerbi-docs#2820]
1. To open the Power BI Desktop page of the Microsoft Store, use one of the following options:

- Open a browser and go directly to the Power BI Desktop page of the Microsoft Store.
- In the Power BI service screen, in the upper right-hand side corner (it is easier to find the icon when to give orientation/directions first), click on ("select" is usually used to choose or highlight) the Download icon and select Power BI Desktop in the drop-down menu.

2. Once (more accurate than "After") you've landed on the Power BI Desktop page of the Microsoft Store, click (instead of "select") the Install button.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-ca/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Yuliadocs.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @Yuliadocs. Thank you again for your edits.  I've applied some of them to the article.  We try to avoid using 'click' and instead use 'select' and then 'choose'.
Take care.
