### ISSUE TITLE
Reference to 1 million row limit invalid

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#2821]
Re: https://docs.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance

In the "Apply filters first" section, the final sentence reads "Also, failing to apply filters early can result in exceeding the 1 million-row limit, as described above." however there is no previous mention of this 1 million row limit in the doc that would allow for the statement "as described above".

Rather this limit is defined in other docs that could be referenced instead - such as the "Other Limitations" section of this doc: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 694e3f20-79d0-debf-1449-38a62492424c
* Version Independent ID: 75c298be-5754-c342-cb4d-228b38f8cec7
* Content: [DirectQuery model guidance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance)
* Content Source: [powerbi-docs/guidance/directquery-model-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/directquery-model-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rosscouldrey.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @rosscouldrey , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
