### ISSUE TITLE
What about any integration between R and Power BI Embedded

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#2822]
I can't find any documentation that explains if R is integrated in Power BI Embedded.
I only found [this old blog post](https://powerbi.microsoft.com/en-us/blog/r-in-pbie/).
Are R transformation steps in Power Query allowed in Power BI Embedded?

I think Docs are missing these informations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-r-packages-support)
* Content Source: [powerbi-docs/connect-data/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @lucazav,

Let me look into this and I'll get back to you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @lucazav,

After confirming with our development team, and if it renders in the portal (Power BI service), it should render when embedded.

Hope this helps.,

Kesem

**Comment by lucazav** [comment]
Thank you, Kesem.
It'd be nice if you specify this also in the Docs.

Thank you.

--
Luca Zavarella
________________________________
