### ISSUE TITLE
What about any integration between Python and Power BI Embedded

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#2823]
I can't find any documentation that explains if Python is integrated in Power BI Embedded.
Are Python visuals allowed in Power BI Embedded?
Are Python transformation steps in Power Query allowed in Power BI Embedded?

I think Docs are missing these informations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db4f2779-18a0-100c-dc5f-ac0f77f05d19
* Version Independent ID: e6654e84-bba6-8280-645a-5e56e999276e
* Content: [Learn which Python packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-python-packages-support)
* Content Source: [powerbi-docs/connect-data/service-python-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-python-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by KesemSharabi** [comment]
Hi @lucazav,

Thanks for your feedback. I'll look into this and get back to you shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @lucazav,

After confirming with our development team, anything that renders in the portal (Power BI service) should render when embedded.

Hope this helps.,

Kesem
