### ISSUE TITLE
Using the Sort by Column button has complex requirements

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2824]
[Enter feedback here]

Using the Sort by Column button actually has complex requirements - the selected column must be at the same level of granularity or less granular. The data is tested when a choice is made and on every subsequent refresh. Breaking the granularity requirements will trigger a fatal error. It should also be noted that it's a model-level change that applies across all visuals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort by column in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Mike-Honey.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- good points! Adding them to the article.

**Comment by maggiesMSFT** [comment]
Thanks for both suggestions, @Mike-Honey ! I've added them to a rewrite of the article. Changes will be live this afternoon Pacific time 6/30/2021
