### ISSUE TITLE
Similar page for Python Visuals

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#2825]
Is there any similar page also for Python Visuals? Here there are data size limitations that are missing for Python in [this page](https://bit.ly/powerbi-python-limits).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c7931b-9fbb-bec4-09c4-9c827e4ec7a1
* Version Independent ID: 7ebc1400-482b-62e6-3747-bb7ffdb1dcf3
* Content: [Create advanced analytics and visualizations using R scripts - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#licensing)
* Content Source: [powerbi-docs/visuals/service-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/service-r-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Hi @lucazav  - thank you for the feedback on our documentation. If I understand correctly, you'd like to see the same level of detail for Python that are shown in this article about R scripts. I am routing your feedback to the feature owners to consider this update. Please feel free to comment if I have misinterpreted your request!

**Comment by lucazav** [comment]
Hi Kate,

exactly. I’m wondering if the same limitations also apply for Python Visuals.

Thanks.

--
Luca Zavarella

**Comment by lucazav** [comment]
Hi @kfollis ,
any update?

Thanks

**Comment by msftrien** [comment]
There are some differences between Desktop and Service, particularly supported packages, so I'm not sure if data limits are the same between the two, but this related link may be relevant--
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-visuals

**Comment by lucazav** [comment]
Hi @msftrien ,
that page is useful for sure!

I also noticed that there is an undocumented limitation: if the input dataset of a Python Visual has a column that contains a string value longer than 32766 characters, that value is truncated. The same thing applies to R Visual.

Can you confirm this and maybe add it to the limitations in the Docs?

**Comment by msftrien** [comment]
Adding to limitations to docs. @mihart I think that should close this?

**Comment by mihart** [comment]
@msftrien @lucazav ,
Thank you both!  Closing this now.
