### ISSUE TITLE
Visual 5 Field Clarity

### ISSUE THREAD

**Issue by PaulComis** [MicrosoftDocs/powerbi-docs#2826]
For the section on Visual 5 (Slicer)...it could be clearer that we're selecting the "Date" Field from the "Calendar" source, and not the "Date" in the Financials source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @PaulComis -- good point! Thanks. I'll clarify.

**Comment by maggiesMSFT** [comment]
OK, update made and signed off. Should be live tomorrow afternoon, Feb 11. Thanks!
