### ISSUE TITLE
Typo Issue

### ISSUE THREAD

**Issue by pramotepm** [MicrosoftDocs/powerbi-docs#2827]
I think you are missing comma (,) in this sentence.

OneDrive - Business – If you have OneDrive for Business and you sign into it with the same account you sign into Power BI with, this is by-far the most effective way to keep your work in **_Excel Power BI Desktop_**, or a .CSV file and your dataset, reports, and dashboards in Power BI in-sync.

would be

OneDrive - Business – If you have OneDrive for Business and you sign into it with the same account you sign into Power BI with, this is by-far the most effective way to keep your work in **_Excel, Power BI Desktop_**, or a .CSV file and your dataset, reports, and dashboards in Power BI in-sync.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394d90a7-d6ad-c666-9099-a85e7ab4d817
* Version Independent ID: 5077293e-a2c0-16b6-08bb-b65b11b1e9e5
* Content: [Get data from files for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data-from-files)
* Content Source: [powerbi-docs/connect-data/service-get-data-from-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-get-data-from-files.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @prmotepm - Good catch! I have already made the change and it will be live when we publish again tomorrow. I appreciate your careful reading and pointing that out! Thanks for your contribution.
