### ISSUE TITLE
Storage Account in the same tenant ?

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#2829]
Hi, 

must the storage account be created in the same Azure Active Directory tenant as the Power BI tenant ? 

As it is specified in this page for Power App Dataflows : https://docs.microsoft.com/en-us/powerapps/maker/data-platform/connect-azure-data-lake-storage-for-dataflow#prepare-your-azure-data-lake-storage-gen2-for-power-platform-dataflows.

Thanks!

Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @nstraw - thanks for asking! The prerequisites state that the storage account has to be in the same region as the tenant. I am assigning this to the writer, though, to further clarify.

**Comment by JayPat65** [comment]
Hi,

Once the dataflow storage is configured to use Azure Data Lake Gen 2, there is no way to go back without deleting all the dataflows? There will be a lot of redo activity in that case for users.
In such a case, can we configure only admin can use the feature? 

Regards,
Jaydip

**Comment by nstraw** [comment]
Hi @kfollis, thanks for your message, did you get some feedback ? I'm trying to attach a Workspace to another tenant ADLS, I've set up all the security but it does not seem to work :(

**Comment by kfollis** [comment]
Hi @nstraw - the writer is investigating but I don't have further detail. You may try asking in community.powerbi.com or if you're stuck, contact support.powerbi.com.

**Comment by mihart** [comment]
Hi @nstraw , 
Thank you for your question. I spoke with one of the PMs and the answer is "Yes, same tenant and same region."  We've made the update and set the article to republish later this week. 
All the best,
The DOCS team
