### ISSUE TITLE
Need to correct and validate

### ISSUE THREAD

**Issue by sergeig888** [MicrosoftDocs/powerbi-docs#2830]
1. This statement "Query text and query result traffic for imported data models" needs to be updated to "Query text and query result traffic for imported and Direct Query data models"
2. Last bullet: "Moving large-storage format datasets from the region where they were created will result in reports failing to load the dataset. Move the large-storage dataset back to its original region to make it available." needs to be clarified in my opinion that since large data models went GA it is possible to create and maintain them in the remote region meeting data residency requirements even for large data models.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/admin/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Thank you for the feedback, @sergeig888! I am assigning this issue to the author to verify and make these updates. We appreciate the contribution and will address this soon.

**Comment by mihart** [comment]
Hi @sergeig888 
Thank you for your feedback.  The article has been updated and is scheduled for republish next week.
