### ISSUE TITLE
Data gateway recovery key based encryption

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/powerbi-docs#2831]
Documentation says that data sources credentials are encrypted with public key (generated using recovery key) but it does not clarify where these encrypted credentials are stored in the cloud. Gateway cluster which is installed on the machines is covered very well, but cloud part is not clear.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @prashant1380 -- thanks for asking! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
Thanks for your comment. Determining where those keys reside is a support request rather than documentation request for this article. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
