### ISSUE TITLE
Multiple select

### ISSUE THREAD

**Issue by bosschgn** [MicrosoftDocs/powerbi-docs#2832]
Is there any way to do multiple select without holding the ctr key on pc ?  On the ipad it seems to work and works so much better, especially when doing presentations.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02349558-4417-b39f-be59-b80655babdd2
* Version Independent ID: 6c5c0c15-6bf4-e775-1f0e-d95525ec30cf
* Content: [Multi-select data elements in visuals, or multiple visuals, in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-multi-select)
* Content Source: [powerbi-docs/create-reports/desktop-multi-select.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-multi-select.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @bosschgn, thanks for your reaching out to us with your question. I am forwarding it on to the doc owner. Thanks!

**Comment by mihart** [comment]
Hi @bosschgn , 
Thank you for your suggestion.  You are able to drag and select too.  Dragging creates a rectangle around your selection.  We've made the update and set the article to republish. If this does not answer your question, please try the Power BI Community (community.powerbi.com)
All the best,
The DOCS team

**Comment by mihart** [comment]
Hi @bosschgn, 
Thank you for your suggestion.  I'm not sure that I understand your question.  The article does describe how to do a "lasso" select.  The lasso doesn't work for selecting individual data points though.  Are you looking for a way to multi select data points without using CTL?   
All the best,
The DOCS team
