### ISSUE TITLE
API removing user from gateway datasource using service principal doesn't work

### ISSUE THREAD

**Issue by nodenks** [MicrosoftDocs/powerbi-docs#2833]
Hi,
I am trying to use the removing user API (https://docs.microsoft.com/en-us/rest/api/power-bi/gateways/deletedatasourceuser) with service principal and it gets stuck in execution. There is no error code, it just keeps waiting. Could you help me with this issue?

Below code, I am using

$gatewayId = "xxx"
$spnID = "xxx"
$spnClientSecret = "xxx"
$datasourceId = "xxx"
$emailname =  "xxx"

$relativeUrlPath = "https://api.powerbi.com/v1.0/myorg/gateways/" + $gatewayId + "/datasources/" + $datasourceId + "/users/" + $emailname

## Connect to Data Gateway
$ClientSecret = $spnClientSecret | ConvertTo-SecureString -AsPlainText -Force
$tenantId ="xxxxxxxxx"

$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $spnID, $ClientSecret
Connect-PowerBIServiceAccount -Tenant $TenantId -ServicePrincipal -Credential $Credential

# Thrown an error if not logged in
Get-PowerBIAccessToken | Out-Null

#Delete user from data source
Invoke-PowerBIRestMethod -Url $relativeUrlPath -Method DELETE
![powershell1](https://user-images.githubusercontent.com/51742346/107874786-3cecf000-6ebc-11eb-95d4-6b4156949eea.png)

**Note: I have granted all API permissions to my SPN (app registration)**

![apipermission](https://user-images.githubusercontent.com/51742346/107875703-c5ba5a80-6ec1-11eb-8e5d-34cbab8137b8.JPG)

**Comment by nodenks** [comment]
> There is no error code, it just keeps waiting

After a while i got this error message:
Invoke-PowerBIRestMethod: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)

**Comment by paulinbar** [comment]
Hi @nodenks, thanks for reaching out. You've reached the docs team, and I think you need product support. Try opening a ticket at our [support site](https://powerbi.microsoft.com/support/). You might also try the [Power BI Community]( https://community.powerbi.com).
