### ISSUE TITLE
I am using oracle 11g 32its with powerBI 64 bits

### ISSUE THREAD

**Issue by mafuz** [MicrosoftDocs/powerbi-docs#2835]
I am using oracle 11g 32its with powerBI 64 bits when I try to connect to the database I am getting  Details: "Oracle: ORA-12541: TNS:no listener"  and I have configured the TNS correctly in both oracle and powerBI client. Will it be the result of my oracle version?

**Comment by paulinbar** [comment]
Hi @mafuz, thanks for reaching out to us. You have reached the docs team. I think you will have better luck putting your question out to the [Power BI Community]( https://community.powerbi.com), or you can also try our [support page](https://support.powerbi.com).  Good luck!
