### ISSUE TITLE
Paginated report for Dynamics 365 Fails to Publish in Power BI service

### ISSUE THREAD

**Issue by deepakn1079** [MicrosoftDocs/powerbi-docs#2836]
I have been trying to publish a power BI paginated report to power BI Service it doesn't seem to work . I ve built the report with the power BI report builder . It works fine with the azure databse and i can preview the report . I can also connect to the azure SQL with Sql managment studio . But when i imported the RDL file into the Power BI service it keeps throwing the error that 

Failed to update data source credentials: Login failed: Request is not authenticated.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @deepakn1079, thanks for reaching out. You've reached the docs team, and it sounds to me like you need product support. I suggest you put your question out to the [Power BI Community]( https://community.powerbi.com), and also try our [support page](https://support.powerbi.com). Good luck!
