### ISSUE TITLE
Power BI Report Server January 2021, "filter=" URL parameter is not working

### ISSUE THREAD

**Issue by dp33Fr** [MicrosoftDocs/powerbi-docs#2837]
Hi,

Two customers have same issue: After applying PBRS January 2021, all reports with "filter=" parameter don't woking.
Previous October 2019 version was working without any problem.
http://myserver/reports/MyReportSample?filter=Product/Familly eq 'Computer' 
no error, report are rendering correctly. Char case, spaces are corrects.

After upgrade, the report begin to render and a blank page appear.

I test my URL with Chrome, Firefox, Edge and Safari and get same issue.
If I uninstall this update and install PBRS October 2019, restore ReporterServer databases, SSRS Key, all work fine.
So, it's a bug with latest version.
There is nothing about "error" in PBRS logs files.

Is there a fix?
Regards,
Denis

**Comment by paulinbar** [comment]
Hi @dp33Fr, thanks for reaching out. You've reached the docs team, but this sounds more like a problem for product support. I suggest you try putting your question out to the [Power BI Community]( https://community.powerbi.com), or try our [support page](https://support.powerbi.com).  Good luck!
