### ISSUE TITLE
version 2.88.1682.0 64-bit (December 2020) using unsupported ODBC driver (version 2.20.2) for native Snowflake connector

### ISSUE THREAD

**Issue by targetpharma** [MicrosoftDocs/powerbi-docs#2839]
Running the latest version 2.88.1682.0 64-bit (December 2020) of Power BI Desktop, and the native Snowflake connector is using an unsupported (old) version of the Snowflake ODBC driver (version 2.20.2)

![image](https://user-images.githubusercontent.com/20141935/107995254-3e95e100-6fac-11eb-8dd3-ba4686c10a8a.png)

![image](https://user-images.githubusercontent.com/20141935/107995229-2faf2e80-6fac-11eb-8f25-4f9514babb0d.png)

There does not appear to be a way to update the ODBC driver for the native Snowflake connector, as I tried downloading the latest Snowflake ODBC driver 2.22.4 and Power BI Desktop does not use that driver.

![image](https://user-images.githubusercontent.com/20141935/107995584-84eb4000-6fac-11eb-8471-111dd7c93118.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @targetpharma, thanks for reaching out to us. I am forwarding your comment along to the doc author - I hope he will be able to  direct your query to the right place.

**Comment by mihart** [comment]
Thanks for your comment, @targetpharma . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
