### ISSUE TITLE
Access the directory as a signed in user

### ISSUE THREAD

**Issue by BharathiAN** [MicrosoftDocs/powerbi-docs#284]
Why the "Access the directory as a signed in user" permission to be enabled for this. Does the "sign-in and read user profile" permission is not enough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed Power BI content into an application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@BharathiAN You are correct, there is no difference. The "Sign in and read user profile" permission would work the same.  Thank you for your feedback.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by BharathiAN** [comment]
Hi,
Thanks for your response. In that case, whether this article will be modified accordingly.
