### ISSUE TITLE
Phrase meaning

### ISSUE THREAD

**Issue by fred31330** [MicrosoftDocs/powerbi-docs#2840]
[Enter feedback here]
The bolded section in sentence "**If your initial refresh with the compute engine turned on**, then data gets written in the lake and in the cache. This double write means these refreshes will be slower." is confusing. Can you fix it?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6054103-4999-9ce2-ba30-095a6d469465
* Version Independent ID: 2ce5b049-276a-a159-4f28-fd1dca17442f
* Content: [Configure Power BI Premium dataflow workloads - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-workload-configuration#using-the-compute-engine-to-improve-performance)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @fred31330, thanks for your comment. I am forwarding it on to the doc author for consideration. Thanks!

**Comment by mihart** [comment]
Hi @fred31330 , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
