### ISSUE TITLE
MariaDB is not listed in the data sources lists

### ISSUE THREAD

**Issue by juanparati** [MicrosoftDocs/powerbi-docs#2842]
MariaDB is not listed in the data source lists despite that it supports Direct Query.

See [Mariadb Direct Query instructions](https://mariadb.com/resources/blog/getting-started-with-the-mariadb-direct-query-adapter-for-microsoft-power-bi/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources#feedback)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @juanparati, thanks for your comment. I am forwarding it on to the doc author for further consideration.

**Comment by mihart** [comment]
Hi @juanparati , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
