### ISSUE TITLE
Contributor does not have Manage dataset permissions as incorrectly documented

### ISSUE THREAD

**Issue by jaredwbrown77** [MicrosoftDocs/powerbi-docs#2843]
The table in the "Roles in the new workspace" section suggests that Contributors can "Manage dataset permissions", but I don't believe that is the case unless I am missing something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @jaredwbrown77, thanks for your comment. I am forwarding it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @jaredwbrown77 -- you're right! I just tried it. I've updated the table and the article. Change should be live this afternoon.
Thanks!
