### ISSUE TITLE
CLI version?

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/powerbi-docs#2844]
Needs to include how to pause/unpause using something like the Azure CLI so you could schedule this (e.g. only have running during office hours).
If this is not possible then the page should call this out that it is currently a manual task

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 842bcbb2-ce2c-3729-f876-5d306595b33c
* Version Independent ID: 1a915436-b70f-a6e9-a3c1-f7fc8db4cdb2
* Content: [Pause and start your Power BI Embedded capacity in the Azure portal for your Power BI embedded analytics embedded BI solution - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-pause-start)
* Content Source: [powerbi-docs/developer/embedded/azure-pbie-pause-start.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/azure-pbie-pause-start.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @thommck, thanks for your comment. I am forwarding it along to the doc author for further consideration.

**Comment by KesemSharabi** [comment]
Hi @thommck,

Currently you cannot start/pause a Power BI capacity using CLI.

For a list of all the Power BI CLI commands, see [az powerbi](https://docs.microsoft.com/cli/azure/ext/powerbidedicated/powerbi?view=azure-cli-latest).

To update capacities programmatically, you can use:
* ARM APIs:
   * [Capacities - Resume](https://docs.microsoft.com/rest/api/power-bi-embedded/capacities/resume)
   * [Capacities - Update](https://docs.microsoft.com/rest/api/power-bi-embedded/capacities/update)
* Azure PowerShell:
   * [Resume-AzPowerBIEmbeddedCapacity](https://docs.microsoft.com/powershell/module/az.powerbiembedded/resume-azpowerbiembeddedcapacity?view=azps-5.5.0)
   * [Suspend-AzPowerBIEmbeddedCapacity](https://docs.microsoft.com/powershell/module/az.powerbiembedded/suspend-azpowerbiembeddedcapacity?view=azps-5.5.0)

When we update the page we'll add this information to it.

Hope this helps,

Kesem
