### ISSUE TITLE
What's missing is an explanation of how the RangeStart and RangeEnd parameters are set by the service

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/powerbi-docs#2845]
What's missing here is the inside scoop of how the two values get used by the service.

For instance, in my queries, I have a case where thousands of tables are uploaded each time the refresh runs.  For this I'm using a List.Generate().  What I'm trying to do is to setup my queries so they don't bother to run for date ranges that will be stored in the service.  I built a report that shows the values of the parameters, in hopes of seeing the values get set by the service, but the entire report so far won't refresh.

Please include the setting of the ``RangeStart`` and ``RangeEnd`` parameters by the service, for instance in the case that we set "Store data for 3 years" and "update data for the last 10 days", as an exmple.  That will help those of us who have queries that are more complex than "get entire big table"

-thanks
-e

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb026fd-1515-7484-1acd-3d363e143cc8
* Version Independent ID: 62650e83-de5c-0323-cacc-31bad6e46361
* Content: [Incremental refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-incremental-refresh#rangestart-and-rangeend-parameters)
* Content Source: [powerbi-docs/admin/service-premium-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-incremental-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ericleigh007.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by KesemSharabi** [comment]
Hi @ericleigh007,

Apologies for the very late reply. As per the [Create parameters](https://docs.microsoft.com/power-bi/connect-data/incremental-refresh-overview#create-parameters) section, `RangeStart` and `RangeEnd` are set automatically by the service as per this statement:

*After the model is published to the service, RangeStart and RangeEnd are overridden automatically by the service to query data defined by the refresh period specified in the incremental refresh policy settings.*

![image](https://user-images.githubusercontent.com/54834915/152111077-46d886a2-2254-4e94-a12c-326ee09f027e.png)

Hope this helps,

Kesem
