### ISSUE TITLE
Missing step in enabling Gen 2 mode

### ISSUE THREAD

**Issue by mark-thurston-icgam-com** [MicrosoftDocs/powerbi-docs#2846]
[Enter feedback here]

The section:
In the admin portal, navigate to Capacity settings.
Select Power BI Premium.
A section appears titled Premium Generation 2 (preview), and in that section is a slider to enable Premium Generation 2 (preview).
Move the slider to Enabled.

is missing one step, which is to select the existing allocated capacity first. So, it should say:

In the admin portal, navigate to Capacity settings.
Select Power BI Premium.
If you have already allocated capacity, select it. 
A section appears titled Premium Generation 2 (preview), and in that section is a slider to enable Premium Generation 2 (preview).
Move the slider to Enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mark-thurston-icgam-com -- thanks for the feedback! Referring to the author for consideration.

**Comment by mihart** [comment]
Hi @mark-thurston-icgam-com ,
Thank you.  The article has been updated with the added step.
