### ISSUE TITLE
Make it more clear how different gov plan get Power BI

### ISSUE THREAD

**Issue by kerbos** [MicrosoftDocs/powerbi-docs#2847]
This section deals with helping the customer understand how to sign up for the appropriate environment.
https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup#select-the-right-sign-up-process-for-your-us-government-organization

For GCC High, they need to buy (no trials) and go straight to How do I buy Microsoft 365 Government? link (https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/office-365-us-government/microsoft-365-government-how-to-buy#how-do-i-buy-microsoft-365-government)

For GCC, they can proceed and follow this section:
https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup#sign-up-for-a-new-microsoft-365-government-plan

This section also applies to GCC only. GCC High customers cannot use Purchase Services.
https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup#add-power-bi-to-a-microsoft-365-government-plan

By clarifying above, this will keep customers who already have an Azure Government tenant from accidentally spinning up a GCC trial tenant (resulting in two tenants). Existing Azure Government tenants will get paired with GCC High and thus need to work to purchase Power BI with reseller if the product is desired.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff5ba960-512e-7a76-10c9-ac6a33bd6022
* Version Independent ID: 44d12651-bb26-9d9d-42c4-66b3c42e8465
* Content: [Sign Up for Power BI for United States government customers - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup)
* Content Source: [powerbi-docs/admin/service-govus-signup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-govus-signup.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks, @kerbos! Great clarification and I appreciate all the links. I will make those updates soon.

**Comment by kfollis** [comment]
An update has been made to better clarify the right process for gov't orgs to get Power BI in this article https://docs.microsoft.com/en-us/power-bi/admin/service-govus-signup#select-the-right-sign-up-process-for-your-us-government-organization. In addition, this article https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview has been updated to move cloud types and sign up steps higher up in the article. Hope that helps! Thank you for your contribution.
