### ISSUE TITLE
Dataflows for reporting

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/powerbi-docs#2848]
This line in the article might be misleading given that you can connect to dataflows as a data source:

"However, they can't be used directly as a source for reporting."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f7e98b-d12a-5896-50c4-bd33f63481d0
* Version Independent ID: a1ccb451-0ba0-f4b5-63eb-22b62fcc93f6
* Content: [Basic concepts for designers in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-basic-concepts#workspaces)
* Content Source: [powerbi-docs/fundamentals/service-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @kasavin -- thanks for the feedback! Assigning to the author for consideration.

**Comment by mihart** [comment]
Hi @kasavin , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
