### ISSUE TITLE
Unable to import data from excel labeled as confidential 

### ISSUE THREAD

**Issue by cshailaja** [MicrosoftDocs/powerbi-docs#2849]
We have a confidential sensitivity label that applies protection.
I am unable to import data from the excel file to powerBI when the file is labeled with confidential label. However I am able to import data from a file that where label doesn't apply protection. 

I would like to know if it is the expected behavior?

I receive the below error:

"Something went wrong

Failed to configure selected file
Please try again later or contact support. If you contact support, please provide these details.
Hide details
Activity IDf0073cc4-f93f-47b2-8c79-3864d3ee24ef
Request ID09981c97-e272-4b39-c001-a5416619072a
Correlation ID0427d1c2-e9fe-53f1-a1d0-34f5e9ae84c4
Status code400
TimeThu Feb 18 2021 13:07:20 GMT+0530 (India Standard Time)
Service version13.0.15383.18
Client version2102.2.04869-train
Cluster URIhttps://wabi-us-east2-b-primary-redirect.analysis.windows.net/"

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ffb799-4e1a-c47c-749e-c27b0bd0ae65
* Version Independent ID: 7744ac08-00fd-62d1-6014-14b96f0f2f2f
* Content: [Microsoft Information Protection sensitivity labels in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-sensitivity-label-overview#limitations)
* Content Source: [powerbi-docs/admin/service-security-sensitivity-label-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-sensitivity-label-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @cshailaja, I believe this is the expected behavior now, as I don't think importing an Excel file that has a label with protection is supported yet. I am checking just to make sure though and will get back to you when I hear. Thanks for your question!

**Comment by cshailaja** [comment]
Sure. Thanks for the quick update.

**Comment by paulinbar** [comment]
Hi @cshailaja, yes, I checked. Import from Excel of data that has a label with protection is not yet supported and will fail. So that is the expected behavior. I think they are working on it though. Meanwhile, not a great error message, I have to say...

**Comment by cshailaja** [comment]
Thanks for confirming. Looking forward for that capability to be implemented.
