### ISSUE TITLE
Premium capacity recommended data model size guidance

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#2850]
Can we please update the Premium capacity recommended data model size guidance to more clearly say the sizes are recommendations due to the way data refreshes occur but that it is not a hard limit?  This is confusing for customers and even internal Microsoft support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#size-considerations)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
Hi @Hikmer - thank you for the feedback on our documentation. I am routing your request for this update to the writer to review and ensure that the model size guidance is clear on recommendations vs. hard limits. Please be patient as we evaluate the request and plan our updates.

**Comment by KesemSharabi** [comment]
Hi @Hikmer,

With [Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-what-is) and the plan to discontinue the original version of Premium, is this still relevant?

Thanks,

Kesem
