### ISSUE TITLE
Small correction in Tutorial Example to be made. The Date field in the Calendar from the join table, to be used for the 1st PowerBI visual chart

### ISSUE THREAD

**Issue by mohijarada2017** [MicrosoftDocs/powerbi-docs#2851]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @mohijarada2017, thanks for your comment. I am forwarding it on to the doc author for further consideration.

**Comment by maggiesMSFT** [comment]
Hi, @mohijarada2017 -- thanks for your comment! Actually either Date field will work. I've added the one from the Calendar table. Change should be live in the next few days. 
Thanks!

**Comment by mohijarada2017** [comment]
Thanks a lot. I am so happy i was able to contribute.
BR,
Mohee
