### ISSUE TITLE
Missing conditions for automatically installing apps

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerbi-docs#2852]
Please mention in the "Considerations for automatically installing apps" section that it is not possible to automatically install an app for the entire organization.  The permissions for the app must specify named users or groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Dan1480.  We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @Dan1480 , 
Thank you for your suggestion.  You are correct! We've made the update and set the article to republish in the next few days. 
All the best,
The DOCS team
