### ISSUE TITLE
Section "Set your visual to send data" has wrong instruction in Step 2.

### ISSUE THREAD

**Issue by KayUnkroth** [MicrosoftDocs/powerbi-docs#2854]
Step 2 says: **Replace** the content of the ReactCircleCard class, with the following code.

It should say, **Add** the content of the ReactCircleCard class, with the following code.

If you replace the code, the render() method would get lost and you wouldn't see anything in the visual.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfc5549-16a6-5afd-dac4-64021c25dfa9
* Version Independent ID: b8bf0ca1-1f11-bac0-76fa-cfd6a0d1231b
* Content: [Create a React-based visual for Power BI in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual)
* Content Source: [powerbi-docs/developer/visuals/create-react-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/create-react-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @KayUnkroth. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Thanks @KayUnkroth, I've made the update.
