### ISSUE TITLE
Missing workspace level setting

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#2855]
Please add the workspace setting for ArcGIS visuals too, many people dont know where that setting is located.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Interacting with an ArcGIS map that has been shared with you - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @Hikmer . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @Hikmer ,
Thank you for your suggestion.  Would you please clarify what you mean by "workspace settings" for ArcGIS? If an ArcGIS map is one of the visuals on a page in a report in a workspace, the "workspace settings" are the same as the settings for the rest of the pages in the report.  If I'm not understanding your questions, please let me know.
Take care,
the DOCS team

**Comment by msftrien** [comment]
This is mentioned in the "Manage the use of ArcGIS for Power BI within your organization" section of the doc. Also this is a duplicate (or the other is a duplicate)

**Comment by Hikmer** [comment]
This is missing from the documentation

[image: image.png]
