### ISSUE TITLE
Cloning when Migrating to Power BI Report Server from SSRS (Native mode) not working

### ISSUE THREAD

**Issue by ChristianGalla** [MicrosoftDocs/powerbi-docs#2856]
According to the documentation, the old SSRS DBs should be cloned and the clones attached to the Power BI Report Server. This only works if the name is not changed because it is copied to another DB server.

The report DB must always have a similar name as the corresponding temp DB (for example ReportServer and ReportServerTempDB). [Renaming of a report server database is not supported](https://docs.microsoft.com/en-us/sql/reporting-services/report-server/administer-a-report-server-database-ssrs-native-mode?redirectedfrom=MSDN&view=sql-server-ver15#naming-conventions-for-the-report-server-databases) and it looks like it is not working during migrations, too. [If tried, there are many issues for example regarding subscriptions](https://community.powerbi.com/t5/Report-Server/Report-Server-to-PBI-Report-Server-upgrade-Subscription-issues/td-p/795516), because Power BI Report Server tries to access the old temp DB.

Ideally, Microsoft should add support for DB renaming.

As a manual workaround [I assume it should be sufficient to recreate all views and stored procedures while searching for the old temp DB name and replacing it to the new temp DB name](https://steveknutson.blog/2017/07/29/changing-ssrs-database-names/). Is this workaround supported?

As an alternative, for now I suggest rewriting the documentation to only back up the existing DB, uninstall / disable the old SSRS and link a new Power BI Report Server installation to the old SSRS DB (without cloning / renaming).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db0a4ba-a14f-6519-c047-0e315fdc50d9
* Version Independent ID: 1e7d1169-fd34-b9e5-2ab2-4498bdde202f
* Content: [Migrate a report server installation - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/migrate-report-server)
* Content Source: [powerbi-docs/report-server/migrate-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/migrate-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ChristianGalla.

I've assigned this issue to the doc author for review.

**Comment by ChristianGalla** [comment]
We are still testing if there are any other errors, but it looks like on migration references in 90 DB objects were automatically updated to the new name of the temp DB. Only one reference in the trigger [dbo].[Schedule_UpdateExpiration] on the table [dbo].[Schedule] was missed.
After changing this trigger to reference the new temp DB, we were able to save email subscriptions again.

We will keep you updated, but for now, I assume the documentation is correct, but there is a bug in the migration code of the Power BI Report server.

Do you have access to the backlog of the coding team responsible for the Power BI Report Server or shall I create an issue via another channel?
Unfortunately, [a post in the Power BI Forum describing the same issue from 2019](https://community.powerbi.com/t5/Report-Server/Report-Server-to-PBI-Report-Server-upgrade-Subscription-issues/td-p/795516) was still not answered...

**Comment by ChristianGalla** [comment]
It looks like there is some GUID based mapping between SQL Server agent jobs and the subscription tables:

```sql
SELECT distinct
sj.[name] AS [Job Name],
rs.SubscriptionID,
c.[Name] AS [Report Name],
c.[Path]
FROM msdb..sysjobs AS sj 
INNER JOIN ReportServer..ReportSchedule AS rs
ON sj.[name] = CAST(rs.ScheduleID AS NVARCHAR(128)) 
INNER JOIN ReportServer..Subscriptions AS su
ON rs.SubscriptionID = su.SubscriptionID
INNER JOIN ReportServer..[Catalog] c
ON su.Report_OID = c.ItemID
```

On migration these GUIDs are not changed, the jobs are still pointing to the old SSRS DBs and no new jobs are created. Also, the Power BI Report Server is unable to execute or update these subscriptions / jobs.

For now my suggestion is to change the documentation for the paragraph "Migrating to Power BI Report Server from SSRS (Native mode)" on the same machine as follows:
- Remove all mentions about DB cloning. Instead the original DB must be used.
- Before configuring the Power BI Report server to use the SSRS DB, SSRS must be uninstalled.
- Hints about running an SSRS on the same machine as Power BI Report servers should be removed or rewritten that this is not the case for migrated DBs from the still running SSRS.
