### ISSUE TITLE
Issue with token expiring after 1 hour

### ISSUE THREAD

**Issue by vlado101** [MicrosoftDocs/powerbi-docs#2857]
Hello,

I just wanted to see if this issue has been resolved. We are facing an issue similar to Power BI where we have an Azure Data Factory job that runs for longer than an hour. When trying to integrate those Azure Data Factory jobs with Control-M it sets our jobs as failed after an hour even if the jobs runs with no issues.

We are trying to look for a solution so any help or insights would be much appreciated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios#refresh-fails-when-updating-data-from-sources-that-use-aad-oauth)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @vlado101 -- thanks for asking. Assigning to the author to look into the issue. In the meantime, I recommend asking the Power BI community, https://community.powerbi.com/ and/or looking on the Power BI Ideas site, https://ideas.powerbi.com/ideas/.

**Comment by mihart** [comment]
Thanks for your comment, @vlado101 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
