### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sanshan20** [MicrosoftDocs/powerbi-docs#2858]
Under section [Limitations and considerations](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets#limitations-and-considerations) there is statement that says "When you connect to these multi-dimensional sources by using **DirectQuery**, you can't connect to another DirectQuery source or combine it with import data."

Shouldn't the bolded text be Live connection instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @sanshan20 -- thanks for asking! Referring to the author to investigate.

**Comment by mihart** [comment]
Hi @sanshan20 , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
