### ISSUE TITLE
Page title still shows December 2020

### ISSUE THREAD

**Issue by aleowuor** [MicrosoftDocs/powerbi-docs#2859]
Page title may need to be updated. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI Desktop update - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @aleowuor -- good catch, thanks! We'll get it updated soon.

**Comment by mihart** [comment]
Hi @aleowuor , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
