### ISSUE TITLE
No longer in preview

### ISSUE THREAD

**Issue by sethsanuMSFT** [MicrosoftDocs/powerbi-docs#2861]
[Enter feedback here]

The preview feature section and image at the bottom can be removed. It's circa 2017 / 2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Use bookmarks in Power BI Desktop to share insights and build stories - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-bookmarks)
* Content Source: [powerbi-docs/create-reports/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @sethsanuMSFT -- good point. Deleted it. Thanks!
Change should be live in the next few days.
