### ISSUE TITLE
updated needed to Conditional Table Formatting page

### ISSUE THREAD

**Issue by JD-BOS** [MicrosoftDocs/powerbi-docs#2862]
In the "Totals and subtotals" section: "Beginning with the April 2020 release, you can apply conditional formatting rules to totals and subtotals, for both table and matrix visuals.

But the next section "Considerations and limitations" the first statement is "Conditional formatting applies only to the values of Table or Matrix visuals, and doesn't apply to any subtotals, grand totals, or the Total row.

Looks like the statement in Considerations and limitations can be removed - and thanks for this "new" feature! ~ Jay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @JD-BOS , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
