### ISSUE TITLE
What is the value of "client id" when using "Master User" auth? 

### ISSUE THREAD

**Issue by mpchen** [MicrosoftDocs/powerbi-docs#2863]
When using "Master User" auth, what is the value of "client id"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @mpchen, thanks for your question. I am forwarding it on to the doc author for further consideration.

**Comment by KesemSharabi** [comment]
Hi @mpchen,

When using **master user** in the 'embed for your customers' solution, the client ID (AKA application ID) is the client ID of the Azure AD app you created in [Step 2 - Register an Azure AD application](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core#step-2---register-an-azure-ad-application).

Hope this helps,

Kesem
