### ISSUE TITLE
BadRequest error when exporting paginated report to csv, Excel or Word

### ISSUE THREAD

**Issue by calebcwells** [MicrosoftDocs/powerbi-docs#2864]
I have a three page report that is embedded in a website and am trying to use version 3.21.0 of the REST API to export the report. Each page has several visuals that I can export separately to Excel using the 'Export Data' menu option. I can also export the full report to pdf and PowerPoint using PowerBIReportExportConfiguration or PaginatedReportExportConfiguration in my code. I am using the code examples provided on the page listed below. When I try to export to csv, Excel or Word I get a BadRequest error with no further details. I have attempted several variations on the configuration referencing https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-url-parameters#report-commands-rdl with the same error result. I understand if the functionality is not complete but would like to make sure that is the case and it is not something particular with my Power BI report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI embedded analytics paginated reports API for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for reaching out to us with your question, @calebcwells. I am forwarding it on to the doc author for further consideration. He might be able to point you in the right direction. I also suggest trying the [Power BI Community]( https://community.powerbi.com), or our [support page](https://support.powerbi.com). Thanks!

**Comment by KesemSharabi** [comment]
Hi @calebcwells,

Can you please confirm which report you're trying to export?

If you're trying to export a regular report (not a paginated report), the error is expected. You cannot export a regular report to Excel, Word or a CSV file. These formats are only supported when exporting a paginated report.

[Export Power BI report to file (preview)](https://docs.microsoft.com/power-bi/developer/embedded/export-to)

![image](https://user-images.githubusercontent.com/54834915/109956199-10263e80-7cec-11eb-879d-a44dba905360.png) 


[Export paginated report to file](https://docs.microsoft.com/power-bi/developer/embedded/export-paginated-report)

![image](https://user-images.githubusercontent.com/54834915/109956904-df92d480-7cec-11eb-8129-cfced669b75f.png)


Thanks,

Kesem

**Comment by calebcwells** [comment]
Hey @KesemSharabi,

I am attempting to export a paginated report. The report in question has three pages each having global slicers and multiple visuals. I followed Paul Inbar's suggestion and searched the Power BI Community for other's having a similar issues but was not able to find something similar.

Thanks,
Caleb

**Comment by AmosHersch** [comment]
Hi @calebcwells ,
For finding the reason you receive Bad Request error for the export request we will need to see the full request message you're sending. So please do at least one of the following:
1. Provide us the request ID from the response you receive with the 403 error 
2. Use Fiddler to capture the network traces during the time you send the request, and send us Fiddler output containing this request 
3. Provide us the exact request body you're sending

We can continue the discussion here, or you can send the requested information to amhersch@microsoft.com and we'll continue the discussion there.

Thanks,
Amos

**Comment by calebcwells** [comment]
Thank you @AmosHersch. I will follow up through email.
