### ISSUE TITLE
Push Datasets Connectivity - update based on new feature of DQ for PBI datasets

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#2865]
In the Q&A section of the RealTime Steaming for PowerBI - it states that push datasets can be connected via live connect
https://docs.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming#can-i-connect-to-push-or-streaming-datasets-in-power-bi-desktop

From the recent announcement of Direct Query over PowerBI datasets - Push datasets are now also available for Direct Query are they not?  This is an important update as Direct Query provides the opportunity to configure Auto Page Refresh and when combined with Push Datasets becomes a very near approximation to real time data inside PowerBI reports!
https://powerbi.microsoft.com/en-us/blog/directquery-for-power-bi-datasets-and-azure-analysis-services-preview/

Please consider validating and updating the Q&A as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46e4476-1fc8-de9c-dc49-ffb8358d22b0
* Version Independent ID: 7af1eac8-5069-8beb-cee4-29c413f7b957
* Content: [Real-time streaming in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-real-time-streaming)
* Content Source: [powerbi-docs/connect-data/service-real-time-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-real-time-streaming.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment @rosscouldrey - I've removed that constraint from the article.
