### ISSUE TITLE
Garbled sentence

### ISSUE THREAD

**Issue by lbendlin** [MicrosoftDocs/powerbi-docs#2866]
For large-scale deployments, you can create a gateway of cluster installations.

should read:

For large-scale deployments, you can create a cluster of gateway installations.

or:

For large-scale deployments, you can create a gateway with multiple cluster members.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93be3185-bbc2-6e4a-0b3b-8c2d0482a148
* Version Independent ID: e9c257ea-9a49-d954-5954-4d14442c49a5
* Content: [On-premises data gateway sizing - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/gateway-onprem-sizing)
* Content Source: [powerbi-docs/guidance/gateway-onprem-sizing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/gateway-onprem-sizing.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
Thanks, @lbendlin! I made that change (I liked your second suggestion best) and the article will republish soon with the correction. I appreciate your contribution.
