### ISSUE TITLE
PowerBI missing Date Hierarchy 

### ISSUE THREAD

**Issue by g33gu11mu77** [MicrosoftDocs/powerbi-docs#2868]
This page includes instruction to change from Date to Date Hierarchy in the Axis field but no such Date Hierarchy is showing up in the dropdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @g33gu11mu77 . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @g33gu11mu77 -- you're right. The simplest solution is to not create the DAX Calendar table. The Date field in the original table works as described. I have a work item to fix this. If I don't find another solution, I'm just going to delete the section on creating the DAX Calendar table. 
You can also just keep going, adding more columns to the DAX Calendar table, such as 
Month name = FORMAT('Calendar'[Date], "mmmm")
Hope that helps!

**Comment by maggiesMSFT** [comment]
Hi, @g33gu11mu77 -- here's a better answer. Create the Calendar table, but don't mark it as a Date table. Then the whole tutorial works. Thanks!
