### ISSUE TITLE
Wrong link in "Step 4 - Create and publish a Power BI report"

### ISSUE THREAD

**Issue by intelliot** [MicrosoftDocs/powerbi-docs#2869]
https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=python#step-4---create-and-publish-a-power-bi-report

"Power BI Desktop samples" links to https://github.com/microsoft/PowerBI-Developer-Samples

(Notice the "Developer" in the URL)

Correct URL should be: https://github.com/microsoft/PowerBI-Desktop-Samples

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=python)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @intelliot . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @intelliot,

Thanks for pointing this out! I fixed the link in [Step 4 - Create and publish a Power BI report](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers?tabs=python#step-4---create-and-publish-a-power-bi-report) and it's now pointing to the right place, [PowerBI-Desktop-Samples](https://github.com/microsoft/PowerBI-Desktop-Samples).

Once again, thanks for getting involved,

Kesem
