### ISSUE TITLE
Clarity is needed of the relationship between the APP and Workspace

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/powerbi-docs#2871]
[Enter feedback here]

When you install an application it is not 100% clear what is in the app or the APPS Relationship to 1 or more workspaces. I'm looking for something that says "Typically you house Reports, Dashboards and DataSets within a particular workspace. The workspace is a boundary of security that can contain Security Roles/Role level security. However there are times that you may want or need to share " UPDATE THIS" and therefore would create an APP. Each App containing [UPDATE THIS] could connect to Datasets [UPDATE Found somewhere] in "My Workspace or ALL workspaces. Each APP has its own permission or uses same permission as the workspace it appears in..............

Hopefully my above text clearly identifies the questions I have around the APPS. ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e83a4fd-44f3-4fe6-9237-3cc56f3965cd
* Version Independent ID: 2fbc77d4-2f45-0e00-585a-de9f4f561e64
* Content: [Install and use apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-app-view)
* Content Source: [powerbi-docs/consumer/end-user-app-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-app-view.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @devman2k -- Thanks for asking! The article you're looking at is for a consumer audience, people who will use but not create apps. See if this article answers your questions better:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps
Thanks!

**Comment by mihart** [comment]
Hi @devman2k ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team

**Comment by devman2k** [comment]
Hi

Do you have the link to the question and the Doc please? I quite make quite a few suggestions and no idea which this is.

Thanks
Bryan

**Comment by maggiesMSFT** [comment]
Hi, @devman2k -- your question was about this article, Install and use apps with dashboards and reports in Power BI - Power BI (https://docs.microsoft.com/en-us/power-bi/consumer/end-user-app-view). My suggestion was to look at this article instead, to see if it answers your questions better:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps
Hope that helps!
