### ISSUE TITLE
Azure SQL Data Warehouse DirectQuery article deprecated

### ISSUE THREAD

**Issue by nielsvdc** [MicrosoftDocs/powerbi-docs#2872]
This page probably needs a make-over, because Azure SQL Data Warehouse does not exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5c2cbb-f3de-c63e-fc74-a5157d5f5c9c
* Version Independent ID: dd280f16-bad8-5f60-f960-208047f6f9b2
* Content: [Azure SQL Data Warehouse with DirectQuery - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-azure-sql-data-warehouse-with-direct-connect#feedback)
* Content Source: [powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @nielsvdc. Thanks for your comment! I am forwarding it on to the doc author for further action.

**Comment by mihart** [comment]
Hi @nielsvdc , 
Thank you for your suggestion.  You are absolutely correct, and we are updating the entire Power BI document set to refer to "Azure Synapse".  We've already started and hope to get through all the updates in a few weeks.  If you find any lingering references to the data warehouse, let us know.
All the best,
The DOCS team
