### ISSUE TITLE
Mentions of Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by nielsvdc** [MicrosoftDocs/powerbi-docs#2873]
This article contains several mentions of Azure SQL Data Warehouse, which does not exist anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 694e3f20-79d0-debf-1449-38a62492424c
* Version Independent ID: 75c298be-5754-c342-cb4d-228b38f8cec7
* Content: [DirectQuery model guidance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance)
* Content Source: [powerbi-docs/guidance/directquery-model-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/directquery-model-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @nielsvdc, Thanks again for your observation. Sending it on to the doc author for consideration.

**Comment by mihart** [comment]
Hi @nielsvdc ,
I just sent you a response on your other similar Git Issue. :-) We truly appreciate the input and we are making these updates over the next few weeks.
All the best,
Michele
