### ISSUE TITLE
Multiple typos

### ISSUE THREAD

**Issue by intelliot** [MicrosoftDocs/powerbi-docs#2876]
> Select the Azure AD app your using for embedding your Power BI content.

`your` should be `you're`

> a. In PowerShell or Command Prompt, navigate to the Python > Embed for your customers > AppOwnesData folder, and execute flask run.

`AppOwnesData` should be `AppOwnsData`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=python#client-id)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Hi @intelliot , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
