### ISSUE TITLE
Hi you need better instructions for how to actually open the TopoJSON map file....

### ISSUE THREAD

**Issue by kmkaczmarek** [MicrosoftDocs/powerbi-docs#2877]
Including this comment after the first instruction regarding what to do with the map is poor and sloppy technical writing, because the reader can't complete the prior step without doing this AND this step is absolutely critical to completing this tutorial.  "See the section titled Getting Map Data, below, for information on how to quickly get map data to test Shape Map."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by msftrien** [comment]
This step is not absolutely critical, but does point the user toward a resource from which they can get map data in the case where they don't have any and just want to test the shape map visual. I'll re-word the note to make this clearer: "To get sample map data you can use to test the Shape Map visual, see the section titled Getting Map Data below."

**Comment by mihart** [comment]
@msftrien @kmkaczmarek  Hi,
Thank you both for working to update the documentation.

**Comment by kmkaczmarek** [comment]
I think the proposed update will work fine and avoid confusion so thank you so much for handling!
