### ISSUE TITLE
Question on how to go back, once dataflow storage is configured to use Azure Data Lake Gen 2 is enabled?

### ISSUE THREAD

**Issue by JayPat65** [MicrosoftDocs/powerbi-docs#2878]
Hi,

Once the dataflow storage is configured to use Azure Data Lake Gen 2, Is there a way to go back without deleting all the dataflows? There will be a lot of redo activity in that case for the end-users.
Can we configure only admin can use the feature and rest of the organization use the traditional storage?

Regards,
Jay

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @JayPat65 . This issue has been assigned to the doc author for review.

**Comment by JayPat65** [comment]
Hey @mihart, Any update on this? Thanks, Jay

**Comment by davidiseminger** [comment]
Thanks for your comment, @JayPat65. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
