### ISSUE TITLE
Paginated reports and gateway lacking detail

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#2879]
The section on paginated reports supporting gateways is rather light, could you add more detail and perhaps a specific visual example doing this with RDL reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Hikmer -- thanks for the suggestion! I'll see what I can do.

**Comment by maggiesMSFT** [comment]
Hi, @Hikmer -- I've updated the article some. The process really is the same, whether it's a Power BI report or a paginated report. I hope that helps!
