### ISSUE TITLE
Reason for long network time in "api/v2.0/me" API

### ISSUE THREAD

**Issue by JaySardhara** [MicrosoftDocs/powerbi-docs#288]
What could be reason for "api/v2.0/me" API taking long time ? 
It seems like something related to AD or token issue. But more insights would be helpful.
Issue is being faced in PowerBI Report server.

**Comment by maggiesMSFT** [comment]
Hi, @JaySardhara -- thanks for your comment! This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.  Thanks!
