### ISSUE TITLE
Estimated release dates need update

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2880]
The estimated release dates listed in this page are in the past, should probably be updated.

https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#limitations-in-premium-gen2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#limitations-in-premium-gen2)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chrisweis.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @chrisweis , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
