### ISSUE TITLE
Editing values doesn't actually work.

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#2881]
I can see why the section on Editing Values seems incomplete - it's because the functionality itself doesn't actually work, right? There's no way to actually edit a value currently. Rather than pretend there was something there, it would be more helpful just to note that this feature is not supported in the current preview.  As it stands, I wasted some time going back and forth between your incomplete description of the Editing Values feature and the actual feature as implemented, trying to understand why I couldn't get it to work.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da6c49a-f7cc-213c-adc3-5b33b76716dd
* Version Independent ID: 2be2786b-c764-c142-0821-24f6a28b2459
* Content: [Smart narratives tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-smart-narrative)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-smart-narrative.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-smart-narrative.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Mike-Honey.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @Mike-Honey ,
I apologize for the delay.  We accidentally assigned this Git Issue to the wrong author.  Now that it is assigned to the correct author, please give her some time to respond.  Thank you.

**Comment by Mike-Honey** [comment]
This was fixed in the product a few months ago.
