### ISSUE TITLE
PBI RS Changelog doesn't have version 15.0.1104.310

### ISSUE THREAD

**Issue by mattfloydgm** [MicrosoftDocs/powerbi-docs#2882]
In the current published changelog, https://docs.microsoft.com/en-us/power-bi/report-server/changelog, it does not have what was changed in version 15.0.1104.310. This October 2020 version is available for download at https://www.microsoft.com/en-us/download/details.aspx?id=57270 since 3/8. Please update change log.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @mattfloydgm .

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @mattfloydgm -- we're in luck! Making this update today. Will be live this afternoon. Thanks for asking!
cc @jtarquino @Petebro-MSFT
