### ISSUE TITLE
Cost for Power BI Premium per user Viewers

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/powerbi-docs#2885]
Will there be a cost for Power BI Premium per user Viewers? I cannot find this information anywhere.

Thanks,
Brad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User FAQ (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @bradrush ,
Thank you for your question. @NickyvVr  is correct.  There is no "unlimited distribution" with PPU. If you have additional PPU question, try asking the Power BI community (community.powerbi.com).
All the best,
The DOCS team
