### ISSUE TITLE
Error in Data Refresh

### ISSUE THREAD

**Issue by jgraham529066** [MicrosoftDocs/powerbi-docs#2889]
The data for the COVID-19 Tracking PowerBI Report is not loading.  This is the error I receive:

Data source error: | The column 'stateFIPS' of the table wasn't found.. The exception was raised by the IDbCommand interface. Table: COVID.
-- | --
Cluster URI: | WABI-US-NORTH-CENTRAL-E-PRIMARY-redirect.analysis.windows.net
Activity ID: | 7c001365-d7e5-424c-bb4d-21bedc23f601
Request ID: | 76ac76c8-b474-e107-af8e-39694c5eadd2
Time: | 2021-03-12 15:57:38Z

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1eccadf-bff1-8010-6eab-f8e357aa35fc
* Version Independent ID: f789d447-2bc7-5cf1-5633-e73b45957f70
* Content: [Connect to the COVID-19 US tracking report - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-covid-19-tracking)
* Content Source: [powerbi-docs/connect-data/service-connect-to-covid-19-tracking.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-covid-19-tracking.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @jgraham529066 -- thanks for letting us know! Assigning to the author to investigate. In the meantime, you might want to ask in the Power BI Community, https://community.powerbi.com/.

**Comment by paulinbar** [comment]
Hi @jgraham529066, thanks for your comment. You've reached the doc team so I won't be able to help with the problem, but I'm forwarding your comment on to someone who may be able to help. Not sure it will be right away though. Thanks in advance for your patience!

**Comment by mihart** [comment]
Hi @jgraham529066 ,
I'm cleaning up our Git Issues queue, and I noticed that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your questions to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
