### ISSUE TITLE
App missing

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#289]
There is no "Microsoft Azure Consumption Insights" app listed.  Just "Microsoft Azure Enterprise".  Was the consumption insights app discontinued too, or moved somewhere else that is not reflected in the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by kfile** [comment]
Thank you for your feedback. I have assigned this issue to the author. She will determine if it's a doc omission or a change in feature.

**Comment by mihart** [comment]
@kfile.  Not mine.  I believe Maggie handles this one.

**Comment by maggiesMSFT** [comment]
Hi, @jordanmills -- I see it in the list of apps in Power BI now. Do you see it? It might not have been showing up during the transition period from "Microsoft Azure Enterprise" to "Microsoft Azure Consumption Insights". 
Thanks!

**Comment by jordanmills** [comment]
It did finally show up.  I tried installing it, but it's blank.  And I don't mean that fields and graphs are empty or zero, I mean that all it shows is a grey background.

**Comment by maggiesMSFT** [comment]
Hi, @jordanmills -- sorry to hear it! This sounds more like a support request than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. I hope that helps!
