### ISSUE TITLE
Please provide all final files

### ISSUE THREAD

**Issue by cwhiteScoe** [MicrosoftDocs/powerbi-docs#2890]
I'm trying my best to follow along with your tutorial, but I'm stuck right in the middle with no errors in VSCode and also no visual displaying :(

I know I must have screwed up a step and just put something in the wrong spot, but because all of your directions are essentially deltas, it is very difficult to find where I went wrong. If you included the final complete pages of code, then I could very quickly check and see what I did.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: abfc5549-16a6-5afd-dac4-64021c25dfa9
* Version Independent ID: b8bf0ca1-1f11-bac0-76fa-cfd6a0d1231b
* Content: [Create a React-based visual for Power BI in Power BI embedded analytics for better embedded BI insights - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual)
* Content Source: [powerbi-docs/developer/visuals/create-react-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/create-react-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @cwhiteScoe -- thanks for the question! Assigning to the author to investigate.

**Comment by KesemSharabi** [comment]
Hi @cwhiteScoe,

You can look into [powerbi-visuals-circlecard-react](https://github.com/microsoft/powerbi-visuals-circlecard-react).

Hope this helps,

Kesem
