### ISSUE TITLE
Parameter Passing Page is Not Correct

### ISSUE THREAD

**Issue by tangi12** [MicrosoftDocs/powerbi-docs#2891]
This page does not seem to be correct based on me trying to figure out how to pass parameters to Power BI.

- spaces = _x0020_
- Ampersand instead of and is used from what I can tell
- %2F between table and field is used
- %20 is wrapped around the parameter type

I have been piecemealing this together and came up with how to pass multiple parameters to one field.

Here is an example code that I am using today, but I cannot figure out how to add a 2nd field.

After the standard Power BI URL  add something like the below replacing "My Filter Table", "MyFilterField", and  "Item" with your selections:
?filter=My_x0020_Filter_x0020_Table%2FMyFilterField%20in%20(%27Item%27,%27Item%27,%27Item%27,%27Item%27,%27Item%27)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @tangi12, thanks for your feedback. I am forwarding it on to the doc author for further consideration.

**Comment by maggiesMSFT** [comment]
Hi, @tangi12 -- belatedly, I'm updating this article based on your feedback! Changes should be live tomorrow afternoon Jan 6 Pacific time.
Thanks!
