### ISSUE TITLE
Premium Per User Service Level

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#2893]
Can you please provide guidance as to the service level of support associated with the new Premium Per User license.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e778bb7-c4db-9318-96f6-acca18d414a1
* Version Independent ID: 4bb4e1dd-1ff4-4330-cb2f-8d8e2cc94042
* Content: [Power BI Pro and Power BI Premium support options - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-support-options)
* Content Source: [powerbi-docs/admin/service-support-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-support-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Hi @itsnotaboutthecell - Good question - let me get those details and I should be able to make the update soon.

**Comment by itsnotaboutthecell** [comment]
Content has been updated and this issue can now be closed.
