### ISSUE TITLE
Azure SQL Database - gateway required?

### ISSUE THREAD

**Issue by vtitte2020** [MicrosoftDocs/powerbi-docs#2895]
The document needs to be updated. Azure SQL Database should not be flagged as "Gateway required = 'Yes'"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @vtitte2020 . This issue has been assigned to the doc author for review.

**Comment by canberra2002** [comment]
Do we have any update about this issue? We also got confused about this part and it was updated from 'No' to 'Yes' in last December if Azure SQL Database really requires gateway a lot of our existing customer will be impacted.

**Comment by mihart** [comment]
Hi @canberra2002 @vtitte2020 
Thank you for your feedback.  I've updated the article and set it to republish.  Gateway is recommended but not required.  
All the best
the DOCS team
