### ISSUE TITLE
Rephrase how 'shared dataflows' are referred to

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#2896]
Hi there. Just a suggestion to rephrase how the word "shared" is used on this page. 

- Several references to "shared dataflows" are confusing. Since the concept of sharing has its own very specific meaning in Power BI (as in sharing an individual report or dashboard), it seems like some readers could get really confused by the "shared dataflows" verbiage. 
- The subheading "Dataflows in Shared" is meant to indicate non-Premium dataflows. I get that. However, with the move to Premium Gen 2 which is not considered dedicated capacity, the term "shared capacity" isn't as relevant anymore I don't think.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ec2a31-ae63-38f7-00e8-234bcedd571d
* Version Independent ID: ff4d4e25-80f5-cac3-49c8-a85b7cf1c476
* Content: [Dataflows Limitations, restrictions and supported connectors and features - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @sqlchick :-) This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! I've tried to clarify that distinction in that section, to make it clearer about Premium vs shared capacities. There is still the concept of shared (non-Premium) capacities.
