### ISSUE TITLE
Power Automate can also restart usage metrics refresh

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#2897]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by GitWesDone** [comment]
The new Power Automate action can also restart a dataset refresh without having to delete and recreate.

**Comment by Bhavik-MSFT** [comment]
Hi @GitWesDone , thanks for the suggestion. I assume you are talking about the Troubleshooting steps for refresh issues. You are correct that Power Automate can perform a refresh which can force the Report Usage model to reload data. Please note that this option may not resolve all refresh issues, for example if an older version is stuck in the workspace.

**Comment by maggiesMSFT** [comment]
Thanks, @GitWesDone and @Bhavik-MSFT ! I've updated the article with a note about Power Automate. Change should be live later today, 29 Mar 21.
Thanks!
