### ISSUE TITLE
Workaround for stale usage dataset does not work for GCC

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#2898]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#feedback)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by GitWesDone** [comment]
The use of the REST API try button does not work for GCC because the API endpoint is different.  This is for the usage dataset.

**Comment by mihart** [comment]
Hi @GitWesDone  , 
Thank you for your question. According to the product team, the reason this doesn't work for GCC is that the endpoints are different and hence the "Try It" button in the REST documentation would not work.  What those endpoints are, would be a question to GCC folks as we normally don't have access to those.  
All the best,
The DOCS team

**Comment by GitWesDone** [comment]
URLs are posted here: https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview#sign-in-to-power-bi-for-us-government
