### ISSUE TITLE
the visual creates incredible amounts of performance issues.

### ISSUE THREAD

**Issue by aray6607** [MicrosoftDocs/powerbi-docs#2899]
I used the feature and everything works fine besides the bugs that have been reporting in the forums, like losing variable names etc. However, the worst part is the performance issue this visual creates in a report. I published a report with this visual and it won't load at all up until I removed the visual from the report... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da6c49a-f7cc-213c-adc3-5b33b76716dd
* Version Independent ID: 2be2786b-c764-c142-0821-24f6a28b2459
* Content: [Smart narratives tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-smart-narrative)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-smart-narrative.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-smart-narrative.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by mihart** [comment]
Thanks for your comment, @aray6607 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @aray6607. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
