### ISSUE TITLE
How much data is available via the custom report route?

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/powerbi-docs#2901]
I note that the data in the report in the workspace is limited to 30-days. However, when connecting to the dataset via PowerBI Desktop a longer period is available. What is the limit in the Power BI dataset? Is it something like 90-days or longer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @buildbod -- thanks for asking! I'll check and get back to you.

**Comment by Bhavik-MSFT** [comment]
Hi @buildbod , there should not be any differences in the history available. When you connect to the usage metrics report dataset from Power BI Desktop, you are using the same data model that powers the in-product reports.
