### ISSUE TITLE
Unable to complete the walkthrough as specified

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2902]
We've been having challenges following this walkthrough. This could be because of versioning changes to PBI Desktop, R or the mice package since the article was written, or due to other reasons.

The [sample .pbix file provided](https://download.microsoft.com/download/F/8/A/F8AA9DC9-8545-4AAE-9305-27AD1D01DC03/Complete%20Values%20with%20R%20in%20PQ.pbix) is missing this line from the instructions:

> dataset <- read.csv(file="<Your File Path>/EuStockMarkets_NA.csv", header=TRUE, sep=",")

As a result, it's throwing this error upon refresh:

```
DataSource.Error: ADO.NET: R script error.

Attaching package: 'mice'

The following objects are masked from 'package:base':

    cbind, rbind

Error in str2lang(x) : <text>:1:17: unexpected symbol
1: Day ~ 0+SMI+SMI missing
                    ^
Calls: mice ... lapply -> FUN -> formula -> formula.character -> str2lang
Execution halted

Details:
    DataSourceKind=R
    DataSourcePath=R
    Message=R script error.

Attaching package: 'mice'

The following objects are masked from 'package:base':

    cbind, rbind

Error in str2lang(x) : <text>:1:17: unexpected symbol
1: Day ~ 0+SMI+SMI missing
                    ^
Calls: mice ... lapply -> FUN -> formula -> formula.character -> str2lang
Execution halted

    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.R.Exceptions.RScriptRuntimeException
```

The other issue, when following the instructions themselves, is that this step does not seem to create the expected result:

> Notice a new column in the Fields pane called completedValues.

No such column is present in PQ. The resulting table looks like this:

![image](https://user-images.githubusercontent.com/1765732/111575157-0c260200-876b-11eb-8598-095cc91116bd.png)

Can you please review the walkthrough and the sample solution .pbix file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- thanks for this question, too! Assigning to the author to investigate.

**Comment by VitalyMCT** [comment]
@maggiesMSFT Is it possible to get an update please? We are still blocked.

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- I'll check with the author. 
Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment, and apologies for the delay. R packages and versioning is managed by the engineering team as their bandwidth and priority allow. Your best bet is to find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
