### ISSUE TITLE
Ambigious reference to "this release"

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2903]
> With **this release**, you can launch your external R IDE from Power BI Desktop and have your data automatically imported and displayed in the R IDE.

Can this reference please be clarified?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d08953c-1912-d458-f1ef-d2d3041f5e41
* Version Independent ID: 18d26011-dd33-6f46-a01d-8cca0e31d040
* Content: [Use an external R IDE with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-ide)
* Content Source: [powerbi-docs/connect-data/desktop-r-ide.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-r-ide.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- thanks for asking! Given that the article was last updated May 2019, it's safe to say the release is pretty far in the past. Does that resolve your question, or do you need an exact release number?

**Comment by VitalyMCT** [comment]
I think simply removing that reference would resolve the confusion.

**Comment by mihart** [comment]
Hi @VitalyMCT , 
Thank you for your suggestion.  We've removed the reference and set the article to republish in the next few days. 
All the best,
The DOCS team
