### ISSUE TITLE
Enabling script visuals

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#2904]
The instructions currently include this step:

> Select some fields from the Fields pane that you want to work with. If you haven't enabled script visuals yet, you'll be prompted to do so.

This step seems to be out of sequence, as simply selecting fields from the Fields pane would result in one of the built-in PBI visualizations being displayed (not R visualization). To enable script visuals one must select the R visual first - that's done in the next step.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d08953c-1912-d458-f1ef-d2d3041f5e41
* Version Independent ID: 18d26011-dd33-6f46-a01d-8cca0e31d040
* Content: [Use an external R IDE with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-ide)
* Content Source: [powerbi-docs/connect-data/desktop-r-ide.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-r-ide.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- thanks for asking! Referring to the author to evaluate.

**Comment by davidiseminger** [comment]
You're right! Sorry about that, I've updated that sequence in the article.
