### ISSUE TITLE
Export underlying data / limitations page

### ISSUE THREAD

**Issue by ShannenR** [MicrosoftDocs/powerbi-docs#2905]
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#export-underlying-data-details mentions it exports related data from tables with *:1 and 1:1 relationships and https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#limitations-and-considerations mentions "If the visualization uses data from more than one data table, and no relationship exists for those tables in the data model, Power BI only exports data for the first table.".

I think this might need to be clarified to say an "active relationship exists" as for me exporting "underlying data" for DAX measures which use in-active relationships returns me only the data for the first table ?

**Comment by msftrien** [comment]
Adding "active" to the doc under limitations/considerations.

**Comment by mihart** [comment]
Hi @msftrien @ShannenR 
Thank you both for your suggestion and update.  Closing this Git Issue now.
