### ISSUE TITLE
How can I pass "today" as a variable instead of hardcoding a date?

### ISSUE THREAD

**Issue by alexleyva68** [MicrosoftDocs/powerbi-docs#2907]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d33d675d-2104-d84a-2385-79011e31282c
* Version Independent ID: ad2ee9b4-c3a8-2dde-a896-aa1e4fe6074c
* Content: [Pass a report parameter in a URL for a paginated report - Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-url-pass-parameters)
* Content Source: [powerbi-docs/paginated-reports/report-builder-url-pass-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/report-builder-url-pass-parameters.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alexleyva68 -- good question! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @alexleyva68 -- have you tried an expression? How about
=Today()

**Comment by alexleyva68** [comment]
this is one that works:
https://app.powerbigov.us/groups/{blah, blah}/rdlreports/{blah, blah} &rp:courthouse=BUR%20&rp:courthouse=NCA%20&rp:courthouse=NCB%20&rp:courtstartdate=2021-03-16

for courtstartdate I have tried the following:
&rp:courtstartdate=Today
&rp:courtstartdate=Today()
&rp:courtstartdate=Now()

None of them work.

**Comment by maggiesMSFT** [comment]
Hi, @alexleyva68 -- OK, got the story. 
"The engine will only convert the “value” of parameters. Passing expressions via URL is not supported in RDL. I think this is the same to on-prem Report Server." 
Hope that helps.
