### ISSUE TITLE
Custom Themes

### ISSUE THREAD

**Issue by lbjennings** [MicrosoftDocs/powerbi-docs#2908]
The create themes button is not available in Power Bi Desktop. I checked the community board and there was discussion of a difference in Power BI Desktop On Premise Edition. Please update to clarify. I want to save my current report theme and use it on new report themes. How can this be done? Your page description features not available for my edition, which should be the most updated version. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @lbjennings -- thanks for asking, assigning to the author.  Can you explain what you mean by the Power BI On Premise edition? Can you check the **File** menu > **About** for the version number?

**Comment by davidiseminger** [comment]
This has been updated in the document, and in recent releases of Power BI Desktop. Thanks!
