### ISSUE TITLE
Instructions should be instructions

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/powerbi-docs#2909]
This document does not actually say HOW to add members to a role. Specifically, it does not say how to access that dialog or where to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-rls)
* Content Source: [powerbi-docs/admin/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @boomalator, thanks for your comment. You've reached the right place. The row-level security documentation definitely has problems and I am currently reviewing it all and will be taking a stab at consolidating and improving it. In that regard your comment is helpful and I'll keep it in mind. It still may be a few weeks until the updated docs are online though. I'm going to close this issue now but I've put an item in my calendar to give you an update in a month's time. In the meantime, if you have questions, you might ask in the [Power BI Community]( https://community.powerbi.com). There are a lot of knowledgeable people active there. Once again, thanks for taking the time to submit your feedback!
