### ISSUE TITLE
Embedded Setup Tool (link) generates broken project

### ISSUE THREAD

**Issue by jaxidian** [MicrosoftDocs/powerbi-docs#291]
I'm not sure who/how to give this feedback, so I'm starting here, hoping somebody can pass this along to the best person/project/team.

When you click on the link for the "Embedding setup tool" (near the top), it produces a couple projects. I'm not sure about the other but the "AppOwnsData" project that it generates fails to compile correctly. Apparently there's some issue with Nougat dependencies.

The error:

&gt; Could not find a part of the path
&gt; '[ProjectPath]\bin\roslyn\csc.exe'.

While looking deeper into this, I stumbled upon this SO post that had [the solution](https://stackoverflow.com/a/34391473/294863). The solution was a one-liner in the Package Manager Console:

`PM > update-package Microsoft.CodeDom.Providers.DotNetCompilerPlatform -r`

This fixed the project and allowed it to run correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed Power BI content into an application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
jaxidian You are correct. There are some fine tuning that needs to be done in Visual Studio before running the sample, such as downloading the appropriate NuGet packages.  In the prerequisites' section, I have you need Visual Studio installed before trying the tutorial.  However, if you feel it will help, I can add the word "configure" to the prerequisites' section.

**Comment by jaxidian** [comment]
@markingmyname 

> such as downloading the appropriate NuGet packages

Right-clicking [solution] -> Restore NuGet Packages does not resolve this issue. I just retested this multiple times again to be 100% certain.

I have to specifically run the `update-package` command for some reason to resolve the issue.

> I can add the word "configure" to the prerequisites' section

If you think that's a viable solution to this problem, perhaps it would be better to elaborate on what you mean by "configure" instead of just adding that word. I mean, the two PCs I repro'd this on have Visual Studio instances that I've been using regularly for many months supporting a variety of different application types with a variety of Azure SDKs installed - it's not like they're a virgin VS install. In my mind, both instances of Visual Studio are very well configured.

Additionally, reloading a virgin copy of the project/solution download still has the problem until I run the `update-package` command even after I got a different instance of that project/solution working. Whatever the problem is seems to stay with the project/solution rather than the instance of Visual Studio.

**Comment by jaxidian** [comment]
@markingmyname VS2017 Community Edition, fully-updated (as of yesterday - I saw an update pop up today that I have not yet installed)

**Comment by markingmyname** [comment]
Hi @jaxidian.  sorry for the delayed response.  I spun up a new environment with VS 2017 and using the "REstore Package" did work for me.

I am still considering adding something, but I need to do a bit more testing.

**Comment by markingmyname** [comment]
@jaxidian I apologize, but I was unable to replicate your issue.  As such, without further data, I do not have enough information to continue to add information to this article.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
