### ISSUE TITLE
March 2021 Update (2.91.383.0) no Paginated pipeline support and secret video

### ISSUE THREAD

**Issue by plapic** [MicrosoftDocs/powerbi-docs#2910]
Why is [Power BI monthly update for March](https://www.youtube.com/watch?v=r88EE4IzZlE) video private?
Also what happened to [support for paginated reports in deployment piplelines ](https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave2/power-bi/deployment-pipelines-support-paginated-reports )which was supposed to be part of the March 2021 release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66293710-49bc-2b37-8899-bd917e70d626
* Version Independent ID: 913116b4-7117-ee02-8aff-5be681896a71
* Content: [What's new in the latest Power BI update - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop#power-bi-monthly-update-video)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @plapic -- thanks for asking. I've assigned to the content author. I know the videos will be coming soon!

**Comment by mihart** [comment]
Thanks for your comment, @plapic . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by maggiesMSFT** [comment]
Hi, @plapic -- great timing! The video is live now, and so is the documentation about paginated reports in deployment pipelines! See https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started?tabs=paginated-reports for details. 
Thanks!

**Comment by plapic** [comment]
Thanks for the info. However when I try to create a new pipeline and select a workspace that contains paginated reports I get
***@***.***D71FC7.48975830]

Regards
Peter Lapic

**Comment by maggiesMSFT** [comment]
Hi, @plapic -- The feature is just releasing today. I recommend trying again tomorrow. Otherwise, you might find a solution in the Power BI Community, at https://community.powerbi.com, or you can get support by going to https://support.powerbi.com. 
Thanks!

**Comment by plapic** [comment]
It appears the updated service version 13.0.15751.56 now supports the paginated reports in Deployment Pipelines.

**Comment by maggiesMSFT** [comment]
@plapic -- great, glad to hear it!
