### ISSUE TITLE
No longer supported

### ISSUE THREAD

**Issue by solvim** [MicrosoftDocs/powerbi-docs#2911]
Connecting to SSAS in power bi service is no longer supported. this doc might confuse people.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d888c803-df07-4052-dd98-70e084f8cf2d
* Version Independent ID: 33753a82-0571-222a-0ff5-28ba18348418
* Content: [SQL Server Analysis Services live data in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/sql-server-analysis-services-tabular-data)
* Content Source: [powerbi-docs/connect-data/sql-server-analysis-services-tabular-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/sql-server-analysis-services-tabular-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **davidi**

**Comment by Minewiskan** [comment]
Done in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/5383
#please-close
