### ISSUE TITLE
"Workspace viewers cannot access the dataset" is misleading

### ISSUE THREAD

**Issue by ThomasKwakman** [MicrosoftDocs/powerbi-docs#2913]
Hi,

"Workspace viewers cannot access the dataset". I was surprised by this sentence as a viewer could - if he has build permission - access the dataset through the global page dataset (i.e. not through the workspace)

Even though this article is not about the distinction between a viewer with and without build permission, perhaps it could be:
"Workspace viewers cannot access the dataset (unless they have build permission)"

Best,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines, the Power BI Application lifecycle management (ALM) tool, process - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for your comment @ThomasKwakman. I am forwarding it on to the doc author for consideration.

**Comment by mihart** [comment]
Hi @ThomasKwakman , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
