### ISSUE TITLE
Use for Teams

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftDocs/powerbi-docs#2916]
Thanks for this great feature! I managed to use the filtered URL in a web page, and even copy to a Teams tab and it works. The trick is to use the html way of entering the address with %20 for the space and %27 for the simple quote 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @Didierma92 . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Didierma92 -- good point! Belatedly, I'm updating the article and including your feedback. Changes should be live tomorrow afternoon Jan 6 Pacific time.
Thanks!
