### ISSUE TITLE
Usage Metrics Report

### ISSUE THREAD

**Issue by tbindas** [MicrosoftDocs/powerbi-docs#2917]
Having issues with the flow of this report. When you go to view usage is filters to a particular report. I am not getting the option to reset to default and the only way to get all of the reports in the workspace to show up are to save a copy of the report and remove the reportid from the filter pane. 

![image](https://user-images.githubusercontent.com/47673380/112048103-1275fe80-8b1c-11eb-8040-42e1fca87d90.png)
![image](https://user-images.githubusercontent.com/47673380/112048166-1efa5700-8b1c-11eb-9d99-f4f6294dfa84.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#create--view-an-improved-usage-metrics-report)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by tbindas** [comment]
https://app.powerbi.com/groups/37e62c22-6657-4047-9163-d1471a11f108/reports/e74cb80b-312b-4c0a-82f9-52c9c88af793/ReportSection141b0c0f1a8c475cab54?noSignUpCheck=1

**Comment by mihart** [comment]
Thanks for your comment, @tbindas . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
