### ISSUE TITLE
Page content seems stale

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2918]
Hi,

I'm trying to find a dependable location for Power BI Desktop version history and release notes, but this page seems to be stale.  Is there a better resource we should be using?  Example: This page shows the latest version is older than the current version of Power BI Desktop (2.91.701.0).

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3105a7f-cb47-9cd9-7144-d5dca900f3f1
* Version Independent ID: 80da6829-c211-d086-df6c-92376e1d640f
* Content: [Change log for Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-change-log)
* Content Source: [powerbi-docs/fundamentals/desktop-change-log.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-change-log.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @jtarquino
* Microsoft Alias: **v-okkyry**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- thanks for asking! I'll check and see if we can get the update.

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- sorry for the delayed response! Of course, in the meantime we've been updating this page regularly. Thanks for your attention!
