### ISSUE TITLE
Unclear definition

### ISSUE THREAD

**Issue by PowerShellToday** [MicrosoftDocs/powerbi-docs#2919]
The point about access needed for the preview are to me unclear.

> Only Azure Administrator roles can authenticate and connect the Sustainability Calculator to company data. This note applies to the December 2020 preview release.

The term "Azure Administrator roles" what does that refer to?
* Azure Ad Admins
* Azure Subscription Admins
* Azure Ea Admins (and if so would it work with department admins)
* Azure PowerBi Admins

Please clarify exactly what "Azure Administrator roles" are needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc4bd0c-b3d7-3ace-ca76-696e9c278d4b
* Version Independent ID: 3c0f58ee-b290-559a-cb6d-b7afe1996760
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator)
* Content Source: [powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @andreabichsel
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by paulinbar** [comment]
Hi @PowerShellToday, I am going to close this issue now. Please feel free to reopen if you think the current docs still need more clarification.
@gabsklad, does this fall within your scope. Do you think the docs sufficiently address the issue mentioned here? Thanks!
