### ISSUE TITLE
Direct Query Automatic Page Refresh - not listed as a Service only feature

### ISSUE THREAD

**Issue by dgosbell** [MicrosoftDocs/powerbi-docs#2920]
If I am not mistaken Power BI Report Server does not support automatic page refresh for Direct Query models since this setting is not visible when authoring a Direct Query based report in Power BI Desktop for Report Server. This should probably be highlighted here as one of the features only available in the Service.

![image](https://user-images.githubusercontent.com/8241830/112233510-b089d600-8c8e-11eb-8cb2-679083dd5d38.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @dgosbell ! I'll confirm and update.

**Comment by maggiesMSFT** [comment]
Hi, @dgosbell -- adding it to the table in this article. Change will be live this afternoon, 25 March. Thanks!
