### ISSUE TITLE
Power BI or Python?

### ISSUE THREAD

**Issue by Ghassan-Alrajeh** [MicrosoftDocs/powerbi-docs#2921]
"Power BI visuals and R visuals aren't currently supported."

Do you mean "Python visuals and R visuals aren't currently supported."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Ghassan-Alrajeh.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @Ghassan-Alrajeh , 
Thank you for your Question.  We've made the update and set the article to republish. I agree it's confusing, but "custom visuals" are sometimes simply referred to as "Power BI visuals".  I've added the word "custom" and set it to republish tomorrow.
All the best,
The DOCS team
