### ISSUE TITLE
Change verbiage from "View" to "Filter"

### ISSUE THREAD

**Issue by TMXemily** [MicrosoftDocs/powerbi-docs#2923]
Under the "What to do if individuals have already used self-service" section, in step 3, there isn't a "Views" section in the admin center under **Users** > **Active Users**. It appears this is now a "Filter" menu because I can create a new filter with the details that the step contains. It just needs updated to reflect Filter instead of View. 

It would also be helpful to note how to locate what licenses are self-service. I can only assume that "(Qualified Offer)" indicates a Self-Service purchase but it isn't mentioned. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c931454d-f706-a12d-5823-54be2594a7a5
* Version Independent ID: 2025949d-a8cf-e241-3e4b-db9050fe1d12
* Content: [Enable or disable self-service sign-up and purchasing - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-disable-self-service)
* Content Source: [powerbi-docs/admin/service-admin-disable-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-disable-self-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @TMXemily.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @TMXemily, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
