### ISSUE TITLE
Power BI Premium per User not mentioned

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2924]
Hello,

It seems this page needs an update based upon the recent announcement of Power BI Premium per User.  One example, the item "The XMLA endpoint can be enabled on both Power BI Premium and Power BI Embedded capacities."

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 942d342d-b542-100b-2eb2-a4aa305da24b
* Version Independent ID: 86c649cf-c841-7600-226a-1befbcf648db
* Content: [Troubleshoot XMLA endpoint connectivity in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/troubleshoot-xmla-endpoint)
* Content Source: [powerbi-docs/admin/troubleshoot-xmla-endpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/troubleshoot-xmla-endpoint.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chrisweis.

I've assigned this issue to the doc author for review.

**Comment by Minewiskan** [comment]
@chrisweis - Thanks for pointing it out.
Addressed in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/5406
#please-close
