### ISSUE TITLE
Personal Bookmarks Limit

### ISSUE THREAD

**Issue by mansfjc** [MicrosoftDocs/powerbi-docs#2925]
I cannot find in the documentation how many personal bookmarks you can have. I thought the limit was initially 20. I am trying to train users and would like to instruct them on how many personal bookmarks they can have. Is there a limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 869a2312-ba01-b3ff-16b3-358ad4d00f5f
* Version Independent ID: dbe26627-e859-42de-7481-f9a52cc04ced
* Content: [Overview of bookmarks in Power BI service reports - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-bookmarks)
* Content Source: [powerbi-docs/consumer/end-user-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-bookmarks.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @mansfjc.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @mansfjc , 
Thank you for your question.  Yes, the max is 20.  We've made the update and set the article to republish. 
All the best,
The DOCS team
