### ISSUE TITLE
Should you be able to drill down in a dashboard?

### ISSUE THREAD

**Issue by dlomara921** [MicrosoftDocs/powerbi-docs#2926]
Should you be able to drill down in a dashboard?  This particular functionality isn't addressed on the doc page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [Intro to dashboards for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboards)
* Content Source: [powerbi-docs/create-reports/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @dlomara921 -- good question! You can't drill down in a visual that's pinned as a regular tile, but you can drill down in a visual if it's part of an entire pinned report page.
https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-pin-live-tile-from-report
I can add that info. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks! I've added drill-down to the table.
