### ISSUE TITLE
Page not valid for desktop app

### ISSUE THREAD

**Issue by karee-ms** [MicrosoftDocs/powerbi-docs#2927]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ede58367-a9ed-f468-5568-71963321d653
* Version Independent ID: 3e599aaa-0931-6680-45f0-a725d177ee22
* Content: [Opt in for preview features - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-preview-features)
* Content Source: [powerbi-docs/consumer/end-user-preview-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-preview-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @karee-ms.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @karee-ms, 
That is correct. The "end-user" consumer content applies to the Power BI service.  Did I answer your question? If not, reply and I'll reopen this Git Issue.
All the best,
The DOCS team
