### ISSUE TITLE
February 2021 Links Named Incorrectly

### ISSUE THREAD

**Issue by ellisjm74** [MicrosoftDocs/powerbi-docs#2929]
Hi! At the bottom of the February 2021 update section, there are links to the 32 & 64 bit downloads.  The URLs point to the correct files, but the labels of the URLs are:
 
**December 2020** version of Power BI Desktop - 32-bit
**December 2020** version of Power BI Desktop - 64-bit

When the URLs should be labeled:

**February 2021** version of Power BI Desktop - 32-bit
**February 2021** version of Power BI Desktop - 64-bit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ellisjm74 -- good catch! updating now. Update will be live tomorrow afternoon, 25 March.
