### ISSUE TITLE
Outdated workspace experience

### ISSUE THREAD

**Issue by bartoszwmalec** [MicrosoftDocs/powerbi-docs#2930]
Could you please provide updated graphics which refers to the New Workspace Look?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @bartoszwmalec . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi @bartoszwmalec -- sorry for the delay getting back to you. This article has been updated. Thanks!
