### ISSUE TITLE
URL Broken in Next Steps sectoin

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerbi-docs#2932]
![image](https://user-images.githubusercontent.com/45298358/112524871-8b17cd80-8d5d-11eb-9caa-dc0951c15c06.png)

You can see in the image attached the Excel workbook URL isn't formatted properly so nothing is clickable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08345191-caf2-6c56-cf95-ecd009dae438
* Version Independent ID: 447ea5e5-d102-1cac-8cbf-1b1136dfb24c
* Content: [Connect to files in OneDrive for a classic workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business)
* Content Source: [powerbi-docs/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-connect-to-files-in-app-workspace-onedrive-for-business.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @edhans -- good catch, thanks! Fixing now. Update will be live later today, 26 March.
