### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by zhenfangyan** [MicrosoftDocs/powerbi-docs#2934]
[Enter feedback here]
The download link doesn't work and returning 404. Please update the link as this version is only compatible to Dynamics 365 FNO which is supposed to available in this page..
https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup-2020-08_x64.exe
![image](https://user-images.githubusercontent.com/18294106/112592389-d951cd00-8e40-11eb-9026-055cddb1ade3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop#power-bi-desktop-monthly-update-video-5)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @zhenfangyan -- thanks for asking! Assigning to the author to investigate.

**Comment by RichdiMSFT** [comment]
Hi @zhenfangyan ,

Please use the version which is installed into the Dynamics 365 Finance and Operations Dev VHD. That version is compatible. I am looking for other options for F&O customers as well. But using the version in the VHD is the best way.
