### ISSUE TITLE
DirectQuery for MySql and MariaDb

### ISSUE THREAD

**Issue by yahorsi** [MicrosoftDocs/powerbi-docs#2935]
Hi Guys,

MariaDb uses the same binary protocol as MySql, but, the MySql direct mode is not supported but for the MariaDb it is.
Is that actually true or just a mistake? Could you please double-check and maybe if it is true and some notes on why and how support for these 2 very similar databases that are using the same client binary protocol is different.

Additionally, please review Gateway supported/required.
For the MariaDb supported=NO and required=Yes,
This a bit confusing.

And same for MySql is YES, YES,

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @yahorsi -- thanks for asking! Assigning to the author to investigate. You can also try asking in the Power BI Community, https://community.powerbi.com/.

**Comment by davidiseminger** [comment]
Thanks for the comment! We've fixed the YES/NO issue for MariaDB. On the support for DQ, those have been checked recently and are up to date. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
