### ISSUE TITLE
Broken  link for how to find your administrator

### ISSUE THREAD

**Issue by weblorin** [MicrosoftDocs/powerbi-docs#2936]
Where it says You need to find one of these people  the link is broken (takes to a 404 page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web#limitations)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @weblorin -- good catch! Fixing the link now. Update will be live later this afternoon, 26 March.
