### ISSUE TITLE
Article links to an old version of Enterprise Deployment whitepaper

### ISSUE THREAD

**Issue by edhans** [MicrosoftDocs/powerbi-docs#2937]
The "Planning an Enterprise Deployment Whitepaper" link at the bottom of this article points to an old July 2018 v2 file.

The newer May 2020 v3.1 that you can get at this URL. https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-faq)
* Content Source: [powerbi-docs/admin/service-premium-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @edhans, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
