### ISSUE TITLE
Link doesnt work on "Get samples for Power BI"

### ISSUE THREAD

**Issue by emkutuk** [MicrosoftDocs/powerbi-docs#2938]
The link to Power BI Report(.pbix file) on the Sales & Returns Sample Report unfortunately doesn't work. 

Link: https://github.com/microsoft/powerbi-desktop-samples/raw/master/Sample%20Reports/Sales%20%26%20Returns%20Sample%20v201912.pbix

**Comment by mihart** [comment]
Thanks for your comment, @emkutuk . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @emkutuk, 
Thank you for your question.  I checked the file and it appears that the link has already been fixed by the author.  Please check and let me know if you are still getting an error.
All the best,
The DOCS team
