### ISSUE TITLE
A suggested imrovement

### ISSUE THREAD

**Issue by russellw999** [MicrosoftDocs/powerbi-docs#2939]
[Enter feedback here]

A nice tutorial.
May i suggest in the data preparation step for the data transforming the source data to transform the existing values to extact the 3 character Month name and    MonthOfYear sort column to ensure the Month name  displays in sorted month order within the Fiscal Year- Month slicer.   Currently from the Source data the contents of the Month column is full date
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 751771a8-ae97-2f7a-45f7-6eab5e30bb98
* Version Independent ID: 69b8d8ce-49e3-feb2-b751-c9a3c26bc501
* Content: [Tutorial: From dimensional model to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-dimensional-model-report)
* Content Source: [powerbi-docs/create-reports/desktop-dimensional-model-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-dimensional-model-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @russellw999, thanks for the suggestion. I am moving your suggestion to our work item backlog for better tracking. Again, thanks for the kind words and taking the time to provide feedback!
