### ISSUE TITLE
No subscription found.

### ISSUE THREAD

**Issue by vladpach** [MicrosoftDocs/powerbi-docs#294]
After runnnig project I have error- No subscription found.
Thank`s for help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23ae77b5-542a-b032-20ec-bf81d041fde0
* Version Independent ID: 70356207-120a-09a8-f8ab-bfdd9b02ad1f
* Content: [Power BI Embedded Migration Tool - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/migrate-tool)
* Content Source: [powerbi-docs/developer/migrate-tool.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/migrate-tool.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@vladpach Thanks for your comment. This looks like a support request rather than documentation feedback – you can get support by going to https://support.powerbi.com. You might find a solution in the Power BI Community, found at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
