### ISSUE TITLE
missing shared dataset icon

### ISSUE THREAD

**Issue by ErjunQ** [MicrosoftDocs/powerbi-docs#2943]
Hi, 
I notice in "Save a copy of a report in a workspace", no.4 Select Save:

[Power BI automatically creates a copy of the report, and an entry in the list of datasets if the report is based on a dataset outside of the workspace. The icon for this dataset is different from the icon for datasets in the workspace: Shared dataset icon

That way, members of the workspace can tell which reports and dashboards use datasets that are outside the workspace. The entry shows information about the dataset, and a few select actions.]

Recently I made the 'save a copy' and the target workspace end up only have the copied report but there is no shared dataset icon under the dataset category. I am wondering if the power bi team removes this feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports#your-copy-of-the-report)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @ErjunQ, thanks for your question. I am checking with the product team and will get back to you. Thanks!

**Comment by paulinbar** [comment]
Hi @ErjunQ,
Indeed it seems that in the new look of workspaces (with list view and lineage view), external datasets are no longer shown in list view. External datasets are shown in lineage view however, and are indicated by a different kind of icon. I can imagine that that might not be the most convenient way to see the external datasets, but that's the way it is now. 

The article you mentioned is indeed out of date, and shows the old look. Updating that article is now on my to-do list. Thanks for bringing this up! Let me know if you have any further questions.
