### ISSUE TITLE
possible extra word

### ISSUE THREAD

**Issue by abnermusonda** [MicrosoftDocs/powerbi-docs#2944]
![21](https://user-images.githubusercontent.com/31890948/113223142-8455f280-9256-11eb-9e34-a978a1a58ed2.PNG)
 "Refreshes are not restricted this at this time."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User FAQ (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @abnermusonda, thanks for reaching out to us. It looks like right after you submitted your feedback the article underwent a significant update, and the issue you pointed out seems to have been resolved. Check out the new article - it's substantially different. Thanks again!
