### ISSUE TITLE
Need clarity for BYOK protection and workbook import

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/powerbi-docs#2945]
This doc bullet:

Excel workbooks (unless data is first imported into Power BI Desktop)

may need to be expanded for 2 modes of Excel workbooks uploads: Connect and Import.  Per research done Import creates service side dataset with API reporting ABF storage mode for that dataset.  This implies Azure storage which should be protected by BYOK.  Note that this clarification if proven to be correct should also be evaluated in the context of multi-geo and added to multi-geo docs if also holds true.  Connect on the other hand keeps the workbook stored on service owned OneDrive and therefore is not protected by BYOK or placed in the remote capacity region (<-needs to be confirmed and possibly documented). 

This question/ask to clarify comes up all the time.

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9a86dc-4be4-d0a2-644d-cb20e3af74fb
* Version Independent ID: d08af8bc-fb3e-e443-7152-abaa0f2df6cc
* Content: [Bring your own encryption keys for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-encryption-byok)
* Content Source: [powerbi-docs/admin/service-encryption-byok.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-encryption-byok.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks Sergei, let me look into this. Thanks!

**Comment by paulinbar** [comment]
Hi @sergeigms, sorry for just getting to this... I have created a work item for this and will close it within the August timeframe. Thanks for pointing this out!
