### ISSUE TITLE
Text boxes are not editable

### ISSUE THREAD

**Issue by jmsmwaura34** [MicrosoftDocs/powerbi-docs#295]
One of the features listed above is that text boxes in the Power BI report should be editable in PowerPoint. I'm not sure if I'm doing something wrong but when I export the report to PowerPoint, the text boxes are not editable in PowerPoint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df1c4c0-80f9-f71a-175f-8362a29ad597
* Version Independent ID: c2a64e2a-ce65-dfb7-588a-381c145ab193
* Content: [Export reports from Power BI to PowerPoint (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint)
* Content Source: [powerbi-docs/consumer/end-user-powerpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-powerpoint.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@jmsmwaura34 Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mihart** [comment]
Hi @jmsmwaura34 
Thank you for your question.  It helped me identify an article that had been duplicated and wasn't yet ready to go live.  I'll be taking down that article, updating it, and republishing soon. 

Take care,
Michele
