### ISSUE TITLE
Block selected data sources

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/powerbi-docs#2950]
Is there any possibility to block certain data sources to be used by users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources?source=docs)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @prashant1380 . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @prashant1380 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
