### ISSUE TITLE
Subscription to reports filtered

### ISSUE THREAD

**Issue by mansfjc** [MicrosoftDocs/powerbi-docs#2951]
There has been an idea with over 900 votes to allow subscriptions from report pages filtered. It has been marked as "planned" for over three years. Is it ever going to be updated to allow this feature?

![image](https://user-images.githubusercontent.com/48630140/113619549-1b3ff780-9627-11eb-88c8-b679542a5c8e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe yourself to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @mansfjc . This looks like a product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com.
