### ISSUE TITLE
Export personalised visuals

### ISSUE THREAD

**Issue by kmarspence** [MicrosoftDocs/powerbi-docs#2952]
Are there any plans to make this feature work when you export? 

We are currently trying to release a standard report to 200 users which they will then go onto personalise, however if we are unable to do this will we have to go  back to square 1 or worse have to write 200 bespoke reports

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615021e0-5504-046d-d6ab-c2d8dee0656f
* Version Independent ID: d9c6ad5a-139f-716e-eb59-473a1f8d73de
* Content: [Let users personalize visuals in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-personalize-visuals)
* Content Source: [powerbi-docs/create-reports/power-bi-personalize-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-personalize-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @kmarspence . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
