### ISSUE TITLE
server resources seem low

### ISSUE THREAD

**Issue by StacyRacks** [MicrosoftDocs/powerbi-docs#2953]
[Enter feedback here]Those memory requirements seem a bit low for a power bi server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f20394b-f5b1-2924-3670-932dba073875
* Version Independent ID: 71ec4d31-53e6-16d4-c250-c38f1bba2ba6
* Content: [Hardware and software requirements for installing Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/system-requirements)
* Content Source: [powerbi-docs/report-server/system-requirements.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/system-requirements.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @StacyRacks . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by StacyRacks** [comment]
The post says that Windows Server 2019, should have a minimum memory assignment of 1 whopping gigabyte and that 4 is recommended.

4 is the minimum, but really to perform optimally the server that runs bi server should have at least 32 GB

[Rackspace]<https://www.rackspace.com/>
Stacy Simpkins
[Facebook]<https://facebook.com/rackspacetechnology>
[Twitter]<https://twitter.com/Rackspace>
[Linkedin]<https://www.linkedin.com/in/stacysimpkins/>
[Rackspace]<https://rackspace.com/>
Email: ***@***.***
Mobile: 2103124000
[Learn More at Rackspace.com]<https://rackspace.com/learn-more>
Achiever + Connectedness + Intellection + Learner + Restorative

Upcoming PTO - Saturday 10APR21 - All Day
Normal Workweek - Tuesday-Saturday 0700-1600 hrs central
