### ISSUE TITLE
Contributor cannot share unless they have reshare permission

### ISSUE THREAD

**Issue by ThomasKwakman** [MicrosoftDocs/powerbi-docs#2954]
Hi,

"You can share dashboards and reports from many places in the Power BI service: Favorites, Recent, My Workspace. You can share from other workspaces, too, if you have the **Admin, Member, or Contributor** role in the workspace. And you can share dashboards and reports in Shared with me, if the owner allows it."

To my understanding, this is slightly off as a Contributor cannot use the share feature for a specific item. In order to share, he needs to be explicitly granted reshare permission on both the report and the dataset.

Could you please tell me if the documentation is correct or not?
Thank you in advance for your time!

Best regards,
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ThomasKwakman.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
@ThomasKwakman -- good point! I've updated the article to reflect that.
Thanks!
