### ISSUE TITLE
Power BI Admin API REST call to obtain activity log event results in not authorized error

### ISSUE THREAD

**Issue by KJLive** [MicrosoftDocs/powerbi-docs#2956]
Despite having set the required Admin API permissions as per this [guide](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication), I kept getting not authorized errors.
After a call with Support, the recommendation is to change the Service Principal's API permissions type from "Application" to "Delegated" AND waiting for a considerable amount of time for the changes to be propagated.

I consider not being able to get authorization a serious blocker.
My feedback is that Microsoft place all the required information for a successful "access" in one set location otherwise having the feature (Admin API) would be completely useless (because it can't be accessed to begin with!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd7616-4a1c-fe01-1b6b-6190bd2fdb63
* Version Independent ID: 93839448-4a4b-5489-14d4-6eebe4b3d34a
* Content: [Enable service principal authentication for read-only admin APIs (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/admin/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @KJLive, this is valuable feedback. I will check out the details and update the doc as necessary. Thanks!

**Comment by paulinbar** [comment]
Hi @KJLive, I'm sorry, a LONG time has gone by, and there have been some changes to the documentation since then to address a particular problem with permissions and authentication. If you have a chance, could you see whether the changes would have affected your problem? Thanks!

**Comment by paulinbar** [comment]
Hi @KJLive, I am going to close this issue for now. Please feel free to reopen if, after consulting the updated documentation, you still encounter the issue. Thanks!
