### ISSUE TITLE
Missing features of Premium

### ISSUE THREAD

**Issue by alan-at-microsoft** [MicrosoftDocs/powerbi-docs#2957]
Why aren't [deployment pipelines](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-overview)  or [Premium features unique to dataflows](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features) even referenced in this document? 

This document is great for answering the "what does Premium give me?" question--and these two topics should not be left out, given 95% of the other Premium specific capabilities are included. A simple sub-heading + link to the primary docs for each of these topics is sufficient IMO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @alan-at-microsoft and @MattRudy -- I've assigned this Issue and related PR to the author for review.
Thanks to you both!

**Comment by davidiseminger** [comment]
Thanks for your work on this!
