### ISSUE TITLE
linked table or dataflow

### ISSUE THREAD

**Issue by ThomasKwakman** [MicrosoftDocs/powerbi-docs#2959]
Hi,

In this excerpt:
Only referenced tables are refreshed when triggered by a source refresh completion. To schedule all the tables, you should set a **schedule refresh on the linked table as well**. Avoid setting a refresh schedule on linked dataflows to avoid double refresh.

The refresh is at the dataflow level, isn't it ?
So the schedule refresh should be set on the dataflow instead of the "linked table".

I am interested in this subject, so please tell me if I'm mistaken or not.

Have a nice day
Best
Thomas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure and consume a dataflow - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-configure-consume)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @ThomasKwakman -- thanks for asking! Assigning to the author to review.

**Comment by davidiseminger** [comment]
The article has been reviewed for accuracy, so I believe it's correct. Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
