### ISSUE TITLE
User

### ISSUE THREAD

**Issue by MelisaCapri** [MicrosoftDocs/powerbi-docs#296]
The steps and menu options outlined in the tutorial do not directly reflect what I am seeing in the application.
Version: 2.62.5222.761 64-bit (September 2018)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Shape and combine data from multiple sources - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@MelisaCapri Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your input, the Desktop does get updated monthly, so some things do change. We update the screens as quickly as we can. Sorry for any inconvenience.
