### ISSUE TITLE
Is this article related to the following capability announced on 2021 release wave 1?

### ISSUE THREAD

**Issue by valenciajdev** [MicrosoftDocs/powerbi-docs#2960]
Hi, is this article related to the following capability announced on 2021 release wave 1? [https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-bi/advanced-network-isolation-ga?source=docs#feature-details](url)

If it's, the article is missing the Service Tags. Please clarify.

**Comment by maggiesMSFT** [comment]
Hi, @valenciajdev -- could you clarify which article you're referring to? Unfortunately that info didn't come through with your question.
Thanks!

**Comment by valenciajdev** [comment]
Hi Maggie,

Here is the link to the document I was referring to: Advanced network isolation (general availability) - Power Platform Release Plan | Microsoft Docs<https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-bi/advanced-network-isolation-ga>
Feedback from page: Private endpoints for accessing Power BI - Power BI | Microsoft Docs<https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links>

Warm regards,

Jose Valencia
Intelligence & Analytics Architect (Power BI & Synapse)
+1 (617) 528-5683 | ***@***.******@***.***> | 5 Wayside Road, Burlington, MA 01803

[Microsoft]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpowerplatform.microsoft.com%2Fen-us%2F&data=02%7C01%7Cjose.valencia%40microsoft.com%7C68b98f882a214ad48d7a08d76dc9013b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637098582395617084&sdata=u8tCSFXITBARtLgNgRyPinvDsRaH38JPcIjLDRmcIuU%3D&reserved=0>

Click here to learn more about the Power BI<https://powerbi.microsoft.com/en-us/>

**Comment by maggiesMSFT** [comment]
Hi, @valenciajdev -- sorry for the delay! I'm going to assume your question got answered, given you were asking about the Release Plan. If not, feel free to ask again!
