### ISSUE TITLE
really badly written

### ISSUE THREAD

**Issue by MartinMcAndrew** [MicrosoftDocs/powerbi-docs#2961]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MartinMcAndrew -- sorry to hear that! Could you provide more guidance on what you'd like to see improved? I realize that some of the screen shots are out of date. We are working through the backlog of updating them.

**Comment by maggiesMSFT** [comment]
Hi, @MartinMcAndrew -- the article has been updated a few times since you wrote this. I hope you find it improved!
