### ISSUE TITLE
Missing noun

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/powerbi-docs#2962]
Hi - this sentence is missing a noun between "only" and "for": 

"The only for Power BI Premium is a 24-hour refresh per dataflow."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ec2a31-ae63-38f7-00e8-234bcedd571d
* Version Independent ID: ff4d4e25-80f5-cac3-49c8-a85b7cf1c476
* Content: [Dataflows Limitations, restrictions and supported connectors and features - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @kasavin -- good catch! Assigning to the author to fill in the missing word. I suspect it's "limit" -- "The only *limit* for Power BI Premium is a 24-hour refresh per dataflow." but I'm checking with the author to be sure.

**Comment by davidiseminger** [comment]
Thanks for the close read. I've added that missing word, and the change should be live later today. Thanks!
