### ISSUE TITLE
This entire page is useless

### ISSUE THREAD

**Issue by rstephensBT** [MicrosoftDocs/powerbi-docs#2964]
Without the actual links to download these previous versions, all this information is pretty much useless.

Versions as of September 2020 and newer completely break compatibility with Dynamics 365 for Operations, and the only way to fix it is download an older version of PowerBI Desktop. (https://fix.lcs.dynamics.com/Issue/Details?bugId=482564&dbType=3&qc=fb519ad5018dd8d206badcba5c54558eb866803a1a39f34f2173c443ae53cce4)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop#august-2020-update-2844610)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @rstephensBT - I'm sorry the page isn't helpful. It serves as a list of when features became available, and links to all available previous versions. Versions that are no longer available aren't listed. You'll need to provide feedback on https://ideas.powerbi.com/ideas/.

**Comment by rstephensBT** [comment]
You said "links to all available previous versions."  That's the problem. There are many versions listed (all prior to the September 2020 version) that ARE on the page, but have NO download links.

**Comment by maggiesMSFT** [comment]
Hi, @rstephensBT -- ah, to clarify: Previous versions are _listed_. Only _available_ previous versions have links. Is that clearer? Thanks!

**Comment by rstephensBT** [comment]
It's clearer, but still unhelpful.  Only Microsoft would make one of their products incompatible with another one, officially tell people that their only remedy is to download X specific version from a specific page, then specifically make X specific version unavailable on that page.
