### ISSUE TITLE
Salesforce Template Apps using implicit measures, inactive relationships?

### ISSUE THREAD

**Issue by gmeronek** [MicrosoftDocs/powerbi-docs#2967]
I appreciate anytime there's available PBIX templates we can download, but I was very surprised that when I downloaded the Salesforce template apps from [https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-samples](url), I saw a number of puzzling choices.

- When I looked at the model for the SalesforceSalesManager PBIX, I saw a ton of inactive relationships. I thought that perhaps those inactive relationships were being used in clever related columns or measures. That doesn't seem to be the case, so I'm curious as to what we should learn from them.
- When I looked at the report view, I was surprised to see that all the measures are implicit measures rather than defined measures. Is that the right practice to show in a template app? Wouldn't it be better to use defined measures to show users what's possible?
- When I reviewed the SalesforceSalesRep model, I was even more surprised to see that the Lead and User table aren't related to the other tables and aren't used. Is that an oversight? Wouldn't it be better to remove them from the model?

I am glad to steer users towards template app examples whenever I can, but I'd hesitate to steer them to these in their current state as I'm not sure they reflect good Power BI modeling habits. There's lots of opportunity here so I hope they iterate!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b777f61-d4cf-bc8e-64b5-43c2e695051b
* Version Independent ID: 20c2b71c-b805-b5e1-4de3-f5bc51de91e5
* Content: [Template apps samples - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-samples)
* Content Source: [powerbi-docs/connect-data/service-template-apps-samples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-template-apps-samples.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @gmeronek . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
