### ISSUE TITLE
Dynamic Titles Using the Tab Name

### ISSUE THREAD

**Issue by ChiliGuy** [MicrosoftDocs/powerbi-docs#2968]
I would like to create a dynamic title for each tab in my PBI report using the name I've entered on the tab. For instance, if I've named a tab "Sales by Category" I want to build a title in the report that pulls from the tab name so the title displays as "Sales by Category". I can then use the values selected in the slicer on that tab so the title will update. For instance, if I have a slicer for "Year" and I select "2021", the title would update to say "Sales by Category for 2021".

This way I can create one measure to build the dynamic title that I can put on each tab of the report. Right now, it looks like I have to build a separate measure for each tab... as Patrick says, I'm not lazy, I just like to be efficient".

Steve

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28a270e6-b0c1-bb57-831c-ce75a4d42085
* Version Independent ID: f831c935-823e-be44-02b8-c4145fe89d28
* Content: [Expression-based titles in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-format-visual-titles)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-format-visual-titles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-conditional-format-visual-titles.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @ChiliGuy . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
