### ISSUE TITLE
Confused by "business user" and "designer" use on this page. Not clear what is meant by those as neither are references to a particular type of Power BI license.

### ISSUE THREAD

**Issue by markvsql** [MicrosoftDocs/powerbi-docs#2969]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6b635cd-366c-c336-bc9f-ed164a92f966
* Version Independent ID: 5399c905-cef4-a156-3e76-e211a3c1945a
* Content: [What is a dashboard and how do I open it? - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-dashboards)
* Content Source: [powerbi-docs/consumer/end-user-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @markvsql ,
I've updated the article with definitions of "business user" and "creator".  Thank you for your suggestion.
The DOCS team.
