### ISSUE TITLE
Benefits of SharePoint over OneDrive For Business

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#297]
Given that most dashboards contain business data, I would recommend that most user put their PowerBI files into SharePoint sites instead of OneDrive because if they leave the organization, their OneDrive For Business site could be closed. It is usually better to keep business documents like these in SPO sites. Please add something about this to the guidance above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset created from a Power BI Desktop file on OneDrive or SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-desktop-file-onedrive)
* Content Source: [powerbi-docs/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@DeanGross Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your input, @DeanGross - much appreciated.
