### ISSUE TITLE
Why is all this necessary?

### ISSUE THREAD

**Issue by erickpolsky** [MicrosoftDocs/powerbi-docs#2970]
This is a GREAT workaround.  I'm a little sad that we have to jump through so many hack-like hoops to connect Microsoft Excel data stored in Microsoft OneDrive to a Microsoft Power BI dataset.  Isn't this a pretty common pattern they would expect customers to need?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/connect-data/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @erickpolsky . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
