### ISSUE TITLE
Ability to add line formula to Scatter Plot trendline. You competitors have had it for years!

### ISSUE THREAD

**Issue by ennismenace** [MicrosoftDocs/powerbi-docs#2971]
I love to use trendlines and my user love to see the formulas.  When is this going to be added to Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
