### ISSUE TITLE
How to Embed PowerBi Reports with Blazor WebAssembly

### ISSUE THREAD

**Issue by stevozilik** [MicrosoftDocs/powerbi-docs#2973]
I'm struggling to adapt the examples for Blazor WebAssembly, could you please provide some guidance/examples for Blazor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90078026-b608-ccf2-f3ef-58021b484f75
* Version Independent ID: e51ab568-5610-ff18-c5c0-4d2f27935dfa
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-your-organization?tabs=net-core)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @stevozilik -- thanks for your question! Assigning to the author for consideration.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @stevozilik. 

I'm not familiar with Blazor and would not be able to help you with adapting the current example.

I suggest that you open a support request.

You might also find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

Thanks,

Kesem
