### ISSUE TITLE
Workspace Tenant setting prerequisite missing in the doc

### ISSUE THREAD

**Issue by satyakeerthikotte** [MicrosoftDocs/powerbi-docs#2974]
HI Team, 

I am Satya Kotte from Power BI CSS. I had a case where the "Save a copy" settings was grayed out. Based on this doc we looked into all the prerequisites and cx had both pro and build permissions; however she was still not able to see this option. After checking the tenant settings to just check if there is any setting it could effect this feature; I found that disabling Use datasets across workspaces under Workspace tenant settings is the cause of the issue. However, no where in our doc mentions about this setting. 
![image](https://user-images.githubusercontent.com/27025039/114898532-cbf08880-9dd7-11eb-8636-c03bb14077c9.png)

So if you could update this doc include this in the prerequisite it would be great. Thanks! 

Stay Safe! 
Satya Kotte 
sakotte@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports?source=docs#feedback)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @satyakeerthikotte -- thanks for letting us know! Assigning to the author to address.

**Comment by paulinbar** [comment]
Hi @satyakeerthikotte, do you know where the user was using when they saw the grayed out Save a copy? Were they in lineage view? List view? In the datasets hub? Somewhere else?

**Comment by satyakeerthikotte** [comment]
customer was viewing in the list view.
I am able to replicate the issue as well. Just checked I see the issue in both list and lineage view
![image](https://user-images.githubusercontent.com/27025039/115528534-be178900-a257-11eb-9ea2-bdae861706c3.png)
![image](https://user-images.githubusercontent.com/27025039/115528452-aa6c2280-a257-11eb-84fd-78f0b2712010.png)

**Comment by maggiesMSFT** [comment]
Hi, @satyakeerthikotte -- thanks for bringing this to our attention! Closing this issue; I know you and @paulinbar will follow up offline.
Thanks again for helping improve the docs!
