### ISSUE TITLE
Need more info on deploying datasets connected to dataflows

### ISSUE THREAD

**Issue by DavidPeraza** [MicrosoftDocs/powerbi-docs#2975]
Hello, I'm from Power BI CSS.

We recently had 3-4 cases where deploying from one stage to the next failed when the dataset was connected to a dataflow in the same workspace. This was working for some time, but PG has clarified that this scenario is not supported.

However, if the dataset and source dataflow are in different workspaces, then the deployment works correctly. We would like to see a reference to this particular scenario in the documentation, just in case more customers are using datasets and dataflows with deployment pipelines.

Please contact me if I can be of help in explaining this scenario in more detail.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c40e327-d8c8-3011-e68b-7694d0ed2b04
* Version Independent ID: 3947ee9f-58b0-763c-8b56-b21cfdcbaac1
* Content: [Troubleshoot deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-troubleshooting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-troubleshooting.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @DavidPeraza -- thanks for the info! Assigning to the author to consider.

**Comment by KesemSharabi** [comment]
Hi @DavidPeraza,

Let me check this with the PM and get back to you.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @DavidPeraza,

One more thing while this is being checked - at present dataflow isn't supported so whatever the outcome of the devs check is, deploying dataflows can't be guaranteed.

[Unsupported items](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-process#unsupported-items)

![image](https://user-images.githubusercontent.com/54834915/115229323-94594780-a11b-11eb-95ba-7c02727a1dbb.png)

Thanks,

Kesem

**Comment by DavidPeraza** [comment]
Hey Kesem,

Thanks for reaching out. I realize the documentation does specify that Dataflows cannot be deployed, which is good.
I think the extra bit of info we need is on selective deployments. Selectively deploying only a dataset that connects to a dataflow in the same workspace fails.
Hope the attached image helps clarify a bit.

Thanks!

David Peraza Cortes
Support Engineer
Microsoft
Power BI Accelerated Customer Experience
Office: 01 81 8133 3666
***@***.******@***.***>
Working hours: 9:00am-6:00pm CST
***@***.***D7351F.99044090]

**Comment by KesemSharabi** [comment]
Hi @DavidPeraza,

Here's the PM's response:

As part of our work to fully support dataflows within deployment pipelines, we currently have a bug in this area. We’re fixing the bug and are expecting it to be solved in two weeks.
Customers can either wait for the bug to be fixed, or remove the dataflow from the pipeline and re-connect the dataset to the dataflow once it’s in an external workspace.
This is how to do it:
1.	Export the dataflow from the relevant workspace in the pipeline.
2.	Import the dataflow into a workspace external to the pipeline and refresh the data.
3.	Open the dataset’s PBIX file in Power BI Desktop, and re-connect the dataset to the new dataflow instance.
4.	Upload the new PBIX version to the dev stage in the pipeline.

Hope this helps,

Kesem
