### ISSUE TITLE
relationship between AllowAdHocSubscriptions and AllowSelfServicePurchase 

### ISSUE THREAD

**Issue by ryeguy637** [MicrosoftDocs/powerbi-docs#2976]
[Enter feedback here]
It would be helpful if this article indicates whether self service purchase is possible if the allowadhocsubscriptions is set to false.

In other words, if you set AllowAdHocSubscriptions to false, does that make blocking selfservice purchase using the mscommerce cmdlets unnecessary?  

Or are these two settings mutually exclusive?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c931454d-f706-a12d-5823-54be2594a7a5
* Version Independent ID: 2025949d-a8cf-e241-3e4b-db9050fe1d12
* Content: [Enable or disable self-service sign-up and purchasing - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-disable-self-service)
* Content Source: [powerbi-docs/admin/service-admin-disable-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-disable-self-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @ryeguy637 -- thanks for asking! Assigning to the author to investigate.

**Comment by mihart** [comment]
Hi @ryeguy637 , 
Thank you for your question. I checked with our M365 guy and he told me that these 2 settings are independent.  Self-service purchase uses the mscommerce module (enable/disable options).  The self-service sign up uses AllowAdHoc.  If you want to block self-service sign up AND self-service purchase, you'd need to disable both.  
All the best,
The DOCS team
