### ISSUE TITLE
Not clear what is needed to export summarized data

### ISSUE THREAD

**Issue by Heniekwpracy** [MicrosoftDocs/powerbi-docs#2977]
Hi Team!
This sentence in "Limitations and considerations" is confusing for me:
"To export the data from a visual, you need to have Build permission for the underlying dataset."

because in this article: [https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions](url)
you write:
"Users also need Build permissions to work with the data outside Power BI:
To export the underlying data."

Also here: [https://powerbi.microsoft.com/pl-pl/blog/change-to-summarized-data-export-behavior-with-build-permission/](url)
"We are adjusting our approach based on your feedback.  Specifically, we will allow users with the Read permission to export summarized data from a visual.  This change will be rolling out over the next week."

So as I understand, you DO NOT NEED Build permission to "export the data from a visual".
You need it to export underlying data specifically. This is not needed to export summarized data.

Hopefully I got this right :)
Cheers,
Adam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data#limitations-and-considerations)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @Heniekwpracy -- yes, you've got that right! We can update the articles to be clearer that you only need Build permission to export the underlying data, and not the summarized data in the visual itself.

**Comment by KesemSharabi** [comment]
Hi @Heniekwpracy,

Yes, I believe you got it right and that this issue was resolved in the documentation.

Thanks,

Kesem
