### ISSUE TITLE
Clarification needed on dataset vs report download

### ISSUE THREAD

**Issue by SteveFringe** [MicrosoftDocs/powerbi-docs#2978]
Hello,
according to the document:
Datasets with incremental refresh can't be downloaded to a .pbix file.
Datasets enabled for large models can't be downloaded to a .pbix file.
Datasets modified by using the XMLA endpoint can't be downloaded to a .pbix file.

But in reality it seems that even reports that are using such datasets (via live connection) can't be downloaded as pbix.
Example: 
Dataset abc.pbix has incremental refresh. 
Report rep.pbix (created in PowerBI desktop and published to the PBI services) is using live connection to the published dataset abc.pbix (same workspace). 
Should the user be able to download the report rep.pbix as pbix? 
Thank you in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @SteveFringe -- thanks for asking! I'll investigate and report back. 
In the meantime, consider asking the community, https://community.powerbi.com/

**Comment by SteveFringe** [comment]
hi @maggiesMSFT, unfortunately our company IT policy is so stupid that it doesn't allow posting into community and i can't login without ActiveDirectory, if i understand correctly.

**Comment by SteveFringe** [comment]
hi @maggiesMSFT is there any feedback on this? I'm also not sure why this issue has "needs-more-info" label. i think i've provided all the info in the initial question

**Comment by paulinbar** [comment]
Hi @SteveFringe, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. We'll update the docs when we get clarification on the question you raised. Thanks for providing your feedback!
