### ISSUE TITLE
Great tutorial

### ISSUE THREAD

**Issue by mxeliezer** [MicrosoftDocs/powerbi-docs#2979]
Great tutorial on data handling, easy to follow and to apply. Everything works fine for me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0f7e4-74cd-dadb-c2ce-4b6c0c511e20
* Version Independent ID: 0d14b983-c47a-1fa7-7103-15182735f26b
* Content: [Tutorial: Combine data from Excel and an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mxeliezer -- thanks for letting us know! Assigning the author so he's aware.
