### ISSUE TITLE
 R scripts is now supported in Personal gateway ,please update Document

### ISSUE THREAD

**Issue by v-kerwan** [MicrosoftDocs/powerbi-docs#298]
R scripts is now supported in Personal gateway ,please update Document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea871f0a-018e-0335-7261-f9d9d2232e36
* Version Independent ID: 345a024a-5964-0979-494f-6f7196a3c929
* Content: [On-premises data gateway (personal mode) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode)
* Content Source: [powerbi-docs/service-gateway-personal-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-personal-mode.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your suggestion, @v-kerwan. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
@v-kerwan - thanks, updated the doc
