### ISSUE TITLE
Cannot create live connection to Power BI dataset if dataset has a live connection to on-prem SSAS

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerbi-docs#2981]
It seems that is not possible to create a live connection to a Power BI dataset from Power BI desktop if that dataset contains a live connection to an on-premises Analysis Services model.
If true, please add a point to the Limitations and Considerations section.
Repro steps:
1. From Power BI Desktop establish a connection to an on-prem Analysis Services model.
2. Save and publish the report to the Power BI service.
3. Close and re-open Power BI Desktop.
4. Attempt to create a live connection to the Power BI dataset in the Power BI service.
The connection attempt fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment @Dan1480. I have forwarded your observation on the the doc author for further consideration.

**Comment by davidiseminger** [comment]
Thanks for your comment! This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. If you learn from the community or support that this article does indeed need updated, feel free to reopen this with the information and reference.
