### ISSUE TITLE
Needs clarification of enterprise deployment path for Analyze in Excel

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2982]
This page has no mention of how to deploy Analyze in Excel across an enterprise via software packaging (when users don't have local administration rights on a PC).  Which software should be deployed?  Where is the version history?  How does this software relate to other similar software such as "Analysis Services client libraries" or "Microsoft® Analysis Server® Feature Pack"?  What MS Office versions are/aren't supported?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- thanks for your questions! I'll investigate and get back to you.

**Comment by paulinbar** [comment]
Hi @chrisweis, it looks like this page has changed significantly since you provided your feedback. I'm going to close this issue now, but please feel free to reopen if you think your questions haven't been sufficiently addressed. Thanks!
