### ISSUE TITLE
Are Paginated Reports also supported in A4-A6 SKUs?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#2983]
Hello,

In this document, it states "With Premium Gen2 and Embedded Gen2, Paginated reports are supported on the EM1-EM3 and A1-A3 SKUs."  That verbiage leaves it unclear whether Paginated reports are/aren't also supported in A4-A6 SKUs.  If Paginated reports are supported in A1-A6 SKUs, then should this text be modified?

Section URL is: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#paginated-reports

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#limitations-in-premium-gen2)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @chrisweis . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @chrisweis,

The [Paginated reports](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#paginated-reports) section has been changed to indicate that paginated reports are supported 

![image](https://user-images.githubusercontent.com/54834915/143459689-14b27d13-6bff-4e7b-ba9d-56137dd2c044.png)

Thanks,

Kesem
