### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#2984]
Please add a awareness in this document: "Please ensure your datasource provide OData service before using Odata connector "
Also referencing this document: https://docs.microsoft.com/en-us/powerquery-m/odata-feed
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29bfbd4c-5149-93be-3982-81af6852a5dd
* Version Independent ID: 75460ed0-c7d9-fe67-8010-b843661dc66e
* Content: [Connect to an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-odata)
* Content Source: [powerbi-docs/connect-data/desktop-connect-odata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-odata.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @KerryWang94 and thanks for your comment. I think that's fairly self-evident, that an OData source must have an OData service.
