### ISSUE TITLE
Wrong screenshot on section Invite external users to your organization

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/powerbi-docs#2985]
Screenshot is wrong on section: https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#invite-external-users-to-your-organization
![image](https://user-images.githubusercontent.com/45423022/115407996-68f05e80-a1e8-11eb-9a31-9ac23ed528c4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @martaequintao, thanks for taking the time to notify us. I have fixed the image. It should be online in about 3 hours. Thanks again!
