### ISSUE TITLE
Since OpenSSL no longer works, page needs updated

### ISSUE THREAD

**Issue by pcgeekus** [MicrosoftDocs/powerbi-docs#2986]
Since OpenSSL no longer works, page needs updated to use only SAP's Encryption Library.
Jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eed1fef3-04bf-6ea9-d64a-bbdace3ef380
* Version Independent ID: 386311c5-3d43-2484-7a2e-56dac972ff20
* Content: [Enable encryption for SAP HANA - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-sap-hana-encryption)
* Content Source: [powerbi-docs/connect-data/desktop-sap-hana-encryption.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-sap-hana-encryption.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @pcgeekus . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
This has been fixed - thanks!
