### ISSUE TITLE
The article doesn't touch the subject of querying two datasets

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#2988]
This article doesn't talk about connecting to two datasets at the same time. My understanding is that it doesn't work, but it's not listed as a limitation or as a preview limitation. If this is a limitation, it would be good if it's mentioned in the article

This is probably a duplicate of isssue #2981, but I might be slightly different

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b13312-84ac-72b4-483f-5d8169ecf1e0
* Version Independent ID: f648e18b-55f9-9167-a6f1-98be8180bac1
* Content: [Using DirectQuery for datasets and Azure Analysis Services (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @erapade . This issue has been assigned to the doc author for review.

**Comment by MichaelFoundation** [comment]
@PRMerger8 [Jan Michael Omondang](1500) Data complex will certify if those codes are within the listed log prefixed-update. 

J

**Comment by davidiseminger** [comment]
It states that this is possible in the first paragraph.

**Comment by erapade** [comment]
@davidiseminger:  I can’t see that it’s described in the first section. The documentation describes how to connect to one Cube and one Excel file, but not two Cubes. IE what about if also Budget would have been a Cube (not an Excel file). This is not addressed at all and not listed as a limitation
