### ISSUE TITLE
Could you please update R Script is not supported with On-Prem Gateway and user have to use personal Mode?

### ISSUE THREAD

**Issue by v-kerwan** [MicrosoftDocs/powerbi-docs#299]
Could you please update R Script is not supported with On-Prem Gateway and user have to use personal Mode?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @v-kerwan. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by DieselAnalytics** [comment]
I am confused because this is still opened but it is listed in the limitation section. Should this be closed or are R scripts available in the on-premises data gateway now?

**Comment by mgblythe** [comment]
@DieselAnalytics - article was updated, closing this now.
