### ISSUE TITLE
Refresh timeout

### ISSUE THREAD

**Issue by vtitte2020** [MicrosoftDocs/powerbi-docs#2990]
In the section “Scheduled Refresh Timeout”, in the specific line “ If you encounter this limit, consider reducing the size or complexity of your dataset, or consider breaking the dataset into smaller pieces.” 

Last line “Breaking the dataset into smaller pieces” doesn’t make sense and needs to be clarified. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshooting refresh scenarios - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @vtitte2020 -- thanks for asking! Assigning to the author to resolve.

**Comment by davidiseminger** [comment]
Thank you for your input, I've reworded that sentence for clarity.
