### ISSUE TITLE
Publish an app in Power BI by cmdlets

### ISSUE THREAD

**Issue by JerrySmithLu** [MicrosoftDocs/powerbi-docs#2991]
How to create an app from workspace by powershell script?

**Comment by MattRudy** [comment]
Hey Jerry, you might want to check out [microsoft/powerbi-powershell](https://github.com/microsoft/powerbi-powershell), that Repo contains most PowerShell scripts for Power BI administration.

**Comment by maggiesMSFT** [comment]
Hi, @JerrySmithLu -- did @MattRudy answer your question? Thanks, @MattRudy !

**Comment by maggiesMSFT** [comment]
Hi, @JerrySmithLu -- hearing no further from you, I'll assume @MattRudy answered your question. If not, feel free to resubmit your question.
