### ISSUE TITLE
"Limitations in Premium Gen 2" section is incomplete

### ISSUE THREAD

**Issue by slavatrofimov** [MicrosoftDocs/powerbi-docs#2993]
Please enhance the "Limitations in Premium Gen 2" section by adding the details that workload management capabilities defined on a capacity are not available in Gen 2 capacities, such as:

- Query Timeout (seconds)
- Max Intermediate Row Count
- Max Result Row Count
- Etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @slavatrofimov -- thanks for asking! Assigning to the author to look into.

**Comment by KesemSharabi** [comment]
Hi @slavatrofimov,

This document was updated. Please review the new document [What is Power BI Premium Gen2](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is), and its [limitations](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is#limitations-in-premium-gen2) section.

Thanks,

Kesem
