### ISSUE TITLE
It's not possible to remove gateways or data sources

### ISSUE THREAD

**Issue by reiniroosh** [MicrosoftDocs/powerbi-docs#2995]
This document for removing a gateway datasource says to click on the More Options, but those don't seem to appear, and so there's no way to remove a data source from powerbi.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Add or remove a gateway data source - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by maggiesMSFT** [comment]
Hi, @reiniroosh -- thanks for your question! Assigning to the author to investigate.

**Comment by maggiesMSFT** [comment]
Hi, @reiniroosh -- got you an answer already! First, the More options may be collapsed down to just 3 dots, ... Do you see that?
If not, you need to open a support ticket at https://powerbi.microsoft.com/en-us/support/.
Hope that helps!

**Comment by reiniroosh** [comment]
Umm, yes, and no.

I do NOT see the three dots. Until I hover my mouse over the space where they would be.
You can see how that could cause a lot of confusion?
There's no visual indicator at all that something is there until you hover your mouse in the magic spot.

![image](https://user-images.githubusercontent.com/7827702/115931164-84a17200-a43f-11eb-9f3f-2b53614c178f.png)

![image](https://user-images.githubusercontent.com/7827702/115931188-91be6100-a43f-11eb-9b62-5e1651f22df6.png)

**Comment by maggiesMSFT** [comment]
@reiniroosh -- that is really useful feedback. Could you enter it in the Ideas site, so it will get to the product team directly?
https://ideas.powerbi.com/ideas/
Thanks!
