### ISSUE TITLE
Add a section on how to Delete the group

### ISSUE THREAD

**Issue by HappymediaDz** [MicrosoftDocs/powerbi-docs#2996]
Hi,

Maybe it is good to add a section on how to remove or delete the group. I was looking for a simple "**Delete**" command like for a meaure. Instead of that, we have to use the "**Delete from model**" and generally I'm affread of this command because I thougth it was about remouving all the table from the model not just the group

Regards,
Mehdi
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1e0b0a-ff95-b2f7-44db-5c07ca876ab4
* Version Independent ID: 1c975595-bf44-5f66-3e08-02c3e8e63797
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/create-reports/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @HappymediaDz -- thanks for your suggestion! Assigning it to the author to look into it.

**Comment by davidiseminger** [comment]
I believe you're asking how to ungroup a group you've created - you simply select the group, and choose the Ungroup button.
