### ISSUE TITLE
just a clarification

### ISSUE THREAD

**Issue by Rmatey** [MicrosoftDocs/powerbi-docs#2998]
Just wanted to point out that it is (at least on my version) "rssrvpolicy" rather than the stated "rssvrpolicy".

That is all. Good article!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e263433-a204-3888-ea1b-d4368c7798f2
* Version Independent ID: fe979f1f-b639-12a2-96cc-247be7e75785
* Content: [Upgrade Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/upgrade)
* Content Source: [powerbi-docs/report-server/upgrade.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/upgrade.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Rmatey -- I bet you're right! Just checking to confirm.

**Comment by maggiesMSFT** [comment]
Hi, @Rmatey -- yes, you're right. We updated the article a while ago, but I didn't get back to you until now. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @Rmatey -- you're right! Sorry for the delay, I have fixed it. Update will be live this afternoon Jan 6 Pacific time. Thanks so much for catching that!
