### ISSUE TITLE
Dead link roundup

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/powerbi-docs#30]
Instead of posting individual issues I figure this might be easier for our inboxes.
Here is a gist of what I ran and what it found https://gist.github.com/nschonni/5e9b44714eb128df80fec16319447da8
Caveats:
    - markdown-link-check has no concept of the redirect.json so there are false positives
    - can search in file for "dead" to see the flagged issues
    - I've PR'd things for typo-ish ones, but a bunch are fwlink or other permalinks that I'm not sure how you fix
    - False positives for stuff that requires login, like my.visualstudio.com. It can hand auth headers, but I didn't do that
    - The video link format used with DocFx is custom and isn't understood by markjs (or other parsers)

Keep up the great work ❤️ ❤️ ❤️

**Comment by mgblythe** [comment]
Hi @nschonni -- thanks for doing this! And sorry for taking so long to get back to you. I'm running a QA report on internal and external broken links, and I'll update here when I'm done. We have a lot of redirects b/c we moved repos/folder structures a while back, hence the false positives.

**Comment by mgblythe** [comment]
Even leaving out the ones that are redirected, we have a lot of broken links, esp. to external content. We'll address these in our next sprint in July. Thanks again for the feedback!

**Comment by nschonni** [comment]
Fixed up the ones I could figure out in #45 and updated the gist

**Comment by mgblythe** [comment]
We made a bunch of link fixes in the last couple days. Our report looks clean at this point. Thanks again @nschonni!
