### ISSUE TITLE
PowerBI training content no in line with data source we get

### ISSUE THREAD

**Issue by rafaelhenck** [MicrosoftDocs/powerbi-docs#300]
There are two erros, which second has much more impact:

1) There are differences in the data source we get from the "Retirement States" websites and see in our PowerBI and what the training shows. For instance, we don't see a column "Senior". As a result of that, the initial calculation proposed for "New Rank" column has to be different by not having "Senior" component and dividing by 7 instead of the instructed 8.

But that's easily identified so we can progress the step-by-step training.

2) Here's the point which we can't progress in the training. There's a session which we need to re-write the formula bar in the "New Rank" column (below). The proposed new formula simply does not work on my end (I copied and pasted, to be clear) because an error box pops out and I can't continue.

= Table.Sort(#"Changed Type1",{{"New Rank", Order.Ascending},{"Rank", Order.Ascending}})

This is caused because column in the database is named "Overall Rank", therefore the above formula with "Rank" won't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Shape and combine data from multiple sources - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @rafaelhenck. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comments, and sorry for the inconvenience. The data is from an outside source, so we don't have control over that. I will put going over that tutorial onto my backlog, but I think the overall steps and learning are helpful to show folks how the flow works. Thanks!
