### ISSUE TITLE
Lower example shows poor report design

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerbi-docs#3000]
In the lower report yellow means "Moderate" in one chart and "Yes" in the other chart. It's report design basics to use same color for same thing consistently within a report. You shouldn't make BI learners get used to such poor report design.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d0aaa2-486e-f7fa-522f-5647ad31c076
* Version Independent ID: 2ce1f307-1258-1fd6-ddcf-9224bafc4444
* Content: [Understand how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-interactions)
* Content Source: [powerbi-docs/consumer/end-user-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-interactions.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @MartinBubenheimer, thanks for your comment. I am forwarding it on to the doc author for consideration.

**Comment by mihart** [comment]
Hi @MartinBubenheimer ,
Thank you for your feedback.  I've updated the visuals per your suggestion.  
All the best,
The DOCS team
