### ISSUE TITLE
Current R runtime version

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#3001]
From the article:

> Current R runtime: Microsoft R 3.4.4

Can you please confirm that this documentation aspect is still current?

According to https://mran.microsoft.com/release-history, Microsoft R 3.4.4. was released 3 years ago. This obviously makes it very dated. 

If the documentation is indeed accurate, can you please advise when the R runtime within Power BI Service will be updated to a newer version, such as Microsoft R Server 4.0.2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-r-packages-support)
* Content Source: [powerbi-docs/connect-data/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @VitalyMCT.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by VitalyMCT** [comment]
There is no answer on the forums, hence we need an answer in the official documentation. I will stay tuned to this ticket.

**Comment by davidiseminger** [comment]
We've updated the article to show (and highlight) the currently supported version.
