### ISSUE TITLE
Get Billing Account instructions not clear and no longer valid

### ISSUE THREAD

**Issue by andyreadman** [MicrosoftDocs/powerbi-docs#3002]
The screenshot of the Billing Account details shows a highlight around billing account type which I believe is misleading, when the Billing Account ID is what is required.

Also, it seems it's not possible to get the Billing Account information for a CSP subscription in this way anymore, there's no properties within the Cost Management / Cost Analysis section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc4bd0c-b3d7-3ace-ca76-696e9c278d4b
* Version Independent ID: 3c0f58ee-b290-559a-cb6d-b7afe1996760
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator)
* Content Source: [powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @andreabichsel
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @andyreadman.

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
@andyreadman - this article was recently updated to reflect changes to the template app. It is now the Emissions Impact Dashboard. Please feel free to open a new issue if your feedback was not addressed with the update.
