### ISSUE TITLE
What units is the 'usage' column in the preparation report?

### ISSUE THREAD

**Issue by richardharrison2** [MicrosoftDocs/powerbi-docs#3003]
Hi,
The emissions section at the top of the page makes sense, however for the usage section at the bottom of the page i don't understand what units usage is being measured in? The documentation doesn't seem to say and the video that goes along with this doesn't explain either?

Is it number of resources/hours/days/something else ?

Thanks,
Rich

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc4bd0c-b3d7-3ace-ca76-696e9c278d4b
* Version Independent ID: 3c0f58ee-b290-559a-cb6d-b7afe1996760
* Content: [Connect the Microsoft Sustainability Calculator - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-microsoft-sustainability-calculator)
* Content Source: [powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-microsoft-sustainability-calculator.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @andreabichsel
* Microsoft Alias: **rosode**

**Comment by maggiesMSFT** [comment]
Hi, @richardharrison2 -- I'm checking and will report back. Thanks for asking!

**Comment by maggiesMSFT** [comment]
Hi, @richardharrison2 -- here's the answer:
"It is a normalized number (currency free) of Azure Consumed Revenue."
Hope that helps!
