### ISSUE TITLE
PowerBI REST API | Export To File In Group

### ISSUE THREAD

**Issue by CristianDuca** [MicrosoftDocs/powerbi-docs#3004]
Hi all 
Trying to use this this method to Export the specified report from the specified workspace to the requested format.
https://docs.microsoft.com/en-us/rest/api/power-bi/reports/exporttofileingroup#code-try-0

POST https://api.powerbi.com/v1.0/myorg/groups/{groupId}/reports/{reportId}/ExportTo

This is what I get:
Response Code: 202

JSON Body: 

{
  "@odata.context": "someURL",
  "id": "IDremoved",
  "createdDateTime": "2021-04-26T17:17:59.8273954Z",
  "lastActionDateTime": "2021-04-26T17:17:59.8273954Z",
  "reportId": "reportID",
  "status": "NotStarted",
  "percentComplete": 0,
  "expirationTime": "0001-01-01T00:00:00Z"
}

in your documentation it says I should receive also a resourceLocation ( URL for retrieving the exported file ). however on above I cannot see that. neither an admin was able to see it. 

What am I doing wrong?

thank you

**Comment by KesemSharabi** [comment]
Hi @CristianDuca,

The [202 response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202) is expected. The resource URL is in the request headers (location header). It’s not part of the request body.

Hope this helps,

Kesem
