### ISSUE TITLE
visualType list is missing several recently added visuals

### ISSUE THREAD

**Issue by MattRudy** [MicrosoftDocs/powerbi-docs#3005]
visualType list on page [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md) should be expanded to include recent visualTypes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#limitations-and-considerations)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @MattRudy,

Thank you for your suggestion. I'll look into it with the development team.

Kesem

**Comment by MattRudy** [comment]
Hi Kesem,

I've linked this to the PR #3006 I created to resolve this.

The current list of visualType options isn't the complete set available - I've been working on building themes and noticed several that were missing from the documentation.

The auto-generated link to the limitations and considerations section is misleading - I was referring to an earlier section in the article called [visualStyles definition list](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#visualstyles-definition-list).

These items have the following values for visualType:

| visualType | Visual Name(s) | State | Notes |
| --- | --- | --- | --- |
| actionButton | Buttons | Released |   |
| azureMap | Azure Map | **Preview** |   |
| decompositionTreeVisual | Decomposition Tree | Released |   |
| esriVisual | ArcGIS Map by Esri | Released |   |
| keyDriversVisual | Key Influencers | Released |   |
| qnaVisual | Q&A | Released |   |
| shape | Shapes | Released | not all shapes respond to 'basicShape', some have visualType 'Shape' |
| textbox | Textbox<br>Smart Narrative | Released<br>**Preview** | Both are controlled by the same visualType settings in themes |

The PR should add all of these to the visualType list
