### ISSUE TITLE
Additional Limitations

### ISSUE THREAD

**Issue by wdeguara** [MicrosoftDocs/powerbi-docs#3007]
In addition to above listed Considerations and Limitations:

1. It is important to note that once an external participant has been invited in PowerBI B2B, the invitation cannot be withdrawn. In other words, if you elect to remove a guest from access a workspace, the guest is still able to access the workspace even though they are no longer authorised to do so.  (BTW.  This has been reported as a security flaw to MS, in that the behaviour does not align with any other M365 products that are B2B enabled).

2. There is also a limitation with Conditional Access.  To access the workspace the Guest needs a license. If they already have one in their tenant that should be able to be used to grant access along with the authorisation to the workspace.  There is a bug in Power BI B2B where the license of the guest user from their home tenant is not recognised. 

3. For multinational organisations operating under single M365 Tenant, once PowerBI B2B has been activated - it is activated for all. (ie. Once it is turned on, all workspace owners will have the right to leverage B2B). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
@mibruhje - can you please review this feedback and suggest an article update?

**Comment by KesemSharabi** [comment]
I started an email thread for this.
