### ISSUE TITLE
Page can mention lack of support for non-colour text values

### ISSUE THREAD

**Issue by TwiddlyTiger** [MicrosoftDocs/powerbi-docs#3008]
To avoid repeated queries on the same question (which is also how I happened on this page), in 'considerations and limitations' the page could mention that conditional formatting in matrix visuals (unsure about tables) doesn't support text values, apart from w3-recognised colours. 

For example, unlike in Excel, it's not possible to colour-code text values to display as a particular colour, such as "Accepted"=blue, "Declined"=red, "None"=grey. One would need to create measures related to these values and apply formatting to those instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Conditional table formatting in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @TwiddlyTiger.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @TwiddlyTiger -- good suggestion! Updating the article today, should be live tomorrow afternoon June 16 Pacific time.
