### ISSUE TITLE
Missing information on sharing Microsoft Azure Consumption Insights

### ISSUE THREAD

**Issue by johnkattenhorn** [MicrosoftDocs/powerbi-docs#301]
We've used this documentation to setup our Azure Consumption Insights and it's working but we can't figure out how to share the configured App with other members of our team; the options we use for our own Apps don't appear for this PowerBI Application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights#next-steps)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @johnkattenhorn . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by SarinaJoan** [comment]
@johnkattenhorn, Power BI service apps are installed per user and don't have a sharing option. If other users in the organization have access to the service, they can install the app through the 'Get Apps' experience.
