### ISSUE TITLE
Data gateway

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#3010]
It's been almost 1.5 years since this article was updated. In the meantime:

1. The personal gateway has been renamed to "on-premises data gateway (personal mode)", so a terminology sync is in order for this article too
2. Perhaps more importantly, does R integration in Power Query in Power BI still require "on-premises data gateway (personal mode)"? Or is it now available in "on-premises data gateway" as well? I've tried to source an answer from the gateway documentation and was unsuccessful. I am hoping this aspect/limitation can be elaborated on.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @VitalyMCT.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by VitalyMCT** [comment]
There is no answer on the forums, hence we need an answer in the official documentation. I will stay tuned to this ticket.

**Comment by davidiseminger** [comment]
I've updated the documentation for terminology about on-premises data gateway (personal mode). For your questions about the feature itself (whether it requires a gateway at all, which one) you can ask (again) in the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
