### ISSUE TITLE
Data Driven Filters in Filters Pane

### ISSUE THREAD

**Issue by jmcguire77** [MicrosoftDocs/powerbi-docs#3012]
A client brought up a great question that I hadn't yet thought of when working with the Power BI Filters pane. We have added several filters that provide data such as a list of all customers, a list of all brokers, a list of all items, etc. We currently have RLS configured so that when salespersons log in, they only view their data. However, it appears they are able to see the complete list of customers, brokers, items, etc. in the Filters pane list of available values.

Is there currently a way, or is something in the works, to limit the list of available values in a filter by either 1) the data returned based on the RLS role and/or 2) the data returned based on other filters being applied to the report, such as a specific date range, customer, broker, etc.?

Thanks,
Joe
Charlotte, NC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1465b3a1-a6de-e2f3-154c-817ea13aa4f0
* Version Independent ID: 20ea6924-2307-d6ef-d601-7f949fe58944
* Content: [Tour the report Filters pane - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-report-filter)
* Content Source: [powerbi-docs/consumer/end-user-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-report-filter.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @jmcguire77 -- great question! 
This article talks about upcoming features: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-bi/
If you don't find an answer to your feature question there, then I recommend checking and asking in the Power BI Ideas forum: 
https://ideas.powerbi.com/ideas/
Hope that helps!
