### ISSUE TITLE
Update sharing Docs for new Sharing experience

### ISSUE THREAD

**Issue by savoy9** [MicrosoftDocs/powerbi-docs#3013]
The first three screenshots on this page are out of date with the new office like sharing experience and because the extended share options have been moved from a share dropdown to the file menu.
![image](https://user-images.githubusercontent.com/41710547/116469750-62d13200-a827-11eb-8100-d807327fd065.png)

Similar issues are found on these pages:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-secure
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @savoy9 -- you're a few minutes ahead of us! We're waiting for the OK to release the updated docs soon -- I believe next week. Check back then. Thanks!
