### ISSUE TITLE
Non-existent step

### ISSUE THREAD

**Issue by pmaldonato** [MicrosoftDocs/powerbi-docs#3014]
Number 5 states "Select ellipses and select Sort By Period" in this example there are only 2 selections so it's not there. I'm going through the exercise and the 'Sort By - Period' isn't there on the Visualisation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b62b6838-df4d-0d8b-c916-e4e7b479c47b
* Version Independent ID: 01a3c0d1-aaa5-ec10-5ad5-deff577e16ba
* Content: [Create a report from an Excel file in the Power BI service  - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-report-create-new)
* Content Source: [powerbi-docs/create-reports/service-report-create-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-report-create-new.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @pmaldonato -- thanks for your comment! I'll add it to the backlog to investigate. A bit swamped this week 😁!

**Comment by paulinbar** [comment]
Hi @pmaldonato, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for providing your feedback!

**Comment by pmaldonato** [comment]
Right on! Thanks
