### ISSUE TITLE
Information Miss-Match

### ISSUE THREAD

**Issue by moniaayush** [MicrosoftDocs/powerbi-docs#3015]
This page talks about  R visual calculation exceeds **5 minutes the script times out**, resulting in an error

Where as other documents talks about only 60 Seconds as Timeout limit. Huge difference.

https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals
Calculation time limitation – if an R visual calculation exceeds **60 seconds the script times out**, resulting in an error.

Please have a look and correct the details.

Thanks
Atul Kumar
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals)
* Content Source: [powerbi-docs/create-reports/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-r-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @moniaayush -- thanks for asking! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
This issue has been fixed, thanks!
