### ISSUE TITLE
Change in language for Scheduled Refresh in service

### ISSUE THREAD

**Issue by Hikmer** [MicrosoftDocs/powerbi-docs#3016]
Scheduled refresh for Direct Queries with Query Caching enabled now says the following:

Scheduled refresh 
Automatic dashboard tile refresh
Adjust the automatic refresh frequency of each dashboard tile to suit your needs, or manually refresh a tile by selecting More.

This is very confusing as we believe that this feature should be keeping the direct query model hydrated with data for subsequent report interactions.  Can someone fix this and add more detail on how it exactly works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#datasets-in-directqueryliveconnect-mode)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Hikmer -- thanks for asking! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
I don't see the passage you're referring to in this article, it may have been updated since you posted.
