### ISSUE TITLE
Out of date options screenshot

### ISSUE THREAD

**Issue by localden** [MicrosoftDocs/powerbi-docs#3017]
The screenshot in the doc may be out of date (in [this section](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about#report-design-guidance)). Here is what I see in Power BI

![Power BI screenshot](https://user-images.githubusercontent.com/53200638/116584434-315e7200-a8cc-11eb-987f-12132bbe790b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about#maximum-number-of-connections-option-for-directquery)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @dendeli-work -- how are you? Thanks for your question. Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
We've updated that screen shot. Thanks!
