### ISSUE TITLE
Missing steps, outdated, screenshots lack context

### ISSUE THREAD

**Issue by rubencanlas** [MicrosoftDocs/powerbi-docs#3018]
[Enter feedback here]
PowerBI Version: 2.92.943.0 64-bit (April 2021)

1. It's not clear in the instructions which tab to use to create the decomp tree. But the screenshot animation seems to suggest the Exploratory Analysis tab. Your screenshot does not provide the context of the tab, because it was cropped to remove the tabs. It will be really useful to show the tab.
2. Explain By - might be helpful if you give the hint to the learner to look at the picture and mimic the fields that are under Explain By.
3. Game example: where is the dataset on this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f919f51d-8623-b039-a1fc-0df774225c46
* Version Independent ID: 0376c331-0f7e-ec9b-6262-f47a6c413d47
* Content: [Decomposition tree - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-decomposition-tree)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-decomposition-tree.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @rubencanlas -- thanks for your feedback! I'm assigning it to the author to look into. I'm fond of decomp trees myself, so I want the docs to explain them well!

**Comment by KesemSharabi** [comment]
Hi @rubencanlas,

Thank you for your suggestions. When we next update this article we'll take them into consideration.

Thanks,

Kesem
