### ISSUE TITLE
Power BI - Analyze in Excel Documentation

### ISSUE THREAD

**Issue by Renatontx** [MicrosoftDocs/powerbi-docs#3019]
Please, review the Requirement Section - ''Guest users can't use Analyze in Excel for datasets sent from (originating from) another tenant." i suggest that statament should be under limitations not requirements...I got confused when I first read that documentation if Guest userts to use analyze in excel was a limitation or requirement...you cannot tell if is possible or not by reading under requirements

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
![Capturar](https://user-images.githubusercontent.com/83366929/116748406-cf8a2f00-a9d5-11eb-8ac7-7666b2e59df3.JPG)

* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Renatontx -- good point! I should have time to fix it next week. Thanks!
