### ISSUE TITLE
Need content for Dataflows

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#302]
There is no mention of the Dataflows memory settings (currently in Preview).  That needs to be added to this document. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Manage capacities within Power BI Premium and Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage)
* Content Source: [powerbi-docs/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @chrisweis - I'll add that info

**Comment by mgblythe** [comment]
@chrisweis -- that info is now in the doc (was waiting on the public preview): https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage#configure-workloads
