### ISSUE TITLE
Graph Security API deprecated

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3021]
Power Query has deprecated its [connector to MS Graph Security](https://docs.microsoft.com/en-us/power-query/connectors/microsoftgraphsecurity#deprecation) due to the API ending support.  Same for Power BI's connector?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @rootsmusic, thanks for your comment. I will check this out.

**Comment by rootsmusic** [comment]
@paulinbar, May's [release update](https://powerquery.microsoft.com/en-us/blog/power-query-updates-in-power-bi-desktop-may-2021-release/) announced "This update will remove the connector from the “Get Data” experience in Power BI Desktop".

**Comment by paulinbar** [comment]
Hi @rootsmusic, thanks for pointing this out. You got to it before I did. So we need to update the Power BI doc. Created a work item. Thanks!

**Comment by paulinbar** [comment]
Hi @rootsmusic, I have put a deprecation notice at the top of the document. It will go live later today. Thanks again for bringing this up!
