### ISSUE TITLE
ReportLevelFilters

### ISSUE THREAD

**Issue by lnogueracmnhospitals** [MicrosoftDocs/powerbi-docs#3022]
The documentation says in the following snipped that we can use ReportLevelFilters when using the Exporting reports using ExportToFile. https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#step-1---sending-an-export-request

```
var powerBIReportExportConfiguration = new PowerBIReportExportConfiguration
    {
        Settings = new ExportReportSettings
        {
            Locale = "en-us",
        },
        // Note that page names differ from the page display names
        // To get the page names use the GetPages REST API
        Pages = pageNames?.Select(pn => new ExportReportPage(Name = pn)).ToList(),
        // ReportLevelFilters collection needs to be instantiated explicitly
        ReportLevelFilters = !string.IsNullOrEmpty(urlFilter) ? new List<ExportFilter>() { new ExportFilter(urlFilter) } : null,

    };
```
But the PowerBIReportExportConfiguration class does not have a ReportLevelFilters property, so it´s no clear how we can export reports with filters.

![image](https://user-images.githubusercontent.com/70968750/116798466-c61fc600-aaac-11eb-9b36-aaa10157a727.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI embedded analytics reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#filters)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @lnogueracmnhospitals, thanks for your observation. I am forwarding it on to the doc author for further consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @lnogueracmnhospitals,

According to the API documentation [PowerBIReportExportConfiguration](https://docs.microsoft.com/rest/api/power-bi/reports/exporttofile#powerbireportexportconfiguration) has the `ReportLevelFilters` property.

![image](https://user-images.githubusercontent.com/54834915/116885756-ebd5d800-ac30-11eb-9534-39fabff7fb95.png)

Is it possible that you're using an old SDK?

`ReportLevelFilters` was added recently. Updating your Power BI C# SDK should solve the issue.
 
Hope this helps,

Kesem

**Comment by lnogueracmnhospitals** [comment]
Ups, sorry about that. You were right, I was using 3.18.1 and once I upgraded to 3.23.0 I was able to find the ReportLevelFilters property. Thank you!

**Comment by KesemSharabi** [comment]
Happy I could help @lnogueracmnhospitals 😀

**Comment by psvenkatesan74** [comment]
Hello Friends, 
I need to know how to use ReportLevelFilters, when I try to add below code, I get badrequest error. Please help.
                PowerBIReportConfiguration = new PowerBIReportExportConfiguration
                {
                    ReportLevelFilters = new List<ExportFilter>() {
                        new ExportFilter(filter: "Origin eq '1'")
                    }
                }
Thanks For Helping.
