### ISSUE TITLE
Provide an example of leveraging Enhanced Compute in separate workspaces

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerbi-docs#3023]
The best practice for scheduling dataflows separately is to create separate workspaces one for ingestion and one for compute. The enhanced compute example in this section doesn't cover that. It solely covers what to do when you have them within the same workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6054103-4999-9ce2-ba30-095a6d469465
* Version Independent ID: 2ce5b049-276a-a159-4f28-fd1dca17442f
* Content: [Configure Power BI Premium dataflow workloads - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-workload-configuration#using-the-compute-engine-to-improve-performance)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @cvillegashak.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your recommendation, we'll look at adding that information in the next refresh of the content.
