### ISSUE TITLE
announce upcoming webinars in the Community

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3025]
Upcoming webinars should be announced in [the Community](https://community.powerbi.com/t5/Upcoming-Events/bd-p/Community).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a082e6-1c36-af62-95b7-69405696764e
* Version Independent ID: 0425ef3a-54b6-3527-6a02-a60642c9d61c
* Content: [Power BI webinars - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/webinars)
* Content Source: [powerbi-docs/fundamentals/webinars.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/webinars.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rootsmusic.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by rootsmusic** [comment]
@KesemSharabi , this issue is about this doc's "[upcoming webinars](https://docs.microsoft.com/en-us/power-bi/fundamentals/webinars#upcoming-webinars)".  (It's not about the software.)

**Comment by kfollis** [comment]
@rootsmusic - thanks for the feedback. I help to maintain the article you reference and honestly assumed that it was also posted to community. My contact for that info has recently changed, so let me bring this to their attention and see if we can add this to community as well - I agree that community is actually the best place for this information. Having it included in documentation does help with discoverability, and there are additional resources (including some from our customers) here: https://community.powerbi.com/t5/Webinars-and-Video-Gallery/bd-p/VideoTipsTricks. Please be patient as I work with the community team to consolidate the webinar list. We'll close the issue, as the article itself is accurate, but will definitely pursue sharing these announcements in Community.

**Comment by rootsmusic** [comment]
Ok @kfollis, I agree with the exception that this doc is still needed to archive files used in webinars in the video gallery.

**Comment by rootsmusic** [comment]
@kfollis, shouldn't "Upcoming webinars from the Power BI community" link to https://community.powerbi.com/t5/Upcoming-Events/bd-p/Community ?

**Comment by kfollis** [comment]
It's quite the trick staying on top of all these resources! The upcoming events link isn't quite as thorough as the webinars/videos link, but it does list events that customers should be aware of. I'm making a couple of other changes today to different articles, and will see if I can find a way to add this link. I think the upcoming events should be listed where you indicate and the webinars link should be under the community section. It's not typical to enumerate the resources on community, but I agree that increasing awareness is useful.
