### ISSUE TITLE
differentiate doc

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3026]
Since there's another doc for [Power BI Desktop videos](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-videos), I suggest appropriately moving videos to that doc in order to dedicate this doc for videos that aren't about Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c2d0b7-fdeb-9e1e-1b60-04854fcb89da
* Version Independent ID: e53a3969-30e8-033d-f76c-71b05dbd0361
* Content: [Power BI videos - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/videos)
* Content Source: [powerbi-docs/fundamentals/videos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/videos.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rootsmusic.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by kfollis** [comment]
Thanks for your feedback, @rootsmusic. We recently made an update to consolidate the 2 articles to just one Videos article that links to the Power BI Desktop video channel. I'll close this issue.
