### ISSUE TITLE
Considerations and limitations not in line with reality? 

### ISSUE THREAD

**Issue by BiekeBras** [MicrosoftDocs/powerbi-docs#3027]
Dear,

The below limitation on page "Connect to datasets in the Power BI service from Power BI Desktop" is no longer valid.
It would be good to remove it as it is still being referenced as cause for reports not being exportable to pbix-format.

"The report must have been created by using Power BI Desktop and published to the Power BI service, or the .pbix file must have been uploaded to the Power BI service."

Best regards,
Bieke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @BiekeBras.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback - that limitation in the article has been removed.
