### ISSUE TITLE
Page seems to be out of date

### ISSUE THREAD

**Issue by sandorspruit** [MicrosoftDocs/powerbi-docs#3028]
The information on this page seems to be out of sync with the current versions of dot-net, i.e. importing the code as-is into Visual Studio 2019 produces a number of errors.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by sandorspruit** [comment]
Specifically, these two lines cause trouble:

            AuthenticationContext authContext = new AuthenticationContext(authorityUri);
            var token = authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUri)).Result.AccessToken;

The third parameter seems to be of the wrong type, a UserCredential is expected. The combination of types and parameters seems to fit the synchronous version of this method, i.e. AcquireToken. I cannot seem to find an asynchronous method with the exact same signature.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 13:58
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)


The information on this page seems to be out of sync with the current versions of dot-net, i.e. importing the code as-is into Visual Studio 2019 produces a number of errors.

________________________________
Document details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
  *   Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
  *   Content: Get an authentication access token - Power BI<https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token>
  *   Content Source: powerbi-docs/developer/automation/walkthrough-push-data-get-token.md<https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md>
  *   Service: powerbi
  *   Sub-service: powerbi-developer
  *   GitHub Login: @KesemSharabi<https://github.com/KesemSharabi>
  *   Microsoft Alias: kesharab

**Comment by sandorspruit** [comment]
The first part of the series is wrong, it introduces an asynchronous method that is not mentioned anywhere else.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 15:27
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: Re: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)

Specifically, these two lines cause trouble:

AuthenticationContext authContext = new AuthenticationContext(authorityUri);
var token = authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUri)).Result.AccessToken;

The third parameter seems to be of the wrong type, a UserCredential is expected. The combination of types and parameters seems to fit the synchronous version of this method, i.e. AcquireToken. I cannot seem to find an asynchronous method with the exact same signature.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 13:58
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)


The information on this page seems to be out of sync with the current versions of dot-net, i.e. importing the code as-is into Visual Studio 2019 produces a number of errors.

________________________________
Document details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: Get an authentication access token - Power BI<https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token>
* Content Source: powerbi-docs/developer/automation/walkthrough-push-data-get-token.md<https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md>
* Service: powerbi
* Sub-service: powerbi-developer
* GitHub Login: @KesemSharabi<https://github.com/KesemSharabi>
* Microsoft Alias: kesharab

**Comment by sandorspruit** [comment]
Another important detail that seems to be missing: the initial authentication uses Windows Forms, that needs to be added as a dependency despite the example being a console application.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 16:38
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: Re: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)

The first part of the series is wrong, it introduces an asynchronous method that is not mentioned anywhere else.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 15:27
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: Re: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)

Specifically, these two lines cause trouble:

AuthenticationContext authContext = new AuthenticationContext(authorityUri);
var token = authContext.AcquireTokenAsync(resourceUri, clientID, new Uri(redirectUri)).Result.AccessToken;

The third parameter seems to be of the wrong type, a UserCredential is expected. The combination of types and parameters seems to fit the synchronous version of this method, i.e. AcquireToken. I cannot seem to find an asynchronous method with the exact same signature.

From: Sandor Spruit ***@***.***>
Reply to: MicrosoftDocs/powerbi-docs ***@***.***>
Date: Monday, 3 May 2021 at 13:58
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: "A. Spruit" ***@***.***>, Your activity ***@***.***>
Subject: [MicrosoftDocs/powerbi-docs] Page seems to be out of date (#3028)


The information on this page seems to be out of sync with the current versions of dot-net, i.e. importing the code as-is into Visual Studio 2019 produces a number of errors.

________________________________
Document details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: Get an authentication access token - Power BI<https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token>
* Content Source: powerbi-docs/developer/automation/walkthrough-push-data-get-token.md<https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md>
* Service: powerbi
* Sub-service: powerbi-developer
* GitHub Login: @KesemSharabi<https://github.com/KesemSharabi>
* Microsoft Alias: kesharab

**Comment by KesemSharabi** [comment]
Hi @sandorspruit,

You're right. This article is out of date. We will updated it in the future. However, this might take some time.

Thanks,

Kesem

**Comment by sandorspruit** [comment]
A bit of a disappointing reaction, to be honest. This is just about the _only_ piece of documentation specifically describing automated access to PowerBI. All that is needed is a link to updated information on authentication which, as I just discovered, is available under "Quickstart" from the Azure portal used to register the application (one of the first steps). I think most developers can take it from there.
