### ISSUE TITLE
PPU users can consume Pro users' content

### ISSUE THREAD

**Issue by bmtorres** [MicrosoftDocs/powerbi-docs#3029]
The 3rd paragraph of this page informs that "If content is stored in that shared capacity, users who are assigned a Power BI Pro license can collaborate only with other Power BI Pro users". The second row of the table also informs that Power BI Pro users can "Publish content to other workspaces, share dashboards, subscribe to dashboards and reports, share with users who have a Pro license" in a shared capacity. Both statements are wrong.

According to https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq#end-user-experience, content created by users with a Pro license **can be consumed by users with a PPU license**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6e1bb7-fbc5-d0a6-5285-e4a9152902bb
* Version Independent ID: ece0823b-c4c5-3acb-41bb-55e5390c0b6c
* Content: [Power BI service features by license type - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type)
* Content Source: [powerbi-docs/fundamentals/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-features-license-type.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bmtorres.

I've assigned this issue to the doc author for review.

**Comment by kfollis** [comment]
@mihart - can you please review and work with the PM to update? This should have been assigned to you.

**Comment by mihart** [comment]
Hi @,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please revisit the article since it has been updated several times since this Git Issue was submitted.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
