### ISSUE TITLE
Power Bi Files

### ISSUE THREAD

**Issue by DownB** [MicrosoftDocs/powerbi-docs#303]
Hi,
Could you give the power bi files you are using for this presentation to be able to do it on my side at the same time ?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14ae2272-c2ec-5bf1-5315-1e854291e821
* Version Independent ID: 24993f50-2188-4999-c907-eb908b03da5a
* Content: [Best design practices for reports and visuals (whitepaper) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-best-practices)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-best-practices.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-best-practices.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @DownB ,
Thank you for your inquiry.  Unfortunately, we don't have a sample for that particular article/whitepaper. It does need updating and I'll see if I can somehow structure it to use one of the free samples when I do the editing. 
Take care,
Michele
