### ISSUE TITLE
more details required

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/powerbi-docs#3030]
this document says that in addition to customer data, it also encrypts user data generated by service. So what is this user data and how it is generated by the service? Could you please clarify this in the documentation.
Also, can i assume that configuration steps which are mentioned in BYOK documentation are also applicable for CMK e.g. key management in Azure key vault, apply the key to the service data encryption and rotating the keys etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b66e6f-daa6-426b-4ac8-41b495562543
* Version Independent ID: 80568118-067c-4e8b-2204-0be904a701d2
* Content: [Use customer-managed keys in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-encryption-customer-managed-keys)
* Content Source: [powerbi-docs/admin/service-encryption-customer-managed-keys.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-encryption-customer-managed-keys.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
I've added a link to the Security whitepaper article, which goes into detail about such matters.
