### ISSUE TITLE
Needs reference to Goals and Scorecards

### ISSUE THREAD

**Issue by MattRudy** [MicrosoftDocs/powerbi-docs#3031]
New features should be added to this document (if relevant - they are limited to Premium features and might make sense on the Premium Features page instead).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [The Power BI service - basic concepts for business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @MattRudy . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @MattRudy,
Thank you for your suggestion.  I try to limit the Basic Concepts article to just the, well, basic concepts.  It's not intended to be an overview of features or it would become way too long.  There are great articles that already cover [goals and scorecards ](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-create)in the "creator" content.  So I'll also add an article on goals and scorecards to the "end user" content when it comes out of preview.  It's a good idea - thank you.
