### ISSUE TITLE
Does this PowerBI connector work for 1st party/Internal subscriptions?

### ISSUE THREAD

**Issue by xuhaohems** [MicrosoftDocs/powerbi-docs#3032]
Does this PowerBI connector work for 1st party/Internal subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @xuhaohems . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
I'm not sure what you mean by "1st party / internal" subscriptions. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
