### ISSUE TITLE
Support for Premium per user 

### ISSUE THREAD

**Issue by Bhodges94** [MicrosoftDocs/powerbi-docs#3033]
it says in the Prerequisites that "At least one workspace in your Power BI tenant backed by a reserved capacity". Does this include Premium Per User or is it limited to Premium Per Capacity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Bhodges94.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by paulinbar** [comment]
Hi @Bhodges94, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for question!
