### ISSUE TITLE
Web.config changes mentioned don't work for new samples

### ISSUE THREAD

**Issue by VsabGit** [MicrosoftDocs/powerbi-docs#3035]
The Web.config changes that are mentioned in this Doc don't work for the new samples that work with MSAL.

for example the Web.config changes that we need to do to embed in GCC according to Doc are:
**<add key="authorityUrl" value="https://login.microsoftonline.com/common/" />
<add key="resourceUrl" value="https://analysis.usgovcloudapi.net/powerbi/api" />
<add key="apiUrl" value="https://api.powerbigov.us/" />
<add key="embedUrlBase" value="https://app.powerbigov.us" />**

But for the new .Net Framework sample these should be the changes:
**<add key="authorityUrl" value="https://login.microsoftonline.com/organizations/" />
<add key="scope" value="https://analysis.usgovcloudapi.net/powerbi/api/.default"/>
<add key="urlPowerBiServiceApiRoot" value="https://api.powerbigov.us/" />**

in addition to that the bootstrap for report embed needs to be commented out (Views > Home > EmbedReport.cshtml > Line 36)
![image](https://user-images.githubusercontent.com/25950746/117298742-634d7680-ae80-11eb-9160-4d2504861d5d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0658cf44-97c9-cb23-68bd-146f29eb644c
* Version Independent ID: e05ed89e-2dfa-0d31-4198-9170a33ef120
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for government and national clouds - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers-national-clouds)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers-national-clouds.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @VsabGit.

You're right. We didn't update the [Embed a Power BI content into your application for national clouds](https://docs.microsoft.com/power-bi/developer/embedded/embed-sample-for-customers-national-clouds) tutorial yet. Updating it is on our roadmap, but it'll take some time before we get it.

In the meantime, if you still have some questions, you might find answers in the [Power BI Community]( https://community.powerbi.com).

Thanks,

Kesem
