### ISSUE TITLE
MariaDB data source line not clear: gateway "required" but "not supported".

### ISSUE THREAD

**Issue by sdt-msft** [MicrosoftDocs/powerbi-docs#3037]
[Enter feedback here]
Please check the line for MariaDB datasource: it says a gateway is required but not supported, which is not clear, and it may be outdated in all language versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources#data-sources-m-o)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @sdt-msft, thanks for your comment. I am forwarding it on to the doc author for consideration.

**Comment by davidiseminger** [comment]
Sorry about that typo, it's been fixed in the article.
