### ISSUE TITLE
Uncompressed data on the gateway limitation has a workaround that is not documented

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/powerbi-docs#3038]
For this limitation: https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot#error-the-received-uncompressed-data-on-the-gateway-client-has-exceeded-the-limit 
Using Power BI Premium is a workaround but it's not documented. Can we add this workaround to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshoot gateways - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot#error-the-received-uncompressed-data-on-the-gateway-client-has-exceeded-the-limit)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by davidiseminger** [comment]
Thanks for your comment, we're closing this issue since the feature has evolved much since then.
