### ISSUE TITLE
Article needs clarification and updating

### ISSUE THREAD

**Issue by chrolivier** [MicrosoftDocs/powerbi-docs#3039]
The article's wording is not in line with the latest version of the app.
For example: The article refers to "Daily peak usage" while the latest version of the app uses the term "Daily peak utilization"

Also: Both screenshots of the "Daily peak usage" visual show that the visual's Y axis lists the number of cores (in this case 8) and the Utilization graph is scaled to fit this. In the new app it seems that the graph's Y axis is scaled to according to the Utilization graph. This needs clarification: Does the Utilization graph display the percentage of available CPU utilized?
In the attachment the Utilization peaks at about 45. Does this mean that 45% of available processing was used?
If so I suggest that "Utilization" in the legend be changed to "Utilization %'. 
The article's description of this graph should also clarify the meaning of Utilization.

![daily_peak_utilization](https://user-images.githubusercontent.com/968591/117426175-e4aa1500-af23-11eb-8344-9e8356c23c80.png)

The description of the graph "Peak utilization - 15m intervals" also needs clarification.
Refer to the attached screenshot:
![Utilization](https://user-images.githubusercontent.com/968591/117427606-7fefba00-af25-11eb-9b74-7dc4562de579.png)

The article does not explain the details of this graph:
- This scale of the Y-axis is unclear. 
- What does the 100% line mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f52eeb-717d-9a67-b775-c17c5cf916e4
* Version Independent ID: 2c804bb2-1cf3-462e-730b-ecfbae2a5e9e
* Content: [Power BI Premium Gen2 Metrics app (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/admin/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by jgibbycsc** [comment]
The app's visual labels don't match the documentation. 

In Utilization by Workspace and Artifact:
There's confusion as to what "Total Utilization (s)" vs "Contribution (s)" means. 

Is there an updated doc for the new report layout and terms?

**Comment by jgibbycsc** [comment]
Please, please: Add the current version number to the Help > Release Notes page. Currently no way to know which version we are using and it seems like the report is updated regularly. For those that are installing from App Source, as of 11/17/2021 version number is 1009. Add it to your reports!

Thank you @KesemSharabi !!

**Comment by jgibbycsc** [comment]
Also, the article states "The release notes page contains the release notes for each new version of the app. As the app updates automatically, it's a good idea to review the release notes from time to time."

https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-metrics-app#release-notes

Does the app **actually** update automatically?

**Comment by jgibbycsc** [comment]
Please reword this: 

 <html>
<body>


CPU | View the top CPUs that consumed Power BI items over the past two weeks
-- | --



</body>
</html>

**Comment by KesemSharabi** [comment]
Hi @jgibbycsc,

I updated the [Install the Gen2 metrics app](https://docs.microsoft.com/power-bi/admin/service-premium-install-gen2-app?tabs=1st) article.

Hope this helps,

Kesem
