### ISSUE TITLE
Invalid API keys / Credentials

### ISSUE THREAD

**Issue by panicacid** [MicrosoftDocs/powerbi-docs#304]
After creating a new set of API keys for our EA we're getting the error:

Failed to update data source credentials: The credentials provided for the MicrosoftAzureConsumptionInsights source are invalid. (Source at 75242865.)Show details

Keys are valid, copied and pasted multiple times, regenerated, still failing each time we're trying to connect Consumption Insights to our EA.

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @panicacid . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
