### ISSUE TITLE
Permission too broad

### ISSUE THREAD

**Issue by stingaa** [MicrosoftDocs/powerbi-docs#3040]
The Github App for PowerBI on powerBi.com allows us to analyze data for 1 repo only.  However, to use it, it requires read/write access to the entire org and the personal user data.  That is very permissive and gives us security and privacy concerns.  Can we reduce the permission scope to the appropriate level?

Link to app - https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github

Connect to only 1 repo:
![image](https://user-images.githubusercontent.com/25179768/117676544-41e7d580-b173-11eb-8292-4701fa42cec6.png)
![image](https://user-images.githubusercontent.com/25179768/117676589-4ca26a80-b173-11eb-9634-5024c4089d95.png)

But asking for access to the whole org:
![image](https://user-images.githubusercontent.com/25179768/117676770-78255500-b173-11eb-9a37-3e6040b0b702.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github)
* Content Source: [powerbi-docs/connect-data/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @stingaa, I checked on this - the answer I got is that unfortunately there isn't a way for an end user to reduce the requested scopes with the current app/connector.

The app developers have been in touch the Github analytics team in regards to them building a new connector for Power BI and deprecating the current one, but there aren't any concrete plans as of yet.

Sorry I don't have better news!
