### ISSUE TITLE
Missing data tables needed for refreshing Power Query Model

### ISSUE THREAD

**Issue by osumvp** [MicrosoftDocs/powerbi-docs#3041]
I love the sample file. However, there are tables missing when I extract the AdventureWorksDW 2017 and 2019. Has there been any thought to provide those missing tables (vFactSales and FactSales) so the Power BI sample file can be refreshed and data added to it?

-Nick
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd23598-fd5d-f637-24a3-a62b7e8c5fa5
* Version Independent ID: 82aaf837-8834-1185-96af-b2855d16886a
* Content: [DAX sample model - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/dax-sample-model)
* Content Source: [powerbi-docs/guidance/dax-sample-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/dax-sample-model.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Hi Nick, and thanks for the nice comments! That sample is only updated every few years (yes, sorry!) so I don't see it being updated again any time soon. But I'll pass along your request, and thanks again!
