### ISSUE TITLE
Page is missing details on the share the app option

### ISSUE THREAD

**Issue by samaguire** [MicrosoftDocs/powerbi-docs#3042]
![image](https://user-images.githubusercontent.com/62320770/117727770-91de9f00-b23c-11eb-9dfe-6b1ab5900da6.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-nz/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @samaguire. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
@samaguire -- so sorry for my delayed response! This article has been updated many times since you entered this feedback, and now does mention the "share the app" functionality. Thanks!
