### ISSUE TITLE
Power BI Shared Datasets | Composite Models Now Supported

### ISSUE THREAD

**Issue by DMiradakis** [MicrosoftDocs/powerbi-docs#3043]
Microsoft Team,

Hello! According to [this Power BI blogpost](https://powerbi.microsoft.com/en-us/blog/directquery-for-power-bi-datasets-and-azure-analysis-services-preview/) as well as [this YouTube video](https://www.youtube.com/watch?v=ZSyYegfA6PQ), you can now connect to shared Power BI datasets by changing the connection mode from Live Connection to Direct Query, and when you do so, you can in fact combine that Direct Query data model with other Direct Query or Import Mode data sources.

I think the sentence below the last bullet point in the Limitations and Considerations section might need to be slightly amended, as a Direct Query Power BI shared dataset is combinable with other data sources now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models)
* Content Source: [powerbi-docs/transform-model/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @DMiradakis.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
You're right! Thanks for pointing that out, I've updated the article and it will update with the next build, likely tomorrow.
