### ISSUE TITLE
Credential cannot decrypt credentials error when opening an existing .pbix file on a new pc. 

### ISSUE THREAD

**Issue by gaofro** [MicrosoftDocs/powerbi-docs#3044]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8131601d-6602-1e2c-0f16-d4b577aaaf74
* Version Independent ID: dac38cd1-2f8f-7a18-6a07-4da8e939545f
* Content: [Power BI Desktop Send a Smile Privacy Statement - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-send-smile-privacy-statement)
* Content Source: [powerbi-docs/fundamentals/desktop-send-smile-privacy-statement.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-send-smile-privacy-statement.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @gaofro.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
