### ISSUE TITLE
Internal Error Issue in Dataflows

### ISSUE THREAD

**Issue by Dhangel03** [MicrosoftDocs/powerbi-docs#3045]
Hi, my team is experiencing quiet few failures in refreshing our dataflow with "internal error". I'm not sure if it affects the timing of refreshing the dataflow, but we are usually manually refreshing the report 3 times a day with 3 hours interval with new added data. The file is just like 55MB and the refreshing time took us 5 hrs max today 12 May 2021 which is very unusual because we are managing other dataflows that has a much more higher size of data source, the only difference is the frequency of how we refresh the dataflow. I'm not sure what could be the reason. Btw, our license is Pro and our dataflow's source is coming from an excel file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ec2a31-ae63-38f7-00e8-234bcedd571d
* Version Independent ID: ff4d4e25-80f5-cac3-49c8-a85b7cf1c476
* Content: [Dataflows Limitations, restrictions and supported connectors and features - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Dhangel03 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
