### ISSUE TITLE
Retire page or clarify its current state?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3046]
Shouldn't this page now be retired?  Or a note added to clarify that it's no longer relevant?

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed24bb68-f505-21a9-3bc3-d55aac3e988d
* Version Independent ID: f50840ad-f8c7-594c-380a-0d006db8074e
* Content: [The 'new look' of the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/service-new-look)
* Content Source: [powerbi-docs/consumer/service-new-look.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/service-new-look.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @chrisweis .  You are absolutely correct and we are in the process of retiring this page.
