### ISSUE TITLE
Tooltip message gone after change to report page

### ISSUE THREAD

**Issue by annatagithub** [MicrosoftDocs/powerbi-docs#3048]
The default tooltip message "Right click to drill through" is gone in PowerBI.com, if we change the tooltip setting of a visual to "Report Page" and when change back to default.

Steps:
1. On one of my bar chart visual, it used to have a message in its tooltips, "Right click to drill through"
2. Changed the tooltips setting to some new report page (which initially planned to be the tooltip"
3. Decided not to use the new page, change back the tooltip setting on my bar chart visual to Default
4. The message is back in PowerBI desktop.
4. After publish, go to my Workspace in PowerBI.com, the tooltip without "Right click to drill through"
5. Affecting all other visual, now all tooltips that used to have the said message, is without the message. Only happened in PowerBI.com. 

I'm using (and have to use) Power BI version August 2020

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @annatagithub -- given my delayed response, you've probably already resolved this issue. If not, I recommend creating a support issue.
Good luck!
