### ISSUE TITLE
Clarify the difference or usage of Workspaces to App

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/powerbi-docs#3049]
Your definition or opening of an APP also describes a Workspace. This text requires either clarification or differ enation between App and Workspace. Also whether a APP can use one or more Workspaces. Talk to usage, security business problem being solved by implementing an APP 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe16182b-c80c-4cc3-da85-bf6fb0fe152f
* Version Independent ID: 6b92afe7-dfda-39b3-455c-e886b27e3d70
* Content: [What is a Power BI app? - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-apps)
* Content Source: [powerbi-docs/consumer/end-user-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @devman2k, thanks for your comments about the article. I am forwarding it on to the doc author for consideration.

**Comment by mihart** [comment]
Hi @devman2k ,
You make some good points!  I've updated the article and set it to republish.  Take a look later this week and let me know if you think it still needs more detail.
Thank you
The DOCS team

**Comment by devman2k** [comment]
Thank you!!!

Thanks,
Bryan



Bryan Tuttle
President
MCT,MCSD,MCDBA,MCAD

CodeRight Inc.
20 Marion Drive
Tewksbury, MA 01876
Phone: 781-389-9695
________________________________
