### ISSUE TITLE
Login Flow Broken

### ISSUE THREAD

**Issue by JoeRandI** [MicrosoftDocs/powerbi-docs#305]
Hey guys, 
When I click the sign in button, I get a popup from jive saying "Oops, the page can't be found." 

Does this service still work? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6faf733f-4da2-a32d-4ca4-a275a6b4a2e0
* Version Independent ID: 0181ac54-9860-96de-cf20-7f95a85cf84a
* Content: [Connect to Lithium with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-lithium#system-requirements)
* Content Source: [powerbi-docs/service-connect-to-lithium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-lithium.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @JoeRandI . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by SarinaJoan** [comment]
Hi @JoeRandI, the Lithium app is still active and should allow you to connect to a community. Can you create a support ticket if this issue persists? https://powerbi.microsoft.com/en-us/support/pro/

**Comment by mimig1** [comment]
@maggiesMSFT @mgblythe - There has been no response from the user, and Sarina has provided follow up action. Can you close this?
