### ISSUE TITLE
Power BI Client

### ISSUE THREAD

**Issue by bec-smith** [MicrosoftDocs/powerbi-docs#3050]
How can customers get a network trace for the Power BI Client, not the browser? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd5e8c4-3b09-ccfa-e68f-e3c7ae6aa472
* Version Independent ID: 3ddf312e-677a-3aef-0f78-91acf55d809c
* Content: [Capture diagnostic information for support - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-capturing-additional-diagnostic-information-for-power-bi?tabs=google-chrome-or-microsoft-edge)
* Content Source: [powerbi-docs/admin/service-admin-capturing-additional-diagnostic-information-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-capturing-additional-diagnostic-information-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @becnichelesmith, thanks for reaching out to us with your question. Let me look into this a bit and I'll get back to  you.

**Comment by kfollis** [comment]
Hi @becnichelesmith - you can find trace info for the Power BI Desktop client here: https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-troubleshooting-sign-in#how-to-collect-a-trace-in-power-bi-desktop

Hope that helps! I'll be sure to add a link to the original article to make this more discoverable.
