### ISSUE TITLE
Power BI Premium Per User - Power BI | Microsoft Docs

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#3052]
[Enter feedback here] Please add under this section https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq#using-premium-per-user--ppu- that Incremental Refresh is supported

Feature description | Per User | Per Capacity
-- | -- | --
Model size limit | 100 GB | Up to 400 GB
Refresh rate | 48/day | 48/day
Paginated reports | ✔ | ✔
AI capabilities (AutoML, Impact Analysis, Cognitive Services) | ✔ | ✔
Advanced dataflows features, such as DirectQuery | ✔ | ✔
Usage-based aggregate optimization | ✔ | ✔
Deployment Pipelines | ✔ | ✔
XMLA endpoint connectivity | ✔ | ✔
Enhanced automatic page refresh | ✔ | ✔
Multi-Geo support | X | ✔
Unlimited distribution | X | ✔
Power BI reports on-premises | X | ✔
Bring Your Own Key (BYOK) | ✔ * | ✔
Incremental Refresh | ✔ | ✔

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b9b37b6-a575-eef3-ba8b-d9f3957f5772
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @prvillal . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @prvillal,

I'm checking whether incremental refresh is supported for PPU. If it is indeed supported, I'll update the table.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @prvillal,

Thank you for getting involved and for pointing out this documentation gap. I've added incremental refresh to the table in [Using Premium Per User (PPU)](https://docs.microsoft.com/power-bi/admin/service-premium-per-user-faq).

![image](https://user-images.githubusercontent.com/54834915/144255918-1bffb349-7b06-4c5d-ae89-d670f1d0c1de.png)

Thanks,

Kesem
