### ISSUE TITLE
It would be nice if things worked this way, but they don't. 

### ISSUE THREAD

**Issue by ripstaur** [MicrosoftDocs/powerbi-docs#3054]
If only we lived in the same world as these developers. Yes, this would make a lot of sense. Go to the site, get the URL, open PBI, go to "Get data," select the Sharepoint Online List option, enter the URL, and presto! You are connected. Instead what we get are error after error after error. We can enter the root, or the root of the root, or start by taking off one character at a time...nothing helps. I'm guessing that there must be some way to get this function to work, but nothing in any of these articles is getting me any closer. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57e8911-0181-d93e-4bd6-ebb6b86324c9
* Version Independent ID: 2cce7962-5ee9-5f67-af93-2c67bb10911f
* Content: [Create a report on a SharePoint List - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-sharepoint-online-list)
* Content Source: [powerbi-docs/connect-data/desktop-sharepoint-online-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-sharepoint-online-list.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @ripstaur. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
