### ISSUE TITLE
How can you make format auto when export using Power BI ? 

### ISSUE THREAD

**Issue by thelemontree10** [MicrosoftDocs/powerbi-docs#3058]
Hi,

I see in your example that the figures in your exported file is auto formatted.

I cannot replicate it.

Example: when export, the figures only show raw data (1000) when I think it should be 1,000.

Can you show me more clearly ?

Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Thanks for your comment, @thelemontree10. I've assigned this issue to the doc author for review. In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by mihart** [comment]
Hi @thelemontree10 ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.   
All the best,
the DOCS team
