### ISSUE TITLE
This does not work on PBI Desktop Version: 2.62.5222.761 32-bit (September 2018)

### ISSUE THREAD

**Issue by tolga-balci** [MicrosoftDocs/powerbi-docs#306]
Unfortunately copy and pasting to PowerPoint, Word or any other Microsoft Office products is not working.
There should be some way to do that as we can copy Excel visualizations to PowerPoint or any other Office product.
Happy to reproduce the issue and present that this is not working in PBI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [Copy and paste a visualization in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @tolga-balci -- Sorry to hear it! It sounds like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
