### ISSUE TITLE
Shared Power BI Dataset with Workspace Viewer Role

### ISSUE THREAD

**Issue by ntsiro** [MicrosoftDocs/powerbi-docs#3061]
It is claimed in this document that the "Only people with at least Read access to the dataset can see the shared dataset." 
No other limitation or requirement is described pertaining to roles for accessing shared datasets.
However, on testing and diagnosis with your support teams it appears that there is a known issue when the workspace of the report is different to that of the dataset. In which case the user needs at least contributor access. i.e. if granted only Viewer access (i.e. the minimum read access) then the report throws an error "Unable to load the model". 

this issue is described here https://community.powerbi.com/t5/Service/Shared-Power-BI-Dataset-with-Workspace-Viewer-Role/m-p/747232

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f09aabd-9f0d-f94d-6e0a-7c9a9884dd71
* Version Independent ID: b4528bd4-f503-3cc2-52ec-9257e485555e
* Content: [Intro to datasets across workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-across-workspaces)
* Content Source: [powerbi-docs/connect-data/service-datasets-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mihart** [comment]
Thanks for your comment, @ntsiro. This issue has been assigned to the doc author for review.
