### ISSUE TITLE
Deleted reports still appear in Home

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3062]
Hi,
Deleted reports still appear in Home "Favorites and frequents" section. And there seems to be no way to detele them. Kinda frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744f5d32-18ed-9018-3003-c5f9bcb3d1ff
* Version Independent ID: e2123a9f-edef-5170-05c6-98d42bc9fd35
* Content: [Find content from Power BI service Home - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-home)
* Content Source: [powerbi-docs/consumer/end-user-home.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-home.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @gvggvg . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
