### ISSUE TITLE
Why don't you have Blazor components to do this?

### ISSUE THREAD

**Issue by sarchibald-mdsol** [MicrosoftDocs/powerbi-docs#3063]
Why don't you have Blazor components to do this?
You need to keep current with your own company...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6105e897-0348-115a-6e1a-17d9d40c0c17
* Version Independent ID: af9d7502-9677-11fd-cf29-bcef34d2d941
* Content: [Embed Power BI report in a Power BI embedded analytics application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-organization-app)
* Content Source: [powerbi-docs/developer/embedded/embed-organization-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-organization-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @sarchibald-mdsol . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
