### ISSUE TITLE
Misleading use of terminology

### ISSUE THREAD

**Issue by darlove** [MicrosoftDocs/powerbi-docs#3064]
Hi.

Regarding the doc in question, some of the explanations are a bit misleading in my opinion. I only give you one example here but such formulations can be found elsewhere (also multiple times in the same article).

Quote from the doc: "In the example, the HASONEVALUE function returns TRUE only when a single value filters the Country-Region column." This formulation is highly imprecise. It should read: "In the example, the HASONEVALUE function returns TRUE only when a single value **IS VISIBLE** in the Country-Region column in the current context."

Why is this important? Well, because a table does not need to be filtered (directly) at all for the function to return TRUE but the explanation in the docs kind of implies that a value must filter a column. Filtering and visibility are two totally different animals.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 535eecb9-b5af-3df8-4f05-4b976d73b29a
* Version Independent ID: 48b8c3e1-6d05-a9c8-3857-ee9e0ab10649
* Content: [DAX: Use SELECTEDVALUE instead of VALUES - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/dax-selectedvalue)
* Content Source: [powerbi-docs/guidance/dax-selectedvalue.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/dax-selectedvalue.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by mihart** [comment]
Thanks for your comment, @darlove . This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @darlove - thanks for pointing that out. I've updated the article to reflect your feedback. Cheers. #please-close
