### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by srijan789** [MicrosoftDocs/powerbi-docs#3066]
[Enter feedback here]

there area two 'The's

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f20ec85-cf09-5d0e-317c-1897a6f63b0b
* Version Independent ID: 8979a4de-7c09-8c5d-0415-e82957d29ccb
* Content: [Radial gauge charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-radial-gauge-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-radial-gauge-charts.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @srijan789.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @srijan789 , 
Thank you for finding this.  We've made the update and set the article to republish. 
All the best,
The DOCS team
