### ISSUE TITLE
Microsoft Sustainability Calculator: Map not showing correct locations

### ISSUE THREAD

**Issue by NovoJeep** [MicrosoftDocs/powerbi-docs#3068]
Hi there,

I 'm trying the Microsoft Sustainability Calculator and I detected some issue I would report.

All my services are hosted on West Europ and France but when looking at the map under "Emissions details" it's not what I see:
- The emission points are located in Philippines and Java
- The Tooltip says "West Europe"

Is there someone who can fix that?

**Comment by KesemSharabi** [comment]
Hi @NovoJeep,

Which document are you referring to?

Thanks,

Kesem

**Comment by NovoJeep** [comment]
Sorry, it may not be the best place to post this.

This is not related to documentation but the Power BI application itself

I don't know where to post improvement suggestions for this Sustainability Calculator"

**Comment by KesemSharabi** [comment]
Hi @NovoJeep,

Apologies for the delayed response. If your still looking to submit feedback or feature ideas, you can go to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

Thanks,

Kesem
