### ISSUE TITLE
Table is misaligned - Format Strings are in the wrong columns

### ISSUE THREAD

**Issue by ruve1k** [MicrosoftDocs/powerbi-docs#3069]
The table after the sentence below is misaligned. (I.e. the 2nd row should be shifted one column to the right as shown in the modified table below.)
Here are examples of different formats for different value strings:

Values | Format String | Format String | Format String | Format String
-- | -- | -- | -- | --
&nbsp; | 0.00;-0.0;"Zero" | 0.00;; | 0.00;-0.0; | 0.00;
-1.234 | -1.2 | "" | -1.2 | ""
0 | "Zero" | "" | "" | 0.00
1.234 | 1.23 | 1.23 | 1.23 | 1.23

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b30eef-0088-3389-5e7e-8009d064e856
* Version Independent ID: 826fcaf7-aa2a-cfca-25a7-d3b1d6af7382
* Content: [Use custom format strings in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-custom-format-strings#supported-custom-format-syntax)
* Content Source: [powerbi-docs/create-reports/desktop-custom-format-strings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-custom-format-strings.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @ruve1k.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out! Fixed the issue, it'll show up in the next Docs build.
