### ISSUE TITLE
This Documentation Needs to be Updated

### ISSUE THREAD

**Issue by kevhav** [MicrosoftDocs/powerbi-docs#307]
Since the July update to Power BI Desktop, there are additional items that can be included in the theme file. There are new cards (cardName) for visual container settings, like 'title' and 'background'. And there is the new, generic 'page' visual (visualName) for setting page-level formatting options. Right?

See this:
https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-july-2018-feature-summary/#theme

Plus, that page also said: "With this month’s update, ALL visual properties can be formatted through theming, with the exception of properties that require data in advanced (e.g. data colors)."

So, I'm wondering if there are even more items that we don't know about yet, and are just not documented?

Could you please update this documentation to include all visual names, card names and properties within each card? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @kevhav! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comments - we'll go through that doc and see which elements are now available in theming.

**Comment by alexander-korn** [comment]
what about "actionbutton"? Urgently need help on that. Please update the docu, since themes are a superb Power Bi "enterprise feature"

**Comment by sMuller13** [comment]
What about the "Customize Series" section of Line and Stacked/Clustered Column charts? The functionality has been available for over a year and I still cannot find any reference to it in this or any other documentation. Am I just missing it or is it still not included?

**Comment by alexander-korn** [comment]
Unfortunately modifying the Display units of data labels is buggy / does not work. 
For example for the clustered bar chart changing it to "Thousands" in the theme will lead to an actual change to Trillions.

**Comment by alexander-korn** [comment]
What about the visual header?

**Comment by davidiseminger** [comment]
We've recently updated the Themes article, and the feature's functionality, with a whole host of improvements. Hopefully this addresses your concerns, thanks for posting.

**Comment by alexander-korn** [comment]
Hello David unfortunately action buttons and more importantly toggles for visual headers are still missing
