### ISSUE TITLE
The MicrosoftGraphSecurity Power Query connector has been deprecated. 

### ISSUE THREAD

**Issue by bezhan-msft** [MicrosoftDocs/powerbi-docs#3072]
The MicrosoftGraphSecurity connector has been deprecated. This documentation should be updated to reflect that. 

https://docs.microsoft.com/en-us/power-query/connectors/microsoftgraphsecurity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @bezhan-msft, thanks for reminding me. I have put a deprecation notice at the top of the document. It will go live later today.
