### ISSUE TITLE
You should also mention who could grant access(approve/decline) becuase report owner may receive email notification but he/she might don't have permission to approve/decline. This point should be explicitly stated. Thanks. 

### ISSUE THREAD

**Issue by MikeSunGithub** [MicrosoftDocs/powerbi-docs#3073]
You should also mention who could grant access(approve/decline) becuase report owner may receive email notification but he/she might don't have permission to approve/decline. This point should be explicitly stated. Thanks. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee97d20-cca2-c705-0429-6debab9f9a32
* Version Independent ID: 40334cca-f3c1-e8a8-7df2-e53e78ecfb40
* Content: [Request or grant access to dashboards or reports - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-request-access)
* Content Source: [powerbi-docs/collaborate-share/service-request-access.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-request-access.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @MikeSunGithub, thanks for your comment. I'm checking out whether the feature has indeed been released yet, and I will also check out the point you mentioned. Thanks!

**Comment by paulinbar** [comment]
Hi @MikeSunGithub, thanks for you comment. I have forwarded it on to the doc author for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @MikeSunGithub -- thanks for your comment. Quick question: Is it possible that the person who's listed as the Contact (whose name appears at the top of the report) is not actually the report owner? Because it is possible for a report owner to set someone else as the Contact. I'm just wondering if that's the scenario. Thanks!

**Comment by paulinbar** [comment]
Hi @MikeSunGithub,
If this is still an issue, can you please indicate whether it is the report owner who can't approve/decline, or someone who has been named as a contact but is not the owner?
In the meantime I am closing this issue, but feel free to reopen if you can provide the details we mentioned. Thanks!
