### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by robertZaufall** [MicrosoftDocs/powerbi-docs#3074]
In my case the dialog shows me **Your data is stored in 44944209aa3d4304b1a2e0960c1e1xyz-api.analysis.windows.net**.
So what region should this be?
How can the region be adjusted so the "Azure Connections" feature can be activated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe99dcd3-62d6-0f11-3b13-031eb65c426c
* Version Independent ID: c0dc599b-c84c-ae09-42a0-5c28bb635810
* Content: [Where is my Power BI tenant located? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located?WT.mc_id=365AdminCSH_support)
* Content Source: [powerbi-docs/admin/service-admin-where-is-my-tenant-located.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-where-is-my-tenant-located.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by paulinbar** [comment]
Hi @robertZaufall , I am sorry about the VERY long delay. I think this is more of a support question than it is a docs question. I suggest you try support, if you've got it: https://support.powerbi.com/, or the community: https://community.powerbi.com/
