### ISSUE TITLE
Custom Visuals security review is not referenced

### ISSUE THREAD

**Issue by wgbrown** [MicrosoftDocs/powerbi-docs#3076]
The documentation around custom visuals does not call out the security reviews done for certified visuals.

**Comment by paulinbar** [comment]
Thanks for your comment, @wgbrown. I've assigned this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @wgbrown,

Can you please explain what you're referring to as 'security review'?

Are you referring to this document - [Get a Power BI visual certified](https://docs.microsoft.com/power-bi/developer/visuals/power-bi-custom-visuals-certified)?

Thanks,

Kesem
