### ISSUE TITLE
Power BI AutoML tutorial : Credentials are blank by default, causing training to fail

### ISSUE THREAD

**Issue by joelgibby** [MicrosoftDocs/powerbi-docs#3078]
In the tutorial, when clicking “Save and Train”, the refresh process begins but fails with "Credentials not found for data source" 

Going to the data flow ellipses > settings > Credentials and assigning proper credentials where needed allows the next refresh to complete.

---#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a Machine Learning model in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-tutorial-build-machine-learning-model)
* Content Source: [powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @joelgibby. I've assigned this issue to the doc author for review.

**Comment by joelgibby** [comment]
Helpful screenshot from https://docs.microsoft.com/en-us/power-bi/connect-data/service-aml-integrate?context=azure/machine-learning/context/ml-context#enable-datasets-to-refresh

https://docs.microsoft.com/en-us/power-bi/connect-data/media/service-aml-integrate/data-refresh.png

**Comment by davidiseminger** [comment]
Thanks for the insights and suggestions! I've added those steps to this tutorial.
