### ISSUE TITLE
Example code doesn't compile - overload updated and requires additional parameter

### ISSUE THREAD

**Issue by matt-hartsock** [MicrosoftDocs/powerbi-docs#3080]
Following the same steps provided in the C# console application will not result in a compliable solution.  line 48, where the token var is set has an invalid cast from System.Uri to Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential.  It appears the overload of the function AcquireTokenAsync now requires PlatformParameters as a 4th parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for your comment, @matt-hartsock. I've assigned this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @matt-hartsock,

I'm sorry to say that this article is very old, and that the code in it is probably not accurate. It really needs a good refresh but unfortunately that's not going to happen soon.

If you need help trying to figure this out, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). 

Thanks,

Kesem
