### ISSUE TITLE
Microsoft Graph Security (Beta) no longer appears in the Get Data list

### ISSUE THREAD

**Issue by bradrush** [MicrosoftDocs/powerbi-docs#3084]
Hi there, it seems the Microsoft Graph Security (Beta) has been removed. Pity because that is what I am wanting to use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Thanks for your comment, @bradrush. Yes, you're right, it's been deprecated. You've reached the documentation channel, but you can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
