### ISSUE TITLE
Linked Entity Support in PPU

### ISSUE THREAD

**Issue by rhariharaneee** [MicrosoftDocs/powerbi-docs#3086]
I can see this below line. is it specific to Power BI Premium not PPU? I can use Linked Entity in PPU. Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @rhariharaneee. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Yes, Premium Per User is a Premium subscription. Hope that helps.
