### ISSUE TITLE
Clarify Premium vs. PPU

### ISSUE THREAD

**Issue by ZacharyGoldman** [MicrosoftDocs/powerbi-docs#3087]
Hi! It would be helpful on this page to clarify how PPU impacts all of the mentions of "premium required." If I have a PPU license, which of these capabilities are available and what are the differences in how dataflows work with Premium vs. PPU? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @ZacharyGoldman. Good question. We've had some others asking for more clarity too. I've assigned this issue to the doc author for review. Thanks taking the time to provide your feedback!

**Comment by davidiseminger** [comment]
Thanks for your comment. A PPU or Premium capacity works for Premium. I've added clarification in the article.

**Comment by roberto-caeiro** [comment]
We have the PPU license, is it possible with this license to use computed entities in dataflows?
