### ISSUE TITLE
Limitation not called out 

### ISSUE THREAD

**Issue by olthomps** [MicrosoftDocs/powerbi-docs#3088]
One limitation that is not called out is RLS will not work for embedded web part, when the Power BI Report is connecting to an Analysis Services model with RLS. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed a report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mberdugo** [comment]
Hi @olthomps. It's been a long time since you opened this issue. Can you tell me if it's still an existing issue or if it's been fixed in the past 2 years?

**Comment by mberdugo** [comment]
Hi @olthomps, I believe this document https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-azure-analysis-services addresses the scenario you mentioned. It was added bout a year ago. I'll close this issue now, and if you still have this problem, please open another one. Thanks.
