### ISSUE TITLE
Adobe Analytics - Versions [1.0 vs. 2.0 Beta] Documentation

### ISSUE THREAD

**Issue by Geary46** [MicrosoftDocs/powerbi-docs#3089]
[Hello, Our team recently noticed that our data connection became broken with PowerBi when the 2.0 Beta option became available. Can you adjust this documentation to include how to authenticate sign in from both the 1.0 and 2.0 versions? We are also experiencing a freeze when trying to authenticate in the 1.0 version currently and I don't know which API feature to point the Adobe Analytics team to to fix. More details about the back end would be helpful in this documentation]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b88aa9e-5500-8904-286c-4a6d22be2e9f
* Version Independent ID: b0faa18f-b2ca-4c95-3486-7227cfb31277
* Content: [Connect to Adobe Analytics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-adobe-analytics)
* Content Source: [powerbi-docs/connect-data/desktop-connect-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-adobe-analytics.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your comment, @Geary46. I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
We're in the process of updating all connector documentation and will update accordingly. Meanwhile, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
