### ISSUE TITLE
I could not find the Export Button

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/powerbi-docs#309]
Can you please let me know why I could not see the export button. I see "Show Data" and "Spotlight"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-export-data)
* Content Source: [powerbi-docs/consumer/end-user-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-export-data.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @ravick4u 
Good catch.  That article has been removed as exporting is no longer available to end users. 
The updated article is here:  https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data.  If you're looking at a report in Reading view, you won't have the option to export data -- you need to open it in Editing view (if you have the permissions).  On a dashboard, if it was shared with you or is part of an app, export won't be available. 
I hope this helped clarify things.
Take care,
Michele

**Comment by GeorgeCMElliott** [comment]
So when is MS going to reverse this before more people notice?
