### ISSUE TITLE
[Revision-Request] Gen2 Chart

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3090]
Hi Authors,

I hope you're doing well and safe.
Could you please check the chart as below:

![image](https://user-images.githubusercontent.com/73410575/120424637-c3640980-c3a7-11eb-84da-47554afbd3d1.png)

There is no info about P4 and P5.
Could you please update these?

Thank you,
Hiroki

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#limitations-in-premium-gen2)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Hyamyam . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Hyamyam,

Are you referring to the table in [Capacity nodes](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#capacity-nodes)? If so, it has been updated and now reflects the P4 and P5 SKUs.

Thanks,

Kesem
