### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by cmargraff** [MicrosoftDocs/powerbi-docs#3091]
Last link in next steps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 800d2586-fb2d-0057-f709-7a58ae9648aa
* Version Independent ID: f6c68337-f88a-ebd3-ece5-8a051993dbd5
* Content: [Data protection in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-data-protection-overview)
* Content Source: [powerbi-docs/admin/service-security-data-protection-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-data-protection-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @cmargraff, thanks for pointing this out. I will find another link or take that one down.
