### ISSUE TITLE
Namespace 'powerbi' has no exported member 'VisualEnumerationInstanceKinds'.ts(2694)

### ISSUE THREAD

**Issue by krngd2** [MicrosoftDocs/powerbi-docs#3092]
I am trying to implement conditional formatting but there is no exported member in 'powerbi-visuals-api'

version 
    "powerbi-visuals-api": "~2.6.1",
    "powerbi-visuals-utils-dataviewutils": "2.2.1"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3300d18-dfe1-a0a0-597e-2f5760924ca1
* Version Independent ID: 29fd380a-48fa-a99c-0e3a-4e3b314f99dd
* Content: [Conditional formatting in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/conditional-format#define-how-conditional-formatting-behaves)
* Content Source: [powerbi-docs/developer/visuals/conditional-format.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/conditional-format.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @krngd2, thanks for reaching out to us. I have forwarded your comment along to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @krngd2. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

@uve - can you provide a quick fix/answer for this issue?

Thanks,

Kesem

**Comment by krngd2** [comment]
Thanks @KesemSharabi This issue is fixed here https://github.com/microsoft/powerbi-visuals-api/issues/24.
