### ISSUE TITLE
URL by icon is now available in matrix

### ISSUE THREAD

**Issue by mothman11** [MicrosoftDocs/powerbi-docs#3093]
URL by icon is now available in matrix, the docs should be updated :)
Glad I tried it, after my initial disappointment after reading the docs that say it's not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-hyperlinks-in-tables#create-a-table-or-matrix-with-a-hyperlink)
* Content Source: [powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mothman11 -- thanks for pointing that out! 
Question: When I add a URL to a matrix and turn on the URL icon, I still see the URL itself if the URL field is in Rows, but I see the icon if the URL is in Columns. Are you seeing the same?

**Comment by paulinbar** [comment]
Hi @mothman11, moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for providing your feedback!
