### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#3100]
Hi, even though the page says:

_you cannot publish or import the workbook back into Power BI, because you can only publish or import workbooks into Power BI that have data in tables, or that have a data model_

I was able to publish a workbook with a simple pivot table connected to the dataset.

I couldn't find a way to refresh it when the underlying dataset was refreshed, however, even though I don't see any problems with circular references as also stated in the page:

_Since the new workbook simply has a connection to the dataset in Power BI, publishing or importing it into Power BI would be going in circles!_

I can't understand why refreshing would not work.

Thanks!
Adolfo

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#refresh-and-dynamic-data-sources)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @asocorro, thanks for reaching out to us with your question. I have forwarded it on to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. While what you found might work, it may not be a supported scenario. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
