### ISSUE TITLE
AAS and gateway update

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#3101]
On Page 86 of the May 2020 release of the Enterprise Deployment Whitepaper there is a reference to utilizing the gateway with AAS behind a VNET. 

<quote>
`If you are connecting to Analysis Services through the data gateway (for on-premises AS, or AAS within a virtual network), `
</quote>

However the Data sources document site states that AAS is not supported with a Gateway in any circumstance.  This has the potential to drive confusion when determining the right architecture for the solution.

Link to data sources doc stating no gateway capabilities for AAS connector:
https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources

Thanks!

Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd0baa2-2e0a-9bbe-115f-f545f7c1ec84
* Version Independent ID: 6148e740-b101-cf26-f445-0b6dc190b39e
* Content: [Power BI enterprise deployment whitepaper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md)
* Service: **powerbi**
* Sub-service: **pbi-enterprise**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by vtitte2020** [comment]
Will add further to Ross feedback, AAS is not supported in a virtual network. "AAS within a virtual network" line should be removed.

**Comment by paulinbar** [comment]
Hi @vtitte2020, thanks for reaching out to us with your comment. I have forwarded it along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thanks for your post @rosscouldrey and the follow-up @vtitte2020. The whitepaper is in the process of being updated, and that passage will be corrected. Meanwhile, to be clear, the Power BI Data Sources article is correct.
