### ISSUE TITLE
Clarification about the limitations and considerations

### ISSUE THREAD

**Issue by AnooshaGarimella** [MicrosoftDocs/powerbi-docs#3102]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02b27c75-1cfd-7fdd-33d8-a401fcf2989c
* Version Independent ID: 0bd5b042-8ab5-bca0-64bb-c0c59665f4d8
* Content: [Connect to an Impala database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-impala)
* Content Source: [powerbi-docs/connect-data/desktop-connect-impala.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-impala.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

Hi there!! I am looking at the impala database connector with power bi. In the limitations and considerations section, it is mentioned : "The Impala connector is supported on the on-premises data gateway, using any of the three supported authentication mechanisms"  Is the connector not supported or supported?

**Comment by AnooshaGarimella** [comment]
My customer is facing a lot of issues while using the on-premises gateway with the impala connector and hence the question.

**Comment by paulinbar** [comment]
Hi @AnooshaGarimella, thanks for reaching out to us with your question. I have forwarded it along to the doc author for consideration.

**Comment by AnooshaGarimella** [comment]
Hello,

Do we have any update on this request? May I setup a quick meeting with the content owner to clarify all the questions I have on the doc?

Thank you.

Regards,
Anoosha Garimella

**Comment by paulinbar** [comment]
Hi @AnooshaGarimella, I am not the doc author, but it sounds from reading the doc that it is supported both on Desktop and on-premises, perhaps, as far as on-premises is only if one of the three supported authentication methods is used. That is probably what you understood as well. I did find this support article, while perhaps not relevant to your situation, does indicate some kind of support in Desktop and on-premises: https://community.powerbi.com/t5/Desktop/Unable-to-Connect-Power-BI-to-Impala-connector/m-p/836587#M401762.

**Comment by davidiseminger** [comment]
Hello @AnooshaGarimella - the documentation is correct. Impala is supported, and a gateway is required, as described.

This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
