### ISSUE TITLE
On Premise Data Gateway will not connect to DB

### ISSUE THREAD

**Issue by SwaglordHabib** [MicrosoftDocs/powerbi-docs#3103]
I'm trying to connect to a SQL Server, somemthing called like [foo.companyname.bar] with the On Premise Data Gateway. Unfortunately I get this error:
![image](https://user-images.githubusercontent.com/43405332/120790740-9c3a4300-c533-11eb-8623-2e6abee3bed7.png)
(I've removed the gateway name from the picture)

I am convinced that this is not a credentials issue, otherwise the error message would be something like "Unable to Connect. Details: "Invalid connection credentials""

I'm using the gateway-version 3000.68.15 from December 2020. 

#163 points out the problem, but describes that it is solved in the September 2018 release.

I've also looked at this: [Troubleshoot gateways - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot) but this problem isn't listed there.

Any thoughts?

Thanks for your time and afford

**Comment by paulinbar** [comment]
Thanks for your comment, @SwaglordHabib. This looks like a support request or product question rather than documentation feedback. I suggest you try asking in the [Power BI Community]( https://community.powerbi.com), or on our [support page](https://support.powerbi.com). Thanks!
