### ISSUE TITLE
Adhoc Invites through Report and Dashboard Sharing.

### ISSUE THREAD

**Issue by raghu4sangeeth** [MicrosoftDocs/powerbi-docs#3105]
In Section - https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b#invite-guest-users 

it is indicated that the users are able to send adhoc invites through "Report / Dashboard Sharing", Per the new sharing experience this is not allowed any more. Please remove the option from the documentation to avoid any confusion.

Please take a look the the documentation section here - https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards#link-settings

Excerpt below from above - 

Specific people

This type of link allows specific people or groups to access the report. If you select this option, enter the names or email addresses of the people you wish to share with. With this link type you can share to guest users in your organization’s Azure Active Directory (AAD), but you cannot share to external users who are not guests in your organization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by raghu4sangeeth** [comment]
To be more specific, we in the new experience adhoc invites need to be sent through the direct access only. This is not documented.

**Comment by paulinbar** [comment]
Thanks for you comments, @raghu4sangeeth. I will review the document and make necessary changes.

**Comment by paulinbar** [comment]
Hi @raghu4sangeeth, I have passed your comments along to the product team and will update the docs if necessary. Thanks!
