### ISSUE TITLE
Confusion on how to share report outside organization

### ISSUE THREAD

**Issue by zwiddoss** [MicrosoftDocs/powerbi-docs#3107]
This article does not seem to help me understand how I share a report outside my organization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @zwiddoss -- does this section answer your questions?
https://docs.microsoft.com/power-bi/collaborate-share/service-share-dashboards#share-outside-your-organization
If not, please let me know your specific questions.
Thanks!
