### ISSUE TITLE
How to access colors set in Conditional formatting

### ISSUE THREAD

**Issue by krngd2** [MicrosoftDocs/powerbi-docs#3110]
I was able to implement the conditional formatting and its showing up in format pane but Where can we access the colors defined in there? This is not mentioned in the article.  I am using Matrix Data view mapping  
I am using class method to define Format Settings.

```
public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstance[] | VisualObjectInstanceEnumerationObject {
        if (options.objectName === 'customFormatting') {  
            return <VisualObjectInstance[]> [{ 
                    objectName : "Custom Formatting",
                    properties : {
                        fill: {solid: {color: '#000000'}}
                    },
                    propertyInstanceKind: {
                        fill: VisualEnumerationInstanceKinds.ConstantOrRule
                    },
                    altConstantValueSelector: this.host.createSelectionIdBuilder().withMatrixNode(this.matrix.rows.root, this.matrix.rows.levels).createSelectionId(),
                    selector : dataViewWildcard.createDataViewWildcardSelector(dataViewWildcard.DataViewWildcardMatchingOption.InstancesAndTotals)
                }]; 
        } 
        return VisualSettings.enumerateObjectInstances(this.settings || VisualSettings.getDefault(), options);
    }
```
I am unable to figure out how to access colors now. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3300d18-dfe1-a0a0-597e-2f5760924ca1
* Version Independent ID: 29fd380a-48fa-a99c-0e3a-4e3b314f99dd
* Content: [Conditional formatting in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/conditional-format)
* Content Source: [powerbi-docs/developer/visuals/conditional-format.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/conditional-format.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @krngd2,

Thanks for your comment. @uve - can you please help here? Is there information missing from the article?

**Comment by uve** [comment]
@krngd2 please send the link to your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>. We'll check the issue.
