### ISSUE TITLE
Customer is unable to share reports to external users using Microsoft 365 group

### ISSUE THREAD

**Issue by rushirvk94** [MicrosoftDocs/powerbi-docs#3115]
Hi Team,
I am Microsoft support engineer ,I was handling a case in which cx mentioned that he is unable to share reports to external users using Microsoft 365 group. So we created an IcM but PG team told me that this is not a bug and this is by design. But in the official sharing report documentation ,nowhere mentioned that we cannot use M 365 groups while sharing reports to users. Customer was asking me to provide official doc or supporting documentation for the same but I could not find it.It is only mentioned as-"Sharing only supports users, distribution groups, or security groups per the documentation:

https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards

"You can also choose to directly send the link to Specific people or groups (distribution groups or security groups). Just enter their name or email address, optionally type a message, and select Send.".

![image](https://user-images.githubusercontent.com/85628851/121371430-2bdc5900-c95b-11eb-969d-aa4eafa0fb00.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @rushirvk94 ! Updating the article to make it clear that you can’t use Microsoft 365 Unified groups for direct sharing, either internal or external.
