### ISSUE TITLE
Link to Azure Information Protection pricing is broken

### ISSUE THREAD

**Issue by IrkenCR** [MicrosoftDocs/powerbi-docs#3116]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233c91bd-3428-d866-aa90-56c18c750153
* Version Independent ID: 5d5597ab-0b10-47b1-ac9c-fca9946a2eab
* Content: [Using Microsoft Cloud App Security controls in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-using-microsoft-cloud-app-security-controls)
* Content Source: [powerbi-docs/admin/service-security-using-microsoft-cloud-app-security-controls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-using-microsoft-cloud-app-security-controls.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by kfollis** [comment]
@IrkenCR - Thank you for bringing this to our attention. It appears that the target page is no longer available and the link is also broken on the marketing page. I'm assigning this to the writer to follow up to see if a better destination is available.

**Comment by paulinbar** [comment]
Hi @IrkenCR , well I see the Azure Information protection pricing info still isn't available on the Azure Information Protection site. I have escalated the issue and will continue to monitor. Right now the link on our page just goes to the Azure Information Protection page (which is live). The problem now is that the Pricing info link on that page is broken. That is what has been escalated. So in the meantime I am closing this issue. Thanks!
