### ISSUE TITLE
Power BI Desktop PDF Export

### ISSUE THREAD

**Issue by paulHQ** [MicrosoftDocs/powerbi-docs#3119]
Where is the pdf exported to?
I can't find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export your reports to PDF format from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-export-to-pdf)
* Content Source: [powerbi-docs/create-reports/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-export-to-pdf.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@paulHQ - the pdf file should automatically open in your browser, but if you've closed it, you should be able to find the pdf in your local downloads folder (users/username/downloads). I am closing this issue now, but will follow up with my team offline to consolidate the related articles.

**Comment by paulHQ** [comment]
@kfollis Hi Kate, and thanks for your prompt reply.
Certainly, if I publish and then export from the online PowerBI console it does land in my downloads folder.
But what is the situation if I export to pdf from the desktop version?
If all goes well, my pdf will open, and I can then save it.  
However, I have had situations where I've accidentally closed the file before saving it or PowerBI itself has crashed in the export process. In these cases, I want to locate the exported pdf file.
There seems to be no option to set an export folder either in the settings or in the export process itself.
Where do files exported from the desktop version go?
Can I change this setting?
Thanks for your help.
