### ISSUE TITLE
How to select multiple columns in many-to-many relationship

### ISSUE THREAD

**Issue by yzhong94** [MicrosoftDocs/powerbi-docs#312]
The description says "Select tables and columns that are related," but I can only select one column per table.  Can I actually selet two keys for the relationship?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477d54a5-8a27-ae63-9887-9801639962e8
* Version Independent ID: 8a2c56c0-cf25-bd2d-8de9-207ccc1e83d1
* Content: [Many-to-many relationships in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-many-to-many-relationships)
* Content Source: [powerbi-docs/desktop-many-to-many-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-many-to-many-relationships.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @yzhong94 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by BarakAvrahami** [comment]
Hello,
I would like to understand what will be the preformance delta in the new M:M VS using a star schema model with a key_table the middle.
Wont it be less efficient to have this snowflak model instead of a star model ?
I would wonder why not the have a feature that creates a star schema for you..

**Comment by Borfnog** [comment]
I second this comment - should we be able to select 1+ columns for relationships? The repeated use of column(s) plural is confusing.

**Comment by davidiseminger** [comment]
Sorry for the confusion - I believe that's suggesting you select one column per table (thus, 2 tables is 2 columns). I'll see if I can make that clearer - thanks!
