### ISSUE TITLE
Storage Blob Data Owner 

### ISSUE THREAD

**Issue by MCaviezel** [MicrosoftDocs/powerbi-docs#3120]
Hi,

I just figured out that Storage Blob Data Owner  is the correct option to select to connect to ADLS Gen2. (at least if you connect Dataverse to ADLS Gen2, which is what I have done).

The classic "owner" isn't working.

Best regards,
Marco

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@MCaviezel - thanks for the input. Assigning to the writer to make an update.

**Comment by davidiseminger** [comment]
Thanks for the clarification! I've updated that in the article.
