### ISSUE TITLE
'"powerbi-visuals-utils-svgutils"' has no exported member named 'pointer'

### ISSUE THREAD

**Issue by krngd2** [MicrosoftDocs/powerbi-docs#3121]
I am trying to import `pointer` but there is no exported module 
Error showing as 

     '"powerbi-visuals-utils-svgutils"' has no exported member named 'pointer'. Did you mean 'Point'?

`package.json` versions 

    "powerbi-visuals-api": "^3.8.2",
    "powerbi-visuals-utils-chartutils": "^2.6.0",
    "powerbi-visuals-utils-dataviewutils": "2.2.1",
    "powerbi-visuals-utils-svgutils": "^2.3.2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a591763-c35b-a993-c418-d348eeb74d5d
* Version Independent ID: 88d987a3-3d37-ecf5-286e-996bd50c99bb
* Content: [Introduction to use SVG utils in Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-svg)
* Content Source: [powerbi-docs/developer/visuals/utils-svg.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/utils-svg.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
@krngd2 - thanks for the input! I'm assigning this to the writer to take a look and update as needed.

**Comment by uve** [comment]
@krngd2, "powerbi-visuals-utils-svgutils"' has no exported member named 'pointer'. Please use "Point" instead:
https://github.com/microsoft/powerbi-visuals-utils-svgutils/blob/master/src/index.ts#L5
