### ISSUE TITLE
What has replaced it?

### ISSUE THREAD

**Issue by bkinnan2** [MicrosoftDocs/powerbi-docs#3123]
[Enter feedback here]
The page states that this feature was deprecated in May 2021, but what is to be used in its place? There doesn't seem to be a clear picture of what should be used in place of this deprecated feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by kfollis** [comment]
@bkinnan2 - unfortunately I can't advise on a replacement solution, but I'm assigning this to the writer to see if we can add that detail. In the meantime, you may find more information in the Microsoft Graph documentation located here: https://docs.microsoft.com/en-us/graph/

**Comment by paulinbar** [comment]
Hi Bob, a while back we had an inquiry from a customer regarding the deprecation of the graph security connector. In our article we point to your documentation where there is a note, but apart from saying they should use another connector, there is no guidance or recommendation. Is there further information that you can give or is that it? Thanks,
Paul
@bezhan-msft

**Comment by paulinbar** [comment]
Hi @bkinnan2, at long last I have it definitively that there is no guidance regarding what to use in the Graph Security connector's place. I have suggested that at least that should be made explicit in the deprecation notice, but I am not sure the notice will be changed. In any event, the [Power BI Community]( https://community.powerbi.com) might be a good place to possibly find others who are in the same boat and may have useful suggestions. I hope you find a satisfactory solution!

**Comment by rootsmusic** [comment]
@bkinnan2 See issue at https://github.com/MicrosoftDocs/powerquery-docs/issues/231
