### ISSUE TITLE
Does PowerBI support IE11?

### ISSUE THREAD

**Issue by rikbrowning** [MicrosoftDocs/powerbi-docs#3124]
The documentation mentions:

"Internet Explorer 11. Some advanced features, such as lineage view, aren't supported in Internet Explorer. See Data lineage (preview) for details."

Which would imply it supports IE11. However the next line is:

"Microsoft 365 apps and services, including Power BI, no longer support Internet Explorer 11 (IE 11). Refer to this Microsoft 365 blog post for more information."

Which states it no longer supports IE11.

Can this be updated with some clarification as to what is actually supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74662424-4c86-7d72-d7ad-4d8a669e83b8
* Version Independent ID: dfa6ec25-3a0c-1ee9-63b9-851c3d2ce055
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/power-bi-browsers)
* Content Source: [powerbi-docs/fundamentals/power-bi-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/power-bi-browsers.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @rikbrowning -- good question! Assigning to the author to investigate.

**Comment by maggiesMSFT** [comment]
Good question, @rikbrowning ! Updated the article to read:
"Microsoft 365 apps and services, including Power BI, will no longer support Internet Explorer 11 (IE 11) starting in August 2021."
change will be live this afternoon June 14, Pacific time.
Thanks!
