### ISSUE TITLE
Update the Limitations

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#3127]
One of the limitations of the Insights feature is that it does not work when the report is distributed via 'App'. It only works if the report is accessed directly. Please confirm with the authors and add this as a limitation. This is an important limitation to know if the report will be distributed via App. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216c87b1-d196-a091-048c-dc55b0649338
* Version Independent ID: f8bb7489-d0bd-58f0-9eb3-6471d4d57eab
* Content: [Use insights to explain increases and decreases in visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-insights)
* Content Source: [powerbi-docs/create-reports/desktop-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-insights.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @pawarbi.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for your comment! I've updated the article to reflect this limitation.
