### ISSUE TITLE
Error in "Connect to a Billing Account" steps

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3129]
Hello,

Step # 5 seems to permit two options with no discernable difference in behavior:

DOCUMENTED STEP:
For Choose Scope, select Manually Input Scope and input the connection string as shown in the example below, replacing {billingAccountId} with the data copied from the previous steps. /providers/Microsoft.Billing/billingAccounts/{billingAccountId}

STEP THAT ALSO SUCCEEDS (and is easier):
For Choose Scope, select Enrollment Number and input the Billing Account ID string as copied from the previous steps.

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @chrisweis.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
This is great! Thanks for taking the time to post this alternative, I've added it to the article.
