### ISSUE TITLE
So how do I edit data?

### ISSUE THREAD

**Issue by NeilMacMullen** [MicrosoftDocs/powerbi-docs#313]
As usual, the user experience in PowerBI is poor when you try to do something even slightly off the beaten track :(  There's not much point in being able to create data directly if I can't then edit it to correct minor mistakes or add new rows/coumns.  The "Enter Data" UI sets the expectation that I'm effectively editing a spreadsheet but once the table is added the 'obvious' edit-data option is missing; instead there seems to be an expectation that I'm going to use some super-complicated query to modify it.  (The use case here btw is in trying to quickly mock up test data for a visualisation - another area where the documentation/usability is poor enough that often the only way to figure out how things work is by trial and error.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a38a6766-9c9e-bb63-02db-893ed942db94
* Version Independent ID: ef2b000c-0ed9-fdb3-f4fe-165262b695f9
* Content: [Enter data directly into Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-enter-data-directly-into-desktop)
* Content Source: [powerbi-docs/desktop-enter-data-directly-into-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-enter-data-directly-into-desktop.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@NeilMacMullen Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by NeilMacMullen** [comment]
@markingmyname   Apologies if this came across as a bit harsh - I do realise the technical authors can't magic up missing features in the product ! :-)

**Comment by markingmyname** [comment]
@NeilMacMullen No worries.  I did not take it that way at all.  I just wanted to make sure your request was seen by the author.

Thank you.

**Comment by ashika789** [comment]
I currently have an Excel Spreadsheet i'm pulling data from. Is there a way to modify the data via a visual in Powerbi, and then somehow it will also update the excel spreadsheet? Any suggestions for a hacky way to do this if it's not implemented?

**Comment by davidiseminger** [comment]
Thanks for your comments and feedback. When importing data, to make changes to that data you do need to go back to the underlying source. There's no two-way updates (in Power BI and round-tripping to the data source) at this point. Hope that helps.
