### ISSUE TITLE
The document has no content related to the title.

### ISSUE THREAD

**Issue by alexdon75** [MicrosoftDocs/powerbi-docs#3130]
The subject line is "Organise work in the new workspaces in Power BI". This article tells about how the new work spaces are different to the old ones and how it requires licences costing twice as much.  All this is very nice.

I want to know how to organise work in a new workspace. There is NO CONTENT on this subject but that is the title of the article. Very frustrating!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @alexdon75.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hey @alexdon75 -- thanks, I love your observation! My intention with the title was to indicate how you organize _all_ of your content into different workspaces, not so much how you organize content within a _single_ workspace.  I'm changing the title of the existing article so it more accurately represents the content. Change will be live in a day or 2.
Could you elaborate on the article you wanted to find? The one about organizing work in a new workspace?
Thanks again!

**Comment by alexdon75** [comment]
Hi Maggie,

I was looking for some best practice ideas about how to organise content in
a new instance of Power BI. I'm not familiar with hte old work spaces so
the article didn't help me with my problem, although I can see hte benefit
for people moving from older work spaces. I wanted to set it up so that
people can see the reports and visualizations but I would be able to
abstract the data sources away - some of the raw data has sensitive
content. I was also looking for any things that might come up as a
maintenance problem in the future if we didn't set the granularity of a
workspace at the start. For example should a workspace be set up for a
department with perhaps 100 users (consumers of content), or a Team level
with maybe 10-20 people. The last thing I wanted to know was about setting
up hierarchies of workspaces, where a child inherited permissions or
content from the parent but not vice versa. This would allow a department /
team setup where teams could have individualised content and the
department would have content for all the teams. It would also allow a
"dev" area for us to test content before it is published to the broader
team.

Thanks!
Alex

**Comment by maggiesMSFT** [comment]
Hi, @alexdon75 -- interesting set of questions, requiring more thought. It's an interesting idea for a different article, as you say. A few of them I can answer quickly.

- Hierarchies of workspaces: Doesn't exist at this time. Good to suggest it at https://ideas.powerbi.com/ideas/, or see if someone else already has.
- A "dev" area: Have you heard about deployment pipelines? https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-overview. That may offer the functionality you need.
- Abstracting the data away: You may be able to use a combo of row-level security and creating an app from your workspace. https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps
- Should a workspace be set up for a department with perhaps 100 users (consumers of content): In general, no. Although you could give the consumers a Viewer role in the workspace. Workspaces are more designed for people to collaborate on content. Apps are a better solution for distributing to consumers.

Hope that helps!
