### ISSUE TITLE
Misleading documentation line about DirectQuery support in Power BI Snowflake SSO

### ISSUE THREAD

**Issue by dlawrences** [MicrosoftDocs/powerbi-docs#3131]
Hey team

In the related page below, instead of

> Please note that AAD SSO **only** supports DirectQuery.

I think you meant

> Please note that **only** AAD SSO supports DirectQuery.

which obviously changes the meaning of the features that are supported and are not supported. The current line misleads users into thinking you can use only DirectQuery through AAD SSO and that "Import" is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @dlawrences.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Great point! I've made that change, thanks for taking the time to clarify that - the update will appear in the next build of our Docs, likely tomorrow.
