### ISSUE TITLE
Misleading data source documentation, nothing about "Azure Database for PostgreSQL server"

### ISSUE THREAD

**Issue by Kristofdeme** [MicrosoftDocs/powerbi-docs#3136]
Nothing is mentioned about "Azure Database for PostgreSQL server".
i assume it needs the gateway as it does not seem to be considered a cloud data source by the power bi service and we are unable to get it to work without the gateway.

some misleading information is on the page stating Postgresql _is_ an approved data source and does not require a gateway. 

Gateway (support) YES
Gateway (required) NO

This does not fly for "Azure Database for PostgreSQL server" and thus should be stated explicitly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@Kristofdeme - thank you for the feedback and the details about your experience. I'm assigning this to the writer to clarify connection details for https://docs.microsoft.com/en-us/azure/postgresql/ implementations. It sounds like you were ultimately successful, but that a direct connection from the service _did_ require a gateway.

**Comment by davidiseminger** [comment]
Thanks for your comments! I've corrected that entry for PostreSQL, and will review your other question for inclusion in our content.
