### ISSUE TITLE
Need to add a explicit process to change custom visuals in "My Organization"

### ISSUE THREAD

**Issue by reneg86** [MicrosoftDocs/powerbi-docs#3137]
Based in our experience during a case (2106140040000456)  with a customer. 

I would like to add a process in the documentation:

The issue identified was that the visuals uploaded from private files included in “My Organization” section were deleted before replacing them with the visuals imported using “App source”. In this case, the visuals imported using “App source” are a different version and are identified as a separate visual ID, this is not automatically updated on all reports. The recommendation for when migrating from private files to using App source is the following:

- Import the custom visuals using App source
- Replace the visuals from private file on the reports to the new ones uploaded from App source
- Delete the custom visuals from private files to prevent confusion with versions

Please contact me if you need additional details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746e3f8f-68fd-b7d2-f61e-6bb8daa63ea4
* Version Independent ID: 50a481ef-6d50-cec0-e21b-2deab73e73b3
* Content: [Organization visuals in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
@reneg86 - thanks for the details about the procedure. I'm assigning this feedback to the writer to verify and address in the related documentation.

**Comment by reneg86** [comment]
@kfollis Hi, thanks for your quick response. Regards Rene

**Comment by reneg86** [comment]
@kfollis Hi Kate, how are you, hope you are ok. I was wondering if you had an update on this request?

**Comment by KesemSharabi** [comment]
Hi @reneg86,

I updated the [Manage Power BI visuals admin settings](https://docs.microsoft.com/power-bi/admin/organizational-visuals) article according to your customer's experience. See [Replace a visual from a file with a visual from AppSource](https://docs.microsoft.com/power-bi/admin/organizational-visuals#replace-a-visual-from-a-file-with-a-visual-from-appsource).

![image](https://user-images.githubusercontent.com/54834915/125627360-7fe9a392-52c5-45c2-a6ae-ed0c3a90eddc.png)

Thanks,

Kesem
