### ISSUE TITLE
сreateModalDialog is not a function

### ISSUE THREAD

**Issue by dmitryvorono** [MicrosoftDocs/powerbi-docs#3138]
[Enter feedback here]
Hello!
I wanted to create a test dialog box as specified in microsoft docs.
But, I get an error:
```
mySuperWidget09FDE52B7F444CB6B7FC6F644D37B5D7_DEBUG.default.createModalDialog is not a function
```
in console. Along with that, i have empty window with two buttons " OK " and "Cancel". My implementation for dialog box do not create.

How would I fix this? Maybe if there are any working examples?

Versions in `package.json`:
```
"powerbi-visuals-api": "^3.8.2",
"powerbi-visuals-utils-dataviewutils": "^2.4.1"
```
and pbiviz 3.2.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3898acbd-6660-318e-a508-6ffba8418116
* Version Independent ID: 7edfb17e-b461-c8ac-45c4-1e38d294e3fd
* Content: [Creating a dialog box in a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-display-dialog-box)
* Content Source: [powerbi-docs/developer/visuals/create-display-dialog-box.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/create-display-dialog-box.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by kfollis** [comment]
@dmitryvorono - thanks for submitting feedback on our documentation. I am assigning this to the writer to consider your experience in a future update. However, for help with the error that you are seeing, please contact https://support.powerbi.com or consult with the community at https://community.powerbi.com, as we can't provide support through this channel.

**Comment by AsafMozes** [comment]
Please try to update to powerbi-visuals-webpack-plugin 2.3.0 on powerbi-visuals-tools project.
( powerbi-visuals-tools location can be usually found by “npm root -g” )

**Comment by dmitryvorono** [comment]
@AsafMozes Thank you, it works!
I would never have guessed)

**Comment by wzorn** [comment]
> Please try to update to powerbi-visuals-webpack-plugin 2.3.0 on powerbi-visuals-tools project.
> ( powerbi-visuals-tools location can be usually found by “npm root -g” )

@AsafMozes 

I'm attempting to follow the same procedure you recommended to resolve and still getting the same error that @dmitryvorono described:

Uncaught TypeError: testDialogPBI3CE526641734417E8F5DB8CCB3381F9A_DEBUG.default.createModalDialog is not a function

These are the dependencies I've setup in my package.json:


    "powerbi-visuals-api": "^3.8.2",
    "powerbi-visuals-tools": "^3.2.3",
    "powerbi-visuals-utils-dataviewutils": "2.2.1",
    "powerbi-visuals-webpack-plugin": "^2.3.0"

I wasn't sure if it the powerbi-visuals-webpack-plugin needed to be installed at package level or global, but I tried both.

I may just need a bit more guidance.
