### ISSUE TITLE
Clarify licensing for Q&A

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#314]
There seems to be no mention of licensing requirements for the Q&A functionality.  Would be great if you could add that.  Is it available to Free users?  Only Pro users?  Can Free users use it in a Premium app?  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8e2480-703a-1417-c5d9-8d019669f45a
* Version Independent ID: 17a9f60e-b9b6-8426-2176-86b5ec3cb68f
* Content: [Overview of Q&A in Power BI service and Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-q-and-a.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@chrisweis Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mihart** [comment]
Hi @chrisweis 
Thank you for the suggestion.  I've updated the article with the info.

**Comment by chrisweis** [comment]
Where is the new content? I searched “licens” and found no results.  Thanks
