### ISSUE TITLE
ExportToFileInGroupAsync does not work - Status code 'Forbidden'

### ISSUE THREAD

**Issue by frnk01** [MicrosoftDocs/powerbi-docs#3140]
There seems to be some issues with the ExportToFileInGroupAsync. I have followed the documentation provided on the docs pages, and verified that all steps are OK.

I'm running the code with service principal, and the service principal has been added to an AD group which has Administrator access to the workspace where the report I want to generate exist.

Code:
```var export = await pbiClient.Reports.ExportToFileInGroupAsync(groupId, reportId, exportRequest);```

Error code:
```Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Forbidden'```

To validate that I actually have access to the PowerBI service I have tried to run ```var reports = await pbiClient.Reports.GetReportsInGroupAsync(groupId);``` and verified that I can retrieve a list of the reports I try to access. This works fine without any issues.

Please provide some guidance on this.

**Comment by kfollis** [comment]
@frnk01 - do you have a specific document that should be updated? We use this channel to improve our documentation, but it sounds like you need support. Please contact https://support.powerbi.com or consult with your peers in the community at https://community.powerbi.com.
