### ISSUE TITLE
Documentation is outdated as Power BI UI has changed

### ISSUE THREAD

**Issue by haider392** [MicrosoftDocs/powerbi-docs#3141]
These steps are no longer accurate as Power BI UI has changed. Please update this documentation to reflect the new UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe99dcd3-62d6-0f11-3b13-031eb65c426c
* Version Independent ID: c0dc599b-c84c-ae09-42a0-5c28bb635810
* Content: [Where is my Power BI tenant located? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located)
* Content Source: [powerbi-docs/admin/service-admin-where-is-my-tenant-located.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-where-is-my-tenant-located.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@haider392 - thanks for pointing that out! We appreciate the input. I'm assigning this to get the change made and will update again after it's published.

**Comment by kfollis** [comment]
This article has been updated and should now reflect the current UI. Thanks again for the feedback!
