### ISSUE TITLE
Format Shape instructions wrong. 

### ISSUE THREAD

**Issue by tacklers** [MicrosoftDocs/powerbi-docs#3142]
The tutorial on creating and editing a title is misleading and not necessary.
On the 'Format Shape' pane there is no 'Outline' setting but there is 'Line' 
It may not mean a lot but if you're trying to follow step by step it is a pain.
The rest of the text then goes onto explain how to change transparency, put the rectangle to the back and change the font colour to white. 
I started to lose the will to live, it is always confusing to be layering and doesn't advance the learning BI cause.
Cheers, Richard
![BI-tutorial-title-formatting](https://user-images.githubusercontent.com/19391937/122607614-c41cc100-d072-11eb-8025-71d302196dcd.png)

!
[BI-tutorial-title-formatting](https://user-images.githubusercontent.com/19391937/122607464-828c1600-d072-11eb-95c0-c4fff4a0e688.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @tacklers -- I don't want you to lose the will to live! But thanks for the chuckle 😁.
I'm puzzled: I do see **Outline**, not **Line**:
![image](https://user-images.githubusercontent.com/12401230/122611578-67031a00-d036-11eb-9c12-125042d945cb.png)
In defense of the article, that section is listed as **Extra credit**... so you are in no way required to do it, to have a working report! Or you can format it completely differently if you want. Go for it!

**Comment by tacklers** [comment]
Hi Maggie,

Thanks for the response, I now see outline, my version was out of date, attached too, sorry for the bother.

Cheers, Richard
