### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by CrystalsForce** [MicrosoftDocs/powerbi-docs#3144]
Noticed typos in the article. References to "Lighting aura components" should be replaced to say "Lightning aura components"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5821622-a34a-d094-789a-f790c9b16204
* Version Independent ID: 53d46759-dd85-c50b-cf64-7b4dd3015d3a
* Content: [Use embedded analytics to embed Power BI content in Salesforce - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-power-bi-salesforce)
* Content Source: [powerbi-docs/developer/embedded/embed-power-bi-salesforce.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-power-bi-salesforce.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for your observation, @CrystalsForce. I have directed it to the doc author for consideration.

**Comment by KesemSharabi** [comment]
Hi @CrystalsForce,

Thanks for catching this typo and letting us know. It's now fixed - see [Lightning Aura](https://docs.microsoft.com/power-bi/developer/embedded/embed-power-bi-salesforce#lightning-aura).

Thanks,

Kesem
