### ISSUE TITLE
Misunderstanding of required features from PBI to user RB

### ISSUE THREAD

**Issue by Contezini** [MicrosoftDocs/powerbi-docs#3145]
Reading this Post, I believed that I needed PBI Pro, Premium **or** PPC to publish an Paginated Report in PBI Service.

So I have spent (a lot of) hours learning, understanding, creating and formatting a very powerful Report in the desktop version, which I intended to publish (at least) to My Workspace in order to generated paginated reports.
Since I only have Pro license, and my company has no Premium Workspace or so, I feel now like all the work was for nothing and this is probably due to a misunderstanding of the necessary license to use PBI RB.

In this page the following sentence is presented:
`You need a **Power BI Pro** license to publish a report to the service. You can publish and share paginated reports in your My Workspace or **in workspaces, as long as the workspace is in a Power BI Premium capacity.**`

From my understanding, I only needed PpC for other workspaces (that are not My Workspace). It may be my fault the wrong interpretation, but this costed me a lot of work!

If possible, please clarify that **PBI Pro + Premium per Capacity** is needed for any kind of publish!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce54c72d-b70b-d3ed-d959-a427c8b35f20
* Version Independent ID: 0729c97e-74d7-ac7a-26b8-54b9a7d18dbd
* Content: [Paginated reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq#feedback)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-faq.yml)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Thanks for your feedback @Contezini. I am forwarding it along to the doc author for further consideration.

**Comment by maggiesMSFT** [comment]
Hi, @Contezini -- sorry that was misunderstood. I'll rewrite to make it clearer. 
If you have a Premium Per User (PPU) license, you can make any workspace, including My Workspace, a Premium workspace. See https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq#end-user-experience
Then others will also need a PPU license to view content in that workspace.
