### ISSUE TITLE
Power BI deployment pipelines - licensing requirements and embedded capacities

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3146]
[Enter feedback here]
For the licensing requirements part it is not clear enough whether A SKU can be used with Power BI deployment pipelines. This documents is only mentioning Premium capacities, which is confusing.
https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#accessing-deployment-pipelines

This is troubleshooting doc is the only document that describes the possibility to use A SKU instead of Premium capacity.
https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting#what-type-of-capacity-can-i-assign-to-a-workspace-in-a-pipeline

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b120d7-3f8f-8bc7-2987-21dbf1090ff2
* Version Independent ID: 6456d67d-cab6-01e1-3654-4848c5058253
* Content: [Get started using deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#accessing-deployment-pipelines)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @anna907 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @anna907,

Thank you for your comment.

I added a link to the [capacity troubleshooting entry](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-troubleshooting#what-type-of-capacity-can-i-assign-to-a-workspace-in-a-pipeline) from the overview of the [Get started with deployment pipelines](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-get-started#accessing-deployment-pipelines) article.

![image](https://user-images.githubusercontent.com/54834915/124374302-cbfb7880-dca2-11eb-8473-9934711b0883.png)

Note that the information in the troubleshooting entry is correct, A SKUs can be used for embedded content.

I hope this clarifies matters.

Thanks,

Kesem
