### ISSUE TITLE
Power BI dataset permissions - documentation on read permissions missing

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3147]
[Enter feedback here]

This article (https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions) is only describing the build permission for datasets. There is no document describing the dataset Read permission in detail however.

See this article for example, there is a comparison matrix between different workspace roles - would it be possible to have something similar for the dataset permissions as well?
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces#roles-in-the-new-workspaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @anna907, thanks for your comment. You are exactly right, and this has come up as an issue several times recently. Providing something more clear, perhaps along the lines of the matrix you mentioned, is on my to-do list for the near future. Thank you for underscoring the importance of getting some clarity here.

**Comment by paulinbar** [comment]
Hi @anna907 , sorry for the long delay. Since you wrote, an article has been added about dataset permissions.

https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-permissions

Please take a look and see if that serves your needs. I am closing this issue now, but please reopen if you have further feedback for the docs team. Thanks!
