### ISSUE TITLE
Failure of Power Bi Refreshing a Dataflow causes whole reference chain to rollback

### ISSUE THREAD

**Issue by sidm-dev** [MicrosoftDocs/powerbi-docs#3148]
https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-configure-consume#refreshing-a-dataflow

Query regarding this statement:-
"
If any of the dataflows in a reference chain fail to refresh, all the dataflows will roll back to the old data (dataflow refreshes are transactional within a workspace).
"
If a Source refreshed successfully, and triggered a refresh of a linked table, why is the whole chain rolled back? Especially the source? Shouldn't only the down stream items rollback to their non refreshed state.

Also, is it possible for the same source to be referenced by other chains. if so, if the source gets refreshed, all fan-out chains would attempt to be refreshed. If one of those fanouts failed to refresh, what gets rolled back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure and consume a dataflow - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-configure-consume)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @sidm-dev.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
