### ISSUE TITLE
SQL Profiler not working

### ISSUE THREAD

**Issue by rhlgupta1383** [MicrosoftDocs/powerbi-docs#315]
Working with the section - "Deep-dive into query performance with SQL Profiler and Power BI Desktop", the profiler did not show any results. I used the following steps:

1. Checked the port used by msmdsrv.exe
2. Started profiler -&gt; New trace -&gt; Analysis Services -&gt; localhost:&lt;&lt;my port number&gt;&gt;
3. Cleared trace
4. Opened the Power BI report

Kindly revert, in case something is missing or needs to be changed to get the trace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc3724b-5c69-73df-1ff2-8fa0a28c9c79
* Version Independent ID: 86932e18-54c4-dc9e-67f9-fe95f1e20f08
* Content: [Power BI performance best practices - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-reports-performance)
* Content Source: [powerbi-docs/power-bi-reports-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-reports-performance.md)
* Service: **powerbi**
* GitHub Login: @MarkMcGeeAtAquent
* Microsoft Alias: **kfile**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rhlgupta1383. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

This looks like it also may be a support request - you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by mgblythe** [comment]
@rhlgupta1383 - I know this one is old, but for future reference the steps in the doc are correct.
