### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by skstanley11** [MicrosoftDocs/powerbi-docs#3150]
In the formatting section of the tutorial where users are asked to add a background shape for visuals 2 and 3. The following instruction is provided:

Fill section, set the coloer to White, 10% darker

The word color is spelled incorrectly.

![PBI Module 2](https://user-images.githubusercontent.com/26886767/123137242-604f1b00-d419-11eb-81ce-4f79062875eb.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @skstanley11 ! Fixing it now, will be live this afternoon June 23, Pacific time. Love those easy fixes! 😊

**Comment by skstanley11** [comment]
@maggiesMSFT thanks for picking this one up and knocking it out of the park! These tutorials are absolutely wonderful, we appreciate them and your efforts!
