### ISSUE TITLE
Title Ribbon Instructions Need Updating

### ISSUE THREAD

**Issue by skstanley11** [MicrosoftDocs/powerbi-docs#3151]
In Visual 1, users add a title to the report. Further on in the tutorial, users are asked to add a light blue ribbon to the title area of the report. However, in order for the Visual 1 text to be brought forward and appear on top of the blue ribbon, users need to make Visual 1 100% transparent.

![image](https://user-images.githubusercontent.com/26886767/123137835-08fd7a80-d41a-11eb-8145-b7c048807286.png)

**Comment by maggiesMSFT** [comment]
Hi, @skstanley11 -- we're talking about this article, right? https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#build-your-report
IDK why it didn't include the link. 
But wait: If you set the transparency of the rectangle fill to 100%, then the rectangle will have no color, right? It has to be transparency 0%, and then you select **Send to back**.
![image](https://user-images.githubusercontent.com/12401230/123481244-51eb3580-d5b8-11eb-84ff-fb0708eb400f.png)
Try it! 😊

**Comment by skstanley11** [comment]
Hey @maggiesMSFT - I am so sorry for the slow response and thank you so much for you assist! The article that you reference is correct. Let me take a look at the instructions again and I am also leading an internal training tomorrow and will see if this group of users struggles with the instructions. Hold please!

**Comment by maggiesMSFT** [comment]
Hi, @skstanley11 -- I hope the training went OK! Feel free to reopen this issue or create another one, if need be. Cheers!
