### ISSUE TITLE
[Update request] Annotation of P4/A7 & A8/P5 SKU

### ISSUE THREAD

**Issue by shogo0729** [MicrosoftDocs/powerbi-docs#3152]
Hi,
I am requesting document update as below.

**[Update request]**
Annotation of P4/A7 and A8/P5 SKU is not clear of what the customer needs to do next for introducing those large SKUs.
So, please clarify this point. I am sharing update idea.

**As is :** By special request only. For very large models greater than 100 GB.
**Idea :** For very large models greater than 100 GB. In order to activate this option, special request is necessary. In case of considering large SKU introduction, please contact Microsoft first 

![image](https://user-images.githubusercontent.com/86394399/123201096-0029a900-d4ed-11eb-8a0b-c66d48861f42.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#feedback)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @shogo0729 -- thanks for your question! Assigning to the author to look into.

**Comment by shogo0729** [comment]
Hi @maggiesMSFT, Thank you so much for your comment!! I would be very happy to contribute this improvement

**Comment by shogo0729** [comment]
@maggiesMSFT Do you have any update on this??

**Comment by shogo0729** [comment]
@maggiesMSFT , @davidiseminger,
Do you have any update on this?

**Comment by maggiesMSFT** [comment]
Actually, @shogo0729 -- you CAN contribute! If you select the Edit pencil in the upper-right corner of the article, you can make the change you'd like to see and submit a pull request for it. Give it a try!

**Comment by davidiseminger** [comment]
Yes @shogo0729 - you can update the doc directly. Let me know once you've done that, and I'll approve it then close this. Doing that (the update yourself) will enable you to make other contributions in the future, too. Thanks!

**Comment by KesemSharabi** [comment]
Hi @shogo0729,

Can you please explain what's the added value of your suggestion? I.e. what's the different between these to options:

* **The current version** - By special request only. For very large models greater than 100 GB.

* **Your suggestion** - For very large models greater than 100 GB. In order to activate this option, special request is necessary. In case of considering large SKU introduction, please contact Microsoft first

Thanks,

Kesem

**Comment by shogo0729** [comment]
Hi @Kesem ***@***.***>

Thanks for your comments.
On current version : “By special request only. For very large models greater than 100 GB”, readers of this docs will not be able to understand the next action.
on the other hand,
My suggestion：For very large models greater than 100 GB. In order to activate this option, special request is necessary. In case of considering large SKU introduction, please contact Microsoft first, , readers of this docs will understand the next action and try to reach out to Microsoft soon.

Thanks,
Shogo

**Comment by KesemSharabi** [comment]
Hi @shogo0729,

I updated the table in the [Capacity nodes](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#capacity-nodes) section, and the footnote that talks about purchasing SKUs greater than 100 GB. This footnote now reads:

"SKUs greater than 100 GB are not available in all regions. To request using these SKUs in regions where they're not available, contact your Microsoft account manager."

Hope this helps,

Kesem

**Comment by shogo0729** [comment]
Thank you so much Kesem!
Confirmed the revision!!
