### ISSUE TITLE
MFA and PowerBI

### ISSUE THREAD

**Issue by JanIvarMoldekleiv** [MicrosoftDocs/powerbi-docs#3153]
The solution provided is
"If you get the error - AADSTS50079: The user is required to use multi-factor authentication.

Need to use an AAD account that doesn't have MFA enabled."

This is just a band-aid on a very bad design choice. PowerBI need to allow API-key for accessing the service. Disabling MFA for developers is just not on the cards. That means using the test projects is not possible. For all other services on Azure the authentication is handled ok. 

Please forward this to the correct team. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52df8397-ddc7-8c40-645d-51ee9b5bfd76
* Version Independent ID: 0ad10266-fd8c-465f-cb1b-f20ae21fc09f
* Content: [Troubleshooting your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-troubleshoot)
* Content Source: [powerbi-docs/developer/embedded/embedded-troubleshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-troubleshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @JanIvarMoldekleiv -- you're right, this feedback needs to go to the product team. 2 ways to get there. At the bottom of the article, next to the **This page** button, select **This product**:
![image](https://user-images.githubusercontent.com/12401230/123476983-485ecf00-d5b2-11eb-9752-fe041ea01bc8.png)

Or this link, https://ideas.powerbi.com/ideas/, will take you to the same place. 

Thanks!
