### ISSUE TITLE
Refresh token example checks too often

### ISSUE THREAD

**Issue by syastrov** [MicrosoftDocs/powerbi-docs#3154]
The JavaScript code sample for refreshing a token tries to check whether to refresh the token every 4 milliseconds.
This is far too often. Perhaps it was meant to be every 4 seconds?

https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/refresh-token

**Comment by maggiesMSFT** [comment]
Hi, @syastrov  - thanks for your question! Assigning to the author to investigate.

**Comment by KesemSharabi** [comment]
Hi @syastrov,

Thanks for your comment, I'm checking it with the development team.

**Comment by KesemSharabi** [comment]
Hi @syastrov,

You're right, the refresh interval was too short. I've changed this to be 30 seconds - see [Refresh token example](https://docs.microsoft.com/javascript/api/overview/powerbi/refresh-token#refresh-token-example).

![image](https://user-images.githubusercontent.com/54834915/124124331-f968dc00-da80-11eb-946c-3a1cc53a0aa6.png)

Thanks,

Kesem
