### ISSUE TITLE
Power BI export does not contain all data and is less than 150,000 row limit

### ISSUE THREAD

**Issue by suesweetsue** [MicrosoftDocs/powerbi-docs#3155]
Some pages on our reports are not exporting all data and is not a row limit issue. For example, we have a page with about 85,000 distinct eligible members, but the exported data contains only 25,892 rows. The export is 3,796 KB, so it is does not appear to be impacted by the 16 MB limit either. It is possible that the export may be impacted by the data that is loaded on the page, which is not complete without arduously continuing to scroll down to load more data. 

Is there a setting that may be preventing the export to contain the complete set of data?
Is there a way to load all data into the published report without continuously scrolling?

Thank you,
Susan Weinfurther

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @suesweetsue --  not sure what's going on with your visual. Assigning to the author, but you may want to ask the community, https://community.powerbi.com/.
Meanwhile, to answer your 2nd question:
"Is there a way to load all data into the published report without continuously scrolling?"
I have a suggestion: You could create a paginated report with a table that contains all the rows, and prints or exports handily. You can base it on the same dataset that's in the Power BI report. This article walks through that scenario:
https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets
Hope that helps!

**Comment by mihart** [comment]
Hi @suesweetsue ,
I see that this Git issue is a bit old, so I'm going to close it.  I hope that you were able to get your questions answered. If not, please let us know.  Another option is to submit your question to the Power BI community (community.powerbi.com).  
All the best,
the DOCS team
