### ISSUE TITLE
Reverting template app to a regular app

### ISSUE THREAD

**Issue by parna86** [MicrosoftDocs/powerbi-docs#3156]
Hi,

It would be really helpful if you could add what to do if I want to disable the option of "Developing a template app". 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-the-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @parna86 -- thanks for asking!Could you clarify, do you want to: 
Disable the option of "Developing a template app".
or 
Revert template app to a regular app
Thanks!

**Comment by parna86** [comment]
Hi @maggiesMSFT , I want to revert the template app to a regular app.

**Comment by maggiesMSFT** [comment]
Hi, @parna86 -- thanks for clarifying! I've checked, and the answer is no. You can't convert a template app workspace back to a regular workspace. Hope that clarifies, at least!

**Comment by maggiesMSFT** [comment]
@parna86 -- one suggestion: Can you upload the .pbix file to a new workspace?

**Comment by parna86** [comment]
@maggiesMSFT when I upload the file to a new workspace, I am able to create a regular app. But this involves transferring all relevant files to a new workspace.

**Comment by maggiesMSFT** [comment]
Hi, @parna86 -- Yes. I'm sorry, that's true.
