### ISSUE TITLE
Is there a limit to the number of rows in featured tables?

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#3157]
Also, should the data be immediately accessible in Excel or is there any post-processing that happens after the PBI dataset is refreshed?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74f8fd61-1d7c-6da2-7279-d88d72668a8a
* Version Independent ID: ce00fe65-ac80-be40-1bbd-ac799e6a2c53
* Content: [Set featured tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-excel-featured-tables)
* Content Source: [powerbi-docs/collaborate-share/service-create-excel-featured-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-excel-featured-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @asocorro ! How are you? I'm not sure. I'll check and get back to you. Thanks!

**Comment by Grubike** [comment]
@asocorro After publishing the dataset to a workspace, the featured table would be immediately available to search in Excel. Users would need to close and reopen any open Excel workbooks to see the data.

**Comment by asocorro** [comment]
Thank you for the quick reply.  I am getting puzzling delays and sometimes failed lookups when the featured table has millions of records.

________________________________
***@***.***D769E4.974217B0]

Adolfo J. Socorro, Ph.D.
President
eSolutions, Inc.

eSolutionsPR.com <http://www.esolutionspr.com/>
LinkedIn Profile<https://www.linkedin.com/in/adolfosocorro/>
787-553-3200 (Mobile)
.:. Business Intelligence and SQL Server Solutions .:.





The information contained in this message is a private interchange between the sender and the recipient.
Business ideas, proposals, and other such matters may not be disclosed to third parties without prior mutual consent.

**Comment by Grubike** [comment]
@asocorro There is an indexing limit for featured tables as it uses QnA; the documentation for featured table would be updated. Read more [here](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-data-sources#how-does-indexing-work-with-qa) about QnA indexing.

**Comment by asocorro** [comment]
Ok, thanks, now it all makes more sense.  I started hitting a wall when loading about 5M rows.  It's too bad because the full table has about 15M rows.  Thanks for the info.  Have a nice weekend.



________________________________

**Comment by maggiesMSFT** [comment]
Thanks for asking, @asocorro and thanks for answering, @Grubike ! I'll update the article https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-excel-featured-tables#considerations-and-limitations.
