### ISSUE TITLE
Number of Users in the App Access List

### ISSUE THREAD

**Issue by nicovillarroel** [MicrosoftDocs/powerbi-docs#3158]
[Enter feedback here]
One of the limitation described in the article says : “You can have at most 100 users or groups in the access list for the app. However, you can give more than 100 users access to the app. To do so, use one or more user groups that contain all the desired users.”
Is this still valid? Which is the expected behavior? 
Right now we have more than 200 users in the Access List, and as far as we see every thing is working fine. 
Is this is still a limit or the doc is wrong? 
Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps#considerations-and-limitations)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @nicovillarroel -- good question! I'll check and get back to you. Thanks!

**Comment by nicovillarroel** [comment]
Hello, any update on this? We are adding more and more users  to the list. Right now we have more than 400 users and we think everything is working well. Is there is any limit? 
Thank you. 
Regards, 
NIco.

**Comment by paulinbar** [comment]
Hi @nicovillarroel, thanks for the update. I see that the 100 user limitation has been lifted, although the limitation states that this relaxation is only temporary. I don't know when this happened. I'll check with the product team to find out what the current situation is, but in the meantime I am closing this issue here for now. Feel free to reopen if you run into trouble. Thanks!
