### ISSUE TITLE
Spaces in field names?

### ISSUE THREAD

**Issue by mortenf** [MicrosoftDocs/powerbi-docs#316]
In the section "Use DAX to filter on multiple values" it says: "Remember that the Field name cannot have any spaces." - is that still true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Add Power BI report parameters using the url - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @mortenf. I don't believe that requirement has changed, but we’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @mortenf -- yes, that requirement remains. I recommend going to https://ideas.powerbi.com to see if anyone else has requested that feature, and up-voting it if they have. And if not, you can create a new request!
thanks!

**Comment by mortenf** [comment]
Hmm. It is still not clear. Spaces are allowed in table names, but not in field names, and + is allowed in field names but not in table names, or?

The section just above the one in question is called "Special characters in URL filters" - and in that, there is a method for dealing with a space in a table name - but not for a field name. Also, there is an example with a "+" in a field name, but not for a table name. They are labeled as examples.

So, if the sentence "the Field name cannot have any spaces" is true, could you please add that fact to the section where a method for e.g. spaces in table names is established?
