### ISSUE TITLE
Thanks for the information. I could not find either key in my registry. Any suggestion?

### ISSUE THREAD

**Issue by MonkeySam** [MicrosoftDocs/powerbi-docs#3160]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b39a01-988d-1237-daf4-92793fb39214
* Version Independent ID: e781c340-b938-6d53-14ec-aa3269ecaa38
* Content: [Evaluation configuration settings for Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-evaluation-configuration)
* Content Source: [powerbi-docs/create-reports/desktop-evaluation-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-evaluation-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @MonkeySam. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
