### ISSUE TITLE
Section 6 appears to be incorrect

### ISSUE THREAD

**Issue by KyronSr** [MicrosoftDocs/powerbi-docs#3161]
Section 6 of the v3 code says to:

pbiClient.Gateways.UpdateDatasource(gatewayId, datasourceId, credentialDetails);

when it should be:

pbiClient.Gateways.UpdateDatasource(datasource.GatewayId.Value, datasource.DatasourceId.Value, new UpdateDatasourceRequest(credentialDetails));

It would additionally be helpful to provide documentation on how to securely update the credentials when you are using Azure SQL DB, as it does not require a gateway and this command fails:

var p = pbiClient.Gateways.GetGateway(datasource.GatewayId.Value);
(even though the gatewayid actually has a value)
Which means I cannot get the public key for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49734fef-2078-76da-a1a1-6a0f1beb49d3
* Version Independent ID: 85700b22-60a2-388d-6230-9b27e8a80d04
* Content: [Configure credentials programmatically for Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/configure-credentials?tabs=sdk3)
* Content Source: [powerbi-docs/developer/automation/configure-credentials.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/configure-credentials.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KyronSr** [comment]
Thank you -- as to my comment on updating the credentials -- I finally figured out what was going on with that piece.  This seems to be a very very common question and googling you find several half-baked efforts to make it work. 

For me to make it work, I had to
1.  Create my PBIX as attached to an Azure SQL DB
2. Import the PBIX  (PostImportWithFileInGroup)
3. Get a list of datasources with GetDatasourcesInGroup and then iterate those and set my new server and database name with UpdateDatasourcesInGroup
4. The get the list of datasources a second time with GetDatasourcesInGroup and then iterate those and set the username and password with UpdateDatasource

It might be helpful to provide a full code listing to simply change the server, database, username and password for a connection as this seems to be a common question.

**Comment by KesemSharabi** [comment]
Hi @KyronSr,

You're right about the code - thanks for catching this and letting us know!

I fixed the code snippet - see **step 6** in [Update credentials flow for data sources](https://docs.microsoft.com/power-bi/developer/automation/configure-credentials#configure-a-new-data-source-for-a-data-gateway).

As for the Azure SQL DB scenario, we're not going to document this at present as it's a specific scenario with many variables that depend on the customer's setup.

Thanks,

Kesem
