### ISSUE TITLE
Prerequisites - PBI Service Principals

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/powerbi-docs#3162]
Please add infos in the prerequisites section about permissions which will need to be set for powerbi in the storage account.
My current assumption ist that at least following is needed?!
- "Power BI Premium" Principal --> Needs "Storage Blob Data Owner" RBAC Role on Storage Account Level?
- "Power BI Service" Principal" --> Needs "Storage Blob Data Owner" RBAC Role on Storage Account Level?
- The "powerbi" and "powerbi-backup" containers MUST be created automatically by PBI, they cannot be created manually?
- Q: Is ist possible to create the conainer and ACL permissions manually? Are BRAC Management Blade permissions  absolutely required? Or ACL permissions sufficient when container is created manually?
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#grant-power-bi-permissions-to-the-file-system)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @JJDE, thanks for reaching out. I have forwarded your feedback along to the doc author for further consideration.

**Comment by davidiseminger** [comment]
Thanks for your request - we've added that information to the article.
