### ISSUE TITLE
Power Automate Visual in Power BI - run with user's connections

### ISSUE THREAD

**Issue by salilathalye** [MicrosoftDocs/powerbi-docs#3166]
Kindly provide some information in the documentation that describes how we can set up this visual so that it runs with the logged in Power BI user's credentials and connections and not the credentials and connections of the Power Automate flow author.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de472a84-f62c-d01c-a8b2-e6ea168a222d
* Version Independent ID: da8c0056-7e3d-fc14-c5a4-1bd3bab573de
* Content: [Create a Power Automate visual for Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-automate-visual)
* Content Source: [powerbi-docs/create-reports/power-bi-automate-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-automate-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Good question! I'll look into it and get back to you. Might not be immediate. I suggest asking the community, https://community.powerbi.com/

**Comment by maggiesMSFT** [comment]
Hi, @salilathalye -- you are correct, this is not possible today, the flow runs in the owner's context currently. There's a backlog item to allow manually run flows from the PowerBI visual which would allow running the flow in the users credential context, but no exact timeline for this. Hope that helps!
