### ISSUE TITLE
Does the app work with Power BI embedded capacities?

### ISSUE THREAD

**Issue by haymansfield** [MicrosoftDocs/powerbi-docs#3169]
Does the app work with Power BI embedded capacities? If so, would be good if this was indicated explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 154ed1fd-e2c5-a4fc-d164-f66505588441
* Version Independent ID: 4bf75ac1-6aaa-34ac-8117-3e756153b0bb
* Content: [Connect to Power BI Premium Capacity Metrics - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-pbi-premium-capacity-metrics)
* Content Source: [powerbi-docs/connect-data/service-connect-to-pbi-premium-capacity-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-pbi-premium-capacity-metrics.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @haymansfield, good question. I'll check with the app developers and get back to you, as well as update the article.

**Comment by paulinbar** [comment]
Hi @haymansfield, I've received an answer to your question - the answer is yes, the app does work with embedded capacities. Please see [Monitor Power BI Embedded capacity](https://docs.microsoft.com/power-bi/admin/service-admin-premium-monitor-capacity#monitor-power-bi-embedded-capacity), which is included in [Monitor Premium capacities with the app](https://docs.microsoft.com/power-bi/admin/service-admin-premium-monitor-capacity). I will add a note about this in the Connect to Power BI Premium Capacity Metrics article.
Thanks for your question!
