### ISSUE TITLE
Associate O365 group to new work space

### ISSUE THREAD

**Issue by deepu299** [MicrosoftDocs/powerbi-docs#317]
Hi @magiesMSFT, Is there any document on how to associate an O365 group or Sharepoint site to the new workspace? Also, when it says No One Drive button, is it the button which says "One Drive - Business"  and we should be using Share point - Team sites to connect files? I am looking for a way like in old workspaces where the files uploaded in One Drive are already connected and only accessible from a related workspace. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#power-bi-apps-faq)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @deepu299 -- just so you know, I'm checking on your questions. Haven't got an answer yet but I'm checking.
Re this part: "when it says No One Drive button, is it the button which says "One Drive - Business" and we should be using Share point - Team sites to connect files?"
Yes, it's that button, and yes, at least for the preview you can use SharePoint - Team Sites to connect to files.

**Comment by JustinGrote** [comment]
I can't figure out how to associate an O365 group either to a workspace, only users

**Comment by maggiesMSFT** [comment]
Hi, @deepu299 and @JustinGrote -- good news! Connecting a OneDrive or SharePoint is now on the Create a Workspace pane, when you first create it, or when you go back and edit it. If you look in the article now, under step 4 you'll see:
"Specify a Workspace OneDrive by typing just the name of the OneDrive location, not the URL. In this step, you're not creating a OneDrive location. You're specifying an existing location."
It can also be a SharePoint site. 
Hope that helps and sorry for keeping you waiting!

**Comment by deepu299** [comment]
@maggiesMSFT Thanks for the update Maggie, I am able to see the option now. Appreciate for the responses and the work done.
