### ISSUE TITLE
Embed reports are missing to guest users

### ISSUE THREAD

**Issue by ingd** [MicrosoftDocs/powerbi-docs#3170]
Hi guys,

I am looking for information about the "embed" option for guest users. Apparently, this option is missing for my third partner. They developed some dashboards and trying to embed in a portal, but this option is missing from powerbi desktop and powerbi web.

Is that possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/admin/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Have you reviewed documentation for Power BI embedded analytics? https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core describes embedding an application for customers which may satisfy your scenario.

**Comment by ingd** [comment]
> Have you reviewed documentation for Power BI embedded analytics? https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core describes embedding an application for customers which may satisfy your scenario.

You are right. This is gonna help a lot.

It was my bad. Thank you very much!
