### ISSUE TITLE
..

### ISSUE THREAD

**Issue by lindaGharbi** [MicrosoftDocs/powerbi-docs#3171]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423bed63-655a-3079-815e-0d9a8c7de44d
* Version Independent ID: ed119c4a-d4f0-7458-fd57-d7247edbd70e
* Content: [Download the Financial Sample Excel workbook for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-financial-download)
* Content Source: [powerbi-docs/create-reports/sample-financial-download.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/sample-financial-download.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @lindaGharbi, I see you opened a Github issue for the docs team regarding the article about the sample financial download, but I don't see that you wrote anything. Did you mean to include some information for us, or did you open the issue by mistake?
Let us know. Thanks!

**Comment by paulinbar** [comment]
Hi @lindaGharbi. I'm closing this issue for now since we've not heard from you. If you still have a question or feedback, please feel free to open the issue again! Thanks.
