### ISSUE TITLE
Distinction between PowerBI and PowerQueryOnline

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3173]
Hi

It would be helpful to call out the distinction between the 2 service tags which relate to Power BI

Datasets are labelled as PowerBI and dataflows as PowerQueryOnline

If not included on this page, think about incorporating into this page; https://docs.microsoft.com/en-us/azure/virtual-network/service-tags-overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764df840-9c91-7535-20fd-eb4837d14add
* Version Independent ID: b498e7ce-7a63-e45a-72c0-7b88a1dc45e8
* Content: [Using service tags with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-service-tags)
* Content Source: [powerbi-docs/admin/service-premium-service-tags.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-service-tags.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @nathanwlee1,

Adding you to an email thread and closing the GitHub issue.

Thanks,

Kesem
