### ISSUE TITLE
Embed Report is now under File menu

### ISSUE THREAD

**Issue by DesertDwarf** [MicrosoftDocs/powerbi-docs#3174]
The page mentions:
`On the Share menu, select Embed report > SharePoint Online.`

However, on my Power BI Service, the Embed report submenu is found inside the File menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed a report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo?source=docs#allowing-free-users-access-to-reports)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hey @DesertDwarf, thanks for calling this out. I've replaced the offending image. Should be online in a few hours. Many thanks!
