### ISSUE TITLE
measures table disrupting table order

### ISSUE THREAD

**Issue by fbouckae-crm** [MicrosoftDocs/powerbi-docs#3175]
We have a model on Azure Analysis Services where we don't want to use measure tables.
In some of the original tables we only have measures, so it appears in Power BI as a measures table, disrupting the alphabetical order of the tables.
is it possible to set a table that only contains measures to show as a 'non-measure' table in Power BI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 014eede5-d529-cc7c-f8d5-3e7247ee857c
* Version Independent ID: 524645c5-86ea-ef3e-a020-c74b44db2c87
* Content: [Measures in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-measures)
* Content Source: [powerbi-docs/transform-model/desktop-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-measures.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
