### ISSUE TITLE
Tab order in Power BI

### ISSUE THREAD

**Issue by prinjos** [MicrosoftDocs/powerbi-docs#3176]
Hello, 
I'm using the June 2021 version or PBI and I do not see an option to hide any objectss under Selection > Tab order. I am only able to change the order using the arrows. Am I looking in the right location?
I can hide objects in the Layers tab but this removes the object completely.

Thank you,
Joe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762701ab-7066-612d-cdc2-a729ba1b5483
* Version Independent ID: 8a64d563-9737-16d3-d83e-fb56e8d3d95c
* Content: [Creating accessible reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-creating-reports#report-accessibility-checklist)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-creating-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
