### ISSUE TITLE
PBI Premium Per User - Clarification

### ISSUE THREAD

**Issue by lphomiej** [MicrosoftDocs/powerbi-docs#3177]
If a user is on the "PowerBI Premium Per User", but the workspace isn't on Premium capacity, can that user use the deployment pipelines on that workspace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b120d7-3f8f-8bc7-2987-21dbf1090ff2
* Version Independent ID: 6456d67d-cab6-01e1-3654-4848c5058253
* Content: [Get started using deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @lphomiej,

You can use a PPU license for the development and testing stages in deployment pipelines. For the production stage, you'll need a Premium license. For more information, see - [What type of capacity can I assign to a workspace in a pipeline?](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-troubleshooting#what-type-of-capacity-can-i-assign-to-a-workspace-in-a-pipeline)

Hope this helps,

Kesem

**Comment by lphomiej** [comment]
Thanks for the clarification!
