### ISSUE TITLE
Targeted release doesn't appear to add visibility

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerbi-docs#3178]
We've wanted to test this feature internally and setup users on the targeted release and added their groups to the Power BI role for tenant settings as well, but it never displays.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @cvillegashak -- I'm checking and will get back to you. Thanks!

**Comment by amandariveraMSFT** [comment]
Hey @cvillegashak - We actually just rolled this feature out to all users, not just targeted release users: https://powerbi.microsoft.com/blog/visualizing-sharepoint-lists-now-available-to-all-users/  (the doc will be updated with this information soon). 

Are you still having issues seeing the Power BI option within the Integrate menu?

**Comment by cvillegashak** [comment]
Hi @amandariveraMSFT No more issues! :) It appeared after your blog post. We just clammored for it after your MBAS presentation and set up a few users on the Insider release as well as anything else we could do to get the Preview features in M365 and it never appeared until the day you mentioned it was available for all. Thanks again!
