### ISSUE TITLE
not able to use code for serviceprinciple when using .net core 

### ISSUE THREAD

**Issue by sajjadkhan253** [MicrosoftDocs/powerbi-docs#3179]
Not able to use code for Node JS and .net core too in visual studio code it is throwing error once we run in localhost just we can see power bi logo refreshing and report is not coming up,

Error
![image](https://user-images.githubusercontent.com/87299550/125246236-2930a300-e30f-11eb-987b-d318f479f66b.png)

![image](https://user-images.githubusercontent.com/87299550/125246283-3c437300-e30f-11eb-8b61-337fb0ba65de.png)

![image](https://user-images.githubusercontent.com/87299550/125246344-4b2a2580-e30f-11eb-87a8-6468697f943a.png)
file is just refreshing and not working as expected.

Please suggest what to be done

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=node-js#client-id)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @sajjadkhan253,

After discussing this with the development engineers, I can confirm that you need to open a support ticket.

Thanks,

Kesem
