### ISSUE TITLE
Python Script not listed in Data Source's "Other"

### ISSUE THREAD

**Issue by chelsbells** [MicrosoftDocs/powerbi-docs#318]
The documentation lists Python Script as a data source for Power BI: https://docs.microsoft.com/en-us/power-bi/desktop-data-sources

![image](https://user-images.githubusercontent.com/19586598/46692866-2da75a80-cbbd-11e8-9f0b-e1e7f4a180ef.png)

I do not see this as a potential source in my version of Power BI (2.62/Sept 2018)

My Get Data menu options:
![image](https://user-images.githubusercontent.com/19586598/46692816-0e103200-cbbd-11e8-8145-343d011fc629.png)

My Version:
![image](https://user-images.githubusercontent.com/19586598/46692657-b96cb700-cbbc-11e8-9dda-e70beea30581.png)

**Comment by davidiseminger** [comment]
In recent versions of Power BI Desktop, it's there - directly below R script in the Other category.
