### ISSUE TITLE
Update the menu options, pictures

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#3180]
The screenshots shared here are outdated and need to be replaced with the current options/layout. Please update to reflect new workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a5535fb-d588-b877-b4cc-25212c8f603c
* Version Independent ID: c72a10a5-84ae-064d-4cb0-054825dc3e80
* Content: [Troubleshoot sharing dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-troubleshoot-sharing)
* Content Source: [powerbi-docs/collaborate-share/service-troubleshoot-sharing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-troubleshoot-sharing.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @pawarbi -- thanks for pointing that out. I'll put it on my backlog.

**Comment by maggiesMSFT** [comment]
#sign-off
