### ISSUE TITLE
Verbiage: Datasets are not "a single source of data"

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3181]
In this page it states that "Each listed dataset represents a single source of data."  I believe that phrase may be misleading since a Power BI dataset can have multiple sources of data.  One alternative may be "Each listed dataset is a source of data available for one or multiple reports, and the dataset may contain data that arrives from one or multiple sources."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f7e98b-d12a-5896-50c4-bd33f63481d0
* Version Independent ID: a1ccb451-0ba0-f4b5-63eb-22b62fcc93f6
* Content: [Basic concepts for designers in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-basic-concepts)
* Content Source: [powerbi-docs/fundamentals/service-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @chrisweis , 
Thank you for your suggestion. It's always great when a Git Issue comes with the suggested fix  :-)  We've made the update and set the article to republish. 
All the best,
The DOCS team
