### ISSUE TITLE
Add the limitation to the Embedded Solution

### ISSUE THREAD

**Issue by anniexudan** [MicrosoftDocs/powerbi-docs#3182]
[Enter feedback here]
It looks like we cannot embed the Power BI Paginated Visual Report into the Embedded solution using PBI Embedded Gen2 A SKUs. Could you confirm it and make it clear on this documentation on this limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaaf125-cd9e-4b88-c808-3bd53525d367
* Version Independent ID: df09f8c6-0e60-14dc-6095-c2be885019c7
* Content: [Create and use the paginated report visual - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/paginated-report-visual)
* Content Source: [powerbi-docs/visuals/paginated-report-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/paginated-report-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @anniexudan -- thanks for asking! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @anniexudan -- quick turnaround! The reply I got:
"It should work in the same scenarios as a stand-alone paginated report would work"
And the hypothesis: 
"They are probably trying to use it with a Power BI dataset, which isn’t yet supported in this scenario."
If that's not your scenario, you may need to create a support request, https://powerbi.microsoft.com/en-us/support/ 
Hope that helps!
