### ISSUE TITLE
Native Query Support for Snowflake

### ISSUE THREAD

**Issue by bezhan-msft** [MicrosoftDocs/powerbi-docs#3183]
[Enter feedback here]

The documentation should be updated to specify Native Query Support for Snowflake - as per Power Query docs - https://docs.microsoft.com/en-us/power-query/connectors/snowflake. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We're in the process of updating and shifting our connector content to reside in the Power Query docs exclusively, and this update / convergence will occur when that is complete. Thanks again.
