### ISSUE TITLE
Live Connection reports download is supported now

### ISSUE THREAD

**Issue by martaquintao** [MicrosoftDocs/powerbi-docs#3184]
Under considerations and troubleshooting, the following statement is no longer true. This has been confirmed by the respective dev's:
**
![image](https://user-images.githubusercontent.com/5985751/125778272-2a2ee80f-45f1-402f-b9ea-cf4fe3eff062.png)
**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @martaquintao -- thanks for pointing that out! That bullet point has been deleted.
