### ISSUE TITLE
Time-based updates needed to this page

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3185]
It looks like this page needs some minor attention since it contains roadmap content such as "The enhanced compute engine is being released in stages to regions around the world. We anticipate all regions will supported by the end of 2020."

Thanks,
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment! We've updated that passage and removed those date-based references.
