### ISSUE TITLE
Clarification about Preview feature exportToFile API in Power BI

### ISSUE THREAD

**Issue by DevRahul05** [MicrosoftDocs/powerbi-docs#3187]
Currently, there is a limitation on exportToFile API in Power BI: For public preview, the number of Power BI exports per hour is limited to 50 per capacity as mentioned here (https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to).

Would there be a new limit when this feature becomes General Availability feature. If yes, what would be the new limit?

Thanks!

**Comment by paulinbar** [comment]
Hi @DevRahul05, thanks for reaching out to us with your question. I have forwarded it on to the doc author for further consideration.
Thanks!

**Comment by KesemSharabi** [comment]
Hi @DevRahul05,

When the exportToFile API becomes GA, the limitations will change. It's most likely that the customer experience will be enhanced, but we don't yet know how. So at this point I can't commit as to whether the limitation will be removed or adjusted.

Hope this helps,

Kesem
