### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by jcaristina** [MicrosoftDocs/powerbi-docs#3188]
Hello everyone, I work for a Microsoft Partner in Argentina as an IT consultant and I am also a translator. 
We found this article (https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-overview) extremely useful and wanted to ask if you would allow us provide you with a translation into Spanish. We are already translating this content for different presentations and thought of contributing to the Microsoft community by sharing our work. If you agree on this, would you please advice us on how to proceed? Thank you!

Kind regards,
José Caristina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5495a85a-be45-63a4-2dd8-6859f55e4737
* Version Independent ID: 28ac0047-394b-670b-350a-8d8171b02b34
* Content: [Power BI adoption roadmap - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-overview?source=docs#feedback)
* Content Source: [powerbi-docs/guidance/powerbi-adoption-roadmap-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/powerbi-adoption-roadmap-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi**
* GitHub Login: @peter-myers
* Microsoft Alias: **maroche**

**Comment by peter-myers** [comment]
Hi @jcaristina - thanks for your feedback and willingness to translate to Spanish. The article is already in queue for translation to a number of languages, including Spanish. It's just a matter of time. You can monitor the article in Spanish using this link: https://docs.microsoft.com/es-es/power-bi/guidance/powerbi-adoption-roadmap-overview. Regards, Peter.
#please-close

**Comment by jcaristina** [comment]
Thank you, @peter-myers !
Regards,
JC
