### ISSUE TITLE
The guide was written in so poor way: report editor, report builder, report creator, are they all same or author simply did not mind what he/she was talking about. 

### ISSUE THREAD

**Issue by jmo6868** [MicrosoftDocs/powerbi-docs#3189]
> 

[Enter feedback here]
It is so painful to read through a such messy introduction!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ba6184-412b-7e75-ef74-46ae14d62dd6
* Version Independent ID: bf97c0bc-6511-e0f0-8df3-9e4f83492fe9
* Content: [Comparing Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop)
* Content Source: [powerbi-docs/fundamentals/service-service-vs-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-service-vs-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @jmo6868 , 
Thank you for your suggestion.  We've made some updates and set the article to republish. 
All the best,
The DOCS team
