### ISSUE TITLE
ShowLeadGenDialog.reg

### ISSUE THREAD

**Issue by sunk818** [MicrosoftDocs/powerbi-docs#319]
For me, it was not in HKLM, it was in HKCU:

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Microsoft Power BI Desktop]
"ShowLeadGenDialog"=dword:00000000
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a847d24-1a24-18c1-aa6e-2c977fa5e7cf
* Version Independent ID: 8089b020-600d-cbf9-fac9-f8a9328a6c00
* Content: [How admins can manage the Power BI Desktop sign-in form - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-admin-sign-in-form)
* Content Source: [powerbi-docs/desktop-admin-sign-in-form.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-admin-sign-in-form.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Yikes - you're right! In addition, it's _Microsoft_ Power BI Desktop (the Microsoft was missing in the key info). Sorry 'bout that, and thanks for pointing it out! Fixed in the article which will show up in the next couple of days. Thanks @sunk818 for pointing that out!
