### ISSUE TITLE
"dataset vs data source A dataset is a collection of data used to create visualizations and reports." This is another example of junk statement from PBI training material. 

### ISSUE THREAD

**Issue by jmo6868** [MicrosoftDocs/powerbi-docs#3190]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [The Power BI service - basic concepts for business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @jmo6868 ,
I'm not sure what you are asking.  Can you give me an example of how you would write this sentence?  Thanks!

**Comment by mihart** [comment]
Hi @jmo6868 ,
I see that this Git issue is a bit old, so I'm going to close it.  Thank you for your documentation input.
All the best,
the DOCS team
