### ISSUE TITLE
Deleting a PowerBI Classic Workspace doesn't seem to delete the Microsoft 365 Group

### ISSUE THREAD

**Issue by pelowski** [MicrosoftDocs/powerbi-docs#3192]
We have **a lot** of classic workspaces in our PowerBI instance that I would rather not see.  This article indicates the following "When you delete a classic workspace, you delete that Microsoft 365 group. The group is also deleted from other Microsoft 365 products like SharePoint and Microsoft Teams."  I have tried this for some really old workspaces for which I was the owner and unless there is a significant time delay between SharePoint and PowerBI, it does not appear that removing the workspace from PowerBI removes the SharePoint team site.  Ideally we'd like to hide/remove many of these workspaces from the view (as they're irrelevant to PowerBI) but have been hesitant to do so because they may or may not be used in other areas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, dataset, or workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-delete#delete-a-classic-workspace)
* Content Source: [powerbi-docs/create-reports/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-delete.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @pelowski -- I'm checking and will get back to you. Thanks for asking!

**Comment by maggiesMSFT** [comment]
Hi, @pelowski -- I've confirmed with the product team that the docs are correct as written. You may need to open a support case:
https://powerbi.microsoft.com/en-us/support/

**Comment by pelowski** [comment]
I can also confirm on my side that this _appears to be working as designed_.  Removing the classic workspace removes the Azure Group but I got confused because on our side [we apparently have some compliance policy set](https://www.screencast.com/t/GJQwTsSWy1OR) which leaves orphaned related records like a SharePoint team site and a Yammer group.  Ultimately what we want to be able to do is hide the 90% of groups that have no current need/relevance to PowerBI but there appears to be no feature to do that so I was testing if removing the Classic workspace (for old Groups that we don't really need anymore anyway) would just remove it from PowerBI or indeed delete the entire group.  I now agree that your documentation is correct and the latter is true.
