### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by HJToland3** [MicrosoftDocs/powerbi-docs#3196]
Manage  relationships does not appear on the Home tab. Also, on the Model tab, Manage relationships is not active, so I can't select it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-create-and-manage-relationships)
* Content Source: [powerbi-docs/transform-model/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback. We've updated the article to reflect where Manage relationships can be found. Also, you must have a model loaded for the Manage relationships to be active.
