### ISSUE TITLE
Text appears off, should be appropriate instead of appreciate

### ISSUE THREAD

**Issue by alliedcvil** [MicrosoftDocs/powerbi-docs#3197]
The text appears off here, should it be appropriate?

"In registry settings
You can also change these settings by setting the **appreciate** DWORD registry values. Admins can also use this method to control the setting for their whole organization."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b39a01-988d-1237-daf4-92793fb39214
* Version Independent ID: e781c340-b938-6d53-14ec-aa3269ecaa38
* Content: [Evaluation configuration settings for Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-evaluation-configuration)
* Content Source: [powerbi-docs/create-reports/desktop-evaluation-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-evaluation-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alliedcvil -- ha ha, good eye! Can I blame autocorrect 😁? Fixing it now, update will be live tomorrow afternoon Pacific time. Thanks!
