### ISSUE TITLE
The Power BI Desktop section containing the Evaluation limits doesn't appear to be available for the MSFT Store or 64-bit version of the clients and should be noted

### ISSUE THREAD

**Issue by alliedcvil** [MicrosoftDocs/powerbi-docs#3198]
This section doesn't appear to be publicly available yet to either the Microsoft Store version of the product nor the 64-bit version of the standard installed product.

In Power BI Desktop
You can change these setting in the user interface in Power BI Desktop. On the File menu > Options and settings > Options, select Data Load under Global, then change the following settings under Loading tables simultaneously:

Maximum number of simultaneous evaluations
Maximum memory used per simultaneous evaluation (MB)
Changing data loading parallelization settings in Power BI Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b39a01-988d-1237-daf4-92793fb39214
* Version Independent ID: e781c340-b938-6d53-14ec-aa3269ecaa38
* Content: [Evaluation configuration settings for Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-evaluation-configuration)
* Content Source: [powerbi-docs/create-reports/desktop-evaluation-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-evaluation-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @alliedcvil -- I'm checking. I can see it, but maybe I'm on an internal version. I'll let you know.

**Comment by maggiesMSFT** [comment]
Hi, @alliedcvil -- good catch! It's not in the external build yet, but will be coming in the August release. Sorry for the confusion!
