### ISSUE TITLE
Change log out of date

### ISSUE THREAD

**Issue by alliedcvil** [MicrosoftDocs/powerbi-docs#3199]
Since the July release is now available (July 21st 2021) figured it would be time to update this in case people have questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3105a7f-cb47-9cd9-7144-d5dca900f3f1
* Version Independent ID: 80da6829-c211-d086-df6c-92376e1d640f
* Content: [Change log for Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-change-log)
* Content Source: [powerbi-docs/fundamentals/desktop-change-log.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-change-log.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @willthom
* Microsoft Alias: **v-okkyry**

**Comment by paulinbar** [comment]
Hi @alliedcvil, thanks for calling this out. I am forwarding your observation along to the maintainers of that page. Thanks!

@davidiseminger, 
@maggiesMSFT 
@oksanakyrychenko

**Comment by davidiseminger** [comment]
Updated!
