### ISSUE TITLE
Wrong content?

### ISSUE THREAD

**Issue by ahmadanuar** [MicrosoftDocs/powerbi-docs#320]
This is not "Create and share apps" content. Seems to me this is a "Install and use apps". When I go to https://docs.microsoft.com/en-us/power-bi/service-install-use-apps , it displays same content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Install and use apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* GitHub Login: @MaggieS
* Microsoft Alias: **maggieMSFT**

**Comment by maggiesMSFT** [comment]
Oooooh, good catch, @ahmadanuar! I'm on the hunt for the content that should be in the article. Thanks for pointing that out!

**Comment by mihart** [comment]
@ahmadanuar @maggiesMSFT  Found it!  It should be back to where it belongs within the next 2 days.

**Comment by maggiesMSFT** [comment]
Thanks, @mihart!

**Comment by maggiesMSFT** [comment]
Hi, @ahmadanuar -- the right content is back in place. Whew!
