### ISSUE TITLE
Please make the sample data available easily

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#3200]
Hi the sample Excel files are in Power View format and to access the data, you have to install SIlverlight, edit registry keys to access the data. Can you please make the underlying data available easily? Perhaps as csv or Excel directly? Thanks.

https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets#download-sample-excel-files

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets#download-sample-excel-files)
* Content Source: [powerbi-docs/create-reports/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @pawarbi -- thanks for commenting on the doc! I note also your suggestion, https://ideas.powerbi.com/ideas/idea/?ideaid=0089a37c-49ee-eb11-ba5e-281878bdb01d. I've reached out to members of the product team and will let you know what I hear back.

**Comment by pawarbi** [comment]
Thanks Maggie

**Comment by maggiesMSFT** [comment]
Hi, @pawarbi -- I finally fixed the Excel samples! I deleted the Power View sheets and added an explanation of how to view the data in Power Pivot. I saved the updated versions to GitHub, 
https://github.com/microsoft/powerbi-desktop-samples/tree/main/powerbi-service-samples

**Comment by pawarbi** [comment]
Awesome, thanks Maggie. Have a great holiday weekend
