### ISSUE TITLE
Add a column for scenario 3 free user with Member licence 

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3201]
Hi - can we please add an additional column for a free user in a workspace with a 'Member' licence?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with free licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @nathanwlee1. This item is definitely on our ToDo list, but may take some time to implement.  I'll update this GitIssue when I update the document.
