### ISSUE TITLE
R / Python Publish to Web availability?

### ISSUE THREAD

**Issue by BoscoMoroni** [MicrosoftDocs/powerbi-docs#3204]
[Are there any plans to enable R or Python script visuals to appear in 'Publish to Web'? My content is built based on Python visuals but could amend for R]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @BoscoMoroni -- I'm checking with the product team and will get back to you. Thx!

**Comment by maggiesMSFT** [comment]
Hi, @BoscoMoroni -- got a quick reply, though not necessarily what you wanted to hear:
"There is no such work planned for Publish to web as of now." 
Thanks for asking.
