### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by drgray77** [MicrosoftDocs/powerbi-docs#3205]
It was reported that this code does not work, but Microsoft apparently is not interested in providing updated correct information. Thanks quys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @drgray77. 

You're right about this article, it's old and will shortly be removed.

If you need help with access tokens, you can look at these articles:
- [Considerations when generating an embed token](https://docs.microsoft.com/power-bi/developer/embedded/generate-embed-token)
- [Refresh the access token](https://docs.microsoft.com/javascript/api/overview/powerbi/refresh-token)

You can also try the [Power BI Community]( https://community.powerbi.com) and our [support page](https://support.powerbi.com).

Thanks,

Kesem
