### ISSUE TITLE
Good info - BI

### ISSUE THREAD

**Issue by chintala999** [MicrosoftDocs/powerbi-docs#3207]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [The Power BI service - basic concepts for business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts?source=docs)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @chintala999 -- thanks for letting us know! It's always a pleasure to hear from customers.
