### ISSUE TITLE
Limitations & Considerations: Workspace Name - Special Characters

### ISSUE THREAD

**Issue by NathanMTMSFT** [MicrosoftDocs/powerbi-docs#3209]
**Workspace Name**
Certain Special Characters when creating a “Workspace Name” are not supported when using XMLA endpoint.
As a workaround users will have to use URL encoding of special characters (eg, “/” = “%2F”)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [The new workspace experience in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @NathanMTMSFT -- thanks for your comment! 
I'm going to add this bullet point to the https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces#limitations-and-considerations section:
- Certain special characters aren't supported in workspace names when using an XMLA endpoint. As a workaround, use URL encoding of special characters, for example, for a forward slash **/**, use **%2F**.

Does that cover it? BTW, I looked for you in the GAL so I could contact you offline, but was unsuccessful 🤔.

**Comment by NathanMTMSFT** [comment]
Hi Maggie,

Yes that’s it!
Thanks so much for adding this!

I don’t have access to GAL but I’m on teams if you’d like to connect 😊

Kind regards,

Nathan Martinez
Support Engineer
Power BI Accelerated Customer Experience
***@***.******@***.***>
***@***.***<https://us-prod.asyncgw.teams.microsoft.com/v1/objects/0-eus-d4-33f93ca2dad4626adc1ccca77696ab37/views/imgo>

**Comment by maggiesMSFT** [comment]
Got it! Change will be live this afternoon. 
I recommend updating your GitHub profile with a little more info, so we can find you in the future 😁. There are a lot of Nathan Ms at MSFT!
