### ISSUE TITLE
What does the "Microsoft may display" warning actually mean?

### ISSUE THREAD

**Issue by CaryCarr3Form** [MicrosoftDocs/powerbi-docs#3210]
In step 4 of "Create embed codes with Publish to web", there is the warning that "Microsoft may display the report on a public website or public gallery". Does this mean that Microsoft is claiming ownership of any reports that we choose to publish, and will use them without informing us? I can understand the warning of "if you put this on a website, anyone who uses the website can see it", but tying that into "Microsoft can use this report however we want" seems like a step too far.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @CaryCarr3Form -- I'm checking and will get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @CaryCarr3Form -- here's the answer:

"We continue to reserve this right to put it in a gallery, though we've never actually created a gallery. This is indeed a requirement for using our free Publish to web capability. The customer can use the Power BI embedded offering to build a public report without that requirement, but this would be significant work and cost to them to build and maintain."

Hope that answers your question!
