### ISSUE TITLE
No longer preview

### ISSUE THREAD

**Issue by MixolydianV** [MicrosoftDocs/powerbi-docs#3211]
According to the [July 2021 Feature Summary ](https://powerbi.microsoft.com/en-us/blog/power-bi-july-2021-feature-summary/) this is now GA, so the (Preview) should probably be removed. Not sure if it needs updating elsewhere too with the new features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d929e6-7e81-16da-91aa-91f5275b0eab
* Version Independent ID: 2b6d7df1-1de2-1c2d-c71c-3715aeee71c5
* Content: [Create small multiples in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-small-multiples)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-small-multiples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-small-multiples.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Good catch, @MixolydianV -- will update.

**Comment by maggiesMSFT** [comment]
Hi, @MixolydianV -- had to get the details for the Considerations section. Changes will be live this afternoon. Thx!
