### ISSUE TITLE
Video Unavailable

### ISSUE THREAD

**Issue by sayan-mohd** [MicrosoftDocs/powerbi-docs#3212]
The YouTube video (https://www.youtube.com/embed/JbL2-HJ8clE) embedded in this page is not available. Please provide the updated URL if available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-set-data-alerts)
* Content Source: [powerbi-docs/create-reports/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @sayan-mohd -- happy news! We were able to get all the videos back online again.
