### ISSUE TITLE
Please add reference to programmatic access

### ISSUE THREAD

**Issue by LevGelman** [MicrosoftDocs/powerbi-docs#3213]
Hello,

I can't found how to add or remove a gateway data source using API or Power Shell

Can you please add reference on this page?

Thanks!

Lev Gelman

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Add or remove a gateway data source - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Hi @LevGelman,

We will consider your request during future updates. In the meantime, you might find information that can help you in the [Power BI REST APIs](https://learn.microsoft.com/rest/api/power-bi/) reference pages or the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

Thanks,

Kesem
