### ISSUE TITLE
Documentation Comment - "Access Power BI privately from the VM"

### ISSUE THREAD

**Issue by monacogp** [MicrosoftDocs/powerbi-docs#3214]
In `[this section](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links#access-power-bi-privately-from-the-vm)`, it may be useful to edit the tenant guid with <your tenant id> with a link to instructions about where to find it. 
Access Power BI privately from the VM. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for the suggestion. It's in another part of the article, but I also added a link for how to do so in the Next Steps section.
