### ISSUE TITLE
Lots of videos are currently unavailable (set to private on Youtube)

### ISSUE THREAD

**Issue by immobo** [MicrosoftDocs/powerbi-docs#3215]
Dear Power BI team,

I just noticed that most of the videos embedded and linked on this documentation page are not available anymore, because they were set to private on Youtube. 

It seems like 114 out of 157 videos of the following playlist, which is also linked on the documentation page, are currently unavailable/private: https://www.youtube.com/playlist?list=PL1N57mwBHtN0JFoKSR0n-tBkUJHeMP2cP

Is there any chance that they will be live again, soon? If not, the documentation needs to be fixed, as there are quite a few references to these videos.

I'm looking forward to your feedback, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43c2d0b7-fdeb-9e1e-1b60-04854fcb89da
* Version Independent ID: e53a3969-30e8-033d-f76c-71b05dbd0361
* Content: [Power BI videos - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/videos)
* Content Source: [powerbi-docs/fundamentals/videos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/videos.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by keraco** [comment]
Hi @immobo 
Thank you for letting us know. We're working on resolving the issue as we speak. 
 Will update you in an hour. 
All the best, 
Kelly Kaye, 
Microsoft Power BI Community Program Manager

**Comment by keraco** [comment]
Hi @immobo 
Please try again, you should start to see a few pop back up again. Let us know your experience and what you are seeing. 
Best, Kelly

**Comment by maggiesMSFT** [comment]
Hi, @immobo -- thanks for the heads-up! That helped us debug the issue. And thank goodness it's fixed!

**Comment by immobo** [comment]
Hi @keraco and @maggiesMSFT 
All videos are back again :) Thanks a lot for your quick support!
