### ISSUE TITLE
Azure Cost Management - PowerBI update

### ISSUE THREAD

**Issue by wjpigott** [MicrosoftDocs/powerbi-docs#3216]
[Enter feedback here]
This page needs to be updated to show Azure Cost Management setup vs. what is shown in preview. 
https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights/

Developer documentation and quickstarts
Learn how to use Azure Cost Management and Billing APIs to add cloud cost data to your applications, and learn how to use the Power BI connectors to create custom dashboards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback. As noted (now) in the article, for new functionality use the Azure Cost Management connector for Power BI.
