### ISSUE TITLE
Databricks

### ISSUE THREAD

**Issue by shawnnesser** [MicrosoftDocs/powerbi-docs#3217]
[Need Azure Databricks in list.  Thx]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37efb1d4-b4bb-f035-c63b-1f8b17d4f448
* Version Independent ID: fe9f8822-a20a-e17c-195c-1dc261ab480f
* Content: [Power BI report data sources in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/data-sources)
* Content Source: [powerbi-docs/report-server/data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @shawnnesser -- thanks for the suggestion! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @shawnnesser -- Thanks again! Closing per the PM.
