### ISSUE TITLE
Refresh a dataset stored on OneDrive or SharePoint Online - update language

### ISSUE THREAD

**Issue by ChrisSmallArbelaTech** [MicrosoftDocs/powerbi-docs#3218]
['Any reports you’ve created in the file are loaded into Reports in the Power BI service.' is confusing since you can't have multiple reports in a Power BI desktop file.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset from OneDrive or SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-desktop-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry for the confusion. I've adjusted that sentence to make it clearer.
