### ISSUE TITLE
 "featured" dashboard

### ISSUE THREAD

**Issue by AzizQuazi** [MicrosoftDocs/powerbi-docs#322]
Hi, I have not found any documentation on the "featured" dashboard - How to create etc. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [What is a dashboard for Power BI service consumers? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboards)
* Content Source: [powerbi-docs/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboards.md)
* Service: **powerbi**
* GitHub Login: @maggiemsft
* Microsoft Alias: **maggie**

**Comment by markingmyname** [comment]
@AzizQuazi Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mihart** [comment]
Hi @AzizQuazi 
Try this link: [featured](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-featured)
Take care,
Michele
