### ISSUE TITLE
Costing of Software assurance in SQL Server Enterprise edition

### ISSUE THREAD

**Issue by HITesh-20** [MicrosoftDocs/powerbi-docs#3220]
what is the costing of software assurance in SQL Server Enterprise Edition ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc8bae8-be5d-ce63-6196-4c2e2f2d6779
* Version Independent ID: 2e836aec-a8a7-41fe-f562-c6c435e441ee
* Content: [What is Power BI Report Server? - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/get-started)
* Content Source: [powerbi-docs/report-server/get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @HITesh-20 -- this looks like a good place to start: https://www.microsoft.com/en-us/sql-server/sql-server-2019-pricing.

**Comment by HITesh-20** [comment]
> Hi, @HITesh-20 -- this looks like a good place to start: https://www.microsoft.com/en-us/sql-server/sql-server-2019-pricing.

I have seen this doc. Is there any other doc for this ?

**Comment by maggiesMSFT** [comment]
@HITesh-20 -- when you're on that page,  https://www.microsoft.com/en-us/sql-server/sql-server-2019-pricing, the option to start a live chat pops up. I'd start with the live chat.
Hope that helps!
