### ISSUE TITLE
prerequisites of power BI Report Server

### ISSUE THREAD

**Issue by HITesh-20** [MicrosoftDocs/powerbi-docs#3221]
What are the prerequisites cores/ram to build a powerbi report server for 50 to 100 users?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc8bae8-be5d-ce63-6196-4c2e2f2d6779
* Version Independent ID: 2e836aec-a8a7-41fe-f562-c6c435e441ee
* Content: [What is Power BI Report Server? - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/get-started)
* Content Source: [powerbi-docs/report-server/get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @HITesh-20 -- I'm investigating. I'll be out of office for a few weeks, so I have asked others to respond to your question.
I recommend asking in the community, too: https://community.powerbi.com/

**Comment by paulinbar** [comment]
Hi @HITesh-20, did you ever get an answer to you question? I am closing this issue here for now, but feel free to reopen it if you are still having trouble. Thanks!
