### ISSUE TITLE
Power BI Report Server

### ISSUE THREAD

**Issue by HITesh-20** [MicrosoftDocs/powerbi-docs#3222]
Do we require SQL Server with Power BI report server? can we existing SQL Server license/developer edition with Power BI Report server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc8bae8-be5d-ce63-6196-4c2e2f2d6779
* Version Independent ID: 2e836aec-a8a7-41fe-f562-c6c435e441ee
* Content: [What is Power BI Report Server? - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/get-started)
* Content Source: [powerbi-docs/report-server/get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @HITesh-20 -- I'm investigating. I'll be out of office for a few weeks, so I have asked others to respond to your question.

**Comment by paulinbar** [comment]
HI @HITesh-20, did you ever find the answer to your question? In the meantime I am closing this issue here, but feel free to reopen if you are still having trouble. Thanks!
