### ISSUE TITLE
What is considered User ?

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3226]
Would be great if you explained in simple terms what you consider User? Is it organization? Or is it individual user within organization with his/her separate account? I think there is a lot of confusion between terms like user, tenant, account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b9b37b6-a575-eef3-ba8b-d9f3957f5772
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @gvggvg,

You're right, these terms are confusing. Perhaps this will help:

- **User** - the *end user* that uses Power BI. For example, the user can view or create Power BI reports.
- **Tenant** - a company or an organization.
- **Account** - a subscription for using Power BI. There are different types of Power BI accounts, such as *free*, *Premium* and *Premium Per User (PPU)*.

An organization (or *tenant*) can have multiple *accounts*, and each account can have one or many *users*. 

I hope that helps to simplify things. In the future we might consider adding this to our documentation.

Thanks,

Kesem
