### ISSUE TITLE
Support for reading PowerBI Dataflow content with ADF

### ISSUE THREAD

**Issue by JJDE** [MicrosoftDocs/powerbi-docs#3229]
[Enter feedback here]
Was so exited about the export dataflow to ADLS feature but the major use case, reading that ADLS content with ADF/Synapse is not implemented...this is really nonsense... the annnounced mainfest support in april2021 update seems only to be for reading CDM into PBI but not what we need (again)?! Is there any roadmap for reading CDM generated by PBI with any other Azure Tool like ADF? https://medium.com/riccardo-perico/is-that-a-bug-or-a-feature-adf-on-power-bi-dataflows-cdm-folder-3bc9380a6794

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
