### ISSUE TITLE
Documented permissions doesn't add up with MS Graph permissions

### ISSUE THREAD

**Issue by dennis-skymill** [MicrosoftDocs/powerbi-docs#323]
The permission listed when trying to modify permissions in Graph Explorer doesn't add up with the ones documented here.

What are the minimal required permissions necessary to connect Power BI to MS Graph API?

**Comment by markingmyname** [comment]
@dennis-skymill Hello, thank you for your comment. I can't tell by the title and the lack of supporting detail what exactly the documentation issue is. Can you please explain in more detail? 

Thank you.

**Comment by markingmyname** [comment]
@dennis-skymill Since I have not heard a response, we will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
