### ISSUE TITLE
Direct Query with Azure Analysis Services is in Preview

### ISSUE THREAD

**Issue by obungimartin** [MicrosoftDocs/powerbi-docs#3230]
I think it is confusing for readers that this page says that Direct Query is not possible with Azure Analysis Services. Isn't this feature in Preview since December 2020? Maybe that should be mentioned on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models#limitations-and-considerations)
* Content Source: [powerbi-docs/transform-model/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. I don't see in the (current) article where it states this limitation. If you can specify the passage, I'll be happy to confirm and update.
