### ISSUE TITLE
Issue with number of content creators image. 

### ISSUE THREAD

**Issue by stevenemyers** [MicrosoftDocs/powerbi-docs#3232]
[Enter feedback here]
Hi The graphic in section for number of content creators is off does not match the Scope order in text.  Departmental and team should be switched.  I only noticed as I was referencing this information for my companies Adoption and Governance doc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18991be8-e63d-0eba-b573-320bd1d4ea1e
* Version Independent ID: 25b88ee7-4976-87bb-83ed-afde7daff5ee
* Content: [Power BI adoption roadmap: Content delivery scope - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-content-delivery-scope)
* Content Source: [powerbi-docs/guidance/powerbi-adoption-roadmap-content-delivery-scope.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/powerbi-adoption-roadmap-content-delivery-scope.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **maroche**

**Comment by kfollis** [comment]
Hi @stevenemyers - that's a great catch! Thanks for bringing it to our attention. I noticed that the consumers graphic was also out of order, so I updated both images and they're on the way to publishing. Appreciate the contribution!
