### ISSUE TITLE
Fixing the time/date for Power BI Tutorial

### ISSUE THREAD

**Issue by troydavidcook** [MicrosoftDocs/powerbi-docs#3233]
I had to go to Options and settings and turn off Auto date under Data load for this particular file and that fixed the issue for Microsoft Power BI. The tip in the tutorial didn't work - Simply checking off "Date Hierarchy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0f7e4-74cd-dadb-c2ce-4b6c0c511e20
* Version Independent ID: 0d14b983-c47a-1fa7-7103-15182735f26b
* Content: [Tutorial: Combine data from Excel and an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for that info @troydavidcook -- I've added that to the Tip, should be updated in the next day or so. Thanks!
