### ISSUE TITLE
Power BI REST API - error: PowerBINotAuthorizedException

### ISSUE THREAD

**Issue by Koldmunch** [MicrosoftDocs/powerbi-docs#3234]
Dear Microsoft.

I'm unable to extract activities from Power BI REST API. I get the following error: 

{
    "error": {
        "code": "PowerBINotAuthorizedException",
        "pbi.error": {
            "code": "PowerBINotAuthorizedException",
            "parameters": {},
            "details": [],
            "exceptionCulprit": 1
        }
    }
}

I have followed this guide: https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication
1. created an Azure AD App
2. created AAD group
3. assigned new app / enterprise app to new group
4. allowed service principals to use read-only Power BI admin APIs in Admin portal by adding group from #2 in Power BI admin portal

Note: I'm trying to extract the activity data from Premium capacity. 

I hope you can help me understand what I'm missing. 

Br,
Christoffer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76dd7616-4a1c-fe01-1b6b-6190bd2fdb63
* Version Independent ID: 93839448-4a4b-5489-14d4-6eebe4b3d34a
* Content: [Enable service principal authentication for read-only admin APIs - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/admin/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Perhaps this article is relevant too: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-admin-consent-workflow

**Comment by Koldmunch** [comment]
I'll ask our IT Admin to remove the Power BI role set in the portal. I hope it will solve the problem. Thanks!

**Comment by paulinbar** [comment]
Hi again, @Koldmunch, ok, great. If that doesn't work let us know and we'l seek more help. I am going to close this issue right now, but please reopen if removing the role doesn't help. Thanks!

**Comment by pedrojunqueira** [comment]
Hi @paulinbar it worked for me. Took a while but the NO PBI admin consent required was hard to get as it was "counter intuitive" for me :). 

Here how the permissions for the Enterprise App needs to look like

![03-PermissionsNoConsent](https://user-images.githubusercontent.com/30810764/190600011-364d164f-96b7-4d7b-8f71-93427a8afa49.png)

Then this app needs to be in a security group


![02-GroupMember](https://user-images.githubusercontent.com/30810764/190600180-d5be3511-802e-468d-8336-43ccfca6ae5d.png)

Which Security group needs to be added to the PBI Adm Portal in Read-Only Adm API

![04-PBI-Enabled](https://user-images.githubusercontent.com/30810764/190600279-a124bc81-4d93-41e3-bcf6-74875aa32816.png)
