### ISSUE TITLE
Usage Metrics - Daily Performance

### ISSUE THREAD

**Issue by mittaltripti** [MicrosoftDocs/powerbi-docs#3236]
In the documents here : https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics

It is mentioned 

Daily performance      The performance for 10%, 50%, and 90% of the open report actions calculated for each individual day.

seven-day performance            The performance for 10%, 50%, and 90% of the open report actions calculated across the past seven days for each date.

 
Though my usage report is displaying 25%, 50% and 75% of report actions. Is the documentation old or not up-to-date ?

![jalantripti_0-1629154483195](https://user-images.githubusercontent.com/10500673/129667345-ceec0005-9edb-4ee9-81de-8aff6ef36c60.png)

**Comment by maggiesMSFT** [comment]
Hi, @mittaltripti -- Good point! Yes, the docs are out of date. Updating now, change will be live Mon afternoon Jan 10, Pacific time.
