### ISSUE TITLE
There  is no place where I can see my dashboards listed? I have to wait until I stumble across an icon?? LOL. Just make a place called Dashboard where  it's easy to find and put dashboards in there. JC!

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/powerbi-docs#3239]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8fcff1-6d5d-2619-8c96-13a00802bb36
* Version Independent ID: cb25f645-8245-7dd7-7020-2b12aaa98098
* Content: [View a Power BI dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-dashboard-open)
* Content Source: [powerbi-docs/consumer/end-user-dashboard-open.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-dashboard-open.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @peteravila . This looks like a support request or product question rather than documentation feedback. You might want to suggest this as an idea at https://ideas.powerbi.com.
