### ISSUE TITLE
clientId and groupId no longer exist in the demo code.

### ISSUE THREAD

**Issue by jackdh** [MicrosoftDocs/powerbi-docs#324]
clientId and groupId no longer exist in the demo code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed Power BI content into an application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@jackdh Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@jackdh Thank you for catching this change.  The change has been made to both the customer and organization articles. Changes should go live in a few days.

And @jackdh  did you know: For minor things like typos, you yourself can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
