### ISSUE TITLE
Dashboards are stored in Workspaces. Click on you workspace on the left side of the screen and you will see a section called Dashboard.  How difficult is it to say that in an article that explains how to find your dashboard?

### ISSUE THREAD

**Issue by peteravila** [MicrosoftDocs/powerbi-docs#3240]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df8fcff1-6d5d-2619-8c96-13a00802bb36
* Version Independent ID: cb25f645-8245-7dd7-7020-2b12aaa98098
* Content: [View a Power BI dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-dashboard-open)
* Content Source: [powerbi-docs/consumer/end-user-dashboard-open.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-dashboard-open.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @peteravila ,
You make a valid point.  I've update the doc and set it to republish.  Thank you for your feedback.

**Comment by peteravila** [comment]
Yeah, I may have made a valid point, but I didn't have to be rude to you about it. I sincerely apologize. Obviously, I was frustrated when I wrote that, but as someone who writes courseware and overlooks things all the time like you did, I could have been kinder. 

Thanks for letting me know that you understood my point. I'm sorry I was rude.
