### ISSUE TITLE
None of what is on this page matches what's in my PowerBI.

### ISSUE THREAD

**Issue by DistinctiveJay** [MicrosoftDocs/powerbi-docs#3241]
[I don't know if the app has been updated and the help page hasn't been, or perhaps my app has not updated, but nothing on this page matches what I see in my app.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#limitations-and-considerations)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by DistinctiveJay** [comment]
Ok, it seems my PBI never automatically updated along with all the other Office products. I have installed a new copy and now it matches. Is updating an issue with PBI, that we have to download it manually every time?

**Comment by davidiseminger** [comment]
Hello @DistinctiveJay -- yes, Power BI Desktop must be updated manually. With recent versions, if you open Desktop and it's not current, you'll be alerted that a more recent version is available.

Power BI Desktop gets updated every month, with added functionality and improvements. Keep coming back for the updates, and check out the following article, which provides pointers to each update: https://docs.microsoft.com/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop
