### ISSUE TITLE
whether the document reference is totally implied to Power BI Service

### ISSUE THREAD

**Issue by ranganathSeltech** [MicrosoftDocs/powerbi-docs#3242]
Well, though it was mentioned the document covers information about data types that could be connected from p**ower bi service,** it makes reader concern whether the document-owner mentioned **Power BI** in generic sense referring to **Power BI Service**; as a reader I got the same concern. Hence, I felt it would be more clear and easy to interpret for the reader when the relevant technical terms (such as Power BI Service) in the document are mentioned with their fully-qualified names; Please correct me if I over-looked any needed information in the document while in the process of understanding it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data#feedback)
* Content Source: [powerbi-docs/connect-data/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-get-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback. Many of the data sources in Power BI Desktop and the Power BI service are similar, but there are some data connectors that are only available in Desktop. For a full list of data connectors for Desktop, please see the following article: https://docs.microsoft.com/power-bi/connect-data/desktop-data-sources
