### ISSUE TITLE
Broken: Analyze in Excel Link

### ISSUE THREAD

**Issue by an-luong** [MicrosoftDocs/powerbi-docs#3243]
Link to download Analyze in Excel is broken.

Link URL: [(https://download.microsoft.com/download/3/8/B/38B8BD8C-E6AB-4B9F-AB1E-03C59A477C48/1033/x64_15.0.2000.802_SQL_AS_OLEDB.msi)]

![image](https://user-images.githubusercontent.com/54855017/129958495-6cba201e-7249-48fd-84e9-8b693d622de1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @an-luong -- you're talking about the link in the product, right? The link in the top bar, **Download** > **Analyze in Excel updates**, right?

![image](https://user-images.githubusercontent.com/12401230/132071087-33d3080e-93e5-4fdb-b996-b49bf9198ca1.png)

I've tried it from 2 different accounts in 2 different browsers, and it worked for both of them. Please try again! Barring that, please file a support ticket at https://powerbi.microsoft.com/en-us/support/.
Hope that helps!
