### ISSUE TITLE
Power BI Desktop Mobile View Design Page needs updating

### ISSUE THREAD

**Issue by electrifiedg** [MicrosoftDocs/powerbi-docs#3245]
[This page on Power BI mobile view needs updating]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf26f16b-9fd6-8518-7dd5-62f51105f5be
* Version Independent ID: 761585e1-c4c0-7528-3a81-9a742e4bfdfa
* Content: [Optimize a dashboard for mobile phones - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-create-dashboard-mobile-phone-view)
* Content Source: [powerbi-docs/create-reports/service-create-dashboard-mobile-phone-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-create-dashboard-mobile-phone-view.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @electrifiedg -- thanks for your feedback! Updating it today. Change should be live either this afternoon or tomorrow, 9/13 or 9/14.
cheers!
