### ISSUE TITLE
Premium capacity and users w/out a pro license

### ISSUE THREAD

**Issue by marcbeacom** [MicrosoftDocs/powerbi-docs#3247]
FYI - the following paragraph is incorrect. I think it boils down to poor naming of the Premium capacities - EM SKUs are listed as premium capacity but all users accessing the report, whether or not it's in a premium capacity (EM Sku), needs a Pro license. 

"If you've purchased Power BI Premium, you don't have to assign Pro licenses to enable user access. Users in the organization can access reports that are shared with them, as long as the reports are published to a Premium capacity."

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@marcbeacom - thank you for the feedback on this article. After consulting with the product team, I made some wording changes to help clarify. Closing this issue now.
