### ISSUE TITLE
 AI Insights features are marked as "Preview" feature when it is has been GAed for more than 1 year. 

### ISSUE THREAD

**Issue by jeeunyoo** [MicrosoftDocs/powerbi-docs#3248]
[Enter feedback here]

On this document, AI Insights features are shown as "Preview" features and it is very confusing for the customer. 
https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights

**Can you please update this doc that these features are GAed and are not "Preview" features?**

![image](https://user-images.githubusercontent.com/88862540/129983386-97e90ccc-79a4-41a2-a47c-81f696deb141.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f95078-89ba-6ba2-231b-b130755c8510
* Version Independent ID: 8f152dab-fea9-714a-f97e-f0d68109151f
* Content: [Connect to AI Insights in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights)
* Content Source: [powerbi-docs/transform-model/desktop-ai-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-ai-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for pointing that out - I've updated the TOC to reflect that.
