### ISSUE TITLE
HANA HDI Containers

### ISSUE THREAD

**Issue by entmike** [MicrosoftDocs/powerbi-docs#325]
Hi, does Power BI support Calculation Views created in HANA HDI Containers?  I can see the container, but no Calculation View.  I can see the Calculation Views in my HDI Container in other tools like Tableau though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea414a5c-c3ca-281e-46ca-3e677d27924b
* Version Independent ID: 363a9c9c-13e2-58ce-cb79-9f897d83c307
* Content: [Use SAP HANA in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana)
* Content Source: [powerbi-docs/desktop-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-hana.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Support request:
Thanks for your comment, @entmike. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by AdamBJ** [comment]
@entmike this feature is available in PBI now. Check it out: https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana#supported-features-for-sap-hana
