### ISSUE TITLE
Missing Limitation for Large Datasets in PowerBI: Unable to Change Regions

### ISSUE THREAD

**Issue by spencerstewart** [MicrosoftDocs/powerbi-docs#3251]
In the article on [Large datasets in Power BI Premium](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models#limitations-and-considerations), the section on limitations identifies some key points to be aware of, but does NOT identify the limitation that once a large dataset is created in a workspace, it must stay in that region. In other words, you cannot reassign a workspace with a large dataset to a Premium Capacity in another region.

This is also not identified in the documentation for changing regions [Multi-Geo support for Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo#change-the-region-for-existing-content).

Unfortunately this led to a limited production outage as we tried to align our Power BI Premium Capacity's regions with out Power BI home region.

![image](https://user-images.githubusercontent.com/4812410/130095310-bcdf03fe-5cc3-440a-b648-d903c65548c8.png)

Please consider updating one or both articles to identify this gotcha and keep other teams safer when making similar changes.

Huge shoutout to a very helpful error message, though - made it quick to identify the cause and rollback. Just would have been nice if this information was know ahead of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large datasets in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-large-models)
* Content Source: [powerbi-docs/admin/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @spencerstewart,

Thanks for your comment. I'm looking into the limitation you described and will update the documents accordingly.

Thanks again for getting involved,

Kesem

**Comment by KesemSharabi** [comment]
Hi @spencerstewart,

For large datasets in Power BI Premium, you need to enable the large dataset storage format option, as stated in [Large datasets in Power BI Premium](https://docs.microsoft.com/power-bi/admin/service-premium-large-models). 

![image](https://user-images.githubusercontent.com/54834915/144008390-4f82dfde-5658-460c-a3ec-3fb7ee17fd3d.png)

Hope this helps,

Kesem

**Comment by spencerstewart** [comment]
Hi Kesem,

Thanks for your reply. We had enabled the *Large dataset storage format*
for a dataset within a Power BI workspace that was hosted on a Power BI
Premium Capacity in one region. When we attempted to reassign the workspace
to a Power BI Premium Capacity in another region (effectively migrating
regions), everything within the workspace migrated successfully except for
the dataset that had *Large dataset storage format* enabled. The error
message is attached in the original message.

The limitation that I think should be better documented is that after
the *Large
dataset storage format* is enabled for a dataset, it dataset cannot be
moved to another region.

Thank you,
Spencer

**Comment by KesemSharabi** [comment]
Hi @spencerstewart,

Once again, thanks for your comment and for getting involved. I'm glad you managed to overcome this problem, and that you pointed it out so that we could improve our documentation.

I added the following note to the [Region availability](https://docs.microsoft.com/power-bi/admin/service-premium-large-models) section.

![image](https://user-images.githubusercontent.com/54834915/144254661-241cdf29-157e-4213-9a93-1ea387a63278.png)

Thanks,

Kesem
