### ISSUE TITLE
GDPR Breach? Why can customers see all other shared users?

### ISSUE THREAD

**Issue by avloon** [MicrosoftDocs/powerbi-docs#3252]
I am quite surprised about the fact that external guest users of a PowerBI report are able to see all the other users, including their e-mail adresses. Also when those users only have Read-rights. In my opinion this should be seen as a cause of GDPR-databreaches, as we also have seen with Teams meetings showing all attendees. Especially because a lot of people (like me) don't expect this to happen, so they publish e-mail addresses without knowing.

How do you all think about this?

See the example image about the page involved:
![manage-dashboard-permissions-page](https://user-images.githubusercontent.com/89184530/130150655-b43f8ae6-92d9-406b-84c6-f078d32be3c4.png)

**Comment by yardenalbeck** [comment]
Hi avloon,
Nice to e-meet you. I'm the PM of this feature and I'm trying to understand what am I missing here. This info is only available for the Dataset owners that have write permission on this dataset, users with read-only permission can't make it to this page. If for some reason this is not the case let's take this offline and check this. Thanks for your help. Best, Yarden Albeck

**Comment by avloon** [comment]
I recieved the notice of one of the external users who only has read rights. So he was able to see all other (external) users including their e-mail addresses. Therefore my concerns.

We solved it by a general tenant setting, but if you are not aware of this default setting you have the risk of exposing personal data.

In my opinion this should not be visible to people with Read rights. especially by default tenant settings.

**Comment by paulinbar** [comment]
@yardenalbeck

**Comment by paulinbar** [comment]
Hi @avloon, do you remember which tenant setting you used to solve the issue?
@yardenalbeck

**Comment by paulinbar** [comment]
Hi @avloon, I haven't heard back from you for awhile regarding the tenant setting you were referring to, so I am closing this issue for the present. If you have more details please feel free to reopen the issue. Thanks.
