### ISSUE TITLE
GCC EM3 doesn't seem to support paginated report deployment

### ISSUE THREAD

**Issue by marcbeacom** [MicrosoftDocs/powerbi-docs#3253]
No mention of it in the article, but this doesn't seem to apply to the GCC Tenants. We have an EM3 SKU but the options to deploy paginated reports isn't available to enable this functionality. Tried testing the deployment of paginated reports to a premium capacity and it failed. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @marcbeacom -- I'm checking and will get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @marcbeacom -- whew, it took some tracking down, but I have the answer. If you have a Premium Gen1 capacity, then no, an EM3 SKU won't support paginated reports. You need a P1 - P3 SKU in Gen1.
If you have Premium Gen2, then EM1 - EM3 should also work, in GCC tenants and everywhere else. If you have Premium Gen2 EM3 and paginated reports aren't working, then the engineers ask that you please open a support request so they can investigate. https://powerbi.microsoft.com/en-us/support/
Hope that helps! 
I'm updating several articles, including this one, as a result: 
- https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-workloads
- https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq#what-size-premium-capacity-do-i-need-for-paginated-reports-

So thanks!
