### ISSUE TITLE
incorrect shortcut shown for "Insert line below"

### ISSUE THREAD

**Issue by scottone** [MicrosoftDocs/powerbi-docs#3254]
I noticed that the incorrect shortcut is shown for "Insert line below".  It should be Shift instead of Ctrl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2afbab-cd91-b0d4-56c7-7c14110342dc
* Version Independent ID: b292616b-04d8-693f-5658-b08a6d875007
* Content: [Formula editor in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-formula-editor)
* Content Source: [powerbi-docs/transform-model/desktop-formula-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-formula-editor.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for that correction! I've updated the article to reflect the correct guidance.
