### ISSUE TITLE
cannot find how to open the DAX editor without the mouse

### ISSUE THREAD

**Issue by scottone** [MicrosoftDocs/powerbi-docs#3255]
I have looked at this page and many other shortcut pages, but cannot find a way to open the DAX editor without clicking on the measure name in the Fields pane.  I also have tried every keystroke I can think of.
Is there a hidden, undocumented shortcut key?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your post. There is no hidden or undocumented shortcut keys. You can use keyboard-based menu navigation to get to its menu-item or ribbon-item button.
