### ISSUE TITLE
Power BI Premium Gen 2

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3256]
This doc doesn’t seem to consider Gen2 Premium/Embedded compute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683b70c5-16bc-6d10-0433-a39a6be16995
* Version Independent ID: 9d664ac7-b484-3b5f-f215-613f95fe60ec
* Content: [Monitor report performance in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/monitor-report-performance)
* Content Source: [powerbi-docs/guidance/monitor-report-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/monitor-report-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Hi @chrisweis,

Thank you for your comment. I'll look into your suggestion for improving the [Monitor report performance in Power BI]() article, and adding Premium Gen2 and Embedded Gen2 considerations into it.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @chrisweis,

I added a reference to the [Gen2 metrics app](https://docs.microsoft.com/power-bi/admin/service-premium-install-gen2-app) in the [Monitor Premium metrics](https://docs.microsoft.com/power-bi/guidance/monitor-report-performance#monitor-premium-metrics) section.

![image](https://user-images.githubusercontent.com/54834915/144253853-254b95e5-dec7-4aa4-9786-9c123d113ced.png)

Thanks again for your suggestion,

Kesem
