### ISSUE TITLE
Deprecation warnings during the powerbi-visuals-tools installation

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#3259]
When running the `npm i -g powerbi-visuals-tools` command I get the following warnings:

> npm : npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> At line:1 char:1
> + npm i -g powerbi-visuals-tools
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (npm WARN deprec...est/issues/3142:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> C:\Users\lucaz\AppData\Roaming\npm\pbiviz -> C:\Users\lucaz\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\bin\pbiviz.js
> 
> > core-js-pure@3.16.2 postinstall C:\Users\lucaz\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\core-js-pure
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
> 
> [96mThe project needs your help! Please consider supporting of core-js:[0m
> [96m>[94m https://opencollective.com/core-js [0m
> [96m>[94m https://patreon.com/zloirock [0m
> [96m>[94m https://paypal.me/zloirock [0m
> [96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
> 
> [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
> 
> 
> > core-js@3.6.4 postinstall C:\Users\lucaz\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\core-js
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
> 
> [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
> [96m>[94m https://opencollective.com/core-js [0m
> [96m>[94m https://www.patreon.com/zloirock [0m
> 
> [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
> 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\powerbi-visuals-tools\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN base64-inline-loader@1.1.1 requires a peer of webpack@^4.x but none is installed. You must install peer dependencies yourself.
> npm WARN less-loader@5.0.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN friendly-errors-webpack-plugin@1.7.0 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
> + powerbi-visuals-tools@3.3.2
> added 868 packages from 472 contributors in 95.953s
> npm WARN file-loader@1.1.11 requires a peer of webpack@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.

The installation seems to be successful, so I guess maybe you need to update the `powerbi-visuals-tools` code to avoid these warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @lucazav,

Thanks for your comments, as far as I'm aware nothing has changed but I'll look into it.

@uve - are you familiar with the issues described above?

Thanks,

Kesem

**Comment by uve** [comment]
thanks for the report. We're going to update all dependencies and release a new version of **powerbi-visuals-tools** later this month.

**Comment by lucazav** [comment]
Thank you, @uve! There will be any breaking change in the new version or just a dependencies update?

**Comment by KesemSharabi** [comment]
Hi @lucazav, the new version will not include breaking changes, only dependency changes.
