### ISSUE TITLE
the newest sample retail analysis PIBX

### ISSUE THREAD

**Issue by rudyh67** [MicrosoftDocs/powerbi-docs#326]
I am reading the https://docs.microsoft.com/en-us/power-bi/desktop-data-categorization but my retail Analysis sample PIBX seems different.

I have already download from https://docs.microsoft.com/en-us/power-bi/sample-retail-analysis

please inform to me the link off newest retail Analysis sample PIBX so that I can continue my reading

regards 
rudy

**Comment by davidiseminger** [comment]
Thanks for your comment @rudyh67. You can get all available samples from the following locations:
https://github.com/Microsoft/powerbi-desktop-samples/tree/master/2018 
https://docs.microsoft.com/en-us/power-bi/sample-datasets
Hope that helps!
