### ISSUE TITLE
"Embedding with Power BI" section is unclear

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3260]
Hello,

The section "Embedding with Power BI" has a brief mention of a concept, but doesn't clarify what it is, and where to get additional information.  Would be great if this section could be expanded with more detail.

Thanks!
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe7888c3-14b3-8120-7fa5-80af7d1febba
* Version Independent ID: af40d3fb-5ed4-fa37-0e1d-afd01b1faf1e
* Content: [Power BI embedded analytics overview - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-analytics-power-bi)
* Content Source: [powerbi-docs/developer/embedded/embedded-analytics-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-analytics-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @chrisweis,

Embedded analytics has two solutions:

* Power BI Embedded - this is a feature that refers to embedding Power BI items using an Azure subscription.
* Embedding with Power BI - this isn't a feature, it's simply a made up name for embedding Power BI items with an Office 365 subscription.

Does that help clarify matters?

Thanks,

Kesem
