### ISSUE TITLE
Power BI visual Paginated Report (preview) early feedback

### ISSUE THREAD

**Issue by rmss-tech** [MicrosoftDocs/powerbi-docs#3261]
Power BI visual: Paginated Report (preview) issues/challenges in current form:

Once one chooses the paginated report to embed, there does not appear to be a way to change it to **select another report** without deleting the visual and recreating adding a new visual to the canvas
This does not appear to have a solution for use in **Deployment Pipelines** feature, where one would want to automatically promote (replace) the paginated report embedded in this visual with the local one in the current environment as the PBI report is promoted from Dev -> Test -> Prod.  
The **supplied parameters does not have sufficient visibility** for troubleshooting.  Initial setup of the visual provides some good feedback on the parameter chosen (e.g.: current format, type conflict).  However, after the initial setup and one encounters an error, there appears to be a limited error message available
 

Thanks for your consideration for enhancing this preview feature. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaaf125-cd9e-4b88-c808-3bd53525d367
* Version Independent ID: df09f8c6-0e60-14dc-6095-c2be885019c7
* Content: [Create and use the paginated report visual - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/paginated-report-visual)
* Content Source: [powerbi-docs/visuals/paginated-report-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/paginated-report-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @rmss-tech -- thanks for taking the time to write up your feedback! Product feedback gets more attention if you enter it at https://ideas.powerbi.com/ideas/
I'm closing this issue. Please enter it where it'll do the most good!
