### ISSUE TITLE
Update tip link

### ISSUE THREAD

**Issue by randomnote1** [MicrosoftDocs/powerbi-docs#3263]
The following tip refers to a YouTube video which refers to a GitHub link which doesn't exist anymore.

> In this video, Using Power BI Desktop in government clouds, Technical Specialist Steve Winward shows how you can apply a registry setting to go directly to the right cloud endpoint for your environment. The registry key settings to bypass the global discovery endpoint are shared on GitHub.

I recommend updating the link to the updated GitHub link:

[https://github.com/microsoft/Federal-Business-Applications/tree/main/whitepapers/power-bi-registry-settings#dod](https://github.com/microsoft/Federal-Business-Applications/tree/main/whitepapers/power-bi-registry-settings#dod)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview?source=docs)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@randomnote1 - thanks for flagging that for us! I appreciate your contribution. I corrected the link and the change will publish within the next 24 hours.
