### ISSUE TITLE
Direct Query utilization on Premium Gen 2

### ISSUE THREAD

**Issue by aislingdeery** [MicrosoftDocs/powerbi-docs#3265]
The documentation is not clear or specific on how Premium Gen2 measures utilization for Direct Query. Here are my questions: 

How does direct query contribute to utilization with Premium Gen 2?	

- Is it a background or interactive operation?	
- How is the utilization/CPU time measured when a query is taking time on the source database to execute? The time between query begin and end?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ebe672-8784-bd46-2637-d8cf157ff676
* Version Independent ID: 0b6f0007-66c8-c90c-bc3e-47ae4555979c
* Content: [Understanding Power BI Premium Gen2 (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-concepts#premium-gen2-capacity-load-evaluation)
* Content Source: [powerbi-docs/admin/service-premium-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-concepts.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by gnair-ms** [comment]
_Is it a background or interactive operation?_

The Direct Query costs can be either interactive or background depending on whether the queries are executed by an interactive user or for refreshing caches/dashboards (if required). In that respect, the interactive vs background is orthogonal aspect to the implementation of Direct Query datasets.

_How is the utilization/CPU time measured when a query is taking time on the source database to execute? The time between query begin and end?_

While the notion of CPU metric can change in future, currently the CPU reported is actual on-core cost of the query execution. Hence while the DAX query is waiting for results from data source, there is no cost reported. Further, on-core cost for Direct Query DAX queries, is mainly about any work the DAX engine had to do (e.g. when joins will not work).

Note that in future, we might have different way report CPU if the resource consumption of waiting queries becomes a resource issue for the larger service, to be honest here.
