### ISSUE TITLE
Ampersand does not get passed as a special character in URL

### ISSUE THREAD

**Issue by daviduber1** [MicrosoftDocs/powerbi-docs#3266]
"URL filters already support all special characters in field values, except the single quote (')."

My testing shows ampersands are not supported, and must instead be passed in fully parsed like filter=Table/Column%20eq%20%27test%20%26%20test%27

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @daviduber1 -- good question! I'll check and get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @daviduber1 -- right you are! Belatedly, updating the article with your feedback. Changes should be live tomorrow afternoon Jan 6 Pacific time.
Thanks!
