### ISSUE TITLE
Unavailable and out of date nuget package and code

### ISSUE THREAD

**Issue by aventius-software** [MicrosoftDocs/powerbi-docs#3267]
Hi Guys

The documenation example code states you should be installing version 2.21.301221612 of the Microsoft.IdentityModel.Clients.ActiveDirectory pacakge. However, not only is this version way out of date, but the version stated above is no longer available on NuGet even if you wanted to use the example code.

As such, please could the code examples be updated to support the latest version of the package (5.2.9 at the time of writing) as the code supplied in the example does not work with the current version of the specified package.

Cheers

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @aventius-software.

This series of articles is very old and currently not maintained. We're planning to retire these articles and replace them with new content sometime in the near future.

In the meantime, if you require assistance you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
