### ISSUE TITLE
Allow unrestricted measures in DirectQuery mode is not available 

### ISSUE THREAD

**Issue by federiconasta** [MicrosoftDocs/powerbi-docs#3268]
<img width="527" alt="powerbi_version" src="https://user-images.githubusercontent.com/88151670/130836350-8fdad68a-c63a-4dfd-b016-3d44f9f5ed02.png">

![image](https://user-images.githubusercontent.com/88151670/130836432-6f66de68-37f4-4a0e-8cca-db5eb4b93107.png)

As of August 2021, "Allow Unrestricted measures in Direct Query Mode" is not available.
In my project I cannot switch to Import Query due to architecture.
Is there an alternative to find this check box that would allow the DAX functions?

Thank you

**Comment by davidiseminger** [comment]
Thanks for your comment, @federiconasta. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
