### ISSUE TITLE
Missing info on working with MS Store version of PBI Desktop

### ISSUE THREAD

**Issue by kpuls** [MicrosoftDocs/powerbi-docs#3270]
Article needs some clarification on how to set up external tools so that they show up in the Microsoft Store version of Power BI Desktop (or that it doesn't work there if this is the case.)  I've been unable to work out how to get this menu to appear as the cited paths do not appear with the store version.

In addition, it would be super helpful to have a scripting example of getting the port number that works in a COM based language (C#/VB.NET), in addition to Power Shell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3888723f-6ff7-d86e-0d6f-4e66af8c17d3
* Version Independent ID: 4afa2f8d-72fc-d2bd-f1af-3e857d246290
* Content: [Register external tools in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-external-tools-register)
* Content Source: [powerbi-docs/transform-model/desktop-external-tools-register.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-external-tools-register.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello @kpuls -- I've confirmed that this does indeed work in the MS Store version of Power BI Desktop. At this point I believe you should pursue some support with what you're trying to achieve. Thanks too for your suggestion. 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
