### ISSUE TITLE
Publish replaced Save As

### ISSUE THREAD

**Issue by tomattto2** [MicrosoftDocs/powerbi-docs#3272]
Followed the steps but found a doc bug under the Manual migration section.  Step 4 in the current doc says to:			

1. Open each report in Power BI Report Builder, and then:
2. Verify all data sources and datasets are embedded in the report definition, and that they're supported data sources.
3. Preview the report to ensure it renders correctly. 
4. Choose the Save As option, and then select Power BI service.

			
When you choose Save As, there is no option to select Power BI Service, it appears now the option should be Publish rather than Save As.  The doc should say:  

1. Open each report in Power BI Report Builder, and then:
2. Verify all data sources and datasets are embedded in the report definition, and that they're supported data sources.
3. Preview the report to ensure it renders correctly.
**4. Choose the Publish option and then select Power BI service
5. Select your workspace
6. Provide a file name and click Save** 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c868cc-a15f-f870-ed4e-7b3d9dbd3ec0
* Version Independent ID: 1c353bbb-038f-5ea9-eb10-98401dd0fddb
* Content: [Migrate SQL Server Reporting Services reports to Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/migrate-ssrs-reports-to-power-bi)
* Content Source: [powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @tomattto2 -- thanks, good catch! I've updated the article. Change will be live tomorrow afternoon Pacific time Sept 8.
