### ISSUE TITLE
Missing Hyperlink/item on Glossary 

### ISSUE THREAD

**Issue by BaioccoA** [MicrosoftDocs/powerbi-docs#3274]
Hello, on the glossary, the "connectors" item is missing/incomplete.

There is a definition for "Data Connector" which tells the user to see "Connectors", however the later does not exist in the glossary.

This is how it appears on screen:

![Screenshot 2021-08-31 at 16 29 25](https://user-images.githubusercontent.com/89859432/131531666-a0c0cfe7-87b2-44b4-a797-cb7acf826d84.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52715480-01e0-b777-74ae-1aadb5fd3f2d
* Version Independent ID: f8ec264c-2df4-5adf-fdba-aa46d30bb07b
* Content: [Glossary for Power BI business users - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-glossary)
* Content Source: [powerbi-docs/consumer/end-user-glossary.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-glossary.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @BaioccoA . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @BaioccoA , 
Good catch! Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
