### ISSUE TITLE
Modification required in the content

### ISSUE THREAD

**Issue by Preeti1910** [MicrosoftDocs/powerbi-docs#3276]
[Need to change a line on this page]

![image](https://user-images.githubusercontent.com/13446409/131623673-6c084c94-9ba6-4338-a375-201b2300672c.png)

Here **Edit Queries** option is not there on HOME tab. We have to click **Transform Data** option from Home tab to open Query Editor window

![image](https://user-images.githubusercontent.com/13446409/131624117-2c999710-a7e1-433f-829a-9f40a7722591.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for pointing that out! I've updated the article to that effect.
