### ISSUE TITLE
Workspace Not Found Error for SPN Authentication to Power BI XMLA

### ISSUE THREAD

**Issue by real-oneill** [MicrosoftDocs/powerbi-docs#3279]
Hello. I'm having an issue connecting to the XMLA endpoint for my Power BI Premium workspace using a Service Principal. I can connect using my personal credentials via PowerShell, Tabular Editor, and SSMS. When I try to connect using the SPN, I consistently get the error:

_The specified Power BI workspace is not found._

I have confirmed that all of the prerequisite workspace settings below are enabled. The SPN has no problem authenticating to the Power BI REST API to refresh datasets, but is having trouble with the XMLA endpoint for some reason.

- Service Principal access to your Power BI tenant is enabled by your Power BI admin
- XMLA read/write endpoint enabled on your Premium capacity
- The Service Principal must be added as an administrator of the workspace

Any insight is appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 942d342d-b542-100b-2eb2-a4aa305da24b
* Version Independent ID: 86c649cf-c841-7600-226a-1befbcf648db
* Content: [Troubleshoot XMLA endpoint connectivity in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/troubleshoot-xmla-endpoint)
* Content Source: [powerbi-docs/admin/troubleshoot-xmla-endpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/troubleshoot-xmla-endpoint.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **davidi**

**Comment by Minewiskan** [comment]
@real-oneill - Git Issues for documentation are not a support channel. Please refer to the Power BI support page for better channels for your questions. https://powerbi.microsoft.com/en-us/support/. Thanks.
#please-close
