### ISSUE TITLE
Public Peering and Microsoft Peering Setup

### ISSUE THREAD

**Issue by sbdoroff** [MicrosoftDocs/powerbi-docs#328]
Hi,

Public Peering has been deprecated for new circuits leaving Microsoft Peering as their only option.  What is the best way to get steps for Power BI setup with Microsoft Peering listed in this document? 

Reference Doc: https://docs.microsoft.com/en-us/azure/expressroute/expressroute-circuit-peerings#azure-public-peering
Configuring MS Peering Route Filters/BGP Communities: https://docs.microsoft.com/en-us/azure/expressroute/how-to-routefilter-portal
Supported BGP Communities: https://docs.microsoft.com/en-us/azure/expressroute/expressroute-routing#bgp

Best,

Steve
Azure Networking - CSS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b54c2c06-9e5e-1ded-a3f8-396f7fdf7841
* Version Independent ID: 4cde51d1-ab58-8889-b187-ac0d3020bdee
* Content: [Power BI and ExpressRoute - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-expressroute)
* Content Source: [powerbi-docs/service-admin-power-bi-expressroute.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-expressroute.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @sbdoroff . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

It also looks like you might have a support request rather than / in addition to documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by mgblythe** [comment]
Thanks @sbdoroff - I'm looping one of the product PMs in too.

**Comment by mgblythe** [comment]
@sbdoroff -- closing out the issue here but we need to work with @KayUnkroth to set up an environment for this.

**Comment by jason-ra** [comment]
This was closed but doesn't seem resolved. Is PowerBI just included in the single location-based route filter? Or is it within Dynamics 365 filter since it's part of the Power Platform? Please clarify in this article as the two links provided make no specific mention.

**Comment by rwiankowski** [comment]
Hi,

It's been a while since this issue was closed but I'm sad to say that it's still pretty hard to figure out which BGP community should be used for PowerBI.

Is there any documentation for this?

Best,
Radek

**Comment by sbdoroff** [comment]
Hi Team,

We never had an ExR to test in the past but I think that has changed.  Let me do some checking to see if it would be possible to test this.

Best,

Steve Doroff
Technical Adviser | Azure Networking | Customer Service & Support

**Comment by sbdoroff** [comment]
Quick follow up:  Did a check in with the team that is hosting the ExR environment.  Sounds like we should be able to identify which path the traffic is flowing down once the BGP Community is enabled.  That stated, we just need the PowerBI FQDN or the correct IP for testing.  Where could I find that information?

Best,

Steve Doroff
Technical Adviser | Azure Networking | Customer Service & Support



From: Steve Doroff
Sent: Tuesday, January 19, 2021 8:24 AM
To: MicrosoftDocs/powerbi-docs <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Public Peering and Microsoft Peering Setup (#328)

Hi Team,

We never had an ExR to test in the past but I think that has changed.  Let me do some checking to see if it would be possible to test this.

Best,

Steve Doroff
Technical Adviser | Azure Networking | Customer Service & Support
