### ISSUE TITLE
Add steps for using Power BI Desktop with Oracle 19C

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3280]
Hello,

It would be great if this page could be updated to explain how to use Power BI Desktop with a more modern Oracle driver, especially Oracle 19C.

Thanks,
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database#install-the-oracle-client)
* Content Source: [powerbi-docs/connect-data/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We're in the process of updating the connector articles and will take this into consideration as we make that move. 

Meanwhile, you can visit this article for the most updated content on connecting to Oracle. https://docs.microsoft.com/en-us/power-query/connectors/oracledatabase
