### ISSUE TITLE
Outdated screenshot for bookmark option

### ISSUE THREAD

**Issue by schuffa** [MicrosoftDocs/powerbi-docs#3281]
This screenshot ...

https://docs.microsoft.com/en-us/power-bi/collaborate-share/media/service-automate-power-bi-report-export/automate-report-bookmark-url-12.png

... used on this help page ...

https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export

... is VERY poor, as it does NOT show what is needed to be entered into that field. 

The correct entry is NOT "?bookmarkGuid=D49722...", but rather in the format "Bookmarkf3078817d7c17fa3fd5d" -> so w/o the "?bookmarkGuid=" and starting with "Bookmark..." in the meantime.

It took me significant time to figures this out - so please update your screenshot / documentation to help other users to avoid the same, bad experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @schuffa! Checking this and will get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @schuffa -- we've updated the article; change will be live tomorrow. Note though that your issue may result from using the word "bookmark" in the bookmark itself, leading to confusion.
Hope that helps!

**Comment by schuffa** [comment]
I have no issues using "Bookmark..." -> works perfectly fine. It's rather the opposite, that what was in the article ("?bookmarkGuid=D49722...") has NOT worked. Looking forward to the changes which are on the way to be pubilshed
