### ISSUE TITLE
Cambio de la libreria en el powershell

### ISSUE THREAD

**Issue by stewartbancolombia** [MicrosoftDocs/powerbi-docs#3282]
Hola,

Validar en la documentación el código del power shell que esta desactualizado -RecordType PowerBI ya que la librería cambio por -RecordType PowerBIAudit

Gracias.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing#feedback)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
¡Gracias por los comentarios! Hemos hecho este cambio.
