### ISSUE TITLE
Azure Log Analytics in Power BI

### ISSUE THREAD

**Issue by mst42a** [MicrosoftDocs/powerbi-docs#3287]
It would be a great improvement if you could log from multiple workspaces to a single Azure Log file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7e7eb5-b6a5-7255-acb1-45f93e39bf17
* Version Independent ID: d616d078-a8b9-0a52-7502-fc528a214f95
* Content: [Using Azure Log Analytics in Power BI (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-overview)
* Content Source: [powerbi-docs/transform-model/log-analytics/desktop-log-analytics-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/log-analytics/desktop-log-analytics-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
