### ISSUE TITLE
Select multiple data points in a visual using rectangular lasso

### ISSUE THREAD

**Issue by jbornema** [MicrosoftDocs/powerbi-docs#3288]
It looks to me the maximum data points that can be selected is 3,500 and not 300 as documented here:
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-multi-select#select-multiple-data-points-in-a-visual
Screenshot:
![image](https://user-images.githubusercontent.com/3399260/132322227-a6532c44-5604-4fdb-bedd-516e5a3b4736.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02349558-4417-b39f-be59-b80655babdd2
* Version Independent ID: 6c5c0c15-6bf4-e775-1f0e-d95525ec30cf
* Content: [Multi-select data elements in visuals, or multiple visuals, in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-multi-select)
* Content Source: [powerbi-docs/create-reports/desktop-multi-select.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-multi-select.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting! I've updated that article to reflect the new maximum.
