### ISSUE TITLE
No update here for May 2021 What's New. Please add.

### ISSUE THREAD

**Issue by mfloyd65** [MicrosoftDocs/powerbi-docs#3289]
[No update here for May 2021 What's New. Please add. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff7e1942-9181-3451-5d1e-08bfa2ca9454
* Version Independent ID: 5547fc15-7d0e-225f-e0f1-890470f6cd5e
* Content: [What's new in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/whats-new)
* Content Source: [powerbi-docs/report-server/whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/whats-new.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @mfloyd65 -- good catch! I'll check and get back to you. In the meantime, the Change Log article was updated for May 2021, if that helps:
https://docs.microsoft.com/en-us/power-bi/report-server/changelog

**Comment by maggiesMSFT** [comment]
Hi, @mfloyd65 -- I've added the highlights, with a link to the blog post with the complete information. Update will be live tomorrow Sept 9 afternoon Pacific time. 
Here's a link to the blog post:
https://powerbi.microsoft.com/blog/power-bi-report-server-may-2021-feature-summary
Thanks!
