### ISSUE TITLE
Whats is expected GA date for new Workspace experience?

### ISSUE THREAD

**Issue by DetlevVreeken** [MicrosoftDocs/powerbi-docs#329]
Any idea when (what date) GA for new Workspace is expected for NorthEurope?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @DetlevVreeken -- thanks for asking! No, we don't have a date for GA yet. Keep your eye on the "October 2018 summary of planned features for Power BI" for updates: https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features#power-bi-service. 
thanks!

**Comment by jeroenhabets** [comment]
@maggiesMSFT please reopen and only close _after_ the GA date is provided (as asked by @DetlevVreeken).

It's been two months so hopefully MS has some visibility on a GA date by now.
