### ISSUE TITLE
Out of date info for dataflows in deployment pipelines

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#3290]
Hi there. Two items appear to be out of date in the table here: https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#permissions

According to my test:
1.	A workspace member can deploy a dataflow. So it looks like the same improvement that datasets got applies to dataflows too…which is awesome! So, on the dataflow row I believe it can be changed from dataflow owner to workspace member like the other artifacts.)
2.	The owner after deployment for the dataflow does change to who deployed it. In the documentation, that’s shown for the paginated report whereas it should be the dataflow.

![image](https://user-images.githubusercontent.com/15078148/132587055-ed63e52e-6f94-496c-b8f3-7a8b08b044df.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines, the Power BI Application lifecycle management (ALM) tool, process - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#permissions)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comments, @sqlchick.

I'm checking this with the development team. If you're right, I'll revise the documentation accordingly.

**Comment by KesemSharabi** [comment]
Hi @sqlchick,

After checking with the engineering team, it seems that the table is correct. The scenario you described can happen during a first time deployment (when using a 'clean copy'). However, during an update, the information in the table is correct. Please try to recreate this scenario when you're updating the pipeline, and let me know if it works.

Thanks,

Kesem

**Comment by sqlchick** [comment]
Hi Kesem - Thanks very much for looking into it. 

Unfortunately that doesn't agree with what I'm seeing in my tenant. 

Here are the steps I've taken to verify & reproduce:
-User A is the owner of the dataflow in both the Dev & Test workspaces.
-User A is a workspace admin for both the Dev & test workspaces.
-User B is a workspace member for both Dev & Test workspaces.
-Users A and B are both deployment pipeline admins.
-User A makes a change to the dataflow in the Dev workspace.
-User B does the compare in the pipeline & successfully deploys all changes to Test workspace.
-User B becomes the new owner of the dataflow in the Test workspace. 

Based on the above steps that I performed just a few minutes ago, it appears to me like a workspace member can deploy an existing dataflow & take over ownership.

Also, regardless of the outcome of the above, I still think the reference to "owner" needs to be taken off of the paginated report row in the table & put on the dataflow row of the table (if you see the arrow in my original screenshot you'll see it's just sitting on the wrong row). Basically item 2 from my original message is just a typo on the page. 

Thanks!
Melissa

**Comment by KesemSharabi** [comment]
Thanks @sqlchick,

This is definitely not the expected behavior. I asked the engineering team to look into this and will keep you posted.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @sqlchick,

As per my understanding the engineering team will investigate this issue with you. I'll sync with them shortly and update the documentation according to their findings.

Thanks,

Kesem
