### ISSUE TITLE
Include clearer guidance over which app to use for Premium Gen 2 users

### ISSUE THREAD

**Issue by AdamRiddick** [MicrosoftDocs/powerbi-docs#3291]
I came across the [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-monitor-capacity) documentation when looking at options for  in-depth monitoring to diagnose any issues that may arise when using power BI embedded.

While there is a section explaining the app can be used to monitor a Power BI Embedded Capacity, this app itself does not work with Embedded Generation 2. We don’t receive an error, just that most (75%+) of the metrics are left blank.

Searching for a solution I came across this post in April which links to a different app: [Solved: Capacity Metrics App is not showing any "Resource ... - Microsoft Power BI Community](https://community.powerbi.com/t5/Service/Capacity-Metrics-App-is-not-showing-any-quot-Resource/m-p/1789281)

I installed the Premium Gen 2 Capacity Utilization Metrics app as suggested in the solution, however upon doing so, I see that this is discontinued as of the 17th September and points us to a third app (Premium Capacity Utilization & Metrics)
 
Ideally, the first documentation link would include details of this app for Generation 2 users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/admin/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @AdamRiddick,

Thanks for your feedback and for sharing your experience with us.

We recently updated the table of contents to reflect a separation between Gen1 and Gen2.

**Gen2**
![image](https://user-images.githubusercontent.com/54834915/141322481-27d11e2e-c97d-4b94-a5b3-7365efbd8252.png)

**Gen1**
![image](https://user-images.githubusercontent.com/54834915/141322747-2d3c0967-709b-42c9-bcf7-312a5f39a63c.png)

Hopefully this will help prevent future confusion. Shortly, when Gen2 becomes GA we'll remove all the Gen1 documents and the Gen1 app.

Hope this helps,

Kesem
