### ISSUE TITLE
No Tooltips for Report Description?

### ISSUE THREAD

**Issue by ChrisSaunders64** [MicrosoftDocs/powerbi-docs#3292]
Publishing multiple reports within an app is great, but the tooltip for each report just repeats the name. Surely it would be more useful to display the report Description where populated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ChrisSaunders64 -- thanks for your comment! It sounds more like product feedback, so I'm going to close this issue and ask that you enter it in the Power BI Ideas site, https://ideas.powerbi.com/ideas/
Thanks!
