### ISSUE TITLE
Some input from review.

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [MicrosoftDocs/powerbi-docs#3294]
1. Let's add the copy visual section here too, liked that very much
2. Will need images to support these
3. May want to add more context and 'why' to each of the sections, they felt a little terse. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c778cbf1-81b2-1a99-2328-471ee4fbd870
* Version Independent ID: 92e418b5-6fb8-317d-01cd-4aeb9bbd8f6e
* Content: [Lead data-driven discussions in Microsoft Teams - Power BI](https://review.docs.microsoft.com/en-us/power-bi/consumer/business-user-teams-share-data?branch=pr-en-us-6384#feedback)
* Content Source: [powerbi-docs/consumer/business-user-teams-share-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/business-user-teams-share-data.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
added to https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/6384
