### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by LukaszPawlowski-MS** [MicrosoftDocs/powerbi-docs#3296]
Let's work on this one next week. I think I need to provide more scaffolding for the value users can get from their personal analytics report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169141e1-d22c-31c4-1808-db91fa33b154
* Version Independent ID: c0022d7d-6707-98b4-8d29-e3997cf0b265
* Content: [Collaborate using data in Microsoft Teams - Power BI](https://review.docs.microsoft.com/en-us/power-bi/consumer/business-user-teams-collaboration-data?branch=pr-en-us-6384)
* Content Source: [powerbi-docs/consumer/business-user-teams-collaboration-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/business-user-teams-collaboration-data.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
added comment to https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/6384
