### ISSUE TITLE
Links in notes sections are broken

### ISSUE THREAD

**Issue by JTUoB** [MicrosoftDocs/powerbi-docs#3297]
[Enter feedback here]

Both links in notes sections are broken:
https://docs.microsoft.com/en-us/admin/service-premium-per-user-faq.yml
https://docs.microsoft.com/en-us/admin/service-premium-what-is.md#power-bi-premium-generation-2-preview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6e1bb7-fbc5-d0a6-5285-e4a9152902bb
* Version Independent ID: ece0823b-c4c5-3acb-41bb-55e5390c0b6c
* Content: [Power BI service features by license type - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type)
* Content Source: [powerbi-docs/fundamentals/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-features-license-type.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
@JTUoB - thank you so much for flagging that for us. The links have been corrected and the fix will be live this afternoon. In the meantime, you can find our content about Premium Gen2 at this location: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is. Thanks again for the contribution!
