### ISSUE TITLE
Tenant specific versus multi tenant error

### ISSUE THREAD

**Issue by JerryMWeeks** [MicrosoftDocs/powerbi-docs#3300]
> 

[Enter feedback here]
Very nice service, although for my purpose powerbi.min.js in the .Net Core example lacks features to obtain dataset and data, guess the clue lies in "Embed"!
Anyway for Tenant specific .Net core "Embed for your organisation" - "User owns data" lacks instructions for adjusting appsettings.json Domain parameter to match company when not multi tenant.
And in  .net framework adding the parameter in web.conf doesn't work, I am currently trying to find where I can switch from multi to Tenant specific.
Error message thrown:
_is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'._ 
Experiment so far in web.config (adjusted for privacy!).
`
    <add key="Domain" value= "mycompany.com"/>
    <add key="TenantId" value="{guid}" />
    <add key="clientId" value="{guid}" />`
etc.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90078026-b608-ccf2-f3ef-58021b484f75
* Version Independent ID: e51ab568-5610-ff18-c5c0-4d2f27935dfa
* Content: [Embed content in your Power BI embedded analytics application enabling better embedded BI insights for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-your-organization?tabs=net-framework)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-sample-for-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by JerryMWeeks** [comment]
Sorted it in web.config use this approach instead:
<add key="authorityUri" value="https://login.microsoftonline.com/{tenant}/v2.0" />
Question regarding OwinOpenIdConnect.cs line 55 - I changed from "common" to "mycompany.com"
`string tenantSpecificAuthority = tenantCommonAuthority.Replace("common", tenantId);

string tenantSpecificAuthority = tenantCommonAuthority.Replace("mycompany.com", tenantId);`

Is that required, or is it worth using a paramter from web.config?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JerryMWeeks. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
