### ISSUE TITLE
Broken link for "Generate token for multiple reports" bullet

### ISSUE THREAD

**Issue by oferash** [MicrosoftDocs/powerbi-docs#3301]
Broken link for "Generate token for multiple reports" bullet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443b866a-5447-5ea7-beab-bf4bd3d3c0ae
* Version Independent ID: 7235c41a-551d-9a8d-6253-cf591a1e336c
* Content: [Considerations for generating an embed token in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/generate-embed-token)
* Content Source: [powerbi-docs/developer/embedded/generate-embed-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/generate-embed-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @oferash,

Thanks for pointing out the broken link. It's now fixed, and will be live in a few days.

Thanks,

Kesem

**Comment by oferash** [comment]
The link is still broken 11 days later.

Now a few customers have already hit the 404 error and asked when is this to be fixed?...

**Comment by oferash** [comment]
How come this is closed while the link is still broken?
https://docs.microsoft.com/en-us/rest/api/power-bi/embed-token/embed-token-generate-token

**Comment by oferash** [comment]
Hi Ofer,

Apologies, I'm not sure what went wrong as I fixed the link before Sukkot.

In any case, I fixed it again and it should be live today at ~13:30 Redmond time.

Thanks,

Kesem

From: Ofer Ashkenazi ***@***.***>
Sent: Thursday, September 30, 2021 9:52 PM
To: MicrosoftDocs/powerbi-docs ***@***.***>; MicrosoftDocs/powerbi-docs ***@***.***>; Alon Baram ***@***.***>; Kesem Sharabi ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/powerbi-docs] Broken link for "Generate token for multiple reports" bullet (#3301)

The link is still broken 11 days later.

Now a few customers have already hit the 404 error and asked when is this to be fixed?...
