### ISSUE TITLE
AI Insights applicability

### ISSUE THREAD

**Issue by TarekSalha** [MicrosoftDocs/powerbi-docs#3302]
For non-IT users it is very hard to understand, that view insights feature on tiles is based on the same principles as the insights feature on datasets (see [Generate data insights on your dataset automatically](https://docs.microsoft.com/en-us/power-bi/create-reports/service-insights)
It should be added, that also tiles based on PUSH, Streaming, direct query as well as RLS equipeed datasets are not supporting insights.
Inside the Dashboard in a day events, we experience many questions regarding the topic due to the docs being unclear.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b424591b-0892-e054-6c7b-b1b7ec18b40a
* Version Independent ID: 394c65bd-bf66-a348-df3b-f0a108eeb37d
* Content: [Run and view insights on dashboard tiles - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-insights#run-insights-on-a-dashboard-tile)
* Content Source: [powerbi-docs/consumer/end-user-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-insights.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @TarekSalha ,
Thank you for this insight from your training class.  I've made some updates to the article that I hope will make it easier to understand for new users.  And I've added the limitations for RLS, DirectQuery, etc... as well.  
Thank you for your suggestions!
the DOCS team
