### ISSUE TITLE
Please add recommendations as to font size

### ISSUE THREAD

**Issue by rovermx** [MicrosoftDocs/powerbi-docs#3304]
Great starting documentation, I would love to see any minimum font size recommendations

Thanks
Renaud Montes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a040fd91-bc39-f1f7-b5bf-1a2964e7067e
* Version Independent ID: 1dd198ca-08a2-022b-a186-70f355882821
* Content: [Overview of accessibility in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-overview)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your suggestion -- we'll take this into consideration as we update our documentation.

**Comment by rovermx** [comment]
Thank you, David, within Microsoft, I have partnered with a team that developed an Accessibility Style guide for Power BI reporting that could be akin to MAS at some point, which I am using within my org and perhaps other orgs and even Power BI customers could benefit from this, let me connect with you via Teams.
