### ISSUE TITLE
Cannot select Power bi activities, only specific ones.

### ISSUE THREAD

**Issue by cking22001** [MicrosoftDocs/powerbi-docs#3305]
Article suggests you can 'select' Power BI Activities but you cannot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@cking22001 - thanks for the feedback and for flagging this for us! It looks like we're a little behind on an interface change in Microsoft 365. I'll work on getting that article caught up this week.

**Comment by kfollis** [comment]
@cking22001 - the article was updated recently and now reflects the interface changes. I'll close this issue. Thanks for contributing to our article accuracy!
