### ISSUE TITLE
Documentation is incomplete for datasets connected to SSAS

### ISSUE THREAD

**Issue by SirEel** [MicrosoftDocs/powerbi-docs#3306]
These instructions are incomplete for datasets that connect to SSAS via an on-premise data gateway. You'll get an error that says, "Creating embed token for accessing dataset xxx-xxx-xxx-xxx-xxx requires effective identity to be provided". To fix this you'll need to grant a special permission to the ServicePrincipal, and then you'll need to modify the client to include the login name of an Active Directory user with the embedToken request. 

Most of the additional information you need is in this blog post, but it really should be in the documentation on this page: https://prologika.com/power-bi-embedded-service-principals-and-ssas/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 794566fc-c06c-1d9c-b656-2e7b59bc2874
* Version Independent ID: 4c57568f-c4f2-0bd6-b724-9868b2455d50
* Content: [Embed Power BI content in an embedded analytics application with service principal and an application secret - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal)
* Content Source: [powerbi-docs/developer/embedded/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @SirEel,

Thank you for your comments - you're right about the missing information. However, I believe it needs to go here: [On-premises data gateway with service principal](https://docs.microsoft.com/power-bi/developer/embedded/embedded-row-level-security#on-premises-data-gateway-with-service-principal).

We're working on updating the [Row-level security with Power BI Embedded](https://docs.microsoft.com/power-bi/developer/embedded/embedded-row-level-security#on-premises-data-gateway-with-service-principal) article, and will do this shortly. When we do, we'll add the missing information that you highlighted.

Thanks,

Kesem
