### ISSUE TITLE
Can a report quickly from a SharePoint list in the Power BI service be embeded in a sharepoint Page?

### ISSUE THREAD

**Issue by Developer0111** [MicrosoftDocs/powerbi-docs#3308]

**Comment by Developer0111** [comment]
Can anyone help me?

**Comment by maggiesMSFT** [comment]
Hi, @Developer0111 -- can you provide a little more info? Are you looking at a specific article? That would help. Also, maybe missing a verb in your question? Is your question: "Can I create a report quickly in the Power BI service from a SharePoint list, and then embed that report in a SharePoint Page?"
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, sorry for the delay! OK, I've checked with the product team. They say:
"Not currently and no current ETA, though we’re definitely aware of the ask. "
You can also enter your feedback here:
https://ideas.powerbi.com/ideas/
Thanks!
