### ISSUE TITLE
F6 and other shortcuts

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3309]
The description is not clear enough. For example F6 is supposed to Activate selection pane, but it doesn't in Desktop. Same with some other shortcuts. 
Also - why would not you make a shortcut to switch pages (Ctrl-PgDown) like in Excel? It is not very efficient when you have to scroll to page no 23.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your update suggestion. We'll take this request into consideration as we update our documentation.
