### ISSUE TITLE
Code Erroring with "cannot convert from 'System.Uri' to 'Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential'

### ISSUE THREAD

**Issue by bryansmith-db** [MicrosoftDocs/powerbi-docs#3310]
Line 47 in the provided code seems to be failing. Any suggestion on how to fix is welcome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @bryansmith-db,

Thanks for your comment. I'm sorry to say that this article is no longer supported and that you're right, the code is outdated and doesn't work. We have a future plan to update these articles but I don't know when this'll happen.

In the meantime, you might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

Thanks,

Kesem
