### ISSUE TITLE
limitation information missing

### ISSUE THREAD

**Issue by vtheresaz** [MicrosoftDocs/powerbi-docs#3311]
this page is missing information about limitations. What-if parameters can only be used with values 0-1000, for numbers greater than 1000 the parameter value will be sampled. This information is not clearly specified in documentation.
We found the following community post where it was reported as a limitation back in 04/2020: https://community.powerbi.com/t5/Issues/What-if-parameters-do-not-work-due-to-1002-sampling-limit-on/idi-p/1043211

Please review, thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c901a3b2-3c35-bb07-b3ed-e7784808f09b
* Version Independent ID: cb24afe9-f74f-dd94-03de-e9e0c7c39045
* Content: [Use what-if parameters to visualize variables - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-what-if#using-a-what-if-parameter)
* Content Source: [powerbi-docs/transform-model/desktop-what-if.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-what-if.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by WaleIlori** [comment]
In addition to limitations, it should be stated that what-if parameters, though can be used in a dimension calculation, will not work (i.e. it will enable user create the calculation but will not evaluate correctly). It is only designed for only measures within a chart.

**Comment by davidiseminger** [comment]
Thanks for your clarifications. I've updated the article to reflect these.
