### ISSUE TITLE
Is there a way for applications to read the AIP encrypted files?

### ISSUE THREAD

**Issue by cshailaja** [MicrosoftDocs/powerbi-docs#3312]
Scenario - There is an app that reads the files from a storage location and updates it in Central Pricing Management. Some of these excel files that are getting upload contains sensitivity label which applies encryption. 

Is a way this application can be given certain privileges to be able to read these encrypted files?

**Comment by paulinbar** [comment]
Hi @cshailaja, I haven't heard back from you about where Power BI fits into this scenario, or if you're question is more general. In the meantime I am closing this issue, but feel free to reopen it if it's still relevant. Thanks.
