### ISSUE TITLE
No mention of P4/5 requiring special request in all documentation

### ISSUE THREAD

**Issue by t-foster2021** [MicrosoftDocs/powerbi-docs#3316]
In https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#capacity-nodes it states that P4/P5 Premium nodes are "By special request only". This however in this documentation https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#sku-memory-and-computing-power the mention about special requests is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @t-foster2021,

Thank you for letting us know about the missing P4/P5 SKU information - I added it to [SKU memory and computing power](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity#sku-memory-and-computing-power).

Thanks,

Kesem
