### ISSUE TITLE
Preparando para certificação

### ISSUE THREAD

**Issue by jeansilvaster** [MicrosoftDocs/powerbi-docs#3317]
[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e3c90ed8-2469-951f-af6a-5d2ec5ee89bc
* Version Independent ID: e651e3d9-8a99-56e9-9424-94c6fa5af927
* Content: [Tutorial: Create a decomposition tree with a Power BI sample - Power BI](https://docs.microsoft.com/pt-br/power-bi/create-reports/sample-tutorial-decomp-tree)
* Content Source: [powerbi-docs/create-reports/sample-tutorial-decomp-tree.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/sample-tutorial-decomp-tree.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jeansilvaster -- It appears that you have not asked a question, so I am closing this issue. Please create a new issue when you have a question. Thanks!
