### ISSUE TITLE
Dataset not visible in My Workspace, so I can't create custom reports from it

### ISSUE THREAD

**Issue by adumont** [MicrosoftDocs/powerbi-docs#332]
I have added the "App" as shown in the guide, and it works. When I go in Power BI Settings, under Datasets I can see a new Dataset has been configured. Th eproblem is when I go to My Workspace, I cannot see this new dataset in the Datasets section. As a consequence, I am unable to create a new report that uses this dataset. (When I try to create a new report, the datasets that I have undert My Workspace / Datasets appear, but not the Azure Consumption Insights dataset, for some reason.

Maybe I'm approaching this wrong? My need would be to create custom reports from the Microsoft Azure Consumption Insights  dataset. (I have some reports I did with Microsoft Azure Entreprise dataset that I would like to do again with this new dataset. I don't see how I can do that now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @adumont -- thanks for your question! We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by SarinaJoan** [comment]
Hi @adumont - have you installed this as a content pack or as an app? The content pack installs in your workspace and is editable, while the app just allows you to view the content. 
![getcontentpackedit](https://user-images.githubusercontent.com/11854211/47375138-6d357280-d6a4-11e8-8b5e-c2978c5c0b1d.png)

**Comment by adumont** [comment]
Hi Sarina,
I installed it as an App via the Get button. To be honest I didn't notice
and I didn't know about the second"Service Content Packs" option. I'll try
that.
Thank you very much for the help.
Best Regards,
--
Alex
