### ISSUE TITLE
Power BI Load Testing

### ISSUE THREAD

**Issue by junaidmajeed** [MicrosoftDocs/powerbi-docs#3322]
[Enter feedback here]

How to perform load testing on the Power BI tool?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 407af4e5-336a-af92-35ad-7a449cced735
* Version Independent ID: 53dc34f6-68b5-3e30-dcc2-1a8525c800bb
* Content: [Use Performance Analyzer to examine report element performance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-performance-analyzer)
* Content Source: [powerbi-docs/create-reports/desktop-performance-analyzer.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-performance-analyzer.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
