### ISSUE TITLE
You can only create template apps in the new workspaces?

### ISSUE THREAD

**Issue by 3b33** [MicrosoftDocs/powerbi-docs#3323]
The article says "You can only create template apps in the new workspaces."

But should this be ->

"You can create template apps only in the new workspaces."

vastly different meaning. I hope normal app creation has not dissappeared?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [The new workspace experience in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @3b33 -- thanks for your careful reading! I've made the update which will be live this afternoon Sept 30, Pacific time.
