### ISSUE TITLE
Feedback on steps for  Connect to a billing account

### ISSUE THREAD

**Issue by rajnair90** [MicrosoftDocs/powerbi-docs#3325]
[Enter feedback here]
I believe the steps given in this section https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management#connect-to-a-billing-account, is for the "Billing Account" as per Title and Screenshot. But the steps are talking about the "Billing Profile ID".
Kindly check. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management#connect-to-a-billing-account)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @rajnair90, thanks for reaching out to us. I have forwarded your comment along to the doc author for consideration.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we've updated that article to reflect.
