### ISSUE TITLE
Nice tip, but can I change a report source?

### ISSUE THREAD

**Issue by andymc123** [MicrosoftDocs/powerbi-docs#333]
This is nice to know, but I would need to start over.  is there a way to move an Excel file to OneDrive and then edit the source to "Web"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by andymc123** [comment]
answered my own question - here is a link - https://community.powerbi.com/t5/Desktop/Change-source-of-Excel-to-OneDrive-for-existing-reports/m-p/230247#M102698

**Comment by maggiesMSFT** [comment]
Hi, @andymc123 -- thanks for the info! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Hello @andymc123 - sorry for the delay getting back. There isn't a way to do that what I'm aware of, sorry.
