### ISSUE TITLE
No mention on Azure subscription limitations, restrictions, SKU on Azure bill?

### ISSUE THREAD

**Issue by cloudloudeu** [MicrosoftDocs/powerbi-docs#3330]
No mention on Azure subscription limitations, restrictions, SKU on Azure bill?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5331ed60-1d4a-dbef-1ec6-b9ca9de05e57
* Version Independent ID: bc5c01f8-67e1-6395-b079-12de4be557b0
* Content: [Using Autoscale with Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-auto-scale)
* Content Source: [powerbi-docs/admin/service-premium-auto-scale.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-auto-scale.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @cloudloudeu,

Thank you for your comment. I'll check if there are any Azure subscription limitations or restrictions.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @cloudloudeu,

Apologies for the late reply.

There are no restrictions on the Azure subscription (however it cannot be a trial subscription). 

As mentioned in [Configure an Azure subscription to use with Autoscale](https://docs.microsoft.com/power-bi/admin/service-premium-auto-scale#configure-an-azure-subscription-to-use-with-autoscale), you need to have contributor rights.

Hope this helps,

Kesem
