### ISSUE TITLE
Incorrect Power Platform admin permissions cited in article

### ISSUE THREAD

**Issue by mikem-MS** [MicrosoftDocs/powerbi-docs#3331]
Hi there,  

The article states exactly the same permissions for Power Platform admin and Power BI admin roles, which is incorrect i.e.

Power Platform admin | Power Platform | Full access to Power BI management tasks
-- | -- | --
  |   | Enable and disable Power BI features
  |   | Report on usage and performance
  |   | Review and manage auditing
Power BI admin | Power BI service | Full access to Power BI management tasks
  |   | Enable and disable Power BI features
  |   | Report on usage and performance
  |   | Review and manage auditing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3d7371c-d74d-6e7f-e6d2-77cff1d888a2
* Version Independent ID: ed31ccb5-e72f-0867-bb2e-100e76e7de72
* Content: [What is Power BI administration? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-administering-power-bi-in-your-organization#administrator-roles-related-to-power-bi)
* Content Source: [powerbi-docs/admin/service-admin-administering-power-bi-in-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-administering-power-bi-in-your-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@mikem-MS - Thanks for the feedback. I'm assigning this to a writer to make an update to the article, to ensure that the correct permissions are listed. If you have the info handy, you can also edit directly to suggest the change and it will be reviewed by a writer before publishing. @paulinbar - please reference https://docs.microsoft.com/en-us/power-platform/admin/use-service-admin-role-manage-tenant#service-administrator-permission-matrix and ensure that our admin permissions matrix aligns!

**Comment by paulinbar** [comment]
Hi @mikem-MS, sorry for the very delayed response. This has been updated now, along with the change from Power BI admin to Fabric admin. Thanks, and sorry again for the delay!
