### ISSUE TITLE
Enhanced Compute Engine documentation out of sync with Gen 2

### ISSUE THREAD

**Issue by aislingdeery1** [MicrosoftDocs/powerbi-docs#3333]
[Enter feedback here]
The details about enabling the enhanced compute engine are confusing and outdated since this is no longer an option on Premium Gen 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Assigning to the article owner.

**Comment by KesemSharabi** [comment]
Hi @aislingdeery1,

I updated the [Enable the enhanced compute engine](https://docs.microsoft.com/power-bi/transform-model/dataflows/dataflows-premium-features?tabs=gen2#enable-the-enhanced-compute-engine) section, with two tabs, one for Gen2 and another for Gen2.

Thanks for pointing out that this needed updating.

Kesem
