### ISSUE TITLE
PBI interface has changed with the newest version - update of document needed   

### ISSUE THREAD

**Issue by vertig00bg** [MicrosoftDocs/powerbi-docs#3339]
1."Tile refresh" option  is no more available in the Power BI Premium service. Please update the document accordingly. 
2."Microsoft recommends that you leave the checkbox Send refresh failure notification emails to me enabled.
It is also a good idea to specify additional recipients by using the Email these users when the refresh fails textbox. "

In the above (2.) the listed textboxes are :
"Send refresh failure notification emails to me " needs to be changed to "Dataset owner"
" Email these users when the refresh fails" needs to be changed to "These contacts:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your post! We've updated the textbox description. We're investigating the comment about tile refresh and its implication for the article, too.
