### ISSUE TITLE
Q&A to add

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/powerbi-docs#334]
How can you restrict marketplace?  Is there a way to only allow approved custom visuals?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6bd837-63e3-8bcd-9743-425e6da4a9b8
* Version Independent ID: 944bd5e0-a52f-0a4c-362b-68701f03c8d8
* Content: [Administering Power BI - frequently asked questions (FAQ) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-faq#how-can-i-prevent-users-from-joining-my-existing-office-365-tenant)
* Content Source: [powerbi-docs/service-admin-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-faq.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @danmyhre -- thanks for your question! We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Assigning to @markingmyname to address.
