### ISSUE TITLE
Explain the reason for Public Privacy Level

### ISSUE THREAD

**Issue by ndesousa** [MicrosoftDocs/powerbi-docs#3340]
You haven't explained the reason why "Public" should be selected as a Privacy level. This causes alarm in a user reading it as one immediately thinks that my data is exposed for the world to see. It's only after reviewing a few other links that I found out that privacy levels control which data sources are allowed to be combined with other data sources during query evaluation - nothing to do with the final report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. We have a link just below the image that explains privacy levels, I hope that helps.
