### ISSUE TITLE
Special Character in Values

### ISSUE THREAD

**Issue by LucaFontana** [MicrosoftDocs/powerbi-docs#3341]
**Special characters in values**
Documentation says: _URL filters already support all special characters in field values, except the single quote ('). That's the only character you need to escape. To search for a single quote character, use two single quotes ('')._

However url filtering with question marks (?) in values is not working and I had to escape them, replacing with "&3f" to make URL filtering work.
Thanks,
Luca

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @LucaFontana -- Good question, sorry for the delay! I'm checking with the product team and will report back.
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @LucaFontana -- right you are! Belatedly, updating the article with your feedback. Changes should be live tomorrow afternoon Jan 6 Pacific time.
Thanks!
