### ISSUE TITLE
Confused by limitation section indicating "multi-dimensional" sources not supported

### ISSUE THREAD

**Issue by markvsql** [MicrosoftDocs/powerbi-docs#3346]
The current limitation of "multi-dimensional" sources not being support lists Power BI Datasets as well as Azure Analysis services, neither of which are multi-dimensional. They are both tabular.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models)
* Content Source: [powerbi-docs/transform-model/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback on that term, we'll look at how it's used and update the content accordingly.
