### ISSUE TITLE
Missing items in documentation, e.g. "outspace"

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#3347]
This documentation are missing properties, e.g. "outspace" but also many more. To fix this, just take a look at your existing templates and make sure that the documentation contains everything that are used in the templates. 

Also, make sure the provided JSON files are complete. One contains fewer "}" than needed and one contains to many "}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by MattRudy** [comment]
Hey @maggiesMSFT - the repo you linked is inactive and the new link to use for the maintained version is below:
https://github.com/MattRudy/PowerBI-ThemeTemplates#readme

**Comment by MattRudy** [comment]
Created issue #3402  and PR #3403 for this update

**Comment by maggiesMSFT** [comment]
Thanks, @erapade and @MattRudy !

@erapade  - for the incomplete JSON files, "One contains fewer "}" than needed and one contains to many "}"" -- are they on https://github.com/deldersveld/PowerBI-ThemeTemplates/blob/master/README.md? If so, could you check the GitHub repo that @MattRudy provided the link for, https://github.com/MattRudy/PowerBI-ThemeTemplates#readme?
Thanks!

**Comment by erapade** [comment]
@maggiesMSFT: No, I refer to the two largest JSON definitions in this issues content. Just put those into an editor and you will se
