### ISSUE TITLE
Wrong Maximum dataset sizes

### ISSUE THREAD

**Issue by RadimHampel** [MicrosoftDocs/powerbi-docs#3348]
[Enter feedback here]
Maximum dataset sizes in Datasets in Import mode section are out dated, please replace with correct sizes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
I've added a note about large datasets and Premium capacities. Thanks for your post.
