### ISSUE TITLE
Incorrect information for data connectivity mode

### ISSUE THREAD

**Issue by lgendwila** [MicrosoftDocs/powerbi-docs#3349]
[Enter feedback here]
Hi. In a recent desktop update, the steps have changed for choosing import or DirectQuery modes when using the Snowflake connector. The "Data Connectivity mode" option is not on the first screen anymore. You need to add your server & warehouse, go to the next screen, select your tables, then on the third screen, you can select import or DirectQuery.

It's just called "Connection settings" now:
![image](https://user-images.githubusercontent.com/69007179/137034180-cbfaa21c-b14a-458c-9cd7-2c27c6e2fc94.png)

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback - we're in the process of updating our connector content, and will address this during that review/conversion.
