### ISSUE TITLE
Download link to example pbix is not working

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs#335]
In this note the download link is broken:
"Want to see a completed .pbix file with these steps completed? You're in luck - you can download the completed Power BI Desktop file used in these examples [right here](http://download.microsoft.com/download/F/8/A/F8AA9DC9-8545-4AAE-9305-27AD1D01DC03/Complete Values with Python in PQ.pbix)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdd46971-2ea5-9271-3b2a-824efc1821e1
* Version Independent ID: 68669cdb-5e4d-bb96-d2d5-bdad4088fb03
* Content: [Using Python in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-in-query-editor)
* Content Source: [powerbi-docs/desktop-python-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-in-query-editor.md)
* Service: **powerbi**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by maggiesMSFT** [comment]
Hi, @DaveRuijter -- thanks for letting us know! We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by mgblythe** [comment]
This was fixed last year but wasn't closed.
