### ISSUE TITLE
missing 4th footnote

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#3351]
There is a 4th footnote reference, but no 4th footnote

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-govus-overview)
* Content Source: [powerbi-docs/admin/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@GitWesDone - thanks for bringing this to our attention! After a little research I discovered that the related line item should have been removed along with the footnote. A publishing conflict created the inconsistency. Thanks again, your input was very helpful.
