### ISSUE TITLE
Personalize is great (until you reset to default)

### ISSUE THREAD

**Issue by charrington2** [MicrosoftDocs/powerbi-docs#3352]
Hi guys,

we love the personalize visuals option in Power BI. It's an amazing tool for some users such as analysts, etc.

The problem we have is that the "Reset to Default" button resets also those personalizations. Normal you say? Maybe.
But the "Reset to default" is widely used by our user community (as everyone else for sure) to reset the filtering they made while navigating through the data. They are often lost, they don't recall what they did, they don't understand the data they see, etc. so great, they hit "Reset to Default" button to get rid of filters. Oh, and then they just lose all their personalization for visuals!

We beleive there is a place for both resetting filters and resetting personalization. It's not the same right? Right now it's linked together. So personalization then becomes very temporary, and users have to redo them over and over again. It would be so nice if we can have maybe an extra option in the power BI file, to say "Reset to Default do not reset personalization" or something like that.

This way this feature would be more useful.

Thanks a lot!
Have a nice day

Christian Harrington
christian.harrington2@gmail.com
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615021e0-5504-046d-d6ab-c2d8dee0656f
* Version Independent ID: d9c6ad5a-139f-716e-eb59-473a1f8d73de
* Content: [Let users personalize visuals in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-personalize-visuals)
* Content Source: [powerbi-docs/create-reports/power-bi-personalize-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/power-bi-personalize-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @charrington2 -- yes, good point. Do read this article, https://docs.microsoft.com/en-us/power-bi/consumer/end-user-personalize-visuals, which talks about the report consumer experience with personalizing visuals. It does mention one way to preserve personalization: create personal bookmarks.
I'm updating this article to mention personal bookmarks. Changes will be live tomorrow afternoon, Jan 4, 2022, Pacific time.
Thanks!
