### ISSUE TITLE
Repeated paragraph

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3355]
Hi, exact same paragraph is repeated : "Deleting a Premium capacity is possible and won't result in the deletion of its workspaces and content. Instead, it moves any assigned workspaces to shared capacity. When the Premium capacity was created in a different region, the workspace is moved to shared capacity of the home region." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995501c4-ccb5-7c88-d4f0-f66ff3380cab
* Version Independent ID: 80a32aa6-18b8-2b8d-5a5e-988f5bc768cc
* Content: [Manage Microsoft Power BI Premium Gen2 capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-capacity-manage-gen2#planning-your-capacity-size-in-advance)
* Content Source: [powerbi-docs/admin/service-premium-capacity-manage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-capacity-manage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @nstraw,

Thank you for pointing out the repeating paragraph. The duplication is now removed, see [Creating and managing capacities](https://docs.microsoft.com/power-bi/admin/service-premium-capacity-manage-gen2#creating-and-managing-capacities).

Thanks again,

Kesem
