### ISSUE TITLE
Do we have a sample code over JavaScript?

### ISSUE THREAD

**Issue by suuuuuper** [MicrosoftDocs/powerbi-docs#3357]
[Enter feedback here]
Hi, do we have a sample code over JavaScript about "PowerBIEmbedded_AppOwnsData sample".
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Using row-level security with embedded content in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @suuuuuper,

There are many code samples in the [PowerBI-Developer-Samples](https://github.com/Microsoft/PowerBI-Developer-Samples) GitHub folder. I hope one of them can help you. 

If you're referring to a row-level security (RLS) code sample, I'm not sure we currently have one. However, we're working on updating the RLS documents, and may have such code snippets in the future.

You can also look for a solution in the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com).

Hope this helps,

Kesem
