### ISSUE TITLE
Adjust "The Power BI app for Microsoft Teams is available only to Commercial Cloud customers."?

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3359]
Feedback: I understand this feature is now available for Government customers, and this text is now outdated: "The Power BI app for Microsoft Teams is available only to Commercial Cloud customers."

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9a0262-d1a5-2824-16f1-0f13c5ce4a64
* Version Independent ID: f73f5d7e-a45a-c8aa-18a3-ab47f641ed57
* Content: [Add the Power BI app to Microsoft Teams - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-microsoft-teams-app)
* Content Source: [powerbi-docs/collaborate-share/service-microsoft-teams-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-microsoft-teams-app.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- yay, we fixed it already, and probably should've closed your comment a while ago! Now it says:
- The Power BI app for Microsoft Teams is available to Commercial Cloud and US Government Community Cloud (GCC) customers.

Thanks!
