### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by tnewton42** [MicrosoftDocs/powerbi-docs#336]
Trying the above steps (with or without adding a port reference to 1521), does not work. Getting error "We couldn't authenticate with the credential provided. Please try again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#determining-which-version-of-power-bi-desktop-is-installed)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by tnewton42** [comment]
problem still occurs after installing 64-bit version of app from .msi.

**Comment by aashisharora13** [comment]
I have been trying to connect to the Oracle Database by following the steps but I am not able to connect.
Getting error as Object reference not set to an instance of an object

**Comment by renezito** [comment]
I can connect to my Oracle DB with other tools, like sql tools, sql developer using my tnsnames,  but not with Power BI... Why it's so difficult?  The instrucctions you gave are not clear.... Can't I just replace some files instead of installing ODAC?  I don't want to install ODAC, my other apps are running ok with my actual oracle installation...

**Comment by nonsensely** [comment]
Excellent question - WHY IS THIS SO DIFFICULT?  Having the same issue.  I've connected our Oracle DB into DataGrip, Excel, iSeries, Symtrax - but even after installing the 64-bit connector (as instructed), getting:  Details: "Oracle: ORA-12154: TNS:could not resolve the connect identifier specified".

**Comment by sloggiz** [comment]
So point number 2 in official MS doc seems to be a complete BS. It never worked with either of the mentioned options so I tried using a full connection string from tnsnames.ora and it worked.
Basically you have to use this:
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=your_hostname_here)(PORT=your_portnum_here))(CONNECT_DATA=(SERVICE_NAME=your_service_name_here)))

**Comment by tnewton42** [comment]
> So point number 2 in official MS doc seems to be a complete BS. It never worked with either of the mentioned options so I tried using a full connection string from tnsnames.ora and it worked.
> Basically you have to use this:
> (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=your_hostname_here)(PORT=your_portnum_here))(CONNECT_DATA=(SERVICE_NAME=your_service_name_here)))

I was so hopeful, but when I try this I get an error "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

Following your example, I made sure my connection string has no carriage returns or spaces.

Oracle version 12.1.

(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=###.###.###.###)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MYDB)))

**Comment by sloggiz** [comment]
> > So point number 2 in official MS doc seems to be a complete BS. It never worked with either of the mentioned options so I tried using a full connection string from tnsnames.ora and it worked.
> > Basically you have to use this:
> > (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=your_hostname_here)(PORT=your_portnum_here))(CONNECT_DATA=(SERVICE_NAME=your_service_name_here)))
> 
> When I try this I get a different error "Attempted to read or write protected memory. This is often an indication that other memory is corrupt." This makes me think it's at least hitting the server.
> 
> Following your example, I made sure my connection string has no carriage returns or spaces.
> 
> Oracle version 12.1.
> 
> (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=###.###.###.###)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MYDB)))

Did Power BI crash after this error? This one seems like a PowerBI issue, rather then DB. I suggest you try re-installing PBI and make sure you have the latest stable version (I tested this on Aug 2018 and on the most recent one).

**Comment by sloggiz** [comment]
Very strange. I'd try one last thing (if possible) before logging a MS support ticket: connecting to a different Oracle DB to see if the error is PBI related or not.
Hope you get to the bottom of this and resolve the issue!

**Comment by rbh1** [comment]
I'm able to connect using the instructions but it seems to time out.  Is there a limitation on the number of rows that can be imported?

**Comment by davidiseminger** [comment]
There may be limitations to the rows, or the server itself may time out on the query. And overall, this looks like a support request rather than documentation feedback - and you'd likely get quicker answers using our support channels. You might also find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
