### ISSUE TITLE
Microsoft.IdentityModel.Clients.ActiveDirectory is deprecated

### ISSUE THREAD

**Issue by ADefWebserver** [MicrosoftDocs/powerbi-docs#3361]
[Microsoft.IdentityModel.Clients.ActiveDirectory is deprecated](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363)

People should use the example code here:
https://github.com/microsoft/PowerBI-Developer-Samples/tree/e8c98408b43b744f86d04079be69676fa3ec5d3b/.NET%20Core/Embed%20for%20your%20customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fb3418-db2e-54a1-9faa-7ba09c5259dc
* Version Independent ID: 87329ec8-d7d4-f66a-0562-13a9b6032543
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/automation/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/automation/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @ADefWebserver,

Thank you for your comment.

The entire [push data into a dataset](https://docs.microsoft.com/power-bi/developer/automation/walkthrough-push-data) tutorial  is old, and requires a refresh. Unfortunately this refers to the entire code in all the articles that are part of this tutorial.

I'm planning to either update or remove these articles but this may take some time. In the meantime, I'm happy that you found a solution.

Thanks,

Kesem
