### ISSUE TITLE
Webinar Downloads

### ISSUE THREAD

**Issue by bgdszepesi** [MicrosoftDocs/powerbi-docs#3362]
Can you provide a direct download for webinars that have passed?  I'd like to use the Power BI modeling webinar for training with my team without having to go through registration/getting an invite, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9a082e6-1c36-af62-95b7-69405696764e
* Version Independent ID: 0425ef3a-54b6-3527-6a02-a60642c9d61c
* Content: [Power BI webinars - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/webinars)
* Content Source: [powerbi-docs/fundamentals/webinars.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/webinars.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
@bgdszepesi - thanks for the feedback - I'll check with the team that supports webinars to see if it's possible to modify the URL to bypass the registration. If so, we'll update the links.

**Comment by kfollis** [comment]
@bdgszepesi - unfortunately we are unable to provide a direct link to the Power BI webinars that bypasses registration. However, we do have free online learning available, such as this course on data modeling: https://docs.microsoft.com/en-us/learn/paths/model-power-bi/. I will close this issue now, as it's not related to the documentation. Thank you for providing feedback!
