### ISSUE TITLE
Emissions Impact Dashboard Power BI report - Data are not updated

### ISSUE THREAD

**Issue by AlonEkelund** [MicrosoftDocs/powerbi-docs#3366]
I followed the instruction on the documentation page - https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard 

24 hours has passed and the report has run a refresh every day for the last couple of days. However I still see data from the demo report.  

I am getting no error? Please advice how and what can I do? 

Thanks

**Comment by paulinbar** [comment]
Hi @AlonEkelund, did your issue ever get resolved?

**Comment by AlonEkelund** [comment]
Unfortunately no. I still cannot get data into the report. It is a problem as I want this to work. This is a strategic matter for us

**Comment by paulinbar** [comment]
@AlonEkelund 

And in step 6 you put in the Billing account ID and in step 8 you logged in with the credentials which have access to the billing ID and has the permissions explained in the prerequisites, i.e. Power BI Pro license and an admin role with read/write permissions on the Azure tenant?

Sorry, just need to ask. I imagine you did this.

**Comment by paulinbar** [comment]
I am not familiar with the bit about the Azure benefit. Do you have any detail on how when you activate the benefit it changes your plan? What kinds of signs about that do you have?

**Comment by paulinbar** [comment]
Hi @AlonEkelund, I consulted with the product PM about what you wrote me, and they said that for this problem the best thing would be for you to open a support ticket at [support.powerbi.com](https://support.powerbi.com/) (I am a docs person). So I'm closing this github issue for now. If you find anything in the docs that needs improvement or clarification, please let us know. Anyway, sorry you've had to wait so long for this answer. I hope you manage to solve the problem!

**Comment by AlonEkelund** [comment]
> You asked. _step 6 you put in the Billing account ID and in step 8 you logged in with the credentials which have access to the billing ID and has the permissions explained in the prerequisites, i.e. Power BI Pro license and an admin role with read/write permissions on the Azure tenant?_ YES to all of that 

And I did open a ticket both on Power BI support and Azure support. I talked to both teams. Non could give me a solution. I am waiting for one og the teams to solve the problem OR to suggest an alternat way to get the data. 

I am guessing this is highly relevant for many other Microsoft Partners. At least it should be :-) I hoped some attention could be put on this matter and I am simply trying different angels and hoping some might have a solution.

Thank you

**Comment by paulinbar** [comment]
Hi @AlonEkelund, ok, thank you for that information. I will also let the product team know about that. I don't know if they'll be able to help, but at least they'll be informed.
Thanks again!
