### ISSUE TITLE
Tables reported in Gb instead of GB

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#3368]
The tables reporting the capacity limits for Power BI Premium are mentioning Gb instead of GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-what-is#power-bi-premium-generation-2)
* Content Source: [powerbi-docs/admin/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @djpirra,

Are you referring to the table in the [Capacity nodes](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#capacity-nodes) section?

If so, it seems to mention GB (not Gb):

![image](https://user-images.githubusercontent.com/54834915/141117314-b3d7cc84-d390-4f94-acb0-98c032c84707.png)

Thanks,

Kesem
