### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#3369]
The doc state the following: 

At the top of the page there's a multi-selection pivot allowing you to focus on refreshing Power BI item types (such as _**reports, dashboards, and datasets**_), successful or failed operations, metrics of interest (CPU, Processing time or number of operations) and the type of refresh performed. Each of these pivots filters all the visuals in the refresh page.

But when you open the app on this Page it only allows to select between Datasets and Dataflows. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f52eeb-717d-9a67-b775-c17c5cf916e4
* Version Independent ID: 2c804bb2-1cf3-462e-730b-ecfbae2a5e9e
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-gb/power-bi/admin/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/admin/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @prvillal,

Thanks for your comment, I'm looking into this issue and will get back to you shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @prvillal,

Is it possible that you only have datasets and dataflows on this capacity?

The app will only show you what you have on the capacity. If you don't have any other Power BI items (artifacts) on this capacity (such as reports), you'll not see them.

Let me know if this is the case or if yo have additional items on the capacity that can't be seen.

Thanks,

Kesem
