### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by arunrknt** [MicrosoftDocs/powerbi-docs#337]
Its not a feedback its a thanks for Microsoft, this is first time i got fulfilled in understanding by manual study in online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [Modeling - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/modeling?tutorial-step=8)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks so much, @arunrknt! Passing your comment on to the author.

**Comment by abhisrivastava2512015** [comment]
Thanks for this online Learning, I have never seen before such a great feature to analyze time-based data so easily. How Power BI Desktop automatically include generated fields that let us drill down through years, quarters, months, and days with a single click, it's Amazing.
Thanks Again to MSFT Team!!

**Comment by davidiseminger** [comment]
Thanks for your nice comments! Glad you enjoyed it, and hopefully we can keep creating great content that helps your online or data life be better!
