### ISSUE TITLE
Question about inconsistency in Dataflow licensing requirements 

### ISSUE THREAD

**Issue by tasmiaa** [MicrosoftDocs/powerbi-docs#3373]
Hi,

I'm a MSFT FTE, and am reaching out to understand why this document suggests that "Dataflows are supported for Power BI Pro, Premium Per User (PPU), and Power BI Premium user" whereas this other document has dataflows unchecked under Power BI Pro. (https://powerbi.microsoft.com/en-us/pricing/?ef_id=99152d3bfcf71ea2053c4c427702ab3f:G:s&OCID=AID2200053_SEM_99152d3bfcf71ea2053c4c427702ab3f:G:s&msclkid=99152d3bfcf71ea2053c4c427702ab3f).

Is dataflow a feature of PBI Pro or not? And why are the documents inconsistent? My MSFT account is tasmiaalam@microsoft.com.

Thanks,
Tasmia
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features#feedback)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @tasmiaa,

I'm checking this inconsistency and will get back to you soon.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @tasmiaa,

I can confirm that the [documentation page](https://docs.microsoft.com/power-bi/transform-model/dataflows/dataflows-premium-features) is correct.

We'll work to update the [pricing page](https://powerbi.microsoft.com/en-us/pricing/?ef_id=99152d3bfcf71ea2053c4c427702ab3f:G:s&OCID=AID2200053_SEM_99152d3bfcf71ea2053c4c427702ab3f:G:s&msclkid=99152d3bfcf71ea2053c4c427702ab3f) shortly.

Once again, thanks for your comment,

Kesem
