### ISSUE TITLE
Typo "wither" vs "either"

### ISSUE THREAD

**Issue by WilliamThinAirLabs** [MicrosoftDocs/powerbi-docs#3374]
wither -> either

Here:
`The two outer sides of the Venn diagram show the features that are unique to wither the Desktop application or to the Power BI service.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0ba6184-412b-7e75-ef74-46ae14d62dd6
* Version Independent ID: bf97c0bc-6511-e0f0-8df3-9e4f83492fe9
* Content: [Comparing Power BI Desktop and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop)
* Content Source: [powerbi-docs/fundamentals/service-service-vs-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/service-service-vs-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Thanks, @WilliamThinAirLabs -- good eye! Fixed now.
