### ISSUE TITLE
No information if the Autoscale also gives additional memory

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#3376]
Hi, There's no information if the additional VCores also comes with Additional RAM. Please make this more clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5331ed60-1d4a-dbef-1ec6-b9ca9de05e57
* Version Independent ID: bc5c01f8-67e1-6395-b079-12de4be557b0
* Content: [Using Autoscale with Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-auto-scale)
* Content Source: [powerbi-docs/admin/service-premium-auto-scale.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-auto-scale.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @erapade,

Thank you for your comment.

In Premium Gen1 memory was restricted to a limited amount of RAM used by all Power BI items running at the same time. However, in Premium Gen2 this restriction was removed. See the 4th bullet in [Limitations in Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-what-is#limitations-in-premium-gen2).

![image](https://user-images.githubusercontent.com/54834915/141109029-96c53453-f081-4214-b90d-b5d64d99e36a.png)

If you're using Gen1, VCores are tied to RAM (see table in [Capacity nodes](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#capacity-nodes)). If you're using Gen2 they're not.

Hope this helps,

Kesem
