### ISSUE TITLE
Visualization Error

### ISSUE THREAD

**Issue by hritik1233** [MicrosoftDocs/powerbi-docs#3377]
I see an error message "The visual is not supported." I've tried multiple combinations of fields. What does this error message mean and what can I do to troubleshoot it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by hritik1233** [comment]
Seems like moderators are not active

**Comment by mihart** [comment]
Thanks for your comment, @hritik1233 . This issue has been assigned to the doc author for review. You might get a quicker  answer by posting on the community forums community.powerbi.com.
