### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#338]
“Sometimes the best way to learn about data refresh in Power BI to look at examples.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for the close read! I've updated that, and will get it republished in the next day or so. Thanks!
