### ISSUE TITLE
Elaborate on this page

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3381]
Couple of suggestions:
1) Add a explanation of the use case of service tags vs using fixed IPs
2) Explain the distinction between PowerBI (datasets) and PowerQueryOnline (dataflows)
3) On this page explain that service tags can be used for other Azure resources other than just  Azure SQL Managed Instance (MI), at face value this doc looks to be only focused on Azure SQL Managed Instance with PBI, which I am sure is not the intention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 764df840-9c91-7535-20fd-eb4837d14add
* Version Independent ID: b498e7ce-7a63-e45a-72c0-7b88a1dc45e8
* Content: [Using service tags with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-service-tags)
* Content Source: [powerbi-docs/admin/service-premium-service-tags.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-service-tags.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by nathanwlee1** [comment]
@KesemSharabi

**Comment by mihart** [comment]
Thanks for your comment, @nathanwlee1 . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @nathanwlee1,

Thank you for your comment!

As we now have an email thread regarding your potential contribution to this page, I'm closing this GitHub issue.

Thanks,

Kesem
