### ISSUE TITLE
Feedback: Licensing PBI embedded vs Premium

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#3387]
It would be very helpful if there was a clear delineation of the licensing between Premium and Embedded on the FAQ page.   Additionally if we could find a way to differentiate the concept/act of embedding from the Embedded SKU (A SKU).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e37c7960-448a-0f10-c84a-f9c531452320
* Version Independent ID: 4867daee-c097-cde7-81c9-4f2a44a4f5b3
* Content: [Frequently asked questions about Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded/embedded-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embedded-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mihart** [comment]
Thanks for your comment, @rosscouldrey . This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your suggestion, @rosscouldrey. I added a link to the page that explains the differences between Embedded and Premium in greater detail.
As for the confusing terminology regarding embedding, that's beyond the scope of this article, but I'll pass it on.

https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-faq#what-is-the-microsoft-recommendation-for-when-a-customer-should-buy-power-bi-premium-vs--power-bi-embedded-

https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#which-sku-should-i-use
