### ISSUE TITLE
Word choice

### ISSUE THREAD

**Issue by bmartin-MHC** [MicrosoftDocs/powerbi-docs#3388]
[Enter feedback here]
under Embed for your Organization.

I prefer not to sing to login.

"Redirect URL - Upon singing in, ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dd93dd-c3a9-fccc-3a74-cebd6bf09067
* Version Independent ID: 0f61cf44-982a-1fcd-1396-4f3da8a40af2
* Content: [Register an app to embed Power BI content in a Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app?tabs=customers%2CAzure)
* Content Source: [powerbi-docs/developer/embedded/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/register-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for pointing that out, @bmartin-MHC. 
If you feel so strongly about it, you can sign in instead. 😄 
The corrected version will be published soon.
