### ISSUE TITLE
Power BI Embedded Gen 2  A SKU

### ISSUE THREAD

**Issue by v-maquay** [MicrosoftDocs/powerbi-docs#3389]
I currently have a customer trying to implement embedding a Paginated report in a SKU Gen 2.  Step 4 in this documentation is very confusing as Gen 2 does not have a Paginated capacity workload.
https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2  This document  states:   Lower entry level for paginated reports and AI workloads – Start with an A1 SKU and grow as you need.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53eef67-91ce-691f-5e29-515d553023f6
* Version Independent ID: f6723c69-a08d-42af-6a74-33f22bc55fba
* Content: [Embed paginated reports in your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/embedded/embed-paginated-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by maggiesMSFT** [comment]
Hi, @v-maquay -- thanks for your question! Assigning to the author to clarify.

**Comment by mberdugo** [comment]
@laurent-mic, @Alonbaram, can you help me out here? 
Does Gen2 have a paginated capacity workload?

Is this line true about gen2
_Lower entry level for paginated reports and AI workloads – Start with an A1 SKU and grow as you need._

**Comment by Alonbaram** [comment]
Hi
CIL
Tx
Alon

**Comment by v-maquay** [comment]
Hello Mona,

Please see this documentation:
Power BI Embedded Generation 2 explained as part of Power BI embedded analytics - Power BI | Microsoft Docs<https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2>

Cx currently testing.  Works for PDL not connected to PBI Dataset.  Working on connecting with XMLA endpoint to dataset.
Please see Tickets# 2110290040007300 and #2110220040007023

Respectfully,
Mary Quayle

***@***.******@***.***> | Support Engineer | Microsoft Business Intelligence
Email: | Manager: Asif Khatib ***@***.******@***.***>)
Hours: 9 AM - 6 PM | Time Zone:  PST (US & Canada) (UTC -08:00)

In case of any delay in response to your email or immediate assistance needed, kindly notify to the Operations Manager's team for immediate attention. ***@***.******@***.***>
Have an Idea?<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fideas.powerbi.com%2Fforums%2F265200-power-bi-ideas&data=04%7C01%7Cv-maquay%40microsoft.com%7C473ed02c2bb5474111e308d8d42e23f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637492641932419365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YAwKKAfsP3981whdhBsYoo5OP7alGLX8uqUWjQDwj9o%3D&reserved=0> | Find Experts Here<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcommunity.powerbi.com%2F&data=04%7C01%7Cv-maquay%40microsoft.com%7C473ed02c2bb5474111e308d8d42e23f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637492641932429363%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u1%2BbAFH1eD%2BIJz7BpxJCQQ6deuXnVWDcIwnaWRkULKI%3D&reserved=0> | Check Known Issues<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpowerbi.microsoft.com%2Fen-us%2Fsupport%2F&data=04%7C01%7Cv-maquay%40microsoft.com%7C473ed02c2bb5474111e308d8d42e23f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637492641932434365%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7U5tu2Vbrm2Gg8qRHV2cvoviP8yby6QPfkbGB45OzoY%3D&reserved=0> | Monthly Updates<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpowerbi.microsoft.com%2Fen-us%2Fblog%2F&data=04%7C01%7Cv-maquay%40microsoft.com%7C473ed02c2bb5474111e308d8d42e23f8%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637492641932444355%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hYgXeUzLaRGTstSTjIzhlAMe0b2CsAWJeRx7WxIAIrw%3D&reserved=0>

**Comment by mberdugo** [comment]
@laurent-mic and @Alonbaram 
Please see step 4 over here: (https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers#step-4---enable-paginated-reports-workload)

The Gen2 version does not have a paginated reports capacity option. 
How do you embed a paginated report for gen2?

**Comment by mberdugo** [comment]
@v-maquay, thank you for pointing out this problem. The documentation has been updated and should be live soon. In the meantime, just know that step 4 is only needed for Gen1 capacities. If you have Gen2, skip to step 5.
