### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#339]
The “overview page” link is going to the Power BI support page. Doesn’t seem right. Thanks

http://go.microsoft.com/fwlink/?LinkId=535031&clcid=0x409

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed468ec7-192b-8ad4-da13-fc3bca5c47b8
* Version Independent ID: a93614a9-2bda-3bb5-782b-ec75cd434105
* Content: [Azure and Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-and-power-bi)
* Content Source: [powerbi-docs/service-azure-and-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-and-power-bi.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by markingmyname** [comment]
@chrisweis Thank you for bringing this to our attention.  The link has been updated and will be live in about a couple of days.
