### ISSUE TITLE
Callout GCC

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#3390]
It is my understanding that GCC falls into the same timelines as commercial.  Can you call this out in the doc for visibility to GCC customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90047b5c-e241-2550-3a15-65ba1528c6d7
* Version Independent ID: 48523198-ea0e-68f4-6b3c-477b3c0d95af
* Content: [Plan your transition to Power BI Premium Gen2 - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-transition-gen1-to-gen2)
* Content Source: [powerbi-docs/admin/service-premium-transition-gen1-to-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-transition-gen1-to-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mberdugo** [comment]
Thanks for your comment, @elfohl . 
I've assigned this issue to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @elfohl,

Thanks for your comment. I'm checking this issue for you and will get back to you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @elfohl,

I added the [National cloud supportability](https://docs.microsoft.com/power-bi/admin/service-premium-transition-gen1-to-gen2#national-cloud-supportability) section to the [Plan your transition to Power BI Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-transition-gen1-to-gen2) article.

Once again, thank you for your comment and for getting involved.

Kesem
