### ISSUE TITLE
Bullet is unclear: "If Internet access is disabled, and if the dataset or dataflow is connecting to a Power BI dataset or dataflow as a data source, the connection will fail."

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3391]
This bullet is unclear: "If Internet access is disabled, and if the dataset or dataflow is connecting to a Power BI dataset or dataflow as a data source, the connection will fail."

Reasons it is unclear:
1. A dataflow can't connect to a Power BI dataset (can it?),
2. The tenant context is unclear (is this a dataset within the Power BI tenant connecting to a dataflow within the same Power BI tenant?  If so, why would that fail?)
3. The dataflow storage location context is unclear (does this apply to dataflows using the default Microsoft-hosted storage?  does it apply to dataflows we host in our own Azure storage?  what if the Azure storage is allowed through the private link?)

Hope this feedback is helpful, thanks!
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your comment, @chrisweis. 
I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback Chris. In the context of private links, I believe that limitation is accurate and clear. But if you'd like more clarification, your best venue for getting an answer or feedback is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
