### ISSUE TITLE
Capacity metrics app content is not up to date with the latest version. 

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#3392]
Hi team, 
The capacity metrics shown in the screenshot, including the descriptions in this documentation are not up to date with the latest version of the capacity metrics app people can download from AppSource. 

I would be happy to contribute if appreciated :) 
Thanks! 
--Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-monitor-capacity?WT.mc_id=DP-MVP-5003435&#feedback)
* Content Source: [powerbi-docs/admin/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @marclelijveld,

Thank you for your comment. The [Monitor Premium capacities with the app](https://docs.microsoft.com/power-bi/admin/service-admin-premium-monitor-capacity) article refers to the old metrics app which works with Premium Gen1. I'm planning to remove it once Gen2 becomes GA (and replaces Gen1).

To understand how to use the new app, please refer to  [Use the Gen2 metrics app](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-metrics-app).

Hope this helps,

Kesem
