### ISSUE TITLE
Review the up to date version of ODAC connector from 12.1 to 19

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3393]
In the documentation the link to install ODAC is version 12.1 whereas the latest version seems to be version 19. 
Can you confirm and update please? 

The documentation has a link to version 12.1 see "install the 64-bit ODAC software, go to 64-bit Oracle Data Access Components (12.1.0.2.4)" 64-bit Oracle Data Access Components (ODAC) for Windows
https://www.oracle.com/database/technologies/odac-downloads.html

However, a search shows that the latest is version 19.3 see here64-bit ODAC 19.3" ODAC Runtime Downloads (oracle.com)
https://www.oracle.com/database/technologies/dotnet-odacdeploy-downloads.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/connect-data/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your comment, @nathanwlee1. 
I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Hello @nathanwlee1 - the supported version of ODAC is maintained by the product team; we only update the docs once they confirm a change / update in supported versions. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
