### ISSUE TITLE
MPA Detail is misleading

### ISSUE THREAD

**Issue by joecarlyle** [MicrosoftDocs/powerbi-docs#3395]
The page outlines the support of MPA customers. However, this is misleading. An MPA customer cannot have a billing ID, this is at all times the Partners and includes all customers on the MPA.

So, this dashboard can be used by a partner, to view their MPA customers.

Not a customer on MPA to view the dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#finding-your-companys-billing-account-id-mcampa-csp-with-azure-plan-customers-only)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by davidiseminger** [comment]
Thanks for your comment, @joecarlyle . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by paulinbar** [comment]
Hi @joecarlyle , this article has been updated several times since you opened this issue. I am going to close it now, but if the document still seems in error, please reopen. Thanks!
