### ISSUE TITLE
goodef

### ISSUE THREAD

**Issue by RESHVANTHKS** [MicrosoftDocs/powerbi-docs#3398]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8da6c49a-f7cc-213c-adc3-5b33b76716dd
* Version Independent ID: 2be2786b-c764-c142-0821-24f6a28b2459
* Content: [Smart narratives tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-smart-narrative)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-smart-narrative.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualization-smart-narrative.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by davidiseminger** [comment]
Thanks for your comment about this article too, @RESHVANTHKS - if you'd like us to address any issues in the future, please make sure you include any details you believe need our attention. Thanks.
