### ISSUE TITLE
Technical Account Manager should be Customer Success Account Manager

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#3399]
We no longer refer to TAM, they are now CSAM - Customer Success Account Manager.  Please update to reference current terminology.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e778bb7-c4db-9318-96f6-acca18d414a1
* Version Independent ID: 4bb4e1dd-1ff4-4330-cb2f-8d8e2cc94042
* Content: [Power BI Pro and Power BI Premium support options - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-support-options#connect-with-support)
* Content Source: [powerbi-docs/admin/service-support-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-support-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the feedback @elfohl - this change has been committed and will publish later today. Did you know that you can make updates like this yourself and help streamline the process? Learn more at https://aka.ms/contribute.
