### ISSUE TITLE
Outdated information regarding SSO Capability with Power BI Gateway, Snowflake, and Power BI Service

### ISSUE THREAD

**Issue by nzregs-snowflake** [MicrosoftDocs/powerbi-docs#3400]
This page need to be updated to cater for the new capabilities of the Power BI On-Premises Gateway.

Specifically, this statement is now incorrect:
[Configuring a Dataset with AAD](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake#configuring-a-dataset-with-aad)

> Because of the way that Power BI works, SSO will only work when no data sources are run through the on-premises data 
gateway.

The newest release of the Power BI On-Premises Gateway does support AAD SSO passthrough. There is a new Power BI tenant setting that needs to be configured - "Azure AD Singe Sign-On (SSO) for Gateway.
[Announcing data gateway support for Single Sign-On (SSO) with Azure Active Directory](https://powerbi.microsoft.com/en-us/blog/announcing-data-gateway-support-for-single-sign-on-sso-with-azure-active-directory/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328a161c-b51e-05d1-c185-cb244547c3f3
* Version Independent ID: 0bef7bb0-541e-a74b-0f68-359690ae8b8e
* Content: [Connect to Snowflake with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/service-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @nzregs-snowflake -- thanks for bringing this to our attention! Assigned to the writer to investigate.

**Comment by nzregs-snowflake** [comment]
Thanks @maggiesMSFT !

**Comment by davidiseminger** [comment]
Great - thanks for bringing this to our attention @nzregs-snowflake. The article will be updated with the next Docs build. Thanks!
