### ISSUE TITLE
Incremental Refresh

### ISSUE THREAD

**Issue by SophieBok** [MicrosoftDocs/powerbi-docs#3401]
[Enter feedback here]

Hi, isn't the incremental refresh feature now available in Power BI pro as well? 
If yes, I think the purple box in this page about the incremental refresh should be edited!

Thanks, 
Sophie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4113f426-5c74-c68d-781b-be0bb9358db1
* Version Independent ID: 4ef47ef7-0502-4161-a43e-4eabc3545931
* Content: [Dataset modes in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand#feedback)
* Content Source: [powerbi-docs/connect-data/service-dataset-modes-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-dataset-modes-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @SophieBok . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point @SophieBok - I've updated that box, which will be reflected in the next Docs build. Thanks!
