### ISSUE TITLE
Power BI Theme Template repository link is outdated and should be updated.

### ISSUE THREAD

**Issue by MattRudy** [MicrosoftDocs/powerbi-docs#3402]
Section:
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#json-example-files

Documentation is pointing to an inactive repository, and the link should be updated to point to https://github.com/MattRudy/PowerBI-ThemeTemplates#readme

I'll submit a PR for this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MattRudy -- thanks! I'll close this and keep the PR open.
