### ISSUE TITLE
Hello,  my Version: 2.96.901.0 64-bit (August 2021) . I have created a calculated table. In Model view I want to cross filter it to another table.  When I specify 'both' in Edit relationship, then it will not show a double arrow in Model view. In fact it will always show 1 direction arrow in model view regardless of  crossfilter direction 'both' or 'single'. THis is the first time I am using calcualted tables. I have not encountered this issue with imported tables.

### ISSUE THREAD

**Issue by BennoRoemer** [MicrosoftDocs/powerbi-docs#3405]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a23f1335-bb33-544a-67da-006015cfc92f
* Version Independent ID: 3e1dc63e-f0ac-5201-c0a5-bc7e4ee30944
* Content: [Using calculated tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-calculated-tables)
* Content Source: [powerbi-docs/transform-model/desktop-calculated-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/desktop-calculated-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by BennoRoemer** [comment]
Update:..after saving the pibx file and opening it again the double arrows finally appear in model view. Using this relationship in a formular, it does not work, hence the result is wrong. Replacing the calculated table by an imported table, everything is fine again. So this calculated tables seem to be not working.

**Comment by mihart** [comment]
Thanks for your comment, @BennoRoemer . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
