### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by armely** [MicrosoftDocs/powerbi-docs#3406]
This section of the document is broken, the link goes to another page that doesn't have information.  

 See how admins enable pushing apps to end users in the Power BI admin portal article.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @armely -- thanks for the feedback! I'll check it out.

**Comment by maggiesMSFT** [comment]
Hi, @armely -- the link was/is going to the right section of the right article, but it didn't have much info. I've added a little more detail and a screen shot. Changes will be live tomorrow. Thanks!
