### ISSUE TITLE
Simple Typo :)

### ISSUE THREAD

**Issue by jjadta** [MicrosoftDocs/powerbi-docs#3407]
[Enter feedback here]

At the top of the page: "This article presents come common scenarios."

Should be: "This article presents some common scenarios."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d2d59d-b88b-17ac-a267-dba67a8fabde
* Version Independent ID: 657c22e2-56e9-468d-11bc-24622777adba
* Content: [Develop solutions with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @jjadta . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Simple indeed! Thanks for pointing that out @jjadta, it'll be fixed with the next build.
