### ISSUE TITLE
Prerequisites - admin role in Azure tenant

### ISSUE THREAD

**Issue by externalperjohanssoniig** [MicrosoftDocs/powerbi-docs#3408]
The following text is in section "Prerequisites":
_"An admin role with read/write permissions on your Azure tenant. If you don't have such permissions, contact an Azure admin who has read/write permissions."_

Can you clarify in more detail what permissions are needed? Can any Azure AD Built-in roles be used to give sufficient permissions?
Why are Write permissions needed? That seems much for connecting to read the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by paulinbar** [comment]
Hi @externalperjohanssoniig , this article has been updated several times since you opened this issue. I am going to close it now, but if the document still seems in error, please reopen. Thanks!

**Comment by krupapavurala** [comment]
Nice Article!

Thanks for sharing with us 🙂

<a href="https://azuretrainings.in/azure-devops-interview-questions/">Azure Devops Interview Questions </a>
