### ISSUE TITLE
Prerequisites - Enrollment permissions 

### ISSUE THREAD

**Issue by externalperjohanssoniig** [MicrosoftDocs/powerbi-docs#3409]
The following text is in section "Prerequisites":
_"If you have an EA Direct account, you must be an Enrollment Administrator with read/write permissions..."_

Should not Read permissions in the Enrollment should be sufficient? Please confirm and update documentation.
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/understand-ea-roles

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#prerequisites)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @externalperjohanssoniig.

I've assigned this issue to the doc author for review.

**Comment by rosode** [comment]
Yes read or write access does work as long as they are EA admin.

Thanks!

Robin Smith
she/her
PRINCIPAL PROGRAM MANAGER
Sustainable Supply Chain
Mobile: +12064091313
***@***.******@***.***>

[Microsoft Logo]

**Comment by paulinbar** [comment]
Hi @externalperjohanssoniig, I've update the doc in accordance with your comment. The updated doc will be online in a day or two. Thanks for providing your feedback on all these issues!

**Comment by externalperjohanssoniig** [comment]
Hi paulinbar, the doc is still not updated.

**Comment by paulinbar** [comment]
Hi @externalperjohanssoniig, strange, I made that change... I'll check out what's going on. Thanks for calling it to my attention!
