### ISSUE TITLE
Log Analytics Integration

### ISSUE THREAD

**Issue by alohaninja** [MicrosoftDocs/powerbi-docs#341]
Are there any plans to integrate this content pack with Log Analytics instead of Azure Storage? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe108af-9a54-8fc1-ff18-7b9d141576eb
* Version Independent ID: 5ee0a5fc-b99f-4624-1c76-f924c4a2a80e
* Content: [Connect to Azure Search with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-search)
* Content Source: [powerbi-docs/service-connect-to-azure-search.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-search.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi @alohaninja -- Thanks for your question. We've assigned it to the author. In the meantime, check this Release Notes article for upcoming features https://docs.microsoft.com/en-us/business-applications-release-notes/October18/intelligence-platform/planned-features
Thanks!

**Comment by SarinaJoan** [comment]
Hi @alohaninja - have you looked at [Azure Audit Logs](https://appsource.microsoft.com/en-us/product/power-bi/37658b17-1e1f-4a5a-8e88-00720ad16b99) or [Application Insights](https://appsource.microsoft.com/en-us/product/power-bi/e08c8ffb-a216-40d5-a909-616c71e66176)?

**Comment by mimig1** [comment]
@maggiesMSFT @mgblythe - There has been no response from the user, and Sarina has provided follow up action. Can you close this?
