### ISSUE TITLE
FAQ - error connecting to data

### ISSUE THREAD

**Issue by externalperjohanssoniig** [MicrosoftDocs/powerbi-docs#3410]
The following text is in section "FAQ":
_"I’m receiving an error at the time of connecting my data with the dashboard. What can I do?
First, check in Azure Cost Management that you have IT Admin privileges."_

Can you give more details what "IT Admin privileges" is? 
Is it sufficient if the account that will be used for connecting to the data can read information in Cost Management?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @externalperjohanssoniig.

I've assigned this issue to the doc author for review.

<I sometimes add this to product question ones> In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by paulinbar** [comment]
Hi @externalperjohanssoniig , this article has been updated several times since you opened this issue. I am going to close it now, but if the document still seems in error, please reopen. Thanks!
