### ISSUE TITLE
FAQ - request to add additional troubleshooting information

### ISSUE THREAD

**Issue by externalperjohanssoniig** [MicrosoftDocs/powerbi-docs#3411]
Can you add additional troubleshooting steps for scenarios where the Prerequisites seem to be fulfilled, but there are still errors when processing the data in the dataset? 
Example: _"The credentials provided for the Web source are invalid."_ even when the logon is successful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by paulinbar** [comment]
Hi @externalperjohanssoniig , this article has been updated several times since you opened this issue. I am going to close it now, but if the document still seems in error, please reopen. Thanks!
