### ISSUE TITLE
Please Make the download option work in more cases

### ISSUE THREAD

**Issue by frgaude** [MicrosoftDocs/powerbi-docs#3413]
There are too many limitations to this feature.

We need to be able to download a report to pbix in most of the cases listed in the "limitation" section:
* when originally created in the Power BI service
* after deployment (ALM).
* Power BI report based on a dataset in one workspace and publish to a different workspace
* Not just the original report. Any copy of the report.

The current limitation is really hampering our day-to-day work and I don't quite see the technical hurdles preventing these cases to be covered.

one typical example is a business user has built a set of reports online (because of the convenience and ease of doing so) and now wants the "experts" to integrate all he's done in a managed set of reports. -> everything has to be redone from scratch, which is very inefficient and time consuming.

thank you,
françois.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @frgaude.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
