### ISSUE TITLE
Confusion in terms

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#3415]
It is really confusing to read something like this: "There's a one-million-row limit for cloud sources ...". What do you mean by cloud sources? SQL server on another external IP - is this understood as cloud source? If not, then what is the limit for non-cloud sources? And why are we talking about any limits in Direct mode context? Don't you load 502 records at any one time? Would be very useful if this was clearly explained in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-use-directquery#limitations-of-directquery)
* Content Source: [powerbi-docs/connect-data/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @gvggvg, thanks for your feedback! I have forwarded it on to the doc author for further consideration.

**Comment by davidiseminger** [comment]
Sorry for any confusion, I've updated that sentence to hopefully provide more clarity.
