### ISSUE TITLE
Change the license requirements that only Power BI Pro works as well, thanks. 

### ISSUE THREAD

**Issue by Jas73** [MicrosoftDocs/powerbi-docs#3417]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e10c5f-20a6-7f7b-8d1b-a5a5a9cb8a98
* Version Independent ID: 938f0c5e-9584-de7a-c564-f4788e7b5b34
* Content: [Get started with goals in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-introduction#license-requirements)
* Content Source: [powerbi-docs/create-reports/service-goals-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-goals-introduction.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Jas73 -- I'll reach out to you directly. Thanks!
