### ISSUE TITLE
Mobile experience isn't currently available.

### ISSUE THREAD

**Issue by Jas73** [MicrosoftDocs/powerbi-docs#3418]
Hi,

Mobile experience isn't currently available: This is supported now according to me because when I test and use the PBI Mobile app from the public MS App store I can see the Goals tab when I'm connected to a demo tenant.

Thanks
 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4e10c5f-20a6-7f7b-8d1b-a5a5a9cb8a98
* Version Independent ID: 938f0c5e-9584-de7a-c564-f4788e7b5b34
* Content: [Get started with goals in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-introduction)
* Content Source: [powerbi-docs/create-reports/service-goals-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-goals-introduction.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Wow, @Jas73 -- we are on the same page! This is on my list of Things To Fix today! Thanks for letting me know it's important 😊

**Comment by maggiesMSFT** [comment]
Hi, @Jas73 -- done. Change will be live in about an hour.
Thanks!
