### ISSUE TITLE
Data from Azure Sustainability Dashboard available through api?

### ISSUE THREAD

**Issue by joeltorby** [MicrosoftDocs/powerbi-docs#3419]
Hi,

I wonder if the data behind the Azure Sustainability Dashboard is available though an API so that our internal systems can be integrated with the numbers presented here? 

/Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by paulinbar** [comment]
Thanks for your comment question @joeltorby.
@rosode, can you comment?

**Comment by paulinbar** [comment]
Hi @joeltorby.
I checked with the product team and they said that unfortunately that data isn't currently available through an API. It's in their backlog, but there isn't yet any firm idea about when they'll be able to provide that functionality.
I would suggest you go to https://ideas.powerbi.com/ideas/, and add this as an idea there that others can vote on. This might help move the API up in the priorities. If you search for "emissions" when you're in the Ideas site you'll see other ideas/requests that people have submitted in regard to the Emissions dashboard.
Thanks for reaching out to us!

**Comment by joeltorby** [comment]
Thanks for the help @paulinbar! Here is the idea: https://ideas.powerbi.com/ideas/idea/?ideaid=1f746d06-af72-ec11-b820-0003ff4569ae

If anyone out there is reading this, please give it an upvote!
