### ISSUE TITLE
Preformance

### ISSUE THREAD

**Issue by BarakAvrahami** [MicrosoftDocs/powerbi-docs#342]
[Enter feedback here]

Hello,
I would like to understand what will be the preformance delta in the new M:M VS using a star schema model with a key_table the middle.
Wont it be less efficient to have this snowflak model instead of a star model ?
I would wonder why not the have a feature that creates a star schema for you--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477d54a5-8a27-ae63-9887-9801639962e8
* Version Independent ID: 8a2c56c0-cf25-bd2d-8de9-207ccc1e83d1
* Content: [Many-to-many relationships in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-many-to-many-relationships)
* Content Source: [powerbi-docs/desktop-many-to-many-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-many-to-many-relationships.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @BarakAvrahami. We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your question, @BarakAvrahami.  Note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
