### ISSUE TITLE
This document does not list any limitations regarding supported/unsupported list configurations

### ISSUE THREAD

**Issue by angoo-atea** [MicrosoftDocs/powerbi-docs#3420]
I'm trying this on a large list (over 5000 objects). The list also has a large number of columns (see below).
The initiation in PowerBI fails with a generic error.

This document does not list any limitations regarding supported/unsupported list configurations. For example the number of items or the types of columns.

----------------------------------------------------------
_Column  | Type_
Affärsområde | Choice
Anbud   inom LOU eller LUF | Yes/No
Anbud   lämnas in som | Choice
Anbudsansvarig | Person or Group
Anbudsbeskrivning | Multiple lines of text
Anbudsdeltagare | Person or Group
Anbudsnamn | Single line of text
Anbudsnummer | Single line of text
Anbudsstatus | Choice
Anbudssumma | Currency
Avdelning. | Managed Metadata
Befintligt   ramavtal | Lookup
Belägenhetsadress | Multiple lines of text
bjeNummer | Single line of text
Created | Date and Time
Enhet | Managed Metadata
Enhet | Managed Metadata
Ersättningsform | Choice
Fastighetsbeteckning | Multiple lines of text
Frågedatum | Date and Time
Förfrågan   kommer från | Choice
Galler   förfragan | Choice
ID_Val | Number
Inlämningsdatum | Date and Time
Kommun | Managed Metadata
Kontaktperson | Single line of text
Kund | Single line of text
Kundadress | Single line of text
KundKontaktEpost | Single line of text
Kundort | Single line of text
Modified | Date and Time
Organisatoriska   grupper | Managed Metadata
Processtatus | Single line of text
Ramavtal | Yes/No
Teams | Hyperlink or Picture
Uppdragsbeskrivning | Multiple lines of text
Uppdragsdeltagare | Person or Group
Utfall | Choice
Utfallskommentar | Multiple lines of text
Utfallsorsak | Choice
Webbplats | Hyperlink or Picture
År | Single line of text
Skapad   av | Person or Group
Ändrad   av | Person or Group
----------------------------------------------------------

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @angoo-atea -- good question! I'll investigate and report back.

**Comment by maggiesMSFT** [comment]
Hi, @angoo-atea -- got somewhat of an answer for you. The product team says:
"There is no limitation as such but with huge amounts of data – we have seen timeouts happening because the data ingestion is very slow."
And they suggest opening a support case so they can debug: https://powerbi.microsoft.com/en-us/support/
Hope that helps!

**Comment by angoo-atea** [comment]
@maggiesMSFT - thanks for following up. Parallel to this I did open a support case, the answer was that large lists are not supported. The page should be updated accordingly.

**Comment by maggiesMSFT** [comment]
Hi, @angoo-atea -- I checked with the product team again, and I've added this sentence to the Considerations section:
- Very large lists may be slow or may time out altogether.
Thanks!
