### ISSUE TITLE
Button Action property not found on the new Format Pane

### ISSUE THREAD

**Issue by douglasdebrito** [MicrosoftDocs/powerbi-docs#3421]
Hi there,

Where in the new Format Pane I can configure the Action property of a button to assign it to a Bookmark or Page Navigation for instance ?

Thanks,

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @douglasdebrito.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @douglasdebrito -- good point! Those aren't currently available, but will be in the December release. I'm adding this to a Considerations and Limitations section of the article.
