### ISSUE TITLE
CategoryColumn typo

### ISSUE THREAD

**Issue by maddogmikeb** [MicrosoftDocs/powerbi-docs#3423]
[Enter feedback here]

First one is "SampleBarChartData.ColumnCategory," should be "SampleBarChartData.CategoryColumn,"

To get the demo to work took a long time, simply following the steps was not enough. Perhaps the whole page needs a review as karma updates have changed some things. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e31ebbc-e248-fc7f-24cf-6e5e9ae04eef
* Version Independent ID: 85ba273c-34bf-bb77-ff62-a9bfc454c63f
* Content: [Introduction to unit tests for Power BI visual projects - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/unit-tests-introduction)
* Content Source: [powerbi-docs/developer/visuals/unit-tests-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/developer/visuals/unit-tests-introduction.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by paulinbar** [comment]
Hi @maddogmikeb, thanks for pointing out the typo and for your other feedback about the page. I am forwarding your comments on to the article owner for consideration.

**Comment by mberdugo** [comment]
Thank you, @maddogmikeb, for your feedback. I fixed the typo, and will work on updating the document.
@uve, who can help me update this article?

**Comment by mberdugo** [comment]
This tutorial has been updated and will be published in the next few days.
https://docs.microsoft.com/power-bi/developer/visuals/unit-tests-introduction
