### ISSUE TITLE
Can't find the "Action" option in buttons. (Can't change the URL it was pointing to)

### ISSUE THREAD

**Issue by zapppsr** [MicrosoftDocs/powerbi-docs#3424]
[Can't find the "Action" option in buttons. (Can't change the URL it was pointing to)
With the release of the New Format Pane, I cant change the action of a button.
Had to revert to the current Format Pane to change it.
]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop - Power BI](https://docs.microsoft.com/pt-br/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @zapppsr -- good point! Those aren't currently available, but will be in the December release. I've added this to a Considerations and Limitations section of the article. The update will be live this afternoon.
