### ISSUE TITLE
Issue when connecting data, followed steps in document

### ISSUE THREAD

**Issue by jonnunez** [MicrosoftDocs/powerbi-docs#3425]
While trying to follow the instructions in the document, I get this error message when I click Sign-In.

I used OAuth2 and entered my credentials. I am the admin in the project online site so I don't think it could be related to permissions?

![image](https://user-images.githubusercontent.com/56936337/142444634-87155431-42f3-463a-aa6e-354c6b42cb8a.png)

Any help is appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ecdd014-b4d0-e97b-78a6-ef22e71d05f8
* Version Independent ID: 0bea8666-c1e3-74ec-d805-c9925baa9999
* Content: [Connect to Project Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-project-online)
* Content Source: [powerbi-docs/connect-data/service-connect-to-project-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-connect-to-project-online.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
@teddybercovitz, do you have any idea why this might be happening? Thanks,

**Comment by teddybercovitz** [comment]
I recommend opening a support ticket. Note that there are 2 Project apps: Microsoft Project Web App<https://appsource.microsoft.com/en-US/product/power-bi/pbi_msprojectonline.pbi-microsoftprojectwebapp> & Microsoft Project for the Web<https://appsource.microsoft.com/en-US/product/power-bi/microsoftcorporation1619756240314.pbi_msprojectfortheweb>. For "Project web app" I Also recommend download the pbit file (GitHub - OfficeDev/Project-Power-BI-Templates: Expand Project with a Power BI Template<https://github.com/OfficeDev/Project-Power-BI-Templates>) and see if that yield better results.

________________________________

**Comment by paulinbar** [comment]
Hi @jonnunez, if what Teddy suggests doesn't work, then please try open a support ticket. Thanks.
[support page](https://support.powerbi.com)


![image](https://user-images.githubusercontent.com/54644589/147403127-371d5e05-ea79-4256-aecc-63a0c9befa15.png)
