### ISSUE TITLE
"Business user" versus "consumer"

### ISSUE THREAD

**Issue by rsbuckles** [MicrosoftDocs/powerbi-docs#3426]
This page seems to be all about defining what a "business user" is, to the point of italicizing the term.  Yet, a completely different term "consumer" is used in the bread crumb and the contents tree.  I find it confusing.  it seems like a page setting out a definition should pick one term and stick to it.

![image](https://user-images.githubusercontent.com/51032818/142519497-10d5dbb2-e15f-49f5-9d7e-67e08347af3c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0687089d-b79d-c566-35a5-9a03498cc168
* Version Independent ID: 30699f15-ec7a-6f19-9f86-99316656c099
* Content: [What is a Power BI 'business user'? - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-consumer)
* Content Source: [powerbi-docs/consumer/end-user-consumer.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/consumer/end-user-consumer.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @rsbuckles, thanks for your feedback!  Good points! I am forwarding along to the author of the article.

**Comment by mihart** [comment]
Hi @rsbuckles , 
Thank you for your suggestion.  You are absolutely right!  We've made updates and set the TOC to republish.  For the breadcrumbs, unfortunately, we can't change the actual file names. I'm hoping that having "consumer" and "end user" as part of file names and having "business user" within the articles, no matter how a customer searches for this content, they will find it. 
All the best,
The DOCS team
