### ISSUE TITLE
Dataverse support for datasource rules

### ISSUE THREAD

**Issue by ashlega** [MicrosoftDocs/powerbi-docs#3428]
"Dataverse" is not mentioned in the list of supported datasources (for the rules), so I am wondering what's the story there. 

We had somewhat strange experience:

- We used to be able to define rules for Dataverse datasource back in the beginning of September
- This this feature broke and we had a support case which lasted for about a month
- Where we were told Dataverse is not a supported datasource (for the pipeline rules)
- However, on the same day, it started to work again (and it works at the moment)

So would it be supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b120d7-3f8f-8bc7-2987-21dbf1090ff2
* Version Independent ID: 6456d67d-cab6-01e1-3654-4848c5058253
* Content: [Get started using deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#supported-data-sources-for-dataflow-and-dataset-rules)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/deployment-pipelines-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @ashlega, thanks for your question! I am forwarding it on to the author of the article for clarification.

**Comment by KesemSharabi** [comment]
Hi @ashlega,

As per the email discussion you're having with the PM regarding this matter, I'm closing this GitHub issue.

Thanks,

Kesem
