### ISSUE TITLE
Using powerbi on android applications 

### ISSUE THREAD

**Issue by elimuhub7407** [MicrosoftDocs/powerbi-docs#3429]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 307efcd2-4f18-db8e-65fe-0dde7438bd45
* Version Independent ID: f503642c-c452-98bf-4da3-cc13d94dde8a
* Content: [Power BI get started with third-party apps - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-power-bi-get-started-third-party-apps)
* Content Source: [powerbi-docs/collaborate-share/service-power-bi-get-started-third-party-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-power-bi-get-started-third-party-apps.md/chrome)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @Elimuhub7407
* Microsoft Alias: **elimuhub**

**Comment by paulinbar** [comment]
Hi @elimuhub7407, thanks for reaching out to us. You've reached the documentation team. Did you have a documentation related question about the page you are referring to?

**Comment by paulinbar** [comment]
Hi @elimuhub7407,
I haven't heard back from you in quite a while about what your issue/question about the document you referred to is, so in the meantime I am closing this issue. If your question/comment is still relevant, please feel free to reopen the issue and to provide more detail. Thanks!
