### ISSUE TITLE
Gen 2 Premium supports more workloads than Gen 1 - doc table is misleading

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/powerbi-docs#3430]
Current documentation here hints that some workloads are not supported in some som SKU's for all premium, but this is no longer true for Gen 2. We should add a disclaimer that in gen 2 they are supported, even though memory cant be changed:

![image](https://user-images.githubusercontent.com/45423022/142869922-749bbee0-29bf-437e-8c9f-7fe45d8ff9a6.png)

Example. Paginated Reports are supported on A1 now: https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is#paginated-reports-and-premium-gen2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-workloads)
* Content Source: [powerbi-docs/admin/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @martaequintao, thanks for the feedback! I am forwarding your comment along to the doc owner for consideration.

**Comment by KesemSharabi** [comment]
Hi @martaequintao,

Thank you for your comment and for getting involved. Following your suggestion, I updated the note below the table in [Default memory settings](https://docs.microsoft.com/power-bi/admin/service-admin-premium-workloads#default-memory-settings), to indicate that all the workloads are supported in Gen2.

![image](https://user-images.githubusercontent.com/54834915/144440194-9c6bc570-999e-4e4c-a803-a6c16df20c47.png)

Once again, thanks for pointing this out.

Kesem
