### ISSUE TITLE
Who authored this app? It is way too slow!

### ISSUE THREAD

**Issue by b77uw771b** [MicrosoftDocs/powerbi-docs#3431]
Maybe the wrong place for this feedback, but somebody needs to urgently do something about the performance of this app. Cannot believe you GA'ed GEN2 with the monitoring capability in this shameful state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f52eeb-717d-9a67-b775-c17c5cf916e4
* Version Independent ID: 2c804bb2-1cf3-462e-730b-ecfbae2a5e9e
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/admin/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @b77uw771b -- right you are, this isn't the best place for this feedback! Please submit it at https://ideas.powerbi.com/ideas/.

thanks!
