### ISSUE TITLE
Possible orphan pages

### ISSUE THREAD

**Issue by rsbuckles** [MicrosoftDocs/powerbi-docs#3433]
I was browsing through the "Connect to data" section of the documentation and noticed that these two pages are not listed in the contents tree to the left.  I.e., if you visit these pages, there is no highlight in the tree indicating where the page is "located" in the section. I am assuming each page is supposed to be listed in the tree, but if I am wrong, please disregard.

https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-understand

https://docs.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24819f2f-72da-f727-d7cd-4a3cf3cac3e4
* Version Independent ID: 560c2ca3-76d5-d269-f4fe-b3b6a0555301
* Content: [Datasets in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-understand)
* Content Source: [powerbi-docs/connect-data/service-datasets-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @rsbuckles, thanks for noticing this! I am forwarding your comment on to the article owner for consideration.

**Comment by davidiseminger** [comment]
You're right - they aren't in the TOC. I've updated the TOC to add them. Thanks for pointing this out @rsbuckles.
