### ISSUE TITLE
DC-installation fails

### ISSUE THREAD

**Issue by mortenf** [MicrosoftDocs/powerbi-docs#3434]
When following directions, DC-installation fails - and client tools etc. are missing:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'InstallDomainController'. Error message: \"DSC Configuration 'CreateADPDC' completed with error(s). Following are the first few: WinRM cannot process the request. The following error with errorcode 0x80090350 occurred while using Negotiate authentication: An unknown security error occurred. \r\n Possible causes are:\r\n -The user name or password specified are invalid.\r\n -Kerberos is used when no authentication method and no user name are specified.\r\n -Kerberos accepts domain user names, but not local user names.\r\n -The Service Principal Name (SPN) for the remote computer name and port does not exist.\r\n -The client and remote computers are in different domains and there is no trust between the two domains.\r\n After checking for the above issues, try the following:\r\n -Check the Event Viewer for events related to authentication.\r\n -Change the authentication method; add the destination computer to the WinRM TrustedHosts configuration setting or use HTTPS transport.\r\n Note that computers in the TrustedHosts list might not be authenticated.\r\n -For more information about WinRM configuration, run the following command: winrm help config.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "}]}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7c7b5d6-c9a4-3445-81c1-41dc41ae0929
* Version Independent ID: a45e9b8a-185b-ff29-dc4a-b8912c13ed1b
* Content: [Tutorial: Explore Power BI Report Server in a VM - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/tutorial-explore-report-server-web-portal)
* Content Source: [powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/tutorial-explore-report-server-web-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @mortenf. You've reached the documentation team, and I think your question is more of a support request or product question than it is documentation feedback. You might find a solution asking in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com). Thanks!
