### ISSUE TITLE
Missing content in Power BI Developer in a Day course

### ISSUE THREAD

**Issue by ShankerISE** [MicrosoftDocs/powerbi-docs#3437]
Missing module videos for Model 6(2 and 3), Module 7 and Module 8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5729783-cd4b-9bcc-1059-aeb3d2cb3c57
* Version Independent ID: c2f8f67e-907d-cfa4-5cbe-ad546694a44f
* Content: [Power BI Developer in a Day course - Power BI](https://docs.microsoft.com/en-us/power-bi/learning-catalog/developer-online-course)
* Content Source: [powerbi-docs/learning-catalog/developer-online-course.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/learning-catalog/developer-online-course.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by mihart** [comment]
Thanks for your comment, @ShankerISE . This issue has been assigned to the doc author for review.

**Comment by YanaBerkovich** [comment]
Hi, 
"In a day" content can be found here:
https://aka.ms/pbitraining 
For dev in a day content:
https://aka.ms/DevIAD_instructor 
https://aka.ms/DevIAD_Student

Video's are out of scope for this training course, the content was updated however there are no current plans to update the videos.

**Comment by peter-myers** [comment]
Hi @ShankerISE - the videos are being released three at a time. By tomorrow, the full course of 21 videos should be available. Thanks for your patience. #please-close

**Comment by YanaBerkovich** [comment]
Thank you Peter!

Yana

**Comment by jsumosa** [comment]
Thank you, this is a great resource!

After searching for some time, I could not find links to the web application example. As a developer, it would be very valuable for me to have access to the sample code to better understand its implementation 😃
