### ISSUE TITLE
ideas for visual

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3438]
Since this visual's development status is still in "preview", where should feedback and ideas be directed?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rootsmusic.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi again @rootsmusic , 
Thank you for your question.  You can still submit ideas using ideas.microsoft.com and questions to community.powerbi.com.  
All the best,
The DOCS team
