### ISSUE TITLE
ideas link

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3439]
Under "Get Help", it says: "If you have a suggestion for an improvement, please submit it to Power BI's ideas list."  Since this visual is owned by ESRI, shouldn't that sentence link to the visual's [ideas community](https://community.esri.com/t5/arcgis-for-power-bi-ideas/idb-p/arcgis-for-power-bi-ideas)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Interacting with an ArcGIS map that has been shared with you - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rootsmusic.

I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @rootsmusic , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
