### ISSUE TITLE
Typo for BI to PI

### ISSUE THREAD

**Issue by zmiftah** [MicrosoftDocs/powerbi-docs#3440]
In What’s supported? section, there is a little typo, it should be "Power BI Desktop" not "Power PI Desktop".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset from OneDrive or SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-desktop-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @zmiftah,

Thank you for your comment. I fixed this typo and the fix will be live tomorrow.

Thanks again for pointing this out,

Kesem
