### ISSUE TITLE
Position Properties 

### ISSUE THREAD

**Issue by asocorrocognex** [MicrosoftDocs/powerbi-docs#3441]
It would be nice to have the Properties-> Position box open automatically.  Before, I needed only one click to get to the X-Y values.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane#considerations-and-limitations)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mberdugo** [comment]
Thanks for your comment, @asocorrocognex. 
This looks like product feedback rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

**Comment by maggiesMSFT** [comment]
Hi, @asocorrocognex -- is this Adolfo? If so, another Hello! 
Yes, as @mberdugo says, this looks like product feedback, so I'm closing this issue. The product group is eager to get feedback on this feature, so please go and enter it at https://ideas.powerbi.com/ideas/.
cheers!
