### ISSUE TITLE
Support for Internet Explorer text is inconsistent

### ISSUE THREAD

**Issue by Piquet65** [MicrosoftDocs/powerbi-docs#3442]
This document page states (correctly) that Internet Explorer 11 is no longer support by Power BI Report Server, however in the subsequent lists of supported browsers on this page Internet Explorer 11 is still listed as a supported browser.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318a843c-3fb6-2ba7-ff3f-a9836a9911ca
* Version Independent ID: 351db014-a769-e7c6-a860-9bfd4e4526ea
* Content: [Browser support for Power BI Report Server - Power BI](https://docs.microsoft.com/en-au/power-bi/report-server/browser-support#feedback)
* Content Source: [powerbi-docs/report-server/browser-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/browser-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @Piquet65, thanks for calling our attention to this. I am forwarding your comment along to the article owner.

**Comment by maggiesMSFT** [comment]
Great point, @Piquet65 ! Deleting it now. Change will be live tomorrow afternoon Jan 4, 2022 Pacific time.
