### ISSUE TITLE
Duplicate and typo about data source list for PBI Desktop

### ISSUE THREAD

**Issue by kuwazzy** [MicrosoftDocs/powerbi-docs#3443]
[Enter feedback here]

Page : https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources

Here are duplicate and typo about data source list for Power BI desktop.

**Duplicate**

- Bloomberg Data and Analytics
- Exasol
- Azure Time Series Insights

**Typo**

- TIBDO(R) Data Virtualization -> TIBCO(R) Data Virtualization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @kuwazzy, thanks for pointing this out. I am forwarding your comment along to the doc owner for further consideration. Thanks!

**Comment by davidiseminger** [comment]
This is a good catch @kuwazzy -- thanks for pointing this out. I found a few more corrections (updates) in there, and made those too. Thanks for the close read, and importantly, for letting us know!
