### ISSUE TITLE
 "Alt text" not available in PBI Desktop

### ISSUE THREAD

**Issue by embeau** [MicrosoftDocs/powerbi-docs#3444]
Hi ! 

It's seems that the "Alt text" option is not anymore available in the last Power BI Desktop version :  

<img width="603" alt="image" src="https://user-images.githubusercontent.com/16632652/143592772-e6ee2572-ae69-4f7b-b25b-1c85f065d073.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 762701ab-7066-612d-cdc2-a729ba1b5483
* Version Independent ID: 8a64d563-9737-16d3-d83e-fb56e8d3d95c
* Content: [Creating accessible reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-creating-reports)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-accessibility-creating-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @embeau, thanks for reaching out. Can you tell me which version of Desktop you're using? I have Version: 2.100.261.0 64-bit (December 2021) installed and I do see Alt text down there as one of the Responsive properties.

**Comment by paulinbar** [comment]
I'm wondering if there is some other factor that's causing it not to show up for you.

**Comment by paulinbar** [comment]
Hi @embeau,
I tried again with this version (2.100.785.0 64-bit (December 2021)), and I still see the alt text box. Have you tried the current version? In the meantime I am closing this issue, but if you have the current version and still don't see the alt text field, please open this issue again. Thanks!

![image](https://user-images.githubusercontent.com/54644589/147226920-1a95a276-790e-42ed-bebc-aa1768a3dab1.png)
