### ISSUE TITLE
You can use parameters in Dataflows but you cannot edit them unless you edit the entire dataflow

### ISSUE THREAD

**Issue by mitchonfire** [MicrosoftDocs/powerbi-docs#3447]
One of the major functions of a "parameter" in general is that it is a variable one can change and pass into the object expecting the parameter.

In the case of Power BI Dataflows, the parameters behave like declared constants and nothing more, you cannot change the value passed into the dataflow when it refreshes.
What is the point?

You might want to list this as a limitation?

**Comment by paulinbar** [comment]
Hi @mitchonfire, thanks for your comment. You've reached the doc team. Can you send us a reference to the article that you had in mind? Thanks.

**Comment by mitchonfire** [comment]
Hi Paul, apologies. I assumed my comment to have already been against the
applicable article.

Anyway, it is this one:
https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations

Thanks for the quick response.

Regards
Duncan Mitchell

**Comment by paulinbar** [comment]
@mitchonfire 
Hi Duncan, thanks for providing the reference.
Your point is a good one, and I am forwarding your comment on to the writer who owns the dataflow documentation.
On another note, can you tell me how you first submitted your comment? Usually the article reference IS included in the github issue submission, so I'm curious if you recall where you clicked in order to open the github issue... perhaps something needs to be fixed there in that mechanism. 
Again, thanks for contacting us!
Regards, 
Paul

**Comment by davidiseminger** [comment]
Seems like a good addition to me - thanks for the comment @mitchonfire, I'll add that clarification to the article, should show up in the next day or two. Thanks!

**Comment by mitchonfire** [comment]
Awesome guys, nice to see such a swift and positive response.

I have another limitation to mention, for the Dataflows (same doc)

Editing Datasource Credentials is not possible after initially setting
them, and in some scenarios the only way around this is to completely
recreate the Dataflow.
e.g. if you use Web.Contents() you will be prompted to specify "how to
connect", and perhaps you choose org account or basic authentication, but
then realise you have to use a token in the headers and connect
anonymously, when this happens you either have to change the base url
slightly to get prompted again as the datasource is detected as new, or you
have to start development of the dataflow again from a point before you
specified the initial auth.

You may need to come up with some better wording on this, sorry, but I hope
the above explains the problem.

Regards
Duncan
