### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#3448]
This UI is no longer available in Gen2, can you provide guidance as to customer expectations and if this will no longer be available to provide that guidance in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a289bc1e-c396-684c-4679-fbf5cde575f5
* Version Independent ID: 07e05427-08d7-5922-bf2e-f2a0d4166b02
* Content: [Monitor Power BI Premium capacities by using the admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-monitor-portal#feedback)
* Content Source: [powerbi-docs/admin/service-admin-premium-monitor-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-premium-monitor-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @itsnotaboutthecell -- I've assigned this issue to the author for consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @itsnotaboutthecell,

I'm closing this GitHub issue as the discussion moved to email.

Thanks,

Kesem
