### ISSUE TITLE
Configure and use data refresh - Step 5 Select My Workspace > Reports >

### ISSUE THREAD

**Issue by AzizQuazi** [MicrosoftDocs/powerbi-docs#345]
Hi, Looks I cannot find the Schedule refresh in the above step 5 &gt; Reports. I  can see that in the Dataset. Please advise. Thanks.

Rgs..Aziz 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial)
* Content Source: [powerbi-docs/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @AzizQuazi -- thanks for your comment. We've forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by jordanmills** [comment]
This seems to be a known issue in the power bi service.  I ran into it recently.  To fix it, you need to re-upload the pbix file after making a "substantial" change to the query (could be as little as adding a dummy column - and you can always change it back and upload it again).  You can download the pbix file from the service from a report to start with/make sure you're not going to lose or change too much.

ref: https://community.powerbi.com/t5/Service/Schedule-Refresh-Greyed-Out/td-p/276311

**Comment by mgblythe** [comment]
@arthiriyer as FYI, will check this as part of the gateways doc update.

**Comment by mgblythe** [comment]
We did a complete rewrite on this article. Please reopen or start a new item if there are any issues. Thanks!
