### ISSUE TITLE
"one of the dataset owners"  - unreleased functionality

### ISSUE THREAD

**Issue by lbendlin** [MicrosoftDocs/powerbi-docs#3450]
"You must be one of the dataset owners to be able to access the dataset access management page."

Currently there can only be ONE dataset owner. Please clarify if you mean workspace admins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a05dd5c-b949-2feb-bbf2-fb721a750827
* Version Independent ID: 09a7f228-77e0-b4f0-2ae3-e59715f759d4
* Content: [Manage dataset access permissions - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-manage-access-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-manage-access-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/connect-data/service-datasets-manage-access-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by maggiesMSFT** [comment]
Hi, @lbendlin -- thanks for asking! Assigning to the author to clarify.

**Comment by paulinbar** [comment]
Hi @lbendlin, I've updated the doc to be precise. The word "owner" was  indeed problematic. The updated doc should go online later today. Thanks for providing your feedback and helping us improve the docs!
