### ISSUE TITLE
Page update required

### ISSUE THREAD

**Issue by OxfordPowerBI** [MicrosoftDocs/powerbi-docs#3451]
Hi there,

This page needs updating since Gen2 went GA. Finding the CapacityID was a bit of guesswork! Thanks, Angus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcddef48-ab1d-cdd2-900a-9b9f3500a06f
* Version Independent ID: 42ce0182-3006-4271-7981-a9f8a984ca53
* Content: [Install the Premium Gen2 metrics app - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-install-gen2-app)
* Content Source: [powerbi-docs/admin/service-premium-install-gen2-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-install-gen2-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @Withnail99,

We're in the process of revamping our documents, and our table of contents. However, this might take some time :-)

Can please describe what you struggled with and why? So that I can update the article accordingly.

Thanks,

Kesem

**Comment by Withnail99** [comment]
Hi Kesem

Well, the image is of the preview and it has now gone GA. So it needs revamping because the process is somewhat different. If you run through it yourself, then you’ll find that parts of the document need re-writing and new images taken.

Kind regards

Angus

**Comment by KesemSharabi** [comment]
Hi @OxfordPowerBI,

I updated the [Install the Gen2 metrics app](https://docs.microsoft.com/power-bi/admin/service-premium-install-gen2-app?tabs=1st) article.

Hope this helps,

Kesem
