### ISSUE TITLE
Missing activities

### ISSUE THREAD

**Issue by georgedarakji** [MicrosoftDocs/powerbi-docs#3452]
When checking the audit log, we have activities called "DeleteDatasetRows" but can't understand what that means. Please add this activity to the document with a clear explanation as to what it signifies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing#operations-available-in-the-audit-and-activity-logs)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @georgedarakji.

I've assigned this issue to the doc author for review.

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by georgedarakji** [comment]
Hi @KesemSharabi. I couldn't find anything related to this on the internet except for someone who previously opened the issue and never received a response. Here is a reference https://github.com/MicrosoftDocs/powerbi-docs/issues/1852
I think you can merge both issues into one but the important thing is for us to get a concrete response. Thank you for your effort and assistance

**Comment by KesemSharabi** [comment]
Hi @georgedarakji,

I'm looking into this issue and will get back to you as soon as I have an answer.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @georgedarakji,

`DeleteDatasetRows` Indicates that the [Push Datasets - Datasets DeleteRows](https://docs.microsoft.com/rest/api/power-bi/push-datasets/datasets-delete-rows) API was called.

I added this information to [Operations available in the audit and activity logs](https://docs.microsoft.com/power-bi/admin/service-admin-auditing#operations-available-in-the-audit-and-activity-logs).

Thank you for your patience and for getting involved.

Kesem
