### ISSUE TITLE
Missing workspace state and lack of clarity on other states

### ISSUE THREAD

**Issue by georgedarakji** [MicrosoftDocs/powerbi-docs#3453]
When retrieving the workspace states, we are getting workspaces with state "Not Found". This state is not mentioned in the documentation. Please explain what this state means.

In addition, there is also confusion regarding the difference between "Deleted" and "Removing". What exactly is the difference between both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#workspaces)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @georgedarakji, thanks for reaching out. Can you provide a little more info about the scenario? How were you retrieving these values? With APIs? Thanks.

**Comment by paulinbar** [comment]
Hi @georgedarakji, thanks for your input again. As we discussed, the article has been updated and should be more informative now. 
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#workspaces
