### ISSUE TITLE
Font weight in theme

### ISSUE THREAD

**Issue by popeadam** [MicrosoftDocs/powerbi-docs#3454]
Delighted to see the ability in Power BI desktop to use [bold/italics/underline text formatting](https://powerbi.microsoft.com/en-us/blog/power-bi-november-2021-feature-summary/#post-17912-_Toc87473939). Is there any way to define this in a custom JSON theme? "fontWeight":"bold" doesn't seem to work... 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by popeadam** [comment]
Figured it out; it's a boolean value set on the format; so for 'bold' it's:

"bold": true
"titleBold": true

**Comment by mberdugo** [comment]
@popeadam , thanks for your question - and answer! 
It's great that you figured out how to do it yourself, and that you got back to us about it.
I assigned this to the author to decide if this is something that should be added to the doc.

**Comment by maggiesMSFT** [comment]
Thanks, @popeadam -- I've added it to this article, which remains a work in progress. Every bit helps!
