### ISSUE TITLE
Usage Metrics Report Direct Access

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3456]
It looks like the Usage Metrics report can actually be shared via Direct Access to a user without workspace access using File>Manage Permissions. Our documentation mentions this as a limitation - Sharing is disabled for the usage metrics report. To give people read access to the report, you first need to give them access to the workspace.
Another observation is that the user given the direct access can see Usage Metrics of multiple reports. It's visible in the Filter pane and user can make multiple selection.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mberdugo** [comment]
Thanks for your comments and feedback, @rjagdon . 
I've assigned this issue to the doc author to review.

**Comment by maggiesMSFT** [comment]
Hi, @rjagdon -- thanks so much for your comments! We're working on the update.
