### ISSUE TITLE
Wrong documentation at "control-report-filters" page.

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [MicrosoftDocs/powerbi-docs#3457]
Hello, there is an error in the documentation at [https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/control-report-filters](url)
 I don't know exactly how to report doc errors, so in case I did something wrong, please explain me what's the best way to do so.

The error is that where it is written `models.FiltersOperation` should be `models.FiltersOperations` (it is missing the last `s`).

**Comment by mberdugo** [comment]
Thanks for your comment, @FelipeCostaGualberto .
This is exactly how you report doc errors. 
We appreciate you taking the time to bring this to our attention.
The error has been fixed and should be live within a few days.
