### ISSUE TITLE
Elements in "Format page" are not available when activating "New format pane" on existing file

### ISSUE THREAD

**Issue by danievalle** [MicrosoftDocs/powerbi-docs#3458]
Dear team,
When I activate the "New format pane" on an **existing** PBI file, I don't see anything under "Format page". (see picture attached)
I suppose it's due to one format used not compatible with the new pane. The functionality is working on a new blank file.
Regards,
Daniel Valle

![image](https://user-images.githubusercontent.com/15209951/144469027-9209a363-07e3-4fc0-bbec-190a36899abe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @danievalle -- thanks for contacting us! This sounds more like product feedback, though. Could you give a little more detail -- what visualization do you have selected?

**Comment by maggiesMSFT** [comment]
Hi, @danievalle -- not hearing back from you, I'm closing this issue. If you're still having trouble:
- Try downloading the latest version of Power BI Desktop, December version 2.100.785.0 64-bit (December 2021).
- If that doesn't help, try contacting support, https://powerbi.microsoft.com/en-us/support/
Good luck!
