### ISSUE TITLE
Out of date content

### ISSUE THREAD

**Issue by SpenCov101** [MicrosoftDocs/powerbi-docs#3459]
[Enter feedback here]

Content is out of date.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c379d7f1-f977-7906-c4ba-6f58ab47d785
* Version Independent ID: 088a4f2c-e571-1282-b265-9b90d4995505
* Content: [Create buttons in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-buttons)
* Content Source: [powerbi-docs/create-reports/desktop-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-buttons.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @SpenCov101 -- thanks for the feedback! Could you be more specific? I don't want to overlook something.

**Comment by SpenCov101** [comment]
The doc references the old format pane.

The new button formatting is as below.

Thanks

![image](https://user-images.githubusercontent.com/30044084/144477526-50d5d272-f205-4a88-a83d-740eb8166e83.png)

![image](https://user-images.githubusercontent.com/30044084/144477591-3c8bbe89-2438-4ac3-ae52-ccd88ac0bfd5.png)

**Comment by maggiesMSFT** [comment]
Hi, @SpenCov101 -- whew, glad I asked! Yes, that's the new Format pane, great that you're using it! It's currently in preview, so we don't update the docs until it's generally available. If you create a button in the Power BI service, you'll still see the original Format pane for buttons. 
The article https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane spells out the approximate timeline:
"We know it's a big change so we're rolling it out slowly, to get your early feedback and make any needed adjustments. It's currently in preview starting with the Power BI Desktop November 2021 release. Give it a try!"
Hope that helps!
