### ISSUE TITLE
External User Self Subscription

### ISSUE THREAD

**Issue by chrismanuel1993** [MicrosoftDocs/powerbi-docs#3460]
[Enter feedback here]
The page says that external users cannot subscribe themselves to content unless said content is hosted in a premium capacity. Could you elaborate how this can be done ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830da8e8-8526-0e6a-d83f-0c804226e006
* Version Independent ID: 3e7b9d31-133d-1b2f-fded-d9218284155b
* Content: [Subscribe others to your reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-report-subscribe)
* Content Source: [powerbi-docs/collaborate-share/service-report-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/collaborate-share/service-report-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment and your documentation request, @chrismanuel1993. We’ve forwarded your feedback to the writer. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @chrismanuel1993 -- thanks for asking! I've added this sentence to the article, to clarify:

- External users can't subscribe themselves to reports or dashboards. Only people in an organization can subscribe external users, if the content is in a Premium capacity workspace or app.

The change will be live this afternoon Pacific time, Dec 17, 2021.
Thanks!
