### ISSUE TITLE
Doesn't work for European or UK customers though.. 

### ISSUE THREAD

**Issue by mhphilip** [MicrosoftDocs/powerbi-docs#3461]
Note that all of this is useless for EU or UK customers whose weeks don't start on a Sunday. There is no current option to change that and Microsoft has been unwilling to fix this for over 3 years now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @mhphilip. This is product feedback (and reasonable feedback, I want to acknowledge and state) – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. 

I'm also adding the author for review.
