### ISSUE TITLE
Incorrect information - you can't drag'n'drop bookmarks in Power BI

### ISSUE THREAD

**Issue by Quorthon1965** [MicrosoftDocs/powerbi-docs#3462]
The help pages say you can drag and drop bookmarks, but this does not work for me in Edge. I have the bookmarks pane open in the right hand side of the screen, but no matter where I click on the bookmark, to the left of the name, on the name, or on the right, it WILL NOT MOVE. It's driving me crazy. Does it only work in Report Bookmarks and not Personal Bookmarks, and, if so, why? Is it somehow disabled? Somewhere along the way, our ICT has disabled exporting table data to Excel, so maybe this is something else turned off???

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Create report bookmarks in Power BI to share insights and build stories - Power BI](https://docs.microsoft.com/en-gb/power-bi/create-reports/desktop-bookmarks#arranging-bookmarks)
* Content Source: [powerbi-docs/create-reports/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/create-reports/desktop-bookmarks.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Quorthon1965 and sorry for the frustration you're having with this. It might be a browser issue, but also, it might be something support or the community can help you solve (this venue is only for documentation issues). 

You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by maggiesMSFT** [comment]
Hi, @Quorthon1965 -- good catch! You can only re-order report bookmarks, so you have to be able to edit the report. You can't rearrange personal bookmarks. I'll add that to the article. Thanks!
