### ISSUE TITLE
projection

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3464]
Please explain the setting for "projection" and define its options (Equirectangular, Mercator, Orthographic).  Which [Coordinate Reference Systems](https://datatracker.ietf.org/doc/html/rfc7946#section-4) are supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @rootsmusic, thanks for reaching out to us with your question. I am forwarding it on to the doc owner for consideration.

**Comment by mihart** [comment]
Hi @rootsmusic ,
I've added a step for selecting Projection and a brief description of the 3 options.  For more detail, I also added a link to ESRI's very excellent PDF on map projections.  When I asked the shape map PM about Coordinate Reference System, he responded that our projections are 2-dimensional and that the referenced article (on Coordinate Reference System) dealt with 3-dimensional. I'm closing this Git Issue for now, but feel free to reopen if you still have questions. 
Thanks
The DOCS team
