### ISSUE TITLE
Action mechanism  for button is missing 

### ISSUE THREAD

**Issue by LLejoly** [MicrosoftDocs/powerbi-docs#3465]
The action mechanism (Blank Button) is not there anymore with the new pane style. Nothing address this point and we do not know if  it is normal or not. If it is, it would be great if we can have guidance to substitute the action mechanism.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @LLejoly -- thanks for asking! This is the initial preview release. More functionality will be coming in December release, in the next week or so.
