### ISSUE TITLE
No mention of availability in US GOV Cloud

### ISSUE THREAD

**Issue by mrpullen** [MicrosoftDocs/powerbi-docs#3466]
This is something that my US Government customers want desperately. Is this available? It should be clear which clouds these features are available in in the documentation - there is alot of confusion about what is and isn't available.

Also the section

`Gateways enabled for Power BI private endpoints will not work properly with non-Power BI scenarios. A potential workaround is to turn off Private Links, config the gateway, and then reenable the Private Links.`

isn't clear - do you mean to say you won't be able to connect Data gateways to power bi configured with a private endpoint - and if so - how does "turning it off, configuring then turning it back on again" actually resolve the issue. Can you clarify this?

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links#using-secure-private-endpoints-to-access-power-bi)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mrpullen -- thanks for asking! Assigning to the author to investigate.

**Comment by davidiseminger** [comment]
Article has been updated
