### ISSUE TITLE
How to shut on and off power bi embed according to my app login?

### ISSUE THREAD

**Issue by SudeshSharma** [MicrosoftDocs/powerbi-docs#3467]
Hey guys 

I want to use power bi embed with my web app. Is it possible to shut on and off power bi embed according to my client login and logout session without interaction with azure portal. I have created my web app with react and nodejs. 

If possible then how? 

Thanks in advanced.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @SudeshSharma. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
