### ISSUE TITLE
Power BI Report Server

### ISSUE THREAD

**Issue by ShenSilva** [MicrosoftDocs/powerbi-docs#3469]
How can i open PowerBI Report Server

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50f2a19e-3613-9ec0-8818-8f76d3c7eef9
* Version Independent ID: 0b8ebf11-af44-2556-db7c-766d5f844c98
* Content: [How to configure Power BI report scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/configure-scheduled-refresh)
* Content Source: [powerbi-docs/report-server/configure-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/report-server/configure-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ShenSilva -- have you checked out this article yet? 
https://docs.microsoft.com/en-us/power-bi/report-server/install-report-server
It may help. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ShenSilva -- closing this issue for now. Feel free to open another issue if you still have a question. Thanks!
