### ISSUE TITLE
Dataflow refresh - Orchestration

### ISSUE THREAD

**Issue by v-jastanek** [MicrosoftDocs/powerbi-docs#3473]
[Enter feedback here]
**Current docs statement:**
Using dataflows in the same workspace allows straightforward orchestration. If you have dataflows A, B and C in a single workspace, and chaining like A > B > C, then if you refresh the source (A), the downstream entities also get refreshed. However, if you refresh C, then you'll have to refresh others independently.

**Scenario to be covered in docs:**
When we refresh linked dataflows within a workspace, we only refresh the entities that are linked and not the whole dataflow.
For example, lets say D2 has two entities E1 and E2. E1 is a linked entity that refers to D1.
Further, D3 refers to E2 from D2.
So for the scheduled refresh of the D1 dataflow, only the linked entities in D2 would be refreshed.
So E1 would be refreshed but not E2.
Hence the data in D3 would be stale, even after D3 is refreshed. To fix this, set an scheduled refresh on D2."

**What should be added:**
Using dataflows in the same workspace allows straightforward orchestration. If you have dataflows A, B and C in a single workspace, and chaining like A > B > C, then if you refresh the source (A), the downstream entities also get refreshed. However, if you refresh C, then you'll have to refresh others independently. Also if you add new data source in B dataflow (which is not included in A) this data will not be refreshed as a part of orchestration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2681b8f8-2d17-81fe-3a28-f31775b723c8
* Version Independent ID: 89d45c22-4835-3f32-94ca-d4bc84ec5c48
* Content: [Understanding and optimizing dataflows refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-understand-optimize-refresh#orchestration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-understand-optimize-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/transform-model/dataflows/dataflows-understand-optimize-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your comment, @v-jastanek 
I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the comment, I've added your suggestion. Will show up in the next update of the docs.
