### ISSUE TITLE
Hyperlinks take users to outdated docs

### ISSUE THREAD

**Issue by MattWoodEQR** [MicrosoftDocs/powerbi-docs#3474]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/master/powerbi-docs/admin/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, I've assigned the content owner to review.

**Comment by KesemSharabi** [comment]
Hi @MattWoodEQR,

Can you please specify which hyperlink/s you're referring to?

Thanks,

Kesem
