### ISSUE TITLE
Use of Group policy to restrict uncertified visuals 

### ISSUE THREAD

**Issue by wgbrown** [MicrosoftDocs/powerbi-docs#3475]
This (subject in title) is incorrect and does not work.  Please remove the section on group policy in PBI desktop ability to limit use of uncertified visuals.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67bf91c4-cbf2-0b4c-2532-4ade0d56afee
* Version Independent ID: 687beece-c5e9-070f-9794-fc6569bb09b0
* Content: [Organizational visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/organizational-visuals#power-bi-visuals-tenant-settings)
* Content Source: [powerbi-docs/admin/organizational-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/organizational-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
I've assigned this to the content author to review.

**Comment by KesemSharabi** [comment]
Hi @wgbrown,

Can you please confirm which version of Power BI Desktop you're using?

Thanks,

Kesem

**Comment by wgbrown** [comment]
Hi, I have word that this was fixed..  I work at MS and my customer
reported this and was acknowledged as a bug  at the time.  I noticed the
doc was still the same but heard that this was resolved.  I'm waiting for
the customer to test now.

I'll escalate via support if it is repoed

Thanks - close this for now

**Comment by KesemSharabi** [comment]
Hi @wgbrown,

I'm happy to fix the doc but am trying to verify that this is indeed incorrect. The engineering team asked me to check the Power BI Desktop version, as part of this verification.  

Perhaps you can send me an internal mail so that we can avoid getting support involved?

Thanks,

Kesem
