### ISSUE TITLE
Update documentation regarding users using social identities

### ISSUE THREAD

**Issue by Bafff** [MicrosoftDocs/powerbi-docs#3476]
Hi!

Can you be more clear in docs regarding does @gmail/outlook/aol email accounts are supported or not because in our experience we just cannot even get successful login in PowerrBI working for those external users?

See discussion here: https://community.powerbi.com/t5/Service/Work-or-School-Account-required-when-sharing-with-hotmail/m-p/2202492

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, and for the links to the community discussion. I'll look into this and update the article with any results or definitive answers we find.

**Comment by paulinbar** [comment]
Hi @Bafff , I will take this up with the product team. Thanks.

**Comment by Bafff** [comment]
Hi!

Any news?

**Comment by parulbansal2009** [comment]
@Bafff I read about the issue via a different channel too. One of our customers opened an ICM. This seems to be a bug which should be fixed soon. If you don't see a fix in few days, I would recommend that you open a ticket regarding this.

**Comment by davidiseminger** [comment]
Thanks for your comment. This is, indeed, an issue with the product rather than the documentation itself. Feel free to pursue the fix (via the ICM) and once that fix is in place, we'll be happy to update the documentation as appropriate.

**Comment by Bafff** [comment]
@davidiseminger can you confirm that with the fix (I still would need to know what ICM means) I would receive back the ability to create guest users accounts in my AAD and grant them access to my PowerBI?
