### ISSUE TITLE
Is Mailchimp deprecated?

### ISSUE THREAD

**Issue by jasonhendrix** [MicrosoftDocs/powerbi-docs#3477]
This page shows that Mailchimp is supported.  However, another page (https://docs.microsoft.com/en-us/power-query/connectors/mailchimp) shows that it is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @jasonhendrix, thanks for your observation. I am forwarding it along to the doc owner for consideration.

**Comment by davidiseminger** [comment]
Thanks for your comment, I've updated that article to reflect that it's deprecated.
