### ISSUE TITLE
Wrong rule on Roles in the new workspaces Power BI : MEMBER need a PRO LICENSE even if Workspace is in PREMIUM 

### ISSUE THREAD

**Issue by olam-MCA** [MicrosoftDocs/powerbi-docs#3479]
Hi, 
Roles in the new workspaces in Power BI - Workspace role : 
in the matrix : View and interact with an item. (5) => All Roles
Mention (5) Even if you don't have a Power BI Pro license, you can view and interact with items in the Power BI service if the items are in a workspace in a Premium capacity.
is Wrong : 
A member that havent a PRO license cant access to the Worksapce even if the Workspace is Premium.

thk you for your support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces#feedback)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @olam-MCA, thanks for your comment. My initial testing indicates that this is indeed the case. I am forwarding your comment along to the doc owner. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @olam-MCA -- I've confirmed with the product team that the documentation is correct as written. If you're seeing something else, please report a bug on the support site! 
https://powerbi.microsoft.com/en-us/support/
thanks!

**Comment by olam-MCA** [comment]
Hello, Thank you for your answer. 
I persist by checking on my side with other users of my organization :
User U1 : Get Proc license
Workspace WS1 : Premium Kind ( Diamond )
U1 is added as "Member" on WS1.
U1 trying to access to WS1 he have a msg : "Upgrade to a PRO License to access "

a) Is it a transient issue ?
b) User must NOT be added as member as he get a PRO License ?
c) This page contain an error :   [https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces#feedback](url)
d) I didnt understand something and I am totally wrong ;-)

![2021-12-21 10_23_10-Roles in the new workspaces in Power BI - Power BI _ Microsoft Docs et 8 pages d](https://user-images.githubusercontent.com/75135333/146905531-e7bc20eb-e1e9-4bf2-ae79-10a9da117d17.jpg)

thk you

**Comment by maggiesMSFT** [comment]
Hi, @olam-MCA -- I've confirmed with the product team again that the documentation is correct as written. They encourage you to report a bug on the support site!
https://powerbi.microsoft.com/en-us/support/
Hope that helps!
