### ISSUE TITLE
I do not see the sort button when I click the ellipses

### ISSUE THREAD

**Issue by cajonemsft** [MicrosoftDocs/powerbi-docs#348]
All I see is the below.

![image](https://user-images.githubusercontent.com/26772936/47188292-58479080-d2ec-11e8-8127-d655d5768c72.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Change how a chart is sorted in a Power BI report - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-change-sort#feedback)
* Content Source: [powerbi-docs/consumer/end-user-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-change-sort.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @cajonemsft -- thanks for your question. We’ve forwarded it to the writer, who should respond shortly. Thanks!

**Comment by cajonemsft** [comment]
Thanks!

**Comment by mihart** [comment]
Hi @cajonemsft ,
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.
If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
Kind regards,
Microsoft DOCS International Team

p.s. I tried to duplicate this and could not.  So if you do contact the product team, pls provide as much detail as you can so they can duplicate.
