### ISSUE TITLE
Clarity for on-demand refresh

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#3480]
"Datasets workload - scheduled refresh, on-demand refresh, background query (after refresh)"

From the above line, can you please clarify if the line "on-demand refresh" includes the REST API and process events via XMLA commands. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7d18dd-7459-baea-2c12-fc47ffcd9b11
* Version Independent ID: 42220c7a-465b-2da2-3014-0aecd9631142
* Content: [Power BI Premium Gen2 FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-faq)
* Content Source: [powerbi-docs/admin/service-premium-gen2-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @itsnotaboutthecell -- thanks for your question! Referring you to the author and closing this issue.
