### ISSUE TITLE
Missing Action setting for Button (for Drill through)

### ISSUE THREAD

**Issue by NikhilPodishetti** [MicrosoftDocs/powerbi-docs#3481]
Hi, that was an awesome experience using the new format pane. But, here is the thing - I liked the new option to navigate / bookmark pages for buttons but I am using Drillthotugh to buttons which I usually select through the action setting, but now in the new format pane, I couldn't see that. Can anyone explain how can I do that using the new Action pane?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @NikhilPodishetti -- good catch, thanks for asking! A new release of Power BI Desktop should be coming out this week, and it'll feature updates to the Format pane. Check it out and see if that answers your questions!

**Comment by NikhilPodishetti** [comment]
Thank you. That's all I need :)
