### ISSUE TITLE
Link to JavaScript Filters is deprecated

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#3482]
The section on CUSTOMDATA() mentions JavaScript filters but points to a deprecated page:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters#page-level-and-visual-level-filters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Using row-level security with embedded content in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security#using-the-customdata-feature)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @otravers .
This page is currently undergoing a complete update. It might take a while before it is live with all the changes. 
In the meantime, if you need help with this issue, you can try contacting [support](http://support.powerbi.com/).
