### ISSUE TITLE
A stated limitation has an undocumented workaround "Guest users can't use Power BI desktop to connect to service datasets in the Power BI service"

### ISSUE THREAD

**Issue by mitchonfire** [MicrosoftDocs/powerbi-docs#3483]
**RE: Considerations and Limitations "Guest users can't use Power BI desktop to connect to service datasets in the Power BI service"

A workaround which I managed to figure out:**

1) Guest can author a report in PBI Desktop against the XMLA Endpoint of the external tenant's Dataset using "Analysis Services" datasource provider (replace "/myorg/" with "/tenantname.onmicrosoft.com/")

**NOTE**: _this actually dispels the stated limitation in itself, however this report will not work after being published to the external tenant workspace even though it will be accepted; the report will throw a "Cannot load model" error_

**So**, in order to work around the Service Hosted report we can do the following to fix the guest authored report .pbix:

2) Use a local tenant account to author a blank report using "Power BI Datasets", connect to the same service Dataset (that the guest has created a report against) and save the .pbix

3) Rename the pbix to .zip, open and extract the "connections" file, provide this file to the guest author/s.

4) Rename the guest-created report .pbix to .zip, overwrite the "connections" file the .zip with the new "connections" file extracted in [3]

5) Revert the guest-created report file name extention from .zip to .pbix

6) when the guest uploads/imports their .pbix file to the external teantn workspace it will be using a "Power BI Datasets" as a datasource.

**PS**: this confirms that the limitation is simply a UI limitation of PBI Desktop; PBI Desktop should simply ask which tenant to connect to and generate the correct "connections" file.

**Comment by KesemSharabi** [comment]
Hi @mitchonfire,

Can you please indicate which document this relates to?

Thanks,

Kesem

**Comment by mitchonfire** [comment]
Hi Kasem,

Strange how the comment lost it's context, anyway was feedback for :
https://docs.microsoft.com/en-us/power-bi/admin/service-admin-azure-ad-b2b#considerations-and-limitations

**Comment by KesemSharabi** [comment]
Hi @mitchonfire,

Thanks for letting me know which article you're referring to. I'll look into the the workaround you suggested, keep you posted re updating the article.

Thanks,

Kesem

**Comment by mitchonfire** [comment]
Great, thanks Kasem.

**Comment by paulinbar** [comment]
Hi @mitchonfire, I am engaging the product team to discuss your workaround. 
Thanks!

**Comment by mitchonfire** [comment]
Great news Paul, thanks, please don’t disable the functionality :P

Regards
Duncan Mitchell

**Comment by paulinbar** [comment]
Hi Duncan, (@mitchonfire)
I see that your issue is still open. I passed your message along to the product team some time ago - but I know that they have been overhauling the way B2B works in Power BI, so I don't know what they did with your suggestion or how they have prioritized it. If you see that something has changed I'd like to know about it. If you want to suggest an improvement to Desktop, try the ideas site. https://ideas.powerbi.com. In the meantime I will close this issue now. Thanks again for the info and sorry for not responding sooner.
