### ISSUE TITLE
Navigation bar title text saying Preview, but feature is apparently in GA?

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3484]
[Enter feedback here]
Hello 

Looking at the document https://docs.microsoft.com/en-us/power-bi/admin/service-premium-backup-restore-dataset

On the left side there is the navigation pane - in the Title text for this doc it says 'Preview'. According to my understanding this feature is in GA already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd58c3c-7cb9-d17f-7a9f-c77fe1c6bf96
* Version Independent ID: 85bc335f-650d-45ec-cc37-f8406658d416
* Content: [Backup and restore Power BI Premium datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-backup-restore-dataset)
* Content Source: [powerbi-docs/admin/service-premium-backup-restore-dataset.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-backup-restore-dataset.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mberdugo** [comment]
Thanks for your comment, @anna907 . 
I've assigned this issue to the doc author to confirm and update.

**Comment by KesemSharabi** [comment]
Hi @anna907,

Thank you for your comment and for pointing this out. I removed 'preview' from the table of contents, see [Backup and restore datasets with Power BI Premium](https://docs.microsoft.com/power-bi/admin/service-premium-backup-restore-dataset).

Thanks,

Kesem
