### ISSUE TITLE
PBI Flow Connector documentation: This documentation needs an example on how to export a single visual by name

### ISSUE THREAD

**Issue by lordneeko** [MicrosoftDocs/powerbi-docs#3485]
The document provides how to get the "bookmark name" and the "page name' from the url, but i can find nothing on the internet to tell me how to use the "visual name" optional field to extract just a single visual.  I need this because the connector doesn't currently allow me to export (underlying or summary) data to a csv or xlsx so when I need to archive something I cannot do it, so I want to archive a single visual of data. But, I cannot figure out how to get the "visual name' field correct.

In addition, how to use the "report filter" field in the connector would be massively helpful as well.  There is VERY little documentation on how to use this action but a bunch of articles on how to use the "Add to dataset" action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment. We’ve forwarded your feedback to the writer, who will respond to this thread. Thanks!

**Comment by lordneeko** [comment]
Thank you @davidiseminger  I've also run into some major bugs with this connector, but I cannot find where I can report those.

**Comment by maggiesMSFT** [comment]
Hi, @lordneeko -- thanks for your comment! I'm checking with the product group about your initial comments, and I'll let you know what I hear back. 
For the major bugs, I recommend contacting https://powerbi.microsoft.com/en-us/support/. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @lordneeko -- here's the reply from the product group:
"The Export to File connector in Power Automate is really just no-code (user interface) way to interact with the export API. 
With that said, any of the docs that explain how to use the export API also apply to the Power Automate connector. The following doc touches on both filters and visual names. Looking through this doc, there are two ways to get the attribute visualName but they are both pretty technical. 
https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to#exporting-a-page-or-a-single-visual
I'm going to add that explanation to the article. The change will be live tomorrow afternoon, Jan 4, 2022, Pacific time.
Hope that helps!
