### ISSUE TITLE
Another Issue plus fix for Power BI Desktop Store Version.  

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/powerbi-docs#3486]
Hi,
Not an Issue, just another entry for your page.  We had the following issues with the Power BI Desktop store version. 

SYMPTOMS
 - starting Power BI gives the message " Hmmmm... can't reach this page.  ms-pbi.pbi.microsoft.com's server IP address could not be found.  
 - Application event log message - The description for Event ID 1 from source MSOLAP$AnalysisServicesWorkspace_0822eaf6-5c17-4ef6-8345-635ca73d8982 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

FIX 
reinstall WebView2
- uninstall webview2 ( standard user can do this)
- install webview2 using the bootstrapper from here - https://go.microsoft.com/fwlink/p/?LinkId=2124703 ( standard user can do this)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533d0cd5-b457-863c-f862-49fac672332c
* Version Independent ID: f5df6cb3-049a-eff0-4d7b-3c3843927a5e
* Content: [Resolve issues when starting Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-error-launching-desktop)
* Content Source: [powerbi-docs/connect-data/desktop-error-launching-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-error-launching-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @PaulKlerkx - great idea! I've added your work-around to that article, should show up in a day or two. Thanks!

**Comment by davidiseminger** [comment]
Fixed!

**Comment by aanyoti** [comment]
Thank you, this fixed my issue.
