### ISSUE TITLE
Power BI Emedded Paginated Report - Docs Out Of Date

### ISSUE THREAD

**Issue by GraemeSMiller** [MicrosoftDocs/powerbi-docs#3487]
"Power BI dataset is not supported as a datasource."

Doesn't Power BI Embedded now support Power BI Dataset as a data source for embedded reports https://powerbi.microsoft.com/en-us/blog/power-bi-december-2021-feature-summary/#post-18168-_Toc89785252?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d53eef67-91ce-691f-5e29-515d553023f6
* Version Independent ID: f6723c69-a08d-42af-6a74-33f22bc55fba
* Content: [Embed paginated reports in your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-paginated-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by davidiseminger** [comment]
Thanks for your comment, @GraemeSMiller. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mberdugo** [comment]
Thanks for bringing this to my attention, @GraemeSMiller. You are correct. 
This page will be updated (hopefully this week) to reflect the change.

**Comment by mberdugo** [comment]
Hi @GraemeSMiller, I just checked with the developers and it appears that there have been some hurdles and this change has been postponed to mid January. As of now, Power BI dataset is still not supported as a datasource. I'll update the page when it becomes relevant. Thanks again for your question.

**Comment by GraemeSMiller** [comment]
@mberdugo That is a pity it has been pulled. We were about to start implementing it. Thanks for letting us know. Look forward to Mid Jan
