### ISSUE TITLE
Direct Query cache restrictions information out of date?

### ISSUE THREAD

**Issue by troyel** [MicrosoftDocs/powerbi-docs#349]
From the text: "Scheduled refreshes: With shared capacity, scheduled refreshes for imported model datasets are limited to eight times per day. For datasets in Premium workspaces, you can schedule refreshes up to 48 times per day. DirectQuery cache refreshes are still limited to eight times a day in Premium capacity."

According to this: https://powerbi.microsoft.com/fr-fr/blog/announcing-custom-cache-refresh-schedules-in-the-power-bi-service/ the standard direct query cache refresh is 1 hour and no restrictions are mentioned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@troyel -- thanks for the feedback. I updated the refresh info in that doc fairly recently. That is the info I got from the product team. I believe the blog is in error, but please reopen this issue if your experience in the product is different.
