### ISSUE TITLE
Confusing metrics in table

### ISSUE THREAD

**Issue by floemmel** [MicrosoftDocs/powerbi-docs#3490]
On the bottom of the page there is a table outlining the limitations. This shows the CPU time per minute, however in all the capacity metrics it is calculated per 30 seconds. Therefore in e.g. a P1 capacity you have 120s CPU for a 30 seconds interval, in this table it says however that you have 240 per Minute. While of course both is correct, this is confusing and should be aligned in my opinion. 

Kind regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3d17a8-8258-5246-24bb-b69c273d06c4
* Version Independent ID: 36f06d1c-4f46-598d-c300-eb4dd22d4487
* Content: [What is Power BI Premium Gen2? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is)
* Content Source: [powerbi-docs/admin/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @floemmel --thanks for letting us know! Assigning to the author for consideration.

**Comment by KesemSharabi** [comment]
Hi @floemmel,

We recently updated the table at the bottom of the [Limitations in Premium Gen2](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-what-is#limitations-in-premium-gen2) section.

Hopefully this update helps clarify matters.

Thanks,

Kesem
