### ISSUE TITLE
Apply security filter in both directions.

### ISSUE THREAD

**Issue by Didierma92** [MicrosoftDocs/powerbi-docs#3491]
Hi folks,
I can see that we should apply Apply security filter in both directions. in this doc : but what for ? and what usage for not activating security filter in both directions checkbox in the relation definition? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af7bffc1-7691-53e6-c582-c17b3f4c03da
* Version Independent ID: 6d3ce776-d39a-b834-e05b-73bc5452fd63
* Content: [Bidirectional cross-filtering in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-bidirectional-filtering)
* Content Source: [powerbi-docs/transform-model/desktop-bidirectional-filtering.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-bidirectional-filtering.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Didierma92 -- thanks for your question! Assigning to the author for consideration.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
