### ISSUE TITLE
Minor correction

### ISSUE THREAD

**Issue by grzegorzwierzbicki** [MicrosoftDocs/powerbi-docs#3492]
This is a minor correction.
Command **Set-MsolCompanySettings** is part of the MSOL PowerShell module - not Azure AD PowerShell module

_If you want to disable all self-service sign-ups, change a setting in Azure Active Directory named AllowAdHocSubscriptions by using Azure AD PowerShell commands. Follow the steps in this article to Set MsolCompanySettings. This option turns off self-service sign-up for all Microsoft cloud-based apps and services_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c931454d-f706-a12d-5823-54be2594a7a5
* Version Independent ID: 2025949d-a8cf-e241-3e4b-db9050fe1d12
* Content: [Enable or disable self-service sign-up and purchasing - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-disable-self-service#use-powershell-azure-ad-and-microsoft-365-to-enable-and-disable-self-service)
* Content Source: [powerbi-docs/admin/service-admin-disable-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-disable-self-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @grzegorzwierzbicki, thanks for your observation. I'm passing it on to the owner of that content for action.

**Comment by mihart** [comment]
Hi @grzegorzwierzbicki , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
