### ISSUE TITLE
The definition of Power BI PaaS Embedded

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3493]
[Enter feedback here]

Looking at this doc - in the Considerations and Limitations, this text
"The visual isn't supported for PaaS embedded scenarios, nor in Sovereign Cloud scenarios"

I am having hard time finding any definition for this 'PaaS embedded' in Power BI documentation. I find only definitions for 'app owns data' or 'embed for your customer' scenarios but not a word about 'PaaS embedded'. It would be nice to have this clearly defined in the doc in order to know whether this is supported in my scenario or not.

Thanks,
Anna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de472a84-f62c-d01c-a8b2-e6ea168a222d
* Version Independent ID: da8c0056-7e3d-fc14-c5a4-1bd3bab573de
* Content: [Create a Power Automate visual for Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-automate-visual)
* Content Source: [powerbi-docs/create-reports/power-bi-automate-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-automate-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @anna907, thanks for your feedback about the definition of Pass embedded. I have forwarded it along to the owner of that content for consideration.
Again, thanks for your time in reaching out to us!

**Comment by mberdugo** [comment]
Hi @anna907, thanks for your question. I checked and the limitation is for "embed for your customers".
I'll notify the the author of this document to clarify. @maggiesMSFT

**Comment by maggiesMSFT** [comment]
Thanks, @anna907 and @mberdugo ! Updating the article to replace "PaaS embedded" and a link to a related article. Update should be live tomorrow Thurs Dec 12, or Mon Dec 17 at the latest, depending on holiday schedules.
