### ISSUE TITLE
What happened to button actions?

### ISSUE THREAD

**Issue by ChiliGuy** [MicrosoftDocs/powerbi-docs#3494]
I'm using the new formatting pane... I've added a button to my report and I want to set the button to drill through to another page. However, there is nowhere I can find the "Action" selection like there was in the old format! Where did it go?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ChiliGuy -- have you downloaded the latest version of Power BI Desktop? A lot of formatting options weren't in the November version of the Formatting pane, but button actions are there in the December version, version 2.100.785.0 64-bit (December 2021)
Check it out 😁
