### ISSUE TITLE
Apply Query Changes Later in Power BI Service

### ISSUE THREAD

**Issue by gigatt-jm** [MicrosoftDocs/powerbi-docs#3495]
[Hi,  I'm wondering if it is possible to apply the query changes made on Power BI Desktop LATER on Power BI SERVICE by pressing the "Refresh Now" button on the Power BI Service webpage. 
I edited the query on Power BI DESKTOP and selected "Close" (instead of "Close & Apply"), and then saved and uploaded the pbix file to Power BI Service. After pressing the "Refresh Now" button on Power BI Service, it seems like the query changes I made on Desktop are still not applied on Service. How could I apply the query changes on Power BI Service? Thanks a lot!]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your question, @gigatt-jm . 

I'm assigning this to the author to investigate and possibly update the document with this information.
In the meantime, you might find the answer by searching the Power BI community support page:
https://community.powerbi.com/

Please understand that things might take longer than usual because of the holidays.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
