### ISSUE TITLE
Push dataset schema documentation missing

### ISSUE THREAD

**Issue by sdg002** [MicrosoftDocs/powerbi-docs#3496]
Hi All,
I am evaluating the suitability of Push datasets for a customer. I was unable to find any documentation which would confidently tell me what aspect of the Tabular model is supported and what is not.  

## Links I have looked at
[Link to Microsoft docs on Push datasets](https://docs.microsoft.com/en-us/rest/api/power-bi/push-datasets/datasets-post-dataset)

[Link to Microsoft docs on step by step walk through on Push datasets](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/automation/walkthrough-push-data-get-token.md)

## Using a BIM file from Visual Studio SSDT
Can I use the BIM file of an Analysis Server project or a BIM file generated by SSDT?  I like this becaues the JSON format of the file gives me GIT integration and CI/CD and Pull Request review. These are very essential for our customer's environment and not something easily doable with out of box PBIX/PBIT.

## BIM file from Tabular Editor seems to be supported
A BIM file generated from PBIT using the [Tabular Editor](https://www.sqlbi.com/tools/tabular-editor/) tool appears to be a possibility.  YouTube [video from Marco Russ on on GuyInACube ](https://www.youtube.com/watch?v=9V-WhDLh1RU&list=WL&index=13&t=1139s)channel .

Thank you,
Sau

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
