### ISSUE TITLE
Overloading score (aka Magars Magic Measure)

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3497]
Hi doc team, would it be possible to have the exact formula of the "overloading score" (aka "Magars Magic Measure" in the dataset) ? Also how the severity of an overload event is calculated ? Any help would be very much appreciated. Thanks! Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f52eeb-717d-9a67-b775-c17c5cf916e4
* Version Independent ID: 2c804bb2-1cf3-462e-730b-ecfbae2a5e9e
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/admin/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @nstraw, I'm forwarding your request on to the owner of the doc you mentioned for further consideration. Thanks for reaching out to us!

**Comment by KesemSharabi** [comment]
Hi @nstraw,

Thank you for your great feedback!

I added the [How is the overload score calculated?](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-faq#how-is-the-overload-score-calculated-) entry to the [Power BI Premium Gen2 FAQ](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-faq#how-is-the-overload-score-calculated-) article.

I hope this helps clarify matters.

Thanks,

Kesem

**Comment by nstraw** [comment]
Hi @KesemSharabi,

Thank you so much for the new entry in the FAQ! 

The information is very clear and truly helpful, it will be very appreciated by our team and customers, and the whole community I'm sure! It surely clarifies the way we should monitor and optimize our Gen2 capacities :)

Nicolas

**Comment by nstraw** [comment]
Hi @KesemSharabi,

just to follow-up, I've tried to "recalculate" the overload score using the formula but it did not match, can you help me getting the right formula ?

I tried [ThrottleTime] x [ThrottledOperations] (from [Throttled_by_Artifact_and_Hour], inside the Capacity Metrics Dataset)

Thanks again for your help!

Nicolas

![image](https://user-images.githubusercontent.com/35227452/150842691-9ed67994-db68-4454-b31b-facbabd45f09.png)

**Comment by nstraw** [comment]
Hello @KesemSharabi,

I understand your point and the approximations will work for us.

I was just curious about this measure (name and formula), I took a chance ;)

Thanks anyway for your time and all the valuable infos. 

Nicolas
