### ISSUE TITLE
typo in https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers

### ISSUE THREAD

**Issue by shayanjafari** [MicrosoftDocs/powerbi-docs#3498]
[Enter feedback here]
Hi
I hope you're doing well

I think there's a typo in the text of this page which I highlighted it with yellow color in the attached picture . slicers is mistyped sliders .

Best Regards
<img width="481" alt="typo" src="https://user-images.githubusercontent.com/72691297/147771089-128250be-44d7-420d-b36e-78fb04beaef0.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @shayanjafari, thanks for the feedback! I'm not sure whether this one should be slicers or sliders. I'm forwarding your comment on to the doc owner for consideration.

**Comment by maggiesMSFT** [comment]
Hi, @shayanjafari -- yes, I think in that sentence, "slider" should be "slicer," although both are used in the article. Thanks! Fixed, change will be live this afternoon Jan 3 Pacific time.
