### ISSUE TITLE
typo in https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers

### ISSUE THREAD

**Issue by shayanjafari** [MicrosoftDocs/powerbi-docs#3499]
[Enter feedback here]
Hi
I hope you're doing great

I recognized a type in the aforesaid page which I have highlighted with green color in the attached picture ( BI is typed B I ) . Sorry I couldn't find a better color to show the typo .
<img width="508" alt="type 2" src="https://user-images.githubusercontent.com/72691297/147780814-a4472446-1a3c-45b7-a077-3ec6d4f23971.PNG">

Best Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Slicers in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-slicers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by shayanjafari** [comment]
found another type on this same page , highlighted in yellow in the attached picture .
<img width="489" alt="typo 3" src="https://user-images.githubusercontent.com/72691297/147785084-ce456bd3-236d-4234-82a4-e5fbc9c62415.PNG">

**Comment by paulinbar** [comment]
Hi @shayanjafari, thanks for the sharp eyes! I'm forwarding your comment on to the doc owner for further action.

**Comment by maggiesMSFT** [comment]
Thanks, @shayanjafari ! Fixing now, changes will be live this afternoon Jan 3, 22, Pacific Time.
