### ISSUE TITLE
"Feature this app" documentation doesn't align with Power BI Service functionality

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3500]
Hello,

The "Feature an app" section of this page doesn't seem to be relevant to the current Power BI Service.  Maybe the feature was retired, not yet deployed, or requires a setting change before the "Feature this app on Home" menu option appears?  Would be great if you could take a look at that section and confirm.

https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-featured-content#feature-an-app

Thanks!
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b40b6f6-89e7-15ae-e536-1a3d796c6dc7
* Version Independent ID: 241c59bb-373c-6890-0655-6bcb1456cad3
* Content: [Feature content on colleagues' Power BI Home page - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-featured-content)
* Content Source: [powerbi-docs/collaborate-share/service-featured-content.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-featured-content.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- 

**Feature this app on Home** functionality is still there. Do note: You don't feature it from the app itself. You feature it in the workspace from which the app was created. I just took this screenshot in the public service:
![image](https://user-images.githubusercontent.com/12401230/147995045-8e99473a-9bca-46c9-a55d-d5510d71ee4e.png)

Two possibilities why you're not seeing it:
- Your admin could disable it. See https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#featured-content. 
- You have to have the right role. As the article says: "To feature the app itself, you need to have the Admin or Member role in a workspace."

I've updated the article to emphasize that. Changes will be live tomorrow afternoon Jan 4, 2022 Pacific Time.

Hope that helps!

**Comment by chrisweis** [comment]
Maggie, you're right!  I confirmed I was misunderstanding that the "Feature this app on Home" is within the workspace, not within the app.  Thanks so much, and thanks for making this great improvement so quickly!
