### ISSUE TITLE
it

### ISSUE THREAD

**Issue by nomanali1424** [MicrosoftDocs/powerbi-docs#3501]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by KesemSharabi** [comment]
Hi @nomanali1424,

Are you trying to leave documentation feedback, or is this a mistake?

Thanks,

Kesem

**Comment by nomanali1424** [comment]
I was trying to leave it...

**Comment by KesemSharabi** [comment]
Hi @nomanali1424,

Can you please state what your doc feedback is?
