### ISSUE TITLE
Which way of export to choose?

### ISSUE THREAD

**Issue by KingR1** [MicrosoftDocs/powerbi-docs#3503]
It's a bit unclear what methods to choose when I have paginated report and I need to export only single page. 

When I am using [Export Power BI report to file](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to) then I can pass into `PowerBIReportExportConfiguration` names of pages to export.
When I'm using [Export paginated report to file](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report), I can pass into `PaginatedReportExportConfiguration` number(start-end) of pages to export. 

In both cases, I think, I can get the same result. Only difference - for paginated export there is supported more file formats than for simple export.

Please explain in which way to move. Thanks

**Comment by KesemSharabi** [comment]
Hi @KingR1,

We're looking into this and will get back to you shortly.

Thanks,

Kesem
