### ISSUE TITLE
Dataflow Limitations Correction - Multiple Credentials for Single Data Source

### ISSUE THREAD

**Issue by ARock22** [MicrosoftDocs/powerbi-docs#3504]
Microsoft Team,

It appears there's an issue with the Dataflows Limitations page, specifically in the [Dataflow authoring section](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations#dataflow-authoring). Based on an error I'm facing, it appears dataflows cannot support multiple credentials for **any** single data source. The current description says this limitation only applies to **gateway** data sources, however, I am using a cloud-based SQL server and I cannot use multiple credentials.
Perhaps I am just missing something, so I welcome any clarification you can provide. Better yet, adding this feature would be great! No matter what, it would be ideal to ensure these instructions/limitations are accurate for the time being.

Thanks for your support!
-Anthony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ec2a31-ae63-38f7-00e8-234bcedd571d
* Version Independent ID: ff4d4e25-80f5-cac3-49c8-a85b7cf1c476
* Content: [Dataflows Limitations, restrictions and supported connectors and features - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations#feedback)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Article has been updated, thanks.
