### ISSUE TITLE
Shared Power BI Dataset refresh is gets paused incorrectly due to inactivity

### ISSUE THREAD

**Issue by Melsize** [MicrosoftDocs/powerbi-docs#3505]
We have several Power BI Datasets that have been created to use along with other data sources.   Since there are not any reports that singularly use these datasets, they mistakenly get automatically paused.  Is there something that can be done to prevent this from happening since these datasets are being used compositely in other reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0097b22-50b6-445a-10e9-a8e2a26dabbe
* Version Independent ID: daf670da-4171-29b2-7171-4e46637c099d
* Content: [Create reports based on datasets from different workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-discover-across-workspaces)
* Content Source: [powerbi-docs/connect-data/service-datasets-discover-across-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-discover-across-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @Melsize, sorry for the long delayed response. I checked with the product team and they said that this issue should have been fixed somewhere in the March 2023 timeframe. I can you check to see if you still have the issue? In the meantime, I am closing this Github issue. Please reopen if you find that you still have the problem you described. Thanks!
