### ISSUE TITLE
The "Xero template app" is no longer working.. 

### ISSUE THREAD

**Issue by Andywareaus** [MicrosoftDocs/powerbi-docs#3508]
The "Xero template app" is no longer working.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 264b8c79-ddc0-a0d6-3f60-f0d53d3dbca4
* Version Independent ID: b490a2a1-c55b-db04-964f-2cd0e1107509
* Content: [Connect to Xero with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-xero)
* Content Source: [powerbi-docs/connect-data/service-connect-to-xero.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-xero.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mberdugo** [comment]
Thanks for your comment, @Andywareaus.
I've assigned this issue to the doc author to look into.

**Comment by paulinbar** [comment]
Hi @Andywareaus, the Xero template app has been deprecated. It looks like there are two other potential "Xero" related template apps in AppSource. If you go into Apps in Power BI, and the choose Get apps, you can search for Xero on the All apps tab. That returns two items. You might check those out. Good luck!
