### ISSUE TITLE
Custom Entities, Authentication & Data Refresh

### ISSUE THREAD

**Issue by delormej** [MicrosoftDocs/powerbi-docs#351]
The example given above is very specific and limited to an handful of CRM entities.  For meaningful reporting against custom entities and complex joins you must use FetchXML and a web connection.  A nice example of how to actually connect to Dynamics CRM from PowerBI is covered in this blog post:  https://crmchartguy.com/2017/09/30/use-fetchxml-in-power-bi-with-dynamics-365-customer-engagement/.  What is missing from this, however is how to get Refresh to work for the datasource.  Refreshes always fail because it does not appear that app credentials are stored.  This document would be more helpful if it explained how to really connect to Dynamics CRM from PowerBI with powerful custom queries, and store user credentials for automatic refresh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01c1a1c3-91f0-69c1-4f19-d2a0b22d29dc
* Version Independent ID: ba6e2063-6267-ced8-17c0-22fa78d2645c
* Content: [Connect to Microsoft Dynamics with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-microsoft-dynamics-crm)
* Content Source: [powerbi-docs/service-connect-to-microsoft-dynamics-crm.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-microsoft-dynamics-crm.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by kfile** [comment]
Hi @delormej thank you for your comment. I've assigned it to the author for review. @SarinaJoan

**Comment by SarinaJoan** [comment]
Hi @delormej, thanks for your suggestion. We are currently making changes to this content pack, and will update documentation shortly.
