### ISSUE TITLE
Power BI usage metrics and "My Workspace" are unclear in this document

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3511]
Hello,

In this page and section...
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#update-usage-metrics-report-credentials

...it seems like the steps don't consider when My Workspace is being used.  Do the steps still apply?  Does a "Note:" need to be added to clarify how My Workspace works or applies for Usage Metrics?  Or does a limitation need to be added to this section?:
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#considerations-and-limitations

Thanks!
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new workspace experience (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- interesting question! I'll ask and get back to you.
Thanks!

**Comment by chrisweis** [comment]
Hi @maggiesMSFT, I created this matrix to try to understand the current state. Hope it's helpful: https://lnkd.in/gG9wKKeU

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- this doesn't address all of your questions/comments, but I did find this out: 
Your My Workspace is based on the classic workspace technology, so it has the usage metrics reports for classic workspaces.
So the other Usage Metrics article, https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-usage-metrics, is more accurate for My Workspace.
I'm adding that to both articles.
Hope that helps!

**Comment by chrisweis** [comment]
@maggiesMSFT, you're awesome, thanks so much!!
