### ISSUE TITLE
Set up more than 24 subscriptions for dashboards and reports

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3512]
As tested in Power BI Service Premium P2, you can set up and run more than 24 subscriptions. The document mentions this as a limitation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rjagdon. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @rjagdon ,
Looks like you found a bug.  Our PMs were able to replicate your experience and have notified the engineers.  We've decided to keep the reference to 24 in the article until the engineering team decides whether to enforce the limit or not. 
Thank you
The DOCS team
