### ISSUE TITLE
Text fix for this document

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3513]
[Enter feedback here]
Hello 

Please check the texts in the first highlighted purple Note textbox. It says:
"Power BI Premium recently released a new version of Premium, called Premium Gen2, which is currently in preview."

-->Power BI Gen2 has been GA for a while now so could you please fix this in the doc as well.

Thanks again,
Anna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38feecc0-9338-8359-5ce0-d2120c0b0004
* Version Independent ID: 96a236e6-2389-dc75-f5c5-4ead7dbd5c30
* Content: [Optimize Microsoft Power BI Premium capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-capacity-optimize)
* Content Source: [powerbi-docs/admin/service-premium-capacity-optimize.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-capacity-optimize.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @anna907 and you're right. That update must have slipped through. I've fixed that, will be updated in the next day or so. Thanks!
