### ISSUE TITLE
Update Excel libraries for the OLE DB provider - Community post link

### ISSUE THREAD

**Issue by Koi999** [MicrosoftDocs/powerbi-docs#3514]
Community post link supplied is old (2016).  Please could the link be reviewed for relevancy?  Thank you

I have the same issue as the post initiator after downloading the latest Analyze in Excel update 6 Jan 2022, however the actions described in the community post have not helped me determine whether Excel libraries are up to date or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae990a42-30ce-e2cd-ef81-b2caba935050
* Version Independent ID: cd6b2f01-2ab8-bd8e-67a5-29a8f1ce3555
* Content: [Troubleshoot connecting Excel to Power BI data - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/desktop-troubleshooting-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/desktop-troubleshooting-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/desktop-troubleshooting-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @Koi999 -- thanks for your question! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @Koi999 -- Good point about the community link. Here's a recent article: https://docs.microsoft.com/en-us/analysis-services/client-libraries?view=asallproducts-allversions#download-the-latest
I've added this link to the article. Change should be live next Mon Jan 10 afternoon Pacific time.
Thanks, hope that helps!
