### ISSUE TITLE
The 2 "notes" are contradictory. 

### ISSUE THREAD

**Issue by kchan-hdr** [MicrosoftDocs/powerbi-docs#3515]
[Enter feedback here]

The 2 notes are contradictory. In the "Register an Azure AD app", "Manual registration" tab, the notes under "An embed for you customers application with a service principal", _If you choose this option, after you register your Azure AD app you'll have to add Power BI permissions to it_.

Further down, in "Change your Azure AD app's permissions", a second note says, _Azure AD app permissions are only applicable for these scenarios: Embed for your organization, Embed for your customers with the master user authentication method_  which explicitly excludes the service principal method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dd93dd-c3a9-fccc-3a74-cebd6bf09067
* Version Independent ID: 0f61cf44-982a-1fcd-1396-4f3da8a40af2
* Content: [Register an app to embed Power BI content in a Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/register-app?tabs=manual%2CAzure)
* Content Source: [powerbi-docs/developer/embedded/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/register-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Hi @kchan-hdr, thanks for pointing this out. I'll look into it, and get back to you.

**Comment by mberdugo** [comment]
The misleading note has been removed. Thanks again, @kchan-hdr , for noticing and pointing this out.
