### ISSUE TITLE
SAP Connector for Microsoft .NET 3.0 - New Versions and Impact on PBI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#3518]
The SAP website now has SAP Connector versions newer than those referenced in the article. Are these appropriate to use for Power BI? Should we always be using the latest versions with Power BI?

![image](https://user-images.githubusercontent.com/1765732/148655519-e6e418a8-d16f-49ce-881f-2f444eadc4b1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP Business Warehouse (BW) Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-sap-bw-connector)
* Content Source: [powerbi-docs/connect-data/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-sap-bw-connector.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. The documentation shows which version is currently supported in Power BI; other updates from external vendors (such as SAP) are not necessarily immediately supported. We update our documentation as support for more recent versions is tested and established.
