### ISSUE TITLE
Reading Properties field from EventHub using streaming dataflow

### ISSUE THREAD

**Issue by domedellolio** [MicrosoftDocs/powerbi-docs#3519]
Hi there,

I would like to know if there is any possibility to read fields different from _Payload_ using streaming dataflow and Event Hub.
Actually we're trying to read _Properties_ field because our application do not contain subject into body, which is stored outside. 
Documentation do not mention anything regards this.

Any clues?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7322cb83-9715-7dca-43f5-43191b867032
* Version Independent ID: 5b7a4cdb-8a4b-9d9b-d2c6-70d54b6ff560
* Content: [Streaming dataflows (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-streaming)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-streaming.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-streaming.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @maikelson
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
