### ISSUE TITLE
SSAS on-premises

### ISSUE THREAD

**Issue by bjarkimg** [MicrosoftDocs/powerbi-docs#352]
Any plans allowing SSAS on-premises connection thru the gateway? 
So we can open live connection to a on-premises SSAS db thru Power BI Gateway?

Thanks

**Comment by arthiriyer** [comment]
@bjarkimg
SSAS is supported via gateway today more information in the link below
https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-ssas

The Direct query option is also available for SSAS.
@kfile FYI

**Comment by bjarkimg** [comment]
Hi, this is the same issue as here:
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/15561135-route-analyze-in-excel-odc-through-power-bi-api?fbclid=IwAR0b4GkU299e73PADC2efIdsZrciKeyzwbK81T5R0tjDKlbPTfWhGzfMoHk

Thanks.

**Comment by arthiriyer** [comment]
@bjarkimg Thanks for clarifying. Ideas.powerbi.com would be the right forum to request new features. Thank you for your feedback.
