### ISSUE TITLE
Missing White Paper content.

### ISSUE THREAD

**Issue by MarcRohde** [MicrosoftDocs/powerbi-docs#3520]
There doesn't appear to be any content in the White Paper section of this doc. There are 'related links' but no content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba640c4-798e-c1f5-0a4d-134334c37e0d
* Version Independent ID: f63ad1a5-01a9-45e4-d4fc-aff071dc9ca1
* Content: [Plan deployment to migrate to Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-migration-planning)
* Content Source: [powerbi-docs/guidance/powerbi-migration-planning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-migration-planning.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by peter-myers** [comment]
Hi @MarcRohde - thanks for your feedback. There is content in this article - perhaps it was a server or browser glitch? Please retry accessing this article. #please-close
