### ISSUE TITLE
Supported data sources for dataflow and dataset rules

### ISSUE THREAD

**Issue by leinoaa** [MicrosoftDocs/powerbi-docs#3523]
Hi!

Is it really so, that data source rules for Premium Capacity aren't supported in deployment pipelines? At least it isn't included in the list "Data source rules can only be defined for the following data sources:".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b120d7-3f8f-8bc7-2987-21dbf1090ff2
* Version Independent ID: 6456d67d-cab6-01e1-3654-4848c5058253
* Content: [Get started using deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @leinoaa . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @leinoaa,

I'm not sure where the statement 'data source rules for Premium Capacity aren't supported in deployment pipelines' comes from.

Can you please explain where you saw this?

Thanks,

Kesem

**Comment by leinoaa** [comment]
Hi!

On this page: https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started#step-4---create-deployment-rules

Under the section "Supported data sources for dataflow and dataset rules" Premium Capacity isn't explicitly stated as a supported data source for which you can define data set rules. And based on my testing & docs the issue seems to be that we are talking about a shared data set and currently those aren't support. Also it was mentioned somewhere in the development pipeline that this support would be added later on. So we'll just have to check back later on and this issue can be closed for now :)

- Anssi

**Comment by KesemSharabi** [comment]
Hi @leinoaa,

Premium capacity isn't a data source. [Premium](https://docs.microsoft.com/power-bi/admin/service-premium-what-is) is a Power BI license that offers more than the free subscription and is aimed at enterprises. Capacity is the type of license you buy and it is divided into [SKUs](https://docs.microsoft.com/power-bi/admin/service-premium-what-is#subscriptions-and-licensing).

Once you purchase a Power BI Premium capacity, you can 'put' on it a wide range of data source, including the ones listed in [Supported data sources for dataflow and dataset rules](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-get-started#supported-data-sources-for-dataflow-and-dataset-rules). However, the capacity itself isn't a data source, it's simply a type of Power BI license.

I hope this helps clarify things,

Kesem
