### ISSUE TITLE
Power BI Operations table anomalies

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [MicrosoftDocs/powerbi-docs#3524]
Hi
duplicates in the Operations Available table on this page:

**Operation name	        Friendly name**
CreateTemplateApp:	Created workspace for Power BI template app
CreateTemplateApp:	Created Power BI template app

**DeleteGoal:	                Deleted Power BI goal
DeleteGoal:	                Deleted Power BI goal**

DeleteTemplateApp:	Deleted workspace for Power BI template app
DeleteTemplateApp:	Deleted Power BI template app
EditDatasetProperties:	Edited Power BI dataset endorsement
EditDatasetProperties:	Edited Power BI dataset properties
ExportReport:	                Exported Power BI report to another file format
ExportReport:	                Exported Power BI report visual data
GetGoal:	                        Retrieved Power BI goal
GetGoal:	                        Retrieved goals of Power BI scorecard

**UpdateDatasourceCredentials:	Updated Power BI gateway data source credentials
UpdateDatasourceCredentials:	Updated Power BI gateway data source credentials**

By design or duplication or multiple functions representing the operation?

The www list is also not aligned with the github repo

https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing
https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/admin/service-admin-auditing.md

Additionally the 'GenerateDataflowSasToken' is a significant operation count in our tenancy and would really like to know what it represents. Some kind of keep alive in dataflows??

Am using table as a reference dictionary of operations. Extremely useful.

Cheers

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the feedback @Chris-Burgess-ACTGOV! I'm assigning a writer to investigate and correct the issues you've flagged. "Deleted Power BI goal" is definitely a duplicate. For the others, I'm not sure as there are some fine nuances - I suspect that the friendly name was updated in UI and added to docs without removing the previous entry. We'll compare to UI and correct - thanks for doing the legwork! The www version is most up to date, so we'll look into why the repo link is showing an older version. Finally, we're continually updating this article and adding details, so will add more info on GenerateDataflowSasToken as soon as we get confirmation from our product team.

**Comment by Chris-Burgess-ACTGOV** [comment]
Thanks @kfollis will monitor and consume as it evolves :)

**Comment by Chris-Burgess-ACTGOV** [comment]
Oh No now im like a dog with a bone. Checking my audit logs the operations below are missing from the www

AddTile
CreateGatewayClusterUser
DeleteTile
EditTile
GatewayClusterSSOTestConnection
GenerateCustomVisualWACAccessToken
GetAllGatewayClusterDatasources
GetAlmPipelinesAsAdmin
GetDataflowUsersAsAdmin
GetDatasetUsersAsAdmin
GetGatewayClusters
GetGatewayClusterStatus
GetGatewayInstallerPrincipals
GetGatewayRegions
GetGatewayTenantPolicy
GetGroupsAsAdmin
GetReportsAsAdmin
InstallTeamsAnalyticsReport
OptInForPPUTrial
PinReportGetUserJoinedTeams
RenameReport
UpdateAccessRequestSettings
UpdateAlmPipeline
UpdateDatasource
UpdateGateway
UpdateGatewayClusterMember
UpdateGroup
UpgradeWorkspace
UpgradeWorkspacesAsAdmin


Hope this helps
CB

**Comment by KesemSharabi** [comment]
Hi @Chris-Burgess-ACTGOV,

Thanks for flagging out the duplications and all the missing operations. I'll do some investigations and try to update the table shortly.

**Comment by KesemSharabi** [comment]
Hi @Chris-Burgess-ACTGOV,

Updating the document is taking longer than expected. Please examine the [Operations available in the audit and activity logs](https://docs.microsoft.com/power-bi/admin/service-admin-auditing#operations-available-in-the-audit-and-activity-logs) section from time to time, as it will slowly get updated.

Thanks and apologies for the length of time these updates are taking.

Kesem

**Comment by Chris-Burgess-ACTGOV** [comment]
Thanks @KesemSharabi appreciate your endeavours.

I do note however that the format of the tables in Ms docs (
Two eg https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources , https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-performance) appears to have changed and as such the web.browsercontents() connector cannot 'find' the embedded tables - so can no longer ingest. This appears to be same on multiple sites.

Is this new www design or css/html oversight or a fault in the web.browsercontents()?

Cheers
Chris
