### ISSUE TITLE
Snowflake Connector Snowflake Driver

### ISSUE THREAD

**Issue by antrogers** [MicrosoftDocs/powerbi-docs#3525]
Hi, this page does not reference the requirement to install the Snowflake ODBC driver? I'm trouble shooting with a colleague and I'm not entirely sure it's still required? 

Original posts indicated it was required: https://powerbi.microsoft.com/en-au/blog/power-bi-enables-connectivity-to-snowflake/

If no longer required for current version it'll probably be useful to include a reference to the versions for which it is required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @antrogers . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks.
