### ISSUE TITLE
link to "Try asking the Power BI Community"

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3526]
Under "Next steps", the link to "Try asking the Power BI Community" should direct to https://community.powerbi.com/t5/Desktop/ArcGIS-Maps-for-Power-BI-Preview-Discussion/td-p/72947

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Interacting with an ArcGIS map that has been shared with you - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @rootsmusic . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi again @rootsmusic :-)
Thank you for pointing that out.  I've updated the article and set it to republish tomorrow.
