### ISSUE TITLE
Should the multi-geo feature be used for disaster recovery?

### ISSUE THREAD

**Issue by assaf-grth** [MicrosoftDocs/powerbi-docs#3529]
Should the Multi-Geo support for Power BI Embedded be used for disaster recovery purpose?
It means that if I have an application which is spread across two regions, both regions should contain the embedded resource configured with the multi geo feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b52b044c-543a-212c-a8e3-db0871826713
* Version Independent ID: 3ee2c29b-5559-3396-4757-7ae3c236a909
* Content: [Multi-Geo support for Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-multi-geo)
* Content Source: [powerbi-docs/developer/embedded/embedded-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @assaf-grth. I’ll look into this and get back to you.

**Comment by mberdugo** [comment]
Hi @assaf-grth, sorry for the delayed response.
This is the answer I received:
Multi-Geo is for compliance (data residency), and performance.
Multi-geo is not necessary for Disaster recovery. 
Power BI automatically takes care of high availability, failover and disaster recovery. 
See  [Power BI high availability, failover, and disaster recovery FAQ](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-failover).
I hope this helps.

**Comment by assaf-grth** [comment]
Hi @mberdugo thank you for the details
My question is about the power bi embedded service, not power bi
The embedded resource is a resource I configure in my subscription for usage in power bi
Are they the same as far as I concern?

**Comment by mberdugo** [comment]
Hi @assaf-grth. The differences in responsibility for the service, versus Premium are described [here](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-failover#am-i-responsible-for-the-availability-of-my-power-bi-solution-). I believe that answers your question.

If it doesn't, you can also find help in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
