### ISSUE TITLE
Step 3 - link is broken

### ISSUE THREAD

**Issue by PhilStollery** [MicrosoftDocs/powerbi-docs#353]
Follow the link: https://portal.office.com/Start/Confirm?Sku=a403ebcc-fae0-4ca2-8c8c-7a907fd6c235&ru=https%3A%2F%2Fapp.powerbi.com%3FredirectedFromSignup%3D1%26noSignUpCheck%3D1 

It no longer works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f747f-9b4f-2bfc-831e-ed8232177d38
* Version Independent ID: b2da371d-aea3-010b-5e57-a6c8d5a9646d
* Content: [Signing up for Power BI with a new Office 365 Trial - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial)
* Content Source: [powerbi-docs/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@PhilStollery -- thanks for the feedback, looking into this now

**Comment by mgblythe** [comment]
I updated the link in the doc. Thanks for the feedback!
