### ISSUE TITLE
Example of how to limit the rows in the table

### ISSUE THREAD

**Issue by welyson1** [MicrosoftDocs/powerbi-docs#3530]
[**Table**
Values: Virtualization (data windowing) by using Window of 500 rows at a time
This topic needs more clarification, maybe even an example. The limitation in the table is necessary for cases where you want to export only X rows]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54c8354c-2d95-1329-7c28-79f3cb3c3c89
* Version Independent ID: ccd2bbae-a4d2-b3dd-3f00-509c099faaba
* Content: [Large datasets, data point limits, and data strategies - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-data-points#strategies-and-data-point-limits-by-visual-type)
* Content Source: [powerbi-docs/visuals/power-bi-data-points.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-data-points.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mberdugo** [comment]
Thanks for your comment and suggestion, @welyson1. 
I've assigned this issue to the doc author for review.

**Comment by mihart** [comment]
Hi @welyson1 ,
Thank you for your suggestion.  I've contacted the PM and will add the info when they respond.

**Comment by mihart** [comment]
Hi @welyson1 ,
I heard back from the PM and the short answer is "no."  Report authors cannot force a data limit on Table rows when exporting data to Excel. And here is additional data he supplied:
As a brief background on data limits, Table visual has a limit of 500 rows at a time (aka. Windowing). This allows the Table to “load more data” by scrolling beyond the first 500 rows. Other Visuals have “Top x data points”, disallowing scrolling. E.g. Matrix Columns has a Top 100 instances of Column grouping.
Generally, data limits per visual are hard-coded. Power BI doesn’t allow authors to control them.

I hope that this answers your question.
All the best
the DOCS team
