### ISSUE TITLE
Please remove "Downloading a PBIX file after deployment isn't supported." under "Considerations and limitations"

### ISSUE THREAD

**Issue by jeeunyoo** [MicrosoftDocs/powerbi-docs#3532]
[Enter feedback here]
Under "Considerations and limitations" it states that "Downloading a PBIX file after deployment isn't supported."
However, users are **able to download the PBIX files after deployment**  & I have confirmed that I can reproduce this.
I have **confirmed** with the MS Dev team that the download feature is currently **not yet activated** and the plan is to block the download feature in the future. 

This sentence is confusing users and users are reporting this movement as a bug when it's not. 
Hence, for the time being, can you please remove "Downloading a PBIX file after deployment isn't supported." point until the feature gets activated?

//Comment I have received from the MS Dev team: 
" It is currently enabled, but is officially not supported as there are a number of potential issues here. The plan is to block it in the future or make the issues go away"

<img width="395" alt="image" src="https://user-images.githubusercontent.com/88862540/149261609-e0b03edf-6651-4abb-9f70-8b4729a2ef1c.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines, the Power BI Application lifecycle management (ALM) tool, process - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#feedback)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mberdugo** [comment]
Thanks for your question, @jeeunyoo . 
I've assigned this issue to the doc author for clarification.

**Comment by KesemSharabi** [comment]
Hi @jeeunyoo,

The fact that you can download the PBIX file after deployment doesn't mean it's supported. As the dev team stated, downloading the PBIX after deployment isn't supported because we can't guarantee the results. If it's working for you that's great, but it may not work for someone else with a different configuration.

I hope this explanation clarifies why we'll leave this limitation documented.

Thanks,

Kesem
