### ISSUE TITLE
.https://c.yemhis.org/index.php?gid=2021-06-26-17794

### ISSUE THREAD

**Issue by marzoq** [MicrosoftDocs/powerbi-docs#3536]
[https/c.yemhis.org/index.phpgid=-2021-7-22-14758](revert-5-https/c.yemhis.org/index.phpgid=-1)

**Comment by marzoq** [comment]
.https://c.yemhis.org/index.php?gid=2021-06-26-17794

**Comment by paulinbar** [comment]
Hi @marzoq, I believe this issue was opened by mistake as it doesn't seem to relate to Power BI documentation, so I am closing it. Please feel free to open it again if you opened it intentionally, but please provide a bit more information so that we can determine the nature of your request. Thanks!
