### ISSUE TITLE
Incomprehensible!

### ISSUE THREAD

**Issue by Quorthon1965** [MicrosoftDocs/powerbi-docs#3539]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deda0833-832f-1984-4ca3-1b59b93bfc58
* Version Independent ID: 78c23031-0096-8c95-e693-73c2ccbbc70d
* Content: [Query folding guidance in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/power-query-folding)
* Content Source: [powerbi-docs/guidance/power-query-folding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/power-query-folding.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by peter-myers** [comment]
Thanks @Quorthon1965 for the feedback. We’re closing this issue as there’s nothing specific to address, but will consider your sentiment in our next update. #please-close
