### ISSUE TITLE
Limitations and considerations

### ISSUE THREAD

**Issue by edwarsco-oregonstate-edu** [MicrosoftDocs/powerbi-docs#354]
"Installing an Analysis Services Power Pivot mode instance lets you work with Excel workbooks that are using Power Pivot"  We have this working using an OOS.  However, we can't figure out how to schedule the Power Pivot refresh like you can with SharePoint.  https://docs.microsoft.com/en-us/sql/analysis-services/power-pivot-sharepoint/power-pivot-data-refresh-with-sharepoint-2013?view=sql-server-2017#bkmk_scheduled_refresh

Are Excel Power Pivot refreshes a limitation of Power BI Report Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90025eee-cd72-9503-6c1d-c14bb617b5b4
* Version Independent ID: 58e25db4-5d25-ac1d-b763-72d27e943373
* Content: [Host Excel workbooks using Office Online Server (OOS) - Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/excel-oos#using-effectiveusername-with-analysis-services)
* Content Source: [powerbi-docs/report-server/excel-oos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/excel-oos.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by davidiseminger** [comment]
Thanks for your comment, @edwarsco-oregonstate-edu . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by markingmyname** [comment]
@edwarsco-oregonstate-edu   Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@edwarsco-oregonstate-edu Correct, today you cannot refresh workbooks with PP models in them. However, we are aware of this limitation and looking into it.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
