### ISSUE TITLE
Does guidance around incremental refresh still apply if Power Platform Dataflows connector is used?

### ISSUE THREAD

**Issue by LastThird** [MicrosoftDocs/powerbi-docs#3542]
Under [Considerations for when not to set incremental refresh](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features#considerations-for-when-not-to-set-incremental-refresh)...
> Do not set a dataflow to incremental refresh in the following situations:
> 
> - Linked entities should not use incremental refresh if they reference a dataflow. **Dataflows does not support query folding** (even if the table is DirectQuery enabled).

...Does this guidance still apply now that the Power Platform Dataflows connector supports query folding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Premium features of dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-features#feedback)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-premium-features.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your question, @LastThird 
I've assigned this issue to the doc author for review.

**Comment by LastThird** [comment]
I can actually confirm that it *does* work, because I've been doing it 😉

**Comment by davidiseminger** [comment]
Thanks for your comment, and the clarification. I've updated the documentation to reflect the current behavior. The update should be reflected in the documentation in the next day or so. Thank you!
