### ISSUE TITLE
Ambiguous Refreshing

### ISSUE THREAD

**Issue by Jason-ky-c** [MicrosoftDocs/powerbi-docs#3543]
Hello,

I find the article ambiguous with the refreshing.

The article states the following can be refreshed for Business User:

- Dashboard
- Report

The following can't be refreshed or not explicitly stated for Business User:

- Apps
- App workspace
- Datasets.

My problem is I would like to give Business Users the freedom to refresh manually the report with updated values. Which supposedly they can do, but they can't update the underlying values as it sits in the Datasets. Which is where I find it's ambiguous - they can refresh the dashboard and report but not the data itself. 

Is there a work around where I can provide to my team members the ability to refresh the underlying values that build the report? This is not described anywhere as I can see. I tried to use microsoft flow to help circumvent this issue, but it's not working as I assume the permissions don't extend that far for them to allow them to manually refresh data when needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with free licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mberdugo** [comment]
Thanks for your comment, @Jason-ky-c 
I've assigned this issue to the doc author for review and clarification.

**Comment by mihart** [comment]
Hi @Jason-ky-c ,
Refreshing definitely is a complex topic and I'll try to clear up ambiguity in the articles. To answer your question about a workaround, you might find a solution in the Power BI Community, at https://community.powerbi.com. You may also be able to contact Support (refer to this article: https://docs.microsoft.com/en-us/power-bi/admin/service-support-options to review available Support options.)
