### ISSUE TITLE
Unable to view a dataflow or dataset in VIEWER role.

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3544]
The viewer workspace role indicates that View and Interact with an item is permissible, however, dataflows and datasets are not viewable in Power BI Service. - https://powerbi.microsoft.com/fr-ch/blog/announcing-the-new-viewer-role-for-power-bi-workspaces/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mberdugo** [comment]
Thanks for your comment, @rjagdon 
I've assigned this issue to the doc author for review and clarification.

**Comment by rjagdon** [comment]
May I follow up on this?

**Comment by maggiesMSFT** [comment]
Hi, @rjagdon -- are you asking if you can provide more information, or if we can provide more information? If the former, please do! If the latter, we're working on it.
Thanks!

**Comment by rjagdon** [comment]
Thanks for working on this. I am looking for further information. Will wait for your outcome.
