### ISSUE TITLE
[Japanese ver] The chart of the limitations that are dependent on the capacity size is old

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3547]
Hi authors,

Greetings!
The chart of the limitations that are dependent on the capacity size is old.
There is information of model refresh parallelism in Japanese ver.

// English ver
![image](https://user-images.githubusercontent.com/73410575/150627671-4845ff3f-0e3d-49d2-8044-69362ff74825.png)

// Japanese ver
![image](https://user-images.githubusercontent.com/73410575/150627691-e0422fc5-0fe5-4627-8bfb-394fd66710f1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3d17a8-8258-5246-24bb-b69c273d06c4
* Version Independent ID: 36f06d1c-4f46-598d-c300-eb4dd22d4487
* Content: [What is Power BI Premium Gen2? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is#limitations-in-premium-gen2)
* Content Source: [powerbi-docs/admin/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @Hyamyam, yes, it looks like the translated versions (not only the Japanese version) haven't yet been updated with recent changes to the article. I am forwarding your comment on to the owner of the doc for consideration. Thanks for calling our attention to the issue!

**Comment by Hyamyam** [comment]
Thanks @KesemSharabi 

I've checked the description is revised in Japanese.
one more thing, recently the description has been updated in English.

![image](https://user-images.githubusercontent.com/73410575/151455668-16c46f72-96ea-486a-911d-e842cb634972.png)

"Analysis Services" to "dataset workloads"

but the description is old in Japanese.
I recommend the description should change from "Analysis Services" to "データセットのワークロード"
![image](https://user-images.githubusercontent.com/73410575/151455769-5cbd63d8-afc0-4a72-b19e-16d69bec8a4c.png)

Thanks,

**Comment by KesemSharabi** [comment]
Hi @Hyamyam,

Translating articles from English to other languages may take time. I suggest that you revisit this page at a later time to check if the updates have been translated.

Thanks,

Kesem

**Comment by Hyamyam** [comment]
Hi @KesemSharabi ,
Thank you for your answer. got it.
I'll wait the translation is updated.
