### ISSUE TITLE
Display a left-formatted string in Power BI leads to the "To turn on Q&A..."

### ISSUE THREAD

**Issue by DougAtClir** [MicrosoftDocs/powerbi-docs#3548]
I am trying to dispay left-formatted postal address as text in Power BI.  This should be a straight-forward task.  This is turning into a major effort.  First: we had to create a custom view in our database because DAX text functions could not find text columns in our database.  Second: The only visual that supports text is a "Card" that cannot display left-justified text.  If we try to add the string to a text box with the "+ Value", we get the "To turn on Q&A, we need to create a local index of your data...".  How do you do this in Power BI Desktop.  

We have spent hours on what should be a very basic task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fe9672-0cf8-7566-6f4b-49991f9aba3f
* Version Independent ID: fd7ecaee-3d87-272c-713b-03b446008cfc
* Content: [Use Q&A with live connections in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-q-and-a-direct-query)
* Content Source: [powerbi-docs/create-reports/service-q-and-a-direct-query.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-q-and-a-direct-query.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @DougAtClir. Thanks for providing the context of what you were trying to do. I am forwarding your comment on to the doc owner so that they can figure out how best to address the issue you raised.

**Comment by Ruebyn** [comment]
Hi  @DougAtClir  Had the same issue, found that if I drop a Q&A visualisation onto the page it then gave me to option to activate in report.  Once that was done the "+ Value " worked fine.

**Comment by paulinbar** [comment]
Hi @DougAtClir and @Ruebyn,  I think more formatting options have been added to visualizations. If you are sill having problems with the issue you mentioned, I would try the [Power BI Community](https://community.powerbi.com/)
 or our [support page](https://support.powerbi.com/). Closing this issue here now, but feel free to reopen if necessary. Thanks!
