### ISSUE TITLE
link for Power BI Community

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3551]
Under "Next steps", the link should be https://community.powerbi.com/t5/Custom-Visuals-Development/bd-p/CustomVisualsDevelopmentDiscussion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17ef433-9857-720a-bb18-66897b27a44e
* Version Independent ID: 6ded7bc0-6f88-272f-7735-0a9e33d78c81
* Content: [Developing custom visuals in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/develop-power-bi-visuals)
* Content Source: [powerbi-docs/developer/visuals/develop-power-bi-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/develop-power-bi-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by paulinbar** [comment]
Hi @rootsmusic, thanks for suggesting the more accurately targeted link. I am forwarding it on to the doc owner.

**Comment by mberdugo** [comment]
Thank you, @rootsmusic, for bringing this link to my attention. I've replaced it and it should be live in a few days.
