### ISSUE TITLE
PowerBI datasource Reference to REST API output (datasource Type)

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [MicrosoftDocs/powerbi-docs#3552]
Hi Team
am consuming the 'definitive list' of Power BI datasources and want to marry them up to the datasource information that i extract using the Admin REST API's .
I can then provide more context and intel around connection and datasource issues and the like.

Unfortunately the Data Sources in the  web list dont necessarily align with the 'datasources.datasourceType' that the API's produce:

eg1 API produces 'AzureBlobs' while the list provides 'Azure Blob Storage'
eg2 API produces 'Exchange' while the list provides 'Microsoft Exchange'
These are simple examples and easy to align, most others are somewhat more esoteric. 

A manual mapping exercise is open to guesswork and mandraulic error!!

Could you consider adding API column to the list that shows the associated datasource datatype? 
Or point me to a repo that has the the list of plain english datasources and associated REST API datasourceTypes?

Cheers

Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @Chris-Burgess-ACTGOV, I am forwarding your request along to the doc owner for further consideration. Thanks for reaching out to us!

**Comment by Chris-Burgess-ACTGOV** [comment]
Thanks @paulinbar 
@davidiseminger there may be an anomoly in the 'web' datasource type - gateway (required) should be 'no'?

Cheers
Chris

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support or feature request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by Chris-Burgess-ACTGOV** [comment]
Hi @davidiseminger 
I guess it is a feature request for the documentation meta. 
If i raise a ticket it will come to you for consideration to add a column for 'REST API' name into https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources content will it not?
Or are you angling that the API response should be amended to align with the published documentation?

Cheers

Chris
