### ISSUE TITLE
It should be 'Premium per Capacity' not 'Premium capacity'

### ISSUE THREAD

**Issue by Mardurolla** [MicrosoftDocs/powerbi-docs#3553]
This is a suggestion for improving the wording in order to help with the understanding and logic of the text. Where you state 'A PPU license does not allow for e-mail subscriptions to external users. The content must be hosted in a **Premium capacity** to subscribe external users.' you must have meant to say 'Premium **_per_** **C**apacity' as in the name of the License type (not the mental of physical ability is the English definition of 'capacity'). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4810006b-6245-ccd5-0d2d-9b1089eb06ab
* Version Independent ID: fe970573-f765-75dc-048e-40ef64cf4285
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq?WT.mc_id=365AdminCSH_capaedac-powerbi)
* Content Source: [powerbi-docs/admin/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @Mardurolla -- I'm pretty sure it's correct as is. We use that wording, "Premium capacity," literally 595 times in 183 different files. A capacity needs to be a "Premium capacity" to support Premium features. 
Assigning to the author for visibility.
Thanks!

**Comment by Mardurolla** [comment]
> 

That’s OK Maggie, 
I was just pointing it out to help with understanding the products, not least to myself. It’s not the only place and time when product names make things really confusing. I was a “Microsoft Select” admin myself, in MS Dublin (Leopardstown) back in 1994-’95. I then successfully but arduously convinced the company that I’ve been with for 14 years in late ‘90’s to 2012 to stay on ‘Software Assurance’ and all the other names it was given later. It was for a branch of a global automaker, that “traded” independently as a supply chain mid-supplier. As a result, I stayed away from the “Global IT policies” and managed to keep everything on “latest version.” My management did not appreciate it, but when they would visit other countries around the world, they would be impressed the locals with all the security and, above all, functionality that my line managers had at their disposal on their laptops [thanks to me in my view]. I left and they are still on all the old versions and not even migrated to 365. [mind you they shut down production here too]. I then worked for several other global Orgs. And believe you me, management get furious when you start trying to explain licensing and all the software layering needed. “You just want to play with gimmicks;” “we can’t afford to upgrade [S.I.C.]; “why do you need to research so much what products and how to use them if you’re such an expert;” “just ask them how much is it going to cost and have done with it;” or “I don’t want to hear about Active Directory.” And every other cliché which every company spits out at every level and department when it comes to the four letter word “upgrade/update” in their [basic] understanding of “computers.” I even had to walk away from a “dream job” in terms of work at hand because of such clichés.

I now plan to advise and deliver consulting and development in all things Tabular AS, DAX Power BI etc. So, I have been trialling [fka Office] 365 since 2012 and all the iterations of ‘Power BI’. I was one of the first to use Office 365 “Pro” specifically to try Power BI Service (as it was then called unofficially) in all its monthly updated glory. Then that functionality vanished so I migrated to ‘MS 365 Business Standard’ with ‘Power BI Pro,’ paid as two separate products. I then recently migrated to ‘MS 365 Premium’ to explore the Azure admin functionality, etc. Now I want to migrate from [with] ‘Power BI Pro’ to [with] Power BI Premium. However, even a few months ago one could get excellent support from a Live Chat and person. All last week I’ve tried your latest bot assistants which have been hopeless. So I had to read the fine print which is when I run into that page. BTW there are other passages that look like grammatical mistakes or bad logic on that page. I am just saying is a positive and helpful feedback. So, I don’t really care if you take it in a defensive stance.) On ”the fine print” [ two PBI’s with the word Premium. PPU (per user) and PBI Premium “Per capacity.”  I am beginning to understand that ‘Per capacity’ is to avoid having to license each consumer user per user (a bit like the “anonymous CAL’s” were supposed to work, for SQL and Windows Pro in the 2000’s, which was so confusing that your LAR that I was using and MS Reading never managed to explain). I am beginning to “get it” that for me to trial XMLA and other interfaces, plus Azure type of Datastore connections, I need, at least the PPU license, but not the ‘per’ capacity license. This is where the word “capacity [as in being empowered to perform activity]” is apt for my situation. The word ‘per’ should be used, in my humble opinion, to differentiate the two PPU and ‘Power BI “Premium” licenses. For people like me at least. Either way, neither you nor the entire community will ever have the capacity (allow me throw this cheeky dig or pun… ) to alleviate the challenges of explaining licensing to management. Not in a thousand years. But don’t get me wrong, what you all are doing on the MS.Docs site is really good and outstanding. I have been referring to it a lot these last several months.

**Comment by maggiesMSFT** [comment]
Hi, @Mardurolla -- thanks so much for taking the time to write up your explanation! I'm reopening this issue so the author @KesemSharabi sees it. Once it's closed, it might fall off his radar.

**Comment by Mardurolla** [comment]
Thank you. I was going to remove my reply this morning, for being too long and crabby. I left it for now as you seem to say that it may be useful. Otherwise, please take it down. In general, I would make sure that nouns and verbs used for naming products [or functionality], are kept clearly distinct from when they are used for their actual meaning. I admired the most wonderful [American] technical writer for MS in Leopardstown back in 1994. So, I know how much effort you put into it. Still the paragraph “Any datasets that reside in a Premium Per User (PPU) workspace are not viewable by users without a license […] using Publish to Web behaves the same way it does with content hosted in a Premium capacity[.],” for example, is very difficult to understand.
