### ISSUE TITLE
Missing Known Limitations

### ISSUE THREAD

**Issue by andrewtuplin** [MicrosoftDocs/powerbi-docs#3555]
- Python Script source isn't supported by the Power BI Enterprise Data Gateway, so if you'd like to use this feature, don't count on being able to keep your data refreshed.  This is pretty massive limitation. 

- Deploying to Power BI Service is incredibly slow. Typically publishing reports doesn't take a ton of time (20-30 seconds). I have a very small report getting about 200 rows from a Python Script source and it take about 25 minutes to publish to Power BI Service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-scripts)
* Content Source: [powerbi-docs/connect-data/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by maggiesMSFT** [comment]
Hi, @andrewtuplin -- thanks for your feedback! Assigning to the author to review.

**Comment by otarb** [comment]
Hello @andrewtuplin 

- When refreshing data, Power BI On-Premise Gateway is for Power BI Service getting On-Premise data sources like databases, OData, ODBC, web, etc. However, for R script, it's not a specific data source. You can only use Personal Gateway to make Power BI Service get your On-Premise server and assign an account with relevant permission to execute the R script.

- Can you share more details? How big is the report file? Are you saying that report without Python script is published in <30 seconds but same report with added script consistently takes 25 minutes to be published?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @andrewtuplin.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
