### ISSUE TITLE
Sample data set for drill down example

### ISSUE THREAD

**Issue by ALau2088** [MicrosoftDocs/powerbi-docs#3556]
Hi, could you provide the sample .pbix file used in the example for explaining drill down here https://docs.microsoft.com/en-us/power-bi/consumer/end-user-drill so I can follow along by working through the example?

**Comment by maggiesMSFT** [comment]
Hi, @ALau2088 -- good question! I can't tell by looking at the images. Assigning to the author to help out. 
Thanks!

**Comment by ALau2088** [comment]
@maggiesMSFT @mihart - Hi there. Just wanted to follow up on this. Thanks!

**Comment by mihart** [comment]
Hi @ALau2088 , 
Thank you for your question. We're about to change the way drilling works and will be updating the article.  When that happens I'll see if I can add a link to the sample being used.  In the current version, the sample came from a PM who did not save it.   
All the best,
The DOCS team
