### ISSUE TITLE
Power BI Dataflows are accessible in Power BI Desktop even without workspace access

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3557]
Even without viewer access, you can still access the PBI dataflows data and use it for reporting. It looks like a security issue. However, you cannot perform a refresh using the same credentials. It looks like a security issue.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @rjagdon . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rjagdon, I am closing this issue now as it seems like a product issue rather than a docs issue. If this behavior is still true, I suggest you open a bug at https://support.fabric.microsoft.com/support//. Thanks!
