### ISSUE TITLE
Good, but insufficient information

### ISSUE THREAD

**Issue by m-hn** [MicrosoftDocs/powerbi-docs#3558]
[Enter feedback here]
Something that should be simple is not - I'm looking to embed a PBI report for distribution - The document does not explain how to do this in Outlook, or Yammer, or Teams. While these are not PBI issues, the user's problem has not been solved here. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-secure)
* Content Source: [powerbi-docs/collaborate-share/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @m-hn . This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @m-hn , I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
