### ISSUE TITLE
Clarification with 'continue the deployment' message

### ISSUE THREAD

**Issue by nathanwlee1** [MicrosoftDocs/powerbi-docs#3559]
Hi

I have a question relating to the 'continue the deployment' message, a customer is raising an issue with this message continuing to show in an infinite loop (i.e. when they press continue it continues to display)

I am confused by the wording in the docs here,  
_"If you continue with the deployment, you'll loose the data in the target stage. You can use this option if the changes you made to the dataset were intentional. After the deployment completes, you'll need to refresh the target dataset."_
Suggests that the dialogue disappears and then the user will need to manually refresh the target dataset. This is the behaviour I would expect

However, in the below paragraph -
_"After a deployment fails due to schema changes, the target stage displays the Deployment failed message, followed by the Show details link. The link opens the same continue the deployment message that was displayed during the failed deployment."_
Suggests that it will continue to show

Can you clarify?

https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting#why-am-i-getting-the-message--continue-the-deployment--

![image](https://user-images.githubusercontent.com/60522406/151188155-21c798d7-012e-4012-9030-5bc7b7b889c9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c40e327-d8c8-3011-e68b-7694d0ed2b04
* Version Independent ID: 3947ee9f-58b0-763c-8b56-b21cfdcbaac1
* Content: [Troubleshoot deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting#why-am-i-getting-the-message--continue-the-deployment--)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-troubleshooting.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-troubleshooting.yml)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @nathanwlee1,

I started an email thread for this.

Thanks,

Kesem
