### ISSUE TITLE
Missing Bing Maps Tenant setting

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#3560]
This article should include the Bing Maps tenant setting announced here:
https://powerbi.microsoft.com/en-us/blog/power-bi-november-2021-feature-summary/#post-17912-_Toc87473943

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mberdugo** [comment]
Thanks for your suggestion, @GitWesDone  
I've assigned this issue to the doc author for review and consideration.

**Comment by paulinbar** [comment]
Hi @GitWesDone, thanks for calling this out. I am adding a section for this in the integrations settings article (https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal-integration). Update should be out tomorrow. It won't have much content besides what's included in the switch itself, but we'll see what else there is to provide. Thanks!
