### ISSUE TITLE
OData feed URL not working

### ISSUE THREAD

**Issue by KrishnamrajuNalimela** [MicrosoftDocs/powerbi-docs#3562]
Hello Team,

The mentioned OData feed URL in one of the screenshot is not working in this page. The updated link is "https://services.odata.org/v2/northwind/northwind.svc/" 

Kindly check and update the page/screenshot.

Thank you,
Krishnamraju
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29bfbd4c-5149-93be-3982-81af6852a5dd
* Version Independent ID: 75460ed0-c7d9-fe67-8010-b843661dc66e
* Content: [Connect to an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-odata)
* Content Source: [powerbi-docs/connect-data/desktop-connect-odata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-odata.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. I've added a note just below that image, letting people know that the link may change from what's in the image, including the current link. That should have better longevity. Thanks!

**Comment by KrishnamrajuNalimela** [comment]
Thank you for the update.

Regards,
Krishnamraju
