### ISSUE TITLE
Please add more detail on what will happen in the azure subscription associated with Premium capacity auto scale 

### ISSUE THREAD

**Issue by wetnurseyang** [MicrosoftDocs/powerbi-docs#3563]
Understand the need of an azure subscription when configuration PBI Premium capacity Gen 2 auto scale. But can we provide more detail of what azure resource would be created there when auto scale happens, anything customer should do or shouldn't do against the resource?

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5331ed60-1d4a-dbef-1ec6-b9ca9de05e57
* Version Independent ID: bc5c01f8-67e1-6395-b079-12de4be557b0
* Content: [Using Autoscale with Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-auto-scale)
* Content Source: [powerbi-docs/admin/service-premium-auto-scale.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-auto-scale.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @wetnurseyang. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @wetnurseyang,

Thanks for identifying this gap!

I updated the procedure in [Configure an Azure subscription to use with Autoscale](https://docs.microsoft.com/power-bi/admin/service-premium-auto-scale#configure-an-azure-subscription-to-use-with-autoscale), and added a clarification note to [Enable Autoscale in the Power BI Admin portal](https://docs.microsoft.com/power-bi/admin/service-premium-auto-scale#enable-autoscale-in-the-power-bi-admin-portal).

Hope this helps,

Kesem
