### ISSUE TITLE
Not all imported visuals work with the new format pane

### ISSUE THREAD

**Issue by rbakerpage** [MicrosoftDocs/powerbi-docs#3566]
I was unable to change the number of rows and columns on the chiclet slicer 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @rbakerpage, thanks for reaching out to us with your comment. I believe the Chiclet slicer is a Microsoft-developed custom visual, is it not? Yes, I can see that it might be helpful to know which properties can't be edited, both for the out-of-the-box visuals and also for custom visuals. In any event, I am forwarding your feedback on to the owner of the article for further consideration. Thanks again for your feedback!

**Comment by maggiesMSFT** [comment]
Hi, @rbakerpage -- thanks for asking! I just installed the cliclet slicer to check it out. I can change rows and columns -- it's under General in the Format pane.
![image](https://user-images.githubusercontent.com/12401230/151869276-bd018141-7819-4563-83ee-56da783c0412.png)
Hmmm, I am using the Feb 2022 version of Power BI Desktop, 2.102.243.0 64-bit (February 2022). That may not be publicly available, but if not, it will be coming soon!
Hope that helps!
