### ISSUE TITLE
Azure Storage Security Documentation is Confusing

### ISSUE THREAD

**Issue by JoelLeichty** [MicrosoftDocs/powerbi-docs#3567]
Comments after spending a month trying to make this work:

> The user must have Azure Blob Data Contributor role, and an Storage Blob Data Owner role at the storage account level.

1. There doesn't seem to be any documentation about an "Azure Blob Data Contributor" role, nor could we find it in the Azure Portal.
2. The sentence structure above is kind of a mess and can be read in many different ways. The user needs two roles? Both roles related to the storage account, or one role is related to the user? Also "an storage".
3. At the end of the day, nothing seemed to work except granting the user "Owner" level access (and Storage Blob Data Owner?). Kept getting "Access denied" error. I have no idea if this error is because of a bug or because we couldn't figure out the right roles to assign.

Then, when trying to reconcile this sentence, also have to deal with this one:

> To bring your own ADLS Gen 2 account, you must have Storage Blob Data Owner permissions at the storage account layer. Permissions at the resource group or subscription level will not work. If you are an administrator, you still must assign yourself Storage Blob Data Owner permission. **Currently not supporting ADLS Gen2 Storage Accounts behind a firewall.**

1. Some of this seems logical, why is it separate from the other security instructions sentence?
2. What does a firewall have to do with assigning security?
3. This one never mentions "Azure Blob Data Contributor" role.

> Attaching a dataflow with ADLS Gen 2 behind multifactor authentication (MFA) is not supported.

1. I don't know what this means but trying to research all the other security stuff this was confusing. You're logged in as a user, but I think it's talking about the ADLS settings, not the user's settings MFA settings. It added confusion when getting errors.

Thanks!

Joel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @JoelLeichty.

I've assigned this issue to the doc author for review.

**Comment by JoelLeichty** [comment]
Would be good to get this sorted. I bet a lot of people deal with the "Access Denied" error.

**Comment by davidiseminger** [comment]
We've updated the article and the product, sorry for the confusion.
