### ISSUE TITLE
Using custom connector with Dataflow produces "Path is invalid" and "There was an error in the OAuth popup window"

### ISSUE THREAD

**Issue by jgibbycsc** [MicrosoftDocs/powerbi-docs#3568]
If Custom Connectors are not supported in Dataflows, please state that in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 137ea074-f635-5cd9-6e94-f6bc12ac2452
* Version Independent ID: 4ce609b2-adfa-8575-4e4a-9cc285028043
* Content: [Use custom data connectors with the on-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-custom-connectors)
* Content Source: [powerbi-docs/connect-data/service-gateway-custom-connectors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-custom-connectors.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jgibbycsc.

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks.
