### ISSUE TITLE
Sensitivity Label

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3570]
According to documentation, Sensitivity Labels are inherited for items meeting the following conditions :
1.	A new item is deployed
2.	An item is deployed to an empty stage
3.	The source item has a label with protection and the target item doesn’t. There is a pop-up window asking for consent to override the target label.

Based on testing, even if conditions 1 and 2 are met, the Sensitivity Labels are not inherited for dataflows. Reports and datasets work just fine.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines, the Power BI Application lifecycle management (ALM) tool, process - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#item-properties-copied-during-deployment)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @rjagdon,

Thank you for this information, I'll investigate further and change the document if that is needed.

Kesem

**Comment by KesemSharabi** [comment]
Hi @rjagdon,

As this is being investigated by our engineering team, I'll close this GitHub issue.

Thanks,

Kesem
