### ISSUE TITLE
Power BI Embedded Support for BYOK

### ISSUE THREAD

**Issue by floemmel** [MicrosoftDocs/powerbi-docs#3571]
As far as I know, Power BI Embedded capacities are also supported by BYOK. However this is not stated anywhere in the documentation. It would be great if you could amend this. 

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9a86dc-4be4-d0a2-644d-cb20e3af74fb
* Version Independent ID: d08af8bc-fb3e-e443-7152-abaa0f2df6cc
* Content: [Bring your own encryption keys for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-encryption-byok)
* Content Source: [powerbi-docs/admin/service-encryption-byok.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-encryption-byok.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mberdugo** [comment]
Thanks for your comment, @floemmel. 
I've assigned this issue to the doc author to look into.

**Comment by davidiseminger** [comment]
Thank you for your comment, we'll look into that!
