### ISSUE TITLE
Question about data refresh when migrating from Gen1 to Gen2

### ISSUE THREAD

**Issue by jopebeni** [MicrosoftDocs/powerbi-docs#3574]
Question about data refresh when migrating from Gen1 to Gen2
    
During the switch from Gen 1 to Gen 2 premium, what is the impact on refreshes that are active at that time? Will the migration wait for all active refreshes to complete or kill any active refresh operations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7d18dd-7459-baea-2c12-fc47ffcd9b11
* Version Independent ID: 42220c7a-465b-2da2-3014-0aecd9631142
* Content: [Power BI Premium Gen2 FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-faq)
* Content Source: [powerbi-docs/admin/service-premium-gen2-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mberdugo** [comment]
Hi, @jopebeni. Thanks for your question. 
I've assigned this issue to the doc author for review. 

In the meantime, you might find an answer in the [Power BI Community]( https://community.powerbi.com).

**Comment by KesemSharabi** [comment]
Hi @jopebeni,

I double checked this with the engineering department and can confirm that during the migration from Gen1 to Gen2, there should be no impact on data refresh.

Hope this helps,

Kesem
