### ISSUE TITLE
Spelling: presistProperties should be persistProperties

### ISSUE THREAD

**Issue by jlukosky** [MicrosoftDocs/powerbi-docs#3575]
Small item: the word "presistProperties" should be spelled persistProperties.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4c3363-db7e-fa34-3ade-dc56ab85fbdd
* Version Independent ID: 71959fd9-4aff-cec0-9f14-93ae3923d8be
* Content: [Power BI visual interactions - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-visuals-concept)
* Content Source: [powerbi-docs/developer/visuals/power-bi-visuals-concept.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/power-bi-visuals-concept.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Hi @jlukosky. Thanks for pointing out my typo. It's good to know that someone is reading these articles so carefully!
I fixed it and it should be live in the next day or so.
