### ISSUE TITLE
DAX for date range returning data from date slicer

### ISSUE THREAD

**Issue by mibrahim1976** [MicrosoftDocs/powerbi-docs#3576]
Hi All,
i need your help,  i am trying to return the max(date) from the main table "Test" according to the Date slicer filter.
Please find the attached photo which shows three different dates, i created measure to return (min_Date and max_Date) based on filter Date, i created summarize table from "Test" table as i need to have the possibility to display values from Test table based on selected date slicer [Date], but unfortunately i am returning the max date value of Test table not from  max_date measure.

DAx function:
1) min_Date = min(test[Date])
2) max_Date = max(test[Date])
3) Selected max Slicer Date= return SUMMARIZE(test,"Modified",[max_Date])

Thanks in advance

![max_date](https://user-images.githubusercontent.com/59564335/152379027-42e986d7-ad96-4e3f-a7e5-77224f950807.png)

**Comment by davidiseminger** [comment]
Thanks for your comment, @mibrahim1976 . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com

**Comment by mibrahim1976** [comment]
Thanks @davidiseminger , i just open a ticket https://community.powerbi.com/t5/Desktop/Calculate-max-date-value-from-date-range/td-p/2321185

**Comment by mihart** [comment]
add tag
