### ISSUE TITLE
UTC_Offset - add a note "numeric value"

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3577]
Hi, 
I would like to ask to add a comment for Offset in section https://docs.microsoft.com/en-us/power-bi/admin/service-premium-install-gen2-app?tabs=1st#run-the-app-for-the-first-time point 4.
Our Customers are entering characters like "UTC" instead of an actual number. 

Please add 
"**Note:** Set the offset to a **numerical value** without time zone reference
Should you experience Capacity Metric App dataset refresh error: We count convert to Number, please verify dataset parameters setting to include only numerical value. "

![image](https://user-images.githubusercontent.com/98977972/152404565-402c094e-a215-4ba5-8efd-2d0bab0a4d85.png)

Thank you. Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcddef48-ab1d-cdd2-900a-9b9f3500a06f
* Version Independent ID: 42ce0182-3006-4271-7981-a9f8a984ca53
* Content: [Install the Premium Gen2 metrics app - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-install-gen2-app?tabs=1st)
* Content Source: [powerbi-docs/admin/service-premium-install-gen2-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-install-gen2-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Thanks for your comment, @MartinaPoddana . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KesemSharabi** [comment]
Hi @MartinaPoddana,

The only value you should enter in the UTC_Offset field is 0. I though that was clear, but as per your comment, it isn't. I'll amend the article to make that clearer.

Hopefully this field will soon be automatically populated.

Thanks,

Kesem

**Comment by MartinaPoddana** [comment]
@KesemSharabi ,
Thank you.  Customers tend to do strange things sometimes.

I actually understood that Cx can use numerical value. 
During first month of Gen2, there used to be comment somewhere that offset “does not work yet”. Since that comment disappeared, I assumed that they could use anything between -12 to +12.
Actually the whole of Release Notes section has disappeared from the app :) .

![image](https://user-images.githubusercontent.com/98977972/152949886-50421f62-3d73-4beb-b4c5-b352edf7b0e2.png)

**Comment by KesemSharabi** [comment]
Hi @MartinaPoddana,

The app is constantly changing and evolving, as we want to bring the best customer experience we can to you. In the future we will try to remove all the unneeded fields.

Think about it like this - the main thing is to install the app properly. Once installed, you should be able to make all your inquiries in the app.

Hope this helps,

Kesem

**Comment by MartinaPoddana** [comment]
Thank you Kesem.
