### ISSUE TITLE
PowerQuery in Excel and PowerBI

### ISSUE THREAD

**Issue by ronssssss** [MicrosoftDocs/powerbi-docs#3579]
I've been told that PowerQuery is the same in both apps. In that case they should have the same list of data source connections.

The PowerBI documentation lists **160 sources**
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources  

While Excel documentation only lists **40 sources**
https://support.microsoft.com/en-us/office/import-data-from-data-sources-power-query-be4330b3-5356-486c-a168-b68e9e616f5a  
.
If PQ is identical in both applications, please synchronize the lists. 
If not, in the excel documentation, explain why Excel PQ cannot access the same set of data sources. 
AND as a workaround, document how you could use PBI to access data in the "extra" sources, then access the PBI file from Excel PQ.  
Does this workaround allow refresh to work? 
Thanks. 
sorry about the bold, your editor apply the funky bolding .. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @ronssssss, thanks for your comment. I am passing it on to the doc owner for consideration.

**Comment by rootsmusic** [comment]
@ronssssss Power Query's data sources has an [Excel doc](https://support.microsoft.com/en-us/office/power-query-data-sources-in-excel-versions-e9332067-8e49-46fc-97ff-f2e1bfa0cb16) and a [Power BI doc](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)

**Comment by ronssssss** [comment]
Yes, that is my point exactly. The Excel page is a P.O.C. The Excel page only lists a couple of dozen, while the PowerBI page lists hundreds.
.
WHY THE DIFFERENCE?!?
.
Is PQ in Excel dumbed down, or the same as in PowerBI?
________________________________

**Comment by ronssssss** [comment]
And here is another page:
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources
.
If PowerQuery is the same, the list of external data sources should be the same. The simplest way to keep it the same is to redirect the various entries to a single page.
________________________________

**Comment by rootsmusic** [comment]
No @ronssssss, PQ supports different connectors in every product and even between different versions of a product.

**Comment by ronssssss** [comment]
Fine, but it really would help to clarify the issue if you put ALL the connectors on one page in One table. Base the table on the grid for Excel 2016 Win -2019, 2021, 365 on this page.
https://support.microsoft.com/en-us/office/power-query-data-sources-in-excel-versions-e9332067-8e49-46fc-97ff-f2e1bfa0cb16
.
Put ALL of the versions on the page into a SINGLE grid, add PQ in the various PowerBI options: Desktop, enterprise server etc.
.
The idea I'm trying to suggest is to make it easiest for users to identify which connectors are available when they are moving files between various versions of Excel and PowerBI.  For example of someone exports to Excel from PowerBI to do analysis because they are more familiar with it. Then they move the file to another OS, ie Mac ...

Please also suggest adding an "Expand all" button to the top of the page.

Thanks
________________________________
