### ISSUE TITLE
Multimedia Learning Approach

### ISSUE THREAD

**Issue by jrsauter** [MicrosoftDocs/powerbi-docs#358]
I'm new to data visualization, though I've done it in Excel for years.  The combination of written narrative, video, and a live test environment is excellent for exposing, learning, and trying the concepts.  Great job.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Getting data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @jrsauter - that's great to hear! Thanks for your nice comments, and we hope to create more content like this in the future. Thanks for the feedback!
