### ISSUE TITLE
Please sort the lists of sources alphabetically in each catory

### ISSUE THREAD

**Issue by ronssssss** [MicrosoftDocs/powerbi-docs#3580]
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources  
Please sort the lists in each category alphabetically, to make it easier to locate specific entries without resorting to find feature, ie
68.	Adobe Analytics
69.	appFigures (Beta)
70.	Asana (Beta)
71.	Assemble Views
72.	Automation Anywhere
73.	Automy Data Analytics (Beta)
74.	Azure DevOps (Boards only)
75.	Azure DevOps Server (Boards only)
76.	Data.World - Get Dataset (Beta)
77.	Dynamics 365 (online)
78.	Dynamics 365 Business Central
79.	Dynamics 365 Business Central (on-premises)
80.	Dynamics 365 Customer Insights (Beta)
81.	Dynamics NAV
82.	Emigo Data Source
83.	Entersoft Business Suite (Beta)
84.	eWay-CRM
85.	FactSet Analytics
86.	GitHub (Beta)
87.	Google Analytics
88.	Hexagon PPM Smart API
89.	Industrial App Store
90.	Intune Data Warehouse (Beta)
91.	LinkedIn Sales Navigator (Beta)
92.	Marketo (Beta)
93.	Microsoft Exchange Online
94.	Mixpanel (Beta)
95.	Palantir Foundry
96.	Planview Enterprise One - CTM (Beta)
97.	Planview Enterprise One - PRM (Beta)
98.	Product Insights (beta)
99.	Projectplace for Power BI
100.	Quick Base
101.	QuickBooks Online (Beta)
102.	Salesforce Objects
103.	Salesforce Reports
104.	SharePoint Online List
105.	Smartsheet
106.	SoftOne BI (beta)
107.	SparkPost (Beta)
108.	Spigit (Beta)
109.	SweetIQ (Beta)
110.	TeamDesk (Beta)
111.	Twilio (Beta)
112.	Webtrends Analytics (Beta)
113.	Witivio (Beta)
114.	Workplace Analytics (Beta)
115.	Zendesk (Beta)
116.	Zoho Creator (Beta)

I made a copy of the page so I could sort the entries. I also numbered them just to get an easy count. Maybe simply add a count to the document. Being able to say that PQ in PBI can access 160 different data sources is "impressive". 
.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data)
* Content Source: [powerbi-docs/connect-data/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-get-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Thanks for your suggestion @ronssssss. Passing it on to the doc author for consideration.

**Comment by davidiseminger** [comment]
That's a good idea - thanks!
