### ISSUE TITLE
Why are Azure entries in to sub categories? 

### ISSUE THREAD

**Issue by ronssssss** [MicrosoftDocs/powerbi-docs#3581]
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources  
.
I'll prefix this by saying the only thing I know about Azure is that it is a cloud Database. 

Azure has a category, with 16 entries.
.
Then the next category, "Online Services Data Sources" lists 2 more "Azure" entries
74.	Azure DevOps (Boards only)
75.	Azure DevOps Server (Boards only)
.
I'm curious why they are not part of the Azure category

**Comment by paulinbar** [comment]
Hi @ronssssss, thanks for your question. Forwarding it along to the doc owner.

**Comment by davidiseminger** [comment]
Thanks for your question, we've passed it on to the engineering team.
