### ISSUE TITLE
Misplaced entries? 

### ISSUE THREAD

**Issue by ronssssss** [MicrosoftDocs/powerbi-docs#3582]
https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources 
.
Just curious why
137.	ODBC
138.	OLE DB
 
are in the "other" category rather than "DB" category?

**Comment by paulinbar** [comment]
Hi @ronssssss, thanks for your question. Sending on to the doc author for consideration.

**Comment by davidiseminger** [comment]
It's based on how the engineering team has organized them in the product. Thanks!
