### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ChessGeekBoy** [MicrosoftDocs/powerbi-docs#3583]
![image](https://user-images.githubusercontent.com/81440771/152714568-1d3f6ec3-8dd4-48bc-840b-c8f6dabc7ce3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea19ca3-9587-e7d0-2b47-5255911eeffc
* Version Independent ID: 50fa187c-94cb-6c82-e2ff-193dd0f0f762
* Content: [Embed Power BI report in a Power BI embedded analytics application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-customer-app)
* Content Source: [powerbi-docs/developer/embedded/embed-customer-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-customer-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for pointing out this typo, @ChessGeekBoy . I fixed it and it should be published in the next day or so.
