### ISSUE TITLE
The number of limits of Model refresh parallelism has not been updated.

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3584]
Hi authors,

Recently the number of limits in English version has been changed.
But the description in Japanese version has not been changed yet.

![image](https://user-images.githubusercontent.com/73410575/152756869-175a83d9-38d3-4795-b6d9-2e56caa95acb.png)

Please kindly modified it.
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3d17a8-8258-5246-24bb-b69c273d06c4
* Version Independent ID: 36f06d1c-4f46-598d-c300-eb4dd22d4487
* Content: [What is Power BI Premium Gen2? - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-what-is#feedback)
* Content Source: [powerbi-docs/admin/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by maggiesMSFT** [comment]
Hi, @Hyamyam -- I'll check to see what our localization turnaround time is. Looks like most recent update was Jan 31, 2022, so I'm sure the update is imminent!
cc @KesemSharabi

**Comment by maggiesMSFT** [comment]
Hi, @Hyamyam -- good catch! The files were just handed off to the Localization team. Updates should be live in about 5 days.
cc @KesemSharabi
