### ISSUE TITLE
Sample Excel files are broken

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#3585]
[Sample Excel](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets?WT.mc_id=DP-MVP-5003435&#download-sample-excel-files) files are broken, due to discontinuing Power View in Excel. 

When opening the Excel files, the following error shows: 
![image](https://user-images.githubusercontent.com/38921736/152787002-8ec2b05b-10a8-4afa-968f-8aa89b0f0217.png)
I think updating the files, or removing should be the solution. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets?WT.mc_id=DP-MVP-5003435&#download-sample-excel-files)
* Content Source: [powerbi-docs/create-reports/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @marclelijveld -- I appreciate the feedback! I've been debating this very question. Currently the only option is to just remove links to the Excel files altogether. Would that be better than leaving them up, with an explanation about the PV sheets? 
I could delete the PV sheets; then the Excel file will open to blank worksheets, because the data is all in Power Pivot. 
One plus for keeping the PV sheets: When you upload to Power BI, each Power View sheet becomes a Power BI report page. Just a thought. 
Your thoughts?
Thanks!

**Comment by marclelijveld** [comment]
Hey @maggiesMSFT, 
Relevant and good questions for sure! Maybe it would be possible to remove the PV elements from the sheets, but leave the files there, as folks can still use it as demo data. Not having the PV error contributes to a positive experience I think, rather than having (unsupported) content. Though, people might be confused when they open the files and sheets are empty. Maybe just add a note to the docs, as well as a row in the sheet that the data is loaded to Power Pivot, so when they open the files from PBI it will display the data etc. 

Maybe also good to mention why the PV is removed by linking to the [official support site where the information about discontinuing PV is shared](https://support.microsoft.com/en-us/office/roadmap-for-power-view-in-excel-c1f0d0f7-adef-4f03-ae35-46d83294e96b#:~:text=While%20Power%20View%20remained%20in,support%20on%20October%2012th%2C%202021.). 

What do you think about this? :) 
--Marc

**Comment by maggiesMSFT** [comment]
Yes, I like it! I'll share with some other folks on the team and put it on the backlog. 
Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @marclelijveld -- I finally fixed the Excel samples! I deleted the Power View sheets and added an explanation of how to view the data in Power Pivot. I saved the updated versions to GitHub, 
https://github.com/microsoft/powerbi-desktop-samples/tree/main/powerbi-service-samples
