### ISSUE TITLE
How to configure with Azure Automation Runbook?

### ISSUE THREAD

**Issue by ShifengWu** [MicrosoftDocs/powerbi-docs#359]
I am trying to use Azure Automation Runbook to monitor all gateways under my account, but I can't overcome the Login-OnPremisesDataGateway since it has popup window. If I run as Azure, will show "the Internet Explorer engine is not available", if I run as Hybrid worker, will show "Showing a modal dialog box or form when the application is not 
running in UserInteractive mode is not a valid operation". Is there any way I can apply above in Azure Automation? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a971ee3-1d8f-50bf-0a23-20bf592779bd
* Version Independent ID: b69b3560-08fd-6c9e-4bb3-4dfa3838d223
* Content: [High availability clusters for On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-high-availability-clusters)
* Content Source: [powerbi-docs/service-gateway-high-availability-clusters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-high-availability-clusters.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ShifengWu . 
In addition to a documentation inquiry, this looks like a possible support request as well. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Adding the author.

**Comment by ShifengWu** [comment]
Hi @mgblythe, thanks for follow this, is there have any update? Can we add PromptBehavior same as AuthenticationContext.AcquireToken so that we can avoid the pop up window? Thank you so much.

**Comment by mgblythe** [comment]
@ShifengWu -- sorry, but I'm unable to find an answer for this issue. Please try support in the Azure portal.
