### ISSUE TITLE
Power Bi REST API Python huge report export .pbix

### ISSUE THREAD

**Issue by PriyankaChaudhariNitor** [MicrosoftDocs/powerbi-docs#3590]
Now, I'm trying to retrieve the .pbix file with REST API (Export report URL)

I have around 900MB file size.
[https://api.powerbi.com/v1.0/myorg/reports/<report_id>/Export]()

 

but maybe because of its huge size, the request runs for 5mins and returns below error response

{
    "Message": "An error has occurred."
}
 
can anyone suggest a workaround or any other way to export this huge file?
 
**This API works fine for small reports

**I am able to download same file using powershell  in 10mins.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @PriyankaChaudhariNitor. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
