### ISSUE TITLE
Count of throttling tooltip

### ISSUE THREAD

**Issue by roconnor39** [MicrosoftDocs/powerbi-docs#3591]
I cannot see in the documentation where the definition of "count of throttled windows" appears.   This appears on the tooltip of the Overloaded minutes per hour visual within the performance app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6f52eeb-717d-9a67-b775-c17c5cf916e4
* Version Independent ID: 2c804bb2-1cf3-462e-730b-ecfbae2a5e9e
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-metrics-app#timepoint)
* Content Source: [powerbi-docs/admin/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @roconnor39,

Thanks for your comment. I'll look into it and get back to you shortly.

**Comment by KesemSharabi** [comment]
Hi @roconnor39,

Thank you for pointing out that there's no definition for 'count of throttled windows'. This really should be renamed to *Overloaded Minutes*. The value is displayed in multiples of half a minute.

We'll shortly change the name in the tooltip so that it doesn't cause any further confusion.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @roconnor39,

Just to update you, the change is already live:

![image](https://user-images.githubusercontent.com/54834915/153814396-6485891f-0fe8-4561-8084-1b14742a9ee5.png)

Thanks,

Kesem

**Comment by roconnor39** [comment]
Thanks for this.  Just to Clarify, the overloaded minutes - if each bar represents an hour, would the over loaded minutes tool tip not exceed 60 minutes - its just that the customer has claimed he has claimed more than 60 in an hour.
