### ISSUE TITLE
Steps for conditional formatting outdated in Hyperlinks in Tables page

### ISSUE THREAD

**Issue by stensjoberg** [MicrosoftDocs/powerbi-docs#3593]
This page is outdated, the steps to apply conditional formatting have changed. I would suggest linking to this page with the new guidance: https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks (URLs) to a table or matrix - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-hyperlinks-in-tables)
* Content Source: [powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @stensjoberg.

I've assigned this issue to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @stensjoberg -- good idea! Adding it to the backlog.

**Comment by paulinbar** [comment]
Moving issue to our work item backlog.
