### ISSUE TITLE
Emissions Impact Dashboard for Microsoft 365 link NOT working

### ISSUE THREAD

**Issue by SerenaPisati** [MicrosoftDocs/powerbi-docs#3597]
Click the following link to get to the app: [Emissions Impact Dashboard for Microsoft 365](https://aka.ms/microsoft-365-emissions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d621bc5e-d39c-3641-9385-24ead7ddb4f7
* Version Independent ID: d621bc5e-d39c-3641-9385-24ead7ddb4f7
* Content: [Connect to the Emissions Impact Dashboard for Microsoft 365 (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-emissions-impact-dashboard-microsoft-365)
* Content Source: [powerbi-docs/connect-data/service-connect-emissions-impact-dashboard-microsoft-365.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-emissions-impact-dashboard-microsoft-365.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @SerenaPisati, thanks for the alerting me. Let me check this out..

**Comment by paulinbar** [comment]
Hi again @SerenaPisati, can you try this link? https://appsource.microsoft.com/en-us/product/power-bi/coi-sustainability.emissions_impact_dashboard_microsoft_365
I will see about updating the doc in the meantime.

**Comment by SerenaPisati** [comment]
Thank you Paul!

It looks like it's working.

Serena

**Comment by paulinbar** [comment]
Great! Thanks again for pointing this out Serena!
@SerenaPisati

**Comment by paulinbar** [comment]
@SerenaPisati, I fixed the link on the docs page, and it should be live in about 15 minutes.
Closing the issue now. Thanks again!
