### ISSUE TITLE
Explanation for RevenueTY field

### ISSUE THREAD

**Issue by shayanjafari** [MicrosoftDocs/powerbi-docs#3601]
[Enter feedback here]
Hi

I wanted to know what exactly "TY" in RevenueTY field in this report stands for .
I know that RevenueTY = CALCULATE ( [ TotalRevenue ] , FILTER ( Scenario , Scenario [ Scenario ] = "Actual" ) ) ; But i couldn't understand the "TY" meaning from that .

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c25ad9a8-50b9-7f83-4e10-ebbbff013d6b
* Version Independent ID: 0584427f-6438-277b-4a0c-5d51f4694f63
* Content: [Customer Profitability sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-customer-profitability)
* Content Source: [powerbi-docs/create-reports/sample-customer-profitability.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-customer-profitability.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @shayanjafari . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by shayanjafari** [comment]
thanks for guidance
