### ISSUE TITLE
Meaning of sandbox technology for R scripts security

### ISSUE THREAD

**Issue by valenciajdev** [MicrosoftDocs/powerbi-docs#3602]
[Under the R scripts security section: _[https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#r-scripts-security](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals#r-scripts-security)_ please detail what do we mean by _sandbox_ technology, whom has access to it and how it protects against security risks]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c7931b-9fbb-bec4-09c4-9c827e4ec7a1
* Version Independent ID: 7ebc1400-482b-62e6-3747-bb7ffdb1dcf3
* Content: [Create advanced analytics and visualizations using R scripts - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals)
* Content Source: [powerbi-docs/visuals/service-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/service-r-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for posting @valenciajdev  – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. In general, sandbox means an environment where you can test work, and develop solutions outside of a production environment. 

Your best venue for getting a more specific answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
