### ISSUE TITLE
Power BI REST API - documentation structure

### ISSUE THREAD

**Issue by romanzdk** [MicrosoftDocs/powerbi-docs#3604]
Power BI API documentation is very unfriendly and illegible.

E.g. https://docs.microsoft.com/en-us/rest/api/power-bi/datasets

Table of content of "In this article" contains only "Required scopes" which does not make much sense nor it is useful. The same applies for all other APIs, not only Datasets.

**Comment by paulinbar** [comment]
Hi @romanzdk, thanks for your feedback. I know that the REST APIs dealing with datasets have been undergoing some work recently, so it is possible some of what you are seeing is the result of that, but in any event I am forwarding your comment along to the person who monitors the REST API documentation. Thanks again for reaching out!
