### ISSUE TITLE
Considerations and Limitations - Repeat Bullets

### ISSUE THREAD

**Issue by jotsap** [MicrosoftDocs/powerbi-docs#3605]
Under Sonsiderations and Limitations, the last 3 bullets are repeated earlier in the list. In other words these items are listed twice 

BULLET 3 AND 9: 
There may be times when using Analyze in Excel that you get an unexpected result, or the feature doesn't work as you expected. See [Troubleshoot Analyze in Excel](https://docs.microsoft.com/en-us/power-bi/collaborate-share/desktop-troubleshooting-analyze-in-excel) for solutions to common issues.

BULLET 4 AND 10:
Only Power BI datasets that use Import mode will preserve hierarchies in Analyze in Excel workbooks. Power BI datasets built on DirectQuery or composite models will not have their hierarchies retained when using Analyze in Excel.

BULLET 5 AND 11:
Analyze in Excel doesn't support specifying a locale by modifying the connection string after a workbook has been generated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Start in Power BI with Analyze in Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @jotsap. I've updated the article and set it to republish.
