### ISSUE TITLE
Is this feature deprecated ?

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/powerbi-docs#3607]
Is this feature deprecated?  The setting for this does not appear in my personal PowerBI tenant settings, nor one of my corporate clients.  If I remember correctly this set else where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 460b9768-213a-bd8b-5ad8-ed5071848a98
* Version Independent ID: 24bdc0f5-a172-0d0b-02b2-ff798ccd96cf
* Content: [Dashboard data classification - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-data-classification)
* Content Source: [powerbi-docs/create-reports/service-data-classification.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-data-classification.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @rwlpf, yes you are correct, the data classification labels have been deprecated. While the feature was deprecated last year, some traces may remain in the UI ... they are scheduled to be removed by the end of March. In any event, here is a link to the main sensitivity label article. https://docs.microsoft.com/power-bi/admin/service-security-sensitivity-label-overview. Sensitivity labels aren't ready to use out of the box. They have to be set up first and enabled. There are links in the doc to other articles that describe this. 
Anyway, thank you for reaching out and reminding us to update the documentation!
