### ISSUE TITLE
Update second bullet to include "custom" -- custom visuals not supported

### ISSUE THREAD

**Issue by BNN-Darren** [MicrosoftDocs/powerbi-docs#3609]
Per this thread, the second bullet I believe should specify report page tooltips are not supported for "custom" PowerBI visuals. https://community.powerbi.com/t5/Desktop/Report-tooltips-are-not-supported-for-Power-BI-visuals/td-p/1828796

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips)
* Content Source: [powerbi-docs/create-reports/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @BNN-Darren . This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi @BNN-Darren -- agreed, that makes it clearer. I've updated the article; change will be live Mon afternoon Mar 21 Pacific time.
Thanks!
