### ISSUE TITLE
PowerBiApiResource

### ISSUE THREAD

**Issue by krishnand** [MicrosoftDocs/powerbi-docs#361]
The AAD app config doc segment is quite confusing. As I understand, there are 2 apps one that assigns permissions to PBI service and the Client that has the secret configured. It is not clear how the Client app configures permission for the Resouce AAD app. I presume we are following the [Client credentials grant flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow) - if so could you confirm that the "PowerBiApiResource" in the cloud.config is the App ID URI of the Resource AAD app. Also could you pls clarify what the 'ApiUrl' in the PowerBIClient init call is - I'm trying this with the base URI of the service where my workspace is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 505b774c-e4e2-78b0-dad9-ae19c9240004
* Version Independent ID: a5dac00f-35c2-a87d-3224-c96682d2ffb7
* Content: [Embed Power BI content into an application for your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization)
* Content Source: [powerbi-docs/developer/embed-sample-for-your-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-your-organization.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Hi @krishnand ,
Thank you for your feedback and questions.  I've assigned this to the author and he will respond to you directly.  
Take care.

**Comment by markingmyname** [comment]
@krishnand Apologize for the delayed response. Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@krishnand 

API URL - endpoint for the PBI REST APIs.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by zuliya** [comment]
Could you please clarify what URL to use for PowerBiApiResource?
