### ISSUE TITLE
"Export data" setting no longer exists

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#3610]
Hello,

The "Export Data" section of this page seems to be outdated as "Export Data" is no longer an individual setting.

Maybe this needs to be updated to reflect the various types of exports (Export to Excel, Export to .csv, etc)?

Thanks,
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85be11e7-5a03-a1b1-605a-d49b4215a8aa
* Version Independent ID: 0877169a-673f-1fe9-45b4-dec6b9e9fe26
* Content: [Tenant settings guidance - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/admin-tenant-settings)
* Content Source: [powerbi-docs/guidance/admin-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/admin-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi Chris, thanks for bringing this to my attention. Putting this on my list of things to do!

**Comment by paulinbar** [comment]
Hi @chrisweis, sorry for the very late response. That guidance page has been retired and now you get redirected the top-level tenant settings page that includes a hyperlinked list to the current relevant pages. That said, the tenant settings documentation is in flux and will be reorganized over the next few months. In any event, thanks for taking the time to write! Closing this issue in the meantime.
