### ISSUE TITLE
Power BI App in MS Teams with Private Link enabled missing in the constraints and limitations section

### ISSUE THREAD

**Issue by mikeane01** [MicrosoftDocs/powerbi-docs#3611]
Request the addition of any constraints and limitations with Private Links for the 'Power BI App in MS Teams' scenario. 

For example if the customer has setup Private Links and enabled 'Disable Internet Access', then will the Power BI App in MS Teams work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @[github person who posted].

I've assigned this issue to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we'll look into adding that in a future update.
