### ISSUE TITLE
Denormalization vs Normalization contradiction in article

### ISSUE THREAD

**Issue by JVerveer** [MicrosoftDocs/powerbi-docs#3614]
In the "Normalization vs. denormalization" section, it is stated that "As described in this article, you should strive to develop optimized Power BI data models with tables that represent normalized data." 

This statement is debunked further on the page in the section "Snowflake dimensions" where it is stated that normalisation leads to "...more tables, which is less efficient from storage and performance perspectives. These tables must include columns to support model relationships, and it can result in a larger model size.", "Longer relationship filter propagation chains will need to be traversed, which will likely be less efficient than filters applied to a single table." and "...more model tables to report authors, which can result in a less intuitive experience, especially when snowflake dimension tables contain just one or two columns." 

It seems like the top statement should be changed to "denormalized data" instead of "normalized data"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by paulinbar** [comment]
Hi @JVerveer, thanks for your feedback. I have forwarded your comments along to the doc author for consideration.

**Comment by peter-myers** [comment]
Hi @JVerveer - thanks for your feedback that has helped us to improve the article. An update to the article has been published and should go live soon. #please-close
