### ISSUE TITLE
Home Canvas section missing information

### ISSUE THREAD

**Issue by vtheresaz** [MicrosoftDocs/powerbi-docs#3615]
Home Canvas section is missing information regarding the "Recommended" Section. It focuses mostly on the Expanded view and describes the Simplified view as follows: "The Simplified view displays less categories of content; you'll see only tabs for Recents, Favorites, My apps and a link to Show more."

However, the Recommended section includes different recommendations than the Favorites + Frequents, such as reports/apps frequented by other users. So it is not just displaying less categories of content. A bit more detail on the Simplified view would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 744f5d32-18ed-9018-3003-c5f9bcb3d1ff
* Version Independent ID: e2123a9f-edef-5170-05c6-98d42bc9fd35
* Content: [Find content from Power BI service Home - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-home)
* Content Source: [powerbi-docs/consumer/end-user-home.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-home.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @vtheresaz. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @vtheresaz ,
Thank you for your feedback.  I've updated the page to include the missing information :-)
All the best,
the DOCS team
