### ISSUE TITLE
Hide sub report from main list

### ISSUE THREAD

**Issue by rubeesh** [MicrosoftDocs/powerbi-docs#3618]
[Enter feedback here]
Is there any way to hide subreports in paginated report, so that the users don't access sub reports directly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3ff44b8-fcd6-eac4-232d-71ce0f9b5933
* Version Independent ID: d367f3a1-0f59-d508-b3cb-0723328e6f22
* Content: [Subreports in Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/subreports)
* Content Source: [powerbi-docs/paginated-reports/subreports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/subreports.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rubeesh . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by AndresDev777** [comment]
You used to be able to do it from the Power BI App, there is a hide option. It may not work with this month's release
