### ISSUE TITLE
Example not working when creating Power BI Private Endpoint

### ISSUE THREAD

**Issue by oussama70** [MicrosoftDocs/powerbi-docs#3619]
Hello community and page owner,
I am trying to build a demo to one of the enterprise clients and I want to show Power BI Private Link solution and how Power BI can access resources privately in their tenant vNet.
I followed the whole exercise and I tried so many things. When reaching the step of provisioning the Private Endpoint, I get an error saying: No supported sub-resources
In brief, I created successfully the privateLinkServicesForPowerBI resource. I already have vNet and subnet all in the same Azure region as the Power BI service "West US 2".
When creating the private endpoint, I followed the same steps till I got the error "No supported sub-resources" at the point of selecting the created resource. The portal does not allow me to proceed to enter tenant at the field: Target sub-resource
I found a workaround by selecting "Connect to an Azure resource by resource ID or alias". When pasting the resource ID, I am able to proceed; however, the service is created with Pending approval and I couldn't proceed right after.
No web resources to help on this issue. I have been diligently trying for the past couple of days with no luck.
I am the global admin of my personal tenant and also my Power BI service.
Will you be able to comment on this issue, so I can proceed with my demo?
I also have screenshots if needed.
You can email me back to my work email address: oussama.kawas@softchoice.com
Regards,
Oussama
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63c8b8f9-7455-6a1a-cf10-cfd6ae088484
* Version Independent ID: d0a2380f-c19d-916a-1416-f9bc7fdc72bc
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-private-links)
* Content Source: [powerbi-docs/admin/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @oussama70. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

If your support experience or outcome specifically says that we need to update the steps, we'll certainly do so.
