### ISSUE TITLE
When will Viewer role be made available?

### ISSUE THREAD

**Issue by MarkL76** [MicrosoftDocs/powerbi-docs#362]
Hi, we really want to start using the new workspace offering, however we are very concerned that we can't offer our users a read only view and that all available options (Admin, Member & Contributor) offer the ability to Edit and download the PBIX.  This is a big deal to us, we do not want our users to be able to do either of these.  We are also concerned that users can download the PBIX and view all data, thereby getting around any RLS setup.  Please can you provide a ETA for when the Viewer Role will be made available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#app-workspace-features-that-work-differently)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @MarkL76 
You're in luck!  We do have a viewer role -- we call it Power BI "consumer".  Here is a link to the landing page. https://docs.microsoft.com/en-us/power-bi/consumer/power-bi-consumer-landing

We've recently split off this "consumer" content from the rest of the Power BI articles and the site is still undergoing changes. Your questions are spot on and I will add them to the FAQ.

**Comment by maggiesMSFT** [comment]
Hi, @MarkL76 -- this functionality for the new workspaces is on the roadmap. For info about upcoming features, see the Summary of Planned Features for Business Intelligence, https://docs.microsoft.com/en-us/business-applications-release-notes/October18/intelligence-platform/planned-features.

**Comment by Vinhaman** [comment]
@mihart i think you got this a bit out of contest... 
What @MarkL76 was asking was for a role in the new Workspaces that are currently on preview... I'm also eager for the GA of the New Workspaces but we'll just have to wait and see... :)

![image](https://user-images.githubusercontent.com/12937232/47378079-f07bb600-d6ee-11e8-9963-c3cc40a89892.png)

**Comment by maggiesMSFT** [comment]
Hi, @Vinhaman -- You're right. It's on the roadmap for sure. Sorry I don't have a specific due date. See my comment I posted just about when you did.

**Comment by MarkL76** [comment]
Hi @maggiesMSFT 

Thanks for the responses.  However I'm afraid I am now a bit more confused with the link to 'Power BI for consumers'.  Is this something in addition to the 3 existing roles and the Viewer role I require?

Is this a workaround?  Eg we can somehow set someone up today as a read-only 'Consumer'?

**Comment by maggiesMSFT** [comment]
Hi, @MarkL76 -- sorry for any confusion. No, "consumers" is a designation we're using for our content. We want to separate out content for people who are consuming, not creating, Power BI dashboards and reports, so they can learn about the Power BI functionality available to them. 
Then we aim in-depth content at Power BI designers, admins, devs, architects.  
Nothing to do with workspace roles. Although of course a workspace creator might assign a Viewer role to a Power BI consumer in a workspace.  Does that make sense?

**Comment by MartinKDK** [comment]
Hi, is there any update on when is this "consumer" role is going to be available?
