### ISSUE TITLE
Xero App not in App Store?

### ISSUE THREAD

**Issue by susan-taylor-nz** [MicrosoftDocs/powerbi-docs#3620]
[Enter feedback here]

---

I searched for Xero in the app store today 18/2/22 and the only options shown were two ACTERYS apps - 

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 264b8c79-ddc0-a0d6-3f60-f0d53d3dbca4
* Version Independent ID: b490a2a1-c55b-db04-964f-2cd0e1107509
* Content: [Connect to Xero with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-xero)
* Content Source: [powerbi-docs/connect-data/service-connect-to-xero.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-xero.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by davidiseminger** [comment]
Thanks for your comment, @susan-taylor-nz. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by paulinbar** [comment]
Hi @susan-taylor-nz, sorry for the long overdue answer. Indeed, the Xero template app has been deprecated. It looks like there are several other potential "Xero" related template apps in AppSource. If you go into Apps in Power BI, and then choose Get apps, you can search for Xero on the Template apps tab. That returns the items. Support for those template apps is provided by the app publisher, not us. You can find the help and support links if you open the offering in AppSource and look under the Support heading in the left-hand navigation pane. Good luck!
