### ISSUE TITLE
Wrong column name written while explaining group by command

### ISSUE THREAD

**Issue by Supriya4466** [MicrosoftDocs/powerbi-docs#3622]
![image](https://user-images.githubusercontent.com/99993644/154748775-0828d16d-d018-485a-8c0f-93b6725eb79e.png)
![Capture](https://user-images.githubusercontent.com/99993644/154748846-9de394e5-9956-4251-9ab0-d54b5f2fd5a1.PNG)

**Comment by paulinbar** [comment]
Hi @Supriya4466... sharp eyes! Thanks for your feedback! I'm forwarding your observation along to the doc owner.

@davidiseminger, I think this is the place being referred to:
https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-common-query-tasks#group-rows

**Comment by Supriya4466** [comment]
Happy to help 

Thanks and Regards,
Supriya

**Comment by davidiseminger** [comment]
I've updated that article - thanks!
