### ISSUE TITLE
Loading data: Click "Transform" to enter Power Query Editor, don't click "OK"

### ISSUE THREAD

**Issue by middlec000** [MicrosoftDocs/powerbi-docs#3623]
# Thank You!
Great tutorial! There is one small misdirection that caused me issues. I suspect its source is an update to the data loading process in Power BI.

# Current
[https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed#import-the-odata-feeds-order-data](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed#import-the-odata-feeds-order-data)
Import the OData feed's order data -> Step 3: "In Navigator, select the Orders table, and then select OK to load the data into Power Query Editor."
# Problem
Clicking "OK" causes the table to be imported as-is without entering the Power Query Editor. The following steps regard actions within the Power Query Editor so it is confusing when this does not appear.
# Change
Step 3: "In Navigator, select the Orders table, and then select Transform to load the data into Power Query Editor."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb0f7e4-74cd-dadb-c2ce-4b6c0c511e20
* Version Independent ID: 0d14b983-c47a-1fa7-7103-15182735f26b
* Content: [Tutorial: Combine data from Excel and an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed#feedback)
* Content Source: [powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-tutorial-analyzing-sales-data-from-excel-and-an-odata-feed.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @middlec000, thanks for reaching out to us with your observation. I am forwarding it on to the doc owner for further action. Thanks for helping us keep the docs up to date! And the kind words about the tutorial I am sure will be appreciated.

**Comment by davidiseminger** [comment]
Great - thank you! I made the update to the article, thanks!
