### ISSUE TITLE
Export to PDF with Sensitivity Label

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3624]
Documentation mentions that :

Export to PDF doesn’t support sensitivity labels. If you export a file that has a sensitivity label to PDF, the PDF won’t receive the label and no protection will be applied.

However, for reports that have highly confidential or restrictive Sensitivity Labels, the exported document contains security warnings and requires Information protection plugin downloaded for PDF.

It looks like the Sensitivity Label of the report affects this behavior. Is the PDF limitation still applicable?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49ffb799-4e1a-c47c-749e-c27b0bd0ae65
* Version Independent ID: 7744ac08-00fd-62d1-6014-14b96f0f2f2f
* Content: [Microsoft Information Protection sensitivity labels in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-security-sensitivity-label-overview)
* Content Source: [powerbi-docs/admin/service-security-sensitivity-label-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-security-sensitivity-label-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @rjagdon, thanks for reaching out with your question. I will check this out.

**Comment by paulinbar** [comment]
Hi @rjagdon. I checked over the docs. The part that says that sensitivity labels aren't applied to exported PDFs is under the Desktop limitations section. As far as I can tell, that limitation still applies. When you export your report from Desktop, there is no warning when you open the PDF, i.e. the sensitivity label and the protection it carries didn't pass over to the exported PDF file. 

Further up in the document PDF is mentioned as a supported export path for sensitivity labels, and the protection does get applied to exported PDFs. That I think is what you are seeing. Do you recall whether you exported from the Power BI service or from Desktop?

In any event, your comment is well-taken - the information isn't presented well in the doc. I will make that Desktop limitation harder to mistake. Soon that overview is going to be rewritten and hopefully things will be presented in a more coherent way then. In short, thanks for your feedback!

I'm closing this issue now, but if what I described doesn't cover your issue please feel free to reopen. Thanks!
