### ISSUE TITLE
The almost of text in article has Bold

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3625]
Hi Authors,

I was checking the article in Japanese.
Almost of the text is kept as Bold. 
![image](https://user-images.githubusercontent.com/73410575/154939977-6e44569d-e259-4471-a579-5df05a34af51.png)

It is hard to read.
Can you please modifiy from Bold to normal font.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Change how a chart is sorted in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-change-sort)
* Content Source: [powerbi-docs/consumer/end-user-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-change-sort.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @Hyamyam, thanks for pointing this out. I am forwarding your observation on to the doc owner for further action.

**Comment by mihart** [comment]
Hi @Hyamyam 
That's bizarre.  The en-us page doesn't have the strange bolding.  This looks like a support request for the DOCS platform.  Please open a new Git Issue at this location:  https://github.com/MicrosoftDocs/feedback/issues
Thank you,
the DOCS team
