### ISSUE TITLE
Suggested Edits

### ISSUE THREAD

**Issue by middlec000** [MicrosoftDocs/powerbi-docs#3626]
# Thank you
Thank you @maggiesMSFT and other contributors for this tutorial - it was very helpful!  
The following I consider minor changes that would help someone new to Power BI (such as myself) follow the tutorial with more ease. Several of these changes I think are due to updates in the Power BI interface.

# Issue 1
## Current
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#build-your-report
## Problem
At the beginning of the "Build your report" section you do not show how to navigate to the Report Tab. This is a basic navigational skill users should figure out pretty quickly, but you do show this step in previous sections and this tutorial appears to be aimed at people very new to Power BI such as myself.
## Suggested Change
To the beginning of the "Build your report" section,
Add: "Now select Report view on the left."  
Add: Image of Report view icon.

# Issue 2
## Current
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#visual-5-year-slicer
Build your report -> Visual 5: Year slicer -> Step 2: "In the Visualizations pane, choose Slicer. Power BI automatically creates a numeric range slicer."
## Problem
Took me a while to find icon corresponding to a Slicer.
## Suggested Change
Add: Image of Slicer icon.

# Issue 3
## Current
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#extra-credit-format-the-report  
Build your report -> Extra credit: Format the report -> Add a background shape for the title -> Step 2: "In the Format shape pane, in the Outline section, change Transparency to 100%."  
Also appears in:  
Build your report -> Extra credit: Format the report -> Add a background shape for visuals 2 and 3 -> Step 2: "In the Format shape pane, in the Outline section, change Transparency to 100%."  
## Problem
Looks like Power BI has changed how to control shape outline transparency. The current direction is outdated.
## Suggested Change
Step 2: "In the Format shape pane, in the Style section, switch Border to Off." 

# Issue 4
## Current
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#extra-credit-format-the-report  
Build your report -> Extra credit: Format the report -> Add a background shape for the title
## Problem
Background from title text box remains - this is an undesired visual.
## Suggested Change
Add a new first step to the "Add a background shape for the title" Subsection:  
Step 1: "Select the title text box. In Format text box -> Effects switch Background to Off."  
Note: This step could instead be added to the Build your report -> Visual 1: Add a title subsection, but I think it is more appropriately placed in the Build your report -> Extra credit: Format the report -> Add a background shape for the title subsubsection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @middlec000, thanks for your detailed feedback, and the kind words! They go to a different author this time, and I am sure will be welcome, as is the feedback. It's always good to hear from someone who has actually gone through the material and has suggestions as to how it can be improved. Thanks again!

**Comment by paulinbar** [comment]
Moving to our work item backlog.
