### ISSUE TITLE
中国語のページが表示されます。

### ISSUE THREAD

**Issue by ayumito** [MicrosoftDocs/powerbi-docs#3628]
[フィードバックをこちらに入力してください]
https://docs.microsoft.com/ja-jp/power-bi/admin/service-premium-gen2-faq と「ja-jp」で指定しているのに中国語です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9e7d18dd-7459-baea-2c12-fc47ffcd9b11
* Version Independent ID: 42220c7a-465b-2da2-3014-0aecd9631142
* Content: [Power BI Premium Gen2 常见问题解答 - Power BI](https://docs.microsoft.com/ja-jp/power-bi/admin/service-premium-gen2-faq)
* Content Source: [powerbi-docs/admin/service-premium-gen2-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by mihart** [comment]
Thanks for your comment, @ayumito . This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @ayumito,

Can you please translate this GitHub issue to English so that I can help you?

Thanks,

Kesem
