### ISSUE TITLE
Number of calls?

### ISSUE THREAD

**Issue by tofu001** [MicrosoftDocs/powerbi-docs#363]
Hi,

I'd like to know the number of calls that this makes to Lithium.  During the import process, on subsequent refreshes, etc.

Also, is it possible to reduce the amount of data pulled by limiting the scope to certain categories or boards?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6faf733f-4da2-a32d-4ca4-a275a6b4a2e0
* Version Independent ID: 0181ac54-9860-96de-cf20-7f95a85cf84a
* Content: [Connect to Lithium with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-lithium)
* Content Source: [powerbi-docs/service-connect-to-lithium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-lithium.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @tofu001 .

We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @tofu001 -- I'll see if I can find an answer to your question. Thanks!

**Comment by tofu001** [comment]
Hi @maggiesMSFT, were you able to find any info about this?

**Comment by maggiesMSFT** [comment]
Hi @tofu001 -- ugh, I'm sorry, no info yet. I'll ping the PM again. Thanks for the reminder.

**Comment by tofu001** [comment]
Hi again @maggiesMSFT, have you heard anything about this?

**Comment by mgblythe** [comment]
Closing b/c this content pack will be deprecated on Sept. 25.
