### ISSUE TITLE
Note which says A4 for full premium functionality is incorrect? 

### ISSUE THREAD

**Issue by marclelijveld** [MicrosoftDocs/powerbi-docs#3631]
Hi there!

The documentation on this page says "_If you purchase an A4 or higher SKU, you can take advantage of all Premium features except for unlimited sharing of content. With A SKUs, all users who consume content require Pro licenses._" 
AFAIK, this limitation for A4 only applies to Premium gen1 capacities. I believe this limitation has been lifted with the introduction of Premium Gen2. 

Can you please check whether this is true and update the docs accordingly? Happy to submit a PR if that helps you :) 
--Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2543f46-e0cd-1615-9d62-58ad18f2ce22
* Version Independent ID: 7b179a0e-e903-4a9e-9311-4851fa347dcd
* Content: [Purchase Power BI Premium for testing - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-testing?WT.mc_id=DP-MVP-5003435&)
* Content Source: [powerbi-docs/admin/service-admin-premium-testing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-premium-testing.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @marclelijveld, thanks for your question. I've forwarded it on to the doc owner for clarification. Thanks again!

**Comment by KesemSharabi** [comment]
Hi @marclelijveld,

I'm looking into this and will update you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @marclelijveld,

I just double checked this with the product team, and the documentation is correct. The note in [Purchase A SKUs for testing and other scenarios](https://docs.microsoft.com/power-bi/admin/service-admin-premium-testing?WT.mc_id=DP-MVP-5003435&#purchase-a-skus-for-testing-and-other-scenarios) is an A4 restriction that applies to both Premium (gen1) and Gen2.

Thanks,

Kesem
