### ISSUE TITLE
Add DLP eval operation type 

### ISSUE THREAD

**Issue by sergeig888** [MicrosoftDocs/powerbi-docs#3632]
Please add operation type for DLP (i.e., MIP label related CPU overhead). MIP docs stated that auto-scale was required to use MIP. This triggered additional customer questions and lead to this doc. Per Anton Fritz, MIP integration PM, DLP CPU consumption is not tracked yet, but this likely will change.  Need to augment response to this question: "Which operations contribute to interactive utilization, and which to background utilization?" if label related operations will become part of CPU consumption metrics.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7d18dd-7459-baea-2c12-fc47ffcd9b11
* Version Independent ID: 42220c7a-465b-2da2-3014-0aecd9631142
* Content: [Power BI Premium Gen2 FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-gen2-faq)
* Content Source: [powerbi-docs/admin/service-premium-gen2-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-gen2-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Thanks for the input @sergeig888. Forwarding it on to the doc owner.
@KesemSharabi, here is the link to the DLP info https://docs.microsoft.com/en-us/power-bi/admin/service-security-dlp-policies-for-power-bi. I can provide more details if necessary.

**Comment by KesemSharabi** [comment]
Hi @sergeig888,

I'm looking into this issue and will update you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @sergeig888,

It will take few more months until DPL will be tracked as part of the CPU consumption. Once this happens I'll consider adding DPL to [Which operations contribute to interactive utilization, and which to background utilization?](https://docs.microsoft.com/power-bi/admin/service-premium-gen2-faq#which-operations-contribute-to-interactive-utilization--and-which-to-background-utilization-) 

Thanks,

Kesem
