### ISSUE TITLE
Documentation: Custom code for AM/PM is incorrect

### ISSUE THREAD

**Issue by Asperson** [MicrosoftDocs/powerbi-docs#3634]
On this page
https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-custom-format-strings
custom code for AM/PM is incorrect, it must say "tt" instead of current "AM/PM".

And, could you, please, add link to that page to all related Power M documentation pages, like to DateTime.ToText():
https://docs.microsoft.com/en-us/powerquery-m/datetime-totext

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b30eef-0088-3389-5e7e-8009d064e856
* Version Independent ID: 826fcaf7-aa2a-cfca-25a7-d3b1d6af7382
* Content: [Use custom format strings in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-custom-format-strings)
* Content Source: [powerbi-docs/create-reports/desktop-custom-format-strings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-custom-format-strings.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfollis** [comment]
@Asperson - Thank you for the feedback and contribution to improving our docs. I have assigned this issue to the writer to make an update. It may take a couple of days to publish the change.

**Comment by artemus-harper** [comment]
Please don't link that page to https://docs.microsoft.com/en-us/powerquery-m/datetime-totext, the format is different. The ToText/FromText format strings follow the c# style.

**Comment by davidiseminger** [comment]
Thanks for the correction! I've update the article.
