### ISSUE TITLE
Set report Page size as tooltip not working correctly, no category or data labels for the shape map with the new February 2021 Update

### ISSUE THREAD

**Issue by presidentecarter** [MicrosoftDocs/powerbi-docs#3637]
[Enter feedback here]

The process for using a tooltip is not the same as documented in this page. There is now a part in the page information tab that you have to click that says "allow use as tooltip". This does work 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Using report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips)
* Content Source: [powerbi-docs/create-reports/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @presidentecarter, sorry for the long delay. I see that the page has been updated, so I am closing this issue now. Thanks for reaching out!
