### ISSUE TITLE
Dataflow Development Comment misleading

### ISSUE THREAD

**Issue by daryl-lynch-bzy** [MicrosoftDocs/powerbi-docs#3642]
The following comment is misleading:

"All work to create a dataflow is done in [Power Query Online](https://powerquery.microsoft.com/)"

We can use Power BI Desktop to develop and test a Dataflow before copying and pasting the query into Power Query Online.  It might be useful to mention this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88628925-92be-d8d7-faaa-fc91ea267fb9
* Version Independent ID: 88628925-92be-d8d7-faaa-fc91ea267fb9
* Content: [Power BI usage scenarios: Self-service data preparation - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @daryl-lynch-bzy.

I've assigned this issue to the doc author for review.

**Comment by peter-myers** [comment]
Hi @daryl-lynch-bzy  - thanks for your feedback. We'll take it into consideration. #please-close
