### ISSUE TITLE
Dataflow - suggested edits

### ISSUE THREAD

**Issue by daryl-lynch-bzy** [MicrosoftDocs/powerbi-docs#3643]
It may useful to mention the following points:

> Dataflows can be linked to other Dataflows.  Point 9 suggests that only Datasets can use Dataflows.
> Dataflow and Dataset refresh - it might be helpful to mention that Power Automate can be use to trigger sequential Dataflow and Dataset refreshes.
> Enhanced Compute Engine - should this feature be mentioned?
> BYO Azure Data Lake Storage versus Enhanced Compute Engine - how do these features interact?
> Dataflow limited connectors - mention there is a limited set of Data Connectors for the Power Query Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88628925-92be-d8d7-faaa-fc91ea267fb9
* Version Independent ID: 88628925-92be-d8d7-faaa-fc91ea267fb9
* Content: [Power BI usage scenarios: Self-service data preparation - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-self-service-data-preparation.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @daryl-lynch-bzy.

I've assigned this issue to the doc author for review.

**Comment by peter-myers** [comment]
Hi @daryl-lynch-bzy  - thanks for your feedback. The objective of this article is *self-service* data preparation. The dataflow features you mention in your feedback will be covered in an upcoming usage scenario that focuses on IT-led data preparation. Stay tuned for that article. #please-close
