### ISSUE TITLE
More information needed to understand the workspace state "Not Found"

### ISSUE THREAD

**Issue by chrisbrown1279** [MicrosoftDocs/powerbi-docs#3644]
Customers are finding "Not Found" as a workspace status.  The documentation doesn't provide much information on why this is happening and how to correct it.  
I suggest more information on this status to assist customers.

thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eb228f2-d033-a44b-5570-da815663e246
* Version Independent ID: 1260b40c-f6bf-3e23-b60f-6966753424b1
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal#workspaces)
* Content Source: [powerbi-docs/admin/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @chrisbrown1279, I see that here: https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-workspaces#workspace-states the following explanation is given: "If the customer's API request includes a workspace ID for a workspace that doesn't belong to the customer's tenant, "Not found" is returned as the status for that ID." Does answer the customer need, or is this the "thin" information you were referring to?

**Comment by paulinbar** [comment]
Hi @chrisbrown1279, I am going to be optimistic and assume that your thumbs up means that the explanation in the docs met your needs :) but if I am mistaken, please feel free to reopen this issue and we'll follow up. Thanks for responding!
