### ISSUE TITLE
Issue with how unlimited content sharing is shown

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#3648]
Hello there. I like the new page. I noticed one issue:

The "Unlimited content sharing" item says it works for PPU, but it's really only supported for capacity (P SKUs only). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adaf5d3f-b1de-10c0-b5d0-42bfd5cb5d30
* Version Independent ID: adaf5d3f-b1de-10c0-b5d0-42bfd5cb5d30
* Content: [Power BI Premium features. - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-features)
* Content Source: [powerbi-docs/admin/service-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-features.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by paulinbar** [comment]
Hi @sqlchick, thanks for reaching out to us with your comment. I am forwarding it on to the doc own for further consideration. Thanks!

**Comment by KesemSharabi** [comment]
Hi @sqlchick,

You're correct - thank you for pointing this out!

I removed PPU from the *Unlimited content sharing* entry, and replaced it with Premium (Gen2 and the original version).

Thanks,

Kesem
