### ISSUE TITLE
Typo on on-premises data gateway page

### ISSUE THREAD

**Issue by mattwhitfield** [MicrosoftDocs/powerbi-docs#3649]
Types of gateways -> Virtual network data gateway -> says 'No installation is requried' and should be 'No installation is *required*'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa9e720-7c65-9e70-acba-7cb58fd5b4b3
* Version Independent ID: 0bcb5169-a217-e90d-52b3-4fdff2b8cf4c
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-onprem.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Hi @mattwhitfield,

Thank you for spotting this typo and for letting us know. I will correct the document shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @mattwhitfield,

This typo is no fixed, see [Types of gateways](https://docs.microsoft.com/power-bi/connect-data/service-gateway-onprem#types-of-gateways).

Kesem
