### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by christino156** [MicrosoftDocs/powerbi-docs#365]
In the last section. "DAX tables and filtering" there are two typos in the paragraph "DAX table functions". Firstly, when  two "rather" are used instead of one in the sentence: "These functions return a full table rather, rather than a value." And secondly, when the words "to" and "use" are concatenated in the sentence "So touse the above DAX expression example...". 

Furthermore, in the previous section, "Table relationships and DAX", I believe there is a mistake in the paragraph "DAX relational functions", where it is mentioned that "For example, the TABLE function...". I believe it should be the "RELATED" function there.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @christino156 .
We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Great points and fixes - thanks! I've updated those articles, they'll refresh on the site in a day or so. Thanks!
