### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#3650]
For section https://docs.microsoft.com/en-us/power-bi/admin/desktop-privacy-levels#configure-privacy-level-settings 

Please add the following: 

Note that the privacy level configuration is not automatically transferred to the Power BI service when you upload your Power BI Desktop file. For example, you might have a Desktop file with multiple data sources set to Organizational, but after uploading the file, scheduled refresh fails because Power BI might treat these data sources as Private unless you apply a less restrictive level manually. In the Power BI service, you can set the privacy level under Advanced settings when adding a data source to an on-premises data gateway, as in the following screenshot.

![image](https://user-images.githubusercontent.com/37197217/156455662-8220e06f-4d1e-4231-9629-4969cda6a183.png)

For Caution with text "The Ignore the Privacy levels and potentially improve performance does not work in the Power BI service. As such, Power BI Desktop reports with this setting enabled, which are then published to the Power BI service, do not reflect this behavior when used in the service. However, the privacy levels are available on the personal gateway.". 

Please update the same to: 

The Ignore the Privacy levels and potentially improve performance does not work in the Power BI service. As such, Power BI Desktop reports with this setting enabled, which are then published to the Power BI service, do not reflect this behavior when used in the service because the service will always use “Combine data according to your Privacy Level setting for each source”. However, the privacy levels are available on the personal gateway.". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/desktop-privacy-levels)
* Content Source: [powerbi-docs/admin/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @prvillal,

Thanks you for your comment. @paulinbar - is this something you're familiar with?

Kesem

**Comment by paulinbar** [comment]
@davidiseminger, are you familiar with this?

**Comment by davidiseminger** [comment]
This article has been reviewed and updated since this comment, thanks for your submission.
