### ISSUE TITLE
Fields are Required

### ISSUE THREAD

**Issue by v-maquay** [MicrosoftDocs/powerbi-docs#3651]
Timepoint and Timepoint2 are required fields, though the default data works

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcddef48-ab1d-cdd2-900a-9b9f3500a06f
* Version Independent ID: 42ce0182-3006-4271-7981-a9f8a984ca53
* Content: [Install the Premium Gen2 metrics app - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-install-gen2-app?tabs=1st)
* Content Source: [powerbi-docs/admin/service-premium-install-gen2-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-premium-install-gen2-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @v-maquay,

Good observation - thank you for this comment! 

I'll fix the article shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @v-maquay,

I updated *step 4* in [Run the app for the first time](https://docs.microsoft.com/power-bi/admin/service-premium-install-gen2-app?tabs=1st#run-the-app-for-the-first-time) to say *automatically populated* in the *Required* column of the Timepoint and Timepoint2 fields.

Thanks,

Kesem
