### ISSUE TITLE
Update page according to the latest updates

### ISSUE THREAD

**Issue by vishnukatta** [MicrosoftDocs/powerbi-docs#3652]
with the current update, this page information is no longer valid. Could you please update the information according to the latest updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for formatting in reports - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @vishnukatta . This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @vishnukatta , 
Thank you for your suggestion.  We're in the process of updating all articles in the /Visuals section of our docsite.  Look to see the updated article later this month. 
All the best,
The DOCS team
