### ISSUE TITLE
More details needed on Database connections

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#3654]
More details are needed on Database connections, from the perspective of a Power BI Desktop user. There are so many features, pop-ups and details to discuss, most of it is not documented here or elsewhere. There are already some separate pages in this section for specific databases, but not all kinds of databases are covered.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Hi @Mike-Honey,

Thanks you for your comment. @davidiseminger - can you please take a look at this?

Kesem

**Comment by davidiseminger** [comment]
Thanks for your feedback, we're improving those connections articles.
