### ISSUE TITLE
Can you clarify 

### ISSUE THREAD

**Issue by awvala** [MicrosoftDocs/powerbi-docs#3656]
Can you provide clarification on the note regarding the rate limit for PPU License?  I'm receiving conflicting information from Microsoft support reps concerning premium capacity and export limits from paginated reports.  

"Note
You can also follow along if you have a [Power BI Premium Per User (PPU) license](https://docs.microsoft.com/en-us/power-bi/admin/service-premium-per-user-faq) but you will be limited to one export within a five minute window."

To me, the note insinuates that the PPU license comes with a unique restriction of 1 export per 5 minutes.  The Microsoft tech support specialist I just spoke with said this rate limit is for all premium capacity licenses, not just PPU.  Any clarification would be appreciated.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d01510-7ea5-3556-00c1-de77f551081d
* Version Independent ID: c5ec0e49-a288-8948-8a87-284bc2d59015
* Content: [Export paginated reports with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-paginated-integration)
* Content Source: [powerbi-docs/collaborate-share/service-automate-paginated-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-paginated-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Hi @awvala,

I just confirmed with the engineering department and the note in [Export Power BI paginated reports with Power Automate](https://docs.microsoft.com/power-bi/collaborate-share/service-automate-paginated-integration) > [Prerequisites](https://docs.microsoft.com/power-bi/collaborate-share/service-automate-paginated-integration#prerequisites) is correct. One export (of a paginated report) withing a five minute window applies only to PPU.

Thanks,

Kesem
