### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by FelixPeckitt** [MicrosoftDocs/powerbi-docs#3659]
[Enter feedback here]
Typo in docs:

"Visualizations on dashboards can't be copied and pasted into Power BI reports or other dashboards.

Open a report that has at least one visualization.

Select the visualization and use Ctrl +C to copy, and Ctrl +V to paste."

"Can't" in this paragraph should be "can"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [Copy and paste a visualization in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @FelixPeckitt ,
Thank you for your feedback. While you can copy/paste a visual from a report, you can't do the same for a visual on a dashboard. 
All the best,
The DOCS team
