### ISSUE TITLE
Mobile Visual Interactions

### ISSUE THREAD

**Issue by Firefly82** [MicrosoftDocs/powerbi-docs#3660]
I've found that the visuals in the Mobile View do **not** keep the interaction settings from the desktop. For example, if I disable the filter option on a table, that doesn't carry over to the Power BI App when I view the visual. I don't see any way to set that same interaction on the Mobile View in the desktop either. Is this a known issue being worked on, or am I just missing something on my end?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions)
* Content Source: [powerbi-docs/create-reports/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Hi @Firefly82,

Thank you for your comment. @paulinbar - can you please take a look at this?

Kesem

**Comment by paulinbar** [comment]
Hi @Firefly82 and @camilafragoso, Let me look into this and I will get back to you. Thanks!

**Comment by paulinbar** [comment]
Hi @Firefly82, I checked with the product team and they told me that they recently discovered this issue and the fix should be out in the April Desktop release. In the meantime they have provided comments about this in the community at the following links.

- https://community.powerbi.com/t5/Desktop/Visual-interaction-setting-not-taken-into-account-in-Mobile-view/m-p/2369578#M852434

- https://community.powerbi.com/t5/Mobile-Apps/Power-BI-Mobile-not-show-any-result/m-p/2378493#M6614

In any event, thanks for noticing this and sending in a comment. Participation like this help us improve things!
