### ISSUE TITLE
Export to PDF disabled?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#3662]
Hello, I am an administrator. Where do I learn how to check this setting you speak of?
> If the Export to PDF menu item isn't available in the Power BI service, it's likely because your Power BI administrator disabled the feature. Contact your administrator for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export reports to PDF - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-pdf?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/consumer/end-user-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-pdf.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @jonwbstr,
Thank you for contributing to the quality of our docs.
In the Power BI service, open the Admin portal and select Tenant settings.  Scroll down to the setting for PDF. 
All the best,
The DOCS team

**Comment by jonwbstr** [comment]
The purpose of this ticket is to update the documentation, has a pull request been created?

**Comment by paulinbar** [comment]
Hi @jonwbstr, I added a note for administrators to the limitation that you mentioned.
