### ISSUE TITLE
Order of words issue

### ISSUE THREAD

**Issue by vertig00bg** [MicrosoftDocs/powerbi-docs#3663]
It is a order of words issue. The following" 
''Across the Format pane, we’ve merged font family and font size onto a single line. Again, we want to reduce vertical space and better to align with Office.'' should be ''Across the Format pane, we’ve merged font family and font size onto a single line. Again, we want to reduce vertical space and TO better align with Office.''

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99728831-9577-faee-e82a-8def045dadea
* Version Independent ID: 99728831-9577-faee-e82a-8def045dadea
* Content: [The new Format pane in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-format-pane)
* Content Source: [powerbi-docs/fundamentals/desktop-format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-format-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Hi @vertig00bg,

Thank you for pointing this out, I'll fix it shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @vertig00bg,

Thanks again for pointing out this error which I have now fixed - see [Merged font settings](https://docs.microsoft.com/power-bi/fundamentals/desktop-format-pane#merged-font-settings).

![image](https://user-images.githubusercontent.com/54834915/157691220-b57f17ee-abf7-43df-b918-10361daac47a.png)

Kesem
