### ISSUE TITLE
This is suddenlty failing for several people

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#3664]
Please see the issue reported in the community:

https://t.co/5hU0ijUVjT

This error now pops up in flows that were working until yesterday:

"Exporting a paginated report requires permissions in both report and dataset workspaces"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa98bb-e9d6-a46f-2c37-6d47b010ac8c
* Version Independent ID: 6582e1da-6d2b-94d0-bfc9-fea0491c22eb
* Content: [Export a paginated report for each row in an Excel Online table or SharePoint list - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-paginated-excel-sharepoint-list)
* Content Source: [powerbi-docs/collaborate-share/service-automate-paginated-excel-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-paginated-excel-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by KesemSharabi** [comment]
Hi @asocorro,

Thank you for your comment. I'm looking into this and will get back to you.

Kesem

**Comment by KesemSharabi** [comment]
Hi @asocorro,

Can you please verify that the user that calls the API is a viewer/contributor/member/admin in the dataset’s workspace?

Thanks,

Kesem

**Comment by asocorro** [comment]
Yes, an admin in both.  I even moved the report to the same workspace as the dataset.

Like others that have posted in the Community link I sent, that flow had been working fine for months.

Thanks,
Adolfo

________________________________
***@***.***

Adolfo J. Socorro, Ph.D.
President
eSolutions, Inc.

eSolutionsPR.com <http://www.esolutionspr.com/>
LinkedIn Profile<https://www.linkedin.com/in/adolfosocorro/>
787-553-3200 (Mobile)
.:. Business Intelligence and SQL Server Solutions .:.





The information contained in this message is a private interchange between the sender and the recipient.
Business ideas, proposals, and other such matters may not be disclosed to third parties without prior mutual consent.

**Comment by KesemSharabi** [comment]
Hi @asocorro,

Thanks for confirming and for pointing out that others are experiencing the same problem. I'll carry on looking into this and will update you as soon as I get some answers.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @asocorro,

After further investigation, I was asked to let you know that you'll need to open a [support ticket](https://support.powerbi.com) for this, so that the engineering team can further investigate.

Thanks,

Kesem
