### ISSUE TITLE
How to delete PowerBI files that prevent Power BI Desktop from starting

### ISSUE THREAD

**Issue by TimoRiikonen** [MicrosoftDocs/powerbi-docs#3665]
[Enter feedback here]
I believe that a problematic report prevents Desktop from starting at all.
I might have enabled logs, but where can I find them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533d0cd5-b457-863c-f862-49fac672332c
* Version Independent ID: f5df6cb3-049a-eff0-4d7b-3c3843927a5e
* Content: [Resolve issues when starting Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-error-launching-desktop)
* Content Source: [powerbi-docs/connect-data/desktop-error-launching-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-error-launching-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @TimoRiikonen. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
