### ISSUE TITLE
Considerations and limitations

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#3666]
Hello,

Under the "considerations and limitations" section, please add "Exporting a Power BI report to file using the exporToFile API, is not supported for [Premium Per User (PPU)](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq)"

The limitations currently say the only consideration and limitation is the report must be in a premium workspace and makes no mention of the license requirement. Other REST APIs do not have this extra consideration/limitation from what I can find.

The above language is found in a Note in the document, which I didn't see until a customer pointed it out to me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI embedded analytics reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-to?tabs=gen2#concurrent-requests)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for pointing this out, @jonwbstr  I added this limitation to the *considerations and limitations* section and it should go live in the next few days.
