### ISSUE TITLE
#3662 closed without any doc improvements

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#3667]
The ticket was submitted to improve the documentation, please reopen #3662 and respond to the request for documentation improvement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export reports to PDF - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-pdf?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/consumer/end-user-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-pdf.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
HI @jonwbstr, I added a note for administrators in the limitation that you mentioned. Should be live in a few hours.
