### ISSUE TITLE
With Power BI Report Server 

### ISSUE THREAD

**Issue by SimonSeez** [MicrosoftDocs/powerbi-docs#3669]
Hello,

How would I be able to achieve this using Power BI Report Server

 Best Regards,
Simon 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfollis** [comment]
Hi @SimonSeez - thanks for the feedback on our documentation. I see that you are asking that our docs be expanded to include an additional scenario - using Power Automate with Power BI Report Server. We'll verify whether the scenario is actually viable first - if so, we'll add your suggestion to our writing backlog.

**Comment by paulinbar** [comment]
Hi @SimonSeez, just to update that we're still checking whether this is a viable - but in any event the issue has been add to our work item backlog, so I'm closing it here for now. Thanks!
