### ISSUE TITLE
Accidental removal of shared report/dashboard

### ISSUE THREAD

**Issue by GeorgeCMElliott** [MicrosoftDocs/powerbi-docs#367]
After a view only user removes the report or dashboard via trash bin icon they don't seem to have any way to bring it back. Even after owner "reshares" it with them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6350fc32-0d69-f6f9-1f7c-2d82cbea0656
* Version Independent ID: dddabd4d-231e-db2a-6d3a-b65848c4c641
* Content: [Display the Power BI content that has been shared with me - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-shared-with-me)
* Content Source: [powerbi-docs/consumer/end-user-shared-with-me.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-shared-with-me.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @GeorgeCMElliott -- that sounds like a bug. If the owner reshares it with them, it should be no different that the owner sharing it with them in the first place. 
I suggest asking the community, https://community.powerbi.com/. 
If that's no help, you may need to create a support ticket, https://powerbi.microsoft.com/en-us/support/.
