### ISSUE TITLE
Additional Snowflake AAD with SSO and Data Gateway user roles setup steps

### ISSUE THREAD

**Issue by v-edgardoc** [MicrosoftDocs/powerbi-docs#3671]
When connecting Power BI Desktop to Snowflake with Azure Active Directory authentication (AAD) Single Sign-on (SSO), Power BI Snowflake connector requires a role to be granted to the user in Snowflake database settings.

If using Data Gateway with this configuration, an additional configuration step is required, pe:

https://eng.ms/docs/cloud-ai-platform/digital-transformation-platform/azure-data-intelligence-platform/data-cloud/power-bi/power-bi-troubleshooting-guides/troubleshooting/snowflake

Additional information in setting up and configuring user roles in Snowflake are available in these links:

https://docs.snowflake.com/en/user-guide/admin-user-management.html#user-roles

https://docs.snowflake.com/en/sql-reference/sql/grant-role.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 328a161c-b51e-05d1-c185-cb244547c3f3
* Version Independent ID: 0bef7bb0-541e-a74b-0f68-359690ae8b8e
* Content: [Connect to Snowflake with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/service-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
We've updated this doc, and much of the data connector information is now in Power Query docs.

**Comment by MichaelTomar** [comment]
[Skyvia](https://skyvia.com/data-integration/powerbi) offers an alternative solution for integrating Snowflake with Power BI.
