### ISSUE TITLE
How to delete a dataset?

### ISSUE THREAD

**Issue by russ-ashman** [MicrosoftDocs/powerbi-docs#3673]
Article mentions it is possible to delete a dataset but does not cover how to get it done. When I click on the "..." delete is not an option. How to remove old datasets that I own that will never be used?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, dataset, or workspace - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-delete)
* Content Source: [powerbi-docs/create-reports/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-delete.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @russ-ashman, thanks for your feedback! You have indeed stumbled upon a bug. I checked with the product team and they said they are aware of this and are working to fix it. Basically, the list of available options a particular user sees is not consistent - it depends on where you open the options menu from. Do you recall where opened the menu from? To start with, to delete a dataset, you must have an Admin, Member, or Contributor role on the workspace where the dataset is located. Then, in the datasets hub, if the dataset appears for you in the "My datasets" tab, you should be able to see the Delete option. If you view the dataset in the "All" tab, I don't think the Delete option shows up. If you go to the workspace where the dataset is located, I think you will also see the Delete option. 
I would be interested to know whether this works for you. Also, I would be interested to know where you originally tried and didn't see the option.
Again, thanks for reaching out!
