### ISSUE TITLE
New Sign in UI.

### ISSUE THREAD

**Issue by AnkitKukreja19** [MicrosoftDocs/powerbi-docs#3674]
Hi Team,
I wanted to share a feedback and just wanted to make sure that we can make the changes for the users.
I see a new UI while logging in a new private window. This generally happens only if you are using in private for first time or if I'll clear all the browser history and cache from my browser or If I'm logging it for the first time.
This is a page I see when signing in for 1st time(Pic -1). Whereas, earlier we used to see the UI already available in the doc(Pic-2).

![image](https://user-images.githubusercontent.com/101596015/158244777-b1a20bfa-a9a8-4529-8ef1-fff4df1d0ee3.png)

![image](https://user-images.githubusercontent.com/101596015/158245054-0407e271-bd5e-4197-bb6a-84ace443cebd.png)

https://docs.microsoft.com/en-us/power-bi/consumer/end-user-sign-in

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ce18a4-d4d9-c16f-0ffd-c0711564ca7a
* Version Independent ID: c6c897ce-2f0f-9a13-a321-89b5a8c85152
* Content: [Sign in and sign out - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-sign-in)
* Content Source: [powerbi-docs/consumer/end-user-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-sign-in.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Thanks for your comment, @AnkitKukreja19 . This issue has been assigned to the doc author for review.

**Comment by AnkitKukreja19** [comment]
Hi! Any updates or ETA on this?

**Comment by elkhalafy0** [comment]
Okay

**Comment by mihart** [comment]
Hi @elkhalafy0 @AnkitKukreja19 ,
No update yet.  We are making other changes to login and will be updating the docs with all changes at the same time.  
Thanks
@mihart

**Comment by AnkitKukreja19** [comment]
Hi! @mihart 

Thank you for your reply. Do we have an ETA for this?

**Comment by AnkitKukreja19** [comment]
Hi! @KesemSharabi @mihart 

Can you please provide us with an ETA for this? 

Also, can you add additional details like what are the scenarios in which this sign-in UI would be seen? I've identified few and sharing them for your reference.

1) If the user is login app.powerbi.com the very first time.
2) Clearing browser history or cookies.
3) Opening in private or incognito mode of the browser.

**Comment by mihart** [comment]
Hi @AnkitKukreja19 , @KesemSharabi ,
This work is still in my backlog.  I can't commit to a date by which I'll get to this.  But know that I am not ignoring this Git Issue.  Thanks.

**Comment by mihart** [comment]
Hi @AnkitKukreja19 ,
This article has been updated.  Thank you for your input and patience.
