### ISSUE TITLE
Where do I get the data for Pivot Column example

### ISSUE THREAD

**Issue by haysonba** [MicrosoftDocs/powerbi-docs#3677]
The page talks about a different data set for Pivot column. But, it doesn't tell me where to get this data so I can follow along.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ca589e-10e9-3924-a3ac-c774368cdec6
* Version Independent ID: 2c7f64d7-8306-1622-6ca3-912b805acf0c
* Content: [Perform common query tasks in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-common-query-tasks)
* Content Source: [powerbi-docs/transform-model/desktop-common-query-tasks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-common-query-tasks.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
We've updated the article with a link.
