### ISSUE TITLE
Previous quarter and current year sales chart didn't work

### ISSUE THREAD

**Issue by haysonba** [MicrosoftDocs/powerbi-docs#3678]
I followed along with the Previous Quarter Sales measure. I copied and pasted the code for the measure. Then I tried to create the clustered column chart with this measure and with the SalesAmount field. 

However, in my chart, it only showed one bar instead of two. 

![image](https://user-images.githubusercontent.com/39141000/158315842-8bbc3b42-b2c0-4443-afa9-b0c37f91aeaf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [DAX basics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-quickstart-learn-dax-basics)
* Content Source: [powerbi-docs/transform-model/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **davidi**

**Comment by vlpchiara** [comment]
Hi, I have the same problem as [haysonba]
Can someone support me? 
![Capture](https://user-images.githubusercontent.com/104903918/166675304-ba4585ee-f053-4859-9601-4362987e824c.JPG)

**Comment by Minewiskan** [comment]
@haysonba, @vlpchiara  - Thanks for pointing out this wasn't clear. We added some additional clarification on how you can create that chart.
