### ISSUE TITLE
Mention that "DirectQuery/Live connection (per second)" is per capacity and not per dataset

### ISSUE THREAD

**Issue by RuiRomano** [MicrosoftDocs/powerbi-docs#3679]
Its not 100% clear that "DirectQuery/Live connection (per second)" is a per capacity metric and not per dataset. A customer planning for a Premium Capacity deployment with DirectQuery its a very important measure to consider and I believe we should make it clearer:

I would recommend changing to:

"2 These limits only apply to the datasets workload per Capacity"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00bf7e05-4c27-38a6-4951-29dff857e10d
* Version Independent ID: 00bf7e05-4c27-38a6-4951-29dff857e10d
* Content: [What is Power BI Premium Gen2? - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @RuiRomano,

I started an email thread for this.

Thanks,

Kesem
