### ISSUE TITLE
I got an error while creating ssl certificate

### ISSUE THREAD

**Issue by nilgunh** [MicrosoftDocs/powerbi-docs#368]
Hi, 

I got an error after command pbiviz --create-cert. Could you help me here?

![2018-10-26 14_51_45-node js command prompt](https://user-images.githubusercontent.com/42370554/47567634-5ce4f800-d92f-11e8-97d4-bd5fbed655ff.png)

**Comment by kfile** [comment]
Thanks for your comment, @nilgunh . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
