### ISSUE TITLE
Trying to understand how exactly background operations contribute to resource utilization in Gen 2

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3681]
[Enter feedback here]
Hi the doc team,
we're trying to understand how exactly background operations contribute to resource utilization in Gen 2.
We understand that a dataset refresh for example, that consumes 30 minutes of CPU, will contribute on a 1/2880 ratio for the next 24 hours, is it right ? Would it be possible to explain with an precise example ? 
Or does this one works : a dataset refresh starts at 9am on January 1st, ends at 10am, and consumed 30 minutes of CPU => it will contribute with 30x60/2880 = 0.625 seconds of CPU for each 30 second evaluation cycle for the next 24 hours, starting at 10am on Januaty the first until 10am on January the 2nd.
Thanks for your help.
Best regards,
Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d931a46e-51b7-db23-0109-b9d317db464c
* Version Independent ID: d931a46e-51b7-db23-0109-b9d317db464c
* Content: [Power BI Premium Gen2 FAQ - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @nstraw,

We're working on improving the documentation for the Gen2 app. I'll check with the product team to see what information I can share with you.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @nstraw,

After speaking to the marketing team, I can confirm that we're not planning to make documentation changes at present. However, this may change in the future.

Your calculation which I believe is based on the information from the docs, is correct.

Hope this helps,

Kesem
