### ISSUE TITLE
Trying to understand Performance Delta

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3682]
[Enter feedback here]
Hi doc team,
Is it possible to have details on the calculation of the Performance Delta ?
The doc says "For example, 20 suggests that there's a 20% improvement today, compared with the same metric taken a week ago." => What metric ? Is it CPU, Duration, Users, all the 3 ? I tried to redo the computation but no success...
Thanks for the help!
Nicolas

![image](https://user-images.githubusercontent.com/35227452/158668796-47358710-899a-41cd-99eb-c1a19b7f7ad5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @nstraw,

Thanks for getting involved and for your question!

Performance delta refers to CPU usage, which is what Power BI uses to measure performance.

Hope this helps,

Kesem

**Comment by nstraw** [comment]
Hi @KesemSharabi,

as you can see on the image, CPU diff does not match : there's a difference of 216% between day 1 and and 7 and Performance Delta says -25, how is it calculated ?

Thanks to take the time to look at my question.

Nicolas

PS : I'm gonna create another issue as it looks like you don't follow up on issue you closed

![158668796-47358710-899a-41cd-99eb-c1a19b7f7ad5](https://user-images.githubusercontent.com/35227452/161433502-74912ebb-1d8f-402d-bb55-e61f839e9698.png)
