### ISSUE TITLE
Missing Dataflow parameters

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3683]
[Enter feedback here]
Hello,
I have checked with several customers, none of them have the Dataflow Workload settings displayed in the Admin Portal (like %memory or container size). Is it an anticipation for future release ? 
Thanks!!
Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Thanks for your comment, @nstraw.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by nstraw** [comment]
Hello @KesemSharabi,

thank you for your response.

I did not explain clearly the issue in the documentation, sorry about that, I will try to explain more.

Actually the section #dataflows in this documentation provides information on parameters like Max Memory (%), Container Size that are not (yet?) exposed in the Gen2 capacity admin page.

So I would expect those parameters either to be removed from the documentation, or to be exposed in the product.

So the doc is in sync with the product, that was my point in the first place :)

Theses parameters are inherited from the Gen1, it is confusing in this doc about whether or not they will be exposed some day in Gen 2.

Let me know your findings!

Thanks,
Nicolas

![image](https://user-images.githubusercontent.com/35227452/159720071-d000028e-3855-4405-b68b-eb72dd2a25cd.png)
