### ISSUE TITLE
Regarding the limitation of max 50 reports per minute

### ISSUE THREAD

**Issue by rraveend** [MicrosoftDocs/powerbi-docs#3684]
1.  is this fixed window like if i send 50 request in 11:30:53 , i can send additional 50 in 10:31:01 ?
or is sliding window - if i send 50 request in 11:30:53 , i can end additional 50 in 10:31:53 ?
2.  Is the limits of 50 a minute per capacity purely on the report execution i.e. that is the step when a report export request is imitated OR does it also include the actual report processing?
3. when i scale up the PBI - embedded capacity from say A3 to A6, it doenst seems to increase the limit of max 50 - is there any configuration that could help here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI embedded analytics paginated reports API - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your questions, @rraveend. I’ll contact the developers and see I can get answers for you.

**Comment by mberdugo** [comment]
Hi @rraveend, 
Here are the answers to your questions from the developers:
1.	To the best of my knowledge is sliding as a any DOS throttle in power bi
2.	Is not per capacity is per user, is how many export calls can be initiated
3.	No, it's not tied to the size of the capacity
I hope this helps.

**Comment by elkhalafy0** [comment]
Thank you for your response
