### ISSUE TITLE
Incremental Refresh is for PREMIUM ONLY, but the content states that it is available for PRO

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerbi-docs#3685]
You make this statement:
Supported plans
Incremental refresh is supported for Power BI Premium, Premium per user, **Power BI Pro**, and Power BI Embedded datasets.

But when I try to set this up on a PRO Workspace, I get this message:
This dataflow contains tables with active incremental refresh policies, which require Premium to refresh. To enable refresh, **upgrade this workspace to Premium capacity.** [Learn more](https://go.microsoft.com/fwlink/?LinkID=875546)

Please be accurate about what plans are supported. THIS IS CRITICAL!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for datasets and real-time data in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by Minewiskan** [comment]
@ToddChitt - Are you trying to setup IR for a _dataflow_ or a _dataset_? The article you reference is IR for a dataset.

**Comment by ToddChitt** [comment]
Data flow

**Comment by Minewiskan** [comment]
@ToddChitt - IR for dataflows is described in [Using incremental refresh with dataflows](https://docs.microsoft.com/en-us/power-query/dataflows/incremental-refresh#incremental-refresh-implementation-details), while it is a bit obscured, "Using incremental refresh in dataflows created in Power BI requires that the dataflow reside in a workspace in Premium capacity. Incremental refresh in Power Apps requires Power Apps Plan 2." is described just below the first image in the intro.

**Comment by ToddChitt** [comment]
Do me a favor:

Use BING search engine for the term: “power bi data flow incremental refresh”

 

Look at the top results. It is a Microsoft Doc with the phrase “Dataflow”. THAT is the article that started all this.

 

If THAT article does NOT pertain to DATA FLOWS, there please go fix THAT.
