### ISSUE TITLE
Code example throws away all exceptions

### ISSUE THREAD

**Issue by timabell** [MicrosoftDocs/powerbi-docs#3688]
https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal-certificate#step-4---get-the-certificate-from-azure-key-vault
```
    catch (Exception)
    {
        return null;
    }
```
Please don't ever put something like this in examples. People *will* copy paste it into production code making it extremely hard to troubleshoot & support. Not everyone knows just what incredibly bad practice this is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 236c57e5-a1ec-6244-d422-b40444e9050c
* Version Independent ID: 2e83122b-755e-f888-d91e-d8af71fb47ef
* Content: [Embed Power BI content in an Power BI embedded analytics application with service principal and a certificate - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal-certificate)
* Content Source: [powerbi-docs/developer/embedded/embed-service-principal-certificate.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-service-principal-certificate.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for pointing this out, @timabell . I asked the developers to provide an alternative code snippet. In the meantime, if you have any suggestions for what to put instead, I'd love to hear them.
Thanks again.

**Comment by mberdugo** [comment]
Thanks again, @timabell, for pointing out this problem. The code has been updated and should be live in a day or so.

**Comment by timabell** [comment]
Amazing, diff looks good to me :+1:  https://github.com/MicrosoftDocs/powerbi-docs/commit/29a731f1f3b6db47030e93d2be459de7a7cacf96
