### ISSUE TITLE
Update Request

### ISSUE THREAD

**Issue by mcruz206** [MicrosoftDocs/powerbi-docs#369]
I noticed that the Power BI Governance and Deployment Approaches document does not list Power BI Report Server as an option for deploying Power BI Reports for on-premises scenarios.  Can this document be updated?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba176b5-d050-3be8-cc69-d8534b7e1982
* Version Independent ID: 8284cd12-eae5-29ea-7c19-3b6ef883355e
* Content: [Governance and deployment approaches - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-governance)
* Content Source: [powerbi-docs/service-admin-governance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-governance.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Hello @mcruz206 , thank you for your question. I've assigned it to the doc author for review.

**Comment by ChimeneB** [comment]
Can we get this updated, please? The paper was published in March 2016!!

**Comment by mgblythe** [comment]
@ChimeneB - thanks for the feedback. I will add it to the backlog but I don't have an ETA for an update to this paper. Is there particular info you're looking for?

**Comment by Grayincarnation** [comment]
@mgblythe  - I stumbled upon this when searching for a high-level strategy for PBI deployment, usage, sharing, etc. Seems like one of the two go-to resources for all the PBI scenarios. My initial thought was also if this whitepaper was still accurate, as there are many updates in the last 2 years.

**Comment by juliobrazil** [comment]
Has the document been updated recently? Power BI envolved a lot since them.

**Comment by DeanGross** [comment]
This document is getting more and more out of date. Please update it incorporate new features and functionality

**Comment by mgblythe** [comment]
Closing this one out. The plan is to remove this paper and ensure an updated version of the information is added to docs or other papers.
