### ISSUE TITLE
The Call Quality Data Connector is targeting CY22H2 not CY22H1

### ISSUE THREAD

**Issue by williamlooney** [MicrosoftDocs/powerbi-docs#3690]
Call Quality Data Connector is targeting CY22H2 not CY22H1, the table needs to be updated. I'm the PM owner for the infra work to enable this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#power-bi-feature-availability)
* Content Source: [powerbi-docs/enterprise/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the feedback, @williamlooney. This update has been made. Did you know that you can make these types of changes yourself? Check out aka.ms/contribute for details.

**Comment by williamlooney** [comment]
I am aware that it is possible, just haven’t invested the time to learn how. May be FHL is the time 😊
