### ISSUE TITLE
Data Source Headings

### ISSUE THREAD

**Issue by Michael-Morrissey** [MicrosoftDocs/powerbi-docs#3692]
The table of data sources contains the headings:

1. Data Source
2. Connect from Desktop
3. Connect and Refresh from Service
4. DirectQuery / Live connection
5. Gateway (supported)
6. Gateway (required)
7. Power BI Dataflows

For the Intune Data Warehouse entry, 3. Connect and refresh from service is a Yes. 

What does this mean? Power BI Service? the Intune DW SaaS? It states that Gateway is not supported. So can a report that works on the desktop be published or not?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Michael-Morrissey. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Michael-Morrissey,

Can you please indicate which document you're referring to?

Thanks,

Kesem

**Comment by Michael-Morrissey** [comment]
Hi Kesem,

This is the document: Power BI data sources - Power BI | Microsoft Docs<https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources>
Regards,

Michael.

From: Kesem Sharabi ***@***.***>
Sent: Wednesday, 23 March 2022 8:28 PM
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Morrissey, Michael (IST-FULLCIRCLEPARTNERS) ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [MicrosoftDocs/powerbi-docs] Data Source Headings (Issue #3692)

You don't often get email from ***@***.*** Learn why this is important<http://aka.ms/LearnAboutSenderIdentification>

Hi @Michael-Morrissey<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMichael-Morrissey&data=04%7C01%7CMichael.Morrissey%40riotinto.com%7Cf4e7fbf9935f41ea852908da0cc883c8%7C4341df80fbe641bf89b0e6e2379c9c23%7C0%7C0%7C637836352593797695%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bTNEaSFxayZLHLwswXEBnJjrBe5lguIzailvL55bNeM%3D&reserved=0>,

Can you please indicate which document you're referring to?

Thanks,

Kesem

-

**Comment by KesemSharabi** [comment]
Hi @Michael-Morrissey,

Thanks for confirming the document you're referring to. I'm looking into this issue and will update you when I get an answer.

Kesem

**Comment by davidiseminger** [comment]
Hello @Michael-Morrissey, that third column refers to the Power BI service, and whether that data connector can be connected from the Power BI service and refreshed from there as well. A report that works on Power BI Desktop can indeed be published to the service using that connector. If you need to use a gateway to access the data for that connector, it's not supported. 

If you need further help, please consult https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
