### ISSUE TITLE
Are Dashborads available in Power BI service only?

### ISSUE THREAD

**Issue by Nata-y** [MicrosoftDocs/powerbi-docs#3695]
The tutorial https://docs.microsoft.com/en-us/power-bi/create-reports/ contains phrase: "Dashboards are a feature of the **Power BI service** only. They're not available in **Power BI Desktop**".  
Is it correct? Because I have just created a dashboard, using **Power BI Desktop**...
This is very confusing for me. I would like to know if I understand all things correctly. Please, help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [Intro to dashboards for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboards)
* Content Source: [powerbi-docs/create-reports/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @Nata-y - yes, the article is correct as written. A *dashboard* is a specific content type in Power BI. 
It's sort of a semantic issue though. You can create a page in a report that acts as a dashboard. 
if you download one of the built-in samples (see https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets#install-built-in-samples), you see you end up with a dashboard, a report, and a dataset:
![image](https://user-images.githubusercontent.com/12401230/159804859-9d119ed5-4bb0-43b8-8080-19b3d74ec6da.png)
Hope that helps!
