### ISSUE TITLE
MS customer asking for support on Emissions Dashboard 

### ISSUE THREAD

**Issue by tessdcotton** [MicrosoftDocs/powerbi-docs#3696]
Got help - please close this

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tessdcotton. This issue has been assigned to the doc author for review.

**Comment by tessdcotton** [comment]
Thank you - I have found what I needed.

Terry Cotton

**Comment by paulinbar** [comment]
Closing as per customer request.
