### ISSUE TITLE
PBI Dataflows multi geo support differences in documentation

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#3697]
According to this documentation it states that Dataflows workspaces can be configured for multi geo support and ability to place storage accounts outside of the region the tenant is located in https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions#multi-geo-support

But if you look at the actual configuration documentation for ADLS as well as try this in the service you can only see storage accounts that are available in the default tenant https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#prerequisites

_- The storage account must be created in the same Azure Active Directory tenant as the Power BI tenant._

Could someone please update the content in the first document URL to correct this because it causes confusion.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d2d59d-b88b-17ac-a267-dba67a8fabde
* Version Independent ID: 657c22e2-56e9-468d-11bc-24622777adba
* Content: [Develop solutions with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions#multi-geo-support)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks!
