### ISSUE TITLE
Graph Security API deprecated

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#3702]
[May 2021 release update](https://powerquery.microsoft.com/en-us/blog/power-query-updates-in-power-bi-desktop-may-2021-release/) announced "This update will remove the connector from the “Get Data” experience in Power BI Desktop".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rootsmusic. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks!

**Comment by rootsmusic** [comment]
@davidiseminger  "[Microsoft Graph Security](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources#data-sources-m-o)" hasn't be noted as deprecated.
