### ISSUE TITLE
PowerPlatform.Dataflows vs PowerBI.Dataflows

### ISSUE THREAD

**Issue by bslattz** [MicrosoftDocs/powerbi-docs#3703]
[Enter feedback here]
Query folding works in datasets for `PowerPlatform.Dataflows`, connector so it is preferred in that context.  In dataflows however, when accessing another dataflow in the same workspace, `PowerPlatform.Dataflows` do not support linked entities properly.  The `PowerBI.Dataflows` connector needs to be used in this case in order to support automatic orchestration.  I suggest it would be worth clarifying that [here](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions#understand-linked-tables).  Especially since the default connector in the dataflow editor is `PowerPlatform.Dataflows`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d2d59d-b88b-17ac-a267-dba67a8fabde
* Version Independent ID: 657c22e2-56e9-468d-11bc-24622777adba
* Content: [Develop solutions with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-develop-solutions.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bslattz. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your input / suggestion!
