### ISSUE TITLE
Add info on deletion of upgraded Ws and impact on O365

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3705]
Hi,

I would like to suggest a change in the Consideration and Limitation section - 4th bullet point
https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-upgrade-workspaces?msclkid=d9ad9d54b01b11ec8c5b288952471257#upgrade-considerations-and-limitations)

From: 
The Microsoft 365 group for your classic workspace isn't affected by the workspace upgrade in Power BI. Any Teams, SharePoint sites, mailboxes, or other resources managed by Microsoft 365 aren't changed. They remain intact after you upgrade your Power BI workspace. The Microsoft 365 group continues to exist as before.

To:
The Microsoft 365 group for your classic workspace isn't affected by the workspace upgrade in Power BI. Any Teams, SharePoint sites, mailboxes, or other resources managed by Microsoft 365 aren't changed. They remain intact after you upgrade your Power BI workspace. The Microsoft 365 group continues to exist as before.
**Upgraded workspace can be deleted if needed. Once upgraded, it's not directly associated with an underlying O365 group.**

Thank you. Martina
(confirmed by Keith S.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3645c7a6-ea10-3dc5-2120-aa17355278ec
* Version Independent ID: 2d13d46d-1eaf-b767-cc88-5663c9191ee1
* Content: [Upgrade classic workspaces to the new workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-upgrade-workspaces?msclkid=d9ad9d54b01b11ec8c5b288952471257#upgrade-considerations-and-limitations)
* Content Source: [powerbi-docs/collaborate-share/service-upgrade-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-upgrade-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @MartinaPoddana,

I moved this discussion to an email thread.

Thanks,

Kesem
