### ISSUE TITLE
Dashboard Refresh - need add one more limitation

### ISSUE THREAD

**Issue by KerryWang94** [MicrosoftDocs/powerbi-docs#3707]
In scenario of Dashboard having tile against AS Server where the specific model in AS is using Direct Query Model, the dashboard won't be able to trigger auto refresh, This is because Power BI Read Data_modified coulmn from AS DBschema_Catalogs using Adom function to determine whether dashboard refresh need to be triggered .

However that particular column only updated when the date that the catalog was last modified. This make sense of import mode because Import AS Model refresh would trigger a reprocess then Catalog would update, however for a Direct Query AS Model it does not required any model process to get refresh triggered, instead AS Model would directly trigger query to data source whenever required (It's same like Direct Query scenario in Power BI where metadata does not change)
[Please Refer to ICM:https://portal.microsofticm.com/imp/v3/incidents/details/297208391/home

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KerryWang94. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @KerryWang94,

I didn't understand your question - can you please explain what you're after?

Thanks,

Kesem
