### ISSUE TITLE
Categories are assigned to subcategories?

### ISSUE THREAD

**Issue by terenceltl** [MicrosoftDocs/powerbi-docs#3710]
In the section for snowflake schema, it said:

"Categories are assigned to subcategories, and products are in turn assigned to subcategories."

Shouldn't it be "Subcategories are assigned to categories, ..." ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @terenceltl. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
@peter-myers can you please review the customer's suggestion in this GitHub issue?

**Comment by peter-myers** [comment]
Hi @terenceltl - thanks for helping us improve our documentation by raising concern about that sentence. The sentence has since been revised to become more accurate and clear.
