### ISSUE TITLE
Performance Delta Correct formula

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3711]
Hi,

Is it possible to have details on the calculation of the Performance Delta ?

The doc says "For example, 20 suggests that there's a 20% improvement today, compared with the same metric taken a week ago." 

As you can see on the image, CPU diff does not match : there's a difference of 216% between day 1 and and 7 and Performance Delta says -25, how is it calculated ? What is the exact formula ?

Thanks.

Nicolas

![158668796-47358710-899a-41cd-99eb-c1a19b7f7ad5](https://user-images.githubusercontent.com/35227452/161433675-b8c2d342-1941-4851-966e-490b890600cf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstraw. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
@Hi nstraw,

As you can see from the documentation, the word 'suggest' from the line you quoted implies that this is not a straightforward calculation. The *Performance delta* calculation is supposed to be a representation of the change in performance over a seven day period.

Thanks,

Kesem

**Comment by nstraw** [comment]
Hi @KesemSharabi,,

I can understand that it is just a suggestion, but it really feels like having a red light blinking on my car's dashboard without knowing what the problem is exactly and most of all, what I should do about it...

Does it refer to refresh CPU consumption, user query CPU consumption ?
Is -25 a big number ? Is it a percentage ? What is the scale ?

It is used by admin to point out Datasets that should be optimized, but no one knows what exactly should be optimized.

It would just be very nice to have some clarification on this indicator.

Just a thought.

Nicolas

**Comment by KesemSharabi** [comment]
Hi @nstraw,

Thanks for the feedback. I'm working with the product team to update the performance delta explanation. I'll let you know as soon as it's published.

Thanks,

Kesem

**Comment by nstraw** [comment]
Hi Kesem,

thanks for the follow up, very much appreciated.

I'll stay tuned.

Nicolas

Le mer. 27 avr. 2022 à 05:40, Kesem Sharabi ***@***.***> a
écrit :

**Comment by KesemSharabi** [comment]
Hi @nstraw,

I updated the **performance delta** text - see last bullet in [Matrix by artifact and operation](https://docs.microsoft.com/power-bi/enterprise/service-premium-gen2-metrics-app#matrix-by-artifact-and-operation).

Hope this helps,

Kesem

**Comment by nstraw** [comment]
Hi Kesem,

very clear, very detailed, very very insightful !

Thanks for the update, very much appreciated around here :)

Have a great week!

Nicolas



Le lun. 2 mai 2022 à 07:37, Kesem Sharabi ***@***.***> a
écrit :
