### ISSUE TITLE
Wrong Dataflow parameters

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3712]
Hi,

the section #dataflows in this documentation provides information on parameters like Max Memory (%), Container Size, Enhanced Compute Engine that do not appear in the Gen2 capacity admin page.

This section should be removed.

Thanks,
Nicolas

![Screenshot_8](https://user-images.githubusercontent.com/35227452/161433935-c0f022a9-ea25-4400-83f9-40d52fc3bfb1.png)

![159720071-d000028e-3855-4405-b68b-eb72dd2a25cd](https://user-images.githubusercontent.com/35227452/161433946-d1427a4a-9f9a-4007-86cd-035d24d7cc15.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstraw. This issue has been assigned to the doc author for review.
