### ISSUE TITLE
Prerequisite are not clear

### ISSUE THREAD

**Issue by zincob** [MicrosoftDocs/powerbi-docs#3713]
[[Enter feedback here]](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#prerequisites) here is it mentioned: "An admin role with read/write permissions on your Azure tenant."

Is it possible to mention some roles? Admin role is very generic 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by paulinbar** [comment]
Hi @zincob, I am going to close this issue for now. Please feel free to reopen if you feel further clarification is necessary.
@gabsklad, did you or are you planning to add those examples to the doc? Thanks!
