### ISSUE TITLE
Power BI Adoption Framework vs Roadmap 

### ISSUE THREAD

**Issue by waltheed** [MicrosoftDocs/powerbi-docs#3714]
What are the main differences between the Power BI Adoption Framework vs the Power BI Adoption Roadmap?
Are they the same? Do the pptx files and you tube videos from the framework also apply to the roadmap?

Many thanks for explaining, 

Edgar Walther

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5495a85a-be45-63a4-2dd8-6859f55e4737
* Version Independent ID: 28ac0047-394b-670b-350a-8d8171b02b34
* Content: [Power BI adoption roadmap - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-overview)
* Content Source: [powerbi-docs/guidance/powerbi-adoption-roadmap-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-adoption-roadmap-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @waltheed. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @waltheed - thanks for your question. There are three different sets of Power BI guidance content that are in a state of development. For a good description of them, see this article: https://docs.microsoft.com/power-bi/guidance/powerbi-implementation-planning-introduction
