### ISSUE TITLE
Sample landing page code may have error

### ISSUE THREAD

**Issue by dogbite1337** [MicrosoftDocs/powerbi-docs#3715]
I believe that there is an error in the sample code provided in the **Example of a visual with a landing page** section of this page. The first line of the HandleLandingPage function is as follows.

`if(!options.dataViews || !options.dataViews.length) { ...`

This didn't work for me as the options.dataView.length column is always > 0, even without any columns added (at least in my custom visual). The following code solved this, though.

`if(!options.dataViews || !options.dataViews[0].metadata.columns.length) { ...`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1bed41-e6a8-a311-102e-079f5a88bb64
* Version Independent ID: 1bcf7398-818f-f65d-805f-8f43bec961d0
* Content: [Add a landing page to your Power BI visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/landing-page#creating-a-landing-page)
* Content Source: [powerbi-docs/developer/visuals/landing-page.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/landing-page.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @dogbite1337. I’ll look into this and get back to you as soon as I can.

**Comment by mberdugo** [comment]
Thanks again, @dogbite1337. I updated the code and it should be live in a day or so.
