### ISSUE TITLE
incorrect reference to another section of the paper??

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#3716]
In the Dataflows architecture section we have the following sentence:

> 
When data is transferred from the gateway to the cloud service, it is encrypted. See the [Data in Processing](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security#data-in-processing) section above.
> 

should we not be pointing to the [data in transit](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security#data-in-transit) section instead?  The data in processing section does not talk to data transfer between gateway and cloud service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security white paper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rosscouldrey. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rosscouldrey, sorry for the VERY delayed response. Fixed as per your suggestion. Should be online a day or so. Thanks!
