### ISSUE TITLE
This feature is available to Per User Premium users

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/powerbi-docs#3717]
Hello team, Is my understanding correct that PPU users should have ALL features related to Azure ML Service available ?
If so can we add PPU licensed users to this paragraph:

[Use Machine Learning and Cognitive Services with dataflows – Power BI | Microsoft Docs](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-machine-learning-integration#automated-machine-learning-in-power-bi)
Automated machine learning is available for dataflows that are hosted on Power BI Premium and Embedded capacities only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 301c08b2-df76-b3b0-5035-7413d8b9d447
* Version Independent ID: f6d974e6-d13a-0413-6d50-3b5a93447600
* Content: [Use Machine Learning and Cognitive Services with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-machine-learning-integration#automated-machine-learning-in-power-bi)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @morcinim. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment - Premium includes PPU, so it's implied.
