### ISSUE TITLE
Update request | Scatter chart can use trend line without time data

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3718]
Hi Authors,

We've confirmed that the Scatter chart can use trend line with any numeric x-axis (mean without time data)
Could you please check and update this?

![image](https://user-images.githubusercontent.com/73410575/161648588-e1bcb716-646b-4976-a007-4929602572d2.png)

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbbf6763-4952-5335-cefb-ae4e85fd9028
* Version Independent ID: cb734eb1-fb6d-b7aa-735a-17b5ba8ca7fd
* Content: [Use the Analytics pane in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-analytics-pane#search-within-the-analytics-pane)
* Content Source: [powerbi-docs/transform-model/desktop-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-analytics-pane.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your suggestion!
