### ISSUE TITLE
Power BI data retention policy link missing

### ISSUE THREAD

**Issue by anna907** [MicrosoftDocs/powerbi-docs#3720]
The following text in the document - data retention policy is mentioned with a link to Power BI Service Agreement. The linked document does not contain any information on the data retention policy. 
Would you be able to check this and provide another link - the data retention policy link for Power BI is valuable for the doc content. 

"Also, as it states in the data retention policy in the [Power BI Service Agreement](https://azure.microsoft.com/support/legal/subscription-agreement/), Power BI deletes any customer data you uploaded or created."

Best regards,
Anna
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c12dd3d7-8816-3a42-a21d-2c0600a83b44
* Version Independent ID: 2f443100-7d3c-0766-c0fd-2979cdc41fe4
* Content: [Close your Power BI account - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-closing-your-account)
* Content Source: [powerbi-docs/enterprise/service-admin-closing-your-account.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-closing-your-account.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anna907. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @anna907, sorry for the long delayed response. I am following up on this and hope to clarify the issue soon. I've created a work item for this and so will close this issue in the meantime. Thanks for your feedback!
