### ISSUE TITLE
There is no mention I can see of a catastrophic limitation with using shared datasets. If you have contributor or admin permissions on a customer's tenant it is impossible to publish directly. Further, if a dataset you have access to in the portal is in a customer's tenant it is impossible to connect to it to develop PowerBI reports in the desktop version. I'd say that'a a pretty good reason for NOT using shared datasets when you are a developer team working for a customer

### ISSUE THREAD

**Issue by napbarnes** [MicrosoftDocs/powerbi-docs#3721]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-gb/power-bi/connect-data/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
