### ISSUE TITLE
link for odac versions

### ISSUE THREAD

**Issue by ivilasboas** [MicrosoftDocs/powerbi-docs#3722]
[customers are requesting to have the link for odac versions download updated because that link is only showing older versions for odac. this new link seems to have all recent ones: https://www.oracle.com/database/technologies/dotnet-odacdeploy-downloads.html]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dda0898-54fe-a25f-f61f-2cbbb11487f4
* Version Independent ID: eea60958-c724-8774-26bc-e212fda7ae3b
* Content: [Manage your data source - Oracle - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-manage-oracle?source=docs)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem-manage-oracle.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-onprem-manage-oracle.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ivilasboas. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
The link has been updated in a previous update to the article.
