### ISSUE TITLE
Need more detail about the Performance Delta Calculation

### ISSUE THREAD

**Issue by mathiasekz** [MicrosoftDocs/powerbi-docs#3723]
[Within the Power BI Premium Metrics App, the Performance delta column which indicates the performance evolution per artifact between the last 7 and the 7 previous one is interesting but the documentation does not contain any explanation about the calculation formula (is it based on CPU ? query duration ? number of queries/users ? combination ?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app#matrix-by-artifact-and-operation)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @mathiasekz,

Thank you for identifying this gap. I'm currently working with the product team to improve the performance delta explanation. I'll let you know as soon as the revamped explanation is published.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @mathiasekz,

I updated the **performance delta** text - see last bullet in [Matrix by artifact and operation](https://docs.microsoft.com/power-bi/enterprise/service-premium-gen2-metrics-app#matrix-by-artifact-and-operation).

Hope this helps,

Kesem

**Comment by mathiasekz** [comment]
Hi Kesem,
Thank you for this documentation update, that is great !
