### ISSUE TITLE
Sentence out of place

### ISSUE THREAD

**Issue by Cornan** [MicrosoftDocs/powerbi-docs#3724]
Immediately above the "Reports" section is this sentence:

On to the next building block -- visualizations

"visualizations" is NOT the next section, "Reports" is the next section in the document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [The Power BI service - basic concepts for beginners - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @Cornan ,
Great catch!  Thank you.  The doc has been updated and set to republish.
