### ISSUE TITLE
Wipe out timing for transition to Gen2

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3725]
Hi,

Just under the title in the Important box, there is timing March. 
![image](https://user-images.githubusercontent.com/98977972/162196713-23ca6902-a5b6-44ca-9a37-d16b3cb6bc40.png)

Discussed with Roy R that timing is being finalized. 
I would like to say something like 
"Microsoft will transition all Premium (original version) capacities to modern Premium Gen2 platform. Admins will be notified 60d in advance prior to the auto-migration"

It would be great to update also this document  [https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-transition-gen1-to-gen2](url)

Thanks. Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Version Independent ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Content: [Power BI Premium features. - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-features)
* Content Source: [powerbi-docs/enterprise/service-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-features.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @MartinaPoddana,

Thank you for your comment - good call!

I amended the note in [Power BI Premium features](https://docs.microsoft.com/power-bi/enterprise/service-premium-features) to look like this:

![image](https://user-images.githubusercontent.com/54834915/162750487-6b9289b0-3fba-4e1c-80e4-e33bb150b049.png)

This note is now aligned with the third paragraph in [Plan your transition to Power BI Premium Gen2](https://docs.microsoft.com/power-bi/enterprise/service-premium-transition-gen1-to-gen2):

![image](https://user-images.githubusercontent.com/54834915/162750387-7c49a040-d52b-47f6-97f9-4ff10bd03b8d.png)

Hope this helps and thanks for letting us know.

Kesem
