### ISSUE TITLE
Customized tooltips not available for Table or Matrix visuals

### ISSUE THREAD

**Issue by filipalai** [MicrosoftDocs/powerbi-docs#3726]
In the section Customize Tooltips (or similar), the below text is found:
_To create a customized tooltip, in the Fields well of the Visualizations pane, drag a field into the Tooltips bucket, shown in the following image. In the following image, three fields have been placed into the Tooltips bucket_.

It does not mention anything that the visual cannot be a Table or Matrix for this to work. The Tooltips bucket is missing from these visualizations' Fields well. Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfbc531-11a6-2543-6c99-d38128af21e4
* Version Independent ID: d7dd98cd-d0f9-5738-677d-41fd64804f16
* Content: [Customizing tooltips in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-custom-tooltips)
* Content Source: [powerbi-docs/create-reports/desktop-custom-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-custom-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @filipalai. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks!
