### ISSUE TITLE
workspace id moved

### ISSUE THREAD

**Issue by mobicycle** [MicrosoftDocs/powerbi-docs#3728]
[Enter feedback here]

My workspace id says "me". 

I found an id in Settings - Admin Portal - Workspaces - Select Workspace - Details
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core#step-5---get-the-embedding-parameter-values)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mobicycle. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi. @mobicycle, I'm glad you figured this out. I'll look into this to see if it's something I need to add to the docs.

**Comment by mberdugo** [comment]
Hi @mobicycle, I updated the doc to include this as an alternative method of finding the workspace ID. Thanks for pointing it out.
