### ISSUE TITLE
"Export" settings have changed, doc needs updating

### ISSUE THREAD

**Issue by npherson** [MicrosoftDocs/powerbi-docs#3729]
There is no longer an "Export data" section like the documentation shows - it has been split out into multiple new settings like "Export to .CSV", "Export to Excel"
]https://docs.microsoft.com/en-us/power-bi/guidance/admin-tenant-settings#export-data)

![image](https://user-images.githubusercontent.com/22797301/162290627-591762ec-21d7-4451-97c9-054b0808210f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85be11e7-5a03-a1b1-605a-d49b4215a8aa
* Version Independent ID: 0877169a-673f-1fe9-45b4-dec6b9e9fe26
* Content: [Tenant settings guidance - Power BI](https://review.docs.microsoft.com/en-us/power-bi/guidance/admin-tenant-settings)
* Content Source: [powerbi-docs/guidance/admin-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/admin-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @npherson, thanks for providing the feedback. Yes, the export settings are not much more granular, and we haven't managed to update all the documentation. Moving up that priority. Thanks for taking the time to reach out!

**Comment by npherson** [comment]
Glad to help! If I felt like more of an expert, I would have just submitted a pull request with the changes...  Power BI is at the edge of my wheelhouse!

**Comment by paulinbar** [comment]
Hi @npherson, ok, as a result of your feedback that guidance page has been retired and you now get redirected to the high-level tenant settings page which has a hyperlinked list to the various sections. That said, I think there are still a lot of settings that are either missing or that don't have any useful documentation. The situation as just gotten more complicated now that Microsoft Fabric is out. We are working to come up with a better way of dealing with all these settings, which seem to pop up like mushrooms after a rain storm. So stay tuned.... ;)  Anyway, in the meantime I will close this issue for now. Thanks again for your input!
