### ISSUE TITLE
Alternative language samples

### ISSUE THREAD

**Issue by stinethebean** [MicrosoftDocs/powerbi-docs#3730]
Hey team,  I'm a PM in Microsoft Philanthropies. We're looking for sample PowerBIs in Spanish, German, French, Arabic, and Japanese. Do we have those available? If so, can we link them on the site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets?source=docs)
* Content Source: [powerbi-docs/create-reports/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stinethebean. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @stinethebean,

I started an email thread for your request.

Thanks,

Kesem
