### ISSUE TITLE
Not able to add map type

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#3731]
I have followed the instructions below, but the option "Add a map type" is greyed out.
![image](https://user-images.githubusercontent.com/76531789/162330079-9b1e015d-b44d-4550-9124-0ee5c8fc111b.png)

_To use a TopoJSON map file, add a Shape map visual to your report and add some data to the Location and Color saturation buckets. Then, in the Format section, expand Shape, and select + Add map.

Open Formatting pane and select Add Map._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by djurecic0** [comment]
Seems like you need to change the Map Type to "Custom Map" first.

![image](https://user-images.githubusercontent.com/76531789/162330280-09bb1007-72d3-4821-8f90-a136e4227302.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi, 
Thank you for your suggestion @djurecic0 and for your solution @djurecic0!  We've made the update and set the article to republish. 
All the best,
The DOCS team

**Comment by RobertoEricMarquesCarimo** [comment]
first of all, you have to enter values in '**Location**' and '**Color Saturation**' after that in **Map Setting** under **Map Type** you have to select **Custom Map** and the **Add map type** option will enable.
