### ISSUE TITLE
Screenshot still shows "(Preview)"

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#3735]
Is it possible to get the screenshot updated to no longer show the "(Preview)"? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 813551b0-a4ad-51a1-1d1d-f95815fed880
* Version Independent ID: 813551b0-a4ad-51a1-1d1d-f95815fed880
* Content: [Sensitivity label change enforcement - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-security-sensitivity-label-change-enforcement)
* Content Source: [powerbi-docs/enterprise/service-security-sensitivity-label-change-enforcement.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-sensitivity-label-change-enforcement.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @denglishbi, thanks for pointing that out, and sorry for the long delayed reply. Made the change and it should be published within 24 hours. Thanks again!
