### ISSUE TITLE
Auto Refresh visuals

### ISSUE THREAD

**Issue by jmarindi** [MicrosoftDocs/powerbi-docs#3736]
Kindly use the latest Microsoft power BI version to update the tutorials. They dont make sense anymore with the new versions of power BI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fedb7099-554f-0eed-eaa6-fc13851eb3b1
* Version Independent ID: 8beddbbe-5ebc-60e4-ab28-fd130283a8c1
* Content: [Automatic page refresh in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh)
* Content Source: [powerbi-docs/create-reports/desktop-automatic-page-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-automatic-page-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jmarindi. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Will do, thanks!
