### ISSUE TITLE
VNet public preview?

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#3737]
The document says that VNet will be in public preview soon. To my understanding VNet already is in public preview and GA is planned for September 2022. Should this be adjusted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security white paper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security#data-at-rest)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmuenster. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @gmuenster, checking for confirmation. Will update the doc once I've got it. Thanks!
