### ISSUE TITLE
Power BI change log

### ISSUE THREAD

**Issue by stevenoig** [MicrosoftDocs/powerbi-docs#3739]
Why is the "What's new in Power BI?" web page not updated when new versions are released?  Only the first monthly update is listed, not subsequent updates.  Example: v2.103.881.0 has been released, but the "What's new in Power BI?" doesn't show the changes in that version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI update - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stevenoig. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article, thanks!
