### ISSUE TITLE
Do the new preview workspaces create anything in the SharePoint namespace?

### ISSUE THREAD

**Issue by rvs222** [MicrosoftDocs/powerbi-docs#374]
If we create new (preview) workspace, does it create or reserve anything in the SharePoint namespace, i.e., anything under O365TenantName.sharepoint.com/sites/... ? E.g., if we create a new standalone workspace named "WSName", will that prevent us from later creating an unrelated SharePoint site collection with the same name? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by jordanmills** [comment]
No, they don't.

**Comment by maggiesMSFT** [comment]
Agreed, thanks @jordanmills. And thanks, @rvs222, for asking!
