### ISSUE TITLE
Article Addition- Resolve issues related to creating and rendering visuals while connecting to Power BI dataset with live connection

### ISSUE THREAD

**Issue by akangsha121** [MicrosoftDocs/powerbi-docs#3740]
[When you attempt to create a new connection or connect to Power BI dataset, you may experience Power BI Desktop stall and timing out, there is no error message displayed on the visuals and the wheel keeps spinning indicating that it is busy and never loads.
Check if your machine has a security product (e.g. Digital Guardian) installed and running on your machine. In some cases security product such as Digital Guardian tend to interfere with outgoing network calls thus, in such cases try disabling the security product and check to see if the Power BI report works and renders properly.]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 533d0cd5-b457-863c-f862-49fac672332c
* Version Independent ID: f5df6cb3-049a-eff0-4d7b-3c3843927a5e
* Content: [Resolve issues when starting Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-error-launching-desktop)
* Content Source: [powerbi-docs/connect-data/desktop-error-launching-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-error-launching-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @akangsha121. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks, I've updated this in the docs.
