### ISSUE TITLE
Service interruption - is Autoscale with Power BI Premium online or offline operation? 

### ISSUE THREAD

**Issue by Robert-Kostecki** [MicrosoftDocs/powerbi-docs#3741]
The article does not prescribe if the Power BI Service goes down during the autoscaling (i.e. offline operation) or whether it stays online (no service interruption). Could you please clarify?

Many thanks,
Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 045fc571-5d81-0179-a69b-58a43d5b8ab6
* Version Independent ID: 045fc571-5d81-0179-a69b-58a43d5b8ab6
* Content: [Using Autoscale with Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-auto-scale)
* Content Source: [powerbi-docs/enterprise/service-premium-auto-scale.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-auto-scale.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @Robert-Kostecki,

Good question, I'll look into it and get back to you shortly.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @Robert-Kostecki,

As autoscale runs on our servers, it will run regardless of your online/offline experience. Autoscale kicks in if it is enabled, and your capacity is overused (runs out of CPU).

Does that answer your question?

Thanks,

Kesem

**Comment by Robert-Kostecki** [comment]
Hi @KesemSharabi, I think you might be answering a different question. The question that requires clarifying was: "Is Power BI autoscale offline or online operation?"  Specifically "will there be any service interruption during PBI autoscale", e.g.: 

1. Already running reports failing or being cancelled during autoscale and/or  
2. New report requests refused during the autoscale

Can you please clarify?

Thanks,
Rob

**Comment by KesemSharabi** [comment]
Hi @Robert-Kostecki,

Power BI doesn't fail reports. Regardless of whether autoscale is turned on or off, reports will run to completion. This is true even in a scenario that involves turning autoscale on or off during a report's execution.

What I don't understand is your online/offline reference. As far as I know the concept of online/offline operations doesn't exist in Power BI. Perhaps you're referring to [interactive and background operations](https://docs.microsoft.com/power-bi/enterprise/service-premium-interactive-background-operations)?

Thanks,

Kesem

**Comment by Robert-Kostecki** [comment]
Perfect - thank you for the confirmation @KesemSharabi ,

The online operation refers to a capability of a component to be able to provide uninterrupted service during the operation. This is a generic concept rather than specific to any technology.
For example, Azure Synapse Dedicated Pool capacity scaling at present requires service interruption and is therefore offline operation. Specifically, all queries are cancelled and for a (short) period of time the service becomes unavailable during this operation. 
Azure Synapse Spark Pool on the other hand can scale up or down without service/queries interruption. 
As I mentioned the concept is generic so for example you would have online/offline database index rebuild. 

From architectural perspective the question often arises: Can I (auto-)scale my system to serve increased business demand and if so, will there be a service interruption? Simply speaking is this online or offline operation. 

Again thank you for the clarification – have a great day!

Many thanks,
Rob
