### ISSUE TITLE
Clunky sample data from Microsoft

### ISSUE THREAD

**Issue by braddarwin** [MicrosoftDocs/powerbi-docs#3742]
[Enter feedback here]
1) First you download a zip file from Microsoft site (instead of linking to individual excel files).  Not terrible but not as easy as simply selecting an individual excel I want and pulling just that file.  This wouldn't be as bad if the actual excel files worked (see comment below).

2) Excel files require extra stuff to even get them to work and I was still unsuccessful.  When you open the files they require a pivot add-on for excel.  Ok, with that enabled I tried reloading the content and received a silverlight install prompt which the site says that silverlight was sunset in October 2021?  This is such a confusing, clunky process to download a simple sample data file for learning PowerBI.  Please improve this or make it easier, maybe less add-on required content in the excel files (after all these are simply going to be pulled into the PowerBI tool for further use).

This is the link for the Excel Zip file located on this powerBI sample page - https://go.microsoft.com/fwlink/?LinkId=535020

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-datasets)
* Content Source: [powerbi-docs/create-reports/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @braddarwin. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @braddarwin,

I'm sorry that you had a bad experience with our excel samples. I'm looking onto ways we can improve this experience and will get back to you shortly.

Thanks,

Kesem

**Comment by braddarwin** [comment]
Great thank you

**Comment by maggiesMSFT** [comment]
Hey, @braddarwin -- I own these, and I know they're clunky in Excel. I'm going to strip out the Power View sheets so you won't be asked to install Sliverlight, but you will still have to enable Power Pivot, because that's where the data is.

Note though, for your last parenthetical remark, "(after all these are simply going to be pulled into the PowerBI tool for further use)." -- If you're just going to pull them into Power BI Desktop, then just do that with these files as they already are. Don't try opening them in Excel first. They'll work fine as sample data in Power BI Desktop or the Power BI service.

cheers!

**Comment by maggiesMSFT** [comment]
Hi, @braddarwin -- I finally fixed the Excel samples! I deleted the Power View sheets and added an explanation of how to view the data in Power Pivot. I saved the updated versions to GitHub,
https://github.com/microsoft/powerbi-desktop-samples/tree/main/powerbi-service-samples
