### ISSUE TITLE
Permissions Prerequisite for Emissions Dashboard is unclear.

### ISSUE THREAD

**Issue by pebarrer** [MicrosoftDocs/powerbi-docs#3743]
Hi there...

The Perquisites specify "An admin role with read/write permissions on your Azure tenant."   I am assuming someone who has Owner or Contributor level to the subscriptions in the Azure tenant.  Can we scope this read/write admin to an Azure Management Group?  Or...  Are we talking about an EA administrator role?  In the case of an EA Administrator, can they just have Read Access or must they have Write access as well?

Can we have some examples as the language can be interpreted a number of ways.

Thanks!

Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#prerequisites)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @rosode
* Microsoft Alias: **rosode**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pebarrer. This issue has been assigned to the doc author for review.

**Comment by gabsklad** [comment]
The admin must have read or write permissions on an enrollment level (billing account level). Meaning, access to a subset of subscriptions is not sufficient.

**Comment by paulinbar** [comment]
Hi @pebarrer, I am going to close this issue for now. Please reopen if you feel the need for further clarify.
@gabsklad, did you or are you planning to add any clarifications in the doc? Thanks!
