### ISSUE TITLE
Adding a mention of OLS

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#3745]
Hello there. 

One of the Q&A items towards the end currently reads as follows:
Question: Can I use RLS to limit the columns or measures accessible by my users?
Answer: No, if a user has access to a particular row of data, they can see all the columns of data for that row.

It would be nice to see this answer updated to acknowledge object-level security (even though it needs to be managed with a tool other than Power BI Desktop). Not everyone will decide to use OLS, but mentioning it will make the answer more accurate.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sqlchick. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for the suggestion, @sqlchick, and sorry for the delayed response. It's a good idea and I'll add a link to OLS in the question.
