### ISSUE TITLE
Users with PPU subscriptions cannot share content with users who have a Pro or free license? 

### ISSUE THREAD

**Issue by NishantRanjan** [MicrosoftDocs/powerbi-docs#3746]
[Enter feedback here]
Users with PPU subscriptions cannot share content with users who have a Pro or free license?

I am not sure what it means? Somewhere it mentioned user with "free/pro" can be added as a viewer role. Also, the content will be shared as APP.

Now both users (Free & Pro) are getting alert to "go with PPU trail for 60 days to access". What purpose does PPU  if all user has to get PPU license? What purposes of the APP and viewer role?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with free licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @NishantRanjan. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @NishantRanjan ,
Thank you for your question.  What you write is correct.  Content in workspaces that are not hosted in Premium capacity can only be shared with users who have a Pro or Premium Per User license, and content in workspaces hosted in Premium Per User capacity can only be shared with users who also have Premium Per User Licenses. It sounds as if you created an app in a workspace hosted in PPU? If so, only other users with PPU can access that content.  
Hope this answers your question.
