### ISSUE TITLE
Check 'Data Connectivity Mode' When Using Dynamic Query

### ISSUE THREAD

**Issue by PU-101** [MicrosoftDocs/powerbi-docs#3747]
Hi team,
I created a new source with **Blank Query** and followed other steps shown in this page. But the graph wasn't be updated when I reselected the slicer. Finally I figure out that it is because the default value of Data Connectivity Mode is '**Import**', not 'DirectQuery'. Dynamic  m query parameters only take effects when the mode is '**DirectQuery**'. I think it's important for a newcomer to PowerBI that this point could be noted in the document. 
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PU-101. This issue has been assigned to the doc author for review.
