### ISSUE TITLE
Misleading text regarding PPU license features

### ISSUE THREAD

**Issue by chrisgmbishop** [MicrosoftDocs/powerbi-docs#3750]
This line is misleading "With a PPU license, you do not need a separate Power BI Pro license, as all Pro license capabilities are included in PPU" as further down it stipulates that PPU users can't share with Pro users. If there were feature parity (as I have already tested this and with my PPU _add-on_ to a Pro license, it is not sharable to Pro users) PPU Users would be able to share with Pro users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Version Independent ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @chrisgmbishop,

Can you please quote the sentence that talks about PPU users can't share with Pro users?

I'd like to get the full picture before I make changes to the article.

Thanks,

Kesem

**Comment by chrisgmbishop** [comment]
No trouble. It is under the End User Experience heading with this text and table. This has also been true as we have tried with Pro users to access my PPU report and they could only see it after they upgraded to PPU.
![Screen Shot 2022-04-27 at 15 16 53](https://user-images.githubusercontent.com/16527614/165588158-22f0256b-fcbc-4921-8e46-75c57bc58f13.png)

**Comment by KesemSharabi** [comment]
Hi @chrisgmbishop,

Thanks for sharing the table.

The sentence 'With a PPU license, you do not need a separate Power BI Pro license, as all Pro license capabilities are included in PPU' refers to what you can do in Power BI with both licenses, as listed in the table in the [Using Premium Per User (PPU)](https://docs.microsoft.com/power-bi/enterprise/service-premium-per-user-faq#using-premium-per-user--ppu-) section.

The table you're referring to, displays a matrix of what users with different licenses will be able to view. I believe that these are two different things. The first describes which features are included in each license, and the second which content can be shared between licenses.

Does this make sense?

Thanks,

Kesem
