### ISSUE TITLE
Grammar/Meaning unclear

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#3751]
"in workspace" does not make sense to me. Which workspace?

> You may decide you no longer want the report and its associated shared dataset in workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @djurecic0, thanks for your feedback, and apologies for the long delayed response. Your comment caused me to review that article, and there were a number of things that needed updating, so I have done that. Your issue should have been resolved in those changes. The list view of a workspace no longer shows datasets that are in other workspaces, and I have added a note that deleting a report does not delete the underlying dataset. I also updated info relating to copying a report from an app.
Anyway, thanks again for reaching out and causing this update! The updates should be online within 24 hours.
