### ISSUE TITLE
Missing condition for "I can't create a report attachment, full report attachment greyed out"

### ISSUE THREAD

**Issue by justinrr07** [MicrosoftDocs/powerbi-docs#3753]
I believe for this section; a 4th condition is required. Only a report owner can use this feature. Please let me know if I'm wrong but this was the only solution I could find when working with a customer on this issue. All other conditions listed in the documentation were met.

https://docs.microsoft.com/en-us/power-bi/consumer/service-troubleshoot-subscribe#i-can-t-create-a-report-attachment--full-report-attachment-greyed-out

-Justin
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d883f7b-4e04-d4af-7a03-652316f9f7b7
* Version Independent ID: 9d883f7b-4e04-d4af-7a03-652316f9f7b7
* Content: [FAQs about Troubleshoot subscribing to dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/service-troubleshoot-subscribe#i-can-t-create-a-report-attachment--full-report-attachment-greyed-out)
* Content Source: [powerbi-docs/consumer/service-troubleshoot-subscribe.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/service-troubleshoot-subscribe.yml)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @justinrr07. This issue has been assigned to the doc author for review.

**Comment by mfloyd65** [comment]
Just leaving this supporting documentation. Including an attachment is a Premium only feature. https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe?tabs=creator#:~:text=Full%20report%20attachment%20as%20(for,and%20less%20than%2025%20MB.

**Comment by justinrr07** [comment]
That is correct. However, in addition to that, only the owner of the report can use the feature. It is an additional requirement.


Justin Rister
Cloud Solution Architect - Data & AI
***@***.******@***.***>

[Microsoft Logo]

________________________________

**Comment by mfloyd65** [comment]
Correct but can we list it as a Premium only feature on the document (with the additional guidance provided)?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by justinrr07** [comment]
Sounds good.

Thank you,

Justin Rister
Cloud Solution Architect - Data & AI
***@***.******@***.***>
[Microsoft Logo]

**Comment by justinrr07** [comment]
Hi,

Is the documentation going to include the suggestion I made below?

Thank you,

Justin Rister
Cloud Solution Architect - Data & AI
***@***.******@***.***>
[Microsoft Logo]

From: Justin Rister
Sent: Wednesday, April 20, 2022 4:03 PM
To: MicrosoftDocs/powerbi-docs ***@***.***>; MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [MicrosoftDocs/powerbi-docs] Missing condition for "I can't create a report attachment, full report attachment greyed out" (Issue #3753)

Does this mean the documentation is being updated?

Justin Rister
Cloud Solution Architect - Data & AI
***@***.******@***.***>
[Microsoft Logo]

**Comment by mihart** [comment]
Hi @justinrr07,
Thank you for your patience.  I've updated the article and set it to republish.  I do appreciate your input!
The DOCS team
