### ISSUE TITLE
Document Alternate Publishing methods from visual studio or API

### ISSUE THREAD

**Issue by jasonhorner** [MicrosoftDocs/powerbi-docs#3755]
it looks like the documentation provides no indication on publishing paginated reports from visual studio. if this isn't a supported option it should be called out explicitly it would also be nice to show an example or provide a link to the documentation for publishing rdl files via powershell or the API  / CLI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0feb8663-445d-8536-37ae-068672c7a5b9
* Version Independent ID: 4818af9e-c69b-0fbe-a106-0d1d711b9f0d
* Content: [Publish a paginated report to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-save-to-power-bi-service)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-save-to-power-bi-service.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jasonhorner. This issue has been assigned to the doc author for review.

**Comment by jasonhorner** [comment]
Not looking for support on this issue. just want to be sure that if an approach isn't supported ie (VS Studio publishing) it is documented.
