### ISSUE TITLE
Developer settings part confusing

### ISSUE THREAD

**Issue by jopebeni** [MicrosoftDocs/powerbi-docs#3757]
the placement of the paragraph "This setting applies to streaming and PUSH datasets. If disabled, users will not be allowed send data to streaming and PUSH datasets using the API with a resource key." makes it confusing to the readers. Does this statement only apply to the tenant settings: Block ResourceKey Authentication (disabled by default)*

or does this statement apply to all the developer tenant settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85be11e7-5a03-a1b1-605a-d49b4215a8aa
* Version Independent ID: 0877169a-673f-1fe9-45b4-dec6b9e9fe26
* Content: [Tenant settings guidance - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/admin-tenant-settings#developer-settings)
* Content Source: [powerbi-docs/guidance/admin-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/admin-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jopebeni. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @jopebeni. 
That statement only applies to *Block ResourceKey Authentication*.
I updated the page and clarified the issue.
