### ISSUE TITLE
Unable to create a responsive slicer as the option to enable Responsive is disabled(greyed out) under Visualizations pane/Format visual tab/General tab/Properties/Advanced options

### ISSUE THREAD

**Issue by merwynpaulose** [MicrosoftDocs/powerbi-docs#3758]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eed3feb5-5b30-8f94-9a3d-7a9574490d9c
* Version Independent ID: 85862cdb-9e39-2427-22de-430080febee9
* Content: [Create a responsive slicer you can resize in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-slicer-filter-responsive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/power-bi-slicer-filter-responsive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-slicer-filter-responsive.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by merwynpaulose** [comment]
![image](https://user-images.githubusercontent.com/98316542/164404278-16b25504-0fad-4115-b557-e2278481e26e.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @merwynpaulose. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @merwynpaulose. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
