### ISSUE TITLE
Doesn’t mention anything about managing subscriptions for report published through an app

### ISSUE THREAD

**Issue by b77uw771b** [MicrosoftDocs/powerbi-docs#3759]
The document on managing report subscriptions in power BI does not mention anything about how to manage a report subscription created by another user in a published app as opposed to a workspace. We suspect it is not even possible. But this must be listed as a limitation if that is the case.  This ambiguity has caused a lot of confusion in the community. You can reference the post on the Power BI blog comment section to see what I mean. There are also a couple of posts from the last week in the Power BI forum from my fellow confused admins. Please clarify this immediately. It is critical that subscription management  functionality support reports published through apps. After all, that is where the users who need the most help with managing subscriptions reside. My workspace users are already pretty savvy with such things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for Power BI reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe?tabs=admin)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @b77uw771b. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @b77uw771b ,
Thank you for your suggestion.  I've updated the document to reflect the current functionality.  It should go live by tomorrow. Admins do not have access to subscriptions created in apps in My workspace.  
All the best,
Michele
