### ISSUE TITLE
Internal dashboard embedding using EM1 License?

### ISSUE THREAD

**Issue by systamper** [MicrosoftDocs/powerbi-docs#376]
Hi,

I have been told in the past that if I want to embed reports into internally facing resources such as a custom embedding solution in Dynamics 365 or in an internal Sharepoint instance, I will need to use the P1 license, and not the EM1 license. 

I was told EM1 is for external embedding, but internal users that would otherwise consume a Pro license can only be shared a report or dashboard using the P1 licensing.  

Is this still true? Was this ever true, or was I given incorrect information? This article seems to suggest that I can use EM1, even for internal embedding such as within Dynamics 365.

Thanks, Scott

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @systamper 
Thank you for your question.  I've assigned this to the author of the article.  He will contact you shortly.
Take care,
Michele

**Comment by KayUnkroth** [comment]
The EM SKU covers the ability to share Power BI reports within an organization through content embedding. For all the details, see https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq.

**Comment by mgblythe** [comment]
@systamper  - closing this based on Kay's response.
