### ISSUE TITLE
Excel mentioned rather than DAX

### ISSUE THREAD

**Issue by MarkHaggett** [MicrosoftDocs/powerbi-docs#3760]
In the fourth bullet-point of [Implicit and explicit data type conversion in DAX formulas](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-types#implicit-and-explicit-data-type-conversion-in-dax-formulas), it mentions Excel rather than DAX.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-types)
* Content Source: [powerbi-docs/connect-data/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great catch! I've updated the article, thanks!
