### ISSUE TITLE
Connect app to multiple repos through an organization?

### ISSUE THREAD

**Issue by Grantglass** [MicrosoftDocs/powerbi-docs#3762]
The GitHub app is really useful! However, it requires you to enter in a repository in order for it to work. What if I wanted a picture of a whole organization or user? Is there a way to configure the app to do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-github)
* Content Source: [powerbi-docs/connect-data/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-github.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @Grantglass, sorry I missed this somehow so long ago. I have forwarded your question along to the group that developed the app. I'll let you know their response. Thanks for the reminder, and sorry again for such a long delay.

**Comment by wolfyncsu7** [comment]
I'm also curious for my company/ organization's use of GitHub and Power BI.  We are looking to report across a large number of repos to show data for repos that can be logically groups (per product or subset of architecture).  Is there a way to do this (even if it requires some customization)?

**Comment by ragbnr** [comment]
We have the same requirement to build out the dashboard which would have metrics from all repositories under the org, so looking for the solution, https://app.powerbi.com/groups/me/getapps/services/pbi-contentpacks.pbiapps-github app works great with one repo but need to be expanded for multiple repos under the org / owner

**Comment by Grantglass** [comment]
@paulinbar any update on this?

**Comment by paulinbar** [comment]
Hi @Grantglass and @ragbnr, sorry again for the very late response. The answer back from the app developers is that
