### ISSUE TITLE
Are streaming dataflows also affected?

### ISSUE THREAD

**Issue by JeKlSt** [MicrosoftDocs/powerbi-docs#3763]
Are streaming dataflows also affected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383d7653-8bb3-5e12-976d-b7b591aa098b
* Version Independent ID: 383d7653-8bb3-5e12-976d-b7b591aa098b
* Content: [Known issue - Long running, failed or stuck dataflow in Premium Gen2 - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JeKlSt. This issue has been assigned to the doc author for review.

**Comment by jessicammoss** [comment]
Hello @JeKlSt.  No, streaming dataflows are not affected by this issue.  Thank you.

**Comment by jessicammoss** [comment]
Reassigning to @mihart for closure.

**Comment by mihart** [comment]
Hi @JeKlSt , 
Thank you for your question.  Please reach out again if you need additional clarification.
All the best,
The DOCS team
