### ISSUE TITLE
Axes or Axis?

### ISSUE THREAD

**Issue by bobert13581** [MicrosoftDocs/powerbi-docs#3765]
PowerBI itself uses Axis. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3229b52a-44a8-a65a-be24-103fd317b6e8
* Version Independent ID: 45eaf33e-42d4-919e-8031-dbefc04d6685
* Content: [Tips to manage axes in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/report-design-tips-axes)
* Content Source: [powerbi-docs/guidance/report-design-tips-axes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/report-design-tips-axes.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bobert13581. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @bobert13581 - thanks for your feedback. I'm unclear about your message. The plural of axis is axes.
