### ISSUE TITLE
Question: Python visuals Publish To Power bi Service

### ISSUE THREAD

**Issue by levalencia** [MicrosoftDocs/powerbi-docs#3768]
I was able to create a Python Visual with matplotlib and it works on Power BI Desktop.
I had to manually install some python packages in the corresponding directory selected in config: eg: pandas, nltk, matplotlib.  But it works.

However when I publish to Power BI Service I get this error:
 No module named 'nltk'

Is there any way to install our own python modules in Power BI Service? Or is this not supported?
I tried running pip install inside the python script editor but it didnt  work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6b7b4f-9f34-cec1-687c-2f5c708fe99f
* Version Independent ID: e66e6e43-157d-8331-20e2-89d1379c5251
* Content: [Create Power BI visuals using Python in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-python-visuals)
* Content Source: [powerbi-docs/connect-data/desktop-python-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-python-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @levalencia. This issue has been assigned to the doc author for review.

**Comment by otarb** [comment]
hello @levalencia, you can find list of supported Python packages here - [Python packages that are supported in Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-python-packages-support)

You will not be able to install your own Python packages in the service, this is not supported
