### ISSUE TITLE
External sharing setting

### ISSUE THREAD

**Issue by mansohrstrom** [MicrosoftDocs/powerbi-docs#3769]
The setting **External sharing** under **Export and sharing settings** in tenant settings is not clearly documented. There's no help text and it's not available on the documentation page. Trying to figure out combination of settings is really hard. This particular setting adds a lot of confusion since it's not explicitly mentioned anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0f6494-b5e6-421f-135a-b863cea102c4
* Version Independent ID: 6e0f6494-b5e6-421f-135a-b863cea102c4
* Content: [Export and sharing admin settings - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal-export-sharing)
* Content Source: [powerbi-docs/admin/service-admin-portal-export-sharing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-export-sharing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mansohrstrom. This issue has been assigned to the doc author for review.

**Comment by mansohrstrom** [comment]
Thanks! Specifically we're confused with the two settings:

- Invite external users to your organization - Set to Enabled for entire org
- External sharing - Set to Enabled for specific group

In relation to the **Guest Inviter** role. We can invite people to our tenant using AAD New guest. But whenever we try to do it from Power BI we get:

One or more e-mail addresses with the following domains are outside your organization: firstname.lastname@domain.com

We're struggling to understand how to make it work. Does the user inviting **always** have to be in the Guest Inviter role although External identities settings in AAD don't require it?

**Comment by paulinbar** [comment]
Hi @mansohrstrom, Good question. I know B2B is being worked on. Let me see if I can get some clarity.

**Comment by mansohrstrom** [comment]
We never managed to make this work. In the end we figured out it had to do with the AAD setting:

Enable guest self-service sign up via user flows

on https://portal.azure.com/#blade/Microsoft_AAD_IAM/AllowlistPolicyBlade. 

We have this set to No and couldn't make ad-hoc flow work for us.

**Comment by paulinbar** [comment]
Hi Eduard,
Thanks for adding to this thread. I have contacted the feature owner and hope to be able to update the documentation in the next few days. 
@ekoekkoek

**Comment by paulinbar** [comment]
Hi @mansohrstrom and @ekoekkoek,
I heard back from the feature team. It turns out that this switch is an old switch that now has no code behind it and it does nothing, no matter how it's set. It just hasn't been removed because of priorities. I will at least update the documentation with this information.
Thanks for bringing this up, and @mansohrstrom , thanks for your patience!
