### ISSUE TITLE
Azure Power BI Embedded Cmdlets for the NEW workspaces

### ISSUE THREAD

**Issue by dfaa502** [MicrosoftDocs/powerbi-docs#377]
When will Powershell cmdlets be available for the NEW workspaces?   (I can use https://docs.microsoft.com/en-us/powershell/module/azurerm.powerbiembedded for the current workspaces but want the same for the new workspaces).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#known-issues)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @dfaa502 ,
Thank you for your question.  I've assigned this to the author .  She will contact you shortly.
Take care,
Michele

**Comment by maggiesMSFT** [comment]
Hi @dfaa502 -- the Summary of Planned Features doc outlines what's planned for upcoming releases. https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features. 
If you don't find an answer there, try searching in https://ideas.powerbi.com/forums/265200-power-bi to see if anyone else has suggested it and it's already in progress. Barring that, enter a new item in https://ideas.powerbi.com/forums/265200-power-bi!
