### ISSUE TITLE
Dataflow fails and no error is shown in log file

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/powerbi-docs#3770]
see this tweet 
https://twitter.com/AgulloBernat/status/1518220705875255296

Today I checked with the issue team and they told me it's a known issue 
TrackingID#2204240050000307

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bernatagulloesbrina. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @bernatagulloesbrina ,
Thank you for bringing this known issue to my attention.  I've passed along the information to the known issues authors and if they concur that it is a known issue then we will add it to the list/site asap. 
All the best,
Michele
