### ISSUE TITLE
OneDrive refresh is only relevant to service created datasets.

### ISSUE THREAD

**Issue by savoy9** [MicrosoftDocs/powerbi-docs#3771]
This document needs to be updated to make clear that it is only relevant to creating a dataset/report in the service and not when creating reports from power bi desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc35788c-900b-1902-db56-c38ae1fd7bf2
* Version Independent ID: 7f045fe8-3ac6-29ae-10c5-69e7564dcbe5
* Content: [Refresh a dataset created from a .csv file on OneDrive - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-csv-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-csv-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-csv-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Okay - thanks!
