### ISSUE TITLE
Are subscriptions created from a Workspace's app manageable by the Workspace's admin????

### ISSUE THREAD

**Issue by b77uw771b** [MicrosoftDocs/powerbi-docs#3773]
@mibruhje Please clarify if it is possible to manage a workspace's app's subscriptions as an admin of that workspace. It appears to be impossible. Need an ETA on this missing functionality.
https://powerbi.microsoft.com/en-us/blog/managing-power-bi-subscriptions-just-got-easier/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for Power BI reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe?tabs=creator)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by b77uw771b** [comment]
https://powerbi.microsoft.com/en-us/blog/managing-power-bi-subscriptions-just-got-easier/

**Comment by mihart** [comment]
Hi @b77uw771b @paulinbar ,
The article has been updated to include the new Admin management capabilities. Thank you for bringing this to my attention .
