### ISSUE TITLE
Its resort, not resource

### ISSUE THREAD

**Issue by bslattz** [MicrosoftDocs/powerbi-docs#3774]
[Enter feedback here]
Change prose from

As a last _resource_, you can try swapping the workspace out of Premium to Pro and wait a few minutes. Then switch the workspace back to Premium. This solution may help to provide relief, but the issue could reoccur.

To

As a last _resort_, you can try swapping the workspace out of Premium to Pro and wait a few minutes. Then switch the workspace back to Premium. This solution may help to provide relief, but the issue could reoccur.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383d7653-8bb3-5e12-976d-b7b591aa098b
* Version Independent ID: 383d7653-8bb3-5e12-976d-b7b591aa098b
* Content: [Known issue - Long running, failed or stuck dataflow in Premium Gen2 - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-dataflow-on-premium-gen2.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
good catch! Fixed, update will be live tomorrow afternoon April 29 Pacific time
