### ISSUE TITLE
Scaling operation will not cause downtime issue with Embedded Gen2

### ISSUE THREAD

**Issue by FengLing007** [MicrosoftDocs/powerbi-docs#3775]
Hi Team,

As said in this [document](https://docs.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2#autoscaling-in-embedded-gen2), with Embedded Gen2, we can scale Power BI Embedded resource **without experiencing any downtime**. Is that correct? If true, then there is a conflict between the current page with that document.
> **Scaling without downtime** - With Embedded Gen2 you can scale your Power BI Embedded resource without experiencing any downtime.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b375fcd4-8bde-c63a-5e83-9086908e48c2
* Version Independent ID: 16898648-391b-67c0-9638-d38f64a4f86b
* Content: [Scale your Power BI Embedded capacity - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/azure-pbie-scale-capacity)
* Content Source: [powerbi-docs/developer/embedded/azure-pbie-scale-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/azure-pbie-scale-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your question, @FengLing007. I see the contradiction in the documentation. I'll look into it and try to clarify it as soon as I can.

**Comment by mberdugo** [comment]
Hi @FengLing007. 
In Gen1 scaling can involve a short downtime. With Gen2 there is no downtime. The documentation will be updated to clarify that information. Thanks again for pointing this out.
