### ISSUE TITLE
Considerations and limitations - The dataflows feature is not supported on Multi-GEO at this time

### ISSUE THREAD

**Issue by marshal115** [MicrosoftDocs/powerbi-docs#3776]
I've found the following sentence really confusing and please revise it or add asterisk next to it.

Source: 
https://staticsint.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html
**The dataflows feature is not supported on Multi-GEO at this time**

Some customers have been confused by this single line because it's not clearly stated. Please take a look at the following link for what I meant by this.  
https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-develop-solutions#multi-geo-support

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo#considerations-and-limitations)
* Content Source: [powerbi-docs/admin/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marshal115. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @marshal115,

Thank you for pointing this out. I'll do some further checks and correct the document shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @marshal115,

After checking this issue with the product and engineering teams, I can confirm that the documentation is correct.

[Considerations and limitations](https://docs.microsoft.com/power-bi/admin/service-admin-premium-multi-geo#considerations-and-limitations) (7th bullet) states that dataflows aren’t supported on Multi-GEO. That's correct, when using the Power BI managed storage, you do not have multi-geo support.

The second paragraph in [Multi-geo support](https://docs.microsoft.com/power-bi/transform-model/dataflows/dataflows-develop-solutions#multi-geo-support) suggests that you can use the bring-your-own-storage-account (BYOL) feature with dataflows. BYOL allows attaching your own storage account to a workspace (which could be created in any geo region you select), to achieve a multi geo effect.

Hope this helps,

Kesem
