### ISSUE TITLE
Capacity Metric App - Refresh tab & refresh detail

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3778]
Hi 

I would like to add for this section [https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app#refresh] what the Timestamp represents.
- when CPU & Duration is 0 then it is the START of a refresh 
- when the CPU & Duration has a value then it is the END of a refresh

The reason is that CX is comparing this against the Refresh history from Service and is confused about the number of refreshes visible.

I also would like to add that refreshes triggered via API shows in the app as on Demand (this is per observation, rather then knowing :) )

I wanted to add a picture, but not sure how :) 

Thank you.
Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @MartinaPoddana,

I'm starting an internal email for your request.

Thanks,

Kesem
