### ISSUE TITLE
Power BI - Capacity Metrics App How to Share report with other user ?

### ISSUE THREAD

**Issue by nusairi** [MicrosoftDocs/powerbi-docs#378]
Hi,

I have installed this great capacity monitoring app but would like to share reports to other users. 

Can we do this if yes How?

Cheers,
Mir

**Comment by mihart** [comment]
Hi @nusairi 
Thank you for your question.  I've assigned this to the author of the[ Monitor Power BI Premium.](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity)... article.  He will contact you shortly.
Take care,
Michele

**Comment by mgblythe** [comment]
@nusairi -- thanks for your question. It's not possible to share the reports from that app. To use the app, you need to be a capacity admin. If you want to suggest sharing as a capability, please file an idea here: https://ideas.powerbi.com/forums/265200-power-bi. Closing this item, but feel free to reopen if necessary.
