### ISSUE TITLE
Microsoft 365 / Dataverse name updates

### ISSUE THREAD

**Issue by mscottsewell** [MicrosoftDocs/powerbi-docs#3780]
The list of connectors needs an update for the Microsoft 365 and Dataverse connectors:

The line for the "Microsoft 365 (Online)" connector is out of date - That connector has been renamed to "Dynamics 365 Online (legacy)"
![image](https://user-images.githubusercontent.com/6276300/165636992-d8fefb7c-a4d9-4f22-8d23-960314ccdc99.png)

The "Microsoft Dataverse" connector is now named both "Dataverse" and "Dynamics 365 (Dataverse)" - the latter being just an alias of the former.
![image](https://user-images.githubusercontent.com/6276300/165636938-8fe6f4c1-a2d6-4d9f-8f40-a5d261b1cdbd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mscottsewell. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated that article, thanks!
