### ISSUE TITLE
Revise the external document to provide clear understanding of permissions in Power BI to download the .pbix from dataset & report

### ISSUE THREAD

**Issue by akangsha121** [MicrosoftDocs/powerbi-docs#3781]
[The Current Statement under limitations section of download .pbix from a report "You can download a file in either Reading view or Editing view, but you must at minimum have Write access to the report or be a Contributor to the workspace" has to be revised as ["You can download a file in either Reading view or Editing view, you must be a Contributor to the workspace"
Also the current statement under download .pbix from a dataset "To download the .pbix file, you must at minimum have Write access to the dataset or be a Contributor to the workspace." has to be revised as [ "To download the .pbix file, you at least must be a Contributor to the workspace."]

 ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#limitations-downloading-a-pbix-from-a-dataset)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
got it, thanks! change will be live this afternoon April 29 Pacific time
