### ISSUE TITLE
Add a note for the Power BI Web Service privacy level.

### ISSUE THREAD

**Issue by jcbendernh** [MicrosoftDocs/powerbi-docs#3782]
In order for the data sources to return data through the AML model in the web service, all privacy levels for all data sources within the dataset must be set to either Organizational or Public.  When it is set to Private for any data source within the dataset, the AML model does not return any data.

This affects the wording the following paragraph of the document...

Follow the instructions for both azureMLFunctions and Web. Make sure that you select a privacy level. You can now set a Scheduled refresh of the data. Select a Refresh frequency and Time zone. You can also select an email address where Power BI can send refresh failure notifications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfdd02ee-f034-f9c3-7d52-199944ac23bb
* Version Independent ID: 4336a0d9-94d1-a5f7-f0d1-e5d260018b68
* Content: [Tutorial: Consume an Azure Machine Learning model in Power BI - Azure Machine Learning](https://docs.microsoft.com/en-us/power-bi/connect-data/service-aml-integrate)
* Content Source: [powerbi-docs/connect-data/service-aml-integrate.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-aml-integrate.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @samuel100
* Microsoft Alias: **samkemp**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jcbendernh. This issue has been assigned to the doc author for review.
