### ISSUE TITLE
Sparklines - more details pls

### ISSUE THREAD

**Issue by Qbit-joe** [MicrosoftDocs/powerbi-docs#3783]
Would be good to get more details on how to read the actual trendline with examples please i.e. based on various dates or other examples :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a8bf4-617f-844d-bfe4-1b9261ef518d
* Version Independent ID: 563a8bf4-617f-844d-bfe4-1b9261ef518d
* Content: [Create sparklines in a table or matrix in a report (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-sparklines-tables)
* Content Source: [powerbi-docs/create-reports/power-bi-sparklines-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-sparklines-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
@Qbit-joe -- thanks for the suggestion! I'll see what we can do.

**Comment by KesemSharabi** [comment]
Hi @Qbit-joe,

Thank you for your suggestion. At this stage, we're not planning to make changes to this article. We'll consider your suggestion for future updates.

Thanks,

Kesem
