### ISSUE TITLE
Clarity on support for reports created in the Power BI service

### ISSUE THREAD

**Issue by kathleenlgo** [MicrosoftDocs/powerbi-docs#3784]
Hi,

May I clarify the 2 highlighted points below please:
![image](https://user-images.githubusercontent.com/22525477/165881483-6f3a53e1-1661-48e2-9597-31b929cf32b6.png)

My understanding of the 1st highlighted bullet point is --> in general, reports created in the Power BI service can be downloaded.

My understanding of the 2nd highlighted bullet point is --> only reports created in the Power BI service **using the quick create option** can be downloaded.

Is my understanding correct?

I tried on my lab and find that the behavior is aligned with the 1st highlighted bullet point.

Thanks,
Kat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#download-a-report-as-a-pbix-file)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kathleenlgo. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @kathleenlgo,

I believe your assumptions are correct. @maggiesMSFT, is there anything I'm missing?

Thanks,

Kesem

**Comment by maggiesMSFT** [comment]
Hi, @kathleenlgo -- good questions! I've clarified in the Considerations section, https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#limitations-downloading-a-pbix-from-a-report.
CHanges will be live tomorrow May 27 afternoon, Pacific time.
