### ISSUE TITLE
Dynamic M Query after loading dataset from Power BI dataflow

### ISSUE THREAD

**Issue by LuciannaFG** [MicrosoftDocs/powerbi-docs#3785]
Dear Microsoft Team. First, thank you for this useful article. 
I would like to ask if it is possible for you to add more information in this article about using the Dynamic M Query when loading data from other sources. In this article, you presented very clearly how to do it when we are loading data from SQL.database and AzureDataExplore.Contents. I am struggling on adding the dynamic parameters when I load data from a dataflow in this line of code:

**Source = PowerPlatform.Dataflows(null),
Workspaces = Source{[Id="Workspaces"]}[Data]**

I hope it will be possible to explain how can we do that. Thank you for your attention.
Kind regards,
Lucianna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LuciannaFG. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your request, we'll look at doing that.
