### ISSUE TITLE
Please update video

### ISSUE THREAD

**Issue by rcfoyn** [MicrosoftDocs/powerbi-docs#3787]
The video should be updated as it is no longer matching the product GUI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 110f9fbe-8e10-9cfc-ea1e-ea6e6a0b210e
* Version Independent ID: 653f794f-5d32-3034-0d26-8cbf5d42e020
* Content: [Control chart gridlines in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/report-tips-chart-gridlines?source=docs)
* Content Source: [powerbi-docs/guidance/report-tips-chart-gridlines.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/report-tips-chart-gridlines.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rcfoyn. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @rcfoyn - thanks for bringing your concern to our attention. We have reviewed the article and decided to remove it.
