### ISSUE TITLE
Planning a Power BI Enterprise Deployment Whitepaper Outdated

### ISSUE THREAD

**Issue by BKColts88** [MicrosoftDocs/powerbi-docs#3788]
Title says it all. The "Planning a Power BI Enterprise Deployment Whitepaper" link references and outdated version (2018). I found the newest version with a separate search (May 2020)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Version Independent ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BKColts88. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @BKColts88,

Thank you for your comment and for getting involved. I fixed the whitepaper link - now it's linked to the 2020 version.

To get the latest whitepapers, you can visit the [White papers for Power BI](https://docs.microsoft.com/power-bi/guidance/whitepapers) page.

Thanks,

Kesem
