### ISSUE TITLE
Add the word sample to the directions to align with the text of PBI Desktop

### ISSUE THREAD

**Issue by billinkc** [MicrosoftDocs/powerbi-docs#3789]
Under the section "Get the sample in Power BI Desktop" the paragraph concludes with "go ahead and choose **Load data**."

The text in PBI Desktop is **Load sample data**. The documentation should mirror the application text to reduce the opportunity for confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 423bed63-655a-3079-815e-0d9a8c7de44d
* Version Independent ID: ed119c4a-d4f0-7458-fd57-d7247edbd70e
* Content: [Download the Financial Sample Excel workbook for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-financial-download)
* Content Source: [powerbi-docs/create-reports/sample-financial-download.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-financial-download.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @billinkc. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @billinkc,

Thanks for pointing out this error. Following your request, I fixed the wording and it now says **Load sample data**. See [Get the sample in Power BI Desktop](https://docs.microsoft.com/power-bi/create-reports/sample-financial-download#get-the-sample-in-power-bi-desktop).

Thanks,

Kesem
