### ISSUE TITLE
Please clarify licensing requirements

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/powerbi-docs#3790]
The information on licensing requirements is not clear 
"A Power BI Pro or Premium Per User (PPU) license or a [Power BI Premium capacity (EM or P SKU)](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is) with a Power BI license"

We need to clarify "with Power BI license" at the end of the sentence - what type of Power BI license?

I think following is correct:
If report is hosted on Premium capacity P SKU or EM SKU then users with Power BI Free license should be able to view reports
embedded in Sharepoint online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed a report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @morcinim - thanks for your feedback! I've updated the language. Changes will be live tomorrow afternoon May 6 Pacific time.
