### ISSUE TITLE
Missing documentation on supported props for text styles

### ISSUE THREAD

**Issue by phil-lgr** [MicrosoftDocs/powerbi-docs#3791]
In [https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#setting-formatted-text-defaults](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#setting-formatted-text-defaults)

the documentation states that those are the supported properties:

```ts
  largeTitle: {
    fontFace: 'Arial'
    fontSize: 12,
    color: '#000000',
  },
```

![image](https://user-images.githubusercontent.com/9644867/166708939-a82df09a-5dd4-4b54-a96f-bd1edb40313f.png)

But it looks like fontWeight work too here.

```ts
  largeTitle: {
    fontFace: 'Arial'
    fontSize: 12, 
    fontWeight: '700'
    color: '#000000',
  },
```

Could you add all the supported properties (fontWeight, text styles etc) in the documentation please?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#properties-within-each-card)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by phil-lgr** [comment]
There is also nothing specified for line height... can we set the line height directly in this style object?

**Comment by phil-lgr** [comment]
There is also NO document on how to style textBoxe

see https://community.powerbi.com/t5/Desktop/JSON-Theme-Code-for-Text-Box/m-p/437973

**Comment by bishalgoswami** [comment]
Thanks for your comment, @phil-lgr. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @phil-lgr.

In the future we may document all the JSON team properties. Until then I suggest that you look for a solution in the [Power BI Community]( https://community.powerbi.com) or our [support page](https://support.powerbi.com).

Thanks,

Kesem

**Comment by maggiesMSFT** [comment]
Hi, @phil-lgr -- I just wanted to add, I've been working with the engineers to get answers to your questions. It's taking longer than expected...

**Comment by phil-lgr** [comment]
> we may document all the JSON team properties. 

We def need PowerBI's theming feature to be fully documented, IMO, without that, it makes it much harder to create complete themes. Please consider prioritizing this. Thanks.
