### ISSUE TITLE
Section out of date

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#3803]
The description and screenshot in the Datasets in DirectQuery/LiveConnect mode section is not up to date. There is no separation between Scheduled Refresh and Optimize Performance any longer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-data#live-connections-and-directquery-to-on-premises-data-sources)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmuenster. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Okay, we'll get that updated. Thanks!
