### ISSUE TITLE
Need screenshot for connecting power bi report server in power bi report builder to save report

### ISSUE THREAD

**Issue by vhjy123** [MicrosoftDocs/powerbi-docs#3804]
Step 4 state that "On the File menu, select Save as, and save it to the report server.", but there is no guide on how to connect to the power bi report server on power bi report builder. Appreciate if this can be added in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bbba956-a7bf-d125-6db5-07ce9c445a0a
* Version Independent ID: 5703d3a1-cf11-45c3-056c-09774ebbf3b9
* Content: [Create a paginated report for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-create-paginated-report)
* Content Source: [powerbi-docs/report-server/quickstart-create-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/quickstart-create-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vhjy123. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @vhjy123,

I believe that after you save your report using 'save as' you can open it with the report server.

@maggiesMSFT, can you please confirm? Perhaps this isn't clear in [Step 4: Save your report to the report server](https://docs.microsoft.com/power-bi/report-server/quickstart-create-paginated-report#step-4-save-your-report-to-the-report-server) and we need to reword something..?

Thanks,

Kesem

**Comment by maggiesMSFT** [comment]
Hi, @vhjy123 -- guess what? You're right! You can't upload from Power BI Report Builder. But you can still upload your paginated reports. Here's what I added to the article:
You can start in the report server and upload it, or you can start in Microsoft Report Builder, and save it.

However, you can't start in Power BI Report Builder and save it. Use the upload to the report server option instead.
Update will be live later today June 22. 
Thanks for the catch!
