### ISSUE TITLE
PowerBI KPI documentation outdated?

### ISSUE THREAD

**Issue by lukeschwenke** [MicrosoftDocs/powerbi-docs#3805]
Hello, I am trying to implement a KPI on the April 2022 version of PowerBI and the parameters are: Value, Trend Axis, and Trend. This is different from the November 2021 version of PowerBI and the current KPI documentation that shows these as the parameters: Indicator, Trend Axis, and Target Goals. 

Do you have updated documentation that I can reference on how to create a KPI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [Key Performance Indicator (KPI) visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-kpi)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-kpi.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lukeschwenke. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Thanks for your comment, @. This issue has been assigned to the doc owner for review. All articles about visualizations are currently being updated to include new UI changes and new functionality.  You should see the update article on our site later this month.
