### ISSUE TITLE
Threshold setting for % Metric

### ISSUE THREAD

**Issue by Melsize** [MicrosoftDocs/powerbi-docs#3806]
When setting an alert for a metric that is a percentage, you are not able to enter a whole number for the threshold like the documentation shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f64d2d-e9b8-59f1-afc1-8d94e2f3c1bd
* Version Independent ID: 565fdc0b-2462-806c-7c17-d189d2378ba4
* Content: [Tutorial:Set data alerts on the Power BI service dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-alerts)
* Content Source: [powerbi-docs/consumer/end-user-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Melsize. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @Melsize , 
Thank you for catching this mistake.  We've made the update and set the article to republish. 
All the best,
The DOCS team
