### ISSUE TITLE
Tenant migration

### ISSUE THREAD

**Issue by patilpappmodz1** [MicrosoftDocs/powerbi-docs#3807]
[Enter feedback here]
This page suggests that tenant migration (migrate PowerBI reports, datasets, etc) can be accomplished using the backup restore method. Can this page or other content be updated to reflect the procedures? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79d603e3-ad07-3500-f035-188baaa305ce
* Version Independent ID: 79d603e3-ad07-3500-f035-188baaa305ce
* Content: [Backup and restore Power BI Premium datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-backup-restore-dataset?msclkid=3a4d20d6d0ad11ecaeeb62e47271434f)
* Content Source: [powerbi-docs/enterprise/service-premium-backup-restore-dataset.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-backup-restore-dataset.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @patilpappmodz1. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @patilpappmodz1,

I'm assuming you're trying to do the following:
* Backup existing datasets from Tenant A
* And restore the datasets to a capacity on Tenant B

If so, I'm afraid we don't have these steps documented.

Also, note that in the scenario described above, your reports will break and you'll need to re-published/re-bound them to the new dataset IDs.

Hope this helps,

Kesem
