### ISSUE TITLE
Clarification on placement of Service Bus

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#3808]
I have a question to clarify the premium architecture - in our diagram on the whitepaper site [here](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security?msclkid=18184d7cd12411eca0ec3d2f9e697d3c#power-bi-premium-infrastructure) we show the service bus inside the premium cluster which is inside the premium region.

However, on our [Multi Geo page](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo?msclkid=1de24ffcd12511ec90bbbe4dc56a5692#enable-and-configure) for premium we state that the service bus resides in the home region, not in the premium region.

These items remain in the home region for the tenant:

Push datasets
Excel workbooks
Dashboard/report metadata: e.g., tile names, tile queries
**Service buses for gateway queries or scheduled refresh jobs**
Permissions
Dataset credentials
Power BI Embedded Analytics Playground saved state

Is there an exception that is not stated for multi geo?  Which of these documents is correct?  

Thanks!
Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b0a5167-9181-bcb4-091c-9e603d2cf296
* Version Independent ID: a8cbde60-5bb8-875f-3b8c-75dac8a2525f
* Content: [Power BI security white paper - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-security?msclkid=18184d7cd12411eca0ec3d2f9e697d3c)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-powerbi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rosscouldrey. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rosscouldrey, I've passed your comments on to the product team and will update the docs as per their feedback. Closing this issue in the meantime. Thanks for pointing this out!
