### ISSUE TITLE
Which is correct about empty classic workspace?

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3811]
There is description:

"To reduce the impact of maintaining empty classic workspaces that were automatically created, empty classic workspaces are deleted by default as part of the upgrade process. However, admins can prevent deleting empty workspaces by enabling the following setting in the Admin portal."

![image](https://user-images.githubusercontent.com/73410575/168194477-391bdc03-ff1d-4ef2-919d-9080cff9d3f5.png)

but the setting explains that it prevents to block classic workspaces with no content from being upgraded if enabled (so it means delete the empty classic workspaces)

![image](https://user-images.githubusercontent.com/73410575/168194796-761d62fc-9fd7-494c-93b5-21868a7b6a90.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3645c7a6-ea10-3dc5-2120-aa17355278ec
* Version Independent ID: 2d13d46d-1eaf-b767-cc88-5663c9191ee1
* Content: [Upgrade classic workspaces to the new workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-upgrade-workspaces#empty-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-upgrade-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-upgrade-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Hyamyam. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Hyamyam -- you're right! It should read: 
"However, admins can prevent deleting empty workspaces by _disabling_ the following setting in the Admin portal."
I've made the change. Thanks!
