### ISSUE TITLE
incorrect syntax for URL filters in embed pages 

### ISSUE THREAD

**Issue by Castillomarcos** [MicrosoftDocs/powerbi-docs#3813]
The sign changed from “?” to “$” according to embed documentation.
And in the end, that’s not even correct, we actually had to use “&”.

---
<img width="308" alt="Correct sintax for URL filters in embed pages" src="https://user-images.githubusercontent.com/105510152/168332237-b1e53ba3-6e07-47d3-a899-e2f0e8bb9113.PNG">

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-embed-secure)
* Content Source: [powerbi-docs/collaborate-share/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Castillomarcos. This issue has been assigned to the doc author for review.

**Comment by Castillomarcos** [comment]
Hi @KesemSharabi 

Thanks for your comment.
Review the documentation and the error is still found.
The issue is inside "Filter report content using URL filters" section.
At the end of the documentation, it shows the URL with the filter added. Where it still tarts with the "$" sign.

![image](https://user-images.githubusercontent.com/105510152/170550163-7eabbe8d-4bfa-4566-9322-d03d6ddee6ca.png)

Regards,
Marcos Castillo.

**Comment by maggiesMSFT** [comment]
Hi, @castillomarcos -- I'm checking with the devs and will get back to you. Thanks!

**Comment by paulinbar** [comment]
Hi @Castillomarcos, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for the input!
