### ISSUE TITLE
Down arrow does not always appear on slicers

### ISSUE THREAD

**Issue by kellytdunn** [MicrosoftDocs/powerbi-docs#3815]
The page says to "Select the down-arrow in the upper-right corner of the numeric range slicer and a menu appears." This down-arrow does not always appear. Furthermore, sometimes the slicer changes to a different format (drop-down, list, etc) after being set one way. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc558f3-8a74-7154-c048-2dd74ad4eb8a
* Version Independent ID: f84aa1a5-4bab-6f6d-a0ba-5040c0f5defb
* Content: [Use the numeric range slicer in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-slicer-numeric-range?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-slicer-numeric-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-slicer-numeric-range.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kellytdunn** [comment]
Found answer here: https://community.powerbi.com/t5/Desktop/Slicer-drop-down/m-p/98650

**Comment by maggiesMSFT** [comment]
Thanks, @kellytdunn! I'll add that note to the article. Change will be live Mon May 16 afternoon Pacific time.
