### ISSUE TITLE
Update the goal tracking cycle feature does not exist, screenshot is incorrect

### ISSUE THREAD

**Issue by triggerfishmartech** [MicrosoftDocs/powerbi-docs#3816]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ac2aa1-b899-184c-10c3-7909aa32bff8
* Version Independent ID: 17e2b2b8-02c5-fcf0-32ab-7f3ef2eb271f
* Content: [Create scorecards and manual goals (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-create)
* Content Source: [powerbi-docs/create-reports/service-goals-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-create.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @triggerfishmartech. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thank you for your comment, @triggerfishmartech.

@maggiesMSFT can you please take a look at this and update the screenshot if needed?

Thanks,

Kesem

**Comment by maggiesMSFT** [comment]
Hi, @triggerfishmartech -- thanks for your feedback! Screenshot is updated. Change will be live this afternoon May 26 Pacific time.
