### ISSUE TITLE
Instructions Need to be Updated

### ISSUE THREAD

**Issue by SueStankus** [MicrosoftDocs/powerbi-docs#3818]
The instructions for adding a data source to a gateway don't look anything like what I see on Power BI service.  When I log in, I click on the cog and choose Manage Gateways.  In your instructions, you say to choose the new at the top of the ribbon.  However, I just see a list of gateways with no way of choosing one and no new button to select. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Add or remove a gateway data source - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SueStankus. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the article since you submitted this feedback. Thanks.
