### ISSUE TITLE
Instructions to update PowrBI Visuals

### ISSUE THREAD

**Issue by MikeAinOz** [MicrosoftDocs/powerbi-docs#3819]
Hi Hopefully I will have solved my problem by the time you update the doco. What I can't find is how to update an existing Power BI Visual in the marketplace. It would be good to have a page for it with a few pictures. We used to get a package from support but that has changed; we need to know the new procedure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0667ec6-a57d-c9c4-3ced-d33e418ace20
* Version Independent ID: d76851d1-c104-b809-225c-f349e11809a5
* Content: [Publish Power BI visuals to the Microsoft commercial marketplace - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/office-store)
* Content Source: [powerbi-docs/developer/visuals/office-store.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/office-store.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MikeAinOz. This issue has been assigned to the doc author for review.

**Comment by MikeAinOz** [comment]
Hi here are my notes from working out how to do and update, please note the glitch in review and publish:
Updating a Power BI Visual

Step 1: Goto technical configuration and remove existing packages using the remove indicator at the end of each package

Step 2: Drag and drop the updated pbix and pbiviz files to the page

Step 3: Save Draft

Step 4. Update any Properties and the offer listing

Step 4: Add Notes for certification even if it's not certified and include testing notes

Step 5: Review and Publish visual

If this occurs:

There are errors in previously published modules associated with this product. Please correct the following errors, and then include the affected modules for publishing:

We found some errors in the Properties page. Please fix these, then try again. (Errors: 2)

Then: Go to the Properties page and untick and retick any box and the problem will be fixed when you resubmit.

**Comment by mberdugo** [comment]
Thanks for your question, @MikeAinOz. And thanks even more for your answer!
I'll work on incorporating this information into the docs to make it easier in the future.

**Comment by mberdugo** [comment]
Hi @MikeAinOz, thanks again for your help. We moved the information about creating and updating offers to the Zaure Marketplace website. The information about updating is here: https://learn.microsoft.com/en-us/azure/marketplace/update-existing-offer
