### ISSUE TITLE
Prerequisites clarification

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/powerbi-docs#3820]
[Enter feedback here]
I believe the statement in Prerequisite is incorrect: "To publish a Power BI paginated report to the Power BI service, you need a [Power BI Pro](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi) license, or [Premium Per User (PPU)](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq) license, and write access to a workspace in a Power BI Premium capacity."

I believe correct statement would be "To publish a Power BI paginated report to the Power BI service, you need a [Premium Per User (PPU)](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq) license or [Power BI Pro](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi) license and write access to a workspace in a Power BI Premium capacity."

Pro license does not offer paginated reports so you need dedicated Premium capacity with that license
PPU license offers paginated reports with no need for dedicated Premium capacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 009519a7-b9c5-c388-53ce-d0e765fef750
* Version Independent ID: 0566119f-c2fc-3d1c-6eaf-f80910635022
* Content: [Create parameters for paginated reports in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-parameters)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-parameters.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @morcinim. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @morcinim -- I see what you mean, it's not clear. I've updated the Prereqs section to this:

**Prerequisites** 
- To publish a Power BI paginated report to the Power BI service, you need at least a Contributor role in a workspace. Read more about [roles in the new workspaces](../collaborate-share/service-roles-new-workspaces).
- You also need either a [Premium Per User (PPU)](../enterprise/service-premium-per-user-faq.yml) license, or you need a [Power BI Pro](../fundamentals/service-self-service-signup-for-power-bi.md) license and the workspace needs to be in a Power BI Premium capacity.
