### ISSUE TITLE
Trouble with using Power BI Desktop: Cost Management Connector

### ISSUE THREAD

**Issue by erdrick22** [MicrosoftDocs/powerbi-docs#3822]
This page has a broken link:

https://docs.microsoft.com/en-us/microsoft-365/commerce/billing-and-payments/manage-billing-profiles&preserve-view=true

The steps under "Connect to a Microsoft Customer Agreement account" are too ambiguous:
This section describes the steps necessary to connect to a Microsoft Customer Agreement account.

How do I know which to choose between these three?

1.Connect to a billing account
2.Connect to a billing profile
3.Connect to an Enterprise Agreement account

Assuming I try option 3,  I am having trouble following the steps under "Connect to an Enterprise Agreement account".

2. Select your billing account.
I don't see any billing accounts

4. For Choose Scope, select Enrollment Number and paste the billing account ID from the previous step.
Are Enrollment Number and Billing Account ID one and the same?  Again this is confusing.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97d9cf44-77fd-5d70-0d6f-d7cefc1458c6
* Version Independent ID: 62c502c1-1831-c94e-d804-f71cb6a569a3
* Content: [Connect to Azure Cost Management data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management)
* Content Source: [powerbi-docs/connect-data/desktop-connect-azure-cost-management.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-azure-cost-management.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
