### ISSUE TITLE
The article should include link to source repo on Github

### ISSUE THREAD

**Issue by HymieHo** [MicrosoftDocs/powerbi-docs#3824]
The source PBIT for the template app described in the article is available from Github. This article should point to it, here is the link:  https://github.com/microsoft/PowerBI-LogAnalytics-Template-Reports

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9479fdb1-6f65-d80b-30d7-768ff7749a0d
* Version Independent ID: 9479fdb1-6f65-d80b-30d7-768ff7749a0d
* Content: [Using the Log Analytics for Power BI Datasets Template App (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-loganalytics-reportguide-datasets)
* Content Source: [powerbi-docs/transform-model/log-analytics/desktop-loganalytics-reportguide-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/log-analytics/desktop-loganalytics-reportguide-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HymieHo. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Great idea! I added the link, thanks!
