### ISSUE TITLE
Is it possible to "Build" documentation locally?

### ISSUE THREAD

**Issue by cfaagaard** [MicrosoftDocs/powerbi-docs#3826]
How can I "build" the documentation locally to see the change I have made before making a PR?

With for example mkdocs I can write "mkdocs serve" in the terminal (in Visual studio code) and then see website.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cfaagaard. This issue has been assigned to the doc author for review.

**Comment by cfaagaard** [comment]
... and I know that you are using fxdocs (of some sort) and tried the "fxdoc build"/"fxdoc serve", but get a bunch of errors (16 Error(s), 850 Warning(s), 503 Suggestion(s))
Examples:
liquid-not-found ./developer/visuals/develop-circle-card.md(1,1): Liquid template is not found for mime type 'Conceptual', the output HTML will not be generated.

schema-not-found ./developer/index.yml(1,1): Unknown schema 'Hub'.

Is the build process documented somewhere?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @cfaagaard. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

If you think this is a documentation request, please let us know which document you're referring to.

Thanks,

Kesem

**Comment by cfaagaard** [comment]
Thank you for your reply @KesemSharabi.
You are right. This is not a documentation feedback for a specific topic or document.
This is rather a QA question: when I want to PR a change in the documentation I would like to see how the change looks in the "website" rather in just markdown. So I would like to build/serve the website locally (on my pc) before submitting the PR.
So my question is: is it possible to build/serve the website for the markdown in this repo?

**Comment by KesemSharabi** [comment]
Hi @cfaagaard,

After you create a PR, you can  click the **View** button in GitHub. You'll be redirected to a draft of the article you editted.
![image](https://user-images.githubusercontent.com/54834915/171427162-f79640be-b92e-49b9-a587-c4a221fe82cc.png)
Is this what you're after?

Thanks,

Kesem
