### ISSUE TITLE
Deleted dataflow's datasources 

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3828]
Hi,

I would also mention the known issue where the list of datasources displayed for a Dataflow is not accurate as it keeps forever old deleted datasources. Same behavior using API.

https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations

It is said to be a limitation, it feels more like a bug or an issue, a security issue in fact as we're not able to have a clear landscape of what are the actual datasources used by dataflows in the tenant.

Thanks to the doc team!

Nicolas

![image](https://user-images.githubusercontent.com/35227452/169033715-78523265-af30-47f5-b220-577c8098142a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstraw. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @nstraw , 
Thank you for your suggestion.  I'll forward this to the Known Issues team.
All the best,
The DOCS team
