### ISSUE TITLE
instructions are unclear AS ALWAYS

### ISSUE THREAD

**Issue by moatazasd** [MicrosoftDocs/powerbi-docs#3829]
[Enter feedback here]
microsoft instruction have never been clear to me ... from step one you say go to navigation panel and click this and that.. i cant even see the navigation panel .. i googled it and it only showed for web power bi.. i looked in the settings maybe it was hidden .. and ofc i cant even confirm or change that...
use clear images when explaining steps so we can follow along!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-scheduled-refresh)
* Content Source: [powerbi-docs/connect-data/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback.
