### ISSUE TITLE
More info on data type/format

### ISSUE THREAD

**Issue by skcary77** [MicrosoftDocs/powerbi-docs#383]
This would be more helpful if it included information on what can be returned from the R-script back into Power Query. For example, can the result of an R-script be a list, or does it have to be a data.frame? Does it have to be assigned to a particular variable (i.e. in your example it is called "output")?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Using R in Power BI Query Editor - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-in-query-editor.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
