### ISSUE TITLE
How refresh the connection to a updated sharepoint list on powerbi  (intergrate->powerbi->visualize the list)?

### ISSUE THREAD

**Issue by ChristopheST** [MicrosoftDocs/powerbi-docs#3830]
Hello,

I'm using sharepoint list and I create Powerbi dashboard with the integrate->powerbi->visualize the list.
It seems that the creation of the field list is done once when we use the first time the integrate->powerbi->visualize the list.
If I update the list add column remove ones ,it seems that the field list is not updated .
How update it without duplicate the list and redo a integrate->powerbi->visualize the list ?
What kind of limitation are already known , limitation of number of field or Type supported ?
I have list of more than 20 field wherie the last ones are not exported in powerbi Fields ?

Thanks for your support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list or library in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @ChristopheST, this is the channel for doc feedback for the content writers, and I think you have more a product related question. I suggest you try the [Power BI Community](https://community.powerbi.com/) orour [support page](https://support.powerbi.com/). Good luck!
