### ISSUE TITLE
Confusing description regarding limitations

### ISSUE THREAD

**Issue by GeorgeYinICF** [MicrosoftDocs/powerbi-docs#3836]
Please clafify the "consideration and Limitation" section of the page. It states there is a limit of 100 users or groups on the access list.  One first read/glance, it implies a published app can only support 100 users.  In our testing, we are able to add more than 100 users .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GeorgeYinICF. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @GeorgeYinICF, thanks for your feedback. We have an open work item precisely on this point now and will be updating the doc soon. I am going to close this issue now, but thanks for taking the time to reach out to us!
