### ISSUE TITLE
PBIRS Services Account is a group managed Service Account?

### ISSUE THREAD

**Issue by arcus4** [MicrosoftDocs/powerbi-docs#3837]
very helpful, thank you! In case that your Power BI reporting Services Account is a gMSA, have a look to the following first 
https://docs.microsoft.com/en-us/windows-server/security/group-managed-service-accounts/configure-kerberos-delegation-group-managed-service-accounts
and then configure your AD attribute(s) and afterwards, re-start your PBIRS service to bring your Constrained Delegation / AD changes online.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a56b58c-95a4-9216-61cf-3758c5debb3d
* Version Independent ID: cd953c75-d91f-91c6-f94a-cb75eff28f6e
* Content: [Configure Kerberos to use Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/configure-kerberos-powerbi-reports#delegation-settings-on-the-report-server-service-account)
* Content Source: [powerbi-docs/report-server/configure-kerberos-powerbi-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/configure-kerberos-powerbi-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @arcus4. This issue has been assigned to the doc author for review.
