### ISSUE TITLE
Old content: Disable copy as an image for a specific visual

### ISSUE THREAD

**Issue by Rickmaurinus** [MicrosoftDocs/powerbi-docs#3838]
[Enter feedback here]
Hi there,

I have two items of feedback for this page: 

1. The content on the below page is outdated. Currently the 'Visual Header' section has been discontinued and replaced by the header icons section. This makes the "Disable copy as an image for a specific visual" outdated.

2. There is a bug. In a Power BI report, when you turn off all items in the header icons -> Icons sections, except for 'Help tooltip, the copy 'Visual as Image' icon still appears when I publish the report to the service. 

Hope this will be solved in a future update. 

Regards,
Rick

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00479245-9654-ad47-b2d5-12f1e36ccdc9
* Version Independent ID: b46f2147-f0e8-cad0-7240-28b7231ae70d
* Content: [Copy and paste a visualization in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-copy-paste)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-copy-paste.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Rickmaurinus. This issue has been assigned to the doc author for review.
