### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#384]
"new workspaces experience workspace" seems like a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- yeah, I can see how it would sound like a typo. It's clumsy, at any rate. I've reworded it. Change should be live soon, like tomorrow. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- fixed now. Thanks!
