### ISSUE TITLE
Images are incorrect

### ISSUE THREAD

**Issue by Hyamyam** [MicrosoftDocs/powerbi-docs#3841]
Hi authors,

I think the images are little bit old.
(Actually the size of workspace is 10GB)

![image](https://user-images.githubusercontent.com/73410575/170010509-f1e7857e-2c0b-41a1-9719-764ca6447c44.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-manage-your-data-storage-in-power-bi#manage-items-you-own)
* Content Source: [powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Hyamyam. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Hyamyam, thanks for this input. I myself noticed this recently and am in the process of going over this article. So I am going to close this issue here now. Thanks again for taking the time to point this out!
