### ISSUE TITLE
Security tab in Power BI service

### ISSUE THREAD

**Issue by PrismaHans** [MicrosoftDocs/powerbi-docs#3844]
[In the document, there is a reference to the "Security" menu in "more options" on a given data set. This is no longer in the list of menu items. Do I have to go to groups through Admin tab to alter members in a given security group?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @PrismaHans, thanks for reaching out, and sorry for the long delay in responding. I still see the Security option in the dataset's more options menu, most of the time. I am trying to figure out why sometimes it's not there - I suspect something having to do with permissions, but I don't have an answer yet. I know it's been a long time, but can you tell me exactly what role you have (Admin, Member, etc.) in the workspace where the dataset resides? Thanks.

**Comment by paulinbar** [comment]
Hi @PrismaHans, sorry for the long delay. The truth is that the option menu for datasets is not consistent in all views. So if you look at a dataset's options when you're in the Onelake data hub, you won't see the Security option. If you go to list view in the workspace, you'll usually see the Security option. Unfortunately this is a known bug that confuses many people, but as far as I know there is no ETA for a fix. ;/
