### ISSUE TITLE
Incorrect information?

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#3845]
In the section https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-manage-gen2#creating-and-managing-capacities we have a list of changeable information:
Power BI service administrators and Global Administrators can modify Premium capacities. Specifically, they can:

Change the capacity size to scale-up or scale-down resources.
Add or remove Capacity Admins.
Add or remove users that have assignment permissions.
Change regions.

To my knowledge, the region of a capacity cannot be changed after the initial creation. This is the only document I know stating this differently. Could you please verify and adjust if necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Version Independent ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Content: [Manage Microsoft Power BI Premium Gen2 capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-manage-gen2)
* Content Source: [powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmuenster. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @gmuenster,

Thank you for your comment and for getting involved.

I'm checking with the product team whether a capacity's region can be changed, and will update you once I gent an answer. If needed, I'll also amend the article.

Thanks,

Kesem
