### ISSUE TITLE
Overwrite, not override

### ISSUE THREAD

**Issue by preston-reynolds** [MicrosoftDocs/powerbi-docs#3846]
4 times on this page the phrase "override" is used. I believe the correct word needed in these scenarios is "overwrite"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c40e327-d8c8-3011-e68b-7694d0ed2b04
* Version Independent ID: 3947ee9f-58b0-763c-8b56-b21cfdcbaac1
* Content: [Troubleshoot deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-troubleshooting)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-troubleshooting.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-troubleshooting.yml)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @preston-reynolds. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @preston-reynolds,

Thank you for catching this error and for letting us know!

I've replaced 'override' with 'overwrite' in [Deployment pipelines troubleshooting](https://docs.microsoft.com/power-bi/create-reports/deployment-pipelines-troubleshooting).

Thanks again,

Kesem
