### ISSUE TITLE
customdata DAX function for RLS not supported with Power BI RS

### ISSUE THREAD

**Issue by mathiasekz** [MicrosoftDocs/powerbi-docs#3848]
Hi,

Can you please specificy if customdata() DAX function is supported or not with Power BI Report Server (probably not supported) because it can be confusing.
Can you also detail a little bit more how customer can assign end users individually to roles, and detail if we can however use username and userprincipalname dax functions with custom authentication, otherwise dynamic RLS would not be possible and we have to be clear with this strong limitation

my Microsoft Alias : mathiase

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddf7cc0d-c931-db8f-5357-4c0b87475950
* Version Independent ID: 942a93eb-9259-351b-3d4b-e69b017227a7
* Content: [Row-level security (RLS) in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/row-level-security-report-server)
* Content Source: [powerbi-docs/report-server/row-level-security-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/row-level-security-report-server.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mathiasekz. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @mathiasekz. Thanks for your question and sorry for the delay answering.
The RLS docs have been revamped since you posted this. I think you'll find your answers here: https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls
