### ISSUE TITLE
Pbix file not as described: Tab missing?

### ISSUE THREAD

**Issue by Supergran** [MicrosoftDocs/powerbi-docs#3850]
Visualisations different to the related Microsoft docs article. Looks like a dashboard tab may be missing? There are no card visuals as described and shown in the article. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aebea8d-720c-4df0-b543-67f95ff1368c
* Version Independent ID: de96c5d7-0c83-c34f-1e3a-a0012553d22d
* Content: [Supplier Quality Analysis sample for Power BI: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/sample-supplier-quality)
* Content Source: [powerbi-docs/create-reports/sample-supplier-quality.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-supplier-quality.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Supergran. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Supergran, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
