### ISSUE TITLE
Power BI visuals interactivity utils: how to import getEvent()

### ISSUE THREAD

**Issue by duncan-health** [MicrosoftDocs/powerbi-docs#3851]
The following code is given in section 6 of this page.

What import or definition is required as getEvent() is not recognised?

```
protected bindClick() {
  const {
      elementsSelection
  } = this.options;

  elementsSelection.on("click", (datum) => {
      const mouseEvent: MouseEvent = getEvent() as MouseEvent || window.event as MouseEvent;
      mouseEvent && this.selectionHandler.handleSelection(
          datum,
          mouseEvent.ctrlKey);
  });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d211e63f-7300-55bc-3e19-2e48b11afd7d
* Version Independent ID: fc3890a9-de8b-cda4-8f8c-823663b37a42
* Content: [Power BI visuals interactivity utils - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/utils-interactivity-selections)
* Content Source: [powerbi-docs/developer/visuals/utils-interactivity-selections.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/utils-interactivity-selections.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @duncan-health. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @duncan-health, it looks like you need to add these lines to your code:

// d3
import { Selection } from 'd3-selection';
const getEvent = () => require("d3-selection").event;

You can see it in context here: https://github.com/microsoft/powerbi-visuals-chord/blob/main/src/interactiveBehavior.ts#L29
Thanks for pointing out this hole in the documentation. I'll add it.
