### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by collinq987** [MicrosoftDocs/powerbi-docs#3852]
I believe that there is more than 100 users (not groups, users) that can be added.  Read this thread:
https://community.powerbi.com/t5/Service/Add-more-than-100-Users-to-App/m-p/2551721

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @collinq987. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @collinq987, I have asked the product team for confirmation and will update the doc as soon as I get the answer. I'm going to close this issue here in the meantime. Thanks for your comment!
