### ISSUE TITLE
OneDrive Refresh Not Working for Report with Live Connection Dataset

### ISSUE THREAD

**Issue by fengjackling** [MicrosoftDocs/powerbi-docs#3854]
We create a report with live connection dataset in power BI service, then store the report in OneDrive and import it to Power BI Service but seems like Power BI cannot automatically sync the updates of report stored in OneDrive. Is it an expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset from OneDrive or SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-desktop-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fengjackling. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
