### ISSUE TITLE
Dashboard - Export tile to Excel	

### ISSUE THREAD

**Issue by ayumito** [MicrosoftDocs/powerbi-docs#3855]
I believe "Export tiles to CSV" is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with Free licenses in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @ayumito, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
