### ISSUE TITLE
Incremental Refresh for staging queries

### ISSUE THREAD

**Issue by bslattz** [MicrosoftDocs/powerbi-docs#3856]
[Enter feedback here]
Please include an explanaition for handling inc refresh for queries in a dependency chain.  e.g. if queries A is a transformation of query B, do we set inc refresh on both?  If A is not loaded, can we still do incrimental refresh from query B and get partitioning on thable A?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for datasets and real-time data in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by Minewiskan** [comment]
This suggestion will be put in the backlog. No additional requests or support incidents for information regarding this scenario have been made. If that changes, we'll revisit.
