### ISSUE TITLE
Power View deprecated

### ISSUE THREAD

**Issue by howardsu1** [MicrosoftDocs/powerbi-docs#3857]
Power view has been deprecated. We should remove all references to Power view. Reach out to Olivia Thomas at Microsoft for any additional details.

-Howard Su

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d15b3b2-c33a-9293-a6f2-749d164d1f1c
* Version Independent ID: 5bafb24c-0e82-7b95-1bc5-468debe8111a
* Content: [Publish to Power BI from Microsoft Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-publish-from-excel)
* Content Source: [powerbi-docs/connect-data/service-publish-from-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-publish-from-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @howardsu1. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @howardsu1 -- thanks for reaching out. I updated this article but there are several others. I'll work with Olivia to resolve the rest.
Thanks!
cc @davidiseminger
