### ISSUE TITLE
What is meant by "Unicode" on this page?  UCS-2, or a more current version of Unicode?

### ISSUE THREAD

**Issue by Cornan** [MicrosoftDocs/powerbi-docs#3858]
The .NET framework and SQL Server do a pretty good job of documenting which versions of Unicode (or UCS-2) are supported by various data types:

See _Strings and the Unicode Standard_ in:
https://docs.microsoft.com/en-us/dotnet/api/system.string?view=net-6.0
and
_Collation and Unicode Support_ in:
https://docs.microsoft.com/en-us/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16

My suggestion is to include a more detailed reference as to how Unicode is supported, on the subject page.  Also, I am becoming aware that Power Query and Power BI Desktop and possibly other components in the "Power" family treat other data types differently; could it be that "Unicode" is also handled differently among the "Power" products?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-types)
* Content Source: [powerbi-docs/connect-data/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Cornan. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion!
