### ISSUE TITLE
SSO?

### ISSUE THREAD

**Issue by jimbobTX** [MicrosoftDocs/powerbi-docs#386]
Does this work with SSO sources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29bfbd4c-5149-93be-3982-81af6852a5dd
* Version Independent ID: 75460ed0-c7d9-fe67-8010-b843661dc66e
* Content: [Connect to an OData feed in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-odata)
* Content Source: [powerbi-docs/desktop-connect-odata.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-odata.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
