### ISSUE TITLE
Symmetry Shading paragraph - Correction needed.

### ISSUE THREAD

**Issue by dhruvinushah** [MicrosoftDocs/powerbi-docs#3861]
[

In the 'Add a Symmetry Shading' paragraph there is an example using a chart for the symmetry shading used. The example however has a **navy blue** box, but the paragraph says that it is a **green** box in the pink area. Please review / fix. Thank you!

]
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668e4cf-3837-c2d4-b818-14476441468b
* Version Independent ID: c95096dd-9b73-79ab-8ff2-158c5900f5a6
* Content: [Scatter, bubble, and dot plot charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-scatter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-scatter.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dhruvinushah. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @dhruvinushah , 
Good catch!  We've made the update and set the article to republish. 
All the best,
The DOCS team
