### ISSUE TITLE
Information "Finding your company’s Microsoft 365 Tenant ID" is provided in the wrong place

### ISSUE THREAD

**Issue by James-Noble** [MicrosoftDocs/powerbi-docs#3862]
When following through this document I get to step 6 of "Install the App" and then I'm left trying to figure out what a TenantID is and where to get it from.  I did eventually work this out for myself after spending a while looking around and searching on google, then carried on through the instructions.  Then when reading through the rest of the page I find the section "Finding your company’s Microsoft 365 Tenant ID" in the middle of nowhere under the issues section.  It contains just a single line with a link to the required information.

It makes no sense to have this information here, instead of simply putting it in step 6 of the "Install the app" section, where it is needed.  Please could you just take the extra section out and put the info where it's needed, to help people following through the steps on this page in future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d621bc5e-d39c-3641-9385-24ead7ddb4f7
* Version Independent ID: d621bc5e-d39c-3641-9385-24ead7ddb4f7
* Content: [Connect to the Emissions Impact Dashboard for Microsoft 365 (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-emissions-impact-dashboard-microsoft-365)
* Content Source: [powerbi-docs/connect-data/service-connect-emissions-impact-dashboard-microsoft-365.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-emissions-impact-dashboard-microsoft-365.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi James, this is an excellent suggestion and I don't know why it wasn't done as you suggested in the first place. Making the change and it'll be online tomorrow. Thanks for taking the time to point this out!
@James-Noble
