### ISSUE TITLE
With what type of license is it?

### ISSUE THREAD

**Issue by AlinaKapshyk** [MicrosoftDocs/powerbi-docs#3863]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a Machine Learning model in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-tutorial-build-machine-learning-model#feedback)
* Content Source: [powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AlinaKapshyk. This issue has been assigned to the doc author for review.
