### ISSUE TITLE
Power BI Professional is stated to be the highest licensing level (actually Power BI Premium Per User is)

### ISSUE THREAD

**Issue by willz06jw** [MicrosoftDocs/powerbi-docs#3868]
This page inaccurately refers to Power BI Professional as the highest license level.  Currently, Power BI Premium-Per-User is the highest licensing level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95dbd95-1d7f-0ef8-34da-dc8bb4a0a26a
* Version Independent ID: e95dbd95-1d7f-0ef8-34da-dc8bb4a0a26a
* Content: [View and manage Power BI user licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-manage-licenses)
* Content Source: [powerbi-docs/enterprise/service-admin-manage-licenses.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-manage-licenses.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @willz06jw. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @willz06jw , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
