### ISSUE TITLE
Update Refresh section

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3869]
Hi,

As the "Try It" buttons are still missing on MS pages, please add to the Refresh section two steps how to trigger a refresh
[https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#troubleshoot-refresh-issues](url)

in the highlighted box, please add 
Use trigger: **Scheduled Cloud flow** - select starting time and run every hour, 
add Next step: **Refresh a dataset**

Let the the flow run once & switch off the Flow 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new modern workspaces (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#delete-the-dataset)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @MartinaPoddana, I am not exactly sure where this stands now, but I am moving this issue to our work item backlog for better tracking and consideration, and closing it here now. Thanks for your input!
