### ISSUE TITLE
Print from Desktop is available from August Update.

### ISSUE THREAD

**Issue by v-nisvoo** [MicrosoftDocs/powerbi-docs#387]
Print from desktop is available from 2018 August Update. https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2018-feature-summary/#print. But this page says  "Printing is only available in Power BI service and not Power BI Desktop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c738da8-eb0a-7e87-0cbc-f424d4d2f381
* Version Independent ID: 1584c6a8-2152-8657-6a0b-6538f94fd1e3
* Content: [Printing from Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-print)
* Content Source: [powerbi-docs/consumer/end-user-print.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-print.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfile** [comment]
Hi @v-nisvoo , thank you for your feedback. This issue has been assigned to the author for review.

**Comment by davidiseminger** [comment]
Re-assigning to the doc owner.

**Comment by mihart** [comment]
Hi @v-nisvoo ,
I've updated the article with this information. Thanks for catching this!
The DOCS team
