### ISSUE TITLE
Missing details

### ISSUE THREAD

**Issue by MathewWest** [MicrosoftDocs/powerbi-docs#3872]
[It seems rather odd, that that there are a lot of functions in the model view not explained - one of them being "Key Column" how to organise fields on a table using folders etc... is there a full document on all Power BI functions like this?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f402391-8dfc-cfa4-89b1-335f7c9dad1c
* Version Independent ID: 31ba30b8-61df-54d2-f97c-93ba77319cba
* Content: [Model view in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-relationship-view#feedback)
* Content Source: [powerbi-docs/transform-model/desktop-relationship-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-relationship-view.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MathewWest. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. There are many capabilities in Model view that correspond to commonly understood database and data model management and interactions, which are outside the scope and intent of this overview article.
