### ISSUE TITLE
Question about the wording of "multiple Gigabit network adapters"?

### ISSUE THREAD

**Issue by rocdong** [MicrosoftDocs/powerbi-docs#3873]
From the document, it says:
**Initial sizing**
It can be difficult to accurately estimate the right size. We recommend that you start with a machine with at least 8 CPU cores, 8 GB of RAM, and **multiple Gigabit network adapters**. You can then measure a typical gateway workload by logging CPU and memory system counters.

Is it referring to multiple adapters for the gateway VM? 
If it's YES, what's the suggestion on numbers and configurations?

thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93be3185-bbc2-6e4a-0b3b-8c2d0482a148
* Version Independent ID: e9c257ea-9a49-d954-5954-4d14442c49a5
* Content: [On-premises data gateway sizing - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/gateway-onprem-sizing)
* Content Source: [powerbi-docs/guidance/gateway-onprem-sizing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/gateway-onprem-sizing.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rocdong. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @rocdong - the answer is yes, but we cannot make a recommendation for the numbers, since it will be dependent on the set-up and load on the customers environment. I hope that helps.
