### ISSUE TITLE
Data Source credentials need to be set in the service after publishing.

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/powerbi-docs#3874]
After publishing the pbix to the service the OAuth2 credentials need to be set by the user to enable refresh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/connect-data/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dbrownems. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated that article. Thanks!
