### ISSUE TITLE
Q&A works with DirectQuery now

### ISSUE THREAD

**Issue by stangeh** [MicrosoftDocs/powerbi-docs#3875]
[Enter feedback here]

This page says Q&A is not supported with DirectQuery... but I've read in other official Power BI documentation that it is indeed supported. See below.

**This needs to be corrected or deleted:** 
'For example, the QuickInsights and Q&A features aren't available on a model if any of the tables within it has a storage mode of DirectQuery.'

**Proof from other Power BI documentation:**
https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-limitations

_Q&A now supports SQL DirectQuery sources, including SQL Server 2019, Azure SQL Database, and Azure Synapse Analytics. You can use Q&A to ask natural-language questions against these data sources. There's one small change to the behavior of Q&A when it's in DirectQuery mode: After you type your question, you select the Submit button. This change prevents overloading the DirectQuery source with unnecessary queries as you type_
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/desktop-storage-mode)
* Content Source: [powerbi-docs/transform-model/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-storage-mode.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stangeh. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out, I've updated the article.
