### ISSUE TITLE
Typo in first bullet point on governance decisions section

### ISSUE THREAD

**Issue by jlmnn** [MicrosoftDocs/powerbi-docs#3876]
Recommendations and requirements for [content ownership and ownership](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-content-ownership-and-management).

Should be:

Recommendations and requirements for [content ownership and management](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-content-ownership-and-management).

in this section: https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-governance#key-power-bi-governance-decisions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf42906e-560f-f231-04a3-bedccdc502cd
* Version Independent ID: e0dda81e-3dd4-eb78-9e5d-aa495e7df70d
* Content: [Power BI adoption roadmap: Governance - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-adoption-roadmap-governance)
* Content Source: [powerbi-docs/guidance/powerbi-adoption-roadmap-governance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-adoption-roadmap-governance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jlmnn. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @jlmnn - thanks for pointing out the typo. I've fixed the error and an updated article should be published soon.
