### ISSUE TITLE
Near efficient?

### ISSUE THREAD

**Issue by dbeavon** [MicrosoftDocs/powerbi-docs#3877]
"...deliver near efficient.."?

I think the "near" was supposed to be bound to the word real-time.  Never heard of anything being nearly efficient before.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf7d5280-8744-92db-82b6-a89ad6f3d696
* Version Independent ID: cf7d5280-8744-92db-82b6-a89ad6f3d696
* Content: [Migrate from Azure Analysis Services to Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/migrate-azure-analysis-services-to-powerbi-premium)
* Content Source: [powerbi-docs/guidance/migrate-azure-analysis-services-to-powerbi-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/migrate-azure-analysis-services-to-powerbi-premium.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by peter-myers** [comment]
Hi @dbeavon - thanks for pointing out the typo. I've fixed the error and an updated article should be published soon.
