### ISSUE TITLE
.

### ISSUE THREAD

**Issue by PetjaS** [MicrosoftDocs/powerbi-docs#3878]
[Enter feedback here]
There is no such button in the dashboard view (edit theme). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b534707-1253-6a56-5b6e-d69edf32e1ab
* Version Independent ID: 34be0bef-858c-658f-4bbd-dc4da405759c
* Content: [Use dashboard themes in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-themes)
* Content Source: [powerbi-docs/create-reports/service-dashboard-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-dashboard-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PetjaS. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @PetjaS, is this the button that you are referring to?
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/54644589/be92ef00-f72a-4295-b8ef-1cda1e975ad7)
If so, I can't recreate your problem. Can you provide more detail. Do you have the right permissions for editing the dashboard? 
I am going to close this issue now, but please feel free to reopen with more detail if you still have the problem. Thanks!
