### ISSUE TITLE
Refresh summary Gen2

### ISSUE THREAD

**Issue by mansohrstrom** [MicrosoftDocs/powerbi-docs#3879]
The refresh schedule booked vs available seems to be based on Gen1 limits (which is 6 for P1 vs Gen2 which has 40 concurrent refreshes). For a P1 Gen2 it uses 30 x 6 = 180 mins for calculation. 

https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-summaries#refresh-schedule

Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fa2461-63e1-b318-df7c-557646976010
* Version Independent ID: c074364c-a68a-5e42-258b-d7b8e24e2552
* Content: [Refresh summaries for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-summaries)
* Content Source: [powerbi-docs/connect-data/refresh-summaries.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-summaries.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mansohrstrom. This issue has been assigned to the doc author for review.

**Comment by gertch** [comment]
As far as I know everybody is on Gen 2 by now.  The portal feature and this page should be retracted or adapted to Gen2.  We need clear communication what refresh limits we have on Gen 2 infrastructure. Nothing is "unlimited".

**Comment by davidiseminger** [comment]
Thanks for your comments. Re-assigning to the author covering Gen2, to review and updated as needed.

**Comment by KesemSharabi** [comment]
Hi @mansohrstrom,

Thanks for bringing this into our attention.

I made some changes to the 4th paragraph in [Refresh schedule](https://learn.microsoft.com/power-bi/connect-data/refresh-summaries#refresh-schedule) to reflect the move to gen2.

The changes will be visible shortly.

Kesem
