### ISSUE TITLE
Both screenshots show unsupported (later) version of R in Desktop

### ISSUE THREAD

**Issue by cclarktax** [MicrosoftDocs/powerbi-docs#3882]
### Two instructional pics on this page show the unsupported version of R (4.0.0) in the R scripting options menubox.  In reference, see pages [/en-us/power-bi/create-reports/desktop-r-visuals](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals#enable-r-visuals-in-power-bi-desktop) and [/en-us/power-bi/visuals/service-r-visuals](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals) with images of the correct (albeit outdated) version of R 3.4.4.  This is misleading to devs who are familiar with R and may not see the overview pages.

![image](https://user-images.githubusercontent.com/48168322/174191277-d9bd2754-2801-4849-8922-2a4150c94b8c.png)

[Link to second pic](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-ide#requirements)

![image](https://user-images.githubusercontent.com/48168322/174190986-725684f1-81e0-4de3-a6a6-d552f2e65a5d.png)

**Correct pic for R version [/en-us/power-bi/create-reports/desktop-r-visuals](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals#enable-r-visuals-in-power-bi-desktop)**

![image](https://user-images.githubusercontent.com/48168322/174158317-40bebaf2-3698-4e42-9106-ec2383e38e1b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d08953c-1912-d458-f1ef-d2d3041f5e41
* Version Independent ID: 18d26011-dd33-6f46-a01d-8cca0e31d040
* Content: [Use an external R IDE with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-r-ide)
* Content Source: [powerbi-docs/connect-data/desktop-r-ide.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-ide.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cclarktax. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we've updated the article. Thanks!
