### ISSUE TITLE
Columnar data mismatch in suggested URL example 

### ISSUE THREAD

**Issue by khybercat** [MicrosoftDocs/powerbi-docs#3884]
I am trying to follow along with the example quoted in the web page below,
but the data referenced in the URL link does not match:

"From [Getting Started with Power BI Desktop](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started), let's use the retirement data, which we found by connecting to a web data source, to shape that data to fit our needs."

That URL referred to in the link above is: https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/ 

Trying to add a custom column, but the columns it  references do not exist in the table I imported from 
the URL as described above.

Can you clarify this issue for me/

Thanks

Malcolm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @khybercat. This issue has been assigned to the doc author for review.

**Comment by khybercat** [comment]
Hi David (@davidiseminger),

Have you managed to look at this query? 
Regards
Malcolm

**Comment by davidiseminger** [comment]
Thanks for your comment, this article has since been updated.
