### ISSUE TITLE
Maybe Updated Concept? Report comes from one dataset?

### ISSUE THREAD

**Issue by tatamoreira11** [MicrosoftDocs/powerbi-docs#3885]
The section under reports reads: "All of the visualizations in a report come from a single dataset"
A report can be made up of multiple datasets. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [The Power BI service - basic concepts for beginners - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tatamoreira11. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @tatamoreira11 , 
Thank you for your suggestion.  We've made the update and set the article to republish. It now says "can be created using data from one dataset. Power BI Desktop can combine more than one data source into a single dataset in a report, and that report can be imported into Power BI."
All the best,
The DOCS team
