### ISSUE TITLE
Web.Contents failed to get contents from 'https://api.tiingo.com/tiingo/daily/FB' (404): Not Found. 

### ISSUE THREAD

**Issue by wiegelman** [MicrosoftDocs/powerbi-docs#3886]
[Enter feedback here]
How can I edit this App so I can fix what appears to broken ticker - I believe FB changed to META recently and this has been broken for a few days now:

Web.Contents failed to get contents from 'https://api.tiingo.com/tiingo/daily/FB' (404): Not Found. 

![image](https://user-images.githubusercontent.com/6857798/174392990-dc2a936a-d787-473d-82c0-4299da23a1ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5308a208-db3b-4809-b53d-c3a377a44ef9
* Version Independent ID: 9da270be-cef5-7699-3b0d-c50a1505179f
* Content: [Analyze Popular Stocks with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-analyze-stocks)
* Content Source: [powerbi-docs/connect-data/service-connect-to-analyze-stocks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-analyze-stocks.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wiegelman. This issue has been assigned to the doc author for review.

**Comment by RodrigoRibeiro1995** [comment]
Has this been resolved?

**Comment by paulinbar** [comment]
Hi @wiegelman and @RodrigoRibeiro1995 , thanks for reaching out, and sorry for the delay. I am putting a person familiar with the app into the loop.
@teddyberco, are you aware of the problem mentioned here with regard to the Analyze Popular Stocks with Power BI template app?

**Comment by paulinbar** [comment]
Hi @wiegelman and @RodrigoRibeiro1995,
Today I was informed by the product team that the Analyze Popular Stocks with Power BI template is no longer being supported and has been withdrawn from AppSource, so I am afraid that no fix for current installations is coming. Sorry to have this news, but thanks for reaching out.
