### ISSUE TITLE
Links to templates not working

### ISSUE THREAD

**Issue by mmahomar** [MicrosoftDocs/powerbi-docs#3889]
None of the links to the templates are working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b777f61-d4cf-bc8e-64b5-43c2e695051b
* Version Independent ID: 20c2b71c-b805-b5e1-4de3-f5bc51de91e5
* Content: [Template apps samples - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-samples)
* Content Source: [powerbi-docs/connect-data/service-template-apps-samples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-template-apps-samples.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mmahomar. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @mmahomar, The samples article is indeed out of date and I just removed it. Those samples are no longer available, and in a number of cases the template apps don't exist anymore either.  
You can find template apps on appsource, or by going into the apps page in Power BI and choosing Get apps. 
Thanks for bringing this obsolete article to my attention.
