### ISSUE TITLE
Service Bus costs and requirements

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/powerbi-docs#389]
you need to ellaborate where the service bus lives / needs to live (ie a subscription) and the costs of such above and beyond Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337848b9-e784-3358-7b8e-853fe40120e3
* Version Independent ID: e92fa154-5fc4-cefe-ebe8-d62c36ce551d
* Content: [On-premises data gateway in-depth - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-indepth)
* Content Source: [powerbi-docs/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-indepth.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @bakerm00 
Thank you for the suggestion.  I've forwarded this to the doc owner who will be in touch soon.
Take care,
Michele

**Comment by mgblythe** [comment]
@bakerm00 and @jordanmills - sorry for the delay on this. I added this sentence to the doc, which will publish today: "Power BI manages the Service Bus for you, so there are no additional costs or configuration steps required."
