### ISSUE TITLE
"Export data to Excel" has PowerPoint picture instead 

### ISSUE THREAD

**Issue by tatamoreira11** [MicrosoftDocs/powerbi-docs#3890]
[Enter feedback here]
Under the Export data to Excel heading, a picture of a PowerPoint presentation shows up instead of Excel 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cece6cf-53cd-6704-7c50-d03007f60a96
* Version Independent ID: 439ed96c-e946-d8d5-1943-82fb4b2c41b0
* Content: [Power BI consumer capabilities in Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-reading-view)
* Content Source: [powerbi-docs/consumer/end-user-reading-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-reading-view.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tatamoreira11. This issue has been assigned to the doc author for review.
