### ISSUE TITLE
Issue: Republishing when RLS is configured

### ISSUE THREAD

**Issue by yaniv-intlock** [MicrosoftDocs/powerbi-docs#3891]
Could you please clarify what is the error in more technical details? - [Issue: Republishing when RLS is configured](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-rls#issue-republishing-when-rls-is-configured)

Is it during publish? or is it after the pbix has been published and while trying to view the report?

Is it related to losing the members of a role after republishing? (this [idea](https://ideas.powerbi.com/ideas/idea/?ideaid=124c7446-e690-4041-9c8c-c675d215b5f7)?)

Is there a fix planned for this and what would it be?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-rls#issue-republishing-when-rls-is-configured)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by mberdugo** [comment]
Thanks for your questions, @yaniv-intlock. I tested this issue and asked around, and it seems like this has been fixed and republishing from the desktop is no longer a problem. I'll update the document accordingly.
