### ISSUE TITLE
Document contradicts itself in 'GET /refreshes'

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerbi-docs#3892]
Under 'GET /refreshes', the example response body does not match the content just below it for 'Response Properties'. 

1. The status values in 'GET /refreshes' doesn't match 'Response Properties'.
2. The status values in 'GET /refreshes' are actually for a new column extendedStatus.
3. The status values for extendedStatus do not match the actual values I'm getting. ie: Docs say 'notStarted', API returns 'NotStarted'.
4. The 'Response Properties' status values are still accurate, and do not need to be changed.
5. the refreshType is coming back as ReliableProcessing and not ViaApi using the new API.

At this time, this doc is inaccurate, and will cause problems if people try to use it. Please check with devs to get the accurate API details and response info. 

**Here is an example of my output:**
requestId      : 644a88d9-f650-4a54-9e59-d3a01e0df8d8
id             : 1277491253
refreshType    : ReliableProcessing
startTime      : 6/20/2022 4:18:58 PM
**status         : Unknown
extendedStatus : NotStarted**

requestId      : 644a88d9-f650-4a54-9e59-d3a01e0df8d8
id             : 1277491253
refreshType    : ReliableProcessing
startTime      : 6/20/2022 4:18:58 PM
endTime        : 6/20/2022 4:19:13 PM
**status         : Completed
extendedStatus : Completed**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6d5230d-8c4f-b353-5d44-d92c61a7ec85
* Version Independent ID: f6d5230d-8c4f-b353-5d44-d92c61a7ec85
* Content: [Enhanced refresh with Power BI REST API - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh)
* Content Source: [powerbi-docs/connect-data/asynchronous-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/asynchronous-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsh121988. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
#in-progress

**Comment by Minewiskan** [comment]
@jsh121988 Thanks for pointing this out. You are correct about the response example being outdated. This was due to recent API changes. The article has been updated with the new response properties and response body example. 
refreshType: ReliableProcessing may still appear in the response body in certain environments, but will become ViaEnhancedApi in all environments in early July.
