### ISSUE TITLE
Add link to creating a Calculated Table 

### ISSUE THREAD

**Issue by mercer2000** [MicrosoftDocs/powerbi-docs#3893]
The **Generate with DAX** section doesn't provide any details how to create a calculated table. It would be helpful to add the steps needed to add a calculated table using DAX. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e837063b-c36b-6bac-5c6b-10534146325c
* Version Independent ID: 7dcf1114-8d0e-39e7-e58f-894904f5a252
* Content: [Create date tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/model-date-tables)
* Content Source: [powerbi-docs/guidance/model-date-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/model-date-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mercer2000. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @mercer2000 - thanks for your feedback. I've added a tip to the article that leads the reader to a learning module about creating calculated tables, including an example of a date table. That change should become available soon.
