### ISSUE TITLE
gateway seems required now on power bi service

### ISSUE THREAD

**Issue by b3rntsen** [MicrosoftDocs/powerbi-docs#3895]
We tried creating a dataset on powerbi desktop connecting directly to a sql server online. When we upload the data set to power bi service, it notes that the data sources has been deleted and the controls for datasource has been deleted. It's only possible to add a gateway. This seems to be in discrepancy with what is expressed in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data)
* Content Source: [powerbi-docs/connect-data/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-get-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @b3rntsen. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This article has been updated since your post here. If you need technical support, ou might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
