### ISSUE TITLE
DataSource.Error: The table has no visible columns and cannot be queried.

### ISSUE THREAD

**Issue by ctako** [MicrosoftDocs/powerbi-docs#3897]
Hi there, I encountered the above error when I tried to connect to a table in Amazon Redshift. Any idea why? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 886f5a19-b68e-777d-670a-99f8dd7e3cac
* Version Independent ID: c5731857-58ec-de4c-785c-f412e097805a
* Content: [Connect to an Amazon Redshift database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connect-redshift)
* Content Source: [powerbi-docs/connect-data/desktop-connect-redshift.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-redshift.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ctako. This issue has been assigned to the doc author for review.

**Comment by someshpk** [comment]
Hi, 

I have encountered the same issue when connecting to a view situated on Hadoop(Hive) db via ODBC connector.
Any solutions on this error?

**Comment by mobenn** [comment]
Please a solution. Same problem using ODBC.

**Comment by davidiseminger** [comment]
Sorry to hear about your trouble. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
