### ISSUE TITLE
Update browser Requirements 

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#3899]
Under minimum requirements, the page suggests that the minimum requirements for the browser are IE11 or later. Now that IE has been deprecated, should the browser min requirements be updated ?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pawarbi. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @pawarbi,

Can you please state which document you're referring to?

Thanks,

Kesem

**Comment by davidiseminger** [comment]
Good point! I've updated that page to reflect. Thanks for posting here.
