### ISSUE TITLE
gửi phản hồi

### ISSUE THREAD

**Issue by khenhhung2** [MicrosoftDocs/powerbi-docs#390]
sữa sản phẩm

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a743ee1c-0e09-a9d8-f211-28b308a2979e
* Version Independent ID: 4a829c6a-b5ba-cff6-5eba-c7f1b688be3e
* Content: [Import Excel workbooks into Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-import-excel-workbooks)
* Content Source: [powerbi-docs/desktop-import-excel-workbooks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-import-excel-workbooks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by imas401** [comment]
Hi, please help me to solve this problem. Why I cannot import the excel workbook in power bi? The notification is: The following Excel workbook does not contain any queries or a model to import?

Many thanks

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
