### ISSUE TITLE
Share Functionality within an App vs. Workspace

### ISSUE THREAD

**Issue by akhil25mani** [MicrosoftDocs/powerbi-docs#3900]
I have been testing the ability to share a report with filters and I see that the "Share" option is available in the workspace (Staging & Production) but not once a report is published to an app. Do you know if the "Share" feature can be added to the app as well?

Share Option in Workspace:
![Share](https://user-images.githubusercontent.com/108012218/175064687-96aaf3ec-874c-49db-a2f8-e4e40ba4fce0.PNG)

No Share Option in App:
![No Share](https://user-images.githubusercontent.com/108012218/175064813-62d08810-8bc6-4664-a0bc-87b890a90efb.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b3989d-4ab1-51f2-6823-970c04f6fba9
* Version Independent ID: 673ccbe9-ef77-5c5b-9936-37eaeb4d3762
* Content: [Share a filtered Power BI report - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-share-reports)
* Content Source: [powerbi-docs/collaborate-share/service-share-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-share-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
HI, @akhil25mani -- interesting observation! I'll check with the product team. Meanwhile, I suggest checking https://ideas.powerbi.com/ideas/ to see if anyone else has suggested it. If not, you can suggest it!

**Comment by maggiesMSFT** [comment]
Hi, @akhil25mani -- you're right, that is the current behavior. The workaround is to have the app owner share the report with that person. but it wouldn't be filtered...
Definitely suggest it at https://ideas.powerbi.com/ideas/! The product team pays a lot of attention to what customers ask for.
