### ISSUE TITLE
Stale data in COVID-19 US Tracking Report template app

### ISSUE THREAD

**Issue by JamesDBartlett3** [MicrosoftDocs/powerbi-docs#3901]
The COVID-19 US Tracking Report template app is set to retrieve its data from these two CSV files:

- [covid_confirmed_usafacts.csv (usafactsstatic.blob.core.windows.net)](https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_confirmed_usafacts.csv)
- [covid_deaths_usafacts.csv (usafactsstatic.blob.core.windows.net)](https://usafactsstatic.blob.core.windows.net/public/data/covid-19/covid_deaths_usafacts.csv)

These CSV files were originally maintained and published by USAFacts.org, but the versions hosted at the links above are copies of those original files, and have NOT been updated since August 16th, 2021, so this template app is now populated with extremely stale data.

However, the [USAFacts.org website](https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/) still keeps its original copies of these files updated with the latest COVID-19 data, so the only change necessary to make this template app work again is to replace the CSV file links in Power Query with these ones:

- [covid_confirmed_usafacts.csv (static.usafacts.org)](https://static.usafacts.org/public/data/covid-19/covid_confirmed_usafacts.csv)
- [covid_deaths_usafacts.csv (static.usafacts.org)](https://static.usafacts.org/public/data/covid-19/covid_deaths_usafacts.csv)

This zip archive contains two files: Cases.m and Deaths.m

- [Cases & Deaths.zip](https://github.com/MicrosoftDocs/powerbi-docs/files/8960934/Cases.Deaths.zip)

Replace the _Cases_ M query with the code in the Cases.m file, and replace the _Deaths_ M query with the code in the Deaths.m file, and the COVID-19 US Tracking Report template app will have the latest data again. I have made the necessary changes to my local copy of the COVID-19 US Tracking Report, so if you'd rather just use my copy of the PBIX or PBIT file to update the template app, just let me know. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1eccadf-bff1-8010-6eab-f8e357aa35fc
* Version Independent ID: f789d447-2bc7-5cf1-5633-e73b45957f70
* Content: [Connect to the COVID-19 US tracking report - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-covid-19-tracking)
* Content Source: [powerbi-docs/connect-data/service-connect-to-covid-19-tracking.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-covid-19-tracking.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @JamesDBartlett3, well, coming up on a year ago I forwarded your suggestion and offer to the app developer, but never heard back, so I am going to close this issue now. Sorry that they didn't take you up on it. Thanks for taking the time in any event.

**Comment by JamesDBartlett3** [comment]
@paulinbar How can I get in touch with the app developer?
