### ISSUE TITLE
Power BI Template App Samples - Page Not Found

### ISSUE THREAD

**Issue by primetimeai3000** [MicrosoftDocs/powerbi-docs#3908]
I'm trying to access template app samples Template app samples from the link below

https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-samples

I'm looking for the QBO Power BI template app specifically. I keep getting a "Page not found" error when clicking the link.

![This site cannot be reached](https://user-images.githubusercontent.com/108133825/175540774-c45fa245-e560-4c30-8ce6-960f1bc3064d.jpg)
![Power BI Template Links](https://user-images.githubusercontent.com/108133825/175540776-1bad57af-eb59-4e62-9d0c-e15e7b455a6b.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.mic
rosoft.com ➟ GitHub issue linking.*

* ID: 7b777f61-d4cf-bc8e-64b5-43c2e695051b
* Version Independent ID: 20c2b71c-b805-b5e1-4de3-f5bc51de91e5
* Content: [Template apps samples - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-template-apps-samples)
* Content Source: [powerbi-docs/connect-data/service-template-apps-samples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-template-apps-samples.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @primetimeai3000. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @primetimeai3000, The samples article is indeed out of date and I just removed it. Those samples are no longer available, and in a number of cases the template apps don't exist anymore either.  
You can find template apps on appsource, or by going into the apps page in Power BI and choosing Get apps. 
Thanks for bringing this obsolete article to my attention.
