### ISSUE TITLE
Useless without SSO

### ISSUE THREAD

**Issue by jimbobTX** [MicrosoftDocs/powerbi-docs#391]
As stated in this article, SSO isn't supported, so any corporate instance is not able to use this. When will that be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e2ce012-0b66-7a2d-2ce0-630f35abdf88
* Version Independent ID: 7d647855-d659-d495-e876-9189a5ba5125
* Content: [Connect to ServiceNow with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-servicenow)
* Content Source: [powerbi-docs/service-connect-to-servicenow.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-servicenow.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Hi, @jimbobTX -- Thanks for your question! It's a product question more than a documentation question, right? So head on over to https://ideas.powerbi.com/forums/265200-power-bi, see if anyone else has asked the same question, and if not, you can add it there. OK? Thanks again for using Power BI!

**Comment by ShaneOss** [comment]
Yeah tried to use but doesn't support federated SSO. So technically not working for me.

**Comment by ShaneOss** [comment]
> 
> 
> Yeah tried to use but doesn't support federated SSO. So technically not working for me.

Ended up building my own PowerBI report from an export of all the data in ServiceNow to Excel file.
