### ISSUE TITLE
Datamarts?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#3911]
Can this page clarify what role can perform which actions with the new datamart functionality?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in the new workspaces in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @otravers , I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
