### ISSUE TITLE
This page should contain the version of Power BI Report Builder associated to it's version of Report Server

### ISSUE THREAD

**Issue by vcarazo** [MicrosoftDocs/powerbi-docs#3912]
[Enter feedback here]
This page contains info for Power BI Report Server but the link to Power BI Report Builder shows info about the report Builder for the cloud service.

This page should contain the version of Power BI Report Builder associated to it's version of Report Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by KesemSharabi** [comment]
Hi @vcarazo,

[Change log for Power BI Report Server](https://learn.microsoft.com/power-bi/report-server/changelog) provides a list of bug fixes for each released build.

To download Report Server visit [On-premises reporting with Power BI Report Server](https://powerbi.microsoft.com/report-server/) and review the article [What's new in Power BI Report Server?](https://learn.microsoft.com/power-bi/report-server/whats-new)

**Comment by vcarazo** [comment]
Hi,

what I was saying is in every release you can see the power bi report server version and associated power bi desktop version. But there is no mention to the associated Report Builder version.
