### ISSUE TITLE
Possible stale limitation - variable editing after publishing to service for SAP HANA

### ISSUE THREAD

**Issue by lesliemui** [MicrosoftDocs/powerbi-docs#3913]
-Change to Variables after publish - You cannot change the values for any SAP HANA variables directly in the Power BI service, after the report is published.
Under considerations and limitations, I'm not sure if this applies any more. 

https://docs.microsoft.com/en-us/power-bi/connect-data/service-edit-sap-variables

As far as I can tell, this seems to have been resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3124203c-c90c-4b87-f657-e3373af0d480
* Version Independent ID: c2f065a5-d48a-c921-92d8-8f99874fef3b
* Content: [DirectQuery for SAP HANA in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-sap-hana#considerations-and-limitations)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-sap-hana.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lesliemui. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
That article has been updated. Thanks!
