### ISSUE TITLE
Metrics is now GA

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#3914]
Title should be updated as the feature is no longer in preview:
https://powerbi.microsoft.com/en-us/blog/power-bi-goals-is-now-metrics-and-is-moving-to-ga/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ac2aa1-b899-184c-10c3-7909aa32bff8
* Version Independent ID: 17e2b2b8-02c5-fcf0-32ab-7f3ef2eb271f
* Content: [Create scorecards and manual metrics (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-create)
* Content Source: [powerbi-docs/create-reports/service-goals-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-create.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @otravers -- fixing now. Changes will be live tomorrow afternoon June 28 Pacific time
