### ISSUE TITLE
User without contributor role within dataset workspace can download PBIX file

### ISSUE THREAD

**Issue by AkshayDutta** [MicrosoftDocs/powerbi-docs#3915]
Hello Team, 

Can you please change below point as it is not correct.

This has been reported in PBI CAT and PBI CSS team as well.

Limitations when downloading a .pbix from a report

You can download a file in either Reading view or Editing view. **You must be at least a Contributor to the workspace that the report is in. If the report is based on a dataset in another workspace, you need to be at least a Contributor to that workspace as well.**

Thanks, AKD.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AkshayDutta. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @AkshayDutta,

Can you please let me know which article you're referring to?

Also, if you're a Microsoft employee, please start an email thread for this.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @AkshayDutta,

Thank you for providing the link.

Can you please explain what is wrong in your opinion with this sentence (the first bullet in [Limitations when downloading a .pbix from a report](https://docs.microsoft.com/power-bi/create-reports/service-export-to-pbix#limitations-when-downloading-a-pbix-from-a-report)):

You can download a file in either Reading view or Editing view. **You must be at least a Contributor to the workspace that the report is in. If the report is based on a dataset in another workspace, you need to be at least a Contributor to that workspace as well.**

Thanks,

Kesem

**Comment by AkshayDutta** [comment]
Hello Kesem,


This Sentence "You must be at least a Contributor to the workspace that the report is in. If the report is based on a dataset in another workspace, you need to be at least a Contributor to that workspace as well."

This Limitation has been removed.

Thanks! Akshay Dutta

**Comment by KesemSharabi** [comment]
Thanks for explaining @AkshayDutta.

I'm validating your claim and will get back to you.

Are you saying that the entire limitation has been removed? Or just this part: "If the report is based on a dataset in another workspace, you need to be at least a Contributor to that workspace as well"?

Thanks,

Kesem
