### ISSUE TITLE
Conflicting info on number of refreshes

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#3916]
In your table you state that refreshes are limited to 48 a day. Later in the same page is stated that: "The number of refreshes isn't currently restricted."

The limit of 48 refreshes per day is only in the service's UI, you can trigger more than 48 refreshes via the API or Power Automate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Version Independent ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @otravers,

I'm checking with the product team whether the PPU refresh rate can be higher than 48 per day when using APIs.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @otravers,

After checking this with the engineering team I can confirm that you're correct, using APIs or Power Automate you can override the '48 per day' limit.

We'll consider adding this to the document.

Thanks,

Kesem
