### ISSUE TITLE
Links to composable Dataflow links are broken

### ISSUE THREAD

**Issue by pugliathomas** [MicrosoftDocs/powerbi-docs#3917]
[Enter feedback here]
The links to staging, transformation, and final data flow do not point to an actual page.

https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-advanced-data-preparation#staging-dataflow

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43eb7a25-a6a4-c798-d581-7b8e703c7aac
* Version Independent ID: 43eb7a25-a6a4-c798-d581-7b8e703c7aac
* Content: [Power BI usage scenarios: Advanced data preparation - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-advanced-data-preparation)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-advanced-data-preparation.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-advanced-data-preparation.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pugliathomas. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @pugliathomas - thanks for pointing out the broken links. I've updated the article and those fixes should become available soon. In the meantime, you can use this link to the intended article: https://docs.microsoft.com/power-query/dataflows/best-practices-for-dimensional-model-using-dataflows
