### ISSUE TITLE
GIS Definition

### ISSUE THREAD

**Issue by johnbonnett** [MicrosoftDocs/powerbi-docs#392]
GIS Stands for Geographic Information Systems, not Geographic Information Science, though I like that better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39395f6d-4136-97c3-348c-00e8060a1cbd
* Version Independent ID: bf20855d-f1ad-be4e-dbbc-bcfa911479a5
* Content: [Create ArcGIS maps by ESRI in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-visualization-arcgis)
* Content Source: [powerbi-docs/power-bi-visualization-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-visualization-arcgis.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
@johnbonnett 
Thanks for letting me know. I've updated the document.
Take care,
Michele
