### ISSUE TITLE
In the 'Limitations' section add an entry for no data-driven subscriptions. 

### ISSUE THREAD

**Issue by atho3009** [MicrosoftDocs/powerbi-docs#3924]
[Enter feedback here]
Hi,

One of the limitations we have bumped in to when migrating SSRS to PowerBI is that Paginated Report subscriptions have no equivalent to data-driven subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720989e-e6c4-2377-e0c0-8c80d5691f46
* Version Independent ID: 3c6392e8-0f91-1c9c-2c21-15291d46bfd0
* Content: [What are paginated reports in Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @atho3009. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @atho3009 -- good point! I added it to the section about subscriptions rather than to the general Limitations section, and then I added it to the article about subscriptions, https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe?tabs=creator#subscribe-to-paginated-reports. Changes will be live tomorrow afternoon July 21 Pacific time.
Thanks!

**Comment by fowl2** [comment]
@maggiesMSFT it appears that there's still no mention of data-driven subscriptions in the limitation sections these two pages:
* [What are paginated reports in Power BI Premium?](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi#considerations-and-limitations)
* [Email subscriptions for reports and dashboards in the Power BI service](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-subscribe).

As far as I can tell this limitation has not been removed - could you look at adding it to the docs?

**Comment by maggiesMSFT** [comment]
Well, that's weird. I can see I added it in the PR https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/8206
but I see that it's not in the article now... 🤔
I'm readding it.
