### ISSUE TITLE
Required permissions not cited

### ISSUE THREAD

**Issue by gerardv** [MicrosoftDocs/powerbi-docs#3925]
The page does not indicate the permissions required to assign a workspace to a capacity. I would think the AAD role 'Power BI Administrator' would suffice, but a assigning this role to a co-worker did not grant him the ability to perform this action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f668ccc8-ab37-d274-956f-4fd2cda22d1a
* Version Independent ID: b66ff0c7-bb4c-afc8-0a70-6de73bf153fb
* Content: [Move your Power BI embedded analytics application to production - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/move-to-production)
* Content Source: [powerbi-docs/developer/embedded/move-to-production.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/move-to-production.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gerardv. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @gerardv. Thanks for your question. 
It says [here](https://docs.microsoft.com/power-bi/developer/embedded/move-to-production#assign-a-workspace-to-a-capacity-using-a-master-user) that the user must have admin permissions to that workspace, and _also capacity assignment permissions to that capacity_. Does the user also have capacity assignment permissions to that capacity?

**Comment by gerardv** [comment]
Thanks for your quick answer @mberdugo . I did read that part, but I thought it pertained to the embedding principal (master user vs service principal). We use a Service Principal for embedding but a AD Member Account for management tasks. This is not a Master User account such as is used throughout the embedding documentation.
Today I figured out that the Member Account indeed needs to be Capacity Administrator on the resource AND admin on the workspace. It's too bad you can't assign an AD group the Capacity Administrator role on the resource, but that's beyond the scope of my question.

I think it would be better if the documentation wouldn't mix up the Master User term that's used throughout the Power BI embedding docs, with the account that's performing setup and configuration here. They're different things imho.

Again, thanks for replying. My best,
Gerard.

**Comment by mberdugo** [comment]
Thanks for getting back to me, @gerardv. You're right, the wording here is a bit confusing. I'll update it to make it clearer.
