### ISSUE TITLE
Matrix and Table dataviews do not support Conditional Formatting. But I see that standard Matrix visual has option to set CF for  Cell Values.  Could you clarify or provide  code sample.

### ISSUE THREAD

**Issue by ConstructionProject** [MicrosoftDocs/powerbi-docs#3926]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3300d18-dfe1-a0a0-597e-2f5760924ca1
* Version Independent ID: 29fd380a-48fa-a99c-0e3a-4e3b314f99dd
* Content: [Conditional formatting in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/conditional-format)
* Content Source: [powerbi-docs/developer/visuals/conditional-format.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/conditional-format.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ConstructionProject. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @ConstructionProject. Thanks for your question, and sorry for the delayed response. I sent your question to the developers, and they said that matrix based custom visuals don’t support conditional formatting and we didn’t do anything explicit to support CF for cell values (though it might just be enabled by default).
I hope this clarifies things.
