### ISSUE TITLE
link to pbix file that is not complete

### ISSUE THREAD

**Issue by BobCreamer** [MicrosoftDocs/powerbi-docs#3927]
Open this [GitHub repo for Power BI Desktop samples](https://github.com/microsoft/powerbi-desktop-samples/blob/main/Sample%20Reports/Sales%20%26%20Returns%20Sample%20v201912.pbix)

This link takes me to a PBI file which misses out data so the drill through examples do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BobCreamer. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @BobCreamer, thanks for this input. I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks again!
