### ISSUE TITLE
iOS App json theme font not rendering

### ISSUE THREAD

**Issue by eyebelieve** [MicrosoftDocs/powerbi-docs#393]
When I set a font in the json theme file (in this case, Calibri) it renders correctly in the desktop tool and web app, but it does not render in the iOS app. 

I have research countless documentation, articles and blog posts and still have not found a solution for this - is there a reason this, is there a solution here?

*ipad and app are fully up to date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de4b72bf-f61d-1c51-24e7-535f4f19f85b
* Version Independent ID: bc9fa241-9606-65a0-038b-a05bc9af159a
* Content: [Get started with the Power BI mobile app for iOS - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-iphone-app-get-started#feedback)
* Content Source: [powerbi-docs/consumer/mobile/mobile-iphone-app-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-iphone-app-get-started.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @eyebelieve -- Thanks for contacting us! I'll check and get back to you.

**Comment by mshenhav** [comment]
Hey @eyebelieve, 
Not all fonts that are available on a Windows device, exist in iOS.
Can you please open the report in Power BI Web using Safari on your device to check if this is a font issue?

Maya

**Comment by mimig1** [comment]
@maggiesMSFT @mgblythe - There has been no response from the user, and Maya has provided follow up action. Can you close this?
