### ISSUE TITLE
Instructions re: Surrogate Keys with Index Column missing important information

### ISSUE THREAD

**Issue by stangeh** [MicrosoftDocs/powerbi-docs#3930]
The documentation regarding surrogate keys is missing a key piece of the instruction and therefore misleading/confusing.
The current doc says you can add an Index column directly to the dimension table while it still has non-unique values. However this would result in creating keys for values which are non-unique. 

So to make these instructions correct, they need to be updated to explain that _first_ you need a table of unique values. This can be achieved by creating a list from the column that will later be used as the key, then convert it to a table, remove duplicates, and _only then_ can you proceed with adding an index column, merging it to the fact table, etc. 

But if you don't specify that you need to first take steps to get a table with unique values, then adding Index is not going to fix the issue in the current documentation surrounding surrogate keys. 
Many thanks.

![Screenshot 2022-06-28 185853](https://user-images.githubusercontent.com/29489487/177869395-4c41063e-b01c-454c-b3ad-2004e2c93322.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 470ca67d-ed62-fbe0-85b2-6b1604f9f946
* Version Independent ID: e8c82d66-ad63-3efa-11b2-060b9b16d4ad
* Content: [Understand star schema and the importance for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/star-schema)
* Content Source: [powerbi-docs/guidance/star-schema.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/star-schema.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stangeh. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @stangeh - thanks for taking the time to provide feedback. The purpose of this section is to explain that a single unique column is required to create a model relationship and that a Power Query index column can help you create a surrogate key column. Your guidance isn't necessarily true should there be combinations of columns that result in a composite (multi-column) key.

**Comment by stangeh** [comment]
Hi Peter, thanks for your response. That’s true there are multiple ways to
achieve it. But in general the instruction is currently misleading because
it just says to add an index column and then merge.
Maybe you should say (or link to) what the options are for merging to make
it clear. (The question that also remains open with the current
documentation is: if I already merged the dimension and fact table, why do
I then need to set up a relationship afterward?)

Maybe this gets too specific for the purpose of introducing surrogate keys
as a use for Index Column, but if it’s only partially explained I find it
misleading.
