### ISSUE TITLE
What unit is Duration data type?

### ISSUE THREAD

**Issue by propellor** [MicrosoftDocs/powerbi-docs#3931]
[Enter feedback here]
After reading the description for the duration data type, I'm wondering what is the unit.  Is it a day?  

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b83479d4-0fb8-7500-e6ec-5559c4e2fdae
* Version Independent ID: 23b93f03-3ab9-d658-4243-89ebebbd6796
* Content: [Data types in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-types)
* Content Source: [powerbi-docs/connect-data/desktop-data-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-types.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your post, looks like this is a question best answered by the community or by support. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
