### ISSUE TITLE
Q&A Tooling on Composite Data

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3932]
This document mentions that Q&A Tooling is only supported in Import mode. But, based on testing, it also works on Direct Query data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63687608-fb0f-31f8-a1d2-dc35aa361f70
* Version Independent ID: 2e2cde8b-b59e-1577-4c43-6ad5cd7e2ef1
* Content: [Intro to Q&A tooling to train Power BI Q&A (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/natural-language/q-and-a-tooling-intro)
* Content Source: [powerbi-docs/natural-language/q-and-a-tooling-intro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/natural-language/q-and-a-tooling-intro.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rjagdon. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rjagdon, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
