### ISSUE TITLE
Need to remove(Exporting a Power BI report to file using the exportToFile API, isn't supported for Premium Per User (PPU)) from limitations

### ISSUE THREAD

**Issue by AkshayDutta** [MicrosoftDocs/powerbi-docs#3933]
<img width="474" alt="PPU" src="https://user-images.githubusercontent.com/108328248/177999606-e279b414-9179-4c30-91d3-af00cea80d7a.PNG">

Under limitations PPU workspaces need to be removed.

**Comment by KesemSharabi** [comment]
Hi @AkshayDutta,

This limitation is still in place. Why are you asking to remove it?

Thanks,

Kesem

**Comment by AkshayDutta** [comment]
Hello Kesem,

I can confirm using Power Automate flow user was able to export file from PPU workspace, hence under limitations this sentence is wrong.

Thank You.

Regards, Akshay Dutta, Power BI Support Engineer.

**Comment by KesemSharabi** [comment]
Hi @AkshayDutta,

Thank you for explaining your experience. I've asked the engineering team to look into this.

Kesem
