### ISSUE TITLE
Consolidate Information

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/powerbi-docs#3935]
The article below also talks about data molding data reduction techniques. 
https://docs.microsoft.com/en-us/power-bi/guidance/import-modeling-data-reduction

Can we consolidate the information into one place? At the moment I'm copy/pasting information from both articles to create an internal article for my future reference :).

Also, the journey that lead me to these articles resulted in a few other doc bug tickets. I wanted to reference them here as they are all related in some way. #3922, #3871

#### I have a dataset in a powerbi Pro Workspace. Which power bi premium capacity sku is needed to embed this report?

Also, I have lots of notes in #3922 that covers some of the information obtained through a support ticket created during this adventure  that I have not found covered in an existing article.

In case you're wondering, I am still searching for the answer to my planning question and will update #3922 as I learn more.

Apologies in advance if creating 3 separate doc issues was not the best approach.
-jon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38feecc0-9338-8359-5ce0-d2120c0b0004
* Version Independent ID: 96a236e6-2389-dc75-f5c5-4ead7dbd5c30
* Content: [Optimize Microsoft Power BI Premium capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-optimize)
* Content Source: [powerbi-docs/enterprise/service-premium-capacity-optimize.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-capacity-optimize.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jonwbstr. This issue has been assigned to the doc author for review.
