### ISSUE TITLE
Continuous vs Categorical could use more detail

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#394]
This page briefly mentions continuous and categorical, but it doesn't provide enough detail, or a link to more detail about them.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad604499-b845-44de-acc9-1bd9a7a97488
* Version Independent ID: f16079ec-98ee-e35d-f928-c5d493365051
* Content: [Customize X-axis and Y-axis properties - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-customize-x-axis-and-y-axis)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @chrisweis ,
I'll add more information to the document and republish.  Look for an update by next week.
Thanks for your feedback,
Michele
