### ISSUE TITLE
Power BI dataflows - DirectQuery / Live connection

### ISSUE THREAD

**Issue by heste023** [MicrosoftDocs/powerbi-docs#3940]
On this documentation page - https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources - for data sources P-R, Power BI dataflows, I believe that you can make a DirectQuery / Live connection to a Power BI dataflow (https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-directquery). If so, the DirectQuery / Live connection column for the Power BI dataflows row should be changed from "No" to "Yes." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @heste023. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! We've updated that article, thanks!
