### ISSUE TITLE
Add to paragraph - trigger scheduled refresh

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#3941]
Please add/change to [https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#usage-metrics-report-dataset](url)

**From**:
When you first launch the improved usage metrics report, Power BI automatically creates a Usage Metrics Report dataset. The improved usage metrics report relies on that dataset. Power BI then refreshes this dataset daily. While you can't change the refresh schedule, you can update the credentials that Power BI uses to refresh the usage metrics data. You may need to resume scheduled refresh if the credentials expired, or if you removed the user who first launched the usage metrics report from the workspace where the dataset resides.

**To**:
When you first launch the improved usage metrics report, Power BI automatically creates a Usage Metrics Report dataset. The improved usage metrics report relies on that dataset. Power BI then refreshes this dataset daily. While you can't change the refresh schedule, you can update the credentials that Power BI uses to refresh the usage metrics data. You may need to resume scheduled refresh if the credentials expired, or if you removed the user who first launched the usage metrics report from the workspace where the dataset resides. **To trigger scheduled refresh simply open the Usage metric report. In case of issues, you may need to delete the dataset - see**  [https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#troubleshoot-refresh-issues](url)

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in the new modern workspaces (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @MartinaPoddana -- thanks for your comment. Please see the email I sent you, about how to edit and submit suggested changes yourself 😉
