### ISSUE TITLE
Datamarts are currently not supported in Microsoft Teams

### ISSUE THREAD

**Issue by rjagdon** [MicrosoftDocs/powerbi-docs#3943]
Based on testing, you can add Power BI report to a Teams Channel even if the data source is Power BI Datamart. The limitation - Datamarts are currently not supported in Microsoft Teams does not seem to be true anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589a83ac-1fda-b3f1-1590-9372d97cf132
* Version Independent ID: 589a83ac-1fda-b3f1-1590-9372d97cf132
* Content: [Administration of datamarts (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-administration)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-administration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-administration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rjagdon. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we've updated that article.
