### ISSUE TITLE
Connecting data from Teams PowerBI App not working

### ISSUE THREAD

**Issue by rmbuan** [MicrosoftDocs/powerbi-docs#3946]
Hello,

I tried to connect the data to our Tennant using OAuth2 via the Teams PowerBI App but every time it opens the web browser (Edge or Chrome) with a popup disabled it completely closes the preview.powerbi.com link. I tried adding both powerbi.com and microsoftonline.com still doesn't work.

Performing the data connection on a browser directly on the powerbi website works.

rmbuan

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rmbuan. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @rmbuan. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
