### ISSUE TITLE
SAP HANA related information in section "How to enable the feature" needs review

### ISSUE THREAD

**Issue by lesliemui** [MicrosoftDocs/powerbi-docs#3947]
When connecting to HANA, the Options -> Current File -> DirectQuery sections are now missing.

The SAP Variables box is visible in the Options -> Current File -> Published dataset settings section:
![image](https://user-images.githubusercontent.com/105888646/179088392-495842e7-c81c-4516-9161-3082e7a58267.png)

documentation update required to match the options menu if this is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea9c21b0-3583-2744-5a5f-9401b791821c
* Version Independent ID: f8432546-d080-97aa-7b15-7c456f0e5a12
* Content: [Edit SAP variables in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-edit-sap-variables#requirements-for-sap-edit-variables)
* Content Source: [powerbi-docs/connect-data/service-edit-sap-variables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-edit-sap-variables.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lesliemui. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for submitting this, the article is under review for updates.
