### ISSUE TITLE
Warning Message about free trial version in embedded report

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [MicrosoftDocs/powerbi-docs#3948]
For the last few days, we are seeing the following warning message in our embedded reports on the web app. We never saw this warning before. How can we remove this warning message? We are using the service principle approach to embed the report, and people log in through Azure Active Directory into the web app. All users are assigned pro licenses.

![image](https://user-images.githubusercontent.com/30843127/179115733-893756a5-9073-4daa-97eb-3d34f35c6f7c.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sanjaydatasciencedojo. This issue has been assigned to the doc author for review.

**Comment by fenix2222** [comment]
Having the same problem. Any solution?

**Comment by KesemSharabi** [comment]
Hi @sanjaydatasciencedojo and @fenix2222,

Are you using a [free trial](https://azure.microsoft.com/pricing/details/power-bi-embedded/)? If so, it looks like the free trial tokens expired. As soon as you purchase a capacity the message will disappear.

![image](https://user-images.githubusercontent.com/54834915/180010063-02bbfb7d-e24d-4261-a84e-c99da799979d.png)

For more information see:
* [How many embed tokens can I create?](https://docs.microsoft.com/power-bi/developer/embedded/embedded-faq#how-many-embed-tokens-can-i-create-)
* [Capacity and SKUs in Power BI embedded analytics](https://docs.microsoft.com/power-bi/developer/embedded/embedded-capacity)

Hope this helps,

Kesem

**Comment by sanjaydatasciencedojo** [comment]
Email from MIcrosoft Support

*** 
"This is a free trial version, to remove this label, a capacity must be purchased".

This notification banner was recently enabled. Its purpose is to notify customers that they are embedding using the free trial tokens for authentication. If the customers seeing these messages are using free trial tokens ( without using a Premium capacity ) then this is expected.

Each tenant/user gets a limited amount of Free tokens where a user can embed the Power BI Reports without a Premium Capacity. If this scenario has very low usage (less than ten embeds per day), it could have worked for a year - but once the pool is exhausted, all embed attempts will fail.


The motivation for this notification was to help customers realize they are not using a dedicated Premium Capacity and to avoid an unexpected outage once the last token is used (this happened several times when customers did not realize they were using up tokens and had experienced a sudden outage).

 
Therefore, the Product team introduced this notification to let the Customers know that they are using Free tokens and you would need a Premium capacity to avoid any outages. We strongly recommend upgrading to Premium capacity once you move to Production.

***

**Comment by lankaapura** [comment]
@sanjaydatasciencedojo  do we need to buy dedicated capacity? or getting a PPU license for the user who creating the workspace and building reports is enough?
