### ISSUE TITLE
Need further information on one limitation

### ISSUE THREAD

**Issue by nstraw** [MicrosoftDocs/powerbi-docs#3949]
Hi doc team!

Would it be possible to elaborate on this limitation : "A filter can only touch a table once. Applying the same filter to a table twice, through one of more tables outside of the DirectQuery source, isn't supported."

We want to reproduce the issue, but we do not understand it... What do you mean by a filter "touching" a table ? How a filter can be applied twice to a table ? Could you maybe provide a example ? That would be very much appreciated :)

Thanks for your help with this.

Kindly,

Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b13312-84ac-72b4-483f-5d8169ecf1e0
* Version Independent ID: f648e18b-55f9-9167-a6f1-98be8180bac1
* Content: [Using DirectQuery for datasets and Analysis Services (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-datasets-azure-analysis-services.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nstraw. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post and question, this sounds like a technical and feature question best answered by the community or support. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by nstraw** [comment]
Hi, thanks for your message. 

I can confirm it is not a technical or a feature question. It concerns the "Considerations and limitations" section and the limitation stated in the documentation as "A filter can only touch a table once. Applying the same filter to a table twice, through one of more tables outside of the DirectQuery source, isn't supported." This sentence is not comprehensible as is, it needs to be clarified.

Community or support won't be able to help.
