### ISSUE TITLE
Logical operators in Quick Measures

### ISSUE THREAD

**Issue by avnish19** [MicrosoftDocs/powerbi-docs#395]
Wondering if Logical Operators (AND, OR, XOR, NOT) would be part of the Quick Measures calculations?
It would be helpful to be able to process a list of input of "true/false" and "yes/no" values into a summarized format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0614115b-602d-cab2-307e-618f6a3dbd2f
* Version Independent ID: 09e23d6d-c1f8-ca45-3ad0-47a6ff5ec213
* Content: [Use Quick measures to easily perform common and powerful calculations in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quick-measures)
* Content Source: [powerbi-docs/desktop-quick-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quick-measures.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @avnish19 
That's a good question.  I've forwarded it to the author who will get back to you soon.
Take care,
Michele

**Comment by davidiseminger** [comment]
Adding another assignee to look into this question.

**Comment by MI77** [comment]
It's a good suggestion, but not available in the product today. You can submit it on ideas.powerbi.com if you want.

#please-close @mgblythe
