### ISSUE TITLE
We need an example for how to create the rule in the 'Affordability' example

### ISSUE THREAD

**Issue by jamesjohns01** [MicrosoftDocs/powerbi-docs#3950]
There is no example for how to create the rule in the 'Affordability' example.  I want to do exactly the same thing with dates but can't seem to do it.  An example would be very helpful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Apply conditional table formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jamesjohns01. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post and question, this sounds like a request / question best answered by the community or support. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
