### ISSUE TITLE
Dashboard directly from dataset?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#3954]
This page states that one can create a dashboard from a dataset, but this doesn't seem to be documented anywhere, nor do I see an option in the service to pin directly from a dataset to a dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88b71635-b53c-d810-b40a-8c67ae1edba0
* Version Independent ID: 8de35da5-401a-7834-11de-7f4e8af35ca9
* Content: [Intro to dashboard tiles for Power BI designers - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-dashboard-tiles?source=docs)
* Content Source: [powerbi-docs/create-reports/service-dashboard-tiles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-dashboard-tiles.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @otravers -- good catch! I've updated the article to remove "dataset." Change should be live later today, Mon July 18.
