### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by gabycasale** [MicrosoftDocs/powerbi-docs#3955]
Hi,

The purpose of this feedback is to inform some documentation inconsistencies demonstrated by a customer who has Azure Private Link enabled, and had the following observations:
•	Capacity Metrics App is working fine, even though documentation indicates it shouldn´t. 
•	Export to PDF and Power Point is working fine, even though documentation indicates it shouldn´t. 
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gabycasale. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your clarifications! We'll update the article to reflect the behavior.
