### ISSUE TITLE
Pls check if Dataflow supports connect to MariaDB 

### ISSUE THREAD

**Issue by Maggie18z** [MicrosoftDocs/powerbi-docs#3956]
[Enter feedback here]
Pls check if Dataflow supports connect to MariaDB. In this page it says not supported. But in Power Query doc it says supportive. https://docs.microsoft.com/en-us/power-query/connectors/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources#data-sources-m-o)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Maggie18z. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hi there, in the article you reference it shows that MariaDB is _not_ supported, and is consistent in the Power BI article.
