### ISSUE TITLE
Export to File for Power BI Reports -  Export Format

### ISSUE THREAD

**Issue by Nickelodeon111** [MicrosoftDocs/powerbi-docs#3958]
In 'Export to File for Power BI Reports'
You select the desired Export Format for your Power BI report, can you add 'csv' and 'excel' as export format option ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @Nickelodeon111, is this a suggested product improvement? If so the best route for your input is to suggest it as an idea on https://ideas.fabric.microsoft.com/ideas/search-ideas/?q=Power%20Automate. In any event, I am going to close this issue now, but feel free to reopen if you need further assistance.
