### ISSUE TITLE
But why?

### ISSUE THREAD

**Issue by Quorthon1965** [MicrosoftDocs/powerbi-docs#3959]
Why would you want to do this, when Power BI reports can already have multiple pages. This page does not explain the purpose very well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd025cf2-076c-996e-4928-a16c8b340ea6
* Version Independent ID: aff5d091-7be0-1845-8fdf-4b87787dc9b3
* Content: [Power BI Report Builder - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/report-builder-power-bi)
* Content Source: [powerbi-docs/paginated-reports/report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Quorthon1965. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Quorthon1965 -- a reasonable question! I've added more info to the article. The update will be live tomorrow afternoon July 21 Pacific Time. In the meantime, check out another article, https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi, for more info now.
