### ISSUE TITLE
First line under Considerations and troubleshooting is an incomplete sentence

### ISSUE THREAD

**Issue by karmamule** [MicrosoftDocs/powerbi-docs#396]
The first bullet point in this section is "When using the in operator, the values to the right of in must be either a comma-separated list enclosed in parentheses.".

It uses the word "either" implying there will be two or more options, yet only one option is listed. Either remove 'either', or provide the second option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
@karmamule 
Good catch!  I've assigned this to the author who will get back to you shortly.
Take care,
Michele

**Comment by maggiesMSFT** [comment]
Good catch indeed, @karmamule! I'll check and let you know. Thanks for the eagle eye!

**Comment by maggiesMSFT** [comment]
I got an answer, @karmamule , and I'll update the doc shortly. The answer is, delete "either." So the sentence should read: "When using the in operator, the values to the right of in must be a comma-separated list enclosed in parentheses." Thanks so much for asking!

**Comment by maggiesMSFT** [comment]
OK, just checked in the fix. Should be live later today. Thanks again, @karmamule !
