### ISSUE TITLE
Single Sign On - Include Azure Databricks

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#3961]
Azure Databricks is not listed in the Single Sign On (SSO) list for data sources and that has been available for quite a while now. https://docs.microsoft.com/en-us/azure/databricks/integrations/bi/power-bi

"You can also publish Power BI reports to the Power BI service and enable users to access the underlying Azure Databricks data using single sign-on (SSO), passing along the same Azure Active Directory credentials they use to access the report."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the clarifications, I've updated the article.
