### ISSUE TITLE
Documentation Feedback

### ISSUE THREAD

**Issue by electrifiedg** [MicrosoftDocs/powerbi-docs#3965]
Hi,

The purpose of this feedback is to inform some documentation typos:

>Power BI ignores some format changes of existing columns. For example, if you change a column’s format from 0.25% to 25%. 

The example should say "from 0.25 to 25%"

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/create-reports/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-upload-desktop-files.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @electrifiedg. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good catch! Thanks for that, I've updated the article.
