### ISSUE TITLE
Profiler advice is outdated and potentially just wrong

### ISSUE THREAD

**Issue by chandleya** [MicrosoftDocs/powerbi-docs#3966]
SQL Profile is deprecated and not supported on Azure SQL at all. This content should be revised with advice on extended events or point to extended event documentation, preferably a location with detailed explanations for Azure SQL. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 683b70c5-16bc-6d10-0433-a39a6be16995
* Version Independent ID: 9d664ac7-b484-3b5f-f215-613f95fe60ec
* Content: [Monitor report performance in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/monitor-report-performance)
* Content Source: [powerbi-docs/guidance/monitor-report-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/monitor-report-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by peter-myers** [comment]
Hi @chandleya - this article is about using SQL Server Profiler to trace SQL Server and Analysis Services workloads. It's not about tracing Azure SQL Database workloads.
