### ISSUE TITLE
Update the "Considerations and limitations" section of the article

### ISSUE THREAD

**Issue by timplMSFT** [MicrosoftDocs/powerbi-docs#3967]
Under the "Considerations and limitations" section at the bottom of this page it says the following:

When using Power Automate to export a paginated report that's larger than 20 MB, it's likely that the export will fail.

This seems inaccurate based on my testing and my customer's (Accenture) testing as we've been able to consistently report exports of well over 20MB (up to 100MB) to successfully export via Power Automate. Accenture opened a support case on this (2207150040005255) and were told that the size limit is actually 250MB but that some reports can fail at much smaller sizes so the recommendation is to add retry logic into your Power Automate flow. For that reason I feel like better wording to the above limitation could help avoid customer confusion like Accenture has had - something such as:

Using Power Automate to export a paginated report that's larger than 20MB may fail so it is recommended to add retry logic to the flow in that scenario in case of failure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d01510-7ea5-3556-00c1-de77f551081d
* Version Independent ID: c5ec0e49-a288-8948-8a87-284bc2d59015
* Content: [Export paginated reports with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-paginated-integration)
* Content Source: [powerbi-docs/collaborate-share/service-automate-paginated-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-paginated-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @timplMSFT. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @timplMSFT, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
