### ISSUE TITLE
Outdated Power BI Formatting UI

### ISSUE THREAD

**Issue by arkansang** [MicrosoftDocs/powerbi-docs#3968]
The Format Page icon has changed/moved in a recent Power BI update

![image](https://user-images.githubusercontent.com/48665866/180897194-8e9cf537-f810-4457-aa85-71887393c7d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @arkansang. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out to me, @arkansang. I'll try to update the tutorial when I can.

**Comment by mberdugo** [comment]
The screenshots for the tutorial have been updated. Thanks again.

**Comment by arkansang** [comment]
No worries, thanks for updating :)
