### ISSUE TITLE
Is it possible to do Grouping in Direct Query with more than 10 groups

### ISSUE THREAD

**Issue by NV2601** [MicrosoftDocs/powerbi-docs#3969]
I tried creating more than 10 groups in Direct Query, But Power BI does not allow to create more than 10 Groups.
Is there any way i can create more than 10 groups on my data column which is using Direct Query ?

Any permissions which Admin can update and change this limit to more than 10 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1e0b0a-ff95-b2f7-44db-5c07ca876ab4
* Version Independent ID: 1c975595-bf44-5f66-3e08-02c3e8e63797
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/create-reports/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @NV2601. This issue has been assigned to the doc author for review.

**Comment by MarkusFra** [comment]
Is there any update to this? I am running into the same issue. 10 is a ridiculously low limit for the number of groups.

**Comment by davidiseminger** [comment]
Thanks for your post and question, this sounds like a technical and feature question best answered by the community or support. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
