### ISSUE TITLE
Paginated Reports in Power BI Service

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#397]
@mpoeckl commented on [Tue Nov 06 2018](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/3)

According to the list, paginated reports are not available in Power BI Service. While the feature is still in preview for the Power BI Service, it is possible to publish SSRS reports to Power BI Service... Therefore "No" should change to "In preview".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Vergleich zwischen Power BI-Berichtsserver und Power BI-Dienst - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by CeciAc** [comment]
Hi team, 
I copying this here since the user is reporting an inaccuracy in the service documentation
Kind regards,
Microsoft DOCS International Team

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc and @mpoeckl -- Wow, @mpoeckl, you are way out in front! We haven't even officially released the preview of paginated reports in the Power BI service, but coming so so soon! And I promise, when we do, I'll fix this list. 
Thanks for keeping us honest!

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc and @mpoeckl -- the product has caught up with you, and so has the article. Thanks for keeping us honest!
