### ISSUE TITLE
Using A1-A3 for Export Power BI paginated reports with Power Automate

### ISSUE THREAD

**Issue by scottyoleary** [MicrosoftDocs/powerbi-docs#3971]
Hello!

My question is whether we can use A1-A3 SKUs to deploy a solution like this for a client.  The "Prerequisites" section states that this solution must use A4-A6 (or P SKUs).  I have tested this with A1 and it worked fine.  Please let me know any feedback you have on this.  Thank you!

![image](https://user-images.githubusercontent.com/58477891/181367969-863aa182-420a-4dc9-842e-3037706f0f04.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9d01510-7ea5-3556-00c1-de77f551081d
* Version Independent ID: c5ec0e49-a288-8948-8a87-284bc2d59015
* Content: [Export paginated reports with Power Automate - Power BI](https://docs.microsoft.com/en-us/power-bi/collaborate-share/service-automate-paginated-integration)
* Content Source: [powerbi-docs/collaborate-share/service-automate-paginated-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-paginated-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @scottyoleary. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @scottyoleary, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!

**Comment by thuynga2706** [comment]
Is it still working? I have the same question why it's specified it's supported from A4 SKUs
