### ISSUE TITLE
Missing the scenarios of adding visuals from file / app source and other

### ISSUE THREAD

**Issue by vajnorcan** [MicrosoftDocs/powerbi-docs#3972]
One of the questions we have is that what happens to the Certified Visual that's been added to the OrgLibrary via AppSource (via reference so the updates are automatically propagated) when this visual is removed from the AppSource by developer !?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746e3f8f-68fd-b7d2-f61e-6bb8daa63ea4
* Version Independent ID: 50a481ef-6d50-cec0-e21b-2deab73e73b3
* Content: [Organization visuals in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization#feedback)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vajnorcan. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @vajnorcan. I don't know the answer to that, but I'll ask and get back to you.

**Comment by mberdugo** [comment]
Hi, @vajnorcan. The answer I got to your question is that as long as we don’t remove it from Power BI internal deployment, the visual will render as it did prior to it being delisted from AppSource.
We usually don’t deprecate from internal deployment. 
I'll add this information to the doc.
Thanks again for your question and helping us improve our documentation.
