### ISSUE TITLE
Clarify support (or not) for "Virtualized Environment"

### ISSUE THREAD

**Issue by SvenAelterman** [MicrosoftDocs/powerbi-docs#3976]
This page, under the heading "Installing Power BI Desktop on remote machines", contains this statement: "Power BI Desktop is not supported in Virtualized Environment (eg. Citrix)."

This statement needs clarification. Does this refer to application layering/virtualization, or to technologies like RemoteApp, or to any kind of virtual machine?

On a smaller note, the sentence needs some grammar/typo corrections: "Power BI Desktop is not supported in a Virtualized Environment (e.g., Citrix)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop#installing-power-bi-desktop-on-remote-machines)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by SvenAelterman** [comment]
Further clarification that would be helpful is whether Power BI Desktop is supported in a multi-session scenario like AVD.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SvenAelterman. This issue has been assigned to the doc author for review.

**Comment by Austinlsink** [comment]
When can we expect more information on this article note?

**Comment by davidiseminger** [comment]
Thanks for your post and question. I've updated the note and improved / fixed the grammar.

On whether a given virtual environment may work, the note states that virtual environments are not supported. However, you might check with the community or support if you have a specific scenario in mind. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
