### ISSUE TITLE
Libreria de datos

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#398]
@augusmendoza commented on [Tue Nov 06 2018](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/14)

Deberian tener librerias de datos para seguir los mismos ejemplos y hacer mas practico el curso

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Obtención de datos - Power BI](https://docs.microsoft.com/es-es/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr.es-ES/blob/live-sxs/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hi Team, 
The user made a suggestion to the documentation.
Backtranslation: _You should have data libraries to follow the same examples and make the course more practical_

**Comment by davidiseminger** [comment]
Thanks for your comment, @CeciAc - we anticipate adding sample data and libraries in the future of some of these courses, for that very reason. Thanks!
