### ISSUE TITLE
Unable to update Tracking Cycle following directions

### ISSUE THREAD

**Issue by alp13** [MicrosoftDocs/powerbi-docs#3981]
Directions and screenshot for updating the tracking cycle do not seem to be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12ac2aa1-b899-184c-10c3-7909aa32bff8
* Version Independent ID: 17e2b2b8-02c5-fcf0-32ab-7f3ef2eb271f
* Content: [Create scorecards and manual metrics - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-create)
* Content Source: [powerbi-docs/create-reports/service-goals-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-create.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies*
![screenshot](https://user-images.githubusercontent.com/13023676/182198380-93061a4e-288b-44a4-aa9f-893d6082c82f.png)
*

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alp13. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @alp13, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here now. Thanks for providing your feedback!
