### ISSUE TITLE
Documentation Error in Page Navigation API

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [MicrosoftDocs/powerbi-docs#3983]
Hi, refer to link: [https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/page-navigation](https://docs.microsoft.com/en-us/javascript/api/overview/powerbi/page-navigation)

Where it is written

```
report.on('pageChanged', event => {
    const page = event.details.newPage;
    console.log(page.name);
});
```

should be

```
report.on('pageChanged', event => {
    const page = event.detail.newPage;
    console.log(page.name);
});
```

The correct property name is `detail`, not `details`.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FelipeCostaGualberto. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @FelipeCostaGualberto,

I'm looking into this.

Thanks for your comment,

Kesem

**Comment by KesemSharabi** [comment]
Hi @FelipeCostaGualberto,

Thank you for spotting this typo and for letting us know.

After confirming with the engineering team, I changed `event.details.newPage` to `event.detail.newPage` in [Add an event handler](https://docs.microsoft.com/javascript/api/overview/powerbi/page-navigation#add-an-event-handler).

Thanks again for getting involved!

Kesem
