### ISSUE TITLE
The Figure and the Description of the Gauge charts section don't match

### ISSUE THREAD

**Issue by JennaW666** [MicrosoftDocs/powerbi-docs#3987]
[Enter feedback here]

Hi,

The Figure and the Description of the Gauge charts section don't match. 
[https://user-images.githubusercontent.com/110555152/182658019-26b859d3-9954-4680-9653-0cd0fe6944d4.png](url)
[https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a#gauge-charts](url)

Likely the wrong Figure is embedded in the webpage, because everything looks good if you forward to the external click (For more information, see Gauge Charts in Power BI) at the bottom of the Gauge charts section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69212c7b-4492-a044-a07b-05266b20e370
* Version Independent ID: cc3d001b-1d58-b3b5-62a6-95f3955bf733
* Content: [Visualization types in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a#gauge-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JennaW666. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @JennaW666 @bishalgoswami ,
Thank you for noticing this and bringing it to our attention.  The documentation has been updated and set to republish tomorrow.
