### ISSUE TITLE
Zendesk App able to write

### ISSUE THREAD

**Issue by MadPacUte** [MicrosoftDocs/powerbi-docs#3988]
Hi, 

I was having one of our admins try to connect data to the Zendesk template app. However, it states that the application would be able to read data and WRITE data. I just want to understand why they would need write access. If that is a recent change or at least update the screenshot to include this for future users. 

Thanks,

Randall Madsen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2231f5c7-c73c-0b80-d6b9-5adf207a6b62
* Version Independent ID: 91e7c633-83d4-0714-e92f-e3f169549bd5
* Content: [Connect to Zendesk with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-connect-to-zendesk#system-requirements)
* Content Source: [powerbi-docs/connect-data/service-connect-to-zendesk.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-zendesk.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MadPacUte. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @MadPacUte, thanks for your inquiry. I am checking and will get back to you.

**Comment by ivanosevitch** [comment]
I can't access at all to the Zendesk app on my side (https://github.com/MicrosoftDocs/powerbi-docs/issues/4601)

**Comment by paulinbar** [comment]
Hi @MadPacUte, sorry for the extremely late reply. In your comment, you say " However, it states that the application would be able to read data and WRITE data". Could you tell me where you see that statement? I tried to reproduce, but didn't manage to see any reference to WRITE.  Thanks!

**Comment by MadPacUte** [comment]
When I installed the App from the AppSource and tried connecting the data, there is a prompt that shows up: 
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/25181724/7bdca2be-7d5d-47da-bd5b-0de7a6fdfc66)
However, in the documentation it shows a different screen that looks like it is only read: 
https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-to-zendesk

**Comment by paulinbar** [comment]
Hi @MadPacUte, I haven't heard back from the product team yet. I am still trying to track someone down who can shed some light on this, but in the meantime I have updated the documentation to show the screen you shared. I myself can't get that far in the installation process. If I get more info about why both read and write access is necessary, I'll update the doc if necessary. In any event, I am going to close this github issue now. Please feel free to comment or reopen. Thanks!
