### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by tolarianNZ** [MicrosoftDocs/powerbi-docs#3990]
Duplicate letter "A" under "Planning your capacity size in advance" section, last paragraph, 5th sentence.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/32700672/182755418-e2a31eb4-22d9-4d96-afaa-a1efb8ece273.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Version Independent ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Content: [Manage Microsoft Power BI Premium Gen2 capacities - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-manage-gen2)
* Content Source: [powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tolarianNZ. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @tolarianNZ,

Thank you for spotting this typo and for letting us know.

The typo was fixed - see [Planning your capacity size in advance](https://docs.microsoft.com/power-bi/enterprise/service-premium-capacity-manage-gen2#planning-your-capacity-size-in-advance).

Thanks again for getting involved.

Kesem
