### ISSUE TITLE
Need a table to summarize options

### ISSUE THREAD

**Issue by gfawcett1** [MicrosoftDocs/powerbi-docs#3992]
It would help this documentation if it summarized the functionality and licensing requirements of the different home/guest combinations -- something like this:  

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/gefawcet/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/gefawcet/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Home   Tenant | Guest Tenant | Viewing in Portal | Viewing   Embedded (user-owns data) | Viewing Shared   Links | Create/Modify   Content | Licensing Req's
-- | -- | -- | -- | -- | -- | --
Commercial | Commercial |   |   |   |   |  
Commercial | GCC |   |   |   |   |  
GCC | Commercial |   |   |   |   |  
GCC | GCC |   |   |   |   |  
etc. |   |   |   |   |   |  

</body>

</html>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b#cross-cloud-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gfawcett1. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @gfawcett1, thanks for your suggestion. I will bring it to the attention of the feature team to see if we can put something like you suggest into the documentation. Thanks again!

**Comment by paulinbar** [comment]
Hi @gfawcett1, I have sent your suggestion to the product team for consideration, so in the meantime I will close this issue. Thanks for taking the time to give us your feedback!
