### ISSUE TITLE
Bind to parameter option is not available

### ISSUE THREAD

**Issue by sergordon** [MicrosoftDocs/powerbi-docs#3993]
Hi, I see that this document is updated (Article 06/17/2022), how ever I am unable to get the dynamic M parameter works, even following step by step this document. I dont have Bind to parameter option. I have PBI Version: 2.107.841.0 64-bit (july 2022)

It is a valid document? Do I missing something than is not writed in the document?

I'll really appreciate any help.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sergordon. This issue has been assigned to the doc author for review.

**Comment by ekiragu** [comment]
I am experiencing the same issue, I can not see the feature to Bind Parameters on the Advanced Tab as illustrated on the document above

**Comment by sanjana-sampath-kumar** [comment]
I'm facing the same issue currently.  I have PowerBi desktop August release(2.108.997.0 64-bit (August, 2022)) and trying to implement date picker to fetch data dynamically using KQL query, but unable to find the Bind to parameter option.

**Comment by luisvalleGH** [comment]
Same issue. I have PowerBi desktop 2.108.997.0 64-bit (agosto de 2022) and trying to implement date picker to fetch data dynamically using an API query, but unable to find the Bind to parameter option.

**Comment by cbeible** [comment]
Same issue. Power BI desktop 2.108.997.0 64-bit (August 2022). Bind To Parameter option is missing.

**Comment by gutweniger** [comment]
Version: 2.109.1021.0 64-bit (September 2022)
Bind to parameter option is also missing here.

**Comment by kaysunda** [comment]
I am using sql server as a source with direct query i am not getting Bind to parameter option. any idea or inputs please

**Comment by davidiseminger** [comment]
Hello all, sorry for the issues you're experiencing. The article is correct, so it may be one of the exclusions (described toward the bottom of the article). You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

If the overall community finds a discrepancy with this article, please post again and we'll bring it up with engineering.
