### ISSUE TITLE
Data Source for the Exercise has Changed

### ISSUE THREAD

**Issue by UristMcFarmer** [MicrosoftDocs/powerbi-docs#3996]
The data source for this exercise (https://www.bankrate.com/retirement/best-and-worst-states-for-retirement) has changed and required columns no longer exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @UristMcFarmer. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks, we've updated that article with new guidance.
