### ISSUE TITLE
PowerBI Admin API access - Successful OAuth authentication, followed by 403 : Forbidden

### ISSUE THREAD

**Issue by Acteon-Jon** [MicrosoftDocs/powerbi-docs#3997]
I hope you can assist;
I've followed the steps here repeatedly, with the intention to access the Power BI **read-only** Admin API's via a CData REST connector (within a Data Warehouse application).

Each time I can use the ServicePrincipal to authenticate (wtih Client Secret) against; https://login.microsoftonline.com/59c9ee96-c521-4815-aabd-bd304a261708/oauth2/token
Each time the token received is used to access data at the endpoint; "https://api.powerbi.com/v1.0/myorg/admin/reports?$top=100" the response is a 403 forbidden.

The endpoint "https://analysis.windows.net/powerbi/api" is noted in many forums, but that always fails with "no such host".

I've made the same attempts via web.postman.co with the same results.

The 403 error seems to indicate an obvious lack of permissions, but the steps listed in your guide don't say to assign any, and my assumption is that the Security Group (with SP as member) is provided permissions to the Power BI Admin API's in an automated fashion, in the background.  I left the configuration for 48 hours, with no change.

Where you state; "The application's permissions are then managed through the Power BI admin portal." no doubt because the preceding steps state not to have any AAD permissions assigned (or indeed any PowerBI Admin Roles), then what additional permissions (aside from enabling the option "Allow ServicePrincipals to access Admin APIs") would be required, and should they be set against the SP, or against the Security Group assigned in the Power BI Admin portal to the "Allow SPs to access Admin APIs"?

Thanks in advance,

Jon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Version Independent ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Content: [Enable service principal authentication for read-only admin APIs - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Acteon-Jon. This issue has been assigned to the doc author for review.

**Comment by Acteon-Jon** [comment]
Thanks @bishalgoswami much appreciated.
Hi @paulinbar - I'm not sure where this falls on your to-do list, not high-up I suspect (!) but would you be able to give any indication of timeframe for me?
Thanks in advance,
Jon.

**Comment by paulinbar** [comment]
Hi @Acteon-Jon, thanks for your question. Let me check with the people I worked with when I wrote the article. Hopefully they'll either be able to help or at least point you in the right direction.
In the meantime you might try the [Power BI Community](https://community.powerbi.com), or the [Power BI support page](https://support.powerbi.com)

**Comment by paulinbar** [comment]
Hi again @Acteon-Jon. The answer I got back is that they suspect your Power BI tenant admin might not have enabled the feature switch for this ability, but without knowing a specific request ID it's hard to know for sure. They rechecked the documentation and it looks ok to them. They said the best thing to do is to contact Power BI support and they'll help you figure it out.

Hope this helps. In the meantime I will close this issue here now as this is a documentation channel and at this point it doesn't look like this is a documentation issue. If the support engineer thinks we need to enhance the documentation, they will get back to me.
Thanks for reaching out!
