### ISSUE TITLE
Web.Contents failed to get contents from 'https://api.tiingo.com/tiingo/daily/FB' (404): Not Found

### ISSUE THREAD

**Issue by RodrigoRibeiro1995** [MicrosoftDocs/powerbi-docs#3998]
[Enter feedback here]
How can I edit this App so I can fix what appears to broken ticker - I believe FB changed to META recently and this has been broken for a few days now:

Web.Contents failed to get contents from 'https://api.tiingo.com/tiingo/daily/FB' (404): Not Found.

![image](https://user-images.githubusercontent.com/33553521/183921078-a6dfd628-354f-47cd-aa20-05e39519716a.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RodrigoRibeiro1995. This issue has been assigned to the doc author for review.
