### ISSUE TITLE
Need to add premium capacity Gen 2 within document.

### ISSUE THREAD

**Issue by AkshayDutta** [MicrosoftDocs/powerbi-docs#3999]
[Hello Team, can you please add Power BI premium capacity Gen 2 within this document]

Photos attached 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/108328248/183949380-f83579cc-f2ac-42b9-b650-720878a201ff.png)
<img width="486" alt="Capture" src="https://user-images.githubusercontent.com/108328248/183949514-ef91a154-b531-4a65-875b-5c0f237b1a0d.PNG">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for reports and dashboards in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe?tabs=creator#requirements)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AkshayDutta. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @AkshayDutta , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
