### ISSUE TITLE
How does this license function

### ISSUE THREAD

**Issue by Jacob-Strickland** [MicrosoftDocs/powerbi-docs#400]
I'm looking for more information regarding the POWER_BI_PRO license and what it includes exactly.
From the following documentation (https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/licensing-service-plan-reference) I am able to see that it includes a BI_AZURE_P2 (70d33638-9c74-4d01-bfd3-562de28bd4ba) license, however I am unable to find anything regarding that specific license.

Does the BI_AZURE_P2 function similarly to the regular AAD_PREMIUM_P2 licenses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d7c8609-4a9a-2a7b-5533-fd9684ae5fc6
* Version Independent ID: c8bb1362-f519-e0f7-a85d-d46dd06c1b15
* Content: [Purchase and assign Power BI Pro licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-purchasing-power-bi-pro)
* Content Source: [powerbi-docs/service-admin-purchasing-power-bi-pro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-purchasing-power-bi-pro.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @Jacob-Strickland.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by KayUnkroth** [comment]
Hi Jacob, a Power BI Pro license is an individual license that allows access to all content and capabilities in the Power BI service. It is not an AAD license. For more information, see https://powerbi.microsoft.com/en-us/pricing/.

**Comment by mgblythe** [comment]
@Jacob-Strickland - closing this based on Kay's response.

**Comment by eliasjd** [comment]
No puedo obtener la licencia del Power Bi Pro, Que tengo que hacer?
