### ISSUE TITLE
issue is fixed

### ISSUE THREAD

**Issue by lbendlin** [MicrosoftDocs/powerbi-docs#4000]
connection owners can now perform the expected actions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50beda6a-7bfb-7a1a-72de-ca434c1eccbd
* Version Independent ID: 50beda6a-7bfb-7a1a-72de-ca434c1eccbd
* Content: [Known issue - Gateway data source owners can't update data source credentials - Power BI](https://docs.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-220-gateway-data-source-owners-cant-update-credentials)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-220-gateway-data-source-owners-cant-update-credentials.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-220-gateway-data-source-owners-cant-update-credentials.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lbendlin. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @lbendlin , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
