### ISSUE TITLE
Manually setting a tooltip page is not supported by Button visual

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4001]
The button visual does support tooltips, but does not support manually setting a tooltip page as the tooltip. This limitation is not clear from the article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Create report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @djurecic0, thanks for the observation. I'm moving this issue to our work item backlog for better tracking and consideration. Closing it here now. Thanks!
