### ISSUE TITLE
Consumption section is incorrect

### ISSUE THREAD

**Issue by charris22** [MicrosoftDocs/powerbi-docs#4002]
This line is not correct: "When DirectQuery is available for a dataflow, connecting to a dataflow using the **Power BI dataflows** connector prompts you to choose whether to connect to tables through DirectQuery or Import."

To get this to work, I had to use the **Dataflow** connector (not the Power BI dataflow connector). Either a bug in the product or it changed. 

Here is working M code. Note it is using PowerPlatform.Dataflows
let
    Source = PowerPlatform.Dataflows(null),
    Workspaces = Source{[Id="Workspaces"]}[Data],
    #"WorkspaceId" = Workspaces{[workspaceId=pWorkspaceId]}[Data],
    #"DataflowId" = #"WorkspaceId"{[dataflowId=pDataflowId]}[Data],
    dfAccount_ = #"DataflowId"{[entity="dfAccount",version=""]}[Data]
in
    dfAccount_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a73aa1ea-ad60-282f-7a91-acfc3480344a
* Version Independent ID: 12ca283a-0fab-07e3-1541-12b85b63d07f
* Content: [Using DirectQuery with dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-directquery)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-directquery.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @charris22. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
I've updated the article to cite the correct connector. Thanks!
