### ISSUE TITLE
confusing and probably wrong information

### ISSUE THREAD

**Issue by lcallewier** [MicrosoftDocs/powerbi-docs#4003]
[Enter feedback here]
Hello,
I think in the sentence "While this feature is in Preview, reports created using the multi-dimensional approach cannot be published to the Power BI service, and doing so will result in errors when the report is opened within the Power BI service"  the word "multi-dimensional" should be replaced with "relational". As the multi-dimensional approach is the default way.
Best regards,
Lieven

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3124203c-c90c-4b87-f657-e3373af0d480
* Version Independent ID: c2f065a5-d48a-c921-92d8-8f99874fef3b
* Content: [DirectQuery for SAP HANA in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-sap-hana)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-sap-hana.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lcallewier. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we'll review that guidance with the product team.
