### ISSUE TITLE
Capacity assignment rights required

### ISSUE THREAD

**Issue by bonwhit** [MicrosoftDocs/powerbi-docs#4005]
The document states: "You may not be able to change it. If not, then contact your Power BI Premium capacity admin to give you assignment rights to add your workspace to a Premium capacity."

It would be very helpful if this was listed clearly under the Requirements section. I wasted quite a bit of time researching this issue before I found the answer, and capacity assignment ability is obviously required and not at all apparent. Everything I looked up says you have to have Premium or Premium Pro, but nothing other than that one sentence hidden under a screenshot said anything about capacity.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bonwhit. This issue has been assigned to the doc author for review.

**Comment by bonwhit** [comment]
Instead of the above recommendation, it might be better to state something like "Workspaces created before the Premium license was added (like My Workspace) will not be created with the diamond. Workspaces created after the Premium license was added will be created by default with the diamond." Replace "diamond" with better phrasing if desired.

**Comment by KesemSharabi** [comment]
Hi @bonwhit,

Can you please state which document you're referring to?

Thanks,

Kesem
