### ISSUE TITLE
'Target' field not visible.

### ISSUE THREAD

**Issue by adamguk** [MicrosoftDocs/powerbi-docs#4006]
Step 7 of the reference page mentions a 'Target' field. When creating a KPI the only available fields are 'Value', 'Trend Axis', and 'Trend'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [Key Performance Indicator (KPI) visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-kpi?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-kpi.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adamguk. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks, we've refreshed that article with new steps.

**Comment by adamguk** [comment]
> Thanks, we've refreshed that article with new steps.

Does it take a little time to appear live? I can't see the changes by viewing the article
