### ISSUE TITLE
Automated tooltips don't work

### ISSUE THREAD

**Issue by TimoRiikonen** [MicrosoftDocs/powerbi-docs#4007]
- Automated tooltips don't work any more.
- These instructions are in a confusing order: you should start from the most simple case and from there to gradually go to more complex cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Create report tooltip pages in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TimoRiikonen. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @TimoRiikonen -- thanks for your feedback! 

I added a link from https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop
to https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-custom-tooltips, which is simpler.

Can you elaborate on this comment?

- Automated tooltips don't work any more.
