### ISSUE TITLE
Is the Power BI component in Power Apps supported in GCC High?

### ISSUE THREAD

**Issue by thatmattwade** [MicrosoftDocs/powerbi-docs#4008]
The table at this section: https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#power-bi-feature-availability

is missing any reference to displaying Power BI tools in a Power App. We can't confirm that this feature works in our GCC H tenant and I'd like to see this called out in this table even if it is supported. That way we know whether it's something we can expect to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview)
* Content Source: [powerbi-docs/enterprise/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thatmattwade. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @thatmattwade - thanks for the feedback. I did a little research, and the info that you need is available via this doc: https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government. There is a related download with a table detailing feature parity. As the Power BI table is intended to highlight only those areas that don't have parity, I won't be adding Power Apps to the list. However, I will definitely add a cross-link to the PowerApps article so that info can be more easily found.

**Comment by thatmattwade** [comment]
Sorry, I don't see the information in the Power Apps link you provided. The only reference to Power BI is an on-prem data gateway, which isn't what I'm looking for. The question is whether data published in the Power BI Service (cloud) can be added as a part in a Power App, which currently doesn't work in our environment. I'd assumed it wasn't supported, hence my reference to the original Power BI article. If you're certain a Power BI web part inserted into a Power App is supported in GCC H, I'm not seeing it stated anywhere.

**Comment by kfollis** [comment]
Hi @thatmattwade - there is a PDF download link with the feature parity info. You may want to connect with support to see if this is an issue in your environment or something we should flag as an exception. We strive for feature parity across cloud environments so documentation typically only highlights features that don't work.
