### ISSUE TITLE
The number provided for the US directs customers to use a website to open a ticket. They need to speak with a human being.

### ISSUE THREAD

**Issue by valenciajdev** [MicrosoftDocs/powerbi-docs#4009]
[Enter feedback here]
The customer is lock out of their M365 Admin Console and needs to speak with a person of CSS to unlock their account. The number provided for the US instruct to open a ticket through the M365 Console or the Support Site contradicting what is stablished on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40aa7a48-bd93-f118-d68f-007a1b4cf80a
* Version Independent ID: fa5b7302-57d4-d507-460a-ea95a559f1c4
* Content: [Options to contact Power BI support to troubleshoot sign-in issues - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/power-bi-cannot-sign-in#contact-microsoft-support)
* Content Source: [powerbi-docs/admin/power-bi-cannot-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/power-bi-cannot-sign-in.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @valenciajdev. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @valenciajdev ,
Just to be sure that I understand.  The customer is locked out of M365 Admin console and the documentation tells them to log into that Admin console to open a ticket.  Which is, of course, not possible.  I get that. 
But the page you reference is for Power BI sign-in issues, not M365.  Here are some M365 articles and Community posts that may help.  If not, let me know. I've also sent these to you in email where the links are active. 
https://docs.microsoft.com/en-us/microsoft-365/admin/add-users/reset-passwords?view=o365-worldwide#reset-my-admin-password
[Change or reset your password in Microsoft 365 operated by 21Vianet](https://support.microsoft.com/en-us/topic/change-or-reset-your-password-in-microsoft-365-operated-by-21vianet-d8eb5b62-9d0e-4267-a9bf-2aa491ee6d0b)
[When you can't reset your Microsoft account password](https://support.microsoft.com/en-us/account-billing/when-you-can-t-reset-your-microsoft-account-password-123834ba-0b7c-404c-974c-2353caec8b10)
[Get support for Microsoft 365 for business ](https://docs.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide&tabs=online#phone-support)and [Global Customer Service phone numbers](https://support.microsoft.com/en-us/topic/global-customer-service-phone-numbers-c0389ade-5640-e588-8b0e-28de8afeb3f2)
[Microsoft 365 Admin password reset - Microsoft Community](https://answers.microsoft.com/en-us/msoffice/forum/all/microsoft-365-admin-password-reset/b5a05083-26f7-4557-b49d-4f006b84294f)
[Office 365 Admin Password Reset - Microsoft Community](https://answers.microsoft.com/en-us/msoffice/forum/all/office-365-admin-password-reset/f20864bb-60dc-4b78-ad67-a2f372db945c)
[Office 365 Admin Password Reset - Microsoft Community](https://answers.microsoft.com/en-us/msoffice/forum/all/office-365-admin-password-reset/13b33b5d-b391-4eee-8319-c872b69b0f66)
[https://.../admin/add-users/reset-passwords...](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fadd-users%2Freset-passwords%3Fview%3Do365-worldwide%23reset-my-admin-password&data=02%7C01%7Cv-regich%40microsoft.com%7C4ea4fcd318d44dbd411708d85f9d3943%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637364476189444127&sdata=%2F4AyFiL7yaSjM0%2B0kB808oyL1Jbc%2Bt9LS3RBWnQVn3M%3D&reserved=0)
[Global Customer Service phone numbers (microsoft.com)](https://support.microsoft.com/en-gb/topic/global-customer-service-phone-numbers-c0389ade-5640-e588-8b0e-28de8afeb3f2)

**Comment by valenciajdev** [comment]
Michele,

The user is locked out of M365, Outlook, Team, PBI, etc. She realized that she can't no longer access her PBI Report and the Admin of M365 is not around. Therefore she tried to open a ticket with CSS by using the phone.

Warm regards,

Jose Valencia
Analytics Technical Specialist (Power BI & Synapse)
+1 (617) 528-5683 | ***@***.******@***.***> | 5 Wayside Road, Burlington, MA 01803

[Microsoft]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpowerplatform.microsoft.com%2Fen-us%2F&data=02%7C01%7Cjose.valencia%40microsoft.com%7C68b98f882a214ad48d7a08d76dc9013b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637098582395617084&sdata=u8tCSFXITBARtLgNgRyPinvDsRaH38JPcIjLDRmcIuU%3D&reserved=0>

Click here to learn more about the Power BI<https://powerbi.microsoft.com/en-us/>

**Comment by mihart** [comment]
Hi @valenciajdev ,
Did any of the links I sent solve the problem?  Does the user have a Support plan?  If she has Power BI Pro or Premium, then she has free access to Support. Is she assigned the Admin role in her org?  Is there another person there with Admin permissions? Has she emailed Support or posted?  Did she try asking the Community community.powerbi.com? I would need to know a lot more to help solve this, but I'm a writer not a Support engineer.  Is there a reason that she is unable to speak with a Support person?  This isn't a documentation question, it's a Support question, so I am going to close this documentation Git Issue.  We can continue communicating via email if I can help in any way, however, I am vacation until 8/29.
