### ISSUE TITLE
Text Boxes not working as documented.

### ISSUE THREAD

**Issue by Christopher-Hastings** [MicrosoftDocs/powerbi-docs#401]
Hi! Thanks for the clear explanation of this new feature! Unfortunately the text boxes are inserted into PowerPoint as part of the image and not as an editable textbox as stated in your documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df1c4c0-80f9-f71a-175f-8362a29ad597
* Version Independent ID: c2a64e2a-ce65-dfb7-588a-381c145ab193
* Content: [Export reports from Power BI to PowerPoint - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint#feedback)
* Content Source: [powerbi-docs/consumer/end-user-powerpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-powerpoint.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Christopher-Hastings . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @Christopher-Hastings 
Good eye!  Thank you for catching that mistake.  I've removed it from the article and set it to republish.  
Take care,
Michele
