### ISSUE TITLE
Help with data in space role not showing in mobile app

### ISSUE THREAD

**Issue by usvjosh** [MicrosoftDocs/powerbi-docs#4010]
Hello,

We have followed the instructions on this page and are testing the mobile app on an iphone. The user in the owner role does not see the role show up under the "your role:" area of the mobile app. We have no one else using this yet, this is the first user, our first time setting it up. 

I confirmed the connection from PBI to Azure is working. I ensured we are using Azure AD Security Groups with the role use turned on. The spatial anchors account resource in azure looks okay too. The user is only in the group with the role 'Spatial Anchors Account Owner ' assigned to the RG as well as the spatial anchors account resource. I've also given the group read rights to the resource group. The user testing is NOT a power bi admin (no admin role). 

Are we missing something?

Thanks for any help in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b04b9d-1de7-169d-238f-af20d006f1a7
* Version Independent ID: b3b04b9d-1de7-169d-238f-af20d006f1a7
* Content: [Set up Data in space - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-data-in-space-set-up)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-data-in-space-set-up.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-apps-data-in-space-set-up.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @usvjosh. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @usvjosh, thanks for reaching out. I am the tech writer who wrote the article you are referring to. There a several things you mentioned that I am not sure about, so I am connecting you with the product group who I am sure will be interested in your experience, and then hopefully if there is anything in the documentation that can be made more clear I will happy to make those changes.

@mshenhav, can you take a look at Josh's experience and advise?

**Comment by paulinbar** [comment]
Hi Josh (@usvjosh), the product group at this point suspects either a bug or the wrong type of security group, and suggests that the best way to proceed would be for you to contact them through Power BI Mobile Support at mpbisup@microsoft.com. I would include what you wrote here, and perhaps a bit more detail about the security group you used. 
Good luck and let me know if I can be of further assistance!

**Comment by usvjosh** [comment]
Sounds good. I've got a ticket open with power bi support. Thanks for the help!
