### ISSUE TITLE
Link information very out of date and unhelpful

### ISSUE THREAD

**Issue by nghtchld** [MicrosoftDocs/powerbi-docs#4011]
The link from the Generate with Power Query section is from 2013 and very out of date and unhelpful. Surely there is a better more recent link or even a proper standardised Date Table Power Query that someone at Microsoft has coded to show as an example, given how important it is and how hard it can be to get right!
(https://docs.microsoft.com/en-us/power-bi/guidance/model-date-tables#generate-with-power-query)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e837063b-c36b-6bac-5c6b-10534146325c
* Version Independent ID: 7dcf1114-8d0e-39e7-e58f-894904f5a252
* Content: [Create date tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/guidance/model-date-tables)
* Content Source: [powerbi-docs/guidance/model-date-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/model-date-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nghtchld. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @nghtchld - thanks for taking the time to provide feedback. While Chris' blog entry might be old, it's still relevant and provides a working example of how to achieve a date table with Power Query. There are many other examples on the internet. So, if this example doesn't suit your needs, we encourage you to do a web search to find one that does.
