### ISSUE TITLE
Timezone question

### ISSUE THREAD

**Issue by MattHson** [MicrosoftDocs/powerbi-docs#4013]
Hi, Been using the Premium Capacity Utilization And Metrics and while I've found it useful I have a question regarding the Refresh Detail on the Refresh sheet.

The Timestamp... What time region is this in? I'm in the UK and it appears to be an hour & 20 mins behind & starting to wonder if the time is set to GMT/UTC or BST?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://docs.microsoft.com/en-gb/power-bi/enterprise/service-premium-gen2-metrics-app?wt.mc_id=powerbi_inproduct_gen2app)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MattHson. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @MattHson, 

I'm looking into this and will get back to you shortly.

Thanks,

Kesem

**Comment by kishanpujara-ms** [comment]
The app displays data in UTC time zone by default. There is a parameter called 'UTC_offset' which can be set to offset the data to show in your current timezone.  
This is documented here in the installation page: https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-install-gen2-app?tabs=1st#run-the-app-for-the-first-time

This can be set either while installing the app or later through dataset settings in the installed app.

**Comment by KesemSharabi** [comment]
Hi @MattHson,

I can confirm that @kishanpujara-ms reply above is correct.

Thanks,

Kesem
