### ISSUE TITLE
Deprecated JavaScript filters link

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4014]
The link to Javascript filters is deprecated:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters#page-level-and-visual-level-filters

![image](https://user-images.githubusercontent.com/3731532/185666871-0ae57af9-46b5-442e-b4d6-7ba5f9eab0c6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8345d077-5dab-e3b0-4109-facb509c8b68
* Version Independent ID: c666ff4f-6f8d-28b6-c4cf-57f433fc2688
* Content: [Using row-level security with embedded content in Power BI embedded analytics - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-row-level-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @otravers. The RLS pages are going through a major update and this page will soon be redone, but in the meantime, I replaced the link with one that works.
Thanks again,
Mona
