### ISSUE TITLE
Request for better explanation.

### ISSUE THREAD

**Issue by paulinbar** [MicrosoftDocs/powerbi-docs#4015]
Please expand as the setting and setting name create a double negative, which this document offers no explanation on how to address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccd8030-3b66-0de6-ce3e-816107259769
* Version Independent ID: 1ccd8030-3b66-0de6-ce3e-816107259769
* Content: [Dataset Security admin setting - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal-dataset-security)
* Content Source: [powerbi-docs/admin/service-admin-portal-dataset-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-dataset-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @paulinbar. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @loryanstrant. Well I heard back and I'm sorry to say that there is no further information regarding how to use that switch other than what you see in the UI. Apparently this switch was added for some security-related issues and is so extreme in its effects that it is basically not really practical to use. The product team is currently working to solve these issues more holistically and with more useful improvements and switches, but I think these are coming out individually and there isn't an ETA yet as to when all the work will be done. I guess covering all the bases is a complex task. 
Not exactly the answer you were hoping for but that's the best I can do for now.
Feel free to comment further, or if you think we're done for this round, then feel free to close this issue.
Thanks!

**Comment by loryanstrant** [comment]
Thanks so much Paul, but I've gotta say I think that outcome is even worse - they accept that there is a switch in the admin portal which is extreme in use and not practical to use, but offer no documentation to even explain that in softer terms?

I really appreciate your efforts, and I understand this is a complex issue, but the fact they can't even add an extra paragraph or two is beyond disappointing.
As a product manager myself I can't imagine providing that kind of response to you.

I'll raise this through my MVP communities and see if someone can get someone to budge on this.
Thanks for your efforts.

**Comment by paulinbar** [comment]
Hi again @loryanstrant. I will also take your feedback to the people I talked to. Hopefully feedback from your direction will prompt them to move this up in their list of priorities. So thanks for reaching out. I'll close this issue now but will continue to monitor the situation.
