### ISSUE TITLE
One Drive Option Not visible

### ISSUE THREAD

**Issue by AnkitKukreja19** [MicrosoftDocs/powerbi-docs#4016]
Hi! Team,

I'm following this documentation https://docs.microsoft.com/en-us/power-bi/connect-data/service-get-data-from-files
and as per the doc, I should see the One Drive option, but I cannot see it. I'm using the August'22 version.

Please guide me am I doing something wrong?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AnkitKukreja19. This issue has been assigned to the doc author for review.

**Comment by AnkitKukreja19** [comment]
Hi!

Thanks for your reply. What is the eta for this issue?

**Comment by AnkitKukreja19** [comment]
Hi! @KesemSharabi and @bishalgoswami 

Any updates on this?

**Comment by KesemSharabi** [comment]
Thanks for your comment, @AnkitKukreja19. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
