### ISSUE TITLE
"Labels" sample does not seem to work as described

### ISSUE THREAD

**Issue by sekaing** [MicrosoftDocs/powerbi-docs#4018]
The labels seem all to be contained in the first column only, instead of spreading across rows and columns as described, until switched to print layout.

Serge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e78cead-4fa4-cd7d-2a34-33179671d00b
* Version Independent ID: 87f8e772-35b0-c5c9-5853-b41373242a0b
* Content: [Sample Power BI paginated reports - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-samples)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-samples.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-samples.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sekaing. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @sekaing -- good question! I added this to the article to make it clear how to see the view with multiple columns:
**View the report**

When you run this report in Report Builder, it appears to have only one column.

- Select Print Layout to see what it will look like when you print it.

Likewise, when you upload this report to the Power BI service and open it there, it opens with only one column.

- Select View > Print Layout to see the multicolumn view.

Changes will be live this afternoon, Aug 30, or tomorrow. I hope that helps!
