### ISSUE TITLE
DirectQuery cautionary statement is missing a verb--meaning unclear

### ISSUE THREAD

**Issue by jeff-at-work** [MicrosoftDocs/powerbi-docs#4019]
The verb is missing in this explanation, so it does not convey meaning yet.

`However, there are some limitations associated with DirectQuery models:
Power Query/Mashup expressions can only functions that can be transposed to native queries understood by the data source.`

I believe it should ready "can only [something] functions" where something might be "include", but it's just a guess.

Thanks!

Jeff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4113f426-5c74-c68d-781b-be0bb9358db1
* Version Independent ID: 4ef47ef7-0502-4161-a43e-4eabc3545931
* Content: [Dataset modes in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand)
* Content Source: [powerbi-docs/connect-data/service-dataset-modes-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-dataset-modes-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jeff-at-work. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good catch! We've updated that article.
