### ISSUE TITLE
https://docs.microsoft.com/en-us/power-bi/desktop-getting-started

### ISSUE THREAD

**Issue by davepile** [MicrosoftDocs/powerbi-docs#402]
For a getting started tutorial, you really should use a data sources you control. The first data source on this page has changed. While it still works, the fields and values have changed so that the steps in the tutorial do not realy apply.

The second data source, http://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations i can open in the browser but not connect to from Power BI desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Getting started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @davepile.  We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback, and we'll take that into account when we review or update that article.
