### ISSUE TITLE
Inserted Wrong link instead of nodejs

### ISSUE THREAD

**Issue by thesureshpatel** [MicrosoftDocs/powerbi-docs#4021]
Under Code sample specifications=>
![Screenshot (1)](https://user-images.githubusercontent.com/72536375/186343745-73530835-cc87-4931-9aeb-a98368209cb6.png)
 Under Prerequisites => Under Code dependencies , inside nodejs section instead of nodejs link you have provided NET Framework 4 link please update it as soon as possible
Thanks and Regards,
Suresh Patel
sureshpatel.js@gmail.com

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thank you so much for pointing this out to me, @thesureshpatel! I changed the link to point to the main node.js download page - https://nodejs.org/en/download/
It should be live by tomorrow.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thesureshpatel. This issue has been assigned to the doc author for review.
