### ISSUE TITLE
Need a GOV version of this page

### ISSUE THREAD

**Issue by cchapin2020** [MicrosoftDocs/powerbi-docs#4022]
[Enter feedback here]
I was linked to this page from https://docs.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#power-bi-urls-for-general-site-usage. It would be good to have this page include the GOV versions in the General Site Usage table. I realize that they are included on the page that I started at, but if a Gov user doesn't get to this page through the link, they would be targeting the wrong URLs. I know, because I am fighting that very battle today with my Gov customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0bf9e3f-d1fc-9edc-c4b1-c2c214f71454
* Version Independent ID: 3b2b0285-2a7b-7eff-3053-dd4591414149
* Content: [Add Power BI URLs to allowlist - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/power-bi-allow-list-urls)
* Content Source: [powerbi-docs/admin/power-bi-allow-list-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/power-bi-allow-list-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cchapin2020. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @cchapin2020 - thank you for the feedback. I've reviewed the documentation experience, and I see that it could be frustrating to determine all of the correct endpoints for a gov allowlist. The articles currently cross-link to each other, though I think the link in the "important" note in the general allowlist article could be better targeted.  I can make that change today, and will consider how best to position this information and maintain over time. I think it might be useful to create a new article to separate the US-gov specific allowlist from the general gov guidance and include the generic endpoint list to give gov customers a one-stop reference. Is this what you're thinking?

**Comment by kfollis** [comment]
This article has been recently updated. Changes will continue as we transition this content to Microsoft Fabric. This need has been captured as a work item, so I will close this issue now. Thank you for the input!
