### ISSUE TITLE
Grouped visuals break apart

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#4027]
Grouped visuals break apart after some while after some manipulations with individual visuals within a group (moving, aligning, format changing, etc.) are carried out. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6669843-8752-7777-31e8-1d1e4ec96648
* Version Independent ID: b7be0303-1882-621e-a630-32895aafa84d
* Content: [Use grouping in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-visuals)
* Content Source: [powerbi-docs/create-reports/desktop-grouping-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-grouping-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gvggvg. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. You might find others who've experienced this in the Power BI Community, found at https://community.powerbi.com.
