### ISSUE TITLE
Bugs and suggestions in kusto query in desktop-dynamic-m-query-parameters.md

### ISSUE THREAD

**Issue by artemus-harper** [MicrosoftDocs/powerbi-docs#4028]
In the images (2 of them) showing the kusto query used,
Issues:
1. The datetime format is incorrect, the hours need to be capitalized, since h refers to 12-hour time, while H refers to 24-hour time. Additionally, `" zzz"` should be appended to account for local time zone differences, or the data type should be datetimezone. Also, the second format is missing seconds.
2. Remove extra space in `make-series count() on##CreatedAt from` (at the ##)
3. Remove extra space in last line in M query (it is not vertically aligned).

Suggestions:
1. Instead of `Type.Is(Value.Type(RepoParameterName), List.Type)` use `RepoParameterName is list`
2. Instead of `Text.Combine({";",Var, "'"})` use `"'" & Var & "'"`, or `Text.Format("'{0}'", {Var})`
3. Add a new line, `"#(cr,lf)"` between the two combined queries in `finalQuery`
4. Include the text to the query so we can run it.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @artemus-harper. This issue has been assigned to the doc author for review.

**Comment by artemus-harper** [comment]
I should mention that it appears that the database GithubEvent is not visible to external users (only the ML database in demo11.westus appears to be externally viewable). I would recommend using help/samples:StormEvents, as it is the standard demo table used in the Kusto docs.

**Comment by KesemSharabi** [comment]
Hi @artemus-harper,

Can you please state which document you're referring to?

Thanks,

Kesem

**Comment by artemus-harper** [comment]
@KesemSharabi https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters

**Comment by KesemSharabi** [comment]
Hi @artemus-harper,

Thanks for pointing out the issues in [Dynamic M query parameters in Power BI Desktop](https://learn.microsoft.com/power-bi/connect-data/desktop-dynamic-m-query-parameters). We'll update this article shortly.

Kesem
