### ISSUE TITLE
Clarification related to the Note about Version control for PBIX files

### ISSUE THREAD

**Issue by owenrae** [MicrosoftDocs/powerbi-docs#4029]
I would like to get some clarification related to the note about version control and using auto-sync.  In the note you specifically say that you should only auto-sync PBIX files in the deployment pipeline's development stage.  I wonder if you are really saying, only auto-sync PBIX files in the deployment pipeline's "initial" stage.  In the setup we are using for our deployment pipelines we are only using the Test and Prod stages.  So our test stage is our initial stage.  My thought is that you are saying with the note, don't auto-sync to midstream stages and that could mess things up.

If you are saying in order to auto-sync you have to have a three stage pipeline and you should only auto-sync to the Dev stage I question why that is?  Is there something inherently different with the Dev stage that works with auto-sync?

Thanks for any clarification you can provide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa579c66-952b-33ee-748f-ecfe240623f2
* Version Independent ID: 3ad65d22-635c-ebcc-b21a-930aff1e60ab
* Content: [Best practices for deployment pipelines, the Power BI Application lifecycle management (ALM) tool - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-best-practices)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-best-practices.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-best-practices.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @owenrae. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @owenrae,

I believe you're right and that in your scenario the recommendation is to only auto sync the PBIX in the 'initial' stage, which in your case is the test stage. However, I'm going to double check this with the product and engineering team and get back to you.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @owenrae,

Just confirmed with engineering and product, you don't have to use the development stage. In your case you can use the test stage.

Thanks,

Kesem
