### ISSUE TITLE
Goals became metrics; need to update

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/powerbi-docs#4030]
[Enter feedback here]
This line:
[Power BI goals](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-introduction) do not currently support bring your own key (BYOK)
Needs to become:
[Power BI Metrics](https://docs.microsoft.com/en-us/power-bi/create-reports/service-goals-introduction) do not currently support bring your own key (BYOK)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9a86dc-4be4-d0a2-644d-cb20e3af74fb
* Version Independent ID: d08af8bc-fb3e-e443-7152-abaa0f2df6cc
* Content: [Bring your own encryption keys for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-encryption-byok)
* Content Source: [powerbi-docs/enterprise/service-encryption-byok.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-encryption-byok.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Good catch, we've updated the article.
