### ISSUE TITLE
Power Bi PPU

### ISSUE THREAD

**Issue by jalao12** [MicrosoftDocs/powerbi-docs#4032]
I had a Powerbi license but the PPU trial date is still counting, tried to sign out of the account completely, restart the machine and then sign in back, the trial date issue was still counting, is there a way to fix that? thank you
![image-20220825-154245](https://user-images.githubusercontent.com/112185493/186927043-00e38113-e04c-4334-9ef2-b272f1f8cee2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Version Independent ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Content: [Power BI Premium Per User - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq#using-premium-per-user--ppu-)
* Content Source: [powerbi-docs/enterprise/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jalao12. This issue has been assigned to the doc author for review.
