### ISSUE TITLE
PPU shared with Free users

### ISSUE THREAD

**Issue by andremcastro** [MicrosoftDocs/powerbi-docs#4033]
Docs says that PPU can distribute reports to free users, which is not correct. Only Premium capacity has this feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6e1bb7-fbc5-d0a6-5285-e4a9152902bb
* Version Independent ID: ece0823b-c4c5-3acb-41bb-55e5390c0b6c
* Content: [Power BI service features by license type - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type)
* Content Source: [powerbi-docs/fundamentals/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-features-license-type.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
Hi @andremcastro - Thanks for the feedback! I reviewed the article and the table that describes capabilities does differentiate between shared and Premium capacity. I'm not finding the statement you mention. I have asked the author to review the article for clarity, however. If I missed something, please do let me know!
