### ISSUE TITLE
Private DNS Zone detail is incorrect

### ISSUE THREAD

**Issue by plynch66** [MicrosoftDocs/powerbi-docs#4034]
Hi,

The documentation states that a new Azure Private DNS Zone named 'privatelink.tip1.powerquery.microsoft.com' will be created when enabling Private Link for Power BI.

This is incorrect. The Private DNS Zone which gets created is named 'privatelink.prod.powerquery.microsoft.com'

Regards,

Paul Lynch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for accessing Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @plynch66. This issue has been assigned to the doc author for review.

**Comment by schwarztrinker** [comment]
Any Updates here? Got the same error today after a long network debugging session...

**Comment by davidiseminger** [comment]
I've updated that article, thanks!
