### ISSUE TITLE
For the cognitive services image tagging example

### ISSUE THREAD

**Issue by alpkayaMSFT** [MicrosoftDocs/powerbi-docs#4035]
[Enter feedback here]

For the cognitive services image tagging example, the instructions don't work.  I am not able to get through on the instruction where we select "anonymous" and click next. It won't work and it won't let me go through to the next step. I've asked a few others to test this out and same issue on their end.  Can we either get these instructions updated? or remove them if this no longer works?
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a614670c-d6fb-2933-ca40-1be5901beb27
* Version Independent ID: f7f97531-c634-e7c0-8280-26b1c7931f47
* Content: [Tutorial: Use Cognitive Services in Power BI (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-tutorial-use-cognitive-services)
* Content Source: [powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alpkayaMSFT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated this document to clarify the steps, thanks.
