### ISSUE TITLE
Outdated section for upgraded apps

### ISSUE THREAD

**Issue by ivoburger** [MicrosoftDocs/powerbi-docs#4036]
Section: How to get the correct link format, Links to apps and items in apps shows
shows a picture to get links which is not available any more after you upgrade App.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ed5d7c-7973-17bd-8a5a-2b80c33eab2c
* Version Independent ID: 71e8bc7e-55a5-fb95-4805-34a2be26a0ed
* Content: [Create a link to a specific location in the Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-deep-link-specific-location)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-deep-link-specific-location.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-apps-deep-link-specific-location.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @ivoburger, thanks for comment. I will check this out and update in the coming days.

**Comment by paulinbar** [comment]
Hi @ivoburger, sorry for the delayed response. I have created a work item for myself to follow up on your observation and will update the documentation as necessary. So for the meantime I am closing this issue. Thanks for taking the time to send your feedback!

**Comment by paulinbar** [comment]
Hi @ivoburger, just wanted to let you know that I investigated the issue. You are right that the links for reports and dashboards are not available on the app setup pane. There there is only the link to the app. However, the "in app" links to reports and dashboards are still available from the "Share" option of the report or dashboard (provided that sharing has been allowed for the report or dashboard). When you selected the Share option, you'll see the "Copy link" possibility. If you look at the URL, you'll see that it includes the appID as well as the report or dashboard ID. Anyway, I'll be updating the documentation to reflect this change. Again, thanks for pointing this out!
