### ISSUE TITLE
Power BI references old python interpreter

### ISSUE THREAD

**Issue by schulzalbrecht** [MicrosoftDocs/powerbi-docs#4037]
The power bi tool was using a python interpreter located on:
`C:\Users\xx\Projects\ProjectA\venv\Scripts\`

I decided delete this python interpreter and create a new one on:
`C:\Users\xx\Projects\ProjectB\venv\Scripts\`

So, I went to file > options > python scripting. And set the path to the new directory.

After doing do, my power bi is *still* referencing the old interpreter. Apparently the variable that holds the path to the python interpreter is not being updated. 

When i open the window to write the script, power bi makes sure to print out that: 
`This script will run with the following Python installation: C:\Users\xx\Projects\ProjectB\venv\Scripts\`

however it does not do so! When I run the script, I get the error: 
```
DataSource.Error: ADO.NET: Python script error.
<pi>No Python at '`C:\Users\xx\Projects\ProjectA\venv\Scripts\python.exe'
</pi>
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
<pi>No Python at '`C:\Users\xx\Projects\ProjectA\venv\Scripts\python.exe'
</pi>
    ErrorCode=-2147467259
```

I've already tried to close and re-open again the program, but it doesn't solve the program.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @schulzalbrecht. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @schulzalbrecht. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
