### ISSUE TITLE
RangeStart/RangeEnd Time Zone

### ISSUE THREAD

**Issue by bharath47** [MicrosoftDocs/powerbi-docs#4038]
[Believe when you enter the RangeStart/RangeEnd date/time value, it got to be in UTC timezone. Would be good to mention that.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 703aa6c4-1701-ea81-5fe6-c0afd163021e
* Version Independent ID: 13601081-10c5-3947-f19b-daa8c44a5382
* Content: [Configure incremental refresh and real-time data for Power BI datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-configure)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-configure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-configure.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bharath47. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@bharath47 - Did you run into a scenario where specifying a non-UTC time for the parameters caused an issue? For example, Scheduled Refresh is UTC, but parameters specified were non-UTC. Can you describe why you think this is important to mention.
Thanks

**Comment by bharath47** [comment]
@Minewiskan - I'm working in NZT time zone (and the same configured in my locale settings); When i first tried this feature, i set the RangeStart date as 1/04/2022 12:00:00 pm (intention is to use 1-Apr-2022), but noticed, the records changed prior to Apr were pulled in. Later i changed it to 4/01/2022. Please let me know if my understanding is incorrect, will recheck.

**Comment by Minewiskan** [comment]
@bharath47 - NZT is UTC+12 or 13. Is the date/time format in the date column of your data in dd/mm/yyyy or mm/dd/yyyy format?
