### ISSUE TITLE
Evaluation Context / October 2018 release

### ISSUE THREAD

**Issue by joerobert06** [MicrosoftDocs/powerbi-docs#404]
I have noticed that I have lost the ability to hold an evaluation context when using bookmarks to toggle between visualizations on the same page. For example if I was to select a bar on a bar chart and switch between visuals, the selected context goes back to the original state. “Data” is unchecked under data properties and so I am not sure why I’m seeing this response. I used this technique very frequently prior to the oct release. Your assistance is very appreciated

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @joerobert06. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
