### ISSUE TITLE
View history of this document

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4041]
This is a question more than an issue. This document is dated 08/29/2022. How can I see previous versions of the article and what has been changed between versions?

Specifically, I'm trying to find out when the following was added.
_Limitations when downloading a dataset .pbix file
Downloading a .pbix file that is larger than 1 GB isn't supported_

I've downloaded reports > 1GB many times, but am having issues this week. I wanted to see if this limitation was recently added. 

Thanks,
Dean

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix?source=docs#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @djurecic0 -- 
- I've asked about that specific change and will let you know what I hear back.
- And yes, you can see the history of any article. 

How to see the history: 
On this page, select the link next to **Content Source**: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md). 
On that page, select **History**.
You see a list of **Commits**.
You can open each commit and see the markdown, with the old text highlighted in red, the new in green.
I opened a bunch of them. That bullet point was already there by June 7, 2022.
Hope that helps!

**Comment by maggiesMSFT** [comment]
Hey, another writer shared with me this other view, "Blame view" (?):
https://github.com/MicrosoftDocs/powerbi-docs/blame/main/powerbi-docs/create-reports/service-export-to-pbix.md
It shows that line 104 was last updated 7 months ago. 
Hope that helps!

**Comment by djurecic0** [comment]
This is helpful- thank you!

**Comment by maggiesMSFT** [comment]
@djurecic0 -- thanks for asking. I learned something new, too!

**Comment by djurecic0** [comment]
Thank you!!
