### ISSUE TITLE
Question on file size and download type

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4042]
_Limitations when downloading a dataset .pbix file
Downloading a .pbix file that is larger than 1 GB isn't supported._

Since the 1GB limit is listed only in the _Limitations when downloading a dataset .pbix file_ section, does this mean that it is supported when downloading a report .pbix file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix?source=docs#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @djurecic0 - a reasonable question! The 1 GB limitation is the same, whether it's a dataset or a report .pbix file.
Apparently the limitation has been there all along but was not always enforced. 
We're updating the report .pbix section of the article to make the limitation clear.

**Comment by djurecic0** [comment]
Thank you- this is helpful!

I kind of wish that the decision to enforce got a bit more publicity since I work with several organizations that regularly download large .pbix files.

I like to think I follow Power BI news pretty closely, but did not notice that the documentation changed 7 months ago. The only previous issues we had with downloading was having to disable large datasets.

We will start to make alternate arrangements- maybe something like this:
https://docs.microsoft.com/en-us/power-bi/connect-data/refresh-desktop-file-onedrive
