### ISSUE TITLE
Best and Worst states table doesn't show up in Power BI

### ISSUE THREAD

**Issue by Wedfrisat** [MicrosoftDocs/powerbi-docs#4045]
The html table in the url used for the lesson ( https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/ ) doesn't show up in Power BI import even though I can clearly see it when I browse there.  And it is an HTML table still.  I see 4 suggested tables but no HTML table listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks, we've updated that article.
