### ISSUE TITLE
Disabling Azure Data Lake Gen 2

### ISSUE THREAD

**Issue by elfigha** [MicrosoftDocs/powerbi-docs#4046]
[Enter feedback here]
[https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#disabling-azure-data-lake-gen-2](url)
The documentation at this link does not correctly describe how the Dataflows setting works. Indeed, in Admin Portal, under Dataflow setting, there is only the possibility to activate or deactivate the creation of dataflows
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#feedback)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfigha. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, this article has been updated since your post.
