### ISSUE TITLE
Copy visual as image button has moved; docs not updated.

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/powerbi-docs#4047]
The Copy Visual as Image has moved from the context menu to the visual header.  Docs still show it in the old location.
![image](https://user-images.githubusercontent.com/28908684/189709273-f7a53677-440f-47ab-94cf-0891f4170b1e.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1534304-51bc-e015-e942-d7be33e2a9b6
* Version Independent ID: b317e804-65fc-a354-18c1-333b3b1191b9
* Content: [Copy and paste a visualization in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-copy-paste)
* Content Source: [powerbi-docs/consumer/end-user-copy-paste.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-copy-paste.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dbrownems. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @dbrownems , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
