### ISSUE TITLE
PPU and AutoML

### ISSUE THREAD

**Issue by ogzozo** [MicrosoftDocs/powerbi-docs#4048]
[Enter feedback here]
I am subscribed to Premium Per User, but I get an error message when I try to Apply ML model. It says I need to be on Premium per capacity. Kindly advise what I need to do. I am the only user in the organisation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a Machine Learning model in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/service-tutorial-build-machine-learning-model)
* Content Source: [powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ogzozo. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
