### ISSUE TITLE
Remove Filter

### ISSUE THREAD

**Issue by DataDanCalgary** [MicrosoftDocs/powerbi-docs#4049]
Section on Remove Filter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7006d534-e3ee-c389-a834-516212b607ef
* Version Independent ID: f0d40c66-9c24-8c36-1142-df06d9a7ffee
* Content: [Format filters in Power BI reports - Power BI](https://docs.microsoft.com/en-us/power-bi/create-reports/power-bi-report-filter?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/power-bi-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-report-filter.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DataDanCalgary. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi @DataDanCalgary -- a couple of clarifying questions/comments.

- Are you in Editing or Reading view? 
- Are you trying to _clear_ a filter, or actually get rid of it?
- If you're in Reading view, you can't get rid of filters, but you can clear them. Here's an article about filters in Reading view: https://learn.microsoft.com/en-us/power-bi/consumer/end-user-report-filter.
- In either view, you can't get rid of filters on individual visuals, but in Editing view you can hide them. See https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-report-filter?tabs=powerbi-desktop#lock-or-hide-filters.
- In Editing view you can get rid of the filters on the page or the report.

Let me know if you're asking something else!
