### ISSUE TITLE
AuthorityUrl is incorrect when using Microsoft.IdentityModel.Clients.ActiveDirectory v4.3.0

### ISSUE THREAD

**Issue by nicholas-brooks** [MicrosoftDocs/powerbi-docs#405]
A FYI for anyone using the latest nuget packages for PowerBI integration (specifically v4.3.0 Microsoft.IdentityModel.Clients.ActiveDirectory).  You need to use "https://login.microsoftonline.com/common" instead of "https://login.windows.net/common/oauth2/authorize/" for the AuthorityUrl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed Power BI content into an application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @nicholas-brooks.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by markingmyname** [comment]
@nicholas-brooks Sorry for the delayed response. Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@nicholas-brooks Thank you for bringing this to our attention.  The article is planned for a refresh by early next month and this suggestion should be addressed with the new updates.
