### ISSUE TITLE
Can't add custom connector

### ISSUE THREAD

**Issue by Khoi1201** [MicrosoftDocs/powerbi-docs#4050]
[Enter feedback here]

Hi, I'm using a custom connector to connect Trino to Power BI https://github.com/pichlerpa/PowerBITrinoConnector,
I follow the instruction and create custom connector 
![image](https://user-images.githubusercontent.com/90588753/190229159-22cbb7d0-1a93-4d0b-88e4-a0c25a7fd178.png)
and put the file there
![image](https://user-images.githubusercontent.com/90588753/190229224-57e55902-892a-4be0-b8c1-3d0d9a1d831b.png)
I change the option as the instruction
![image](https://user-images.githubusercontent.com/90588753/190229709-82ffb594-9133-49fb-b311-af31b8ffa53c.png)
but it just won't work
![image](https://user-images.githubusercontent.com/90588753/190229403-35528b1d-d080-459f-a766-7e9a999e9855.png)
If you know any other way to connect Trino to Power BI I would like to hear it, thanks.

--
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de9db81b-e91f-c1c8-7062-eb8bd5920eb9
* Version Independent ID: 63ba058e-817c-3b82-767b-5f94d8204e5b
* Content: [Connector Extensibility in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-connector-extensibility)
* Content Source: [powerbi-docs/connect-data/desktop-connector-extensibility.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connector-extensibility.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Khoi1201. This issue has been assigned to the doc author for review.

**Comment by Khoi1201** [comment]
I put it in the wrong folder
![image](https://user-images.githubusercontent.com/90588753/190346921-6582f19f-81f7-4dfc-b206-6f97587b03c0.png)
