### ISSUE TITLE
Missing info regarding "Connect an Azure Data Lake Gen2 storage account."

### ISSUE THREAD

**Issue by yangyud-cn** [MicrosoftDocs/powerbi-docs#4053]
To add ADLS Gen2 storage account, you also need to add **"00000009-0000-0000-c000-000000000000 | Power BI Service"** to admin role.  Or it will fail with a misleading error message as: 
"CdsaUserStorageOwnerRoleRequiredException: You can't connect to this storage account because you don't have the necessary role-based-access-control (RBAC) permissions. **Make sure you're assigned the owner role for this storage account**, and try again."

BTW, there could be multiple "Power BI Service" AAD applications by display name and you need to ensure to select the one with AppId as "00000009-0000-0000-c000-000000000000".  The others could be fake ones.

Note that https://docs.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-configure mentioned this:  
 -  The service principal 'Power BI Service' must be in the Owner role for the Log Analytics Workspace.

But again, the user needs to be sure the correct "Power BI Service" is added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://docs.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yangyud-cn. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks, we've updated the docs for this situation.
