### ISSUE TITLE
Please clarify the Azure subscription rights for PowerBI Premium autoscale

### ISSUE THREAD

**Issue by clorax** [MicrosoftDocs/powerbi-docs#4054]
The documentation states:

_The person configuring Autoscale must be at least a contributor for the Azure subscription to successfully complete these steps._

Once Autoscale is configured in the PowerBI Portal, are contributor rights on the subscription necessary for autoscaling to function?  What about for making changes to the autoscaling configuration?  Is it safe to remove contributor rights from the subscription once autoscaling is enabled?

Please clarify what rights are required in the Azure subscription after the initial configuration is done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 045fc571-5d81-0179-a69b-58a43d5b8ab6
* Version Independent ID: 045fc571-5d81-0179-a69b-58a43d5b8ab6
* Content: [Using Autoscale with Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/enterprise/service-premium-auto-scale#enable-autoscale-in-the-power-bi-admin-portal)
* Content Source: [powerbi-docs/enterprise/service-premium-auto-scale.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-auto-scale.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @clorax,

I'm looking into your questions and will get back to you once I have answers.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @clorax,

Only users with admin rights for the capacity can turn Autoscale on or off. If the user who enabled Autoscale loses their permissions the Autoscale feature will continue to have the settings it had before they lost their permissions; Autoscale isn’t impacted by user permission changes. You could revoke the admin rights after someone enables Autoscale, but you'd later need to grant new permissions if you want that user to change the feature.

Hope this helps,

Kesem
