### ISSUE TITLE
Missing steps for OS X certificate setup

### ISSUE THREAD

**Issue by coreyroth** [MicrosoftDocs/powerbi-docs#4055]
There are missing steps missing in the OS X certificate setup.  It doesn't tell you to open KeyChain Access first.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @coreyroth. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @coreyroth. I’ll add this request to our docs backlog.

**Comment by mberdugo** [comment]
Thanks again, @coreyroth. I added that step.
