### ISSUE TITLE
Different behavior between Pro and PPU/Premium should be mentioned

### ISSUE THREAD

**Issue by yaniv-intlock** [MicrosoftDocs/powerbi-docs#4056]
Hi Team,

Me and my team have spent some time trying to figure out why incremental refresh is slow, and reached the following conclusion.

In case a dataset is published to **Pro** workspace or "My Workspace", the service refresh will execute a 'TOP 1000' query for each partition. This slows down the refresh dramatically and likely to hit a timeout. In addition, it's overloading the data source (Azure SQL DB in my case) with long running queries.
On the other hand, it doesn't happen on **PPU/Premium** workspace, where only relevant queries, that have date range conditions, are executed, making the incremental refresh fast and efficient.

I think it should be mentioned in this KB, to save us a lot of time troubleshooting and digging into profiling traces to find out this issue. Also would be great to know why it's behaving differently in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for datasets and real-time data in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yaniv-intlock. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@yaniv-intlock - Thanks for bringing this to our attention. Engineering has entered a fix that should appear in the production shared capacities environment around the second week of October. When in place, Pro workspaces should have the same initialization query performance as Premium workspaces.  Re-open this issue or open a support case if you don't see improvement by the third week of October.
