### ISSUE TITLE
can't connect ODBC driver and DSN from starburst enterprise from power BI

### ISSUE THREAD

**Issue by Khoi1201** [MicrosoftDocs/powerbi-docs#4059]
Hi, I'm having a trouble with deploying Power BI and Trino

![image](https://user-images.githubusercontent.com/90588753/190545497-0362a934-d4ec-44ae-be48-f8fcfda2ec71.png)
![image](https://user-images.githubusercontent.com/90588753/190545599-3e456ea1-bade-456f-9187-7b2fe7db6bfd.png)
![image](https://user-images.githubusercontent.com/90588753/190545619-b2f27344-a442-4574-b86a-efb971ac88be.png)

The error say like missing certain words which confuse me, I have fill it in the SQL statement.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-gb/power-bi/connect-data/desktop-data-sources)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Khoi1201. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
For information on the ODBC drive, please see the Power Query documentation.

**Comment by joao9905** [comment]
@Khoi1201 have you been able to resolve this issue? I've read a lot about it but wasn't able to get any answer on how to resolve it

**Comment by Khoi1201** [comment]
> @Khoi1201 have you been able to resolve this issue? I've read a lot about it but wasn't able to get any answer on how to resolve it
It has been a while, But I think I used this link to solve my problem.
https://github.com/CreativeDataEU/PowerBITrinoConnector
