### ISSUE TITLE
What are the concerns?

### ISSUE THREAD

**Issue by erapade** [MicrosoftDocs/powerbi-docs#406]
Could you please elaborate a little about the concerns with enabling this option. I understand it might be IP/URL concerns to reach the external data sources, but do we also have security concerns like information from local sources might be visible in the queries for the external data sources, etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @erapade.  We’ve forwarded your feedback to the writer, who should respond shortly. Thanks!

**Comment by mgblythe** [comment]
@arthiriyer - can you answer the question in this issue? Thanks!

**Comment by arthiriyer** [comment]
@erapade  This feature should be used along with the privacy settings for each data source to make sure the joins are handled in a secure manner.  However Privacy settings in Power BI desktop are not transferred to the service. You can set privacy settings for the On-prem data sources. For cloud data sources, it is set to “Private” by default in the service with an exception for the ones which are using anonymous authentication and these are set as “Public” by default.   We are however working on a feature which will help with setting these  explicitly for cloud data sources as well

**Comment by mgblythe** [comment]
Added a sentence to step 6 in “Merge or append on-premises and cloud data sources” (https://docs.microsoft.com/power-bi/service-gateway-mashup-on-premises-cloud) about making sure the privacy levels for both cloud and on-premises data sources are set appropriately.
