### ISSUE TITLE
The screenshot is outdated.

### ISSUE THREAD

**Issue by soheildataviz** [MicrosoftDocs/powerbi-docs#4061]
The existing screenshot on this page is outdated. 
There are currently 4 options on the **Azure Connections** page in the **Admin Portal**.
Image attached:
![image](https://user-images.githubusercontent.com/58403397/190550461-a9968025-ed54-4723-a07c-eb942fef6d12.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb435e9b-f9d0-ed9e-3f7b-01ecfc7f18ea
* Version Independent ID: eb435e9b-f9d0-ed9e-3f7b-01ecfc7f18ea
* Content: [Audit and usage admin settings - Power BI](https://docs.microsoft.com/en-us/power-bi/admin/service-admin-portal-audit-usage)
* Content Source: [powerbi-docs/admin/service-admin-portal-audit-usage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-audit-usage.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @soheildataviz. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @soheildataviz, I have updated the screenshot and it should be online soon.
Thanks!
