### ISSUE TITLE
The setting explained on this page is different from the one currently available in the Power BI Admin Portal.

### ISSUE THREAD

**Issue by soheildataviz** [MicrosoftDocs/powerbi-docs#4068]
Hi there,

The setting explained on this page is different from the one currently available in the Power BI Admin Portal.
Here is a screenshot of the current setting:

![image](https://user-images.githubusercontent.com/58403397/191375432-cf6c3ef7-c947-4028-ae59-bf129c6f6e4c.png)

I believe the image and the descriptions must be updated.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 236be35d-5c21-cd23-12ca-2a9b420545d3
* Version Independent ID: 236be35d-5c21-cd23-12ca-2a9b420545d3
* Content: [Share data with your Microsoft 365 services admin settings - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-share-data-microsoft-365-services)
* Content Source: [powerbi-docs/admin/service-admin-portal-share-data-microsoft-365-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-share-data-microsoft-365-services.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @soheildataviz. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @soheildataviz, thanks for pointing this out. I've created a work item to correct the documentation. In the meantime I will close this issue. Again, thanks for taking the time!
