### ISSUE TITLE
Not really the same: "Publishing from Power BI Desktop has the same effect as using Get Data in Power BI to connect to and upload a Power BI Desktop file."

### ISSUE THREAD

**Issue by murmukka** [MicrosoftDocs/powerbi-docs#407]
I would argue that these two things don't have the same effect and stating that is a bit misleading. By publishing from Power BI desktop, the file doesn't get updated on an hourly basis, even if it is on OneDrive for Business/Sharepoint, as it does when you connect to the file using Get Data, but to get it updated, you have to publish it again. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @murmukka.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by davidiseminger** [comment]
That's a good point - sorry for any confusion. I'll look at changing the wording on that.
