### ISSUE TITLE
Move scorecard failed.

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#4072]
I received the following when trying to move an existing Scorecard to a new workspace I'd just created. 

Activity ID: 548e9cd4-8731-4e30-8147-777244954a24
Request ID: 195d1c8e-f6f1-932c-28d6-44ba61bc9eaa
Correlation ID: f3331b1a-7b45-5968-488a-33090577eeca
Status code: 403
Time: Wed Sep 21 2022 14:07:21 GMT-0500 (Central Daylight Time)
Service version: 13.0.19087.42
Client version: 2209.2.13372-train
Cluster URI: https://wabi-us-north-central-g-primary-redirect.analysis.windows.net/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12ac2aa1-b899-184c-10c3-7909aa32bff8
* Version Independent ID: 17e2b2b8-02c5-fcf0-32ab-7f3ef2eb271f
* Content: [Create scorecards and manual metrics - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-goals-create)
* Content Source: [powerbi-docs/create-reports/service-goals-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-create.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- Thanks! I've passed your feedback along to the product team. I'm going to close this issue, as it's not a documentation issue. I suggest selecting the other link at the bottom of the article: 
Submit and view feedback for:
**This product**

**Comment by maggiesMSFT** [comment]
Hi, @nicheplayer -- quick update. I heard back from the product team. They ask if you're trying to move the scorecard to or from My Workspace, because that is currently not supported. If not that, you can report an issue at https://community.powerbi.com/t5/Issues/idb-p/Issues.
Hope that helps!
