### ISSUE TITLE
Duplicate report from an app

### ISSUE THREAD

**Issue by elfigha** [MicrosoftDocs/powerbi-docs#4075]
[Enter feedback here]
I applied the procedure described in the following link
https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports#copy-a-report-in-an-app
User1 created a workspaace W and publish a Power BI Desktop file Report1 in W.
User1 publsih this report in an app aand give User2 buildin permission on Report1
However, when User2 open the app he don't see the option save under file menu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfigha. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @elfigha, thanks for reaching out to us. Can you tell my how build permission on the dataset was granted? And when creating the app, what permissions were to be granted to users, and which users were indicated?

**Comment by paulinbar** [comment]
Hi @elfigha, there are two settings in the app configuration that you have to watch out for. In the Audience tab, under Advanced, there is an option to allow users to build new content on the dataset. This option doesn't grant permission to copy reports that are in the app. On the Setup tab, there is an option to allow users to copy reports in the app. That option causes the Save a copy option to appear. 
I'll close this issue now, but feel free to reopen if you still can't get the Save a copy option to appear. Thanks!
