### ISSUE TITLE
Field parameter preview feature not included in any release schedule

### ISSUE THREAD

**Issue by jlteranl** [MicrosoftDocs/powerbi-docs#4076]
Hi there, the company our team is working for is trying to use the field parameter preview feature, we have tested and we found it very useful, but my organization won't deploy anything that is marked as a preview feature.  We have also checked the future release calendars and this feature is not present in any of them. Could you please confirm that there are good possibilities to be released and also a timeframe where this to happen? Thanks

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jlteranl. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jlteranl. 

This looks like a product question rather than documentation feedback.

You might find an answer in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
