### ISSUE TITLE
Multiple Pages PNG

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4077]
The action allows for an array of pages:  what happens when the export format is PNG and multiple pages are provided to the action?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GitWesDone. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @GitWesDone, You've reached the channel for feedback about the docs. I think this sounds more like a product question, so I'd try our [support page](https://support.powerbi.com/) or perhaps also the [Power BI Community](https://community.powerbi.com/). Good luck!
