### ISSUE TITLE
Couldn't load the table from web

### ISSUE THREAD

**Issue by stumit63** [MicrosoftDocs/powerbi-docs#4078]
Using Power BI Desktop Version: 2.108.997.0 64-bit (August 2022), the table of interest does not show up in Navigator. Could be a page change or something that's missing or changed in the PBI web connector. The html source for the table seems valid. Navigator shows me three tables (Table[1..3]) which I can't see on the page.

To solve the issue for this data set I downloaded and imported the csv provided. 
Kind regards to all
Stuart

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stumit63. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we've updated that article with new information since you posted. Thanks!
