### ISSUE TITLE
Under limitation can you mention Admin API calls which require (Tenant.Read.All or Tenant.ReadWrite.All) and doesn't comes under Admin read-only API.

### ISSUE THREAD

**Issue by AkshayDutta** [MicrosoftDocs/powerbi-docs#4079]
Hello Team,

Hope you are having great day.

I have a small request from my end, can you please add the Admin API calls under limitation which require (Tenant.Read.All or Tenant.ReadWrite.All) and doesn't comes under read only API's just to avoid confusion between both the API's calls, Please consider my request from one of our client's as they got confused while assigning permissions to APP.

Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Version Independent ID: 58a83362-3a66-ba07-ebe5-b83a49171917
* Content: [Enable service principal authentication for read-only admin APIs - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/read-only-apis-service-principal-authentication)
* Content Source: [powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/read-only-apis-service-principal-authentication.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AkshayDutta. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @AkshayDutta, I am afraid I don't quite understand what you'd like to see. Can you elaborate a little? Thanks!

**Comment by paulinbar** [comment]
HI @AkshayDutta, I am afraid I don't understand the ask. I am going to close this issue for now, but please don't hesitate to reopen it if you can provide some clarification. Thanks!
