### ISSUE TITLE
https://learn.microsoft.com/en-gb/power-bi/consumer/end-user-reading-view links to wrong page

### ISSUE THREAD

**Issue by TheKiltyOne** [MicrosoftDocs/powerbi-docs#4083]
[[Enter feedback here]](https://learn.microsoft.com/en-gb/power-bi/consumer/end-user-reading-view) 
This link actually brought me to the wrong page. It is not possible to access the Reading View page.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3cece6cf-53cd-6704-7c50-d03007f60a96
* Version Independent ID: 439ed96c-e946-d8d5-1943-82fb4b2c41b0
* Content: [Power BI consumer capabilities in Power BI service - Power BI](https://learn.microsoft.com/en-gb/power-bi/consumer/end-user-reading-view)
* Content Source: [powerbi-docs/consumer/end-user-reading-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-reading-view.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TheKiltyOne. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @TheKiltyOne ,
Please let me know which article has the broken link.  
Thank you.

**Comment by mihart** [comment]
Hi @TheKiltyOne, 
Thank you for your feedback.  I haven't heard back from you so am closing this Issue.  If you can provide more details, please create a new Git Issue with the URLs for the page with the broken link and the page it links to.
All the best,
The DOCS team
