### ISSUE TITLE
Remove preview from the screenshots

### ISSUE THREAD

**Issue by feridunkadir** [MicrosoftDocs/powerbi-docs#4084]
[Enter feedback here]

The screenshots all show the Power Automate action for Power BI as preview. 

I suggest adding a statement in the main article that the feature is now GA or update the screenshots.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68b5de8f-c5ce-8566-dfe3-38db0e98d169
* Version Independent ID: bd701ba6-98f5-0b12-0c0b-73206ae6d7ad
* Content: [Integrate Power BI data alerts with Power Automate - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-flow-integration)
* Content Source: [powerbi-docs/collaborate-share/service-flow-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-flow-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @feridunkadir. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @feridunkadir -- guess what? The feature is still in preview, and no GA date to share date. Thanks for asking!
