### ISSUE TITLE
Gen1 terminology for parallel refreshes used

### ISSUE THREAD

**Issue by tarekbanims** [MicrosoftDocs/powerbi-docs#4086]
[Enter feedback here]
https://learn.microsoft.com/en-us/power-bi/developer/embedded/move-to-production#capacity-specifications

We are using Gen1 refresh parallelism here, we should change this to Gen2 here https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is#capacities-and-skus

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe7888c3-14b3-8120-7fa5-80af7d1febba
* Version Independent ID: af40d3fb-5ed4-fa37-0e1d-afd01b1faf1e
* Content: [Power BI embedded analytics overview - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-analytics-power-bi#embed-for-your-organization)
* Content Source: [powerbi-docs/developer/embedded/embedded-analytics-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-analytics-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tarekbanims. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @tarekbanims, thanks for pointing this out. The table has been updated and should be live in a day or so.
