### ISSUE TITLE
Can I use Paginated reports with type A Embedded SKU as described here 

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/powerbi-docs#4088]
Can I use Paginated reports with type A Embedded SKU as described here 

](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq)

if yes, please fix the current article, because it says only P and EM SKUs can be used for embedding Paginated reports.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d53eef67-91ce-691f-5e29-515d553023f6
* Version Independent ID: f6723c69-a08d-42af-6a74-33f22bc55fba
* Content: [Embed paginated reports in your Power BI embedded analytics application - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-paginated-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ed7257. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks, for your question, @ed7257. 
It depends on the scenario. [Step 2 - Create a capacity](https://learn.microsoft.com/power-bi/developer/embedded/embed-paginated-reports?tabs=customers) has two tabs. The "Embed for your customers" tab explains that you can use A SKUs and Power BI Embedded. If you're embedding for your organization, you need Power BI Pro or Premium which means you must use either an EM or P capacity.
I hope this helps.
