### ISSUE TITLE
Embedding paginated reports with A type SKUs

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/powerbi-docs#4089]
Could you please verify that it is possible to embed paginated reports using A SKU. 
this option is not listed on this page https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78655418-d567-8c78-455d-913fab3277a5
* Version Independent ID: 0729c97e-74d7-ac7a-26b8-54b9a7d18dbd
* Content: [Paginated reports in Power BI: FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-faq.yml)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ed7257. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @bishalgoswami. Yes, you can embed paginated reports with A SKUs, as shown in the table here: [Create a capacity - embed for your customers](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers#step-2---create-a-capacity). I'll update the table in the *embed for your organization* tab to reflect this as well.
