### ISSUE TITLE
[Glitch] :: Evaluation Context / Ad-hoc highlighting / Oct. 2018 Release

### ISSUE THREAD

**Issue by joerobert06** [MicrosoftDocs/powerbi-docs#409]
Hello,
I just posted this concern on the community site regarding ad-hoc highlighting. Your support is greatly appreciated. 

https://community.powerbi.com/t5/Desktop/Glitch-Evaluation-Context-Ad-hoc-highlighting-Oct-2018-Release/td-p/562546

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21d0aaa2-486e-f7fa-522f-5647ad31c076
* Version Independent ID: 2ce1f307-1258-1fd6-ddcf-9224bafc4444
* Content: [Understand how visuals interact in a report (for report consumers) - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-interactions)
* Content Source: [powerbi-docs/consumer/end-user-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-interactions.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @joerobert06 -- you did well to post to the community site! If that doesn't pan out, you can contact support by going to https://support.powerbi.com.
