### ISSUE TITLE
Small error in the code getValue code

### ISSUE THREAD

**Issue by tchin94** [MicrosoftDocs/powerbi-docs#4091]
Hi, a small error in the code displayed on this page.

In the getValue function, the line 
`let property: T = object[propertyName];`
should be 
`let property: T = <T>object[propertyName];`

This is correct in the [source code](https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/blob/master/src/objectEnumerationUtility.ts) but not on the documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-bar-chart?tabs=CreateNewVisual)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tchin94. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @tchin94. I fixed this, and it should be live in a day or so.
