### ISSUE TITLE
download link for Report Server September 2022 goes to May 2022

### ISSUE THREAD

**Issue by gwalkey** [MicrosoftDocs/powerbi-docs#4092]
[Enter feedback here]

download link for Report Server September 2022 goes to May 2022
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Change log for Power BI Report Server - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @jtarquino
* Microsoft Alias: **jaimeta**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gwalkey. This issue has been assigned to the doc author for review.
