### ISSUE TITLE
Incorrect link "Automatic Swagger schema generation in the Deploy models with the Azure Machine Learning"

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/powerbi-docs#4093]
[Enter feedback here]
The link with instructions to generate swagger schema is pointing to article that does not contain the information on this topic
(there is no subsection "Automatic Swagger schema generation in the Deploy models with the Azure Machine Learning"
Please point to the right page 

"This schema file must be included in the deployed web service for Machine Learning models. To automatically generate the schema for web service, you must provide a sample of the input/output in the entry script for the deployed model. Please see the subsection on [(Optional) Automatic Swagger schema generation in the Deploy models with the Azure Machine Learning](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-deploy-managed-online-endpoints) service documentation."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 301c08b2-df76-b3b0-5035-7413d8b9d447
* Version Independent ID: f6d974e6-d13a-0413-6d50-3b5a93447600
* Content: [Use Machine Learning and Cognitive Services with dataflows - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-machine-learning-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @morcinim. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated the document, thanks for your feedback.
