### ISSUE TITLE
Slicer Orientation/Horizontal Option Missing

### ISSUE THREAD

**Issue by Rissa1008** [MicrosoftDocs/powerbi-docs#4094]
Hello Team,
This new update that I just recently downloaded: Version: 2.109.844.0 64-bit (September 2022), does not have a General option in the visualization edits for slicers. I have reviewed all the other drop downs and I cannot locate anything that allows me to change a slicer orientation to horizontal. Please see the attached, Is it located through somewhere else?
Thank you.

<img width="137" alt="Slicer" src="https://user-images.githubusercontent.com/114763106/193315583-395e65c3-f609-424b-965c-be77f73b687b.PNG">

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Rissa1008. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Rissa1008. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
