### ISSUE TITLE
Would like to see other visual properties explained including color

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4095]
Specifically, I'm looking into the Color field in the Visualizations pane. Not changing the color from the symbol style settings, but from the Color field in the visualization pane. I see that the Size field  is explained, but did not see anything about color. Also, what are the different functions between the color settings in symbol style and color settings in visualizations pane?

_From the Fields pane, drag a measure to the Size bucket to adjust how the data is shown. In this example, we're using Sales > Last Year Sales._
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Create an ArcGIS map in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. Looks like this is product feedback and a feature request, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
