### ISSUE TITLE
The recent issue on Usage Metrics not working in Power BI service

### ISSUE THREAD

**Issue by sarava8304** [MicrosoftDocs/powerbi-docs#4097]
Hi Team, 
I dont see the issue on Usgae metrics not working in Power BI service since 9 Sep22, and no ETA mentioned anywhere on this bug.

https://community.powerbi.com/t5/Issues/We-are-unable-to-view-latest-usage-metrics-data-for-any-of-the/idc-p/2809812#M86157
Thanks,
Saravanan R
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sarava8304. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @sarava8304 , 
I've emailed the Known Issues team and will update you when I hear back.

**Comment by mihart** [comment]
Hi @sarava8304 ,
This is indeed a known issue and is being added to the known issues list this week.  Thanks for the reminder,
