### ISSUE TITLE
Linking Power BI to Azure Data Lake Storage

### ISSUE THREAD

**Issue by elfigha** [MicrosoftDocs/powerbi-docs#4098]
[Enter feedback here]
The Azure Admin created a Data Lake Gen2. X is the name of this Data Lake
The Azure Admin add me as owner of this Data Lake
In Power BI PPU, where I'm admin, I created a PPU workspace Y 
Me and the Azure Admin we checked all the condition in the following link: 
[https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#prerequisites](url)
However, 
1-I'm not able to link the Workspace to the Data Lake
2-if I add the Azure Admin as Admin in the workspace, he is able to link the workspace to the Data Lake
So I believe that the prerequisites listed in the above URL are wrong
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfigha. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback, as the pre-reqs have been validated by engineering. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
