### ISSUE TITLE
Create a responsive slicer you can resize in Power BI-Clear Filter

### ISSUE THREAD

**Issue by SarabjitSinghSethi** [MicrosoftDocs/powerbi-docs#410]
Only issue which i found in this is clear selection button is not appearing while using the horizontal orientation in slicer.Could you please look and fix it or any solution is available ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eed3feb5-5b30-8f94-9a3d-7a9574490d9c
* Version Independent ID: 85862cdb-9e39-2427-22de-430080febee9
* Content: [Create a responsive slicer you can resize in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-slicer-filter-responsive)
* Content Source: [powerbi-docs/power-bi-slicer-filter-responsive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-slicer-filter-responsive.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @SarabjitSinghSethi -- Hmmm. I find if I make the slicer too short, then the Clear button is hidden behind one of the values in the slicer. You see what I mean? Try making the slicer taller and see if you can see the Clear button.

**Comment by maggiesMSFT** [comment]
Hi, @SarabjitSinghSethi -- I hope that helped. I'm closing this issue. Feel free to open it again if you have further questions!
