### ISSUE TITLE
Some questions about download report as pbix file

### ISSUE THREAD

**Issue by a2o2juzi** [MicrosoftDocs/powerbi-docs#4100]
[Enter feedback here]
Hi team,
I use the rest Api below to download report as pbix file:
GET https://api.powerbi.com/v1.0/myorg/groups/{groupId}/reports/{reportId}/Export
Sometimes it fails. It may be that the report does not support downloading or for other reasons, but I cannot know the specific reason from the response. Does your team plan to add a clear message or error code to indicate unsupported download?
I hope to check whether a report supports download as pbix file through the API Is there a plan to support this?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @a2o2juzi. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @a2o2juzi -- I'm checking and will get back to you. Some folks are out on holiday so response may be delayed. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @a2o2juzi -- a quick response instead! The product team suggests opening a ticket, https://community.powerbi.com/t5/Issues/idb-p/Issues
Hope that helps!
