### ISSUE TITLE
Dynamic M Query Parameters with Analyze in Excel

### ISSUE THREAD

**Issue by LoisLoriot** [MicrosoftDocs/powerbi-docs#4103]
Hi,

This feature is not working when accessing the dataset in Excel. Maybe to add a note about it on the considerations and limitations.

https://community.powerbi.com/t5/Issues/Dynamic-M-query-parameters-doesn-t-work-in-analyze-in-excel/idi-p/2009990

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LoisLoriot. This issue has been assigned to the doc author for review.

**Comment by LoisLoriot** [comment]
Hi @davidiseminger, @bishalgoswami, any update on this please ?

**Comment by davidiseminger** [comment]
Thanks for your input, I've added a note about this limitation.
