### ISSUE TITLE
Outdated compared to the newly released interface

### ISSUE THREAD

**Issue by Teckfahimkanji** [MicrosoftDocs/powerbi-docs#4104]
Hi,

This page needs to be updated to reflect the new UI

Cheers,

Fahim.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Teckfahimkanji. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Teckfahimkanji, thanks for your comment. Many of our articles have gone through a refresh and I believe the page now reflects the current UI. Thanks for taking the time to reach out!
