### ISSUE TITLE
Correction needed (I think)

### ISSUE THREAD

**Issue by rjoboyle** [MicrosoftDocs/powerbi-docs#4105]
[Enter feedback here]

Article says
"In your tenant, go to the data hub in Power BI Desktop"

Think it should be changed "Power BI Service"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74430e48-5764-9eff-7410-26ab2c400917
* Version Independent ID: 74430e48-5764-9eff-7410-26ab2c400917
* Content: [Access shared datasets in Power BI as a guest user from an external organization (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-dataset-external-org-share-view)
* Content Source: [powerbi-docs/collaborate-share/service-dataset-external-org-share-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-dataset-external-org-share-view.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rjoboyle. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @rjoboyle,

You're right, this is a typo - thanks for pointing this out.

I fixed this typo and it'll show on the website soon.

Thanks,

Kesem
