### ISSUE TITLE
Content to Add: PPU Data Host

### ISSUE THREAD

**Issue by DataGuru311** [MicrosoftDocs/powerbi-docs#4106]
[It would be useful for this page, about Premium Per User, to detail precisely where data will get stored or hosted. Would it be hosted on the same as the Home Tenant, like Pro Workspaces, or does it have any sort of capabilities for choosing a Geography, like Premium Per Capacity.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Version Independent ID: 86beb6b6-cc13-ca11-8caa-ddd4b0c0fe29
* Content: [Power BI Premium Per User - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq)
* Content Source: [powerbi-docs/enterprise/service-premium-per-user-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-per-user-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DataGuru311. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @DataGuru311,

PPU shares one capacity among all users, as described in the first two bullets in [Considerations and limitations](https://learn.microsoft.com/power-bi/enterprise/service-premium-per-user-faq#considerations-and-limitations).

Hope this helps,

Kesem

**Comment by DataGuru311** [comment]
Hello Kasem,

When reading those bullet points, only the second tries to hint at that,
but there really is no definitive explanation that says a PPU storage will
be on the Default/Home Tenant where the Shared Workspaces are hosted the
same as when using Pro Licensing.

Thank you
Andrew
