### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'Kind')  

### ISSUE THREAD

**Issue by J4tkins** [MicrosoftDocs/powerbi-docs#4107]
Attemping to follow text analysis tutorial and keep hiting this error:

TypeError: Cannot read properties of undefined (reading 'Kind')
    at Re (https://uk.prod.powerquery.microsoft.com/MashupEditor/scripts/qegsb.qe.dpfv.bmfv.c2b757d1115da0666d6b.bundle.js:1:60393)
    at async https://uk.prod.powerquery.microsoft.com/MashupEditor/scripts/qegsb.qe.dpfv.bmfv.c2b757d1115da0666d6b.bundle.js:1:64332
    at async https://uk.prod.powerquery.microsoft.com/MashupEditor/scripts/qegsb.qe.dpfv.bmfv.c2b757d1115da0666d6b.bundle.js:1:63383

The tutorial doesnt explain how to deal with this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a614670c-d6fb-2933-ca40-1be5901beb27
* Version Independent ID: f7f97531-c634-e7c0-8280-26b1c7931f47
* Content: [Tutorial: Use Cognitive Services in Power BI (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-tutorial-use-cognitive-services)
* Content Source: [powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @J4tkins. This issue has been assigned to the doc author for review.

**Comment by wangfei13** [comment]
@bishalgoswami  Is there any update? I got the same issue today

@J4tkins  Did you got a workaround?

**Comment by wangfei13** [comment]
any update???

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
