### ISSUE TITLE
User Mapping

### ISSUE THREAD

**Issue by rajj281** [MicrosoftDocs/powerbi-docs#411]
Under Ad lookup mapping for step 4 where there is screenshot of the ad attribute mapping. The "AADEmail" should be "mail" could the document be updated as it is bit confusing 

https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-ssas#ad-lookup-mapping

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa43934-b1b5-2227-9f9e-cfce1801b659
* Version Independent ID: 0d169b19-7c1c-b37d-3915-b8c55da6f0ff
* Content: [Manage your data source - Analysis Services - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-ssas#ad-lookup-mapping)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-ssas.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-enterprise-manage-ssas.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @rajj281. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by mgblythe** [comment]
I updated the screenshot to use "Email" which I believe is the correct value for this option. Feel free to reopen if there's a problem with this fix. Thanks!
