### ISSUE TITLE
Sales Quick Measure Table

### ISSUE THREAD

**Issue by datageeq** [MicrosoftDocs/powerbi-docs#4112]
Hi, Please how do I derive the "Sales" Quick Measure Table in the Retail Analysis sample for PowerBI (https://learn.microsoft.com/en-us/power-bi/create-reports/sample-retail-analysis#get-the-pbix-file-for-this-sample).

@maggiesMSFT, @davidiseminger @v-kents.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @datageeq. This issue has been assigned to the doc author for review.
