### ISSUE TITLE
The Navigator window no longer displays the suggested table "Ranking of best and worst states for retirement"

### ISSUE THREAD

**Issue by gdeckler** [MicrosoftDocs/powerbi-docs#4113]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gdeckler. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated that example. Thanks!
