### ISSUE TITLE
Rest API Enhanced Refresh Docs Incomplete

### ISSUE THREAD

**Issue by thunter05** [MicrosoftDocs/powerbi-docs#4114]
Hi!

**CONTEXT - REST API DOCS EXAMPLES NEEDED**
My company is using the Power BI Rest API to refresh our dataset so we can pick up forecasted periods. The documentation on the "refreshes" body parameters is a little hard to understand. It would be great to have multiple examples of different combinations of body parameters that are valid.

**PROBLEM - INCREMENTAL REFRESH NOT HITTING OUR DATABASE?**
Our current issue is that is we use the parameters below then we noticed that Power BI is not pulling data from our tables. Sometimes we see the queries against our database (Snowflake) and sometimes nothing happens.

![image](https://user-images.githubusercontent.com/59625778/194877329-ad43fe5c-17af-4ab0-a749-ee7e0b9397a5.png)

**PROBLEM - CHANGING TYPE TO FULL BUT REFRESH TIMES OUT WITH CRYTIC ERROR**
So we are trying to run "Full" refreshes using our incremental refresh policy. When we run this we see Power BI query Snowflake the way we want, but the refresh seems to time out with an error that we do not understand. Note that if we run the incremental refresh in Power BI service that the refresh complete is about 10 minutes. So this seems to be an issue with the REST API.

![image](https://user-images.githubusercontent.com/59625778/194875954-262c099d-6c69-4b06-8065-a66fc11c2ad7.png)

![image](https://user-images.githubusercontent.com/59625778/194877079-3db1cd3d-5b52-41e0-b100-9bc5eabee584.png)

**SOLUTION?**
We are trying to figure out what is the right parameters to run our incremental refreshes. Both options above are not working for us.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thunter05. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @thunter05. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
