### ISSUE TITLE
Preview link

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4117]
Regarding 

>[Intro to datasets across workspaces (preview)](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-across-workspaces)

According to the destination page this feature is now GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5405aff7-0d96-0b9d-c389-dd72a367e415
* Version Independent ID: 0f1bf43c-d51e-c7e8-6250-c8ee8239183e
* Content: [Dataset impact analysis - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-dataset-impact-analysis)
* Content Source: [powerbi-docs/collaborate-share/service-dataset-impact-analysis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-dataset-impact-analysis.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @VitalyMCT, it looks like this issue has been resolved, so I am closing it. Feel free to reopen if necessary. Thanks.
