### ISSUE TITLE
Clarification on tenant / subscription support for this feature

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4118]
In the bring your own storage we call out in the Prerequisites that "The storage account must be created in the same Azure Active Directory tenant as the Power BI tenant." 
https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration#prerequisites

and is that the same for configuring and using Azure Log Analytics, I am assuming "Yes" but we do not seem to call that out any place. In the considerations and limitations, it mentions "Azure Log Analytics doesn't support tenant migration." which I am not sure what that means exactly, but maybe hinting at that this feature only works in same tenant?
https://learn.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-overview#considerations-and-limitations

If we could clarify this that would be great, thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ef7e7eb5-b6a5-7255-acb1-45f93e39bf17
* Version Independent ID: d616d078-a8b9-0a52-7502-fc528a214f95
* Content: [Using Azure Log Analytics in Power BI (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-overview)
* Content Source: [powerbi-docs/transform-model/log-analytics/desktop-log-analytics-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/log-analytics/desktop-log-analytics-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
