### ISSUE TITLE
Unneeded question marks at Step 11

### ISSUE THREAD

**Issue by molnarj** [MicrosoftDocs/powerbi-docs#412]
There are unneeded quotation marks around the "this.visualSettings.circle.circleColor" expression.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f573b62f-4028-ce65-b5ae-a4115ee1bcd1
* Version Independent ID: 1cedde6a-9245-42da-c25e-83706f551c79
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @molnarj.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by markingmyname** [comment]
@molnarj Sorry for the delayed response. Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@molnarj Thank you again for bringing this to our attention.  I have made the appropriate changes to the article.  The changes should go live in a few days.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
