### ISSUE TITLE
Supported data sources

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4120]
Regarding

>When working with DirectQuery SQL-based sources, the Performance Analyzer only shows queries for the following data >sources:
>
>   SQL Server
>   Oracle
>   Teradata

This list does not seem to be current. For example, Azure SQL Database connections also show queries.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3422402-b1e9-db0c-cbb6-4dd3eaa528c4
* Version Independent ID: 124204c3-bbcb-f705-c88f-90c81be27a2f
* Content: [DirectQuery model troubleshooting in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-troubleshoot)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-troubleshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-troubleshoot.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated this article since you commented. Thanks!
