### ISSUE TITLE
Please move or rephrase metrics related limitations

### ISSUE THREAD

**Issue by sergeigms** [MicrosoftDocs/powerbi-docs#4121]
Current version of the MG doc has Metrics (formerly goals) listed as last bullet in Considerations and Limitations section.
It is our understanding that Metrics in fact can be setup on MG capacity, but the data and metadata will be hosted in tenant home region.  Can we confirm with PM owners and move metrics under this heading "These items remain in the home region for the tenant:" to follow the same pattern for the artifacts that remain in the home region?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e1ae590-933f-bf65-888e-03dbf0ddc252
* Version Independent ID: ae8f54bb-5fdb-a071-528d-169b4b766be6
* Content: [Multi-Geo support for Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-premium-multi-geo)
* Content Source: [powerbi-docs/admin/service-admin-premium-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-premium-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sergeigms. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @sergeigms, I started an internal email for this.
