### ISSUE TITLE
Configuring enabling / disabling custom visuals and uncertified visuals via Microsoft Intune

### ISSUE THREAD

**Issue by KrisMedici** [MicrosoftDocs/powerbi-docs#4122]
Hi, 

This document explains how to disable custom, and uncertified visuals via AD Group Policy, but we use MS Intune in our organisation (as per MS recommendation). 

Where can we find the instructions on how to carry out the above activity in MS Intune?

Thanks
Kris

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67bf91c4-cbf2-0b4c-2532-4ade0d56afee
* Version Independent ID: 687beece-c5e9-070f-9794-fc6569bb09b0
* Content: [Organizational visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/organizational-visuals#feedback)
* Content Source: [powerbi-docs/admin/organizational-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/organizational-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KrisMedici. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @KrisMedici. I'll look into this and get back to you.

**Comment by mberdugo** [comment]
Sorry for the delayed response, @KrisMedici. As far as I can tell, this question relates to group policies.
Here are a couple of links about setting group policies in Intune. I'll add them to the doc.
[Use Windows 10/11 templates to configure group policy settings in Microsoft Intune](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fconfiguration%2Fadministrative-templates-windows&data=05%7C01%7Cmonaberdugo%40microsoft.com%7C454b16c48e2d4fa1e9c308dab77f9175%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638024055797214312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FrCacG9xgb1EB01r%2FMTtixBrVnzkJb5q3GFUFeIiDqY%3D&reserved=0)
[Tutorial: Use the cloud to configure group policy on Windows 10/11 devices with ADMX templates and Microsoft Intune](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fconfiguration%2Ftutorial-walkthrough-administrative-templates&data=05%7C01%7Cmonaberdugo%40microsoft.com%7C454b16c48e2d4fa1e9c308dab77f9175%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638024055797214312%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Rpd8RLcWk2Y1z6EuijmyG%2FY6Ejr3dEgzauEhe%2FrNaOY%3D&reserved=0)
Hope this helps.
