### ISSUE TITLE
Schema and column descriptions for Power BI Rest API's

### ISSUE THREAD

**Issue by KrisMedici** [MicrosoftDocs/powerbi-docs#4124]
Hi there, 

When can I find the schema for the Power BI Rest API's?

For instance, I've extracted the data from the admin API called 'Activity Events' however there are over 100 columns which I would like to know the schema for, as well as column descriptions (what is the column doing etc?)

Thanks
Kris

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KrisMedici. This issue has been assigned to the doc author for review.

**Comment by KrisMedici** [comment]
Hi @KesemSharabi 

Thanks for this. Sadly it doesn't give me what I need as it is just a sample output of the data from the API. 

What I'm intrerested in, is the schema and column descriptions. For example, what does the column 'CreationTime' mean, and what are the characteristics of this field i.e. does it only show times in UTC, or based on tenant region. Or what does 'Workload' mean? I appreciate some of these are super self-explanatory such as 'Activity' but to use these effectively I don't want to guess. 

Thanks
Kris

**Comment by KesemSharabi** [comment]
Hi @KrisMedici,

I'm afraid we don't have this information at the moment.  

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

I'll also consider adding this to our documentation in the future.

Kesem

**Comment by KrisMedici** [comment]
Thanks for clarifying, Kesem.

All the best.

Kris
