### ISSUE TITLE
Markdown issue in the section "next steps" (missing bracket)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftDocs/powerbi-docs#4126]
[Enter feedback here]

Markdown issue in the section "next steps" (missing bracket)

* Get a Power BI visual certified](power-bi-custom-visuals-certified.md)

Should become

* [Get a Power BI visual certified](power-bi-custom-visuals-certified.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 746e3f8f-68fd-b7d2-f61e-6bb8daa63ea4
* Version Independent ID: 50a481ef-6d50-cec0-e21b-2deab73e73b3
* Content: [Organization visuals in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-organization)
* Content Source: [powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/power-bi-custom-visuals-organization.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @weslbo. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks, @weslbo. Fixed it!
