### ISSUE TITLE
Overload email notifications - showing screenshot of Gen1 notification vs Gen2 now

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4127]
The picture in the documentation page for "Overload email notifications" is what was received while customers were on Gen1 capacity versus the more generic one that gets sent out now with Gen2. All of the details are not included now regarding long running queries, etc. and we don't provide the additional capacity utilization information anymore. This screenshot is confusing for customers that are using Gen2 now and don't get this information anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2c1d174-599a-d84e-d309-0987f24ef41f
* Version Independent ID: 9e4735be-c98c-5887-3414-8413f5cb2881
* Content: [Service interruption notifications - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-interruption-notifications#capacity-and-reliability-notifications)
* Content Source: [powerbi-docs/admin/service-interruption-notifications.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-interruption-notifications.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@denglishbi - the functionality described in this article is separate from the Gen2 notifications, so I'm closing this issue. However, your feedback did draw my attention to the fact that the article is ready for an update and I am adding a note to the related work item asking to further clarify the different notification options. Thanks for the feedback!
