### ISSUE TITLE
Page has wrong title in the index

### ISSUE THREAD

**Issue by dbrownems** [MicrosoftDocs/powerbi-docs#4129]
Title should be "Create page and bookmark navigators" in the index like it is on the page.

![image](https://user-images.githubusercontent.com/28908684/196468343-d0ec9918-1b27-40f6-964f-c9f1cdcc34f4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Version Independent ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Content: [Create page and bookmark navigators - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/button-navigators.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/button-navigators.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dbrownems. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @dbrownems,

Thank you for pointing out that the name of the article in the table of contents wasn't correct. I fixed this error and it'll shortly appear on the website.

Thanks again,

Kesem
