### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by bneelon85** [MicrosoftDocs/powerbi-docs#413]
I was following this tutorial today and once I get to step 7, it goes through the import process but then only brings up the tables available to import. It doens't provide the automatically created Power BI Dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by bneelon85** [comment]
Nevermind...I was trying to do it through Power BI Desktop. Once I did it in app.powerbi.com it worked as expected.

**Comment by maggiesMSFT** [comment]
Thanks for letting us know, @bneelon85 -- glad it worked out!
