### ISSUE TITLE
Platform "Not specified"

### ISSUE THREAD

**Issue by floemmel** [MicrosoftDocs/powerbi-docs#4131]
Hi. 

Could you please describe in more detail what the different categories (Legend items) in the visual with Distribution and Platform mean? Specifically there is an item "Not specified" for which I couldn't find an explanation. In what cases is this selected, what is the difference to "Other" and how can we understand what it means? 
![image](https://user-images.githubusercontent.com/49025350/196631540-81c13620-b5f4-42be-9a67-1790f5b379fd.png)

Thank you! 
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in workspaces (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#considerations-and-limitations)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @floemmel. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @floemmel, I'm moving this issue to our work item backlog for better tracking and consideration and closing it here now. To get a faster answer until the docs are updated, you might try the [Power BI Community](https://community.powerbi.com/).
