### ISSUE TITLE
OK button is greyed out

### ISSUE THREAD

**Issue by rderidder-lda** [MicrosoftDocs/powerbi-docs#4133]
this page does not mention what might be the issue, if when selecting the column to be the date column, and it even passes validation.. the OK button is still greyed out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09750051-75cf-7829-b70b-8912f822ea8c
* Version Independent ID: b761024d-5166-47db-9c19-410073e5f46e
* Content: [Set and use date tables in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-date-tables#setting-your-own-date-table)
* Content Source: [powerbi-docs/transform-model/desktop-date-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-date-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rderidder-lda. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post, this sounds like a technical and feature question best answered by the community or support. If you need technical support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
