### ISSUE TITLE
Links to download of older versions of PBI installation files don't work

### ISSUE THREAD

**Issue by bobokdalibor** [MicrosoftDocs/powerbi-docs#4134]
I've tried to download older versions of PBI (Apr 2022 in this case) and none of the links work. It returns 404 error, Page not found.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bobokdalibor. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @bobokdalibor, which document are you referring to?
