### ISSUE TITLE
"Visualize this view" in Power BI allows users to Export to Excel from Power BI service with data generated from dataverse

### ISSUE THREAD

**Issue by frankitecho** [MicrosoftDocs/powerbi-docs#4136]
Is there an option to restrict the user from their generated Quick Summary workspace from Exporting the data in Excel?
The security in dataverse restriction for Export to Excel seems to be bypassed when the user launches the Visualize this view. In the generated summary report, once the report is saved to their My Workspace, allows them to Export to Excel as they are the owner of the workspace.
Am I missing something in the security?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa2a0fbc-0b85-9b61-d5a6-af09b1e11608
* Version Independent ID: fa2a0fbc-0b85-9b61-d5a6-af09b1e11608
* Content: [Visualize your data quickly from Power Apps and Dynamics 365 apps - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/dynamics-quick-create-report)
* Content Source: [powerbi-docs/create-reports/dynamics-quick-create-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/dynamics-quick-create-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @frankitecho. This issue has been assigned to the doc author for review.

**Comment by amandariveraMSFT** [comment]
Hi @frankitecho thanks for reaching out! 

Users are able to download the data, but as we use SSO & DQ for the autogenerated report, the data they can download is only the data they have permission to in Dynamics. They can’t get access to data they normally wouldn't be able to see. 

If you want to restrict the ability to download to Excel on the Power BI side, you can manage who can and cannot download data through the Power BI Admin portal.

**Comment by frankitecho** [comment]
Hi @amandariveraMSFT thanks for the response.

We were able to apply a restriction in the Power BI Admin Portal with a custom security group. We targeted users for the dataverse generated workspaces to restrict the Quick Summary workspaces and worked as designed.

**Comment by maggiesMSFT** [comment]
@frankitecho -- I'm working on an update to the article, waiting for sign-off from @amandariveraMSFT.
Thanks!
