### ISSUE TITLE
Misleading information on ability to embed report to SharePoint

### ISSUE THREAD

**Issue by mireQT** [MicrosoftDocs/powerbi-docs#4137]
This sentence suggests that user with free Power BI can use described procedure to copy link and embed it into SharePoint for reports in Premium Capacity:

_"Users need a Power BI Pro or Premium Per User (PPU) license, unless the report is hosted in a [Power BI Premium capacity (EM or P SKU)](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is). In that case, users only need a free Power BI license to view reports embedded in Sharepoint Online."_

Unfortunately, the free Power BI user does not have this option "Embed Report" in the "File" menu...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed a report web part in SharePoint Online - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-embed-report-spo)
* Content Source: [powerbi-docs/collaborate-share/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-report-spo.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mireQT. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @bishalgoswami -- I guess the key word in that sentence is *view*:
"... users only need a free Power BI license to *view* reports embedded in Sharepoint Online."
I've reworded it to make it clearer. Change should be live tomorrow afternoon Pacific time.
Thanks!
