### ISSUE TITLE
Max memory per dataset

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4138]
Is "Max memory per dataset" the same as "Model size limit" from this page: https://powerbi.microsoft.com/en-us/pricing/ ?

If not the same, how are they different?

If they are the same, why does Microsoft use 2 different terms to refer to the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity?tabs=gen2#sku-memory-and-computing-power)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @djurecic0. I'll confirm the correct terminology and clarify the document accordingly.

**Comment by mberdugo** [comment]
Hi @djurecic0. Both phrases mean the same thing. It seems that the marketing people and the developers were using different terms to refer to the same thing. I'll update the documentation. Thanks for pointing this out.

**Comment by djurecic0** [comment]
Thank you for your reply- this is helpful.

I have a similar question that may be outside of the scope of this conversion, but may be related to marketing and developers using different terms.

On the pricing page (https://powerbi.microsoft.com/en-us/pricing/), the Model Size limit for Power BI Premium Capacity is listed as 400 GB.

However, this is the limit only for P5 Premium Capacity (referenced here: https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is#capacities-and-skus) and not the limit for P1-P4. There is no footnote or reference to P5 on the pricing page.

To me, a plain reading of the pricing chart below means that any version (P1-P5) of premium capacity has a limit of 400GB which is not correct. It also looks like Premium Capacity always has a greater model size limit than Premium Per User, which is not correct. In fact, Premium Per User has the same max model size as Premium Capacity P3 and greater max model size than P1 and P2.

Showing Premium Capacity with a 400GB limit and no explanation or disclaimer is confusing and I believe misleading, even if it could be considered technically true.

I believe it would be more appropriate to list the max model size for Premium Capacity as 25 - 400 GB.

I know you are not in charge of the pricing page, but if you are in agreement with the statements above, I’d appreciate anything you could do to have this addressed.

If the statements above are not correct, I welcome correction and any additional information. I am also trying other avenues to reach Microsoft Sales for any comments on this issue.

Thanks,
Dean Jurecic



***@***.***

***@***.***


***@***.***
