### ISSUE TITLE
Size considerations question

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4139]
I'm a little confused about how this section relates to other PBI documentation.

For example, [this page](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity?tabs=gen2#sku-memory-and-computing-power) says that the Max memory per dataset is 25 GB for P1, 50GB for P2 and 100 GB for P3.

Can you please explain how these limits and suggested .pbix file sizes are related? It seems like P1 can handle up to a 25 GB 
dataset, but P1 is recommended only for up to 3GB .pbix file. 

the other page does say this "The Max memory per dataset (GB) column represents an upper bound for the dataset size. However, some memory must be reserved for operations such as dataset refreshes and queries. The maximum dataset size permitted on a capacity may be smaller than the numbers in this column."

But it seems like there is a big difference between 25GB theoretical maximum and 3GB .pbix file recommendation. Is Microsoft recommending using only 12% of the maximum?

The use case for this is that I am trying to recommend to clients which version of PBI to use.

SKU | Size of .pbix
P1/A4 | Up to 3 GB
P2/A5 | Up to 6 GB
P3/A6, P4/A7 and P5/A8 | Up to 10 GB

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

The information in [What is Power BI Premium?](https://learn.microsoft.com/power-bi/enterprise/service-premium-what-is) is outdated. We'll soon delete this article. Please refer to [What is Power BI Premium Gen2?](https://learn.microsoft.com/power-bi/enterprise/service-premium-gen2-what-is) instead.

I hope this will clarify things,

Kesem

**Comment by djurecic0** [comment]
@KesemSharabi Thank you, this is helpful.
