### ISSUE TITLE
'Extract Tables Using Examples' Button Missing

### ISSUE THREAD

**Issue by steve-oo** [MicrosoftDocs/powerbi-docs#414]
I have just discovered Excel Power Queries and after trying out a few examples from various ''You Tube videos, I was impressed. I then got adventurous and tried to pull data from a selected web site, however, all I get is the folder & document icons as shown in the 'Navigator' dialog box. Hence the 'Connect to a Web page by example' seemed perfect to resolve my issue.  Unfortunately in my version of Excel/Power Query the 'Extract table using example' button is not visible in my dialog box. Am I missing something and is there a way forward? Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe95746-2616-66d1-cb63-7d62bc27c991
* Version Independent ID: e1e479f5-1fe0-3b55-f32f-153fa6197286
* Content: [Extract data from a Web page by example in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-to-web-by-example)
* Content Source: [powerbi-docs/desktop-connect-to-web-by-example.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-to-web-by-example.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @steve-oo . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. If you're using Excel, try support.office.com as well.
