### ISSUE TITLE
Capacity nodes- Memory

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4140]
Is "Memory" in this table the same as "Model Size Limit" on [this page ](https://powerbi.microsoft.com/en-us/pricing/) or "Max memory per dataset" on [this page](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity?tabs=gen2#sku-memory-and-computing-power)?

If they are not the same, how are they different?

If they are the same, why are 3 different terms used?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

The information in [What is Power BI Premium?](https://learn.microsoft.com/power-bi/enterprise/service-premium-what-is) is outdated. We'll soon delete this article. Please refer to [What is Power BI Premium Gen2?](https://learn.microsoft.com/power-bi/enterprise/service-premium-gen2-what-is) instead.

I hope this will clarify things,

Kesem

**Comment by djurecic0** [comment]
@KesemSharabi Thank you, this is helpful.
