### ISSUE TITLE
Concurrent Page limitation - 429 error - thresholds for throttling

### ISSUE THREAD

**Issue by davideldersveld** [MicrosoftDocs/powerbi-docs#4142]
Customer is experiencing limits exporting paginated reports (429 error -- throttling evident). Can we amend Considerations and Limitations section to include the following?

A) be clear that the concurrent page limits for paginated reports differ from what is stated on the Power BI report page for different Premium tiers (https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to#considerations-and-limitations).

B) publish limits specific to paginated reports so that customers will not assume paginated limits will be the same as Power BI report limits when it comes to concurrent pages

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 53195679-7a58-c111-3814-fccf4cc38854
* Version Independent ID: ee9e8e36-45e1-8029-4f9a-b1d41ef4a3f1
* Content: [Export Power BI embedded analytics paginated reports API - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-paginated-report)
* Content Source: [powerbi-docs/developer/embedded/export-paginated-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/export-paginated-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davideldersveld. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @davideldersveld. Thanks for your question. I updated the document with a section discussing concurrent requests. I didn't give an actual number because the number is constantly being reevaluated and subject to change. I hope this helps.

**Comment by davideldersveld** [comment]
Thank you! Having the distinction plainly stated goes a long way, and I understand that not wanting to publish evolving limits. Will set expectations with customer.
