### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by jamezhangMS** [MicrosoftDocs/powerbi-docs#4143]
Feedback from customer regarding this documentation:

It is too long and hard to focus. The beginning of the documentation goes straight into PowerShell and REST API which is intimidating for beginners looking for audit logs data (not sure if that also suggested to users to start with PowerShell and REST API, rather than Microsft 365 Admin Center). Would help if it is split into multiple pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jamezhangMS. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@jamezhangMS - thank you for the feedback. We are looking at ways to improve this article and appreciate you sharing your ideas. I'm assigning this to a writer for consideration.
