### ISSUE TITLE
What about dataflows?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4145]
I'm not able to get data (in a new dataset, dataflow, or datamart) from existing dataflows in a tenant where I'm a guest user. When I log in, I can only see the list of workspaces in my own tenant, not the tenant where I'm a guest. If there's a workaround, it should be documented. If there's no workaround, the documentation should explicitly state that dataflows can't be used by guest users.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. We will consult with the authors to determine whether to add your suggested comment. 

Meanwhile, you might find a solution or answer in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
