### ISSUE TITLE
Max Memory Per Dataset and refreshing the dataset

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4148]
I'd like to know how the concepts below are related. The second paragraph states that the memory used by the dataset will double during refresh, while the first paragraph states that "an amount of memory" must be reserved for refresh. Does "an amount of memory" = "double"? 

If that is the case, then .pbix files would be limited to approximately half of the Max Memory if they needed to be refreshed. Is that correct?

> The Max memory per dataset (GB) column represents an upper bound for the dataset size. However, **an amount of memory** must be reserved for operations such as refreshes and queries on the dataset. The maximum dataset size permitted on a capacity may be smaller than the numbers in this column.

> Refreshing the dataset - The second action is refreshing the dataset after it's loaded into the memory. **The refresh operation will cause the memory used by the dataset to double**. The required memory doubles because the original copy of data is still available for active queries, while another copy is being processed by the refresh. Once the refresh transaction commits, the memory footprint will reduce.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 00bf7e05-4c27-38a6-4951-29dff857e10d
* Version Independent ID: 00bf7e05-4c27-38a6-4951-29dff857e10d
* Content: [What is Power BI Premium Gen2? - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

What you're saying is correct. During a refresh you'll need double the memory that the refreshed dataset requires. Note that during a refresh you may be refreshing only some of the datasets that you have. There are also some datasets that don't require a refresh. For more information see [Data refresh in Power BI](https://learn.microsoft.com/power-bi/connect-data/refresh-data).

Thanks,

Kesem

**Comment by djurecic0** [comment]
Hi @KesemSharabi,
 Thank you for your response- this is helpful.
