### ISSUE TITLE
Model size limit PPU vs. Premium Capacity

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4149]
Though technically correct, I don't think the description of "Up to 400GB" is the best way to describe the Per Capacity limit. The actual limit range is 25-400GB [Source](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is#capacities-and-skus)

The way it is listed here makes it seem that Premium capacity always has an equal or greater limit than PPU, which is not the case. In fact, you will lose model size limit if you go from PPU to Premium P1 or P2. This should be made more clear to users. Right now users need to look at 2 different tables on 2 different pages and piece this together themselves. 

Additionally, most premium capacity users do not use P5. So 400GB is not a good number for the average Premium user.

All other items in this table, as well as the table on "What is Power BI Premium Gen2" page show actual numbers. This is the only item with "Up to" included.

"Up to 400 GB" is potentially misleading and should be changed to the actual numeric limits which are 25- 400GB. You could say that Microsoft employees make up to $309 Million per year, but that is not relevant to the average employee's experience :-) 

If this change is not possible, at least be consistent with the table from "What is Power BI Premium Gen2" page and add a footnote explaining the limits for different tiers of Premium Capacity.

Feature description  | Per User  | Per Capacity
Model size limit        | 100 GB   | Up to 400 GB

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Microsoft Power BI Premium? - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

Can you please explain in which article you found the phrase 'Up to 400GB'?

Thanks,

Kesem

**Comment by djurecic0** [comment]
Hi @KesemSharabi,
 Thank you for your response. Sorry, I may have submitted this with the wrong article. 

Here is the article with "Up to 400GB"

**Power BI Premium Per User**
https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-per-user-faq

The table in section **Using Premium Per User (PPU)**.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

Let me check what the product team has to say about the way *model size limit* is described in the [PPU article](https://learn.microsoft.com/power-bi/enterprise/service-premium-per-user-faq).

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

Thank you for pointing out this issue. I've updated the table header from 'up to 400 GB' to '25-400 GB' with a footnote that explains that this figure depends on the SKU you have (see [Using Premium Per User (PPU)](https://learn.microsoft.com/power-bi/enterprise/service-premium-per-user-faq#using-premium-per-user--ppu-)).

Thanks again for getting involved,

Kesem
