### ISSUE TITLE
Please mention that everyone can update the PowerBI report and not just read it

### ISSUE THREAD

**Issue by charletsjp** [MicrosoftDocs/powerbi-docs#4150]
Our user would like to use this feature, but they realized that everyone could edit the PowerBI report and just not read it. This limitation makes complicated to maintain a single source of truth for all the one who may access the 'vizualize this list'. 

So please mention that everyone can update the PowerBI report and not just read it in the Consideration and limitations: https://learn.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list#considerations-and-limitations 

Thanks, 

Best regards, 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list or library in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @charletsjp. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
@charletsjp thanks for your comment! I've added it to the Considerations section of https://learn.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list#considerations-and-limitations. The change should be live later today Fri Oct 28 Pacific time.
