### ISSUE TITLE
The section referenced no longer exists

### ISSUE THREAD

**Issue by rihoughton** [MicrosoftDocs/powerbi-docs#4153]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9e4a2a2-636c-d935-9b16-82e15ab941b1
* Version Independent ID: e9e4a2a2-636c-d935-9b16-82e15ab941b1
* Content: [Configure automatic aggregations - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto-configure)
* Content Source: [powerbi-docs/enterprise/aggregations-auto-configure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/aggregations-auto-configure.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rihoughton. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@rihoughton - What exactly are you referring to?

**Comment by Minewiskan** [comment]
No clarification on what this is about.

**Comment by rihoughton** [comment]
This section no longer exists.  It needs to be updated.
![image](https://user-images.githubusercontent.com/99290906/199348688-865f6563-79d9-4e82-bf90-1d4c01cec50c.png)

**Comment by rihoughton** [comment]
![image](https://user-images.githubusercontent.com/99290906/199349175-2d0aa1bb-414c-4e82-9efb-db06ac231216.png)

**Comment by Minewiskan** [comment]
@rihoughton - There has been no engineering change to this functionality. We tested and everything is as expected. It's likely that you don't have Owner permissions for the dataset, or your dataset is not DirectQuery. The Schedule refresh flyout will not show optimization if those requirements aren't met. Be sure to read through the Requirements section in the Automatic aggregations overview article. If you continue to have issues, it's best to contact support.

<img width="255" alt="autoaggsdialogue" src="https://user-images.githubusercontent.com/12401320/199544322-d5e72f82-4f24-429b-a8d1-6fe91231486d.png">

**Comment by rihoughton** [comment]
Removing portions of the UI because a condition hasn't been met is an objectively bad design choice.  Keep the UI the same and throw an error indicating the specific conditions that haven't been met.  Microsoft wouldn't need such extensive documentation and support staff if they took the time to design their products effectively.  Thumbs down!
