### ISSUE TITLE
Published SSRS Reports on PBI Services

### ISSUE THREAD

**Issue by tahmid-bari** [MicrosoftDocs/powerbi-docs#4154]
Hi Microsoft Team,
In the fourth week of October 2022, I manually migrated existing SSRS reports to PBI (premium per capacity) services. And expected those reports would have self-service interactivity (drill-down, filtration) in the same way that Power BI reports do. Unfortunately, those reports lack those features, and I was unable to create a SharePoint embedded link for those migrated reports from PBI services. Can the published SSRS reports on PBI services have the SharePoint embedded link and PBI report features? Thank you kindly.

Sincerely,
Tahmid Bari

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8c868cc-a15f-f870-ed4e-7b3d9dbd3ec0
* Version Independent ID: 1c353bbb-038f-5ea9-eb10-98401dd0fddb
* Content: [Migrate SQL Server Reporting Services reports to Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/migrate-ssrs-reports-to-power-bi?source=docs)
* Content Source: [powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tahmid-bari. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @tahmid-bari -- You're right, some features are not supported in paginated (aka SSRS) reports in the Power BI service. The article you're referring to, , links to the "Paginated reports FAQ", which lists features not supported yet. https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq#what-paginated-report-features-in-ssrs-aren-t-yet-supported-in-power-bi-
I hope that helps!

**Comment by tahmid-bari** [comment]
Hi, @maggiesMSFT -- Thank you so much for your note. Yes, this information is useful even though we are looking for those services in our uploaded paginated (aka SSRS) reports in the Power BI service. Thanks.
