### ISSUE TITLE
Kerberos only vs Use any authentication protocol

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/powerbi-docs#4155]
Hi,

recommending a constrained deleation to  "Use any authentication protocol" is not safe and should be configured via "Kerberos Only". Could you provide a safe documentation that works?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PehDeh. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @PehDeh,

Can you please let us know which document you're referring to?

Thanks,

Kesem

**Comment by PehDeh** [comment]
Hi,
sory the notification ended up in spam.
I meant this article:
https://learn.microsoft.com/en-us/power-bi/report-server/configure-kerberos-powerbi-reports
Especially that part with constrained delegation set to Use any authentication protocol:
https://learn.microsoft.com/en-us/power-bi/report-server/media/configure-kerberos-powerbi-reports/powerbi-report-config-delegation.png
Shouldn´t you recommend a secure Kerberos only to get rid of NTLM/RC4 etc?

**Comment by KesemSharabi** [comment]
Hi @PehDeh, I've reopened this issue and will look into it. Thanks for providing a link to the article.

**Comment by paulinbar** [comment]
Hi @PehDeh, I'm moving this issue to our work item backlog for better tracking and consideration. Closing it here now. Thanks for providing your input!

**Comment by paulinbar** [comment]
We need to get this into a system where we can better prioritize and track, and things aren't as likely to sit or fall through cracks. I'll indicate in the work item that you request to be notified of changes/status updates.
