### ISSUE TITLE
Can't copy the path in documents with a lot of history

### ISSUE THREAD

**Issue by agansari** [MicrosoftDocs/powerbi-docs#4157]
Regarding https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-use-onedrive-business-links

This is of no help, sharing a link won't work, you cant import the onedrive hosted excel, not even logged in. Copy path seems to work, BUT.....
In documents with a lot of history or changes you are not able to scroll down to copy path, please provide a different solution.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @agansari. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @agansari,

Can you please describe what you're trying to do and what doesn't work for you?

Thanks,

Kesem
