### ISSUE TITLE
Additional explanation of 'detail-level data'

### ISSUE THREAD

**Issue by eBentl** [MicrosoftDocs/powerbi-docs#4160]
Hi, can you please provide additional context to the below statement from the warning at the top of the page:

> It includes viewing detail-level data that your reports aggregate.

This statement feels very vague for the (potential) severity of the warning. I'm aware that network monitoring tools expose the 
conceptualschema and modelsAndExploration files, revealing the data model schema and report metadata - is this what is meant by 'detail-level data' or can a viewer expose row-level data from the model?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eBentl. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @eBentl, thanks for reaching out. I'm moving this issue to our work item backlog for better tracking and consideration and closing it here now. To get a faster answer until the docs are updated, you might try asking on the [Power BI Community](https://community.powerbi.com/). Good luck!

**Comment by VitalyMCT** [comment]
@paulinbar I think @eBentl 's question is very valid. Can it please be answered via an update to the official Microsoft documentation, or at least, via an official answer by yourself or another Microsoft employee within this ticket? 

Power BI Community forums have all kinds of guesses around the meaning of this sentence. We cannot rely on assumptions when making decisions around data security. Here are some of the community's guesses:

https://community.fabric.microsoft.com/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&filter=location&location=category:powerbi&q=It%20includes%20viewing%20detail-level%20data%20that%20your%20reports%20aggregate
