### ISSUE TITLE
Multi row card

### ISSUE THREAD

**Issue by MichaelURev** [MicrosoftDocs/powerbi-docs#4163]
Since the latest update that allows clicking on multi row cards, where do we see edit interactions? I don't want my multi row card to affect other visuals.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @MichaelURev, you've reached the channel for feedback to the content writers, and I think this is more of a product question. I suggest you try either the [Power BI Community](https://community.powerbi.com/) or our [support page](https://support.powerbi.com/). Good luck!
