### ISSUE TITLE
Why server aggregation are not supported for DAX?

### ISSUE THREAD

**Issue by santoswill** [MicrosoftDocs/powerbi-docs#4164]
So, if server aggregation is not suppported by DAX Queries and you have a complex DAX Query Script (wich turn it dificult to translate into MDX), the tool becomes useless entirely. Is there any workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6272c2ce-1197-0987-c70b-e67b5954513e
* Version Independent ID: af832a96-9038-cc39-62f9-36779c92659a
* Content: [Data retrieval guidance for paginated reports - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/report-paginated-data-retrieval)
* Content Source: [powerbi-docs/guidance/report-paginated-data-retrieval.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/report-paginated-data-retrieval.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @santoswill. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @santoswill - sorry, that's how the product works for now. There's a workaround, but it could be complex for some report authors to do. It would involve writing a DAX query that returns all aggregates that your report requires. You'd then need to use conditional logic to retrieve field values you want to show in the report.
