### ISSUE TITLE
Dealing with the many many-many relationships in Dataverse

### ISSUE THREAD

**Issue by ScottSzathmary** [MicrosoftDocs/powerbi-docs#4165]
Thanks for the great article with updated guidance on Power BI and Dataverse.

One thing I was hoping to see was some guidance on *how* many-to-many relationships should be dealt with in creating a star schema.  Many-many is so common in Dataverse, almost every entity I am dealing with uses that paradigm.  

Also, my users are not looking for deep analytical reporting against dataverse right now, just an extension/improvement of charts and graphs available in our model driven app.  So it has to be able to answer all the questions that are built into the model driven app's reporting, plus go a step beyond in some cases.  If not replicating the dataverse model is an anti-pattern, what is the desired pattern for meeting customer reporting needs when they want full reporting capabilities out of Power BI, not just analytical reporting? 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b22276bb-dce9-9f59-fe03-1359a401afbb
* Version Independent ID: b22276bb-dce9-9f59-fe03-1359a401afbb
* Content: [Power BI modeling guidance for Power Platform - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-modeling-guidance-for-power-platform?WT.mc_id=twitter)
* Content Source: [powerbi-docs/guidance/powerbi-modeling-guidance-for-power-platform.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-modeling-guidance-for-power-platform.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by peter-myers** [comment]
Hi @ScottSzathmary - thanks for your feedback. Many-to-many isn't exclusive to models that connect to Dataverse. You can find this topic is covered in detail in this guidance article: https://learn.microsoft.com/power-bi/guidance/relationships-many-to-many - I hope that helps you.
