### ISSUE TITLE
Any Changes to the Structure of the WWW pages in MS Learn or MS DOCS??

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [MicrosoftDocs/powerbi-docs#4168]
Hi Team
am getting the errors below when trying to consume any MS Learn content via PowerBI (Dataflows, using Gateway)
<img width="917" alt="image" src="https://user-images.githubusercontent.com/60373199/199449480-87709e02-2019-4d43-86e1-92a40517bec6.png">

The resource at '**https://learn.microsoft.com**/en-us/power-bi/collaborate-share/service-roles-new-workspaces' cannot be retrieved using Web.Page. It doesn't appear to be a web page.Detailshttps://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces

Has there been a change to the html content that now stops web.page(web.contents([URL])) traversing?

It may be a bug but I can 'consume' other www happily.
Help!!

Cheers

Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Chris-Burgess-ACTGOV. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Chris-Burgess-ACTGOV, you've reached the channel for feedback to the content writers, and I am afraid we wouldn't know anything about connecting to the web pages as you've described. I suggest you either try our [support](https://support.powerbi.com) or perhaps the [Power BI Community](https://community.powerbi.com). Thanks for reaching out, and good luck!

**Comment by Chris-Burgess-ACTGOV** [comment]
Thanks @paulinbar 
The issue arose when ms docs transitioned to ms learn - same content in different urls -  but a redirect was on the docs to learn www content. Dataflows (powerquery online) do not like dynamic web content - the redirect - so was causing the ingest to fail.
Repointing the dataflows to the learn urls and rebooting our gateway cluster (cached content) resolved.

Cheers
Chris
