### ISSUE TITLE
How to configure BYOSA?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#417]
"Power BI can be configured to store dataflow data in your organization’s Azure Data Lake Storage Gen2 account." -&gt; Where do you set that up? I don't see anything letting you select your own ADLSG2 account from Power BI's Admin Portal &gt; Tenant settings in the Dataflow settings section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4e74b8-9f4a-a195-7347-cf6732ffeab5
* Version Independent ID: a1513d50-f098-9b75-2b48-94e08ee34751
* Content: [Learn about dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-overview)
* Content Source: [powerbi-docs/service-dataflows-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-overview.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @otravers. Note that dataflows are in preview, so features are being refined and expanded upon during the preview. You might find more information in the Power BI Community, found at https://community.powerbi.com.
