### ISSUE TITLE
Retention policy for audit logs. 

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/powerbi-docs#4171]
I see I can create a retention policy for Office unified Log for up to 10 years. Could you please verify your numbers in the table for PBI Activity and Unified Log (90 and 30 days in the table)? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @ed7257,

Thank you for your comment. I'm looking into this and will verify the numbers shortly.

Kesem

**Comment by KesemSharabi** [comment]
Hi @ed7257,

The information in the table is correct. In addition to the numbers in the table, if you have a Microsoft 365 E5 SKU (which includes Power BI services), you can buy a 10 year Audit Log retention.

Hope this helps,

Kesem
