### ISSUE TITLE
"Maximum of 1,000 datasets, or 1,000 reports per dataset"

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4172]
I'm not clear on what "or" means in the context below.

If the limit for datasets per workspace is 1000 and the limit for reports per dataset is 1000, does that mean that the limit for reports per workspace is 1,000,000 (1000 * 1000) ?

Or is there a limit of 1000 datasets + reports per workspace?

Or another combination?

> Workspaces can contain a maximum of 1,000 datasets, or 1,000 reports per dataset.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Version Independent ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Content: [Workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @otravers, thanks for your question. I believe that it is either 1000 datasets, or one dataset and 1000 reports. But we need to check this, and also whether these limits are even still in place. So I'm moving this issue to our work item backlog for better tracking and consideration, and closing it here here now. To get a faster answer until the docs are updated, you might try the [Power BI Community](https://community.powerbi.com/). Usually someone there knows the answer. Thanks!
