### ISSUE TITLE
Prerequisites and limitations not complete

### ISSUE THREAD

**Issue by floemmel** [MicrosoftDocs/powerbi-docs#4173]
Hi, 

I noticed a small mistake in the documentations. In the "Prerequisites" section as well as in the Considerations and limitations it is stated that "_Publish to web is available for reports you can edit in your personal and group workspaces._". However what is not mentioned, is that additionally you need sharing permissions. Therefore the minimum permissions required are Member or Contributor + Re-Share. 

Would be great if this could be reflected in the documentation! 

Thank you. 
Kind regards,
Florian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web#considerations-and-limitations)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @floemmel, I'm moving this issue to our work item backlog for better tracking and consideration, and am closing it here now. Thanks for providing your feedback!
