### ISSUE TITLE
Outdated information regarding connecting to Synapse Analytics?

### ISSUE THREAD

**Issue by goonerCW** [MicrosoftDocs/powerbi-docs#4175]
The article claims "Both Azure Synapse Analytics (formerly SQL Data Warehouse) and Azure HDInsight Spark data sources can be connected to directly, without the need to use Power BI Desktop.".
However, the linked article next to it (and Power BI services itself, when trying to connect) claim 
"The previously available direct connector for Azure Synapse Analytics in the Power BI service **is no longer available**." https://learn.microsoft.com/en-us/power-bi/connect-data/service-azure-sql-data-warehouse-with-direct-connect

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 694e3f20-79d0-debf-1449-38a62492424c
* Version Independent ID: 75c298be-5754-c342-cb4d-228b38f8cec7
* Content: [DirectQuery model guidance in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance)
* Content Source: [powerbi-docs/guidance/directquery-model-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/directquery-model-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @goonerCW. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @bishalgoswami - thanks for your feedback. I've removed that entire section because it was outdated. The published change should take affect with 24-48 hours.
