### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by prvillal** [MicrosoftDocs/powerbi-docs#4177]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

[Enter feedback here]
There is missing information on how to disable this feature... 

If you see the link, it states is enabled by default, then it says... to disable this feature... and does not explain how. 

https://review.learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out?branch=pr-en-us-8660#disable-power-bi-query-scale-out

![image](https://user-images.githubusercontent.com/37197217/200084494-874b7cb0-13eb-4be1-823e-12d387e6f481.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Version Independent ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Content: [Power BI Premium Scale-out - Power BI](https://review.learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out?branch=pr-en-us-8660)
* Content Source: [powerbi-docs/enterprise/service-premium-scale-out.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-scale-out.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @prvillal. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @prvillal,

Thanks for letting us know. This article was accidently published prematurely. I'll remove this section and republish the article with the required information shortly.

Thanks,

Kesem
