### ISSUE TITLE
What is "Odatafeed Auth 2.0"? There's no explanation given.

### ISSUE THREAD

**Issue by LarsKemmann** [MicrosoftDocs/powerbi-docs#4178]
A note on this page says:
> Currently template apps do not support custom connectors, it is recommended to explore using Odatafeed Auth 2.0 as a mitigation for some of the connection use-cases or to submit your connector for certification. For details on how to develop a connector and certify it check the [Data Connectors documentation](https://aka.ms/DataConnectors).

There is no explanation given for what "Odatafeed Auth 2.0" is (and the casing is odd).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b816e194-4069-e526-a96d-04238bf354cd
* Version Independent ID: 369aca21-55ba-d5f5-b699-bb4d85f1d540
* Content: [Tips for authoring template apps in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-template-apps-tips)
* Content Source: [powerbi-docs/connect-data/service-template-apps-tips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-template-apps-tips.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LarsKemmann. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
@teddyberco, should "Odatafeed Auth 2.0" be “Odata Feed Oauth 2.0” or “OAuth 2.0”, or  should we just leave it as is? Thanks!
