### ISSUE TITLE
What are variation and caldenar tables

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#4179]
Hi, 

Under the Dataset Limitations section, it is mentioned that datasets with [variation and calendar tables aren't supported](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#dataset-limitations:~:text=uses%20variation%20or%20calendar%20tables). Can you please clarify what that means ? There is no such thing as calendar table in Power BI. There are [Date Tables](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-date-tables) but those are supported in deployment pipelines so please clarify what variation table and calendar table are. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: adc3b8dc-0d07-e0d4-a27a-dc80c45c121e
* Version Independent ID: 389f5272-2ed2-dd5d-5671-f514e086fb7d
* Content: [Deployment pipelines, the Power BI Application lifecycle management (ALM) tool, process - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-process#unsupported-items)
* Content Source: [powerbi-docs/create-reports/deployment-pipelines-process.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/deployment-pipelines-process.md)
* Service: **powerbi**
* Sub-service: **pbi-deployment-pipeline**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pawarbi. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @pawarbi,

Auto-calendar tables are created automatically, when the _Auto date/time_ option is selected, to optimize the use of _Date_ columns in other, user-authored, tables (see [Auto date/time in Power BI Desktop](https://learn.microsoft.com/power-bi/transform-model/desktop-auto-date-time)).

_Variations_ is a property of a column within a table. Each variation refers to an associated relationship, a table and a hierarchy. Most likely the associated table is hidden so it won’t be accessible without the variation. Identifying if a table has variations can be done by looking at the _Variations_ property in a column within a table (see [Column.Variations Property](https://learn.microsoft.com/dotnet/api/microsoft.analysisservices.tabular.column.variations?view=analysisservices-dotnet)).

Hope this helps,

Kesem

**Comment by pawarbi** [comment]
> Hi @pawarbi,
> 
> Auto-calendar tables are created automatically, when the _Auto date/time_ option is selected, to optimize the use of _Date_ columns in other, user-authored, tables (see [Auto date/time in Power BI Desktop](https://learn.microsoft.com/power-bi/transform-model/desktop-auto-date-time)).
> 
> _Variations_ is a property of a column within a table. Each variation refers to an associated relationship, a table and a hierarchy. Most likely the associated table is hidden so it won’t be accessible without the variation. Identifying if a table has variations can be done by looking at the _Variations_ property in a column within a table (see [Column.Variations Property](https://learn.microsoft.com/dotnet/api/microsoft.analysisservices.tabular.column.variations?view=analysisservices-dotnet)).
> 
> Hope this helps,
> 
> Kesem

Thanks @KesemSharabi . So If I understood it right, if a DQ or composite model uses auto/date time, deployment pipeline will not work? 
I am still don't understand variations. I get that it is a property of the column but how do I check in Power BI Desktop or Tabular Editor if a column has variation ? If a column is used in a hierarchy or is in relationship, it cannot be used in deployment pipeline? Pretty much all Power BI models will have a column with a relationship so I don't understand it. Can you please explain with an example? Thanks.
