### ISSUE TITLE
Allow Embeded Fileter in Sharepoint

### ISSUE THREAD

**Issue by rosskingplatt** [MicrosoftDocs/powerbi-docs#418]
I have a great dashboard, but it has alot of data. I would like to embed into SharePoint but Filter to select items and I can via a URL but not via the Embed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by davidiseminger** [comment]
Thanks for your comment, @rosskingplatt . This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
