### ISSUE TITLE
Maturity Perspective tagging to Release Wave/Plan items

### ISSUE THREAD

**Issue by Chris-Burgess-ACTGOV** [MicrosoftDocs/powerbi-docs#4180]
Hi Team
Any thoughts on tagging the:
![image](https://user-images.githubusercontent.com/60373199/200206340-ba7f5d85-4188-4454-a74e-29d50bd9fd93.png)

maturity levels to the release wave items
https://learn.microsoft.com/en-gb/power-platform-release-plan/2022wave2/power-bi/planned-features
and/or
https://experience.dynamics.com/releaseplans/?app=Power+BI

Would certainly give some visibility and measurability of aligned activity (those 365 audit activity logs!!) to adoption 

Cheers
Chris
---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03be611a-54dc-68cf-1eee-c6ae5f884a8c
* Version Independent ID: c25b6852-b85b-fa28-3e9f-1fc354b5e2e4
* Content: [Power BI adoption roadmap maturity levels - Power BI](https://learn.microsoft.com/en-gb/power-bi/guidance/powerbi-adoption-roadmap-maturity-levels)
* Content Source: [powerbi-docs/guidance/powerbi-adoption-roadmap-maturity-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-adoption-roadmap-maturity-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Chris-Burgess-ACTGOV. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @Chris-Burgess-ACTGOV - thanks for the suggestion. We'll let the release team know of your suggestion and let them decide whether they will adop your idea. Thanks again.
