### ISSUE TITLE
Needs a note about limitations in service

### ISSUE THREAD

**Issue by ryan2275** [MicrosoftDocs/powerbi-docs#4181]
Although the page is clearly designated for 'PowerBI Desktop' -- there still needs to be something added that explains that R script cannot be refreshed in Enterprise gateways.  

Considerable time and effort can be spent to enable and develop R scripts that end up being useless as they cannot be promoted to a fully scheduled PowerBI report in service.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65c5ff52-929f-1722-cae7-a13193afcbc5
* Version Independent ID: 9dae40ab-e5d9-42a3-d95a-5c1610f02682
* Content: [Run R scripts in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-scripts)
* Content Source: [powerbi-docs/connect-data/desktop-r-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ryan2275. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
I added a note limitation that they R scrips cannot run in the service. Thanks for your feedback.
