### ISSUE TITLE
Pls. add guidence on choosing an identity for scheduled refresh

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerbi-docs#4182]
Please add best practices what kind of identiy (user, service principal, or the like) to use to authenticate with SharePoint Online in a scheduled refresh scenario, talking about a file that is stored in SharePoint and loaded into the Power BI Dataset, e.g Excel or CSV file, not talking about the pbix file being stored on SharePoint. To me there is a lot of confusion around this without guidance:
- I think it's not a good idea to use the login of a natural person because this person might change password at any time, which would first initiate failed refresh and then administrative costs. So what is the recommended approach?
- What to be aware of if the company policy requires multi factor authentication? Is it a good idea to use a MFA enabled login for scheduled refresh? If not, how do I get a login without MFA if company policies require MFA?
- Can I use a service principal for scheduled refresh from files on SharePoint? How do I set this up?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3090a14-7c69-f5a7-9cf1-88c98c211470
* Version Independent ID: d66a60a9-ea01-f7c3-8b26-3dea86641c0b
* Content: [Refresh a dataset from OneDrive or SharePoint Online - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-desktop-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-desktop-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-desktop-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinBubenheimer. This issue has been assigned to the doc author for review.
