### ISSUE TITLE
Add VNET Gateway (supported) & (required) to overview

### ISSUE THREAD

**Issue by BenniDeJagere** [MicrosoftDocs/powerbi-docs#4184]
With the VNET Gateways slowly creeping into public preview more and more, and GA arriving soon, I find customers get confused with the verbiage on Gateway (supported) and Gateway (required). It would useful to have a split between the on-premises data gateway and the VNET data gateways.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources?source=docs)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by BenniDeJagere** [comment]
A new addition. This should either:
- Add Power BI Datamarts as a single source
- Combine Power BI Datamarts and Power BI dataflows under the single name of 'PowerQuery Online'

**Comment by davidiseminger** [comment]
Thanks for your comments, that article has been updated and now points to the Power Query connector page, which is updated frequently by the engineering team.
