### ISSUE TITLE
No mention of troubleshooting steps for 'Visualize this list' taking the user to PowerBI login page

### ISSUE THREAD

**Issue by simoninnyc** [MicrosoftDocs/powerbi-docs#4185]
There's no explanation for why a user (with PowerBI Pro license) is taken to the login page of PowerBI even after authenticating. Unable to proceed without this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list or library in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @simoninnyc -- I'm checking with the product team. Thanks!

**Comment by paulinbar** [comment]
Hi @simoninnyc, is the account that you used to login to Power BI the same account that is logged in SharePoint? If they aren't the same, that could lead to a need to reauthenticate. Please check that and reopen this issue if you still have the problem. Thanks!
