### ISSUE TITLE
Save a copy requiring Build permissions???

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#4186]
At multiple places in this doc we state that you require build permissions on the dataset to make a copy of a report - I believe this is incorrect.  You can copy a report if you have read access to the report and dataset, but you cannot edit/update it. 

So I can create a copy of a report into my own workspace when I have read permissions, and that report will remain connected to the original dataset and continue to work for me, however I cannot edit or change the copied report unless I have build permission on the dataset.

Can someone please confirm the permission requirements to copy a report?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rosscouldrey. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rosscouldrey, I didn't observe the behavior you describe. The dataset and report you are making a copy of are not in your My Workspace, correct? My Workspace is only the destination for the copy, right? In my trials, copying works as described. Can you confirm that the source dataset is located in a workspace where you only have a viewer role, and that no build permissions have been granted on the dataset via some other means, such as explicit permissions?
In the meantime I am closing this issue, but feel free to reopen it if you still manage to copy the report as you described. Thanks!

**Comment by rosscouldrey** [comment]
Hi Paul - i think the issue still persists.  If you review the article you'll find the following statements:

- To copy a report to another workspace, ..., you need build permission for the dataset
- You only see the "Save a copy" option if you have Build permisssion
- You only see the "Save a Copy" option if app permissions grant Build permission

I dont believe these statements are true and I've tested again this morning.  I am able to copy a report to another workspace without Build permissions... you cannot EDIT the report... but you can copy it.  I have put together a series of screenshots to demonstrate the workflow which i will send via email for your review.

I think the update here just needs to be clarity that we're talking about needing Build permissions to EDIT a report... not to COPY it.

**Comment by rosscouldrey** [comment]
You were correct - the user had access to the app which granted build permissions on the dataset by default...
