### ISSUE TITLE
creating a dataflow from cloud sources in power bi service (scorecard cloud dataset)

### ISSUE THREAD

**Issue by PatStats** [MicrosoftDocs/powerbi-docs#4187]
[Enter feedback here]

Hi,

just wondering if anyone has had success using scorecard (goals) as datasets in power bi, 

I have been able to connect the scorecard data set via direct query, but I need to further transform the dataset in order to perform some simple powerquery transformations
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating a dataflow - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-create)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-create.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PatStats. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
