### ISSUE TITLE
Request for clarification- "members of workspace"

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4189]
First, is there such a thing as "members of a workspace"? Should this be called "users who have access to a workspace"? In this context, the word "member" is confusing with the "Member" role. To me, Workspace Members, Workspace Admins, and Workspace Contributors mean the users who have been assigned those roles. In Power BI service, to see who has access to a workspace, you go to "Access", not "Members". The term "members of a workspace" to mean something other than the users who have the Member role is potentially confusing.

Second, the second paragraph quoted below seems to contradict the first paragraph. The first paragraph states that (all) members of a workspace have access to datasets which is not restricted by RLS.  The second paragraph states that members of a workspace who have the Viewer role are affected by RLS. The second paragraph is correct, but the first is not, unless there is an interpretation that I am missing.

>  In the Power BI service, members of a workspace have access to datasets in the workspace. RLS doesn't restrict this data access.
....
> If you publish your Power BI Desktop report to a [workspace](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces) in the Power BI service, the RLS roles are applied to members who are assigned to the Viewer role in the workspace. Even if Viewers are given Build permissions to the dataset, RLS still applies. For example, if Viewers with Build permissions use [Analyze in Excel](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-analyze-in-excel), their view of the data will be protected by RLS. Workspace members assigned Admin, Member, or Contributor have edit permission for the dataset and, therefore, RLS doesn’t apply to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @djurecic0, thanks for your question. I will look into it. Thanks!

**Comment by paulinbar** [comment]
Hi @djurecic0,
I think the confusion stems from what access means. If you are have a viewer role in a workspace, you can see the dataset in the workspace, and you can access it's details page. I think access in the RLS context refers to rules applied to the actual rows of data in the dataset. But no question - the documentation isn't clear. I will take this up with the person who now maintains that document. Thanks!

**Comment by djurecic0** [comment]
Thank you @paulinbar
