### ISSUE TITLE
"Security Group" vs Azure Active Directory Security Group and Active Directory Security Group

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4190]
Instead of "Security Group", I think it would be helpful to list the specific types of security groups like below. This is how most people refer to these types of groups. The generic term "security group" is not specific enough and leaves questions in the user's mind about what types of security groups can be used.

Azure Active Directory Security Group
Active Directory Security Group

> You can use the following groups to set up row level security.
> 
> Distribution Group
> Mail-enabled Group
> Security Group

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @djurecic0, thanks for the input. I think you are right to say that this needs to be more specific. Let me see if I can get that information from the developers.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for the suggestion, @djurecic0, I updated the doc for clarity.
