### ISSUE TITLE
Reordering of (calculated columns)

### ISSUE THREAD

**Issue by KurtPetteloot** [MicrosoftDocs/powerbi-docs#4192]
It sure would be very useful to developers and data modelers to reorder the columns in the data view. When a calculated column is created it is added to the far right and there seems no way to move it to a more appropriate position in the column order.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32b2d1e0-b435-be54-bcf5-bdd0dfe1e813
* Version Independent ID: 18009f37-9663-0513-b62d-8fc3cf5da5b3
* Content: [Data view in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-view)
* Content Source: [powerbi-docs/connect-data/desktop-data-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-view.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KurtPetteloot. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
