### ISSUE TITLE
Food Engineering

### ISSUE THREAD

**Issue by tarsedagnetarle** [MicrosoftDocs/powerbi-docs#4193]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Version Independent ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Content: [Workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @tarsedagnetarle. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @tarsedagnetarle, I don't see that you provided any feedback. I'm going to close this issue now, but feel free to reopen it if you wish to provide feedback. Thanks!
