### ISSUE TITLE
Limitations for download pbix for report and dataset

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4194]
The limitations section needs to be updated based on the changes made with the October release of Power BI desktop since more scenarios are now supported with regards to being able to download reports referencing large datsets, incremental refresh, or deployed through the deployment pipelines.
https://powerbi.microsoft.com/en-us/blog/power-bi-october-2022-feature-summary/#post-21148-_Toc116053194

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#download-a-report-as-a-pbix-file)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @denglishbi, I'm moving this issue to our work item backlog for better tracking, and closing it here now. Thanks for providing your feedback!
