### ISSUE TITLE
could this page be updated please? Very old.

### ISSUE THREAD

**Issue by SHKS-GFT** [MicrosoftDocs/powerbi-docs#4195]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for accessing Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FalkeSK. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've recently updated that article. Thanks!
