### ISSUE TITLE
which access paths are needed to use this information?

### ISSUE THREAD

**Issue by MSUMOLL** [MicrosoftDocs/powerbi-docs#4196]
This page gives no indication of which access path is needed to obtain the views and information it contains. I believe the images and instructions are for a person using Power BI on the web, and that they do not pertain to a person using Power BI desktop. Is it possible to [mention this information on the page like pages like this do](https://support.microsoft.com/en-us/office/customize-or-create-new-styles-d38d6e47-f6fc-48eb-a607-1eb120dec563).

Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Version Independent ID: 6e8c4b5e-196c-ebdb-e024-d9380b3bd657
* Content: [Workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MSUMOLL. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @MSUMOLL, I am not sure I understand your question. Workspaces only exist in Fabric and Power BI on the web, not in Power BI Desktop. Can you clarify your question?

**Comment by paulinbar** [comment]
Hi @MSUMOLL, I am closing this issue now, but feel free to reopen if you can provide more information. Thanks!
