### ISSUE TITLE
"Principles" not principals

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4199]
The word "principal" means something different from "principle."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand)
* Content Source: [powerbi-docs/transform-model/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-petermyers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @otravers - thanks for reporting the error. I've published an update for the article, and it should go live in the next 24 hours.
