### ISSUE TITLE
Profiler Event 

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#420]
Hi, in the SQL Server Profiler I don't see the event "Query Processing\Aggregate Table Rewrite Query" as indicated above.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [Use Aggregations in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-aggregations#caches-should-be-kept-in-sync)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Sorry for any confusion, and I believe other customers do see that information. You might find help or a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
