### ISSUE TITLE
"As long as your datasets do not exceed this value"- context

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4200]
I think this statement may be technically correct, but does not send the most useful message to the end user since it does not make any reference to refreshing the data. A full refresh of an imported dataset will cause the size of the dataset to double during the refresh process (source: https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data#datasets-in-import-mode)

Evaluating a dataset's size using the method recommended in this article will not show that the dataset size will double on refresh. I've heard the argument that not all import data needs to be refreshed, but I would argue that those situations are outliers and not typical.

If I followed the instructions in this article to get dataset size and took the statement "As long as your datasets do not exceed this value" at face value, I would not account for refresh and could end up under sizing the capacity. Of course, you can always increase the capacity, but this can be an issue if $5k was budgeted per month and now you need to go back and ask for $10k or more.

Is there a way to make it more clear that if you need refresh capability on import data (which I would argue many if not most organizations need), you cannot have a model size that goes up to the limit of the capacity? In my experience, this issue is confusing to users looking at Microsoft documentation to try to understand what capacity they might need.

> For example, if you have a P1 SKU, datasets are supported up to a [limit of 25Gb](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is#capacity-nodes). _**_As long as your datasets do not exceed this value_**_, the SKU should meet your needs.
> ...
> You can evaluate a typical dataset’s size by measuring the memory footprint of the Power BI Desktop tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Version Independent ID: f728b16f-4072-f818-5b3d-9ce27968e7df
* Content: [Manage Microsoft Power BI Premium Gen2 capacities - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-manage-gen2)
* Content Source: [powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-capacity-manage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

I made some changes to [Planning your capacity size in advance](https://learn.microsoft.com/power-bi/enterprise/service-premium-capacity-manage-gen2#planning-your-capacity-size-in-advance) to reflect the issue that you raised.

Thanks,

Kesem

**Comment by djurecic0** [comment]
Hi @KesemSharabi ,
 Thank you for making the changes. This recent blog post makes it even more explicit:
https://powerbi.microsoft.com/en-us/blog/announcing-the-public-preview-of-power-bi-dataset-scale-out/
"When selecting a Premium SKU, the amount of memory required to refresh a dataset must be accounted for in addition to the target dataset size in memory. This typically limits the dataset size to approximately 50% of the max. available memory per dataset. "
