### ISSUE TITLE
Secure Embed vs Power BI Embedded clarification

### ISSUE THREAD

**Issue by JeffZheng666** [MicrosoftDocs/powerbi-docs#4203]
[Enter feedback here]
Hello team,

I'd like to know that in the statement about Secure Embed 'The viewer of the report must be properly licensed and _can't interact with the report._ ' , Based on my test, in Secure Embed option, I can interact with the embed report such as using filters and select the part in the visuals. So what does this 'The viewer can't interact with the report' means? 

Also, I know that Secure Embed is no code/low code option to embed Power BI Report with authentication, however, Power BI Embedded need some development skills to embed  Power BI report. Besides that, what is the main difference between Secure Embed and Power BI Embedded in term of supported features. Thanks.

I look forward to hearing from you at your earliest convenience.

![image](https://user-images.githubusercontent.com/20716250/202487309-40c95f31-60b3-4129-9032-fea5b6358b09.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe7888c3-14b3-8120-7fa5-80af7d1febba
* Version Independent ID: af40d3fb-5ed4-fa37-0e1d-afd01b1faf1e
* Content: [Power BI embedded analytics overview - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-analytics-power-bi)
* Content Source: [powerbi-docs/developer/embedded/embedded-analytics-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-analytics-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JeffZheng666. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @JeffZheng666. Thanks for your questions. I'll look into it and get back to you with a clarification.

**Comment by mberdugo** [comment]
Hi, @JeffZheng666. You're right that the user can interact with the report in secure embed. Here are the differences:
1.	Secure Embed - easy, low-code [just iFrame level integration], no automatic authentication, and no API support, not hostable in apps (supports web pages only). 
2.	Embedded Analytics - rich, fully integrated, full APIs, supports automatic authentication, and is hostable in apps.

I hope this helps.
I'll update the doc accordingly.
Thanks again for your question.

**Comment by JeffZheng666** [comment]
Thank you for the clarification @mberdugo!
