### ISSUE TITLE
Report Server license clarification needed

### ISSUE THREAD

**Issue by ChristianGalla** [MicrosoftDocs/powerbi-docs#4205]
The current [licensing documentation](https://learn.microsoft.com/en-us/power-bi/report-server/get-started#licensing-power-bi-report-server) including its links does not mention the number of Power BI Report Server instances a company can use, for example:

1. If you have only 1 SQL Server Enterprise Edition with Software Assurance
   1. Can you install only 1 Power BI Report Server on the same SQL Server?
   2. Can you install multiple Power BI Report Servers on dedicated machines only using the SQL Server Enterprise Edition with Software Assurance to host the report server DBs?
   3. Can you install multiple Power BI Report Servers using one or more (separately licensed) SQL Server Standard without technically using the SQL Server Enterprise Edition with Software Assurance at all for the Power BI Report Servers?
2.  If you have only 1 Power BI Premium license, can you only use 1 or multiple Power BI Report Server instances?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfc8bae8-be5d-ce63-6196-4c2e2f2d6779
* Version Independent ID: 2e836aec-a8a7-41fe-f562-c6c435e441ee
* Content: [What is Power BI Report Server? - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/get-started#licensing-power-bi-report-server)
* Content Source: [powerbi-docs/report-server/get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/get-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ChristianGalla. This issue has been assigned to the doc author for review.

**Comment by ChristianGalla** [comment]
I was able to find the missing information on the Product Terms site:

- [SQL Server Enterprise Edition with Software Assurance](https://www.microsoft.com/licensing/terms/productoffering/SQLServer/MPSA#SoftwareAssurance) 
  > Customer may run Power BI Report Server software on the [Licensed Server](https://www.microsoft.com/licensing/terms/product/Glossary/all), on any allowed [Fail-over OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all) in accordance with those same limits, or in Azure. Customer may run the software on a maximum numbers of cores equal to the number of SQL Server Enterprise Edition Core Licenses with active SA assigned to the [Licensed Server](https://www.microsoft.com/licensing/terms/product/Glossary/all), subject to a minimum of four core licenses per [OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all). Alternatively, if the software is run in Azure, Customer must allocate one SQL Server Enterprise Edition Core License with active SA per virtual core, subject to a minimum of four core licenses per [OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all). Use is additionally subject to the applicable terms of Customer’s volume license agreement. A Power BI Pro User SL is required to publish shared Power BI reports using the Power BI Report Server. This right expires upon expiration of Customer’s SA coverage.

- [Power BI Premium](https://www.microsoft.com/licensing/terms/productoffering/MicrosoftPowerPlatform/MPSA#Availability)
  > For each Microsoft Power BI Premium P subscription license, Customer may run any number of [Instances](https://www.microsoft.com/licensing/terms/product/Glossary/all) of the Power BI Report Server software in a [Physical OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all) or [Virtual OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all) on a Server dedicated to Customer’s user or a [Virtual OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all) on shared servers on Microsoft Azure Services only. [Servers](https://www.microsoft.com/licensing/terms/product/Glossary/all) used for this purpose, that are under the management or control of an entity other than Customer or one of its Affiliates, are subject to the [Outsourcing Software Management](https://www.microsoft.com/licensing/terms/product/ForallSoftware/all) clause. Customer may run the Power BI Report Server software in a Physical or [Virtual OSE](https://www.microsoft.com/licensing/terms/product/Glossary/all) with up to the number of cores included under its Power BI Premium P plan.  If any [Virtual Core](https://www.microsoft.com/licensing/terms/product/Glossary/all) is at any time mapped to more than one [Hardware Thread](https://www.microsoft.com/licensing/terms/product/Glossary/all), Customer needs an additional subscription license for each additional Hardware Thread mapped to that [Virtual Core](https://www.microsoft.com/licensing/terms/product/Glossary/all).

Unfortunately, the Product Terms site and its content is not available via Google search and also Bing results are very limited, so it is hard to find.

Therefore, I suggest to include some of this information and / or deeplinks to the docs.
