### ISSUE TITLE
There is confusions as to which audit log "audit log" refers to.

### ISSUE THREAD

**Issue by Darian-FRB** [MicrosoftDocs/powerbi-docs#4206]
The section title "Use the audit log" at https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing#use-the-audit-log does not clearly identify that this section pertains to the Unified Audit Log. This has confused Power BI administrators who have been attempting to access Purview and Exchange Online, which are beyond their responsibilities and in violation of separation of duties.

At least be clear as to which scope (M365 Unified or Power BI Activity) each section applies to or break up the content into two different articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Darian-FRB. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Darian-FRB,

Thank you for your comment and for getting involved.

We're in the process of creating better documentation for logs in Power BI. As part of this process, we'll replace this article with a new one. This will be done shortly, and your comments will be addressed. Please note that this may take some time.

Kesem
