### ISSUE TITLE
Paginated reports now in Pro:) 

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4207]
It was just announced this week at PASS Summit that paginated reports are now no longer just a premium feature and will be made available to Pro / Shared workspaces as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Version Independent ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Content: [Power BI Premium features. - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-features)
* Content Source: [powerbi-docs/enterprise/service-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-features.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @denglishbi,

Thank you for pointing out that paginated reports are not a Premium feature anymore.

I removed the paginated reports entry from the [Power BI Premium feature list](https://learn.microsoft.com/power-bi/enterprise/service-premium-features#power-bi-premium-feature-list).

Kesem
