### ISSUE TITLE
No more "Sign up for a Microsoft 365 trial of Office"

### ISSUE THREAD

**Issue by davidkhala** [MicrosoftDocs/powerbi-docs#4208]
Per [this section](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial#sign-up-for-a-microsoft-365-trial-of-office)

We are supposed to be able to sign up for a Microsoft 365 trial [on the Microsoft 365 web site](https://www.microsoft.com/microsoft-365/business/compare-more-office-365-for-business-plans)

But the current status of o365 trial webpage shows no trial option anymore.

Please get it updated
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f747f-9b4f-2bfc-831e-ed8232177d38
* Version Independent ID: b2da371d-aea3-010b-5e57-a6c8d5a9646d
* Content: [Signing up for Power BI with a new Microsoft 365 Trial - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial)
* Content Source: [powerbi-docs/enterprise/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @davidkhala. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @davidkhala , 
Thank you for your suggestion.  I've checked, and there still is an option to "Try for free" on the M365 site.  
All the best,
The DOCS team
