### ISSUE TITLE
How to reset incremental update

### ISSUE THREAD

**Issue by ThierryBIENVENU** [MicrosoftDocs/powerbi-docs#4209]
How to reset the incremental update programmatically ?
In other words, return to the first page of data after retrieving all the data ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a56f1862-1408-700b-2a3a-69f5473a6467
* Version Independent ID: 743dafe3-9296-eb47-0449-dd9874b1e086
* Content: [Fetch more data from Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/fetch-more-data)
* Content Source: [powerbi-docs/developer/visuals/fetch-more-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/fetch-more-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ThierryBIENVENU. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @ThierryBIENVENU. Here's the answer I got from one of the engineers:

The visual is usually expected to hold the dataview passed to it, so it can access whatever piece of data without communicating with PowerBI.

It’s also possible to start over by triggering a “fresh” update.
The visual can call persistProperties() to do that.

I hope this helps. I'll update the documentation to reflect this additional information.

**Comment by ThierryBIENVENU** [comment]
Thank you for your response. I will test the call to persistProperties()
Regarding "hold the dataview passed to it": In this case it is the same as doing an aggregate update, the incremental should be a way to avoid maintaining all data in the visual.

**Comment by mberdugo** [comment]
#sign-off

**Comment by ThierryBIENVENU** [comment]
That doesn't work for me :
- if I persist nothing persistProperties({})
-- Nothing append, the visual is not update
- if I persist a properties with the same value
-- Nothing append, the visual is not update
- if I persist a properties with an incremented value
-- update is call but with the same data view, i.e. the last dataview consumed and not the first page

**Comment by mberdugo** [comment]
Hi, @ThierryBIENVENU. It looks like you're right that it doesn't work. 
The general preference is for the visual to hold the data it has to avoid requesting it again.
Could you explain more about why you want to reset the data to the beginning? Maybe we can find a solution for you.

**Comment by ThierryBIENVENU** [comment]
Hi @mberdugo, thanks for your answer
For my case I gave up the idea of refreshing via the code and instead I display a message to the user asking them to filter to another visual so that reset my visual. As my visual is a button that post data to an external rest api it makes sense not to post the same data again.

As mentioned, I don't think it's a good idea to keep the data in the visual in addition to having it in the powerbi engine, it's double the memory footprint and it goes against the delegation principle of the general meaning of 'incremental update'.

But anyway, at least the information that datas are to be kept and note indicating that there are no way to go back to previous page should be mentioned in the documentation of the incremental update.

**Comment by mberdugo** [comment]
Hi, @ThierryBIENVENU. Thanks for your feedback. I passed your comments on to the engineers and will update the documentation soon.
