### ISSUE TITLE
Power BI Premium

### ISSUE THREAD

**Issue by ManuSQLGeek** [MicrosoftDocs/powerbi-docs#421]
Can you add a Power BI Premium column? Even though there are few features marked Yes in Power BI Service, they need Premium, like paginated reports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ManuSQLGeek . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ManuSQLGeek -- good point, thanks. For now I'm adding a note to the row for paginated reports. If we end up with a lot of Premium-only features, I can add a column. Thanks again!
