### ISSUE TITLE
ETA?

### ISSUE THREAD

**Issue by hokeson** [MicrosoftDocs/powerbi-docs#4210]
is there any estimation about when [Azure Log Analytics for Power BI](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-bi%2Ftransform-model%2Flog-analytics%2Fdesktop-log-analytics-configure&data=05%7C01%7CDharsini.B%40nestle.com%7Cfc419bb3816e41d1e1b408dac96a4843%7C12a3af23a7694654847f958f3d479f4a%7C0%7C0%7C638043755560021914%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=huoxBaFlrxOBB9WSPKdbVIZ4ZmfXsLKh3ZJvylI6wK4%3D&reserved=0)  will be moved to general availability?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38b32bbf-8798-420d-47d7-f94ece253385
* Version Independent ID: 6c39e53b-3089-26f5-ff03-771919d95c7a
* Content: [Configuring Azure Log Analytics in Power BI (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-configure)
* Content Source: [powerbi-docs/transform-model/log-analytics/desktop-log-analytics-configure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/log-analytics/desktop-log-analytics-configure.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hokeson. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post, and we cannot comment on when features will move to GA.
