### ISSUE TITLE
SSO for end users - implications when using PowerBI embedded

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerbi-docs#4211]
Hi,

we have PowerBI reports point to a data warehouse using AAD login. When enabling the `SSO for end users`, this works fine when viewing the report in the PBI service.

What are the implications of embedding the report (the users viewing the embedded report don't have AAD credentials):
- will the end user be prompted for credentials anyway
- will the SSO use the embedding's applications service principle (that is owner of the PBI workspace)
- will this not work?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf5c2cbb-f3de-c63e-fc74-a5157d5f5c9c
* Version Independent ID: dd280f16-bad8-5f60-f960-208047f6f9b2
* Content: [Azure Synapse Analytics (formerly SQL Data Warehouse) with DirectQuery - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-azure-sql-data-warehouse-with-direct-connect#single-sign-on)
* Content Source: [powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-azure-sql-data-warehouse-with-direct-connect.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @w0ut0. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
