### ISSUE TITLE
Circle Card visual documentation fix

### ISSUE THREAD

**Issue by vyshnavmk-lumel** [MicrosoftDocs/powerbi-docs#4212]
Need to add following Visual.ts constructor
`    this.formattingSettingsService = new FormattingSettingsService();
`

`import { VisualSettings } from "./settings";
`: No VisualSettings present in settings.ts, need to change 
`VisualFormattingSettingsModel -> VisualSettings  in settings.ts
`
 and 
`this.visualSettings = this.formattingSettingsService.populateFormattingSettingsModel(VisualSettingsModel, options.dataViews);
`  **to**
 `this.visualSettings = this.formattingSettingsService.populateFormattingSettingsModel(VisualSettings , options.dataViews);
`
in visual.ts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Add formatting options to a Power BI custom visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vyshnavmk-lumel. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @vyshnavmk-lumel. This entire article is currently undergoing revision and will be republished soon.

**Comment by mberdugo** [comment]
Thanks, @vyshnavmk-lumel. We're working on it. I wish I could give you a time estimate, but it's in our backlog.
