### ISSUE TITLE
Private Endpoint DNS Zone Names not matching Documentation

### ISSUE THREAD

**Issue by richardcaoshihua** [MicrosoftDocs/powerbi-docs#4214]
Hi, Team,

The Private DNS Zone name listed in the document (https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links) is as followed:
+ privatelink.analysis.windows.net
+ privatelink.pbidedicated.windows.net
+ privatelink.tip1.powerquery.microsoft.com

However, when we create the Private Endpoint, we are only getting the following:
+ privatelink.analysis.windows.net
+ privatelink.pbidedicated.windows.net
+ privatelink.prod.powerquery.microsoft.com

This is very confusing as the Customer does not know which DNS Forwarding Zone they should configure on their DNS Server as only tip1.powerquery.microsoft.com is mentioned in: https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns

Could you please help to check with Power BI Team and see if any update to the documentation is needed?

Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for accessing Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, we've updated that article with the proper endpoints. Thanks!

**Comment by andreaskhvid** [comment]
Seems like the private DNS zones listed here: https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns#analytics

Still does not match the ones listed here: https://learn.microsoft.com/en-us/fabric/security/security-private-links-use#step-5-create-a-private-endpoint
