### ISSUE TITLE
Linked Reports will not migrate

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4217]
Another item that there is not an equivalent for in the Power BI service for migration is Linked reports, so might want to include that in the following section here - https://learn.microsoft.com/en-us/power-bi/guidance/migrate-ssrs-reports-to-power-bi#assess

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f8c868cc-a15f-f870-ed4e-7b3d9dbd3ec0
* Version Independent ID: 1c353bbb-038f-5ea9-eb10-98401dd0fddb
* Content: [Migrate SQL Server Reporting Services reports to Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/migrate-ssrs-reports-to-power-bi)
* Content Source: [powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/migrate-ssrs-reports-to-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @denglishbi -- fixing now. Thanks!
