### ISSUE TITLE
Alaska Census and Borough Information

### ISSUE THREAD

**Issue by ttobinak** [MicrosoftDocs/powerbi-docs#4219]
Copper River Census Area is not recognized in choropleth map/filled map visualization in Power BI. It is still being recognized by Valdez-Cordova Census Area where this census area was split to Chugach and Copper River in 2019.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ttobinak. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @ttobinak,

Can you please let us know which document you're referring to?

Thanks,

Kesem
