### ISSUE TITLE
Salesforce connector

### ISSUE THREAD

**Issue by ManuSQLGeek** [MicrosoftDocs/powerbi-docs#422]
I see there is a salesforce connector in Power BI Desktop for RS. The table may be corrected with a right example for 

Connect to services like Salesforce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ManuSQLGeek . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ManuSQLGeek -- you're right that Power BI Desktop you can connect to Salesforce Objects and Salesforce Reports. Those aren't the same as the Salesforce content pack available in the Power BI service spelled out here: https://docs.microsoft.com/en-us/power-bi/service-connect-to-salesforce. Make sense?

**Comment by maggiesMSFT** [comment]
So I'm changing the No to a Yes and adding a note. Thanks for pointing that out!

**Comment by MichaelTomar** [comment]
You can leverage [Skyvia](https://skyvia.com/data-integration/analyze-salesforce-with-powerbi) to integrate Salesforce with Power BI in two main ways. First, you can replicate your Salesforce data to a data warehouse and subsequently connect it to Power BI. Alternatively, you can expose your Salesforce data as an OData endpoint that Power BI can directly consume. Both methods facilitate seamless data sharing and analytics.
