### ISSUE TITLE
Active StoreName example does not follow the column reference best practice Table[Column]

### ISSUE THREAD

**Issue by stachulec** [MicrosoftDocs/powerbi-docs#4222]
link to the best practice:
https://learn.microsoft.com/en-us/dax/best-practices/dax-column-measure-references
example should show 
`Active StoreName = IF(Stores[Status] = "On", Stores[StoreName], "Inactive")
`
instead of
`Active StoreName = IF([Status] = "On", [StoreName], "Inactive")
`
it can be valuable to new users to show the best practice in the offical examples
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16b31202-eae5-59aa-3de4-7e1fb897ed4f
* Version Independent ID: 9f595797-0c89-63d1-e8d8-9a67e2cc7e19
* Content: [Tutorial: Create calculated columns in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-tutorial-create-calculated-columns)
* Content Source: [powerbi-docs/transform-model/desktop-tutorial-create-calculated-columns.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-tutorial-create-calculated-columns.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stachulec. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look at updating that code with your suggestions.
