### ISSUE TITLE
Information on this page about sharing reports is confusing

### ISSUE THREAD

**Issue by devjain1987** [MicrosoftDocs/powerbi-docs#4223]
Please read this page again and make the modifications if required. In the Venn diagram while comparing difference between Power BI Desktop and Service. Sharing is written t be the unique feature of Power BI Service but the text in the first para states the Power BI desktop can also share reports directly.
It is confusing as to sharing reports is unique feature available in Service or Both

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0ba6184-412b-7e75-ef74-46ae14d62dd6
* Version Independent ID: bf97c0bc-6511-e0f0-8df3-9e4f83492fe9
* Content: [Comparing Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop)
* Content Source: [powerbi-docs/fundamentals/service-service-vs-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-service-vs-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devjain1987. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @devjain1987 , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
