### ISSUE TITLE
Saving to another workspace does not seem to work

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#4224]
I am an admin for a number of workspaces. Why "Save a Copy" is greyed out? It does not seem to be possible to copy a report even if you are the admin.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83c63999-09de-cccf-ae53-ef7fcfbc1186
* Version Independent ID: 39407557-14d4-f78b-bfcb-ea95cf501c47
* Content: [Copy reports from other apps or workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-copy-reports)
* Content Source: [powerbi-docs/connect-data/service-datasets-copy-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-copy-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gvggvg. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @gvggvg, I am going to close this issue now. Please reach out with more detail if you find you are still having the issue. Thanks!
