### ISSUE TITLE
Please Menton the -Environment Parameter When Presenting the Connect-PowerBIServiceAccount Cmdlet

### ISSUE THREAD

**Issue by Darian-FRB** [MicrosoftDocs/powerbi-docs#4226]
Documentation such as https://learn.microsoft.com/en-us/powershell/power-bi/overview?view=powerbi-ps#log-in-to-power-bi does not mention the existence or need of the -Environment parameter when connecting to Power BI via PowerShell. Such a parameter is not needed for a number of other M365/Azure modules, so Power BI is an outlier.

As an example, one of my colleagues was encountering an 'Unauthorized' error that appeared to be a permissions issue. This was actually a licensing issue since he did not include the correct Environment parameter. In our case it is the "USGov" environment. Since the MicrosoftPowerBIMgmt PowerShell module is somewhat unique with the need of the -Environment parameter it would be helpful if this was noted in the documentation.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Darian-FRB. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Darian-FRB,

I believe this issue was fixed.

Thanks for pointing this out,

Kesem
