### ISSUE TITLE
View as other user need to select role as well

### ISSUE THREAD

**Issue by Jogihu** [MicrosoftDocs/powerbi-docs#4227]
Hello

It should be added and clarified, that in "View as roles", "Other user" only works if one of the defined roles is selected as well.
So, if you only select "Other user", no RLS is applied.
In order to be applied, you have to select the role as well, that shall be used for the "Other user".

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jogihu. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @jogihu. Sorry for the very delayed response. I'd like to figure out if this is still an issue, or if the documentation has already been fixed, or maybe the software updated.
When you select **View as** Other user and supply a user, you should see what that user would see. If that user is assigned to  a role you should see what members of that role can see. If the user is not assigned to a role, they shouldn't be able to see anything, unless of course, they are admins, members or contributors to the workspace. It shouldn't depend on having another role selected.

**Comment by Jogihu** [comment]
Hi @mberdugo
Thanks for your response. I didn't have time until today to have a look at it, sorry. The issue is still present. 

It is specifically about the "Validate the roles within Power BI Desktop" part of that documentation, which is in a sub-page: 
https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/includes/rls-desktop-view-as-roles.md

As there is no assignment of users to roles in Power BI Desktop (because this is done and used only in the Service), it doesn't know which role it should apply. 

The behavior of PBI Desktop (Version 2.119.986.0 64-bit) still is: 
If you want to test RLS with a user, you have to select the role as well. 
Else it completely ignores RLS, as it doesn't know which role it should apply (even if there is only one).

So at least the screenshot in the documentation must be updated to reflect this. That is, in step 3. "Eastern US" must be selected as well. Would be nice to have some explanation (as proposed) as well.

Please reopen, or maybe it is better to create an new issue for that specific subpage of the document.

**Comment by mberdugo** [comment]
Interesting. So validation by individual users can only be done in the Service because that's where the users are assigned to a role. In the Desktop, the username is meaningless and only the roles themselves can be validated. Is this correct?

**Comment by Jogihu** [comment]
The username has a meaning, but only if it is combined with a role by activating both check boxes - so in the example of the documentation you have to activate "Other user" and additionally "Eastern US".
This is important for dynamic RLS where we use the DAX function USERNAME() combined with a table containing user names.
Then, PBI returns the value of "Other user" as the result of USERNAME() in our DAX in the table filter that we defined for the selected role.

**Comment by mberdugo** [comment]
Got it. Thanks. I'll update the doc.
