### ISSUE TITLE
Capacity Re-Sizing - downtime

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#4228]
We should explicitly state that there is no downtime involved in resizing a capacity.  We currently state this for Embedded capacities (see https://learn.microsoft.com/en-us/power-bi/developer/embedded/power-bi-embedded-generation-2) but i was unable to find this stated for Premium Capacities.

The section on resizing the capacity would be a perfect place to make a statement that this happens without any downtime of the capacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Configure and manage capacities in Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-manage)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-manage.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rosscouldrey. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @rosscouldrey,

I'll start an email thread for this.

Thanks,

Kesem
