### ISSUE TITLE
No information on impacts of how Power BI Embedded effects Azure Analysis Live Connection queries

### ISSUE THREAD

**Issue by TwoPatient** [MicrosoftDocs/powerbi-docs#4229]
I'm struggling to find out any information on how Power BI Embedded capacity effects Azure Analysis Services Live Connection queries.

How do I determine what Power BI Embedded capacity for an Azure Analysis Services live connection?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#which-sku-should-i-use)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TwoPatient. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @TwoPatient. I'll try to find this out for you.

**Comment by mberdugo** [comment]
Hi @TwoPatient, sorry for delayed response. Check out the column: “DirectQuery/Live connection (per second)” in the table [here] ([https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#sku-memory-and-computing-power]). Live Connection is for AAS hosted datasets.
The table shows the concurrency of connections per second limit for each SKU.
I hope this helps.
