### ISSUE TITLE
R Visuals

### ISSUE THREAD

**Issue by ManuSQLGeek** [MicrosoftDocs/powerbi-docs#423]
The R Visuals can be created in Power BI Report Server. Is this comparison up to date with August release of Power BI RS?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ManuSQLGeek . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @ManuSQLGeek, as we discussed in your PR https://github.com/MicrosoftDocs/powerbi-docs/pull/424, you're right -- you can create R visuals in the Power BI Report Server version of Power BI Desktop. But you can't successfully save them to Power BI Report Server. I've updated the table to make that clearer. Let me know what you think. Thanks again!
