### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JossMarnez** [MicrosoftDocs/powerbi-docs#4230]
Broken link: https://blogs.office.com/2014/03/24/creating-burndown-charts-for-project-using-power-pivot-and-power-query/

![image](https://user-images.githubusercontent.com/28204394/205182759-f04c6a95-c43c-4ccf-b03b-7b58e24b981a.png)

/joss
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-project-online-connect-to-data)
* Content Source: [powerbi-docs/connect-data/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JossMarnez. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks, we're removed that (bad) link.
