### ISSUE TITLE
Every single day I fight with this

### ISSUE THREAD

**Issue by RobWaibelJr** [MicrosoftDocs/powerbi-docs#4231]
About ready to go to Tableau

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8131601d-6602-1e2c-0f16-d4b577aaaf74
* Version Independent ID: dac38cd1-2f8f-7a18-6a07-4da8e939545f
* Content: [Power BI Desktop Send a Smile Privacy Statement - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-send-smile-privacy-statement)
* Content Source: [powerbi-docs/fundamentals/desktop-send-smile-privacy-statement.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-send-smile-privacy-statement.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @RobWaibelJr. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
I'm sorry to hear you're having so much trouble with that. There might be people in the community who could provide help, feedback, or other alternatives that might make your experience better. 

Here's a link: Power BI Community, found at https://community.powerbi.com.
