### ISSUE TITLE
this page is asking to install vulnerabilities in d3 library v5 

### ISSUE THREAD

**Issue by ansgargw** [MicrosoftDocs/powerbi-docs#4232]
I don't understand why I am asked to install a lib with vulnerabilities. I don't feel this is safe guidance and at least the reason should be addressed. 
**PS C:\Users\AGW> npm list**
AGW@ C:\Users\AGW
`-- d3@7.6.1

**PS C:\Users\AGW> npm ins d3 --save**
up to date, audited 39 packages in 4s
found 0 vulnerabilities

**PS C:\Users\AGW> npm i d3@^5.0.0 --save**

added 2 packages, removed 4 packages, changed 32 packages, and audited 37 packages in 6s

**8 high severity vulnerabilities**

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ansgargw. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @ansgargw, and sorry for the delayed response. I consulted with the engineers and the vulnerabilities are because we are installing old versions of d3. I'll update the document to not include version numbers. In the meantime, install them again using `@latest` instead of the version number and you shouldn't get any vulnerabilities. I hope this helps.
