### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lalitprasad** [MicrosoftDocs/powerbi-docs#4233]
There is a broken link on the page (https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-data-protection-overview.md). 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lalitprasad. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @, 
Thank you for your suggestion.  I am unable to find the file referenced so am closing this Issue.  (https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-data-protection-overview.md).
All the best,
The DOCS team
