### ISSUE TITLE
RLS new way to access permissions

### ISSUE THREAD

**Issue by iqb-dawn** [MicrosoftDocs/powerbi-docs#4235]
As per this link https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/row-level-security-report-server.md

```
In Power BI Report Service, select the ellipsis (…) next to the report.

Select Manage > Row-level security.
```
In my case I could not find this. Instead I selected `select the ellipsis (…) next to the data set` and click `Security`

Dunno I was only one or someone else will faces the same issue.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @iqb-dawn. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @iqb-dawn -- investigating.

**Comment by paulinbar** [comment]
Hi @iqb-dawn, thanks for reaching out. I'm moving this issue to our work item backlog for better tracking and consideration. Closing it here here now.
