### ISSUE TITLE
constructor missing formattingSettingsService

### ISSUE THREAD

**Issue by FritsWillem** [MicrosoftDocs/powerbi-docs#4236]
The example code doesn't construct the formattingSettingsService.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Add formatting options to a Power BI custom visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FritsWillem. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi, @FritsWillem. The tutorial has been updated. Good luck with it!
