### ISSUE TITLE
"AAD Credentials" 

### ISSUE THREAD

**Issue by sfc-gh-mjohnson** [MicrosoftDocs/powerbi-docs#4237]
This sentence is unclear and has concerned some of the teams we support:
"This setting approves sending AAD credentials to Snowflake for authentication for the entire organization. "

It should be revised to say something like: "This setting approves sending AAD authentication tokens to Snowflake from within the Power BI Service. This setting is set at the organization level."  You could also link to the Snowflake docs here where there is a helpful diagram. 

 https://docs.snowflake.com/en/user-guide/oauth-powerbi.html 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 328a161c-b51e-05d1-c185-cb244547c3f3
* Version Independent ID: 0bef7bb0-541e-a74b-0f68-359690ae8b8e
* Content: [Connect to Snowflake with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-snowflake)
* Content Source: [powerbi-docs/connect-data/service-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-snowflake.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sfc-gh-mjohnson. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the suggestion, I've incorporated that into the article.
