### ISSUE TITLE
Interaction with filter pane?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4238]
It's not clear how filter parameters are supposed to interact, if at all, with filters in the filter pane. Are they complementing each other, or overwriting each other?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @otravers, thanks for reaching out. I'm moving this issue to our work item backlog for better tracking and consideration. Closing it here here now. To get a faster answer until the docs are updated, try the [Power BI Community]( https://community.powerbi.com).
