### ISSUE TITLE
Configuration Instructions Missing

### ISSUE THREAD

**Issue by Teckfahimkanji** [MicrosoftDocs/powerbi-docs#4241]
Hi,

You're missing configuration instructions.  What value do I put in for capacity-id (i know but just saying) ... UTC_OFFSET, time1 time2 etc...

Cheers,

Fahim.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Version Independent ID: 7cb41873-ca46-e5d3-14a9-d7d97a1197f2
* Content: [Monitor Power BI Premium Gen2 capacities with the Gen2 metrics app. - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-gen2-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-gen2-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Teckfahimkanji. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Teckfahimkanji,

Configuration instructions are available from [Install the Gen2 metrics app](https://learn.microsoft.com/power-bi/enterprise/service-premium-install-gen2-app).

Thanks,

Kesem
