### ISSUE TITLE
Prerequisites section for Analyze in Excel

### ISSUE THREAD

**Issue by marshal115** [MicrosoftDocs/powerbi-docs#4242]
[Enter feedback here]
The prerequisites section for Analyze in Excel should be corrected. 
1. Your dataset in Power BI must have pre-defined measures....
>>Now implicit measures can be used so this sentence should either be removed or revised.

3. Analyzing Power BI data in Excel requires that the dataset be in a Power BI Premium workspace or that you have a Power BI Pro or Premium Per User (PPU) license....
>>Now even Free users can use this feature connecting datasets in My Workspace. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 239b3819-f483-97d3-2c1c-e5747a2dcc3a
* Version Independent ID: 239b3819-f483-97d3-2c1c-e5747a2dcc3a
* Content: [Connect Excel to Power BI datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-power-bi-datasets-excel#prerequisites)
* Content Source: [powerbi-docs/collaborate-share/service-connect-power-bi-datasets-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-power-bi-datasets-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marshal115. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi again, @marshal115, I'm also moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for providing your feedback!
