### ISSUE TITLE
PowerShell with Power BI Premium

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4243]
The page states:

> "Azure Analysis Services cmdlets in the Az.AnalysisServices module aren't supported for Power BI datasets."

This is not entirely true as [Invoke-ASCmd cmdlet](https://learn.microsoft.com/en-us/powershell/module/sqlserver/invoke-ascmd) is supported in Power BI Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee1b920c-639a-a627-58f2-e8fd69c9ef7d
* Version Independent ID: ab13e62f-0629-0aed-7e85-a902e150f9b1
* Content: [Dataset connectivity and management with the XMLA endpoint in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools)
* Content Source: [powerbi-docs/enterprise/service-premium-connect-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-connect-tools.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@otravers - The statement is correct. Invoke-ASCmd is in the SQLServer module, not the Az.AnalysisServices module.
