### ISSUE TITLE
VisualSettingsModel should be VisualSettings

### ISSUE THREAD

**Issue by domdtyler** [MicrosoftDocs/powerbi-docs#4247]
The code as provided does not compile correctly. It appears that the error is in 'Adding custom formatting options' > part 5. The code currently ends with: 

`export class VisualSettingsModel extends FormattingSettingsModel {
    public circle: CircleSettings = new CircleSettings();
    public cards: FormattingSettingsCard[] = [this.circle];
}`

Changing this to the following corrects the compile errors: 

`export class VisualSettings extends FormattingSettingsModel {
    public circle: CircleSettings = new CircleSettings();
    public cards: FormattingSettingsCard[] = [this.circle];
}`

I assumed that the error was here as the following code in part 8 refers to `VisualSettings` twice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Add formatting options to a Power BI custom visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @domdtyler. This issue has been assigned to the doc author for review.

**Comment by domdtyler** [comment]
It appears my understanding of what was broken was insufficient. I will open a new ticket to clarify.

**Comment by mberdugo** [comment]
Thanks for your comment, @domdtyler, This tutorial is in the process of being updated. It should be fixed in a week or so.
