### ISSUE TITLE
Tutorial instructions and code contain errors

### ISSUE THREAD

**Issue by domdtyler** [MicrosoftDocs/powerbi-docs#4248]
I am currently working through the Power BI visual development tutorial. On the 'Add formatting options' page, there are a number of issues that I have come across: 

1. Under 'Adding formatting options', point (2) suggests that I should see a message that reads 'Formatting options are unavailable for this visual.' This is not the case - I can alter the title, background, and more for this visual.
2. Under 'Adding custom formatting options', point (2) provides code to add into the `objects` object. However, pasting this between the `{}` provided previously throws an error, as there are extra curly braces. Perhaps this instruction should be updated to simply replace `"objects": {},` with:

`"objects": {
        "circle": {
            "properties": {
                "circleColor": {
                    "type": {
                        "fill": {
                            "solid": {
                                "color": true
                            }
                        }
                    }
                },
                "circleThickness": {
                    "type": {
                        "numeric": true
                    }
                }
            }
        }
    },`

3. Under 'Adding custom formatting options', point (8) provides code which imports `VisualSettings` then references it within the `Visual` class. Point (5) actually creates `VisualSettingsModel`, which means that this code throws an error. I updated the point (8) code to import/reference `VisualSettingsModel`.
4. Point (10) seems to break the Power BI visual. The code up to this step works correctly, but after this point, no visual is displayed. Any combination of those three lines of code causes the visual to disappear. 
5. I was unable to get past point (10) so that may be the cause, but point (15) shows that new settings should be available in the Power BI Formatting pane. These do not appear for me. 

I would be more than happy to provide any other documentation or details that you might find useful to support this issue. Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc4f82a-1cec-444c-8561-c02aa38caa96
* Version Independent ID: c05253d9-f12e-b2ee-763f-96e4a76fec54
* Content: [Add formatting options to a Power BI custom visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your question, @domdtyler. This tutorial is in the process of being updated. Hopefully, it should be done by next week.

**Comment by mberdugo** [comment]
Hi @domdtyler . The new tutorial is up. Good luck!
