### ISSUE TITLE
In step 12, need instructions for Windows Authentication

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#425]
The instructions above only show "For Log on to the server, make sure Use SQL Server Authentication is selected, then type the user name and password you created in Azure for the sample database."  What if we don't use SQL Server authentication?  Need either instructions for it, or details on Windows authentication support. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da59f209-0ccd-01d0-6e0e-12943ef3680e
* Version Independent ID: 390690ff-76bd-f4c6-afac-d5ad2f3854cb
* Content: [Tutorial: Create a paginated report and upload it to the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-quickstart-aw)
* Content Source: [powerbi-docs/paginated-reports-quickstart-aw.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-quickstart-aw.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @chrisweis. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @chrisweis -- Thanks for asking! Windows auth isn't supported when connecting to SQL Azure, so it wouldn't work in this tutorial. However, to connect to an on-premises SQL DB, you can use Windows Auth when going through a Power BI gateway -- the same gateway you'd use for a Power BI report. https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started 
Hope that helps!
