### ISSUE TITLE
Known issues page in Power BI Docs does not represent all known issues.

### ISSUE THREAD

**Issue by greggyb** [MicrosoftDocs/powerbi-docs#4251]
The known issues page seems to represent only a subset of known issues. As of this submission, there is a known issue in Power BI Desktop with product team involvement, that has been acknowledged for 1.5 weeks, yet it is not reflected on the known issues page.

Here is the community issues post with involvement by Taylor Clark and an indication that the root cause is identified and a patch is underway: https://community.powerbi.com/t5/Issues/Memory-leak-when-using-PQ-advanced-editor/idc-p/2961837

The known issues page seems less than useful if it is not a reliable communication of the current state of the product.

As a side note, I find projects and products with comprehensive communication about issues to be much more attractive in the market than those without. Every product will have bugs and issues of varying severity. It is comforting to know that I can depend on a vendor to provide support and let me know what is going on. It fosters feelings of frustration and futility when such communication is lacking.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @greggyb. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @greggyb ,
Thank you for your input.  We are working on improving our known issues process so please stay tuned. 
All the best,
the DOCS team
