### ISSUE TITLE
Known issues Log

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#4252]
It looks like the Known Issues are deleted after 46 days. Not sure where 46 came from. Can you please explain. Here are few suggestions:
1. It's hard to believe that there are only 5 known active issues and 4 closed issues. What criteria are used to surface the issues to this page ?
2. Can you please make all the issues available on a separate page? This will be super helpful. Ideally a Power BI report that tracks all the issues (active/closed) would be great.
3. Issues are very scant on details. No error messages are shown, which Power BI release was used, how it was solved with steps/screenshots, how to recreate the issue etc. I understand that can be a burden on the docs team but imagine how much it will help the users and the support team. 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by greggyb** [comment]
cross reference #4251

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pawarbi. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @pawarbi ,
Thank you for your suggestions.  We are in the process of improving how we present our known issues, so stay tuned.  I've passed along your comments to the Known Issues team.  
Thanks again. 
the DOCS team
