### ISSUE TITLE
Example on github uses API 3.8.0

### ISSUE THREAD

**Issue by novasilva-wouter** [MicrosoftDocs/powerbi-docs#4255]
[Enter feedback here]
This document contains a link claiming to use the 5.1 version of the API : 
https://github.com/microsoft/PowerBI-visuals-sampleBarChart

This example still uses API version 3.8.0

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 777292ae-fa02-7f8f-395d-2d9b850883ba
* Version Independent ID: 777292ae-fa02-7f8f-395d-2d9b850883ba
* Content: [Customize the format pane in Power BI custom visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/format-pane)
* Content Source: [powerbi-docs/developer/visuals/format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/format-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @novasilva-wouter. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @novasilva-wouter. We recently upgraded to 5.1 but I guess we forgot to update the barchart sample. I'll look into it and try to get it updated as soon as I can.

**Comment by mberdugo** [comment]
Hi @novasilva-wouter, here's the correct link. I'll update the document. Thanks again for pointing this out.
https://github.com/microsoft/PowerBI-visuals-sampleBarChart/tree/barChartTutorial
