### ISSUE TITLE
Lacking clear explanation and examples for a simple TextInput

### ISSUE THREAD

**Issue by novasilva-wouter** [MicrosoftDocs/powerbi-docs#4256]
The following code does not work.
"Type 'FormattingComponent.TextInput' is not assignable to type '"FontControl" | "MarginPadding"'

Type '{ objectName: string; propertyName: string; }' is not assignable to type 'ControlType<SimpleComponentType>'.
  Object literal may only specify known properties, and 'objectName' does not exist in type 'ControlType<SimpleComponentType>'

Please provide a more basic example of how to express this very basic case.

        const group1_license: powerbi.visuals.FormattingGroup = {
            displayName: "License Control Group",
            uid: "license_licenseControl_group_uid",
            slices: [                
                {
                    displayName: "License Name",
                    uid: "License_licenseControl_licenseName_slice",
                    control: {
                        type: powerbi.visuals.FormattingComponent.TextInput,
                        properties: {
                            descriptor:
                            {
                                objectName: "license",
                                propertyName: "licenseName"
                            }
                        }
                    }
                }                
            ]
        };

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 777292ae-fa02-7f8f-395d-2d9b850883ba
* Version Independent ID: 777292ae-fa02-7f8f-395d-2d9b850883ba
* Content: [Customize the format pane in Power BI custom visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/format-pane#formatting-model)
* Content Source: [powerbi-docs/developer/visuals/format-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/format-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @novasilva-wouter. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @novasilva-wouter. I sent your code sample to one of our engineers and here's the fix she suggested:

      const group1_license: powerbi.visuals.FormattingGroup = {
            displayName: "License Control Group",
            uid: "license_licenseControl_group_uid",
            slices: [                
                {
                    displayName: "License Name",
                    uid: "License_licenseControl_licenseName_slice",
                    control: {
                        type: powerbi.visuals.FormattingComponent.TextInput,
                        properties: {
                            descriptor:
                            {
                                objectName: "license",
                                propertyName: "licenseName"
                            },
                            placeholder: "Enter here text input placeholder",
                            value: "Enter here text input value"
                        }
                    }
                }                
            ]
        };

The issue was fixed by adding the last two lines “placeholder: … “ and “value: …”

Take a look at the “TextInput” object and check what the required fields are in “formatting-model-api.d.ts”
In this case, you missed adding required TextInput fields “value” and “placeholder”

I would suggest looking at [Introduction to use Data view utils to create formatting models in Power BI visual - Power BI | Microsoft Learn](https://learn.microsoft.com/en-us/power-bi/developer/visuals/utils-formatting-model) and think about using the formatting models utils which should be easier to work with and clearer. 

Hope this helps.

**Comment by novasilva-wouter** [comment]
Thank you @mberdugo that is very helpful.

Somehow I hadn't been able to locate that documentation link.
