### ISSUE TITLE
NPM install commands

### ISSUE THREAD

**Issue by mtsanaissi** [MicrosoftDocs/powerbi-docs#4257]
In the "Install development libraries" section, it says that the npm install commands could be ran once per machine. In this case, shouldn't the commands have the -g flag?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup?tabs=windows)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mtsanaissi. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @mtsanaissi. I'll check and get back to you.

**Comment by mtsanaissi** [comment]
If you take this direction, I believe the article will be misleading. It will take more than just removing that note from the document, because the preceding steps don't get the reader to the point where it makes sense to install local dependencies, as the reader would not have created a project yet.

Glad to help and happy to learn it's best to install as local dependencies.

**Comment by mberdugo** [comment]
Thanks for your feedback. I'm working with the engineers to update this article. I'll pass along your comments.

**Comment by mberdugo** [comment]
@mtsanaissi, while we're at it, another problem we noticed with this article is that the version numbers it gives for the d3 libraries are old and lead to vulnerabilities. Install them without the version numbers. If you already installed with the version numbers, reinstall using @latest instead of the version number.

**Comment by mberdugo** [comment]
Hi @mtsanaissi. After discussing some more with the engineers, it looks like you don't even need to install the d3 dependencies separately When you create a new project, the dependencies are installed automatically. The pbiviz tool can be installed either locally or globally. The advantage of doing it locally is that you always get the latest version whereas if you do it globally you can forget about it and not update when a new version comes out. I'll update the documentation to reflect this, though it might not be published until after the holidays.
