### ISSUE TITLE
Isn't Premium required?

### ISSUE THREAD

**Issue by tomweinandy** [MicrosoftDocs/powerbi-docs#4261]
There appear to be a contradiction in describing the premium capacity requirement here: https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights#publishing-a-report-with-text-analytics-or-vision-functions

The final line of the section reads "Reports with applied Text Analytics and Vision functions should be published to a workspace that is not on a Premium capacity, otherwise refreshing the dataset will fail." Shouldn't the "not" be removed since the data refresh will **only** succeed if the report is published to a workspace with premium capacity?

Happy to be proven wrong. Thanks!

~Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86f95078-89ba-6ba2-231b-b130755c8510
* Version Independent ID: 8f152dab-fea9-714a-f97e-f0d68109151f
* Content: [Connect to AI Insights in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-ai-insights)
* Content Source: [powerbi-docs/transform-model/desktop-ai-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-ai-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by paulinbar** [comment]
Hi @tomweinandy, thanks for your comment. I have assigned the author of the article to look into it. Thanks!

**Comment by davidiseminger** [comment]
You're absolutely right! I've corrected that, thanks!
