### ISSUE TITLE
TMSL scripting of automatic aggregations?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4262]
The announcement mentioned both TMSL and TOM scripting:
https://powerbi.microsoft.com/en-in/blog/announcing-general-availability-of-automatic-aggregations/

The documentation only mentions TOM. Is there TMSL support for automatic aggregations?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49236109-b1a3-c7d9-27d2-93b99a6b024c
* Version Independent ID: 49236109-b1a3-c7d9-27d2-93b99a6b024c
* Content: [Automatic aggregations overview - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/aggregations-auto)
* Content Source: [powerbi-docs/enterprise/aggregations-auto.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/aggregations-auto.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.
