### ISSUE TITLE
Support in TOM and TMSL?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4263]
Automatic aggregations are exposed for programmatic use in the TOM. Is there a way to use TMSL or TOM scripting to create user-defined aggregations?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [User-defined aggregations - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/aggregations-advanced)
* Content Source: [powerbi-docs/transform-model/aggregations-advanced.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/aggregations-advanced.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@otravers - The current scripting limitation was described in the [Auto Aggs GA blog post](https://powerbi.microsoft.com/en-us/blog/announcing-general-availability-of-automatic-aggregations/#:~:text=Tabular%20Object%20Model,the%20coming%20months.). Unfortunately, that engineering work continues to be ongoing. When available, it will be announced first on the blog. We'll add something to the documentation at some point after.
