### ISSUE TITLE
"Download a copy of a report" statement not true?

### ISSUE THREAD

**Issue by marshal115** [MicrosoftDocs/powerbi-docs#4264]
[Enter feedback here]
It looks like the statement "You can only download the original report. You can't download a copy of a report" may not be true as I could download the copy of a report. 

---
#### Document Details
![2022-12-31_11-32-32](https://user-images.githubusercontent.com/63047810/210122523-c4e83090-50dc-480a-a6e5-36c222a31f57.png)

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [Download a report from the Power BI service to Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#limitations-when-downloading-a-report-pbix-file)
* Content Source: [powerbi-docs/create-reports/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-export-to-pbix.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marshal115. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @marshal115, I'm moving this issue to our work item backlog for better tracking, and closing it here here now. Thanks for providing your feedback!
