### ISSUE TITLE
How to define the roles?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4265]
Step 3 states:

> The roles created in the previous step will appear. 

However, the previous step does not define roles. How did the roles get into the model?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7fb699f-5c14-f5d5-8f32-1c1539f213d1
* Version Independent ID: a7fb699f-5c14-f5d5-8f32-1c1539f213d1
* Content: [Object-level security (OLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-ols?tabs=table)
* Content Source: [powerbi-docs/enterprise/service-admin-ols.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-ols.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @VitalyMCT. You're correct. The roles aren't created in the previous step. They're created in step 1 using the same method as creating RLS roles [here](https://learn.microsoft.com/power-bi/enterprise/service-admin-rls#define-roles-and-rules-in-power-bi-desktop). I'll update the documentation accordingly.
