### ISSUE TITLE
Step 4 user interface on Power BI service is a way off of what we have in the documntation here

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/powerbi-docs#4267]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12ac2aa1-b899-184c-10c3-7909aa32bff8
* Version Independent ID: 17e2b2b8-02c5-fcf0-32ab-7f3ef2eb271f
* Content: [Create scorecards and manual metrics - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-goals-create)
* Content Source: [powerbi-docs/create-reports/service-goals-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-create.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ed7257. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @ed7257, Thanks for your feedback. I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime.
