### ISSUE TITLE
Full screen mode no longer exists in Power BI Desktop

### ISSUE THREAD

**Issue by mazamorac** [MicrosoftDocs/powerbi-docs#4269]
The text and screenshots mention "Full screen mode" in Power BI Desktop.

That doesn't exist anymore and all the discussion about that is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 052edfa5-0db0-da15-88c0-7841f4149347
* Version Independent ID: fa7d4f3d-6480-700b-bd67-3edcc464859b
* Content: [Focus mode and full screen mode - how to zoom in to see more detail - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-focus?source=docs)
* Content Source: [powerbi-docs/consumer/end-user-focus.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-focus.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mazamorac. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @mazamorac m 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
