### ISSUE TITLE
Alternative Email Address

### ISSUE THREAD

**Issue by penguinjack2005** [MicrosoftDocs/powerbi-docs#427]
Hi all. The above doesn't seem to be working for us. I can now see an alternate email has been setup in Office 365 however when I try to setup a report subscription and refresh the data nothing is received at the alternate email address. We're also trying to use this alternate email for gateway failure notifications as well. Can you suggest anything we may be doing wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed24d8b1-4126-84b9-e255-3b0fd3d16046
* Version Independent ID: 54c8d9b9-f6ca-a05d-6714-23fc593e31dd
* Content: [Using an alternate Email Address - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-alternate-email-address-for-power-bi)
* Content Source: [powerbi-docs/service-admin-alternate-email-address-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-alternate-email-address-for-power-bi.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @penguinjack2005. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @penguinjack2005, I recommend checking with support (https://powerbi.microsoft.com/en-us/support/) or posting a question to the forums for this (https://community.powerbi.com/).

**Comment by penguinjack2005** [comment]
No I don't think there is. I raised a support ticket but there doesn't appear to be an outcome from that and others have again raised the issue in forums without an outcome. I don't really understand what the above article is supposed to resolve?

**Comment by mgblythe** [comment]
Closing b/c this is a service/support issue. I'll update the doc if I get any more guidance.
