### ISSUE TITLE
Too technical by far.

### ISSUE THREAD

**Issue by Quorthon-23** [MicrosoftDocs/powerbi-docs#4270]
[Article begins by explaining that datamarts provide something to do with datamarts]. Lots of technical jargon such as 'semantic layer' without explaining what it is. Really not helpful.

Why is this form marked as 'submit new issue'? I was giving feedback on a web page, not reporting a bug. 
Why is Github designed to be so non-intuitive?

This will probably be my first and last post on here. What a ridiculous way to collect feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4ed455dc-940f-cb5f-86d6-36448122edad
* Version Independent ID: 4ed455dc-940f-cb5f-86d6-36448122edad
* Content: [Understand datamarts (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-understand)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Quorthon-23. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for taking the time to respond, even if it's cumbersome. Sorry for the overly technical info in this article, there's other information in other articles on datamarts that might be helpful
