### ISSUE TITLE
should "line">"roundEdge" be "border">"radius"?

### ISSUE THREAD

**Issue by snowliver** [MicrosoftDocs/powerbi-docs#4272]
"line" > "roundEdge" is not working as expected, and changing the theme inside PowerBI Desktop leads to the setting "border" > "radius".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @snowliver. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @snowliver, you've reached the channel for feedback for the content writers, while this sounds like product issue. I suggest you contact our [support](https://support.powerbi.com/) if you think things are not working as they should. Thanks!

**Comment by snowliver** [comment]
Hi @paulinbar https://github.com/MicrosoftDocs/powerbi-docs/commit/e1f789ef6fdfe87778c758358905ab4afced5aa3 from Feb 17th addressed that already by removing the whole section.
