### ISSUE TITLE
Could you make this page be readable?

### ISSUE THREAD

**Issue by dineshj231** [MicrosoftDocs/powerbi-docs#4273]
Very hard to understand as there are many headers with confusing details. Please write an article that is reader friendly. 
[Enter feedback here]
Very hard to understand as there are many headers with confusing details.  Please write an article that is reader friendly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dineshj231. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @dineshj231, You definitely have a point about this. I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
