### ISSUE TITLE
Remove reference to Internet Explorer

### ISSUE THREAD

**Issue by vattybear** [MicrosoftDocs/powerbi-docs#4275]
Update the note about authentication requiring Internet Explorer 10 or higher 

( There are many data connectors for Power BI Desktop that require Internet Explorer 10 (or newer) for authentication. )

I am not sure if this requires just updating to Edge or if that note is valid / required anymore (or else I would have submitted a PR) 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources)
* Content Source: [powerbi-docs/connect-data/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vattybear. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated that article. Thanks!
