### ISSUE TITLE
Activities missing technical name

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/powerbi-docs#4276]
Why are there Activities with a friendly name but not a technical name? 

if there's no technical name how can we indentify the activity in the log? 
are these deprecated activities or in the roadmap and not yet implemented? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by davidiseminger** [comment]
Sorry, I don't see the activities you mention in the article. It could be that the article has been updated since you submitted.
