### ISSUE TITLE
Include how to get user row in addition to username and userprincipalname  

### ISSUE THREAD

**Issue by iqb-dawn** [MicrosoftDocs/powerbi-docs#4277]
In the documentation of,

**Row-level security (RLS) with Power BI**
https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls
https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md

I can see **Using the username() or userprincipalname() DAX function** but how to get role of the user because the documentation is related to role?

**Comment by mberdugo** [comment]
Thanks for your question, @iqb-dawn. I'm not sure I understand your problem. 
To assign a user as a member of a role, see [this section](https://learn.microsoft.com/power-bi/enterprise/service-admin-rls#working-with-members). Then, the user will automatically see only what their role allows. 
I hope this helps.

**Comment by iqb-dawn** [comment]
@mberdugo I am talking about M Queries. So, if you right on data source -> Advance Settings you will see M Query like below. How can I get logged-in user role?

![image](https://user-images.githubusercontent.com/87642965/212832637-f37c7b99-fc1d-45db-bc63-a3ba10004ad5.png)

![image](https://user-images.githubusercontent.com/87642965/212832679-4fcea91b-09cd-42ca-863a-efff3c3dc24a.png)

**Comment by mberdugo** [comment]
OK, I think I understand your question. You want to know what function will return the role of a user?
If so, try using the SELECTEDVALUE function on the table that the Role (RLS) is applied against.
Good luck.

**Comment by iqb-dawn** [comment]
RLS roles are not coming from table. They are Power BI features.

**Comment by iqb-dawn** [comment]
Thanks. Posted the idea https://ideas.powerbi.com/ideas/idea/?ideaid=ec108ef2-769a-ed11-9ac4-281878bd50c1
