### ISSUE TITLE
duplicated technical names for activities

### ISSUE THREAD

**Issue by bernatagulloesbrina** [MicrosoftDocs/powerbi-docs#4278]
there are duplicated technical names for activities sometimes with different friendly names

![image](https://user-images.githubusercontent.com/40455069/211291186-7b9ccf28-6d06-4e8b-9fd2-70f36176c7de.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)
* Content Source: [powerbi-docs/admin/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bernatagulloesbrina. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, and apologies that such differences exist in the product/features.

Note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
