### ISSUE TITLE
Example requires additional information

### ISSUE THREAD

**Issue by novasilva-wouter** [MicrosoftDocs/powerbi-docs#4280]
[Enter feedback here]

The references "this.show" and "this.displayNameProperty" are not shown on this page.

This way it is unclear how the topLevelToggle is meant to be used.

Please complete / clarify the example when not using formatting utils.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21268b6d-592b-8a5e-e332-2ce014c2d36a
* Version Independent ID: eb9c880d-35fe-f931-2485-1aa3d1958845
* Content: [The Analytics pane in Power BI visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/analytics-pane?tabs=API-5-1)
* Content Source: [powerbi-docs/developer/visuals/analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/analytics-pane.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @novasilva-wouter. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @novasilva-wouter. I'll pass it on and get back to you soon.

**Comment by mberdugo** [comment]
Hi, @novasilva-wouter. Sorry for the delayed response. You're right, there was some missing code there.
Try this:

        const show: powerbi.visuals.EnabledSlice = {
            uid: "enableAxisCard_topLevelToggle_show_uid",
            suppressDisplayName: true,
            control: {
                type: powerbi.visuals.FormattingComponent.ToggleSwitch,
                properties: {
                    descriptor: {
                        objectName: "YourAnalyticsPropertiesCard",
                        propertyName: "show"
                    },
                    value: false
                }
            }
        }
        
        const displayNameProperty: powerbi.visuals.FormattingSlice = {
            uid: "enableAxisCard_displayName_uid",
            suppressDisplayName: true,
            control: {
                type: powerbi.visuals.FormattingComponent.TextInput,
                properties: {
                    descriptor: {
                        objectName: "YourAnalyticsPropertiesCard",
                        propertyName: "displayName"
                    },
                    value: "Analytics Instance",
                    placeholder: ""
                }
            }
        }

        const averageLineCard: powerbi.visuals.FormattingCard = {
            displayName: "Your analytics properties card's name",
            uid: "yourAnalyticsCard_uid",
            analyticsPane: true, // <===  Add and set analyticsPane variable to true 
            topLevelToggle: show,
            groups: [{
                displayName: undefined,
                uid: "yourAnalyticsCard_group_uid",
                slices: [displayNameProperty],
            }]
        };


I'll update the doc. Thanks for pointing this out.
