### ISSUE TITLE
What does ** means in documentation

### ISSUE THREAD

**Issue by iqb-dawn** [MicrosoftDocs/powerbi-docs#4283]
I was reading this document https://learn.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi where I saw ** at 3 places but could not found ** description anywhere in the document.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @iqb-dawn. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @iqb-dawn,

This is a typo - thank you for letting us know!

I removed the typo, and you should be able to see this shortly.

Thanks,

Kesem
