### ISSUE TITLE
Outdated Premium Gen1 instructions

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#4285]
For the below paragraph, Premium Gen1 capacities have (largely) been all moved to Gen2 - should this disclaimer still be present?

In a Premium Gen1 capacity, a Power BI admin needs to enable paginated reports in the [Premium capacities section](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#paginated-reports) of the Power BI admin portal. In a [Premium Gen2 capacity](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is#paginated-reports), paginated reports are enabled automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a720989e-e6c4-2377-e0c0-8c80d5691f46
* Version Independent ID: 3c6392e8-0f91-1c9c-2c21-15291d46bfd0
* Content: [What are paginated reports in Power BI? - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @rvpatkar 
@cookiemccray 
@nirusrin 
Can one of you comment on Alex Powers's (@itsnotaboutthecell) comment?
Thanks!

**Comment by rvpatkar** [comment]
It's a fair point, not much value in calling out Gen1 as that's mostly all moved to Gen2. @mgmeyer

**Comment by maggiesMSFT** [comment]
Thanks, @rvpatkar. adding @mgmeyer. 
 
So in the context of the section:

**Prerequisites**

- You don't need any license to [download Power BI Report Builder](https://go.microsoft.com/fwlink/?linkid=2086513) from the Microsoft Download Center for free.
- You can publish and share paginated reports in your My Workspace or in other workspaces, as long as you have write access to the workspace.
- In a Premium Gen1 capacity, a Power BI admin needs to enable paginated reports in the [Premium capacities section](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#paginated-reports) of the Power BI admin portal. In a [Premium Gen2 capacity](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-gen2-what-is#paginated-reports), paginated reports are enabled automatically.

just delete the last bullet? Or leave:

- Paginated reports are enabled automatically.

Or?

**Comment by rvpatkar** [comment]
Please delete the last bullet. Regarding pre-req, how about using the INCLUDE you have created elsewhere? On topic of Gen1, can you also please update https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq#what-size-premium-capacity-do-i-need-for-paginated-reports- answering there by pointing to https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-capacity-planning

**Comment by maggiesMSFT** [comment]
Hi, @rvpatkar -- Yes, I'll use the INCLUDE. This is one of the articles in the other PR:
https://review.learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-report-builder-power-bi?branch=pr-en-us-9394#prerequisites

I haven't published that PR yet because so far only you have signed off. Also, I asked if you could review a few outliers, which have more than just the basic prereqs. I listed them in the PR here:
https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/9394/#issuecomment-1379658875

thanks!

**Comment by maggiesMSFT** [comment]
Hi, @itsnotaboutthecell -- Prerequisites section redone.

**Prerequisites** 

License requirements for Power BI paginated reports (.rdl files) are the same as for Power BI reports (.pbix files).

- You don't need a license to [download Power BI Report Builder](https://go.microsoft.com/fwlink/?linkid=2086513) from the Microsoft Download Center for free.
- With a free license, you can publish paginated reports to My Workspace in the Power BI service. For more information, see [Feature availability for users with free licenses in the Power BI service](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-features#licenses).
- With a Power BI Pro license or a PPU license, you can publish paginated reports to other workspaces. You also need at least a [contributor role](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces#workspace-roles) in the workspace.

cheers!
