### ISSUE TITLE
Resume/Suspend Power BI Embedded Capacity with REST API

### ISSUE THREAD

**Issue by Lueton** [MicrosoftDocs/powerbi-docs#4288]
Hey! Im really new to Power BI and Im currently trying to [resume](https://learn.microsoft.com/en-us/rest/api/power-bi-embedded/capacities/resume?tabs=HTTP) or [suspend](https://learn.microsoft.com/en-us/rest/api/power-bi-embedded/capacities/suspend?tabs=HTTP) my Power BI Embedded capacity. But Im completely stuck and out of ideas. Ill explain what i did so far.  
  
First I fetch the required token: 
```
POST https://login.microsoftonline.com/{tenantIdOfCapacity}/oauth2/token  
{  
   grant_type: 'client_credentials',  
   client_id: '{clientIdOfAppRegistration}',  
   client_secret: '{secret}',  
   resource: 'https://management.azure.com/.default'  
}
```
This works so far.  But im not sure if the request resource is correct.
  
After that i try to make the actual API request to suspend my capacity.
```
POST https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.PowerBIDedicated/capacities/{dedicatedCapacityName}/suspend?api-version=2021-01-01  
with Authorization Bearer token
```
This always returns the following response (note: client and object id are identical):
```
{
    "error": {
        "code": "AuthorizationFailed",
        "message": "The client 'XXX' with object id 'XXX' does not have authorization to perform action 'Microsoft.PowerBIDedicated/capacities/suspend/read' over scope '/subscriptions/YYY/resourceGroups/ZZZ/providers/Microsoft.PowerBIDedicated/capacities/AAA' or the scope is invalid. If access was recently granted, please refresh your credentials."
    }
}
```
And thats where im stuck. I tried to configure everything, grant all permission i could think of and so on, but to be honest its a bit overwhelming and confusing. So it would be helpful to know all things that need to be configured in order to get this working.  Maybe i missed one of them.
  
Thanks for any advice!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Lueton. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Lueton. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
