### ISSUE TITLE
Obsolete indication

### ISSUE THREAD

**Issue by machi67** [MicrosoftDocs/powerbi-docs#4289]
The phrase "To add a button, on the Home ribbon, select Buttons > Q&A. You can completely customize the Q&A button image." is incorrect. "Buttons" now is in the Insert ribbon. Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0583247e-c2df-3917-c197-81e40334dc46
* Version Independent ID: 9b04755b-12ea-fb0d-6633-41d04fdeb261
* Content: [Use natural language to explore data with Power BI Q&A - Power BI](https://learn.microsoft.com/en-us/power-bi/natural-language/q-and-a-intro)
* Content Source: [powerbi-docs/natural-language/q-and-a-intro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/natural-language/q-and-a-intro.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @mohaali
* Microsoft Alias: **mohaali**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @machi67. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @machi67,

Thanks for getting involved and letting us know about this error. The mistake is now fixed.

Kesem
