### ISSUE TITLE
What is generating an entire for ViewReport

### ISSUE THREAD

**Issue by devaccount89** [MicrosoftDocs/powerbi-docs#429]
Hi MS-Team, 
is there any documentation when a "ViewReport" entry is created. 
So if a user opens the report in the Service then one entry is created. Will there be an additional one created if the user navigates to the next Page? 

Thanks.

Moritz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Using auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#activities-audited-by-power-bi)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @devaccount89. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by KayUnkroth** [comment]
Auditing is more about tracking who accessed/viewed a report, rather than tracking individually what particular tab the user was navigating to or which filters the user was applying.

**Comment by mgblythe** [comment]
@devaccount89 - closing this based on Kay's response.
