### ISSUE TITLE
Error in description

### ISSUE THREAD

**Issue by jsoneill17** [MicrosoftDocs/powerbi-docs#4290]
In the "Create formulas for you custom column" section there is a description on the second screenshot in step 2 that says "If there's a syntax error, there is a green checkmark, along with a link to where the error occurred in your formula." which is incorrect. It should probably say "If there's a syntax error, there is a warning, along with...".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02e8e549-7fba-9ece-3e32-73a0cc3c6046
* Version Independent ID: a9b39810-c302-c153-3123-ddb8f459e9f4
* Content: [Add a custom column in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-add-custom-column)
* Content Source: [powerbi-docs/create-reports/desktop-add-custom-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-add-custom-column.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jsoneill17. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the close read, you're right! We've updated that article.
