### ISSUE TITLE
Missing information for Paginated Report that uses a Power BI dataset

### ISSUE THREAD

**Issue by TomHuguelet** [MicrosoftDocs/powerbi-docs#4294]
[Enter feedback here]
This page describes needing a multi-resource access token to embed a Paginated Report that uses a Power BI dataset as a data source. It then refers the reader to the [embed content for your customers tutorial](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers). However, none of the [referenced sample applications](https://github.com/microsoft/PowerBI-Developer-Samples) on that page can handle appropriately the multi-resource access token, so the instructions on this page and the [embed content for your customers](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers) tutorial page are either incomplete or wrong. 

One of two things need to happen for this page to be correct and useful: 

1. Include instructions for modifying the sample application(s) so that a Paginated Report that uses a Power BI dataset can be used successfully -- or -- 
2. Update the sample applications so that they work as described on these pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d53eef67-91ce-691f-5e29-515d553023f6
* Version Independent ID: f6723c69-a08d-42af-6a74-33f22bc55fba
* Content: [Embed paginated reports in your Power BI embedded analytics application - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-paginated-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TomHuguelet. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @TomHuguelet.
Have you read all the [limitations regarding capacities and permissions](https://learn.microsoft.com/power-bi/developer/embedded/embed-paginated-reports?tabs=customers#considerations-and-limitations)?
And have you looked at these [examples](https://learn.microsoft.com/rest/api/power-bi/embed-token/generate-token#examples) for generating tokens for paginated reports?
If so, and you're still having trouble, please describe the problem you're having with the sample app, and I'll try to find out for you.

**Comment by TomHuguelet** [comment]
Good morning, @mberdugo .
<< read all the limitations >> Yes  
- I'm running a service principal
- I have an A-SKU for embedded capacity
- I'm using postman to acquire an embed token. I'm focused on the [2nd example](https://learn.microsoft.com/en-us/rest/api/power-bi/embed-token/generate-token#example-of-generating-an-embed-token-for-a-paginated-report-which-has-a-power-bi-dataset-as-a-datasource.-the-id-of-the-dataset-must-be-specified-in-the-request.-the-report-and-dataset-can-each-have-its-own-identity) as a test case, but I am not using identities.
-  I can run the sample apps (.Net Core and .Net Framework are the two I've tested) and using those sample apps I can embed a standard PBIX with no issues. However, if I switch the ReportID from the standard PBIX to the ReportID of the RDL, the app fails

I believe the issue is with the call on line 58 of PbiEmbedService.cs and the definition on line 251 (this is from the solution "Embed for your customers" .Net Core. For the token to work, it must include the datasetID. However, neither the call nor invocation of the API includes the datasetID, so the token will never work for an RDL that uses a PowerBI Dateset.

**Comment by mberdugo** [comment]
Thanks for the details. I'll look into this and let you know. Then I'll update the docs accordingly.

**Comment by mberdugo** [comment]
Hi @TomHuguelet,

Try using the code shown here marked **New**

![image](https://user-images.githubusercontent.com/82447518/214036056-efe71657-d6bd-45d5-82aa-3dafcb5dd2ad.png)

Please let me know if it works for you so we can update it.
Thanks.

**Comment by TomHuguelet** [comment]
I get a CS1729 compiler error if I structure my code that way with the GUID's substituted for my environment. 
![image](https://user-images.githubusercontent.com/121529617/214207258-1a197777-ebaa-431b-bf4e-b1d2953b05d4.png)

**Comment by mberdugo** [comment]
The compiler suggests that there’s an issue with the parameters types sent to the constructor of GenerateTokenRequestV2Dataset.
Indeed, the second parameter shouldn’t be a string, it’s an enum of type XmlaPermissions, the value should be XmlaPermissions.ReadOnly
Good luck debugging the code.

**Comment by TomHuguelet** [comment]
Even after correcting my code, I still receive the CS1729 error. I can only find the [single-constructor version documented.](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.models.generatetokenrequestv2dataset.-ctor?view=azure-dotnet#microsoft-powerbi-api-models-generatetokenrequestv2dataset-ctor) I don't doubt that your code is working, but the reason must be that your version is using a different library or API version.

**Comment by TomHuguelet** [comment]
OK, I got it working. Two things required:

1. Update Microsoft.PowerBI.Api 3.21.0 to latest version (today, that's 4.11.0)
2. Comment out the previous "Generate token request" code, from lines 255 - 261. This probably means this version wouldn't work for RDL reports that don't use a Power BI dataset. 

This is what it looks like:
![image](https://user-images.githubusercontent.com/121529617/214668626-2cc64957-b44f-4949-a1ee-7bd6833c9c92.png)

**Comment by mberdugo** [comment]
I'm so glad you got it working!
Thanks for the comments. I'll update the docs accordingly.
