### ISSUE TITLE
Dataflow takeover if owner is missing

### ISSUE THREAD

**Issue by hokeson** [MicrosoftDocs/powerbi-docs#4295]
there is a tsg [TSG:: Unable to take over a dataflow when current owner was deleted - Overview (visualstudio.com)](https://supportability.visualstudio.com/Power%20BI/_wiki/wikis/PBICSSWIKI/594380/TSG-Unable-to-take-over-a-dataflow-when-current-owner-was-deleted) which is not public.  it help users to take over a dataflow it the owner is lost

it looks like this 
![image](https://user-images.githubusercontent.com/6493057/213251977-32e412f0-a260-4573-a77b-2ed5ab49021d.png)
more options cant be accessed, dataflow cant be taken over from GUI.

as the TSG is advising to use postman it cant be spread publicly.
there for I propose to add here a chapter which gives the user option to takeover dataflow by some powershell command or an API call as one of other Dataflow API calls here https://learn.microsoft.com/en-us/rest/api/power-bi/dataflows. it can be called Dataflow takeover. only workspace admin would be able to use it. for other it will fail.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3ec2a31-ae63-38f7-00e8-234bcedd571d
* Version Independent ID: ff4d4e25-80f5-cac3-49c8-a85b7cf1c476
* Content: [Dataflows Limitations, restrictions and supported connectors and features - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-features-limitations)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-features-limitations.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hokeson. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look into including that in the article.
