### ISSUE TITLE
Dependency to pandas and matplotlib not mentioned on "Use Python in Power Query Editor" page

### ISSUE THREAD

**Issue by hski-github** [MicrosoftDocs/powerbi-docs#4296]
On the page "[Use Python in Power Query Editor](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-in-query-editor) it says that pandas is required at point 6. after the Python example script and it sounds like it is because of the example itself, because pandas is used in the Python script

But even with an empty Python script you still get an error message that the Python wrapper requires import os, pandas, matplotlib. See screenshot.

This dependency on pandas and matplotlib should be mentioned right at the beginning ideally in the section [Install Python](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-in-query-editor#install-python) as this is general requirement to work with Python in Power BI. 

![image](https://user-images.githubusercontent.com/1921015/213382426-577705a6-3a71-463b-86b6-a79f9a4f268e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdd46971-2ea5-9271-3b2a-824efc1821e1
* Version Independent ID: 68669cdb-5e4d-bb96-d2d5-bdad4088fb03
* Content: [Use Python in Power BI Power Query Editor - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-python-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-python-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hski-github. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @hski-github,

Thank you for your comment. I'm looking into this issue and will get back to you once I have an answer.

Kesem

**Comment by KesemSharabi** [comment]
Hi @hski-github,

Thanks you for your suggestion. I amended [Use Python in Power Query Editor](https://learn.microsoft.com/power-bi/connect-data/desktop-python-in-query-editor) so that pandas is mentioned as a prerequisite.

The change will be visible shortly.

Thanks again,

Kesem
