### ISSUE TITLE
URGENT! The screenshot of the tenant settings to disable Query Scale Out for the tenant shows a Project Trident Setting! Please replace with a screenshot without Trident.

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#4297]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Version Independent ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Content: [Power BI Dataset Scale-Out - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out)
* Content Source: [powerbi-docs/enterprise/service-premium-scale-out.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-scale-out.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
@gmuenster - thanks for catching this! I fixed this in [PR 9487](https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/9487).
