### ISSUE TITLE
On-demand refreshes don't affect the next scheduled refresh time, but they do count against the daily refresh limit.

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4298]
This appears to conflict with the information on this page:

https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data#data-refresh
_On-demand refreshes aren't included in the refresh limitation._

That page was corrected to say that on demand refreshes are not included.
https://github.com/MicrosoftDocs/powerbi-docs/issues/1604

 I believe that this page also needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sql-tutorial)
* Content Source: [powerbi-docs/connect-data/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @djurecic0,

Thank you for your feedback and for getting involved.

I removed 'but they do count against the daily refresh limit' from the sentence and it'll be published shortly.

Thanks,

Kesem
