### ISSUE TITLE
Power BI limits datasets on shared capacity to eight daily dataset refreshes

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4299]
The limit is 8 **scheduled** refreshes daily. Manual refreshes are not included per 
https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data#configure-scheduled-refresh
_On-demand refreshes aren't included in the refresh limitation._

Can you please change the text 
"Power BI limits datasets on shared capacity to eight daily dataset refreshes"
to 
"Power BI limits datasets on shared capacity to eight **scheduled** daily dataset refreshes"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data#data-refresh)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
That's a great clarification -- I've added that, thanks!
