### ISSUE TITLE
Report sharing documentation is wrong

### ISSUE THREAD

**Issue by Kirtc** [MicrosoftDocs/powerbi-docs#4301]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Kirtc. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Kirtc, we've opened a work item to improve this article. Thanks for your feedback! Closing this issue here now.
