### ISSUE TITLE
Report sharing documentation is wrong

### ISSUE THREAD

**Issue by Kirtc** [MicrosoftDocs/powerbi-docs#4302]
The documentation says that you can affect the abilities of those receiving the share access by either checking or unchecking the box granting them the ability to reshare the report.  This is not true.  I have tested this numerous times with multiple reports both with the box checked and unchecked.  In all cases, the person receiving the email granting report access is allowed to reshare it.  Power BI does not honor the directions denying reshare rights.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Kirtc. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Kirtc,

Can you please let us know which document you're referring to?

Thanks,

Kesem

**Comment by Kirtc** [comment]
Sorry,

I expected that it would include this information when I submitted feedback.  The document is https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards

Specifically where it discusses sharing reports and checking or unchecking the "Allow recipients to share this report".  This document states that if this box is unchecked, then the recipient will not be able to reshare.  This is not true.  I have performed numerous tests with an individual who does not have access to our reports.  In all cases, whether the box is checked or unchecked, he is still able to reshare the report I share to him.

From: Kesem Sharabi ***@***.***>
Sent: Sunday, January 22, 2023 11:45 PM
To: MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Clem, Kirtley S ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [MicrosoftDocs/powerbi-docs] Report sharing documentation is wrong (Issue #4302)


Hi @Kirtc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKirtc&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8087667cc8414205eefd08dafd15bab7%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100567025048147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ItX7jK8uSYZF86yltuwx4vxznyz9EZSw438jUMHUWEc%3D&reserved=0>,

Can you please let us know which document you're referring to?

Thanks,

Kesem

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fissues%2F4302%23issuecomment-1399924179&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8087667cc8414205eefd08dafd15bab7%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100567025048147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wxh04str01Eels%2B%2FaUx4tkoRzJvxlMbMaao2meUS0hM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5LKOOX6ISVRWQ3ACINM6I3WTYZHVANCNFSM6AAAAAAUAYPVJE&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8087667cc8414205eefd08dafd15bab7%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100567025204372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6snxj43rFi8%2FkhRXm5sjqP5JiCzyDC7nY%2FjtBCG%2B0oY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
This message originated from an external sender. Use caution when clicking on links or opening attachments.

**Comment by Kirtc** [comment]
***@***.***

From: Clem, Kirtley S ***@***.***>
Sent: Monday, January 23, 2023 7:23 AM
To: MicrosoftDocs/powerbi-docs ***@***.***>; MicrosoftDocs/powerbi-docs ***@***.***>
Cc: Mention ***@***.***>; Clem, Kirtley S ***@***.***>
Subject: RE: [EXTERNAL]Re: [MicrosoftDocs/powerbi-docs] Report sharing documentation is wrong (Issue #4302)

Sorry,

I expected that it would include this information when I submitted feedback.  The document is https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpower-bi%2Fcollaborate-share%2Fservice-share-dashboards&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8f0fb78fb5ae4adf8abe08dafd55aa3c%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100841618684883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CH0lHjDZ4pcIL2BF3%2ByMSShetCmwi90wUL%2Bfd4ySqAk%3D&reserved=0>

Specifically where it discusses sharing reports and checking or unchecking the "Allow recipients to share this report".  This document states that if this box is unchecked, then the recipient will not be able to reshare.  This is not true.  I have performed numerous tests with an individual who does not have access to our reports.  In all cases, whether the box is checked or unchecked, he is still able to reshare the report I share to him.

From: Kesem Sharabi ***@***.******@***.***>>
Sent: Sunday, January 22, 2023 11:45 PM
To: MicrosoftDocs/powerbi-docs ***@***.******@***.***>>
Cc: Clem, Kirtley S ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Subject: [EXTERNAL]Re: [MicrosoftDocs/powerbi-docs] Report sharing documentation is wrong (Issue #4302)


Hi @Kirtc<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKirtc&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8f0fb78fb5ae4adf8abe08dafd55aa3c%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100841618684883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ixkJbimz99WQQbkcXO5ahd%2FgXY%2F%2FZhkN7QC3Wa63tIg%3D&reserved=0>,

Can you please let us know which document you're referring to?

Thanks,

Kesem

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fpowerbi-docs%2Fissues%2F4302%23issuecomment-1399924179&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8f0fb78fb5ae4adf8abe08dafd55aa3c%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100841618684883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xnH4t9Y%2Fj3oHUVmQtA1nWCgViKsi9tcsCBJNhql%2F3ZE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5LKOOX6ISVRWQ3ACINM6I3WTYZHVANCNFSM6AAAAAAUAYPVJE&data=05%7C01%7Ckirtley_s_clem%40rl.gov%7C8f0fb78fb5ae4adf8abe08dafd55aa3c%7C61e35c42ffa04f89bb152b8c13320625%7C0%7C0%7C638100841618684883%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dnKaedrPliNul%2BbqSmiXOx6sjdrkfLCtCQwmeZbTjxk%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
This message originated from an external sender. Use caution when clicking on links or opening attachments.

**Comment by KesemSharabi** [comment]
Hi @Kirtc,

Thank you for pointing out which document you're having problems with. We'll look into it and get back to you.

Kesem

**Comment by paulinbar** [comment]
Hi @Kirtc, I have run this scenario several times and found that a user who has had a report shared with them via a share where the "Allow recipients to share this report" box is unchecked cannot give view access to someone who doesn't already have access. You can share the item, or a link to the item, but if that person doesn't already have access, and they try to open the report, they will be blocked, and given the opportunity to request access. 

So I think the word reshare is perhaps misleading. What is really meant is reshare with view permissions.  Now, I think you are claiming that the person at the end of the chain could access the report. This is what didn't happen for me. Are you sure the person didn't have view access through some other path, such as a link that said everyone in the org can access the item? Did you check the info in all the tabs on the Manage permissions page? 

I am going to close this issue now, but please feel free to reopen it if you feel that the behavior is not as described. Thanks!
