### ISSUE TITLE
Dataflow take over with Gateway 

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4305]
hi,

I would like to amend this text:

Take ownership: If you're not the owner of the dataflow, many of these settings are disabled. To take ownership of the dataflow, select Take over to take control. You are prompted to provide credentials to ensure you have the necessary access level.

Gateway Connection: In this section, you can choose whether the dataflow uses a gateway, and select which gateway is used.

to:
Take ownership: If you're not the owner of the dataflow, many of these settings are disabled. To take ownership of the dataflow, select Take over to take control. You are prompted to provide credentials to ensure you have the necessary access level.

Gateway Connection: In this section, you can choose whether the dataflow uses a gateway, and select which gateway is used.
In case you have specified the Gateway as part of editing dataflow, upon taking ownership you may need to update credentials via the edit dataflow option. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure and consume a dataflow - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-configure-consume)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-configure-consume.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Looks like a good addition, I've added that to the article. Thanks!
