### ISSUE TITLE
"Power BI visuals do not support page tooltips."

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4306]
This statement is an error since some visuals do support page tooltips, but not all of them do.

Please see:
https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop#manually-setting-a-report-tooltip

Maybe it is supposed to read "Some Power BI visuals do not support page tooltips"?
or "Custom Power BI visuals do not support page tooltips"
https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop#considerations-and-limitations
"Report tooltips are not supported for Power BI custom visuals."

---
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db84fc62-b85a-1bef-987c-36345b762928
* Version Independent ID: a8c23738-1f6f-f99a-0cff-9553dca83d96
* Content: [Extend visuals with report page tooltips - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/report-page-tooltips)
* Content Source: [powerbi-docs/guidance/report-page-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/report-page-tooltips.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Thanks for the feedback @djurecic0! I agree that there is confusion between visual tooltips and report page tooltips in the referenced article and what is supported for custom visuals. I am asking another writer to review the best practices in https://learn.microsoft.com/en-us/power-bi/guidance/report-page-tooltips and ensure that the guidance is accurate.

**Comment by davidiseminger** [comment]
Thanks for submitting -- that's just an outdated note that I've corrected. Thanks!
