### ISSUE TITLE
Question about "When users are deleted from the company's Active Directory..."

### ISSUE THREAD

**Issue by philosophicles** [MicrosoftDocs/powerbi-docs#4308]
https://learn.microsoft.com/en-gb/power-bi/admin/service-admin-portal-workspaces#prevent-my-workspace-owners-from-reassigning-their-my-workspaces-to-a-different-capacity:~:text=When%20users%20leave%20the%20company%2C%20their%20My%20workspaces%20show%20up%20as%20Deleted%20in%20the%20State%20column%20on%20the%20Workspaces%20page%20in%20the%20Admin%20portal

> When users leave the company, their My workspaces show up as Deleted in the State column on the Workspaces page in the Admin portal.

This appears not to happen universally, or quite as worded. In my organisation, users who leave the company are disabled in Active Directory, but not deleted. I think (but I am just guessing) that this does not prompt any change to the status of their 'My workspace'. 

Certainly, I observe that there are many former staff members who _have_ left the company, but whose My workspaces are still in State 'Active'.

My guess is that this status change only occurs if/when the Active Directory user is fully deleted. I do not think it is uncommon for organisations to merely disable, not delete, their former employees.

**QUESTION/REQUEST:** please could somebody closer to the actual behaviour confirm if my guess is correct, and if so, update the documentation to clarify this? 

E.g. changing the first part of that sentence to:

> When users are deleted from the company's Active Directory, their My workspaces show up as Deleted...

...would suffice.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43e3835f-01d6-6e0e-7b46-cece481d7166
* Version Independent ID: 43e3835f-01d6-6e0e-7b46-cece481d7166
* Content: [View workspaces - Power BI](https://learn.microsoft.com/en-gb/power-bi/admin/service-admin-portal-workspaces#prevent-my-workspace-owners-from-reassigning-their-my-workspaces-to-a-different-capacity)
* Content Source: [powerbi-docs/admin/service-admin-portal-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-workspaces.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @philosophicles. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @philosophicles, thanks for the feedback! Let me run your comment by the content experts and I'll update the docs accordingly.

**Comment by paulinbar** [comment]
Hi @philosophicles, sorry for the delay in getting back to you. I communicated with the product team and indeed, the behavior is as you describe, and I will update the documentation with your suggestion. Thanks for the input!
