### ISSUE TITLE
Oracle now provides a "Oracle Client for Microsoft Tools" installer

### ISSUE THREAD

**Issue by lesliemui** [MicrosoftDocs/powerbi-docs#4309]
Oracle now provides a MSFT tools installer:
https://www.oracle.com/database/technologies/net-downloads.html#

This installer allows us to deprecate the manual steps here:
https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-oracle-database#64-bit-power-bi-desktop

Users should first be directed to the MSFT tools version of the installer as this performs the registration automatically.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lesliemui. This issue has been assigned to the doc author for review.

**Comment by fedemartino** [comment]
@davidiseminger this is the same issue I mentioned in my PR https://github.com/MicrosoftDocs/powerbi-docs/pull/4395 I should have checked the issue list before requesting the merge

**Comment by davidiseminger** [comment]
Thank you for your feedback - and as I mentioned, after discussing internally it was determined that this might work, in many cases, but there are other cases (outside of what you have experience) where their configuration isn't specifically supported by Microsoft.
