### ISSUE TITLE
Update PerformanceAnalytics

### ISSUE THREAD

**Issue by sergiped** [MicrosoftDocs/powerbi-docs#431]
Can you please update the version of PerformanceAnalytics included in the service?  The latest version is 1.5.2 and the new functions are not currently available in the version you utilize.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported for using and creating R scripts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#r-scripts-that-are-not-supported-in-power-bi)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @sergiped 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.
If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
Kind regards,
Microsoft DOCS International Team
