### ISSUE TITLE
"A heavy usage experience can occur when a report receives too many queries in a short amount of time."

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4313]
Can you provide more detailed information on how many queries is "too many"? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @djurecic0, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for your suggestion!
