### ISSUE TITLE
Link destination missing

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#4317]
Dear all,

the destination to the link at the bottom to Purview Lockbox Requests has a dead end.
https://learn.microsoft.com/en-us/compliance/customer-lockbox-requests

Thanks,
Gabi

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6bb2c94a-cea9-5279-e057-9d533053501c
* Version Independent ID: 6bb2c94a-cea9-5279-e057-9d533053501c
* Content: [Lockbox for Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-power-bi-security-lockbox)
* Content Source: [powerbi-docs/enterprise/service-admin-power-bi-security-lockbox.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-power-bi-security-lockbox.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmuenster. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @gmuenster,

Thank you for pointing this out. The link will be fixed shortly.

Kesem
