### ISSUE TITLE
SQL Server Profiler is deprecated

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4320]
It's confusing that the current DirectQuery guidance points to SQL Server Profiler, a tool deprecated since SQL Server 2016. It's also confusing that Extended Events which are supposed to replace Server Profiler are not supported in Power BI Premium!

- https://learn.microsoft.com/en-us/sql/tools/sql-server-profiler/sql-server-profiler?view=sql-server-ver16
- https://learn.microsoft.com/en-us/analysis-services/instances/monitor-analysis-services-with-sql-server-extended-events?view=asallproducts-allversions
- 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3422402-b1e9-db0c-cbb6-4dd3eaa528c4
* Version Independent ID: 124204c3-bbcb-f705-c88f-90c81be27a2f
* Content: [DirectQuery model troubleshooting in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-troubleshoot)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-troubleshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-troubleshoot.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments, we'll look at updating those links and those tool references.
