### ISSUE TITLE
Add private endpoints to the unsupported features?

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4322]
HI

pls add to the below section
Enabling private end points blocks delivery of the subscription emails - see [https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links#considerations-and-limitations](url) . Users are not notified and Run Now action appears as a successfully sent subscription.

Section to add it to: 
**Unsupported features**
Email subscriptions don't support:

R-powered Power BI visuals
most [custom visuals](https://learn.microsoft.com/en-us/power-bi/developer/visuals/develop-power-bi-visuals). The exception is those Power BI custom visuals that have been [certified](https://learn.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified).
Dataset refresh operations using an XMLA endpoint.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for reports and dashboards in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/end-user-subscribe?tabs=creator#considerations-and-limitations)
* Content Source: [powerbi-docs/collaborate-share/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @MartinaPoddana , 
Thank you for your suggestion.  We've added this to the Troubleshooting subscriptions article.  Since it's not technically an "unsupported feature," but a tenant setting that can be turned on/off, we believe that article is a better location.
