### ISSUE TITLE
Add private endpoint as a reason to stop receiving subscribed emails

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4323]
Hi 
please add to [https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-troubleshoot-subscribe#email-issues](url)

Please check with your tenant admin for Private end points setting - if it is enabled it blocks delivery of subscribed emails - see [https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links#considerations-and-limitations](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d883f7b-4e04-d4af-7a03-652316f9f7b7
* Version Independent ID: 9d883f7b-4e04-d4af-7a03-652316f9f7b7
* Content: [FAQs about Troubleshoot subscribing to dashboards and reports - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-troubleshoot-subscribe)
* Content Source: [powerbi-docs/collaborate-share/service-troubleshoot-subscribe.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-troubleshoot-subscribe.yml)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @MartinaPoddana ,
Thank you for your suggestion.  We've updated the article with a better description of this issue.  We appreciate your contribution!
