### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by Sanjay-Manandhar** [MicrosoftDocs/powerbi-docs#4326]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd16a9c-3620-e1c6-518a-d6a5f9174089
* Version Independent ID: c55ccf5a-5563-1a05-7cec-46666a9e8f08
* Content: [Introduction to dataflows and self-service data prep - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-introduction-self-service)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-introduction-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-introduction-self-service.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sanjay-Manandhar. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hi there -- appreciate your willingness to provide feedback, but we need information on how to act. Feel free to open a new issue with more specifics for us to respond to.
