### ISSUE TITLE
developer visual not working in multiple environments including learning lab.

### ISSUE THREAD

**Issue by Wedfrisat** [MicrosoftDocs/powerbi-docs#4327]
[Enter feedback here]

I tried to follow these instructions in several settings including LabOnDemand.com but steps 4 & 5 always displays an error message:
"Uncertified visuals fromappsource or added from a file, are not available due to your admin  settings, unless the visual was added to the 'My Organization' page."
I have no idea how to get this development framework working with this message.
![image](https://user-images.githubusercontent.com/78030442/216153677-6dd0cda7-559e-462d-aa76-46659aa85c41.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd119235-31a3-4c74-9aed-848d2438c0ef
* Version Independent ID: 87eb1e86-6977-00df-a032-8f1c2ccb48ef
* Content: [Learn how to develop your own Power BI visual using the circle card visual as an example - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/develop-circle-card)
* Content Source: [powerbi-docs/developer/visuals/develop-circle-card.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/develop-circle-card.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Wedfrisat. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @Wedfrisat. 
If looks like the developer setting might be disabled.
Go into settings and see if you can enable it: 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/82447518/216254501-7fe58f2c-4b4d-400a-9592-0c6fef9ff9f5.png">

Good luck.
Mona

**Comment by Wedfrisat** [comment]
I did actually set that.  It had remained set when I checked it just now.    I should mention that I am on app.powerbigov.us .

![image](https://user-images.githubusercontent.com/78030442/216315749-d2e8ef3a-9a8f-4b3a-8b5a-1fa6fc92ef9b.png)

**Comment by mberdugo** [comment]
Hi @Wedfrisat,
Try enabling non-certified visuals.

**Comment by mberdugo** [comment]
@Wedfrisat, can you have your admin enable non-certified visuals?

**Comment by Wedfrisat** [comment]
It has started to work for me.   I was able to complete the lesson.


Thanx

**Comment by mberdugo** [comment]
Great! Glad you figured it out.
