### ISSUE TITLE
The script didn't change the connections string in power bi desktop

### ISSUE THREAD

**Issue by ons24** [MicrosoftDocs/powerbi-docs#4329]
[but this will not change the dbname and servername in power bi desktop, the connection string was changed in power BI report server but when I click on Edit in power BI desktop i see the data base name and server name didn't change ]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99521173-b241-25e5-ea78-de782dc25edc
* Version Independent ID: 98a21d67-6880-73cd-571b-cfcf4aeac4f2
* Content: [Change data source connection strings with PowerShell - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis)
* Content Source: [powerbi-docs/report-server/connect-data-source-apis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/connect-data-source-apis.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ons24. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @ons24, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback. We'll look into it!
