### ISSUE TITLE
Other clients are now supported

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4332]
This section should be updated:

"Datamarts currently support the following SQL clients:

- SSMS
- Azure Data Studio"

This is no longer accurate, other clients are now supported:
https://powerbi.microsoft.com/en-us/blog/power-bi-datamart-january-2023-feature-summary/

I can vouch for this as I've personally tested DBeaver and the ODBC SQL driver v18.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 589a83ac-1fda-b3f1-1590-9372d97cf132
* Version Independent ID: 589a83ac-1fda-b3f1-1590-9372d97cf132
* Content: [Administration of datamarts (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-administration)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-administration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-administration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Great! Thanks for the heads up, we've updated that article.
