### ISSUE TITLE
Private Link limitations should make mention of Paginated Reports

### ISSUE THREAD

**Issue by ZacharyMcGuire** [MicrosoftDocs/powerbi-docs#4333]
I believe the limitations section should be updated to include Paginated Reports.
Paginated Reports doesn't work with Private Link enabled, nor do any of the options that use the Paginated tech like "_View as Formatted Table_" on datasets.

Some feedback for the Web UI in the service would also be to disable these options to the end-users, as it's quite a bad user experience to be presented options that will simply never work given how the tenant is configured and leads to support requests for errors returned by the PBI Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for accessing Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ZacharyMcGuire. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We'll update the limitations section to reflect paginated reports. Thanks!
