### ISSUE TITLE
Excel PivotTable connected experience - supports implicit measures now

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4334]
It would be good to update the documentation now that there is support for implicit measures in Analyze in Excel with Power BI and that the measures no longer need to be predefined https://insider.office.com/en-us/blog/improvements-to-the-connected-power-bi-experience

This is definitely not widely known and perhaps it could be posted on Excel and/or Power BI blog as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 239b3819-f483-97d3-2c1c-e5747a2dcc3a
* Version Independent ID: 239b3819-f483-97d3-2c1c-e5747a2dcc3a
* Content: [Connect Excel to Power BI datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-power-bi-datasets-excel)
* Content Source: [powerbi-docs/collaborate-share/service-connect-power-bi-datasets-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-power-bi-datasets-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @denglishbi. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @denglishbi, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for pointing this out to us!
