### ISSUE TITLE
Update the screenshot

### ISSUE THREAD

**Issue by JamesVanWaza** [MicrosoftDocs/powerbi-docs#4335]
[2. Drag the Year field from the Calendar table onto the new blank table visualization.

Because Year is a numeric field, Power BI Desktop sums up its values. This summation doesn’t work well as an aggregation; we'll address that in the next step.] 

The screenshot should be as follows 

<img width="1392" alt="Screenshot 2023-02-06 at 1 55 23 PM" src="https://user-images.githubusercontent.com/4000076/217060219-218d9f2d-2e8d-44fb-a8f8-5c52073ee254.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5439d8e1-71bb-cdf7-53bc-952f08a359e0
* Version Independent ID: 11f475af-c858-0a7e-d07d-7083e4fc8e39
* Content: [Tutorial: Create your own measures in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-tutorial-create-measures)
* Content Source: [powerbi-docs/transform-model/desktop-tutorial-create-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-tutorial-create-measures.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JamesVanWaza. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
This article is in the process of being refreshed. Thanks for your comment!
