### ISSUE TITLE
Goals now called metrics....please update

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#4338]
In the datasource and storage considerations section - this article still refers to a feature by the old name.  PowerBI Goals was rebranded as PowerBI Metrics in May 2022 (https://powerbi.microsoft.com/en-us/blog/power-bi-goals-is-now-metrics-and-is-moving-to-ga/)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9a86dc-4be4-d0a2-644d-cb20e3af74fb
* Version Independent ID: d08af8bc-fb3e-e443-7152-abaa0f2df6cc
* Content: [Bring your own encryption keys for Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-encryption-byok)
* Content Source: [powerbi-docs/enterprise/service-encryption-byok.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-encryption-byok.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks - we've updated that article / term.
