### ISSUE TITLE
No longer a good out-of-the-box demo

### ISSUE THREAD

**Issue by ToddASchultz** [MicrosoftDocs/powerbi-docs#4339]
I was looking for something to get students started using Power BI and thought this would be a good place. Unfortunately they have apparently reformatted the page at https://www.bankrate.com/retirement/best-and-worst-states-for-retirement/ and the html table the tutorial uses for data doesn't appear after you've connected to the web page. As an instructor I could provide addenda to the MS Learn guidance and provide a downloaded version of the data or use it as an outline for my own pedagogy but I'm disappointed this didn't 'just work'. Perhaps referencing a data source you have control over in a rewrite would help give the lesson legs. But thanks for MS Learn and other great content; cheers!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ToddASchultz. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments! We're in the process of updating this page, with new steps and data samples.

**Comment by ToddASchultz** [comment]
This is great responsiveness and much appreciated. My 'alter ego' is as a prof including Power BI in coursework so thank you!

Todd Schultz | 678 787 3186
