### ISSUE TITLE
link

### ISSUE THREAD

**Issue by ioshiames** [MicrosoftDocs/powerbi-docs#434]
sign up link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae3f747f-9b4f-2bfc-831e-ed8232177d38
* Version Independent ID: b2da371d-aea3-010b-5e57-a6c8d5a9646d
* Content: [Signing up for Power BI with a new Office 365 Trial - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial)
* Content Source: [powerbi-docs/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-signing-up-for-power-bi-with-a-new-office-365-trial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @ioshiames . We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by mgblythe** [comment]
@ioshiames - this is fixed now, thanks!
