### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by DanMaker** [MicrosoftDocs/powerbi-docs#4341]
I am unable to find the sample report and dashboard referenced in the document. It seems to have been removed from the current version of Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd11f485-a55c-c55e-a650-3453d3672a6c
* Version Independent ID: 92a62a8f-0da0-4e52-4f66-9156c3ed3fa6
* Content: [Getting around in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-experience)
* Content Source: [powerbi-docs/consumer/end-user-experience.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-experience.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DanMaker. This issue has been assigned to the doc author for review.

**Comment by DanMaker** [comment]
Thanks!

Dan Maker
Autodidact - Polymath
ADHD - ASD - Dyslexic
