### ISSUE TITLE
AI Insight Not working as per instruction

### ISSUE THREAD

**Issue by girdhars** [MicrosoftDocs/powerbi-docs#4345]
The instruction on this page seems outdated and does not work.  
Returns following error. 

---------- Message ----------
Cannot read properties of undefined (reading 'Kind')

---------- Stack ----------
TypeError: Cannot read properties of undefined (reading 'Kind')
    at Fe (https://us.prod.powerquery.microsoft.com/MashupEditor/scripts/qegsb.qe.dpfv.bmfv.4b4ba1099813582b7d72.bundle.js:1:63159)

---------- Session ID ----------
f56e4c09-4d00-4325-952d-825c6e1a8d58

---------- Mashup script ----------
section Section1;
shared FabrikamComments = let
  Source = Csv.Document(Web.Contents("https://pbiaitutorials.blob.core.windows.net/textanalytics/FabrikamComments.csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"id", Int64.Type}, {"inreplyto", Int64.Type}, {"name", type text}, {"userid", type text}, {"emailaddress", type text}, {"datetime", type time}, {"topic", type text}, {"subject", type text}, {"comment", type text}, {"spamscore", Int64.Type}, {"votes", Int64.Type}})
in
  #"Changed column type";

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a614670c-d6fb-2933-ca40-1be5901beb27
* Version Independent ID: f7f97531-c634-e7c0-8280-26b1c7931f47
* Content: [Tutorial: Use Cognitive Services in Power BI (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-tutorial-use-cognitive-services)
* Content Source: [powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-use-cognitive-services.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @girdhars. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated and tested these steps since you posted here, thanks for your contribution.
