### ISSUE TITLE
This does not work for User Groups

### ISSUE THREAD

**Issue by alexsaare** [MicrosoftDocs/powerbi-docs#4346]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5db2f3b5-305f-2803-012a-04154b58acb2
* Version Independent ID: 3bf41b0d-cd66-9782-1d2c-d1d79319048c
* Content: [Give users access to workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-give-access-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-give-access-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-give-access-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alexsaare. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @alexsaare, I know that it is possible to put assign a workspace role to a user group, but I am not sure whether all the groups mentioned in the article are still supported. Can you provide more detail as to which kind of group didn't work for you? In the meantime time I'm closing this issue, but please reopen when you can provide me a bit more detail. Thanks!
