### ISSUE TITLE
Impossible to do the tutorial as the required sample report is not available

### ISSUE THREAD

**Issue by fredzj** [MicrosoftDocs/powerbi-docs#4347]
Step 2 "_Select Learn and in the Learning center, scroll down to Sample reports. Select the right arrow until you get to Sales and Marketing Sample. Select the sample report_." is not possible as **there is no** "Sales and Marketing Sample" **report**.
However, I do see other sample reports:
- Revenue Opportunities
- Regional Sales Sample
- Corporate Spend
- Artificial Intelligence Sample
- Employee Hiring and History
- Store Sales
- Competitive Marketing Analysis

Do I really need the "Sales and Marketing Sample" report or can I use any one of the available reports?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dd11f485-a55c-c55e-a650-3453d3672a6c
* Version Independent ID: 92a62a8f-0da0-4e52-4f66-9156c3ed3fa6
* Content: [Getting around in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-experience)
* Content Source: [powerbi-docs/consumer/end-user-experience.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-experience.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @fredzj ,
You can use any sample data to follow along. But the Sales and Marketing sample will allow you to mimic exactly what you see in the screenshots.  I just checked the Learning Center, and the Sales and Marketing Sample is there.  Please check again.  If you still don't see it, please reopen this Git Issue. 
Thank you,
the DOCS team
