### ISSUE TITLE
RLS and external identities

### ISSUE THREAD

**Issue by hokeson** [MicrosoftDocs/powerbi-docs#4348]
could you please amend the document with information how RLS can be used for external users?

their email addresses are recognized as mail#name@domain.com or name_gmail#EXT#domain.onmicrosoft.com and it is unpredictable

this is undocumented since long time. please se here 
https://teams.microsoft.com/l/message/19:ebd5245e2cb246c78ab70aeaf2b33624@thread.skype/1675345315741?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=77f40803-dca6-4e92-bcab-1104d6a99c97&parentMessageId=1675345315741&teamName=PBICAT&channelName=General&createdTime=1675345315741&allowXTenantAccess=false

https://teams.microsoft.com/l/message/19:ebd5245e2cb246c78ab70aeaf2b33624@thread.skype/1544651277685?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=77f40803-dca6-4e92-bcab-1104d6a99c97&parentMessageId=1544651277685&teamName=PBICAT&channelName=General&createdTime=1544651277685&allowXTenantAccess=false

https://learn.microsoft.com/en-us/azure/active-directory/external-identities/user-properties#key-properties-of-the-azure-ad-b2b-collaboration-user

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hokeson. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @hokeson for reaching out and for the links. I have reached out to some of the people there to try to come up with a informative/useful update to the doc regarding the issue you have raised. Thanks!

**Comment by mberdugo** [comment]
Hi @hokeson. Unfortunately, it doesn't look like this issue will be solved any time soon. 
You can try consulting with your Azure AD SME to find out how foreign tenant UPNs get reformatted on the resource tenant.

Since this is really a product question, you can submit product feedback at [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi). Maybe that will encourage them to come up with a solution faster.
Good luck.
