### ISSUE TITLE
What is Premium Capacity, and how is it accessed?

### ISSUE THREAD

**Issue by jimblair** [MicrosoftDocs/powerbi-docs#435]
What is "Premium Capacity", because it is not intuitive, and how does Premium Capacity figure into these roles?....is it that some published content is classified as "premium" and users that want access to the "premium" content must have "Premium Capacity" access rights?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c145d771-e728-7687-bc99-a23bc5bcb648
* Version Independent ID: b26adda7-398b-b2e2-e51d-b4f1f762bb62
* Content: [Power BI Free vs Pro - Power BI](https://docs.microsoft.com/en-us/power-bi/service-features-license-type)
* Content Source: [powerbi-docs/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-features-license-type.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@jimblair -- sorry, we just realized that this issue was sitting around unassigned. In the meantime, we updated the article and there's a link out to the premium capacity article, which covers what that is.
