### ISSUE TITLE
Storage location for Premium capacity vs. Shared capacity

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4358]
From the article: 

![image](https://user-images.githubusercontent.com/1765732/219977032-e8416cd5-9726-44ec-93e3-421d8bb1d7c0.png)

The structure described in the table is the same across the 2 options. Is this correct? 

The paragraph before the table leads the reader to believe the structure would be different.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @VitalyMCT ,

Can you please let us know which article you're referring to?

Thanks,

Kesem

**Comment by VitalyMCT** [comment]
Sorry, I've mistakenly removed the article link from the original post :)

It's https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration

**Comment by davidiseminger** [comment]
Thanks for pointing this out - we've updated the article in a few places to remove the ambiguity (the location is the same regardless of using Premium or shared). The updates will go live later today.
