### ISSUE TITLE
Usage metrics - changes to the report are not supported

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4359]
Hi,
in this section [https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#create-a-copy-of-the-usage-report](url) the documentation suggests that Customers can freely create copies & add new visualisations.
Product group has mentioned that when a customer edits & there are performance issues, the report will not be supported by Microsoft. The model does not show the relationships thus Customers can built models that will not perform well.

Please add to the document - there is the purple-ish box with other warnings.
Although Microsoft allows the option to connect to the dataset and make changes/create additional views, these changes may impact the performance of the new Usage metric app. Please note such changes may be out of scope of Microsoft support.

Thank you.
Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in workspaces (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @MartinaPoddana, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
