### ISSUE TITLE
Incorrect Link Text for December 2022 PowerBI Archive Downloads

### ISSUE THREAD

**Issue by dlwillequer** [MicrosoftDocs/powerbi-docs#4360]
The link text for the December 2022 downloads incorrectly references November 2022 downloads, though the actual file is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dlwillequer. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out -- fixed!
