### ISSUE TITLE
PPU vs "Premium capacity"

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#4361]
It is very confusing to understand what is the difference between PPU vs Premium capacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6e1bb7-fbc5-d0a6-5285-e4a9152902bb
* Version Independent ID: ece0823b-c4c5-3acb-41bb-55e5390c0b6c
* Content: [Power BI service features by license type - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type)
* Content Source: [powerbi-docs/fundamentals/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-features-license-type.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gvggvg. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. 

Note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests (or in this case, potentially confusing terms for license types).

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
