### ISSUE TITLE
Cannot embed icons.

### ISSUE THREAD

**Issue by FlatCapHat** [MicrosoftDocs/powerbi-docs#4363]
[Enter feedback here]
Please list all schema properties including how icons are embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FlatCapHat. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @FlatCapHat, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for your request!
