### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4364]
I think the article would benefit from covering the security model associated with comments.

Who can comment on the reports? Is read-only access possible to configure? If so, how?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3fe39329-a8c9-8a14-ab97-ca853b432bf3
* Version Independent ID: 7dbe16ce-5a10-1162-a1f1-92d5280ed534
* Content: [Add comments to dashboards and reports - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-comment)
* Content Source: [powerbi-docs/consumer/end-user-comment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-comment.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @VitalyMCT , 
Thank you for your suggestion.  We've made the updates and set the article to republish. 
All the best,
The DOCS team
