### ISSUE TITLE
Adding Guest User Changed?

### ISSUE THREAD

**Issue by rconiv** [MicrosoftDocs/powerbi-docs#4368]
(Found this was under the preview view in Azure, if under the classic it is the listed steps on the page).

Under the section Case Study: Building a BI Portal using Power BI + Azure AD B2B – Step-by-Step instructions there is an entry for creating a guest account.

If I go to Azure Active Directory\Users\All Users, there is not a guest user option.  

If I though do the drop down for New User, there is a Create new user or Invite external user which I am guessing would be a guest user.

![image](https://user-images.githubusercontent.com/72881999/221023010-be56f74f-c569-43c9-9b4b-570189c7c90f.png)

The layout of the next page it basically the same with a couple more options for Identity.

![image](https://user-images.githubusercontent.com/72881999/221023271-f4836633-afe2-4bd9-bce2-fce452c7e4ad.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rconiv. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing this out, we'll look at updating those screens.
