### ISSUE TITLE
QnA Not Working

### ISSUE THREAD

**Issue by westmich** [MicrosoftDocs/powerbi-docs#437]
I cannot get QnA on HR example.  I see the icon and underline on the initial dashboard but once I click into it, I am brought to a blank screen.  There is a link at the top to exit but no place to enter questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26de6125-fac6-cf9b-3677-861d0dd69d13
* Version Independent ID: 7ab8f758-bc5a-12b6-96ba-1b14c091811a
* Content: [Human Resources sample: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-human-resources)
* Content Source: [powerbi-docs/sample-human-resources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-human-resources.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by westmich** [comment]
And yes I have it enabled from settings.

**Comment by westmich** [comment]
I did find an additional settings tab (yes I am new to this) and when I attempt to refresh the data I get the following error message.  I assume without a model defined the QnA doesn't work?  But it doesn't give me any indication - just a blank screen.

Refresh can't be scheduled because the data set doesn't contain any data model connections, or is a worksheet or linked table.

**Comment by maggiesMSFT** [comment]
Hi, @westmich -- Sorry to hear it's not working. The refresh part makes sense -- the sample is a static file. It has no data sources to refresh. 
The Q&A part is a puzzle though. I recommend asking the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. Good luck!
