### ISSUE TITLE
Better explanation of the Distribution methods would be needed

### ISSUE THREAD

**Issue by arherva** [MicrosoftDocs/powerbi-docs#4370]
Hi,

This page could contain a brief explanation of the Distribution Methods on the usage metrics. I believe the content packs mean the usage metrics of the report artefact via a power bi app but the term content pack is a bit misleading or counterintuitive and hence it might be good to an explanation on this page.

-Arttu

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor report usage metrics - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @arherva. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @arherva, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for your suggestion!
