### ISSUE TITLE
where is the option to edit y axis?

### ISSUE THREAD

**Issue by mikebk95** [MicrosoftDocs/powerbi-docs#4371]
In the video, it looks like there is the ability to rename the y-axis inside the format of your visual section. This is not the case in the current PowerBi tool. Can you please update me on how to edit the Y axis without changing the table name in the add visual to data section?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ad604499-b845-44de-acc9-1bd9a7a97488
* Version Independent ID: f16079ec-98ee-e35d-f928-c5d493365051
* Content: [Customize X-axis and Y-axis properties - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-customize-x-axis-and-y-axis)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-customize-x-axis-and-y-axis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
