### ISSUE TITLE
Power BI Item Certification Criteria

### ISSUE THREAD

**Issue by BhupendraUpadhyay1992** [MicrosoftDocs/powerbi-docs#4372]
Hi Melissa,

I am new to Power BI admin team in Canberra, Australia. We look after around 500+ PRO users in our tenancy. 

Thank you for publishing this article. It is extremely helpful. 😀 

We are at the early stages of investigating certification and tagging of the Power BI content. 

Do you have any plans to provide a (best practice) guide on certification criteria (report, datasets etc) ? 
There are many sites on the internet that give steps to certify but nobody describes how/what the certifications criteria to certify the items (e.g. https://learn.microsoft.com/en-us/power-bi/admin/service-admin-setup-certification). 
Being in the data science field, a measurable set of criteria is where we want to land for assessment and monitoring of certification conformance.

I would be happy to provide any of our findings etc if you are going to include certification criteria in this space. 

Thank you :) 

Bhupendra

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aaef981b-ed05-d084-6692-b168cccac28c
* Version Independent ID: aaef981b-ed05-d084-6692-b168cccac28c
* Content: [Power BI implementation planning - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-introduction#subject-areas)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-introduction.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BhupendraUpadhyay1992. This issue has been assigned to the doc author for review.

**Comment by BhupendraUpadhyay1992** [comment]
Hey @davidiseminger,

Is there any update on this?

Thanks,
Bhupendra

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
