### ISSUE TITLE
Feature is GA

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4376]
The following note is obsolete and should be removed:

> Query Diagnostics is currently a preview feature, and so you must enable it in Options and Settings. Once enabled, its commands are available in the Power Query Editor window, on the Tools ribbon tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 683b70c5-16bc-6d10-0433-a39a6be16995
* Version Independent ID: 9d664ac7-b484-3b5f-f215-613f95fe60ec
* Content: [Monitor report performance in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/monitor-report-performance)
* Content Source: [powerbi-docs/guidance/monitor-report-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/monitor-report-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out, done!
