### ISSUE TITLE
Filter report that is published to web via URL parameters

### ISSUE THREAD

**Issue by niamhhenry** [MicrosoftDocs/powerbi-docs#4377]
URL parameters can filter report when in Power BI service, however, this does not work on report that is published to web (with public access). Only want to use it in the public facing report, to allow users to land on a report filtered for a specific country. Is there plans for this functionality to be introduced, or are there any ways to implement this? 

It has been posted as an idea here years ago with some traction on comments, but unsure if it has been noted: https://ideas.powerbi.com/ideas/idea/?ideaid=48c29869-fb16-4eea-b0ab-26e973309112

**Comment by bishalgoswami** [comment]
Thanks for your comment, @niamhhenry. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @niamhhenry,

This is a GitHub channel for documentation issues. We don't comment on future product plans.

Apart from submitting your idea, you can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

Thanks,

Kesem
