### ISSUE TITLE
Relationship to Data Gateway

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#438]
how do these settings relate to the privacy level settings in the Data Gateway Data Source Settings page. Do they have to match? please provide an explanation in this documentation and in the documentation for the Gateways.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-privacy-levels)
* Content Source: [powerbi-docs/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-privacy-levels.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @DeanGross.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by mgblythe** [comment]
@arthiriyer as FYI, will address in gateways docs update

**Comment by mgblythe** [comment]
For data refresh, you have to specify the settings again either on the dataset settings page for cloud sources or on the manage gateways page for on-prem sources.

**Comment by mgblythe** [comment]
We have this info in the overall [refresh article](https://docs.microsoft.com/en-us/power-bi/refresh-data):

Apply the same privacy settings as in Power BI Desktop to ensure that Power BI can generate efficient source queries. Keep in mind that Power BI Desktop does not publish privacy settings. You must manually reapply the settings in the data source definitions after publishing your dataset.
