### ISSUE TITLE
Creaciones Acme

### ISSUE THREAD

**Issue by LoboVerga** [MicrosoftDocs/powerbi-docs#4382]
![16777274693545839162430875781793.jpg](https://user-images.githubusercontent.com/111120272/222323130-cd6377be-486d-4742-8823-4c5f4cf20598.jpg)

![dvdprofiler.png](https://user-images.githubusercontent.com/111120272/222323232-ba831f42-3dd6-4b4a-8d0a-8b7297a2f836.png)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LoboVerga. This issue has been assigned to the doc author for review.
