### ISSUE TITLE
Creaciones Acme

### ISSUE THREAD

**Issue by LoboVerga** [MicrosoftDocs/powerbi-docs#4383]
https://github.com/LoboVerga/Jose-Manuel-Lopez-Lobato/issues/12

**Comment by LoboVerga** [comment]
> https://github.com/LoboVerga/Jose-Manuel-Lopez-Lobato/issues/12

🙋

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LoboVerga. This issue has been assigned to the doc author for review.
