### ISSUE TITLE
2023-03-01 Captura de pantalla

### ISSUE THREAD

**Issue by LoboVerga** [MicrosoftDocs/powerbi-docs#4384]
Creaciones Acme

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LoboVerga. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @LoboVerga,

Thanks for getting involved and contributing to our documentation. The changes you're suggesting will be dealt with in the repositories you listed.

Kesem
