### ISSUE TITLE
@ksgaipal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

### ISSUE THREAD

**Issue by LoboVerga** [MicrosoftDocs/powerbi-docs#4385]
@ksgaipal : Thanks for your contribution! The author(s) have been notified to review your proposed change. 

_Publicado originalmente por @prmerger-automator en https://github.com/MicrosoftDocs/powerbi-docs/pull/4315#issuecomment-1405929773_

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LoboVerga. This issue has been assigned to the doc author for review.

**Comment by LoboVerga** [comment]
Duplicate of #

**Comment by KesemSharabi** [comment]
Hi @LoboVerga,

PR [https://github.com/MicrosoftDocs/powerbi-docs/pull/4315](https://github.com/MicrosoftDocs/powerbi-docs/pull/4315) has been merged.

Thanks for getting involved.

Kesem
