### ISSUE TITLE
Add Query memory limit in Shared to the Doc

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4387]
Please add 1GB query memory limit in a Shared Workspace

[https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#query-memory-limit](url)

a Note under the Automatic Query Memory Limits
**The query memory limit for Shared workspaces is 1GB.**

I found the information in Teams Escalation channels and in Chriss Webb's blog.

[https://teams.microsoft.com/l/message/19:8b3f41a1c2c24182a67a5df032152c4f@thread.skype/1616718050807?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=1938a03d-6811-4a8a-8334-7aabc55fbd65&parentMessageId=1616520677467&teamName=Power%20BI%20Escalations%20Team&channelName=Service%20Back-end%20(UseAva)(MiddleTier-ServiceInfra)&createdTime=1616718050807&allowXTenantAccess=false](url)

[https://blog.crossjoin.co.uk/2020/01/20/visual-has-exceeded-the-available-resources-error-power-bi/](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#query-memory-limit)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Started an email thread for this.
