### ISSUE TITLE
What are the options?

### ISSUE THREAD

**Issue by tasranson** [MicrosoftDocs/powerbi-docs#4389]
This statement:
The Microsoft Graph Security connector is deprecated as of May 2021 and has been removed from the "Get Data" experience in Power BI Desktop. We recommend that you replace existing connections that use this connector, and refrain from using this connector for new connections. For more information, see the [Microsoft Graph Security documentation](https://learn.microsoft.com/en-us/power-query/connectors/microsoftgraphsecurity).

Clearly recommends moving away from the Microsoft Graph Security Connector.  The for more information link provides LESS information than this page does.  Surely it would be useful to readers to give them an idea of what the alternatives are that they should migrate to?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @tasranson, yes the connector has long been deprecated and the Graph Security connector team has provided no information about possible alternatives. I left our page up just in case someone needed the documentation there, but it seems to be only causing confusion so I am deleting it now and just redirecting to theirs, even though I know there is no useful information there. The only thing I can suggest is to open an issue from that page ( https://learn.microsoft.com/power-query/connectors/microsoft-graph-security ) and see whether you have better luck.
In any event, thanks for taking the time to reach out!
