### ISSUE TITLE
Out-of-date informations

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerbi-docs#4390]
Hello,

I would like to draw attention on this page that contains out-of-date information. Power BI Desktop has reached February 2023 version but the page still shows versions up to December 2022 only.
I have some issues with Power BI Desktop and I need older versions to test if that version had same issues and it would be helpful to find the proper download here.

Kind Regads,
Lucian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks, we've updated that article.
