### ISSUE TITLE
Page is incorrect

### ISSUE THREAD

**Issue by MagDev175** [MicrosoftDocs/powerbi-docs#4391]
https://learn.microsoft.com/en-us/power-bi/connect-data/service-parameters#next-steps is incorrect. You can't change parameters in url. You can change a filter, but that is not the same thing as parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d00a910-94df-cb0d-d8e5-81160bd2f569
* Version Independent ID: 4925a925-42fd-8deb-d702-25cd929a5849
* Content: [Edit parameter settings in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-parameters#review-and-edit-parameters-in-power-bi-service)
* Content Source: [powerbi-docs/connect-data/service-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MagDev175. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! Thanks, I've updated that article.
