### ISSUE TITLE
XMLA Endpoint seems to be incompatible with SSMS 19.0.

### ISSUE THREAD

**Issue by b77uw771b** [MicrosoftDocs/powerbi-docs#4393]
XMLA Endpoint seems to be incompatible with SSMS 19.0.  
SEE: https://community.powerbi.com/t5/Service/Is-XMLA-Endpoint-incompatible-with-SSMS-19-0/m-p/3050910#M186883
This should either be resolved by the SSM product team or documented here.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 394a809f-0675-e6df-536d-ed6af56a8068
* Version Independent ID: 394a809f-0675-e6df-536d-ed6af56a8068
* Content: [Troubleshoot XMLA endpoint connectivity in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/troubleshoot-xmla-endpoint#connect-to-server-error-in-ssms)
* Content Source: [powerbi-docs/enterprise/troubleshoot-xmla-endpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/troubleshoot-xmla-endpoint.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @Minewiskan
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @b77uw771b. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
#in-progress

**Comment by Minewiskan** [comment]
This was fixed in SSMS 19.0.2. Released on March 13th.
