### ISSUE TITLE
Appears broken in last update

### ISSUE THREAD

**Issue by jluftman** [MicrosoftDocs/powerbi-docs#4394]
Since the last update my shortcut no longer opens my report.
Shortcut now opens Power Bi to the home screen then navigates to My Workspaces and the spinner just spins.
Deleted and readied shortcut without success. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: afadb43c-aeb1-0570-2237-45ac596b4833
* Version Independent ID: dee1e434-5ea7-54d0-cb05-1e7ddc1e523f
* Content: [Power BI mobile app integration with Siri shortcuts - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-ios-siri-shortcuts)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-ios-siri-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-apps-ios-siri-shortcuts.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @jluftman, you've reached the documentation team, and this seems to be more of a product support issue. Can you describe your problem in an email and send it to mpbisup@microsoft.com? Best sure include something in the subject line like "Shortcuts don't work since last update" or something like that, to focus their attention. They will be the best ones to address your problem. Thanks!

**Comment by jluftman** [comment]
Yeah. The doc page wasn’t clear that is was looking to report a documentation Issa and not an application issue.  All good since there must have been another update a couple days ago since it works again.  (I made no changes on my side)ThanksSent from my iPadOn Mar 13, 2023, at 2:32 PM, Paul Inbar ***@***.***> wrote:﻿
Hi @jluftman, you've reached the documentation team, and this seems to be more of a product support issue. Can you describe your problem in an email and send it to ***@***.***? Best sure include something in the subject line like "Shortcuts don't work since last update" or something like that, to focus their attention. They will be the best ones to address your problem. Thanks!

**Comment by paulinbar** [comment]
@jluftman, Great! Glad to know it worked out, whatever it was.
