### ISSUE TITLE
When was this page last edited?

### ISSUE THREAD

**Issue by docgregt** [MicrosoftDocs/powerbi-docs#4398]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae7715f-ecbe-4d43-de96-6ec3459e59f0
* Version Independent ID: 8ae7715f-ecbe-4d43-de96-6ec3459e59f0
* Content: [Power BI high availability, failover, and disaster recovery FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-failover)
* Content Source: [powerbi-docs/enterprise/service-admin-failover.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-failover.yml)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @docgregt. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. We review and update articles as features change and on an ongoing basis. If there is specific feedback about any of the guidance, feel free to submit it and we'll review.
