### ISSUE TITLE
Different Table1 dataset

### ISSUE THREAD

**Issue by igwesamuel** [MicrosoftDocs/powerbi-docs#4400]
[Enter feedback here]

The Table1 dataset from the Web has been changed but the page still seems to use an old one. The data gotten from the web and the one used in the tutorial are different. Kindly look into this. Thank you.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @igwesamuel. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
We've updated that article, thanks!
