### ISSUE TITLE
Incorrect number of days

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/powerbi-docs#4402]
"When you select Usage metrics or the icon usage metrics icon. next to a dashboard or report, Power BI generates a pre-built report with usage metrics for that content for the last 90 days. "

The last 90 days is to the best of my knowledge incorrect.  Only the last 30 days are available via the Power Bi service, the Power API activity only returns that last **30 days**. All reports which I have access to via a number of different clients only returns **30 days** of history.

That said the Office 365 audit logs do return that the last 90 days. It should be noted that this history is not available via the end use of the Power BI Metrics User reports do not have access to those logs. Via the Power BI service. Nor to the best of my knowledge is that data surfaced by the dataset which support the Power BI Metrics User reports.

If I am incorrect, then can you let me know how to get the last 90 days of data in the power bi service, and via the the Power Restful API activity as this would be of significant benefit.

Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Monitor report usage metrics - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rwlpf. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
thanks for your comment @rwlpf! I'm checking with the product group. I note that it says 90 days on the usage metrics report itself.

**Comment by paulinbar** [comment]
Hi @rwlpf , I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime.
