### ISSUE TITLE
Documentation does not clearly cover the Power BI licensing for Email subscription

### ISSUE THREAD

**Issue by kushaldugar** [MicrosoftDocs/powerbi-docs#4403]
[Enter feedback here]
Can a user with Power BI Pro/PPU license set up an email subscription for free users in the organization, in a scenario when the Premium per capacity is not available? Will the free users receive emails in this scenario?

I referred the documentation _**https://learn.microsoft.com/en-us/power-bi/collaborate-share/end-user-subscribe?tabs=creator**_ but did not get much clarity on the topic.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for reports and dashboards in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/end-user-subscribe?tabs=creator)
* Content Source: [powerbi-docs/collaborate-share/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kushaldugar. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
