### ISSUE TITLE
Instructions for connecting PowerBI Desktop to Msft Graph are obsolete

### ISSUE THREAD

**Issue by ExchangeTips** [MicrosoftDocs/powerbi-docs#4404]
Page instructions are obsolete. Microsoft Graph Security API is not an available option for Power BI Desktop.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e7110b1-ad2a-f73a-3ada-27fbc387075c
* Version Independent ID: 1f8fafd5-ddfa-76c1-1ee0-3a015b87c84c
* Content: [Connect to the Microsoft Graph Security API in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-graph-security)
* Content Source: [powerbi-docs/connect-data/desktop-connect-graph-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-graph-security.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi Jay, yes the connector has long been deprecated and the Graph Security connector team has provided no information about possible alternatives. I left our page just in case someone needed the documentation there, but it seems to be only causing confusion so I am deleting it now and just redirecting to theirs, even though I no there is no useful information there. The only thing I can suggest is to open an issue from that page ( https://learn.microsoft.com/power-query/connectors/microsoft-graph-security ) and see whether you have better luck.
In any event, thanks for taking the time to reach out!
@ExchangeTips
