### ISSUE TITLE
Refining dataflow settings in Premium refering to Premium GEN 1

### ISSUE THREAD

**Issue by fabienadato** [MicrosoftDocs/powerbi-docs#4406]
The "Refining dataflow settings in Premium" paragraph is referring to Power BI Premium GEN 1 (old architecture). Is it possible to adapt it to GEN 2 or remove it ?

Thanks !

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6054103-4999-9ce2-ba30-095a6d469465
* Version Independent ID: 2ce5b049-276a-a159-4f28-fd1dca17442f
* Content: [Configure Power BI Premium dataflow workloads - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-premium-workload-configuration#refining-dataflow-settings-in-premium)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-premium-workload-configuration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fabienadato. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Assigning to Kesem, as owner of Premium content to determine how best to handle this feedback.

**Comment by KesemSharabi** [comment]
Hi @fabienadato,

Thank you for pointing this out!

We updated the [Refining dataflow settings in Premium](https://learn.microsoft.com/power-bi/transform-model/dataflows/dataflows-premium-workload-configuration#refining-dataflow-settings-in-premium) section for Premium Gen2.

Thanks,

Kesem
