### ISSUE TITLE
Confusing information in getting the T-SQL connection string

### ISSUE THREAD

**Issue by Shuwi75** [MicrosoftDocs/powerbi-docs#4407]
The section 'getting the T-SQL connection string" says "To connect to a datamart’s SQL endpoint with client tooling, navigate to the dataset settings page. From there, expand the Server settings section and copy the connection string, as shown in the following image."
This is confusing as people could go to the dataset in the workspace, go to the settings page and copy the connectionstring from there (ALSO CALLED SERVER SETTINGS) but is in format 'powerbi://api.powerbi.com/v1.0/....'; Which won't work to connect to the datamart azure sql db. From the text, it's not clear users need first to go to the datamart(preview) tab and perform the actions from THAT location. (The picture shows this, but there are people who only read the text and don't look at the picture..). 

Thanks in advance for your support!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2be7c787-9e6b-f36b-ba68-78a49f41b6fa
* Version Independent ID: 2be7c787-9e6b-f36b-ba68-78a49f41b6fa
* Content: [Analyzing datamarts (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-analyze)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-analyze.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-analyze.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Shuwi75. This issue has been assigned to the doc author for review.
