### ISSUE TITLE
Wrong hyperlink in Next section

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4408]
In section "Next" you have link "[Esri's ArcGIS Maps for Power BI documentation](https://www.esri.com/arcgis/products/arcgis-for-power-bi/)" which leads me to page with 404 error code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: acf2c48a-66f7-6c38-286e-ae429fc34883
* Version Independent ID: 033ec0fc-5c72-8cf2-20fb-1c7a36ebcd5f
* Content: [Create an ArcGIS map in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualizations-arcgis#considerations-and-limitations)
* Content Source: [powerbi-docs/visuals/power-bi-visualizations-arcgis.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualizations-arcgis.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @MartinKDK , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
