### ISSUE TITLE
This page is out of date

### ISSUE THREAD

**Issue by stevemc77** [MicrosoftDocs/powerbi-docs#4409]
As of today this page is out of date. In the new navigation pane I am missing a useful option when using RLS. I can no longer toggle between reports that are linked to one dataset/workspace in the navigation pane to the left.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1ac88ce-bda3-f687-18a2-ec414b7b6b15
* Version Independent ID: c1ac88ce-bda3-f687-18a2-ec414b7b6b15
* Content: [Updates to the experience in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-experience-changes#navigation-pane-changes)
* Content Source: [powerbi-docs/fundamentals/service-experience-changes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-experience-changes.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stevemc77. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @stevemc77, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for pointing this out!
