### ISSUE TITLE
Tutorial: Shape and combine data in Power BI Desktop

### ISSUE THREAD

**Issue by Dorothyhs** [MicrosoftDocs/powerbi-docs#4414]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by Dorothyhs** [comment]
The dataset from the web site: https://www.fool.com/research/best-states-to-retire does not match the documentation for the training over this title: "Tutorial: Shape and combine data in Power BI Desktop".  There is no weather column in the dataset.  This is the Retirement Data

**Comment by Dorothyhs** [comment]
I hit the wrong button:  

The dataset from the web site: https://www.fool.com/research/best-states-to-retire does not match the documentation for the training over this title: "Tutorial: Shape and combine data in Power BI Desktop". There is no weather column in the dataset. This is the Retirement Data

**Comment by davidiseminger** [comment]
Thanks, we've updated that article.
