### ISSUE TITLE
Mistake in documentation - viewers are not getting build permission

### ISSUE THREAD

**Issue by AdamGlArla** [MicrosoftDocs/powerbi-docs#4415]
I think this documentation section is wrong or at least very confusing:

`All users who already have Read permission for datasets via app permissions, sharing, or workspace access also get Build permission for those datasets. Those users get Build permission automatically because Read permission already grants them the right to build new content on the dataset by using Analyze in Excel or Export.`

Viewers are not getting build permission for the dataset!

(https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions?source=recommendations#more-granular-permissions)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions?source=recommendations#more-granular-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @AdamGlArla. Thanks for pointing this out. I am working with the product team to get clarification and will update the doc as necessary. So in the meantime I am closing this issue. Thanks again for your feedback!
