### ISSUE TITLE
Limitation Not supported for Power BI Report server

### ISSUE THREAD

**Issue by KornAlexander** [MicrosoftDocs/powerbi-docs#4419]
Hello team,

can we please add a big block in the beginning that the functionality is not supported with Power BI Report Server? This will benefit case deflection.
Thanks in advance. 

Best regards,
Alexander Korn
Support Engineer SQL BI
Microsoft Alias: akorn

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KornAlexander. This issue has been assigned to the doc author for review.
