### ISSUE TITLE
Paginated Reports not showing correclty

### ISSUE THREAD

**Issue by saiyash05** [MicrosoftDocs/powerbi-docs#442]
Paginated Reports bookmark on "Filters" tab is  showing actual PBI Reports not the Paginated Reports.
Also, the same issue under "Display Names and IDs" tab. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity#use-the-metrics-app)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Hi @saiyash05 - so this is an issue you're seeing in the app (i.e. not the docs)?

**Comment by saiyash05** [comment]
@mgblythe : Yes, this is an issue I am seeing in the app.

**Comment by mgblythe** [comment]
Adding @swgupt to comment on this

**Comment by mgblythe** [comment]
Closing b/c this a product support issue. saiyash05 -- if you have any further issues with the app, please get support by going to https://support.powerbi.com.
