### ISSUE TITLE
A sku capacity licensing- no separate license required for consumers of content

### ISSUE THREAD

**Issue by lauraadelman** [MicrosoftDocs/powerbi-docs#4420]
"Note

If you purchase an A4 or higher SKU, you can take advantage of all Premium features except for unlimited sharing of content. With A SKUs, all users who consume content require Pro licenses."
[Enter feedback here]
This appears to be in conflict with capacity licensing tenets. I believe it is incorrect and should read "developers of content" and not consume content.  Thank you for clarifying!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 438cf2c2-6f00-d09e-1bb9-05b7a1daa1fa
* Version Independent ID: 438cf2c2-6f00-d09e-1bb9-05b7a1daa1fa
* Content: [Purchase Power BI Premium for testing - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-testing)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-testing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-testing.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lauraadelman. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @lauraadelman,

I double checked with the product team, and the statement below is correct (taken from [Purchase A SKUs for testing and other scenarios](https://learn.microsoft.com/power-bi/enterprise/service-admin-premium-testing#purchase-a-skus-for-testing-and-other-scenarios)).

<img width="522" alt="image" src="https://user-images.githubusercontent.com/54834915/236785405-552e990c-e609-446a-8bc3-2ad7654cabb3.png">

Thanks,

Kesem
