### ISSUE TITLE
PowerBI Desktop Prerequisite Missing Version/Type Details

### ISSUE THREAD

**Issue by UdbhavDesai** [MicrosoftDocs/powerbi-docs#4421]
In order to bind a parameter to a table column, you need to work off the standard Power BI Desktop. I was trying this on Power BI Desktop optimized for the Report Server, and this feature does not work on that edition/type of Power BI Desktop. Adding this disclaimer could save a lot of time for another Power BI developer. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
I added that limitation to the article, thanks!
