### ISSUE TITLE
A way of enforcing RLS not mentioned

### ISSUE THREAD

**Issue by AdamGlArla** [MicrosoftDocs/powerbi-docs#4422]
Hi,
I read the purple "Note" at the end of section [https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces#workspace-roles](url)

It says: 
`Use the Viewer role to enforce [row-level security (RLS)](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls) for users who browse content in a workspace. You can also enforce RLS without giving access to the workspace, [publish an app](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps) and distribute it to those users, or use [sharing to distribute content](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards).`

I can read in the Note that I can 'enforce RLS without giving access to the workspace' by publishing an app or by using the 'sharing' option. **What it does not mention is that we can simply go to dataset permission and assign users there**, without creating an app or using the share option. I had to test this with my colleagues to see if that option is valid and it is.

Also this fact:
**'to enforce RLS' for users who are only viewing content based on a dataset, it is not obligatory to assign those users with 'Viewer' access to the workspace where the dataset resides**

is only mentioned in the purple note, I did not find such information in documentation for RLS itself (would be nice to add it there as well!) [https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls](url)

Me and my team would appreciate it and I think the rest of community as well!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces#workspace-roles)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AdamGlArla. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @AdamGlArla, thanks for reaching out with this. I will look into it and update the docs as necessary.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
