### ISSUE TITLE
Add troubleshooting bullet point related to filters applied to the tile when pinned.

### ISSUE THREAD

**Issue by johndill** [MicrosoftDocs/powerbi-docs#4423]
I have had many users come to me complaining that their "tiles are not updating".  After some investigation, it appears that they are updating but the values shown in the tile on the dashboard do not match what is displayed in the visual on the report.  

Under the "Considerations and troubleshooting" section of this page, there is a bullet point that discusses changes to the visualization type not affecting the tile.  There is no mention of changes to visual/page/report level filters not affecting the information displayed in the tile.  I think this is an important point that should be clearly noted.

Some more clear wording for exactly what happens when you pin a tile could help here as well.  As far as I can tell "snapshot" is the keyword here.  It's creating a snapshot of the visual definition and the filter context.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0228b032-19fa-c869-8bd5-f3b5af3b492e
* Version Independent ID: 9c8d0c4b-01bc-a0b3-08df-ba6d76a0c185
* Content: [Dashboard tiles in Power BI service for business users - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-tiles)
* Content Source: [powerbi-docs/consumer/end-user-tiles.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-tiles.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment. The first paragraph of the article states that it's a snapshot, and a screenshot:

A tile is a snapshot of your data, pinned to a dashboard by a designer. Designers can create tiles from a report, dataset, dashboard, the Power BI Q&A question box, Excel, SQL Server Reporting Services (SSRS), and more. This screenshot shows many different tiles pinned to a dashboard.
