### ISSUE TITLE
broken link here

### ISSUE THREAD

**Issue by dataDad** [MicrosoftDocs/powerbi-docs#4424]
![image](https://user-images.githubusercontent.com/25039222/227168775-404effd4-d225-4d2a-a3ec-56ff095a0883.png)

you have a broken link here. second paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 840af022-bd15-4b43-f930-c4543cce050f
* Version Independent ID: 840af022-bd15-4b43-f930-c4543cce050f
* Content: [Power BI in-place dataset sharing with guest users in external organizations(preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-dataset-external-org-share-about)
* Content Source: [powerbi-docs/collaborate-share/service-dataset-external-org-share-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-dataset-external-org-share-about.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dataDad. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@dataDad - thanks for the feedback and for your patience! I have verified that the link you flagged is now properly resolving so will close this issue.
