### ISSUE TITLE
Dataset Scale-Out questions

### ISSUE THREAD

**Issue by abates100** [MicrosoftDocs/powerbi-docs#4427]
It is unclear in the documentation what happens if there are multiple datasets in a workspace once it is enabled for scale-out.  Or is that not possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Version Independent ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Content: [Power BI Dataset Scale-Out - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out)
* Content Source: [powerbi-docs/enterprise/service-premium-scale-out.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-scale-out.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @abates100. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @abates100,

If you have several datasets in a workspace that has scale-out turned on, copies will be created for all of the datasets, as long as the capacity has available compute power.

 Hope this helps,

Kesem

**Comment by JCREW-AnshulPurohit** [comment]
@KesemSharabi, in Premium Gen 2, Let say for P1, each dataset has a maximum memory allocation of 25 GB.

When a replica of a dataset is created, will it be assigned a new 25 GB memory allocation, or will it utilize the existing one from the read/write instance?

I'm trying to grasp this in terms of the potential for dataset eviction.
