### ISSUE TITLE
Drill through feature is no longer working the same in the latest version of PowerBI Desktop (March 2023)

### ISSUE THREAD

**Issue by johandeconingmswa** [MicrosoftDocs/powerbi-docs#4429]
You can add a drill through from your dataset in the latest version of PowerBI (March 2023), but it's not showing the Drill through selection as it used to, and it does not create the drill-through anymore from your main page.  Please update this page as to how this feature now works with the latest version of PowerBI.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @johandeconingmswa. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @johandeconingmswa, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
