### ISSUE TITLE
Missing GUI for add refresh plan /task

### ISSUE THREAD

**Issue by GGBMLC** [MicrosoftDocs/powerbi-docs#4430]
[Enter feedback here]
Hi
GUI at the Power BI missing input for setup Refresh time and date?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue l
![power bi](https://user-images.githubusercontent.com/92221040/227968976-092c4cde-d2c6-40e9-9412-b1ef1f92c737.PNG)
inking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://learn.microsoft.com/en-gb/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
