### ISSUE TITLE
Duplicate on incremental refresh page

### ISSUE THREAD

**Issue by elaynejones** [MicrosoftDocs/powerbi-docs#4433]
The paragraph about "There's no requirement the final query support folding...." is repeated on this page

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for datasets and real-time data in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by Minewiskan** [comment]
@elaynejones - Thanks for letting us know!  The updated page will appear later today.
