### ISSUE TITLE
Please provide link to updated/new page

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#4439]
Based on the [blog by Melissa Coates](https://www.coatesdatastrategies.com/blog/updated-whitepaper-planning-a-power-bi-enterprise-deployment), this whitepaper is outdated and will not be updated in the future. Moreover, it looks like it will be replaced by 
[this page](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-introduction) in the future. Please provide link to this updated page and also clarify that the existing whitepaper is out-dated and won't be updated or may be deprecated. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd0baa2-2e0a-9bbe-115f-f545f7c1ec84
* Version Independent ID: 6148e740-b101-cf26-f445-0b6dc190b39e
* Content: [Power BI enterprise deployment whitepaper - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/whitepaper-powerbi-enterprise-deployment)
* Content Source: [powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-powerbi-enterprise-deployment.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll update that article when new content is available.
