### ISSUE TITLE
Would this be a good place to mention the "export linked data" feature

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#4442]
Or at least link to it? Or is it too new as of this writing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nicheplayer. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello there - can you be more specific? Do you have a particular article in mind, and if so, please provide the link in your comments. Thanks.

**Comment by mihart** [comment]
Hi @nicheplayer,
I don't see an update to this Git issue, so I'm going to close it.  I did update some screenshots and added the new option for live connections.  Perhaps this was what you were referring to? 
All the best,
the DOCS team
