### ISSUE TITLE
Issue with permissions needs to be communicated

### ISSUE THREAD

**Issue by AndreaWestacott** [MicrosoftDocs/powerbi-docs#4444]
I have been struggling for weeks, trying to figure out why users of my Metrics scorecard could not save new check-ins.  Microsoft support haven't been able to help, and I could find nothing online.  The answer is buried in this page - metric-level permissions currently aren't working (although they used to work perfectly).  

It would have been so useful if you could have passed this on via your Power BI blog, or a support document, a "known issues" page, or something!  

I am finding it very hard to find any help in relation to Power BI Metrics online - searches, even the suggested documentation from support, always refer to **usage** metrics instead.   

Thanks for your time.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d4e10c5f-20a6-7f7b-8d1b-a5a5a9cb8a98
* Version Independent ID: 938f0c5e-9584-de7a-c564-f4788e7b5b34
* Content: [Get started with metrics in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-goals-introduction)
* Content Source: [powerbi-docs/create-reports/service-goals-introduction.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-goals-introduction.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @AndreaWestacott, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
