### ISSUE TITLE
cannot see drill through in the 2023 new PBI desktop

### ISSUE THREAD

**Issue by jowangkinetic** [MicrosoftDocs/powerbi-docs#4445]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jowangkinetic. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @jowangkinetic, thanks for reaching out. I am going to close this issue as I have already commented on  it here in another issue: https://github.com/MicrosoftDocs/powerbi-docs/issues/4429
