### ISSUE TITLE
Confusing CA Cert Setup

### ISSUE THREAD

**Issue by Darryl-G** [MicrosoftDocs/powerbi-docs#4446]
Hello,

On this page, it says:   _You can establish a trust relationship between a HANA server and the gateway IdP by signing the gateway IdP's X509 certificate with a root certificate authority (CA) that's trusted by the HANA server._

But then it goes on to establish a trust with the IdP certificate only.

I believe that there are some scenarios where a CA cert is useful, but normally just a self-signed cert is actually the simplest solution and would allow point-to-point trust.

Is there a recommended approach?   The page seems to confuse the two options i.e. creating a CA, but not trusting the CA certificate...

Many thanks

Darryl

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa7ca8d8-0f83-2cd6-57b1-04fc8e04981b
* Version Independent ID: 196ee3c3-aa88-f8ca-c725-33bf77be0db5
* Content: [Use Security Assertion Markup Language for SSO from Power BI to on-premises data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-saml)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-saml.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-saml.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Darryl-G. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
