### ISSUE TITLE
not possible to create calculated tables in directquery mode

### ISSUE THREAD

**Issue by DirkGubbels** [MicrosoftDocs/powerbi-docs#4448]
[Enter feedback here]

The documentation states it is possible to create a calculated table in DirectQuery mode. this is not possible. 
please adjust.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a23f1335-bb33-544a-67da-006015cfc92f
* Version Independent ID: 3e1dc63e-f0ac-5201-c0a5-bc7e4ee30944
* Content: [Using calculated tables in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-calculated-tables)
* Content Source: [powerbi-docs/transform-model/desktop-calculated-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-calculated-tables.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DirkGubbels. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look into your request and update the article as appropriate.
