### ISSUE TITLE
Add to Operation list

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4449]
Hello 

can we please ask the product owners to add two more operations to the list & its identifications whether it is a interactive operation or background operation?
[https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-interactive-background-operations#operation-list](url)

1. export to Excel / PDF / PPT
2. Analyze in Excel
Thank you.
Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e021f5ea-561c-0ff1-5bf3-a57f6cec28b3
* Version Independent ID: e021f5ea-561c-0ff1-5bf3-a57f6cec28b3
* Content: [Interactive and background operations in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-interactive-background-operations)
* Content Source: [powerbi-docs/enterprise/service-premium-interactive-background-operations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-interactive-background-operations.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
I started an email thread for this.
