### ISSUE TITLE
Administrators

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#445]
Can an office365 group be assigned as a gateway administrator? 
What kind of security group can be used? does it have to be a mail enabled, can it be from on-premises?
Please clarify this in the appropriate location above

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87176394-a2d4-7e3d-922e-d124d59fe9c5
* Version Independent ID: 99c3109b-b094-1300-86e2-0cebb4475169
* Content: [Manage a gateway for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-manage)
* Content Source: [powerbi-docs/service-gateway-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your question, @DeanGross.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by mgblythe** [comment]
Adding @arthiriyer to address the question.

**Comment by arthiriyer** [comment]
@DeanGross Yes, office365 groups can be added. The only known issue is that we cannot add security groups which are not email enabled.

@mgblythe FYI

**Comment by mgblythe** [comment]
Using an Office 356 account to install the gateway (and be the adminstrator of that gateway) is described in Install an on-premises data gateway (https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-install). Using security groups that require an email name is described in Manage gateway admins (https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-manage#manage-gateway-admins).
