### ISSUE TITLE
Considerations and limitations of Large datasets in Power BI Premium

### ISSUE THREAD

**Issue by rudzimj** [MicrosoftDocs/powerbi-docs#4451]
The first consideration on this page is out of date. It reads:

> **Download to Power BI Desktop:** If a dataset is stored on Premium Files, [downloading as a .pbix](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix) file will fail.

This is not the current behavior. The Power BI Service now supports [Download modes](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#download-modes), and one mode will be unavailable but the other mode will work.

![image](https://user-images.githubusercontent.com/36211641/230175142-4bdf925d-b2fb-45c7-b513-824dfda475c2.png)

Suggested update:

> **Download to Power BI Desktop:** If a dataset is stored on Premium Files, you will not be able to download a copy of your report and data as a .pbix, though you will still be able to download a copy of the report with a live connection to the data. See [Download modes](https://learn.microsoft.com/en-us/power-bi/create-reports/service-export-to-pbix#download-modes) for more details.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 246f0cce-9c53-3bea-15df-0fb7c8520f12
* Version Independent ID: aefc566c-9abf-1e4f-6d38-18a1e192fa23
* Content: [Large datasets in Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-large-models#enable-large-models)
* Content Source: [powerbi-docs/enterprise/service-premium-large-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-large-models.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rudzimj. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
HI @rudzimj,

I tried to recreate your scenario but from what I can see the documentation is correct, you cannot download a large model dataset in Power BI service. When you try, you get this error:
<img width="152" alt="image" src="https://user-images.githubusercontent.com/54834915/232395519-251096f7-286d-4ac2-8e1a-495f16f5d1e2.png">

Thanks for reporting this and for getting involved. If we hear from other customers that this is indeed the behavior we'll investigate further.

Thanks,

Kesem
