### ISSUE TITLE
Wrong label for Feb 2023 download & missing section for Jan 2023

### ISSUE THREAD

**Issue by luconsta** [MicrosoftDocs/powerbi-docs#4453]
Hello,

It seems that for February 2023 download there is a wrong label but hopefully the link is the correct one:
[February 2022 version of Power BI Desktop - 32-bit](https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup-2023-02.exe)
[February 2022 version of Power BI Desktop - 64-bit](https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup-2023-02_x64.exe)

Also there is a missing section for January 2023. From December 2022 it skips directly to February 2023.

Kind Regards,
Lucian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop&source=docs)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @luconsta. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out - fixed!

**Comment by davidiseminger** [comment]
Also - there was no update for January 2023, thus no entry.
