### ISSUE TITLE
Missing data source details such as directquery, gateway supported / required, ...

### ISSUE THREAD

**Issue by eerik47** [MicrosoftDocs/powerbi-docs#4454]
[Enter feedback here]
Hi,
it seems you remove details around data sources mainly details such as support for direct query, gateway supported / required, etc.
Please can you return.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comments about the gateway information on this page. DirectQuery information is provided in the table in the linked-to article on this page, in the Power Query docs. After an assessment from the engineering team about how best to ensure the gateway content is current and maintained, it was determined that information is best held in individual connector articles. I realize this isn't as convenient as a centralized table; we'll continue to assess whether such information can be aggregated and properly maintained centrally, in future updates.

**Comment by davidiseminger** [comment]
Apologies, the DirectQuery is not in the table, but in the individual connector articles.
