### ISSUE TITLE
Reference to Office 365 groups instead of Microsoft 365

### ISSUE THREAD

**Issue by RJBrower** [MicrosoftDocs/powerbi-docs#4456]
Row-level security (RLS) with Power BI > Working with members > Add members
"Note, however, that Office 365 groups aren't supported and can't be added to any roles."
Under the assumption that "Office 365" groups are now "Microsoft 365" groups, this should read something like:
"Note, however, that Microsoft 365 groups aren't supported and can't be added to any roles."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @RJBrower, thanks for reaching out. I've forwarded your comment on to the article owner. Thanks!

**Comment by mberdugo** [comment]
Thanks for pointing this out, @RJBrower. The article has been updated.
