### ISSUE TITLE
Missing table for DirectQuery, gateway, etc support

### ISSUE THREAD

**Issue by timplMSFT** [MicrosoftDocs/powerbi-docs#4457]
Unless I'm mistaken this table used to have a large grid that shows each Power BI data source and whether it supported import, DirectQuery, gateway, required a gateway, etc. This was very valuable information for me supporting customers who are constantly asking questions about various connectors. The article at https://learn.microsoft.com/en-us/power-query/connectors/ shows the list of data sources still but not whether they support DirectQuery, gateways, etc. Can you advise whether there is a new article where this information is at or whether it can be re-added to this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @timplMSFT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments about the gateway information on this page. The DirectQuery information is provided in that linked-to article, as one of the columns. After an assessment from the engineering team about how best to ensure the gateway content is current and maintained, it was determined that information is best held in individual connector articles. I realize this isn't as convenient as a centralized table; we'll continue to assess whether such information can be aggregated and properly maintained centrally, in future updates.

**Comment by davidiseminger** [comment]
Apologies - the DirectQuery is not in that table, but in the corresponding connector pages.

**Comment by timplMSFT** [comment]
Thanks David - I can understand the problem with maintaining this information in multiple places but the problem is many of the individual connectors do not have corresponding pages (like Cosmos DB, Netezza, and many popular 3rd party connectors) and most of those pages do not list information like whether a gateway is required and/or supported. I'd just give feedback that this table is very valuable information to keep in this article for those reasons if this decision is revisited in the future.

**Comment by timplMSFT** [comment]
I'd also add that this is very valuable information for customers that aren't looking for whether a specific connector supports DirectQuery and gateways but for those looking for a list of connectors that support DirectQuery and gateways. We're now telling them to go to various 3rd party documentation which may or may not have that information and if they do it won't be in a standardized format. It's an inconvenience that the table in this document helps them avoid and saves customers (and our support team) a lot of time.

**Comment by Mike-Honey** [comment]
I strongly agree with @timplMSFT - key information has been lost, not just made inconvenient to access.  For now I'm bookmarking the old version out of github and sharing with my users, but please reconsider the deletion of key information needed by your customers.
