### ISSUE TITLE
"Since Region is under the Filters on this page heading, all visuals on this page aren't displaying. The data from West and East regions are excluded." is not describing the situation of the snip above it and can confuse readers

### ISSUE THREAD

**Issue by MYE31** [MicrosoftDocs/powerbi-docs#4458]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1465b3a1-a6de-e2f3-154c-817ea13aa4f0
* Version Independent ID: 20ea6924-2307-d6ef-d601-7f949fe58944
* Content: [Tour the report Filters pane - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-report-filter)
* Content Source: [powerbi-docs/consumer/end-user-report-filter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-report-filter.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MYE31. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks - that excerpt is referring to the image directly following that paragraph, which reflects what that sentence says.
