### ISSUE TITLE
Implementing RLS on Paginated Report Connected to PBI Dataset

### ISSUE THREAD

**Issue by frost-s** [MicrosoftDocs/powerbi-docs#4459]
The article doesn't clearly specify if RLS implemented on the dataset will be applied to the Paginated report.

"This article explains how to set up row-level security (RLS) for paginated reports in Power BI. If your paginated report is based on a Power BI dataset, the article [Row-level security (RLS) with Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls) provides a solid background."

The above sentence at the start of the article only suggests the reader follow the link but doesn't specify if the RLS implemented on the dataset applies to the paginated report.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a958605e-1228-21ac-fbb1-75345a869cc6
* Version Independent ID: a958605e-1228-21ac-fbb1-75345a869cc6
* Content: [Set up row-level security in Power BI paginated reports - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-rls)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-rls.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @frost-s. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @frost-s. I'll clarify in the article.
