### ISSUE TITLE
Grouping when data comes from live connection to Analysis Services?

### ISSUE THREAD

**Issue by Liszet** [MicrosoftDocs/powerbi-docs#446]
We are unable to create groups when we have a live connection to Analysis Services. Is this expected behaviour? If yes, is it planned to be made available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1e0b0a-ff95-b2f7-44db-5c07ca876ab4
* Version Independent ID: 1c975595-bf44-5f66-3e08-02c3e8e63797
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Liszet, thanks for your comment. We’ve forwarded your feedback to the writer, who should respond soon. You might also try asking in the Power BI Community, https://community.powerbi.com. Thanks!

**Comment by mdiscenza** [comment]
@maggiesMSFT any update on this? I'd really like to know why we can't use grouping and have to do everything with measures with pushed datasets in the analytics service-- especially because I don't see this documented anywhere as a limitation.

**Comment by davidiseminger** [comment]
Thanks for your comment, @Liszet and @mdiscenza, and sorry for the delay. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
