### ISSUE TITLE
Invalid data structure for example

### ISSUE THREAD

**Issue by jamilscott** [MicrosoftDocs/powerbi-docs#4460]
The columns in table1 appear to have changed.  I pasted the query into power BI but all values were errros.  I checked the query against the structure of table1 and the columns in the query are not in the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data?source=recommendations)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jamilscott. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Sorry you're having trouble with this, we've tested these steps and they work properly in our tests.
