### ISSUE TITLE
Microsoft Support has stated that Azure AD security groups are not supported by Power BI workspaces.

### ISSUE THREAD

**Issue by Darian-FRB** [MicrosoftDocs/powerbi-docs#4461]
Our Power BI administrators were not able to add Azure AD security groups to Power BI workspaces using the web interface. Microsoft Support stated that groups must be Microsoft 365 groups for use with Power BI workspaces.

Microsoft Support Case #35611349

Please update or clarify support for Azure AD security groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5db2f3b5-305f-2803-012a-04154b58acb2
* Version Independent ID: 3bf41b0d-cd66-9782-1d2c-d1d79319048c
* Content: [Give users access to workspaces - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-give-access-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-give-access-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-give-access-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Darian-FRB. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi @Darian-FRB -- Checking with the product team. I'll reply and update the article if appropriate. Thanks!

**Comment by maggiesMSFT** [comment]
Him @Darian-FRB -- the product team says Azure AD security groups are supported. Are your Power BI admins still having issues?

**Comment by Darian-FRB** [comment]
> Hi @Darian-FRB -- the product team says Azure AD security groups are supported. Are your Power BI admins still having issues?

Based on previous information from Microsoft, my organization is instructing users to only use M365 Groups with Power BI and that Azure AD security groups are not supported. I am investigating the original statement from Microsoft that only M365 Groups and not Azure AD security groups are supported.

**Comment by Darian-FRB** [comment]
I have had my users confirm that when attempting to grant permissions to Power BI workspaces using groups that they can find and select M365 Groups and Azure AD groups that have been mail enabled. Azure AD security groups without mail addresses do not appear and cannot be entered.

We have separate informal guidance from Microsoft that Azure AD security groups need to be mail enabled upon creation for use as security groups with Exchange Online. There may be a common quirk/bug/requirement.

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
