### ISSUE TITLE
Wrong Attendee kit after december 2022 update

### ISSUE THREAD

**Issue by R1k91** [MicrosoftDocs/powerbi-docs#4466]
after priad update to december 2022 release (at the time of writing)
attendee localized kit is wrong:
- docx instead of pdf
- only documents not solutions 
![image](https://user-images.githubusercontent.com/57228476/231437896-c7776fa5-85ae-4397-8291-6e897df6de9a.png)

- mysolution, presentation, setup folders are missing

![image](https://user-images.githubusercontent.com/57228476/231438022-1f6c2d38-965a-44ca-bdea-a1f61e4946ea.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0439d49-76b1-380b-f226-317e96ca0397
* Version Independent ID: 2dd9f620-5244-936f-76f9-1f32f5ac5a23
* Content: [Power BI Paginated Reports in a Day course - Power BI](https://learn.microsoft.com/en-us/power-bi/learning-catalog/paginated-reports-online-course)
* Content Source: [powerbi-docs/learning-catalog/paginated-reports-online-course.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/learning-catalog/paginated-reports-online-course.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @R1k91. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Assigning to the right writer for that type of content.

**Comment by ajburnle** [comment]
I removed the assignment. I don't own paginated reports @davidiseminger

**Comment by davidiseminger** [comment]
Hi Maggie - might not be you, but dealing with paginated reports. If not you, maybe you know someone who could fix?

**Comment by maggiesMSFT** [comment]
Hi, @R1k91 -- Hoping to find the current owner of this content. I'll let you know.

**Comment by davidiseminger** [comment]
Thanks, it appears this issue has been resolved.
