### ISSUE TITLE
Confusing text, "When you want the data in your Power BI report and in your Report Builder report to be the same, "

### ISSUE THREAD

**Issue by jbruneFei** [MicrosoftDocs/powerbi-docs#4468]
What is a _Report Builder report _?  And as far as I know there are two types of Power BI reports, Standard and Paginated.  Which Power BI report type is it referring to here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed0cd82d-e7c4-4b5b-700f-1152a2a6bf38
* Version Independent ID: b2d4aeb5-1a98-ad43-4cf6-9539d9073600
* Content: [Create a paginated report based on a Power BI shared dataset - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/report-builder-shared-datasets)
* Content Source: [powerbi-docs/paginated-reports/report-builder-shared-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/report-builder-shared-datasets.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @jbruneFei --
Thanks for the question! You're right, it's a paginated report. Making the update now. Change should be live this afternoon.
