### ISSUE TITLE
Replace the screenshot showing high-contrast mode

### ISSUE THREAD

**Issue by mlongoria** [MicrosoftDocs/powerbi-docs#4469]
The report shown in a high-contrast view contains a map, but there are no data points shown on the map. It's a poor example of high contrast as the map is all low-contrast with no data. Please replace the map with another map or other visual that does show data in high contrast. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a040fd91-bc39-f1f7-b5bf-1a2964e7067e
* Version Independent ID: 1dd198ca-08a2-022b-a186-70f355882821
* Content: [Overview of accessibility in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-overview)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-accessibility-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mlongoria. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your comment, we'll look into replacing that visual.
