### ISSUE TITLE
Adding a link to PowerBI Playground would be nice !

### ISSUE THREAD

**Issue by JulienFJaji** [MicrosoftDocs/powerbi-docs#4471]
Hi everyone,

I was asking for help when a link to **PowerBI Playground** was sent to me by the Microsoft support 
=> [https://playground.powerbi.com/en-us/](https://playground.powerbi.com/en-us/)
This would certainly help to have a small word about this on this page.

Best Regards,
Julien

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54016cab-2de5-0d30-2dfa-ee386dcfb881
* Version Independent ID: 4e464b91-bc16-270d-cd51-9bfa396c0326
* Content: [Embed content in your Power BI embedded analytics application - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-customers?tabs=net-core)
* Content Source: [powerbi-docs/developer/embedded/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-sample-for-customers.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your suggestion, @JulienFJaji 
I'll add a sentence about the playground in the "Developing your app" section.
