### ISSUE TITLE
Unclear explanation of RLS application

### ISSUE THREAD

**Issue by filipalai** [MicrosoftDocs/powerbi-docs#4472]
In the first paragraph on this page it says:
_"Row-level security (RLS) with Power BI can be used to restrict data access for given users. Filters restrict data access at the row level, and you can define filters within roles. In the Power BI service, users with access to a workspace have access to datasets in that workspace. **RLS only restricts data access for users with Viewer permissions**. It doesn't apply to Admins, Members, or Contributors."_

Imho, this is an unclear/incomplete description. I think it could be worth clarifying that:
- If the permission is _App_ (with or without (Build etc) additions), RLS is also applied.
- If users/groups are only given access to an app, they must be added to a Role to be able to view the reports in the app. There is no other way to circumvent the RLS in that case, even if RLS should not be applied to that specific user/group.
- The RLS also applies to users implicitly given access through AD groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @filipalai, thanks for your comment. I am forwarding it on to the content developer who is maintaining that doc for further consideration.

**Comment by mberdugo** [comment]
Thanks for your suggestion, @filipalai. I’ll add this request to our docs backlog.
