### ISSUE TITLE
help - about licences 

### ISSUE THREAD

**Issue by ThomasD60** [MicrosoftDocs/powerbi-docs#4473]
Hi

I would like to update my Power BI data via the REST API, do I need a special license?

Thx

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ThomasD60. This issue has been assigned to the doc author for review.

**Comment by ThomasD60** [comment]
hi , the question is still up .

**Comment by KesemSharabi** [comment]
Hi @ThomasD60,

You don't need a special license to use the[ Power BI REST APIs](https://learn.microsoft.com/en-us/rest/api/power-bi/). However, some of the actions you might want to take may need a license. In such cases, the APIs will not work.

You can find a more information in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
