### ISSUE TITLE
Require clarity on granular permissions section

### ISSUE THREAD

**Issue by nachiketkmaat** [MicrosoftDocs/powerbi-docs#4474]
Link: https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions#more-granular-permissions

`All users who already have Read permission for datasets via app permissions, sharing, or workspace access also get Build permission for those datasets.`

This statement needs more context. Please can you review because it is very confusing.

For example- when I publish an app, then it automatically gives the audience read permission to the dataset. But there are separate option for reshare and build permisisons. Only read doesn't automatically give build permission as the above quote from the documentation suggests. Please can this be better explained.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nachiketkmaat. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @nachiketkmaat , thanks for reaching out on this. I agree with you and am following up with the product team. I'll update the docs when I get more clarity from them. Thanks!
