### ISSUE TITLE
When user assigned to many groups the RLS does not work

### ISSUE THREAD

**Issue by akangsha1221** [MicrosoftDocs/powerbi-docs#4477]
When a user is assigned to many groups the RLS does not propagate and work properly. (reference Case Id
2302280050001493) 

<img width="317" alt="image" src="https://user-images.githubusercontent.com/100001295/232184685-e76e4c1d-45b0-415f-b553-a1c1ce533fe4.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @akangsha1221. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi. @akangsha1221, thanks for your comment, and sorry for the delayed response. Do you know if there's a maximum number of groups the use can be in, or is it just more than one?

**Comment by mberdugo** [comment]
Hi, @akangsha1221. RLS is additive, I'll add a sentence in the doc to that effect. Thanks.
