### ISSUE TITLE
Update feature title

### ISSUE THREAD

**Issue by itsnotaboutthecell** [MicrosoftDocs/powerbi-docs#4479]
[Enter feedback here]

DirectQuery for Power BI datasets and AS (preview) is now generally available and the title has changed, can we please update this limitation to the correct feature title:

GA announcement: https://powerbi.microsoft.com/en-us/blog/announcing-general-availability-for-composite-models-on-power-bi-datasets-and-analysis-services-models/

Limitation:
"You can't create parameters in live connection data sources without a local model. However, if you use DirectQuery for Power BI datasets and AS (preview), you can add a local model to create field parameters. For more information about using DirectQuery for live connections, see [DirectQuery for Power BI datasets and AS (preview)](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-datasets-azure-analysis-services#using-directquery-for-live-connections)."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Version Independent ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Content: [Let report readers use field parameters to change visuals (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters)
* Content Source: [powerbi-docs/create-reports/power-bi-field-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-field-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @itsnotaboutthecell. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @itsnotaboutthecell, do you know the correct current feature name? Is it the same, except without (preview), or is it "Composite models on Power BI Datasets and Analysis Services models, as in the blog title?

**Comment by paulinbar** [comment]
Hi @itsnotaboutthecell, I've opened a work item about this and will make any necessary updates. Thanks for the comment. Closing this issue now.
