### ISSUE TITLE
App Workspace with Premium capacity allocated

### ISSUE THREAD

**Issue by Ventilios** [MicrosoftDocs/powerbi-docs#448]
The documentation is stating the following: "Everyone you add to an App Workspace needs a Power BI Pro license.". From my understanding, an App Workspace that was allocated with premium capacity would also have the ability to share their dashboards and reports with consumers in a free tier. Is that correct? If yes, please highlight this in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54452a1b-613f-5718-a6bd-16429fdfc678
* Version Independent ID: 3352343d-b326-4f63-5c37-51403d8f6358
* Content: [Create workspaces with your colleagues in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-workspaces#feedback)
* Content Source: [powerbi-docs/service-create-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by markingmyname** [comment]
@Ventilios Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @Ventilios -- apologies for the delay! I too have heard similar remarks from others. 
Here's the answer from the product team:

If a user want to browse to the workspaces and view items in it, they need a Pro license.
If you want to distribute content from a workspace to others, you have the following options:
1.	Give them a pro license, then give them access to the workspace, share the item, or publish an app to them
2.	Put the workspace in premium, then share the item or publish an app containing the item.

Confirms what is stated in the article. 
Hope that helps!
