### ISSUE TITLE
Second serverless SQL "pool"-> Second serverless SQL "database"

### ISSUE THREAD

**Issue by fumi11** [MicrosoftDocs/powerbi-docs#4480]
Hi Team,

I believe  Second serverless SQL "pool" should be  Second serverless SQL "database"

![image](https://user-images.githubusercontent.com/102130723/232513567-aaadb608-c0e5-4a32-9623-da4c694592fd.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b22276bb-dce9-9f59-fe03-1359a401afbb
* Version Independent ID: b22276bb-dce9-9f59-fe03-1359a401afbb
* Content: [Power BI modeling guidance for Power Platform - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-modeling-guidance-for-power-platform#create-a-second-serverless-sql-pool)
* Content Source: [powerbi-docs/guidance/powerbi-modeling-guidance-for-power-platform.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-modeling-guidance-for-power-platform.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mscottsewell** [comment]
+1 - This change should reduce confusion.

**Comment by ShettyGaneshprasad** [comment]
Suggested changes is correct. As we cannot create 2nd serverless SQL pool
