### ISSUE TITLE
Quick measure suggestions and example workbook

### ISSUE THREAD

**Issue by FRFR-LO** [MicrosoftDocs/powerbi-docs#4481]
Hello,

I'd like to know if the examples listed [here](https://learn.microsoft.com/en-us/power-bi/transform-model/quick-measure-suggestions#optional-filters-1) and [there](https://learn.microsoft.com/en-us/power-bi/transform-model/quick-measure-suggestions#count-of-rows) are intended to be used with the example workbook provided [here](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-quickstart-learn-dax-basics#example-workbook).

Because I don't see "Word" in the products... of the example workbook. Or did I get it wrong, and "Word" does not mean "Microsoft Word" here?

![image](https://user-images.githubusercontent.com/125807698/232726625-74f45755-cc48-44ff-844e-8fefd2b1fd3a.png)

For instance, does "sales table" refer to the table titled "Sales" in the example workbook?

![image](https://user-images.githubusercontent.com/125807698/232726971-57012b58-ed9d-4ea6-b44d-c50ad30e8b01.png)

Best regards,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf7765d5-5166-ea69-65af-2c912f2b44da
* Version Independent ID: cf7765d5-5166-ea69-65af-2c912f2b44da
* Content: [Quick measure suggestions - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/quick-measure-suggestions#natural-language-examples)
* Content Source: [powerbi-docs/transform-model/quick-measure-suggestions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/quick-measure-suggestions.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by paulinbar** [comment]
Hi François, thanks for reaching out. I am forwarding your questions along to the doc author for consideration. If the items you referred to do indeed relate to the sample file you mentioned, that should be pointed out explicitly in the article. I am not sure that it does relate however. In any event, as I said, I'll ask the doc author.
@Sujata994, can you answer?
