### ISSUE TITLE
Aggregations with detail table in dual mode

### ISSUE THREAD

**Issue by akangsha1221** [MicrosoftDocs/powerbi-docs#4482]
what does be the expected behavior for creation of aggregations with detail table in dual mode?
Can the document be updated as part of the validations section to reflect that. (Support case # 2304120050002506)
As the customer has found a workaround to create Aggregations with a Detail Table in Dual mode and want to check if this a gap.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [User-defined aggregations - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/aggregations-advanced#validations)
* Content Source: [powerbi-docs/transform-model/aggregations-advanced.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/aggregations-advanced.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @akangsha1221. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
Clearing backlog. This issue will not be addressed.
