### ISSUE TITLE
The first step from the section 'Option B: Resource-based Kerberos constrained delegation' is not correct.

### ISSUE THREAD

**Issue by omeuid** [MicrosoftDocs/powerbi-docs#4484]
Hi,

The first step in the section 'Option B: Resource-based Kerberos constrained delegation' indicates:

```
1. Use the Active Directory Users and Computers MMC snap-in on the domain controller for the ContosoFrontEnd domain and verify no delegation settings are applied for the gateway service account
```

Based on my experience performing some tests with the gateway and the target service in different domains, this statement is wrong. 
* As I understand (and the only way that I could make this scenario work), the gateway service account must be configured with `Standard Kerberos constrained delegation ` before configuring `Resource-based constrained delegation ` into the target service account.
    * Instead of selecting the `Do not trust this user for delegation ` option, which is the order of this step. 
* Also, the screenshot should be updated too.

Please, correct me if some of the statements are not right.

Regards,
Carlos

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Configure Kerberos-based SSO from Power BI service to on-premises data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @omeuid. This issue has been assigned to the doc author for review.

**Comment by ms-kgorgi** [comment]
Hi Carlos, given this statement:

`As I understand (and the only way that I could make this scenario work), the gateway service account must be configured with Standard Kerberos constrained delegation  before configuring Resource-based constrained delegation  into the target service account.`

Likely the gateway is not doing Resource-based constrained delegation but Standard constrained Kerberos delegation. We have had customers in the past successfully use Resource-based constrained delegation using the steps in the documentation.

Unfortunately, setting up gateway sso in a multiple domain scenario is complicated given the variety of possible Active Directory deployments. Therefore, if you are having difficulties, I recommend you reach out to PBI support to troubleshoot your specific issues.

**Comment by omeuid** [comment]
Hi @ms-kgorgi,

Some details regarding your comment:

> Likely the gateway is not doing Resource-based constrained delegation but Standard constrained Kerberos delegation. We have had customers in the past successfully use Resource-based constrained delegation using the steps in the documentation.

First, My testing environment was built using two domains created with two Active Directory 2019 (with its default functional level). 

As I understand Standard constrained delegation cannot be done between accounts of different domains. So, could you explain why you think that?

Also, If Resource-base constrained delegation can be configured using those steps, could you provide some details about an environment where those steps could be followed without any issue?

> Unfortunately, setting up gateway sso in a multiple domain scenario is complicated given the variety of possible Active Directory deployments. Therefore, if you are having difficulties, I recommend you reach out to PBI support to troubleshoot your specific issues.

Sorry if my explanation was not clear enough, I was able to configure PowerBI gateway correctly but not following your documentation, which seems to be wrong (at least for my scenario with two Windows Server 2019 domains).

Regards,
Carlos

**Comment by ms-kgorgi** [comment]
Hi @omeuid, 

Standard delegation can be used depending on the trust relationship of the domains. One quick way to test is remove the Resource-based settings and checking if your scenario still works. If it still works, then you are using Standard delegation.

Regards,
Kian
