### ISSUE TITLE
Unable to create alert directly from dashboard

### ISSUE THREAD

**Issue by sumitburnwal** [MicrosoftDocs/powerbi-docs#4485]
[Enter feedback here]
The "manage alert" option is appearing only after a certain visual is pinned to an independent dashboard. It does not work directly from dashboard page. Can you please check?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-set-data-alerts)
* Content Source: [powerbi-docs/create-reports/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @sumitburnwal, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for your question. Checking it out.
