### ISSUE TITLE
Adding more clear hints on KPI Card Troubleshooting

### ISSUE THREAD

**Issue by federicoco** [MicrosoftDocs/powerbi-docs#4486]
I think that Troubleshooting paragraph on that page has been written in a poor way.
I would like to add that if by any means, your KPI card does not show Trend Axis Line is either because 1) your column in Value has a null and is not continuos or, 2) the trend axis is not continuos or has a null value.
There should be more hints about troubleshooting why your kpi card does not show trend axis line in correct way.
Learned that after 2 days of debugging. At least online documentation should be wrote from peoples that knows PowerBI 100x times more than me 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [Key Performance Indicator (KPI) visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-kpi?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-kpi.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @federicoco. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @federicoco, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
