### ISSUE TITLE
Power BI Service ->In the Dataset page, Refresh now is not available. Ribbon on the Top is missing.

### ISSUE THREAD

**Issue by dhanishreddy** [MicrosoftDocs/powerbi-docs#4488]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a72e523-2194-f53c-9a27-abf960e77851
* Version Independent ID: bdc43737-adc5-b7bf-245e-e065a1478566
* Content: [Configure scheduled refresh - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-scheduled-refresh)
* Content Source: [powerbi-docs/connect-data/refresh-scheduled-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-scheduled-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dhanishreddy. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we'll look into updating or clarifying this page.
