### ISSUE TITLE
Confused about wording

### ISSUE THREAD

**Issue by suetholen** [MicrosoftDocs/powerbi-docs#4489]
[Enter feedback here]
Paragraph 2 says "After you attach your dataflow, "  - I see no prior reference to attaching a dataflow and am not at all clear on what exactly one would "attach it to". I'm not sure what that means.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57f28e6c-a22d-484b-6599-9b17e6c011f0
* Version Independent ID: 307cb997-5d54-a43c-f278-5247769e682b
* Content: [Configuring dataflow storage to use Azure Data Lake Gen 2 - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-azure-data-lake-storage-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-azure-data-lake-storage-integration.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @suetholen. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello there -- the article is about attaching your dataflow to ADLS Gen 2 (Azure Data Lake Storage), so it's referencing attaching it to your ADLS Gen 2 account / subscription.
