### ISSUE TITLE
Ability to Group By Defined Ranges

### ISSUE THREAD

**Issue by kcinmelbourne** [MicrosoftDocs/powerbi-docs#449]
This feature is fantastic but doesn't quite offer the flexibility that I've seen elsewhere.  For example, in your example above, you allow to Bin by a range such as months.  Where there isn't a logical data set like dates, such as a simple Whole Number field, it would be great if you could group by set ranges.  I suppose it would be similar to the rules in conditional formatting.

In my instance, it would allow us to create a hierarchy of projects codes. Eg 10000-15000 = Portfolio A, 15001 - 20000 = Portfolio B.

Often people are using DAX to calculate bands for ranking their data. This suggestion could also be used to make such groupings easier to Manage. For example, applying the banding to a % Profit field you could group 0 - 30% = Low Profit Customers, 31%- 60% = Mid Profit Customers etc. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1e0b0a-ff95-b2f7-44db-5c07ca876ab4
* Version Independent ID: 1c975595-bf44-5f66-3e08-02c3e8e63797
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-grouping-and-binning.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@kcinmelbourne Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by kitobotucatu** [comment]
Good Morning, I think that this flexibilities and dinamismi is important in this case, example, I need to classify the range, <0 = delay; >=0 e <=30 = next; >30 = futuro.

**Comment by jakeyu22** [comment]
Is there no current way in Power Bi to create custom bins as in kcmelbourne's example? Seems like a fairly simple request

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
