### ISSUE TITLE
Document not up to date with premium gen 2 properties

### ISSUE THREAD

**Issue by martaequintao** [MicrosoftDocs/powerbi-docs#4490]
Most of these properties in this page no longer exist in Gen 2 premium and this is raising some customer confusion. Can this document be reviewed an updated to be more up to date with Gen 2 please?

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads?tabs=gen1)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
I followed this up with an email.
