### ISSUE TITLE
Possibly unneccessary post now

### ISSUE THREAD

**Issue by rosscouldrey** [MicrosoftDocs/powerbi-docs#4491]
This post was created when the service tags for PowerBI were not available in the Azure Portal and required users to enable access to PowerBI through scripting.

However, since this post has been up, the Azure portal has been updated (as has SQL MI) and now this documentation is available through SQL MI docs. 

Specifically: 

1) You can now enable access from Azure services to enable connection from PowerBI as demonstrated here: https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/instance-create-quickstart?view=azuresql#networking-tab

2) You can use the Portal to create your NSG rule and select PowerBI service tags from the drop down.
https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/public-endpoint-configure?view=azuresql#allow-public-endpoint-traffic-on-the-network-security-group

thanks,
Ross

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01cad641-4e21-029b-3413-9e8b1de5ddbe
* Version Independent ID: 01cad641-4e21-029b-3413-9e8b1de5ddbe
* Content: [Use service tags with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-service-tags)
* Content Source: [powerbi-docs/enterprise/service-premium-service-tags.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-service-tags.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @rosscouldrey
* Microsoft Alias: **rocould**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rosscouldrey. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
HI @rosscouldrey, thanks for pointing this out. I will consult with the Fabric/Power BI team to see whether we need to update our documentation. Closing this issue now. Thanks again!
