### ISSUE TITLE
What about the Power Automate Environment - Selector

### ISSUE THREAD

**Issue by zuerichris** [MicrosoftDocs/powerbi-docs#4493]
Hi, when can I expect to be able to use a Power Automate Flow from a not default environment?

_The visual will only display flows within your default environment. We plan to add support for an environment selector by the general availability release.)_

Thanks
Christian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de472a84-f62c-d01c-a8b2-e6ea168a222d
* Version Independent ID: da8c0056-7e3d-fc14-c5a4-1bd3bab573de
* Content: [Create a Power Automate visual for Power BI (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-automate-visual?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/power-bi-automate-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-automate-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zuerichris. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
@maggiesMSFT gentle ping... :)

**Comment by maggiesMSFT** [comment]
Hi, @zuerichris -- sorry for the delay! This is a question for the product team, not the docs team. You can submit your question here:
https://ideas.fabric.microsoft.com/
