### ISSUE TITLE
Power BI API - Swagger/OpenAPI

### ISSUE THREAD

**Issue by fransf-wtax** [MicrosoftDocs/powerbi-docs#4495]
I cannot find a link (or the file itself) with the formal (Swagger/OpenAPI) specification of the Power BI (embedded) REST API.

I would expect to find this on https://learn.microsoft.com/en-us/rest/api/power-bi/ since most of this, I imagine, would have been generated from such a specifcation.

Can this link (and the specification itself) be added?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fransf-wtax. This issue has been assigned to the doc author for review.

**Comment by harrisony** [comment]
@fransf-wtax you'll find it's hidden away here https://github.com/microsoft/PowerBI-CSharp/blob/master/sdk/swaggers/swagger.json

**Comment by fransf-wtax** [comment]
@KesemSharabi We keep an inventory of external services we integrate with on our team's intranet. We like to have a standardized API spec with each external service's entry in this inventory; OpenAPI/Swagger is the de facto standard for REST API specifications. This way our team has an unambiguous point of reference for the API. 

Also there is quite some tooling out there that can generate stubs for various programming languages out of an OpenAPI spec. 

So all in all, it's good to have.

**Comment by KesemSharabi** [comment]
Hi @fransf-wtax,

You can get this info from the public repo - [PowerBI-CSharp](https://github.com/microsoft/PowerBI-CSharp). Here's a direct link - [swagger.json](https://github.com/microsoft/PowerBI-CSharp/blob/master/sdk/swaggers/swagger.json).

Thanks,

Kesem

**Comment by harrisony** [comment]
@KesemSharabi could we get an openapi/swagger file for the fabric APIs too?
