### ISSUE TITLE
not correct

### ISSUE THREAD

**Issue by NBK-PowerBI** [MicrosoftDocs/powerbi-docs#4496]
This article makes it seem as if the CSV data will automatically be updated, but it isn't, not by just uploading the report.  If having this document online it should be updated to explain how the data gets updated as in Adams video below .  This is the same for any file on OneDrive, including CSV, and Excel files 

https://www.youtube.com/watch?v=CYSMZxaXNLk

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc35788c-900b-1902-db56-c38ae1fd7bf2
* Version Independent ID: 7f045fe8-3ac6-29ae-10c5-69e7564dcbe5
* Content: [Refresh a dataset created from a .csv file on OneDrive - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-csv-file-onedrive)
* Content Source: [powerbi-docs/connect-data/refresh-csv-file-onedrive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-csv-file-onedrive.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @NBK-PowerBI. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! I've updated the article, it will go live with updates in the next day or so. Thanks!
