### ISSUE TITLE
Page is Out of Date, screenshots don't match production

### ISSUE THREAD

**Issue by NickDorak** [MicrosoftDocs/powerbi-docs#4497]
This page is out of date, warning that Migration paused, but link to details shows resolved last month. 

The screenshots in this page do not match what is seen in production. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 670c13f1-8741-24e9-c754-d7ac45fbe8be
* Version Independent ID: 45e02065-2360-3a34-e6a9-1a7223ee7bc3
* Content: [Move Power BI between regions - Power BI](https://learn.microsoft.com/en-us/power-bi/support/service-admin-region-move)
* Content Source: [powerbi-docs/support/service-admin-region-move.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/support/service-admin-region-move.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by kfollis** [comment]
Thanks for the feedback, @NickDorak! I'll check for needed updates and republish. Appreciate the awareness.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @NickDorak. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
The article is now updated. Thanks for the heads up @NickDorak!
