### ISSUE TITLE
Provided R code in the sample does not work

### ISSUE THREAD

**Issue by Rich-at-Chester-Business-Analytics** [MicrosoftDocs/powerbi-docs#4498]
The provided R code has bugs.  The missing data is not provided by using MICE, and the new column is not added to the output as the column name is misspelled in the script.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Rich-at-Chester-Business-Analytics. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. We've fixed the code (and added a couple screen shots) to make it all work. Thanks!
