### ISSUE TITLE
Page needs updating New visuals - where do we turn on Drill through cross report

### ISSUE THREAD

**Issue by BobCreamer** [MicrosoftDocs/powerbi-docs#4499]
Page needs updating New visuals - where do we turn on Drill through cross report?

The Visuals pane no longer exists.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70cc0df0-14a7-079d-c32c-78fff8aef03f
* Version Independent ID: ff23bd8e-3901-3010-af39-19fb69f2fa6c
* Content: [Use cross-report drillthrough in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-cross-report-drill-through?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-cross-report-drill-through.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-cross-report-drill-through.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @BobCreamer, can you provide a bit more detail? When you say the Visuals pane no longer exists, do you mean the Visualizations pane? I still see that pane, and I see a cross-report toggle. Is this what you were referring to? In any event, I am closing this issue now, but please feel free to reopen it if you are still having problems and can provide more detail. Thanks!
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/54644589/f6101bb2-08db-4baf-8da3-faa68ca150fb)
