### ISSUE TITLE
Typo? 

### ISSUE THREAD

**Issue by jhauff77060** [MicrosoftDocs/powerbi-docs#450]
The 2nd paragraph of this document states "... visual that shows Sales Amount by Year and Country."; I believe it should state "... visual that shows Sales Amount by Year and Quarter".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216c87b1-d196-a091-048c-dc55b0649338
* Version Independent ID: f8bb7489-d0bd-58f0-9eb3-6471d4d57eab
* Content: [Use insights in Power BI Desktop to explain increases and decreases in visuals (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-insights)
* Content Source: [powerbi-docs/desktop-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @jhauff77060 -- Good eye! I believe you are correct. Assigning to the author, who should respond soon, though probably after the holiday. 
Did you know: For minor things like typos, you can edit the doc yourself!  Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.
Thanks again!

**Comment by jhauff77060** [comment]
Thanks I did know about the edit option. 👍

**Comment by maggiesMSFT** [comment]
Great -- feel free to make use of it when you find typos and possible typos. The author can always close it without accepting it, with an explanation, so you won't hurt anything. Thanks again!

**Comment by davidiseminger** [comment]
You're right, @jhauff77060 ! Thanks for the close read - I've fixed that, the update should go out in the next day or so. Thanks!
