### ISSUE TITLE
Scheduled refresh attempts under dedicated capacity

### ISSUE THREAD

**Issue by BeantechStrizzolo** [MicrosoftDocs/powerbi-docs#4501]
The documentation specifies that scheduled refreshes are disabled when they fail four consecutive times.

![image](https://user-images.githubusercontent.com/63155123/235670860-abc59666-2f88-4240-9e5b-b46ef124015f.png)

However, if the dataset resides in a workspace under Embedded capacity with capacity switched off, at the *first* attempt (which obviously returns an error since the capacity is switched off) the scheduled refresh is *immediately* disabled.

![image](https://user-images.githubusercontent.com/63155123/235674964-35d89de9-7159-487f-b27c-92d779a97da8.png)
Is this behavior intended or is it missing from the documentation?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshoot refresh scenarios - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BeantechStrizzolo. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! I've updated the article, it will go live with updates in the next day or so. Thanks!
