### ISSUE TITLE
recommended version is not working correctly 

### ISSUE THREAD

**Issue by serva07** [MicrosoftDocs/powerbi-docs#4502]
[Enter feedback here]
The requirement is: Current Python runtime: Python 3.7.7. numpy 1.21.6 Customer installed the same versions as mentioned in the document, but it is failing with the below error: File "C:\Users\User\PythonScriptWrapper_6cf37a27-b0d1-401a-8715-831784775b22\PythonScriptWrapper.PY", line 2, in import os, pandas, matplotlib File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\__init__.py", line 16, in raise ImportError( ImportError: Unable to import required dependencies: numpy: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE! Importing the numpy C-extensions failed. This error can happen for many reasons, often due to issues with your setup or how NumPy was installed. We have compiled some common reasons and troubleshooting tips at: https://numpy.org/devdocs/user/troubleshooting-importerror.html Please note and check the following: * The Python version is: Python3.9 from "C:\ProgramData\Anaconda3\python.exe" * The NumPy version is: "1.20.3" and make sure that they are the versions you expect. Please carefully study the documentation linked above for further help. So, after installing the version Python 3.9 and NumPy 1.20.3, the issue got resolved.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db4f2779-18a0-100c-dc5f-ac0f77f05d19
* Version Independent ID: e6654e84-bba6-8280-645a-5e56e999276e
* Content: [Learn which Python packages are supported - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-python-packages-support#requirements-and-limitations-of-python-packages)
* Content Source: [powerbi-docs/connect-data/service-python-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-python-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by otarb** [comment]
What's the issue here? Those are versions currently supported in the service and working as expected. 

When using Python within PowerBI desktop, user's environment is used, and they have completely control over packages and their versions. Any compatibility issues on desktop are user's responsibility. 

Initially you mention customer installed same versions, but later from error message is says installed numpy version is 1.20.3, please double-check you are using correct python installation during setup and consumption.
