### ISSUE TITLE
Suggested detail to add to the considerations & limitations section

### ISSUE THREAD

**Issue by alan-at-microsoft** [MicrosoftDocs/powerbi-docs#4503]
It's not crystal clear whether the dataset scale-out setting is altered or removed when a .pbix file is re-deployed from PBI desktop, overwriting an existing scale-out enabled dataset. 

After testing, scale-out does not appear to be altered in any way when re-publishing, however stating this in the docs could save the audience a lot of time :)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alan-at-microsoft. This issue has been assigned to the doc author for review.

**Comment by alan-at-microsoft** [comment]
When my comment was originally made, I didn't see this information in any of the PBI scale-out docs. For example:

https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out#considerations-and-limitations

**Comment by KesemSharabi** [comment]
Hi @alan-at-microsoft,

Thank you for your suggestion and for explaining which document you're referring to. As you stated, a republished PBIX doesn't break scale-out, therefore, I see no need to document an expected behavior that doesn't break the anything.

Thanks,

Kesem
