### ISSUE TITLE
New Workspaces no longer allow users other than the "dataset owner" to refresh the dataset

### ISSUE THREAD

**Issue by alhughes8** [MicrosoftDocs/powerbi-docs#451]
In the old workspaces, as long as a user was an admin of that workspace, they could refresh a dataset that was not owned by them. It appears that the new workspaces no longer allow this. Only the "dataset owner" can refresh the dataset. Is this intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by markingmyname** [comment]
@alhughes8 Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @alhughes8 -- this shouldn't be the case. If this is still an issue, please post it in the Power BI community, https://community.powerbi.com/ or in support, https://powerbi.microsoft.com/en-us/support/. 
thanks!
