### ISSUE TITLE
Please reinstate table of datasources, for crucial columns on whether a gateway is supported and/or required

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#4512]
The main use of this page previously were the tables that listed all the datasources with the crucial information about whether a gateway is supported and/or required. Customers need this info to assess and plan new projects integrating Power BI with new data sources.  The linked page for Power Query content and sub-pages for individual connections do not contain this info in any form.

Please re-instate this table or re-create it on another page.

Here's the final version of this page I could find with the tables intact.

https://github.com/MicrosoftDocs/powerbi-docs/blob/0ec176053b43ced1cecc73dc97394963372239e6/powerbi-docs/connect-data/power-bi-data-sources.md

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment -- I've passed along your request to engineering, which decides which information we maintain for public purposes.
