### ISSUE TITLE
Can you please link to the page that displays the Power BI connectors and the available connection types?

### ISSUE THREAD

**Issue by llarkan** [MicrosoftDocs/powerbi-docs#4515]
[Enter feedback here]
Hi! At the bottom of the page (https://docs.microsoft.com/en-us/power-bi/connect-data/desktop-data-sources), under Next Steps, there's some hypertext that reads [Data sources supported by DirectQuery](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources), but it doesn't link to a page that provides the information. 

I've seen a list like that before, and I was looking for it to share with a group of students. It seems to have disappeared. That was a super helpful list, and I'd be grateful it you all could please bring it back.

Thank you,
Linda
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [DirectQuery in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @llarkan. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello there -- thanks for your feedback. The engineering team is aware of the request for DirectQuery links, and is reviewing it.
