### ISSUE TITLE
How to customize the display pattern of measures in  matrix visual

### ISSUE THREAD

**Issue by JTTonywujie** [MicrosoftDocs/powerbi-docs#4516]
I just have some customized demand in using matrix visual, could anyone give some suggestion？
As seen in the picture, in this dashboard, I use two matrices ,but I have set them to display different messuare values of the same row label(namelly inventory sku code),based on user's filter selection.
What I need  is to ensure when I scroll up and down in one matrix, the other one may scroll in the same direction.
Since synchronous scroll in several matrices seems unavailable yet, so I try to put all measures into  one matrix, but the result is not so satisfactory,
Specifically, when the  measures in  the left matrix are dargged into the right one,  they will be expanded to compute and list according to each date column label in the right matrix.---this looks a little weird, because the results of these two measures keep constant  in  a whole month, not variable to each date of a certrain month. In another words,  I need set these two measures  to  display in  each single column
![微信截图_20230512114456](https://github.com/MicrosoftDocs/powerbi-docs/assets/120431845/e41f1a07-b185-421c-a290-f4c318bca8ae)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d5bd-51e3-468a-0f7d-a936083f0dc5
* Version Independent ID: 59eea08a-c392-951e-2ba6-860cfcc58281
* Content: [Create a matrix visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual)
* Content Source: [powerbi-docs/visuals/desktop-matrix-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-matrix-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JTTonywujie. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
