### ISSUE TITLE
Augment documentation on Query Limit to include information for Premium Per User license

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/powerbi-docs#4518]
Hi there,
Could you add information to the "Query limit" section https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#query-memory-limit , below the table that specifies information for query limits for dedicated capacities:

"For Premium per User license (PPU) the query limit that applies is that of Power BI Premium P3 dedicated capacity (10GB) whereas for Power BI Premium license the limit is 1GB."

This was confirmed in tests with customer experiencing the issue.

Thank you,
Michal

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 74987f4b-691c-9816-f600-e0cbbb2d78a7
* Version Independent ID: c017e29d-f021-6e76-356e-5e0018122b91
* Content: [How to configure workloads in Power BI Premium - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-workloads#query-memory-limit)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-workloads.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-workloads.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @morcinim,

Can you please start an internal email thread for this?

Thanks,

Kesem
