### ISSUE TITLE
Set up Power BI desktop for developing a visual (missing setting)

### ISSUE THREAD

**Issue by kubow** [MicrosoftDocs/powerbi-docs#4519]
PowerBI Desktop (Version: 2.116.884.0 64-bit (April 2023)): 
"Developer Mode" check box is not present ... Only "Develop a visual" to say to Override some session visual. It is quite misleading... not sure if this setting corresponds to the actual set up of developer mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**
<img width="615" alt="PowerBI_developer_mode" src="https://github.com/MicrosoftDocs/powerbi-docs/assets/6998388/b736f28d-eb70-4784-9af9-782bd059fdd2">

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kubow. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @kubow. There were some recent changes in the UI. The *Developer mode* section was indeed renamed to *Develop a visual*. I'll update the documentation.
