### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by woodbridge** [MicrosoftDocs/powerbi-docs#452]
"Understanding your audience and the benefit they'll receive from the content pack will help ensure your users are _successfully_ with the content you provide."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfe7dce-81b2-b49b-e911-9c1bf7d4c7ff
* Version Independent ID: 8c2148f0-bd90-1712-2f3c-1c17c3b71f88
* Content: [Overview of the Power BI service content pack program - Power BI](https://docs.microsoft.com/en-us/power-bi/service-content-pack-overview)
* Content Source: [powerbi-docs/service-content-pack-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-content-pack-overview.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Good catch, @woodbridge ! I'll fix that. 
BTW, did you know that for minor things like typos, you can edit the doc yourself! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.
Thanks again!

**Comment by maggiesMSFT** [comment]
OK, @woodbridge -- fixed now. Thanks!
