### ISSUE TITLE
Add the other group types that can be used & limitations

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4521]
Hi I just looked up a video from Patrick that mentions 3 types of groups are supported in RLS and 1 is not. Can we please add that to the docs? The current document [https://learn.microsoft.com/en-us/power-bi/guidance/rls-guidance#configure-role-mappings](url) only mentions security groups can be added. 

I do trust the video, where it mentions that security groups, distribution group, mail enabled groups are supported, while office 365 group is not. The video is dated 2020 - eg 3y old, so maybe by now they have enabled all 4 group.

Thank you so much, Martina

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e49a178-5b5e-ae62-b12c-be846eb6ce40
* Version Independent ID: 8372b4a0-75e5-dc84-cdbf-e1c2d76331a7
* Content: [Row-level security (RLS) guidance in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/rls-guidance)
* Content Source: [powerbi-docs/guidance/rls-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/rls-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion, I've updated the article. Much appreciated!
