### ISSUE TITLE
UNION vs. INTERSECTION

### ISSUE THREAD

**Issue by vara-tr** [MicrosoftDocs/powerbi-docs#4522]
Tried as the article suggest.  I have a table with columns that are basically Boolean.  So, if price exist for a product pants, the column shows a 1 in the "Pants Boolean" column, otherwise 0.  If price exist for product shirts, the 1 shows in the "Shirts Boolean" column otherwise 0; same with blanket, etc.

Creating slicers and turning off interactions still results in an Intersection, where certain columns are filtered, whereas I expected a UNION.   So, selecting 1 for Pants and 0 for Shirts, down-filters the number of columns for Pants even though Pants slicer says it is not being impacted by any other filters.   I'm using a Stacked Column Chart with color-coding, so it's easy to see that selecting any combination of 1s and 0s with slicers automatically reduces the # of columns for the remaining product, even if there were values in the now-hidden columns to being with. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-reports-visual-interactions?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-reports-visual-interactions.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vara-tr. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @vara-tr, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
