### ISSUE TITLE
Three missing sections to be added.

### ISSUE THREAD

**Issue by rwlpf** [MicrosoftDocs/powerbi-docs#4526]
Just checking this page against the current Tenant settings, the following sections are not listed.

- Datamart Setting
- Data model settings 
- Scale-out settings 

This is the page I give to my customers and students for reference. While I explain that the Power BI service is a fast-moving target, DataMarts have been available for several months.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 700f1531-6391-647b-788d-56d176c930e7
* Version Independent ID: 700f1531-6391-647b-788d-56d176c930e7
* Content: [About tenant settings - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-about-tenant-settings)
* Content Source: [powerbi-docs/admin/service-admin-portal-about-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-about-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rwlpf. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rwlpf, thanks for the feedback. We are reviewing how best to keep up with the fast changing tenant settings and how to handle the specific cases you mentioned.

**Comment by paulinbar** [comment]
Hi @rwlpf. I have updated the article you mentioned. The updates should be online by tomorrow. Thanks!
