### ISSUE TITLE
powerBI

### ISSUE THREAD

**Issue by Chets2015** [MicrosoftDocs/powerbi-docs#4527]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 423bed63-655a-3079-815e-0d9a8c7de44d
* Version Independent ID: ed119c4a-d4f0-7458-fd57-d7247edbd70e
* Content: [Download the Financial Sample Excel workbook for Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/sample-financial-download)
* Content Source: [powerbi-docs/create-reports/sample-financial-download.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-financial-download.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @Chets2015, I do not see any info in the issue you've opened. I am going to close it now, but please feel free to reopen if you can provide some more info. Thanks!
