### ISSUE TITLE
 November 15, 2018 AAD Update

### ISSUE THREAD

**Issue by sweetlapeet** [MicrosoftDocs/powerbi-docs#453]
Has this document taken the following issue into consideration?
https://social.msdn.microsoft.com/Forums/en-US/4192e141-309a-4dd6-a5c9-f1a8ce32f4ca/aadsts54005-oauth2-authorization-code-was-already-redeemed?forum=WindowsAzureAD

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#change-notice-authorization-codes-will-no-longer-be-available-for-reuse

**Comment by maggiesMSFT** [comment]
Hi, @sweetlapeet -- I'm not sure how your comment ended up in the Power BI docs. I'm adding @eross-msft, one of the authors of  https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/whats-new#change-notice-authorization-codes-will-no-longer-be-available-for-reuse
Hope that helps. Thanks for your comment!

**Comment by eross-msft** [comment]
@sweetlapeet  I'm speaking with the product group about your question and will get back to you as soon as I can. With the holiday, there will be a bit of a lag. Thanks!!!

**Comment by eross-msft** [comment]
@sweetlapeet  For the best answer to your question, you should speak with @hpsin on the product group side. Again, with the holidays, responses might be delayed.

**Comment by sweetlapeet** [comment]
@maggiesMSFT this is a powerbi question as it is the power bi access token sample that I am referring to. 

AAD had an update and it seems that pbi sample code on the doc has not been updated. Can you confirm?

Regards, 
Aharon Najafi

**Comment by maggiesMSFT** [comment]
Ah, OK, thanks @sweetlapeet. In which article did you come across the Power BI access token sample? That info will help me direct your question to the right author. 
thanks!

**Comment by mgblythe** [comment]
Closing this one out, but @sweetlapeet feel free to reopen if you have the Power BI doc you were referring to. CC @eross-msft, @maggiesMSFT
