### ISSUE TITLE
& instead of ?

### ISSUE THREAD

**Issue by zebrassimo** [MicrosoftDocs/powerbi-docs#4530]
This is a deviation from the documentation

For me, it only works if I replace the `?` with an `&`

Besides that, I can also use tables and fields with spaces using `_x0020_`

like so: 
`URL&filter=Jira_x0020_Epics/issue_x0020_key eq PP-1`

related: https://community.powerbi.com/t5/Service/Embedding-report-deep-links/m-p/2840351

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-url-filters)
* Content Source: [powerbi-docs/collaborate-share/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zebrassimo. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @zebrassimo, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
