### ISSUE TITLE
Security groups vs. Power BI admin rights

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4531]
Hello,

Please add to this document [https://learn.microsoft.com/en-us/power-bi/admin/service-admin-metadata-scanning-setup#enable-tenant-settings-for-metadata-scanning](url) a note somewhere. 

Note that when you enable the API setting only for specific security groups, Power BI Admin will need to be added to the security group as well. 

__________________________
**The information is from Teams Power BI escalation channels:**
[13:29] Meir Shimon
Indeed, your observation is correct.

To utilize the Scanner API, you have two authentication options:

Authenticate as a delegated user of the Power BI admin account.
Authenticate as a service principal that has been granted the necessary permissions by the Power BI admin, with the first switch enabled.

In either case, in order to obtain the schema of the dataset (sub-artifact), you must first enable the switch and be a member of the corresponding security group.

So, to answer on your question, these switches setting not overriding Power BI Admin rights to run the API but they overriding his privilege to get the schema in the response until it will enable it and will be member in the SG that enabled for.
_________________________

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5057b20-527f-b796-47c6-e63add79b15b
* Version Independent ID: e7305792-f359-d0a9-3c59-9e6cd2024b13
* Content: [Set up metadata scanning in an organization - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-metadata-scanning-setup)
* Content Source: [powerbi-docs/admin/service-admin-metadata-scanning-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-metadata-scanning-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-eim**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.
