### ISSUE TITLE
Sample Table does not match the example in tutorial

### ISSUE THREAD

**Issue by Mark-BerryS2** [MicrosoftDocs/powerbi-docs#4533]
The Table 1 which is to be used in the first portion of the tutorial doesn't match the resulting table provided by the URL as a result the rest of the tutorial is not able to be properly followed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mark-BerryS2. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, looks like they've changed a handful of the names of columns in that table. We'll schedule an update for that article, to match the current experience. I'll leave this open while we get that into the queue.

**Comment by davidiseminger** [comment]
I've added a note that clarifies column names and selections may vary as that site is updated. Thanks!
