### ISSUE TITLE
Minor tweaks / edits

### ISSUE THREAD

**Issue by denglishbi** [MicrosoftDocs/powerbi-docs#4535]
In the Orchestrate a data pipeline section opening it states “data flow” instead of “dataflow”.

In relationship section the DimStore to DimEmployee is in the table backwards.

For the last section and outline at beginning “autocreate” should be hyphenated like shown in context menu for doing the quick create.

great content, keep it up 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by itsnotaboutthecell** [comment]
This was updated in the last merge. Please close @bishalgoswami

**Comment by paulinbar** [comment]
Thanks for your suggestions, @denglishbi. Closing this issue now.
