### ISSUE TITLE
State ranks for retirement not visualice

### ISSUE THREAD

**Issue by fernandoarbe** [MicrosoftDocs/powerbi-docs#4536]
After load HTML, on navigator, doesn't show html table in this section: "Full results: How your state ranks for retirement", when clic on "web view" of powerbi navigator, doesn't show any table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Get started with Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-getting-started)
* Content Source: [powerbi-docs/fundamentals/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-getting-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello there, thanks for your feedback. The process works properly for me and for others, though there have been updates to that website that may affect the names of some columns. We'll look at updating the table names, feel free to try again.
