### ISSUE TITLE
List of data sources that support DirectQuery

### ISSUE THREAD

**Issue by ielizaga** [MicrosoftDocs/powerbi-docs#4539]
This page is referenced from some others (including [DirectQuery in Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)) that mention the existence of a list of data sources that support DirectQuery but that seems to no longer exist here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ielizaga. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, we'll update that article referencing the list (that no longer exists). Thanks.
