### ISSUE TITLE
Multi-Geo support for Workload

### ISSUE THREAD

**Issue by ahmadanuar** [MicrosoftDocs/powerbi-docs#454]
Is workload supported in Multi-Geo? Been getting information that this is not supported. And I cannot find information in this documentation,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium#workloads-in-premium-capacity)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by ahmadanuar** [comment]
This is regarding on Dataflow workload in Multi-Geo environment

**Comment by mgblythe** [comment]
@ahmadanuar - I just added a note to the Multi-Geo docs today. Dataflows aren't supported in Multi-Geo.
