### ISSUE TITLE
Missing doc about Kerberos HTTPS setting

### ISSUE THREAD

**Issue by arcus4** [MicrosoftDocs/powerbi-docs#4540]
Instructions on how to set Kerberos SPNs for HTTP exist, yes. But how do we set SPNs for secure PBIRS on HTTPS. Would it as easy as the following:
Setspn -a HTTPS/contosoreports.contoso.com ContosoRS
Setspn -a HTTPS/contosoreports ContosoRS

Thanks,
Jan

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bishalgoswami. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
