### ISSUE TITLE
Can't get past error when building semantic model

### ISSUE THREAD

**Issue by rob-stover** [MicrosoftDocs/powerbi-docs#4541]
I've worked through this example several times and always induce an error in the semantic model after the pipeline is built. I can't ever make it past the first measure creation. Ever. Not when I even start from scratch. Same story
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rob-stover. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Hi @rob-stover I know there were some early bugs that may have prevented some users from moving forward in the tutorials, if you have since tested - can you please let us know if you were able to proceed?

**Comment by rob-stover** [comment]
Yes. I got through them eventually

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by paulinbar** [comment]
Closing this issue now.
