### ISSUE TITLE
Microsoft Fabric for Power BI users

### ISSUE THREAD

**Issue by BREMERQUIQUIA** [MicrosoftDocs/powerbi-docs#4542]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BREMERQUIQUIA. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Unfortunately there are no details within this ticket. @BREMERQUIQUIA can you please provide a description for me to review.

**Comment by paulinbar** [comment]
Hi @BREMERQUIQUIA, I am going close this issue now. Feel free to reopen it if you are still having issues and can provide more detail. Thanks!
