### ISSUE TITLE
Export Power BI embedded analytics reports API

### ISSUE THREAD

**Issue by BREMERQUIQUIA** [MicrosoftDocs/powerbi-docs#4543]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7b2a51d-0025-3209-a1c1-db3362b909bb
* Version Independent ID: a952e5a8-acf6-31cc-43ff-77cef73b2a9e
* Content: [Export Power BI embedded analytics reports API - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/export-to)
* Content Source: [powerbi-docs/developer/embedded/export-to.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/export-to.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BREMERQUIQUIA. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
@BREMERQUIQUIA, there doesn't seem to be a question here. I'm closing this issue. If you have questions or comments about the documentation, you can open a new one.
Thanks.
