### ISSUE TITLE
pqt

### ISSUE THREAD

**Issue by odeddror** [MicrosoftDocs/powerbi-docs#4548]
How do you open pqt file?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @odeddror. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Hi @odeddror - the PQT file is for use in importing/exporting in the Power Query application, if you wanted to open this as a file, you can convert the file extension from .PQT to .ZIP to view the underlying code and other metadata in the file.
