### ISSUE TITLE
QR CODE option unavailable

### ISSUE THREAD

**Issue by sakshiagarwalg** [MicrosoftDocs/powerbi-docs#4550]
I cannot find the 'generate QR code' option after following the required steps stated in the page. If anyone can guide me on how to create QR code for powerBi report on desktop/service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c8216a5-c800-afbe-8eaa-dea3dcf5c8da
* Version Independent ID: c07c4f24-583f-5c6e-c943-4dd727c782bd
* Content: [Create a QR code for a tile to use in Power BI mobile apps - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-create-qr-code-for-tile)
* Content Source: [powerbi-docs/create-reports/service-create-qr-code-for-tile.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-create-qr-code-for-tile.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sakshiagarwalg. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hey, @sakshiagarwalg, thanks for reaching out. Can you give me some detail about where things went wrong for you? I assume you were trying to get a QR code for a particular tile in a dashboard? If so, did you find the "Open in Focus mode" option?" Not all types of tiles have that option. If you don't see the Open in focus mode option, try another visual - a graph or a chart, if possible. If you managed to open a visual in focus mode, did you manage to open the options menu (the three dots...). The Generate QR code option should be there. In any event, if you can't find the option, please provide more detail about the particular case you had problems with. Note that sometimes the "Open in focus mode" option is not listed in the options menu for the tile, but rather is one of the icons located in the corner of the tile.

Please note that the QR codes generated from within Power BI don't support URL query parameters - parameters that will get you to a specific view or filter. If you want to generate a QR code for a URL that has query parameters you need to use an external generator.. those are freely available on the web. Just open the report or visual you are interested in, configure the view/filtering you want, and then use the external generator to create the QR code.

Here's another article that provides info about creating QR codes in a report, as opposed to a dashboard.
https://learn.microsoft.com/en-us/power-bi/create-reports/service-create-qr-code-for-report

Hopefully, this helps. I am closing this issue now, but please don't hesitate to reopen if you still have trouble. 
Thanks!
