### ISSUE TITLE
Lexical error

### ISSUE THREAD

**Issue by mtsanaissi** [MicrosoftDocs/powerbi-docs#4552]
I believe the last bullet point - "Prepare and **transformation** data in the source" - should be "Prepare and **transform** data in the source".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: deda0833-832f-1984-4ca3-1b59b93bfc58
* Version Independent ID: 78c23031-0096-8c95-e693-73c2ccbbc70d
* Content: [Query folding guidance in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/power-query-folding)
* Content Source: [powerbi-docs/guidance/power-query-folding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/power-query-folding.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mtsanaissi. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good catch! I've updated that error, thanks.
