### ISSUE TITLE
Out of date tutorial???

### ISSUE THREAD

**Issue by dave8136** [MicrosoftDocs/powerbi-docs#4555]
I assume the tutorial is out of date.  I am using the latest version of Power BI Desktop and many of the navigation directions in the tutorial do not match the present menus and tabs.  For example, the tutorial often refers to the "Fields" section which seems to now be called the "Data" section.  Another example, the tutorial calls out to set the Outline transparency to 100% and I never did find what "Outline" referred to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dave8136. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @dave8136, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for calling this out!
