### ISSUE TITLE
Broken Steps

### ISSUE THREAD

**Issue by nenslow** [MicrosoftDocs/powerbi-docs#4556]
Orchestrate a data pipeline

- After initial creation (Step 3) met with a blank window for "Copy data into lakehouse" there was no cancel button (Step 4) 
- Navigating away from the blank window to the workspace, and back into the data pipeline allows to continue on
- Step 8 had no option to select Office365 Outlook as an Activity, had to abandon the tutorial at this point

Create relationships
- Failed Changes (relationshipDelete) occur when attempting to delete/re-create relationships for step 5 - which reverts changes

Write a measure in DAX
- Cannot create the DAX measure, get the following Failed Changes: newMeasureCreated and setAnnotation reverting my changes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by itsnotaboutthecell** [comment]
Hi @nenslow are you still experiencing issues? or would it be ok to close this issue, I know there were some early bugs that possibly prevented users in some scenarios from moving forward.

**Comment by paulinbar** [comment]
Hi @nenslow, I am going to close this issue now, but if you still experience the same issues, feel free to reopen it. Thanks!

**Comment by nenslow** [comment]
Hey Alex, we’re all good now. Feel free to close this one.
