### ISSUE TITLE
Feedback: Add additional installation switches to PowerBI Desktop Installation

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/powerbi-docs#4557]
Hey Team!

It looks like we recently added some additional switches we have in the most recently PowerBI Desktop Setup.exe (May 2023).

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/26752719/57eb5d30-c996-4137-8f04-451ab593d99f)

Also the `REG_SHOWLEADGENDIALOG` does not work anymore.  That does not show up in the list of options.

Hope this helps!

Thanks,

- Brandon
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop#use-command-line-options-during-installation)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @brmcmill. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Hello there -- after consulting with the engineering team, those switches are not going to be exposed in the UI, and are being removed. Sorry for the confusion, thanks for your feedback.
