### ISSUE TITLE
Typo: Create a new project > Create a new visual > 4. says to replace project.json instead of package.json

### ISSUE THREAD

**Issue by JimAtPCG** [MicrosoftDocs/powerbi-docs#4559]
### Create a new visual

4. The *package.json* file containst a list of project dependencies. Replace your *project.json* file with [this one](https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/main/package.json).

Should be:

4. The *package.json* file containst a list of project dependencies. Replace your *package.json* file with [this one](https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/main/package.json).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-bar-chart?tabs=CreateNewVisual)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JimAtPCG. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @JimAtPCG 
I'll fix it right away.
