### ISSUE TITLE
New Workspace Preview - update of App access list not populated

### ISSUE THREAD

**Issue by lukaszjakubczyk** [MicrosoftDocs/powerbi-docs#456]
When I change the list of users in the Access to App that was built in new workspace (Preview) it is not saved and populated though I got the message that it has been updated. Tried several times and it did not work even after 24h. However It works fine if users apply for the change and I approve it from the list.

**Comment by mgblythe** [comment]
@lukaszjakubczyk Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by maggiesMSFT** [comment]
Hi, @lukaszjakubczyk -- Thanks for your feedback! This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
