### ISSUE TITLE
Missing list of supported data sources

### ISSUE THREAD

**Issue by santiagortiiz** [MicrosoftDocs/powerbi-docs#4561]
[Enter feedback here]
The following paragraph contain some link to unrelated information, there are no lists of supported datasources.

Compare the provider with the list of supported data sources found in [Power BI data sources](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources).

Following the mentioned steps, can be found for example the Python.Execute data source, which is not explicit information about refresh capabilities.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a46dbd1-2511-bc77-e09a-00b01540afa5
* Version Independent ID: 58ec402c-8a94-0752-c823-2ddd917b18df
* Content: [Troubleshooting unsupported data source for refresh - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-admin-troubleshoot-unsupported-data-source-for-refresh)
* Content Source: [powerbi-docs/connect-data/service-admin-troubleshoot-unsupported-data-source-for-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-admin-troubleshoot-unsupported-data-source-for-refresh.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @santiagortiiz. This issue has been assigned to the doc author for review.

**Comment by santiagortiiz** [comment]
I saw that the list is in other link, which is referenced in the mentioned page, might be difficult to find because it's nested but it's there.
