### ISSUE TITLE
PPC requirement for external parties who want to subscribe to content via email

### ISSUE THREAD

**Issue by CJuulmann** [MicrosoftDocs/powerbi-docs#4562]
Under the Enable access section we have a sentence that causes confusion with our customer due to the context it's written in:  see here https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b#:~:text=The%20guest%20user%20can%20only%20be%20subscribed%20to%20content%20in%20workspaces%20that%20are%20backed%20by%20a%20Premium%20capacity. 

Customers fails to understand that "subscribe" in this case is a reference to a specific feature for getting email notifications on reports. This should be called out, that it has nothing to do with actually enabling access to external users and giving them access to see content.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by ajburnle** [comment]
Thanks for your feedback! The content has been updated.

**Comment by maggiesMSFT** [comment]
closing for @ajburnle
