### ISSUE TITLE
Power BI Shape Tooltip Link Feedback

### ISSUE THREAD

**Issue by emivy20** [MicrosoftDocs/powerbi-docs#4564]
I was looking for more information on the conditional tooltip feature in relation to shapes, as that's the window I had pulled up in Power BI desktop. However, clicking the "Learn more about conditional formatting" link brought me to [this page](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting) on matrix and table tooltip customizations. I realize some of it overlaps, but none of it called out how it was related to the tooltip on a shape. Snip below shows which link I clicked in the desktop and the shape I had selected. I was editing the "Tooltip" under the "Action" property.

**TLDR: The link seen in the bottom left corner of the snip doesn't bring you to a relevant documentation page.**

<br/>
<br/>

![Shape Tooltip Window](https://github.com/MicrosoftDocs/powerbi-docs/assets/94653172/e761fbee-523a-4dca-9c56-aee4469e8f32)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Apply conditional table formatting in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/create-reports/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @emivy20. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment, and sorry about that misdirection. We'll forward this to the product team to see about putting a better doc link into that dialog.
