### ISSUE TITLE
Fabric context

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4565]
The Datamart page would benefit from linking to the Fabric decision guide for context:
https://learn.microsoft.com/en-us/fabric/get-started/decision-guide-warehouse-lakehouse

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02e17802-d798-33a1-163d-bfe358953051
* Version Independent ID: 02e17802-d798-33a1-163d-bfe358953051
* Content: [Introduction to datamarts - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-overview)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! I've updated the article, it will go live with updates in the next day or so. Thanks!
