### ISSUE TITLE
编辑数据管道时加载数据流失败（Failed to load data stream when editing data pipeline）

### ISSUE THREAD

**Issue by liliwen365** [MicrosoftDocs/powerbi-docs#4566]
[Enter feedback here]
中文：如下图：在编辑数据管道时，无法加载数据流；点击旁边的刷新会显示：加载数据流失败！
English：The following figure: When editing the data pipeline, the data stream cannot be loaded; clicking Refresh next to it will show: Load data stream failed！
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/76478019/c9af331c-5179-4734-8ed6-9080e4015953)
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/76478019/94d47df1-ad9f-4489-a20d-b383ffb0a8e3)
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/76478019/44e36c87-c2f7-4ddd-8a7a-499937c0748a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by itsnotaboutthecell** [comment]
@liliwen365 I wanted to first check to see if you were still having issues, there were some bugs that users were experiencing that have since been resolved.

**Comment by paulinbar** [comment]
Hi @liliwen365, I am going to close this issue now, but feel free to reopen if you find you are still having the issue after the bug fixes that @itsnotaboutthecell mentioned. Thanks!
