### ISSUE TITLE
Capacity and SKUs in Power BI embedded analytics - missing information

### ISSUE THREAD

**Issue by oferash** [MicrosoftDocs/powerbi-docs#4567]
This page is missing the reference to "F" (Fabric) capacities that can be used for your Power BI Embedded analytics workspaces for either scenario ("embed for your organization" or "embed for customers").

Also the note: "You'll need a Power BI Pro or Premium Per User (PPU) account to publish content." is wrong as it is missing the fact that you can publish content without a Pro/PPU license by using a service principal executing the REST API: "[https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group](https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group)".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @oferash. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks, @oferash. I fixed the note and added a link to the Fabric article on licenses and F SKUs.
Fully updating this article will require some more time.
