### ISSUE TITLE
Extremely Poor Page

### ISSUE THREAD

**Issue by richardbranson** [MicrosoftDocs/powerbi-docs#4571]
This page(s) information is very badly laid out. 

Trying to figure out how to share reports with Users that don't have to pay for their license is impossible. Conflicting information on every page I look at.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09828fad-a8e9-a2b3-0942-6e19724fa00b
* Version Independent ID: 4b67d4da-c2b7-a6ef-e511-7e61b6b35c58
* Content: [Sign up or purchase the Power BI service as an individual - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-self-service-signup-for-power-bi)
* Content Source: [powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-self-service-signup-for-power-bi.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Sorry to hear your experience with that article wasn't good. We'll look at the article and see where we can improve its layout.
