### ISSUE TITLE
Missing Dataflow list at data pipeline Settings 

### ISSUE THREAD

**Issue by MorrisQiu** [MicrosoftDocs/powerbi-docs#4576]
[Enter feedback here]
Under Orchestrate a data pipeline, step 7

7. With the dataflow activity still selected, select Settings and choose OnlineSalesDataflow from the Dataflow list. If necessary to update the list, select the Refresh icon.

Issue : there is no Dataflow list visible to select, even the Refresh icon was selected several times. I also tried to create a new Dataflow, but the newly created Dataflow was still not visible
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MorrisQiu. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Hi @MorrisQiu there is an outstanding issue when utilizing "My Workspace" - if possible, I'd ask that you leverage a group workspace to complete the tutorial for now.
