### ISSUE TITLE
What about getting diagnostics via Power Shell?

### ISSUE THREAD

**Issue by alpkayaMSFT** [MicrosoftDocs/powerbi-docs#4577]
[Enter feedback here]
Thanks for the great article - this is very applicable to many of my customers.
One follow up - can I get these diagnostics logs for paginated reports via Powershell? or other scripting method? In the case where customers have large number of paginated reports, the Powershell (or other), would be a great option. Any chance we can add a section on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17d735f0-7ec8-5faa-6472-f97cf033852e
* Version Independent ID: 17d735f0-7ec8-5faa-6472-f97cf033852e
* Content: [View diagnostics  for Power BI paginated reports - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-diagnostics)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-diagnostics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-diagnostics.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alpkayaMSFT. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @alpkayaMSFT, Thanks for the suggestion! I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks again!
