### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by EevaMak** [MicrosoftDocs/powerbi-docs#4579]
Hi, after change to fabric, these instructions are not valid. It seems that Power BI URL parameters are handled differently than instructed in this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71f67df5-c9be-c514-e152-d10d5987214b
* Version Independent ID: 71f67df5-c9be-c514-e152-d10d5987214b
* Content: [Pass a report parameter within a URL for a Power BI paginated report - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/parameters/pass-report-parameter-url)
* Content Source: [powerbi-docs/paginated-reports/parameters/pass-report-parameter-url.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/parameters/pass-report-parameter-url.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EevaMak. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @EevaMak, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
