### ISSUE TITLE
Missing steps for delegation success 

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/powerbi-docs#458]
Looking at the section named:  Configure delegation settings on the gateway service account

Found that the PowerBI service account needs to be added to the "Windows Authorization and Access Group" group within the Users domain, to be able to successfully authenticate the user via Kerberos authentication in certain scenarios where the Active Directory domain has had any hardening done on it, or the PowerBI account and the user account are in separate domains or forests.  NOTE:  This can be done even in situations where the domain / forest has not been harden as well.

For more information about the group:  https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/active-directory-security-groups#bkmk-winauthaccess 

1.  Logon to the user domain, and launch Active Directory Users and Computers.
2.  Locate the group named "Windows Authorization and Access Group"; which is typically located in the "Builtin" container.
3.  Double click on the group, and click on the Members tab.
4.  Click the Add button, and change the domain location to the PowerBI service account domain.
5.  type in the PowerBI account name and click the Check Names button.
6.  Click OK button.
7.  Click OK button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Use Kerberos for single sign-on (SSO) to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos)
* Content Source: [powerbi-docs/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @RobG-MSFT.  We’ve forwarded your feedback to the writer, who should respond soon -- after the holiday. Thanks!

**Comment by mgblythe** [comment]
Adding @arthiriyer to comment on this one, then I can add to the docs.

**Comment by inthemedium** [comment]
This issue should be closed, right?

https://docs.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos#add-gateway-service-account-to-windows-authorization-and-access-group-if-required

**Comment by maggiesMSFT** [comment]
Hi, @inthemedium -- thanks for pointing that out! Closing it now.
