### ISSUE TITLE
Guest users can't use Power BI desktop to connect to service datasets in the Power BI service - or Dataflows

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#4582]
There's a bullet point in the Considerations and Limitations section which probably needs expanding. It currently says:

Guest users can't use Power BI desktop to connect to service datasets in the Power BI service

From my testing and understanding, it should say:

Guest users can't use Power BI desktop to connect to service datasets or dataflows in the Power BI service

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by ajburnle** [comment]
Thanks for your feedback. The content has been updated!

**Comment by maggiesMSFT** [comment]
closing for @ajburnle
