### ISSUE TITLE
visuals.ts to visual.ts change

### ISSUE THREAD

**Issue by christophermetrikus** [MicrosoftDocs/powerbi-docs#4585]
For the tutorial page: '[Use React to create a Power BI visual](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual)'

Minor typo under the section 'Add a method to apply visual settings'. In the sentence 'In VS Code, from the src folder, open `visuals.ts`, the filename should be `visual.ts`.

Very minor typo but thought I would mention as it made me wonder if such a file exists (it doesn't).

Thanks for all the hard work putting these visuals tutorials together: they represent a great set of docs that I've found invaluable for getting Power BI up and running.

(And would love to see more for specifically functional components in React.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: abfc5549-16a6-5afd-dac4-64021c25dfa9
* Version Independent ID: b8bf0ca1-1f11-bac0-76fa-cfd6a0d1231b
* Content: [Create a React-based visual for Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual)
* Content Source: [powerbi-docs/developer/visuals/create-react-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-react-visual.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Hi @christophermetrikus. Thanks for the great feedback and for pointing out that typo. The typo is fixed. (It should be live by Tuesday at the latest.)
Improving the React tutorials has been in my backlog for a while now. I'll see what I can do about speeding things up.
