### ISSUE TITLE
How about Team Foundation Server integration with OneDrive Integration?

### ISSUE THREAD

**Issue by duncfair** [MicrosoftDocs/powerbi-docs#4586]
Please cover whether users can use OneDrive as their 'local' repositiory.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a07e15c6-9882-de08-f98e-2ada7146e349
* Version Independent ID: a07e15c6-9882-de08-f98e-2ada7146e349
* Content: [Power BI Desktop OneDrive and SharePoint integration - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-sharepoint-save-share#how-to-enable-power-bi-desktop-and-sharepoint-integrations)
* Content Source: [powerbi-docs/create-reports/desktop-sharepoint-save-share.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-sharepoint-save-share.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @lafaberMSFT
* Microsoft Alias: **lafaber**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @duncfair. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @duncfair, I have passed your feedback along to the people who maintain the document for their consideration. In the meantime I am closing this issue. Thanks for reaching out!
@maggiesMSFT 
@lafaberMSFT
