### ISSUE TITLE
Feedback - Request to update - Out of Date screen shots and information..

### ISSUE THREAD

**Issue by Swbell02** [MicrosoftDocs/powerbi-docs#4587]
When opening a support ticket, there has been a change to the form, and the screenshots on this page no longer match.

When requesting support, this is now the form you see:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/136093211/87eacadb-a9bf-40db-9789-d8e652d417f9)

You need to select the Arrow to move forward in the process.

The solution then points to KB articles that instructed you to open this ticket to complete the Power BI migration.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/136093211/9d7dd544-b057-40f3-9a1f-cba7e5abe739)

Then you have to select "contact support."

On the next page, you have:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/136093211/377c465d-cb59-4ad2-9ebc-d89d0c493d99)

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/136093211/39e8eaf1-4164-4108-a5c9-3a869d68f246)

From here, you can enter the information in the tenant info etc.  But the other drop-downs never appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 670c13f1-8741-24e9-c754-d7ac45fbe8be
* Version Independent ID: 45e02065-2360-3a34-e6a9-1a7223ee7bc3
* Content: [Move Power BI between regions - Power BI](https://learn.microsoft.com/en-us/power-bi/support/service-admin-region-move)
* Content Source: [powerbi-docs/support/service-admin-region-move.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/support/service-admin-region-move.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by davidiseminger** [comment]
Thanks for the input here, the article has been updated. Much appreciated.
