### ISSUE TITLE
Bubble Chart with four dimensions and data labels

### ISSUE THREAD

**Issue by Klinkert** [MicrosoftDocs/powerbi-docs#4589]
Labeling bubbles does not work in my scatter plot. I have four dimensions (x, y, bubble size, bubble color plus LABLEs for each row/point/bubble). I have x in X-Axis, y in Y-Axis, size in Size, and color in Legend and the chart looks good except for data labels. When I try to put LABLEs in Values, I get the error "Remove Values to display x- and y-axis pairs."  How can I place LABLES on bubbles to identify each bubble to a row/point?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5668e4cf-3837-c2d4-b818-14476441468b
* Version Independent ID: c95096dd-9b73-79ab-8ff2-158c5900f5a6
* Content: [Scatter, bubble, and dot plot charts in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-scatter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-scatter.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Klinkert. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
