### ISSUE TITLE
Error while writing rows to Push Dataset

### ISSUE THREAD

**Issue by JMMB1986** [MicrosoftDocs/powerbi-docs#459]
Tried adding a few rows to the push dataset created. 

Got an error shown in screenshot.

![error](https://user-images.githubusercontent.com/26969000/48865460-efd94c80-ed8c-11e8-96ce-67d050a51c14.PNG)

**Comment by maggiesMSFT** [comment]
Hi, @JMMB1986 -- thanks for contacting us. Is your question related to a specific article?
