### ISSUE TITLE
Where is the "prompt user" property in PBI Report Builder?

### ISSUE THREAD

**Issue by dbradish-microsoft** [MicrosoftDocs/powerbi-docs#4590]
Under [Considerations](https://learn.microsoft.com/en-us/power-bi/paginated-reports/parameters/pass-report-parameter-url#considerations-and-limitations), you state that the`Prompt User` property must be selected in `Power BI Report Builder`.  First, is the reader to assume that you are actually talking about `Power BI Desktop`?  If so, where is the `Prompt User` switch in the Parameter UI?

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/58762114/22433b43-9191-4ba5-8f3f-b15c19f05b7a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71f67df5-c9be-c514-e152-d10d5987214b
* Version Independent ID: 71f67df5-c9be-c514-e152-d10d5987214b
* Content: [Pass a report parameter within a URL for a Power BI paginated report - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/parameters/pass-report-parameter-url)
* Content Source: [powerbi-docs/paginated-reports/parameters/pass-report-parameter-url.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/parameters/pass-report-parameter-url.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dbradish-microsoft. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @dbradish-microsoft, thanks for your feedback. I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks again!

**Comment by Caraballo-D** [comment]
Having this same issue, can you link the new work item?
