### ISSUE TITLE
Paginated Reports visual can now be used with just a Power BI Pro Subscription

### ISSUE THREAD

**Issue by bdejagere-msft** [MicrosoftDocs/powerbi-docs#4591]
Following the change of making Paginated Reports available to Power BI Pro Subscriptions, it's now possible to use the Paginated Reports visual in a Power BI Report without the usage of a PPU or Premium Capacity, but with just a Power BI Pro Subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfaaf125-cd9e-4b88-c808-3bd53525d367
* Version Independent ID: df09f8c6-0e60-14dc-6095-c2be885019c7
* Content: [Create and use the paginated report visual - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/paginated-report-visual)
* Content Source: [powerbi-docs/visuals/paginated-report-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/paginated-report-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bdejagere-msft. This issue has been assigned to the doc author for review.
