### ISSUE TITLE
Text Adjustment and Image Quality

### ISSUE THREAD

**Issue by Zarumoth** [MicrosoftDocs/powerbi-docs#4592]
https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a

**Gauge charts** - text in the description is smashed together. I won't paste it here because it is very weirdly formatted.
**Maps** - it would be very cool if you can zoom in / expand the different map visuals examples: _power-bi-esri-map-theme2.png_, _azure-maps-visual-hero.png_, _visual-filled-map.png_, _power-bi-shape-map2.png_.
**Scatter-high density** - the example image, _density-scatter.png_, is compressed into unreadability.
**R script visuals** - the example image, power-bi-r-visual.png, is compressed into almost being unreadable.

In general, a very informative and awesome page!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69212c7b-4492-a044-a07b-05266b20e370
* Version Independent ID: cc3d001b-1d58-b3b5-62a6-95f3955bf733
* Content: [Visualization types in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Zarumoth. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the nice comments! I've fixed the text (an errant dollar sign threw the markdown processor off kilter), and unfortunately the images we have for the maps and others are kind of small (no way to enable zoom in, or a lightbox). Fixes will land in a day or so. Thanks again!
