### ISSUE TITLE
Power BI report on secure public portal that uses custom auth

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [MicrosoftDocs/powerbi-docs#4596]
I don't see a clear point here on how to use a Power BI on a public portal where its "unfeasible" to register users on power bi... think of the scenario of a multi-tenant application where I have financial reports

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-embed-secure)
* Content Source: [powerbi-docs/collaborate-share/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-embed-secure.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Leonardo-Ferreira. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Leonardo-Ferreira , Thanks for your feedback! I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime.
