### ISSUE TITLE
Need working code samples for this documentation

### ISSUE THREAD

**Issue by breakpoint7** [MicrosoftDocs/powerbi-docs#4599]
There really needs to be some working code samples for this page (https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers).  I was able to get standard Power BI reports working, but have not been able to get the auth code working with embedded paginated reports.  The token generation is different and event though there is at least one feedback thread where someone shares what worked, I never could get it working.  How about a real, working code sample that demonstrates how to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d53eef67-91ce-691f-5e29-515d553023f6
* Version Independent ID: f6723c69-a08d-42af-6a74-33f22bc55fba
* Content: [Embed paginated reports in your Power BI embedded analytics application - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-paginated-reports?tabs=customers)
* Content Source: [powerbi-docs/developer/embedded/embed-paginated-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-paginated-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @breakpoint7. I've reached out to the dev team and hope to add some clarifying code and/or instructions soon.

**Comment by mberdugo** [comment]
I linked to some more explanations.
Good luck.
