### ISSUE TITLE
Issue with Adobe Experience Cloud issue in Power BI Desktop

### ISSUE THREAD

**Issue by mattpkelly** [MicrosoftDocs/powerbi-docs#460]
We are trying to use our Adobe Experience Cloud credentials in Power BI desktop to create a connection to Adobe Analytics.  When we enter our Adobe credentials all we get is a blank grey screen on log in and the sign in indicator spinning.

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @mattpkelly.  This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
