### ISSUE TITLE
No longer working via Service

### ISSUE THREAD

**Issue by justin-m-schmidt** [MicrosoftDocs/powerbi-docs#4600]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls)
* Content Source: [powerbi-docs/enterprise/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @justin-m-schmidt, I'm closing this issue for the time being. Please reopen if you want to provide more detail regarding the issue you faced. Thanks.
