### ISSUE TITLE
Zendesk template app link not working

### ISSUE THREAD

**Issue by ivanosevitch** [MicrosoftDocs/powerbi-docs#4601]
## How to reproduce

1. Make sure you are connected to https://app.powerbi.com/
2. In the [Connect to Zendesk with Power BI page](https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-to-zendesk), click on [Zendesk template app](https://app.powerbi.com/getdata/services/zendesk)

**Actual**: I'm redirected to a "We couldn't find the page you were looking for." page
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/15523557/52ce92c3-55dc-4a37-b7cb-056fbf1eb4cf)

**Expected** access to the Zendesk template.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2231f5c7-c73c-0b80-d6b9-5adf207a6b62
* Version Independent ID: 91e7c633-83d4-0714-e92f-e3f169549bd5
* Content: [Connect to Zendesk with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-to-zendesk)
* Content Source: [powerbi-docs/connect-data/service-connect-to-zendesk.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-zendesk.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @ivanosevitch, Thanks for pointing that out. I've updated the link and made a few other minor changes. The updates will be online tomorrow. Thanks again for taking the time to let us know about this!
