### ISSUE TITLE
Dynamic M query parameters don't support row-level security (RLS).

### ISSUE THREAD

**Issue by MarianneSchmidt** [MicrosoftDocs/powerbi-docs#4603]
Hi, I was reading your article as I developed a report with Dynamic Parameters, and also I had set up RLS. I did a test on Power BI service, by asking someone to look at the report for me by testing it on an app, I swap the roles accordingly with the RLS group created, and it works well. 
So I think this article needs to be corrected because it looks like RLS its supported with this set up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc66475d-11b3-ba33-cde4-9948dc07ea2c
* Version Independent ID: 46aeb704-a74f-2064-307f-24660579ef4c
* Content: [Dynamic M query parameters in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-dynamic-m-query-parameters)
* Content Source: [powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-dynamic-m-query-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, we're looking into this issue to get a definitive response. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback - while RLS may work in some circumstances, full support of RLS must encompass many scenarios and can't be officially stated unless all such scenarios work properly. Thanks for your feedback!
