### ISSUE TITLE
Can't find the sample on app.powerbi.com

### ISSUE THREAD

**Issue by Burmeister** [MicrosoftDocs/powerbi-docs#4604]
I cant find the sample as described in the article

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36ee7a24-cd5a-6919-0845-1802c03fb770
* Version Independent ID: 36ee7a24-cd5a-6919-0845-1802c03fb770
* Content: [Artificial Intelligence sample for Power BI: Take a tour - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/sample-artificial-intelligence#get-the-built-in-sample)
* Content Source: [powerbi-docs/create-reports/sample-artificial-intelligence.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-artificial-intelligence.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by itsnotaboutthecell** [comment]
@Burmeister - I wanted to confirm that I'm in the Power BI service now (if you've enabled Fabric, ensure you are in the Power BI persona) and I went to Learn and can see the sample visible. I'm curious what is the behavior you're experiencing?

**Comment by paulinbar** [comment]
Hi @Burmeister, I have made some changes in the doc to address your issue. The updates should be online shortly. Thanks for reaching out!
