### ISSUE TITLE
About directquery link is broken

### ISSUE THREAD

**Issue by TechnicalCode** [MicrosoftDocs/powerbi-docs#4605]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 694e3f20-79d0-debf-1449-38a62492424c
* Version Independent ID: 75c298be-5754-c342-cb4d-228b38f8cec7
* Content: [DirectQuery model guidance in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/directquery-model-guidance)
* Content Source: [powerbi-docs/guidance/directquery-model-guidance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/directquery-model-guidance.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TechnicalCode. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing this out - I've updated that with the correct link. Thanks!
