### ISSUE TITLE
No Update Info for May 2023 release on this page

### ISSUE THREAD

**Issue by GregDBABMW** [MicrosoftDocs/powerbi-docs#4607]
There has also been a June 6th 2023 Update to PBIRS

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff7e1942-9181-3451-5d1e-08bfa2ca9454
* Version Independent ID: 5547fc15-7d0e-225f-e0f1-890470f6cd5e
* Content: [What's new in Power BI Report Server - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/whats-new)
* Content Source: [powerbi-docs/report-server/whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/whats-new.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GregDBABMW. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for asking! I'll investigate.

**Comment by GregDBABMW** [comment]
Nothing has ever changed. May 2023 release as well as June 4, 2023 update still missing

**Comment by paulinbar** [comment]
@maggiesMSFT, gentle ping.. :)

**Comment by maggiesMSFT** [comment]
@GregDBABMW & @paulinbar -- gentle reply! I'll ping the author again. So sorry!

**Comment by maggiesMSFT** [comment]
Hi, @GregDBABMW -- May 2023 What's New for Power BI Report Server is live this afternoon!
https://learn.microsoft.com/en-us/power-bi/report-server/whats-new
