### ISSUE TITLE
Basic Configuration missing Step 5?

### ISSUE THREAD

**Issue by ddkpe** [MicrosoftDocs/powerbi-docs#4609]
Basic Configuration jumps from Step 4 (with A & B options) directly to Step 6.  Step 5 missing or numbering issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Configure Kerberos-based SSO from Power BI service to on-premises data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-kerberos)
* Content Source: [powerbi-docs/connect-data/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ddkpe. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @ddkpe. Good call! As it turns out, we were intending to put in the step 5 but there there were some issues that needed checking, but I've put in the step now and it should go live later today. Thanks for taking the time to reach out!
