### ISSUE TITLE
Some observation on this page

### ISSUE THREAD

**Issue by devalph** [MicrosoftDocs/powerbi-docs#4612]
[Two observations:
a. When Transparency is 100%, shade may not be visible
b. We added a button SELECT ALL to visual 5 but observed to be missing in final visual.
However, great learning. Thanks.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @devalph. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @devalph, thanks for the kind words, and your feedback. We're moving this issue over to our work load backlog, and closing it here. Thanks again for taking the time to reach out!
