### ISSUE TITLE
needs correction

### ISSUE THREAD

**Issue by Sree-Ranjini** [MicrosoftDocs/powerbi-docs#4613]
NOTE "The drill-down and drill-up icons only apply to rows. In order to drill down on columns, you must use the right-click menu." seems incorrect

when columns are selected drilluip works for columns

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d5bd-51e3-468a-0f7d-a936083f0dc5
* Version Independent ID: 59eea08a-c392-951e-2ba6-860cfcc58281
* Content: [Create a matrix visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual)
* Content Source: [powerbi-docs/visuals/desktop-matrix-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-matrix-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TechnicalCode. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Great - thanks! I've made that clarification in the note.
