### ISSUE TITLE
Update Permissions for Workspace Settings

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4614]
Hi Team,
could you please update the permission table to include the Required role for Workspace Settings:

1. section "About". This section can be modified only by Workspace Admins
2. section "Premium". This section can be modified by Workspace Admins. In my opinion the capacity settings should not be available to Workspace Admins and I have MS Support ticket 2306140050003011 for this. Right now the Workspace Admins can leave the capacity but cannot come back because they will (typically) not have Capacity Admin role.
3. section "Azure Connections" requires Workspace Admin
4. section "Git integration". I am not sure what is the minimum Workspace permission to set-up Git integrations. In some workspaces Member role has the Git menu available while in other workspaces only Workspace Admin has the Git menu available.
5. section "General", the "Data Model Settings" is missing in this MS Docs, the Workspace Admin is required for it.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/48448079/08137ed3-097e-4e49-82c6-a65f58fb6df3)

Thank you.
BR
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @MartinKDK, thanks for your suggestion. I'll be looking into it and updating the docs as appropriate. Going to close this issue now and move it over to our workload backlog.
