### ISSUE TITLE
Outdated information | Composite models on Power BI datasets

### ISSUE THREAD

**Issue by barnabastoth16** [MicrosoftDocs/powerbi-docs#4615]
Hi there,

https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-storage-mode#considerations-and-limitations

This part of the page is possibly outdated since with the GA of [Composite models on Power BI datasets and Azure Analysis Services](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models#composite-models-on-power-bi-datasets-and-azure-analysis-services) using a composite model, one can combine the data in Power BI datasets with other DirectQuery and imported data.

At least I have the impression that it is outdated.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-storage-mode)
* Content Source: [powerbi-docs/transform-model/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-storage-mode.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Good point, thanks for bringing that to our attention. I'll update that section based on updated functionality. Much appreciated!
