### ISSUE TITLE
Does not work, the sorting

### ISSUE THREAD

**Issue by mfilart** [MicrosoftDocs/powerbi-docs#4616]
Hi,

Thanks for the article. It was helpful, but unfortunately, it doesn't work for me,
My Power BI version is
Version: 2.116.966.0 64-bit (April 2023)

I tried many times, and ended just doing my task in Excel.
I think it's a bug, I'm not sure where to report bugs.

Regards,
mfilart

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort one column by another column in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by paulinbar** [comment]
Hi @mfilart, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for providing your feedback!
