### ISSUE TITLE
Tutorial: Fabric for Power BI users - Pipeline does not identify workflow

### ISSUE THREAD

**Issue by avijitghosh77** [MicrosoftDocs/powerbi-docs#4617]
[Enter feedback here]
Does not allow me to continue as the dataflow is never available for the Pipeline, even if I have one and refresh multiple times.
My developer account ID: [abhijit@6z2kfn.onmicrosoft.com]
I created another data flow using create new from the dataflow in Pipeline, but still fails to appear in the lookup.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @avijitghosh77. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
@bishalgoswami are you attempting to build this in your "My Workspace" if so, there is a known issue and the team is working to resolve. For the meantime, we'd ask that you utilize a group workspace.

**Comment by avijitghosh77** [comment]
> @avijitghosh77 are you attempting to build this in your "My Workspace" if so, there is a known issue and the team is working to resolve. For the meantime, we'd ask that you utilize a group workspace.

Kindly help with the steps to create group workspace and try again. I have been through the MSFT learning path for Fabric and was stuck at the same issue.

**Comment by itsnotaboutthecell** [comment]
Hi @avijitghosh77 below is the doc for how to create a group workspace: 
https://learn.microsoft.com/power-bi/collaborate-share/service-create-the-new-workspaces
