### ISSUE TITLE
DQ over datasets no longer in preview

### ISSUE THREAD

**Issue by gmuenster** [MicrosoftDocs/powerbi-docs#4619]
The link on the bottom of the page referencing DQ over PBI datasets still says preview although that feature is now GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [DirectQuery in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gmuenster. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing that out, I've fixed that reference to clarify it's no longer in preview. Much appreciated.
