### ISSUE TITLE
Great input but could do with a little more

### ISSUE THREAD

**Issue by CBurton87** [MicrosoftDocs/powerbi-docs#4620]
Love this feature, however it would be extremely helpful if the analysis could be broken down by channels within the teams as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b915f0b3-9522-c54f-99a1-a5b4e3e9b3fa
* Version Independent ID: ab0ec929-ce56-b9f1-90a7-623b2ead4119
* Content: [Analyze Teams usage in the Power BI app for Teams - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-teams-analytics)
* Content Source: [powerbi-docs/collaborate-share/service-teams-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-teams-analytics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CBurton87. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @CBurton87, thanks for your feedback. You've reached the channel for docs feedback to the content writers, and it seems like your feedback is more about a feature enhancement. If that's the case, then I suggest you make the suggestion at https://ideas.fabric.microsoft.com/. Hope this helps!
