### ISSUE TITLE
Is the sample available as a download?

### ISSUE THREAD

**Issue by rphaturos** [MicrosoftDocs/powerbi-docs#4622]
Is the sample in this image available as a download?

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/42671187/94f172fe-0660-46d0-903d-fdb1461093b5)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Version Independent ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Content: [Create page and bookmark navigators - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/button-navigators.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/button-navigators.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rphaturos. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @rphaturos -- I asked the report creator. She says no, but pointed me to this report, which she says is similar:
https://1drv.ms/u/s!AhkMSncn4ZOYgoBDxBcXwoBWmrQrvQ?e=KvqjQ1
I hope that helps!

**Comment by rphaturos** [comment]
Thank you.
