### ISSUE TITLE
add dataset to Flow

### ISSUE THREAD

**Issue by rahulsawant01** [MicrosoftDocs/powerbi-docs#4624]
can we add this dataset in power automate flow? if yes then please share the steps

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b915f0b3-9522-c54f-99a1-a5b4e3e9b3fa
* Version Independent ID: ab0ec929-ce56-b9f1-90a7-623b2ead4119
* Content: [Analyze Teams usage in the Power BI app for Teams - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-teams-analytics)
* Content Source: [powerbi-docs/collaborate-share/service-teams-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-teams-analytics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rahulsawant01. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rahulsawant01, interesting question. However, you've reached the channel for docs feedback for the content writers. I am not sure about whether the dataset can be added in the power automate flow. I suggest you try the [Power BI Community](https://community.powerbi.com/). Someone there might be able to answer your question and provide the steps. Thanks for reaching out!
