### ISSUE TITLE
Migrate existing reports to Azure Maps- publish to web?

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4625]
In a future release, Power BI plans to deprecate older map visuals and migrate existing reports to Azure Maps.
[Enter feedback here]

Since Azure Maps does not support Publish to Web, what is the recommended solution for maps on reports that are published to web once the older map visuals are deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 735d805a-0981-4f84-12e7-b5560ea9c3bb
* Version Independent ID: d5dce962-ecf1-014e-65d9-00121fdd6d3c
* Content: [Tips and Tricks for maps (including Bing Maps integration) - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-map-tips-and-tricks)
* Content Source: [powerbi-docs/visuals/power-bi-map-tips-and-tricks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-map-tips-and-tricks.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
