### ISSUE TITLE
end of support for Python 3.7

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/powerbi-docs#4626]
Since it's [end of life](https://devguide.python.org/versions/#supported-versions) for version 3.7, when will your version upgrade?  Please also upload the upgraded version to Microsoft Store.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db4f2779-18a0-100c-dc5f-ac0f77f05d19
* Version Independent ID: e6654e84-bba6-8280-645a-5e56e999276e
* Content: [Learn which Python packages are supported - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-python-packages-support)
* Content Source: [powerbi-docs/connect-data/service-python-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-python-packages-support.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rootsmusic. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @rootsmusic, thanks for the feedback. I have passed it on to the person who maintains that document for consideration.
@otarb, can you take a look at @rootsmusic's input and take appropriate action, if necessary? Thanks.
I am closing this issue now, but please feel free both of you to continue the conversation.
