### ISSUE TITLE
example shows error

### ISSUE THREAD

**Issue by Sree-Ranjini** [MicrosoftDocs/powerbi-docs#4628]
[Enter feedback here]
sample pbix shows error while following step
An error occured while running analysis

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 946c17db-7cc8-70d7-45d5-5502fe115f67
* Version Independent ID: 62a891ef-32c6-9913-699c-dfed292839d7
* Content: [Anomaly detection tutorial - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-anomaly-detection)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-anomaly-detection.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TechnicalCode. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Sree-Ranjini, thanks for your feedback. I am going to close this issue now and move it over to our work item backlog for better consideration and tracking. Thanks again!
