### ISSUE TITLE
PROD.OUTLOOK.COM as sender

### ISSUE THREAD

**Issue by BraniBKA** [MicrosoftDocs/powerbi-docs#4629]
Hi all

The subscriber receives the email via PROD.OUTLOOK.COM as sender. 

If we as a company, do want to be the sender and not PROD.OUTLOOK.COM, is there a setting to change this? Or is each email sent to a subscriber being sent via PROD.OUTLOOK.COM?

Many thanks
Brani

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BraniBKA. This issue has been assigned to the doc author for review.
