### ISSUE TITLE
editable text boxes

### ISSUE THREAD

**Issue by Rademenes44** [MicrosoftDocs/powerbi-docs#463]
"Text boxes in the Power BI report become editable text boxes in PowerPoint"
Is there any update on this feature? When it will be available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df1c4c0-80f9-f71a-175f-8362a29ad597
* Version Independent ID: c2a64e2a-ce65-dfb7-588a-381c145ab193
* Content: [Export reports from Power BI to PowerPoint - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint)
* Content Source: [powerbi-docs/consumer/end-user-powerpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-powerpoint.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @Rademenes44. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @Rademenes44 ,
For product related questions, please post your question in the Power BI forums: 
https://community.powerbi.com/t5/Forums/ct-p/Forums

and/or suggest a new feature by visiting ideas.powerbi.com.

Take care,
Michele
