### ISSUE TITLE
Request for updating of Reports vs Dashboards table in document.

### ISSUE THREAD

**Issue by FUNMTT** [MicrosoftDocs/powerbi-docs#4630]
Hi there,  

Came across this page when looking for a comparison between dashboards and reports, and noticed that this table is not fully aligned with that in another document page in Microsoft docs.
Comparing [https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards#dashboards-versus-reports](url) with [https://learn.microsoft.com/en-us/power-bi/consumer/end-user-dashboards#dashboards-vs-reports-for-power-bi-business-users](url)
Particularly the comparison for 
1. Filtering
2. Power BI Q&A
3. Can see underlying dataset tables and fields.

Your page was last updated on 02/07/2023 vs that page was last updated on 03/30/2023, so made this request on to this page as it was the older of the two. Thank you so much for your consideration and help in aligning both to reflect the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91935bb2-c486-cb9f-be71-ae18ad28cf96
* Version Independent ID: 761de430-9bc7-4d7d-4c56-d14e6354194c
* Content: [Intro to dashboards for Power BI designers - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards)
* Content Source: [powerbi-docs/create-reports/service-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FUNMTT. This issue has been assigned to the doc author for review.
