### ISSUE TITLE
Documentation should not be adhoc

### ISSUE THREAD

**Issue by rka05** [MicrosoftDocs/powerbi-docs#4631]
Documentation should be in sync with the example, which is being used for creating custom visual. Which make lot of senses.
I feel this document is totally outdated and just written theories, whereas all examples are with the deprecated APIs.

How can someone who is new in developing custom visual can understand these logic and implement this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2096cf9-d97d-4297-6146-e2e5b425e1f2
* Version Independent ID: 80d6fa15-6082-ed8a-a549-0154700bd37f
* Content: [Introduction to use Data view utils in Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/utils-dataview)
* Content Source: [powerbi-docs/developer/visuals/utils-dataview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/utils-dataview.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @rka05. I'll check with the engineers about updating the APIs.

**Comment by mberdugo** [comment]
Hi @rka05. After checking with the engineers, it seems the only deprecated API on this page is EnumerateObjectInstances which was replaced by FormattingModles API. I suggest doing the tutorials and if you still have questions, ask the [Power BI Community](https://community.powerbi.com/).
Good luck!
