### ISSUE TITLE
Adaption of default view potentially necessary

### ISSUE THREAD

**Issue by severin1992** [MicrosoftDocs/powerbi-docs#4634]
When creating a report directly via the "Integrate"->"Power BI" feature from a sharepoint list it might be that you don't get all data/columns from the sharepoint list. It is necessary to adapt the default view and add the necessary columns there. Please add this information in this version of Power BI or at least in this article. See also my [forum entry](https://community.fabric.microsoft.com/t5/Service/Column-does-not-appear-as-data-when-creating-a-quick-report-from/m-p/3295193/thread-id/198917). Thanks and best.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be7b35f1-76fc-3c6c-b97c-42b9724c7644
* Version Independent ID: edb54e4e-c730-5573-fe30-d331946a7c54
* Content: [Create a report quickly from a SharePoint list or library in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-quick-create-sharepoint-list)
* Content Source: [powerbi-docs/create-reports/service-quick-create-sharepoint-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-quick-create-sharepoint-list.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @severin1992. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @severin1992, I'm moving this issue to our work item backlog for better consideration and tracking, and closing it here in the meantime. Thanks for your suggestions!
