### ISSUE TITLE
Explicit mention of enterprise gateway

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4635]
Hi MS Docs Team,

I just got confirmation in my MS Ticket 2306280050000387 that the enterprise gateway cannot be used for refreshing datasets containing R Script in Power Query. This MS Docs only says that we should use Personal gateway but it is not explicitly saying that enterprise GW cannot be used.

Could you please explicitly mention in the section Considerations and limitations that the enterprise gateway cannot be used?

BR
Martin Kmec

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor#considerations-and-limitations)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Sounds like a good addition to me -- added, will be updated with the next publishing run. Thanks for your contribution.
