### ISSUE TITLE
Move From Em3 to an F32

### ISSUE THREAD

**Issue by stevenemyers** [MicrosoftDocs/powerbi-docs#4638]
Hello, 
 We use a Power BI Premium EM3 to share reports in Teams and internal Websites using the free license. 
As the F32 is equivalent to the EM3 would we still be still be able to share reports in Teams and internal Websites using the free license? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your question, @stevenemyers.
Yes, you should still be able to share reports in Teams and internal Websites using the free license.
