### ISSUE TITLE
DQ over AS is no longer in preview

### ISSUE THREAD

**Issue by barnabastoth16** [MicrosoftDocs/powerbi-docs#4639]
Small correction.
In [this section](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters#limitations) at the 3rd bullet DQ over AS still contains the text "preview" in the link body. However it is already in GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Version Independent ID: 5221841f-f47d-838f-7dae-a4b5a94cefa2
* Content: [Let report readers use field parameters to change visuals (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-field-parameters)
* Content Source: [powerbi-docs/create-reports/power-bi-field-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-field-parameters.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @barnabastoth16. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @barnabastoth16, thanks for your feedback. I've updated the doc and will close this issue now. Thanks!
