### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by dnavia** [MicrosoftDocs/powerbi-docs#464]
Hey,

I just went through the whole introduction tutorial and I noticed a few mistakes in the spanish subtitles (I'm latin so you can trust me).

- Table is tabla instead of mesa
- Performance is rendimiento instead of actuación

Those two changes may change a lot the meaning of the phrase.

I hope it helps! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comments and close read @dnavia. Apologies for the mistakes in the subtitles, we'll let the translators know about them. Much appreciated!
