### ISSUE TITLE
Layout updated

### ISSUE THREAD

**Issue by omerahm** [MicrosoftDocs/powerbi-docs#4641]
The layout of Power BI has been changed significantly and there is no way that we can check CTID and Data Location of Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe99dcd3-62d6-0f11-3b13-031eb65c426c
* Version Independent ID: c0dc599b-c84c-ae09-42a0-5c28bb635810
* Content: [Where is data for the Power BI service stored? - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located#how-to-find-the-default-region-for-your-organization)
* Content Source: [powerbi-docs/admin/service-admin-where-is-my-tenant-located.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-where-is-my-tenant-located.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @omerahm. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, this article has been significantly updated since your comments.
