### ISSUE TITLE
Make Power BI Desktop Proxy Aware using the WinINet API

### ISSUE THREAD

**Issue by loaderladdy-work** [MicrosoftDocs/powerbi-docs#4642]
I know the documentation for Power BI Desktop says it is not proxy aware, but Microsoft's own documentation for developers details how to design apps to consume Windows WinINet API to make the PBID behaviour like a real enterprise class application, especially as it is designed to be used by large organisations that typically use proxy servers to monitor what their staff are doing, both for the organisations protection and the protection of end users.

Please consider this an enhancement request for Power BI Desktop

Sincerely yours,

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 57120f28-dce7-01db-855c-33e40721776f
* Version Independent ID: e8c49eaf-3bed-ed73-0512-c7adda73bcb3
* Content: [Troubleshoot sign-in issues in Power BI Desktop - Power BI](https://learn.microsoft.com/en-gb/power-bi/connect-data/desktop-troubleshooting-sign-in#proxy-authentication-required-error)
* Content Source: [powerbi-docs/connect-data/desktop-troubleshooting-sign-in.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-troubleshooting-sign-in.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your input and enhancement request, Pete. We'll pass it along to the engineering teams.
