### ISSUE TITLE
Bulletpoint

### ISSUE THREAD

**Issue by Roman-Sin** [MicrosoftDocs/powerbi-docs#4644]
The Keep in mind section is awkward. Why are there number after some points, with a fake link ? 
+ The Question/Answer could be more clear to separate different questions (e.g Question only in bold, and make the space between the question and answer smaller)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Version Independent ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Content: [Power BI Desktop projects (PBIP) - Power BI](https://learn.microsoft.com/en-gb/power-bi/developer/projects/projects-overview)
* Content Source: [powerbi-docs/developer/projects/projects-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-overview.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Roman-Sin. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
There are no "fake links" here. Those are footnotes linked from the table above. While agreed that it doesn't look all that well, these list items appear as designed.
