### ISSUE TITLE
Trying to generate a simple PDF list report from Excel

### ISSUE THREAD

**Issue by Sockratise** [MicrosoftDocs/powerbi-docs#4645]
All I want to do is create a simple PDF report from Excel, not emulate the dam* spreadsheet.  You know, like:
Name  
Address    City  State   Zip
Phone 1
Phone 2
etc
____________________
next record, etc.
___________________ 
(next page, etc.)

There are too many fields, some with long content, to import into Word and make a table. 

This should not be rocket science, It should not require the Cloud, another program, fancy formatting, Mail Merge, scotch tape, anything like that. I am not an Excel expert and do NOT want to become one.

What has the world come to?  This was a no-brainer with spreadsheets 30 years ago. 
---
#### Document Details
⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d15b3b2-c33a-9293-a6f2-749d164d1f1c
* Version Independent ID: 5bafb24c-0e82-7b95-1bc5-468debe8111a
* Content: [Publish to Power BI from Microsoft Excel - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-publish-from-excel?redirectSourcePath=%252farticle%252f7342b49c-6567-4155-a7ac-acdc14d9ad0f)
* Content Source: [powerbi-docs/connect-data/service-publish-from-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-publish-from-excel.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sockratise. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments, you might find more assistance in an online search, or from the Power BI community at community.powerbi.com
