### ISSUE TITLE
PBI content consumers need Pro licensing with capacity SKUs? Seems incorrect.

### ISSUE THREAD

**Issue by MMullery** [MicrosoftDocs/powerbi-docs#4648]
[Enter feedback here]
The following line seems to be contradictory to the purpose of an A SKU - or any capacity based sku for that matter.
"With A SKUs, all users who consume content also require Pro licenses."

Above that it is noted that
"Content creators still need a [Power BI Pro license](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-purchasing-power-bi-pro), even if your organization uses Power BI Premium"
Which seems correct. Content creators always need a pro or PPU license.

It seems unlikely that the A SKU would require Pro licenses for content **consumers**. Since A SKUs are marketed as SKUs to support external users, like customers, how would someone account for unknown users hitting their web app containing Power BI reports? 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 438cf2c2-6f00-d09e-1bb9-05b7a1daa1fa
* Version Independent ID: 438cf2c2-6f00-d09e-1bb9-05b7a1daa1fa
* Content: [Purchase Power BI Premium for testing - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-premium-testing)
* Content Source: [powerbi-docs/enterprise/service-admin-premium-testing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-premium-testing.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MMullery. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @MMullery.

This looks like product feedback or a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).

You can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).
