### ISSUE TITLE
Incorrect limitation

### ISSUE THREAD

**Issue by MixolydianV** [MicrosoftDocs/powerbi-docs#4649]
The documentation under Considerations and Limitations states that when signing in as a guest user, "Direct publishing from Power BI desktop to the Power BI service" is not supported. However, it's possible to do this through the following steps:

1. Sign out of PBI Desktop
2. Open the sign-in page to PBI desktop
3. Press "Sign-in options"
4. Press "Sign in to an organization"
5. Enter the domain name of the org
6. Sign in with your guested account

This is a pretty cool bit of functionality and it's a shame that it doesn't appear to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b#considerations-and-limitations)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MixolydianV. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
closing for @ajburnle
