### ISSUE TITLE
Paginated reports do not require Power BI Premium

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4650]
Paginated reports do not require Power BI Premium anymore.
See https://powerbi.microsoft.com/en-us/blog/announcing-support-for-paginated-reports-in-power-bi-pro/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Compare Power BI Report Server and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GitWesDone. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @GitWesDone, checking this one too. Thanks!
