### ISSUE TITLE
Plotly or ternary-diagram or mpltern or a power bi visual (probably the best option)

### ISSUE THREAD

**Issue by chiliverde** [MicrosoftDocs/powerbi-docs#4652]
Hi it would be nice to be able to create ternary diagrams in power bi. I'm a geologist working with Assay data and ternary diagrams are very useful for displaying this type of data. Plotly is great for creating ternary diagrams using plotly.express. matplotlib can also do it but needs the ternary-diagram library or mpltern library to do it. Another route would be to create a powerbi visual that can make these types of plots. Geoscientists around the world could use them to automate their ternary diagram plotting. 

Thank you!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6b7b4f-9f34-cec1-687c-2f5c708fe99f
* Version Independent ID: e66e6e43-157d-8331-20e2-89d1379c5251
* Content: [Create Power BI visuals using Python in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-visuals?source=recommendations)
* Content Source: [powerbi-docs/connect-data/desktop-python-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-python-visuals.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @chiliverde. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @chiliverde, thanks for your feedback. You've reached the channel for documentation feedback for the doc authors, and it sounds like you've got an idea regarding visuals you'd like to see. The best place for that is the ideas portal (https://ideas.fabric.microsoft.com/), where the product team can view suggestions, and other users can also vote for ideas they like. I suggest you visit that side and copy your suggestion into there. Good luck, and again, thanks for reaching out!
