### ISSUE TITLE
pbix file doesn't opened in PBI Desktop after chances in PBI Desktop with other app or model language

### ISSUE THREAD

**Issue by Zidcov** [MicrosoftDocs/powerbi-docs#4653]
A pbix file does not opened in an PBI Desktop with USA English app and model language after saving changes by another developer in PBI Desktop with Russian app and model language.
I'm not sure if it's because of the model language or the interfacing. I don't have time to experiment 
Problem has started from June 2023
All users have Version: 2.118.1063.0 64-bit (June 2023)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Zidcov. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Zidcov. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
