### ISSUE TITLE
Streaming datasets were removed from Premium

### ISSUE THREAD

**Issue by wgbrown** [MicrosoftDocs/powerbi-docs#4656]
Feature listed Streaming datasets was removed from Premium

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Version Independent ID: 8aaa37e4-51a4-928b-fdd8-8a2b2794c09e
* Content: [Power BI Premium features. - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-features)
* Content Source: [powerbi-docs/enterprise/service-premium-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-features.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @wgbrown,

We don't mention every Power BI feature in the Premium list. We try and mention the main features. It's also possible that streaming datasets is no longer a Premium feature (i.e. it can be used without Premium).

Thanks,

Kesem
