### ISSUE TITLE
Broken markdown link

### ISSUE THREAD

**Issue by lpasHex** [MicrosoftDocs/powerbi-docs#4657]
There's a broken markdown link here:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/136588691/a93a60af-7a57-42ea-890b-5a6246a22a6c)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 66f7e98b-d12a-5896-50c4-bd33f63481d0
* Version Independent ID: a1ccb451-0ba0-f4b5-63eb-22b62fcc93f6
* Content: [Basic concepts for designers in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-basic-concepts)
* Content Source: [powerbi-docs/fundamentals/service-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-basic-concepts.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by clairecharles** [comment]
Hi @bishalgoswami @mihart, I see this issue hasn't been fixed yet. I'd love to work on it.

**Comment by paulinbar** [comment]
Hey @clairecharles, are you still interested in fixing it? You know, you don't have to wait for us, you can create a PR and we'll review it and publish it if solves the problem. :)

@lpasHex, thanks for pointing this out. It's being worked on! :) Closing this issue for now.
