### ISSUE TITLE
Mumbo Jumbo

### ISSUE THREAD

**Issue by Quorthon-23** [MicrosoftDocs/powerbi-docs#4658]
More gobbledygook. What does this mean to the average Power BI user? It's far too technical and the examples use code samples. What's that got to do with relationships?. You are supposed to be explaining how they work, not write random code snippets. What's an active relationship, an inactive relationship, an active but indirect relationship, etc. This is the stuff that we are presented in error messages, so that's what you should be working on. Explain every error message. This is what would help people. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-create-and-manage-relationships)
* Content Source: [powerbi-docs/transform-model/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Quorthon-23. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look at providing more clarity to that article.
