### ISSUE TITLE
Incorrect Documentation

### ISSUE THREAD

**Issue by MMahmoodNationwide** [MicrosoftDocs/powerbi-docs#4660]
This line is wrong: All users who already have Read permission for datasets via app permissions, sharing, or workspace access also get Build permission for those datasets.

Users with Read permission do not have Build permission...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MMahmoodNationwide. This issue has been assigned to the doc author for review.
