### ISSUE TITLE
Error: On-Prem execution not supported for entity

### ISSUE THREAD

**Issue by Ryan34747** [MicrosoftDocs/powerbi-docs#4661]
Hello,
I did this on a Premium Per User workspace, in a new dataflow and mine will not refresh, keep getting the below error? Wondering if other users might get the same problem and how to resolve?

Error: On-Prem execution not supported for entity '<ccon>/ML_Test Training Data</ccon>' since it refers to another entity.. Param1 = <ccon>/ML_Test Training Data</ccon>.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a machine learning model in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-tutorial-build-machine-learning-model)
* Content Source: [powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
