### ISSUE TITLE
Custom tooltip totally obstructing the main report

### ISSUE THREAD

**Issue by Bifarin** [MicrosoftDocs/powerbi-docs#4665]
It's quite disappointing to see that the native tool tips background are relatively transparent and the custom ones are not. This unavailable feature in the custom version is taking away from the beauty and useability  of this very useful element of Dashboarding. 

Can we have the ability to set the background of a custom tooltip to be transparent?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 97cbbb3e-3916-4340-4ddc-67bf22159bf3
* Version Independent ID: 5b620628-1c10-b0bb-bd4d-1fd229260ea1
* Content: [Create report tooltip pages in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tooltips?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tooltips.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Bifarin. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Bifarin -- I'm checking with the product team to see if it's possible to format it as you're suggesting. I'll let you know what I find out.

**Comment by maggiesMSFT** [comment]
Hi, @Bifarin -- I checked. Currrently not possible, but on the product roadmap. So it's coming!
