### ISSUE TITLE
Power BI

### ISSUE THREAD

**Issue by tammyreservoir** [MicrosoftDocs/powerbi-docs#4666]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2368b421-38bc-b939-af6e-2cd36e3e752d
* Version Independent ID: 4c44f153-86e5-1f2b-5d04-705676475f96
* Content: [Types of Insights supported by Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-insight-types)
* Content Source: [powerbi-docs/consumer/end-user-insight-types.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-insight-types.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by paulinbar** [comment]
Hi @tammyreservoir, I don't see that you provided any specific feedback with your issue. I'm going to close it now, but feel free to reopen if you can provide some specific information. Thanks!
