### ISSUE TITLE
Remove the workspace has moved under Other in the WOrspace settings pane

### ISSUE THREAD

**Issue by ikhall** [MicrosoftDocs/powerbi-docs#4668]
"Remove the workspace" has been moved under the Other selstion of Worspace settings pane. 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/19318333/e6ba43b3-acbc-4d36-9ea1-efa363eadfca)

Apologies if I've done something wrong, this is my first time submitting an issue correction.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, dataset, or workspace - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-delete)
* Content Source: [powerbi-docs/create-reports/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-delete.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ikhall. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @ikhall, the article has been undated. Thanks for your feedback. You did great! :)
