### ISSUE TITLE
Link under See also needs to link to the Azure DevOps subpage and not to itself

### ISSUE THREAD

**Issue by mihagor** [MicrosoftDocs/powerbi-docs#4671]
[Enter feedback here]

Link under See also: Power BI Desktop projects Azure DevOps integration does not link to the right subpage. It references itself. 
The right link would be: 
https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-azdo. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa0561f3-eb9c-ecd5-b97a-52ecee0fc759
* Version Independent ID: aa0561f3-eb9c-ecd5-b97a-52ecee0fc759
* Content: [Git integration with Power BI Desktop projects - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-git)
* Content Source: [powerbi-docs/developer/projects/projects-git.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-git.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mihagor. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@mihagor - Thanks for pointing this out! We'll take care of it.
