### ISSUE TITLE
RLS creation

### ISSUE THREAD

**Issue by saiprasadb365** [MicrosoftDocs/powerbi-docs#4672]
With the new "Open data model" feature in Power BI service, roles can be created in Service too

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0ba6184-412b-7e75-ef74-46ae14d62dd6
* Version Independent ID: bf97c0bc-6511-e0f0-8df3-9e4f83492fe9
* Content: [Comparing Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-service-vs-desktop)
* Content Source: [powerbi-docs/fundamentals/service-service-vs-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-service-vs-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @saiprasadb365. This issue has been assigned to the doc author for review.

**Comment by sqlblog** [comment]
Why was this not picked up in the communication plan when editing in the service was rolled out?   Just sayin.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @saiprasadb365.
The Venn diagram will be updated accordingly.
