### ISSUE TITLE
Inconsistent illutrations

### ISSUE THREAD

**Issue by Abhra1992** [MicrosoftDocs/powerbi-docs#4673]
The page is unnecessarily confusing to follow and has inconsistent illustrations.
In Screenshot 2, it says the default location is selected, which is depicted as East US 2. In Screenshot 3, however, it says the tenant region is "Central Canada".
Even though the capacity is created in East US 2 in Screenshot 3, Screenshot 4 shows the location of the capacity as Canada Central.
Finally, Screenshot 4 and Screenshot 5 show different locations and different SKUs for the same capacity.

I understand that the screenshots may have been taken at different points in time, but the documentation should include consistent illustrations so that it is useful to follow.

Also, the narrative somehow gives the impression that a capacity can exist in multiple locations. It should be clearly depicted, that a capacity can only exist in one location, and to use multiple geos, one needs to create multiple capacities, one in each geo.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b52b044c-543a-212c-a8e3-db0871826713
* Version Independent ID: 3ee2c29b-5559-3396-4757-7ae3c236a909
* Content: [Multi-Geo support for Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-multi-geo)
* Content Source: [powerbi-docs/developer/embedded/embedded-multi-geo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-multi-geo.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Abhra1992. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your feedback, @Abhra1992. You're right, the screenshots were taken at different times so they have different values. Sorry for the confusion. I'll fix it soon.
