### ISSUE TITLE
PowerBi App Dark Mode - Apply Filter Button Hidden

### ISSUE THREAD

**Issue by SAIMMINHAS** [MicrosoftDocs/powerbi-docs#4674]
One of our users is having an issue related to PowerBi App on her iOS device. Below is her issue:

This is one to be raised with Microsoft. I have installed the PowerBi mobile app on my iOS device and I had massive trouble today filtering a report. I worked out that the apply filter button was there, but because my phone was in dark mode it is not showing as it’s not been coded in the appropriate colour so it shows on the background. I have attached a screenshot with the phone in normal mode where you can see the button, and then in dark mode where it vanishes - even though it is functionally actually there, so you can use it as long as you imagine where the button is on the screen.

This is a bug that needs raising with Microsoft please.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/30388154/9884810f-aff3-4697-950f-f8b15bb247c4)

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/30388154/9e31836f-092f-4090-8f2a-563f147189ff)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 774bf332-1b5f-4892-3bf5-999ba91930b7
* Version Independent ID: 02020144-c4dc-6be5-2e55-f7cbe96e7ea5
* Content: [Fixing 'communication failures' in iOS mobile apps - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/mobile/mobile-known-issues-with-the-iphone-app)
* Content Source: [powerbi-docs/consumer/mobile/mobile-known-issues-with-the-iphone-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-known-issues-with-the-iphone-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SAIMMINHAS. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @SAIMMINHAS, thanks for forwarding this along to us. I in turn have forwarded it along to the product team for consideration. Thanks!

**Comment by SAIMMINHAS** [comment]
Hi Paul,
Many thanks. I'll let the user know about it.

**Comment by SAIMMINHAS** [comment]
Hi @paulinbar 
Many thanks for the update. Is it possible to get an update once the fix is released?

Waiting for your reply...

**Comment by paulinbar** [comment]
Hi @SAIMMINHAS, ok, no problem. I'll make a note to let you know.
