### ISSUE TITLE
 If no insights found are found

### ISSUE THREAD

**Issue by saffariniAon** [MicrosoftDocs/powerbi-docs#4679]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfe0644-acb8-beab-abc5-3f0d65cf36fa
* Version Independent ID: a368a4c7-8389-8c22-2dd6-811b601f2696
* Content: [Find Insights in your reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/insights)
* Content Source: [powerbi-docs/create-reports/insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @saffariniAon. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @saffariniAon, you've reached the channel for documentation feedback. I don't see any specific comment from you so I don't know what you're issue with the doc was. I am closing this issue now, but please feel free to reopen if you can provide some specific feedback. Thanks!
