### ISSUE TITLE
Unable to Add data destinations to complete tutorial.

### ISSUE THREAD

**Issue by james-pickens** [MicrosoftDocs/powerbi-docs#4682]
In the **Add a data destination** section, **Step 1** "With the DimDate table selected, from the Home tab, select Add data destination and then select the Lakehouse option menu item.", the Add data destination menu item is _**disabled**_ for the following tables:

**DimDate**
**DimCustomer**
**DimEmployee**
**DimProduct**
**DimStore**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Version Independent ID: c55d0f50-08ee-2361-fe1f-8a1e6df76dca
* Content: [Tutorial: Microsoft Fabric for Power BI users - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/fabric-get-started)
* Content Source: [powerbi-docs/fundamentals/fabric-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/fabric-get-started.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @itsnotaboutthecell
* Microsoft Alias: **alpowers**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @james-pickens. This issue has been assigned to the doc author for review.

**Comment by itsnotaboutthecell** [comment]
Hi @james-pickens can you provide some more guidance on "disabled", you would have to select each one at a time to configure the destination. I'm unsure if you were attempting to do all in bulk - but trying to understand where you may have possibly been stuck.

**Comment by andrewgaskins** [comment]
I am seeing the same thing as the OP. When I select the DimDate after changing the column type the Add data destination button is grayed out. 

Thanks!

**Comment by paulinbar** [comment]
@itsnotaboutthecell, can you comment?

**Comment by itsnotaboutthecell** [comment]
@andrewgaskins I had just clicked thru the tutorial again and was successfully able to add the DimDate table to a destination, are there any possible error messages that you're experiencing or is it being greyed out the only behavior at the moment?

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/44716363/0134443d-b34d-42d7-ab92-6111fe8cfef4)

**Comment by james-pickens** [comment]
I will attempt this again and let you know

**Comment by mberdugo** [comment]
Unfortunately, we have been unable to review this issue in a timely manner. We sincerely apologize for the delayed response. Both the product and documentation might have changed since this issue was opened. Therefore, we are closing this issue. If you feel that the problem persists, please respond to this issue with additional information.

Please continue to provide feedback about the documentation. We appreciate your contributions to our community.
