### ISSUE TITLE
Power BI doesn't show coloured headings in report view.

### ISSUE THREAD

**Issue by Quorthon-23** [MicrosoftDocs/powerbi-docs#4684]
You've mentioned here that Power BI shows coloured headings in report view, but the image doesn't show that. Can you change the image to one that does show the point you are trying to make.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f402391-8dfc-cfa4-89b1-335f7c9dad1c
* Version Independent ID: 31ba30b8-61df-54d2-f97c-93ba77319cba
* Content: [Model view in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationship-view)
* Content Source: [powerbi-docs/transform-model/desktop-relationship-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-relationship-view.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment and feedback. I've updated that article to describe how the colors in the Model view headings work, to be more specific, and made sure the colors in the image map the description and explanation. Thanks.
