### ISSUE TITLE
Information is incorrect. The sorting function does actually work in this way or it all. We need the ability to sort data in a visual by the data that is in that visual. Either repair the existing functions describe in the article so that it actually works, or include new UI elements that achieve the same result. Excruciating.

### ISSUE THREAD

**Issue by codywinchester** [MicrosoftDocs/powerbi-docs#4685]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc6eda16-f142-5163-b0af-38fa634d7e42
* Version Independent ID: 58599a34-91ac-4947-c2e5-a0508a554080
* Content: [Sort one column by another column in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-sort-by-column?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/desktop-sort-by-column.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-sort-by-column.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @codywinchester. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @codywinchester, We've had some other issues opened on this same topic, so I'm going to move this issue to our work item backlog for better consideration and tracking, and close it here in the meantime. We'll update the docs as necessary. Thanks for providing your feedback!

**Comment by codywinchester** [comment]
@paulinbar , I appreciate your reply and attention on this item. Thanks so much.
