### ISSUE TITLE
The link to the Tabular Editor is not working

### ISSUE THREAD

**Issue by bambam229** [MicrosoftDocs/powerbi-docs#4686]
The link in bullet point 2 is not working and is invalid to Tabular Editor.  I believe the new link is:  https://tabulareditor.com/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7fb699f-5c14-f5d5-8f32-1c1539f213d1
* Version Independent ID: a7fb699f-5c14-f5d5-8f32-1c1539f213d1
* Content: [Object-level security (OLS) with Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-ols?tabs=table)
* Content Source: [powerbi-docs/enterprise/service-admin-ols.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-ols.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bambam229. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @bambam229. The link is fixed.
