### ISSUE TITLE
Yeah... Right.

### ISSUE THREAD

**Issue by nlovelace** [MicrosoftDocs/powerbi-docs#4687]
[Enter feedback here]
I'm following these steps exactly and not able to use drill through. I must be missing something, but, the documentation doesn't tell me what I might be missing, or what I can or cannot use as the starting point of my drill through.
Thumbs down.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nlovelace. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @nlovelace, thanks for reaching out. Can you specify where exactly things start to go wrong?

**Comment by paulinbar** [comment]
Hi @nlovelace, I am going to close this issue here now, but please feel free to reopen if you can provide a bit more information about where things started to go wrong for you. Thanks!
