### ISSUE TITLE
Update screenshot "About Power BI"

### ISSUE THREAD

**Issue by R1k91** [MicrosoftDocs/powerbi-docs#4688]
the screenshot showing how to reach "about power bi" is out of date
this is the new look

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/57228476/b7c302a9-3e72-4388-9672-2d6a4099954f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe99dcd3-62d6-0f11-3b13-031eb65c426c
* Version Independent ID: c0dc599b-c84c-ae09-42a0-5c28bb635810
* Content: [Where is data for the Power BI service stored? - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-where-is-my-tenant-located)
* Content Source: [powerbi-docs/admin/service-admin-where-is-my-tenant-located.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-where-is-my-tenant-located.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @R1k91. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @R1k91, thanks for pointing this out. I've created a workitem to update the doc. Closing this issue now. Thanks for reaching out!
