### ISSUE TITLE
Upload does not work

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#469]
This page says: Beginning with the October 2018 release of Power BI Desktop, you can publish composite models to the Power BI service. For scheduled refresh and dashboard tile refresh, composite models in the Power BI service behave in the same way as Import models.

But when I try to upload a pbix file with a simple composite model (two direct query sources without any relationships between them and where reports only pull from one source or the other), it fails:
Unsupported preview feature
The Power BI service currently doesn't support datasets with composite models because it's a Power BI Desktop preview feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models)
* Content Source: [powerbi-docs/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-composite-models.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @jordanmills and apologies you're running into this trouble. Have you updated your version of Power BI Desktop? This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by jordanmills** [comment]
Can't even wait a couple of hours for confirmation before rushing to close the pesky work-generating issue?  I wish I could get away with delivering that level of service.

I'm running the latest version of power bi desktop (2.64.5285.741 64-bit (November 2018)).  I'm not sure how that is relevant though.  You create a pbix file, then go upload it to the web site, and it gives the noted error.  It's not like there's a whole lot that can change about the process.  

The documentation is wrong.  Again.  Apparently this isn't the first time this non-feature has been incorrectly included in this document.
