### ISSUE TITLE
Page Content does not match title

### ISSUE THREAD

**Issue by Cornan** [MicrosoftDocs/powerbi-docs#4690]
The page title suggests that it will help the reader to use the "Fields" pane, but it doesn't include any information about when and how the fields pane is displayed.

While the lower section contains a useful icon reference, the upper section describes a software change regarding changes to the fields pane.

Please add at least minimal content at the top to explain what steps a user would execute to cause the "Fields" pane to display in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 781ebece-b103-78ae-2c8a-8db99390f23d
* Version Independent ID: ca9c1aec-14fd-867a-1660-79fd33cb8158
* Content: [Use the Field list in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-field-list)
* Content Source: [powerbi-docs/transform-model/desktop-field-list.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-field-list.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Cornan. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your input. In current builds the Fields pane is (now) called the Data pane. I've updated the article to reflect that update, and to provide info on how to find that pane. Thanks for your suggestion!
