### ISSUE TITLE
The https://mran.microsoft.com/documents/what-is-r link is broken in this page.

### ISSUE THREAD

**Issue by ChristianTellefsen** [MicrosoftDocs/powerbi-docs#4691]
The https://mran.microsoft.com/documents/what-is-r link is broken in this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for reporting this -- that resource is no longer available, so I've removed the link. Thanks!
