### ISSUE TITLE
need a note to tell customer do a manual refresh at least one time

### ISSUE THREAD

**Issue by HaidongHuang-Microsoft** [MicrosoftDocs/powerbi-docs#4693]
[Enter feedback here]
In the section that says

By default, data changes in OneLake are automatically reflected in a Direct Lake dataset.

There should be a note telling the customer the have to perform at least one manual refresh (framing command) after the creation of the dataset, otherwise the auto sync manager will not work. It is from https://eng.ms/docs/cloud-ai-platform/azure-data/azure-data-intelligence-platform/data-cloud/power-bi/power-bi-troubleshooting-guides/troubleshooting/as_directlake_autosync_tsg   

The dataset must have been refreshed(framing) at least once such that auto sync manager knows which directlake table to poll.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Version Independent ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Content: [Learn about Direct Lake in Power BI and Microsoft Fabric - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#refresh)
* Content Source: [powerbi-docs/enterprise/directlake-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HaidongHuang-Microsoft. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
Please use internal channels.
