### ISSUE TITLE
Deleted reports still apear in Home tab in Service

### ISSUE THREAD

**Issue by gvggvg** [MicrosoftDocs/powerbi-docs#4694]
Deleted reports still apear in Home tab in Service in user account although they do not appear if you try to navigate to the report through the Workspace tab. It is impossible to delete such hanging reports from the admin account either as they do not appear in admin's Home tab, nor in the workspace in question. They are only visible (and active !) in the user account. Such hanging reports appear with no Workspace name in the Home tab.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/6566796/e3a36909-2732-4f6a-81f4-5a4194fc5b03)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744f5d32-18ed-9018-3003-c5f9bcb3d1ff
* Version Independent ID: e2123a9f-edef-5170-05c6-98d42bc9fd35
* Content: [Find content from Power BI service Home - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-home)
* Content Source: [powerbi-docs/consumer/end-user-home.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-home.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gvggvg. This issue has been assigned to the doc author for review.

**Comment by gvggvg** [comment]
OK. This is not just documentation issue. This is actually a serious security issue.

**Comment by paulinbar** [comment]
Hi @gvggvg, yes, this looks like it's not a docs issue. I would open a bug at [support.powerbi.com](https://support.fabric.microsoft.com/en-us/support/). Thanks!
