### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by lalliv** [MicrosoftDocs/powerbi-docs#4696]
In the following paragraph, English version mention "datamarts" and in Spanish says "dataflows(flujos de datos)": 

"Use datamarts when you need to:

Sort, filter, do simple aggregation visually or through expressions defined in SQL
For outputs that are results, sets, tables, and filtered tables of data
Provide accessible data through a SQL endpoint
Enable users who don’t have access to Power BI Desktop"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02e17802-d798-33a1-163d-bfe358953051
* Version Independent ID: 02e17802-d798-33a1-163d-bfe358953051
* Content: [Introduction to datamarts - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-overview)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lalliv. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for sending - that's a good catch, and datamarts and dataflows are certainly different. Will investigate.

**Comment by davidiseminger** [comment]
Our localization team is looking into the proper steps to fix the translation. Thanks for bringing this to our attention!
