### ISSUE TITLE
Help doesn't explain where Canvas settings are located

### ISSUE THREAD

**Issue by mrfnord** [MicrosoftDocs/powerbi-docs#4698]
There is no "Canvas" button on the Visualization tab. Searching for Canvas or Page Size yields no results. Need more info on navigating to the Canvas settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c47fd87-706c-8aa1-b12e-931cda2a0e07
* Version Independent ID: 83c11fd3-ba17-6267-b342-dd84930f2872
* Content: [Page display settings in a Power BI report - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-report-display-settings?tabs=powerbi-desktop#canvas-settings)
* Content Source: [powerbi-docs/create-reports/power-bi-report-display-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-report-display-settings.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mrfnord. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @mrfnord, they should be there on the Visualizations pane. I admit that this information isn't stated clearly enough in the article. Passing your feedback along. 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/54644589/0d8dce65-c926-407e-b388-5c22cd84b903)
