### ISSUE TITLE
so i am looking at the moving average tutorial page. please tutor the guy who made this. so unclear and unreadable.  every step written on this page is unclear,  he /she defly needs more education on this please do it. This is damaging Microsoft's reputation

### ISSUE THREAD

**Issue by jiangcheng1999** [MicrosoftDocs/powerbi-docs#4699]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 28e42436-53d2-710b-8ae7-5e92589ca8a2
* Version Independent ID: 28e42436-53d2-710b-8ae7-5e92589ca8a2
* Content: [Add a moving average to a chart in Power BI paginated report - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/report-design/visualizations/add-moving-average-chart-report-builder)
* Content Source: [powerbi-docs/paginated-reports/report-design/visualizations/add-moving-average-chart-report-builder.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/report-design/visualizations/add-moving-average-chart-report-builder.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jiangcheng1999. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @jiangcheng1999, thanks for taking time to record your feedback. I'm moving it over to our work load backlog and am closing this issue here. Again, thanks for reaching out.
