### ISSUE TITLE
Unable to view Color saturation

### ISSUE THREAD

**Issue by u00get3** [MicrosoftDocs/powerbi-docs#470]
I am unable to view Color saturation in https://docs.microsoft.com/en-us/learn/modules/build-your-first-power-bi-report/4-exercise-create-visuals-in-power-bi as instructed in "First visual
Drag the Overall rank field from the Fields pane to the Color saturation well in the Visualizations pane."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Getting data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @u00get3 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by cstorega** [comment]
@u00get3 we are currently investigating this. Thank you for your feedback.

**Comment by Scalisee** [comment]
They moved it, it's not nearly as intuitive. This field is now hidden within the format tab under data colors. If you click into the Advanced Controls link it will be controlled by the "Based on field" dropdown.

**Comment by cstorega** [comment]
We are processing the fix for this exercise, so you can expect to see the update within the next couple of days.

**Comment by rm12656** [comment]
Documentation linked below also needs updating to reflect the changed location of the "Color Saturation" feature. 

Also, the first two screenshots on the page show clustered column charts. This is misleading - as far as I can tell, clustered column charts do not support the Color Saturation feature. I am only able to see Format > Data Colors > Advanced Controls when a single field is listed under Fields > Values. 

Setting up a color gradient based or a single column bar chart, then adding a second field to Values reverts the the first column's color back to a single solid color.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by cstorega** [comment]
@mihart - this seems to be about the documentation, not Learn content?

**Comment by mihart** [comment]
@cstorega 
It's about both.  I'll fix it in the tips and tricks doc and leave it to you to fix it in the Learn content.

**Comment by cstorega** [comment]
@mihart the Learn course is fixed

**Comment by mihart** [comment]
@cstorega fixed in doc.  will publish after Jan 3rd.  Thanks everyone.
