### ISSUE TITLE
Use report themes in Power BI Desktop - Add Free Theme Generator

### ISSUE THREAD

**Issue by OscarValerock** [MicrosoftDocs/powerbi-docs#4703]
Hi,

Good afternoon. Would it be possible to add https://powerbithemegenerator.bibb.pro/ to the "More sources of report themes" section of the page?

In advance, thanks. regards, 

Oscar

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/60475729/ee618516-b15c-46ea-8f8c-c29d2c2bbd0e)

https://powerbithemegenerator.bibb.pro/
https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes#more-sources-of-report-themes

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use report themes in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-report-themes)
* Content Source: [powerbi-docs/create-reports/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-report-themes.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @OscarValerock. This issue has been assigned to the doc author for review.

**Comment by OscarValerock** [comment]
Thanks! 🤞

**Comment by maggiesMSFT** [comment]
Hi, @OscarValerock -- I'm checking. Thanks for your suggestion!
