### ISSUE TITLE
Need clarity around Network subnet details. 

### ISSUE THREAD

**Issue by Kash-msft** [MicrosoftDocs/powerbi-docs#4706]
[Document does not talk about what is criteria of choosing subnet length. Considering Power BI IP Requirements tie to any new Premium P/A/F level capacity, we should clearly indicate with example that how many IP are needed for solution size. EVen though VNET address space is private, Big Banks and companies are particular about IP Subnet allocations]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for secure access to Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links#create-a-virtual-network)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @Dandanzhang
* Microsoft Alias: **danzhang**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Kash-msft. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Kash-msft, I started an internal email for this.
