### ISSUE TITLE
Document Update Required for 500000 Limit for Live Connection

### ISSUE THREAD

**Issue by SanchitSood** [MicrosoftDocs/powerbi-docs#4709]
On PowerBI Service, i can see that the limit for "Live Connection" is 500,000 but it is not mentioned in the document. Kindly update the document

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @SanchitSood , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
