### ISSUE TITLE
Missing list of supported data sources

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4712]
In the following page:
https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-use-directquery

You can find this statement:

"For a full listing of data sources that support DirectQuery, see [Data sources supported by DirectQuery](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)."

There's no such full listing the power-bi-data-sources page. In particular it's not clear whether ODATA is supported or only relational databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c34c249-033f-4156-0abc-8d16cbe355a0
* Version Independent ID: 20dc29c2-9cb7-2322-e80b-3f801bc34cfe
* Content: [Power BI data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/power-bi-data-sources)
* Content Source: [powerbi-docs/connect-data/power-bi-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/power-bi-data-sources.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CarrieAnne** [comment]
It is a shame that this page has changed.  Back before 30th March it had more useful information for Power BI users with a grid showing which connectors supported the gateway, and that information is missing from the page which is now linked for Power Query .  Previous grid headers:
| Data source | Connect from Desktop | Connect and refresh from service | DirectQuery / Live connection | Gateway (supported) | Gateway (required) | Power BI Dataflows |

**Comment by davidiseminger** [comment]
Great point! We've recently changed how we identify support for DirectQuery, for better sustainability, and I've updated that article to reflect. Thanks for posting this, that update should appear in a day or so. 

Thanks again.
