### ISSUE TITLE
Wrong target link for GW Azure SSO

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4713]
Hi Team,
The current link in the item "Azure AD Single Sign-On (SSO) for Gateway" is pointing to general home page about Tenant settings. I believe it should be pointing to one of the specific pages, thought not sure which of the two:
https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sso-overview
https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-azure-active-directory-sso

The same issue is in the link in the Admin Portal:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/48448079/0ff74b12-2bb3-4bf2-9756-8164e42c5be1)

With best regards,
Martin Kmec

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 700f1531-6391-647b-788d-56d176c930e7
* Version Independent ID: 700f1531-6391-647b-788d-56d176c930e7
* Content: [About tenant settings - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-about-tenant-settings)
* Content Source: [powerbi-docs/admin/service-admin-portal-about-tenant-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/service-admin-portal-about-tenant-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @MartinKDK, thanks for the heads up, and for the suggested possibilities for the target. I've opened a work item for this and will follow up. It may take a few days until the fix is in place, but I'm going to close this issue here now since I've got the work item, if that's ok. Please reopen if you feel the need. Thanks again!

**Comment by paulinbar** [comment]
Hi @MartinKDK, should be fixed now. Thanks again for pointing this out!
