### ISSUE TITLE
Missing latest updates

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4714]
Hi Docs Team,
the July 2023 version was numbered 2.119.323 (https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop).
The current version in MS Download Center is 2.119.986.

Could you please update the ChangeLog with the latest QFE?

Thank you
With best regards,
Martin Kmec

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3105a7f-cb47-9cd9-7144-d5dca900f3f1
* Version Independent ID: 80da6829-c211-d086-df6c-92376e1d640f
* Content: [Change log for Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-change-log)
* Content Source: [powerbi-docs/fundamentals/desktop-change-log.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-change-log.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments -- we've uploaded the change log with information current to today. The information should be updated in the live content set within a day or so.
