### ISSUE TITLE
Doesn't work numerous errors while copy pasting code many missing function in api

### ISSUE THREAD

**Issue by CodeWithAbdurrehman** [MicrosoftDocs/powerbi-docs#4717]
[Enter feedback here]
documentation that doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3898acbd-6660-318e-a508-6ffba8418116
* Version Independent ID: 7edfb17e-b461-c8ac-45c4-1e38d294e3fd
* Content: [Creating a dialog box in a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-display-dialog-box)
* Content Source: [powerbi-docs/developer/visuals/create-display-dialog-box.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-display-dialog-box.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your feedback, @CodeWithAbdurrehman. I'll ask our engineers to review the code. Can you be more specific about which sections didn't work and what was missing?

**Comment by mberdugo** [comment]
Hi @CodeWithAbdurrehman. Thanks again for bringing this to our attention. I've added this to our backlog for better tracking while we rework this document.

**Comment by mberdugo** [comment]
Hi @CodeWithAbdurrehman. Thanks again for your feedback. This page has been reviewed and the code updated. It might take a day or so until the changes are live.
Good luck.
