### ISSUE TITLE
Push Datasets not working in PowerShell 7 without useragent declared

### ISSUE THREAD

**Issue by gtowsey** [MicrosoftDocs/powerbi-docs#4719]
Hi,

We have discovered push datasets are not working in PowerShell 7.3 (local install), 7.2 via azure automate, 7.1 via azure automation and 5.1 via azure automation without useragent declared. it does work with 5.1 locally.

This is the case when using the below commands

$a = Invoke-RestMethod -Method Post -Uri "$endpoint" -Body (ConvertTo-Json @($output)) 
$a = Invoke-WebRequest -Method post -Uri "$endpoint" -Body (ConvertTo-Json @($output)) 

The return value is a 200 however the datasets do not update.

To workaround this we discovered that declaring the useragent (any useragent works) via the example below resolves this issue and teh dataset updates correctly in all the above versions

$userAgent = [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
$a = Invoke-WebRequest -Method post -Uri "$endpoint" -Body (ConvertTo-Json @($output)) -useragent $useragent. 

It appears the default useragent is causing some kind of issues in the mentioned versions

![example of working and not working outputs](https://github.com/MicrosoftDocs/powerbi-docs/assets/35312555/81222d9a-3182-4306-86b3-d9322e1abbdc)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gtowsey. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thank you for this information @gtowsey. I'll pass it on to the relevant engineers.
