### ISSUE TITLE
Navigational menu changed

### ISSUE THREAD

**Issue by geo101** [MicrosoftDocs/powerbi-docs#4724]
The document refers to the location "Billing->Purchase Services" to purchase licenses.  However, that has been changed to "Marketplace".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5f9906-58f7-9b21-85ee-8d33ffcbdce0
* Version Independent ID: 712e418a-5290-fe94-e9b0-6fa84ec1c7cb
* Content: [Purchase and assign Power BI Pro licenses - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-purchasing-power-bi-pro)
* Content Source: [powerbi-docs/enterprise/service-admin-purchasing-power-bi-pro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-purchasing-power-bi-pro.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @geo101. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @geo101 ,
Thank you for your suggestion.  We will be updating our licensing documentation after the Ignite conference.
All the best,
The DOCS team.
