### ISSUE TITLE
Image in "Create a dynamic subscription" section has wrong button highlighted

### ISSUE THREAD

**Issue by mibruhje** [MicrosoftDocs/powerbi-docs#4725]
Image in "Create a dynamic subscription" section should have red box around "Parameters" button, not subscription button. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5d618c4-8c58-b82f-2b59-0eb75364afe9
* Version Independent ID: a5d618c4-8c58-b82f-2b59-0eb75364afe9
* Content: [Create a dynamic subscription (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/dynamic-subscriptions)
* Content Source: [powerbi-docs/collaborate-share/dynamic-subscriptions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/dynamic-subscriptions.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mibruhje. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @mibruhje ,
All fixed :-)
