### ISSUE TITLE
New Workspaces & Row-Level Security

### ISSUE THREAD

**Issue by gnutter** [MicrosoftDocs/powerbi-docs#473]
The new workspaces do not seem to work with the row-level security features built into reports. This may be due to the lack of the "Members can only view Power BI content" option when creating the workspace. I tried both the "member" and "contributor"  options, but users can see all content and not just the roles I have built. Let me know if I am missing something. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @gnutter -- good question! I don't know the answer. I suggest going to https://community.powerbi.com/ and asking. You may get a faster response than I would. Thanks!

**Comment by DaveRuijter** [comment]
Are you sharing the App? Or adding users as members?

**Comment by simoualhi** [comment]
The RLS is not working when workspace members can edit content, with the new way to create the workspaces we have three type of users, to apply RLS I suppose we will need the user Viewer

**Comment by maggiesMSFT** [comment]
Yes, this is correct @gnutter -- currently RLS is not working in the new workspaces. Continue using the classic workspaces for now.
