### ISSUE TITLE
Prerequisites missing SharePoint SE as an option

### ISSUE THREAD

**Issue by getalex** [MicrosoftDocs/powerbi-docs#4730]
The article lists under prerequisites SharePoint 2013, 2016, or 2019 but does not include SE -- I don't see any technical limitation for this, so I wanted to point out to include SE in the list or mention why SharePoint SE is not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [Embed a Power BI Report Server report using an iFrame in SharePoint Server - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/quickstart-embed#next-steps)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @getalex. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @getalex. I'll investigate.

**Comment by getalex** [comment]
Looking to get an update on this matter. Thank you!

**Comment by maggiesMSFT** [comment]
Got the update, updating the article. Yes, SharePoint SE _is_ supported. Change will be live tomorrow afternoon Pacific time. 
Thanks for asking, @getalex !
