### ISSUE TITLE
Hard to understand. 

### ISSUE THREAD

**Issue by dineshj231** [MicrosoftDocs/powerbi-docs#4731]
I always have to go to an youtube video or another non-Microsoft article for reference. These written by Microsoft are terrible because they are hard to understand and not an easy read. 

I would ask you do a better job of writing articles. Maybe hire an English major to assist you. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae01e9b-bd39-c224-badf-4078d1df8be4
* Version Independent ID: 57caeb1f-c8f1-7fa5-d37f-b550beb75bfc
* Content: [Active vs inactive relationship guidance - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/relationships-active-inactive)
* Content Source: [powerbi-docs/guidance/relationships-active-inactive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/relationships-active-inactive.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dineshj231. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll look at improving that article's readability and understandability.
