### ISSUE TITLE
How does one create the aggregate table in the first place?

### ISSUE THREAD

**Issue by JonathanBrune** [MicrosoftDocs/powerbi-docs#4734]
I think it would be good to have more information on how to add the aggregate table, not just adding aggration.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [User-defined aggregations - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/aggregations-advanced)
* Content Source: [powerbi-docs/transform-model/aggregations-advanced.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/aggregations-advanced.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JonathanBrune. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
Clearing backlog. This issue will not be addressed.
