### ISSUE TITLE
I have a Power BI Pro account but don't have the Publish to Web (public) option

### ISSUE THREAD

**Issue by TheChrisTroutner** [MicrosoftDocs/powerbi-docs#4736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Publish to web from Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web)
* Content Source: [powerbi-docs/collaborate-share/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @TheChrisTroutner. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @TheChrisTroutner -- have you perused the list of Considerations and limitations? It's pretty extensive. Are you sure that your situation doesn't violate any of them? 
https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-publish-to-web#considerations-and-limitations
Some of them are common situations. For example, here are the first 7 exceptions that would prevent you from using Publish to web:

- Reports using row-level security.
- Reports connecting to data using DirectQuery. Connect using composite or import mode instead. Read about the [differences between the modes](https://learn.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand).
- Reports using any Live Connection data source, including Analysis Services Tabular hosted on-premises, Analysis Services Multidimensional, and Azure Analysis Services.
- Reports using a [shared dataset](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-across-workspaces) that is stored in a different workspace from the report.
- [Shared and certified datasets](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-share).
- Reports shared to you directly or through an app.
- Reports in a workspace in which you aren't an edit member.

**Comment by TheChrisTroutner** [comment]
This has been resolved, thanks!

**Comment by maggiesMSFT** [comment]
Thanks for letting us know, @TheChrisTroutner! Closing the issue.
