### ISSUE TITLE
Sample for page navigation custom visual

### ISSUE THREAD

**Issue by MartinBubenheimer** [MicrosoftDocs/powerbi-docs#4740]
I'd love to see a sample solution in the Power BI custom visuals samples that shows how to build something like the page navigation visual in Power BI.
References: 
https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/visuals/samples.md
https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop#page-navigator

**Comment by KesemSharabi** [comment]
Hi @MartinBubenheimer,

I'll pass your suggestion on to the PM that's in charge of Power BI visuals.

You can also submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi) and/or engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

Thanks,

Kesem
