### ISSUE TITLE
Outdated information about workspace's grace period in the localized document

### ISSUE THREAD

**Issue by takawazo** [MicrosoftDocs/powerbi-docs#4741]
In the English version, it shows grace period is 30 days in the workspace states.
On the contrary, it shows grace period is 90 days, which is not correct, in the Japanese localized version.
It looks like update date is 4 month behind for Japanese version.

Updated at 07/27/2023
https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal-workspaces

Updated at 3/22/2023
https://learn.microsoft.com/ja-jp/power-bi/admin/service-admin-portal-workspaces

**Comment by bishalgoswami** [comment]
Thanks for your comment, @takawazo. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @takawazo,

Thank you for pointing out this issue. The wrong number in the localized Japanese page was corrected.

Kesem
