### ISSUE TITLE
Power BI App, Refresh setting is not possible ?

### ISSUE THREAD

**Issue by GGBMLC** [MicrosoftDocs/powerbi-docs#4742]
[Enter feedback here]
Refresh setting for Power BI App. 
I have one dataset there is setup to get data 6 time pr. day from my SQL server. That is ok, and works fine.

But now the report in Power BI App do not get this new data?
I also not able to set Refresh in the Power BI App.  under >Datasets>Refresh 

WHY??????

---
![power bi app](https://github.com/MicrosoftDocs/powerbi-docs/assets/92221040/0c858ba0-f7dc-48f4-bcb1-fc209391f9f3)

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GGBMLC. This issue has been assigned to the doc author for review.

**Comment by GGBMLC** [comment]
I solved the issue by check the dataset again. 
The data set in the premium workspace needs new gateway connection setting. (WHY is not just copy when it is added to the APP ?
But now I can set the refresh time.

**Comment by davidiseminger** [comment]
Glad to hear you were able to find a solution.
