### ISSUE TITLE
Inclusion of Analysis Services in Power Query limitation

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4747]
Regarding this limitation (quote from page):

> The connection to a Power BI dataset won't be shown in Power Query.

From empirical testing it also appears to apply to AS models, at least for SSAS 2022. I think the scoping to Power BI datasets only may be in this document for historical reasons, from before AS support for composite models was introduced.

With this in mind, should the sentence be expanded to something like the following?

> The connection to a Power BI dataset or Analysis Services model won't be shown in Power Query.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models)
* Content Source: [powerbi-docs/transform-model/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! Thanks for the close read, I'll add your suggestion to the article. Thanks!
