### ISSUE TITLE
Delineate between Zone failover and Region failover (DR Event)

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#4749]
[Enter feedback here]

It is not clear from this doc that there is a difference between Zone failover and Region failover / DR Scenario.  

I was in a call with a FabricCAT person and customer today and it was stated that 
- Zone failover can be done in 30 seconds and Power BI will continue to function without any limitations.  
- In a Region failover / DR scenario, is done in 15 minutes (more or less depending on the situation) and Power BI is available in read only mode. 

The doc speaks to the 2nd point but not the first.  At a minimum, it would be helpful to include a blurb about Zone failover to the top of the document (30 seconds and Power BI continuing to function without any limitation).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8ae7715f-ecbe-4d43-de96-6ec3459e59f0
* Version Independent ID: 8ae7715f-ecbe-4d43-de96-6ec3459e59f0
* Content: [Power BI high availability, failover, and disaster recovery FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-failover)
* Content Source: [powerbi-docs/enterprise/service-admin-failover.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-failover.yml)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kfollis**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfohl. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
That's a good addition, thanks! We'll update that article with the blurb.
