### ISSUE TITLE
Power BI Premium - Usage Metrics App - Query Durations & Query Waits no longer working

### ISSUE THREAD

**Issue by dsutherlandafex** [MicrosoftDocs/powerbi-docs#475]
Since updating the Premium Usage Metrics app to V1.9, I am no longer getting any 'Query Durations' or 'Query Waits' data being populated.

I have tried deleting the app and re-installing but this did not fix the issue.

![snip - query durations](https://user-images.githubusercontent.com/37163410/49054539-b00cdc00-f248-11e8-936f-e282f3f99475.jpg)
![snip - query waits](https://user-images.githubusercontent.com/37163410/49054541-b00cdc00-f248-11e8-9cb7-4089985eec7e.jpg)

**Comment by mgblythe** [comment]
Thanks @dsutherlandafex, adding @swgupt to see if she has any insight here.

**Comment by dsutherlandafex** [comment]
Thank you.... please also not that in addition to the Query metrics not working..... it appears the 'Dataset' metrics are also not capturing (screenshots attached)
![dataset issue - further](https://user-images.githubusercontent.com/37163410/49187475-bb344900-f3bb-11e8-8f2e-9366e2c2e4fb.jpg)
![dataset issue](https://user-images.githubusercontent.com/37163410/49187476-bb344900-f3bb-11e8-94d5-b1ea5c69d867.jpg)

**Comment by mgblythe** [comment]
Would still like to hear from @swgupt on this, but did this resolve with new app install? If you still have issues, please contact support: https://powerbi.microsoft.com/en-us/support/. Thanks!

**Comment by dsutherlandafex** [comment]
Yes this is now fixed. Many thanks
