### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerbi-docs#4750]
Small error.
This sentence...
"Sort to view the top CPUs that consumed Power BI items over the past two weeks."
...is back to front.
It should read:
"Sort to view the top Power BI items that consumed CPUs over the past two weeks."
Cheers.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4843cde8-6191-2773-7500-272b87ad8084
* Version Independent ID: 27ff08bc-43e8-4c8d-2cf5-ad096b6f11ff
* Content: [Monitor Power BI Premium capacities with the Premium metrics app. - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @@Dan1480,

Thanks for spotting this and for letting us know. I will fix this mistake shortly.

Kesem
