### ISSUE TITLE
This is very inaccurate

### ISSUE THREAD

**Issue by CodyConner** [MicrosoftDocs/powerbi-docs#4751]
[Enter feedback here]
I assume this page is extremely out-of-date. The options it has you start with are wrong. Currently, the only way to create a paginated report is in the service and it looks nothing like the example. As it is, the tutorial is useless for creating a paginated report. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98ce098f-9ce5-58fc-d62e-6346ee6a4f13
* Version Independent ID: 0316a08b-470d-e711-44b2-e369fd792de3
* Content: [Tutorial: Create a paginated report and upload it to the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-quickstart-aw)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-quickstart-aw.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-quickstart-aw.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @CodyConner. This issue has been assigned to the doc author for review.

**Comment by CodyConner** [comment]
I appreciate that. After making the comment, I realized that I had been looking for the wrong thing. The document is indeed correct. I simply misread the beginning portion of the document.

   [Logo, company name  Description automatically generated]
Cody Conner
Senior Analyst
970-795-2772
www.capitalizeanalytics.com<http://www.capitalizeanalytics.com/>

**Comment by maggiesMSFT** [comment]
Thanks for letting me know the article is OK as is, @CodyConner! I appreciate you taking the time to tell me 😁
