### ISSUE TITLE
Missing information on "View As" from Modeling ribbon

### ISSUE THREAD

**Issue by EXSchott** [MicrosoftDocs/powerbi-docs#4752]
[Enter feedback here]
There's no indication on how to get to the model view to "View As" in the report you are building connected to the dataset.   I wouldn't expect to change the model here but if I can't view as one of the security members I'm seeing duplicate wrong data that would have been filtered out and can't correctly size the visuals.   If it's not possible to do that when connected to a dataset then that should be clearly indicated so folks know to use an alternate method/product.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a254362d-15ad-96e4-3eed-1af41783843a
* Version Independent ID: cb9f4fb9-1d07-81c6-466f-a2682b18e574
* Content: [Separate reports from models in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/report-separate-from-model)
* Content Source: [powerbi-docs/guidance/report-separate-from-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/report-separate-from-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @EXSchott. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, we'll review that article and look at adding more clarity around View As.
