### ISSUE TITLE
An unintuitive feature that encourages data breach

### ISSUE THREAD

**Issue by dgriggs125** [MicrosoftDocs/powerbi-docs#4753]
What an absolutely stupid idea this is! Why would you allow shared links to by-pass all the security permissions set up on the workspace?

When people see that share button, they would instantly think it's totally safe to send to people in their team who they know also have access to the workspace, not thinking twice if that URL were shared more widely, every man and his dog can see the report too.

This is a major data breach waiting to happen, I suggest Microsoft re-thinks this design.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dgriggs125. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @dgriggs125 -- thanks for your comment! Because it's about the product more than the documentation, I'm going to close this and direct you to the Feedback site for Power BI and Fabric, https://ideas.fabric.microsoft.com/?forum=2d80fd4a-16cb-4189-896b-e0dac5e08b41
