### ISSUE TITLE
You might indicate on this page that the solution of exporting to Excel instead only exists in the service, NOT in the desktop app.

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#4755]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4abf36c7-f5d8-3e53-e0c8-a9a6cbb40370
* Version Independent ID: 4abf36c7-f5d8-3e53-e0c8-a9a6cbb40370
* Content: [Known issue - Export to CSV file truncated at 300 rows - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-498-export-csv-file-truncated-300-rows)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-498-export-csv-file-truncated-300-rows.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-498-export-csv-file-truncated-300-rows.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **jessicamo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nicheplayer. This issue has been assigned to the doc author for review.

**Comment by amanda-lamb** [comment]
We just started having it happen on the desktop app also, seems like it is working now from the PBI service.

**Comment by mihart** [comment]
Hi @nicheplayer , 
Thank you for your suggestion.  Looks like this known issue is now fixed.  If it is still happening in Desktop, please let us know. 
All the best,
The DOCS team
