### ISSUE TITLE
Change Sales Manager's Name

### ISSUE THREAD

**Issue by nrjmatta** [MicrosoftDocs/powerbi-docs#4756]
Suggest to use a different sales managers' name! 

Since this is a Power BI article, Jan, Feb, etc. subconsciously are treated as month names.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 014eede5-d529-cc7c-f8d5-3e7247ee857c
* Version Independent ID: 524645c5-86ea-ef3e-a020-c74b44db2c87
* Content: [Measures in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-measures)
* Content Source: [powerbi-docs/transform-model/desktop-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-measures.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @nrjmatta. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Great point @nrjmatta, totally agree! Made the change from Jan > Janice, should show up later today. Thanks for the suggestion!
