### ISSUE TITLE
Create a link to a specific location in the Power BI mobile apps

### ISSUE THREAD

**Issue by ericjia888** [MicrosoftDocs/powerbi-docs#4758]
Can this be done with locally deployed Power BI?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80ed5d7c-7973-17bd-8a5a-2b80c33eab2c
* Version Independent ID: 71e8bc7e-55a5-fb95-4805-34a2be26a0ed
* Content: [Create a link to a specific location in the Power BI mobile apps - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/mobile/mobile-apps-deep-link-specific-location)
* Content Source: [powerbi-docs/consumer/mobile/mobile-apps-deep-link-specific-location.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-apps-deep-link-specific-location.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ericjia888. This issue has been assigned to the doc author for review.
