### ISSUE TITLE
Screenshot not updated

### ISSUE THREAD

**Issue by R1k91** [MicrosoftDocs/powerbi-docs#4759]
the screenshot at point 1 in the list is not updated.
this is the new look of the UI.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/57228476/3902c3b9-d278-4732-a9c4-730f2ecf4aee)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/connect-data/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @R1k91. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your help and suggestion. We've updated that screenshot.
