### ISSUE TITLE
dataset does not show up

### ISSUE THREAD

**Issue by gregatcssi** [MicrosoftDocs/powerbi-docs#476]
I am attempting to build a bit more of a custom report for a client, but the dataset does not show up as stated above.  (step 3. Alternately, start with the new dataset and build a report from scratch.)
I need in add an additional table which would provide a little more information on users from another source, and without access to the data model that really limits possibilities of this.  also an Export to PBIX would be amazing or 
if this is not possible from the template hopefully a document providing the web api would save a lot of time and effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 719feeea-d688-78bf-fef5-8b58c2fb047f
* Version Independent ID: 78793fa4-e2e2-7113-3652-b1165ee92145
* Content: [Usage metrics for dashboards and reports - Power BI](https://docs.microsoft.com/en-us/power-bi/service-usage-metrics)
* Content Source: [powerbi-docs/service-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-usage-metrics.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @gregatcssi . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. In the meantime, you could ask your question in the community: https://community.powerbi.com/.

**Comment by syedaqibm** [comment]
Hello, Is there a way to get usage metrics for 1 year instead of 90 days?

**Comment by jiteshparwal93** [comment]
@mgblythe: I still see document is not updated regarding dataset. However, we cant see dataset for usage metrics. Can you please ask user to update document

**Comment by KDAylesworth** [comment]
The usage metrics are not showing up for items in an App that I created. This issue has been reported by other people on the Power BI community site, but so far I have not seen a solution.

**Comment by g33kay** [comment]
Tried creating the copy of the Usage Metrics, however, the dataset is not getting added. Any additional settings i need to enable to create the dataset?

**Comment by maggiesMSFT** [comment]
Hi all -- thanks for your questions. Working on answers. I have one so far, for @KDAylesworth: 
Yes, we are aware of this issue and we’re investigating it right now. We currently don’t have a timeline to share for a fix.
More to come --

**Comment by KDAylesworth** [comment]
@maggieMSFT -- I just found a workaround that was posted in the Power BI user community on 5/1/2019. Here is the link: https://community.powerbi.com/t5/Service/Power-BI-App-no-usage-metrics/td-p/229453/page/2

**Comment by KDAylesworth** [comment]
@maggiesMSFT -- sorry I tagged you incorrectly the first time -- I just found a workaround that was posted in the Power BI user community on 5/1/2019. Here is the link: https://community.powerbi.com/t5/Service/Power-BI-App-no-usage-metrics/td-p/229453/page/2

**Comment by maggiesMSFT** [comment]
Hi, @KDAylesworth -- I realize I updated the article with the info about seeing data for the whole workspace, but I didn't mention it. I added this section: https://docs.microsoft.com/en-us/power-bi/service-usage-metrics#see-all-workspace-usage-metrics. 
Thanks again!
