### ISSUE TITLE
Why is it not possible to connect Python/R to Power BI through WSL 2?

### ISSUE THREAD

**Issue by vasilygrz** [MicrosoftDocs/powerbi-docs#4760]
I'm currently on a new learning journey, recently upgraded to Windows 11 and discovered WSL 2. As a Power BI beginner user, I've tried to set both the Python and R home directories to the bin folders I already have in WSL 2 and it refuses to open them.

Can you please explain how Power BI interfaces Python and R so a connection through WSL 2 is not possible? I couldn't find an answer in the documentation.

In 'Create a [Python](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-scripts#enable-python-scripting)/[R](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-scripts#run-your-r-script-and-import-data) script', it's not mentioned that WSL 2 directories can't be used.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @vasilygrz. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bishalgoswami. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
