### ISSUE TITLE
 Links corresponding to the "learn more" contents are missed

### ISSUE THREAD

**Issue by AlexWuSh** [MicrosoftDocs/powerbi-docs#4761]
hi

Looks like the links corresponding to the "learn more" contents in the page are missed. 

Can you please provide them? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cfe0644-acb8-beab-abc5-3f0d65cf36fa
* Version Independent ID: a368a4c7-8389-8c22-2dd6-811b601f2696
* Content: [Find Insights in your reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/insights)
* Content Source: [powerbi-docs/create-reports/insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @aphilip94
* Microsoft Alias: **anphil**

**Comment by AlexWuSh** [comment]
@bishalgoswami hi, any updates? Thanks!

**Comment by KesemSharabi** [comment]
Hi @AlexWuSh,

We're looking into this issue.

Thanks for alerting us of the missing links.

Kesem

**Comment by davidiseminger** [comment]
The Next Steps (previously Learn More) links are working. Thanks for your feedback.
