### ISSUE TITLE
license powerbi usertype guest vs member

### ISSUE THREAD

**Issue by ClaudioTorresAcevedo** [MicrosoftDocs/powerbi-docs#4762]
This text below:
"There are some limitations to the B2B experience that you should be aware of:

Guest users may already have a Power BI license that was assigned to them through their own organization. But “Bring your own license” doesn’t work across different Microsoft Azure clouds. A new license has to be assigned to these guest users by the provider tenant."

This is only valid when the usertype is member and not for all b2b collaboration right? Regular external-guest registered users brings their licenses over without issues as far as I can see.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Azure AD B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b#who-can-you-invite)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ClaudioTorresAcevedo. This issue has been assigned to the doc author for review.

**Comment by ajburnle** [comment]
Thanks for your feedback! The content has been updated.

**Comment by maggiesMSFT** [comment]
closing for @ajburnle
