### ISSUE TITLE
Release Status?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4763]
What's the release status of this capability? Is it GA or public preview? Or a mix, depending on the feature used?

The only note about release status is this one within the page:

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/1765732/90a26f33-75f5-4750-974e-bfcc8c48e09b)

Does this mean everything is GA except for that authentication option? Or everything is in public preview and the global disclaimer is missing from the top of the page?

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a835a554-a786-d48e-4ef8-154d3946514f
* Version Independent ID: ee115c37-f292-576c-deb3-e76496111371
* Content: [Power BI gateway and Report Builder support for ODBC data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-odbc-support)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-odbc-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-odbc-support.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- I'll check.

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- good catch. I updated the note to read: "The Anonymous authentication method isn't supported." Change will be live tomorrow afternoon, 9/28 Pacific time.
