### ISSUE TITLE
Why use PBI Project?

### ISSUE THREAD

**Issue by WillBee123** [MicrosoftDocs/powerbi-docs#4764]
[Enter feedback here]
It seems this is the place you might want to tell people the benefits of PBI Project files.  I see no benefits to this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Version Independent ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Content: [Power BI Desktop projects (PBIP) - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview)
* Content Source: [powerbi-docs/developer/projects/projects-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-overview.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @WillBee123. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
The benefits of Power BI Desktop projects is clearly described in the introduction and in the embedded video.
