### ISSUE TITLE
Admin role name changes

### ISSUE THREAD

**Issue by stijh** [MicrosoftDocs/powerbi-docs#4765]
Looks like the note on Power BI Admin becoming Fabric Admin hasn't been applied here yet as it has in https://learn.microsoft.com/en-us/power-bi/admin/service-admin-portal

other pages not yet updated:

- https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-info-protection-data-loss-prevention-overview
- https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-security-report-consumer-planning

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f90e0836-c4b6-c3d9-dc27-f277b9262f17
* Version Independent ID: f90e0836-c4b6-c3d9-dc27-f277b9262f17
* Content: [Power BI implementation planning: Tenant-level security planning - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-security-tenant-level-planning)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-security-tenant-level-planning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-security-tenant-level-planning.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @stijh. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments, we've added the note to those articles.
