### ISSUE TITLE
Refresh failure notifications not being sent

### ISSUE THREAD

**Issue by M1ckB** [MicrosoftDocs/powerbi-docs#4766]
We are experiencing that refresh failure notifications are only being sent for some data sources and not for others. According to the [documentation](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data), we should _always_ receive notifications on refresh failures:

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/98694606/ca73b962-1f13-45a3-a04d-86616333f2da)

We are configuring notifications in the `Refresh` section of a dataset:

![connecting-to-other-source](https://github.com/MicrosoftDocs/powerbi-docs/assets/98694606/a5bcee01-734a-42f2-bc0e-e065d47e9030)

But we have discovered that when we are connecting to SSAS data (a cloud source), we are not receiving any refresh failure notifications. Looking through the available options, we cannot even configure notifications:

![connecting-to-cloud-source](https://github.com/MicrosoftDocs/powerbi-docs/assets/98694606/b3b0ffad-7050-4fcb-beff-12655346dc6e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your feedback, and sorry you're experiencing this difficulty. This sounds like a support request, which you can find at https://support.powerbi.com -- and if the documentation needs to be updated, we'll revise that article accordingly. Thanks.
