### ISSUE TITLE
Missing requironments for SAP Permissions per connector

### ISSUE THREAD

**Issue by Lego296** [MicrosoftDocs/powerbi-docs#4769]
In the requironment section it is not clearly defined what permissions the SAP User needs on SAP to be able to connect with the different connectors. Also what RFCs have to be available outside SAP Systems and not blocked by the UCON Firewall of SAP.

This results in a lot on wasted time with trial and error approach and communication with SAP base teams.

Mainly this Issue is focusing on https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-sap-bw-connector#other-improvements but this is a general insufficiency in documentation for PowerBI, ADF, Synapse and Fabric on all SAP Connectors. An overview over all possibilities and rights/permissions/UCON settings would be of help

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Lego296. This issue has been assigned to the doc author for review.
