### ISSUE TITLE
Unable to download Sep 2023 Version

### ISSUE THREAD

**Issue by shekarkola** [MicrosoftDocs/powerbi-docs#4771]
The Document includes the release notes for the Sep 2023 Power-BI Report Server, but the provided URL part of this page still redirects to May 2023 Power-BI Report Server installers. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff7e1942-9181-3451-5d1e-08bfa2ca9454
* Version Independent ID: 5547fc15-7d0e-225f-e0f1-890470f6cd5e
* Content: [What's new in Power BI Report Server - Power BI](https://learn.microsoft.com/en-us/power-bi/report-server/whats-new)
* Content Source: [powerbi-docs/report-server/whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/report-server/whats-new.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @shekarkola -- you're right! Good catch. This updated article went out ahead of the release, which should be here shortly. There will definitely be a blog post announcing the release here:
https://powerbi.microsoft.com/en-us/blog/category/report-server/
