### ISSUE TITLE
Text Formatting Issues for Gauge Chart Visualization

### ISSUE THREAD

**Issue by VincentK16** [MicrosoftDocs/powerbi-docs#4772]
Found some formatting issues for the "Gauge Chart" visual. Please fix it. Thanks!

<img width="641" alt="Screenshot 2023-09-27 183535" src="https://github.com/MicrosoftDocs/powerbi-docs/assets/3338753/24e5c261-7e1b-4471-948a-6ee6097675e3">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69212c7b-4492-a044-a07b-05266b20e370
* Version Independent ID: cc3d001b-1d58-b3b5-62a6-95f3955bf733
* Content: [Visualization types in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a#gauge-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VincentK16. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @VincentK16 ,
Thank you for your comment.  We've updated the article and the strange formatting has been fixed.
