### ISSUE TITLE
Improve description how to enable hyperlinks in tables when using Direct Query

### ISSUE THREAD

**Issue by hski-bayer** [MicrosoftDocs/powerbi-docs#4774]
Please update the description to set a column to Web URL on this page https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-hyperlinks-in-tables.

The current description "2. In Data view, select the column." does not work for Direct Query, because there is no Data view when you use direct query. 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/127206085/6082171e-4b1a-4a2b-a1dd-9db450683a56)

What works for both In Memory and Direct Query, is to select the column in the Data panel in the Report view. 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/127206085/489ce582-e787-426c-bb76-34b6d301b23f)

Then the same Column tool ribbon is shown, where you can set the Data Category to Web URL.

Please update the description and the screenshot. Thank you very much for considering this update. :-)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hski-bayer. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @hski-bayer,

Thank you for your suggestion, we'll consider this update in one of our future doc revamps.

Kesem

**Comment by hski-bayer** [comment]
Hello Kesem,

How frequently are you doing those doc updates? I am asking because I consider a lot of people struggling with this problematic description which does not work, if you work with direct query. 

Also I would not consider this issue as "closed", as the issue is still there, just postponed to be resolved, right?


BR, Holger
