### ISSUE TITLE
Add link to Microsoft Office documentation

### ISSUE THREAD

**Issue by elue-wrd** [MicrosoftDocs/powerbi-docs#4776]
I'm on the government cloud and I have feedback on this statement:

Power BI entry points for the add-in aren't available in national/regional, government, and air-gapped clouds. See the Microsoft Office documentation for information about the availability of the add-in in PowerPoint in these clouds.

Would like a link to the "Microsoft Office documentation" to get more information or updates on when Power BI entry points will be available for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5d14ba-66ff-7447-76d6-4f4d38e5b382
* Version Independent ID: 6a5d14ba-66ff-7447-76d6-4f4d38e5b382
* Content: [Power BI add-in for PowerPoint - Admin info - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-power-bi-powerpoint-add-in-admin)
* Content Source: [powerbi-docs/collaborate-share/service-power-bi-powerpoint-add-in-admin.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-power-bi-powerpoint-add-in-admin.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elue-wrd. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @elue-wrd, thanks for your feedback, and sorry about the long delay in replying. I am looking for a link and will put it into the documentation if I find one. Closing this issue now and hoping that I'll be able to find the link you're looking for.
