### ISSUE TITLE
Connection to AdventureWorksDW2021-PRIAD is down

### ISSUE THREAD

**Issue by giraffe24** [MicrosoftDocs/powerbi-docs#4777]
Course documentation offers connection properties to server priad.database.windows.net which no longer work. Other users who have completed this course confirm that they are also no longer able to connect.

Copied the connection properties directly from:
<CourseFolder>\PowerBIPRIAD\MySolution\MyEnvironment.txt

No success.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0439d49-76b1-380b-f226-317e96ca0397
* Version Independent ID: 2dd9f620-5244-936f-76f9-1f32f5ac5a23
* Content: [Power BI Paginated Reports in a Day course - Power BI](https://learn.microsoft.com/en-us/power-bi/learning-catalog/paginated-reports-online-course)
* Content Source: [powerbi-docs/learning-catalog/paginated-reports-online-course.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/learning-catalog/paginated-reports-online-course.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @data-goblin
* Microsoft Alias: **v-kurtbuhler**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @giraffe24. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @giraffe24,

Thanks for pointing this out.

Can you please send a screenshot or explain where in [Power BI Paginated Reports in a Day course](https://learn.microsoft.com/power-bi/learning-catalog/paginated-reports-online-course) you found either priad.database.windows.net or \PowerBIPRIAD\MySolution\MyEnvironment.txt?

Thanks,

Kesem

**Comment by giraffe24** [comment]
Hi Kesem,

This direction is found in the file titled "PowerBIPRIAD_Lab02A" in Exercise 1 and is also shown in the videos.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/146382538/762fd049-887d-49fe-b9d7-00b0ddcbef61)

**Comment by KesemSharabi** [comment]
Hi @giraffe24,

Thanks for the additional details. I'm looking into this issue.

Kesem

**Comment by jari2023** [comment]
I have the same issues, any news on this?

**Comment by ConspiracyCode** [comment]
I am having the same issue. Any help is appreciated. Thank you.

**Comment by bradleyaidanjohnson** [comment]
Same issue, cannot connect

**Comment by brenter1** [comment]
Following up on this.  We still cannot connect.

**Comment by nirusrin** [comment]
Hi @KesemSharabi :

This information needs to be in the Attendee kit: 

1.	Lab02A/PowerBIPRIAD_Lab02A.pdf

Server name: priad.database.windows.net needs to be updated to labresources.database.windows.net

2.	Solution folder, MyEnvironment.txt:
Server name: priad.database.windows.net needs to be updated to labresources.database.windows.net

**Comment by KesemSharabi** [comment]
Hi @giraffe24,

This issue is being addressed and will be resolved shortly.

Thank you for engaging with us.

Kesem
