### ISSUE TITLE
Power BI datamart SQL endpoint is missing

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs#4778]
Power BI datamart SQL endpoints are missing in the allow list documentation.

The datamart FQDN should be covered by the [general site usage](https://learn.microsoft.com/en-us/power-bi/admin/power-bi-allow-list-urls#general-site-usage) table (*.pbidedicated.windows.net which covers *.datamart.pbidedicated.windows.net) but the SQL endpoint requires ports TCP 1433 in addition to 443 to be opened.

The [Power BI datamart documentation](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-administration#considerations-and-limitations) in contrast covers the information about the port (TCP 1433) but does not mention the respective FQDN (*.datamart.pbidedicated.windows.net) that needs to be added to the allow list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0bf9e3f-d1fc-9edc-c4b1-c2c214f71454
* Version Independent ID: 3b2b0285-2a7b-7eff-3053-dd4591414149
* Content: [Add Power BI URLs to allowlist - Power BI](https://learn.microsoft.com/en-us/power-bi/admin/power-bi-allow-list-urls)
* Content Source: [powerbi-docs/admin/power-bi-allow-list-urls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/admin/power-bi-allow-list-urls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kesharab
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mpoeckl. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @mpoeckl,

I'm looking into this issue and will update you when I have an answer.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @mpoeckl,

Thanks again for your help and for getting involved.

I updated [General site usage](https://learn.microsoft.com/power-bi/enterprise/power-bi-allow-list-urls) with the missing endpoint and the change will go live shortly.

Kesem
