### ISSUE TITLE
HomeController example uses UserPasswordCredential which the ADAL team doesn't support 'by design' in .NET Core

### ISSUE THREAD

**Issue by krouskop** [MicrosoftDocs/powerbi-docs#478]
It would be helpful for the HomeController example to be re-created to not rely on UserPasswordCredential, as the ADAL team has judged the use of UserPasswordCredential as such a poor practice they explicitly won't support implementing UserPasswordCredential in the .NET Core version of the ADAL library.  (see https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for your comment, @krouskop. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by ajpi222** [comment]
Agree @krouskop, having trouble trying to figure out the .NET Core implementation.

**Comment by markingmyname** [comment]
@krouskop Apologizes for the delayed response.  There are current discussions to make changes to this piece.  I will update everyone once I have more information about this topic.

**Comment by markingmyname** [comment]
@krouskop 

We are aligning to restructure the authentication portion to fit better best practices.

No ETA on when this information will be released. As such for now, UserPasswordCredential is the only current option.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by sbosell** [comment]
You closed this thread without proving any information, direction, timing, or help.  Can you re-open it and/or provide the code to achieve what this page documents using the core library?

**Comment by adamvan101** [comment]
@markingmyname is there any update on this?

**Comment by dlmotter** [comment]
This issue has been reported multiple times, but MS just diverts to the (totally useless) PBI Community page. If you are like me and having this issue, you may have luck with https://www.c-sharpcorner.com/article/how-to-get-access-token-for-powerbi-embedding-in-net-core/

I did not write and have no affiliation with that site - it's just the solution that worked for me.
