### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by imlescano** [MicrosoftDocs/powerbi-docs#4780]
[Enter feedback here]
Link https://mran.revolutionanalytics.com/download/ doesnt work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-r-visuals)
* Content Source: [powerbi-docs/create-reports/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-r-visuals.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @imlescano. This issue has been assigned to the doc author for review.
