### ISSUE TITLE
Dynamic subscriptions: Increase limit from 50 recipients

### ISSUE THREAD

**Issue by jobonsak** [MicrosoftDocs/powerbi-docs#4784]
It is not clear to me if the max 50 recipients is meant to be permanent or just a preview limit. If just preview, then please clarify it on the web page. If permanent, then it is not a good enough alternative to ssrs data driven subscriptions, which we are trying to move away from. We're fine with a few hundred (200 in preview phase), but I guess bigger enterprises needs thousands. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5d618c4-8c58-b82f-2b59-0eb75364afe9
* Version Independent ID: a5d618c4-8c58-b82f-2b59-0eb75364afe9
* Content: [Create a dynamic subscription (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/dynamic-subscriptions)
* Content Source: [powerbi-docs/collaborate-share/dynamic-subscriptions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/dynamic-subscriptions.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jobonsak. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @jobonsak ,
Yes, 50 is a preview limit and I'll add that to the document.  Thank you for your input :-)
Michele
