### ISSUE TITLE
Please add note about premium capacity metrics app being deprecated and add the link to download fabric capacity metrics app.

### ISSUE THREAD

**Issue by rishigautam11** [MicrosoftDocs/powerbi-docs#4785]
Please add a note on the page for information about "The PBI Premium Metrics app will be deprecated in Fall of '23. After 10/1 please install the Fabric version of the metrics app to ensure accuracy of analysis for all platform features."
Click on the below link to install the Fabric version of capacity metrics app.
[https://appsource.microsoft.com/en-us/product/power-bi/pbi_pcmm.microsoftpremiumfabricpreviewreport?exp=ubp8](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4843cde8-6191-2773-7500-272b87ad8084
* Version Independent ID: 27ff08bc-43e8-4c8d-2cf5-ad096b6f11ff
* Content: [Monitor Power BI Premium capacities with the Premium metrics app. - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-metrics-app)
* Content Source: [powerbi-docs/enterprise/service-premium-metrics-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-metrics-app.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rishigautam11. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Resolved.
