### ISSUE TITLE
Show Export data option separately on top of the Power BI report 

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/powerbi-docs#4789]
How to show default export data option separately on top of the Power BI report? 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/78982760/296dbc7d-ae9f-477b-876b-f495740e7cc3)

**Something like this:**

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/78982760/c6ddddee-a2cb-4893-8c03-035b4084c2fc)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c87c556b-b1da-0b24-606b-89c371c6bae8
* Version Independent ID: 20141574-acfa-f5f8-b6cf-6b32b3c55b4f
* Content: [Export data from a Power BI visualization - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-export-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-export-data.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jaganpt. This issue has been assigned to the doc author for review.

**Comment by jaganpt** [comment]
@bishalgoswami , Any update on this?
