### ISSUE TITLE
Firewall settings

### ISSUE THREAD

**Issue by cbailiss** [MicrosoftDocs/powerbi-docs#479]
Although not stated, it sounds like the gateway needs connectivity to the cloud sources.  It would be helpful if you could confirm this and if so explicitly state this in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @cbailiss . The gateway is typically for on prem sources, and it also needs access to the Power BI service in the cloud. Did you have another scenario in mind?

**Comment by cbailiss** [comment]
The doc page I raised this question on is taking about merging data from on-prem and cloud sources.  The doc page does not make clear whether the gateway needs connectivity to the cloud sources. 
https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud

I understand that connectivity to the on-prem data sources and Power BI is needed (pretty obvious).  But it is not clear if connectivity is needed to cloud sources.  It is perhaps implied in the doc page, but making this requirement clearer (if it is a requirement) would be helpful, i.e. especially because the name of the gateway, i.e. on-prem gateway, could be interpreted to mean it is only used for on-prem sources.

**Comment by mgblythe** [comment]
Adding @arthiriyer to clarify this one.

**Comment by arthiriyer** [comment]
@cbailiss Thanks for the feedback.  For any cloud connection routed via the Gateway , you would need to make sure the gateway can access it.
@mgblythe FYI

**Comment by mgblythe** [comment]
Added a note to the prerequisites stating that to use cloud data sources, your gateway must have access to those sources. See https://docs.microsoft.com/power-bi/service-gateway-mashup-on-premises-cloud#prerequisites.
