### ISSUE TITLE
POWER_BI_DEVELOPER

### ISSUE THREAD

**Issue by shivendra1-cyber** [MicrosoftDocs/powerbi-docs#4790]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe7888c3-14b3-8120-7fa5-80af7d1febba
* Version Independent ID: af40d3fb-5ed4-fa37-0e1d-afd01b1faf1e
* Content: [Power BI embedded analytics overview - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-analytics-power-bi)
* Content Source: [powerbi-docs/developer/embedded/embedded-analytics-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-analytics-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shivendra1-cyber. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Hi @shivendra1-cyber, you didn't provide any feedback in the feedback section so I'm going to assume this was a mistake and close this item. If you have any feedback to offer, you can open a new one.
