### ISSUE TITLE
MRAN link to be removed

### ISSUE THREAD

**Issue by Jihong-v** [MicrosoftDocs/powerbi-docs#4792]
[Enter feedback here]
Since MRAN has retired, you may want to remove the link to navigate users to download R from it.
https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-r-application-network-retirement/ba-p/3707161 

Jihong
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65c5ff52-929f-1722-cae7-a13193afcbc5
* Version Independent ID: 9dae40ab-e5d9-42a3-d95a-5c1610f02682
* Content: [Run R scripts in Power BI Desktop - Power BI](https://learn.microsoft.com/en-gb/power-bi/connect-data/desktop-r-scripts)
* Content Source: [powerbi-docs/connect-data/desktop-r-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jihong-v. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point! Removed, will be reflected in the next build / release of the docs. Thanks!
