### ISSUE TITLE
PowerBI API Refresh example

### ISSUE THREAD

**Issue by edgar-leung** [MicrosoftDocs/powerbi-docs#4795]
Under the section "_Response Properties_", it is stated within the table that for the `Status` property,
> Unknown indicates that the completion state can't be determined. With this status, endTime is empty.

However, the section "_GET /Refreshes_" shows an example with `Unknown` for `status`, but an `endTime` is given.

```json
[
    {
        "requestId": "1344a272-7893-4afa-a4b3-3fb87222fdac",
        "refreshType": "ViaEnhancedApi",
        "startTime": "2020-12-07T02:06:57.1838734Z",
        "endTime": "2020-12-07T02:07:00.4929675Z",
        "status": "Completed",
        "extendedStatus": "Completed"
    },
    {
        "requestId": "474fc5a0-3d69-4c5d-adb4-8a846fa5580b",
        "startTime": "2020-12-07T01:05:54.157324Z",
        "refreshType": "ViaEnhancedApi",
        "endTime": "2020-12-07T01:05:57.353371Z",
        "status": "Unknown",
        "extendedStatus": "InProgress"
    }
    {
        "requestId": "85a82498-2209-428c-b273-f87b3a1eb905",
        "refreshType": "ViaEnhancedApi",
        "startTime": "2020-12-07T01:05:54.157324Z",
        "endTime": "2020-12-07T01:05:57.353371Z",
        "status": "Unknown",
        "extendedStatus": "NotStarted"
    }
]
```
Which is correct, the table or the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6d5230d-8c4f-b353-5d44-d92c61a7ec85
* Version Independent ID: f6d5230d-8c4f-b353-5d44-d92c61a7ec85
* Content: [Enhanced refresh with the Power BI REST API - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/asynchronous-refresh)
* Content Source: [powerbi-docs/connect-data/asynchronous-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/asynchronous-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @edgar-leung. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
#in-review

**Comment by bishalgoswami** [comment]
Thanks for your comment, @edgar-leung. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @edgar-leung,

I'm looking into this issue and will get back to you when I get an anwer.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @edgar-leung,

We're closing the GitHub issues functionality. I'll try to make changes to the documentation to clarify what you point out in the near future.

Thanks,

Kesem
