### ISSUE TITLE
Power BI Dataset Refresh without premium capacities

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/powerbi-docs#4800]
How to refresh (>4 times per day) Power BI Dataset without Premium capacities/subscriptions? 
Are there any alternatives to achieve this to show real-time data (with modeling, visuals  and filters) in Power BI ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-data)
* Content Source: [powerbi-docs/connect-data/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jaganpt. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
