### ISSUE TITLE
Correction required in the Build/Version mentioned in the article.

### ISSUE THREAD

**Issue by Sujeeth0909** [MicrosoftDocs/powerbi-docs#4802]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Version Independent ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Content: [Power BI dataset experience in Excel - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-excel-power-bi-datasets)
* Content Source: [powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sujeeth0909. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Sujeeth0909 -- I sent you an email. You can edit the article yourself and I'll sign off. Cheers!
