### ISSUE TITLE
Instructions not up to date

### ISSUE THREAD

**Issue by HUrquhart** [MicrosoftDocs/powerbi-docs#4803]
To enable the Power Bi visual dev tools you need to use the following url
https://app.powerbi.com/user/user-settings/developer-settings?experience=power-bi

Then turn Developer Mode on.

the screen shots also need to be updated as they are just plain confusing for first time developers / users

here is the current section
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/46597391/550cbda6-146a-4320-92c4-0649dee3961f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42b50f4b-5e10-6fef-ad73-612996d2001a
* Version Independent ID: 8eda699d-40de-e20b-d030-719a6c4e2ff2
* Content: [Setting up an environment for developing a Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/environment-setup#install-pbiviz)
* Content Source: [powerbi-docs/developer/visuals/environment-setup.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/environment-setup.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HUrquhart. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @HUrquhart. You're right, the UI has changed, and the documentation wasn't updated. Thanks for pointing it out. It'll be corrected soon.
