### ISSUE TITLE
Meaning of frequency when set to "After data refresh"

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#4805]
In the document, it is stated that:

Subscriptions that have the frequency set to After data refresh will only send an email after the first scheduled refresh on that day.

Is "that day" based on the UTC time zone?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2caf5705-b9c8-3818-4524-3c4bf9b112a2
* Version Independent ID: 98ede3b9-f4f6-88a6-83fc-6afab863bf4a
* Content: [Email subscriptions for reports and dashboards in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/end-user-subscribe?tabs=creator)
* Content Source: [powerbi-docs/collaborate-share/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/end-user-subscribe.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @asocorro. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @asocorro , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
