### ISSUE TITLE
Fiddler is no longer free

### ISSUE THREAD

**Issue by KalenBerry** [MicrosoftDocs/powerbi-docs#4806]
Fiddler is a paid product now and shouldn't be advertised as free. In fact, I would suggest that you link to an alternative free product or remove this section as it is unhelpful to be told to pay someone else money to fix the product we already pay for. 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/9022087/9c07ae17-8b21-4dfc-ace3-4c346482ffda)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshoot gateways - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-onprem-tshoot)
* Content Source: [powerbi-docs/connect-data/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KalenBerry. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point. We've removed that section.
