### ISSUE TITLE
.Net requirements inconsistent with MS PBI Blog

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4808]
Hi PBI Docs Team,
In MS blog post it was announced that minimum the .NET version is 4.7.2 (https://powerbi.microsoft.com/en-us/blog/power-bi-september-2023-feature-summary/#post-24646-_Toc145515962). 
In the section https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop#minimum-requirements it says 4.6.2 or later.

Could you align these 2 requirements?

With best regards,
Martin Kmec

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Great point - I've updated that requirement. Thanks for pointing that out!
