### ISSUE TITLE
Test to see if Issues working for end-user content

### ISSUE THREAD

**Issue by mihart** [MicrosoftDocs/powerbi-docs#481]
this is a test. Please assign to me, mihart. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66e6d45d-17cd-6e69-cdf8-2b1d58bb4889
* Version Independent ID: 058458dd-4115-4dc0-c87e-0ed659bd0d60
* Content: [Power BI service- basic concepts for consumers - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-basic-concepts)
* Content Source: [powerbi-docs/consumer/end-user-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-basic-concepts.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @mihart -- assigning this test issue to you. Hope that helps!
