### ISSUE TITLE
Nice article

### ISSUE THREAD

**Issue by SakthiPillai** [MicrosoftDocs/powerbi-docs#4811]
##### Thanks for the great article and the hands-on. Easy to understand and follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 14fa9def-43a2-7673-c891-3cd9df9e3d18
* Version Independent ID: f54b6ef4-eebd-3b31-2261-881166045dc2
* Content: [Create and use funnel charts in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-funnel-charts?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-funnel-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-funnel-charts.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SakthiPillai. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @SakthiPillai ,
Glad you enjoyed it!

Michele
