### ISSUE TITLE
Sep-2023 PBI Desktop Release info is still not updated in this page

### ISSUE THREAD

**Issue by Sh5678** [MicrosoftDocs/powerbi-docs#4812]
[Enter feedback here]
While the Oct-2023 PBI Desktop release has been announced on 11-Oct-2023, the Previous Monthly Updates to PBI Desktop & Service page is still having info only till Aug-2023 PBI Desktop release -- thereby no active link currently available to download the Sep-2023 PBI Desktop. 

Please have this page updated with Sep-2023 & Oct-2023 PBI Desktop release details asap, so that we can refer this to download the Sep-2023 PBI Desktop installations.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sh5678. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for noticing, we've updated that page.
