### ISSUE TITLE
This page has outdated code example:

### ISSUE THREAD

**Issue by Hinalover** [MicrosoftDocs/powerbi-docs#4814]
The example uses `let allowInteractions = options.host.allowInteractions;`  when it should be `let allowInteractions = options.host.hostCapabilities.allowInteractions`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5b9a9ae-d0e4-7c63-f9ee-9f7f077559dc
* Version Independent ID: a481723b-b5f2-1c26-aa56-e98abb61359a
* Content: [Visual interactions in Power BI visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/visuals-interactions)
* Content Source: [powerbi-docs/developer/visuals/visuals-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/visuals-interactions.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for pointing that out, @Hinalover. I'll make sure to correct it!
