### ISSUE TITLE
PowerBI  "Fields" Section on Right Vertical NavBar is Now Called "Data"

### ISSUE THREAD

**Issue by avongonzales2021** [MicrosoftDocs/powerbi-docs#4815]
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @avongonzales2021. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @avongonzales2021! Working on the update.
