### ISSUE TITLE
Update the Instructions for the Word "Formatting Pane" is "Visualizations"

### ISSUE THREAD

**Issue by avongonzales2021** [MicrosoftDocs/powerbi-docs#4816]
Update the Instructions for the Word "Formatting Pane" is "Visualizations"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 751771a8-ae97-2f7a-45f7-6eab5e30bb98
* Version Independent ID: 69b8d8ce-49e3-feb2-b751-c9a3c26bc501
* Content: [Tutorial: From dimensional model to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-dimensional-model-report)
* Content Source: [powerbi-docs/create-reports/desktop-dimensional-model-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-dimensional-model-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @avongonzales2021. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @avongonzales2021 -- Thanks so much for your feedback! What I'm seeing is that it's called the Format pane. So that's what I'm changing it to, and I'm closing this issue.
