### ISSUE TITLE
"Manage connections and gateways"

### ISSUE THREAD

**Issue by avongonzales2021** [MicrosoftDocs/powerbi-docs#4817]
Select the Datasets tab, and then select the AdventureWorksProducts dataset from the list of datasets.

the msit.powerbi.com settings page now says "Manage connections and gateways"
instead of datasets

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-sql-tutorial)
* Content Source: [powerbi-docs/connect-data/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @avongonzales2021. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @avongonzales2021,

Can you please point to the place in [Refresh data from an on-premises SQL Server database](https://learn.microsoft.com/power-bi/connect-data/service-gateway-sql-tutorial) that needs to be fixed?

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
No response. Closed.
