### ISSUE TITLE
Great Visual! Quick Question :)

### ISSUE THREAD

**Issue by rkostrzewa1** [MicrosoftDocs/powerbi-docs#482]
Hi, I really like this feature a lot. It's particularly useful to see the data in tabular form for visuals with drill down features. Is there any way to export this "Show Data" table visual into Excel? Thanks for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1c055f0-f722-d10c-f94e-7db7861df5d7
* Version Independent ID: 4837f276-8668-ed25-9ee9-44cb9fa0cad6
* Content: [Show the data that was used to create the Power BI visualization - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-show-data)
* Content Source: [powerbi-docs/consumer/end-user-show-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-show-data.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by rkostrzewa1** [comment]
Awesome! Thanks for the quick response and thanks for looking into this!

**Comment by rkostrzewa1** [comment]
Hi there. Could I get an update on this please? I'd be excited to learn if this was possible. Thanks!

**Comment by mihart** [comment]
Hi @rkostrzewa1 
Sorry for the delay.  I'm not sure if I understand your question.  Because you definitely can export the data into Excel and the article shows that.  So I must be missing some key part of your question.   Are you asking if "Show Data" is available, not in Power BI, but available in Excel?  Please send more details or an example and I'll do my best to answer your question.  Thanks.

**Comment by rkostrzewa1** [comment]
Hi, I am looking to export the data behind the visual seen in Show Data to Excel. I understand you can export data to Excel but sometimes it is not rolled up as seen in the Show Data table. For example, if I have a hierarchical count by month and then by week I can be at a level to look by month or drill down to see by week. When I am on the first level to see count by month and I do Show Data, I see the count rolled up by month and don't see it by week. When I export the data to Excel with the ellipses, it is broken down by month and week on one line. I'd like to be able to export the Show Data visual exactly as shown, not with all underlying data but rolled up as shown in Show Data. Thanks for your help.

**Comment by rkostrzewa1** [comment]
Also, I don't see in the article where it says anything about exporting the Show Data table to Excel.  Could you elaborate on that please?

**Comment by mihart** [comment]
Hi @rkostrzewa1 ,
Does this article help?
https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-export-data
?

**Comment by rkostrzewa1** [comment]
No I'm sorry it does not. Here is my example:

This is the original data I loaded into Power BI
![image](https://user-images.githubusercontent.com/45493512/50482596-02a6f880-09ad-11e9-9227-e1b56abd7f99.png)

Here is the first hierarchy of my data rolled up by month including the Show Data feature. As you can see it sums up Packaging and Printing for all of the weeks in month 1.
![image](https://user-images.githubusercontent.com/45493512/50482643-41d54980-09ad-11e9-8014-935988078015.png)

Here is the second hierarchy of my data rolled up by week including the Show Data visual.
![image](https://user-images.githubusercontent.com/45493512/50482658-5dd8eb00-09ad-11e9-8172-386cf43e80b7.png)

When I click Export Data, this is the output I get. I want to see it rolled up by month and not broken out by week. 

![image](https://user-images.githubusercontent.com/45493512/50482676-8365f480-09ad-11e9-9abe-469c9caaabb0.png)

I want to see it exactly like shown in Show Data in Excel. I want the below table in Excel. 
![image](https://user-images.githubusercontent.com/45493512/50482702-abedee80-09ad-11e9-8336-4c245fbd1d9f.png)

I understand I could use pivot tables in Excel to get the data by month and not broken out by week with Export Data but many of our users don't know how to use pivot tables. I want to be able to export the visual Show Data exactly as shown. Thanks.

**Comment by mihart** [comment]
Got it.  I'm going to defer to the Product team on this one, since it's a product-reated issue and not a docs issue.  I've copied/pasted this conversation into a post on https://community.powerbi.com.  The PMs and Devs who monitor the forums are pretty quick to answer.  
HTH,
Michele

**Comment by rkostrzewa1** [comment]
Thank you. Could you link me to the post? I am having a hard time locating it.

**Comment by rkostrzewa1** [comment]
Hi, could you link me to the post you created? I can't find it. @mihart
