### ISSUE TITLE
Broken link to Activity Logs

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#4821]
Hi MS Docs Team,

the link in the first sentence "from the [Power BI activity log](https://learn.microsoft.com/en-us/power-bi/admin/service-admin-auditing)." is broken.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/48448079/75f431de-5836-43db-9342-3a9b2ec9cfb9)

Could you please have a look into it?

With best regards,
Martin Kmec

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9782ea1-8981-f692-e398-3f95ec3bc145
* Version Independent ID: 03339c88-780b-caa8-6c3a-1fdb59ff7189
* Content: [Access the Power BI activity log - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/admin-activity-log)
* Content Source: [powerbi-docs/guidance/admin-activity-log.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/admin-activity-log.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @MartinKDK - thanks for your feedback. You found a gremlin in our system and we're on to it. Please try the link again soon.

#please-close

**Comment by KesemSharabi** [comment]
Hi @MartinKDK,

This issue was fixed. Thanks for flagging it.

Kesem
