### ISSUE TITLE
404 for "Add Power BI URLs to allowlist" article

### ISSUE THREAD

**Issue by lesliemui** [MicrosoftDocs/powerbi-docs#4823]
https://learn.microsoft.com/en-us/powerbi-docs/enterprise/power-bi-allow-list-urls

This page is no longer accessible publicly and returns a 404 error.
May be related to other issue: https://github.com/MicrosoftDocs/powerbi-docs/issues/4821

The github side seems to exist:
https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/power-bi-allow-list-urls.md

**Comment by KesemSharabi** [comment]
Hi @lesliemui,

Can please let me know which article links to https://learn.microsoft.com/powerbi-docs/enterprise/power-bi-allow-list-urls?

Thanks,

Kesem

**Comment by lesliemui** [comment]
I think we can close this:
The link which doesn't work:
https://learn.microsoft.com/en-us/powerbi-docs/enterprise/power-bi-allow-list-urls

It was a bookmark I had previously that seems to have been updated
https://learn.microsoft.com/en-us/power-bi/enterprise/power-bi-allow-list-urls 

The old URL was also cached in a few search indexes including the internal docs search.
It seems to be resolved now.

**Comment by KesemSharabi** [comment]
Thanks for confirming @lesliemui.
