### ISSUE TITLE
There is no power bi platform in get dat of excel

### ISSUE THREAD

**Issue by minthu891** [MicrosoftDocs/powerbi-docs#4824]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Version Independent ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Content: [Power BI dataset experience in Excel - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-excel-power-bi-datasets)
* Content Source: [powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @minthu891. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @minthu891, to me the images in the article correspond to what I see in Excel. Please take another look at the documentation and make sure you are looking at the correct ribbon - there are two mentioned - the Insert ribbon and the Data ribbon. I'm closing this issue now, but if you still think the documentation is in error, please respond again using the feedback link that you'll find at the bottom of the documentation article. Thanks for reaching out with your question!
