### ISSUE TITLE
Are multiple filters for single table+column using embedded dynamic RLS possible?

### ISSUE THREAD

**Issue by 3b33** [MicrosoftDocs/powerbi-docs#4826]
Hi! Important note, is it possible to filter to multiple [CountryRegionCode]? The example is just for "France". My quick test says no, but I need to make sure. This makes or breaks the usability of this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 17c045ba-610c-4441-446c-96f5eb760a09
* Version Independent ID: 17c045ba-610c-4441-446c-96f5eb760a09
* Content: [Using standard cloud based row-level security with embedded content in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/cloud-rls#dynamic-security)
* Content Source: [powerbi-docs/developer/embedded/cloud-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/cloud-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your question, @3b33. In the past I know this wasn't possible, but check out how to [Define roles and rules in Power BI Desktop using enhanced row-level security editor (Preview)](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-rls#define-roles-and-rules-in-power-bi-desktop-using-enhanced-row-level-security-editor-preview). I think it might help you.

**Comment by 3b33** [comment]
Hi ya. Thanks for the answer. It seems the enhanced rls still requires predetermined roles. My goal is for the embedding application to determine what tables and columns are filtered with what values dynamically.

The page I commented on tranferred information about what to filter to (France) through the userprincipal(). The link you gave requires a predetermined role to filter to France.

Customers embedded solution should be able to pass table columns and values to filter to without predetermined roles. Example: filter teams table team column to "Sales", and/or filter employee id column to 123.
