### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Sabarish2903** [MicrosoftDocs/powerbi-docs#4828]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 688dd4d0-611c-56eb-c9e7-94171c0d4902
* Version Independent ID: 688dd4d0-611c-56eb-c9e7-94171c0d4902
* Content: [Download a sample template app from AppSource - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/sample-sales-marketing-template-app)
* Content Source: [powerbi-docs/create-reports/sample-sales-marketing-template-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-sales-marketing-template-app.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Sabarish2903. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Sabarish2903, can you provide more info? I am closing this issue now, as we have transitioned to a new feedback system. If you'd like to follow up, please use the feedback button you'll find at the end of the specific doc page you're looking at. Thanks!
