### ISSUE TITLE
Does Power BI Report server support embedding Power BI reports in my custom application?

### ISSUE THREAD

**Issue by mow700** [MicrosoftDocs/powerbi-docs#483]
The documentation is unclear on this topic.  Can I use the embedding API against Power BI reports hosted in an on premise Report Server in my custom application?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by RobertCazaciuc** [comment]
This is an important question - can anyone help with an answer on this?

**Comment by ignatvilesov** [comment]
I guess it is possible to embed a PBIRS report into a web application by using an iframe. Have a look at t[his short ](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-embed) guide.

**Comment by maggiesMSFT** [comment]
Thanks for that answer, @ignatvilesov, and thanks, @mow700, for asking your question!

**Comment by michielzh** [comment]
> I guess it is possible to embed a PBIRS report into a web application by using an iframe. Have a look at t[his short ](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-embed) guide.

I think his question is how to access the power bi server in the form of rest api just like accessing the power bi service. Now the official documentation does not cover this content, just embedded through the iframe. This feature is too rudimentary. Now our company only purchases the power bi server of the local deployment mode, and the company requires that the report cannot be released through the cloud. How can I solve the inline in our own html application? Iframe inline will show the filter panel and sheet tab, which is too ugly.

**Comment by brettpostin** [comment]
Has there been any movement on this or is the iframe solution still the only valid option?
