### ISSUE TITLE
The Report Icons are outdated.

### ISSUE THREAD

**Issue by gtherezan** [MicrosoftDocs/powerbi-docs#4832]
The Report Icons are outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a651c9cf-5ec4-f771-ced9-8c72acbafdbc
* Version Independent ID: ce15b525-d7fe-1c6d-cf03-62a1dbe64b5a
* Content: [View a report - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-report-open)
* Content Source: [powerbi-docs/consumer/end-user-report-open.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-report-open.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gtherezan. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @gtherezan , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
