### ISSUE TITLE
The Dashboard Icons are outdated.

### ISSUE THREAD

**Issue by gtherezan** [MicrosoftDocs/powerbi-docs#4833]
The Dashboard Icons are outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df8fcff1-6d5d-2619-8c96-13a00802bb36
* Version Independent ID: cb25f645-8245-7dd7-7020-2b12aaa98098
* Content: [View a Power BI dashboard - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-dashboard-open)
* Content Source: [powerbi-docs/consumer/end-user-dashboard-open.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-dashboard-open.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @gtherezan. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @gtherezan , 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
