### ISSUE TITLE
Broken link for : AppOwnsDataMultiTenant sample application

### ISSUE THREAD

**Issue by Josverl** [MicrosoftDocs/powerbi-docs#4835]
The link to a sample github repo for [AppOwnsDataMultiTenant sample application](https://github.com/PowerBiDevCamp/AppOwnsDatamultitenancy) is broken.

Also a search on Github for the repo name does not find a likely target.

Having a good link to a current sample would help anwser questions from ISVs that are interested in exploring this rather complex scenario, so please do not resolve this by just removing the link.

/Jos 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 37909616-be39-0deb-77b5-f3ac1cb49cee
* Version Independent ID: 37909616-be39-0deb-77b5-f3ac1cb49cee
* Content: [Develop scalable multitenancy applications with Power BI embedding - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/develop-scalable-multitenancy-apps-with-powerbi-embedding)
* Content Source: [powerbi-docs/guidance/develop-scalable-multitenancy-apps-with-powerbi-embedding.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/develop-scalable-multitenancy-apps-with-powerbi-embedding.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Josverl. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @Josverl - thanks for bring this issue to our attention. I'm looking into it now and will see if there's an alternative resource we can refer the reader to. I'll keep you posted.

**Comment by peter-myers** [comment]
Hi @Josverl - it looks like you're using an incorrect link. The link in the article is correct and it points to a current resource at GitHub: https://github.com/PowerBiDevCamp/AppOwnsDataMultiTenant

#please-close

**Comment by Josverl** [comment]
Could it be that that is a private repo and lot accessible to the public , 
I copied the link from the article

**Comment by peter-myers** [comment]
Please click the link in the article. It worked for me, and I don't have any special access to the repo. Please let me know how you go.
