### ISSUE TITLE
Property 'Card' does not exist when importing from 'formattingSettings.Card' - Develop custom visual with React

### ISSUE THREAD

**Issue by phatsp** [MicrosoftDocs/powerbi-docs#4839]
Hi, I'm following this tutorial for developing custom visuals with React: 
https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-react-visual

But then got the error when reaching the [Add a circle formatting settings class to the settings file](url) part. Hope someone can help.

![2023-10-29_191248](https://github.com/MicrosoftDocs/powerbi-docs/assets/43247670/a3fb4240-d04a-4cfc-a7bf-b98b6b2e533b)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @phatsp. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @phatsp. I agree that this tutorial is a bit outdated. It's in our backlog and we hope to get around to updating it soon. Thanks.
