### ISSUE TITLE
Screenshots for App Registrations differs to Azure Portal

### ISSUE THREAD

**Issue by archieag** [MicrosoftDocs/powerbi-docs#484]
Screenshot in this documentation differs to App registration experience in Azure Portal and this is confusing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embed Power BI content into an application for your customers - Power BI](https://docs.microsoft.com/en-gb/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @archieag. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by markingmyname** [comment]
Hi, archieag.  Thank you for bringing this to our attention.  This has been addressed.  Thank you and happy holidays!

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
