### ISSUE TITLE
Is there a bug on styling the page navigator

### ISSUE THREAD

**Issue by StevenSpruce** [MicrosoftDocs/powerbi-docs#4842]
When the bold, italic and underline settings are 'on' for the state 'default' it appears they cannot be turned off for the state 'selected'.

However the reverse is not true.  If they are off on the default I can turn them on for selected.

I want to create a scenario where my selected button is not underlined, with the not selected button being underlined.  So I set the default as underlined, then tried to turn it off for selected....to no avail.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Version Independent ID: f4858b56-a0e2-8836-e522-4b8a69b0fefa
* Content: [Create page and bookmark navigators - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/button-navigators.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/button-navigators.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @StevenSpruce. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Interesting, @StevenSpruce ! I hadn't tried that. I'm adding a note to that effect to the article, and I'll pass your feedback along to the product team.
