### ISSUE TITLE
Build permission

### ISSUE THREAD

**Issue by Ilocans** [MicrosoftDocs/powerbi-docs#4843]
I think this sentence is either contradictory or false: 

"Power BI provides Build permission as a complement to Read and Reshare permissions. All users who already have Read permission for datasets via app permissions, sharing, or workspace access also get Build permission for those datasets. Those users get Build permission automatically because Read permission already grants them the right to build new content on the dataset by using Analyze in Excel or Export."

Build is a complement of Read so the sentence "All users who already have Read permission for datasets via app permissions, sharing, or workspace access also get Build permission for those datasets" does not match avec the previous one.

Also according to https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-permissions
Read | Allows user to access reports and other solutions, such as composite models on Premium/PPU workspaces, that read data from the dataset. Allows user to view dataset settings.

Giving read permission should/does not give build permission else each time read permission are given, build permission also are given. This is not the right behaviour.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16dbd9ca-dcd3-a4f3-43a8-01ead54fc9f9
* Version Independent ID: 66217fc3-a852-201c-a563-54ecbd9e5726
* Content: [Build permission for shared datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-build-permissions)
* Content Source: [powerbi-docs/connect-data/service-datasets-build-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-build-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Ilocans. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @Ilocans , thanks for your comment. I have taken this up with the product team and we'll update the docs to be more clear. Thanks again for taking the time to write.
