### ISSUE TITLE
private svg:Selection<SVGElement> throw an error

### ISSUE THREAD

**Issue by novascotia10** [MicrosoftDocs/powerbi-docs#4845]
This page doesn't represent accurate information and outdated steps
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fd119235-31a3-4c74-9aed-848d2438c0ef
* Version Independent ID: 87eb1e86-6977-00df-a032-8f1c2ccb48ef
* Content: [Learn how to develop your own Power BI visual using the circle card visual as an example. - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/develop-circle-card)
* Content Source: [powerbi-docs/developer/visuals/develop-circle-card.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/develop-circle-card.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for you feedback, @novascotia10. Sorry about the delayed response. Can you please be more specific about what you found outdated and inaccurate? If you're still having trouble, please open a new issue with more details. Thanks.
