### ISSUE TITLE
Report Server Saving Vs Publishing

### ISSUE THREAD

**Issue by kshelton23** [MicrosoftDocs/powerbi-docs#4846]
Currently with PowerBI (free) you are able to save(publish) reports to PowerBI server without a Pro or Premium license. Can we get clarification in this document that states the difference between saving a report to PowerBI Server that doesn't require a license and publishing a report to o365 which does require a license?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6e1bb7-fbc5-d0a6-5285-e4a9152902bb
* Version Independent ID: ece0823b-c4c5-3acb-41bb-55e5390c0b6c
* Content: [Power BI service features by license type - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type)
* Content Source: [powerbi-docs/fundamentals/service-features-license-type.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/service-features-license-type.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @kfollis
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kshelton23. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
Hi @kshelton23 - thank you for the feedback. Licensing information for Power BI Report Server can be found here: https://learn.microsoft.com/en-us/power-bi/report-server/get-started#licensing-power-bi-report-server - is this the information you need? Please clarify if I misinterpreted, but I assume you are referring to Power BI Report Server vs. the Power BI service, but please comment with more details about your scenario if that's not right!

**Comment by kshelton23** [comment]
I have a ticket open for that article as well because it is incorrect. You do not need a license to save to PowerBI Server #4830

**Comment by kfollis** [comment]
Aha! Thanks for connecting the dots for me. I better understand the scenario now - I'll get work items in place for making the content updates for that clarification.

**Comment by kfollis** [comment]
Article has been updated. Clarifications re Report Server are in https://github.com/MicrosoftDocs/powerbi-docs/issues/4830
#please-close
