### ISSUE TITLE
Add Datamart feature

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4847]
Can you add the Datamart feature to the table? Goal:  show if Datamarts are planned for Gov tenants and when.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-govus-overview)
* Content Source: [powerbi-docs/enterprise/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your suggestion. Datamarts are not currently planned for Gov tenants.

**Comment by GitWesDone** [comment]
Understood:  could this be reflected in the table as a new row, and using the "Not Planned" verbiage similar to other features not planned for government.  This provides official clarity on the intent for this feature in GCC*

**Comment by davidiseminger** [comment]
We don't usually document things that aren't planned, but I do see the value of that official clarity. Yes -- I've added that to the table, should show up later today (or on our next build run). Thanks for your persistence @GitWesDone  !
