### ISSUE TITLE
power bi automatic page refresh does not work in the cloud

### ISSUE THREAD

**Issue by zhuhongfei123test** [MicrosoftDocs/powerbi-docs#4848]
[Enter feedback here]

 
The power bi workspace I tested was a Premium workspace, mounted Embedded A1, and had the minimum auto page refresh interval set to 5 seconds in the Admin portal

 
Test steps:
 
1. A dataset was pre-published to this workspace as the data source

2. A new Power BI Desktop is opened and connected to the pre-released dataset. By default, the liveconnect connection mode is used, but the option to configure auto page refresh cannot be seen in the Power BI Desktop
 
 
3. When I tried to change the connection mode of this dataset from liveconnect to directquery in the Power BI Desktop, I saw the option to configure auto page refresh, and after publishing the report to the workspace, the automatic page refresh worked.
 
**The above test results are not consistent with the official documents.**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fedb7099-554f-0eed-eaa6-fc13851eb3b1
* Version Independent ID: 8beddbbe-5ebc-60e4-ab28-fd130283a8c1
* Content: [Automatic page refresh in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-automatic-page-refresh)
* Content Source: [powerbi-docs/create-reports/desktop-automatic-page-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-automatic-page-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zhuhongfei123test. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. We'll investigate those steps against the documentation and make appropriate updates.
