### ISSUE TITLE
Spruce up the visuals - missing one step?

### ISSUE THREAD

**Issue by thaohap** [MicrosoftDocs/powerbi-docs#4849]
[Enter feedback here]
Add a background shape for the title
I think there's a missing background shape for visuals 2 and 3 (the white bit) in the instruction.

Suggestion:

On the Insert ribbon, select Shapes > Rectangle, and stretch it to be the width and height of Visuals 2 and 3.
In the Format shape pane, in the Outline section, change Transparency to 100%.
In the Fill section, set the color to White.
On the Format tab, select Send backward > Send to back.

Hope this helps.

Thanks,

Thao

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 751771a8-ae97-2f7a-45f7-6eab5e30bb98
* Version Independent ID: 69b8d8ce-49e3-feb2-b751-c9a3c26bc501
* Content: [Tutorial: From dimensional model to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-gb/power-bi/create-reports/desktop-dimensional-model-report)
* Content Source: [powerbi-docs/create-reports/desktop-dimensional-model-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-dimensional-model-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thaohap. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @thaohap -- thanks for your suggestion. However, if I set the color of the box to just
"In the Fill section, set the color to White."
There would be no box. It's set to White, 10% darker, so we can see it. 
Or maybe I'm misunderstanding your comment?
If you'd like to comment more, please do! Select the Feedback hand at the top of the page.
Thanks!
