### ISSUE TITLE
Power Bi PDF Learning Document

### ISSUE THREAD

**Issue by snpruthvik** [MicrosoftDocs/powerbi-docs#485]
Power BI PDF learning document just downloading 1st page of contents but not full pdf
[d067af1e2e7b6b98f815910f9604f107 (1).pdf](https://github.com/MicrosoftDocs/powerbi-docs/files/2635614/d067af1e2e7b6b98f815910f9604f107.1.pdf)

**Comment by kfile** [comment]
Thanks @snpruthvik  for your question. I've assigned this to the author to check, though it may be an issue with our docs platform in which case another group would handle it.

**Comment by davidiseminger** [comment]
Sorry for the issue - it seems to be working properly now (I just checked).
