### ISSUE TITLE
WWW.fool.com has changed data source

### ISSUE THREAD

**Issue by kwajpaige** [MicrosoftDocs/powerbi-docs#4851]
www.fool.com has changed the original files in the data source. I was able to complete the tutorial :) but I had to improvise the directions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Tutorial: Shape and combine data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/connect-data/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kwajpaige. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your post, we've added a note that mentions website layouts may change, and steps might need to be adjusted.
