### ISSUE TITLE
What Power BI Desktop Version has PBIP 

### ISSUE THREAD

**Issue by txandrew** [MicrosoftDocs/powerbi-docs#4852]
What version of Power BI Desktop supports the Power BI project file (pbip)? I'm currently trying to get upgraded from 2.99, but don't know if my organization has approved the latest Desktop version that supports the save as feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Version Independent ID: d1b2ecab-08d6-e267-7ae6-119de463d769
* Content: [Power BI Desktop projects (PBIP) - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-overview)
* Content Source: [powerbi-docs/developer/projects/projects-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-overview.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @txandrew. This issue has been assigned to the doc author for review.

**Comment by txandrew** [comment]
Looks like it was first published in August

[Power BI August Release](https://powerbi.microsoft.com/en-us/blog/power-bi-august-2023-feature-summary/)

**Comment by txandrew** [comment]
Thanks for taking the time and using Github to make comments possible and effective
