### ISSUE TITLE
Add C++ Redistributable Packages to the Prerequisites

### ISSUE THREAD

**Issue by Fennerr** [MicrosoftDocs/powerbi-docs#4853]
The prerequisites did not cover everything - I was getting an ADO.NET: Python script error.
...
ImportError: DLL load failed while importing _cext: The specified module could not be found.

After googling around, I saw someone recommend that the Visual C++ Redistributable Package needs to be installed, which I got from here:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

After installing it, I could run python scripts.

I am using a relatively fresh install of windows 10 64bit, with python3.12, and the latest version of Power BI Desktop.

Please update the prerequisites to include this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Run Python scripts in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-python-scripts)
* Content Source: [powerbi-docs/connect-data/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-python-scripts.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Fennerr. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @Fennerr,

Thank you for this feedback. I'm looking into this and will update the document if needed.

Kesem

**Comment by KesemSharabi** [comment]
Hi @Fennerr,

I've verified that the **Run Python scripts in Power BI Desktop** [Prerequisites](https://learn.microsoft.com/power-bi/connect-data/desktop-python-scripts#prerequisites) are correct.

Perhaps you didn't use python 3.7.7?

Thanks,

Kesem
