### ISSUE TITLE
Need a warning about inability to update historic records

### ISSUE THREAD

**Issue by Nuglar** [MicrosoftDocs/powerbi-docs#4854]
There needs be be more clarity and/or warnings about setting up incremental refresh on tables that have records that get updated. Please see the following for the problem: https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-configure

Data profressionals with a data modelling background (I.E. most users setting up PBI incremental refreshes) when they see "incremental refresh" will assume that you can put the incremental column as the "updated date" metadat column, and it will load (and replace) records that have been updated since they were first inserted. This is not the case. It will load them, but it will not replace them if they are outside the incremental period. This is not made clear in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 703aa6c4-1701-ea81-5fe6-c0afd163021e
* Version Independent ID: 13601081-10c5-3947-f19b-daa8c44a5382
* Content: [Configure incremental refresh and real-time data for Power BI datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-configure)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-configure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-configure.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Nuglar. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
As of now, we haven't had any other instances of this issue for users.  We simply don't have the bandwidth to address this without further need. Closing for now to clear backlog.
