### ISSUE TITLE
wrong table name in DAX formula

### ISSUE THREAD

**Issue by BrettFromLA** [MicrosoftDocs/powerbi-docs#4856]
In the section titled "Let’s look at an example", Janice is creating a new measure in the Reseller Sales table. However, the DAX formula in the example references a nonexistent table named Sales:

**Projected Sales = SUM('Sales'[Last Years Sales])*1.06**

That formulas should be changed to the formula below:

**Projected Sales = SUM('Reseller Sales'[Last Years Sales])*1.06**

Also, the image below it shows the table name (in the Fields pane) as "financials". I'm not sure where that comes from. I think it should also be "Reseller Sales".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 014eede5-d529-cc7c-f8d5-3e7247ee857c
* Version Independent ID: 524645c5-86ea-ef3e-a020-c74b44db2c87
* Content: [Measures in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-measures)
* Content Source: [powerbi-docs/transform-model/desktop-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-measures.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BrettFromLA. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good points! I'll update the DAX sample.
