### ISSUE TITLE
glossary feature suggestion

### ISSUE THREAD

**Issue by monacojay** [MicrosoftDocs/powerbi-docs#4858]
Should have a glossary. Like, I'm new here and learning about Power BI, but when it says "data model" I have no idea what that is. It would be nice to have glossary of terms with a connected hover feature for common technical terms a self-taught newb like myself might find useful. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-what-is-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @monacojay. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion, we'll look into creating that. Meanwhile, search can be very useful.
