### ISSUE TITLE
No Outline Section for Shape formating

### ISSUE THREAD

**Issue by cowhitley** [MicrosoftDocs/powerbi-docs#4859]
In the format report section of the instructions the following option no longer appears to be available as I'm unable to find an outline section in the Format shape pane.

_In the Format shape pane, in the Outline section, change Transparency to 100%_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @cowhitley. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Greate question, @cowhitley ! Turns out they changed it. Now it's:
In the **Format shape** pane, in the **Visual border** section, set it to **Off**.
