### ISSUE TITLE
Azure Service Bus deployment

### ISSUE THREAD

**Issue by Simon999** [MicrosoftDocs/powerbi-docs#486]
What is not clear, do we need out own Azure subscription to deploy the Azure Service Bus? Or is this handled as part of the Power BI service, and invisible to us?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb1195df-a72b-61c1-3490-64ca851e81b1
* Version Independent ID: 8e9e2f51-78eb-7dfc-8195-cf99bd55d61c
* Content: [What are Power BI gateways? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started)
* Content Source: [powerbi-docs/service-gateway-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-getting-started.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hello, @Simon999 
Your contribution is much appreciated. I've passed along your question to the doc owner, who will respond shortly.
Kind regards,
Microsoft DOCS International Team

**Comment by cbailiss** [comment]
@Simon999 For Power BI, it is part of the Service and does not need to be set up separately.  I suspect most users do not know it is being used / exists.

**Comment by mgblythe** [comment]
I'm adding the following sentence to this article + another one that mentions Service Bus:

Power BI manages the Service Bus for you, so there are no additional costs or configuration steps required.
