### ISSUE TITLE
Prerequisites - should this also include Fabric Capacity options?

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#4860]
[Enter feedback here]
https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export#prerequisites

I noticed that this doc calls out Power BI Premium capacity as a prerequisite, but does not reference Fabric Capacity.
Is this workload not supported with Fabric Capacity?  If it is, we should update this doc as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfohl. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Good point, @elfohl ! Yes, you're right. I'll make that update.
