### ISSUE TITLE
'Query overly complex' needs clarification

### ISSUE THREAD

**Issue by JTDotNet** [MicrosoftDocs/powerbi-docs#4861]
The section 'Other DirectQuery Limitations' contains the text 'If the Power Query Editor query is overly complex, an error occurs. To fix the error, you must either delete the problematic step in Power Query Editor, or switch to import mode.'

Developers shouldn't be expected to spend large amounts of time probing around a black box which will throw out errors with no guidance as to the underlying principles of why it is behaving the way it is. Documentation covering the logic of supported and non-supported queries is required. I have just discovered that while the Date.Year M function is supported, the Date.Month and Date.Day functions aren't. This is too involved to simply guess our way around.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-use-directquery)
* Content Source: [powerbi-docs/connect-data/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-use-directquery.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JTDotNet. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback, we'll try to make the documentation clearer and more usable in those situations.
