### ISSUE TITLE
"Before submitting a Support request"

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4863]
I think this text should link to https://learn.microsoft.com/en-us/power-bi/support/create-support-ticket

Thank you for considering this change.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Version Independent ID: f647b6e3-c651-b39b-56d5-f919184c92c1
* Content: [Power BI known issues - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/power-bi-known-issues)
* Content Source: [powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/power-bi-known-issues.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @djurecic0 ,
Thank you for contacting us and for your suggestion.  Since this is a known issues article, the sentence is suggesting that before submitting a Support request, check to see if we already know about the problem (and are working on it).  The current link goes to the report that lists known issues by experience -- which is the correct location.  If this is unclear, please let me know.

**Comment by djurecic0** [comment]
Hi Michelle,
 Thanks for your response. I was not suggesting that the current links are wrong or should be changed.

I was suggesting that since this page mentions creating a support request, it would be nice to add a link to the page “Create a support ticket”  (https://learn.microsoft.com/en-us/power-bi/support/create-support-ticket) to make it easier for users to learn how to submit a support request.

It does make sense that submitting a support request is not the purpose of this page since there is a separate page that deals with submitting a support request.

Best,
Dean
