### ISSUE TITLE
Errors in Chinese version of "desktop-r-ide.md"

### ISSUE THREAD

**Issue by shujuecn** [MicrosoftDocs/powerbi-docs#4865]
In the [desktop-r-ide](https://learn.microsoft.com/zh-cn/power-bi/connect-data/desktop-r-ide) page, "R IDE" was miswritten as "Python IDE".

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/50800313/cb6e8882-a3dd-4cc6-8e20-fd7e62710ef7)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shujuecn. This issue has been assigned to the doc author for review.
