### ISSUE TITLE
Premium Only or Not?

### ISSUE THREAD

**Issue by KornAlexander** [MicrosoftDocs/powerbi-docs#4866]
Please be more specific if this is a premium only feature or not. If it is indeed premium only please include it in the other documentation: https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-features

"multiple-language reports might not work as expected." What specifically might not work?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52877790-6fbe-d274-3ff2-ecda89bf6c45
* Version Independent ID: 52877790-6fbe-d274-3ff2-ecda89bf6c45
* Content: [Plan translation for multiple-language reports in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/multiple-language-translation)
* Content Source: [powerbi-docs/guidance/multiple-language-translation.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/multiple-language-translation.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KornAlexander. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for your question, @KornAlexander ! I'll check with the product team and update the article.
