### ISSUE TITLE
Outdatedd information

### ISSUE THREAD

**Issue by PbBarney** [MicrosoftDocs/powerbi-docs#4868]
Two things:

1.  The "Fields" pane is now "Data"
2.  Instructions before the "Build your report" step is unclear.  https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#build-your-report

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report#build-your-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @PbBarney. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @PbBarney -- I've added another screenshot to show the table you create.
https://review.learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report?branch=pr-en-us-11920#create-a-new-table
I hope that helps! If not, you can add more feedback by using the feedback link on the article.
Thanks!
