### ISSUE TITLE
Not good  idea to translate (Microsoft) Fabric as "Tejido"

### ISSUE THREAD

**Issue by HermesMG** [MicrosoftDocs/powerbi-docs#4869]
Not good  idea to translate (Microsoft) Fabric as "Tejido"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d638bfd6-4966-689c-d59f-dc468f7260ca
* Version Independent ID: d638bfd6-4966-689c-d59f-dc468f7260ca
* Content: [New name for Power BI datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-rename?source=docs)
* Content Source: [powerbi-docs/connect-data/service-datasets-rename.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-rename.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @HermesMG. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @HermesMG - thanks for your feedback. I can't see where the word _Fabric_ was incorrectly translated. Can you please provide the precise link you used to access the article?
