### ISSUE TITLE
uploading brand files to azure report server tutorial

### ISSUE THREAD

**Issue by zotechdigital** [MicrosoftDocs/powerbi-docs#487]
I'm just experimenting with the branding elements of the report server and would like to upload a zip containing the json ,png and xml files. Any way of of adding these onto the test VM I've set up?

**Comment by kfile** [comment]
Thanks @zotechdigital for your question. I've assigned this to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @zotechdigital -- belatedly, are you familiar with the article about branding the web portal? https://docs.microsoft.com/en-us/sql/reporting-services/branding-the-web-portal?view=sql-server-2017
Does it contain any useful info for you?
