### ISSUE TITLE
Non-sense text

### ISSUE THREAD

**Issue by marciotex** [MicrosoftDocs/powerbi-docs#4871]
Hi

This text "Replace <Your File Path> with the path to EuStockMarkets_NA.csv on your local file system, for example, C:/Users/admin/Documents/Microsoft/EuStockMarkets_NA.csv." doesn´t make sense since script dont have file path.

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4253d0e-7a9f-a0a7-edee-4cbd387ec98d
* Version Independent ID: 14a7818e-43ac-86ca-a4a1-d4da38441e42
* Content: [Use R in Power Query Editor - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-r-in-query-editor)
* Content Source: [powerbi-docs/connect-data/desktop-r-in-query-editor.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-r-in-query-editor.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marciotex. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Good point - I've removed that passage. Thanks!
