### ISSUE TITLE
Power Bi excel export 

### ISSUE THREAD

**Issue by Jaya-sys** [MicrosoftDocs/powerbi-docs#4872]
Hello, I am trying to export the file in xlsx format . while i can download the file the content is corrupted. Because the content is not properly encode.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jaya-sys. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Jaya-sys. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
