### ISSUE TITLE
Use of PBI Free license with premium capacities 

### ISSUE THREAD

**Issue by Jas73** [MicrosoftDocs/powerbi-docs#4873]
Hi, 

When I look at the Fabric license page it says P1 or F64-SKU or above to be able to use the PBI Free license to consume, which I've heard and known for a long time - https://learn.microsoft.com/en-us/fabric/enterprise/licenses#capacity-license, but when I look at the page for Embedded SKU's https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#which-sku-should-i-use. it says that from F32-SKU or bigger allows PBI Free users to consume (internal & external). Am I missing something here or is the documentation wrong?

Best regards
Johan Åslund
Intelligence TS | Microsoft

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72fa2a8f-51b8-14fc-5c99-7875d009d5f3
* Version Independent ID: 2bd4bd19-28f7-7c64-2a5f-fb2b368ab088
* Content: [Capacity and SKUs in Power BI embedded analytics - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity#which-sku-should-i-use)
* Content Source: [powerbi-docs/developer/embedded/embedded-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embedded-capacity.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jas73. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @Jas73. You're right. It should be 64. I'll update the doc.

**Comment by Jas73** [comment]
[like]  Johan Åslund reacted to your message:
________________________________
