### ISSUE TITLE
sync possibility with a "personal dev" workspace

### ISSUE THREAD

**Issue by wrende** [MicrosoftDocs/powerbi-docs#4874]
The following image shows that there is a sync possibility with a "personal dev" workspace.
![image](https://learn.microsoft.com/en-us/power-bi/developer/projects/media/projects-build-pipelines/pipeline.png)

Where can I find documentation for this specific sync, is this also possible with PowerBI Pro or Premium?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f25aa02c-35e6-7554-a78d-cf79c50bc5eb
* Version Independent ID: f25aa02c-35e6-7554-a78d-cf79c50bc5eb
* Content: [Azure DevOps build pipeline integration with Power BI Desktop projects - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-build-pipelines)
* Content Source: [powerbi-docs/developer/projects/projects-build-pipelines.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-build-pipelines.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wrende. This issue has been assigned to the doc author for review.

**Comment by RuiRomano** [comment]
Sorry for the confusion and we will update the diagram. But, no you cannot sync with a Personal Workspace. Its not yet supported by Fabric Git Integration.
The "{Personal Dev} Workspace" meaning is the "Develop using another workspace" isolation described in our docs: https://learn.microsoft.com/en-us/fabric/cicd/git-integration/manage-branches#develop-using-another-workspace.
