### ISSUE TITLE
Limitations- reports cannot be created from Power BI Desktop

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4876]
I believe that you must create a report from the Power BI service to use Direct Lake. Creating a report from Power BI desktop creates a live connection to the Power BI dataset/semantic model and does not use Direct Lake.

If this is correct, I believe that this should be noted as a limitation of Direct Lake. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Version Independent ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Content: [Learn about Direct Lake in Power BI and Microsoft Fabric - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview)
* Content Source: [powerbi-docs/enterprise/directlake-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by djurecic0** [comment]
Hi @bishalgoswami I'd like to withdraw/delete this comment.

**Comment by djurecic0** [comment]
I see that it is possible to create a report, but it will show up as Live Connection in PBI desktop.
