### ISSUE TITLE
Guide on how to perform this is missing

### ISSUE THREAD

**Issue by AndersZH** [MicrosoftDocs/powerbi-docs#4877]
[Enter feedback here]
This article should contain guidelines, examples or links on how to perform the disable/enable operations. Both on an individual product level as well as on a global organizational level. Especially the last option is important, so you wont have to manage each single product when it is a corporate policy to not allow self-service sign-up.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea9dfd7d-af97-e666-e94f-d15e5f016df3
* Version Independent ID: ea9dfd7d-af97-e666-e94f-d15e5f016df3
* Content: [Enable or disable self-service sign-up and purchasing - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-disable-self-service)
* Content Source: [powerbi-docs/enterprise/service-admin-disable-self-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-disable-self-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AndersZH. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @AndersZH , 
Thank you for your suggestion.  We've made the update and set the article to republish. The article now links to: https://learn.microsoft.com/microsoft-365/commerce/subscriptions/manage-self-service-purchases-admins?view=o365-worldwide&source=recommendations.
All the best,
The DOCS team

**Comment by AndersZH** [comment]
Excellent. What a quick update. Good work.
