### ISSUE TITLE
Update Power BI, refresh data

### ISSUE THREAD

**Issue by GGBMLC** [MicrosoftDocs/powerbi-docs#4878]
[Enter feedback here]
Why is there not a default setting in Quercy  to only load new data from the SQL DB?

Why use so many code/setting for a simple GUI function?

Filter RowS > is in the prvious   XX days " is also not working well. 

Missing a BASIC function for. "only load new rows in the SQL DB"? 

Br
Bo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23849d95-194e-b2b1-735a-03aebb56703a
* Version Independent ID: 391f63a3-2b18-3676-a151-d9859df54ad6
* Content: [Incremental refresh for semantic models and real-time data in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/incremental-refresh-overview)
* Content Source: [powerbi-docs/connect-data/incremental-refresh-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/incremental-refresh-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GGBMLC. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
This isn't a documentation issue. Please submit your idea to https://ideas.fabric.microsoft.com/
