### ISSUE TITLE
DirectLake vs live connection

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4879]
This may be outside of the scope of the article, but when I follow the steps below, how can I tell if the connection is live connection or direct lake? 

_In Get Data > Power Platform, select Power BI datasets, and then select Connect.

In the Data hub page, select the Direct Lake dataset you want to connect to, and then select Connect._

Looking at the modeling view in PBI desktop, it says that the table datasource is SQL Server Analysis Services database and the storage mode under Properties- Advanced is blank.
 
As a follow up, If users are not able to tell if a storage mode is Direct Lake or Live connection except by running query analyzer, should that be considered a limitation of Direct Lake.? Finally, is it possible to test the connection as DirectLake, then when the report is published, it fails over to DirectQuery?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Version Independent ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Content: [Learn how to analyze query processing for Direct Lake datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-analyze-qp)
* Content Source: [powerbi-docs/enterprise/directlake-analyze-qp.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-analyze-qp.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.
