### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#488]
@IgorRozani commented on [Fri Oct 19 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9)

The link "the index" in the README file is broken.

![image](https://user-images.githubusercontent.com/802968/47243450-6c60c000-d3c8-11e8-99e3-280095530c12.png)

---

@CeciAc commented on [Tue Oct 30 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9#issuecomment-434310790)

Hi @Alisha-Acharya 
Please, check this issue

---

@CeciAc commented on [Mon Nov 12 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9#issuecomment-437978148)

Hi @Alisha-Acharya @JasonCard 
any update on this?

---

@CeciAc commented on [Tue Nov 20 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9#issuecomment-440317867)

Hi @Alisha-Acharya @JasonCard
any update on this?

---

@CeciAc commented on [Tue Nov 27 2018](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9#issuecomment-442108842)

Hi @Alisha-Acharya @JasonCard
any update on this?
@DavidPrio FYI

**Comment by JasonCard** [comment]
Hi @mihart @CeciAc @Alisha-Acharya 
I've looked into this and found that README.md was outdated in loc repos due to localization tooling issue. Opened [Loc Issue 54773](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/54773) for following up on this issue.
cc @bodhigautam

**Comment by JasonCard** [comment]
@mihart @CeciAc You may close this issue here as it's localization issue and we will follow up in [https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/9).

**Comment by JasonCard** [comment]
@mihart @CeciAc [https://github.com/MicrosoftDocs/powerbi-docs-pr.pt-br/blob/live/README.md](https://github.com/MicrosoftDocs/powerbi-docs-pr.pt-br/blob/live/README.md) has been updated and this issue has been resolved. I don't have access to close this issue, so please help to close. 
cc @Alisha-Acharya
