### ISSUE TITLE
Issues and limitations- Views

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4880]
Can you please provide more information about views and DirectLake?

This sentience seems to indicate that DirectLake does support views:
_Direct Lake models can only contain tables and views from a single Lakehouse or Data Warehouse._

However, this seems to indicate that DirectLake does not support views:
_Tables based on TSQL-based views cannot be queried in Direct Lake mode_

What is the difference if any between views in the first sentence and "Tables based on TSQL-based views" in the second?

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Version Independent ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Content: [Learn how to analyze query processing for Direct Lake datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-analyze-qp)
* Content Source: [powerbi-docs/enterprise/directlake-analyze-qp.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-analyze-qp.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.
