### ISSUE TITLE
You can disable fallback to DirectQuery mode if you prefer to process DAX queries in pure Direct Lake mode.

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4881]
Can you please provide more information or a link on how to disable fallback to DirectQuery mode?

Thanks,
Dean

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Version Independent ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Content: [Learn about Direct Lake in Power BI and Microsoft Fabric - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#fallback)
* Content Source: [powerbi-docs/enterprise/directlake-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.
