### ISSUE TITLE
DirectLake mode?

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4882]
Are there plans to include DirectLake in this article?

According to this page, https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview#fallback, Power BI semantic models can be in Direct Lake mode.

"Power BI semantic models in Direct Lake mode read delta tables directly from OneLake."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4113f426-5c74-c68d-781b-be0bb9358db1
* Version Independent ID: 4ef47ef7-0502-4161-a43e-4eabc3545931
* Content: [Semantic model modes in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-dataset-modes-understand#directquery-mode)
* Content Source: [powerbi-docs/connect-data/service-dataset-modes-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-dataset-modes-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @djurecic0. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback and suggestion. We'll look into adding that in future updates / reviews.
