### ISSUE TITLE
Save queries to separate files

### ISSUE THREAD

**Issue by KennethBWSong** [MicrosoftDocs/powerbi-docs#4883]
In current power bi projects, we can find the queries in models.bim. Do we have any support to separate the queries (like content in the image) to different files? It's a better way to host the queries.
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/63089166/7a6c9960-ec9e-4c0f-87ed-67acaf29a532)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aa0561f3-eb9c-ecd5-b97a-52ecee0fc759
* Version Independent ID: aa0561f3-eb9c-ecd5-b97a-52ecee0fc759
* Content: [Git integration with Power BI Desktop projects - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/projects/projects-git)
* Content Source: [powerbi-docs/developer/projects/projects-git.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/projects/projects-git.md)
* Service: **powerbi**
* Sub-service: ****
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KennethBWSong. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@KennethBWSong - Please submit your idea at https://ideas.fabric.microsoft.com/
