### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by FRFR-LO** [MicrosoftDocs/powerbi-docs#4884]
Hi there,
In this part: https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-migration-requirements#gather-report-requirements

"_Identify the report owner and any subject matter expert(s) associated with the report or data domain. **They** might become the owners of the new Power BI report going forward._"

I would like to know if "They" ("They might become") refers to "any subject matter expert(s)" only, or includes "the report owner" too?

Could you help me with that?
Thanks,
François

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d5c14784-da2e-bbd0-88f0-e86308ed38a5
* Version Independent ID: 103e879d-a23e-d973-9529-11b383935001
* Content: [Gather requirements to migrate to Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-migration-requirements#gather-report-requirements)
* Content Source: [powerbi-docs/guidance/powerbi-migration-requirements.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-migration-requirements.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @FRFR-LO. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @bishalgoswami - "they" could mean either one.

#please-close

**Comment by KesemSharabi** [comment]
Closing this GitHub issue. @peter-myers, please consider clarifying this in the doc.
