### ISSUE TITLE
Is there a version of these support pages that is appropriate for the licence my org has?

### ISSUE THREAD

**Issue by hasseldine** [MicrosoftDocs/powerbi-docs#4885]
Every time I think "what a great feature - I'll use that" there's a disclaimer at the bottom that it's a premium-only feature. I would love a support page with only information that is relevant to the product (PBI Pro) that I can actually access via my org account. I don't care about features that aren't even available and there's no info at the TOP of each section to say which product levels the section relates to.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0dcf4e23-69b7-0a67-5d67-315ea36f5490
* Version Independent ID: 0a4fdf12-27bd-d3f1-b94a-761cd2e0dd47
* Content: [Creating a dataflow - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-create)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-create.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-create.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @hasseldine. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your doc update request/suggestion. We'll consider updating this article / creating such a table or banner for each section.
