### ISSUE TITLE
the document isn't updated with the current sample dataset

### ISSUE THREAD

**Issue by Eakta08** [MicrosoftDocs/powerbi-docs#4886]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 751771a8-ae97-2f7a-45f7-6eab5e30bb98
* Version Independent ID: 69b8d8ce-49e3-feb2-b751-c9a3c26bc501
* Content: [Tutorial: From dimensional model to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-gb/power-bi/create-reports/desktop-dimensional-model-report)
* Content Source: [powerbi-docs/create-reports/desktop-dimensional-model-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-dimensional-model-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Eakta08. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Eakta08 -- can you provide a little more detail? I think the current sample dataset and the article are close enough that the reader can follow along.
