### ISSUE TITLE
instructions - need one more

### ISSUE THREAD

**Issue by dixonland** [MicrosoftDocs/powerbi-docs#4887]
Need to add an instruction how to do this step:  Hide summarizable fact-type table columns—this way, only measures can be used to summarize the fact-type table
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 864a3cfe-f1fb-342a-cf76-9603a81e64f9
* Version Independent ID: 59891c79-e71c-96e4-79ad-58853c6b9f0d
* Content: [Many-to-many relationship guidance - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/relationships-many-to-many)
* Content Source: [powerbi-docs/guidance/relationships-many-to-many.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/relationships-many-to-many.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dixonland. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your doc update suggestion. We'll look at updating that in our next review.
