### ISSUE TITLE
Dataflow Gen2 and AutoML

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4888]
It seems the information in this page is applicable to legacy (Gen1) dataflows, at least in as far as AutoML is concerned. Is this the case? 

If so, what's the recommended approach for Gen2?

I think these aspects are important to clarify in the documentation, especially now that Gen2 is GA.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 301c08b2-df76-b3b0-5035-7413d8b9d447
* Version Independent ID: f6d974e6-d13a-0413-6d50-3b5a93447600
* Content: [Use Machine Learning and Cognitive Services with dataflows - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/dataflows/dataflows-machine-learning-integration)
* Content Source: [powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/dataflows/dataflows-machine-learning-integration.md)
* Service: **powerbi**
* Sub-service: **powerbi-ai**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

**Comment by davidiseminger** [comment]
Oops - reopening, applied to the wrong PR!
