### ISSUE TITLE
This feature is now GA

### ISSUE THREAD

**Issue by R1k91** [MicrosoftDocs/powerbi-docs#4891]
Blue box on top says
"Semantic model scale-out is currently in preview."

according to this arcticle https://powerbi.microsoft.com/en-us/blog/empower-power-bi-users-with-microsoft-fabric-and-copilot/

this feature is in GA

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Version Independent ID: b3d4befd-cdb9-2add-1b27-114166b21526
* Content: [Power BI semantic model scale-out - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-scale-out)
* Content Source: [powerbi-docs/enterprise/service-premium-scale-out.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-scale-out.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @R1k91. This issue has been assigned to the doc author for review.
