### ISSUE TITLE
Direct Lake- only in Lakehouse

### ISSUE THREAD

**Issue by djurecic0** [MicrosoftDocs/powerbi-docs#4893]
If DirectLake only applies to Lakehouse, what does it mean that SQL views "in a Warehouse" can cause fallback to direct query?
 
Can you please clarify how SQL views in a Warehouse apply to DirectLake?

Also, why do views show as DirectLake in the data model view in the PBI service if they are not supported for DirectLake? Attached image as an example.
![View with DirectLake Storage Mode](https://github.com/MicrosoftDocs/powerbi-docs/assets/76531789/93695d64-2ffa-42f5-8136-0509c2de12d6)

_Typical fallback reasons include memory pressures that can prevent loading of columns required to process a DAX query, and certain features at the data source might not support Direct Lake mode, like SQL views in a Warehouse._ 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Version Independent ID: ab036a43-788f-3e66-21ab-ca34bba6c8b2
* Content: [Learn how to analyze query processing for Direct Lake datasets - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-analyze-qp?WT.mc_id=DP-MVP-5003435)
* Content Source: [powerbi-docs/enterprise/directlake-analyze-qp.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-analyze-qp.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by Minewiskan** [comment]
"If DirectLake only applies to Lakehouse, " - This was true in early preview, but no longer the case. Warehouse is supported in GA.

**Comment by djurecic0** [comment]
Owen,
Thank you for the clarification.

-Dean
