### ISSUE TITLE
Documentation error on how to assign EM capacity.

### ISSUE THREAD

**Issue by kelleylong-m** [MicrosoftDocs/powerbi-docs#4895]
In the documentation, it mentioned:
"To enable Premium capabilities for P and EM SKUs, set the license mode to Premium per capacity. To enable Premium capabilities for A SKUs, set the license mode to Embedded. "

However, currently in Power BI Service, EM SKU are assigned under the "Embedded" option which is different from what mentioned in the documentation.

https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-capacity-manage

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kelleylong-m. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @kelleylong-m,

I'm checking the validity of the document and will get back to you.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @kelleylong-m,

You're right, to enable Premium capabilities for SKUs, you need to use the *Embedded* option.

Thank you for bringing this to our attention. I made the changes in the article and they will soon be published.

Kesem
