### ISSUE TITLE
Stored Credentials for RLS/OLS in Direct Lake mode

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#4896]
At Ignite Microsoft [announced](https://powerbi.microsoft.com/en-us/blog/empower-power-bi-users-with-microsoft-fabric-and-copilot/) stored credentials to enable RLS/OLS in Direct Lake mode:

"For more information about how to set up stored credentials, see the [Direct Lake](https://learn.microsoft.com/power-bi/enterprise/directlake-overview) product documentation."

There's nothing about stored credentials on the Direct Lake page, and nothing about Direct Lake on the RLS/OLS page.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Version Independent ID: b4140ce1-5f43-81b2-36c4-cf90b2a72682
* Content: [Learn about Direct Lake in Power BI and Microsoft Fabric - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/directlake-overview)
* Content Source: [powerbi-docs/enterprise/directlake-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/directlake-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @otravers 
You're correct, that RLS wasn't working when the blog came out. It's working now and I added a link.
