### ISSUE TITLE
Unclear on minimum capacity requirements to enable Power BI Free License holders to consume content

### ISSUE THREAD

**Issue by joe-plumb** [MicrosoftDocs/powerbi-docs#4898]
Hi,

I am trying to determine the minimum F SKU size required to enable Power BI Free license holders to consume content from a Premium capacity, and am finding conflicting information in the documentation.

> A P or EM [capacity](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embedded-capacity) or [**Fabric F64 or greater capacity**](https://learn.microsoft.com/en-us/fabric/enterprise/licenses#capacity-and-skus). This configuration allows all users to have free licenses.

[Source](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-sample-for-your-organization?tabs=net-core#prerequisites)

> Only P SKUs and F SKUs larger than **F32** allow free Power BI users to consume Power BI apps and shared content in Power BI service. Smaller F SKUs require a Pro license to consume Power BI content.

[Source](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-license#licenses)

Is it F32 or F64?

Thanks

**Comment by bishalgoswami** [comment]
Thanks for your comment, @joe-plumb. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @joe-plumb,

Thanks for pointing out the confusion in our documentation. I believe that to enable Power BI Free license holders to consume content from a Premium capacity, you need an F64 SKU or a higher SKU.

However, I'm checking this with the product and engineering teams and will confirm shortly. After I get an answer, I'll also fix the docs.

Thanks,

Kesem

**Comment by KesemSharabi** [comment]
Hi @joe-plumb,

After speaking to the engineering team I can confirm that to consume content with a free license you need an F64 or higher SKU, or an equivalent A or P SKU. EM SKUs require a Pro license to access the portal.

I'll also clarify the documentation shortly.

Hope this helps,

Kesem
