### ISSUE TITLE
роро

### ISSUE THREAD

**Issue by muktarkhanabilda** [MicrosoftDocs/powerbi-docs#4900]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Get samples for Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/sample-datasets)
* Content Source: [powerbi-docs/create-reports/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @muktarkhanabilda. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @muktarkhanabilda. I have no idea what to do with it, so I'm closing it. If you wish to reopen it with more details, feel free to do so.
