### ISSUE TITLE
New Calculation Group Feature in PBI

### ISSUE THREAD

**Issue by r00tnpm** [MicrosoftDocs/powerbi-docs#4902]
I am using PBI Desktop Nov.2023 version. 

The new "calculation group" preview is very good, however, there are 2 issues:
1) No way to sort calculated items (cardinal)
2) Can format calculated items (other than dynamic formatting w/ measure, which has limitations). 

Both features are available from 3rd party plug-in, such as Tabular Editor, but not available in PBI. Hopefully they will be added soon!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b377ee06-5722-34e4-6bde-626de3ae6b8a
* Version Independent ID: b377ee06-5722-34e4-6bde-626de3ae6b8a
* Content: [Create calculation groups in Power BI (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/calculation-groups)
* Content Source: [powerbi-docs/transform-model/calculation-groups.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/calculation-groups.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @r00tnpm. This issue has been assigned to the doc author for review.
