### ISSUE TITLE
There seems to be a typo in 'al app'

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/powerbi-docs#4908]
Hello,

please note that 'al app' should probably be 'organizational app' in this sentence:

"To work around this issue by giving you access to update the _al app_, a workspace admin can temporarily grant you **Member** or **Admin** permissions on the workspace."

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 423e5aff-43d8-6342-a6da-25c246d9ca5a
* Version Independent ID: 423e5aff-43d8-6342-a6da-25c246d9ca5a
* Content: [Known issue - Contributor can't update organizational app - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-571-contributor-can-not-update-organizational-app)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-571-contributor-can-not-update-organizational-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-571-contributor-can-not-update-organizational-app.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **jessicamo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @QueryCoordinator. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @QueryCoordinator , 
Good catch! Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
