### ISSUE TITLE
Inconsistent sourcecode compare to example

### ISSUE THREAD

**Issue by novascotia10** [MicrosoftDocs/powerbi-docs#4909]
This is form the page;
// import "regenerator-runtime/runtime";
Latest source code doesn't have the line
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/85726725/6031dea7-ec42-4708-b0ba-4fc6502f0091)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart visual in Power BI - Power BI](https://learn.microsoft.com/en-sg/power-bi/developer/visuals/create-bar-chart?tabs=CreateNewVisual)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by mberdugo** [comment]
Thanks for your comment, @novascotia10. 
I'm not sure what you are asking. The sample code on the page is the same as the source code here: https://github.com/microsoft/PowerBI-visuals-sampleBarChart/blob/barChartTutorial/src/barChart.ts
Where is the inconsistency?

**Comment by novascotia10** [comment]
Hi @mberdugo  so sorry for the confusion. In my local workspace i need to commented the line // import "regenerator-runtime/runtime", for the barchart script to work. I used the same repo as per link, looking for a file that maybe related to specific file within the repo, but find none.

**Comment by mberdugo** [comment]
Thanks for the clarification, @novascotia10. I discussed your comments with our engineers and as it turns out, the code on this page is old and being updated. The updated version should be available soon.
