### ISSUE TITLE
Inconsistent Source code against example

### ISSUE THREAD

**Issue by novascotia10** [MicrosoftDocs/powerbi-docs#4910]
[Enter feedback here]
Here is the snapshot of the section of source code, with this code, it gives  1 color series(even though there are more than 1 category from the data point) resulting on same category render in formatting pane because index was set to 1. This made the example confusing at first because why are the example adding loops if it is not to handle dynamic series color
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/85726725/463a86fa-6149-400a-a312-bb9219aa2334)
replace with this will render proper formatting pane with all series from data, which give dynamic color rendering
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/85726725/7891d5d7-1ceb-4963-841c-5011f6e9fa20)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-bar-chart?tabs=CreateNewVisual)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @novascotia10. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @novascotia10. I'll bring this up with the engineers and update the code, if necessary.

**Comment by mberdugo** [comment]
Thanks again for bringing this to my attention, @novascotia10. I changed the code as you suggested as a temporary fix.
All the code here will be revised and updated soon.
