### ISSUE TITLE
Inconsistencies between enterprise content publishing scenarios

### ISSUE THREAD

**Issue by adamgrisdale** [MicrosoftDocs/powerbi-docs#4914]
The [scenario diagram](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing#scenario-diagram) depicts that the development workspace should be synced to the main branch, then content is pushed through to test and production using Power BI Deployment Pipelines.

Further down in the article, the [collaboration flow diagram](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing#collaboration-flow-diagram), particularly items 7, 8 and 9, state that there should be multiple branches. This implies that each dev/test/prod workspace is also synced to those branches using the git sync feature.

To me this is confusing. Is the documentation saying to sync the dev workspace to the main branch, or is it saying to have multiple branches syncing to multiple workspaces, aka sync the dev workspace to the dev branch, test workspace to the test branch, and production workspace to the production/main branch?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff3cd434-f233-3be0-2ed7-51d98e799f5f
* Version Independent ID: ff3cd434-f233-3be0-2ed7-51d98e799f5f
* Content: [Power BI usage scenarios: Enterprise content publishing - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adamgrisdale. This issue has been assigned to the doc author for review.

**Comment by adamgrisdale** [comment]
Thanks @data-goblin, love your work. Had a look through the diffs and the new changes look really good and do make it clearer regarding which workspaces do/don't sync. Item 9 on the collaboration flow diagram makes it clear that the dev workspace is to be synced to the main branch.
