### ISSUE TITLE
Collaboration flow diagram shows old version in preview, but new version which clicked on/expanded

### ISSUE THREAD

**Issue by adamgrisdale** [MicrosoftDocs/powerbi-docs#4916]
The [collaboration flow diagram](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing#collaboration-flow-diagram) shows an older version of the diagram on the page, but when clicking on it to expand it, shows the newer version.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/58644518/60c43273-3809-4cc5-93b2-8991f5e0b4d6)

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/58644518/184e05bf-e357-44cb-9c62-79018908c47b)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff3cd434-f233-3be0-2ed7-51d98e799f5f
* Version Independent ID: ff3cd434-f233-3be0-2ed7-51d98e799f5f
* Content: [Power BI usage scenarios: Enterprise content publishing - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing)
* Content Source: [powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/powerbi-implementation-planning-usage-scenario-enterprise-content-publishing.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by peter-myers** [comment]
Hi @adamgrisdale - I've just checked, and the images (inline and expanded) have been published. Perhaps your browser has cached the older version? Can you please reload your browser (Ctrl+F5) and determine whether that load the newer image? Thanks.

**Comment by adamgrisdale** [comment]
Yes this is now showing correctly, thank you!

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adamgrisdale. This issue has been assigned to the doc author for review.
