### ISSUE TITLE
Donwlaod the pbix file of the Power BI Monthly new features

### ISSUE THREAD

**Issue by dhania-m** [MicrosoftDocs/powerbi-docs#4918]
Hello

Can you please insert a link on this page so that we can download the pbix file that you are using during the power bi monthly features video ?

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI update - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dhania-m. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion, we'll look at adding that link in future updates.
