### ISSUE TITLE
Not working with Nov-2018 power bi update 

### ISSUE THREAD

**Issue by maverickbhuvi** [MicrosoftDocs/powerbi-docs#492]
Error : Collection was modified; enumeration operation may not execute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce75d8cd-195a-b057-bea9-6e250f58d3c8
* Version Independent ID: e5e294b3-56a5-44e6-3846-31a3cdbb19bc
* Content: [Third-party service: Google Analytics connector for Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/service-google-analytics-connector)
* Content Source: [powerbi-docs/service-google-analytics-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-google-analytics-connector.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @maverickbhuvi. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
