### ISSUE TITLE
Ambiguous information about composite models

### ISSUE THREAD

**Issue by barnabastoth16** [MicrosoftDocs/powerbi-docs#4920]
Hi there,

In this page in this [section ](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models#calculated-tables) it is stated:

_You can add calculated tables to a model that uses DirectQuery. The Data Analysis Expressions (DAX) that define the calculated table can reference either imported or DirectQuery tables or a combination of the two.

Calculated tables are always imported, and their data is refreshed when you refresh the tables. If a calculated table refers to a DirectQuery table, visuals that refer to the DirectQuery table always show the latest values in the underlying source. Alternatively, visuals that refer to the calculated table show the values at the time when the calculated table was last refreshed._

On the other hand in this [section ](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models#working-with-a-composite-model-based-on-a-semantic-model) it is stated:

_Calculated tables aren't supported in the Service using this feature. Attempting to perform a refresh on a semantic model with a calculated table or a calculated column that references a DirectQuery data source will result in a "Single sign-on (SSO) credential isn't provided" error message._

However, I understand that the first section is meant to be working in Power BI Desktop (and it works accordingly), but having the limitation in the Service is a huge issue. I understand the security implications why it is designed that way, but I see lot of frustrated people around this topic (solution works perfectly in Desktop but cannot be refreshed from the Service). 
Therefore I think for the first section you should include a huge warning referencing the second section and stating explicitly what is in the context of Desktop and what is in the context of the Service.

Thank you for your work!
ps: I think the feature is amazing, but quite intricate and community needs to get used to its peculiarities.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dffd6b4-434b-868e-56fe-a0f53fb655a1
* Version Independent ID: 894f109f-c20b-c9f3-0e42-f6980d454075
* Content: [Use composite models in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-composite-models)
* Content Source: [powerbi-docs/transform-model/desktop-composite-models.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-composite-models.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @barnabastoth16. This issue has been assigned to the doc author for review.

**Comment by barnabastoth16** [comment]
Great David! Thank you for it.
This [community question](https://community.fabric.microsoft.com/t5/Desktop/Field-parameters-in-local-composite-model-with-DirectQuery/m-p/3586050#M1179221) is also related to the topic, which I tried to address with an answer.

For sure there is more to the complete explanation, but this by design limitation could be better accepted if people were aware of the security implication taking place here: **evaluation of calculated opjects objects happens before RLS gets applied.** 
I think that little piece of information would add even more value to the edit, but is up to your discretion to elaborate on that.

Thank you for your work.
