### ISSUE TITLE
Following update to Power BI, the option to show values with no data has been removed

### ISSUE THREAD

**Issue by adam-pope-arup** [MicrosoftDocs/powerbi-docs#4921]
[Enter feedback here]
There is no option to show items with no values in the new interface; at least, not that I can find.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52f1d303-a1ee-766e-dac0-d68dad08080c
* Version Independent ID: 053d3adb-90c2-03ce-87c7-47d441a1a79e
* Content: [Show items with no data in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-show-items-no-data)
* Content Source: [powerbi-docs/create-reports/desktop-show-items-no-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-show-items-no-data.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @adam-pope-arup. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback, this feature is still operational. Since this may be a support request, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
