### ISSUE TITLE
Documentation doesn't match the actual product. 

### ISSUE THREAD

**Issue by fvalencia12** [MicrosoftDocs/powerbi-docs#4923]
[Enter feedback here]
After  Power BI UI got updated, the documentation doesn't match the actual user interface. This documentation states there is a drill through section under the visualization section, but now that everything is moved, I can't find that section anywhere. Have been at this for 40 minutes already. Should not be that hard.

Any help would be appreciated. 
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/70413619/d9bffc67-9a76-4111-aa7b-7f860b5d96c6)
 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Set up drillthrough in Power BI reports - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-drillthrough)
* Content Source: [powerbi-docs/create-reports/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-drillthrough.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @fvalencia12. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @fvalencia12 -- I'm so sorry for the frustration! Took me a while to find it, too. I'll update the article with this information.
Select the **Insert** menu, and select **Buttons** > **Blank**.
Now on the **Data/Drill** tab, select **Drill through**.
And fill in the **Apply drill down filters to** box.
