### ISSUE TITLE
View Usage Metric semantic model

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#4924]
We have many customers raising issues to open semantic model for usage metrics (UM). They try opening the settings from the UM report itself, which has never worked. Currently there is a new message requesting build permission & leading nowhere.
Can you please add somewhere a sentence / note.

Note: that UM semantic model settings and refresh history can only be accessed via Power BI settings (gear icon) and Semantic model tab. See section Update Credentials [https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#update-usage-metrics-report-credentials](url)
Trying to open from the Usage metrics report via using the View Semantic model, will lead into "Request build permission" instead of viewing the semantic model settings.

![UM_settings](https://github.com/MicrosoftDocs/powerbi-docs/assets/98977972/abbbcd00-9a0d-4cff-80d0-2f4bcbb37970)
![UM_settings_viewSM](https://github.com/MicrosoftDocs/powerbi-docs/assets/98977972/45f3588f-b737-4981-ab6b-4275adab968c)
![UM_settings_request permission](https://github.com/MicrosoftDocs/powerbi-docs/assets/98977972/c3924043-b04b-4e7a-ba77-7b4f69523142)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in workspaces (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @MartinaPoddana -- Great points! This article is out of date. I'm going to assign your comment to the author who owns this article now.

**Comment by maggiesMSFT** [comment]
Hi, @KesemSharabi -- I think you own this article now:
[Monitor usage metrics in workspaces (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)

**Comment by KesemSharabi** [comment]
@MartinaPoddana,

Thank you for your feedback. I added this as a future improvement request and will attempt to make this change soon.

Kesem
