### ISSUE TITLE
Visuals that support conditional formating

### ISSUE THREAD

**Issue by Mkimani305** [MicrosoftDocs/powerbi-docs#4925]
In the article, its mentioned that one limitation of conditional formatting is that its not supported in Table and Matrix visuals. However, this contradicts with below
https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-conditional-table-formatting

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3300d18-dfe1-a0a0-597e-2f5760924ca1
* Version Independent ID: 29fd380a-48fa-a99c-0e3a-4e3b314f99dd
* Content: [Conditional formatting of Power BI custom visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/conditional-format?tabs=getFormattingModel)
* Content Source: [powerbi-docs/developer/visuals/conditional-format.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/conditional-format.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mkimani305. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @Mkimani305.
Unfortunately, the conditional formatting API does not work with Table/Matrix dataview custom visuals.
The article you referenced is talking about native/ out of the box visuals, not custom visuals.
