### ISSUE TITLE
Reactive Limit Clarity

### ISSUE THREAD

**Issue by sarahmuma** [MicrosoftDocs/powerbi-docs#4926]
This part in the docs “If the subscriptions Budget is exhausted, Power BI is prevented from using the v-core resources for that subscription” is misleading for customers as cost management budgets only alert the customer but do not take action against resources.

In order for this to work “as advertised” in these docs, one could implement the following 
-	An Azure Policy to restrict the Resource Group to resources of type  "microsoft.powerbidedicated/autoscalevcores" only
-	An Action Group within the Azure Budget which calls a custom Azure PowerShell Runbook to get and delete all resources in the resource group. 
 
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/130933419/59483044-dcce-4c90-a9ed-76d6b9e63f80)
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/130933419/1b9914c1-913a-443f-b478-2b90be302d55)

the code for the runbook would be something like this: 
[PowerShellPowerBIAutoscale.txt](https://github.com/MicrosoftDocs/powerbi-docs/files/13709445/PowerShellPowerBIAutoscale.txt)

---

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea1adec6-8c0c-a72c-c165-19a72bae7cc6
* Version Independent ID: a2543cc8-a37b-dde4-b0fe-5ebeb9ed2560
* Content: [Power BI Premium FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-faq#how-can-i-control-the-costs-of-autoscaling-)
* Content Source: [powerbi-docs/enterprise/service-premium-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-faq.yml)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sarahmuma. This issue has been assigned to the doc author for review.
