### ISSUE TITLE
Bar Charts

### ISSUE THREAD

**Issue by shinyion** [MicrosoftDocs/powerbi-docs#4927]
[Enter feedback here]

Have you ever seen a bar chart that displays data for different categories over a time period? For example sales by month for different products? Why does your section on bar charts not cover this simple scenario? Do you even review these pages for quality or relevance?
Why even have it if there is no value? 

This is why I have coming to your corporate documentation, because it is verbose and pointless.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 69212c7b-4492-a044-a07b-05266b20e370
* Version Independent ID: cc3d001b-1d58-b3b5-62a6-95f3955bf733
* Content: [Visualization types in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-types-for-reports-and-q-and-a#bar-and-column-charts)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-types-for-reports-and-q-and-a.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @shinyion. This issue has been assigned to the doc author for review.
