### ISSUE TITLE
Conflicting master account information

### ISSUE THREAD

**Issue by gunna025** [MicrosoftDocs/powerbi-docs#493]
Under the *"Applying permission to your application with in Azure Active Directory"* section I see the following information. 

>Enable additional permissions for your application, in addition to what was provided on the app registration page. Sign in with the master account that you are using for embedding. **The master account needs to be a global admin account.**

And under *"Use the Azure Active Directory portal"* in step # 8

>The Grant Permissions action needs the master account to avoid being prompted for consent by Azure AD. If the account performing this action is a Global Admin, you need to grant permissions to all users within your organization for this application. **If the account performing this action is the master account and is not a Global Admin, you need to grant permissions only to the master account for this application.**

The former indicates that the master account used for embedding *needs* to be a global admin while the latter appears to contradict that statement. If the master account can grant permissions and not be a global admin, then why does my master account *need*  to be a global admin. 

Hoping you can provide some clarification on this, I would be happy to submit a PR to improve the docs based on the answer.

**Comment by mihart** [comment]
Hello, @gunna025 
Your contribution is much appreciated. I've forwarded your question to the doc owner who will respond soon.
Kind regards,
Microsoft DOCS International Team

**Comment by gunna025** [comment]
@mihart @markingmyname
Well, I can confirm through my own testing that the master account used for embedding does not **_need_** to be a global admin. It may be more convenient for the sake of the tutorial here, but makes for misleading and potentially dangerous documentation.

I had a global admin create the app registration and grant permissions, but the account used for communicating with the API and retrieving embed tokens (master account) is just a regular account, with a Power BI Pro license. Since the Power BI API requires you to pass the master account credentials to get an access token, suggesting it be a global admin is potentially dangerous if that request is not handled with care.

I would love to help fellow devs like myself by keeping the documentation as helpful and safe as possible.. Please let me know if you would like me to submit a PR to clarify the master account information.

**Comment by markingmyname** [comment]
@gunna025 Apologizes for the delayed response.  

Please feel free to submit a PR if you have information or corrections you feel need to be addressed in the documentation.

**Comment by markingmyname** [comment]
@gunna025 Thank you again for this feedback.  Due to some changes in the app registration tool and process, I will be updating that section in the embed for your customers and embed for you organization articles by the end of the month.

Please note that your PR was closed since I am going to make internal changes to the article and that would cause merge conflicts.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
