### ISSUE TITLE
Sign in fails for embedded report

### ISSUE THREAD

**Issue by ljtdream** [MicrosoftDocs/powerbi-docs#4932]
[Enter feedback here]
Power BI embedded through the http web page has always been able to log in normally. Recently, I suddenly cannot log in. No matter refreshing or clearing the browser memory, it is useless. I can log in normally by accessing the Power BI link alone. It is the Power BI embedded that has changed the login restrictions. ? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 10762750-98c2-a51e-97ac-dc733075c83c
* Version Independent ID: 10762750-98c2-a51e-97ac-dc733075c83c
* Content: [Known issue - Sign in fails for securely embedded reports using Chrome or Microsoft Edge browser - Power BI](https://learn.microsoft.com/en-us/power-bi/troubleshoot/known-issues/known-issue-532-sign-in-fails-securely-embedded-reports-using-chrome-browser)
* Content Source: [powerbi-docs/troubleshoot/known-issues/known-issue-532-sign-in-fails-securely-embedded-reports-using-chrome-browser.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/troubleshoot/known-issues/known-issue-532-sign-in-fails-securely-embedded-reports-using-chrome-browser.md)
* Service: **powerbi**
* Sub-service: **pbi-troubleshooting**
* GitHub Login: @mihart
* Microsoft Alias: **jessicamo**

**Comment by mihart** [comment]
Hi @, 
Thank you for your suggestion.  This sounds like a Support or product question and not a documentation issue.  To find an answer, try community.powerbi.com or submit a Support ticket. 
All the best,
The DOCS team
