### ISSUE TITLE
Tutorial not updated to pbiviz 5.3.0

### ISSUE THREAD

**Issue by lucazav** [MicrosoftDocs/powerbi-docs#4933]
The object model used in `settings.ts` of the tutorial is obsolete. Now the RHTML template for `settings.ts` is the following:

```
"use strict";

import { formattingSettings } from "powerbi-visuals-utils-formattingmodel";

import FormattingSettingsCard = formattingSettings.SimpleCard;
import FormattingSettingsSlice = formattingSettings.Slice;
import FormattingSettingsModel = formattingSettings.Model;


/**
 * RCV Script Formatting Card
 */
class rcvScriptCardSettings extends FormattingSettingsCard {
    provider: FormattingSettingsSlice = undefined;
    source: FormattingSettingsSlice = undefined;

    name: string = "rcv_script";
    displayName: string = "rcv_script";
    slices: Array<FormattingSettingsSlice> = [this.provider, this.source];
}

/**
* visual settings model class
*
*/
export class VisualFormattingSettingsModel extends FormattingSettingsModel {
    // Create formatting settings model formatting cards
    rcvScriptCard = new rcvScriptCardSettings();

    cards = [this.rcvScriptCard];
}
```

The actual pbiviz version is 5.3.0, so the example must be updated using the upon mentioned new objects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e0c67dbf-4135-8776-8c42-302f0bc325a7
* Version Independent ID: ad800d5e-0881-bea5-1428-702119a61823
* Content: [Create an R-powered Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-r-based-power-bi-desktop)
* Content Source: [powerbi-docs/developer/visuals/create-r-based-power-bi-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-r-based-power-bi-desktop.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @lucazav. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for pointing this out, @lucazav. I'll update the doc.

**Comment by lucazav** [comment]
Hi @mberdugo, you closed the issue, but documentation is not updated. Any issue in pushing the update? Thanks

**Comment by mberdugo** [comment]
Hi, @lucazav. You're right. There was a delay in the publishing. It sometimes takes a few days.
It should be live sometime this week.

**Comment by lucazav** [comment]
I'm add this cross-reference for visibility:

[Tutorial on creating an R-powered Power BI visual is not updated](https://github.com/microsoft/PowerBI-visuals-tools/issues/499#issuecomment-1904232699)

**Comment by AleksSavelev** [comment]
Now documentation is up to date.
We can close the issue @mberdugo

**Comment by mberdugo** [comment]
Great. Thank you!
