### ISSUE TITLE
Provided Sample Script Uses Outdated cmdlets Making it Unusable in a non-RunAs Runbook

### ISSUE THREAD

**Issue by scrampy** [MicrosoftDocs/powerbi-docs#4935]
The cmdlets used in the script are for managing legacy Azure resources that use Service Management APIs. Newly created Automation Accounts that want to use this script in a PowerShell runbook will fail.

Not only does the entire authentication section need to be replaced, but the cmdlets in the script:
Set-AzureRmContext
Get-AzureRmPowerBIEmbeddedCapacity
Update-AzureRmPowerBIEmbeddedCapacity

need to be replaced with

Set-AzContext
Get-AzPowerBIEmbeddedCapacity
Update-AzPowerBIEmbeddedCapacity

See the [Az PowerShell module](https://learn.microsoft.com/en-us/powershell/azure/install-azure-powershell) for cmdlets to manage Azure Resource Manager resources.

[ScaleUp-Automation-RunBook.ps1](https://github.com/microsoft/PowerBI-Developer-Samples/blob/master/PowerShell%20Scripts/ScaleUp-Automation-RunBook.ps1)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c0280ad2-25f3-0593-dd63-0d2b5b524304
* Version Independent ID: 08e55939-7be5-140b-02f7-cdcdd5b36c2e
* Content: [Monitoring Power BI Embedded data reference - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/monitor-power-bi-embedded-reference#example-script-for-scaling-a-capacity)
* Content Source: [powerbi-docs/developer/embedded/monitor-power-bi-embedded-reference.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/monitor-power-bi-embedded-reference.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @scrampy. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @scrampy. I'll look into updating the script.

**Comment by mberdugo** [comment]
Thanks again for pointing this out, @scrampy .
We'll add this script update to our backlog.
