### ISSUE TITLE
Issue 4557 closed, but documentation page still shows REG_SHOWLEADGENDIALOG switch which doesn't work

### ISSUE THREAD

**Issue by nzdudeinsydney** [MicrosoftDocs/powerbi-docs#4938]
[Enter feedback here]

If you use REG_SHOWLEADGENDIALOG=0 as part of your command-line, setup will not complete, but rather show you the command-line switches.  Issue 4557 was closed with a comment that the new switches will be removed, but closure didn't address the documented, but non-working switch.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2102c86-5037-0609-9dd3-a1487732df3f
* Version Independent ID: 73cfef71-a511-5ba2-b7b1-fa02a58a9e15
* Content: [Get Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop#download-power-bi-desktop-directly)
* Content Source: [powerbi-docs/fundamentals/desktop-get-the-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-get-the-desktop.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for the input, that switch has been removed.
