### ISSUE TITLE
Power Automate visual for Power BI not working after embed in Power App Application

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/powerbi-docs#4939]
Hi Team,

My power automate for Power BI  is working in my power bi web and desktop. But when I embed in Power App Application its showing triggering message but not working at all. Please help.

Thanks,
Jagan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: de472a84-f62c-d01c-a8b2-e6ea168a222d
* Version Independent ID: da8c0056-7e3d-fc14-c5a4-1bd3bab573de
* Content: [Create a Power Automate visual for Power BI (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/power-bi-automate-visual?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/create-reports/power-bi-automate-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/power-bi-automate-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by jaganpt** [comment]
Hi Team,

Any update on this pls?

Regards,
Jagan

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jaganpt. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @jaganpt -- so sorry for the delay! This sounds like a question for the Power Automate team. Here's a link to the Power Automate documentation:
https://learn.microsoft.com/en-us/power-automate/getting-started 
I hope they can help!
