### ISSUE TITLE
Q&A support for RLA

### ISSUE THREAD

**Issue by prwani-microsoft** [MicrosoftDocs/powerbi-docs#494]
The limitations on this page states that "Q&A and Cortana are not supported with RLS at this time. You will not see the Q&A input box for dashboards if all models have RLS configured. This is on the roadmap, but a timeline is not available."

But recent announcement states that it is available - https://powerbi.microsoft.com/en-us/blog/qna-december-2018-update/ (pls check last paragraph on this page)

Can you please fix the docs ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls#feedback)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hello, @j-leungyy 
Your contribution is much appreciated. I've forwarded your question to the doc author, who will respond shortly.
Kind regards,
Microsoft DOCS International Team

**Comment by mgblythe** [comment]
I removed the Q&A limitation. Thanks again for the feedback!
