### ISSUE TITLE
Maximum storage (Power BI native storage)9

### ISSUE THREAD

**Issue by ViktoriiaPavliuk** [MicrosoftDocs/powerbi-docs#4940]
I do not see information about Maximum storage (Power BI native storage) for each SKU. https://powerbi.microsoft.com/en-us/pricing/ states the limit of 100TB, is this limit the same for all SKUs or only for maximum P5?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18013a6f-b02d-30d4-3b6d-93295624f352
* Version Independent ID: e307e1d7-e565-8742-e563-86d596d7d1e1
* Content: [What is Power BI Premium? - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is)
* Content Source: [powerbi-docs/enterprise/service-premium-what-is.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-premium-what-is.md)
* Service: **powerbi**
* Sub-service: **powerbi-premium**
* GitHub Login: @KesemSharabi
* Microsoft Alias: **kesharab**

**Comment by KesemSharabi** [comment]
Hi @ViktoriiaPavliuk,

The maximum storage limit is 100 TB for all the SKUs.

Thanks,

Kesem
