### ISSUE TITLE
SKU Requirements

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4942]
Can this table please be extended to cover SSAS versions after 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6fa43934-b1b5-2227-9f9e-cfce1801b659
* Version Independent ID: 0d169b19-7c1c-b37d-3915-b8c55da6f0ff
* Content: [Manage SQL Server Analysis Services data sources - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-enterprise-manage-ssas#sku-requirements)
* Content Source: [powerbi-docs/connect-data/service-gateway-enterprise-manage-ssas.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-enterprise-manage-ssas.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by KesemSharabi** [comment]
Hi @VitalyMCT,

Thank you for your comment and for getting involved. We added the missing information to the table and it'll get published shortly.

Kesem
