### ISSUE TITLE
The usual lack of consideration for learners

### ISSUE THREAD

**Issue by drewjames1234** [MicrosoftDocs/powerbi-docs#4943]
As usual, this article assumes pre understanding of semantics, in this case 'cached' as related to the dual mode.  I have no idea what this is talking about. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-storage-mode)
* Content Source: [powerbi-docs/transform-model/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-storage-mode.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
You have a good point. I've added a definition of caching in the first paragraph, thanks for your feedback.
