### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/powerbi-docs#4944]
Please update licensing and other details within this page for Fabric.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 78655418-d567-8c78-455d-913fab3277a5
* Version Independent ID: 0729c97e-74d7-ac7a-26b8-54b9a7d18dbd
* Content: [Paginated reports in Power BI: FAQ - Power BI](https://learn.microsoft.com/en-us/power-bi/paginated-reports/paginated-reports-faq)
* Content Source: [powerbi-docs/paginated-reports/paginated-reports-faq.yml](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/paginated-reports/paginated-reports-faq.yml)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **petebro**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @VitalyMCT. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @VitalyMCT -- please see the Fabric licensing page for that information.
https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-licensing-organization
The link in this article takes you to the current licensing information. I'm closing this issue.
Thanks for asking!

**Comment by VitalyMCT** [comment]
Sorry, not following the rationale. This page is out of date and inaccurate - why not fix it? Other pages are other pages.
