### ISSUE TITLE
Can two people refresh and publish the reports?

### ISSUE THREAD

**Issue by AntoanetaNik** [MicrosoftDocs/powerbi-docs#4945]
Hello there, 
I have one question. Can two people refresh and publish reports on Power BI. And if it's possible, is it gonna be on the same link? 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df058604-4117-88d8-0cb0-935d08e5b22a
* Version Independent ID: dc8d3604-1fea-0109-2a94-13bd70a10522
* Content: [Ways to collaborate and share in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports)
* Content Source: [powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-how-to-collaborate-distribute-dashboards-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AntoanetaNik. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @AntoanetaNik -- interesting question! Yes, >1 person can definitely edit a report, though not at the same time. I _think_ it can have the same link, but I'll check on that. I'm closing this issue and moving it to a different tracking system.
