### ISSUE TITLE
Content is not anymore up-to-date

### ISSUE THREAD

**Issue by zsomborzsuffa** [MicrosoftDocs/powerbi-docs#4946]
The current Power BI service as of today 2024-01-05 does not offer this functionality any more as documented here. The current functionality is asking to specify a space where to save the notification.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64b2fae9-3356-f90c-8b3c-647aa2ad5f75
* Version Independent ID: 5ee251f0-8e8b-47eb-937c-356e15c341ba
* Content: [Set data alerts in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-set-data-alerts)
* Content Source: [powerbi-docs/create-reports/service-set-data-alerts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-set-data-alerts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @zsomborzsuffa. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks, @zsomborzsuffa for your comment! I'm closing this and moving it to a different tracking system so I can work on it.
