### ISSUE TITLE
Next Steps are circular and Edit option for report consumers seems confusing

### ISSUE THREAD

**Issue by SMHolck** [MicrosoftDocs/powerbi-docs#4947]
The links for Next Steps at the bottom of this page are not in order.
If you click the first, it jumps two topics down.
In that one, when you click the only link it jumps back to this page.
I think users will find that confusing.
I am looking for training that more clearly separates the roles to provide to our end users and to our report designers on business teams. 
 I found it confusing that the business users just got told they don't have to build anything, but one of the early topics on this page shows them the Edit and Read view buttons.  Could that topic be moved to a report or dashboard designer role documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0687089d-b79d-c566-35a5-9a03498cc168
* Version Independent ID: 30699f15-ec7a-6f19-9f86-99316656c099
* Content: [What is a Power BI business user? - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-consumer)
* Content Source: [powerbi-docs/consumer/end-user-consumer.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-consumer.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @SMHolck. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @SMHolck , 
Thank you for your suggestion.  Perfect timing for your comment.  We're in the process of removing "Next steps" and replacing it with "Related content".  
All the best,
The DOCS team
