### ISSUE TITLE
RLS is now supported with Q&A 

### ISSUE THREAD

**Issue by v-kerwan** [MicrosoftDocs/powerbi-docs#495]
Check below bolg 
https://powerbi.microsoft.com/en-us/blog/qna-december-2018-update/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hello, @v-kerwan 
Your contribution is much appreciated. I've forwarded your question to the doc owner, who will respond shortly.
Kind regards,
Microsoft DOCS International Team

**Comment by bbrown44** [comment]
Documentation is out of date.  

documentation after "Validating the role within the Power BI service" is no longer a function in power bi service portal.

**Comment by mgblythe** [comment]
Removing the Q&A reference. Leaving this issue open to address the validation info in the article

**Comment by mgblythe** [comment]
@bbrown44 - I know this one's old, but coming back to address. Which part of the doc is out of date? You can still validate roles in the service - was something else at issue? Thanks!

**Comment by mgblythe** [comment]
Closing this one out. Feel free to reopen if you have more feedback on the content after "Validating the role"
