### ISSUE TITLE
 Import or connect to a CSV file (Solution no longer Valid)

### ISSUE THREAD

**Issue by KENNYCOKER** [MicrosoftDocs/powerbi-docs#4950]
[The guide (In a Power BI workspace, select + New, and choose Upload a file) stated on this page is no longer valid. "Upload a file" submenu is no longer available under "new"menu. Please advice an alternative way to upload a CSV in Power Bi Service]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54d7c7b5-fd5e-fa05-ce87-a0d8af4e8ca7
* Version Independent ID: 24160b8a-1995-254f-2834-a3c44f6f6164
* Content: [Get data from comma separated value (CSV) files - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-comma-separated-value-files?wt.mc_id=searchapi_inproduct_fabrichelppane#import-or-connect-to-a-csv-file)
* Content Source: [powerbi-docs/connect-data/service-comma-separated-value-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-comma-separated-value-files.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @KENNYCOKER. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your input - I've updated the article with new guidance. Quickly, it's: 

select **My workspace > New > Semantic model** then choose **CSV**.
