### ISSUE TITLE
Any additional information about "Business Rules Engine framework"?

### ISSUE THREAD

**Issue by bentcg** [MicrosoftDocs/powerbi-docs#4953]
The page mentions a "Business Rules Engine framework".  Is this just a wiki/document listing the calculations/expressions, a database of rules, or using some custom software?  Just intersted in more detail about this or how it's been implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 645ea9af-1b0d-4e7b-3590-206a602a7871
* Version Independent ID: aaef598a-f8d7-47a2-9cbe-7f91a485f4e7
* Content: [BI solution architecture in the Center of Excellence - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/center-of-excellence-business-intelligence-solution-architecture)
* Content Source: [powerbi-docs/guidance/center-of-excellence-business-intelligence-solution-architecture.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/center-of-excellence-business-intelligence-solution-architecture.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bentcg. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
As described in the article, it can manifest in various ways, and if you search online for Business Rules Engine, you'll find examples and solutions.
