### ISSUE TITLE
the diagram is misaligned to the text

### ISSUE THREAD

**Issue by batemansogq** [MicrosoftDocs/powerbi-docs#4958]
shouldn't the Team & Department labels be swapped around on the diagrams to align with the text?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18991be8-e63d-0eba-b573-320bd1d4ea1e
* Version Independent ID: 25b88ee7-4976-87bb-83ed-afde7daff5ee
* Content: [Microsoft Fabric adoption roadmap: Content delivery scope - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/fabric-adoption-roadmap-content-delivery-scope?context=%2Ffabric%2Fcontext%2Fcontext)
* Content Source: [powerbi-docs/guidance/fabric-adoption-roadmap-content-delivery-scope.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/fabric-adoption-roadmap-content-delivery-scope.md)
* Service: **fabric**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @batemansogq. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @batemansogq - thank you for letting us know. We appreciate your feedback that helps us maintain great content. A revised image will "go live" very soon. #please-close
