### ISSUE TITLE
Connection information

### ISSUE THREAD

**Issue by rat-af** [MicrosoftDocs/powerbi-docs#496]
The 'How to connect' information seems to be outdated.   I do not get a 'Services' window.
I try to connect to my D365FO url, but it won't let me use my organisational account.  We need some more up to date information on this page about connecting to D365FO.  A lot has changed in the 12 months of publishing this, and it doesn't look like the document has kept up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8689ec32-44dd-7104-94c6-980b3825c730
* Version Independent ID: fe610d63-0667-9a39-bc5b-f595f9d3a9ba
* Content: [Connect to Microsoft Dynamics AX content pack with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-microsoft-dynamics-ax)
* Content Source: [powerbi-docs/service-connect-to-microsoft-dynamics-ax.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-microsoft-dynamics-ax.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by SarinaJoan** [comment]
Hi rat-af, thanks for your feedback. This content pack will be either improved or deprecated within two months, please expect changes soon.
