### ISSUE TITLE
Faulty solution to: Tutorial: From dimensional model to stunning report in Power BI Desktop

### ISSUE THREAD

**Issue by Gamborg1987** [MicrosoftDocs/powerbi-docs#4960]
I followed the tutorial provided called "Tutorial: From dimensional model to stunning report in Power BI Desktop".

Mostly I managed to get through it with good visuals and learning as I went. However I struggled with the slicer adding a (Blank) selection. And the data from year 2021 apparently not getting detected.

Thought I made the mistake, but the downloaded example of a completed version also contains both problems.
I solved the (Blank) simply by filtering the (Blank) from month.

Looking into the data, I see that there are blank data located within the Sales Table under ShipDateKey
And I guess the data is limited to 2017-2020, since tracking the date keys to the sales keys there were no correlation in sales for 2021.

Thank you for the tutorial :) It was educational.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Gamborg1987. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thank you for your feedback and for getting involved. I'll forward your message to the tutorial owner and hopefully we'll be able to fix the tutorial (and sample) soon.
