### ISSUE TITLE
Fabric CoP graphic Champ vs Creators

### ISSUE THREAD

**Issue by rriggstx** [MicrosoftDocs/powerbi-docs#4963]
[Enter feedback here]
I believe the Microsoft Fabric community of practice graphic has Champions and SS Content switched.

For instance, an arrow points from CoExcellence to SS Content Creators, but the text says "COE interacts closely with champions."  Then, below that, the arrow from Champions to Content consumers says "[SSC]... produce, publish, and support used by colleagues."

Suggested change:
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/30546944/39d9429a-c657-41f0-84d8-542741704945)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 704e7118-94a5-c056-1eb3-91cfed0f0e1a
* Version Independent ID: ee561000-f3bd-09ac-9d11-20966385a24e
* Content: [Microsoft Fabric adoption roadmap: Community of practice - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/fabric-adoption-roadmap-community-of-practice)
* Content Source: [powerbi-docs/guidance/fabric-adoption-roadmap-community-of-practice.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/fabric-adoption-roadmap-community-of-practice.md)
* Service: **fabric**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @rriggstx. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @rriggstx - thank you for your feedback. We have corrected the image, and it should "go live" in the next 24 hours.

#please-close

**Comment by KesemSharabi** [comment]
@peter-myers can you please respond to this GitHub issue?

**Comment by peter-myers** [comment]
Hi @KesemSharabi  - this issue was resolved last week. #please-close
