### ISSUE TITLE
Power BI Free was replaced by Fabric Free

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#4968]
[Enter feedback here]
This doc is referencing Power BI Free, shouldn't this be Fabric Free now?  Didn't Fabric Free replace Power BI Free?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with Free licenses in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @haydnr
* Microsoft Alias: **haydnr**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @elfohl. This issue has been assigned to the doc author for review.

**Comment by elfohl** [comment]
I don't see a doc change made.  This doc is misleading, as it makes it seem that Free user is only a concept available with Power BI Premium capacity, we know that not to be the case, as it is also available with Fabric capacity.

Customers reference this feature list for what they can do without any license and as a free user associated with capacity.
________________________________
