### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ZackWJames** [MicrosoftDocs/powerbi-docs#4969]
Looks Good.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e9a0262-d1a5-2824-16f1-0f13c5ce4a64
* Version Independent ID: f73f5d7e-a45a-c8aa-18a3-ab47f641ed57
* Content: [Add the Power BI app to Microsoft Teams - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-microsoft-teams-app)
* Content Source: [powerbi-docs/collaborate-share/service-microsoft-teams-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-microsoft-teams-app.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ZackWJames. This issue has been assigned to the doc author for review.

**Comment by ajburnle** [comment]
Thank you for the feedback, @ZackWJames. #please-close

**Comment by ajburnle** [comment]
#please-close
