### ISSUE TITLE
Important missing information for SSO

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#497]
There's no information on how to bypass adding credentials when using SSO.  Adding them is pointless since the service identity is used.  And most environments with any measure of security won't allow user credentials to be shared by a wide audience like this.  It's kind of unbelievable that a basic security issue this big has been completely overlooked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d4509b-ab31-a917-16a2-8ed7ce834c41
* Version Independent ID: 31f21190-cd0d-f369-fc4a-48ca7ac1ccb0
* Content: [Use Kerberos for single sign-on (SSO) to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos)
* Content Source: [powerbi-docs/service-gateway-sso-kerberos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sso-kerberos.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by jordanmills** [comment]
To clarify, I'm talking about the credentials the web site demands when adding a data source like SQL server.

**Comment by mgblythe** [comment]
Thanks @jordanmills, I'll take a look at this.

**Comment by arthiriyer** [comment]
@jordanmills Thanks for the feedback. Unfortunately currently credentials are required even if you are using SSO.  Do suggest this in ideas.powerbi.com and it will help us fix this in the upcoming semester.
