### ISSUE TITLE
Update the requirements for the use of this feature

### ISSUE THREAD

**Issue by Jas73** [MicrosoftDocs/powerbi-docs#4970]
This page needs to be updated when it comes to the requirements part and also make it clearer. Add the F64-SKU and change - This capacity can be any of A1, EM1, A6?, P1 or F64-SKU or larger capacities. It's easy to think that you will need a P3 which is note case according to me.

Original text:
"At least one workspace in your Power BI tenant backed by a reserved capacity. This capacity can be any of the A1/EM1 - A6/P3 SKUs."

Johan
Intelligence TS @ Microsoft
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d92e4209-59ef-2aed-dd62-b38c443d96d3
* Version Independent ID: ba65faca-8ef1-3cb3-3a32-bc23fbb1e64c
* Content: [Export and email a report with Power Automate - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-automate-power-bi-report-export)
* Content Source: [powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-automate-power-bi-report-export.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jas73. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @Jas73 -- Thanks for your question! I'm asking the PMs for guidance on an update for this article, and will update appropriately when I find out.
