### ISSUE TITLE
documentation up to date?

### ISSUE THREAD

**Issue by wt-asw** [MicrosoftDocs/powerbi-docs#4973]
[Enter feedback here]
I do not see the options to switch off the secondary axis: 

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/110596449/3b68f06c-cf1b-408e-bdbe-56f767ec4fbd)

Is this documentation up to date? I would like to have the same axis for both line and column in this plot.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83e368c2-36c2-a5c0-f2af-993f6ee73665
* Version Independent ID: 452524d5-e375-9750-19ac-eb76903b36b3
* Content: [Combo chart in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-combo-chart?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-combo-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-combo-chart.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @ajburnle , Adding you to this Git issue since you are working on freshness for this article.  Let me know if you have any questions. Thanks!

**Comment by kfollis** [comment]
@wt-asw Thank you for taking the time to submit feedback! A project is underway to update this entire set of articles and ensure that they are all up to date. Your feedback will help us to prioritize review. As we are tracking this update under another work item, I am closing this issue. If you have additional comments, please feel free to use the on-page feedback tools. Thank you again for taking the time to submit feedback!
