### ISSUE TITLE
Include in report refresh DISABLE turns to enable after publishing the report to Power BI service

### ISSUE THREAD

**Issue by paivikilo** [MicrosoftDocs/powerbi-docs#4974]
If I disable 'include in report refresh" in Power BI desktop and only using it in desktop, it works ok.
But after publishing it to Power Bi service and auto refresh it there using On-Premises gateway, it has turned ON.
And after downloading the report to my desktop from Power BI service to modify it again, I can also see, that it
has turned on and is not disabled anymore.

This error has been always. With all reports  and with all datasets. And is annoying, since I don't want to refresh the history data all over again. Only once.

Dataset includes three table which are appended as one.
2 of these are historydata tables and include in report refresh has been disabled.
1 of these is realtime data and report refresh is on.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bafd843f-fda5-f156-8f38-9fde59bc4b57
* Version Independent ID: c5f241c6-8423-3f98-6d9f-ed20cba9b11c
* Content: [Managing query refresh - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-include-in-report-refresh)
* Content Source: [powerbi-docs/connect-data/refresh-include-in-report-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-include-in-report-refresh.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @paivikilo. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you for your feedback on the way this feature operates. Since this is product feedback rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
