### ISSUE TITLE
Outdated "Max concurrent DirectQuery connections" for Power BI Premium 

### ISSUE THREAD

**Issue by jonaskoeASYS** [MicrosoftDocs/powerbi-docs#4976]
In the section "Maximum number of connections" there are three different values which depend on the licensing. However on this page [Semantic model SKU limitation](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-what-is#semantic-model-sku-limitation) the premium license connections recently got changed and now depend on the premium/fabric sku.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [DirectQuery in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-directquery-about)
* Content Source: [powerbi-docs/connect-data/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-directquery-about.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jonaskoeASYS. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. If you look toward the bottom of that section, you'll see there's a table that describes / specifies the upper limit of concurrent connections per the SKU (as you mentioned); these other settings are configurable per report.

**Comment by jonaskoeASYS** [comment]
Indeed commit 5850d0a solved this. Thanks!
