### ISSUE TITLE
Does not address how to correct incorrectly-placed states

### ISSUE THREAD

**Issue by eddiebabs** [MicrosoftDocs/powerbi-docs#4977]
It would be great if this addressed why the state of Mississippi is shown in Brazil

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a47d7082-17fb-3b37-de23-020f49991e0c
* Version Independent ID: 4d904a62-6e2e-b05f-b222-2500df079b76
* Content: [Create and use filled maps (choropleth maps) in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-filled-maps-choropleths?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-filled-maps-choropleths.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eddiebabs. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @eddiebabs ,
Just an update.  I'm working with PMs and engineers to figure out how to document this. Thank you for bringing it to my attention.

**Comment by mihart** [comment]
Hi @eddiebabs, 
Thank you for your suggestion.  This issue is known by the engineering team and they are working on a fix. 
All the best,
The DOCS team
