### ISSUE TITLE
Not showing up in the external user's tenant

### ISSUE THREAD

**Issue by bing-ho-afon** [MicrosoftDocs/powerbi-docs#4978]
I have tried this but it is not showing up in the external user's tenant.

If I log into Power BI Service / Desktop with the following user:
<EXTERNAL_USER@EMAIL.COM>#EXT#@<SHARING_GROUP>.onmicrosoft.com
I am able to see the semantic model in the sharing tenant.
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/156170861/44e04d31-29ad-4044-b726-839f0f2a97c3)

However if I log into the external tenant (simply <EXTERNAL_USER@EMAIL.COM>) I don't see any way to connect to the semantic model at all.
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/156170861/7657292c-6d08-4441-bd06-063a61d4a226)

I already have the preview feature enabled: 
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/156170861/e2cb07dc-8258-43be-b65f-893e39a074af)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bing-ho-afon. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @bing-ho-afon. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
