### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by helen1point5** [MicrosoftDocs/powerbi-docs#4979]
When I follow these instructions I don't get the same outcome. There is no 'fields' pane in my version of PowerBI (desktop), it's called "Data" and I've never seen a group created in there, nor the legends field.

I need to create two different groups of visualisations that respond to two different slicers, can I still do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1e0b0a-ff95-b2f7-44db-5c07ca876ab4
* Version Independent ID: 1c975595-bf44-5f66-3e08-02c3e8e63797
* Content: [Use grouping and binning in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-grouping-and-binning)
* Content Source: [powerbi-docs/create-reports/desktop-grouping-and-binning.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-grouping-and-binning.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @helen1point5. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment! We're in the process of refreshing our articles with updates to Power BI screens, and will update this article as a part of that process. 

On your (support) questions, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
