### ISSUE TITLE
Update Matrix documentation

### ISSUE THREAD

**Issue by flavio-meneses** [MicrosoftDocs/powerbi-docs#4981]
In the "Considerations and troubleshooting", it should be stated the matrix can only show a maximum of 100 columns (including totals and sub-totals).

Also, the second point on "Considerations and troubleshooting" is out of date - the option to "Unfreeze row headers" is now available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3825d5bd-51e3-468a-0f7d-a936083f0dc5
* Version Independent ID: 59eea08a-c392-951e-2ba6-860cfcc58281
* Content: [Create a matrix visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/desktop-matrix-visual)
* Content Source: [powerbi-docs/visuals/desktop-matrix-visual.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-matrix-visual.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @flavio-meneses. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @flavio-meneses , 
Thank you for your suggestions.  We've made the update and set the article to republish. 
All the best,
The DOCS team
