### ISSUE TITLE
Service Principals Problem with Power BI Embedded Analytics  

### ISSUE THREAD

**Issue by Chuck0007** [MicrosoftDocs/powerbi-docs#4982]
Dear System Manager,
I encountered a problem and need your help while developing an “Embedded Power BI” app for customers (with external excess).
To build a “Special Principal”, I followed the following instructions:
https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal
License type: [chuckqi@westernqrm.com](mailto:chuckqi@westernqrm.com) (PPU) 
Step 1 - Create a Microsoft Entra app (a secret is also added):
 
Step 2 - Create a Microsoft Entra security group (“MS Entra roles can be assigned to the group”=Yes):
 
Step 3 - Enable the Power BI service admin settings:
Problem emerged in options: “Embedded content in apps” and “Allow service principals to use embedded Power BI APIs” (see below screen shot). 
When typing in “Specific security groups” (in my case: PBIgroupWQRM), it was NOT recognized by the system.
I couldn’t find answers online. Would you please let me know the right direction to move forward. Thank you very much for your help.
[EmbedPBIHelp.docx](https://github.com/MicrosoftDocs/powerbi-docs/files/14057026/EmbedPBIHelp.docx)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 794566fc-c06c-1d9c-b656-2e7b59bc2874
* Version Independent ID: 4c57568f-c4f2-0bd6-b724-9868b2455d50
* Content: [Embed Power BI content in an embedded analytics application with service principal and an application secret - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/embedded/embed-service-principal)
* Content Source: [powerbi-docs/developer/embedded/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-service-principal.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Chuck0007. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @Chuck0007 

This looks like product feedback or a product question, rather than documentation feedback. You can try opening a [support ticket](https://learn.microsoft.com/en-us/power-bi/support/create-support-ticket) or asking the [Power BI community](https://community.powerbi.com/).

**Comment by Chuck0007** [comment]
Thanks. 
Any update on the status of this project?
Chuck

**Comment by mberdugo** [comment]
As I said,
This looks like product feedback or a product question, rather than documentation question. You can try opening a [support ticket](https://learn.microsoft.com/en-us/power-bi/support/create-support-ticket) or asking the [Power BI community](https://community.powerbi.com/).
