### ISSUE TITLE
Auto Play Slideshow

### ISSUE THREAD

**Issue by marketing-tld** [MicrosoftDocs/powerbi-docs#4984]
Will there be an auto-play slideshow in the https://app.powerbi.com/ version or desktop app version? This is a feature that was lost in the sunsetting of the Power BI Windows app that is frequently used.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 936fe9bd-5642-1de4-88c1-d876d2659cac
* Version Independent ID: 3a57ea7d-ebe9-190b-2991-a9215256d5b6
* Content: [View presentation mode on Windows devices - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/mobile/mobile-windows-10-app-presentation-mode#slideshow-settings)
* Content Source: [powerbi-docs/consumer/mobile/mobile-windows-10-app-presentation-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/mobile/mobile-windows-10-app-presentation-mode.md)
* Service: **powerbi**
* Sub-service: **powerbi-mobile**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marketing-tld. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @marketing-tld, thanks for your question. I don't think such a feature exists or is planned, but let me double check that with the product team. I'll get back to you here in a day or two.

**Comment by paulinbar** [comment]
Hi @marketing-tld, ok, so the team is planning to make similar functionality available in PowerPoint via the Power BI add-in for PowerPoint (https://learn.microsoft.com/power-bi/collaborate-share/service-power-bi-powerpoint-add-in-about).  No dates given yet, though.

I'm closing this issue now, but feel free to reopen if you have further questions. Thanks for reaching out!
