### ISSUE TITLE
Does the Azure Cost Management connector support CSP/MPA?

### ISSUE THREAD

**Issue by secretsoup** [MicrosoftDocs/powerbi-docs#4987]
I would like to see if there is some clarity around the documentation for the connector:

https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-azure-cost-management

Per the document, MPA/CSP is currently supported:

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/17623860/9e0b019d-c6b2-475c-a30d-4370108868af)

However, viewing issues on Github and on the support forum all seem to point towards it **not** being supported. I'm having difficulty getting this working with indirect reseller accounts and would like to see if there can be some clarification if this is an issue with my own usage/implementation or a limitation of the connector itself.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @secretsoup. This issue has been assigned to the doc author for review.
