### ISSUE TITLE
How can a custom visual access the visuals background theme color?

### ISSUE THREAD

**Issue by ek-work** [MicrosoftDocs/powerbi-docs#4990]
# How can a custom visual access the visuals background theme color? 

**It doesn't appear to be available in color utils**

When applying a theme in PowerBI Desktop, we have the ability to customize the theme. With that customization, various colors are available using `colorHelper.getThemeColor` or via the `powerbi.extensibility.ISandboxExtendedColorPalette` interface. For example, if I change the `Names and colors - Advanced - Third-level elements`, I can then access that color change with `colorHelper.getThemeColor("foregroundNeutralLight")`

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/7796057/656a1e0c-2a50-4b79-8851-ada4a36a3c71)

But the color and other theme values I change related to the visual don't seem to be available. For example, I change the `Visuals Background` color here (see screen shot below), but I don't see that `Visuals Background` value in the `colorPalette` or available via the `ColorHelper`.

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/7796057/eea2983f-0fcc-4f00-95a4-854bcb433b35)

You can see the applied background color in the pie chart visual on the right. You can also that it is the applied background color for our map visual on the left. Our map visual uses a basemap, and that basemap cannot be applied as transparent. So we want to be able to switch to a `dark-mode` basemap based on the `Visuals Background` color as set by the theme. But without access to that color, it's not possible.

---
I've tried to use `getComputedStyle` to determine the background color, but unfortunately because the custom visual is within an iframe, and the background color applied to the visual is in the iframe's parent document, there isn't an apparent way to determine that color.

```
parent-powerbi-document . . .
  <div ... class="visualWrapper report" style="padding: 0px 5px 5px; background-color: rgb(0, 0, 0);"
  ...
    <iframe ... class="visual-sandbox ... i.e. custom visual iframe
      ...
      <body ...
        <div id="sandbox-host" class="visual visaul-/our visual/"...
```

**Is there any other way that this `Visuals Background theme color` can be deteremined from within the context of a custom visual?**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22cb8fba-241c-285a-3483-a6f9e8043a30
* Version Independent ID: 642518f9-28fe-e83f-ae4b-7c6b618294ba
* Content: [Introduction to use color utils in Power BI visual - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/utils-color#colorhelper)
* Content Source: [powerbi-docs/developer/visuals/utils-color.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/utils-color.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ek-work. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your question, @ek-work. Unfortunately, for now it's not possible to add customized colors to the color palette, but this seems like a good idea for a future update. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).
