### ISSUE TITLE
Documentation does not match screen shot snippets, nor does it match current experience.

### ISSUE THREAD

**Issue by ToddChitt** [MicrosoftDocs/powerbi-docs#4991]
Under the section for "Explore the navigation pane", it first shows a tall, narrow snippet of a navigation pane. Below that, the last sentence of the paragraph states, "It can be collapsed by selecting this icon." <small snipped of a hamburger icon>

But that icon does NOT show up in the tall narrow screenshot above, and it does not show up on my page. 

Mostly, I'm looking for how I can CUSTOMIZE my nav panel. I see that I can "Unpin" any one particular item, like, say, Monitoring Hub. But once I do, how might I get it back? I would like to get rid of half the icons on my nav panel but am nervous about doing so in fear that I won't be able to navigate to that particular item should I need it later.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 744f5d32-18ed-9018-3003-c5f9bcb3d1ff
* Version Independent ID: e2123a9f-edef-5170-05c6-98d42bc9fd35
* Content: [Find content from Power BI service Home - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-home)
* Content Source: [powerbi-docs/consumer/end-user-home.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-home.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ToddChitt. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @ToddChitt ,
Thank you for your suggestions.  I've updated the article and submitted it for publish.  
Take care,
the DOCS team
