### ISSUE TITLE
Updates to this article

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/powerbi-docs#4993]
I noticed this was last updated in 2022. Lots has changed can some check over this to make sure still accurate?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7c4b038-e61f-691f-f155-333e271e611c
* Version Independent ID: 3e653013-5cf2-269f-aa6e-d617d7607de6
* Content: [Feature availability for users with Free licenses in the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-features)
* Content Source: [powerbi-docs/consumer/end-user-features.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-features.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @haydnr
* Microsoft Alias: **haydnr**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @makdaddy8888. This issue has been assigned to the doc author for review.
