### ISSUE TITLE
Add on this page a table explaining the license options and basic limitations 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/powerbi-docs#4994]
Please add a basic table with links for more details

eg

Microsoft fabric free - can create your own dashboard and see internal published report

power bi pro - can create and share reports

power bi premium - list benefits 

this will help people know what they  need to purchase 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d5e96ad-ac67-4211-95b3-3707ce55e088
* Version Independent ID: 018d2a68-896b-170c-f3ec-3694f8f2f85d
* Content: [What is Power BI? - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/power-bi-overview)
* Content Source: [powerbi-docs/fundamentals/power-bi-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/power-bi-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @makdaddy8888. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your input. Licensing options are covered in a different article: https://learn.microsoft.com/en-us/power-bi/fundamentals/service-features-license-type
