### ISSUE TITLE
Revise:  Manage Access Requests not available in Government

### ISSUE THREAD

**Issue by GitWesDone** [MicrosoftDocs/powerbi-docs#4999]
For the section: https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps#manage-app-access-requests 

This capability is not in Power BI for US Government.  Recommend verifying that this is the case, and updating documentation with this caveat.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @GitWesDone -- I'm checking with the product team. Thanks!

**Comment by maggiesMSFT** [comment]
Guess what, @GitWesDone -- the functionality is rolling out to the sovereign clouds next week! So the docs will be right, as they are!
