### ISSUE TITLE
Allow Print / Export inside SharePoint embedded

### ISSUE THREAD

**Issue by Vinhaman** [MicrosoftDocs/powerbi-docs#500]
It would be very helpful if we could have the Print / Export Power point functionality in this SharePoint embedded...

Currently we can only parameterize the Show Navigation Pane and the Show Filter Pane. A show print / export pane would be nice...
If we just print the page with the headers and the rest the report comes out very poorly.

**Comment by mgblythe** [comment]
Thanks @Vinhaman, can you post this to Power BI Ideas: https://ideas.powerbi.com/forums/265200-power-bi
