### ISSUE TITLE
Power BI Security

### ISSUE THREAD

**Issue by GayaniTharu** [MicrosoftDocs/powerbi-docs#5001]
[Very Useful!]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-power-bi-security)
* Content Source: [powerbi-docs/enterprise/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-power-bi-security.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @GayaniTharu. This issue has been assigned to the doc author for review.
