### ISSUE TITLE
connect data

### ISSUE THREAD

**Issue by AhmedSyeda** [MicrosoftDocs/powerbi-docs#5003]
Hello.
Thanks for the detailed info in the bi docs. However, like to point out the following link doesn't provide the table mentioned in the example activity. There are all other tables or data but not specifically for the states and retirement. Kindly update the link or information for activity. I'm doing a demo for beginners with this platform. your help is much appreciated.
https://www.fool.com/research/best-states-to-retire 
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/110947965/bb6ff934-52e0-4269-a2b7-96a38622022e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b7b252-3153-db11-68e0-3362f3a1197c
* Version Independent ID: 97161c15-0905-a7a4-692d-e4eb4490496b
* Content: [Connect to data in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-connect-to-data)
* Content Source: [powerbi-docs/connect-data/desktop-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/desktop-connect-to-data.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @AhmedSyeda. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment! We're in the process of refreshing those articles, and will address your request during that process.
