### ISSUE TITLE
Wrong order in visual for content creators

### ISSUE THREAD

**Issue by Erik-H-zz** [MicrosoftDocs/powerbi-docs#5007]
The image shows Personal - Departmental - Team - Enterprise, while the text says Personal - Team - Departmental - Enterprise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18991be8-e63d-0eba-b573-320bd1d4ea1e
* Version Independent ID: 25b88ee7-4976-87bb-83ed-afde7daff5ee
* Content: [Microsoft Fabric adoption roadmap: Content delivery scope - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/fabric-adoption-roadmap-content-delivery-scope)
* Content Source: [powerbi-docs/guidance/fabric-adoption-roadmap-content-delivery-scope.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/fabric-adoption-roadmap-content-delivery-scope.md)
* Service: **fabric**
* GitHub Login: @peter-myers
* Microsoft Alias: **v-myerspeter**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Erik-H-zz. This issue has been assigned to the doc author for review.

**Comment by peter-myers** [comment]
Hi @Erik-H-zz - thanks for reporting the issue. We've updated the image and it should "go live" in the next 24 hours.

#please-close
