### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by klinejordan** [MicrosoftDocs/powerbi-docs#5008]
This screen has outdated screenshots of the workspace UI experience and could be confusing to users trying to follow along

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d01ab260-aec3-2f8f-af82-1def43e55196
* Version Independent ID: a7bd683c-88e3-3ac1-ab97-7fa6a87719c5
* Content: [Delete a dashboard, report, workbook, semantic model, or workspace - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/service-delete#remove-members-from-a-workspace)
* Content Source: [powerbi-docs/create-reports/service-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/service-delete.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @klinejordan. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @klinejordan -- thanks for the reminder. Screenshots updated, changes will be live tomorrow Fri Feb 9 afternoon Pacific time.
