### ISSUE TITLE
power bi

### ISSUE THREAD

**Issue by kamdemliberte** [MicrosoftDocs/powerbi-docs#5009]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a07e15c6-9882-de08-f98e-2ada7146e349
* Version Independent ID: a07e15c6-9882-de08-f98e-2ada7146e349
* Content: [Power BI Desktop OneDrive and SharePoint integration - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-sharepoint-save-share)
* Content Source: [powerbi-docs/create-reports/desktop-sharepoint-save-share.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-sharepoint-save-share.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @lafaberMSFT
* Microsoft Alias: **lafaber**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kamdemliberte. This issue has been assigned to the doc author for review.
