### ISSUE TITLE
Multiple Report GUIDs Per Report Name

### ISSUE THREAD

**Issue by ginger-schooling** [MicrosoftDocs/powerbi-docs#5010]
Can this page talk about why there'd be multiple ReportGUIDs per Report Name in the usage metrics? It makes it look like there's duplicate reports in the workspace, but there is only one report with that name. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f16f558c-a397-7d10-b953-6c8972df9478
* Version Independent ID: ffc58ae8-f232-f6d8-f0ea-e4d6001e0e3d
* Content: [Monitor usage metrics in workspaces (preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics)
* Content Source: [powerbi-docs/collaborate-share/service-modern-usage-metrics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-modern-usage-metrics.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ginger-schooling. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @ginger-schooling -- I'm not familiar with your scenario. I've asked the product PMs to advise.

**Comment by maggiesMSFT** [comment]
Hi, @ginger-schooling -- PMs ask: we need some clarification and evidence from Ginger. Is she asking about one report usage metrics per a given workspace? If yes, then there should only be one report GUID linked to one report name. If it is across workspaces then it is possible for multiple reports to have the same name. 

Another possible explanation is that Ginger may be looking at the report page GUID, not report GUID. It is possible for multiple reports to have the same page names.

**Comment by ginger-schooling** [comment]
I'm referring to one usage report per workspace. 

We have many reports in the one workspace, and I'm auditing the reports using the usage report and I see duplicate report names, implying duplicate reports. When I search the workspace, there is only ONE report with the name. 

Seems to happen for various reasons, one reason might be when a report is uploaded to workspace then the report name is changed...results in two report GUIDs and two dup report names but only one actual report. 

See [this](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-modern-usage-metrics#considerations-and-limitations) where it says "Duplicate reports with different Report ObjectIds in the usage metrics report can show up for the following scenarios..."

I was hoping this page could explain how to filter out pseudo duplicates from the Usage Report. I also did ctrl+F for 'GUID' and nothing came up on the microsoft page I mentioned earlier. Looks like it's called Objectid in the page, which is kind of confusing.
![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/100626839/ed5d7b03-d78c-48e7-9f87-6d7fadb84340)

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/100626839/9a76949b-c251-4712-b8f3-b62d4b8a76a8)

**Comment by maggiesMSFT** [comment]
From the PM: 
Hi Ginger,
You could add ‘Report views’ measure to filter out these duplicates. 
![report-view-measure](https://github.com/MicrosoftDocs/powerbi-docs/assets/12401230/4bf77049-ee2e-4ebc-bd90-21cefe0544c5)

**Comment by maggiesMSFT** [comment]
I'm adding this to the article. Thanks for the question!
