### ISSUE TITLE
Rephrase wording on free viewers for Fabric

### ISSUE THREAD

**Issue by Johannes-Vink** [MicrosoftDocs/powerbi-docs#5012]
"Only P SKUs and F SKUs **larger than F32** allow users with a Microsoft Fabric free license who have Viewer role on the workspace containing the content to consume Power BI apps and shared content in the Power BI service. Smaller F SKUs require a Pro license to consume Power BI content."

Emphasis mine. If you quickly read the sentence, it suggests that a F32 capacity is enough for free viewers, whereas it is F64 and higher. I suggest rephrasing it to:

"Only P SKUs and F SKUs **F64 or larger** allow users with a Microsoft Fabric free license who have Viewer role on the workspace containing the content to consume Power BI apps and shared content in the Power BI service. Smaller F SKUs require a Pro license to consume Power BI content."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI reports and dashboards with coworkers and others - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-share-dashboards)
* Content Source: [powerbi-docs/collaborate-share/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Johannes-Vink. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for your suggestion, @Johannes-Vink ! Making your update now.
