### ISSUE TITLE
Visualizations panel format is resetting to the "visual" tab when we click in a different visual

### ISSUE THREAD

**Issue by LopesRui** [MicrosoftDocs/powerbi-docs#5014]
Hi everyone,

In the Power bi desktop cloud Version: 2.122.746.0 64-bit (October 2023) the Visualizations panel format is resetting when we click in a different visual. 

Previously I could keep comparing the same format settings in the General by simply clicking in the different visuals, now, each time I click in a different visual it goes back to the "Visual" tab even if I was checking the "General" tab. This now consumes me much more time than before.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 540c095a-44b8-bd64-6bb2-81fdefbcb591
* Version Independent ID: 4a74c2a6-2b28-5c73-9243-1ad5e08d6dd2
* Content: [What's new in the latest Power BI update - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @LopesRui. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. 
Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
