### ISSUE TITLE
"actove" should be "active"

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/powerbi-docs#5015]
Hello,

there is a typo in this note: "If the spotlight mode is **actove** when you add a bookmark, that mode is retained in the bookmark."

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 01d247da-ec76-ad4c-e570-fa0e1318fb25
* Version Independent ID: 6acfdc28-ab9e-6441-6295-d0c681fa37fa
* Content: [Use spotlight to highlight - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-spotlight)
* Content Source: [powerbi-docs/consumer/end-user-spotlight.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-spotlight.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @QueryCoordinator. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @, 
Thank you for your suggestion.  We've made the update and set the article to republish. 
All the best,
The DOCS team
