### ISSUE TITLE
Security Whitepaper Data and Storage section

### ISSUE THREAD

**Issue by cignum** [MicrosoftDocs/powerbi-docs#502]
I am not sure wheter it is perfectly clear or correct the statement:
"
Non-DirectQuery queries do not include credentials for the underlying data, and the underlying data is loaded into the Power BI service unless it is on-premises data accessed through a Power BI Gateway, in which case the query only stores references to on-premises data.
"

I mean, if a gateway is used, is the data collected, processed and computed when the report is executed by the user (reflecting the direct query behavior)?
I thought the on-prem data, fetched using a gateway, was stored at rest into the Power BI service.

Can anyone give me a bettere explanation?
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security)
* Content Source: [powerbi-docs/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-security.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @cignum . This looks like a support request (or further explanation is required by a support engineer) rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
