### ISSUE TITLE
Not helpful

### ISSUE THREAD

**Issue by ccustis-bitterroot** [MicrosoftDocs/powerbi-docs#5020]
Format visual is now impossible until data has been added, as Power BI changed its behavior for some terrible reason.  As such, this guide does not comply with current (Feb 2024) Power BI processes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape maps in Power BI Desktop (Preview) - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @msftrien
* Microsoft Alias: **mihart**

**Comment by kfollis** [comment]
@ccustis-bitterroot Thank you for taking the time to provide feedback! We have a project underway to update all of our visualization documentation and this article will be further reviewed as a part of that. I will be sure to share your feedback with the project team. In the meantime, the article is recently updated and should align with current processes, so I am closing this issue. If you have additional feedback, please feel free to submit additional comments using the on-page feedback tools. Thanks again for your feedback!
