### ISSUE TITLE
Misleading Single Sign On Identity providers

### ISSUE THREAD

**Issue by koureasstavros** [MicrosoftDocs/powerbi-docs#5027]
This page describes how Microsoft Entra ID could be used to invite an external user using a social account like gmail.com or hotmail.com but at the moment social / personal accounts (not work or scool accounts) are not allowed for sing in into PowerBI Service. At the end a guest external user with a gmail account can be set up into PowerBI Workspace account but what is the effect from the moment user with gmail cannot login into PowerBI Service? So Microsoft Entra ID allows gmail.com but PowerBI does not (at the moment).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Microsoft Entra B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @koureasstavros, thanks for your comments. I know they are working on improving the B2B experience, and the documentation is a part of that effort. But I am forwarding your comments on to the feature crew to make sure they keep the scenarios you described in mind, and we’ll update the docs accordingly. In the meantime I’ll close this issue. Thanks again for reaching out!
