### ISSUE TITLE
Configure Azure Log Analytics for Power BI

### ISSUE THREAD

**Issue by bravojairo** [MicrosoftDocs/powerbi-docs#5029]
In Prerequisites, the contributor permissions on the subscription is for the user who configures the log analytics? what permissions should be given to the Power BI service, clarify these issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38b32bbf-8798-420d-47d7-f94ece253385
* Version Independent ID: 6c39e53b-3089-26f5-ff03-771919d95c7a
* Content: [Configure Azure Log Analytics in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/log-analytics/desktop-log-analytics-configure)
* Content Source: [powerbi-docs/transform-model/log-analytics/desktop-log-analytics-configure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/log-analytics/desktop-log-analytics-configure.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bravojairo. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Correct, those permissions are for the user configuring; as it states, you must provide Power BI with permission to write logs.
