### ISSUE TITLE
User Authentication to Data Sources section

### ISSUE THREAD

**Issue by cignum** [MicrosoftDocs/powerbi-docs#503]
In the security whitepaper, there are multiple reference to "Role-level security (RLS)". 
Isn't it "Row-level security (RLS)" ? Am I missing something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security)
* Content Source: [powerbi-docs/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-security.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
The Security whitepaper is correct as it's written; sorry that those two terms are so close.
