### ISSUE TITLE
December Download missing

### ISSUE THREAD

**Issue by Monjbaker** [MicrosoftDocs/powerbi-docs#5030]
At the bottom of the December update post, the download link says November 2023, the exact same as in the November 2023 Update section, they both read as November 2023. There is a big issue with my February version so would really like to go back to December 2023 once the link is updated to December 2023.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 93f23670-d83a-dffc-c17a-8cef53d0de7b
* Version Independent ID: 1b63f449-9fbd-3544-bee5-17c70fe55229
* Content: [Previous monthly updates to Power BI Desktop and the Power BI service - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-latest-update-archive?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/fundamentals/desktop-latest-update-archive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/desktop-latest-update-archive.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, fixed that reference (the link is correct), the update will go live shortly.
