### ISSUE TITLE
How to Monitor the usage of Quick measure suggestions generated 

### ISSUE THREAD

**Issue by ratnaponnam** [MicrosoftDocs/powerbi-docs#5031]
How to monitor usage of Quick measure suggestions generated by copilot and who leveraged this feature from developers .
Is there any API will provide this information from Power BI Service .

Regards,
Ratnakishore 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf7765d5-5166-ea69-65af-2c912f2b44da
* Version Independent ID: cf7765d5-5166-ea69-65af-2c912f2b44da
* Content: [Quick measure suggestions - Power BI](https://learn.microsoft.com/en-gb/power-bi/transform-model/quick-measure-suggestions)
* Content Source: [powerbi-docs/transform-model/quick-measure-suggestions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/quick-measure-suggestions.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @Sujata994
* Microsoft Alias: **sunaraya**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @ratnaponnam. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @ratnaponnam,

At this point there isn't an API for monitoring the usage of quick measure suggestions generated by copilot.

You can look at our API pages to see if this changes in the future:
* [Using the Power BI REST APIs](https://learn.microsoft.com/rest/api/power-bi/)
* [Microsoft Fabric REST API documentation](https://learn.microsoft.com/rest/api/fabric/articles/)

You might also want to look at the Fabric [monitoring hub](https://learn.microsoft.com/fabric/admin/monitoring-hub) and the [Capacity Metrics app](https://learn.microsoft.com/fabric/enterprise/metrics-app).

Hope this helps,

Kesem
