### ISSUE TITLE
Guest (External Users) PowerBI License Requirements

### ISSUE THREAD

**Issue by koureasstavros** [MicrosoftDocs/powerbi-docs#5032]
In the beginning it says:
_External members currently can't use the Power BI license they have in their home tenant to access content and perform activities in the provider tenant. Rather, they must explicitly be granted an appropriate license in the provider tenant. External members are similar to internal users on the provider tenant._

But in the bottom it has two scenarios:

1. _Assign a Power BI Pro or Premium Per User (PPU) license to guest user_
2. _Guest user brings their own Power BI Pro or Premium Per User (PPU) license_

And then even closer to the bottom it says:
_There are some limitations to the B2B experience that you should be aware of:_

_Guest users may already have a Power BI license that was assigned to them through their own organization. But “Bring your own license” doesn’t work across different Microsoft Azure clouds for B2B guest users. A new license has to be assigned to these guest users by the provider tenant._

I have to admit that I do not understand, it is unclear when this "Bring your own license" is not going to work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Microsoft Entra B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi Stavros,
Thanks for indicating all these points. As I mentioned, an effort is underway to sort out the issues related to B2B and to clarify the story. I can't tell you exactly when that will be done, however. It is helpful though that you've pointed out the documentation that you've found confusing, and I am passing your comments along to the product team (I am the doc owner). Please feel free to send in more feedback as it comes to you. 
Thanks! 

@koureasstavros
