### ISSUE TITLE
Unable to Use Starbusrt Trino ODBC to connect 

### ISSUE THREAD

**Issue by jlriverayuso** [MicrosoftDocs/powerbi-docs#5033]
as soon as i try to set the ODBC Connection or even attempt to connect i get the 
FAILED!

[Starburst][Trino] (1010) Error occurred while trying to connect: SYNTAX_ERROR : USER_ERROR : line 1:1: mismatched input '{'. Expecting: 'ALTER', 'ANALYZE', 'CALL', 'COMMENT', 'COMMIT', 'CREATE', 'DEALLOCATE', 'DELETE', 'DENY', 'DESC', 'DESCRIBE', 'DROP', 'EXECUTE', 'EXPLAIN', 'GRANT', 'INSERT', 'MERGE', 'PREPARE', 'REFRESH', 'RESET', 'REVOKE', 'ROLLBACK', 'SET', 'SHOW', 'START', 'TRUNCATE', 'UPDATE', 'USE', <query>

**Comment by bishalgoswami** [comment]
Thanks for your comment, @jlriverayuso. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @jlriverayuso. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
