### ISSUE TITLE
Histogram with PowerBI | Recommended DAX function does not match

### ISSUE THREAD

**Issue by roodee** [MicrosoftDocs/powerbi-docs#5035]
Dear feedback team,

being new to PowerBI I was searching on how to create a histogram and found this site. In particular the section https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tips-and-tricks-for-creating-reports?source=docs#histograms seemed to be very helpful. But it was not. Instead of the proposed expression

````
Frequency:=COUNTROWS(<Column Name>)
````

I used the following successfully

````
Frequency:=COUNT(<Column Name>)
````

Using `COUNTROWS(<Column Name>)` did not work at all: It was not even parsed . My next approach then was `COUNTROWS(VALUES(<Column Name>))`. The result was, that each value within the passed column was mapped to 1. 

However: The last approach using `COUNT(<Column Name>)` really made it.  

My PowerBI version is 2.126.927.0 64-bit.

Thank you and kind regards

roodee

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70782244-c01c-bc5b-d266-d9404e02678e
* Version Independent ID: 1fda6a5f-784f-cfee-1352-81619f490814
* Content: [Tips and tricks for creating reports in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-tips-and-tricks-for-creating-reports?source=docs)
* Content Source: [powerbi-docs/create-reports/desktop-tips-and-tricks-for-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-tips-and-tricks-for-creating-reports.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @roodee. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. I've made the correction you suggested, it will be live with the next release. Thanks for taking the time to let us know, and help others who read that article later on!
