### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by alanraetz** [MicrosoftDocs/powerbi-docs#5036]
TYPO: engine is spelled "egine"

"To correct the behavior, the column data types should be updated in the Power Query Editor to remove the Time portion from the imported data, so when the egine is handling the data, the values will appear the same."

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a808705-dc30-b57f-7e2e-2ec0a9360124
* Version Independent ID: 2d766a55-b579-0991-5d79-78ca2a82ef4a
* Content: [Model relationships in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand)
* Content Source: [powerbi-docs/transform-model/desktop-relationships-understand.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-relationships-understand.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @alanraetz. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the close read! I've made that correction, the update will be live with the next release. Much appreciated.
