### ISSUE TITLE
Badly written article

### ISSUE THREAD

**Issue by dineshj231** [MicrosoftDocs/powerbi-docs#5037]
[Enter feedback here]

![image](https://github.com/MicrosoftDocs/powerbi-docs/assets/122114781/571e686d-43db-4eae-9706-29890062ad45)

Hi, In the above snapshot you can see that the wording of this article is off. What does pushing mean here? Could you possibly use another term here? 
This is another badly written article. It's hard to understand! 
Please write and explain your materials so we can understand them. Please have a writer write an article, not a programmer/developer. 
I am going to let my IT department know about this. We don't understand the material your write so we are not able to use the full scope of services of PowerBI. 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish an app in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-create-distribute-apps)
* Content Source: [powerbi-docs/collaborate-share/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-create-distribute-apps.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @dineshj231. This issue has been assigned to the doc author for review.

**Comment by dineshj231** [comment]
Ok thank you.
Please see below. Another example of grammar mistakes. The word highlighted
below should be "works".
As you can understand, the article is difficult to read. Please forward
this request to the management as this is not the only case.

[image: image.png]

**Comment by maggiesMSFT** [comment]
Hi, @dineshj231 -- I updated the article, mostly replacing "push" with "publish" and adding a bit more text. Change won't be live until tomorrow afternoon 2/29/24 Pacific time. Let me know if it's clearer now.
