### ISSUE TITLE
Update FAQ to include Azure Carbon Optimization

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/powerbi-docs#5038]
The article mentions using Cost Management to target reductions in the FAQ: What can I do to reduce emissions further? 
Now we have Azure Carbon Optimization in public preview it should mention that and link to resources here https://learn.microsoft.com/en-us/azure/carbon-optimization/overview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82f8dd20-599d-ab7f-a1db-7e2b5310abb1
* Version Independent ID: 897a9588-8a69-dc64-6722-fd2c731f0f03
* Content: [Connect to the Emissions Impact Dashboard for Azure - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-connect-to-emissions-impact-dashboard)
* Content Source: [powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-connect-to-emissions-impact-dashboard.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @andreabichsel
* Microsoft Alias: **anbichse**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @thommck. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @thommck,

Thanks you for your comment and for getting involved.

As you suggested, I added [What is Azure carbon optimization](https://learn.microsoft.com/azure/carbon-optimization/overview) to *What can I do to reduce emissions further?* in [App setup](https://learn.microsoft.com/power-bi/connect-data/service-connect-to-emissions-impact-dashboard#app-setup).

These changes will go live shortly.

Thanks,

Kesem
