### ISSUE TITLE
OAuth issue when connecting to table fed by external data source

### ISSUE THREAD

**Issue by valentinLeister** [MicrosoftDocs/powerbi-docs#504]
Thanks for the description. I am running into an OAuth error when trying to query a bigquery table which is fed by an external data source (a Google Sheet). 

DataSource.Error: ODBC: ERROR [HY000] [Microsoft][BigQuery] (20) Query execution failed: Access Denied: BigQuery BigQuery: No OAuth token with Google Drive scope was found.
Details:
    DataSourceKind=GoogleBigQuery
    DataSourcePath=GoogleBigQuery
    OdbcErrors=Table

Any thoughts on how to get this working? I would like to avoid creating a clone which lives on bigquery.
Many thanks

let
    Source = GoogleBigQuery.Database(null),
    #"project_name" = Source{[Name="project_name"]}[Data],
    sandbox_Schema = #"project_name"{[Name="sandbox",Kind="Schema"]}[Data],
    external_data_table_View= sandbox_Schema{[Name="external_data_table",Kind="View"]}[Data]
in
    external_data_table_View

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-bigquery)
* Content Source: [powerbi-docs/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-bigquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks @valentinLeister. Can you follow up with support (https://powerbi.microsoft.com/en-us/support/) or ask a question in the community (https://community.powerbi.com/).
