### ISSUE TITLE
Power BI Tutorial is out of date

### ISSUE THREAD

**Issue by eulerpony** [MicrosoftDocs/powerbi-docs#5040]
There are some notational inaccuracies ("Data" pane is inaccurately labeled as "Fields") and images in the tutorial that no longer resemble how the UI functions (I'm struggling to complete "Visual 5. Date Slicer" with the current instructions.)

These are just two examples of how out-of-date this tutorial is. It's a very helpful tutorial, and would be much easier to use if it resembled the actual, current Power BI Desktop UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e0083e3-c11c-2462-6f0f-a166759f14c0
* Version Independent ID: 927cc95e-d442-db4d-75ae-d4a2fa64ae71
* Content: [Tutorial: From Excel workbook to stunning report in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-excel-stunning-report)
* Content Source: [powerbi-docs/create-reports/desktop-excel-stunning-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-excel-stunning-report.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @eulerpony. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @eulerpony, thanks for your feedback. I'm creating a work item in our system for better tracking and management, and will close this issue here now. Thanks again for reaching out!
