### ISSUE TITLE
No mention of Analyze in Excel feature, which is disabled for Viewer role.

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#5043]
The Analyze in Excel feature is disabled for users with the Viewer role. Apart from this blog post, this does not seem to be documented anywhere - this page seems a good spot to do that.
https://powerbi.microsoft.com/en-us/blog/announcing-the-new-viewer-role-for-power-bi-workspaces/

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ad65c63-c38d-5ec7-0386-45ff2602e2a6
* Version Independent ID: d8146ced-680a-5df4-531f-06ebf9c1c2e0
* Content: [Roles in workspaces in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-roles-new-workspaces)
* Content Source: [powerbi-docs/collaborate-share/service-roles-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-roles-new-workspaces.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Mike-Honey. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Thanks for pointing that out, @Mike-Honey ! Updating the article with a new row in the table. Change should be live this afternoon Mar 4, Pacific time.
