### ISSUE TITLE
Information Out Of Date

### ISSUE THREAD

**Issue by qwerty2582** [MicrosoftDocs/powerbi-docs#5046]
This page is out of date.

The documentation for [Azure Maps](https://learn.microsoft.com/en-us/azure/azure-maps/power-bi-visual-get-started) clearly shows that the feature is not currently available for GCC, but it is not documented as an exclusion here.

Microsoft Fabric is not currently available in GCC.

There have been many new features introduced to Power BI that are not currently available in GCC, and they should be properly reflected here.  The items noted here are just a couple of concrete examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for US government customers - Overview - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-govus-overview#limitations-of-power-bi-us-government)
* Content Source: [powerbi-docs/enterprise/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-govus-overview.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @qwerty2582. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments. The table on that page is not meant to be a comprehensive list, and is reviewed by engineering periodically. I have added Azure Maps to the table.
