### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by pawarbi** [MicrosoftDocs/powerbi-docs#5048]
OneLake instead of OneLace

https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-excel-power-bi-datasets#connect-to-your-power-bi-data-in-excel:~:text=the%20Power%20BI-,OneLace,-data%20hub%20(

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Version Independent ID: e44cb508-a74e-ec70-4fcc-e356c6e1e339
* Content: [Power BI semantic model experience in Excel - Power BI](https://learn.microsoft.com/en-us/power-bi/collaborate-share/service-connect-excel-power-bi-datasets#connect-to-your-power-bi-data-in-excel)
* Content Source: [powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/collaborate-share/service-connect-excel-power-bi-datasets.md)
* Service: **powerbi**
* Sub-service: **pbi-collaborate-share**
* GitHub Login: @ajburnle
* Microsoft Alias: **ajburnle**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pawarbi. This issue has been assigned to the doc author for review.

**Comment by pawarbi** [comment]
@maggiesMSFT FYI

**Comment by ajburnle** [comment]
Hey @pawarbi Thank you for your feedback. The typo has been resolved in this following PR: https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/11612. Changes should be shown in the documentation tomorrow. 
Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @pawarbi !
