### ISSUE TITLE
Please add the consequences

### ISSUE THREAD

**Issue by spikylellie** [MicrosoftDocs/powerbi-docs#505]
It would be helpful to add whether this will, or will not, break any existing bookmarks or Excel connections which point to the dataset - for example, the connections created by "Analyse in Excel".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd392eed-242c-00d8-4dac-3cc3b3493adf
* Version Independent ID: 3ab02bc8-6880-ccf8-f010-2854f538ec99
* Content: [Rename dashboards, reports, workspaces, report pages, datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/service-rename)
* Content Source: [powerbi-docs/service-rename.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-rename.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Thanks @spikylellie for your comment. I've assigned to the doc writer for review. Regards - Kelly

**Comment by maggiesMSFT** [comment]
Hi, @spikylellie -- Good question! I'll check for an answer. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @spikylellie -- here's the answer: "Renaming should not break any of the existing bookmarks or connects. It should be just be string change for the artifact." Did you experience an issue with renaming?
I'll update the article with this info. Thanks for asking!

**Comment by maggiesMSFT** [comment]
OK, article is updated. Thanks, @spikylellie !
