### ISSUE TITLE
Block public internet disabling Fabric

### ISSUE THREAD

**Issue by JerroldAI** [MicrosoftDocs/powerbi-docs#5050]
"When you turn on Block Internet Access, Microsoft Fabric is disabled."
This is changed since the private link support for Fabric: https://learn.microsoft.com/en-us/fabric/security/security-private-links-use#step-8-disable-public-access-for-fabric

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27338e81-9282-521f-e0b6-245124da59ec
* Version Independent ID: 27338e81-9282-521f-e0b6-245124da59ec
* Content: [Private endpoints for secure access to Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-security-private-links)
* Content Source: [powerbi-docs/enterprise/service-security-private-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-security-private-links.md)
* Service: **powerbi**
* Sub-service: **pbi-security**
* GitHub Login: @Dandanzhang
* Microsoft Alias: **danzhang**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JerroldAI. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
@paulinbar - can you please look into this?

**Comment by paulinbar** [comment]
Thanks @KesemSharabi
Hi @JerroldAI, you are absolutely correct. Private links support for Fabric was just recently released and documented, and the article you cited now redirects to the new Private links article that resides in the Fabric documentation. Thanks for calling this out though!
