### ISSUE TITLE
External Guest User Cannot Access PowerBI "Workspace"

### ISSUE THREAD

**Issue by yehoshuadimarsky** [MicrosoftDocs/powerbi-docs#5051]
Great write-up, thanks. There was one scenario not covered, which applies to my org, I'm wondering if you can answer this.

Instead of sharing a PowerBI App with hundreds of suppliers, is there a way to grant access to a PowerBI/Fabric "Workspace" to hundreds of suppliers? Specifically, I have a requirement to make several semantic models in a Workspace available to external users to query (like via Excel Pivot Tables).

I have tried doing this but it has not worked.

Steps I tried:
- Invited an external user as a Guest user in my Entra tenant
- Navigated to `app.powerbi.com`, selected my workspace, selected "Manage Access", and granted the external guest user the "Viewer" role
- When the guest user logs into `app.powerbi.com` using their own credentials, they cannot find the Workspace that I granted them access to

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f70ccdae-1552-2465-be6f-d47cd260ad8e
* Version Independent ID: 1ffea5bb-64b0-2661-801e-9eec46e6eec1
* Content: [Distribute Power BI content to external guest users using Microsoft Entra B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/guidance/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/guidance/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-resource**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @yehoshuadimarsky. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond to feature requests.

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
