### ISSUE TITLE
Keyboard access

### ISSUE THREAD

**Issue by anmeeks-vt-edu** [MicrosoftDocs/powerbi-docs#5052]
Please document the keyboard shortcut for accessing focus mode.  This page only describes mouse interaction.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 052edfa5-0db0-da15-88c0-7841f4149347
* Version Independent ID: fa7d4f3d-6480-700b-bd67-3edcc464859b
* Content: [Focus mode and View mode - how to zoom in to see more detail - Power BI](https://learn.microsoft.com/en-us/power-bi/consumer/end-user-focus)
* Content Source: [powerbi-docs/consumer/end-user-focus.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/consumer/end-user-focus.md)
* Service: **powerbi**
* Sub-service: **pbi-explore**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anmeeks-vt-edu. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @anmeeks-vt-edu , 
Thank you for your suggestion.  I added a tip with a link to the page that lists keyboard shortcuts. 
All the best,
The DOCS team
