### ISSUE TITLE
keyboard access to filters and slicers

### ISSUE THREAD

**Issue by anmeeks-vt-edu** [MicrosoftDocs/powerbi-docs#5053]
Visuals in the publicly shared web version of a PowerBI chart have an upside down pyramid icon that opens "Filters and slicers affecting this visual".  This popup lists all the slicers and filters affecting the visual.  There is no keyboard path listed for opening this.  Tab navigation in the visual does not focus it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8df72ff6-206a-243a-a84a-0f6ac418a9b2
* Version Independent ID: e6d1ac0d-3785-cb59-da9c-7dcac2876d2d
* Content: [Keyboard shortcuts in Power BI Desktop - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-accessibility-keyboard-shortcuts)
* Content Source: [powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-accessibility-keyboard-shortcuts.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anmeeks-vt-edu. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comments. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
