### ISSUE TITLE
About Semantic Model owner permissions 

### ISSUE THREAD

**Issue by renanalmeidjr** [MicrosoftDocs/powerbi-docs#5054]
[Enter feedback here]

Hi Team. The table Permission/Description in the doc ( https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-permissions#what-are-the-semantic-model-permissions ) has the following statement:
"The semantic model owner **can do all of the things mentioned in the permissions above**, as well as configure semantic model refresh, credentials, and automatic aggregations.  " 
The part of the statement in bold is probably misleading because the semantic model owner with contributor workspace permission, for example, cannot do things like Reshare a semantic model. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 99e45282-1bfd-170a-5f29-86a247e566f2
* Version Independent ID: 99e45282-1bfd-170a-5f29-86a247e566f2
* Content: [Semantic model permissions - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-datasets-permissions?source=docs)
* Content Source: [powerbi-docs/connect-data/service-datasets-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-datasets-permissions.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @renanalmeidjr. This issue has been assigned to the doc author for review.

**Comment by paulinbar** [comment]
Hi @renanalmeidjr, thanks for your comment. I've forwarded it on to the product team for consideration and will update the documents according to their answer. Again, thanks for taking the time to raise this issue.
