### ISSUE TITLE
Dynamic Visual Calculation

### ISSUE THREAD

**Issue by murtuzamomin** [MicrosoftDocs/powerbi-docs#5055]
Is it possible to use SELECTEDMEASURES() IN Visual Calculation for dynamic approach?
some thing like calculation item.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c71df7c2-3df7-7bb0-63fa-2641b4d23874
* Version Independent ID: c71df7c2-3df7-7bb0-63fa-2641b4d23874
* Content: [Using visual calculations in Power BI Desktop - Power BI](https://learn.microsoft.com/en-gb/power-bi/transform-model/desktop-visual-calculations-overview)
* Content Source: [powerbi-docs/transform-model/desktop-visual-calculations-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/desktop-visual-calculations-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-transform-model**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @murtuzamomin. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
