### ISSUE TITLE
Composite models are now GA.

### ISSUE THREAD

**Issue by snotebaert** [MicrosoftDocs/powerbi-docs#506]
Update reference to composite models being in preview.  Since the november release of Power BI and on-premise data gateway they are GA.

https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-november-2018-feature-summary/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-storage-mode)
* Content Source: [powerbi-docs/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-storage-mode.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @snotebaert. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by davidiseminger** [comment]
Thanks for pointing this out! I've updated the article, which will be republished in the next day or so. Thanks for the close read!
