### ISSUE TITLE
First step is select bar chart visual?

### ISSUE THREAD

**Issue by JPSwan** [MicrosoftDocs/powerbi-docs#5060]
The first step appears to be to select the bar chart visual? It would be helpful to have that in the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 08417ab2-2284-2bef-1573-cd3133c0ade6
* Version Independent ID: afb0a0e3-e502-92b9-4a82-606bf6ed8334
* Content: [Key Performance Indicator (KPI) visuals - Power BI](https://learn.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-kpi?tabs=powerbi-desktop)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-kpi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/visuals/power-bi-visualization-kpi.md)
* Service: **powerbi**
* Sub-service: **pbi-visuals**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @JPSwan. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@JPSwan - thank you for your feedback. We have incorporated your comment with an active work item to improve this article. Closing this issue.
