### ISSUE TITLE
Update to reference both Premium & Fabric Capacity

### ISSUE THREAD

**Issue by elfohl** [MicrosoftDocs/powerbi-docs#5062]
[Enter feedback here]
This doc speaks to Premium Capacity as a licensing option.  We should add Fabric Capacity as a supported licensing option.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 725c3bff-b250-c882-6f2b-1f2cb7f00341
* Version Independent ID: f48832e7-8fc5-498a-8522-435a8ce42129
* Content: [Distribute content to external guest users with Microsoft Entra B2B - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-azure-ad-b2b)
* Content Source: [powerbi-docs/enterprise/service-admin-azure-ad-b2b.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-azure-ad-b2b.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @paulinbar
* Microsoft Alias: **painbar**

**Comment by paulinbar** [comment]
Hi @elfohl, thanks for your comment. I have reached out to the product team with your question and will update the docs accordingly. Thanks for reaching out!
