### ISSUE TITLE
Missing information on Audit logs.

### ISSUE THREAD

**Issue by MartinaPoddana** [MicrosoftDocs/powerbi-docs#5064]
Hi, 

this document used to include reference & information of Audit logs. The ones that can be accessed from Power BI Admin portal & take users to the M365 Admin centre. 
It also included the permission needed.
 - PBI Activity logs -- Power BI Admin
 - Audit logs -- M365 Admin
 
 & included some additional comparison when between Audit logs & Activity logs.
I cannot find similar information anywhere now. There is just a simple page about Audit logs sharing no information on Audit & then transferring to Activity logs [https://learn.microsoft.com/en-us/fabric/admin/service-admin-portal-audit-logs](url)

Can the documentation be enhanced again?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11461058-284e-d146-50d9-9252ebc8e96a
* Version Independent ID: 11461058-284e-d146-50d9-9252ebc8e96a
* Content: [Track user activities in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/enterprise/service-admin-auditing)
* Content Source: [powerbi-docs/enterprise/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/enterprise/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @kfollis
* Microsoft Alias: **kesharab**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @MartinaPoddana. This issue has been assigned to the doc author for review.

**Comment by kfollis** [comment]
@MartinaPoddana - thank you for your feedback. As you're aware, many of the admin activities that applied to Power BI are now Fabric-wide concepts. To support this, we are actively updating and moving content, so I apologize for the disruption. The information that you are looking for can be found in the article https://learn.microsoft.com/en-us/fabric/admin/track-user-activities, which links to the full https://learn.microsoft.com/en-us/fabric/admin/operation-list. I'll close this issue now, but please feel free to reopen if your question isn't anwered.
