### ISSUE TITLE
Details on re-publishing

### ISSUE THREAD

**Issue by andrewbrick** [MicrosoftDocs/powerbi-docs#507]
This document states that "When you re-publish your Power BI Desktop file, the dataset in your Power BI site will be replaced with the updated dataset from the Power BI Desktop file."  You should clarify that not only is the dataset updated, but the report itself is, too.  I think you could create confusion, particularly with the bullet "If you rename or delete a column or measure, any visualizations you already have in Power BI with that field could be broken" because it should be assumed that if an author did this, that they would fix those visualizations in the report prior to re-publishing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @andrewbrick. Good observation. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback!
