### ISSUE TITLE
The word "New" disappears when "On-premises data gateways" is selected in the body of the page

### ISSUE THREAD

**Issue by wayne-at-DSN** [MicrosoftDocs/powerbi-docs#5071]
One of the instructions says "Select New at the top of the screen to add a new data source."

If the user presses "On-premises data gateways" within the page, the word "New" will disappear from the top of the page.

This is really more of a Power BI Service issue, but if this behavior is going to be in place, it could be documented.

If "New" is pressed when "Connections" is selected, one of the choices is "On-premises", so the UI is a bit confusing overall.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 92e0c038-1195-d758-ccf4-903b689139ca
* Version Independent ID: 181904c0-1ec5-0a1d-4cbf-a5a639bbdfeb
* Content: [Add or remove a gateway data source - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/service-gateway-data-sources)
* Content Source: [powerbi-docs/connect-data/service-gateway-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/service-gateway-data-sources.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @arthiriyer
* Microsoft Alias: **arthii**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @wayne-at-DSN. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback.  Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
