### ISSUE TITLE
Foundry connector does appear to be working as expected in Premium dataflow.

### ISSUE THREAD

**Issue by marcadamcarter** [MicrosoftDocs/powerbi-docs#5072]
Recent testing within Premium P1 (dedicated) capacity in DoD sovereign cloud, indicates that Foundry connector works as intended for extracting and refreshing data in a dataflow in a premium workspace despite being listed as "not supported" within [Dataflows or datamart failures in Premium workspaces](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios#dataflows-or-datamart-failures-in-premium-workspaces).  I am unable to confirm same in commercial tenant cloud.

Hesitant to submit PR on this documentation as I'm not sure how this would impact "not supported" status.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7809469d-1c82-a875-3b77-83038a901f52
* Version Independent ID: 5c41e498-26bb-eec4-444e-1c376a2fe87f
* Content: [Troubleshoot refresh scenarios - Power BI](https://learn.microsoft.com/en-us/power-bi/connect-data/refresh-troubleshooting-refresh-scenarios?source=docs#dataflows-or-datamart-failures-in-premium-workspaces)
* Content Source: [powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/connect-data/refresh-troubleshooting-refresh-scenarios.md)
* Service: **powerbi**
* Sub-service: **pbi-data-sources**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @marcadamcarter. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment and testing / observations. Setting a connector as supported has many implications, and while it may work in some circumstances (as you've experienced), the bar for stating it's supported is significant. We continually review our connectors for supportability across all required areas, so thanks for your input, but we can't state support for it at this time.

**Comment by marcadamcarter** [comment]
Thanks @davidiseminger, I understand. Just wanted to provide feedback.
