### ISSUE TITLE
Checking on a page redirect..

### ISSUE THREAD

**Issue by buster35** [MicrosoftDocs/powerbi-docs#5074]
[Enter feedback here]
Looks like Line 585's anchor tag links to `../fabric/admin/microsoft-fabric-admin` endpoint rather than `../power-bi/admin/service-admin-administering-power-bi-in-your-organization`. Intentional?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d5e96ad-ac67-4211-95b3-3707ce55e088
* Version Independent ID: 018d2a68-896b-170c-f3ec-3694f8f2f85d
* Content: [What is Power BI? - Power BI](https://learn.microsoft.com/en-us/power-bi/fundamentals/power-bi-overview)
* Content Source: [powerbi-docs/fundamentals/power-bi-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/fundamentals/power-bi-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-fundamentals**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @buster35. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment! That article does point to the Fabric docs (which now manage admin for Power BI) through the use of what we call a 'redirect' so it works properly... but no reason why we can't update that link to go directly. I'll do that. 

Thanks for the close read!
