### ISSUE TITLE
Screenshots for this page are from a legacy version of Power BI

### ISSUE THREAD

**Issue by popeadam** [MicrosoftDocs/powerbi-docs#5075]
Please update screenshots on this page to reflect the new version of Power BI as I can't for the life of me find a way to 'Show items with no data' using it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52f1d303-a1ee-766e-dac0-d68dad08080c
* Version Independent ID: 053d3adb-90c2-03ce-87c7-47d441a1a79e
* Content: [Show items with no data in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/create-reports/desktop-show-items-no-data)
* Content Source: [powerbi-docs/create-reports/desktop-show-items-no-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/create-reports/desktop-show-items-no-data.md)
* Service: **powerbi**
* Sub-service: **pbi-reports-dashboards**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @popeadam. This issue has been assigned to the doc author for review.

**Comment by popeadam** [comment]
Cheers. Just figured out the issue - it's when you've opted into the 'On-object interactions' preview feature that you can't choose to show items with no values...
