### ISSUE TITLE
Manage terms in Teach Q&A is missing

### ISSUE THREAD

**Issue by Jippi33** [MicrosoftDocs/powerbi-docs#5076]
The possibility to Manage Terms in the Natural language Q&A, Teach Q&A to understand is missing from my Power BI desktop. Any ideas? I need to delete a teaching that is wrong.
![2024-03-25 10_15_46-Teach Q A to understand questions and terms in Power BI Q A - Power BI _ Microso](https://github.com/MicrosoftDocs/powerbi-docs/assets/157715570/c5c16f41-278e-4abf-ae1f-78582e9700a4)

**Comment by bishalgoswami** [comment]
Thanks for your comment, @Jippi33. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Thanks for your comment, @Jippi33. 

This looks like a support request or product question rather than documentation feedback.

You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
