### ISSUE TITLE
Old R prophet package in powerbi service

### ISSUE THREAD

**Issue by BehnamEbrahimiSBUHB** [MicrosoftDocs/powerbi-docs#5077]
Hi, 

The R prophet package used in Power BI service is outdated (0.2.1), whereas the latest version is now 1.0.0, which includes numerous additional features and enhancements. Is an upgrade feasible?

https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/connect-data/service-r-packages-support.md

**Comment by bishalgoswami** [comment]
Thanks for your comment, @BehnamEbrahimiSBUHB. This issue has been assigned to the doc author for review.

**Comment by BehnamEbrahimiSBUHB** [comment]
Hi all, I would appreciate an update regarding this issue. Additionally, my question is whether this is the right place to request updating a package in Power BI service?

**Comment by KesemSharabi** [comment]
Hi @BehnamEbrahimiSBUHB,

Apologies for the delayed response. The correct place to ask for a package upgrade/update, is: Fabric community > Power BI forums > [Ideas](https://community.fabric.microsoft.com/t5/Ideas/ct-p/PBI_Comm_Ideas).

Hope this helps,

Kesem
