### ISSUE TITLE
Git Repo for sample code is out of date

### ISSUE THREAD

**Issue by bsherwin** [MicrosoftDocs/powerbi-docs#5088]
The sample is 2 years old and there are node libraries that no longer exist. The pbi interface has even changed such that this code would never run.

For example, d3 is at 7.8.5 currently. This project references 5.12.

I could not get this sample to build per the website instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95b6da01-c39e-67af-541e-6c9ee48c1d26
* Version Independent ID: bc9e9e91-8151-e02f-ee88-e12929dff9ba
* Content: [Build a bar chart visual in Power BI - Power BI](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-bar-chart?tabs=CreateNewVisual)
* Content Source: [powerbi-docs/developer/visuals/create-bar-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/visuals/create-bar-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @mberdugo
* Microsoft Alias: **monaberdugo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @bsherwin. This issue has been assigned to the doc author for review.

**Comment by mberdugo** [comment]
Thanks for your comment, @bsherwin. We're working on updating this tutorial. 
Hopefully, it will be done soon.
