### ISSUE TITLE
Confusion about purpose of "view-only" membership role

### ISSUE THREAD

**Issue by LydiaLim93** [MicrosoftDocs/powerbi-docs#509]
Under point number 4 of the subsection "Create an app workspace based on an Office 365 group", it is mentioned that "You can also choose if members can edit or have view-only access."

However the sentence which follows immediately is causing confusion:
"**Only add people to the app workspace so they can edit the content.** If they're only going to view the content, don't add them to the workspace. You can include them when you publish the app."

So assuming I take that advice, and only add people who are meant to edit, then why is there still an option to grant them "view-only access"? Is that not redundant?

**Comment by maggiesMSFT** [comment]
Hi, @LydiaLim93 -- yes, good question. With the current version of workspaces, yes, it is possible to add people and give them view-only access. As a workflow, we were recommending against that, suggesting instead to create apps and distribute them to those folks.
Going forward, the new workspaces experience will have a view-only role, and we'll be updating that guidance.
Hope that helps!

**Comment by LydiaLim93** [comment]
Alright, thank you for the clarification, Maggie!
