### ISSUE TITLE
Picture is unreadable

### ISSUE THREAD

**Issue by sqlenders** [MicrosoftDocs/powerbi-docs#5091]
Please make the picture bigger and sharper

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02e17802-d798-33a1-163d-bfe358953051
* Version Independent ID: 02e17802-d798-33a1-163d-bfe358953051
* Content: [Introduction to datamarts - Power BI](https://learn.microsoft.com/en-us/power-bi/transform-model/datamarts/datamarts-overview)
* Content Source: [powerbi-docs/transform-model/datamarts/datamarts-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/transform-model/datamarts/datamarts-overview.md)
* Service: **powerbi**
* Sub-service: **pbi-dataflows**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @sqlenders. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your suggestion. We've increased the size of that image, and included a lightbox (so you can click the image and it appears in full size). Thanks!
