### ISSUE TITLE
Not entirely correct about replacing

### ISSUE THREAD

**Issue by precedence** [MicrosoftDocs/powerbi-docs#51]
"the dataset in your Power BI site will be replaced with the updated dataset from the Power BI Desktop file" is not entirely correct.  If you try to publish a report that is named the same thing as another report but one is import and the other is live connect, then it will not replace the first dataset.  It's more like it "updates" the dataset as much as it can.   If you want to truly replace an impoart dataset with another dataset that is direct query, then you'll need delete the first dataset.  Interesting distinction between "update" and "replace."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@precedence - thanks for posting and for the clarification. I'll check with the engineering team about how best to clarify what you've described, and meanwhile, others will benefit by having your post here in the article. Thanks for posting!
