### ISSUE TITLE
Timeline for certification

### ISSUE THREAD

**Issue by brmort** [MicrosoftDocs/powerbi-docs#510]
Would it be possible to have an approximate timeline included with the process section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43339087-a0a1-451d-76f6-bb6bad776a43
* Version Independent ID: 2ef46a24-2aeb-fbe3-821a-bffed8a03de0
* Content: [Certified Power BI custom visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified)
* Content Source: [powerbi-docs/power-bi-custom-visuals-certified.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-custom-visuals-certified.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @brmort -- thanks for your question! I've assigned it to the author, who'll get back to you soon.

**Comment by markingmyname** [comment]
@brmort Apologizes for the delayed response.

I'm not sure, but that is an excellent question.

Let me discuss with the team, and I will follow-up after the New Year.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
