### ISSUE TITLE
Documentation seems incorrect for dynamic dataset binding

### ISSUE THREAD

**Issue by anujkuchiya** [MicrosoftDocs/powerbi-docs#5106]
We are trying to implement dynamic dataset binding during report embedding in our angular application for Embed for your customer scenario (App owns data). We are following below learn article for that.

Bind datasets dynamically to a report: [here](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/bind-report-datasets#example-1-embed-a-paginated-report-with-dynamic-binding).

But datasetbindings property changes mentioned in the above article are not working for a .pbix report
```
datasetBindings: [{
            sourceDatasetId: "originalDatasetId",
            targetDatasetId: "notOriginalDatasetId"
        }]
```

When we looked at the Powerbi-Docs repository, the bind report datasets documentation is missing. 
Documentation: [here](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/powerbi-docs/developer/embedded/embed-dynamic-binding.md#adjusting-the-config-object) does not have correct link to [bind-report-datasets](https://github.com/MicrosoftDocs/powerbi-docs/blob/main/javascript/api/overview/powerbi/bind-report-datasets) ( 404 - page not found )

While trying to find the doc for that, came across this old documentation on dynamic binding, which is working correctly though [here](https://github.com/microsoft/PowerBI-JavaScript/wiki/Dynamic-Binding/7d37f4c69aa058aec03e4c68cc5c9b4f5d8a29b5#example)
```
datasetBinding: {
		datasetId: "notOriginalDatasetId", // The wanted dataset id
	}
```
 Could you please help me out, if we should consider old documentation, or am I missing something in new one ?

**Comment by bishalgoswami** [comment]
Thanks for your comment, @anujkuchiya. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @anujkuchiya,

I think you're looking in the wrong place. You're looking at an article that's targeting [paginated reports](https://learn.microsoft.com/power-bi/paginated-reports/paginated-reports-report-builder-power-bi) but you're trying to bind a 'regular' report.

Try following the instructions in [Bind datasets dynamically to a paginated report](https://learn.microsoft.com/en-us/javascript/api/overview/powerbi/bind-report-datasets). You can also use the old document you found.

Hope this helps,

Kesem
