### ISSUE TITLE
Clarify XMLA read/write capabilities of Default Semantic Models

### ISSUE THREAD

**Issue by otykier** [MicrosoftDocs/powerbi-docs#5107]
[Default Semantic Models](https://learn.microsoft.com/en-us/fabric/data-warehouse/semantic-models) (such as those created by a Power BI Datamart, or Fabric Warehouse/Lakehouse), cannot be modified through the XMLA endpoint.

This seems to be a pretty important limitation, but I didn't see it mentioned anywhere in the docs. A good place to mention this would be on the [Semantic Model connectivity with the XMLA Endpoint](https://learn.microsoft.com/en-us/power-bi/enterprise/service-premium-connect-tools)-article.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @otykier. This issue has been assigned to the doc author for review.

**Comment by KesemSharabi** [comment]
Hi @otykier,

Thank you for your feedback. I moved your request to my internal queue and will attempt to make the changes you suggest soon.

Kesem
