### ISSUE TITLE
PDF exported location

### ISSUE THREAD

**Issue by henriquebrisola** [MicrosoftDocs/powerbi-docs#512]
The location of the PDF file exported should be noted on the documentation.
I could find it somewhere on Local App Data / Temp.

Also, I think it should save on the same PBIX file location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export your reports to PDF format from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-export-to-pdf)
* Content Source: [powerbi-docs/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-export-to-pdf.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @henriquebrisola! Thanks for your suggestion. We’ve forwarded your feedback to the writer, who should respond soon. 
It looks like you have some product feedback, too. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. 
Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback, and sorry about the trouble you had.

**Comment by henriquebrisola** [comment]
Documentation hasn't been changed.
This thread should not be closed.
