### ISSUE TITLE
"Expand Q&A and Cortana" does not exist

### ISSUE THREAD

**Issue by camwally** [MicrosoftDocs/powerbi-docs#514]
Step 3 is "Expand Q&A and Cortana, select the checkbox for Turn on Q&A for this dataset and choose Apply." I cannot see "Expand Q&A and Cortana" I can only see "Gateway connection", "Data source credentials", "Parameters" and "Scheduled refresh". Why would this be? The dataset is connecting to Sharepoint.   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8fe9672-0cf8-7566-6f4b-49991f9aba3f
* Version Independent ID: fd7ecaee-3d87-272c-713b-03b446008cfc
* Content: [Use Q&A with live connections in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-q-and-a-direct-query)
* Content Source: [powerbi-docs/service-q-and-a-direct-query.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-q-and-a-direct-query.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
hi, @camwally -- Thanks for asking -- good question. I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @camwally -- sorry for the delay. I've confirmed that Cortana is deprecated., so I can remove it from the article. I'm checking on the Q&A part.
Thanks for asking!

**Comment by AmnerisMarquez** [comment]
I think the option that you are looking is on "Dashboards Settings"---"Q&A"

**Comment by kfollis** [comment]
@camwally and @AmnerisMarquez - Thank you for submitting feedback on our documentation. This article has been updated since your feedback was submitted. If your feedback isn’t addressed, please feel free to submit additional feedback for the page.
