### ISSUE TITLE
I am not able to utilize the Usage Metrics by Report/Dashboard in Power BI Pro (Government Tenant).

### ISSUE THREAD

**Issue by omanlap** [MicrosoftDocs/powerbi-docs#517]

**Comment by mihart** [comment]
Hi @omanlap 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.
If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
Kind regards,
Microsoft DOCS International Team
