### ISSUE TITLE
NOT ALL  transformations using M editor, are supported

### ISSUE THREAD

**Issue by ozhug** [MicrosoftDocs/powerbi-docs#518]
What kind of transformations can be performed with computed entities? Any transformation that you usually specify using the transformation user interface in Power BI, or the M editor, are all supported when performing in-storage computation.

This is incorrect using not all M editor transformations are supported. doing something like below and you end up with a complex column which cannot be loaded.

 #"Added Custom" = Table.AddColumn(Source, "Updated", each Date.AddDays(Date.From(DateTimeZone.From("20" & Text.Start(Number.ToText([COLUMN]),2) & "-01-01")),Int64.From(Text.End(Number.ToText([COLUMN]),3))))
  using 

It would be helpful if there was a list of "M editor" steps that are supported in dataflows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71265a0f-32b6-7cf3-7daa-3b523aa556a5
* Version Independent ID: da1e7392-ea68-65c7-916e-89e0d9974dc5
* Content: [Using computed entities on Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-computed-entities-premium)
* Content Source: [powerbi-docs/service-dataflows-computed-entities-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-computed-entities-premium.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Adding another assignee to help look into this request.

**Comment by ozhug** [comment]
Thanks my transformation to add a date column from data is now working.
