### ISSUE TITLE
Using others models in Power BI Report Server on-premises

### ISSUE THREAD

**Issue by persefer** [MicrosoftDocs/powerbi-docs#519]
My customer doesn't want to publish reports via cloud so we will use Power BI report server. Can we still share our datasets/models or use others models with reports server installation? Or sharing via cloud in Power BI Online Services required? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @persefer -- sorry for the delay! Answers to your two questions:
Q; Can we still share our datasets/models or use others models with reports server installation?
A: No
Q: Or sharing via cloud in Power BI Online Services required?
A: Yes
Thanks for asking!

**Comment by dirtyknights** [comment]
> My customer doesn't want to publish reports via cloud so we will use Power BI report server. Can we still share our datasets/models or use others models with reports server installation? Or sharing via cloud in Power BI Online Services required?
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
> * Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
> * Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
> * Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
> * Service: **powerbi**
> * GitHub Login: @davidiseminger
> * Microsoft Alias: **davidi**

I would like to talk to you about your Google Page Speed Insight results.  Please contact me at miknight@dirtyknights.com
