### ISSUE TITLE
Limitation solved: How to avoid reseting report filters when using bookmarks

### ISSUE THREAD

**Issue by zhouqinp** [MicrosoftDocs/powerbi-docs#52]
In the Limitations, there lists "If you add a visual on a report page after creating a bookmark, the visual will be displayed in its default state. This also means that if you introduce a slicer into a page where you previously created bookmarks, the slicer will behave in its default state." Actually, you are allowed to change the settings to keep the filters applied when you use bookmarks. I learn this from the 2018 Jan Updates of Bookmark. (http://microsoft-bitools.blogspot.com/2018/01/power-bi-bookmarking-feature-update.html). Simply right-click the bookmark and uncheck 'data' category, you will get the report/page level filters kept when you jump between bookmarks.
In my case, I create two slicers and a 'Search' button on the 'Search' bookmark. The slicers are applied to the report-level. The button directs to the 'Result' bookmark with the two slicers, a table showing search results and a 'Return' button back to the first bookmark. By default, the 'data' category is checked in the 'Result' bookmark, which means each time I click on the 'Search' button, the filters get reset and the search results are gone, not what I want. So I uncheck 'data' category of 'Result' bookmark. The slicers are kept and results are filtered. EASY! I keep the 'data' category of 'Search' bookmark checked so each time I click 'return' button, it goes back to the 'Search' bookmark and clear the slicers. EASY!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@zhouqinp - that's great! Thanks for sharing this, and I'll also share this with the engineering team. Thanks for posting!

**Comment by annmarygit** [comment]
Thanks for the solution! It really helped to resolve similar issue.

**Comment by itshudak** [comment]
Way late to this conversation, but this is exactly what I was looking for! Thank you. This should definitely be added to the main doc.

**Comment by sujaynadkarni** [comment]
Thank you!!! Exactly what we were looking for!
