### ISSUE TITLE
Premium

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs#520]
This page does not mention the concept of Power BI Premium capacity. It would be good to explain if App Workspaces backed by Premium capacity contribute to the total storage of a Pro user, or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0947245-d1c6-486a-94a1-f8622a4f7efc
* Version Independent ID: c837d3a1-75f5-ffd4-a32a-541bab72ffa7
* Content: [Manage data storage in your workspaces - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-manage-your-data-storage-in-power-bi)
* Content Source: [powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-manage-your-data-storage-in-power-bi.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @DaveRuijter -- great question. I've gotten confirmation from the product team that an app workspace in a Premium capacity does not count to the storage of a Pro user. Thanks for asking!
