### ISSUE TITLE
The code is obsolete since 2 major versions have been released since.

### ISSUE THREAD

**Issue by peterhel** [MicrosoftDocs/powerbi-docs#521]
I managed to get it "working" with the latest (async) version of the NuGet package. But I got a reply URL error. I reverted to the old version, but the problem is still there. I have no way to get this working since I have no idea where to look for the correct URLs. Please update the docs since I really don't want to have to turn to stackoverflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @peterhel -- thanks for your comment. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by markingmyname** [comment]
@peterhel Sorry for the delayed response.

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@peterhel can you try this version of the NuGet package? -https://www.nuget.org/packages/Microsoft.PowerBI.Api/2.1.1

**Comment by markingmyname** [comment]
@peterhel The article is scheduled to be updated with this new information sometime in February.  

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
