### ISSUE TITLE
Filters Preview

### ISSUE THREAD

**Issue by akrottcsp** [MicrosoftDocs/powerbi-docs#526]
I love the idea of the filter pane. But there's a reason why I use the filter visuals instead of the standard report filters when sharing reports - customization and misrepresentation. 

1) to use the new filter pain, it would have to be highly customizable and include options for font size, padding, line height, etc. PowerBI can't predict what values would be filtered and there are times when we deal with long values, etc. Other options would be renaming the filter to a more user friendly name as well being able to include some help text. 
2) Obviously being able to order, group and style the filters independently is important
3) The value count needs to be an option setting. This is a big one. Because sometimes your report may be based off a table that is already prefiltered. However, the total values shown in the filter pane is always showing ALL values found in the DB. It's for this reason alone I wouldn't be able to use it as the numbers could be highly misleading.

It's a great idea and I'm excited about it assuming we have the customization we need. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by akrottcsp** [comment]
Two other comments - please include the ability to hide the value "blank." Sometimes there is a reason why this value exists but it does not mean you want users filtering by it.

Also, in general, the scroll pane on all visuals is much too narrow and you can't customize. It's actually a feature which my users gripe about all the time because on smaller displays they have a hard time working with it. Please provide the ability to customize width in general on all visuals and filters.

**Comment by kfile** [comment]
@akrottcsp, thank you for your feedback. I've assigned to the doc author who will share your comments with the product team. Please note that the doc team is out for the holidays so there will be a delay in responding. Regards - Kelly

**Comment by maggiesMSFT** [comment]
Hi @akrottcsp -- yes, thanks for your feedback! Looks like it's about the product, rather than the documentation. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.  Thanks again!

**Comment by MiroslawK** [comment]
This optron is not available in the Polish language version. 
The association of actions on the button also does not work (bookmark).

**Comment by UalasCaixeta** [comment]
Olá, em um relatório publicado no serviço Power BI, os filtros do Visual que estão marcados como ocultos no Power BI Desktop estão sendo apresentados ao usuário final.

Desktop:
![image](https://user-images.githubusercontent.com/31940829/55891041-3daeef80-5b8a-11e9-99a7-2cb050cb7b0e.png)

Serviço:
![image](https://user-images.githubusercontent.com/31940829/55891086-515a5600-5b8a-11e9-9dfa-5381a92dae63.png)

**Comment by ahpitre** [comment]
As of May 2019 Desktop RS version the new Filter Pane is not available. Seems only available in Power BI Service. When will this be available for Power BI RS version?

**Comment by maggiesMSFT** [comment]
Hi, @ahpitre and @UalasCaixeta -- have you turned on the preview in the Desktop? https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview#turn-on-the-new-filter-experience 
That's the first step. If yes, or if you're not seeing the option, then I recommend contacting support. https://powerbi.microsoft.com/en-us/support/

**Comment by ahpitre** [comment]
The preview new features is not available. Like always, seems that the cool features always make it first to Power BI Service. Will have to wait till RS version gets them. ;(

**Comment by maggiesMSFT** [comment]
Oh, so sorry, @ahpitre -- I read your comment too fast. Yes, you're absolutely right, PBI RS doesn't have preview features.
