### ISSUE TITLE
Column Limit ambiguity

### ISSUE THREAD

**Issue by dkikan** [MicrosoftDocs/powerbi-docs#527]
"Dataset size limit - there is a 1 GB limit for each dataset in the Power BI service.
Row limit - the maximum number of rows in your dataset (when not using DirectQuery) is 2 billion, with three of those rows reserved (resulting in a usable maximum of 1,999,999,997 rows); the maximum number of rows when using DirectQuery is 1 million rows.
Column limit - the maximum number of columns allowed in a dataset, across all tables in the dataset, is 16,000 columns. This applies to the Power BI service and to datasets used in Power BI Desktop. Power BI uses an internal row number column per table included in the dataset, which means the maximum number of columns is 16,000 minus one for each table used in the dataset."

The first line reads "maximum number of columns allowed in a data, across all tables in the dataset, is 16,000 columns" whereas the last line reads "the maximum number of columns is 16,000 minus one for each table used in the dataset." 
So the total limit, of 16,000 columns, applies to dataset or table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @dkikan and thanks for your comment. I have assigned the issues to the author. He is on vacation until after the holidays, FYI. Regards - Kelly

**Comment by davidiseminger** [comment]
I think the content is correct and clear; if you have multiple tables, you lose one per table in the dataset. So if you had three tables, the max would be 16,000 minus 3.
