### ISSUE TITLE
good work !

### ISSUE THREAD

**Issue by vikpande** [MicrosoftDocs/powerbi-docs#53]
Short and sweet. Thanks for the quick explanation here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd66fe6d-5d79-32f8-d77d-621df2e04d97
* Version Independent ID: 5004c7d8-ea11-8cc2-0e25-69b9ab98f5e1
* Content: [Power BI Desktop videos - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-videos)
* Content Source: [powerbi-docs/desktop-videos.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-videos.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
#sign-off

**Comment by davidiseminger** [comment]
You're welcome - thanks for the nice comments!
