### ISSUE TITLE
Relationships

### ISSUE THREAD

**Issue by hifihedgehog** [MicrosoftDocs/powerbi-docs#531]
In order to perform on-the-fly random forest calculations based on parameter selection, I need to have multiple tables of unrelated information pass through into the Python visualization. Each table contains an independent variable that I filtered via a slicer. I need all of these independent variables for the random forest algorithm to be able to make its prediction. Otherwise, it is impossible to do so currently in Power Bi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c6b7b4f-9f34-cec1-687c-2f5c708fe99f
* Version Independent ID: e66e6e43-157d-8331-20e2-89d1379c5251
* Content: [Create Power BI visuals using Python - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-visuals)
* Content Source: [powerbi-docs/desktop-python-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-visuals.md)
* Service: **powerbi**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mgblythe** [comment]
@hifihedgehog - closing this issue. Feel free to reopen if this is a doc request.

You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.
