### ISSUE TITLE
can the recipient modify the filter?

### ISSUE THREAD

**Issue by asocorrocognex** [MicrosoftDocs/powerbi-docs#532]
Can the recipient modify the filter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7b3989d-4ab1-51f2-6823-970c04f6fba9
* Version Independent ID: 673ccbe9-ef77-5c5b-9936-37eaeb4d3762
* Content: [Filter and share Power BI reports with coworkers - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-reports)
* Content Source: [powerbi-docs/service-share-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-reports.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @asocorrocognex -- me again! Thanks for asking, good question. Yes, they can just remove the filter from the end of the URL to see the report with no filter. Hope that helps!

**Comment by asocorrocognex** [comment]
I’m voting for you for employee of the year.  Thanks!  I think it was obvious that the user could, but nevertheless wanted to be 100% certain.  Every time I have visited that page the same doubt crept in, so I decided to ask.

Perhaps I was initially thrown in doubt by the article’s title, as you are not really sharing a filtered version of the report, but a full report with an initial filter applied.  Oh well.

Thanks again!

**Comment by maggiesMSFT** [comment]
Hi, @asocorrocognex -- ha! (on the Employee of the Year part)
You make a good point. I'm going to update the article to clarify that. Thanks!

**Comment by maggiesMSFT** [comment]
Oh -- I updated the article ages ago and didn't close this. OK, I've updated it more. Thanks again, @asocorrocognex!

**Comment by pellodan** [comment]
Also, if they use Analyze in Excel, the filters are REMOVED
