### ISSUE TITLE
Images unreadable if Dark theme is used

### ISSUE THREAD

**Issue by mow700** [MicrosoftDocs/powerbi-docs#533]
I'm using the Dark theme on the site, and it took me a few minutes to discover why the images in this article didn't seem to make sense.  I switched to the Light theme and discovered why, images are using a transparent background with black elements.  The black elements appear hidden if using the dark theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce725cf3-1fcb-9942-3b6f-63dade96b0d3
* Version Independent ID: 0e724841-6fcc-d35a-167f-f5c7d2162f30
* Content: [Power BI Security - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-power-bi-security)
* Content Source: [powerbi-docs/service-admin-power-bi-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-power-bi-security.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @mow700 -- thanks for pointing that out! I'll let this author and other authors on the site know.

**Comment by saurius** [comment]
Still not working :(

**Comment by davidiseminger** [comment]
That is correct, and an artifact of using a dark theme. Please use different colored images if you'll use a dark theme, to prevent them from disappearing / becoming non-visible.

**Comment by jcondina** [comment]
Same thing if High Contrast theme is used, which should be even clearer to read
