### ISSUE TITLE
Power BI Desktop connection to  'On-premises SharePoint server 2016'  with 'SharePoint Folder"

### ISSUE THREAD

**Issue by mdittakavi** [MicrosoftDocs/powerbi-docs#534]
Hi Team
Does installing  gateway public or personal mode help 'Power BI' desktop client to connect to a file in On-premesis Sharepoint server library.  

From Power BI desktop , using 'SharePoint list' we can connect to ON-premesis SharePoint list but not SharePoint Folders. any idea

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb1195df-a72b-61c1-3490-64ca851e81b1
* Version Independent ID: 8e9e2f51-78eb-7dfc-8195-cf99bd55d61c
* Content: [What are Power BI gateways? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started)
* Content Source: [powerbi-docs/service-gateway-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-getting-started.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Hi @mdittakavi and thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
