### ISSUE TITLE
Potential Error

### ISSUE THREAD

**Issue by Aidan-Aoki** [MicrosoftDocs/powerbi-docs#535]
Net Sales per Unit = [Net Sales] / SUM(Sales[SalesQuantity])

In regards to the above, shouldn't another measure be made for [Net Sales Quantity] being [SalesQuantity] - [ReturnQuantity] so that you are comparing [Net Sales] to the correct figure for quantity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5439d8e1-71bb-cdf7-53bc-952f08a359e0
* Version Independent ID: 11f475af-c858-0a7e-d07d-7083e4fc8e39
* Content: [Tutorial: Create your own measures in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-create-measures#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-create-measures.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-create-measures.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @Aidan-Aoki.  We’ve forwarded your feedback to the writer, who should respond soon. Do note that as we head into the holidays, we may experience delays. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment @Aidan-Aoki - I believe that content is correct as-is, but if you have questions about how to use it, please take a look at https://community.powerbi.com.
