### ISSUE TITLE
Use Azure AD groups in New Workspaces

### ISSUE THREAD

**Issue by jeroenhabets** [MicrosoftDocs/powerbi-docs#536]
Hi,
I've created a new workspace and now want to give Member access to an Azure AD group.

The input for the principals has "Enter email addresses" as default text ~~and only lets me search on email. If I enter a group name it finds no results~~.
I would have expected the default text "Enter email addresses or group names" ~~and groups to be returned in addition to matching users~~.

*Update*: I discovered the input is no longer working in Firefox 64.0. So two issues:
- Fix functionality for Firefox
- Improve functionality by replacing "Enter email addresses" with "Enter email addresses or group names"

Cheers, Jeroen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#planned-new-app-workspace-preview-features)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @jeroenhabets, Thanks for your comment. Looks like this is product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.  
Thanks!

**Comment by jeroenhabets** [comment]
Closed and logged: https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/36518479-workspace-preview-quickwin-improve-access-set-up
