### ISSUE TITLE
who in an organization can create workspaces

### ISSUE THREAD

**Issue by rocksde** [MicrosoftDocs/powerbi-docs#537]
I checked several times but the article mentions "Power BI admins decide who in an organization can create workspaces. See the Power BI admin portal article, Workspaces section for details." and I am unable to find where I can define who and who not can create new workspaces. Could you make this a little clearer please. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @rocksde -- thanks for your feedback! I agree, we don't make it very clear. I will discuss with the author of https://docs.microsoft.com/en-us/power-bi/service-admin-portal#workspace-settings and see where we can make improvements. We are heading into the holidays, so we may experience delays...

**Comment by hfulks** [comment]
Power BI Admin normally can determine which users can create workspaces, but the tenant admin can override and block workspace creation even for the Power BI Admin role.

**Comment by maggiesMSFT** [comment]
Good answer, @hfulks. I'll leave it at that. I've updated the admin portal article with some more info.
Thanks, @rocksde, for asking!
