### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by xstodeepak** [MicrosoftDocs/powerbi-docs#539]
Under the heading "View filters for a visual in Reading mode", in the first line i.e. "In Reading mode, you can hover over a visual and see.....", should be "In Reading mode, you can hover over 'filter' icon in the visual and see....".

Simply hovering pointer over a a visual doesn't show applied filters, rather the viewer has to over the 'filter' icon in that particular visual to see all the applied filters. I think this documentation line needs to be fixed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by jainn4** [comment]
Hi there, 

I have noticed that the December desktop version doesn't have the same options as I can see in the service. You can see the screenshot below

**### Options in Service**
![filter_pane_service](https://user-images.githubusercontent.com/42496773/51788154-ad5c3380-2172-11e9-8682-0524e919b05e.PNG)

**### Options in Desktop**
![filter_pane_desktop](https://user-images.githubusercontent.com/42496773/51788155-adf4ca00-2172-11e9-9e8b-7dfd852bc86d.PNG)

Can you please look into this?

**Comment by maggiesMSFT** [comment]
So true, @xstodeepak! I'll update the article.

**Comment by maggiesMSFT** [comment]
Hi, @Ghuiles -- good question! Reading mode is in the Power BI service. When you first open a report, it's in reading mode. If you have edit permissions, you can select Edit Report in the upper-left corner. Then you're in edit mode. If you don't have edit permissions, Edit Report is grayed out.
