### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by maggiesMSFT** [MicrosoftDocs/powerbi-docs#54]
Thanks for answering these questions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f6bd837-63e3-8bcd-9743-425e6da4a9b8
* Version Independent ID: 944bd5e0-a52f-0a4c-362b-68701f03c8d8
* Content: [Administering Power BI - frequently asked questions (FAQ) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-faq)
* Content Source: [powerbi-docs/service-admin-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-faq.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Closing test issue
