### ISSUE TITLE
Not all scopes in the Azure Portal are documented here (ex. View all workspaces)

### ISSUE THREAD

**Issue by ryanspletzer** [MicrosoftDocs/powerbi-docs#543]
Not all scopes in the Azure Portal are documented here (ex. View all workspaces)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b836b669-bee0-737a-8de1-b3fd0cda0218
* Version Independent ID: f6ae700d-4db0-fd20-fab5-6020ecde08c4
* Content: [Power BI permissions - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/power-bi-permissions)
* Content Source: [powerbi-docs/developer/power-bi-permissions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/power-bi-permissions.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@ryanspletzer I apologize for the delayed response.

We will investigate and review if we need to change/add the information suggested.

I am in current talks with the parties involved.

Thank you for your feedback!

**Comment by markingmyname** [comment]
Hi @ryanspletzer,

Well, the API is called Groups but it applies to group-based and v2 workspaces.

I am thinking of adding a note to the article to clarify that a bit.

Thank you for your feedback.

**Comment by jayendranarumugam** [comment]
@markingmyname I couldn't understand, Can you tell me the difference between workspaces and groups?
We are still seeing two difference API permissions in the PowerBI (During App registration) which is `View all workspaces` and `View all groups` which one is we need to give?

You are saying that groups are the V2 workspaces and workspace are the `classical(v1) workspace ` ???
