### ISSUE TITLE
Documentation only fits for .NET developers

### ISSUE THREAD

**Issue by gregra81** [MicrosoftDocs/powerbi-docs#545]
If I'm not a .NET developer, this is not useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by kfile** [comment]
HI @gregra81 and thanks for your comment. This issue has been assigned to the author who is on vacation until after the holidays. Thank you.

**Comment by markingmyname** [comment]
@gregra81 Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@gregra81 We plan to have more samples in other languages in the next few months.  However, there is not an exact ETA.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
