### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by ajobbins** [MicrosoftDocs/powerbi-docs#546]
This doesn't seem to work. I have admin access to our Project Online tenant and when I try and connect (after signing into my organisational O365 account), I just get an error saying "We couldn't authenticate with the credentials provided"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data)
* Content Source: [powerbi-docs/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
HI @ajobbins and thanks for your question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
