### ISSUE TITLE
Failed to update data source credentials

### ISSUE THREAD

**Issue by sukpakan** [MicrosoftDocs/powerbi-docs#547]
I have following this instruction but its show error below.

Failed to update data source credentials: The credentials provided for the MicrosoftAzureConsumptionInsights source are invalid.
status code: 400

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by kfile** [comment]
Hi @sukpakan and thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
