### ISSUE TITLE
Spelling mistake in documentation

### ISSUE THREAD

**Issue by iamankitpawar** [MicrosoftDocs/powerbi-docs#55]
Under the heading Next Steps, it should be :
To get started with Power BI Desktop, the first *thing* you need is to download and install the application. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e941f6c9-1676-dc84-ed1b-027a1c61cd23
* Version Independent ID: 373ee1b3-c001-d1a8-6eb4-832cbea29fe1
* Content: [What is Power BI Desktop? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-what-is-desktop)
* Content Source: [powerbi-docs/desktop-what-is-desktop.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-what-is-desktop.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @iamankitpawar - you're right! Thanks for catching that, I've fixed that typo and it should be corrected in the next day or so. Thank you!
