### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jeetsharma78** [MicrosoftDocs/powerbi-docs#550]
Nice. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Getting data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@jeetsharma78 Thanks so much for contacting us! We appreciate the feedback. The author of this article is away on vacation. When he returns, he should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
You're welcome!
