### ISSUE TITLE
Why the application is registered as a Native App for "App Own Data" scenario

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [MicrosoftDocs/powerbi-docs#551]
As per the document for "App Owns data" needs to registered as Native App compared to "User Owns Data" scenario but I couldn't able to find reason for registering as a Native app ? It would be good to document the reason for the registering it as a Native app ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@SaurabhSharma-MSFT Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by jayendranarumugam** [comment]
+1 I've the same confusion, where I posted my question [here](https://social.msdn.microsoft.com/Forums/en-US/8fbe4a13-6813-456a-a6a8-83eca060e2c9/why-powerbiembedded-app-owns-data-using-azure-native-app-registration-?forum=WindowsAzureAD)

**Comment by markingmyname** [comment]
@SaurabhSharma-MSFT Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@SaurabhSharma-MSFT I hope this explanation helps.

Use Native app for apps that run on client devices. Choose Native app if you are embedding content for your customers regardless of what is the application, even for web applications.

Use Server-side Web app for web apps or web APIs.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
