### ISSUE TITLE
Activity types missing

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#552]
Hello, the following Activity Types are missing from this otherwise very helpful document: MGPP MGPE MDGR MGTD MGCC MDSR MGGS MGEE MGOC MGGC MGGS MGEA MGEQ

Would be great if they can be documented here, since they don't seem to be documented anywhere else. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f41ca5-f249-e0a8-fb68-d19215f5ca66
* Version Independent ID: 74828e70-9e56-afd3-aa11-5bfaab20e384
* Content: [Troubleshooting the On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot#activities)
* Content Source: [powerbi-docs/service-gateway-onprem-tshoot.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-tshoot.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @chrisweis, adding @arthiriyer to see if she has info on these.

**Comment by arthiriyer** [comment]
@chisweis Currently the non-documented information in the logs is more  for internal diagnostics and troubleshooting- and hence is not widely publicized.
That being said, in this semester, we are working on improving our documentation and as part of that we will take this as feedback and check if we can add any additionally details which may be useful to the customers.

**Comment by mgblythe** [comment]
The logging/monitoring info we do support for public consumption is now in a new article: https://docs.microsoft.com/data-integration/gateway/service-gateway-performance.
