### ISSUE TITLE
Add information to connect to Pay-as-you-go

### ISSUE THREAD

**Issue by atxjd** [MicrosoftDocs/powerbi-docs#554]
Just shows instructions for EA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @atxjd. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. In the meantime, can you provide a little more detail on the issue you raised?

**Comment by woodbridge** [comment]
hey, this is on the backlog but we're not sure when it'll land!  We're working on it though :)

**Comment by maggiesMSFT** [comment]
Thanks, @atxjd, for asking, and thanks, @woodbridge, for answering. I'll close this issue now.  
cc @SarinaJoan
