### ISSUE TITLE
Mixed Storage Mode 

### ISSUE THREAD

**Issue by bibinbastian** [MicrosoftDocs/powerbi-docs#555]
https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#limited-to-a-single-source
This portion needs updating, with Mixed Storage Mode multiple sources can be connected along with DirectQuery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#limited-to-a-single-source)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @bibinbastian. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by davidiseminger** [comment]
Adding another assignee to look into this - thanks!

**Comment by alwweb** [comment]
In the following paragraph, I believe the first reference to DirectQuery should be connect live instead. There is no such thing as DirectQuery for SSAS as far as I know.
"If you select import, then you define a query against that external SSAS source, and the data is imported as normal. If you select to connect live, then there is no query defined, and the entire external model is shown in the field list. If you select DirectQuery, as visuals are built, queries are sent to the external SSAS source. However, unlike DirectQuery, there is no sense in which a new model is being created; in other words, it's not possible to define new calculated columns, hierarchies, relationships, and so on. Instead you are simply connecting directly to the external SSAS model.

**Comment by MI77** [comment]
Thanks for the feedback everyone! I've made changes to the articles to make it more accurate. #please-close @mgblythe
