### ISSUE TITLE
A small typo in text

### ISSUE THREAD

**Issue by abhi-debuginside** [MicrosoftDocs/powerbi-docs#556]
There is a small typo in below highlighted sentence under the [Granting access to reports](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo#granting-access-to-reports) section.
> The author publishes the app then installs it. _**TThe**_ author needs to make sure to install the app to have access to the report URL that is used to embed in SharePoint Online.

---
thanks
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thanks, @abhi-debuginside for spotting this.  I noticed it yesterday myself.  This should be corrected by early next week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
