### ISSUE TITLE
Possibility to change the associated Data Lake

### ISSUE THREAD

**Issue by lehmus** [MicrosoftDocs/powerbi-docs#557]
In the CDM & Data Services Tutorial (https://github.com/Azure-Samples/cdm-azure-data-services-integration/blob/master/Tutorial/CDM-Azure-Data-Services-Integration-Tutorial.md), it is said that "the ADLS Gen2 account you associate with your Power BI account cannot be changed later so consider this step carefully if you are doing this with an important Power BI account". I think this very important fact should mentioned in this article as well.

Question: is this a temporary restriction that will be removed in the future (eg. when the products are not in preview anymore)? I would like to test the Dataflow feature with a certain Data Lake, but I might want to change it later to a "production" Data Lake. Since our company has only one Power BI tenant, should I create the production Data Lake now and start using it immediately? This is quite awkward, since I might want to change the properties of the production Data Lake at some point.

Related question: what happens if the associated Data Lake is deleted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @lehmus. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by rahulunlimited** [comment]
We have a similar scenario where we have on PowerBI tenant and would still like to isolate the DEV/TEST/PROD environments.

**Comment by lehmus** [comment]
Hello, any insights on this?

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
