### ISSUE TITLE
Doesnt work when refreshing on personal gateway

### ISSUE THREAD

**Issue by nujcharee** [MicrosoftDocs/powerbi-docs#558]
Hi there
I have downloaded this sample file, all successfully refreshed on desktop but not via personal gateway December 2018 release. I raised this on community forum and also raised a ticket with the product team. I understand it is a bug? Would appreciate alternative solution for the time being please.

Thank you so much :)
Nujcharee

**Comment by mgblythe** [comment]
Thanks @nujcharee, I think support and community are the right channels for this, but what sample are you referring to?

**Comment by nujcharee** [comment]
Hi there, I contacted them and got some correspondence thank you for your reply :)
I got a copy of September 2018 release which seemed to work again so I think I will stick with that version. Many thanks again
