### ISSUE TITLE
Missing Download Link

### ISSUE THREAD

**Issue by Skit-FW** [MicrosoftDocs/powerbi-docs#56]
[Enter feedback here]

In your "How to" tutorial at chapter "Common query Tasks in Power BI Desktop" you forgot to add the download link for the Excel workbook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ca589e-10e9-3924-a3ac-c774368cdec6
* Version Independent ID: 2c7f64d7-8306-1622-6ca3-912b805acf0c
* Content: [Common query tasks in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-common-query-tasks)
* Content Source: [powerbi-docs/desktop-common-query-tasks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-common-query-tasks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Thank you for your comment. This issue has been assigned to the author for review.

**Comment by davidiseminger** [comment]
Hello @Skit-FW - sorry about the inconvenience. I'll look into updating that page with a download link to the file. Thanks for posting!

**Comment by davidiseminger** [comment]
Updated the doc with a download link to the workbook. @Skit-FW thanks again for pointing that out!
