### ISSUE TITLE
Inspection of DataView object in Visual Studio Code

### ISSUE THREAD

**Issue by njolee** [MicrosoftDocs/powerbi-docs#560]
I modified capabilities.json for circleCard to read data from an .xlsx spreadsheet. I basically want to copy a few columns of numbers in my spreadsheet into arrays (the dataView object?) in Power BI and then perform mathematical operations on them (i.e. the dataView object).

I can see all of my data in the table view of Power BI after loading my spreadsheet and Power BI app. I am however only able to see the first row in the variables below. 

dataView.single.value 
dataView.metadata.columns[0].displayName

What does the dataView object contain? How can I inspect different parts of the dataView object?

Visual Studio Code is showing me something that I do not believe is the dataView object (see screen shot below).

![image](https://user-images.githubusercontent.com/9676375/50712394-5796de80-103f-11e9-805d-fd6d2bf860ee.png) 

It is relatively easy to inspect complex objects level by level, in Chrome/Firefox's console view. How can I do the same with Visual Studio Code.

I want to inspect the dataView object, figure out where my spreadsheet data has been stored inside it, so I can then do what I need to do with that data inside Power BI.

Thanks for your help,

J

**Comment by kfile** [comment]
Hi @njolee and thanks for your comment/question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.  Thank you.
