### ISSUE TITLE
Unable to register AdlsFileSystemNotPreparedForAttachException

### ISSUE THREAD

**Issue by sjkp** [MicrosoftDocs/powerbi-docs#562]
After having done all the prerequisites I get the following bad request response when I try to finishing setting up the connection in the PowerBI admin portal. 

I use
Subscription: 
5e343fdd-7565-4568-adc1-251121cbf6b5 
Resource Group:
Delegate.DataLake 
Storage Account:
dgdatalake

{"error":{"code":"AdlsFileSystemNotPreparedForAttachException","pbi.error":{"code":"AdlsFileSystemNotPreparedForAttachException","parameters":{},"details":[]}}}

What does this mean? The storage account does show up in Azure storage explorer as a ADLS Gen2 Preview account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @sjkp, and sorry for the trouble you're having. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. 

Meanwhile, I've assigned this thread to someone who may be able to respond to your issue.

**Comment by sjkp** [comment]
I got it fixed now. Apparently as stated on this thread https://community.powerbi.com/t5/Service/Power-BI-Dataflow-to-Azure-Data-Lake-Gen2-Setup/td-p/583564/highlight/true/page/5 storage explorer 1.61 is buggy and cannot set the permissions correct :/
