### ISSUE TITLE
What is "large"

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/powerbi-docs#563]
In the "Premium capacity nodes" section you write: "Having sufficient memory becomes especially important when dealing with large data models or with a large number of active datasets."
Can you clarify what you mean by "large data models". We have 10 datasets in P1 where the dataset size is between 0.5-1GB and they struggle with constant memory evictions. There seems to be no way to easily or accurately plan what size of node you need based on existing datasets. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [What is Microsoft Power BI Premium? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium#premium-capacity-nodes)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @thommck, and sorry for the ambiguity. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by DavidMagarMS** [comment]
Hi @thommck, 0.5Gb to 1Gb models are by no means considered large. evictions are perfectly normal behaviour and don't indicate anything wrong. capacity planning should be informed by both concurrency requirements of datasets (how often do reports based on these get used, by how many users), dataset size, complexity and refresh requirements. 
is there a specific effect you refer to when you say "we struggle"?

**Comment by thommck** [comment]
The struggle is with all the things you mention!
We know the size of our data models and how many people are expected to interact with the dashboards and reports at certain points in the day.
If Microsoft could provide a tool or even a spreadsheet that helps calculate capacity requirements then it would help immensely

**Comment by mgblythe** [comment]
@thommck - closing this one out, but a few things to consider: if you're not already, use the monitoring app to understand capacity usage, suggest product improvements through https://ideas.powerbi.com/forums/265200-power-bi, and look out for some perf-related content in the next couple of weeks - we'll announce on the blog.
