### ISSUE TITLE
Does this flush all the memory & cpu?

### ISSUE THREAD

**Issue by thommck** [MicrosoftDocs/powerbi-docs#564]
It's not clear from the docs if a restart completely clears out all datasets or just the in-memory version (with a version still in storage). i.e. If I restart the Premium Capacity, will all my reports be blank until the next scheduled refresh, or will they just show out of date data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98ac065d-33c5-2f3b-6cee-36153c2a8afa
* Version Independent ID: 40b95c43-2aca-da1b-9325-709366056f28
* Content: [Restart a Power BI Premium capacity - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-restart)
* Content Source: [powerbi-docs/service-admin-premium-restart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-restart.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @thommck. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

Note that you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by davidiseminger** [comment]
Added author.

**Comment by mgblythe** [comment]
@thommck -- they will just show out of date data.
