### ISSUE TITLE
OneDrive for Business Issue - this process didn't work

### ISSUE THREAD

**Issue by drew5251** [MicrosoftDocs/powerbi-docs#565]
I tried following this documentation and it was very frustrating because I would not get the Access web content screen to show up anymore.  It would just jump right to the error message: Unable to connect.  We encountered an error while trying to connect. Details "Access to the resource is forbidden."
I believe I would get the Access web content screen the first time I tried to connect, but if I connected with the wrong authorization info, it wouldn't show the Access web content screen again.
Luckily I managed to find a workaround.  Just go to the SharePoint or OneDrive library and click the Sync button.  This will allow you to sync the folder to your local computer.  Then go back to Power BI and select Get Data &gt; Excel (instead of Web) and use the URL to the SharePoint / OneDrive library that works on your computer.  
This solved the issue for me.  It would be helpful if the document were updated with this other way of connecting and if the bug were fixed in the application.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1e2f2-6f7a-06ab-77a5-efff8aedabe3
* Version Independent ID: 67d3cd28-51ec-07d9-ed36-840097415f56
* Content: [Use OneDrive for Business links in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-onedrive-business-links)
* Content Source: [powerbi-docs/desktop-use-onedrive-business-links.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-onedrive-business-links.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hello @drew5251, thanks for your comments, and for the workaround! We'll update the steps in that article, so everyone else can benefit from your work, and your contribution here. Thanks!

**Comment by drew5251** [comment]
Thanks. I found out though that it doesn't really work for the service...
once you publish, it can't find the file for refreshes. I'll try to update
my notes tomorrow.

**Comment by drew5251** [comment]
Hi @davidiseminger, I found out that there is a way to clear the setting.  You need to go to Edit Queries > Data source settings.  This was an easy fix to my problem.  But it was really unclear where this data was being saved, and it's a little bid maddening that it was hidden under Edit Queries.  I wouldn't have thought I'd need an Edit Queries option when I couldn't even connect to start a query.

**Comment by davidiseminger** [comment]
Thanks for all your help on this, @drew5251  - we'll get the docs updated to reflect your insights and help.

**Comment by marklovejoy** [comment]
Hello,

this tutorial shows how to get data for Excel files, but what about txt files?

Regards

Mark

**Comment by drew5251** [comment]
Mark,
A web search came up with this: https://docs.microsoft.com/en-us/power-bi/service-get-data-from-files
I'd suggest googling for your reply, or posting a detailed post in the Power BI forum (https://community.powerbi.com/t5/Forums/ct-p/Forums)
Thanks,
Drew
