### ISSUE TITLE
Timeline for read-only Viewer role for new Workspaces?

### ISSUE THREAD

**Issue by sonyadelger** [MicrosoftDocs/powerbi-docs#567]
Is there a time frame regarding the following item?

"Read-only workspaces: Instead of granting users read-only access to a workspace, you'll assign users to a forthcoming Viewer role, which allows similar read-only access to the content in a workspace."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces#known-issues)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hello @sonyadelger ,
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly submit your product question by using the button "Give Product Feedback" at the bottom of the DOCS page.
Kind regards,
Microsoft DOCS International Team
