### ISSUE TITLE
Misunderstanding

### ISSUE THREAD

**Issue by themagiccog** [MicrosoftDocs/powerbi-docs#568]
Hi, I am having trouble understanding this line: "Filter specification will flow from CompanyProject to CompanyEmployee (as shown in the image below) but, it won’t flow up to CompanyEmployee. However, if you set the cross filtering direction to Both it will work. The Both setting allows the filter specification to flow up to Employee." when talking about Both vs Single Cross Filter Direction.

Could you please clarify? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0390b42-0ab0-15fc-29e1-620a0ef9104c
* Version Independent ID: 44197a9d-f275-6959-8cc8-88999b740147
* Content: [Create and manage relationships in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-create-and-manage-relationships)
* Content Source: [powerbi-docs/desktop-create-and-manage-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-create-and-manage-relationships.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hello @themagiccog 
Your contribution is much appreciated. I've assigned this to the author of the article and he will respond soon.
Kind regards,
Microsoft DOCS International Team

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
