### ISSUE TITLE
Data Source Compatibility with Pagniated Reports

### ISSUE THREAD

**Issue by BM4291** [MicrosoftDocs/powerbi-docs#569]
Currently paginated reports can't be hooked up to SharePoint Online data sources; is there any ambition for this in the near future?

Also, is functionality planned to allow access to published data models?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce5d0507-1ff2-46ed-8563-e80b19644f26
* Version Independent ID: 415119ab-1731-b361-10ec-d9ace9802f7d
* Content: [What are paginated reports in Power BI Premium? (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-report-builder-power-bi)
* Content Source: [powerbi-docs/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @BM4291. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.

**Comment by maggiesMSFT** [comment]
Also, @BM4291, I recommend checking the Summary of Planned Features doc for what's planned in upcoming releases. https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features. 
If you don't find an answer there, try searching in https://ideas.powerbi.com/forums/265200-power-bi to see if anyone else has suggested it and it's already in progress. Barring that, you can enter a new item in https://ideas.powerbi.com/forums/265200-power-bi yourself!
