### ISSUE TITLE
How to proceed if Certificate had expired?

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/powerbi-docs#57]
Can you provide information on how to proceed when the certificate had expired?

Also trying to use PBIVIZ --create-cert but it say that create-cert is a unknown option...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Use developer tools to create custom visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/service-custom-visuals-getting-started-with-developer-tools#ssl-setup)
* Content Source: [powerbi-docs/service-custom-visuals-getting-started-with-developer-tools.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-custom-visuals-getting-started-with-developer-tools.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by kfile** [comment]
Thank you for your question. This issue has been assigned to the author for review.

**Comment by markingmyname** [comment]
@sranins Can you please take a look at this?

**Comment by ignatvilesov** [comment]
Hi @djpirra,

What version of pbiviz do you use? (pbiviz --version)

If it lower than 1.11.1 we would recommend to install the latest version to use `--create-cert` command to generate a new valid certificate. You can install the latest version by using this command:
```bash
npm install powerbi-visuals-tools@latest -g
```
