### ISSUE TITLE
Is this supposed to work for the Power BI Service?

### ISSUE THREAD

**Issue by gsacavdm** [MicrosoftDocs/powerbi-docs#571]
Show items with no data works just fine on Power BI Desktop however when I publish the report, the rows with those "no data" columns don't show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52f1d303-a1ee-766e-dac0-d68dad08080c
* Version Independent ID: 053d3adb-90c2-03ce-87c7-47d441a1a79e
* Content: [Show items with no data in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-show-items-no-data)
* Content Source: [powerbi-docs/desktop-show-items-no-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-show-items-no-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @gsacavdm. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com

**Comment by gsacavdm** [comment]
Hmmm this is also documentation feedback if you rephrase it as:
"Can you please document whether this works or not on the Power BI Service?"

This is done in the [Power BI Desktop Privacy Levels](https://docs.microsoft.com/en-us/power-bi/desktop-privacy-levels) documentation which has the following blurb:

> Caution: The Ignore the Privacy levels and potentially improve performance does not work in the Power BI service. As such, Power BI Desktop reports with this setting enabled, which are then published to the Power BI service, do not reflect this behavior when used in the service.

Based on [this](https://community.powerbi.com/t5/Issues/quot-Show-Items-with-no-data-quot-option-not-working-in-Online/idi-p/347827) thread in the community forum, sounds like it's not and that should be documented here.

**Comment by mgblythe** [comment]
Thanks @gsacavdm - I took your initial post to mean that it was supported but just not working. Assigning to a writer to review.

**Comment by davidiseminger** [comment]
Adding another assignee to help sort this out. Thanks!

**Comment by MI77** [comment]
No longer relevant - Desktop and Service were out of parity for a couple of weeks in Jan/Feb but the Feb release of Desktop fixed this.

**Comment by MI77** [comment]
#please-close @mgblythe
