### ISSUE TITLE
Invalid ReportId Values

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#572]
I am able to query the audit log but in some cases I am getting two ReportId values for the same report in the same workspace.  I ruled out that the report was deleted and created again as the ReportId values are intermixed in time.   Also, I am getting workspace names that don't exist (or ever existed).  Any clues?  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Using auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks @maggiesMSFT. @asocorro - I'm not sure what would cause this, so I would follow Maggie's suggestion to try community or support.
