### ISSUE TITLE
GA date for this feature?

### ISSUE THREAD

**Issue by yzhong94** [MicrosoftDocs/powerbi-docs#574]
When can we expect this feature to GA?  I'm using this on PowerBI desktop and would like to publish it as a dashboard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 477d54a5-8a27-ae63-9887-9801639962e8
* Version Independent ID: 8a2c56c0-cf25-bd2d-8de9-207ccc1e83d1
* Content: [Many-to-many relationships in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-many-to-many-relationships)
* Content Source: [powerbi-docs/desktop-many-to-many-relationships.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-many-to-many-relationships.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your question, @yzhong94  I recommend checking the Summary of Planned Features doc for what's planned in upcoming releases. https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/planned-features.

**Comment by yzhong94** [comment]
I cannot find many-to-many relatinoships or composite model in that table. @maggiesMSFT
