### ISSUE TITLE
Does PowerBI and Azure egress apply for gateway scenarios?

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#575]
This document is missing explicit mention of following aspects
-&gt; Does egress charges apply in context of gateway taking care of pulling data from azure and pumping to powerbi
-&gt; What does the charges of egress look like.. any link is much appreciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0577c02-6c3e-870c-ddee-d93cafef9206
* Version Independent ID: b9c65245-32e4-8bc9-8971-e76bff0ad837
* Content: [Power BI and Azure egress - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-egress-power-bi)
* Content Source: [powerbi-docs/service-azure-egress-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-egress-power-bi.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mganeshphani** [comment]
@maggiesMSFT I am suggesting to update the documentation with the information I asked here.. that is how the azure docs work.. are PowerBI docs having their own rules?

**Comment by maggiesMSFT** [comment]
Hi, @mganeshphani -- It'll be great to update the docs when we get the answers. I was just suggesting that if you need the info quicker than the author can provide it, you can try those other sources.
thanks!

**Comment by davidiseminger** [comment]
Adding assignees to help clarify - thanks for your comments and questions.

**Comment by mgblythe** [comment]
@arthiriyer - can you comment on this one, and let me know if we need a doc update.

**Comment by arthiriyer** [comment]
Gateway by itself doesn't have any additional charges.  I don't think we need doc updates here.
