### ISSUE TITLE
Firefox Not the Best

### ISSUE THREAD

**Issue by apfenech** [MicrosoftDocs/powerbi-docs#577]
Firefox is technically supported, but has issues with styling and can remove some features of visuals - it's probably worth mentioning.  See here:
https://community.powerbi.com/t5/Desktop/Fonts-changed-in-Firefox-compared-to-IE-and-Desktop/td-p/567953

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 753770c6-5424-85a6-1bd7-963e2c1c7e64
* Version Independent ID: 09a4403f-9fbd-535a-4b45-83e89f380ba0
* Content: [Supported browsers for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-browsers)
* Content Source: [powerbi-docs/consumer/end-user-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-browsers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @apfenech -- I've assigned this issue to the author, who'll get back to you soon. Thanks!

**Comment by mihart** [comment]
Hi @apfenech ,
I've updated the document with this information.  Thank you so much for letting me know.
