### ISSUE TITLE
Gateway troublingshooting link /fwlink/?LinkId=627089 doesn't find content 404

### ISSUE THREAD

**Issue by darthwalsh** [MicrosoftDocs/powerbi-docs#579]
I hit an error updating the On-premises data gateway, and on the error dialog there is a link https://go.microsoft.com/fwlink/?LinkId=627089 that forwards to https://powerbi.microsoft.com/en-us/documentation/powerbi-gateway-enterprise-tshoot/ which throws a 404 error because the content doesn't exist.

I think the FWLink should point to https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-tshoot, based on [this forum thread about the same 404 issue](https://community.powerbi.com/t5/Service/Troubleshoot-connection-problems-link-not-working/td-p/339407).

**Comment by davidiseminger** [comment]
Thanks for your comment, @darthwalsh. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks @darthwalsh - I added a redirect from the old article, and we'll update the FWLink also.
