### ISSUE TITLE
Efficient and improving every day

### ISSUE THREAD

**Issue by rjb7607** [MicrosoftDocs/powerbi-docs#58]
The tooltip function really helps us include much more information on a visual. Clients generally want to see different versions of the same data, and this functionality is increasingly useful. We love the new tooltip visualization functionality that came out recently! We wrote a blog about it if anyone is interested! 

https://www.rhobear.com/single-post/2018/07/02/Power-BI-201---How-to-customize-Tooltips

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfbc531-11a6-2543-6c99-d38128af21e4
* Version Independent ID: d7dd98cd-d0f9-5738-677d-41fd64804f16
* Content: [Customizing tooltips in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-custom-tooltips)
* Content Source: [powerbi-docs/desktop-custom-tooltips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-custom-tooltips.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Glad to hear that @rjb7607 - thank you!
