### ISSUE TITLE
Only one Live Connection is supported per model

### ISSUE THREAD

**Issue by buildbod** [MicrosoftDocs/powerbi-docs#580]
Missing from the limitations and considerations is that once you have added a Live Connection you cannot add in other datasources nor can you have multiple Live Connections in the same PBIX file. It is limited to one connection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @buildbod . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Adding assignees to help clarify - thanks!

**Comment by MI77** [comment]
Thanks for the feedback! I've made the change. #please-close @mgblythe
