### ISSUE TITLE
SharePoint: Request failed: Unable to connect to the remote server

### ISSUE THREAD

**Issue by adaltons** [MicrosoftDocs/powerbi-docs#581]
Hi All,
 
I am getting this same error message after connecting my datasources to the On-premise Gateway for other sources in the report.
 
The SharePoint datasource is giving me the error "SharePoint: Request failed: Unable to connect to the remote server" when I initialize a refresh from the Power BI service or when i schedule a refresh through the Gateway.
 
If i initialize a refresh through the Power BI Desktop, it works perfectly fine.
 
Also it does not complain about the file that I am loading but complains about the another table where I am merging the SharePoint file with another file 
All the steps mentioned in this document has been performed and still the same error message.
 
Please if you can help.
 
Thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 183a8242-3c94-8a80-6d36-85c608790a25
* Version Independent ID: 2d8728c3-3662-27a3-6cd4-2c88b08f7847
* Content: [Merge or append on-premises and cloud data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-mashup-on-premises-cloud)
* Content Source: [powerbi-docs/service-gateway-mashup-on-premises-cloud.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-mashup-on-premises-cloud.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @adaltons. Sorry to hear it!  This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
