### ISSUE TITLE
Power BI premium 

### ISSUE THREAD

**Issue by annaye2010** [MicrosoftDocs/powerbi-docs#582]
I am really interested to know if the Power BI premium license is available in the G cloud?  If not, when will it be available?  We love Power BI but it really does not make a lot of sense to buy G5 license for every employee in the government. This is preventing  the cool Power BI tool from growing inside government. The power Bi premium seems to be a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d017bc96-49d4-7b63-9394-1739cdf7528d
* Version Independent ID: 1e70d724-121d-feea-471e-307c2f27dd24
* Content: [Power BI for United States Government customers - Overview - Power BI](https://docs.microsoft.com/en-us/power-bi/service-govus-overview)
* Content Source: [powerbi-docs/service-govus-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-govus-overview.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @annaye2010 -- thanks for your question! I've forwarded your feedback to the writer, who should respond soon. In the meantime, you can also check the Power BI Community, found at https://community.powerbi.com, or go to https://support.powerbi.com.

**Comment by annaye2010** [comment]
Hi Maggie:
Thank you for your response.
I have found the answer on another post at Microsoft website:
https://blogs.msdn.microsoft.com/azuregov/2017/09/28/power-bi-premium-generally-available-for-u-s-government-users/
Power BI Premium generally available for U.S. government users – Microsoft Azure Government - blogs.msdn.microsoft.com<https://blogs.msdn.microsoft.com/azuregov/2017/09/28/power-bi-premium-generally-available-for-u-s-government-users/>
With more than 20 compliance offerings, Power BI delivers an end-to-end business intelligence solution while helping organizations comply with national, regional and industry-specific requirements. Today, we are pleased to build on this legacy by announcing Power BI Premium will be generally available for both the U.S. Government Community Cloud (GCC) and U.S. Department of Defense...
blogs.msdn.microsoft.com


"Today, we are pleased to build on this legacy by announcing Power BI Premium<https://powerbi.microsoft.com/en-us/power-bi-premium/> will be generally available for both the U.S. Government Community Cloud (GCC) and U.S. Department of Defense (DOD) users beginning Oct. 1."

But it will be nice to get the confirmation from the author.   If possible, I would also like to get an answer for another question I have : Does G cloud premium work the same way as E cloud premium when it comes to the license. In another words, if G cloud purchases the premium, users do not need G5 licenses to view the report if the report is published at the premium service. Is this true?

The G5 license has been preventing Power BI platform well adopted by the government clients and I hope this Power BI premium will be the answer for it.

Thanks
Anna
________________________________

**Comment by mgblythe** [comment]
Thanks @annaye2010, @Minewiskan as FYI.
