### ISSUE TITLE
What role / privilege do you need to install the app?

### ISSUE THREAD

**Issue by gtageek** [MicrosoftDocs/powerbi-docs#583]
Hello - What role do you need to install the Power BI Premium Capacity Metrics app?
Do you need to be a Global Admin or Power BI Pro Admin or is it sufficient to only be a Premium Capacity Admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities in your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @gtageek -- thanks for your question! I've forwarded your feedback to the writer, who should respond soon. In the meantime, you can also check the Power BI Community, found at https://community.powerbi.com, or go to https://support.powerbi.com.

**Comment by mgblythe** [comment]
Hi @gtageek - capacity admin perms are sufficient.
