### ISSUE TITLE
How to specify role

### ISSUE THREAD

**Issue by BenWarden** [MicrosoftDocs/powerbi-docs#584]
Is there any way to specify the snowflake user role to use? We're having issues with sharing cross functional reports due to PowerBI only showing whatever is visible to their default role regardless of whether they have permission to use a cross functional db role for reporting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35e91b2c-b946-0945-4ef5-6451a1833b5f
* Version Independent ID: 730bf023-2cab-5db2-c1fd-d96e8bac4e02
* Content: [Connect to Snowflake computing warehouse in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-snowflake)
* Content Source: [powerbi-docs/desktop-connect-snowflake.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-snowflake.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @BenWarden -- thanks for your question.! I've forwarded your feedback to the writer, who should respond soon. In the meantime, you can also check the Power BI Community, found at https://community.powerbi.com, or go to https://support.powerbi.com.

**Comment by BenWarden** [comment]
thanks @maggiesMSFT ! I did check there, I also looked for documentation for the Snowflake.Databases function to see if I can pass role as a parameter in the advanced editor. I would expect the documentation to be here: https://docs.microsoft.com/en-us/powerquery-m/accessing-data-functions
but I haven't been able to find any documentation for what options are permitted in the third argument of the connector function (eg: `Snowflake.Databases("aa12345.snowflakecomputing.com", "MY_WAREHOUSE", [])`

**Comment by BenWarden** [comment]
just trying `role="my_role"` inside the array as a swag didn't work

**Comment by tcpaddock** [comment]
We also need this capability. I tried the following step in Advanced Editor with no luck:
`Role = Source{[Name=<Role Name>,Kind="Role"]}[Data],`

**Comment by tcpaddock** [comment]
Microsoft Support says Role is not supported. I've submitted a request to add here: [https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/36665524-add-support-for-role-in-snowflake-connector](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/36665524-add-support-for-role-in-snowflake-connector)

**Comment by davidiseminger** [comment]
Sounds like you've added a request to support, so we'll close this. Thanks for adding the links, so others who come across this can follow your path to a resolution. Thanks!

**Comment by jjjain** [comment]
Snowflake connection string doesn't  have option to specify additional parameters. Since all our traffic outside is encrypted, we need to specify a CABundleFile in connection string. There is no way to specify this in Snowflake connector in Power BI

**Comment by vajnorcan** [comment]
so I take it this fundamental connection string property is still not supported in PowerBI Snowflake connector?
