### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rubeshd** [MicrosoftDocs/powerbi-docs#586]
Hi,
There is a typo in the doc powerbi-docs/powerbi-docs/report-server/migrate-report-server.md @ section "Migrateing from one Power BI Report Server to another".
Migrateing => Migrating
Regards,
Rubesh

**Comment by davidiseminger** [comment]
Thanks for your comment and close read, @rubeshd. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @rubeshd. Good catch! Fixing these now.

**Comment by markingmyname** [comment]
@rubeshd This is now corrected.  Thank you again for bringing this to our attention.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
