### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rubeshd** [MicrosoftDocs/powerbi-docs#587]
Hi,
There is a typo for this doc:
powerbi-docs/powerbi-docs/report-server/migrate-report-server.md
@Migrating from one Power BI Reprot Server is the same process as migrating from SSRS (Native-mode)
Regards,
Rubesh

**Comment by davidiseminger** [comment]
Thanks for your comment and close read, @rubeshd. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Thanks, @rubeshd -- good catch. Fixing this now.

**Comment by markingmyname** [comment]
@rubeshd This is now corrected. Thank you again for bringing this to our attention.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
