### ISSUE TITLE
direct query runs a query for each visual

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/powerbi-docs#589]
The above article does not explicitly state that there will be one query for every single visualization, even if the fields are coming from the same query. So your query might be : 

SELECT student-id, forename, surname, address, gender, ethnicity, nationality, etc... from dimStudent join factTutortutee... where employeeID  = currentuser()

And then you use a synced slicer to choose a student and display the fields, e.g. gender in one visual and nationality in another, so PBI then runs two more queries, one for each visual

SELECT min(gender) from 
(SELECT student-id, forename, surname, address, gender, ethnicity, nationality, etc... from dimStudent join factTutortutee... where employeeID  = currentuser()
) where student-id = 123456

SELECT min(nationality) from 
(SELECT student-id, forename, surname, address, gender, ethnicity, nationality, etc... from dimStudent join factTutortutee... where employeeID  = currentuser()
) where student-id = 123456

This article explains the issue nicely

http://radacad.com/directquery-connection-in-power-bi-how-does-it-work-limitations-and-advantages

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#directquery-in-the-power-bi-service)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment, @ChipDale66 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
We added clarification to that article about how DirectQuery operates. Thanks for your feedback!
