### ISSUE TITLE
Properties at .config files for PowerBI Gateway

### ISSUE THREAD

**Issue by elelement** [MicrosoftDocs/powerbi-docs#590]
Hi,

I've been trying to figure out how to get a complete list of properties that can be configured in the gateway config files, located at:
`C:\Program Files\On-premises data gateway`

Looking at the gateway logs, I can see some of them, but not all are clear enough to me:
```
0000-0000-000000000000  900561DA [DM.GatewayCore] Creating GatewayTransferServiceHost 
against 'sb://wabi-north-europe-relay40.servicebus.windows.net/ddd8a9a0-6fd7-49c2-92bf-b5632855ec93/' 
with following binding configuration: 
```

```json
{"ReliableSession":{"Enabled":false,"Ordered":true,
"InactivityTimeout":"00:10:00"},"HostNameComparisonMode":0,
"ConnectionMode":0,"TransferMode":0,"MaxBufferPoolSize":8500000,
"MaxBufferSize":8500000,"MaxConnections":1500,"ListenBacklog":10,
"IsDynamic":false,"MaxReceivedMessageSize":8500000,
"ReaderQuotas":{"MaxStringContentLength":8192,"MaxArrayLength":16384,
"MaxBytesPerRead":4096,"MaxDepth":32,"MaxNameTableCharCount":16384,
"ModifiedQuotas":0},"Scheme":"sb","EnvelopeVersion":
{"NextDestinationActorValue":
"http://www.w3.org/2003/05/soap-envelope/role/next"},
"Security":{"Mode":1,"RelayClientAuthenticationType":0,"Transport":
{"ProtectionLevel":2},"Message":{"ClientCredentialType":1,
"AlgorithmSuite":"Default"}},"CloseTimeout":"00:01:00",
"Name":"GatewayServiceBusTransferBinding","OpenTimeout":"00:01:00",
"ReceiveTimeout":"06:00:00","MessageVersion":"Default",
"SendTimeout":"00:01:00"}
```

I can't find any file in the docs talking about this and where and how to set up these properties. What do they mean? Would it be possible to add a link to a more detailed documentation?

Thank you very much for the clarification.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
