### ISSUE TITLE
Loved the options

### ISSUE THREAD

**Issue by MTwem** [MicrosoftDocs/powerbi-docs#591]
Really appreciated having video alongside text so I can choose which one I want to use. i.e. I prefer video but when I've lost my headphones the text is better for a quiet office

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c7a5b0-75bd-3ba7-1fac-7557b790d511
* Version Independent ID: b89aefeb-6cc8-4874-e514-7a1428611c8c
* Content: [Getting data - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingdata?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/gettingdata.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingdata.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Great! Thanks for taking the time to comment @MTwem - much appreciated. Glad you liked the video!
