### ISSUE TITLE
Clarification on external user scenarios

### ISSUE THREAD

**Issue by t-val** [MicrosoftDocs/powerbi-docs#593]
Can you please provide clarification on whether it is possible to use Analyze in Excel with external (Azure AD B2B) users?  In my experience, you cannot get past the Forbidden message even if the external user has a Power BI Pro license.  Perhaps the issue is that the user is being redirected to the /common AAD login endpoint instead of the tenant specific one?  Since a datasest only lives in a single known tenant, why is the user not forced to authenticate and get an access token from that tenant which owns the dataset?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.

**Comment by t-val** [comment]
Ok, then my feedback is the documentation is insufficient/incomplete because it does not discuss whether the feature is available to external users.
