### ISSUE TITLE
does dual storage mode work in Power BI Service?

### ISSUE THREAD

**Issue by ChipDale66** [MicrosoftDocs/powerbi-docs#594]
This article is about Power BI Desktop Client. I want to know if dual storage mode works in Power BI Service.

thanks
Andrew

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d807f76-0284-c917-4e56-b5c897c9ed61
* Version Independent ID: e837a12c-fa26-ea56-cfb3-46ac87a1843c
* Content: [Use storage mode in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-gb/power-bi/desktop-storage-mode)
* Content Source: [powerbi-docs/desktop-storage-mode.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-storage-mode.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @ChipDale66. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by davidiseminger** [comment]
Adding an assignee to help clarify.

**Comment by sgoley** [comment]
@ChipDale66 

According to this section of the documentation: 

[Using Composite Models](https://docs.microsoft.com/en-us/power-bi/desktop-composite-models#using-composite-models)

This was a published feature as of Oct 2018, however the rollout did have a few issues:

[Publishing Composite Model](https://community.powerbi.com/t5/Desktop/Publishing-Composite-Model/td-p/482858)

That said, I haven't seen anywhere in the official documentation which specifies the refresh schedule of "dual" storage.

**Comment by christianwade** [comment]
Yes, it works in the Power BI service, as do the other settings

**Comment by mgblythe** [comment]
Thanks @christianwade, assigning to @davidiseminger to address in the docs.

**Comment by davidiseminger** [comment]
Both documents have been updated with a note explaining availability in the Power BI service, and will appear online in the next 24 hours. Thanks!
