### ISSUE TITLE
Missing semi-colon in code for step 10

### ISSUE THREAD

**Issue by ian-barker** [MicrosoftDocs/powerbi-docs#595]
The code in step 10 that you can copy is missing the semi-colon on the max circleThickness which will mean the visual doesn't work when starting the visual in powershell. 
Note that in the screenshot, it looks ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f573b62f-4028-ce65-b5ae-a4115ee1bcd1
* Version Independent ID: 1cedde6a-9245-42da-c25e-83706f551c79
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for catching that issue, @ian-barker! We’ve forwarded it to the writer, who should respond shortly.

For future reference - you can also edit articles directly. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer, who will sign off and get it published. Thanks again!

**Comment by markingmyname** [comment]
Good eye, @ian-barker! 

Also, did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

For this instance, you should see the article updated early next week.

Thanks again!
