### ISSUE TITLE
Issue with PowerBI Report Server Template in Portal

### ISSUE THREAD

**Issue by MicahMcKittrick-MSFT** [MicrosoftDocs/powerbi-docs#6]
See the following MSDN post for more information: 

https://social.msdn.microsoft.com/Forums/azure/en-US/ec008145-f419-49a7-870c-e8e8d6a83465/azure-vm-template-power-bi-report-server-not-allowing-hyphendash-in-vm-name?forum=WAVirtualMachinesforWindows&prof=required

When deploying the template it brings you to the following doc for release notes: 
https://docs.microsoft.com/en-us/power-bi/report-server/release-notes

However the comment section has not yet been converted to GitHut hence I am posting it here. 

The tooltip in the PowerBI Report Server Template says it allows dashes to be used in the name. However after testing we have found this to not be true. Is this by design? If so, we should update the tooltip. Else, if it is not, we should get the template fixed.  Please feel free to put me into contact with the right person so we can work together to get this resolved.

**Comment by MicahMcKittrick-MSFT** [comment]
@maggiesMSFT could you look into this? You appear to be the content author for the related doc.

**Comment by maggiesMSFT** [comment]
Thanks @MicahMcKittrick-MSFT.
Hey @jtarquino @lishibo @rvpatkar -- can any of you advise? Where should we put this info? This is feedback from  Scott Staffer in the Forums: https://social.msdn.microsoft.com/Forums/azure/en-US/ec008145-f419-49a7-870c-e8e8d6a83465/azure-vm-template-power-bi-report-server-not-allowing-hyphendash-in-vm-name?forum=WAVirtualMachinesforWindows&prof=required

**Comment by maggiesMSFT** [comment]
Hi, @MicahMcKittrick-MSFT -- you're right, create the PBI RS VM in Azure, you can't use dashes in the VM name, even though the tooltip says you can. I've assigned this to @jtarquino and asked if they can either a) fix it so you can use dashes or b) fix the tooltip.
thanks!

**Comment by maggiesMSFT** [comment]
Oh, I also replied to Scott Stauffer on twitter.

**Comment by MicahMcKittrick-MSFT** [comment]
@maggiesMSFT great thank you!
