### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by Cobalt34** [MicrosoftDocs/powerbi-docs#60]
All this training is like the product itself: Clear and friendly.
After just few days, it looks like you can do so many thing on power BI.
Online documentation is also perfect.

Congratulation to the Power BI team for such a great work !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcb9bc55-ac56-d1ab-c465-4e41bfa8f152
* Version Independent ID: 44bd9bb3-5aad-31ac-27b6-53e3c0554960
* Content: [Introduction to DAX - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/introductiontodax?tutorial-step=7)
* Content Source: [powerbi-docs/guided-learning/introductiontodax.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/introductiontodax.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Thank you very much for the positive feedback. We work hard to ensure that we provide quality experiences for our customers - good to know we're making progress.

**Comment by mgblythe** [comment]
Thanks @Cobalt34, we appreciate the feedback.
