### ISSUE TITLE
New Workspaces do not provide Usage Metrics

### ISSUE THREAD

**Issue by KMac0615** [MicrosoftDocs/powerbi-docs#602]
Being able to pull usage metrics for reports is no longer an option with the new workspaces as a SharePoint site is not automatically created anymore. What can I do to enable this feature again? I have to be able to pull usage metrics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @KMac0615 -- thanks for asking. Usage metrics are coming to the new workspaces. I don't have an exact date to share with you. Thanks --

**Comment by 2materazzi3** [comment]
Hi maggiesMSFT, your comment is 2 months old - anything new regarding this feature? 
I used it a lot.

**Comment by mparowski** [comment]
I certainly hope that usage metrics will be incorporated before forced migration out of classic workspaces.
