### ISSUE TITLE
API(Datasets - Get Gateway Datasources In Group) not working

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#605]
Hello,

Following API always returns 404 
GET https://api.powerbi.com/v1.0/myorg/groups/{groupId}/datasets/{datasetKey}/Default.GetBoundGatewayDatasources

If this is not right place to check.. please tell me the GitHub location I can log this issue on

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba56089-7634-454b-aeec-cbe6c7d4deb8
* Version Independent ID: c092a3d5-20f2-ac15-be3d-1387559e8b33
* Content: [Power BI REST API Reference - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/rest-api-reference)
* Content Source: [powerbi-docs/developer/rest-api-reference.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/rest-api-reference.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @mganeshphani -- I'm assigning to the author, who may have a suggestion.  This does look like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by markingmyname** [comment]
Thanks for your comment, @mganeshphani.  This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
