### ISSUE TITLE
Service Principal login for PowerBI API

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#606]
Hello,

I am very desperate about to make this work for admin scenarios in our organization... can someone provide an update on this issue
https://github.com/Microsoft/powerbi-powershell/issues/51

Looks like no one is committing on timeline when this would be released

-Ganesh M.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eba56089-7634-454b-aeec-cbe6c7d4deb8
* Version Independent ID: c092a3d5-20f2-ac15-be3d-1387559e8b33
* Content: [Power BI REST API Reference - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/rest-api-reference)
* Content Source: [powerbi-docs/developer/rest-api-reference.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/rest-api-reference.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @mganeshphani -- I'm assigning this to the author, but I see you're in contact with @CodeCyclone on another GitHub issue, https://github.com/Microsoft/powerbi-powershell/issues/51. I hope they can help you resolve it!

**Comment by mganeshphani** [comment]
@maggiesMSFT I am not in contact with codecyclone.. looks like the docs api referenced this automatically..  if I can get a answer from powerbi PG soon on the timeline of this implementation that would be helpful

**Comment by markingmyname** [comment]
@mganeshphani We are working on this exact issue.  There is another update planned for this topic sometime in the next month or two.  No exact date is known yet.  I apologize I do not have a more direct answer, but we are still discussing this topic.

**Comment by markingmyname** [comment]
@mganeshphani I will update this particular issue, but not the other one.  Please reach out to the Power BI Community, found at https://community.powerbi.com to see if there is a beta testing sample that can be shared. If not, you can get support by going to https://support.powerbi.com.

**Comment by markingmyname** [comment]
@mganeshphani Please look over article - https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal - for further details on using service principal with Power BI.

Thank you again for your feedback.
