### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by JeroenTournierSubotic** [MicrosoftDocs/powerbi-docs#608]
You can download Power BI Desktop direclty, or you can get it from the Microsoft Store.

should be "directly"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7499eea2-bb50-3b31-530a-fd92911f1f92
* Version Independent ID: 8eecfe46-e9bc-c78a-077f-1d048ef22a28
* Content: [Quickstart Connect to data - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quickstart-connect-to-data#feedback)
* Content Source: [powerbi-docs/desktop-quickstart-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quickstart-connect-to-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
Good eye, @JeroenTournierSubotic! We’ve forwarded it to the writer, who should respond soon. Thanks!

And @JeroenTournierSubotic, did you know: For minor things like typos, you yourself can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by markingmyname** [comment]
@JeroenTournierSubotic Again, thank you for bringing this to our attention. The update should be live in a few days.  Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
