### ISSUE TITLE
Incredibly unoptimized preview data load for Azure Consumption Insights

### ISSUE THREAD

**Issue by herrbpl** [MicrosoftDocs/powerbi-docs#609]
Azure Consumption Insights data preview is incredibly inefficient. For each step taken in query editor, PowerBI proceeds to download nealry 100MB of data. If you have query of any complexity, you download tens of gigabytes of data while moving at snail pace with development. 

It make take hours to complete your query because of this VERY INFURIATING issue. 

Can there be any kind of caching for this data source? Any sort of optimization? Setting months count in parameters helps nothing. 

Thanks,

Siim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data (Beta) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
Thanks for your comment, @herrbpl.

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log in through this channel.

We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
