### ISSUE TITLE
Using iOS as main access?

### ISSUE THREAD

**Issue by CarlMagnusC** [MicrosoftDocs/powerbi-docs#61]
We are using PowerBI and some reports are shared with me as email attachments. 
It would be great to have guidance on How to use those if all you have is the mobile app?
I use a Mac Laptop and have not Found the Power BI sw for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf174abf-6474-14ae-3183-31e40fa9b1b6
* Version Independent ID: ca82ad59-c057-fccd-b6e0-627df4326c62
* Content: [Explore reports in the Power BI mobile apps - Power BI](https://docs.microsoft.com/en-us/power-bi/mobile-reports-in-the-mobile-apps#open-a-power-bi-report-in-the-mobile-app)
* Content Source: [powerbi-docs/mobile-reports-in-the-mobile-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/mobile-reports-in-the-mobile-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Thank you for your question. This issue has been assigned to the author for review.

**Comment by maggiesMSFT** [comment]
Hi, @CarlMagnusC -- thanks for your question! If I understand correctly, you've received a Power BI report, a PBIX file, via email. Right? And you have the Power BI mobile app for iOS? Or you're trying to view it on the Mac? 
Either way, you and the person who created it need Power BI Pro licenses, and the creator needs to publish it to the Power BI service on the web. Then you can view it in a browser on the Mac or in the Power BI mobile app for your iOS device. 
Does that answer your question? 
Thanks again!

**Comment by CarlMagnusC** [comment]
However, my college that uses a PC can be Viewed with the trial licence... and We are evaluating it together.

Br, Carl-Magnus


Sent from my iPhone

On 20 Jul 2018, at 3.36, Maggie Sparkman <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #61<https://github.com/MicrosoftDocs/powerbi-docs/issues/61>.
