### ISSUE TITLE
cached settings

### ISSUE THREAD

**Issue by aaronboock** [MicrosoftDocs/powerbi-docs#610]
I incorrectly selected oAuth for the authentication method.  The installation failed.  Whenever I retry the installation, I am not able to select authentication method.  It appears my selection is cached in a way I am unable to clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe108af-9a54-8fc1-ff18-7b9d141576eb
* Version Independent ID: 5ee0a5fc-b99f-4624-1c76-f924c4a2a80e
* Content: [Connect to Azure Search with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-search)
* Content Source: [powerbi-docs/service-connect-to-azure-search.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-search.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by markingmyname** [comment]
@aaronboock Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

Thanks for your comment, @mortenf. I don't believe that requirement has changed, but we’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
Thanks for your comment, @aaronboock. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
