### ISSUE TITLE
Using standard HANA CDS views in Power BI

### ISSUE THREAD

**Issue by tomaskutac** [MicrosoftDocs/powerbi-docs#611]
Hello, I am able to connect standard CDS views from SAP HANA database but it always return only empty table. I identified that it is because these CDS views are taking client ID from connection session. In SAP you provide client id when you are connecting to SAP. Is there any way how to specify client id for connection session so this views will work? This text in CDS view identify client handling: @ClientHandling.algorithm: #SESSION_VARIABLE Thank you for help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea414a5c-c3ca-281e-46ca-3e677d27924b
* Version Independent ID: 363a9c9c-13e2-58ce-cb79-9f897d83c307
* Content: [Use SAP HANA in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-hana)
* Content Source: [powerbi-docs/desktop-sap-hana.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-hana.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@tomaskutac Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

Thanks for your comment, @mortenf. I don't believe that requirement has changed, but we’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by davidiseminger** [comment]
Thanks for your comment, @tomaskutac. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
