### ISSUE TITLE
Columns added during Power Query Mash-up

### ISSUE THREAD

**Issue by pottie08** [MicrosoftDocs/powerbi-docs#612]
While working with my PDF imported data I have found that "non-existent" columns are added while removing other columns. These columns are then referenced later when doing for example a columns re-order. For example: Columns 1 to 20 are loaded from a PDF import. When removing columns 7 to 13, a new column, column 21 is added at the end (which didn't exist in the original import). When reordering columns, column 21 is referenced in the m code which results in an error "column 21 wasn't found in the table" when applying close and load. I also saw data being moved from column 15 to column 16 after removing columns. Maybe someone else has also experienced a similar problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6ab70d2-6a8d-9457-9fe0-b7e5a11f7a23
* Version Independent ID: 8d847641-59f8-8914-799d-0c1c7ccad9a6
* Content: [Connect to a PDF file in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-pdf)
* Content Source: [powerbi-docs/desktop-connect-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-pdf.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
Thanks for your comment, @pottie08. Looks like this is product feedback, rather than documentation feedback – you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com. Please keep in mind this is still a preview feature.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pottie08** [comment]
Thank you Mark. Noted. Prinsloo
