### ISSUE TITLE
Y-Axis title

### ISSUE THREAD

**Issue by devudu** [MicrosoftDocs/powerbi-docs#613]
I did not find any option to set the Y-Axis Title anywhere.  By default it is empty and I don't see any property to set this in any of the tabs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b02cab33-595c-5e4f-0f93-5a129198be4d
* Version Independent ID: 8e8609ea-6858-5b34-cb19-f8de8a0420e3
* Content: [Use ribbon charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-ribbon-charts#feedback)
* Content Source: [powerbi-docs/visuals/desktop-ribbon-charts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-ribbon-charts.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@devudu  Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mihart** [comment]
Hi @devudu ,
I am not able to add a Y axis title either.  I was able to add data labels, which helps.  
Since this seems to be a product issue (not a docs issue), please post this on the community forum:
community.powerbi.com.  
Thanks,
The international DOCS team
