### ISSUE TITLE
Access Token via pure JS

### ISSUE THREAD

**Issue by cfharp** [MicrosoftDocs/powerbi-docs#614]
As the title suggests, any recommendations on obtaining the access token via pure JS? I have a project where I'm working without real access to the backend. I could build another web service to retrieve an access token, but if there's a pure JS method to already do the same I would rather go with that. Any ideas?

**Comment by markingmyname** [comment]
@cfharp I apologize for the delayed response.

Please visit - https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#load-an-item-using-javascript - for information.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
