### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by LinkOps** [MicrosoftDocs/powerbi-docs#617]
4. Past the report URL into the property pane. This report URL is the URL you copied from the steps above. The report loads automatically.

Should read

4. Paste the report URL into the property pane. This report URL is the URL you copied from the steps above. The report loads automatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Hi @LinkOps ,
Good eye!  Thank you for passing this along.  The article author will fix this asap. 
Take care,
The Power BI DOCS team

**Comment by markingmyname** [comment]
Good eye, @LinkOps.

Also, did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

For this instance, you should see the article updated early next week.

Thanks again!
