### ISSUE TITLE
There is no option to specify tenant ID in a multitenant environment

### ISSUE THREAD

**Issue by jvincke** [MicrosoftDocs/powerbi-docs#619]
There is no option to specify tenant ID in a multitenant environment. Adding ?tenant=sometenantid to the URL does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd3eb8d-0f4f-e8cd-7ed3-5ceccc433ddd
* Version Independent ID: 2164905a-fae3-c9e8-a62f-08d9b7ac95de
* Content: [Connect to Microsoft Dynamics NAV with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-microsoft-dynamics-nav)
* Content Source: [powerbi-docs/service-connect-to-microsoft-dynamics-nav.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-microsoft-dynamics-nav.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @jvincke.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by SarinaJoan** [comment]
Hi @jvincke, we currently do not support tenant selection for cloud instances. If you are running on-prem, the tenant is the instance you are connecting to and that is part of the URL path you enter when connecting.
