### ISSUE TITLE
I can't connect Adobe Analytics to Power BI Desktop

### ISSUE THREAD

**Issue by thesmarthomeninja** [MicrosoftDocs/powerbi-docs#62]
Is this missing all troubleshooting steps for Adobe Analytics connecting?  Basically I'm getting a bug or something and no workaround or troubleshooting steps are suggested in this article. 

When trying to connect in Power BI desktop, It just gives me a grey screen popup when trying to connect it.  I already have it connected as an app to the web client UI for PowerBI - but when I try to do it from Desktop, the only way I can connect it is with the PowerBI datasource (online) and it only shows me just a handful of dimensions/metrics, whereas I can't just setup a datasource like I can with Google Analytics- and see more dimensions and metrics to create custom reports or get a larger selection of dimensions.  It's a little frustrating, because my adobe ID is connected to my adobe analytics account and I've tried using my password and my google account that is connected to my adobe ID to sign in and basically during authentication after password is entered or google ID is used, a blank grey window pops up and just sits there and does nothing and won't let me fully connect...  Is there potentially a troubleshooting step missing from this documentation?  Hence why I mention all of this.  (I am an admin of our adobe account by the way, and know that everything is setup on my end with my credentials correctly). 
 Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 384b4a18-dc3a-6a05-379f-8821b4a06513
* Version Independent ID: b48f64dd-0d26-6cbb-3d3c-a29335f6ce82
* Content: [Connect to Adobe Analytics with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-adobe-analytics#troubleshooting)
* Content Source: [powerbi-docs/service-connect-to-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-adobe-analytics.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by kfile** [comment]
Thank you for your question. This issue has been assigned to the author for review. He may need to refer you to customer support. He'll be in touch.

**Comment by davidiseminger** [comment]
Hi @thesmarthomeninja - sorry about the trouble you're having. Sounds like it's an issue that'll require help from our support folks, rather than documentation. I'll also follow up with them to see if the docs can be clearer, but you'll want to initiate a support request (through the channel that's best for you - check out support.powerbi.com for a starting point) so they can troubleshoot your individual situation.

**Comment by thesmarthomeninja** [comment]
Sounds good, thank you sir!

Sent from Mail for Windows 10

**Comment by lfjhickory** [comment]
HI @thesmarthomeninja , did you ever get a solution for this? The same thing happens to me when I attempt to use the connector.

**Comment by thesmarthomeninja** [comment]
No, I could never figure it out. Seems like a broken feature or bug of some
sort. Thanks for responding, I was curious if it was just me!

On Aug 7, 2018 10:42 AM, "lfjhickory" <notifications@github.com> wrote:

HI @thesmarthomeninja <https://github.com/thesmarthomeninja> , did you ever
get a solution for this? The same thing happens to me when I attempt to use
the connector.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MicrosoftDocs/powerbi-docs/issues/62#issuecomment-411141405>,
or mute the thread

**Comment by mattpkelly** [comment]
We are having the exact same issue with the grey screen on Adobe's end and the sign in with our experience cloud credentials just spins.

**Comment by thesmarthomeninja** [comment]
It's been broken for well over 6 months... Don't know who to contact about
it. I'm in the same boat as you all... Sorry

**Comment by mattpkelly** [comment]
I've submitted a ticket to Adobe Client Care for this and escalated it through our Account Manager to address with the Product Team.  In the meantime, I'm using ReportBuilder to publish data to Power BI.  So far it's working perfectly.

**Comment by Donquiweb** [comment]
I have the same issue and think that it's due to the migration to the Adobeid model.

**Comment by Donquiweb** [comment]
Hi,

 it works for me on a PC under Windows7 but you need to have IE11 or higher (update is required). 
The point here is that on windows XP, 7 and 8, you can't change the default registry key to open links from Applications like PowerBI with préfixe URL:RES. 

So, except if you find a way to hack the registry entries to open this url in Google Chrome for example it won't work !
see : https://support.mozilla.org/fr/questions/1175204

**Comment by Swimshow** [comment]
Same problem here... Grey screen of death.

**Comment by Vulpette** [comment]
I have the same problem, so basically we can not use this.

**Comment by jeffshieldsdev** [comment]
This issue has been reported a couple times in the Power BI Community too:

- https://community.powerbi.com/t5/Desktop/Adobe-and-Power-BI-Connector/m-p/594653#M282361
- https://community.powerbi.com/t5/Desktop/Unable-to-connect-Adobe-Analytics-to-Power-BI-Desktop-blank/m-p/498941/highlight/true#M232742

**Comment by kingadobe** [comment]
The blank grey window is supposed to be the one-time authorization step. If it's not appearing in the Power BI Desktop workflow you can try performing the authorization directly from the browser. 

1. In a separate browser navigate to this [link](https://marketing.adobe.com/authorize?display=popup&client_id=506b6724cb-adobe-analytics-connector-pbi-desktop&redirect_uri=https%3a%2f%2foauth.powerbi.com%2fviews%2foauthredirect.html&response_type=code). The link is defined with the client_id used by the Power BI Desktop application that you need to authorize with Adobe.
2. Login with your Adobe ID.
3. The Authorization page will appear. Authorize access and then close the browser window after it progresses to a blank screen at "https://oauth.powerbi.com".
4. Then go back to Power BI Desktop and you will be able to successfully log in with your newly authorized Adobe ID.

**Comment by Vulpette** [comment]
> The blank grey window is supposed to be the one-time authorization step. If it's not appearing in the Power BI Desktop workflow you can try performing the authorization directly from the browser.
> 
> 1. In a separate browser navigate to this [link](https://marketing.adobe.com/authorize?display=popup&client_id=506b6724cb-adobe-analytics-connector-pbi-desktop&redirect_uri=https%3a%2f%2foauth.powerbi.com%2fviews%2foauthredirect.html&response_type=code). The link is defined with the client_id used by the Power BI Desktop application that you need to authorize with Adobe.
> 2. Login with your Adobe ID.
> 3. The Authorization page will appear. Authorize access and then close the browser window after it progresses to a blank screen at "https://oauth.powerbi.com".
> 4. Then go back to Power BI Desktop and you will be able to successfully log in with your newly authorized Adobe ID.

KingAdobe, thank you for helping out on this.
