### ISSUE TITLE
two-factor authentication

### ISSUE THREAD

**Issue by crathermel** [MicrosoftDocs/powerbi-docs#620]
Does this content pack support github two-factor authentication ? Doesn't seem to be working for me. The console log in chrome shows several 400 requests after the pop-up. But the pop-up just open to a white screen and then closes but doesn't log me in.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c027250-07bf-8656-c8a1-fa3267172003
* Version Independent ID: d8719b06-78bd-e835-3d7f-494babb076da
* Content: [Connect to GitHub with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-github)
* Content Source: [powerbi-docs/service-connect-to-github.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-github.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by crathermel** [comment]
Actually it doesn't look to be two factor related since my account is two factor but I just can't connect to my other organization.. What settings need to be set for this to work on the org/repo level?

**Comment by maggiesMSFT** [comment]
Hi, @crathermel -- Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by mimig1** [comment]
@maggiesMSFT @mgblythe - Please close, user fixed the issue.
