### ISSUE TITLE
How to change the API Key ?

### ISSUE THREAD

**Issue by timoleo23** [MicrosoftDocs/powerbi-docs#623]
My data source is pluged on my enrollment and I need to change the API Key : how can I do that ?
I don't see we to change this property of the data source.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data (Beta) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @timoleo23 and thanks for your question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
