### ISSUE TITLE
Applying user and role to an embed token sample is broken

### ISSUE THREAD

**Issue by nicolaslledo** [MicrosoftDocs/powerbi-docs#624]
The example refering to Home\HomeController.cs line 76 and 77 .
The code has been refactored into Services\EmbedService.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#applying-user-and-role-to-an-embed-token)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by kfile** [comment]
Hi @nicolaslledo. Thanks for your comment. I've assigned it to the author, Mark. He will probably need to work with engineering to come up with improved sample data. Please be patient with our process. Thanks.

**Comment by markingmyname** [comment]
Hi @nicolaslledo, 

Sorry for the delayed response.

**Comment by markingmyname** [comment]
Good eye, nicolaslledo! 

Also, did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

For this instance, the update will be available sometime next week.

Thanks again!
