### ISSUE TITLE
"in" is missing in data flows documentation

### ISSUE THREAD

**Issue by wolfgangstrasser** [MicrosoftDocs/powerbi-docs#625]
[Enter feedback here]
Hi 
in the sentence "Power BI can also connect to folders with schematized data in the Common Data Model format, which are stored your organization’s Azure Data Lake Storage account. " there is an IN missing 
-> I think it should be

"

Power BI can also connect to folders with schematized data in the Common Data Model format, which are stored IN your organization’s Azure Data Lake Storage account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d4e74b8-9f4a-a195-7347-cf6732ffeab5
* Version Independent ID: a1513d50-f098-9b75-2b48-94e08ee34751
* Content: [Learn about dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-overview)
* Content Source: [powerbi-docs/service-dataflows-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-overview.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @wolfgangstrasser. Thanks for letting us know about the typo. Did you know that you can submit a public PR and make the change yourself in the future? I've assigned to the author, meanwhile.

**Comment by davidiseminger** [comment]
You're absolutely right - thanks for the close read! I've fixed that, it'll show up in the updated/refreshed article in a day or so. Thanks @wolfgangstrasser for pointing that out!
