### ISSUE TITLE
Google Analytics Data Connector for Data Flows

### ISSUE THREAD

**Issue by jzagelbaum001** [MicrosoftDocs/powerbi-docs#626]
I have tried setting up Google Analytics using the blank query method shown in the article. When trying to use organizational account, I receive "Unexpected Error GoogleAnalytics: GoogleAnalytics". Using basic / anonymous authentication does not work either. Here is the M query I am attempting to use:

let
    Source = GoogleAnalytics.Accounts(),
    #"39288188" = Source{[Id="39288188"]}[Data],
    #"UA-39288188-1" = #"39288188"{[Id="UA-39288188-1"]}[Data],
    #"70170325" = #"UA-39288188-1"{[Id="70170325"]}[Data],
    #"Added Items" = Cube.Transform(#"70170325",
        {
            {Cube.AddAndExpandDimensionColumn, "ga:eventAction", {"ga:eventAction"}, {"Event Action"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventCategory", {"ga:eventCategory"}, {"Event Category"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventLabel", {"ga:eventLabel"}, {"Event Label"}},
            {Cube.AddMeasureColumn, "Avg. Value", "ga:avgEventValue"},
            {Cube.AddMeasureColumn, "Event Value", "ga:eventValue"},
            {Cube.AddMeasureColumn, "Events / Session with Event", "ga:eventsPerSessionWithEvent"},
            {Cube.AddMeasureColumn, "Sessions with Event", "ga:sessionsWithEvent"},
            {Cube.AddMeasureColumn, "Total Events", "ga:totalEvents"},
            {Cube.AddMeasureColumn, "Unique Events", "ga:uniqueEvents"}
        })
in
    #"Added Items"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1458e2bc-7637-e305-55f3-596c64972ff3
* Version Independent ID: b5437e14-6d46-e2f6-0369-e61f72988ff3
* Content: [Learn how to connect to dataflows in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-data-sources)
* Content Source: [powerbi-docs/service-dataflows-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @jzagelbaum001 and thanks for your question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by jzagelbaum001** [comment]
Well, if the feature doesn't work eventhough multiple people have tested trying to follow the documentation, then not entirely sure I would consider this closed.

**Comment by mllopis** [comment]
Google Analytics works fine today – both with and without an On-prem gateway.

Here’s what you need to do:

1.	Select “Blank Query”.
2.	Paste in the query you created using Power BI Desktop. 
3.	You will get an error “Specify how to connect” in the Power Query Editor if it is the first time you connect to Google Analytics. This error has a “Specify Credentials” button next to it.
4.	Within the Credentials dialog, select “Organizational Account”
5.	Go through the OAuth sign in flow for Google Analytics.

After completing these steps, you Google Analytics query should return the expected results in the Power Query Online Query Editor.

Hope that helps. Let us know if you're still running into issues.

Thanks,
M.

**Comment by jzagelbaum001** [comment]
Hi Miguel,

Not sure if you’re in a different tenant or what (have tested on both North Central US (Illinois) & Southeast Asia (Singapore) tenants), but when I follow those steps I continue to receive this error when trying to authenticate using an organizational account:

[cid:image001.jpg@01D4B6FB.A0C7C440]

Here is the M query that I am pasting in to the blank query window:


let
    Source = GoogleAnalytics.Accounts(),
    #"39288188" = Source{[Id="39288188"]}[Data],
    #"UA-39288188-1" = #"39288188"{[Id="UA-39288188-1"]}[Data],
    #"70170325" = #"UA-39288188-1"{[Id="70170325"]}[Data],
    #"Added Items" = Cube.Transform(#"70170325",
        {
            {Cube.AddAndExpandDimensionColumn, "ga:eventAction", {"ga:eventAction"}, {"Event Action"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventCategory", {"ga:eventCategory"}, {"Event Category"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventLabel", {"ga:eventLabel"}, {"Event Label"}},
            {Cube.AddMeasureColumn, "Avg. Value", "ga:avgEventValue"},
            {Cube.AddMeasureColumn, "Event Value", "ga:eventValue"},
            {Cube.AddMeasureColumn, "Events / Session with Event", "ga:eventsPerSessionWithEvent"},
            {Cube.AddMeasureColumn, "Sessions with Event", "ga:sessionsWithEvent"},
            {Cube.AddMeasureColumn, "Total Events", "ga:totalEvents"},
            {Cube.AddMeasureColumn, "Unique Events", "ga:uniqueEvents"}
        })
in
    #"Added Items"

There is no redirect to the Google Analytics OAuth sign in flow. Please advise.

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

**Comment by jzagelbaum001** [comment]
Hi Miguel,

Wondering if you would humor me and test it on either of the Power BI tenants that I listed?

Thank you,

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Monday, January 28, 2019 11:22 AM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

Not sure if you’re in a different tenant or what (have tested on both North Central US (Illinois) & Southeast Asia (Singapore) tenants), but when I follow those steps I continue to receive this error when trying to authenticate using an organizational account:

[cid:image002.jpg@01D4B7AE.C86B8870]

Here is the M query that I am pasting in to the blank query window:


let
    Source = GoogleAnalytics.Accounts(),
    #"39288188" = Source{[Id="39288188"]}[Data],
    #"UA-39288188-1" = #"39288188"{[Id="UA-39288188-1"]}[Data],
    #"70170325" = #"UA-39288188-1"{[Id="70170325"]}[Data],
    #"Added Items" = Cube.Transform(#"70170325",
        {
            {Cube.AddAndExpandDimensionColumn, "ga:eventAction", {"ga:eventAction"}, {"Event Action"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventCategory", {"ga:eventCategory"}, {"Event Category"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventLabel", {"ga:eventLabel"}, {"Event Label"}},
            {Cube.AddMeasureColumn, "Avg. Value", "ga:avgEventValue"},
            {Cube.AddMeasureColumn, "Event Value", "ga:eventValue"},
            {Cube.AddMeasureColumn, "Events / Session with Event", "ga:eventsPerSessionWithEvent"},
            {Cube.AddMeasureColumn, "Sessions with Event", "ga:sessionsWithEvent"},
            {Cube.AddMeasureColumn, "Total Events", "ga:totalEvents"},
            {Cube.AddMeasureColumn, "Unique Events", "ga:uniqueEvents"}
        })
in
    #"Added Items"

There is no redirect to the Google Analytics OAuth sign in flow. Please advise.

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

**Comment by jzagelbaum001** [comment]
Hi Miguel,

I still need assistance with this. Would you have some time available to real time troubleshoot this with me?

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Tuesday, January 29, 2019 8:44 AM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; 'MicrosoftDocs/powerbi-docs' <powerbi-docs@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

Wondering if you would humor me and test it on either of the Power BI tenants that I listed?

Thank you,

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Monday, January 28, 2019 11:22 AM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com<mailto:powerbi-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

Not sure if you’re in a different tenant or what (have tested on both North Central US (Illinois) & Southeast Asia (Singapore) tenants), but when I follow those steps I continue to receive this error when trying to authenticate using an organizational account:

[cid:image001.jpg@01D4BC98.CBA66E80]

Here is the M query that I am pasting in to the blank query window:


let
    Source = GoogleAnalytics.Accounts(),
    #"39288188" = Source{[Id="39288188"]}[Data],
    #"UA-39288188-1" = #"39288188"{[Id="UA-39288188-1"]}[Data],
    #"70170325" = #"UA-39288188-1"{[Id="70170325"]}[Data],
    #"Added Items" = Cube.Transform(#"70170325",
        {
            {Cube.AddAndExpandDimensionColumn, "ga:eventAction", {"ga:eventAction"}, {"Event Action"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventCategory", {"ga:eventCategory"}, {"Event Category"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventLabel", {"ga:eventLabel"}, {"Event Label"}},
            {Cube.AddMeasureColumn, "Avg. Value", "ga:avgEventValue"},
            {Cube.AddMeasureColumn, "Event Value", "ga:eventValue"},
            {Cube.AddMeasureColumn, "Events / Session with Event", "ga:eventsPerSessionWithEvent"},
            {Cube.AddMeasureColumn, "Sessions with Event", "ga:sessionsWithEvent"},
            {Cube.AddMeasureColumn, "Total Events", "ga:totalEvents"},
            {Cube.AddMeasureColumn, "Unique Events", "ga:uniqueEvents"}
        })
in
    #"Added Items"

There is no redirect to the Google Analytics OAuth sign in flow. Please advise.

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

**Comment by jzagelbaum001** [comment]
Current error message for reference:

[cid:image002.png@01D4BC9A.615D58C0]

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Monday, February 4, 2019 2:49 PM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; 'MicrosoftDocs/powerbi-docs' <powerbi-docs@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

I still need assistance with this. Would you have some time available to real time troubleshoot this with me?

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Tuesday, January 29, 2019 8:44 AM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; 'MicrosoftDocs/powerbi-docs' <powerbi-docs@noreply.github.com<mailto:powerbi-docs@noreply.github.com>>
Cc: 'Mention' <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

Wondering if you would humor me and test it on either of the Power BI tenants that I listed?

Thank you,

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>

From: Jared Zagelbaum
Sent: Monday, January 28, 2019 11:22 AM
To: 'MicrosoftDocs/powerbi-docs' <reply@reply.github.com>; MicrosoftDocs/powerbi-docs <powerbi-docs@noreply.github.com<mailto:powerbi-docs@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [MicrosoftDocs/powerbi-docs] Google Analytics Data Connector for Data Flows (#626)

Hi Miguel,

Not sure if you’re in a different tenant or what (have tested on both North Central US (Illinois) & Southeast Asia (Singapore) tenants), but when I follow those steps I continue to receive this error when trying to authenticate using an organizational account:

[cid:image001.jpg@01D4BC9A.619817D0]

Here is the M query that I am pasting in to the blank query window:


let
    Source = GoogleAnalytics.Accounts(),
    #"39288188" = Source{[Id="39288188"]}[Data],
    #"UA-39288188-1" = #"39288188"{[Id="UA-39288188-1"]}[Data],
    #"70170325" = #"UA-39288188-1"{[Id="70170325"]}[Data],
    #"Added Items" = Cube.Transform(#"70170325",
        {
            {Cube.AddAndExpandDimensionColumn, "ga:eventAction", {"ga:eventAction"}, {"Event Action"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventCategory", {"ga:eventCategory"}, {"Event Category"}},
            {Cube.AddAndExpandDimensionColumn, "ga:eventLabel", {"ga:eventLabel"}, {"Event Label"}},
            {Cube.AddMeasureColumn, "Avg. Value", "ga:avgEventValue"},
            {Cube.AddMeasureColumn, "Event Value", "ga:eventValue"},
            {Cube.AddMeasureColumn, "Events / Session with Event", "ga:eventsPerSessionWithEvent"},
            {Cube.AddMeasureColumn, "Sessions with Event", "ga:sessionsWithEvent"},
            {Cube.AddMeasureColumn, "Total Events", "ga:totalEvents"},
            {Cube.AddMeasureColumn, "Unique Events", "ga:uniqueEvents"}
        })
in
    #"Added Items"

There is no redirect to the Google Analytics OAuth sign in flow. Please advise.

Jared Zagelbaum
Senior Consultant | BlueGranite, Inc.<https://www.blue-granite.com/>
m: (651) 431-0035 | p: (877) 817-0736 ext. 717
jzagelbaum@blue-granite.com<mailto:jzagelbaum@blue-granite.com>
