### ISSUE TITLE
Reply URL is case sensitive

### ISSUE THREAD

**Issue by SteveWinward** [MicrosoftDocs/powerbi-docs#63]
The reply URL in AAD is case sensitive.  The actual reply URL for the dashboard sample should be "http://localhost:13526/Redirect", not "http://localhost:13526/redirect"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edce6995-b777-06fc-49ee-b23eabf6a862
* Version Independent ID: ffd0c74b-4a05-1019-6897-804d60c13765
* Content: [Register an app to embed Power BI content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/register-app)
* Content Source: [powerbi-docs/developer/register-app.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/register-app.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thank you for your feedback.  I have corrected the URL.
