### ISSUE TITLE
Different options in Service vs Desktop for "Filter Cards"

### ISSUE THREAD

**Issue by jainn4** [MicrosoftDocs/powerbi-docs#630]
Hi there, 

I have noticed that the December desktop version doesn't have the same options as I can see in the service. You can see the screenshot below

**### Options in Service**
![filter_pane_service](https://user-images.githubusercontent.com/42496773/51788154-ad5c3380-2172-11e9-8682-0524e919b05e.PNG)

**### Options in Desktop**
![filter_pane_desktop](https://user-images.githubusercontent.com/42496773/51788155-adf4ca00-2172-11e9-9e8b-7dfd852bc86d.PNG)

Can you please look into this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Dear @jainn4 ,
Thank you for your feedback and attention to detail.  I've forwarded your observational along to the doc author, who will respond as soon as possible.  We truly appreciate your contributions to the documentation. 
Take care,
The international DOCS team

**Comment by maggiesMSFT** [comment]
Hi, @jainn4 -- good eye! Yes, you're right, different options right now. They'll be the same soon, with the next release of Power BI Desktop.
