### ISSUE TITLE
Error interacting with REST API using Google Bigquery connector

### ISSUE THREAD

**Issue by linhdh9** [MicrosoftDocs/powerbi-docs#631]
I'm running into this error when trying to create a direct query connection to BigQuery using the built-in Google BigQuery connector

DataSource.Error: ODBC: ERROR [HY000] [Microsoft][BigQuery] (100) Error interacting with REST API: Not found: Job [project-id]:[job-id]
Details:
    DataSourceKind=GoogleBigQuery
    DataSourcePath=GoogleBigQuery
    OdbcErrors=Table

I follow the tutorial in this [page](https://docs.microsoft.com/en-us/power-bi/desktop-connect-bigquery#) and specify the BillingProject to mine. However, the above error pop up.

I check the job in BigQuery query history and it was marked successful. Hence, there's probably something wrong when Power BI is trying to get the data into Power Query. 

My table is in the asia-northeast region, and when I try to query with a table in the US region instead, I find that it works.  

Is this a bug with the REST API having something to do with region of the table?

P/S: I'm currently using the latest version of Power BI I believe (Version: 2.65.5313.1381 64-bit (December 2018)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 974455fc-88ff-6a48-4dd0-036419eaa849
* Version Independent ID: 2700a36d-177a-7596-2d91-4f0fc9f9d695
* Content: [Connect to a Google BigQuery database in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-bigquery)
* Content Source: [powerbi-docs/desktop-connect-bigquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-bigquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @linhdh9 ,
Thank you for your feedback.  I've forwarded your question along to the author, who will respond as soon as possible. We appreciate your contribution to our documentation.
The DOCS team.

**Comment by benschmucker** [comment]
Also seeing the same issue.

**Comment by linhdh9** [comment]
> Also seeing the same issue.

They say they're going to fix it in the March release.

**Comment by daniel-zrust** [comment]
This thing is currently not working as it used to. If you try to pull more than 1M rows from BigQuery, you may be out of luck. Datasets which have been refreshing with 0 issues for the past 2 years are now failing because of timeouts. 

The issues started around 2019-02-13 and no resolution since. More about the issue here: https://community.powerbi.com/t5/Service/Timeout-expired-The-timeout-period-elapsed-prior-to-completion/td-p/625894

**Comment by davidiseminger** [comment]
Sorry for the trouble you're having. Please note we can't fix product issues (only doc issues), but you can always provide product feedback (or support/bug issues) in the following locations:
https://support.powerbi.com
https://ideas.powerbi.com
https://community.powerbi.com
