### ISSUE TITLE
Cannot see Drillthrough filters

### ISSUE THREAD

**Issue by reza-h78** [MicrosoftDocs/powerbi-docs#632]
I am on PowerBI Desktop (December 2018) and I cannot see the Drillthrough filters under FILTERS panel. Has this been removed in later updates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8caeb04f-19a3-320d-2bfa-147c5377728e
* Version Independent ID: d3785a20-eeaa-a3a0-5198-b6a4c8fd475b
* Content: [Use drillthrough in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-drillthrough)
* Content Source: [powerbi-docs/desktop-drillthrough.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-drillthrough.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @reza-h78 , 
Thank you for your feedback.  I've forwarded your question along to the author, who will respond as soon as possible. We appreciate your contribution to our documentation.
The DOCS team.

**Comment by Yaswanth-Goli** [comment]
I have 6 slicers, 3 donut chart visuals and a table with drillthrough on my report page. I selected options in the slicers and also filtered the other visuals on the page by selecting one section on the donut chart. When i click on back button in the drillthrough page after going to the drillthrough page by selecting drillthrough and drillthrough page name in the actual page, the selection i made on the donut chart is gone and only slicer selections remained as it is. Can you please confirm whether donut selection should remain as it is similar to slicer selection or not.

**Comment by davidiseminger** [comment]
Hi @Yaswanth-Goli - sorry for the trouble you're having.

Note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
