### ISSUE TITLE
PowerBI rest API examples for Embedding report

### ISSUE THREAD

**Issue by dilanarandara** [MicrosoftDocs/powerbi-docs#633]
Could you please provide PowerBI rest API examples for Embedding report?

**Comment by mihart** [comment]
Hi @dilanarandara ,
Thank you for your input.  I've forwarded your question along to our "embedded" author.  He'll respond as soon as possible.  We appreciate your contribution to the Power BI docs.
- The DOCS team

**Comment by markingmyname** [comment]
@dilanarandara, sorry for the delayed response.

**Comment by markingmyname** [comment]
@dilanarandara , hope this helps.

https://github.com/Microsoft/PowerBI-Developer-Samples

Thank you.

**Comment by dilanarandara** [comment]
@mihart @markingmyname 
Thank you very much. This is what I needed.
