### ISSUE TITLE
Need documentation on programmatically adding data sources

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#634]
I have a list of a few hundred data sources to add.  How do I do that without tippy-tapping every one of them in manually?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58eaf5cf-f2f4-785c-a766-38e1868bf820
* Version Independent ID: 5f8db39f-c5bd-c7ce-5258-c8b47cb83c7f
* Content: [Manage your data source - SQL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-enterprise-manage-sql)
* Content Source: [powerbi-docs/service-gateway-enterprise-manage-sql.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-enterprise-manage-sql.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @jordanmills ,
Thank you for your question.  I've forwarded it along to the article author, who will respond as soon as possible.  We really appreciate your contribution to our docs. 
Take care,
The Power BI International DOCS team

**Comment by mgblythe** [comment]
Adding @arthiriyer to comment on whether you can add datasources programmatically. Also adding @markingmyname in case we cover this in the dev docs.

**Comment by jordanmills** [comment]
Okay, so I know you can create manage data sources programmatically.  If you waste enough time searching, you can eventually find incomplete documentation: https://docs.microsoft.com/en-us/rest/api/power-bi/gateways/createdatasource

I don't know if detail should go here or there.  A link to the REST API documentation might help here, but only if that REST API documentation is completed.  What I've noticed is missing so far are details on the composition and construction of the credentials object and working with gateway clusters instead of individual gateways.  I'm sure there's lots more.

**Comment by arthiriyer** [comment]
@jordanmills thats correct- the APIs should help to create it programatically. Thanks for your feedback- we are working on enhancing the gateway documentation.

**Comment by mgblythe** [comment]
We added a link to the REST API, and I will share your feedback with the team that maintains the REST API docs. Thanks!
