### ISSUE TITLE
Couldn't get this working.

### ISSUE THREAD

**Issue by osmanerzinclioglu** [MicrosoftDocs/powerbi-docs#635]
Sadly, we haven't gotten this app working yet. We keep getting a Marketo error related to the number of calls being made by Power BI to retrieve the data. (Error 606: The number of calls in the past 20 seconds was greater than 100.)

We let the app run for five days consecutively, having selected the minimum number of months (1). The app made between 23,000 to 43,000 API calls each day, but never produced a functioning dashboard.

Our Marketo instance experienced that 606 error anywhere from 8,000 to 17,000 times each day for the five days it ran.

I think modifying the rate of the API calls from this app may help. Also, being able to set some sort of daily cap would be useful because companies using Marketo have different caps on their daily number of API requests and also may have other services they need to reserve a certain number of calls for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33fec0d-5dc1-3229-754a-df9e506f2284
* Version Independent ID: f30a20c7-688f-5f3c-5ae2-1901e4bb893d
* Content: [Connect to Marketo with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-marketo)
* Content Source: [powerbi-docs/service-connect-to-marketo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-marketo.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mihart** [comment]
Hi @osmanerzinclioglu  and @SarinaJoan ,
Thank you for letting us know about this issue.  This sounds like a product issue and not a documentation issue.  Please post on the community forum for a quick response.  The URL for the forum is: 
community.powerbi.com

Take care,
The international DOCS team
