### ISSUE TITLE
Notes tutorials custom visual

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/powerbi-docs#637]
@FANOUCHKA commented on [Tue Jan 29 2019](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/issues/8)

**Developing the visual elements**
Replace 9.In PowerShell, start the custom visual. "pbiviz" by "pbiviz start"

and 

**Adding custom formatting options**
Missing a ";" in typescript code
10.In the update method, after the declaration of the radius variable, add the following code.
this.visualSettings = VisualSettings.parse<VisualSettings>(dataView);
this.visualSettings.circle.circleThickness = Math.max(0, this.visualSettings.circle.circleThickness)**;**this.visualSettings.circle.circleThickness = Math.min(10, this.visualSettings.circle.circleThickness);

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Développement d’un visuel personnalisé Power BI - Power BI](https://docs.microsoft.com/fr-fr/power-bi/developer/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs.fr-fr/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by LisandroSu** [comment]
Hi team,

Please check on this issue.

Thanks!

**Comment by mihart** [comment]
Hi @LisandroSu and @Fanouchka,
Thank you for your documentation feedback.  I've forwarded this info along to the author, who will respond as soon as possible. 
Take care,
The international DOCS team

**Comment by markingmyname** [comment]
@LisandroSu , sorry for the delayed response.

Thank you for your suggestion and request. We're on it. This will be discussed with the parties involved.

**Comment by markingmyname** [comment]
@LisandroSu, Changes will be applied to the article by the end of the week.

Thank you for the feedback and good eye.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
