### ISSUE TITLE
Unable to select time and day

### ISSUE THREAD

**Issue by jameskim1701** [MicrosoftDocs/powerbi-docs#638]
Hi, is there a reason I'm unable to set the Time as shown in the screetshots?
I'm able to set only Daily and Weekly frequency however the Time and day (Sunday - Saturday) is not available.
I have the Power Bi Pro edition and also can set only the standard subscription?
thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e35489ab-e39e-b7be-588d-38f26ccf5442
* Version Independent ID: f5145d5d-afbc-f3f0-7275-1186b60890d0
* Content: [Subscribe yourself to reports and dashboards - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-subscribe#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/consumer/end-user-subscribe.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-subscribe.md)
* Service: **powerbi**
* GitHub Login: @mihart

**Comment by mihart** [comment]
Hi @jameskim1701 
You can only set the days of the week if you choose Weekly.  Have you selected Weekly and still can't choose days of the week?  
Thanks,
Michele

**Comment by maggiesMSFT** [comment]
Hi @jameskim1701 -- also, the new functionality is still rolling out, so you may not be able to see it yet. Give it a day or so and try again. 
Thanks!

**Comment by Tobeornottobethatisthequestion** [comment]
Hello, I have full admin rights and as of this morning don't have any daily/weekly or other time selection. All I get is a message saying " You will be sent an email whenever the data is updated, but no more than once per frequency selected". But there is no option to select any frequency and there always was up until yesterday. Is there something happening with the latest release that's a bug?

**Comment by jameskim1701** [comment]
> Hi @jameskim1701 -- also, the new functionality is still rolling out, so you may not be able to see it yet. Give it a day or so and try again.
> Thanks!

Awesome. Found another article that says it will be rolled out on the 2nd Feb for everyone.
thanks!
