### ISSUE TITLE
Ambiguous "If any changes are found"

### ISSUE THREAD

**Issue by coreyindahouse** [MicrosoftDocs/powerbi-docs#64]
In the " Where your file is saved makes a difference" under "OneDrive - Business", it is ambiguous what the change is. 

Is the change a change in the raw data point in the dataset, a change of a visual, calculated column? What happens when a new entry is added to an SQL database, will OneDrive know about that change?

Note: first time using GitHub please mention me somehow to acknowledge this comment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394d90a7-d6ad-c666-9099-a85e7ab4d817
* Version Independent ID: 5077293e-a2c0-16b6-08bb-b65b11b1e9e5
* Content: [Get data from files - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data-from-files)
* Content Source: [powerbi-docs/service-get-data-from-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data-from-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @coreyindahouse - sorry for any ambiguity. The change is for anything in a file that's stored in OneDrive for Business in that location. So changes to Excel or PBIX files that are then saved in that location would show up. If you have a connection to a database in that Excel file and the database is changed, but the Excel file doesn't automatically pick it up, the report would only be updated once the source Excel file is actually updated. I hope that helps.

**Comment by davidiseminger** [comment]
Answered - thanks for posting!
