### ISSUE TITLE
New documentation needed

### ISSUE THREAD

**Issue by mtzupan** [MicrosoftDocs/powerbi-docs#640]
The directions for how to 'Manage Gateways' is now obsolete. The 'gear' graphic no longer exists in the latest released version of PowerBI.

Version: 2.65.5313.1381 64-bit (December 2018)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87176394-a2d4-7e3d-922e-d124d59fe9c5
* Version Independent ID: 99c3109b-b094-1300-86e2-0cebb4475169
* Content: [Manage a Power BI on-premises gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-manage)
* Content Source: [powerbi-docs/service-gateway-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mtzupan** [comment]
Update - please specify in this document that the 'Manage gateways' option is through the PowerBI web app, not the Desktop app :)

**Comment by mgblythe** [comment]
Thanks for your comment, @mtzupan. We're planning a gateway docs update, and we'll include this.

**Comment by mgblythe** [comment]
@mtzupan -- the intro to the doc has the following: 

You can manage a gateway through the **Manage gateways** area of the Power BI service, in the gateway app on your local computer, and with PowerShell scripts. This article focuses on the Power BI service.

The first set of steps has this:

In the upper-right corner of the Power BI service, select the gear icon 

I'll close for now, but feel free to re-open and let me know if you have any suggestions.
