### ISSUE TITLE
Fix the feedback email link

### ISSUE THREAD

**Issue by guvijaya** [MicrosoftDocs/powerbi-docs#641]
pbicortanasg is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01469f26-0e17-b9ac-851b-a19aa8f39fcf
* Version Independent ID: 17b3a3ce-0963-39dc-fc5b-cf8df728ce91
* Content: [Quickly find and view your reports and dashboards using Cortana - Power BI](https://docs.microsoft.com/en-us/power-bi/service-cortana-intro#feedback)
* Content Source: [powerbi-docs/service-cortana-intro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-cortana-intro.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
The update is live now. Thanks again for pointing that out!
