### ISSUE TITLE
Relationship Link and Image of Final Result

### ISSUE THREAD

**Issue by SeaDude** [MicrosoftDocs/powerbi-docs#642]
Hello,
Great tutorial, thank you. It would be very beneficial to have a link to the "faster" method (using relationships) in the Tip. 
Also, would love to see a final view of the table. After reading all the way through the doc, I want to see the result, but its missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Shape and combine data from multiple sources - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-shape-and-combine-data)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @SeaDude. We appreciate the positive feedback. We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by davidiseminger** [comment]
Thanks for your feedback and nice comments. Let us look into adding that to the tutorial. Thanks!
