### ISSUE TITLE
Max Length

### ISSUE THREAD

**Issue by alfatema** [MicrosoftDocs/powerbi-docs#643]
Hi!

I try to fetch data from SAP BW, but I see only first 133 symobls or less.

Execution mode = BasXmlGzip
Batch size = 500000
Data Connectivity mode = Import
Implementation = 2.0 (requires SAP .NET Connector 3.0)

But I see full text when I connect to the cube throught Excel Analysis Services.

How can I fetch full text from SAP BW with Power BI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP BW Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-bw-connector)
* Content Source: [powerbi-docs/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-bw-connector.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @alfatema. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
