### ISSUE TITLE
Disable refreshing of offline datasets

### ISSUE THREAD

**Issue by carps84** [MicrosoftDocs/powerbi-docs#644]
So it looks like you have added a feature to disable the refreshing of certain datasets from within power query e.g. offline files, however, the power BI schedule refresh service ignores this and try to connect anyway resulting in a total failure. Is this a bug or a feature? Can Power BI scheduler not see the setting applied in the power query on power BI desktop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d66fa27-d240-0161-71fe-4ba1c55ca1ea
* Version Independent ID: 1f95372c-9caf-5547-0e7b-95cf1dca769e
* Content: [Refresh a dataset created from an Excel workbook - local - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-excel-file-local-drive#feedback)
* Content Source: [powerbi-docs/refresh-excel-file-local-drive.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-excel-file-local-drive.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @carps84 -- Thanks for your comment. We’ve forwarded your feedback to the writer. In the meantime, you might find a solution in the Power BI Community, found at https://community.powerbi.com, or the support site, https://support.powerbi.com. Thanks!

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
