### ISSUE TITLE
Add MarkLogic to list of supported DirectQuery sources

### ISSUE THREAD

**Issue by aroach337** [MicrosoftDocs/powerbi-docs#645]
MarkLogic has been added to the list of DirectQuery drivers in the December release.  Can this source be added to the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your comment, @aroach337.  We’ve forwarded your feedback to the writer, who should respond soon. Thanks!

**Comment by davidiseminger** [comment]
Thanks for posting - adding an assignee to confirm.

**Comment by ambleside** [comment]
Status?

**Comment by mgblythe** [comment]
Adding @cpopell to confirm DQ support for MarkLogic

**Comment by cpopell** [comment]
Confirmed. Let me get back to that spreadsheet identifying everything with DQ support...

**Comment by mgblythe** [comment]
Thanks @cpopell, @davidiseminger to fix.

**Comment by davidiseminger** [comment]
Added to the list, thanks! Will update within 24 hours.
