### ISSUE TITLE
Icons need to be updated

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerbi-docs#646]
The icons when for visual interactions have changed since the December 2018 update I believe. This document still contains images of the old icons.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b7c372d-539c-5857-01c5-8a8d835380a8
* Version Independent ID: 08d1564e-d1dc-ae37-8147-ef21c80feccc
* Content: [Change how visuals interact in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-reports-visual-interactions)
* Content Source: [powerbi-docs/service-reports-visual-interactions.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-reports-visual-interactions.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @jsh121988 -- thanks for your comment! We've passed your feedback on to the author, who respond soon. Thanks again!

**Comment by mihart** [comment]
Hi @jsh121988 
I checked the document, and the icons seem to be up-to-date.  Can you let me know which icon(s) specifically?
