### ISSUE TITLE
Page navigation suggestion

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#649]
When on this page, the is nothing highlighted on the left side navigation to indicate where this content is in the overall documentation hierarchy which is a little confusing. It would be helpful if this could be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f546db7-20fa-c87d-f7a4-a0a931f47e05
* Version Independent ID: 0180dfc6-d05d-8517-ec8c-94723f0f832e
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-portal#users)
* Content Source: [powerbi-docs/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-portal.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Hi @DeanGross and thanks for the suggestion. I've assigned this to one of my doc leads but he will need to take this up with the people who develop our docs platform to see if there is interest in enhancing it.

**Comment by mgblythe** [comment]
Thanks for the feedback. The article now syncs correctly with the TOC.
