### ISSUE TITLE
Connection to other classification tools in O365

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#650]
Is this data classification connected to the Classification labels for SharePoint Sites, Office Groups and Teams? I don't think that it is, but it should be. Can you please confirm my assumption and let us know if there are any plans to make this type of connection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 460b9768-213a-bd8b-5ad8-ed5071848a98
* Version Independent ID: 24bdc0f5-a172-0d0b-02b2-ff798ccd96cf
* Content: [Dashboard data classification - Power BI](https://docs.microsoft.com/en-us/power-bi/service-data-classification)
* Content Source: [powerbi-docs/service-data-classification.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-data-classification.md)
* Service: **powerbi**
* GitHub Login: @amandacofsky
* Microsoft Alias: **amac**

**Comment by kfile** [comment]
Hi @DeanGross and thanks for your question. I've assigned it to Amanda, who is a product PM and who owns the doc page you listed. She's the best one to answer your question. Thanks.

**Comment by kfile** [comment]
Heard back from Amanda that she's not the right person. Trying Kay Unkroth.

**Comment by KayUnkroth** [comment]
Classification labels in Power BI are only for Power BI and are not integrated with other classification labels from SharePoint or other systems.
