### ISSUE TITLE
Insufficient info

### ISSUE THREAD

**Issue by chris586** [MicrosoftDocs/powerbi-docs#651]
This page is referenced in the community.powerbi  pages.  The info here is extremely simple and doesn't cover advanced sorting, e.g. how to change sorting to be based on anything other than alphabetically and by visible dimensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d720907-1bee-2523-b53b-a1f2ffad1bfc
* Version Independent ID: b5a1765e-8008-af99-e82f-4e694fb0c75b
* Content: [Change how a chart is sorted in a report - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-change-sort)
* Content Source: [powerbi-docs/consumer/end-user-change-sort.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-change-sort.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfile** [comment]
Hi @chris586 and thanks for your question. I've assigned this to the owner of the document who can best address your question about enhancing the doc.

**Comment by mihart** [comment]
Hi @chris586 ,
The articles in the /consumer section are intended for customers interacting with Power BI service, and in Reading view. The article is intentionally simple and does not describe the type of sorting that, say, a report designer can do.  If you send me a link to the community page, I can update with a better article for reference.  

Thank you for your comment and suggestion!
Michele
