### ISSUE TITLE
Workspace State

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#652]
What are the State options in Workspaces table and how are they defined? I see some that are "Active" but they don't contain any content, which is confusing. I also see some that are "Removing", does this mean that the associated Office Group has been deleted, or something else. Please provide some additional information about the data in table shown on the Workspaces page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f546db7-20fa-c87d-f7a4-a0a931f47e05
* Version Independent ID: 0180dfc6-d05d-8517-ec8c-94723f0f832e
* Content: [Power BI admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-portal#workspaces-preview)
* Content Source: [powerbi-docs/service-admin-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-portal.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@DeanGross -- here's the info you're looking for:

Active - a normal workspace. It doesn't indicate anything about usage or what's inside, only that the workspace itself is "normal".
Orphaned - a workspace that has no admin user.
Deleted - a workspace that has been deleted. We maintain enough metadata to restore the workspace if desired.
Removing - a workspace that is in the process of being deleted, but isn't done yet.
I don't know if we remove a workspace when the corresponding Office group is deleted or not, but users can delete their own workspaces, putting things into Removing and eventually Deleted.

@maggiesMSFT - assigning to you to see if you have a good place for this info in the workspace docs.

**Comment by maggiesMSFT** [comment]
Thanks for your question, @DeanGross! Adding that info to https://docs.microsoft.com/en-us/power-bi/service-admin-portal#workspaces-preview
