### ISSUE TITLE
App Access

### ISSUE THREAD

**Issue by subashsivaji** [MicrosoftDocs/powerbi-docs#654]
When publishing an App - under Access tab what methods of individuals we can add? Can you please explicitly mention the methods.
Azure Active Directory Security Groups (please clearly mention it must be mail enabled)
Individual Users
Office 365 Groups?
Distribution lists?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Publish apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps#publish-your-app)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @subashsivaji. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by maggiesMSFT** [comment]
Thanks for asking, @subashsivaji! I updated the article on April 14 but neglected to reply to you. Here's the answer:
Either your entire organization, or individuals, Office 365 groups, distribution lists, and Active Directory security groups, whether email-enabled or not. 
Thanks again!
