### ISSUE TITLE
Point number 2 is incorrect

### ISSUE THREAD

**Issue by sloggiz** [MicrosoftDocs/powerbi-docs#655]
I couldn't connect using the provided connection string format. After some experimentation I was able to connect using this for a Server Name field:
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host_name)(PORT=port_num))(CONNECT_DATA=(SERVICE_NAME=service_name)))
Please correct the documentation!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @sloggiz. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by davidiseminger** [comment]
Thanks for the help! I've added a note to that article, so others can benefit from your post. Thanks! Should show up in a day or so.

**Comment by lynchmob98** [comment]
When I try this, PowerBI tells me "The server name cannot have more than 128 characters", so this documentation does not help me.

**Comment by lynchmob98** [comment]
What eventually worked for me for "Server" was ... HOST_NAME:PORT_NUM/SERVICE_NAME

**Comment by trailbla2er** [comment]
Thank you all!
Thanks @lynchmob98 for the last tips!
