### ISSUE TITLE
CSE installation issue

### ISSUE THREAD

**Issue by adamstigall** [MicrosoftDocs/powerbi-docs#656]
I've tried to deploy this several times and have found a couple issues with the SSRSAzureInstallation.ps1 script.

1) The command after Get-AzCopy command does not download any files. I can run this command on a local PC and get the same results. 0 files downloaded.

2) No scripts directory exists in the following command when trying to dot source some PS scripts:
   ` # Load all PowerShell scripts  `
    `$scripts =  Get-ChildItem "$rootInstallDirectory\Scripts" -Recurse -Include *.ps1`
    `foreach ($script in $scripts) { . $script }`

**Comment by mgblythe** [comment]
Thanks for your comment, @adamstigall. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
