### ISSUE TITLE
Reporting Services mobile report samples

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftDocs/powerbi-docs#657]
Step #2 says "Tap Reporting Services samples". However, this option does not appear to be available in the current version of the Android app. Can you please investigate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f16a650-3781-bafb-88da-25ee12d688a1
* Version Independent ID: 4fc5c657-cbae-d49c-ce67-e8ae8b503164
* Content: [Get started with the Power BI mobile app on Android devices - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/mobile/mobile-android-app-get-started#reporting-services-mobile-report-samples)
* Content Source: [powerbi-docs/consumer/mobile/mobile-android-app-get-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/mobile/mobile-android-app-get-started.md)
* Service: **powerbi**
* GitHub Login: @mshenhav
* Microsoft Alias: **mshenhav**

**Comment by mgblythe** [comment]
Thanks for your comment, @vitaly-livshits. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by mshenhav** [comment]
We are looking into this. Thank  you your report.

**Comment by maggiesMSFT** [comment]
Thanks for reporting this, @vitaly-livshits! We've fixed the app as a result of your report.
