### ISSUE TITLE
Power Bi API doc

### ISSUE THREAD

**Issue by hopstar** [MicrosoftDocs/powerbi-docs#658]
At Automation & operational complexity in Power BI workspace-based isolation [https://docs.microsoft.com/en-us/power-bi/developer/embed-multi-tenancy#automation--operational-complexity-1](url)

"For example, creating a workspace for a new tenant is a common task, which needs automation. With the Power BI REST API, you can achieve full automation when creating workspaces."

In the sentence it refers to this doc: https://docs.microsoft.com/en-us/rest/api/power-bi/ 
On this doc their is no documentation about the creaction/editing of viewing of  workspace as referend in this document.

**Comment by mihart** [comment]
Hi @hopstar ,
Thank you for your feedback.  I've forwarded your comment along to the author, who will respond asap.
Take care
The Microsoft Power BI DOCS team.

**Comment by Minewiskan** [comment]
@hopstar - This https://docs.microsoft.com/en-us/rest/api/power-bi/ is an API reference that is automatically generated from swagger.json. Specific steps on how to complete a task using the APIs are not documented in API references. This applies to all API references, and is based on an industry standard. 
#please-close

**Comment by hopstar** [comment]
@Minewiskan I found out what the problem was. In the article your talking about workspaces and in the api their called groups.
