### ISSUE TITLE
The 3 worst ways to create a historgram

### ISSUE THREAD

**Issue by NordinLars** [MicrosoftDocs/powerbi-docs#659]
I'm sorry, but I'm very annoyed by this article as I can't think of worse ways of creating a histogram than the 3 suggestions you've provided. All three of them require an additional query!?!? Just imagine how cluttered any descent data model will be if an additional table (with relationships) is created every time a user wants a histogram. I have 3 other suggestions:
1. Bin the field you want to build a histogram on by right clicking it and choose "New group". Then use that group as a dimension in a column chart and any measure you prefer (e.g. COUNTROWS) as value. 
2. Use the custom visual called "Histogram Chart"
3. Ask Microsoft to build a better standard visual than "Histogram Chart", since that one is quite limited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414d2796-4f3f-8ebe-c9b9-0445c4523b82
* Version Independent ID: d6906e43-5f47-9712-f08c-27ad5e2c2b82
* Content: [Histograms - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-histograms)
* Content Source: [powerbi-docs/visuals/service-histograms.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-histograms.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @NordinLars ,
Thank you for your feedback and suggestions for ways to improve the article.  I'll take a look at the article and consider your suggestions.  
Take care,
The Microsoft DOCS team

**Comment by mihart** [comment]
Hi @NordinLars ,
We're taking down the article until it can be rewritten.  Thank you for pointing out the issues with it.
