### ISSUE TITLE
Bookmark Sharing

### ISSUE THREAD

**Issue by VincentSaelzlerFRA** [MicrosoftDocs/powerbi-docs#66]
I publish a report to a shared workspace / sharepoint group. Will bookmarks be user-specific or all-company?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e579557-27e4-8a24-69b7-55189b0f4966
* Version Independent ID: 0c97fa47-9695-aaaf-efcd-63b35362310e
* Content: [Using bookmarks in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-bookmarks)
* Content Source: [powerbi-docs/desktop-bookmarks.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-bookmarks.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Hi @VincentSaelzlerFRA - bookmarks will show up for anyone viewing the report that you publish. Hope that helps!

**Comment by davidiseminger** [comment]
Answered - thanks for posting!
