### ISSUE TITLE
RLS section needs updating

### ISSUE THREAD

**Issue by benjamin-holcombe** [MicrosoftDocs/powerbi-docs#660]
RLS section needs to be updated given the January 2019 release of Power BI Report Server.
https://powerbi.microsoft.com/en-us/blog/power-bi-report-server-update-january-2019/ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Comparing Power BI Report Server and the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Dear @benjamin-holcombe 
Thank you for your feedback.  I've passed your suggestion along to the author who will respond asap.
Take care,
The Microsoft DOCS team

**Comment by maggiesMSFT** [comment]
Hi, @benjamin-holcombe -- good eye! Guess what? I updated it yesterday. Check it out!
