### ISSUE TITLE
Uploading .rdl file to Power BI Web Service is not working

### ISSUE THREAD

**Issue by madhuzode** [MicrosoftDocs/powerbi-docs#661]
Hi, 
Is the paginated report option available in Power BI government cloud? 
I tried to upload my .rdl file in premium workspace in Power BI service using the steps mentioned above but i get the error message saying "This file isn't supported".  Please let me know.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da59f209-0ccd-01d0-6e0e-12943ef3680e
* Version Independent ID: 390690ff-76bd-f4c6-afac-d5ad2f3854cb
* Content: [Tutorial: Create a paginated report and upload it to the Power BI service (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-quickstart-aw)
* Content Source: [powerbi-docs/paginated-reports-quickstart-aw.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-quickstart-aw.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @madhuzode ,
That's a great question.  I've passed it along to the article author who will get back to you asap.
Take care,
The Microsoft DOCS team

**Comment by madhuzode** [comment]
Hi,
Can I get an update on my query i posted a month ago?

Is the paginated report option available in Power BI government cloud?
I tried to upload my .rdl file in premium workspace in Power BI service using the steps mentioned above but i get the error message saying "This file isn't supported". Please let me know.

**Comment by maggiesMSFT** [comment]
Hi, @madhuzode -- thanks for asking! I've gotten the official word. You're right, paginated reports are currently not supported in the Power BI government cloud. That work is in progress. Thanks!
