### ISSUE TITLE
AI workload is missing

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/powerbi-docs#662]
There is a new Power BI Premium AI workload switch, but no documentation here about it.  Would be great if you could add that.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Manage capacities within Power BI Premium and Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage)
* Content Source: [powerbi-docs/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @chrisweis 
Good catch.  I'll pass this along to the article author and he'll get back to you asap. 
We appreciate your contribution to the Power BI docs.
Take care,
The Power BI DOCS team

**Comment by mgblythe** [comment]
Assigning to Minewiskan, who now owns this article.

**Comment by Minewiskan** [comment]
#in-progress

**Comment by Minewiskan** [comment]
@chrisweis - Thanks for your suggestion. AI features were not yet available on all PBI platforms when you initially made this GitIssue. Preview AI Cognitive Features were announced on March 11th. Updates to docs were made soon after to coincide.
#please-close
