### ISSUE TITLE
Link Typo

### ISSUE THREAD

**Issue by adamtappis** [MicrosoftDocs/powerbi-docs#663]
"PowerShell untilies" should presumably read Utilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3889030d-38f1-8788-119d-3615f7487f73
* Version Independent ID: f6b4aecd-1fc0-2b39-d1ac-27735f36329e
* Content: [Developer handbook overview, Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/developer-handbook-overview)
* Content Source: [powerbi-docs/report-server/developer-handbook-overview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/developer-handbook-overview.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @adamtappis -- good eye! I'm fixing it today. 
And did you know: For minor things like typos, you yourself can edit the doc. Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.
Thanks again!
cc @markingmyname

**Comment by maggiesMSFT** [comment]
@adamtappis -- fixed now. Thanks again!
cc @markingmyname
