### ISSUE TITLE
Add specifications for if or how Azure SQL Managed Instance could be used for PBI RS.

### ISSUE THREAD

**Issue by gcarder** [MicrosoftDocs/powerbi-docs#664]
We are considering a new deployment and the documentation does not currently specify if the database component for the report server can be on Azure SQL PaaS or Azure SQL Managed Instance.   We would prefer to not build a custom IAAS SQL Server instance just for Report Server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69db1b96-91ed-2440-5a1c-873a19d7ee47
* Version Independent ID: db0e2007-963b-44a5-9b6e-5be35481473e
* Content: [Install Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/install-report-server)
* Content Source: [powerbi-docs/report-server/install-report-server.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/install-report-server.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @gcarder . We’ve forwarded your feedback to the writer, who should respond to this thread shortly.

**Comment by maggiesMSFT** [comment]
Hi @gcarder -- thanks for your question! 
Support for this is in the works, but not expected in the near future. Sorry not to be more definitive. Best bet is to follow the Power BI product team blog, https://powerbi.microsoft.com/en-us/blog/
