### ISSUE TITLE
Power BI report server version numbers don't match each other or the changelog versions

### ISSUE THREAD

**Issue by robrien6** [MicrosoftDocs/powerbi-docs#665]
In the changelog for the January release(s) of the report server component we have these versions/builds:

Version 1.4.6969.7395 (Build 15.0.1102.235), Released: January 30, 2019
Version 1.4.6960.38798 (Build 15.0.1102.222), Released: January 22, 2019

Neither of those are shown in my Report server configuration manager having applied the first Jan release.  Report Server configuration manager show Product Version: 15.0.2.540

Furthermore when navigating to the web portal Help/About we see a much earlier build version:

Version 1.3.6801.38816 (August 2018)  [this is for the Jan release]

Please can these be aligned properly as it makes roll out/troubleshooting unnecessarily difficult.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef9c2df3-28df-34d8-bd4e-4209996f7f8d
* Version Independent ID: e5dc42c8-b17a-4e0e-09c5-76124b0ad924
* Content: [Changelog for Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/changelog)
* Content Source: [powerbi-docs/report-server/changelog.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/changelog.md)
* Service: **powerbi**
* GitHub Login: @jtarquino
* Microsoft Alias: **jtarquino**

**Comment by maggiesMSFT** [comment]
Hi, @robrien6 -- thanks for asking. I've assigned your question to the author, who will reply soon. Thanks!

**Comment by jtarquino** [comment]
Thanks, this have been updated for the latest release of PBIRS May

**Comment by maggiesMSFT** [comment]
Thanks, @jtarquino. Closing this issue now.
