### ISSUE TITLE
The new filter experience in Power BI - Export Excel hide filters

### ISSUE THREAD

**Issue by aidatain** [MicrosoftDocs/powerbi-docs#666]
Hi folks!

Awesome this new feature, congrats!! I have a question, in all of my all reports I have hidden filters (not showing in filter pane) and works great, but, when I export my data to a excel file (.xlsx) all applied filters are showing in my header file (image). I believe this header in excel should show only filters that not set a hidden filter. Will be awesome, because exists filters that end user can't see. 
![hide filter](https://user-images.githubusercontent.com/47067397/52421277-e1244b00-2ada-11e9-8266-0fb3903cc358.png)

**Comment by maggiesMSFT** [comment]
Hi, @aidatain -- thanks for asking! I'll check and get back to you when I have an answer.

**Comment by maggiesMSFT** [comment]
Hi, @aidatain -- I've confirmed this is a bug. I recommend that you go to https://ideas.powerbi.com/forums/265200-power-bi and search to see if anyone else has created an entry for it. If not, feel free to create one. Thanks for raising the issue!

**Comment by aidatain** [comment]
Thanks @maggiesMSFT for the analyze and answer. I just create a task in power bi community.
