### ISSUE TITLE
Pic #1 is tiny

### ISSUE THREAD

**Issue by jonaselreweny** [MicrosoftDocs/powerbi-docs#667]
Hi,
The first picture in this article is so tiny that it is next to impossible to see what it is trying to illustrate.

Please zoom in or make the picture clickable to get a larger version of the picture.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f09b043-ca4f-8d06-16b9-19f03e89b344
* Version Independent ID: 8166553d-853a-204d-b0bf-e7380d4042d6
* Content: [Manage capacities within Power BI Premium and Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-manage)
* Content Source: [powerbi-docs/service-admin-premium-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-manage.md)
* Service: **powerbi**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by maggiesMSFT** [comment]
Hi, @jonaselreweny -- thanks for asking! I've assigned your question to the author.

**Comment by Minewiskan** [comment]
@jonaselreweny - Agreed. Guidelines require this first image include the whole browser, which make it tough to get a large enough screen grab in an article like this, but I'll see what I can do.

**Comment by Minewiskan** [comment]
@jonaselreweny - Updated this image. This is about the best we can do here. Thanks for letting us know.
#please-close
