### ISSUE TITLE
The menu options have changed since this article was written.

### ISSUE THREAD

**Issue by hankluhring** [MicrosoftDocs/powerbi-docs#668]
The article says that if you click on Get Data, that under Online Services, there is an item called Power BI service. This is not true now. Now, if you click Get Data, instead of Online Services, you should click on a new item called Power BI. Then you can do what you set out to do. There is no "Power BI service" item under Online Services anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for pointing that out, @hankluhring. I'm forwarding your feedback to the writer, who should respond soon. Thanks!

**Comment by davidiseminger** [comment]
Okay - sorry about the inconvenience. We'll get that updated, and I'll leave this open until it's fixed. Thanks for submitting!

**Comment by davidiseminger** [comment]
Fixed, will update with the next publishing run. Thanks!
