### ISSUE TITLE
Embed reports -  Warnings: Some of your markup was stripped out. Try using the Embed command.

### ISSUE THREAD

**Issue by LarissaBoydston** [MicrosoftDocs/powerbi-docs#669]
I don't get the "click here to add new content" prompt when I add in a content editor.  This seems to be key because if I try to just edit source code from the format text menu, I will add the corect code, but then get an error message of;

Warning: Some of your markup was stripped out. Try using the Embed command.

Has anyone else seen this behavior? I've tried chrome and IE, as well as embedding PBI reports on my landing page or any other subsequent pages within my sharepoint site.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [Embed a report using an iFrame - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/quickstart-embed)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @LarissaBoydston -- Thanks for your comment. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.  Good luck resolving it!
