### ISSUE TITLE
Register an application speaks about delegated powerbi permissions

### ISSUE THREAD

**Issue by mganeshphani** [MicrosoftDocs/powerbi-docs#670]
Following section
https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal
refers to 
https://docs.microsoft.com/en-us/power-bi/developer/register-app
which further speaks about permissions to be granted... while the following blog says its not required
https://powerbi.microsoft.com/en-us/blog/use-power-bi-api-with-service-principal-preview/
"Note that AAD permissions are not required to be added"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mganeshphani** [comment]
you can close the issue.. looks like I was too fast in logging it before reading caution element

**Comment by maggiesMSFT** [comment]
Thanks for letting us know, @mganeshphani! I'm glad you were able to resolve the issue. I'll close this now.
