### ISSUE TITLE
Power BI Report Server does not support custom visuals created in R

### ISSUE THREAD

**Issue by SteveWinward** [MicrosoftDocs/powerbi-docs#671]
The docs should be updated to say that only custom visuals created in TypeScript/JavaScript are supported with Power BI Report Server.  Custom visuals that are written in R are not supported with Power BI Report Server.  

For example, the Clustering with Outliers visual will not work with Power BI Report Server.

https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380889?tab=Overview

**Comment by mgblythe** [comment]
Thanks for your comment, @SteveWinward ]. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by mgblythe** [comment]
@markingmyname - please route based on where an update/mention should go for this.

**Comment by markingmyname** [comment]
@SteveWinward, thanks for bringing this to our attention.

I will investigate where is the best place for this information.

Thank you.

**Comment by markingmyname** [comment]
@SteveWinward We do have this noted in the article - https://docs.microsoft.com/en-us/power-bi/report-server/compare-report-server-service.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
