### ISSUE TITLE
Adding Service Principal as workspace admin via API - how exactly ?

### ISSUE THREAD

**Issue by kumbol** [MicrosoftDocs/powerbi-docs#672]
The documentation quickly runs through this, but it has been my blocker so far trying this new method. 

"5. Add the service principal as an admin to the new workspace you created. You can manage this task through the APIs or with the Power BI service."

How do I actually do that when the exact API that is linked here (https://docs.microsoft.com/pl-pl/rest/api/power-bi/groups/addgroupuser) is requiring me to put email address of the user in the requests, body. Service principal, unless I'm mistaken, does not have an email address (or I can't find in in AAD). Trying to put in object id, both as a  emailAddress or as identifier fails. 

Any idea how to move past this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by eligr** [comment]
Hi, we just updated the documentation and added a sample for service principal:
https://docs.microsoft.com/en-us/rest/api/power-bi/groups/addgroupuser#example_for_giving_admin_access_right_to_a_service_principal

**Comment by kumbol** [comment]
Excellent, got it up & running now! Perfect! Thank you very much :-)

**Comment by markingmyname** [comment]
@kumbol, thank you for the feedback.

@eligr, Thank you for the update.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by craig-miller** [comment]
Latest example doesn't seem to work anymore.  principalType: "App" results in an error:

Parameter userDetails.PrincipalType is missing or invalid

{
  "identifier": "{Service Principle Object ID}",
  "groupUserAccessRight": "Admin",
  "principalType": "App"
}

**Comment by salasosvaldo** [comment]
It is not working for me, using REST API and doing a POST I get this error:
    "error": {
        "code": "PowerBIEntityNotFound",

**Comment by ulriksenstian** [comment]
Any update on this?

**Comment by shahanur** [comment]
It does not work with service principal. I also get the same error. code": "PowerBIEntityNotFound".

**Comment by coreyspagnoli** [comment]
I'm having the same issue trying to link my app to power bi through the API.  Has this been resolved?

**Comment by kjhangiani** [comment]
Also running into this exact issue above - the request looks fairly simple, but this does not seem to work.  Is there any update on this?

**Comment by kjhangiani** [comment]
Nevermind - figured it out.  The particular workspace I was testing it on was still using the old workspaces - after upgrading to new workspace (can you do that from the API?), everything worked as expected
