### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by Oddjobe** [MicrosoftDocs/powerbi-docs#673]
Hi, Just wanted to "ping" that the screenshot used is outdated.
https://dev.powerbi.com/Apps.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0fdbb42-7ed0-af9a-6a4b-ba2829923d25
* Version Independent ID: ffe2d9fd-6517-ee61-b907-482560075083
* Content: [Register an app with Azure AD - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-register-app-with-azure-ad)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-register-app-with-azure-ad.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-register-app-with-azure-ad.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Hi @Oddjobe 
Thank you for your feedback.  I've passed it along to the page author who will get back to you asap. 
We really appreciate your contribution to our docs.
The DOCS team

**Comment by markingmyname** [comment]
@Oddjobe, sorry for the delayed response.

The article has been updated and the changes should go live early next week.

Also, note this article will soon be deprecated as there is another article similar to this with more information. 

https://docs.microsoft.com/en-us/power-bi/developer/register-app

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
