### ISSUE TITLE
Status of Streaming datasets in PBI Embedded?

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#674]
I can't find any mention of streaming datasets (push, streaming, hybrid) in the embedded documentation. Are they supported, and if yes, to what extent (i.e. dashboards, dashboard tiles, visuals)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a447889-379d-3ded-9ab9-313c4f55a667
* Version Independent ID: 4f8e3f79-5025-919a-7282-8a63dda6bc8d
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq)
* Content Source: [powerbi-docs/developer/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-faq.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for your comment, @otravers. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by markingmyname** [comment]
@otravers, sorry for the delayed response.

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@otravers 

It is not yet available.  

However, please go to the ideas page and vote to make this feature a reality.

https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/19026709-allow-streaming-datasets-in-power-bi-embedded

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by markingmyname** [comment]
@otravers,

[Streaming datasets](https://docs.microsoft.com/en-us/power-bi/service-real-time-streaming) are supported in PBIE similarly to how they’re supported in Power BI service. 

If the user builds a dashboard with real-time tiles then they’ll get updated immediately in embedded mode as well.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by otravers** [comment]
Thank you @markingmyname, wouldn't it make sense to add your statement to the embedded faq?
