### ISSUE TITLE
Size of .pbix for P4, P5

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#69]
Hi! Two remarks:
1. Max size for P4\P5 plans in missed
2. Don't we have ability to upload up to 12 Gb in P3 after refreshes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67d4d246-073c-41e2-3940-8f84bcee9139
* Version Independent ID: 665dc73b-218f-18e4-6e5c-c093efbd7904
* Content: [Power BI Premium support for large datasets - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium-large-datasets)
* Content Source: [powerbi-docs/service-premium-large-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium-large-datasets.md)
* Service: **powerbi**
* GitHub Login: @jocaplan
* Microsoft Alias: **jocaplan**

**Comment by mgblythe** [comment]
Hi @chizhova - thanks for the questions. I'm checking with engineering to get information on this.

**Comment by chizhova** [comment]
Great, thank you!

2018-07-12 17:41 GMT+03:00 Michael Blythe <notifications@github.com>:

**Comment by dairecunningham** [comment]
Any update on this? What are the current max dataset size limits for the five nodes?

**Comment by markingmyname** [comment]
@dairecunningham Thanks so much for contacting us! The author of this article is away on vacation. I'll try to check into it.

**Comment by mgblythe** [comment]
Here's the info I added to the article: 

Power BI Premium supports uploads of Power BI Desktop (.pbix) files that are up to 10 GB in size. **Once uploaded, a dataset can be refreshed to up to 12 GB in size.**
P3, P4, P5 | up to 10 GB

Thanks @chizova
