### ISSUE TITLE
Utterly Lost

### ISSUE THREAD

**Issue by Scott-Phoenix** [MicrosoftDocs/powerbi-docs#70]
I don't know if I should have started someplace else, but a search landed me here. However, I can't make it past the 2nd sentence of the Simple Histograms section. I have no idea what's being references with the use of the "Reference option for the query". In fact, you don't even tell me to work in Power Query - I finally figured out that's where you are.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414d2796-4f3f-8ebe-c9b9-0445c4523b82
* Version Independent ID: d6906e43-5f47-9712-f08c-27ad5e2c2b82
* Content: [Histograms - Power BI](https://docs.microsoft.com/en-us/power-bi/service-histograms#simple-histograms)
* Content Source: [powerbi-docs/service-histograms.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-histograms.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@Scott-Phoenix  - sorry for the confusion with that article. Let me see if I can provide more clarity in that article and improve it. Thanks for your feedback, and sorry for the inconvenience.
