### ISSUE TITLE
Pin visual to a personnal dashboard

### ISSUE THREAD

**Issue by danievalle** [MicrosoftDocs/powerbi-docs#71]
I've read in a in the "Spring '18 Release Overview" (https://docs.microsoft.com/en-us/business-applications-release-notes/april18/release-overview) that you can pin visual from a shared report or an apps. But today if I try that I cannot because the pin is greyed-out with the message "read-only content can't be pinned". Which will be the case every time you share, because share is "read-only". 
The only workaround I see is to use a content pack to take the ownership of the report. But in a recent communication I saw that content pack will be replaced by APPS (which doesn't give me this flexibility).

Could someone from the Power BI team comment on this ?
Thanks in advance,
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eccfbc1d-74ab-9c0d-9fee-608508056da5
* Version Independent ID: 8c090f12-937c-b9cf-44db-c7014d9a9e23
* Content: [Pin a tile to a Power BI dashboard from a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-pin-tile-from-report)
* Content Source: [powerbi-docs/service-dashboard-pin-tile-from-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-pin-tile-from-report.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by tjmasters43** [comment]
Hi, kind of and old message but you cannot pin from the APP as its read only, must pin from the workspace.

**Comment by danievalle** [comment]
Hello,
So why it's written in the Release Note (page 263) https://aka.ms/dynamics365releasenotes.
Is this a upcoming feature ?
Thanks in advance.

**Comment by mihart** [comment]
Hi @danievalle ,
Thanks for pointing this out.  I'll contact the Release Notes author and have this updated.
