### ISSUE TITLE
Content pack vs apps

### ISSUE THREAD

**Issue by danievalle** [MicrosoftDocs/powerbi-docs#72]
Dear Power BI Team,
You plan to replace content packs by apps, which is totally understandable to keep only one way of sharing multiple contents. But if you do that, could you please explain me how and when you will add bellow missing functionalities in the apps:

- in the app it's not possible to use the dataset available in the same way than in the Content Packs. With the content pack you can reuse the dataset to create your own report (via Power BI Desktop and Service). The only feature available in the apps regarding dataset is the "Analyze in Excel. This is a non sense, why you can access through Excel and not trough Power BI Desktop ?
- in the app I cannot pin a visual to a dashboard. Despite what I've read in a in the "Spring '18 Release Overview" page 228 (https://docs.microsoft.com/en-us/business-applications-release-notes/april18/release-overview). If I try that I cannot because the pin is greyed-out with the message "read-only content can't be pinned". Which will be the case every time you share an element, because a share is "read-only".

Could someone from the Power BI team comment on this ?
Thanks in advance,
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ff3e88-8793-8e2b-bdb2-0e3d09372b93
* Version Independent ID: 0e1245cb-d7af-c73c-39c4-39f5665ae51a
* Content: [Create and publish apps with dashboards and reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-distribute-apps)
* Content Source: [powerbi-docs/service-create-distribute-apps.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-distribute-apps.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @danievalle -- thanks for your question! When we replace content packs with apps, apps will be changing, too. Stay tuned!
