### ISSUE TITLE
Numerical values mentioned is different from the image

### ISSUE THREAD

**Issue by rvenkata02** [MicrosoftDocs/powerbi-docs#73]
the documentation mentions "Let’s set Minimum to 20,000,000, and set Maximum to 20,000,000.". But, the image has different values. Documentation has to be updated to "Let’s set Minimum to 20,000,000, and set Maximum to 20,000,001."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@rvenkata02 - that's a great catch! I've fixed that, should be updated in the next day or so. Thanks!
