### ISSUE TITLE
Update required! New PDF available.

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs#732]
Hi, please update this page as it contains a link to a document dated 2016.
There is a new document available called "Planning a Power BI Enterprise Deployment" via:
https://docs.microsoft.com/en-us/power-bi/whitepapers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba176b5-d050-3be8-cc69-d8534b7e1982
* Version Independent ID: 8284cd12-eae5-29ea-7c19-3b6ef883355e
* Content: [Governance and deployment approaches - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-governance)
* Content Source: [powerbi-docs/service-admin-governance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-governance.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @DaveRuijter. I’ll add this request to our docs backlog.

**Comment by mgblythe** [comment]
Updated the link, thanks!
