### ISSUE TITLE
Dashboard Usage does not have values

### ISSUE THREAD

**Issue by RickFoster** [MicrosoftDocs/powerbi-docs#733]
The dashboard Paginated Report summary for views is blank however if I go to the Admin Portal is shows 480 views as the top report and though it does not show a total for the 115 reports, based on just adding up the top views it would be close to 10K, why doesn't the the dashboard show anything for usage?  It shows refresh data but not usage data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a289bc1e-c396-684c-4679-fbf5cde575f5
* Version Independent ID: 07e05427-08d7-5922-bf2e-f2a0d4166b02
* Content: [Monitor Power BI Premium capacities by using the admin portal - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-portal)
* Content Source: [powerbi-docs/service-admin-premium-monitor-portal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-portal.md)
* Service: **powerbi**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by mihart** [comment]
Hi @RickFoster ,
Thank you for your feedback.  I've assigned it to the doc author who will respond asap. 
However, you may want to post this question in the Power BI forums (community.powerbi.com), since it is more of a product question than a docs question. 
Take care,
The DOCS team

**Comment by Minewiskan** [comment]
@mihart @RickFoster - I don't see any doc issue here. This is more of a support issue or forums question.
#please-close

**Comment by Minewiskan** [comment]
@mihart 
#please-close
