### ISSUE TITLE
Powerbi Updates

### ISSUE THREAD

**Issue by Bluetaurean** [MicrosoftDocs/powerbi-docs#74]
I have been using PowerBI for over 2 years now and updating almost each month. the last few updates on a windows 10 pro system almost never go through without issues. and the last one just wont install! i have tried uninstalling the previous version, deleting registry entries, deleting folders of powerbi, running the uninstall fix utility, cleaning temp folders, program file directory, app data. just about everything. the error message is "the feature you are trying to use is on a network resource that is unavailable. click ok to try again or enter an alternative path to a folder containing the install package..... Note i also run my Powerbi on Citrix on the same the same computer (office computer)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#feedback)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@Bluetaurean - thanks for your feedback. That's an engineering issue, rather than docs, so please check in with support.powerbi.com and submit there, so hopefully someone can help you there.
