### ISSUE TITLE
Button state

### ISSUE THREAD

**Issue by dunxd** [MicrosoftDocs/powerbi-docs#75]
The current options for button state are Default state, On Hover and On Press.  What is really needed is a state that toggles when the button is pressed (and is reset to default when another button is pressed). On Hover is great to give feedback to the viewer that this is indeed a button.  On press isn't much use, as it only appears when at the point the button is pressed.  Buttons can only be used to open Q&A or view a bookmark.  Since bookmarks don't change the page, it would be really helpful to be able to see which bookmark is selected.  Or add a new control for selecting bookmarks which shows which is the current bookmark.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c379d7f1-f977-7906-c4ba-6f58ab47d785
* Version Independent ID: 088a4f2c-e571-1282-b265-9b90d4995505
* Content: [Using buttons in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-buttons)
* Content Source: [powerbi-docs/desktop-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-buttons.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@dunxd Thanks for your feature suggestion / request, adding other folks for visibility.

**Comment by DanielOverdevest** [comment]
@davidiseminger , this feature will help us a lot but we're not able to use this new feature. I updated PowerBI to the latest release September 2019 and if I create a new button and select "bookmark", go to Outline I see only the old 3 options: Default State, On Hover, On Press. Not the new "Selected" option. Can you have a look? Thanks!
