### ISSUE TITLE
Add Reserved Instances API to connector

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/powerbi-docs#76]
Add to 3 extra datasets to connector
Reserved Instance usage
Reserved Instance transaction charges
Reserved instance purchase recommendation 
https://docs.microsoft.com/en-us/rest/api/billing/enterprise/billing-enterprise-api-reserved-instance-usage

I know, that it's for Product Team, but maybe they will also look here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure Consumption Insights data in Power BI Desktop (Beta) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@SychevIgor - thanks for your suggestions. Try ideas.powerbi.com for submitting these request, they're more likely to get attention. Hope that helps!
