### ISSUE TITLE
New project creation location

### ISSUE THREAD

**Issue by AnirudhKishan** [MicrosoftDocs/powerbi-docs#774]
'Creating a custom visual' 'Step 3' should call out that the new project would be created at the current location of the prompt. Also, to cd to a new location, if required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Developing a Power BI Custom Visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Hi @AnirudhKishan ,
Thank you for your suggestions.  I've forwarded this to the doc author who will respond asap.
We appreciate your input!
The DOCS team

**Comment by markingmyname** [comment]
@AnirudhKishan This has been addressed.  The update should be merged by the end of the end of te week.

Thank you for the feedback.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
