### ISSUE TITLE
Useless without the ability to analyze measures or simple aggregate dimensions

### ISSUE THREAD

**Issue by DaveStabilify** [MicrosoftDocs/powerbi-docs#779]
Useless without the ability to analyze measures.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @DaveStabilify ,
Thank you for your suggestion.  I believe the Product team is planning updates to this brand new feature. Please post product suggestions and questions in the Power BI forums:  community.powerbi.com.
Take care,
The DOCS team

**Comment by juluczni** [comment]
@DaveStabilify we are finalizing the work on measures with key influencers. Would you be willing to jump on a call to see if the updates we are making meet your needs?
