### ISSUE TITLE
Removal of anchor gateway

### ISSUE THREAD

**Issue by asocorro** [MicrosoftDocs/powerbi-docs#780]
What happens is the anchor gateway in a cluster is removed?  Will one of the other gateways be promoted to anchor?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87176394-a2d4-7e3d-922e-d124d59fe9c5
* Version Independent ID: 99c3109b-b094-1300-86e2-0cebb4475169
* Content: [Manage a Power BI on-premises gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-manage#remove-a-gateway)
* Content Source: [powerbi-docs/service-gateway-manage.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-manage.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Hi @asocorro ,
Thank you for your question.  I've forwarded it to the doc owner who will respond asap.
I also suggest posting this question in the Power BI forums (community.powerbi.com), since this is more of a product question than a docs question. 
Take care,
The DOCS team

**Comment by mgblythe** [comment]
Thanks @asocorro, great to hear from you -- we cover this in https://docs.microsoft.com/en-us/power-bi/service-gateway-high-availability-clusters: "The Power BI service always uses the primary gateway in the cluster, unless it’s not available. In that case, the service switches to the next gateway in the cluster, and so on."
