### ISSUE TITLE
Ability to stop users from "removing" a filter

### ISSUE THREAD

**Issue by SPowell42** [MicrosoftDocs/powerbi-docs#783]
We'd like the ability to turn off the "X" icon in the top right of a filter pane that allows a user to completely delete a filter. They can either use the "clear" eraser icon or "select all"...but if they delete a filter, they have hard time figuring out how to get it back. Would be better if they could only "clear" the filter but not completely remove it.

Thanks,
Scott

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 169f0fd8-5f91-c727-863e-775092492219
* Version Independent ID: f2870679-e514-3e52-3513-eb62c81983c7
* Content: [The new filter experience in Power BI reports (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-report-filter-preview)
* Content Source: [powerbi-docs/power-bi-report-filter-preview.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-report-filter-preview.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @SPowell42 ,
Thank you for your feedback.  I've assigned your suggestion to the doc author who will respond asap.  I also suggest that you submit this as a question on the Power BI forum (community.powerbi.com) and/or suggest this as a new idea (ideas.powerbi.com).  
Take care,
The DOCS team

**Comment by rdgbrito** [comment]
@SPowell42, tottaly agree!!!

**Comment by maggiesMSFT** [comment]
Hi, @SPowell42 and @rdgbrito -- good idea! As @mihart says, the place to submit ideas is at https://ideas.powerbi.com/forums/265200-power-bi-ideas. The product team pays a lot of attention to the ideas submitted there. Good luck!
