### ISSUE TITLE
Oracle.DataAccess.Client is not installed

### ISSUE THREAD

**Issue by scooleo** [MicrosoftDocs/powerbi-docs#784]
Hi, 
I have installed multiple Oracle drivers on multiple machines that all use PowerBi x64. Tableau, sqlplus and oracle SQL connect perfect. I followed the guide to the letter and spent way too many hours trouble shooting this now.  The current version of Oracle on my "virgin" home machine is ODAC122010Xcopy_x64. I installed from an Admin command screen using the following command c:\&gt; install.bat all c:\oracle myhome true    
..I also installed PowerBI for the first time on my virgin home machine after the oracle drivers were installed and still get the recommended provider (Oracle.DataAccess.Client) is not installed.....
I have tried this on two other work machines with different Oracle Drivers - I even got one of the work machines completely reimaged. It is very frustrating now!
Any help would be greatly appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Connect to an Oracle database - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-oracle-database#troubleshooting)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @scooleo ,
Thank you for your question.  I've assigned this to the doc author, who will respond asap. I'm not an expert in this area, but this does sound like a Product question and not a Docs question.  So you may want to post this on the Power BI forum (community.powerbi.com) as well. 
Take care,
The DOCS team

**Comment by scooleo** [comment]
Thanks a million Michele, much appreciated!

**Comment by davidiseminger** [comment]
Thanks for your comment, @scooleo. This is a support request rather than documentation feedback, and I'm sorry but we can't support you in this format/forum. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by dhimanaddress** [comment]
You can try to use the following link, it worked for me where I was facing the same issue:
http://download.oracle.com/otn/other/ole-oo4o/ODAC121024_x64.zip

**Comment by kritchens** [comment]
> 
> 
> You can try to use the following link, it worked for me where I was facing the same issue:
> http://download.oracle.com/otn/other/ole-oo4o/ODAC121024_x64.zip

I can Confirm this worked. It seems there has to be a specific version of Oracle Client installed to run correctly.
