### ISSUE TITLE
Suggestion and correction.

### ISSUE THREAD

**Issue by aghonaim** [MicrosoftDocs/powerbi-docs#786]
in the Top single factor influencing likelihood of a low rating definition, I suggest changing the wording from (difference between green bar and red dotted line) to (the green bar over/divided by the red dotted line).
Also in the Second single factor influencing likelihood of a low rating, the usability of the product were (2.21x) should be (2.55x) according to the visual.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#top-single-factor-influencing-likelihood-of-a-low-rating)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Dear @aghonaim ,
Thank you for your feedback. I'll review the article and update per your suggestions.
I really appreciate your contribution to our docs.
Michele

**Comment by mihart** [comment]
Hi @juluczni ,
Would you please review this feedback?  Thanks,
@mihart

**Comment by mihart** [comment]
Hi @aghonaim ,
Both of these changes have been made.  Thank you for bringing this to our attention and I apologize for the delay.
