### ISSUE TITLE
No checkbox about "Under Report settings, select Enable the updated filter pane, and show filters in the visual header for this report."

### ISSUE THREAD

**Issue by maxdomico** [MicrosoftDocs/powerbi-docs#787]
I can't find the option "Under Report settings, select Enable the updated filter pane, and show filters in the visual header for this report." under the Report settings, is that issue?

**Comment by mgblythe** [comment]
Thanks for your comment, @maxdomico. We’ve forwarded your feedback to the writer, who should respond to this thread.

@maggiesMSFT - this is for power-bi-report-filter-preview.md

**Comment by maggiesMSFT** [comment]
Hi, @maxdomico -- If you go to **File** > **Options and settings** > **Options**, do you see **Report settings** in the left navigation bar under **Current file**? 
If you do, then select **Report settings**, and under **Filtering experience**, select **Enable the updated filter pane, and show filters in the visual header for this report**.
Does that work for you now?
thanks!

**Comment by maggiesMSFT** [comment]
Oh, I meant to add, I've added that more specific language to the article, so thanks for your feedback!
