### ISSUE TITLE
Dataset being explained is not available in the explanation page.

### ISSUE THREAD

**Issue by viswanath-puttagunta** [MicrosoftDocs/powerbi-docs#788]
Hi,

The videos and notes are awesome. But I want to follow along on my own Power BI desktop. So, I need the CSV files that the lesson is based on.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [Modeling - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/modeling?tutorial-step=8)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @viswanath-puttagunta. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by davidiseminger** [comment]
Thanks for your nice comments @viswanath-puttagunta. The CSV files for that article aren't available, but when we update it, we'll make sure that we also include the file. Sorry for the inconvenience.
