### ISSUE TITLE
Report cant display any visuals

### ISSUE THREAD

**Issue by OskariNi** [MicrosoftDocs/powerbi-docs#789]
I have a few workspaces in premium capacity and I would like to monitor their performance. However, all of the visuals fail to display anything. 

Could you take a look at this?

BR. Oskari

Couldn't load the data for this visual
The expression referenced a relationship between 'RefreshMetrics'[datasetId] and 'DatasetInfo'[id], which does not hold any data because it needs to be recalculated.
Please try again later or contact support. If you contact support, please provide these details.
Activity ID: 0949fe85-e5cf-40e1-9e30-4438b4267177
Request ID: 28c09cbb-d84f-0895-abc5-b57f525412d7
Correlation ID: cfacca63-742c-1d04-d575-16941ab42cfe
Time: Wed Feb 13 2019 16:27:21 GMT+0200 (Eastern European Standard Time)
Version: 13.0.8309.200
Cluster URI: https://wabi-north-europe-redirect.analysis.windows.net

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by mgblythe** [comment]
Thanks for your comment, @OskariNi. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
