### ISSUE TITLE
Color saturation is obsolete

### ISSUE THREAD

**Issue by aabundez** [MicrosoftDocs/powerbi-docs#790]
This page still shows the Color Saturation option in column charts which is now called "Advanced controls" in the Data colors formatting option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3066fc06-cbb2-def8-1505-cccbb818c147
* Version Independent ID: aedfaa65-1253-f7f0-c0bd-2c89bc0a21f5
* Content: [Tips and tricks for color formatting in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-tips-and-tricks-for-color-formatting)
* Content Source: [powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-tips-and-tricks-for-color-formatting.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @aabundez. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by mihart** [comment]
Thank you @aabundez .  I am in the process of updating that article to reflect the new formatting options.

**Comment by BrianBeswick** [comment]
Can you also have the author explicitly indicate that you need an axis value, and only a single value series for this to work? Multiple value series and/or no axis the advanced data colors are not available.
