### ISSUE TITLE
embedded?

### ISSUE THREAD

**Issue by Hansonaplane** [MicrosoftDocs/powerbi-docs#793]
Does "embedded" in the bullet point "Consuming the visual in embedded" refer to Power BI Embedded? If yes, I would highly recommend to use the proper name of the service instead of shortening it in order to improve the clarity of the statement. At the moment, "embedded" is not even capitalized so it might be very distracting for new users since the sentence does not really make sense with "embedded" if you don't know there's a service called "Power BI Embedded".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by Hansonaplane** [comment]
(The same goes for "Power BI mobile" in the next bullet point where "mobile" should also be capitalized.)

**Comment by maggiesMSFT** [comment]
Great questions, @Hansonaplane. I defer to the author for the question about 'embedded.' 
For 'mobile,' it shouldn't be capped, but I'll suggest rephrasing it to: 
"Consuming the visual in the Power BI mobile apps"
Thanks for the careful read!

**Comment by juluczni** [comment]
Great points, making the changes now.

**Comment by Hansonaplane** [comment]
"Power BI Mobile" is actually a thing, see https://www.microsoft.com/en-us/p/power-bi-mobile/9nblgggzlxn1?activetab=pivot%3Aoverviewtab
I am just not sure if this was meant here or not, but I guess it is.

**Comment by mihart** [comment]
Hi @Hansonaplane and @juluczni ,
Made the 2 updates to the article.  Thanks everyone for the updates!
Michele
