### ISSUE TITLE
GA date / Read Role in workspace

### ISSUE THREAD

**Issue by MartinaPD** [MicrosoftDocs/powerbi-docs#794]
Hi, 
in one of your pages https://powerbi.microsoft.com/en-us/blog/enable-your-team-with-new-workspaces-experiences-preview/ I found that Viewer Role is available at GA(General Availability).  In the Closed comments section I found that  GA date is still not available ( 1-2 month ago). 
Can you share expected timeline? Even if it would be "not for another 6 months".... Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Hi @MartinaPD - based on the [release notes](https://docs.microsoft.com/business-applications-release-notes/April19/business-intelligence/planned-features), the current plan is May 2019.
