### ISSUE TITLE
Scrolling through model

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#795]
@Jasper8888 commented on [Thu Feb 14 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/19)

Hi, 
It would be usefull if one can scroll through a model by left-click on the canvas and hold the button. Mouse movement will now navigate through the model. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f4cfe8c6-b047-1277-8726-0d45d3630b8d
* Version Independent ID: b2e24404-209e-f043-b749-2e2e865a9e79
* Content: [Modelweergave in Power BI Desktop gebruiken (preview) - Power BI](https://docs.microsoft.com/nl-nl/power-bi/desktop-modeling-view)
* Content Source: [powerbi-docs/desktop-modeling-view.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/desktop-modeling-view.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hi team, 
The user is making a suggestion on the functionality of the product. 
best

**Comment by mgblythe** [comment]
Thanks @CeciAc. @Jasper8888 - You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.
