### ISSUE TITLE
Licensing Section is incorrect

### ISSUE THREAD

**Issue by dejadee** [MicrosoftDocs/powerbi-docs#796]
When working with Microsoft support, we found out that having the content in a workspace that's in a Power BI Premium capacity was insufficient. If you have the "install app automatically" box checked, you ALSO have to make sure that all viewers have the "Power BI (free)" license. Otherwise they will see the "This content isn't available" screen. 

See also this thread: https://community.powerbi.com/t5/Service/Power-BI-Premium-Embed-SharePoint-Online/td-p/230064

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Embed with report web part in SharePoint Online - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for your comment, @dejadee. We’ve forwarded your feedback to the writer, who should respond to this thread.

**Comment by markingmyname** [comment]
@dejadee Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@dejadee,

sorry for the delayed response.

does this note that is already in the article, not suffice?

**Comment by dejadee** [comment]
@markingmyname,

The note is sort of misleading. In the scenario I've outlined in my original comment--Power BI Premium capacity workspace, "install app automatically" is checked--if a user does not have a Power Bi (free) license, but is given a link to the Power BI app then upon logging into Power BI, they are automatically assigned a Power BI (free) license so they can view the app without any issues. So the user "has access to the Power BI app."

But suppose that same user didn't click on the link directly to the Power BI app (or another user in the same group that the app is shared with). Suppose they are trying to view the app report which is embedded in SharePoint. In this scenario, they will NOT be automatically assigned a Power BI license. So they get a "this content isn't unavailable" error. That is, until an administrator manually assigns them a Power BI (free) license. Because this is a manual step that has to happen for the functionality described in the article, I think it should be added to the list of steps in the "Grant access to reports" section. Or at least in the "Known issues and limitations" section.

**Comment by markingmyname** [comment]
@dejadee 

Thank you for clarifying that in more details.

I am in current discussions about this scenario.  Once I have an update I will let you know.

Again, thank you for bringing this to our attention.

**Comment by markingmyname** [comment]
Hi @dejadee,

I wanted to inform you that there will be no changes made to the article at this time.

the information is clear that you have to have access to both Power BI and SP to access the app.

If you feel this needs more clarification from the Product Group, please select the Product issue button.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
