### ISSUE TITLE
Please document odata version #

### ISSUE THREAD

**Issue by ianbruckner** [MicrosoftDocs/powerbi-docs#798]
Please document odata version #

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data)
* Content Source: [powerbi-docs/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Adding another assignee to resolve.

**Comment by mgblythe** [comment]
We don't have the specific version info. Power BI relies on Project OData endpoints and uses the generic OData connector.
