### ISSUE TITLE
Article is outdated

### ISSUE THREAD

**Issue by saket90** [MicrosoftDocs/powerbi-docs#799]
Hi,
The article states  - "The Export to PDF feature is only available with Power BI Desktop, and is not currently available in the Power BI service."
However, we do have the feature available in Power BI Service. Could you please update this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export your reports to PDF format from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-export-to-pdf)
* Content Source: [powerbi-docs/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-export-to-pdf.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @saket90 and thanks for your comment. This has been assigned to the author for review.

**Comment by davidiseminger** [comment]
Thanks for pointing this out @saket90 - I've updated that article, which should refresh in the next day or so. Thanks!

**Comment by saket90** [comment]
Thanks David!
