### ISSUE TITLE
Publish date

### ISSUE THREAD

**Issue by Wobyn** [MicrosoftDocs/powerbi-docs#80]
Good design + fast to consume. Would like to see a publish date, so I know how current the information is given the "plan to deprecate organizational content packs soon".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbffbf18-2789-7aaa-6f21-08a2a8dd018f
* Version Independent ID: 759b3f52-ab4a-176e-5be3-6e9dc062ca82
* Content: [Publishing and sharing - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/publishingandsharing?tutorial-step=13)
* Content Source: [powerbi-docs/guided-learning/publishingandsharing.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/publishingandsharing.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@Wobyn - thanks for the feedback! A publish date would definitely be beneficial, I'll pass that request on.
