### ISSUE TITLE
No documented relationship between Visual and Card

### ISSUE THREAD

**Issue by tpdsl** [MicrosoftDocs/powerbi-docs#800]
Unless I'm missing something, there doesn't seem to be a documented relationship between Visual and Card when creating JSON for a customer theme.

In other words, given a Visual, how do you determine which cards can be set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @tpdsl. Thanks for your comment. The issue has been assigned to the author for review.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
