### ISSUE TITLE
New Workspaces not Sharable in Teams Tabs?

### ISSUE THREAD

**Issue by JustinGrote** [MicrosoftDocs/powerbi-docs#801]
Hello,

I created one of the new workspaces, but when I try to add a report to the corresponding teams site by clicking + and then PowerBI, the new workspace is not visible in the list, only my "classic" ones.

Is this a known preview limitation? I gave the team rights to view in PowerBI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Hi @JustinGrote and thanks for your comment. I've assigned this to the author of the doc but it may end up going to our product group to answer the question about functionality. Thanks in advance for your patience.

**Comment by maggiesMSFT** [comment]
Hi, @JustinGrote -- sorry for the delay! This functionality works for me -- I can see new workspaces in Teams. Closing the issue. You can reopen if necessary.
Thanks!
