### ISSUE TITLE
Power PI App icon image requirements

### ISSUE THREAD

**Issue by dsgg18** [MicrosoftDocs/powerbi-docs#802]
Please provide detailed information regarding the app icon image requirements (size, accepted formats, other). This information should be included in the documentation.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54452a1b-613f-5718-a6bd-16429fdfc678
* Version Independent ID: 3352343d-b326-4f63-5c37-51403d8f6358
* Content: [Create workspaces with your colleagues in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-workspaces#add-an-image-to-your-office-365-app-workspace-optional)
* Content Source: [powerbi-docs/service-create-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Hi @dsgg18 and thanks for your comment. The issue has been assigned to the author for review.

**Comment by maggiesMSFT** [comment]
Hi, @dsgg18 -- I'm investigating and will report back.

**Comment by maggiesMSFT** [comment]
Hi, @dsgg18 -- Thanks for asking! Here are the results of my research. 

Old workspaces:
Whatever Office 365 groups support. I found these work:
File formats: png, jpg, bmp. 
File size: Not sure what the upper limit is, but I was able to upload a 3 MB png file.
 
New workspaces:
File formats: .png and .jpg 
File size: < 45 KB

thanks for asking! I'll add this info to the articles in question.

**Comment by maggiesMSFT** [comment]
Hi, @dsgg18 -- I've updated both articles (new and classic) with these specifics. Thanks for asking!
