### ISSUE TITLE
Failed to resolve name 'AI.SAMPLESTRATIFIED'. It is not a valid table, variable, or function name

### ISSUE THREAD

**Issue by compkos** [MicrosoftDocs/powerbi-docs#803]
Hello
I get this error on PowerBi Desktop February 2019 release when try above example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfile** [comment]
Hi @compkos and thanks for your comment. The issue has been assigned to the author but it may be a product issue - she will need to determine this and it may take additional time to troubleshoot.

**Comment by mihart** [comment]
@juluczni 
Hi Justyna, Can you help us with this?
Thanks,
Michele

**Comment by juiko** [comment]
I'm still getting this same issue on the March release of PowerBI Desktop. The data set itself is not the issue, as the visualisation works fine when loaded to PowerBI Service.

**Comment by EoinTheForge** [comment]
Same issue

**Comment by juluczni** [comment]
Hi everyone, we released a number of updates that should have dealt with the problem described above. If you are still hitting that problem could you please reach out to me on juluczni@microsoft.com Thanks!

**Comment by mihneanichifor** [comment]
Hi, 
I get the same issue on POWER BI Version: 2.71.5523.941 64-bit (July 2019). 
Updated .Net Framework to 4.8 as found here (https://community.powerbi.com/t5/forums/replypage/board-id/power-bi-designer/message-id/338022 ) without success. 

Any advice ?

thanks,
M

**Comment by jiezhao9** [comment]
> Hi everyone, we released a number of updates that should have dealt with the problem described above. If you are still hitting that problem could you please reach out to me on [juluczni@microsoft.com](mailto:juluczni@microsoft.com) Thanks!

Hi juluczni, could you let us know the version of release that including the fix for the above problem?   Thanks in advance!
