### ISSUE TITLE
How do you pass a query string parameter to an SSRS report published to Power BI?

### ISSUE THREAD

**Issue by dmbeas12** [MicrosoftDocs/powerbi-docs#804]
My SSRS RDL report displays correctly in Power BI, and I have a "PN" parameter built into the report. I need the ability to pass a unique PN number when the report first loads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 829630fd-6378-a8d1-dee5-140b43ddb9b3
* Version Independent ID: 8e7790f6-2a6d-f68c-3969-b177548ba74d
* Content: [View parameters for paginated reports in the Power BI service (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-view-parameters)
* Content Source: [powerbi-docs/paginated-reports-view-parameters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-view-parameters.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by kfile** [comment]
Hi @dmbeas12 and thanks for your comment. I've assigned this to the doc author but she may need to get help from engineering to address your question. Please be patient with our response. Thanks.

**Comment by maggiesMSFT** [comment]
Hi, @dmbeas12 -- thanks for your question! Paginated reports in the Power BI service don't yet support query string parameters. You can https://ideas.powerbi.com/forums/265200-power-bi and submit a vote for the idea!
