### ISSUE TITLE
Premium licensing information missing

### ISSUE THREAD

**Issue by viradu** [MicrosoftDocs/powerbi-docs#805]
I've received questions on this article from my customers. The article mentions requirements for a Pro license, however it is Possible for Free users to consume R visuals in reports hosted in Premium workspaces. So Managed tenant with free license / View visuals in report should be changed from Not Supported to Premium only (or something similar).

Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90c7931b-9fbb-bec4-09c4-9c827e4ec7a1
* Version Independent ID: 7ebc1400-482b-62e6-3747-bb7ffdb1dcf3
* Content: [Create advanced analytics and visualizations using R scripts - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals)
* Content Source: [powerbi-docs/visuals/service-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/service-r-visuals.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by kfile** [comment]
HI @viradu and thanks for the question. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @viradu ,
Thank you for catching that.  I've updated the chart per your suggestion.
We really appreciate your contribution to our docs.
The DOCS team
