### ISSUE TITLE
Preview Workspace: No "Files" option under the elipsis "..."

### ISSUE THREAD

**Issue by jsh121988** [MicrosoftDocs/powerbi-docs#806]
I'm not seeing an option to open the Workspaces SharePoint files. If Sharepoints are no longer being created with the Workspace then it will be a huge hassle to have to create a SharePoint in addition to every workspace. We currently use the SharePoint behind the Workspace to store all of our source pbix files, and manage version history.

It is a requirement that SP is enabled, and I'm deleting my new workspace immediately to create a old workspace.

New:
![image](https://user-images.githubusercontent.com/11296487/52880501-ffabc700-3116-11e9-8c81-6584e88b4605.png)

Current:
![image](https://user-images.githubusercontent.com/11296487/52880443-dab75400-3116-11e9-8cd2-b399b59e36f4.png)

**Comment by markingmyname** [comment]
@jsh121988 Thank you for the feedback.  Can you provide the exact article link, so we may assign this to the proper author?

Thank you.
