### ISSUE TITLE
Important omission from Limitations and Considerations

### ISSUE THREAD

**Issue by orygreg** [MicrosoftDocs/powerbi-docs#807]
Certainly a great feature.  We took advantage of it so we wouldn't have many copies of the same data model, one for each report.  HOWEVER, when it came time to setup automated deployments using PBI's REST API from within Power Shell script, we were disappointed (understatement!) to learn that reports which share a dataset on the PBI service are NOT supported.  Please include this in the Limitations and Considerations so that other users who want to deploy with REST API don't waste their time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @orygreg,
Thank you for the feedback and the suggestion.  I've forwarded this along to the article author and he will get back to you asap.
Take care,
The DOCS team

**Comment by davidiseminger** [comment]
Adding another assignee to review.

**Comment by docgregt** [comment]
This is very cool until you run into the REST API limitation. Then it becomes useless when supporting a multiclient environment where you want to clone reports to different workspaces assigned to different clients.

**Comment by alitwaij** [comment]
I am surprised that we cannot mix datasources with this on the same model. Would be a very useful feature if it was there. So that we can bring in our own lookup tables and use them in conjunction with the live dataset.

**Comment by mgblythe** [comment]
@davidiseminger - assigning back to you, reassign as appropriate.

**Comment by davidiseminger** [comment]
Added that limitation - thanks for bringing it to our attention. Will show up in the article within 24 hours.
