### ISSUE TITLE
Direct Query limitation to one data source is outdated -> Composite Models

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs#808]
Composite models (https://docs.microsoft.com/en-us/power-bi/desktop-composite-models) are allowing the combination of multiple direct queries or direct query with import. The documentation states the limitation to one data source für DQ on multiple pages!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed1625f-12a2-5962-2959-696188711efe
* Version Independent ID: d8796367-6bd1-c63c-db86-59eb5a66c213
* Content: [Using DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about)
* Content Source: [powerbi-docs/desktop-directquery-about.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-about.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @mpoeckl 
Thank you for your feedback.  I've forwarded it along to the article author and he will respond asap.
Take care,
The DOCS team

**Comment by davidiseminger** [comment]
Thanks for pointing this out @mpoeckl - we reviewed and updated those articles recently with those changes, and I believe we got them all. Appreciate the close read!

**Comment by nstraw** [comment]
As pointed by @mpoeckl, this statement is not true : "When selecting DirectQuery for a source, it will then only be possible to use data from that single source (such as a single SQL Server database)"

Direct link : https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about#limited-to-a-single-source

**Comment by wdehaas** [comment]
@mpoeckl I think the article is not updated. Single Source Paragraph is not true anymore because now Power BI Support Mixed Storage Mode.
