### ISSUE TITLE
Limitation to one data source is outdated -> composite models

### ISSUE THREAD

**Issue by mpoeckl** [MicrosoftDocs/powerbi-docs#809]
A composite model (https://docs.microsoft.com/en-us/power-bi/desktop-composite-models) allow the combination of multiple direct querie data sources or direct query with import sources. The documentation states the limitation to one data source für DQ on multiple times!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Dear @mpoeckl ,
Thank you for your feedback.  I've assigned this issue to the author and he will respond asap.
Take care,
The DOCS team

**Comment by davidiseminger** [comment]
Thanks - recent updates refreshed that article, and I don't see any more references to that limitation.
