### ISSUE TITLE
Confusing description of sharing options

### ISSUE THREAD

**Issue by jcbowyer** [MicrosoftDocs/powerbi-docs#81]
"If you want to share any of your content, you have several choices: create an app workspace where you bundle content into an app and make it available to others in your organization, or create an app workspace and give colleagues access to that workspace so you can share and collaborate."   Is this supposed to say create an app workspace or an app workspace?  Perhaps it is mean to refer to content packs which is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f7e98b-d12a-5896-50c4-bd33f63481d0
* Version Independent ID: a1ccb451-0ba0-f4b5-63eb-22b62fcc93f6
* Content: [Power BI service- basic concepts - Power BI](https://docs.microsoft.com/en-us/power-bi/service-basic-concepts)
* Content Source: [powerbi-docs/service-basic-concepts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-basic-concepts.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @jcbowyer -- good point. It should explain that you can create an app workspace, then you have two options: either add coworkers to the workspace so you can collaborate, or create an app from the workspace and distribute that to others. Does that make more sense? I can update the article to better explain.

**Comment by maggiesMSFT** [comment]
I'll update the article. Thanks, @jcbowyer!
