### ISSUE TITLE
Time filtration based on hours and minutes

### ISSUE THREAD

**Issue by N389ER** [MicrosoftDocs/powerbi-docs#810]
Hi! Is it possible to include a filter that you can filter down to hour or minute increments? From the example dataset: sales between 07:00-08:00 for example.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [Modeling - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/modeling?tutorial-step=8)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @N389ER 
Thank you for your feedback.  I've forwarded your question to the doc author and he will get in touch asap. 
Take care,
The DOCS team

**Comment by davidiseminger** [comment]
Hello @N389ER  - looks like this is a product question rather than docs feedback. You can get support from the community (community.powerbi.com) or support.powerbi.com to get an answer to your question.
