### ISSUE TITLE
Visualization Error

### ISSUE THREAD

**Issue by jford369** [MicrosoftDocs/powerbi-docs#811]
I see an error message "The visual is not supported." I've tried multiple combinations of fields. What does this error message mean and what can I do to troubleshoot it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @jford369 ,
Thank you for your feedback.  I've assigned this to the doc author and she will respond asap.
Take care,
The DOCS team

**Comment by mgblythe** [comment]
@jford369 -- did you get anywhere with this problem? Were you able to use the visual at all?

**Comment by jford369** [comment]
The issue for me was that the storage mode was mixed, has to be an entirely import data model to work. Some indication of that in the error message itself or on this page would have saved me some time though.

**Comment by mgblythe** [comment]
Thanks @jford369. Closing this out, but @juluczni as FYI in case we can improve the error message.
