### ISSUE TITLE
Issue with API Call.

### ISSUE THREAD

**Issue by bradfarley** [MicrosoftDocs/powerbi-docs#812]
My connection continually times out (Server 500 error). Looking more into it, the app's date_macro=all call is not valid. It works intermittently. 

From intuit's documentation: 

date_macro: (Optional) String

Predefined date range. Use if you want the report to cover a standard report date range; otherwise, use the start_date and end_date to cover an explicit report date range. Supported Values: Today, Yesterday, This Week, Last Week, This Week-to-date, Last Week-to-date, Next Week, Next 4 Weeks, This Month, Last Month, This Month-to-date, Last Month-to-date, Next Month, This Fiscal Quarter, Last Fiscal Quarter, This Fiscal Quarter-to-date, Last Fiscal Quarter-to-date, Next Fiscal Quarter, This Fiscal Year, Last Fiscal Year, This Fiscal Year-to-date, Last Fiscal Year-to-date, Next Fiscal Year

Additionally, we should have an additional endpoint:

"The QuickBooks Reports API response for the General Ledger report hierarchy is broken in certain circumstances when there are sub accounts configured in the QuickBooks Online company. Invoke the report endpoint with the minorversion=3 query parameter to get a well-formed, correct response."

Ultimately, I think we need to add Date Selections to the App, instead of the Date_macro

start_date end_date (Optional) String

The start date and end date of the report, in the format YYYY-MM-DD. start_date must be less than end_date. Use if you want the report to cover an explicit date range; otherwise, use date_macro to cover a standard report date range. If not specified value of date_macro is used.

Example: BaseURL/v3/company/1386066315/reports/GeneralLedgerFR?minorversion=3&start_date=2015-01-01&end_date=2015-06-30&...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mihart** [comment]
Hi @bradfarley 
Thank you for this detailed feedback.  I've forwarded it to the author and she will be in tough asap.
Take care,
The DOCS team

**Comment by bradfarley** [comment]
@mihart @SarinaJoan  Closing the loop: I've been in touch with the engineering team for the app. Sounds like an update is in the works. Have you made any headway or have any status from your efforts?

**Comment by acumencds** [comment]
@bradfarley do you know when this will be out as I have an Issue: an number of Account Sub Types are not in the data set. Namely; expenses -‘Commissions and fees’ and ‘Staff costs’, Income – ‘Revenue - General’. There may be more but these are the ones I have found so far that give incorrect reports for our data.

**Comment by SarinaJoan** [comment]
Hi @bradfarley, thanks for bringing this up. We are close to releasing this content pack as a template app, would you be open for a chat to see if these issues still show in the new app?
