### ISSUE TITLE
Power View Link

### ISSUE THREAD

**Issue by daveeasey** [MicrosoftDocs/powerbi-docs#813]
The link to enable the Power View add-in does not lead to anything about Power View.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Take a tour of the samples available with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-datasets)
* Content Source: [powerbi-docs/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-datasets.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Hi @daveeasey ,
Thank you for your feedback, we really appreciate it.  I've assigned this to the doc author who will respond asap.
Take care,
The DOCS team

**Comment by maggiesMSFT** [comment]
Hi, @daveeasey -- Thanks for pointing that out! Looks like Excel moved their article about Power View. I found the link: https://support.office.com/en-us/article/power-view-overview-and-learning-5380e429-3ee0-4be2-97b7-64d7930020b6. 
I'll update the article when I return from a business trip.
Thanks again!

**Comment by maggiesMSFT** [comment]
Hi, @daveeasey -- I updated the article with a new link. Thanks for pointing that out! Here's the link: https://support.office.com/article/flash-silverlight-and-shockwave-controls-blocked-in-microsoft-office-55738f12-a01d-420e-a533-7cef1ff6aeb1
