### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by acldemac** [MicrosoftDocs/powerbi-docs#814]
Just finished the set of videos on MicrosoftDocs/Power BI/Guided Learning/"**_Introduction to DAX_**"
If I did understand the subjects correctly, I believe there is a typo on the page "Table relationships and DAX" (DAX5) that seems to be important to the correct understanding of this section.
--- Current text is: ---
For example, the **_TABLE_** function follows relationships and returns the value of a column, while RELATEDTABLE follows relationships, and returns an entire table that is filtered to include only related rows.
--- I believe it should read: ---
For example, the **_RELATED_** function follows relationships and returns the value of a column, while RELATEDTABLE follows relationships, and returns an entire table that is filtered to include only related rows.
Thank you,

**Comment by mihart** [comment]
Hi @acldemac 
Thank you for your feedback, we really appreciate it.  I've assigned this to the author of that article and she will respond asap.
Take care,
The DOCS team.

**Comment by davidiseminger** [comment]
Adding an assignee to look into resolution.

**Comment by MI77** [comment]
Seems to be fixed already. #please-close @mgblythe
