### ISSUE TITLE
Flatten data feature

### ISSUE THREAD

**Issue by nickcellini** [MicrosoftDocs/powerbi-docs#816]
Wish you could connect to the data source and get out flat data, not in a pivot table. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 458afd24-a62a-7944-5cd4-de9a9290c308
* Version Independent ID: ed6a56f0-e067-9f92-5d54-6755b49f3bc0
* Content: [Using Power BI publisher for Excel - Power BI](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel)
* Content Source: [powerbi-docs/publisher-for-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/publisher-for-excel.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Dear @nickcellini 
Thank you for your feedback.  I've forwarded your comment on to the article author and he will respond asap.  This sounds like it may be a product issue, and not a doc issue.  If that is the case, I suggest posting this in the community forums:  community.powerbi.com or as a new idea ideas. powerbi.com.
Take care,
The DOCS team

**Comment by davidiseminger** [comment]
Thanks for your comment. Feel free to use ideas.powerbi.com to submit feature requests. Thanks.
