### ISSUE TITLE
Unable to connect from Excel 2010

### ISSUE THREAD

**Issue by pvalli** [MicrosoftDocs/powerbi-docs#817]
Trying out the Power BI Excel Plugin. We have people running Excel 2010 and Excel 365. Based on the documentation (Excel 2007 or later) this should not make a difference.
However, after installing the plugin, people running Excel 2010 are not able to get the data (they are signed in). They get into a loop of additional Company sign-ins and eventually they get this error message:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/13329618/53085172-97882700-3502-11e9-844d-6f076b843d80.png">

Permissions are the same between the two user types at powerbi level but office 365 users don't seem to experience the problem.
Are there any version-specific limitations that are not explicitly documented?

**Comment by mgblythe** [comment]
@pvalli -- do you have a doc page where the limitations are listed?

**Comment by markingmyname** [comment]
@pvalli, We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Comment by pvalli** [comment]
@mgblythe sorry for the late reply. The only documentation I could find was [here](https://docs.microsoft.com/en-us/power-bi/publisher-for-excel): 
> Power BI publisher for Excel is an add-in you can download and install on desktop versions of Microsoft Excel 2007 and later.
This is correct in the sense that it can be installed on e.g. Excel 2010 but the connection did not work in our case with any instance of Office prior to 365.
@markingmyname there are no further questions in that we solved it by upgrading to O365 but I still find the documentation misleading.
