### ISSUE TITLE
Workspace Viewers

### ISSUE THREAD

**Issue by JayDoc386** [MicrosoftDocs/powerbi-docs#818]
There are currently three roles for Workspaces: admins; members; and, contributors.  What about creating a role called viewers?  These would be individuals that can view content inside of a workspace but cannot add, delete, or edit any of the content within the workspace.  They can download the files inside of the workspace to use in the desktop version of Power BI but that would be the extent of what they can do within the workspace.  We have individuals that need only view the information within a workspace but we don't want them to have the power to change anything. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 220c2a2b-9a3e-3bdf-5fcd-ac2fc85542b4
* Version Independent ID: 024b0981-3008-08cd-8d2d-4dc6d87fe3fd
* Content: [Organize work in the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-new-workspaces)
* Content Source: [powerbi-docs/service-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @JayDoc386. This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.
