### ISSUE TITLE
Empty Values return upon large request

### ISSUE THREAD

**Issue by cwra007** [MicrosoftDocs/powerbi-docs#82]
Hi there,

For the most part I have everything running smoothly. However when I try and make large requests (a years worth of data broken out by month with a segment and a single dimension), I get no data returned. It doesn't error out, I just get 0's back for all of my metrics. The obvious answer here would be to break my pull into smaller requests, but this isn't ideal for me. The reason being is that i have some base code that loops through ~40 report suites twice. That alone takes a while to run, and I don't really want to increase the wait time by 12 and then stitch it all together. 

What I was wondering is: Are there any settings/code I can adjust to stop this from happening? I've tried adding ([Timeout=#duration(0,0,30,0)]) to my Source, but the connector doesn't support it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b88aa9e-5500-8904-286c-4a6d22be2e9f
* Version Independent ID: b0faa18f-b2ca-4c95-3486-7227cfb31277
* Content: [Connect to Adobe Analytics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-adobe-analytics)
* Content Source: [powerbi-docs/desktop-connect-adobe-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-adobe-analytics.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@cwra007 - thanks for your comment. Sounds like a support request rather than doc feedback, so please try support.powerbi.com.
