### ISSUE TITLE
PowerShell snippet is badly formatted

### ISSUE THREAD

**Issue by montydrei** [MicrosoftDocs/powerbi-docs#820]
The script snippet in step 4 of Configuring delegation settings has syntax errors. Please correct this to the following:

```powershell
$c = Get-ADGroup ResourceDelGroup
Set-ADUser SQLService -PrincipalsAllowedToDelegateToAccount $c
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89287a5d-f44b-6483-c79c-a0d0c83bc8c3
* Version Independent ID: f9766f6d-ec9e-3609-91bc-859e0c0eb76c
* Content: [Use Kerberos (resource-based) for single sign-on (SSO) from Power BI to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos-resource#configuring-kerberos-constrained-delegation-for-the-gateway-and-data-source)
* Content Source: [powerbi-docs/service-gateway-sso-kerberos-resource.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sso-kerberos-resource.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
Thanks for your comment, @montydrei. I’ll add this request to our docs backlog.

**Comment by mgblythe** [comment]
This is fixed now, closing out. Thanks again @montydrei.
