### ISSUE TITLE
Add "Implemented date"

### ISSUE THREAD

**Issue by nicheplayer** [MicrosoftDocs/powerbi-docs#821]
It would be very helpful to have some mention in this (and all) documentation of when (in which version) the feature was added to Power BI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c379d7f1-f977-7906-c4ba-6f58ab47d785
* Version Independent ID: 088a4f2c-e571-1282-b265-9b90d4995505
* Content: [Using buttons in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-buttons)
* Content Source: [powerbi-docs/desktop-buttons.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-buttons.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @nicheplayer. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your comment. We always recommend users run the most recent version of Power BI Desktop. Meanwhile, you can look through the latest updates article (and its friend, latest updates archive) to see about finding when a feature was released.

**Comment by nicheplayer** [comment]
> Thanks for your comment. We always recommend users run the most recent version of Power BI Desktop. Meanwhile, you can look through the latest updates article (and its friend, latest updates archive) to see about finding when a feature was released.

Thanks for your reply. I've been told by my on-prem server admin that I need to be running the version of desktop that coincides with our on-prem server version; perhaps this isn't actually the case? I appreciate you taking the time to reply. Thanks again.
