### ISSUE TITLE
JSON not valid

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#822]
@ImkeF commented on [Wed Feb 20 2019](https://github.com/MicrosoftDocs/powerbi-docs.de-de/issues/4)

The JSON for "Properties within each card" is not valid.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Verwenden von Berichtdesigns in Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is reporting an issue on the example
best

**Comment by kfile** [comment]
Hi @CeciAc and thanks for posting your comment. Sorry you are having trouble with the JSON. I've assigned it to the author for triage. We get a lot of comments, so please be patient! Thanks.

**Comment by davidiseminger** [comment]
Adding another assignee to help with resolution.

**Comment by amandacofsky** [comment]
It isn't supposed to be valid JSON.  It's just a list of available properties, their names, the formatting card they are under, their type, and a description. It's a reference list that just happens to be in a JSON-ish layout. You can use it to find the name of the properties you want to change and then build out your theme using those names and the layout we demonstrated earlier in the article.
