### ISSUE TITLE
Documentation is a "maze"

### ISSUE THREAD

**Issue by Vasco10** [MicrosoftDocs/powerbi-docs#823]
Despite knowing Power Query for Excel since its inception, I did not have so much interest in using it, except if some clients asked for it (actually very few).
But with Power BI, esp. the last improvements, woke up my interest.
Navigating your documentation, I got lost - the reason I mentioned is a "maze", esp. through your sublinks where I find some of the information repetitive.
You could combine certain explanations and leave some sublinks short and to the point.
I enjoy reading, looking at printscreens, also the videos, ... but frankly too much information gets on the way, like I said in the sublinks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Data sources for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-get-data)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@Vasco10 Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thank you!

**Comment by davidiseminger** [comment]
Thanks for your comments @Vasco10  - I'll try to keep the sublinks and other elements to an only-needed basis. Your feedback is appreciated.
