### ISSUE TITLE
More datacolors than fit on the Theme colors palette?

### ISSUE THREAD

**Issue by JulieBABI** [MicrosoftDocs/powerbi-docs#825]
If there are more than 8 datacolors in the JSON file, how can the report designer see and choose the other colors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by kfile** [comment]
Hi @JulieBABI and thanks for your question. It has been assigned to the author for triage. Please be patient as we receive many comments on Power BI. Thank you.

**Comment by davidiseminger** [comment]
Adding another assignee to review.

**Comment by amandacofsky** [comment]
Users can only manually choose from the first 8 colors, but the other colors will be automatically chosen by the visuals if they have more than 8 data points.
