### ISSUE TITLE
How to do I add a service principal through PowerBI.com?

### ISSUE THREAD

**Issue by SenthuranSivananthan** [MicrosoftDocs/powerbi-docs#826]
5. Add the service principal as an admin to the new workspace you created. You can manage this task through the APIs or with the Power BI service.

I've followed through the steps but there's no way to add my service principal through the PBI.com portal.  The input field expects an email address and there's no way to add the GUID or the Service Principal Name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#considerations-and-limitations)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by kfile** [comment]
Hi @SenthuranSivananthan and thanks for your question. It has been assigned to the author for triage. Service Principal is new, we appreciate you trying to use this feature.

**Comment by skanthb** [comment]
I have done it though API

import requests


url = "https://api.powerbi.com/v1.0/myorg/groups/ef3ab46b-2566-4567-4r56-thfddfgd343/users"


payload = "{\r\n\"displayName\":\"testApp1\",\r\n\"emailAddress\":\"name.name@company.com\",\r\n\"groupUserAccessRight\":\"Admin\",\r\n\"identifier\":\"2rtyh624-3d6d-41cb-97d5-ghfshfhfdh\r\n\"principalType\":\"App\"\r\n}"
headers = {
    'Content-Type': "application/json",
    'Authorization': "Bearer eyJ0eXAiOiJKV1Qgfg*************"   }


response = requests.request("POST", url, data=payload, headers=headers)


print(response.text)

**Comment by markingmyname** [comment]
@SenthuranSivananthan, thank you for your feedback.

@skanthb, thank you for the response.

@SenthuranSivananthan, does @skanthb's response help or further assistance is needed?

**Comment by SenthuranSivananthan** [comment]
@markingmyname I will test the option this afternoon and post back if it works for me.  I will ensure to test w/ v2 workspaces.

@skanthb thank you

**Comment by markingmyname** [comment]
@SenthuranSivananthan Thank you and good luck!

**Comment by SenthuranSivananthan** [comment]
@markingmyname success!

My payload ended up being:

```json
{
	"groupUserAccessRight":"Admin",
	"identifier":"xxxxxxxxx-0123-4b40-beda-xxxxxxxxxxx",
	"principalType":"App"
}
```
