### ISSUE TITLE
Custom Column vs Calculated Column

### ISSUE THREAD

**Issue by rvadnai** [MicrosoftDocs/powerbi-docs#827]
Can you please explain whether there are any advantages or disadvantages associated with creating a Custom Column (through PQ) rather than a Calculated Column (through DAX)?

Calculated Column are created based on data that has already been loaded in the model.  So I guess (and please confirm) that would mean that using a Custom Column instead of Calculated Column would in some cases allow for the removal of intermediary columns that might not be necessary in the model and thus allow us to **reduce the size of the model.** 

Are there any other benefits to using one type of column over the other?

Thank you!

**Comment by kfile** [comment]
Hi @rvadnai and thanks for your question. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com. Thanks.
