### ISSUE TITLE
Comment on authentication to on-prem sources (DQ can use SSO)

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs#828]
Just a small but important improvement for the info on this page.
You say: "A stored credential will be used to connect to on-premises data sources from the gateway except Analysis Services. Regardless of the individual user, the gateway uses the stored credential to connect.".
But, this is not taking into account the DirectQuery option, where the credential of the current user can be sent to the source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 337848b9-e784-3358-7b8e-853fe40120e3
* Version Independent ID: e92fa154-5fc4-cefe-ebe8-d62c36ce551d
* Content: [On-premises data gateway in-depth - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem-indepth#authentication-to-a-live-analysis-services-data-source)
* Content Source: [powerbi-docs/service-gateway-onprem-indepth.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem-indepth.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by kfile** [comment]
Hi @DaveRuijter and thanks for your suggestion. This has been assigned to the author for triage.

**Comment by agusbuhori** [comment]
Masih bingung

**Comment by mgblythe** [comment]
@arthiriyer - will address as part of the gateway docs update

**Comment by mgblythe** [comment]
We added info to https://docs.microsoft.com/data-integration/gateway/service-gateway-onprem-indepth#authentication-to-on-premises-data-sources. Thanks!
