### ISSUE TITLE
Pivoting data to create new columns

### ISSUE THREAD

**Issue by jebradfield** [MicrosoftDocs/powerbi-docs#829]
In the section that begins "In this example I pivoted my data to create new columns..." - After pivoting the data, I had to delete and then recreate the relationship between "Customer Table" and "Device" and then I had to close the pbix file and re-open it in order to fix the "A field in "Explain By" is not uniquely related..." error.  It's not immediately obvious that users have to go through these steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#considerations-and-troubleshooting)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by juluczni** [comment]
Thank you for the feedback! I will add the point about fixing the relationship as I agree it is not intuitive. The other point you mentioned is a caching bug and should be fixed in the next release of the Desktop.

**Comment by davidiseminger** [comment]
Thanks for the comment and update.

**Comment by juluczni** [comment]
#please-close @mgblythe
