### ISSUE TITLE
Relative date filter not working the same in Service as in Desktop

### ISSUE THREAD

**Issue by mmarois123** [MicrosoftDocs/powerbi-docs#832]
As a default state, I would like the Relative Date Filter to show "This Month (Calendar)" so that when the user selects "Next" it will continue to show "Next 1 Month (Calendar)". This was previously working for me and it appears to continue to work in my Power BI Desktop file. However, now when I load the report to Power BI Service, it changes the "This Month (Calendar)" to "This Month" regular with no option available for "Month (Calendar)" and when a user selects "Next" it will show "Next 1 Month" giving incorrect results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f19b40b2-9df7-adf8-3f9b-c6c7b188f3c1
* Version Independent ID: 70e043bb-c04e-2c5f-a121-3cf4368b0c49
* Content: [Use a relative date slicer or filter in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-slicer-filter-date-range)
* Content Source: [powerbi-docs/visuals/desktop-slicer-filter-date-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-slicer-filter-date-range.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your feedback @mmarois123. We'll let the author know about this, and they should get back to this when they have a chance to review.

**Comment by mgblythe** [comment]
@mmarois123 - you might also find a solution in the Power BI Community, at https://community.powerbi.com.
