### ISSUE TITLE
How to combine filter with ?rs:embed=true

### ISSUE THREAD

**Issue by 369Martin369** [MicrosoftDocs/powerbi-docs#835]
Hi, I have filters provided with URL and want to hide the black header with ?rs:embed=true. It seems to me that ?rs:embed=true cannot be combined with ?filters=......

Thanks
Matt

**Comment by mihart** [comment]
Hello, @369Martin369 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.
If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
Kind regards,
Microsoft DOCS International Team
