### ISSUE TITLE
Older versions of Office Don't work for Export

### ISSUE THREAD

**Issue by DarkSideOfTheBI** [MicrosoftDocs/powerbi-docs#837]
I noticed it wasn't mentioned that really old versions of Office don't work for export.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df1c4c0-80f9-f71a-175f-8362a29ad597
* Version Independent ID: c2a64e2a-ce65-dfb7-588a-381c145ab193
* Content: [Export reports from Power BI to PowerPoint - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint#limitations)
* Content Source: [powerbi-docs/consumer/end-user-powerpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-powerpoint.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @DarkSideOfTheBI 
Thank you for your feedback.  I've updated the document with this limitation. We appreciate your contributions to our docs!
The Power BI DOCS team
