### ISSUE TITLE
Live connection running against the cache when loading the report?

### ISSUE THREAD

**Issue by cevipu** [MicrosoftDocs/powerbi-docs#838]
Hi,
It's stated in the document that "the Live connection to a SSAS source can run against the cache, even upon loading a report". What does it mean? Which cache it will run against? How is RLS on Azure Analysis Services affected? Does the user always get fresh data when they open the report, or is refresh sometimes required? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce280443-0aa3-da51-f71d-ff7c1704b268
* Version Independent ID: 8122662c-44c4-317d-ef45-44bd3f204487
* Content: [Data refresh in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/refresh-data#live-connections-and-directquery-to-on-premises-data-sources)
* Content Source: [powerbi-docs/refresh-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/refresh-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @cevipu ,
Thank you for your feedback.  I've forwarded your comment along to the doc author, and he'll respond as soon as he can. 
Take care,
The DOCS team

**Comment by SanaAbdul** [comment]
Hi
 I  have a direct query report.I want to configure schduled cache refresh manually for a data set to reflect changes in data in report every 15 mins. My problem is that  can see the cache refresh option disabled for my  dataset. How to enable this option.
Rgrds, 
Sana!

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
