### ISSUE TITLE
Missing Image?

### ISSUE THREAD

**Issue by nastassiar** [MicrosoftDocs/powerbi-docs#839]
"Ben receives an error similar to the following image, because he was not authorized to the dataflow’s CDM folder in the lake"

What image is this referring to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Hi @nastassiar ,
Thank you for your documentation feedback.  I've forwarded your question on to the author and he will respond asap.
Take care,
The DOCS team

**Comment by olthomps** [comment]
Hi @mihart - any updates on the missing image? Thanks!

**Comment by davidiseminger** [comment]
Sorry for the confusion - there's no associated image. I've clarified that in the doc.
