### ISSUE TITLE
Link for data connected with DirectQuery

### ISSUE THREAD

**Issue by karaoan** [MicrosoftDocs/powerbi-docs#84]
The instructions provided here for me using an SSAS source with a field with an html link simply do not work. This step is NOT possible: "Select the column, and in the Modeling tab, choose the dropdown for Data Category."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [How to add a hyperlink to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
@karaoan - sorry for the trouble you're having with this. You might be able to get answers using support.powerbi.com.
