### ISSUE TITLE
Power BI Premium Capacity Metrics - No data for Models

### ISSUE THREAD

**Issue by jainn4** [MicrosoftDocs/powerbi-docs#840]
Hi, 
The Power BI Premium Capacity Metrics for my premium node is not showing any information for dataset. See screenshot below. Is there a bug in the app?

![capture](https://user-images.githubusercontent.com/42496773/53479324-b3df1300-3a70-11e9-91ce-bca3e72527b9.PNG)

Thanks
Nishant

**Comment by mihart** [comment]
Hi @jainn4 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.
If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
Kind regards,
Microsoft DOCS International Team
