### ISSUE TITLE
Step 5 unclear

### ISSUE THREAD

**Issue by AttBa** [MicrosoftDocs/powerbi-docs#841]
The statement

"Expand Values, locate URL icon, and turn it to On."

in Step 5 in unclear. I could not locate the URL icon - the point of visiting this page in the first place. Could you please add (a) screenshot(s) for this? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbaf2eb-b0c1-6631-727f-f99d0ce28a97
* Version Independent ID: 23ede21d-e41a-9121-e23c-b52409198e31
* Content: [Add hyperlinks to a table - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-hyperlinks-in-tables#feedback)
* Content Source: [powerbi-docs/power-bi-hyperlinks-in-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-hyperlinks-in-tables.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @AttBa -- I updated the article with a screen shot for this step. Thanks for the feedback!
