### ISSUE TITLE
Can't download PBIX with data sourced from Dataflows

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#842]
Can the documentation clarify whether a dataset sourced from Power BI dataflows can be exported as a PBIX from the service?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091669c-6d15-1d87-9d1b-87720f50a908
* Version Independent ID: 2989dde3-eef4-28ea-4eec-846efc140735
* Content: [How to export a report from Power BI service to Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-export-to-pbix)
* Content Source: [powerbi-docs/service-export-to-pbix.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-export-to-pbix.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @otravers. This issue has been assigned to the doc author for review.

@davidiseminger in case he knows the answer to this one.

**Comment by Al3x68** [comment]
It would be great to list all the supported (and not supported) scenario. It seems downloading a report that is using Live connection to a Tabular model is also not supported...

**Comment by kfollis** [comment]
@otravers and @Al3x68 - Thank you for submitting feedback on our documentation. This article has been recently updated. We are closing this issue, but have created a work item in the writer’s backlog to consider your feedback in the next update.
