### ISSUE TITLE
Python scripts causing Failed Scheduled Refresh 

### ISSUE THREAD

**Issue by j-staab** [MicrosoftDocs/powerbi-docs#846]
It was really great being able to integrate python scripts directly into my latest PBI report with PBI desktop.  BUT I discovered when I published the report, I get a Failed Scheduled Refresh error because Python is a Preview Feature -- which means it doesn't work on Power BI services ( see  https://community.powerbi.com/t5/Service/Failed-Scheduled-Refresh-Credentials-are-required-to-connect-to/td-p/491613 ).  So the easiest fix, was to just not 'refresh' the queries/tables that use python scripts (which would work in my case since the data the scripts are run on doesn't need refreshed).  With PBI desktop, I used a checkbox feature to NOT include the queries/tables using Python Scripts as an "attempt" to solve this problem. Then I discovered that excluding query/table from refresh is ALSO NOT included in Power BI Service; thus, I still have the same problem.  

I'm rather disappointed since this issue with the turning OFF Refresh has been an open issue for over a year and 1/2 (open since August 17, 2017 -- see https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/20579641-exclude-a-table-from-refresh-in-power-bi-service).  I can understand how a "preview" feature might not be totally resolved as the nature of a "preview" feature, but I cannot understand how a "bug" in a regular feature can remain unfixed for over 18 months.  I feel like it was my mistake to attempt to use a "preview" feature -- not knowing that "preview" meant it wasn't available in PBI services.  Only to discover the "easiest" solution of turning "off" refresh (which is a regular feature and would solve this issue) isn't available to me because it remains an unaddressed bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070da3e8-5146-a2ca-9ac3-ed77621fc050
* Version Independent ID: 2dcfbb4b-3661-50bb-43b7-050aa77e710d
* Content: [Running Python Scripts in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-python-scripts#feedback)
* Content Source: [powerbi-docs/desktop-python-scripts.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-python-scripts.md)
* Service: **powerbi**
* GitHub Login: @otarb
* Microsoft Alias: **otarb**

**Comment by mihart** [comment]
Hi @j-staab 
Thanks for your comment. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
The Power BI DOCS team

**Comment by j-staab** [comment]
Hi Michele (@mihart),
I appreciate that you got back to me. I was wondering if you could add some clarity to the documentation regarding Preview Feature(s) only being available in PBI desktop and not within PBI services.  If I would have known, likely I wouldn't have used Python in the way that I did.  Additionally, it took a lot of searching to realized that the error message I was getting from the "refresh" was related to PBI services not supporting Python scripting.    I'll be sure to see if I can get some support on the refresh issue from  https://support.powerbi.com 
Thanks in advance for the help.
Jennifer

**Comment by mgblythe** [comment]
Thanks @j-staab, I've reached out to the doc owner to make an update.

**Comment by mgblythe** [comment]
Assigning to @otarb

**Comment by otarb** [comment]
@j-staab you should be able to refresh Python data sets in service using personal gateway. Python support is not longer a preview feature. 

For more information check out this article [Use personal gateways in Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-personal-mode)

**Comment by otarb** [comment]
#please-close @otarb
