### ISSUE TITLE
The title in the left menu says SAP BW connector is Preview

### ISSUE THREAD

**Issue by laandermsft** [MicrosoftDocs/powerbi-docs#848]
I believe the SAP BW connecter has been GA for a while now, please update the title in the left menu by removing (Preview). The title of the document itself does not include (Preview)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ffc50e-bb57-9a79-ab89-2cbd9ca1e335
* Version Independent ID: c0a48358-4144-6d9f-f4c0-b2747b091bf9
* Content: [Use the SAP BW Connector in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-sap-bw-connector#feedback)
* Content Source: [powerbi-docs/desktop-sap-bw-connector.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-sap-bw-connector.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @laandermsft  This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
You're absolutely right - sorry about that. I've updated the TOC, which will be reflected in our next publishing run. Thanks!
