### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by ArvidBaa** [MicrosoftDocs/powerbi-docs#849]
I must say that I am slightly confused by the date format choices in Power BI. Why is mm/dd/YYYY the standard format, in any part of the software? It is an American date format, that most other people ar unfamiliar with. It is both ambiguous compared to the widely used dd/mm/YYYY date format, but most importantly, it doesn't follow international standard.

The International Organization for Standardization (ISO) has decided, quite some years ago, that the international standard for dates should be YYYY-mm-dd (or YYYYmmdd). This is just as short as the mm/dd/YYYY date format, and has the benefit of being non-ambiguous, but most importantly being the _international standard_!

Could you please do the entire world a huge favor and change mm/dd/YYYY to YYYY-mm-dd?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc558f3-8a74-7154-c048-2dd74ad4eb8a
* Version Independent ID: f84aa1a5-4bab-6f6d-a0ba-5040c0f5defb
* Content: [Use the numeric range slicer in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-slicer-numeric-range)
* Content Source: [powerbi-docs/desktop-slicer-numeric-range.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-slicer-numeric-range.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @ArvidBaa . This looks like product feedback | a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.

**Comment by ArvidBaa** [comment]
@mihart you're correct. My mistake.
