### ISSUE TITLE
export to PDF

### ISSUE THREAD

**Issue by matdriks** [MicrosoftDocs/powerbi-docs#850]
[Enter feedback here]

Export to PDF is also available in the Power BI Service.
But the Docs says it is only available in Power BI desktop.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7dd54f0-efd3-c6df-7129-e2affa3ae942
* Version Independent ID: cc7bd663-267f-21d5-547b-b3d8614005fd
* Content: [Export your reports to PDF format from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-export-to-pdf)
* Content Source: [powerbi-docs/desktop-export-to-pdf.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-export-to-pdf.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Assigned to author: Thanks for your comment, @matdriks . This issue has been assigned to the doc author for review.

**Comment by Zorgonaute84** [comment]
Great feature to print from PowerBI. But there is 2 issues. It's impossible to print multiple pages with a selection. (ex : select a specific month). Only the current page is printed with the selection available.
2nd issue, it's impossible to print one page, the report is generated with all pages.

**Comment by davidiseminger** [comment]
The article now mentions it works in the Power BI service. Thanks!
