### ISSUE TITLE
This Feature Not Working

### ISSUE THREAD

**Issue by urspalani** [MicrosoftDocs/powerbi-docs#851]
Hi,
For past few days we are not able to add the Dataset share via Content pack?
Is it bug or is it removed ?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d12a4b-f24d-121e-e639-a99977c5eaae
* Version Independent ID: 99fbbca9-428c-47cf-452b-369a8d62df96
* Content: [Create and publish an organizational content pack - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-organizational-content-pack-create-and-publish#feedback)
* Content Source: [powerbi-docs/service-organizational-content-pack-create-and-publish.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-organizational-content-pack-create-and-publish.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by markingmyname** [comment]
Thanks for your comment, @urspalani. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by maggiesMSFT** [comment]
Hi, @urspalani -- yes, this looks like a support request. I'm going to close this comment.  Please do check with the Power BI Community, found at https://community.powerbi.com. Or you can get support by going to https://support.powerbi.com.
Thanks!
