### ISSUE TITLE
PowerBI GeoMaps Integration

### ISSUE THREAD

**Issue by adilshahzad** [MicrosoftDocs/powerbi-docs#852]
Hi,
Any tutorial to integrate PowerBI Maps to a website? Would like to generate the locations from the DB and draw them on the map with exact Lat and Lang.

Kind regards,
Adil

**Comment by markingmyname** [comment]
Hello, @adilshahzad, thank you for your comment. I can't tell by the title and the lack of supporting detail what exact article you are referencing. Can you please explain by 03/15? Thank you.

**Comment by mgblythe** [comment]
Assigning to @mihart to see if this fits in with any upcoming viz work.

**Comment by mihart** [comment]
Thanks for your comment, @adilshahzad . This looks like product feedback, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.
