### ISSUE TITLE
Move "Once a dataflow storage location is configured, it cannot be changed" to Start of Doc

### ISSUE THREAD

**Issue by ellisjm74** [MicrosoftDocs/powerbi-docs#853]
Move the "Once a dataflow storage location is configured, it cannot be changed." bullet that is currently under Considerations and Limitations to the start of the document.  It is important information to know before starting this process and should not be left to the end.  I'd suggest just before "Prepare your Azure Data Lake Storage Gen2 for Power BI". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#feedback)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@ellisjm74, thanks for your comment. 

We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by kungfuko** [comment]
Havent been moved after a month? Such important information has to be on the top! I have already linked Data Lake and PBI and now i cant remove the connection!

**Comment by davidiseminger** [comment]
Thanks for your feedback - this has been updated to show up as a warning near the top of the article, and will show up within the next day.

**Comment by axaeffect** [comment]
I'm facing the same problem, it's being filled / set without my knowledge then now I have no idea how to fix it or change it to another storage account.
Please help to expedite this issue. 
Many thanks.
