### ISSUE TITLE
Publishing to App Workspaces?

### ISSUE THREAD

**Issue by jsteinha1975** [MicrosoftDocs/powerbi-docs#856]
Specific to leveraging a Service Principal and not Master User.  In the above it states:

"Publish to app workspaces. This process differs depending on whether you're using a master account (Power Pro license), or service principal. If you're using a master account, then you can publish your report through Power BI Desktop. Now if you're using service principal, you must use the Power BI REST APIs."  

If for example one is attempting to publish a report, are their specific properties or parameters that need to be set via the API's which are not set'able via the Power BI Desktop?  Does the actual Service Principal need to be used as the credential when publishing the report?  More specifics would be helpful, thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Hi @jsteinha1975, thank you for the comment.

The article is explaining if you decide to use Service Principal instead of a Master Account then you have to use the New Workspaces to publish your PBI artifacts.  If you use Service Principal, you are not required to have a PBI Master Account and that is why you need to use the APIs.

Does that help answer your question?

Please let me know.

Thank you.

**Comment by jsteinha1975** [comment]
Hey Mark, thanks for the reply but it isn't quite getting to my question.  I'll try and explain my question better.

I've been successful implementing the Master User/Account pattern.  When I try and implement the Service Principal pattern I've encountering a 401 error.  As I've been troubleshooting my issue I stumbled upon the wording above which says "Now if you're using service principal, you must use the Power BI REST APIs"  My question is are their specific properties I need to set while publishing via the APIs?  Or do I need to use the Service Principal secret to publish?  Asking as I have tested via publishing the report via the UI as well as via the Power BI REST API and I continue to receive the 401 error.  Per the tutorial I believe I have all of my settings / permissions set appropriately but looking to confirm concerning the publishing step.  

Perhaps another way to ask, will the Service Principal pattern work with reports published via the Power BI Application?
thx

**Comment by markingmyname** [comment]
@jsteinha1975 I apologize for the delayed response.

To answer the direct question you asked, Service Principal will work with reports published to the Power BI service if those reports are stored in the new workspaces. Traditional workspaces (workspaces v1) do not work with service principal.

To answer the other question about do you need any parameters or settings to be set to use the APIs, they do not.

I would also suggest going to [support](https://support.powerbi.com) and creating a ticket for this. Also, you might find a solution in the Power BI Community, found at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
