### ISSUE TITLE
Power BI Premium Capacity Metrics App - Failure to refresh app data

### ISSUE THREAD

**Issue by dsutherlandafex** [MicrosoftDocs/powerbi-docs#857]

**Comment by dsutherlandafex** [comment]
Yesterday I increased our Power BI Premium Capacity from P1 to P2 and since then I have been getting an error when refreshing the data in the Capacity Metrics app.

The error (as attached) states "There weren't enough elements in the enumeration to complete the operation. Table: MemeoryMetrics"
![2019-03-08 15_30_22-power bi](https://user-images.githubusercontent.com/37163410/54007759-88b69b00-41b7-11e9-8757-502942a953a5.png)

Please help as this app was crucial in troubleshooting errors we had been having with poor performance

**Comment by dsutherlandafex** [comment]
In addition to this I am now getting this error
![2019-03-08 22_18_10-refresh failed_ power bi premium capacity metrics has failed to refresh - messag](https://user-images.githubusercontent.com/37163410/54025922-2c23a200-41f0-11e9-9f6d-d9022efd8018.png)

**Comment by markingmyname** [comment]
Thanks for your comment, @dsutherlandafex! Sounds like this is a product question, so please use the Product Feedback button in this article, or try the community, https://community.powerbi.com/.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
