### ISSUE TITLE
Screenshots need to be updated

### ISSUE THREAD

**Issue by Oddjobe** [MicrosoftDocs/powerbi-docs#858]
Power BI service live connection has changed name to Power BI Datasets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets#feedback)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@Oddjobe, Thanks for your comment. 

We’ve forwarded your feedback to the writer, who should respond to this thread.

Thanks!

**Comment by davidiseminger** [comment]
Thanks! I've updated that information in the article.
