### ISSUE TITLE
Dead link in this document.

### ISSUE THREAD

**Issue by yuedai** [MicrosoftDocs/powerbi-docs#86]
The links in following pragraph are dead (404).

For embedding for your organization, see the following walkthroughs:

Integrate a dashboard into an app
Integrate a tile into an app
Integrate a report into an app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [How to embed your Power BI dashboards, reports and tiles - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedding-content#createreports)
* Content Source: [powerbi-docs/developer/embedding-content.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedding-content.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@yuedai Thank you for the feedback.  We did notice this, and we are working on correcting it.  The update to the article should be live in a few days.
