### ISSUE TITLE
pbix files for tutorial and "demo" don't open message says they are corrupt

### ISSUE THREAD

**Issue by clarkmac** [MicrosoftDocs/powerbi-docs#860]
I am trying to share/show and tell with the demo files but PBI Desktop won't open saying they are corrupt.  This file location is the link from abovehttps://github.com/Microsoft/powerbi-desktop-samples/blob/master/2019/customerfeedback.pbix

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by clarkmac** [comment]
Please close.  Working from Github repo just fine.

**Comment by markingmyname** [comment]
@clarkmac, Thanks for your comment. 

We’ve forwarded your feedback to the writer, who should respond to this thread. 

Thanks!

**Comment by mgblythe** [comment]
Thanks @clarkmac, closing now.
