### ISSUE TITLE
In the Relationship aggregate case, column mapping is wrong

### ISSUE THREAD

**Issue by davidbaxterbrowne** [MicrosoftDocs/powerbi-docs#862]
In the Manage Aggregations dialog for Sales Agg, the GroupBy columns should not be mapped.  In the displayed example mapping ProductSubcategoryKey to Product.ProductSubcategory only works because Product is a DirectQuery table.  When you switch Product to Dual, this mapping no longer works.  Since this is Relationship mapping, the Group By columns should not be explicitly mapped.  Only the Aggregate columns should be mapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 651949b2-ae84-a7c1-d012-e41891e5931c
* Version Independent ID: bb6928af-2e51-320e-e69b-577f9bbdcd17
* Content: [Use Aggregations in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-aggregations#feedback)
* Content Source: [powerbi-docs/desktop-aggregations.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-aggregations.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @davidbaxterbrowne. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback @davidbaxterbrowne  - we'll send that info to the product team who created the sample.
