### ISSUE TITLE
Dual Mode

### ISSUE THREAD

**Issue by mb040574** [MicrosoftDocs/powerbi-docs#863]
You could also mention the Dual Mode which is available when starting out with DirectQuery for a datasource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563a1b09-bcdc-2638-d9a0-6801b44d3cb0
* Version Independent ID: dea2c705-c2f7-3f2d-798b-ee41857e0ca2
* Content: [Use DirectQuery in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery#feedback)
* Content Source: [powerbi-docs/desktop-use-directquery.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-use-directquery.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @mb040574. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback!
