### ISSUE TITLE
Issues with multi-currency usage

### ISSUE THREAD

**Issue by joninmoz** [MicrosoftDocs/powerbi-docs#864]
Transactions made in currencies that are not USD input 1:1 with USD, instead of at the exchange rate. This is a serious issue and makes the QBO connector un-usable for multi-currency situations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a74e3ffd-eefd-e93f-2a88-20d872922762
* Version Independent ID: 678b36be-0224-af5b-28d9-f457856611e7
* Content: [Connect to QuickBooks Online with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-quickbooks-online#feedback)
* Content Source: [powerbi-docs/service-connect-to-quickbooks-online.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-quickbooks-online.md)
* Service: **powerbi**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @joninmoz. This issue has been assigned to the doc author for review.

You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, at https://community.powerbi.com.

**Comment by SarinaJoan** [comment]
@joninmoz thanks for highlighting this. We are transitioning the content pack to a template app, so will take this into account if it can be fixed in the report. Adding @cpopell for visibility on this issue with the connector.
