### ISSUE TITLE
Record operations performed when incremental refresh is run

### ISSUE THREAD

**Issue by MartinKDK** [MicrosoftDocs/powerbi-docs#865]
I and potentially others would appreciate few lines about the order of operations performed when refresh with incremental policy is run. Something like simple diagram. To discover how the incremental refresh works, I have tried to create a dataflow (DF) based on SharePoint Online List (SHPL). 
Test1: added a record into SHPL &gt; refreshed DF &gt; new record appeared &gt; OK
Test2: modified the above record in SHPL &gt; refreshed DF &gt; field value was changed &gt; OK
Test3: deleted the above record &gt; refreshed DF &gt; record remained in the dataset
From your article, operations like INSERT, UPDATE, DELETE are to me not clearly explained.
Question1: could you transform and describe my above tests into some formal documentation?
Question2: can I use incremental refresh for datasources where records could be deleted? How do I handle this, e.g. combination of full refresh & incremental refresh?
Question3: can I use incremental refresh in PBI Desktop for Dataflow datasource? Example: DF connects to SQL server with X-million rows, and DF has incremental policy set to decrease number of records extracted. In PBI Desktop, I and my colleague would connect to DF. We both modify the model to our needs, build a report and publish it to PBI service. To make our datasets relevant we would set-up scheduled refresh on our (two) separate datasets. Do these datasets have to run in full-refresh only? I have actually tried this scenario and got an error "Unable to confirm if the M query can be folded..."

I love Dataflows &gt; please continue building and expanding functionalities around them.

Thank you beforehand for your reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b60093b2-2bdf-92e9-ee7c-de316b601beb
* Version Independent ID: 25307bcb-648e-e620-3fe9-a1412e89c0b5
* Content: [Using incremental refresh with Power BI dataflows - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-incremental-refresh#feedback)
* Content Source: [powerbi-docs/service-dataflows-incremental-refresh.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-incremental-refresh.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @MartinKDK. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your nice comments about dataflows. Note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
