### ISSUE TITLE
Embed PowerBI using Service Principal in Java Web app

### ISSUE THREAD

**Issue by LincredibleD** [MicrosoftDocs/powerbi-docs#867]
Hi there, thank you for the great example here on how to embed PowerBI in .NET and C#. Is there an example for Java web App? Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @LincredibleD -- thanks for your comment! Are you referring to this article? 
https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal
I can't tell from your comment.

**Comment by LincredibleD** [comment]
@maggiesMSFT hi Maggie, I was referring to this tutorial. It was a very good tutorial in .NET and C#. https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization

I know there is a related Java example that uses ADAL4J but instead of powerbi it was for GraphAPI.

**Comment by maggiesMSFT** [comment]
Great, thanks, @LincredibleD, that helps. As it happens, @markingmyname is the writer for that one, too, so it's all good!

**Comment by markingmyname** [comment]
@LincredibleD Thank you for the kind words.

There is a [Javascript Git repo](https://github.com/Microsoft/powerbi-javascript/wiki) with more information, but not one for Java.

I would suggest submitting product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.

Hope this helps.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
