### ISSUE TITLE
Holes in B2B Collaboration and Power BI Premium

### ISSUE THREAD

**Issue by Bally-Kahlon** [MicrosoftDocs/powerbi-docs#869]
There are several holes we're finding with B2B Collaboration and Power BI.  
RLS - We're unable to find B2B users to add to RLS unless the users have redeemed their invitation.  This effectively means we have to send guest users to a blank application or dashboard through either planned or ad hoc invites and ask them to notify us when they have redeemed so we can then add them into RLS.  We ideally need to add these users prior to redemption to overcome this poor user experience.
For guest users we share with from our Premium capacity, those who do not have existing PBI licenses have a far from optimal experience.  When an external user (non O365) goes through B2B redemption and creates an MSA account to access PBI, they cannot login directly to app.powerbi.com on subsequent login attempts -  produces the “username is not recognised” message when attempting to access.  I’m not clear in this is the case for guest O365 users also but we believe it is… This is proving to be very difficult to support.  It's also frustrating that B2B invited users without existing PBI licenses cannot access the mobile app, the sharepoint webpart and the new embed is website option.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad42c3b-e011-733d-dbdf-53944a2724a6
* Version Independent ID: 05e0f67c-5852-5b10-ac94-694ec2d0d8f9
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-gb/power-bi/whitepaper-azure-b2b-power-bi#feedback)
* Content Source: [powerbi-docs/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Bally-Kahlon . This looks like product feedback , rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.Thanks for your comment,

**Comment by mgblythe** [comment]
Closing b/c this is product feedback and @mihart provided links to @Bally-Kahlon.
