### ISSUE TITLE
Subscription

### ISSUE THREAD

**Issue by brightlight1** [MicrosoftDocs/powerbi-docs#87]
Do the users that i subscribe to must have licenses as well? Will i be able to schedule refreshes with one subscription if i install gateway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a5f9906-58f7-9b21-85ee-8d33ffcbdce0
* Version Independent ID: 712e418a-5290-fe94-e9b0-6fa84ec1c7cb
* Content: [Quickstart: Purchase Power BI Pro licenses - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-purchasing-power-bi-pro#purchase-subscription-in-office-365)
* Content Source: [powerbi-docs/service-admin-purchasing-power-bi-pro.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-purchasing-power-bi-pro.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@brightlight1 - let me know if you need any more information on this, thanks.

**Comment by mgblythe** [comment]
Closing as addressed with the info from @markingmyname . @brightlight1 -- feel free to reopen if necessary.
