### ISSUE TITLE
"List of supported data sources" misleading

### ISSUE THREAD

**Issue by jt000** [MicrosoftDocs/powerbi-docs#871]
The list of supported data sources combines "Live/DirectQuery", however this list really only is accurate when talking about "DirectQuery". The only supported data sources for "Live" are SSAS and AAS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37efb1d4-b4bb-f035-c63b-1f8b17d4f448
* Version Independent ID: fe9f8822-a20a-e17c-195c-1dc261ab480f
* Content: [Power BI report data sources in Power BI Report Server - Power BI](https://docs.microsoft.com/en-us/power-bi/report-server/data-sources#feedback)
* Content Source: [powerbi-docs/report-server/data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/report-server/data-sources.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Thanks for your comment, @jt000 . This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
Thank you for your feedback, @jt000.

We combined the 2 because Live and Direct Query are similar terms for different types of data sources that both use "live" data.  That is why we included SSAS and AAS in that list.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
