### ISSUE TITLE
Doesnt work when I place it in the Policies Key

### ISSUE THREAD

**Issue by Pestilential** [MicrosoftDocs/powerbi-docs#872]
Wouldnt work in this key
HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Microsoft Power BI Desktop

however it does works in this key
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Microsoft Power BI Desktop

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a847d24-1a24-18c1-aa6e-2c977fa5e7cf
* Version Independent ID: 8089b020-600d-cbf9-fac9-f8a9328a6c00
* Content: [How admins can manage the Power BI Desktop sign-in form - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-admin-sign-in-form#feedback)
* Content Source: [powerbi-docs/desktop-admin-sign-in-form.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-admin-sign-in-form.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Pestilential . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for sharing your information @Pestilential - I've updated the article to reflect what you found. Thanks!
