### ISSUE TITLE
Dremio connector for online powerbi

### ISSUE THREAD

**Issue by anukaushalsingh** [MicrosoftDocs/powerbi-docs#873]
How can I publich PowerBI report with dremio as source to online powerbi without using Onpremise Gateway. I would like to refresh dataset without dependency on gateway, but couldn't find this connector support online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca836d9-2353-3725-f4ae-73e8d1ca34ba
* Version Independent ID: 80ff9e5a-772f-b1ec-61f0-de544ae9e959
* Content: [Data sources in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-sources#feedback)
* Content Source: [powerbi-docs/desktop-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@anukaushalsingh Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
Hi @anukaushalsingh - I recommend asking this question in the Power BI Community, at https://community.powerbi.com.

**Comment by davidiseminger** [comment]
Thanks for your comment, @anukaushalsingh. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
