### ISSUE TITLE
Port listing for firewall seems to be missing https://aaddn.msauth.net

### ISSUE THREAD

**Issue by ronaldvanrij** [MicrosoftDocs/powerbi-docs#874]
In reference to https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem#ports. 
When registering the On premises data gateway I attempt to login using the wizard, a windows opens and I get the following (Javascript) error: Failed to load external resource ['https://aadcdn.msauth.net/.......']. This suggests this domain/IP also needs to be included. Please confirm. 

After whitelisting above url, the following URL is also undocumented but required: dc.services.visualstudio.com:443

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e1f5955-e5b8-9cff-873e-4a195a462e62
* Version Independent ID: 12a87ce1-0e1b-f21c-bad3-09963e628d99
* Content: [On-premises data gateway - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem)
* Content Source: [powerbi-docs/service-gateway-onprem.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-onprem.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by markingmyname** [comment]
@ronaldvanrij  Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
@arthiriyer - will address as part of gateway docs update

**Comment by mgblythe** [comment]
As part of a doc rewrite we moved a lot of the info from this page to others. We added the addresses you referenced, along with a couple of others, to the  list of FQDNs used by the gateway in https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-communication#ports. Thanks!
