### ISSUE TITLE
Add JethroData to list of data sources and gateway

### ISSUE THREAD

**Issue by esinger5** [MicrosoftDocs/powerbi-docs#878]

**Comment by markingmyname** [comment]
@esinger5 There is not enough information here to address your feedback.  Please provide the article URL and the title of the article.  Thank you.

**Comment by mgblythe** [comment]
Checking with PM team, on gateway support for this data source.

**Comment by mgblythe** [comment]
Hi @esinger5. This info is now in https://docs.microsoft.com/en-us/power-bi/desktop-data-sources. Assigning to make sure this is included in updated gateways documentation.

**Comment by mgblythe** [comment]
We also added it to https://docs.microsoft.com/en-us/power-bi/service-gateway-data-sources. Thanks!
