### ISSUE TITLE
The detailed documentation on the topic.

### ISSUE THREAD

**Issue by Shrshet** [MicrosoftDocs/powerbi-docs#879]
the documentation is really good on the new topic. It would be great if we have a direct way to add the service principal to the Workspace v2 as admin. At least a Powershell script could work as a quick alternative instead of doing another API call using the Client ID using Postman or other method. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#get-started-with-a-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@v-shshet Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by u02cm62** [comment]
I was told you can add service principal if you add the service principal to a security group.  then add the security group as you can add security groups to workspaces.

**Comment by u02cm62** [comment]
You can see they mention this in some other docs as well as on the Power BI Admin portal to add to a security group as you have to enable service principals to use the Power BI API's in Power BI Admin portal anyway.

**Comment by markingmyname** [comment]
Currently service principal does not work with the admin APIs yet.  That limitation has been added to the [service principal article](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#considerations-and-limitations)

**Comment by markingmyname** [comment]
Thank you all for the collaboration and feedback.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
