### ISSUE TITLE
Replacing reports and consequences on custom reports

### ISSUE THREAD

**Issue by Dan1480** [MicrosoftDocs/powerbi-docs#88]
I think it would be useful to include a warning that to prevent users' custom reports from disappearing when replacing one report with another, the data set for the original report has to be manually included in the updated content pack.  By default the data set is removed when a report is removed and any custom reports based on that data set also become available.  There is no warning that customized reports will disappear and there is no way to bring them back.  The statement "Group members who have customized the content pack . . . get the updated content pack without losing their personalized version" is a little bit misleading because if the data set is gone, they WILL lose their personalized version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3f5c890-8eeb-670e-8cee-ee75d60703e0
* Version Independent ID: 8e0b3c20-9fe6-b92e-330d-2b3bece42dfc
* Content: [Organizational content packs: Manage and update - Power BI](https://docs.microsoft.com/en-us/power-bi/service-organizational-content-pack-manage-update-delete)
* Content Source: [powerbi-docs/service-organizational-content-pack-manage-update-delete.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-organizational-content-pack-manage-update-delete.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Thanks, @Dan1480!  I updated the article.

**Comment by Dan1480** [comment]
Thanks Maggie.  Although I can't see your changes?  The new version hasn't
been published yet?
Cheers,
Daniel

**Comment by maggiesMSFT** [comment]
Oh, yes, @Dan1480, I should've mentioned. You should be able to see the changes tomorrow afternoon. Thanks!
