### ISSUE TITLE
Additional comma in "Adding custom formatting options" Step 2

### ISSUE THREAD

**Issue by EYhellojo** [MicrosoftDocs/powerbi-docs#880]
The comma at the end of the block of code is not required for copy pasting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f573b62f-4028-ce65-b5ae-a4115ee1bcd1
* Version Independent ID: 1cedde6a-9245-42da-c25e-83706f551c79
* Content: [Adding formatting options to a Power BI custom visual - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/custom-visual-develop-tutorial-format-options#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial-format-options.md)
* Service: **powerbi**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by markingmyname** [comment]
@EYhellojo Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by KesemSharabi** [comment]
Hi @EYhellojo,

Thanks for your comments. We are looking to fix this article by the end of the month.

**Comment by KesemSharabi** [comment]
Hi @EYhellojo,

The article [Tutorial: Adding formatting options to a Power BI visual ](https://docs.microsoft.com/en-gb/power-bi/developer/visuals/custom-visual-develop-tutorial-format-options)was updated, and your comment was addressed.
