### ISSUE TITLE
Configuring RLS using service principle.

### ISSUE THREAD

**Issue by CundyTech** [MicrosoftDocs/powerbi-docs#882]
I've successfully assigned the new service principle directly to my Power BI Workspace using the rest api, but how do I now configure my rls? I can't find any documentation to guide me through this, it seems it all pertains to the old way using a username and password.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@CundyTech It's still in preview, but please review this article - https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security#on-premises-data-gateway-with-service-principal-preview.

Hope this helps.

Thank you.

**Comment by CundyTech** [comment]
Thanks @markingmyname. How does this work with Azure Analysis Services as there is no gateway to configure this permission? We've tried using the identity blob, but this comes back as not supported.

**Comment by u02cm62** [comment]
you use custom data and then use the guid service principal for username.  You don't need password.

**Comment by mattschoen** [comment]
I am having issues with this as well. We are using the service principle and I am getting the following error with a Live Connection to Azure Analysis Services: "requries effective identity username to be identical to the caller's principal name"

**Comment by u02cm62** [comment]
// For app only authentication, we need the specific tenant id in the authority url

                var tenantSpecificURL = AuthorityUrl.Replace("common", Tenant);

                var authenticationContext = new AuthenticationContext(tenantSpecificURL);

 

                // Authentication using app credentials

                var credential = new ClientCredential(ApplicationId, ApplicationSecret);

                authenticationResult = await authenticationContext.AcquireTokenAsync(ResourceUrl, credential);

            }

 

            return authenticationResult;

        }



Need to determine how we handle creating Token Param since it requires a master user account.

generateTokenRequestParameters = new GenerateTokenRequest("View", null, identities: new List<EffectiveIdentity> { new EffectiveIdentity(username: credential.UserName, roles: new List<string> { roleName }, datasets: new List<string> { dataSetId }, customData: upn) });

This format where credential.Username, you put your Service Principal object ID.

Matt- Are you still getting that error after doing this?
Do you have the service principal as an admin on the workspace and in the cube role?

**Comment by v-shshet** [comment]
Hi Matt,
In username Tab you need to have the Service principal Object ID instead of Application ID. As discussed offline it is working as expected now. Let us know if you see any issues.

**Comment by mattschoen** [comment]
> Hi Matt,
> In username Tab you need to have the Service principal Object ID instead of Application ID. As discussed offline it is working as expected now. Let us know if you see any issues.

@Shrshet that worked... I used the Service Principal ID based on those instructions as the effective username.

**Comment by markingmyname** [comment]
Application ID - used for authentication
SP Object ID - used for changing the use of the service principal

**Comment by markingmyname** [comment]
Thank you all for the feedback and collaboration.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
