### ISSUE TITLE
"Preview" label

### ISSUE THREAD

**Issue by vitaly-livshits** [MicrosoftDocs/powerbi-docs#884]
Please remove this label as the new modeling experience is live as of March 2019. Likewise for the remaining topics under "Concepts" folder in the TOC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4cfe8c6-b047-1277-8726-0d45d3630b8d
* Version Independent ID: b2e24404-209e-f043-b749-2e2e865a9e79
* Content: [Use Modeling view in Power BI Desktop (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-modeling-view)
* Content Source: [powerbi-docs/desktop-modeling-view.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-modeling-view.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@vitaly-livshits Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Thanks for sending your note @vitaly-livshits  - I've updated the article to reflect GA.

**Comment by vitaly-livshits** [comment]
@davidiseminger, it still shows us the version with "preview" references. Is there a delay to be aware of around propagating the changes?
