### ISSUE TITLE
Content seems outdated, images and descriptions are incorrect

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/powerbi-docs#885]
None of this seems to match what I see.  For example, steps 2/3 say to go to audit logs, but that's not listed.  Instead of what's in the screenshot, I see:

Usage metrics
Users
Tenant settings
Capacity settings
Embed Codes
Organization visuals
Workspaces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Using auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by markingmyname** [comment]
@jordanmills Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
@jordanmills - the screen is slightly out of date (Manage users should be Users) but mostly I just truncated the list on the left. Do you have the perms required to view audit logs: https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#requirements?

**Comment by mgblythe** [comment]
@jordanmills - I confirmed that Audit logs tab should show up in the UI if you have Power BI admin perms. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
