### ISSUE TITLE
Add add'l info about PostgreSQL prerequisite

### ISSUE THREAD

**Issue by scovetta** [MicrosoftDocs/powerbi-docs#886]
The document link takes the user to the NPGSQL GitHub releases page, presumably to download either the .msi or .vsix package. Installing the .msi package gives a by-default-disabled option of installing in the GAC. After installing, PowerBI continues to complain about the component not being there. Perhaps a reboot is required (why?), or maybe I downloaded the wrong package?

(The product "learn more" link should take the user to a page explaining what to do.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75d081a0-4c4b-f756-eaf7-1e98d583ecf8
* Version Independent ID: 0b694de6-df10-daca-888c-1062dd3299db
* Content: [Power BI data source prerequisites - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-source-prerequisites)
* Content Source: [powerbi-docs/desktop-data-source-prerequisites.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-source-prerequisites.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@scovetta Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
Thanks @scovetta, this issue is assigned to the author but in the meantime you might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by davidiseminger** [comment]
Thanks for the suggestion @scovetta. For support, you might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
