### ISSUE TITLE
Missing description of Analytics features 

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#887]
There is no description of Analytics features such as Symmetry Shading and Ratio Line, ref  https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2017-feature-summary/#symmetryShading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5668e4cf-3837-c2d4-b818-14476441468b
* Version Independent ID: c95096dd-9b73-79ab-8ff2-158c5900f5a6
* Content: [Scatter, bubble, and dot plot charts in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-scatter#create-a-scatter-chart)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-scatter.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-scatter.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @Mike-Honey 
Thank you for the feedback.  I'll update the scatter article with the symmetry shading improvement as soon as possible (likely, end of April). 
Thanks again,
Michele
