### ISSUE TITLE
Missing Symmetry Shading and Ratio Line

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#888]
There is no description of features: Symmetry Shading and Ratio Line, ref https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-august-2017-feature-summary/#symmetryShading

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d95f8c96-ab3e-b94c-2de5-abcf98e71169
* Version Independent ID: 709cb0ed-717a-10bc-62d6-2e4075806ce0
* Content: [Create dynamic reference lines for visuals - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analytics-pane)
* Content Source: [powerbi-docs/service-analytics-pane.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analytics-pane.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@Mike-Honey  Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!
