### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by MixolydianV** [MicrosoftDocs/powerbi-docs#89]
The links in the "Capacity Node" column of the Premium capacity nodes table (i.e. the EM1 through P3 links) require me to sign in to the Azure Portal, then throw a 404 when I do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ea9dd-618c-897e-4cce-97edc93df585
* Version Independent ID: 135f4574-36ed-6a3b-85d4-a565c57a1312
* Content: [Power BI Premium - what is it? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-premium)
* Content Source: [powerbi-docs/service-premium.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-premium.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mgblythe** [comment]
@MixolydianV - are you an Office 365 global admin for your tenant?

**Comment by docgregt** [comment]
I am a global admin and the EM1 links takes me to purchase EM3. Provide the EM1 purchase option.

**Comment by mgblythe** [comment]
@docgregt -- Checking into this now - I will update the links as soon as I get them.

**Comment by brmort** [comment]
Adding to this, the "month-to-month" link for the availability column for P1 in the table throws a 404

**Comment by mgblythe** [comment]
We removed the links from the rewritten version of this article. EM1 and EM2 SKUs are available only through volume licensing plans. They can't be purchased directly.
