### ISSUE TITLE
Vague description about consumer email account limitations

### ISSUE THREAD

**Issue by sgiovinetti** [MicrosoftDocs/powerbi-docs#890]
The document states: "However, those users may experience limitations beyond what users with work or school accounts encounter."

This description is very vague. What exactly are those limitations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad42c3b-e011-733d-dbdf-53944a2724a6
* Version Independent ID: 05e0f67c-5852-5b10-ac94-694ec2d0d8f9
* Content: [Distribute Power BI content to external guest users using Azure Active Directory B2B - Power BI](https://docs.microsoft.com/en-us/power-bi/whitepaper-azure-b2b-power-bi)
* Content Source: [powerbi-docs/whitepaper-azure-b2b-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/whitepaper-azure-b2b-power-bi.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@sgiovinetti Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Including the author of that whitepaper for further clarification.

**Comment by danmyhre** [comment]
Any update on this?

**Comment by mgblythe** [comment]
Assigning to @LukaszPawlowski-MS to respond.

**Comment by mgblythe** [comment]
We recommend using an org account rather than a consumer email b/c there are potentially multiple experiences that won't work for personal email accounts.

**Comment by danmyhre** [comment]
Which experiences?

**Comment by mgblythe** [comment]
Sorry @danmyhre, that's all the info I have.
