### ISSUE TITLE
Incorrect Version Number Mentioned

### ISSUE THREAD

**Issue by ajiljins** [MicrosoftDocs/powerbi-docs#891]
Please update the version number in the Title of this documentation, its the same since last December and confusing. Thanks

-Ajil

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6a76e2-8d94-5e76-bfb6-971c3b2c7c85
* Version Independent ID: f7bd2111-3bb0-fb08-0f23-a31efd407f66
* Content: [What's new in the latest Power BI Desktop update? - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-latest-update#feedback)
* Content Source: [powerbi-docs/desktop-latest-update.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-latest-update.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@ajiljins Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Sorry about that @ajiljins - I've fixed those issues and will keep a close eye on future releases. Thanks for your feedback!
