### ISSUE TITLE
Image "select-fields.png" step 6 - Shows incorrect fields selected

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/powerbi-docs#892]
The image in step 6: 

&lt;img src="media/service-gateway-sql-tutorial/select-fields.png" alt="Select fields" data-linktype="relative-path" class="x-hidden-focus"&gt;

Is incorrect, it is showing Category and sales selected, however the text and later images say, Product and Sales.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial#feedback)
* Content Source: [powerbi-docs/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by markingmyname** [comment]
@SteveGoodman Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
@arthiriyer - will add as part of gateway docs update

**Comment by mgblythe** [comment]
Thanks @SteveGoodman - sorry it took so long to get to this. Will be live in about an hour.
