### ISSUE TITLE
Missing step "Install a gateway for Power BI"

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/powerbi-docs#893]
I think there should be a step before "Add SQL Server as a gateway data source" or at least a link to Install a gateway for Power BI (https://docs.microsoft.com/en-us/power-bi/service-gateway-install) - it wasn't clear how I added a gateway.

Also when you refresh the data set of the report, I had to select the Data source.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial#feedback)
* Content Source: [powerbi-docs/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by markingmyname** [comment]
@SteveGoodman Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mgblythe** [comment]
@arthiriyer - will add as part of gateway docs update

**Comment by mgblythe** [comment]
Hi @SteveGoodman - installing the gateway is in the prerequisites for the article. Closing now, feel free to reopen if you have other questions.
