### ISSUE TITLE
Read-only members of a workspace cannot connect to datasets and How RLS can apply ?

### ISSUE THREAD

**Issue by BigDataenthu** [MicrosoftDocs/powerbi-docs#896]
I can see two contradicting statement , Please clarify 
1) Read-only members of a workspace cannot connect to datasets  - ok
2) You have mentioned RLS will be applied - as per https://docs.microsoft.com/en-us/power-bi/service-admin-rls   -&gt;  members have edit permissions, the RLS roles will not be applied to them. Users will be able to see all of the data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@BigDataenthu Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by davidiseminger** [comment]
Sorry for any confusion, we believe those comments are correct.
Your best venue for getting further clarification or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
