### ISSUE TITLE
Visualization Filters and Field Panes Gone!

### ISSUE THREAD

**Issue by mansfjc** [MicrosoftDocs/powerbi-docs#897]
The visualization filters and field panes suddenly disappeared this week. Where did they go and how do you get them back?? We used this Q&A feature to build custom dashboards for end users, but now you can't pick or customize your visualizations or select specific fields. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f8e2480-703a-1417-c5d9-8d019669f45a
* Version Independent ID: 17a9f60e-b9b6-8426-2176-86b5ec3cb68f
* Content: [Overview of Q&A in Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-q-and-a#feedback)
* Content Source: [powerbi-docs/consumer/end-user-q-and-a.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-q-and-a.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@mansfjc Your contribution is much appreciated. Our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
