### ISSUE TITLE
Can I use this in an Employee Use Case, also?

### ISSUE THREAD

**Issue by crisher0219** [MicrosoftDocs/powerbi-docs#898]
Instead of using the JavaScript API to persist filters, can I just use logic to change the URL and its parameters that I have embedded in the iFrame? In addition, if I go that route, will the user be able to see that I have applied a filter context and could they remove that filter context?

Use Case is... Each manufacturer can only see the search data on their products embedded within the Customer Portal app. They do not have their own Power BI licenses, and there are thousands of manufacturers so RLS is not really feasible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by crisher0219** [comment]
Sorry, the subject should be "Embedded Use Case". Stupid auto-correct.

**Comment by markingmyname** [comment]
@crisher0219 Thanks for your comment! Sounds like this is a product question, so please use the Product Feedback button in this article, or try the community, https://community.powerbi.com/.
