### ISSUE TITLE
Streaming or PushStreaming modes not supported

### ISSUE THREAD

**Issue by sinaakhtar** [MicrosoftDocs/powerbi-docs#899]
When I try to create a dataset using the API with "defaultMode":"PushStreaming" I receive a 400 response with the following message:
{
    "error": {
        "code": "InvalidRequest",
        "message": "This dataset or endpoint does not support column properties other than name and dataType."
    }
}

The only defaultMode that works is Push. I do not know understand why the documentation lists this as an option when it's not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0edb0181-a93b-1a46-0eb8-56d0262eb063
* Version Independent ID: c5833e6f-b0c1-4a92-0039-d4ef9b2b935a
* Content: [Power BI dataset properties - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/api-dataset-properties)
* Content Source: [powerbi-docs/developer/api-dataset-properties.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/api-dataset-properties.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@sinaakhtar Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
Good catch, @sinaakhtar!  

Also, @sinaakhtar,  did you know: For minor things like typos, you can edit the doc! Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

I will go ahead and update the article accordingly.

The update should be live by the end of next week.

Thank you again!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
