### ISSUE TITLE
Nothing about content packs vs. app workspaces?

### ISSUE THREAD

**Issue by sqlsauce** [MicrosoftDocs/powerbi-docs#90]
This self-guided learning does not appear to cover app workspaces, and instead presents content packs as a way to share reports and data. Microsoft's latest guidance is to use app workspaces instead of content packs, so please talk about app workspaces in this series.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94b08723-3d20-45e8-1a6e-348c33cb5ff2
* Version Independent ID: a201f1c5-9771-5eff-bac6-85de7058a8b3
* Content: [Getting started - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/gettingstarted?tutorial-step=6)
* Content Source: [powerbi-docs/guided-learning/gettingstarted.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/gettingstarted.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@sqlsauce - thanks for your feedback. We're in the process of updating that guidance, and will certainly cover app workspaces (instead of content packs) during that update.
