### ISSUE TITLE
Service Requests

### ISSUE THREAD

**Issue by JimDionisio** [MicrosoftDocs/powerbi-docs#900]
I notice that the app does not include access to ServiceNow Service Requests.  While we use Open Incidents, We start the process as a service request.  Is it possible to add access to this data as well?

Thank you,

**Comment by mihart** [comment]
Hi @JimDionisio,
Can you provide more context? Which "app" are you referring to?
Thanks,
The DOCS team

**Comment by mihart** [comment]
Hi @JimDionisio ,
Sorry, hit RETURN too quickly.  Please submit a new ticket with more context.  Are you referring to a particular doc article? If this is not feedback about a document, you can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.
