### ISSUE TITLE
Export Data

### ISSUE THREAD

**Issue by mzelich** [MicrosoftDocs/powerbi-docs#901]
Using this feature I can only export data from a visualization in .csv format. Is there an option to export the data as .xlsx?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7197c1f9-ff31-f86c-faf3-ab89e4ab9573
* Version Independent ID: f30cdf40-43c4-e0c3-4941-a02f5bb28fc1
* Content: [Embed a report in a secure portal or website - Power BI](https://docs.microsoft.com/en-us/power-bi/service-embed-secure#feedback)
* Content Source: [powerbi-docs/service-embed-secure.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-embed-secure.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mihart** [comment]
Thanks for your comment, @mzelich . This looks like a product question, rather than documentation feedback. You can submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.

**Comment by markingmyname** [comment]
@mzelich Unfortunately, there is not.

This is a good opportunity to submit product feedback or feature ideas by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team at https://community.powerbi.com.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
