### ISSUE TITLE
What if ... 

### ISSUE THREAD

**Issue by lynchmob98** [MicrosoftDocs/powerbi-docs#902]
The 2nd Step #3 above says ... Verify your credentials, then select Connect ... what if I do that and it says "We couldn't authenticate with the credentials provided"?  These are credentials that work when I use them from SSMS ... so ... the problem isn't the credentials.  It would help here to have more/better examples at this step ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f589c5a-4ee4-be0e-85d1-af9953969631
* Version Independent ID: 0ccf859d-8b81-9d01-62ac-a9c0576887fa
* Content: [Tutorial: Connect to on-premises data in SQL Server - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-sql-tutorial#feedback)
* Content Source: [powerbi-docs/service-gateway-sql-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-sql-tutorial.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @lynchmob98 . This issue has been assigned to the doc author for review.

**Comment by mgblythe** [comment]
@arthiriyer - will include as part of gateways doc update

**Comment by mgblythe** [comment]
Hi @lynchmob98 - we rewrote the article with a different example. Let me know if it;s clear, thanks.
