### ISSUE TITLE
Explain background, foreground, and tableAccent

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#903]
There is some (duplicated) text supposedly describing: "background, foreground, and tableAccent". I find that very confusing and incomplete, e.g. read it and tell me what "tableAccent" does? Also foreground seems to drive table column header and total background colors for some table styles (e.g. alternating rows) - not mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes#structure-of-a-report-theme-json-file)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Mike-Honey -- Thanks for your question. I've referred it to the author for a response. In the meantime, I suggest asking in the Power BI Community, https://community.powerbi.com/.

**Comment by davidiseminger** [comment]
Hello @Mike-Honey - I'm sorry, I don't see where the confusing or incomplete passages are. If you want to resubmit with more specific sections and passages, I'll be happy to see if I can improve or clarify.

**Comment by Mike-Honey** [comment]
@davidiseminger  - To find the specific passages, just use Find on the page and look for "background, foreground, and tableAccent". 

If you think it is complete, please tell me: what does tableAccent do? How does foreground affect a table?
