### ISSUE TITLE
How does Oracle connector works in case of direct query?

### ISSUE THREAD

**Issue by Anmolgan81** [MicrosoftDocs/powerbi-docs#904]
I want to use Direct Query mode in order to query the Oracle database, do we still need to install On-Premise data gateway in the Oracle database in order to directly connect the powerbi.com to the On-premise data gateway?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc3332c2-1973-ba6d-8b13-20185f3178a8
* Version Independent ID: 09b16196-3c5e-8a12-edee-d1c095ebc6d0
* Content: [Data sources supported by DirectQuery in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-directquery-data-sources)
* Content Source: [powerbi-docs/desktop-directquery-data-sources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-directquery-data-sources.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @Anmolgan81 -- Thanks for your question. I've referred it to the author for a response. In the meantime, I suggest asking in the Power BI Community, https://community.powerbi.com/.

**Comment by davidiseminger** [comment]
Thanks for your comment, @Anmolgan81. This looks like a support request rather than documentation feedback. You might find a solution in the Power BI Community, found at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by MichaelTomar** [comment]
You can use [Skyvia](https://skyvia.com/data-integration/powerbi) as an alternative integration solution
