### ISSUE TITLE
Refresh Automatically?

### ISSUE THREAD

**Issue by jaker12** [MicrosoftDocs/powerbi-docs#905]
Can you please offer some clarification on if your get data source is web if the Power BI file will refresh automatically when published to the service or if a schedule refresh via a Gateway needs to occur or if this is not possible at all. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2e2c100-ccb2-a69b-cd7c-f564441c573d
* Version Independent ID: f37af593-9e1f-9bb4-e5d8-b5500505f6a5
* Content: [Tutorial: Import and analyze data from a web page - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tutorial-importing-and-analyzing-data-from-a-web-page#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tutorial-importing-and-analyzing-data-from-a-web-page.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @jaker12 -- Thanks for your question. I've referred it to the author for a response. In the meantime, I suggest asking in the Power BI Community, https://community.powerbi.com/.

**Comment by davidiseminger** [comment]
Thanks for posting – note that we can only answer feedback related to the documentation, and can’t provide direct support or respond feature requests. 
Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.

**Comment by ed7257** [comment]
I don't see @jaker12 question answered in the thread. Could you please answer @davidiseminger ?  I have the same question after I read this article.
