### ISSUE TITLE
image is not correct

### ISSUE THREAD

**Issue by lambiek1963** [MicrosoftDocs/powerbi-docs#906]
The image below this text is not correct:
You can also change, or transform, those columns from text to header by using the Transform ribbon. Here’s the Transform ribbon, with an arrow pointing toward the Data Type button, which lets you transform the current data type to another.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf2015c-41fe-8234-dd4d-698e589b6fc7
* Version Independent ID: bc0deeb1-04c7-abc3-b26c-10ea6d75c57f
* Content: [Getting started with Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-getting-started#feedback)
* Content Source: [powerbi-docs/desktop-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-getting-started.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @lambiek1963 -- thanks for your comment! I've assigned it to the author to respond.

**Comment by davidiseminger** [comment]
Thanks for pointing that out - the image has been fixed, and will update within 24 hours. Thanks!
