### ISSUE TITLE
Less colors than the palette: previous colors kept

### ISSUE THREAD

**Issue by renaudma** [MicrosoftDocs/powerbi-docs#907]
Hello,

contrary to what is said
"dataColors: The list of hex code color codes to use for data in Power BI Desktop visuals. The list can have as many or as few colors as you want."

inputting less than the number of colors on the color palette (example 5 colors in the Json file instead of 8) will only change 5 colors out of the 8. The 3 remaining will be the one from the previous imported / default theme

**Comment by markingmyname** [comment]
Hello, @renaudma,  thank you for your comment. I can't tell by the title and the lack of supporting detail what exact article you are referencing. Can you please explain by 03/29? Thank you.

**Comment by mgblythe** [comment]
It looks like this is for https://docs.microsoft.com/en-us/power-bi/desktop-report-themes, now assigned to the author for review.

**Comment by renaudma** [comment]
Hello,

PBI Desktop has 8 colors in a theme (+2 black & white).
When importing a json file with less than 8 colors, PBI will replace only the colors imported, while keeping previous colors (in my example, 5 colors imported, 3 left from the previous theme).
=> Ideally, for a theme, old colors should be removed. A solution could be to reduce the color palette to less than 8 colors (if that is what is imported) or to generate colors (darker or brighter) based on what is imported to complete it to a total of 8.

**Comment by renaudma** [comment]
and yes sorry, it was linked to this article https://docs.microsoft.com/en-us/power-bi/desktop-report-themes
(I thought the article would be linked automatically when creating a new comment).

thanks for taking a look!
