### ISSUE TITLE
demo PBIX file is corrupted

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs#908]
"Unable to open document - is corrupt or an invalid report file"
PBI Desktop: Feedback Type:
Frown (Error)

Timestamp:
2019-03-22T10:22:16.1350351Z

Local Time:
2019-03-22T13:22:16.1350351+03:00

Session ID:
a58d35f8-eb9f-4574-a095-b9eb092a686a

Release:
April 2019

Product Version:
2.68.5432.241 (19.04) (x64)

OS Version:
Microsoft Windows NT 10.0.17763.0 (x64 en-US)

CLR Version:
4.7 or later [Release Number = 461814]

Peak Virtual Memory:
38 GB

Private Memory:
233 MB

Peak Working Set:
415 MB

IE Version:
11.379.17763.0

User ID:
5a4298cd-88d9-445a-9565-3f8ec74db5c4

Workbook Package Info:
1* - ru-RU, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Model Default Mode:
Empty

Snapshot Trace Logs:
C:\Users\achizh\Microsoft\Power BI Desktop Store App\FrownSnapShot2078847510.zip

Performance Trace Logs:
C:\Users\achizh\Microsoft\Power BI Desktop Store App\PerformanceTraces.zip

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_NewWebTableInference
PBI_showIncrementalRefreshPolicy
PBI_showManageAggregations
PBI_improvedFilterExperience
PBI_qnaLiveConnect
PBI_keyDrivers
PBI_userFavoriteResourcePackagesEnabled

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
MSIT

DPI Scale:
150%

Supported Services:
Power BI

Formulas:

section Section1;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by markingmyname** [comment]
@chizhova, thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by mihart** [comment]
Thanks for your comment, @chizhova . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
