### ISSUE TITLE
Confusing directions

### ISSUE THREAD

**Issue by hooveray5** [MicrosoftDocs/powerbi-docs#909]
Directions say to use format (https://&lt;tenantname&gt;.sharepoint.com/sites/pwa/_api/Projectdata)

But the picture contradicts this by displaying (https://contoso.sharepoint.com/sites/pwa/_api/default.aspx) which did not work for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa7de3f7-737b-cbbd-0911-e5535b198795
* Version Independent ID: 26615fdb-93ac-8d7f-f7cc-f7ebc436aa04
* Content: [Project Online: connect to data through Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-project-online-connect-to-data#feedback)
* Content Source: [powerbi-docs/desktop-project-online-connect-to-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-project-online-connect-to-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by markingmyname** [comment]
@hooveray5, thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by davidiseminger** [comment]
Sorry for the confusion. Please use the directions in text, not the picture. We'll update that picture as soon as we can.
