### ISSUE TITLE
Confusing examples

### ISSUE THREAD

**Issue by RSteeno** [MicrosoftDocs/powerbi-docs#91]
The sample machine names that are used in this article are confusing.  Please update them to something that can be more comprehensible to avoid confusion for the reader.  Here is a sample:

Active Directory Domain (Netbios): contoso
Gateway machine name: MYGATEWAY
Gateway service account: contoso\GatewaySvc (account display name: Gateway Connector)
SQL Server data source machine name: MYSQLServer
SQL Server data source service account: contoso\SQLService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b25ab3-f22b-e70b-e262-6266dd132692
* Version Independent ID: e5cbbdd4-0c02-6c05-91f4-016b767eb233
* Content: [Use Kerberos on the on-premises gateway for SSO (single sign-on) from Power BI to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-kerberos-for-sso-pbi-to-on-premises-data)
* Content Source: [powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @RSteeno -- again, the author is away and will get back to you when he returns. Thanks for your attention!

**Comment by mgblythe** [comment]
Thanks @RSteeno -- I will address week of 8/20.

**Comment by mgblythe** [comment]
@arthiriyer - we'll look at this now we're doing a gateway docs update.

**Comment by AdamBJ** [comment]
@mgblythe this issue should be closable now -- I address it in the revisions that were recently merged in.

**Comment by mgblythe** [comment]
Thanks @AdamBJ. This content is now updated and in https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos.
