### ISSUE TITLE
Error Using RLS with Service Principal (embedded) and Azure Analysis Services Live Connection

### ISSUE THREAD

**Issue by mattschoen** [MicrosoftDocs/powerbi-docs#910]
I cannot get an embedded report to run using a Service Principal and a Azure Analysis Services Live Connection. I am getting the following error:

"Creating embed token for accessing dataset &lt;DATASET GUIDE&gt; requries effective identity username to be identical to the caller's principal name"

The JSON package is as follows:
{
  "accessLevel": "view",
  "identities": [
    {
      "username": "&lt;SERVICE PRINCIPAL APP ID GUIDE&gt;",
      "roles": [
        "Test Role"
      ],
      "datasets": [
        "&lt;DATASET GUID&gt;"
      ],
      "customData": "&lt;EMAIL ADDRESS&gt;"
    }
  ]
}

I have added the Service Principal App ID to Azure Analysis Service at the Admin and Membership level and still not working. I have tried passing the Service Principal App ID along with the Tenant ID and it sill is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61878b62-89e5-e60a-4995-74d9650ca3e6
* Version Independent ID: 378733df-8807-3274-dcf3-3e2aa40a78c0
* Content: [Use row-level security with Power BI embedded content - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security)
* Content Source: [powerbi-docs/developer/embedded-row-level-security.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-row-level-security.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
@mattschoen

Thank you for your feedback! We will investigate and get back to you with the relevant info.

**Comment by markingmyname** [comment]
@mattschoen I see you commented in this thread as well - https://github.com/MicrosoftDocs/powerbi-docs/issues/882.  Is this a different scenario?

**Comment by markingmyname** [comment]
In username Tab, you need to have the Service principal Object ID instead of Application ID. As discussed offline it is working as expected now. Let us know if you see any issues.

Application ID - used for authentication
SP Object ID - used for changing the use of the service principal

**Comment by mattschoen** [comment]
Its the same scenario...

**Comment by markingmyname** [comment]
@mattschoen,

Thanks for your comment! Sounds like this is a product question, so please use the Product Feedback button in this article, or try the community, https://community.powerbi.com/.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
