### ISSUE TITLE
Error: "Something went wrong" when saving Dataflow to ADSL gen 2 after following the article instructions

### ISSUE THREAD

**Issue by KevinCallinswood** [MicrosoftDocs/powerbi-docs#912]
Feedback:  In the section "Grant Power BI permissions to the file system" there is no mention of unchecking the "Default" Owner privileges on the root "powerbi" folder.  This will prevent the first save of a Dataflow to your v2 Workspace from giving the error "Something went wrong".  

In addition, it wasn't clear to me that this feature is only available to v2 Workspaces.  I would recommend making this clear at the start of the article i.e.  "You can configure Power BI workspaces to store dataflows in your organization’s Azure Data Lake Storage Gen2 account".  When creating a V2 Workspace you have to go into the Additional Settings and change the slider to use the Dataflow Storage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#feedback)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @KevinCallinswood. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback. Note that this feature is currently in preview.

You can submit product feedback or feature ideas directly by going to https://ideas.powerbi.com. You can also engage with the Power BI engineering team by being active in the Power BI Community, found at https://community.powerbi.com.
