### ISSUE TITLE
Azure Consumption Insights connector: No cost data retrieved

### ISSUE THREAD

**Issue by A141135** [MicrosoftDocs/powerbi-docs#913]
I've been using this connector for some time and it's generally great.

However as of 22-March, all cost data in the Detail Charges and PriceSheets tables is showing as $0.

Can this please be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e71361e-a9bb-89ee-27ee-7e38a60914a0
* Version Independent ID: df5a9b26-4eb1-a396-1c84-9f3ec6232753
* Content: [Connect to Azure cost and usage from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-connect-azure-consumption-insights#feedback)
* Content Source: [powerbi-docs/desktop-connect-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-connect-azure-consumption-insights.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by matt-black-mac** [comment]
I too have been using the connector for a while without issue - until last week.  Now when I refresh the Detail Charges data going back to July 2018 (when our enrollment started) some months show the costs whilst others report £0.

**Comment by MPEV** [comment]
I have the same with zero cost (if only) since the beginning of March.

**Comment by tom-ditlev** [comment]
I have the exact same problem. Saw it first on 19-March. Doing two or three on demand refreshes "fixed" it but now it broke again. I have done one on demand refresh, but that did not help. I have several different datasets against Azure Consumption Insights and they are all broken.

Wondering if this is the right place to report this issue...?

**Comment by DavidTHunt** [comment]
similar issues here. Is there a known cause or workaround?  Also the consumption insights app you download from marketplace has the same issues, not indicative of all months, it appears to be select months that costs are @0.   201810, 201812, 201901, 201903   Costs are still populated for other months.

**Comment by pbeckman01** [comment]
I have the same problem but I'm missing a different set of months.  In my case all data after November 2018 is missing.

This is a serious issue for us as we track all Azure spend using PowerBI reports.  The monthly and quarterly reports for the exec team are all based on Azure Consumption Insights.

**Comment by sonalimanohar** [comment]
Someone just mentioned to me that we now have to use a new connector called "Azure Cost Management" instead of Azure Consumption Insights. Is that true? I do not find references of this anywhere except this article that mentions that this connector is coming up: https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-march-2019-feature-summary/. Has anyone verified this? 
Note that I do not even see the new connector "Azure Cost Management" in my list.

**Comment by mgblythe** [comment]
Thanks for opening this, @A141135 and for the followup feedback everyone. I'll keep this open b/c this might have a doc component, but you might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.

**Comment by chrisweis** [comment]
Hello all, I submitted a Support request and communicated with the Azure Cost Management team last Friday and this zeroes issue was resolved on Monday.  It was impacting the EA portal, ACI PBI connector and ACI PBI content pack.

**Comment by A141135** [comment]
Also submitted a support case and had confirmation this was resolved on Tuesday. The data has been looking good for us since then. Thanks!
