### ISSUE TITLE
Service Principle currently not support Admin Right

### ISSUE THREAD

**Issue by v-kerwan** [MicrosoftDocs/powerbi-docs#914]
Get confirmation from PG, Service Principle currently not support Admin Right, could you please update the document under consideration and limitation

"Power BI admin rights are required to enable service principal in developer settings within the Power BI admin portal."  this is incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c135bb4c-618b-478d-bce7-ac8608e3caac
* Version Independent ID: a297498b-afa2-575d-417c-0cb4696a90af
* Content: [Service principal with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#feedback)
* Content Source: [powerbi-docs/developer/embed-service-principal.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-service-principal.md)
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for your comment, @v-kerwan . This issue has been assigned to the doc author for review.

**Comment by markingmyname** [comment]
@v-kerwan [Article](https://docs.microsoft.com/en-us/power-bi/developer/embed-service-principal#considerations-and-limitations) has been updated.

Thank you.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
