### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by vish4luffy** [MicrosoftDocs/powerbi-docs#915]
Hi, 

This is Vish here. So I just wanted to point out that the absence of the dataset that the trainer is using is making things hard for me to understand because I'm not able to replicate and practice stuff to better understand concepts. Or is the dataset provided somewhere here? if yes, do point the location of the same. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49462b9d-81da-e29a-f148-1fd95395a570
* Version Independent ID: 4ce1f7c2-0170-35b5-adca-c92c41fb7fc1
* Content: [Modeling - Power BI](https://docs.microsoft.com/en-us/power-bi/guided-learning/modeling?tutorial-step=8#feedback)
* Content Source: [powerbi-docs/guided-learning/modeling.yml](https://github.com/MicrosoftDocs/powerbi-docs-pr/blob/live/powerbi-docs/guided-learning/modeling.yml)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @vish4luffy. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback @vish4luffy  - unfortunately, not all datasets are available for some of our tutorials and articles, including this one. We're anticipating future articles will (and many do) include links to the datasets used for the article.
