### ISSUE TITLE
KCD with Local SID

### ISSUE THREAD

**Issue by RSteeno** [MicrosoftDocs/powerbi-docs#92]
The following note contains reference to the "Service SID" and is NOT clear on where kerberos configuration needs to be made when a company has AAD Sync in place.  In this case, the kerberos configuration needs to be made on the gateways computer object in Active Directory.  Since the gateway service is using a local account, that account will not be present in Active Directory.

"If AAD DirSync / Connect is configured and user accounts are synchronized, the gateway service does not need to perform local AD lookups at runtime, and you can use the local Service SID (instead of requiring a domain account) for the gateway service. The Kerberos Constrained Delegation configuration steps outlined in this article are the same as that configuration (they are simply applied based on the service SID, instead of domain account)."

Example to make it clearer:

"If AAD DirSync / Connect is configured and user accounts are synchronized, the gateway service does not need to perform local AD lookups at runtime, and you can use the local Service SID (instead of requiring a domain account) for the gateway service. The Kerberos Constrained Delegation configuration steps outlined in this article are the same as that configuration (they are simply applied to the gateway's computer object in Active Directory, instead of the domain account)."

After clarifying this approach with Premier Support, i was able to successfully implement kerberos constrained delegation by following the remaining steps in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41b25ab3-f22b-e70b-e262-6266dd132692
* Version Independent ID: e5cbbdd4-0c02-6c05-91f4-016b767eb233
* Content: [Use Kerberos on the on-premises gateway for SSO (single sign-on) from Power BI to on-premises data sources - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-kerberos-for-sso-pbi-to-on-premises-data)
* Content Source: [powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-kerberos-for-sso-pbi-to-on-premises-data.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by maggiesMSFT** [comment]
Hi, @RSteeno -- the author of this article is off on vacation, lucky man. He'll be happy to review your feedback when he returns!

**Comment by RSteeno** [comment]
Great. Thanks for letting me know.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgblythe** [comment]
Thanks @RSteeno - fixing now.

**Comment by mgblythe** [comment]
Well I made the change but never published it :-( It's now live in the updated article: https://docs.microsoft.com/en-us/power-bi/service-gateway-sso-kerberos
