### ISSUE TITLE
Step 5 says Power BI Premium & it should say Power Query Online

### ISSUE THREAD

**Issue by sqlchick** [MicrosoftDocs/powerbi-docs#921]
Step 5 says to copy the Object ID for Power BI Premium when it really should say Power Query Online. (Note that the accompanying reference in step 8 is correct though.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2#feedback)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @sqlchick. This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the close read @sqlchick  - I've updated the article with your corrected step. Thanks!
