### ISSUE TITLE
Error recognizing xls files with passwords removed during import.

### ISSUE THREAD

**Issue by uncommon33** [MicrosoftDocs/powerbi-docs#922]
I am having a problem with Power BI recognizing workbooks that had passwords, and that may still have external links to other data sources.  I have a folder of 187 .xls files. All of them at one point had spreadsheetst that were password protected.  All of the password protection has been removed.  Yet when I set up an import based on the folder, Power BI and Power Query will get through the first five files importing the information, then present an error code when it gets to the next file in the series.  I have reviewed the file and can find nothing that I can see that would prevent the import with the exception of possibly external links. The links are to files that no longer exist. Is this the problem?  
When using Power Query, I get the error saying that the files are password protected, when they are not.  Any help would be deeply appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 680485c7-5823-2c7f-df5d-b8c8a8205759
* Version Independent ID: 5a217642-7723-6980-28ae-e26559c24201
* Content: [Resolve Access and .XLS import issues in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-access-database-errors#feedback)
* Content Source: [powerbi-docs/desktop-access-database-errors.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-access-database-errors.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @uncommon33. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
