### ISSUE TITLE
Don't have a destination

### ISSUE THREAD

**Issue by MadDenker** [MicrosoftDocs/powerbi-docs#923]
I do not see a destination to publish to.  How do I create such a workspace?  Can you link to that information here?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef5362a0-2148-3de0-fd60-a3fe5d06fe91
* Version Independent ID: 1967384e-308d-cf6f-ad5f-cde6e5b741b3
* Content: [Publish from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-upload-desktop-files)
* Content Source: [powerbi-docs/desktop-upload-desktop-files.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-upload-desktop-files.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for your comment, @MadDenker. This issue has been assigned to the doc author for review.

**Comment by MadDenker** [comment]
I found this like to be very helpful https://docs.microsoft.com/en-us/power-bi/service-manage-app-workspace-in-power-bi-and-office-365

**Comment by maggiesMSFT** [comment]
Hi, @MadDenker -- This article might be a better place to start: https://docs.microsoft.com/en-us/power-bi/service-create-workspaces.
