### ISSUE TITLE
System Metrics green tick

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/powerbi-docs#924]
If we have Azure Embedded A1 Capacity and one subscription has a green tick for "System Metrics" and the other has a red cross, what are we missing? 
Could you add documentation about each red cross and how to make it green?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity#use-the-metrics-app)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by mgblythe** [comment]
Thanks for your comment, @mikeblakeuk. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@mikeblakeuk - The red cross means the admin hasn't assigned reader roles to the app in azure portal. Once permission is granted, after the app is refreshed the cross should turn into a green checkmark. We'll try to get this documented.
#in-progress
