### ISSUE TITLE
Version History

### ISSUE THREAD

**Issue by mikeblakeuk** [MicrosoftDocs/powerbi-docs#925]
Please provide a link to the version history.
I'm using 1.10.1.4 yet the latest in this document is 1.10.1.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3451b495-3af0-170e-a93c-d7360bf6b8cd
* Version Independent ID: 5e964973-a536-b049-9eb9-5120be3f75e8
* Content: [Monitor Power BI Premium capacities with the Premium Capacity Metrics app. - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-premium-monitor-capacity#get-app-refresh-history)
* Content Source: [powerbi-docs/service-admin-premium-monitor-capacity.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-premium-monitor-capacity.md)
* Service: **powerbi**
* GitHub Login: @Minewiskan
* Microsoft Alias: **owend**

**Comment by mgblythe** [comment]
Thanks for your comment, @mikeblakeuk. This issue has been assigned to the doc author for review.

**Comment by Minewiskan** [comment]
@mikeblakeuk - Thanks for commenting. We decided to remove the version reference in this article altogether. Often times, engineering makes an update to the app that has no visual or functional change exposed to users. In those cases, there's now coordination with the docs, and things can get out of sync really fast.
#please-close

**Comment by mikeblakeuk** [comment]
Bu the Application still has a version number (as a tile). 
How do we know what has changed?
