### ISSUE TITLE
Availability of Visual in Australia

### ISSUE THREAD

**Issue by justinreading** [MicrosoftDocs/powerbi-docs#928]
Can anyone let us know the release schedule for this visual? Specifically, when will this be available in Australia?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4200dd45-15ab-ee4a-9818-10cc81475f64
* Version Independent ID: 0b96ac28-e2a2-41c9-eff0-efd864fc0529
* Content: [Key influencers visualizations tutorial - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-influencers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-influencers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-influencers.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by justinreading** [comment]
Actually, never-mind latest PBI Desktop update wasn't applied.....all good now.

**Comment by maggiesMSFT** [comment]
Good to hear -- thanks for the update, @justinreading! Closing this now.
