### ISSUE TITLE
refresh from Power BI service doesnt work

### ISSUE THREAD

**Issue by dunganhle** [MicrosoftDocs/powerbi-docs#929]
Hi,

When trying to refresh my report that uses "Web from example" like source, the Power BI Service doesnt want it.
Below is what I get : 

Data source error: | The import Html.Table matches no exports. Did you miss a module reference?. The exception was raised by the IDataReader interface. Table: xxx
-- | --
Cluster URI: | WABI-NORTH-EUROPE-redirect.analysis.windows.net
Activity ID: | 1efea768-e786-4f44-bc91-a00e9f102eda
Request ID: | 6496d34a-57c8-4932-95a2-18e6616b17a6
Time: | 2019-03-27 01:19:55Z

Thank you,
DA

**Comment by mgblythe** [comment]
Thanks for your comment, @dunganhle. This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
