### ISSUE TITLE
Date on employee table

### ISSUE THREAD

**Issue by jfreel** [MicrosoftDocs/powerbi-docs#93]
What is the "date" column used for and what does it represent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26de6125-fac6-cf9b-3677-861d0dd69d13
* Version Independent ID: 7ab8f758-bc5a-12b6-96ba-1b14c091811a
* Content: [Human Resources sample: Take a tour - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-human-resources)
* Content Source: [powerbi-docs/sample-human-resources.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-human-resources.md)
* Service: **powerbi**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mihart** [comment]
Hi @jfreel 
Thanks for writing. I'm not sure I understand your question but will try to answer. 
If you expand the "Date" column, you'll see columns for day, month, quarter, year, etc.  You can use values from the Date column to filter your data.  For example, on the New Hires Scorecard tab, Date > Period is used in the "New Hire Count by Period"  linechart. 

HTH,
Michele

**Comment by spulente** [comment]
Hi @mihart 
 Can I ask an question about the date field, as well?  In the employee tab is the first date column just random dates from the date tab and why from 2011 to 2014?  Is this used to help link tables?  I don't see how the first date column correlates to the data within the employee tab ie. Hire or Term date.  Appreciate some feedback on this as I am new to Power BI and posting in forums.  
Thanks,
Sue

**Comment by gihandt** [comment]
Hi @mihart,
Thanks for this very useful sample. 

I'm not sure you're the best person to ask this question. 

Apologies if that's the case and appreciate if you can direct me where I should get answers to this.  

I'm trying to connect to our data sources now to explore more on this. 
However, I would like to understand how the underlying source database (SQL Server I presume) is modelled. 

I have looked at the Data Model in Excel, but unable to view the underlying SQL queries that pull the data from the source DB to get more sense into the data sourcing process. 
These are grayed out as there's no connection to the original source SQL Server.
Is the source DB an OLTP DB or a DW DB? 


Thanks

**Comment by samhall100** [comment]
Hi @spulente & @Mihart

I too have had the same question about this data, it took me 30 minutes to work out so please see below:

Before answering this question directly lets first think about the data in the model.

The data is extracted from a system once a month, i.e. 01/06/2014 so each month the data in the employee table is refreshed which means we have multiple rows for each employee number.

The "date" field, the first column in the employee table is used as follows.

For active staff - it is the start of the month for that reporting month, the first day (every month new data is added to the model)

For inactive staff - those who have an actual "TermDate" i.e. 24/09/2014 the date displays as the first of that termination month, so it would be 01/09/2014.

The model uses this to roll up the numbers for people who leave on different days in each month.

Go to the employee table in the data view mode and filter on employee 1138 and you will see exactly what I mean as outlined above.

Thanks 

Sam Hall
