### ISSUE TITLE
Those with free licenses suddenly can't connect to datasets in new workspaces

### ISSUE THREAD

**Issue by ameliator** [MicrosoftDocs/powerbi-docs#932]
Hello,

Is anyone else having access issues in the new workspaces?

Those with free licenses are trying to connect to datasets in a workspaces in the premium capacity. (They are trying to connect from the desktop editor)

There were able to connect with member status, but have suddenly lost access. They can see the datasets when they go to get data, but get an error saying they don't have permission when they try to connect. 

We've tried changing them to admins to see if that worked, but it hasn't.

Those with pro are able to connect fine. 

Any ideas?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11357d2a-97f6-c5d6-2a62-0d5cae1a1c3d
* Version Independent ID: 51900b79-f5ed-25b8-ee89-9078129bdb15
* Content: [Create the new workspaces (preview) - Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-create-the-new-workspaces#feedback)
* Content Source: [powerbi-docs/service-create-the-new-workspaces.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-create-the-new-workspaces.md)
* Service: **powerbi**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @ameliator -- This sounds like a bug, not a doc issue. Can you try the Community site https://community.powerbi.com, and/or the Support site, https://powerbi.microsoft.com/en-us/support/?
