### ISSUE TITLE
Paginated reports in Power BI Embedded

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#935]
The Embedded FAQ states that "Power BI Embedded capacity content  [...] doesn't support SSRS reports."

However the Paginated reports in Power BI FAQ states that "The paginated reports workload is available on P1 – P3 SKUs for public preview. You may also use it for test/dev scenarios with A4 – A6 SKUs."

So it looks like the Embedded FAQ needs to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a447889-379d-3ded-9ab9-313c4f55a667
* Version Independent ID: 4f8e3f79-5025-919a-7282-8a63dda6bc8d
* Content: [Frequently asked questions about Power BI Embedded - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedded-faq#)
* Content Source: [powerbi-docs/developer/embedded-faq.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedded-faq.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Thanks for pointing out the discrepancy, @otravers! I've assigned your question to the author, who will be able to clear it up.

**Comment by markingmyname** [comment]
@otravers, good catch!

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
Good eye, @otravers! 

The article will be updated by the end of the week.

Also, for minor things like typos or short edits, you can edit the doc! 

Click the little Edit pencil icon in the article, then click the little Edit pencil in GitHub, make your change, scroll to the bottom, and click Propose file change. And voila! It's sent directly to the writer.
Then all the writer has to do is sign off and it goes into the publishing queue.

Thanks again!

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
