### ISSUE TITLE
missing field

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#936]
@LidiaVonk commented on [Thu Mar 28 2019](https://github.com/MicrosoftDocs/powerbi-docs.es-es/issues/21)

Field Senior in the calculation for "new rank" isn't available in the datasource http://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx . 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Gegevens van meerdere gegevensbronnen vormgeven en combineren - Power BI](https://docs.microsoft.com/nl-nl/power-bi/desktop-shape-and-combine-data#feedback)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Hi team, 
The issue seems to be about the original documentation
best

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc -- thanks for reporting the question! I've assigned it to the author, who will be reviewing it.

**Comment by davidiseminger** [comment]
Thanks for your feedback @CeciAc - we'll look into updating that progression in the article, to match updates in the data source. Sorry for the inconvenience.
