### ISSUE TITLE
Are *both* PowerBI Premium *and* PowerBI Pro required?

### ISSUE THREAD

**Issue by cap273** [MicrosoftDocs/powerbi-docs#937]
To create paginated reports, is my understanding correct that you need *both* (1) an app workspaces in a Power BI Premium capacity, *and* (2) a Power BI Pro license to publish a report to the PowerBI service? Documentation clarification in this regard would be highly appreciated!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce5d0507-1ff2-46ed-8563-e80b19644f26
* Version Independent ID: 415119ab-1731-b361-10ec-d9ace9802f7d
* Content: [What are paginated reports in Power BI Premium? (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/paginated-reports-report-builder-power-bi#feedback)
* Content Source: [powerbi-docs/paginated-reports-report-builder-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/paginated-reports-report-builder-power-bi.md)
* Service: **powerbi**
* Sub-service: **report-builder**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi @cap273 -- thanks for your question. To publish a paginated report, yes, you need a Pro license and you need to publish to a Premium capacity. Your report readers don't need the Pro license. 
Hope that helps!
