### ISSUE TITLE
Multiple, overlapping, inconsistent pages - please consolidate Gateway information 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/powerbi-docs#938]
Please integrate, consolidate or cross-reference all of the content about Data Gateways. There are currently page at https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/gateway-management and https://docs.microsoft.com/en-us/flow/gateway-manage. They are similar but different, since the data gateways are shared between Power BI, PowerApps and Flow, the documentation should be shared also. There is different good stuff in all 3 locations, but some inconsistencies in format and topics make it much harder than necessary to get a thorough understanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb1195df-a72b-61c1-3490-64ca851e81b1
* Version Independent ID: 8e9e2f51-78eb-7dfc-8195-cf99bd55d61c
* Content: [What are On-Premises Data Gateways? - Power BI](https://docs.microsoft.com/en-us/power-bi/service-gateway-getting-started)
* Content Source: [powerbi-docs/service-gateway-getting-started.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-gateway-getting-started.md)
* Service: **powerbi**
* Sub-service: **powerbi-gateways**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by DeanGross** [comment]
why was this closed without any action or explanation?

**Comment by mgblythe** [comment]
@DeanGross - this issue is still open. I closed the one in PowerApps.

@arthiriyer as FYI

**Comment by mgblythe** [comment]
@DeanGross - we've done most of the rework at this point to create a gateway doc set that is relevant for all services (https://docs.microsoft.com/en-us/data-integration/gateway/service-gateway-onprem). We've left any Power BI specific content in the Power BI docs (https://docs.microsoft.com/en-us/power-bi/service-gateway-onprem). I'll update here when we finish the rest of the cleanup work and link from PowerApps, etc. to the new content.

**Comment by mgblythe** [comment]
We've just cleaned up all the [SSO content](https://docs.microsoft.com/power-bi/service-gateway-sso-overview) as well as simplified the [PowerApps](https://docs.microsoft.com/powerapps/maker/canvas-apps/gateway-reference) and [Flow](https://docs.microsoft.com/flow/gateway-reference) docs. We might do more on Logic Apps and Azure Analysis Services, but closing this one out.
