### ISSUE TITLE
grammar tidy up

### ISSUE THREAD

**Issue by flowsthru** [MicrosoftDocs/powerbi-docs#939]
Hi, some of the grammar on this page needs tidied up, especially in the  'Patterns to jump start your use of the Query Editor section.'
For example,
"One easy way to overcome the problem is do decompose the operation into steps. Start by duplicating the initial columns. Then build the steps a temporary columns."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70782244-c01c-bc5b-d266-d9404e02678e
* Version Independent ID: 1fda6a5f-784f-cfee-1352-81619f490814
* Content: [Tips and tricks for creating reports in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-tips-and-tricks-for-creating-reports#feedback)
* Content Source: [powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-tips-and-tricks-for-creating-reports.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @flowsthru . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thank you! We like to be tidy, especially with spelling and grammar. We refresh our articles, and when this article is up for refresh, we'll get out the grammar broom and dustpan. Thanks for posting!
