### ISSUE TITLE
Previous Quarter Sales Measure

### ISSUE THREAD

**Issue by JohnYounie** [MicrosoftDocs/powerbi-docs#94]
I enjoyed the article but I think steps 3 and 4 are the wrong way around, CALCULATE comes before SUM.  The student should create the Measure Name = (CALCULATE(SUM(etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [DAX basics in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-quickstart-learn-dax-basics)
* Content Source: [powerbi-docs/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
@JohnYounie - thanks for posting! We'll look into that sequencing, and update it as needed. Appreciate your post.
