### ISSUE TITLE
Missing content - other Formatting and Properties settings

### ISSUE THREAD

**Issue by Mike-Honey** [MicrosoftDocs/powerbi-docs#941]
Either this page should be expanded or new pages added to this section to cover all the other settings on the Modeling ribbon, in the Formatting and Properties sections.  This would include Data Type, Format, Default Summarization.  In the real world these are used much more heavily than Data Categorization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5bf15cc-1311-278f-5488-0d3c74f01e71
* Version Independent ID: 575f6f93-3945-2278-9027-b1881295078e
* Content: [Data categorization in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-data-categorization)
* Content Source: [powerbi-docs/desktop-data-categorization.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-data-categorization.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @Mike-Honey . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback (again) @Mike-Honey. We'll look at expanding that page when we it's scheduled for a documentation refresh.
