### ISSUE TITLE
"Securing a Tabular BI Semantic Model" document needs an update

### ISSUE THREAD

**Issue by kthejoker** [MicrosoftDocs/powerbi-docs#942]
Hi, the linked Word document "Securing a Tabular BI Semantic Model" was last updated in April 2016. Can the team review the content, make appropriate changes, and then set the new updated date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5505062-94f3-e15d-a52f-ce1ac7f8cb69
* Version Independent ID: 34076b73-0ded-2111-ed44-2a31e07deb53
* Content: [Row-level security (RLS) with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-rls)
* Content Source: [powerbi-docs/service-admin-rls.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-rls.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by mihart** [comment]
Thanks for your comment, @kthejoker . This issue has been assigned to the doc author for review.
