### ISSUE TITLE
Order of Operations is Incorrect

### ISSUE THREAD

**Issue by sk1tt1sh** [MicrosoftDocs/powerbi-docs#943]
The previous instruction "Connect Azure Data Lake Storage Gen2 for dataflow storage (Preview)" should follow this page as users with existing workspaces in PBI may attempt to use a non-dataflow enabled workspace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86b02e80-2a27-b97e-06b2-b71cfc1bc379
* Version Independent ID: 098653b6-3a0b-3455-80a2-b082b8b53bb8
* Content: [Configure workspace dataflow settings - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-configure-workspace-storage-settings#feedback)
* Content Source: [powerbi-docs/service-dataflows-configure-workspace-storage-settings.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-configure-workspace-storage-settings.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @sk1tt1sh . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for your feedback! We'll update this page when this feature comes out of preview, and will look at each step carefully.
