### ISSUE TITLE
Links broken

### ISSUE THREAD

**Issue by nicolaslledo** [MicrosoftDocs/powerbi-docs#944]
AuthenticationContext.AcquireTokenByAuthorizationCode link and Azure AD Authorization Code Grant Flow link  are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a1179b0-7f3d-77de-239b-a33c9d30ff61
* Version Independent ID: ab708f2a-3cb5-fcf3-9733-a2bc26b09e60
* Content: [Authenticate users and get an Azure AD access token for your application - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#feedback)
* Content Source: [powerbi-docs/developer/get-azuread-access-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/get-azuread-access-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by mgblythe** [comment]
Thanks for your comment, @nicolaslledo. This issue has been assigned to the doc author for review.

**Comment by Gabriel-Espinoza** [comment]
been 3 weeks since this issue was opened, we need a fix please

**Comment by markingmyname** [comment]
@Gabriel-Espinoza The links seem to work for me.

Can I ask what you are seeing when you are stating the links are broken?

Thank you.

**Comment by Gabriel-Espinoza** [comment]
the two links informed by @nicolaslledo

one is the very first link in this page: 
* Azure AD Authorization Code Grant Flow => https://msdn.microsoft.com/library/azure/dn645542.aspx
* AuthenticationContext.AcquireTokenByAuthorizationCode => https://msdn.microsoft.com/library/azure/dn479531.aspx

**Comment by markingmyname** [comment]
thank you, @Gabriel-Espinoza for bringing this to our attention.

The article has been updated and should go live with updated links by the end of the week.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
