### ISSUE TITLE
authorityUri is unreachable

### ISSUE THREAD

**Issue by ericoneal** [MicrosoftDocs/powerbi-docs#945]
was able to get working with https://login.windows.net/common/oauth2/authorize/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @ericoneal -- I've assigned your issue to the author. However, I think you'll be better off asking in the Power BI Community, https://community.powerbi.com/, or in Power BI Support, https://powerbi.microsoft.com/en-us/support/. 
Good luck!

**Comment by ericoneal** [comment]
I didnt have a question, just noting that the uri in the sample code:  https://login.microsoftonline.net/common  was unreachable

**Comment by maggiesMSFT** [comment]
Thanks for clarifying, @ericoneal! I've reopened it and assigned it to the author.

**Comment by marcelosarmento** [comment]
Try the following address instead: https://login.windows.net/common/

**Comment by ericoneal** [comment]
I get a 404 error when I visit that link, which is what prompted this thread.
I got it working here:  https://login.windows.net/common/oauth2/authorize/

**Comment by markingmyname** [comment]
@ericoneal,

Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
@ericoneal I am glad you got it working.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
