### ISSUE TITLE
Confusing Privacy Levels disabled / enabled

### ISSUE THREAD

**Issue by yoyogin** [MicrosoftDocs/powerbi-docs#946]
Why do you say that (# 1) 'Combine data according to your Privacy Level settings for each source' means that 'Privacy Levels is not enabled' while (# 2) 'Ignore the Privacy levels and potentially improve performance' means 'Enabling Privacy Levels' (you do it in a consistent manner across the file).

Intuitively, having privacy levels being considered (as in # 1) feels more like 'Privacy Levels is enabled' while not having these considered (as in # 2) feels more like 'Privacy Levels is not enabled' - is it possible that any clarification is missing? or that I'm misreading something ..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb7743c4-abb7-9c9d-6089-eca63ba9ac94
* Version Independent ID: c5bfefde-15ff-683c-5a79-e7210b8bf984
* Content: [Understand Power BI Desktop privacy levels - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-privacy-levels)
* Content Source: [powerbi-docs/desktop-privacy-levels.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-privacy-levels.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @yoyogin -- thanks for asking! I've referred your question to the author, who will reply with more info.
BTW, the numbers you've included, "#1" and "#2", end up being links going to different GitHub PRs. But I think I see now, you're referring to the 2 different sections of the article?
thanks!

**Comment by yoyogin** [comment]
I've updated my original comment (added spaces) - didn't mean to reference PRs but to reference terms showing in the first paragraph of my comment from the second paragraph.

**Comment by davidiseminger** [comment]
Thanks for posting @yoyogin - and sorry if that's not clear. We believe the document is correct. 

For more help and clarification on this, your best venue is the community (https://community.powerbi.com) or from support at https://support.powerbi.com. You can also provide feedback using the Give Product Feedback button at the bottom of the article page.
