### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by amit2505** [MicrosoftDocs/powerbi-docs#948]
Can you please include the actual release date and typical release schedule on this page. The last 2-3 releases have broken our working reports, so we want to track when to expect the PowerBI service release. Is it last Tuesday of every month or 4th Tuesday of every month?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e6b735a-e854-d48d-e535-0785de419b90
* Version Independent ID: be9f5816-3d30-c109-0b6a-848c6008fd4d
* Content: [What's new in the Power BI service - Power BI](https://docs.microsoft.com/en-us/power-bi/service-whats-new#feedback)
* Content Source: [powerbi-docs/service-whats-new.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-whats-new.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @NikhilGaekwad-MSFT
* Microsoft Alias: **nikhilga**

**Comment by maggiesMSFT** [comment]
Good question, @amit2505! Assigning to @NikhilGaekwad-MSFT so he can clarify.
Thanks!

**Comment by rosponda57** [comment]
Hi, on when the April update is planned? I'm waiting for some connector features from Desktop on PowerBI.com.

**Comment by NikhilGaekwad-MSFT** [comment]
Hi @amit2505 - the Power BI service ships weekly and we post all the major announcements on our blog: https://powerbi.microsoft.com/en-us/blog/. You will typically find the roll out schedule for each feature there. We usually have a 3 - 4 day period before everyone in the world receives the feature/update as part of safe deployment practices. If you encounter issues with your report, please file a support ticket and our team should be able to help you there.
