### ISSUE TITLE
Please close the following ideas as resolved since as per the documentation there are no egress charges when the Power BI tenant is deployed in the same Azure region as the data sources

### ISSUE THREAD

**Issue by mpsingh24** [MicrosoftDocs/powerbi-docs#949]
Please close the following ideas as resolved since there are no egress charges when the Power BI tenant is deployed in the same Azure region as the data sources:
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/11571870-egress-charges-from-scheduled-refresh-against-sour
https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/10855002-guarantee-scheduled-refresh-data-processing-is-ini

This is confusing the customers as these two unresolved ideas come up in the search results as open.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0577c02-6c3e-870c-ddee-d93cafef9206
* Version Independent ID: b9c65245-32e4-8bc9-8971-e76bff0ad837
* Content: [Power BI and Azure egress - Power BI](https://docs.microsoft.com/en-us/power-bi/service-azure-egress-power-bi)
* Content Source: [powerbi-docs/service-azure-egress-power-bi.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-azure-egress-power-bi.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi @mpsingh24 -- thanks for raising this issue! Unfortunately we can't close items on ideas.powerbi.com. Can you add this note to the ideas themselves?
thanks!
