### ISSUE TITLE
No "Show Secondary" Slicer

### ISSUE THREAD

**Issue by thecmanp11** [MicrosoftDocs/powerbi-docs#950]
Regarding Step 4 of Add titles to the axes; there is no such slicer as "Show Secondary." Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83e368c2-36c2-a5c0-f2af-993f6ee73665
* Version Independent ID: 452524d5-e375-9750-19ac-eb76903b36b3
* Content: [Combo Chart in Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/power-bi-visualization-combo-chart#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-combo-chart.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/power-bi-visualization-combo-chart.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by maggiesMSFT** [comment]
Hi, @thecmanp11 -- thanks for your question! I've assigned it to the author, who will get back to you with more info. Thanks!

**Comment by mihart** [comment]
Hi @thecmanp11 ,
The "Y Axis" section is very very long.  You'll see two different scroll bars.  Use both scrollbars to get to the section where you can set the Secondary axis options.  
Take care.
