### ISSUE TITLE
New versions

### ISSUE THREAD

**Issue by gerrhardvdw** [MicrosoftDocs/powerbi-docs#952]
Since the release of the March 2019 update, I have received 2 notifications of a newer version.  Where can I find out what changed in the newer updates?

**Comment by maggiesMSFT** [comment]
Hi, @gerrhardvdw -- are you referring to updates to Power BI Desktop? 
A great place to start is with the Power BI Desktop What's New article, https://docs.microsoft.com/en-us/power-bi/desktop-latest-update. 
Another good resource is the Power BI blog, https://powerbi.microsoft.com/en-us/blog/.
 I hope between the 2 they answer your question!

**Comment by gerrhardvdw** [comment]
Thanks Maggie

On the web site you mentioned, the PBI desktop version is 2.67.5404.581.
The latest downloaded version is 2.67.5404.981.  In between these versions
there was also version 2.67.5404.801.  None of the resources tell me what
changed in these versions.
