### ISSUE TITLE
CS1061

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#953]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/powerbi-docs.pt-pt/issues/3
The user may be reporting an error in the example code:

@JoseGoncalves3 commented:
Using this code, i am having a error, a CS1061, it says "'AuthenticationContext' does not contain a definition for 'AcquireToken' and no accessible 'AcquireToken' accepting a first argument of type 'AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)", can someone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bef3a0a2-7cc8-136e-eb8e-a80f4cade7d3
* Version Independent ID: 20093c04-76cd-9266-e2f1-96c329da93c1
* Content: [Get an authentication access token - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/walkthrough-push-data-get-token#feedback)
* Content Source: [powerbi-docs/developer/walkthrough-push-data-get-token.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/walkthrough-push-data-get-token.md)
* Service: **powerbi**
* Sub-service: **powerbi-developer**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by maggiesMSFT** [comment]
Hi, @JoseGoncalves3, thanks for your question! And thanks, @CeciAc, for passing it along. I've assigned it to the writer, who will take a look and get back to you.

**Comment by jhamilton8** [comment]
Hey, I managed to fix the same issue by updating Microsoft.IdentityModel.Clients.ActiveDirectory to version 2.22.302.111727

**Comment by JoseGoncalves3** [comment]
> Hey, I managed to fix the same issue by updating Microsoft.IdentityModel.Clients.ActiveDirectory to version 2.22.302.111727

I have the latest version of Microsoft.IdentifyModel.Clients.ActiveDirectory. How can i get your version?

**Comment by markingmyname** [comment]
@CeciAc,

Does @JoseGoncalves3, resolution work for you?

Please confirm.

Thank you.

**Comment by alexb5dh** [comment]
Would be nice if code was updated for latest ActiveDirectory package anyway

**Comment by markingmyname** [comment]
@CeciAc and @alexb5dh,

The article will be updated with a new known issues section to help others know where to go and download the update.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
