### ISSUE TITLE
Power BI samples work only if Silverlight is enabled

### ISSUE THREAD

**Issue by ansiansi** [MicrosoftDocs/powerbi-docs#954]
Hi, the Power BI sample set is not showing any report in Excel, unless you enable Silverlight. The PowerView add-on led me to a page that has a solution that works:  https://go.microsoft.com/fwlink/?LinkID=2011909.  But I still have concerns about the security on my computer. Can the data from the Obvience samples be provided without Silverlight reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e766e393-243c-51bf-59fc-6e08bcd3223f
* Version Independent ID: 5778a496-ab96-d567-0b55-e07b51ec9493
* Content: [Take a tour of the samples available with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/sample-datasets#feedback)
* Content Source: [powerbi-docs/sample-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/sample-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi @ansiansi -- good question, thanks for asking! I'll check and get back to you.

**Comment by maggiesMSFT** [comment]
Hi @ansiansi -- I updated the article with a new link. Thanks for pointing that out! BTW, here's the new link: https://support.office.com/article/flash-silverlight-and-shockwave-controls-blocked-in-microsoft-office-55738f12-a01d-420e-a533-7cef1ff6aeb1
