### ISSUE TITLE
Wrong Page Title

### ISSUE THREAD

**Issue by kuderaconsulting** [MicrosoftDocs/powerbi-docs#955]
This page does great in explaining how to SET a date table.
But there is nothing on this page that explains/illustrates HOW to use the date table. What good does it do to create and define a date table? What benefit does this add?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09750051-75cf-7829-b70b-8912f822ea8c
* Version Independent ID: b761024d-5166-47db-9c19-410073e5f46e
* Content: [Set and use date tables in Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-date-tables#feedback)
* Content Source: [powerbi-docs/desktop-date-tables.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-date-tables.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Hi, @kuderaconsulting -- good question! I've assigned it to the author, who will respond. 
Thanks!

**Comment by davidiseminger** [comment]
Thanks for your feedback @kuderaconsulting . There are many uses for date tables in various BI reports and analyses, the benefits of which are beyond the scope of this article. 

Your best venue for getting an answer or feedback on your question is from the community (https://community.powerbi.com) or from support at https://support.powerbi.com.
