### ISSUE TITLE
Relationship filtering is limited to a single direction

### ISSUE THREAD

**Issue by frvigano** [MicrosoftDocs/powerbi-docs#956]
in the document it is reported that "Relationship filtering is limited to a single direction". This is no longer true and bi-directional filtering works like in import mode"

**Comment by maggiesMSFT** [comment]
Hi, @frvigano -- Thanks for your comment! It looks like this statement is in 2 articles: 
https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery and 
https://docs.microsoft.com/en-us/power-bi/desktop-directquery-about
I've included the author, who will respond to your question.

**Comment by davidiseminger** [comment]
Thanks for the post - those articles have been updated, and will be live in the next 24 hours. Thanks!
