### ISSUE TITLE
ADLS Gen2 out of Preview

### ISSUE THREAD

**Issue by brmort** [MicrosoftDocs/powerbi-docs#957]
Page should be updated as ADLS is no longer in public preview. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adddb13a-811b-4fda-dcf8-98ce19492126
* Version Independent ID: cc52ac03-b68e-f8c1-aecc-af0b09ccafc4
* Content: [Learn how to connect Azure Data Lake Storage Gen 2 to Power BI for dataflow storage - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dataflows-connect-azure-data-lake-storage-gen2)
* Content Source: [powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dataflows-connect-azure-data-lake-storage-gen2.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mihart** [comment]
Thanks for your comment, @brmort . This issue has been assigned to the doc author for review.

**Comment by davidiseminger** [comment]
Thanks for the comment - I've updated the article to reflect. To further clarify, too, dataflows is out of preview, but this dataflow feature (which uses ADLS Gen2) is still in preview.
