### ISSUE TITLE
"Permission required" message when all the guest users try to view a report (April 2019 update)

### ISSUE THREAD

**Issue by lorenzolancio7** [MicrosoftDocs/powerbi-docs#959]
Hello everybody,
since last update of April 2019, this popup("Permission required") still appear to all guest users (like ...@gmail.com accounts) that open all my Reports :

![image](https://user-images.githubusercontent.com/49403153/55794026-83a18000-5ac4-11e9-9182-45e1428a08ae.png)

I can see in my panel that they have the "Read" Permission for the Dataset and for the Report, but they can't sill access.

![image](https://user-images.githubusercontent.com/49403153/55793925-5228b480-5ac4-11e9-967c-3fe30d107395.png)

Does anyone else had the same problem? How could i fix it?
It always worked before three days ago.
Thank you very much,
kind regards

Lorenzo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21f47742-00cf-eac0-7880-18eb5e988003
* Version Independent ID: 0010dce8-b1e0-b1b4-9840-ff2c3e32b53e
* Content: [Share Power BI dashboards and reports with coworkers and others - Power BI](https://docs.microsoft.com/en-us/power-bi/service-share-dashboards#feedback)
* Content Source: [powerbi-docs/service-share-dashboards.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-share-dashboards.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Thanks for your comment, @lorenzolancio7 . This looks like a support request or product question rather than documentation feedback. You might find a solution in the Power BI Community, at https://community.powerbi.com. If not, you can get support by going to https://support.powerbi.com.
