### ISSUE TITLE
"Publish to web does not currently support R visuals".

### ISSUE THREAD

**Issue by riaanbrits** [MicrosoftDocs/powerbi-docs#96]
The message "Publish to web does not currently support R visuals". appears when publishing a report that contains an R visual. This is kinda relevant... I just wasted time building a report containing R visuals which now cant be published to web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 000c7cf3-dbf4-92c6-3eb6-837329704cfa
* Version Independent ID: 81aa68ff-30b2-84e1-0f15-020890569527
* Content: [Create Power BI visuals using R - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-r-visuals)
* Content Source: [powerbi-docs/desktop-r-visuals.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-r-visuals.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by maggiesMSFT** [comment]
Thanks for your feedback, @riaanbrits! I've notified the author.

**Comment by markingmyname** [comment]
@riaanbrits  R visuals are not supported by the Publish toWeb feature. This article lists the Publish to Web limitations - https://docs.microsoft.com/en-us/power-bi/service-publish-to-web.

**Comment by danazsea** [comment]
which means R visual Report is only useful on local machine? Wow, that kinda limits sharing with coworkers.
