### ISSUE TITLE
Issue publishing from PowerBI Desktop(March edition) connected to Databricks-spark data source Connector

### ISSUE THREAD

**Issue by miguel-lopez** [MicrosoftDocs/powerbi-docs#962]
We are doing PowerBI reports with PowerBI Desktop(March Edition). Our data source is a Databricks table and we are connecting through spark connector .
When we try to publish we get an error that we need an enterprise gateway. After that, when we try to edit credentials in the powerBI Service, this option is disabled.

We published another report, like one month ago, but with powerBI Desktop(February Edition) and we were able to publish it without a gateway then we just edit credentials in powerBI Service and everything works fine. As reference: [https://docs.azuredatabricks.net/user-guide/bi/power-bi.html]

Any Idea on what is happening or if it is a bug in the new version? Or what can we do in order to avoid installing a gateway since our data is in azure databricks not on premise?

Thanks in advance.

**Comment by miguel-lopez** [comment]
Quick Comment. This is a bug. Will be fixed asap. As work around you can try  updating your power query to remove BatchSize option and try uploading your report again.

**Comment by mgblythe** [comment]
Thanks @miguel-lopez - April release is now out. Let us know if you have any issues after updating.

**Comment by mgblythe** [comment]
Closing this out. @miguel-lopez - feel free to reopen if any documentation updates are required for this.
