### ISSUE TITLE
URL filters aren't currently respected when choosing "Current Values" for your export.

### ISSUE THREAD

**Issue by djurecic** [MicrosoftDocs/powerbi-docs#963]
Any estimate on when this will be added? We use URL filtered reports frequently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0df1c4c0-80f9-f71a-175f-8362a29ad597
* Version Independent ID: c2a64e2a-ce65-dfb7-588a-381c145ab193
* Content: [Export reports from Power BI to PowerPoint - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-powerpoint#feedback)
* Content Source: [powerbi-docs/consumer/end-user-powerpoint.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-powerpoint.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your question, @djurecic. For upcoming features, I recommend checking the [What's new and planned doc](https://docs.microsoft.com/business-applications-release-notes/april19/business-intelligence/planned-feature). If you don't find an answer there, try searching in [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi) to see if anyone else has suggested this idea and it's already in progress. If not, enter a new item yourself.
