### ISSUE TITLE
Export to PDF not filtered with query string

### ISSUE THREAD

**Issue by mcalistor** [MicrosoftDocs/powerbi-docs#964]
When visiting a report that is filtered using a query string, the Export to PDF function reports all the underlying data, not just the filtered data.  This is regardless of whether the "Export with" option is set to "Current Values" or "Default Values".  The only workaround is to expose the same filter in the report and ask the end user to filter the report again before exporting to PDF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by davidiseminger** [comment]
Thanks for your comment, @mcalistor. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @mcalistor -- thanks for your question! I'm checking and will get back to you.

**Comment by maggiesMSFT** [comment]
Hi, @mcalistor -- OK, here's the answer: you're right, the Export to PDF currently doesn’t maintain the filter. A fix is planned. I'll add it to the Considerations section of the article. Thanks!

**Comment by mcalistor** [comment]
Good deal and thanks for the heads up!  Looking forward to reducing the number of clicks for our users.

**Comment by gminoza** [comment]
Hi All, looks like this is still an issue?  Please advise of confirm. Thanks

**Comment by maggiesMSFT** [comment]
Hi, @gminoza -- yes, it's still an issue. I added it to the https://docs.microsoft.com/en-us/power-bi/service-url-filters#considerations-and-troubleshooting section. 
thanks, @maggiesMSFT 
cc @cmfinlan

**Comment by gminoza** [comment]
Hi All, looks like this is still an issue as of 11/14/19.  Any ETA on fix?

**Comment by wmoskal** [comment]
Hello @maggiesMSFT,
As of 7/14/2020 I am still having this issue. 
I am also having this issue with the export to PPT functionality, but the docs don't seem to mention that. 

Any update on this, or an ETA for a fix?
Thanks for the support!

**Comment by PascalKTeam** [comment]
Seems like the issue "when opening a report that is filtered using a query string, the Export to PDF function doesn't respect the applied filters" is still open. I'm wondering if this will be fixed in the future.?

**Comment by maggiesMSFT** [comment]
Hi, @PascalKTeam -- yes, this is still an issue, as listed in the Considerations and limitations section:
“In the Power BI service, URL filters aren't currently respected when you choose Current Values for your export.”
Unfortunately we don't have a timeline for fixing it. I suggest checking https://ideas.powerbi.com/ideas/ to see if others have the same concern, and if so, vote it up. If you don't find it, create it!
