### ISSUE TITLE
Operation names that are "Not currently used" need clarification

### ISSUE THREAD

**Issue by TimCurwick** [MicrosoftDocs/powerbi-docs#966]
In the Notes column for "Activities audited by Power BI", please clarify "Not currently used" by replacing it with either "No longer used" or "Reserved for future use", as appropriate in each case. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Using auditing within your organization - Power BI](https://docs.microsoft.com/en-us/power-bi/service-admin-auditing#feedback)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* Sub-service: **powerbi-admin**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by davidiseminger** [comment]
Thanks for your comment, @TimCurwick. We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mgblythe** [comment]
This is all the information we currently have about the state of the audit events. At this point, we recommend using only those not marked "Not currently used". We'll update the table if we get more information.
