### ISSUE TITLE
This page belongs in "Visualizations" instead of in "Transform and shape data".

### ISSUE THREAD

**Issue by w0ut0** [MicrosoftDocs/powerbi-docs#970]
I feel this documentation (about the visual "Shape Map") belongs in category "Visualizations" (Power Bi Desktop/How to/Visualisations) instead of "Transform and shape data" (Power Bi Desktop/How to/Transform and shape data).

best,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Use Shape Maps in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by davidiseminger** [comment]
Thanks for your comment, @w0ut0 . We’ve forwarded your feedback to the writer, who should respond to this thread shortly. Thanks!

**Comment by mihart** [comment]
Hi @w0ut0 ,
Great suggestion.  I've moved it :-)
Thanks.
