### ISSUE TITLE
Is Custom Connector Supported or not?

### ISSUE THREAD

**Issue by italiana** [MicrosoftDocs/powerbi-docs#974]
The article begin suggesting that for OAuth protected resources, custom data connector can be used, however based on the known limitation, data gateway is not supported, which is the only way you can refresh a custom connector data source. So can custom data connector be used in a template app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b816e194-4069-e526-a96d-04238bf354cd
* Version Independent ID: 369aca21-55ba-d5f5-b699-bb4d85f1d540
* Content: [Tips for authoring template apps in Power BI (preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/service-template-apps-tips#feedback)
* Content Source: [powerbi-docs/service-template-apps-tips.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-template-apps-tips.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mihart** [comment]
Dear @italiana , Thank you for your suggestion. I've assigned this issue to the author.

**Comment by maggiesMSFT** [comment]
Hi, @italiana -- I'm investigating and will get back to you. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @italiana -- we've updated the article to be clearer. The change will be live this afternoon. Thanks for asking! And thanks, @teddybercovitz, for the clarification.

**Comment by italiana** [comment]
I'm not sure if this is indeed clearer. What does "Your custom connector must be added to PBI service for it to be accessed by Template app installer" mean? How do I add custom connector to PBI Service? My understanding is that you can only use custom connector through PBI Gateway which is not supported

**Comment by teddybercovitz** [comment]
Hi @italiana, fixed - you will see the changes tomorrow. hopefully, we will have a process to submit custom connectors. 
Thanks for your feedback!
