### ISSUE TITLE
Incorrect specification in "Reports in apps" section

### ISSUE THREAD

**Issue by v-dakoz** [MicrosoftDocs/powerbi-docs#977]
For our apps, provided specification of:
app.powerbi.com/groups/me/apps/app-id/reports/report-id/ReportSection?ctid=ctid&filter=Table/Field eq 'value'

stopped working recently, and link would always redirect to blank page. What we found to work was slightly different format:
app.powerbi.com/groups/me/apps/app-id/reports/report-id/ReportSection?filter=Table/Field%20eq%20%27value%27&ctid=ctid

where %20 = whitespace character and %27 = ' character, not sure if these are necessary, but we use it this way for our purpose. The takeaway here is the order of ctid and query should be different.

Additionally, since we substitute special characters with ASCII codes, we have noticed that some of them, such as / (slash), have to be written not like this: %2F (with usual % prefix before Hex ASCII code) but as follows: ~2F. Is there any reason behind it, so we could account for other cases that might break our links? If in the above example % is used instead of ~, link redirects to blank page also.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70b360f3-21a7-adc2-896a-b1dfd5d9e384
* Version Independent ID: 15e8c09f-46ad-68f9-75e6-c3d5c2c214e5
* Content: [Filter a report using query string parameters in the URL - Power BI](https://docs.microsoft.com/en-us/power-bi/service-url-filters#feedback)
* Content Source: [powerbi-docs/service-url-filters.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-url-filters.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by mgblythe** [comment]
Thanks for your comment, @v-dakoz . This issue has been assigned to the doc author for review.

In the meantime, consider posting in the [Power BI Community]( https://community.powerbi.com).

**Comment by maggiesMSFT** [comment]
Hi, @v-dakoz -- I'm checking and will get back to you. In the meantime, as @mgblythe says, consider posting in the Power BI Community, https://community.powerbi.com/.

**Comment by maggiesMSFT** [comment]
Hi, @v-dakoz -- good catches! I'm updating the article today to tell folks to put the ctid=*ctid* at the end of the URL, as you discovered yourself. 
For your 2nd point, the product team says: 
As for the part about encoding “/” (slash), either “~2F” or “%2F” should work. The %2F will get converted to ~2F in the URL, but that shouldn’t affect anything.
