### ISSUE TITLE
Support for ez package in Power BI service

### ISSUE THREAD

**Issue by brianrmacdonald** [MicrosoftDocs/powerbi-docs#978]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df17e088-5cff-4882-79fc-cc7deb09843d
* Version Independent ID: 641ddc87-0314-47c4-bee7-684ebe7f8e6e
* Content: [Learn which R packages are supported - Power BI](https://docs.microsoft.com/en-us/power-bi/service-r-packages-support#feedback)
* Content Source: [powerbi-docs/service-r-packages-support.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-r-packages-support.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by brianrmacdonald** [comment]
I would like to request support in the Power BI service for the [ez package](https://cran.r-project.org/web/packages/ez/index.html).   This package is able to perform Anova analyses that can be easily made to duplicate the results in SAS and SPSS, something that is pretty tricky to do with the other packages in R especially for unbalanced designs.

I tried to leave this request at powerbiai@microsoft.com but the e-mail was bounced.

Thank you.

**Comment by mgblythe** [comment]
Thanks @brianrmacdonald. You can submit product feedback or feature ideas by going to [Power BI Ideas](https://ideas.powerbi.com/forums/265200-power-bi).
