### ISSUE TITLE
Missing App

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/powerbi-docs#979]
This app is not visible in the Power BI Apps.  It was used in the past, no longer visible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff1b7488-9278-5b12-2025-9d602c113ecd
* Version Independent ID: dbe2cb00-7ab7-5c58-e902-234f0f3ae39c
* Content: [Connect to Google Analytics with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-google-analytics#feedback)
* Content Source: [powerbi-docs/service-connect-to-google-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-google-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @Karr. This looks like a support request or product question rather than documentation feedback. You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).
