### ISSUE TITLE
Software Developer / Architect

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/powerbi-docs#98]
Fantastic facility, but documentation sadly lacking; the basic structure and the short example are a good start, but the huge json above is of little use; suggest what we need is a series of small examples, each focusing on a different aspect, of which colour is only one (current help focuses almost exclusively on colour)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8511-6ff9-78c6-5a8c-3f5ac68224d0
* Version Independent ID: f4fd28c7-71fa-a776-7154-e76eb9bd3649
* Content: [Use Report Themes in Power BI Desktop (Preview) - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-themes)
* Content Source: [powerbi-docs/desktop-report-themes.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-themes.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by ChipDale66** [comment]
excellent site here to create files for you - https://powerbi.tips/tools/report-theme-generator-v3/

**Comment by EricChristoph** [comment]
Both this site and the theme generator mentioned seem to be missing components. For instance, how do you set the background for a table? The background card isn't mentioned, though you can see it in the Desktop.

**Comment by davidiseminger** [comment]
We've updated this Themes article with much more information, and structured theming (overall) to be more user friendly. Hopefully the instructions and changes are helpful, and address your post.
