### ISSUE TITLE
What is the available option to add external members to RLS roles.

### ISSUE THREAD

**Issue by jagzz** [MicrosoftDocs/powerbi-docs#980]
Adding external members to RLS doesn't seems to be an option. I have partners using their organization's domain account to access the Power BI reports. 

'This member has to be within your organization. You cannot add Groups created within Power BI.' @ https://docs.microsoft.com/en-us/power-bi/service-admin-rls

Do you have any suggestion/alternate approach that can work for members accessing from outside Microsoft organization implemented with RLS.

**Comment by maggiesMSFT** [comment]
Hi, @jagzz -- thanks for asking! I've assigned this to the author to respond.

**Comment by mgblythe** [comment]
@jagzz - we have some new information on this in the B2B whitepaper: https://docs.microsoft.com/en-us/power-bi/whitepaper-azure-b2b-power-bi#data-security-for-external-partners. I'll go in and correct the article you referenced. Thanks!

**Comment by mgblythe** [comment]
@jagzz - I removed the restriction in the article and linked to the whitepaper section I mentioned above. Thanks for the feedback.
