### ISSUE TITLE
what's the account of power BI server

### ISSUE THREAD

**Issue by loove** [MicrosoftDocs/powerbi-docs#981]
I haved install the  power BI server in my computer，but when I visit the page http://+:80/reports or http://+:80/reportserver ,the brower  points to me need to account and password。
I what to kwon what is the  account and password？

**Comment by loove** [comment]
thinks！

**Comment by markingmyname** [comment]
@loove 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.

**Comment by loove** [comment]
谢谢！
