### ISSUE TITLE
This information does not apply to Firefox

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#982]
@kah600 commented on [Thu Apr 18 2019](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/issues/15)

Meu navegador Firefox está atualizado com a última versão (66.0.3 - Firefox Release de April 10, 2019) e o PowerBI nem sequer abre. Ele processa a requisição e fica totalmente branco, sem exibir qualquer informação. Com o Chrome Versão 73.0.3683.103 (Versão oficial) 64 bits abre normalmente o mesmo dashboard. Sugiro a mudança do artigo para citar exatamente qual versão era compatível com o PowerBI, porque a mais atualizada, de fato, não é.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 753770c6-5424-85a6-1bd7-963e2c1c7e64
* Version Independent ID: 09a4403f-9fbd-535a-4b45-83e89f380ba0
* Content: [Navegadores com suporte para o Power BI - Power BI](https://docs.microsoft.com/pt-br/power-bi/consumer/end-user-browsers#feedback)
* Content Source: [powerbi-docs/consumer/end-user-browsers.md](https://github.com/MicrosoftDocs/powerbi-docs.pt-br/blob/live/powerbi-docs/consumer/end-user-browsers.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is making a suggestion on the original documentation:
Rough translation:

> My Firefox browser is up to date with the latest version (66.0.3 - Firefox Release of April 10, 2019) and PowerBI does not even open. It processes the request and goes completely blank, without displaying any information. With Chrome Version 73.0.3683.103 (Official release) 64-bit normally opens the same dashboard. I suggest changing the article to cite exactly which version was compatible with PowerBI, because the most up-to-date one, in fact, is not.

**Comment by markingmyname** [comment]
@CeciAc,

Sorry to hear about your issue. However, I have Firefox version 66.0.3 (64-bit), and I have no issues opening up Power BI.

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.

**Comment by markingmyname** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion, and we will reopen the issue.
