### ISSUE TITLE
Step 5. is not clear, there should be an example for them also

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/powerbi-docs#983]
Hi team, 
I'm moving manually this from here: https://github.com/MicrosoftDocs/powerbi-docs.tr-tr/issues/2

---
@metinilhan commented:
Which user name and password, example would be greate. I tried alot but no result

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdd3eb8d-0f4f-e8cd-7ed3-5ceccc433ddd
* Version Independent ID: 2164905a-fae3-c9e8-a62f-08d9b7ac95de
* Content: [Connect to Microsoft Dynamics NAV with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-microsoft-dynamics-nav#feedback)
* Content Source: [powerbi-docs/service-connect-to-microsoft-dynamics-nav.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-microsoft-dynamics-nav.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by markingmyname** [comment]
@CeciAc,  Thanks for your comment. We’ve forwarded your feedback to the writer, who should respond to this thread. Thanks!

**Comment by maggiesMSFT** [comment]
Hi, @CeciAc -- the feature has been completely updated. Are you still having this problem? If not, we will close this issue. 
Thanks!

**Comment by mgblythe** [comment]
Closing this one out based on the last update.
