### ISSUE TITLE
Why you use Google Chrome to Run Application? Whereas you have your own best browser i.e. Edge ?

### ISSUE THREAD

**Issue by csplVinodKumar** [MicrosoftDocs/powerbi-docs#985]
Hi Microsoft 
 Microsoft is always been Excellent above all Technology companies I know. 
 But I am not getting on your documentation page, why there is a screenshot of Visual Studio showing Debug session to begin with Google Chrome? 

  Is Microsoft so small that, Google is taking over it ? 
  Is Microsoft Browser ... Edge... Not capable of running Power BI reports with all features? 
  Does Microsoft intend to Market other Companies Products over to their own products?
  Do you have any doubt on your own capabilities in Browser Compatibilities?

 Hope you can understand what I realy mean with all these. 
 I would suggest to show your own Products in all omni channels, so that we feel confident with Microsoft always, as me and my team is always confident with you. 

 Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [Embedded analytics to embed Power BI content in your application for your customers - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers#feedback)
* Content Source: [powerbi-docs/developer/embed-sample-for-customers.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embed-sample-for-customers.md)
* Service: **powerbi**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by mgblythe** [comment]
Thanks for the feedback @csplVinodKumar. We typically show Chrome to emphasize that a given process can be completed successfully regardless of the browser you choose.
