### ISSUE TITLE
Analyze in Excel empty?

### ISSUE THREAD

**Issue by skgitti** [MicrosoftDocs/powerbi-docs#986]
I would need to copy some summarized data from Azure consuption insights to other program.
Report doesn't allow to select and copy data directly.
Tried to use Analyze in Excel option, but that brings up just empty white excel sheet - should it work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2d95443-afbf-fadd-6932-1edef039548f
* Version Independent ID: b5a9d263-4b72-e566-a53f-5c5e0bebafae
* Content: [Connect to Microsoft Azure Consumption Insights with Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-connect-to-azure-consumption-insights)
* Content Source: [powerbi-docs/service-connect-to-azure-consumption-insights.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-connect-to-azure-consumption-insights.md)
* Service: **powerbi**
* Sub-service: **powerbi-template-apps**
* GitHub Login: @SarinaJoan
* Microsoft Alias: **sarinas**

**Comment by mgblythe** [comment]
Thanks for your comment, @skgitti. This issue has been assigned to the doc author for review. In the meantime, you can also engage with the Power BI engineering team by being active in the [Power BI Community](https://community.powerbi.com).

**Comment by mgblythe** [comment]
Assigning to me, following up with PM. @skgitti - are you still running into issues?

**Comment by scyto** [comment]
Followed the doc, my dataset indicates it is refreshed but shows all data as blank in the app AND in the excel ODBC connection.

**Comment by scyto** [comment]
Ok i just tried to use powerbi desktop and got this, is the app broken?
![image](https://user-images.githubusercontent.com/11369180/57401611-e56c0d00-718a-11e9-8562-2c2ec4ba6764.png)

**Comment by skgitti** [comment]
yes, still having same issues - it will open file to Excel, but it is just blank/empty.

**Comment by scyto** [comment]
my issue was fixed this morning, i think the API I was down yesterday or something.

**Comment by skgitti** [comment]
just tried, same issue, Excel opens up blank/empty

**Comment by mgblythe** [comment]
@skgitti - You might find a solution in the [Power BI Community]( https://community.powerbi.com). If not, try our [support page](https://support.powerbi.com).

**Comment by mgblythe** [comment]
Closing this out. @skgitti - feel free to reopen if the issue persists.
