### ISSUE TITLE
Capacity Default Setting

### ISSUE THREAD

**Issue by apfenech** [MicrosoftDocs/powerbi-docs#988]
"Capacity Default: The dataset inherits the setting from the Premium capacity. The capacity default is controlled by the Power BI Premium capacity administrator."

Where am I able to change the default?  I can't find it in the admin center for our Premium capacity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13962e5-2d39-a6cd-274c-2317477acc22
* Version Independent ID: 099fe9f8-0c2b-b359-b761-251587a0ab76
* Content: [Query caching in Power BI Premium - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-query-caching#feedback)
* Content Source: [powerbi-docs/power-bi-query-caching.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-query-caching.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by NickyvVr** [comment]
On the blog it says: this setting will be added in the near future.
https://powerbi.microsoft.com/en-us/blog/announcing-query-caching-in-power-bi-premium/

**Comment by mgblythe** [comment]
Thanks for your comment, @apfenech. This issue has been assigned to the doc author for review.

**Comment by maggiesMSFT** [comment]
Hi, @apfenech and thanks for your comment, @NickyvVr -- I'm checking to see if you should be seeing it now. If not, I'll delete it.
thanks!

**Comment by maggiesMSFT** [comment]
Hi, @apfenech and @NickyvVr -- I've deleted it for now.
Thanks!

**Comment by Mholsen** [comment]
Has this feature still not been added to the admin center?
