### ISSUE TITLE
Misleading information about App Workspace visibility

### ISSUE THREAD

**Issue by mparowski** [MicrosoftDocs/powerbi-docs#99]
In the section above about creating app workspaces (https://docs.microsoft.com/en-us/power-bi/developer/embedding-content#appws), it says that setting a workspace as Public will allow users to see all content.  From my own testing, this refers only to the relationship the workspace has with Office 365 groups and related content.  Only *members* of the workspace are actually able to see Power BI content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fdac5f7-cd43-34c5-5905-dceeb9813952
* Version Independent ID: 6fd53f84-dbb2-2a9c-2745-ea1999779113
* Content: [How to embed your Power BI dashboards, reports and tiles - Power BI](https://docs.microsoft.com/en-us/power-bi/developer/embedding-content#appws)
* Content Source: [powerbi-docs/developer/embedding-content.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/developer/embedding-content.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thank you for your feedback.  We will look into this, so it's addressed.

**Comment by markingmyname** [comment]
@mparowski Please reference articles - https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-customers or https://docs.microsoft.com/en-us/power-bi/developer/embed-sample-for-your-organization for specific information on embedding applications depending on your audience.  Thank you.
