### ISSUE TITLE
Favoriting selected dashboards within an app

### ISSUE THREAD

**Issue by leotan87** [MicrosoftDocs/powerbi-docs#990]
Feedback on also guidance on how to favorite just one or a few selected dashboards within an app instead of favoriting the entire app in Power BI. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61e1e445-7f15-0f2a-f71a-1cc2bdd97fca
* Version Independent ID: a96c4c4e-0d4f-060e-1b67-5b60c2652259
* Content: [Favorites in Power BI service (dashboards, reports, apps) - Power BI](https://docs.microsoft.com/en-us/power-bi/consumer/end-user-favorite#feedback)
* Content Source: [powerbi-docs/consumer/end-user-favorite.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/consumer/end-user-favorite.md)
* Service: **powerbi**
* Sub-service: **powerbi-consumer**
* GitHub Login: @mihart
* Microsoft Alias: **mihart**

**Comment by mgblythe** [comment]
Thanks for your comment, @leotan87. This issue has been assigned to the doc author for review.

**Comment by mihart** [comment]
Hi @leotan87.  This guidance has been added and will go live later this week.  Thank you for bringing this to our attention.
