### ISSUE TITLE
Limitation Clarification: A corrupted dataset may require deletion and cascade delete all dependent reports

### ISSUE THREAD

**Issue by tx5westmt** [MicrosoftDocs/powerbi-docs#991]
Just a warning that although you may not plan to delete a dataset, if something happens to the root dataset you may be forced to delete it which will essentially force you to rebuild your entire workspace/linked reports/etc. We were very excited to create a shared dataset and link various reports to the shared power bi dataset service instance.  However, one day our scheduled refresh started failing and the error was tracked down to a data table field name change.  The dataset was successfully refreshing locally in power bi desktop but the instance in the power bi service was somehow corrupted and the only fix was to delete the cloud service dataset....which cascade deletes all your dependencies, etc. and means you need to touch every dependent report, re-connect, re-publish...This is more of a warning to beware getting carried away with your linked reports, it was very frustrating for us to have to rebuild everything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1cce347-2064-d2b3-d7dd-008ecdb36013
* Version Independent ID: 6abb84b5-1657-c8b1-62ef-641883c0e4b9
* Content: [Connect to datasets in the Power BI service from Power BI Desktop - Power BI](https://docs.microsoft.com/en-us/power-bi/desktop-report-lifecycle-datasets#feedback)
* Content Source: [powerbi-docs/desktop-report-lifecycle-datasets.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/desktop-report-lifecycle-datasets.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by mgblythe** [comment]
Thanks for the feedback @tx5westmt, and sorry to hear about the issues you faced with the dataset and the dependent reports. Given that this is product feedback rather than doc feedback, I'm going to close this out. It will still show up at the bottom of the doc page under closed feedback.
