### ISSUE TITLE
Checkmarks and Ellipsis Don't Follow Format Settings

### ISSUE THREAD

**Issue by joelvega** [MicrosoftDocs/powerbi-docs#993]
When using the new filter pane, the checkmarks for the filter boxes and the ellipsis don't follow the font and icon color settings in the format pane. We use a dark theme and no matter what both of these icons are always black.

Here is the example of the checkbox:

![image](https://user-images.githubusercontent.com/1467291/56815221-c5456100-680e-11e9-846b-c5c8ee392c83.png)
![image](https://user-images.githubusercontent.com/1467291/56815228-cbd3d880-680e-11e9-8452-d18799b4f0a2.png)

And here is an example of the ellipsis:
![image](https://user-images.githubusercontent.com/1467291/56815267-e60db680-680e-11e9-8542-840d796772e1.png)

**Comment by markingmyname** [comment]
Hi, @joelvega, can I ask what particular article you are referencing ht has this information?

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. If you have any feedback related to the documentation, please feel free to log in through this channel. We truly appreciate your contribution to our articles.
