### ISSUE TITLE
Is it "will not appear" or "will now appear" ? 

### ISSUE THREAD

**Issue by vsun2018** [MicrosoftDocs/powerbi-docs#996]
[content of this page]
Existing dashboard: select the name of the dashboard from the dropdown. Dashboards that have been shared with you will not appear in the dropdown.
[/content of this page]

Is it "will not appear" or "will now appear" ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eccfbc1d-74ab-9c0d-9fee-608508056da5
* Version Independent ID: 8c090f12-937c-b9cf-44db-c7014d9a9e23
* Content: [Pin a tile to a Power BI dashboard from a report - Power BI](https://docs.microsoft.com/en-us/power-bi/service-dashboard-pin-tile-from-report#feedback)
* Content Source: [powerbi-docs/service-dashboard-pin-tile-from-report.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-dashboard-pin-tile-from-report.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by maggiesMSFT** [comment]
Hi, @vsun2018 -- yes, it's right as written: "will not appear." I hope that helps!
