### ISSUE TITLE
Amazingly awesome page

### ISSUE THREAD

**Issue by rlhane** [MicrosoftDocs/powerbi-docs#997]
So many doc pages are a value void.  But this one is a black hole--that is, so dense with knowledge it sucks you in.  Here's ONE more thing that should get drawn into it... For some particular reporting needs you DON'T need Direct mode at all.  For reports where a scheduled nightly refresh is enough, Import mode protects their underlying databases from the impact of intense queries on multiple report elements at inopportune times during the work day generated by the innocent refresh clicks of unknowing managers.  Very important.  BI refreshes were crippling our production time tracking until I did this.  The managers did not need to sit and click refresh to see the latest greatest last minute updates to this data.  They needed to see trends, comparisons, etc. over time. Seeing yesterday's data today is enough for this application--and many others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dc3724b-5c69-73df-1ff2-8fa0a28c9c79
* Version Independent ID: 86932e18-54c4-dc9e-67f9-fe95f1e20f08
* Content: [Power BI performance best practices - Power BI](https://docs.microsoft.com/en-us/power-bi/power-bi-reports-performance#feedback)
* Content Source: [powerbi-docs/power-bi-reports-performance.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/power-bi-reports-performance.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @MarkMcGeeAtAquent
* Microsoft Alias: **kfile**

**Comment by maggiesMSFT** [comment]
Hi, @rlhane -- thanks for the feedback! I've assigned it to the author, who will get back to you.

**Comment by Bhavik-MSFT** [comment]
#please-close @maggiesMSFT
