### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by hongju** [MicrosoftDocs/powerbi-docs#998]
This document was not translated in Korean.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 5192cd8b-545c-5b98-6491-46d5097fcad8
* Version Independent ID: 5e70ae61-72a5-7203-c061-c1d747105ecc
* Content: [Tutorial: Build a Machine Learning model in Power BI (Preview) - Power BI](https://docs.microsoft.com/ko-kr/power-bi/service-tutorial-build-machine-learning-model#feedback)
* Content Source: [powerbi-docs/service-tutorial-build-machine-learning-model.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-tutorial-build-machine-learning-model.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comments @hongju  - sorry for the inconvenience. Your translation process sometimes takes a while to run through all our content, so it may still be coming. Thanks for your comment.
