### ISSUE TITLE
Making feature restrictions explicit

### ISSUE THREAD

**Issue by otravers** [MicrosoftDocs/powerbi-docs#999]
This page should state explicitly that Analyze in Excel is a Power BI service feature which makes it unavailable in Power BI Report Server and Power BI Embedded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fcb95bc-abb8-5147-ddc5-00714e30f79b
* Version Independent ID: 45626f2c-9e5c-6bdd-6fbb-b82c279962e0
* Content: [Analyze in Excel for Power BI - Power BI](https://docs.microsoft.com/en-us/power-bi/service-analyze-in-excel)
* Content Source: [powerbi-docs/service-analyze-in-excel.md](https://github.com/MicrosoftDocs/powerbi-docs/blob/live/powerbi-docs/service-analyze-in-excel.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by davidiseminger** [comment]
Thanks for your comment @otravers - we'll let the writer know so the article can be updated.

**Comment by davidiseminger** [comment]
Added author, labels.

**Comment by davidiseminger** [comment]
Thanks for pointing that out - we've updated the article. The change will show up within 24 hours.
